[translation]
"1014105-1" = "夜の散歩"
"1014105-2" = "シャーレ・正門"
"1014105-3" = "（1階に降りてきた）"
"1014105-4-ハルカ" = "せ、先生！？"
"1014105-5" = "[s] \"こんばんは、ハルカ。\""
"1014105-6-ハルカ" = "こ、こんばんは……！"
"1014105-7-ハルカ" = "すみません、夜分遅くに……。"
"1014105-8-ハルカ" = "何か用、ですか？"
"1014105-9-ハルカ" = "えっと……。"
"1014105-10-ハルカ" = "実は今日も警備のバイトがあって……帰り道に偶然、シャーレの前を通ったので……。"
"1014105-11" = "[s] \"偉いね。バイトはうまくいった？\""
"1014105-12-ハルカ" = "はい！前みたいなミスはありませんでした。"
"1014105-13-ハルカ" = "ちょっとでも怪しいやつはすぐに撃ってやりましたので！"
"1014105-14" = "[s] \"……うん？\""
"1014105-15-ハルカ" = "雇い主さんも「いつもより静かだった」と喜んでくれました！"
"1014105-16" = "[s] \"やはり暴力はすべてを解決するのか……。\""
"1014105-17-ハルカ" = "はい？"
"1014105-18" = "[s1] \"じゃあ、ちょっと歩かない？\"\n[s2] \"送っていくよ。\""
"1014105-19-ハルカ" = "お、送る……？"
"1014105-20-ハルカ" = "そ、そんな……！"
"1014105-21-ハルカ" = "夜中に先生を呼び出しておいて、これ以上お手間をおかけするわけには……！"
"1014105-22" = "[s3] \"手間なんかじゃないよ。\"\n[s4] \"むしろ職場から離れることができてラッキー。\""
"1014105-23-ハルカ" = "え……？ほ、本当ですか？"
"1014105-24-ハルカ" = "じゃ、じゃあ……。"
"1014105-25-ハルカ" = "よ、よろしくお願いします……。"
"1014105-26" = "（そうして、ハルカと二人で夜の散歩を始めた）"
"1014105-27-ハルカ" = "ううぅ……。"
"1014105-28-ハルカ" = "だ、誰もいないですね……。"
"1014105-29-ハルカ" = "暗いし、なんだか寂しい感じがします……。"
"1014105-30-ハルカ" = "すみません……連絡が遅れたせいで……。"
"1014105-31" = "[s] \"仕事が遅くに終わったんだから、仕方ないよ。\""
"1014105-32-ハルカ" = "えっと……。"
"1014105-33-ハルカ" = "その、実は……。"
"1014105-34-ハルカ" = "……仕事なら、2時間前に終わっていました。"
"1014105-35" = "[s] \"え？\""
"1014105-36" = "[ns] \"じゃあずっとシャーレの前に！？\""
"1014105-37-ハルカ" = "はい……。"
"1014105-38-ハルカ" = "その、すぐに連絡しなかったのは……。"
"1014105-39-ハルカ" = "何か急用でお忙しいかも、とか……。"
"1014105-40-ハルカ" = "外回りの最中かも、とか……。"
"1014105-41-ハルカ" = "休憩中かも、とか……。"
"1014105-42-ハルカ" = "そう思って、連絡するのを躊躇ってしまったからなんです……。"
"1014105-43-ハルカ" = "かといって、急にお邪魔すると、先生をびっくりさせちゃうかもしれませんし……。"
"1014105-44-ハルカ" = "迷惑かけてしまうんじゃないかと思って……。"
"1014105-45" = "[s] \"うん、そうかもしれないね。\""
"1014105-46-ハルカ" = "や、やっぱり……！"
"1014105-47" = "[s5] \"でも、ハルカがモモトークをくれたから。\"\n[s6] \"今2人でお散歩できてるでしょう？\""
"1014105-48-ハルカ" = "は、はい……。"
"1014105-49" = "[s] \"勇気を出してくれてありがとう、ハルカ。\""
"1014105-50-ハルカ" = "そ、そんな……。"
"1014105-51-ハルカ" = "こ、これからも言っていいんですか……？"
"1014105-52-ハルカ" = "そ、そうですね……口にしないと分からない、ですもんね。"
"1014105-53-ハルカ" = "そ、それなら……。"
"1014105-54-ハルカ" = "こんな私ですが……。"
"1014105-55-ハルカ" = "一つだけ……[ruby=・]ワ[/ruby][ruby=・]ガ[/ruby][ruby=・]マ[/ruby][ruby=・]マ[/ruby]を言っていいでしょうか……？"
"1014105-56" = "（ハルカがそっと袖をつかんできた）"
"1014105-57-ハルカ" = "その、目的地まで……。"
"1014105-58-ハルカ" = "……少し、ゆっくり歩きたい、です。"
"1014105-59" = "（断る理由などなかった）"
"1014105-60" = "（歩を緩めて、二人きりの時間を存分に楽しんだ）"
