[translation]
"1005202-1" = "セミナー書記ノアの細やかなる記録"
"1005202-2" = "シャーレ・オフィス"
"1005202-3-ノア" = "こんにちは、先生。"
"1005202-4-ノア" = "お伝えした通り、本日はシャーレの当番業務に参りました。"
"1005202-5-ノア" = "当番は初めてですので、至らないところも多いかと思いますが、よろしくお願いします。"
"1005202-6" = "[s] \"こちらこそ、よろしく。\""
"1005202-7-ノア" = "ふふ……なるほど。#nミレニアム生に聞いた通りの印象ですね。"
"1005202-8-ノア" = "彼女らが率先して先生の手伝いをする理由が、少し分かった気がします。"
"1005202-9" = "[s] \"何か噂でもされてる……？\""
"1005202-10-ノア" = "ああ、その点でしたらご心配なく。"
"1005202-11-ノア" = "特段、悪い噂ではありませんから。"
"1005202-12-ノア" = "それでは……どの業務から始めましょうか。"
"1005202-13" = "[s] \"今日はお手伝いしなくて大丈夫だよ。\""
"1005202-14-ノア" = "え……？#n個人業務以外は全部終わらせたから、手伝うものはない、と？"
"1005202-15-ノア" = "あら、困りましたね。#n私は先生を手伝うためにここに居るのですが……。"
"1005202-16-ノア" = "当番の間、何もしないというのはちょっと……。"
"1005202-17" = "[s] \"普段やっている事をするとか？\""
"1005202-18-ノア" = "私が普段やっていること、ですか？"
"1005202-19-ノア" = "普段は、書記業務を遂行しながら、セミナーで交わされる言葉を記録していますが……"
"1005202-20-ノア" = "ああ、なるほど……「記録」しましょうか。"
"1005202-21-ノア" = "……分かりました。#nそれでは書記として、ここで起こることを主観なく記録させていただきますね。"
"1005202-22" = "[s1] \"別に記録するほどの事は起きないと思うけど……。\"\n[s2] \"まあ、楽にしててね。\""
"1005202-23-ノア" = "はい、よろしくお願いいたしますね。"
"1005202-24-ノア" = "はい、よろしくお願いいたしますね。"
"1005202-25" = "[ns] \"あの……。\""
"1005202-26-ノア" = "どうされましたか？#n先生。"
"1005202-27" = "[s] \"さっきから何を書いてるの？\""
"1005202-28-ノア" = "ああ、この日誌のことですか？"
"1005202-29-ノア" = "先程お伝えした通り、先生の日々を書記としてしっかり記録させていただいています。"
"1005202-30" = "[s] \"変わったことは何もなかったと思うけど……。\""
"1005202-31-ノア" = "「変わったこと」の基準は、主観によっていくらでも変動しますから。"
"1005202-32-ノア" = "優秀な書記は、個人の主観に振り回されることなく、目撃した事柄すべてを中立的に記録するべきです。"
"1005202-33-ノア" = "例えば……"
"1005202-34-ノア" = "「15時10分11秒。[USERNAME]先生が業務中に伸びをし、3秒間あくびをした」"
"1005202-35-ノア" = "「15時12分49秒。[USERNAME]先生がマグカップが空になったことを確認し、コーヒーマシーンでコーヒーを補充した。使用した豆はステラバックスのシグネチャブレンド」"
"1005202-36-ノア" = "「15時46分08秒。[USERNAME]先生が窓を叩く野良猫に目を奪われ、約1分30秒間会話を試みた……」"
"1005202-37" = "[s] \"それ書いてどうするの！？\""
"1005202-38-ノア" = "先ほどもお伝えしたように、記録に込められた意味を判断するのは、#n書記の管轄ではありません。"
"1005202-39-ノア" = "私はただ、主観を含めず先生の行動を淡々と記録するだけです。"
"1005202-40-ノア" = "強いて私見を述べるのであれば、#n私にはごく普通の日常記録のように思えますが……。"
"1005202-41-ノア" = "先生のお仕事を知りたい誰かにとっては、意味のある記録になるかもしれません。"
"1005202-42-ノア" = "または、この記録を高額で販売することだって……。"
"1005202-43" = "[s] \"や、止めてくれ……。\""
"1005202-44-ノア" = "申し訳ありませんが、書記の業務は会議が終わるまで中断することができません。"
"1005202-45-ノア" = "外部の事情によって記録が中断されたり、内容の修正が発生してしまいますと、#n記録の中立性が阻害されてしまいますので。"
"1005202-46-ノア" = "ああ、そういう意味では……先ほどの発言も記録に残さなければいけませんね。"
"1005202-47-ノア" = "「16時27分55秒。シャーレの先生が記録を中断するよう要請した」"
"1005202-48-ノア" = "「16時28分10秒。シャーレの先生が記録を中断するよう要請したことを#n　記載しないよう要請した」"
"1005202-49-ノア" = "「16時29分43秒。シャーレの先生が記録を中断するよう要請したことを#n　記載しないよう要請したことを記載しないよう……」"
"1005202-50" = "[ns] 説得を諦める。"
"1005202-51-ノア" = "ふふ。#nご理解いただき、ありがとうございます。"
"1005202-52-ノア" = "では先生、私のことは気にせず、#n引き続きお仕事に集中してください。"
"1005202-53-ノア" = "先ほどもお伝えした通り……私はただ、現状を主観なく記録する書記ですから。"
"1005202-54" = "その後、ノアを気にせず仕事を進めようとしたものの……"
"1005202-55-ノア" = "ふふ……これもなかなか面白い経験ですね。"
"1005202-56" = "ノアの視線が気になって、仕事がほとんど手につかなかった……。"
