[translation]
"10026095-1-ハナコ" = "……ふう。なんとか片付きましたね。"
"10026095-2-ハナコ" = "ここまで多いとは……とても激しい戦いでした……。"
"10026095-3-コハル" = "うぅ……今度こそ最後だよね……？もう居ないよね……？"
"10026095-4-ヒナタ" = "箱は無事です！この通り……！"
"10026095-5-ヒナタ" = "さすがに、これ以上は出てこないかと……。"
"10026095-6-ウイ" = "あ、ヒナタさん、その箱を……"
"10026095-7-ヒナタ" = "あ、はい！どうぞ……！"
"10026095-8-ヒナタ" = "……では、開けます。皆さん、一緒に確認しましょう。"
"10026095-9-ヒナタ" = "……はい。"
"10026095-10-ハナコ" = "ふふっ。"
"10026095-11-コハル" = "…………。"
"10026095-12-コハル" = "……？"
"10026095-13-ハナコ" = "……あら？"
"10026095-14-ヒナタ" = "えっと……"
"10026095-15-ハナコ" = "……何も入ってないですね？"
"10026095-16" = "[s] \"……本当だ。\""
"10026095-17-ヒナタ" = "なぜ空の箱を埋めたのでしょうか……？#nそれも、こんなに遠回りをさせて……。"
"10026095-18-ハナコ" = "……これを埋めた当時は、この箱にも役目があったのでしょう。"
"10026095-19-ヒナタ" = "……役目、ですか？"
"10026095-20-ウイ" = "はい……ハナコさんの言う通りかと。"
"10026095-21-ウイ" = "よく見てください。箱の隅に紙片が残っていますよね。#nこれが、その証拠です。"
"10026095-22-ウイ" = "おそらく、何らかの意味を持った紙が、この中に……"
"10026095-23-ウイ" = "ですが、防腐処理などは施されていなかったようですね。#n歳月に伴い、徐々に風化が進み、形を失っていったのでしょう。"
"10026095-24-ハナコ" = "厳密に密閉されていたわけでもないですし、虫が食べてしまった可能性もありますね。"
"10026095-25-ヒナタ" = "なるほど……そこまで読み解けるものなのですね。"
"10026095-26-ヒナタ" = "でも、その紙がどんな物だったのかは、分からないのでしょうか……？"
"10026095-27-ウイ" = "……必ずしも、そうとは限りません。"
"10026095-28-ウイ" = "過去は私たちに、様々な方法でメッセージを残してくれています。"
"10026095-29-ウイ" = "もちろん、たしかな物が残っているのなら、それに越したことはありませんが……"
"10026095-30-ウイ" = "そうですね。今日の調査で掴んだ手がかりを、総合してみると……"
"10026095-31-ウイ" = "……はい。"
"10026095-32-ウイ" = "滝裏の洞窟は、大聖堂に見つからないよう、私物を隠しておいた保管庫。"
"10026095-33-ウイ" = "そして、まだ足を運んでいないもう一か所は、おそらく大聖堂の目を盗んで作った秘密基地でしょう。"
"10026095-34-ヒナタ" = "……？"
"10026095-35-ヒナタ" = "……はい？"
"10026095-36-ウイ" = "ようやく、点と点が繋がりました。"
"10026095-37-ウイ" = "決定的なのは、この箱。"
"10026095-38-ウイ" = "これは当時、ここで訓練をしていた聖徒会の方たちが埋めた……"
"10026095-39-ハナコ" = "……「タイムカプセル」ですね。"
"10026095-40" = "[s] \"……タイムカプセル？\""
"10026095-41-ウイ" = "その……"
"10026095-42-ウイ" = "……皆さん。"
"10026095-43-ウイ" = "よろしければ、その……"
"10026095-44-ウイ" = "ひとつ、お願いがあるのですが……聞いていただけませんか……？"
