[translation]
"10026030-1" = "第3話;調査ポイントA「石造りの迷路」"
"10026030-2" = "（まずは一番近い遺跡に向かった）"
"10026030-3-ヒナタ" = "こ、これが遺跡……ですか？"
"10026030-4-ヒナタ" = "たしかに、見えなくはありませんが……"
"10026030-5-ハナコ" = "風化こそしていますが……この石模様は、聖徒会の遺跡に間違いないでしょう。"
"10026030-6-コハル" = "そ、そうねっ。私もそう思ったわ。"
"10026030-7-コハル" = "……あら？"
"10026030-8-ハナコ" = "コハルちゃんは、ここがどこか知っていたのですか？"
"10026030-9-コハル" = "んっ……！？も、もちろん！見れば分かるじゃない！？#nあ、あんた達も知ってたんでしょ……？"
"10026030-10-コハル" = "ど、どうして私だけ知らないと思ったの！？"
"10026030-11-ハナコ" = "たしかに、みんな知ってるのにコハルちゃんだけ知らないのもおかしなお話ですね。#nふふ、すごいです、コハルちゃん。"
"10026030-12-ハナコ" = "こ、これくらい当然よ！"
"10026030-13-コハル" = "……あれ。まさか、からかってるんじゃないよね……？"
"10026030-14" = "[ns1] \"……ウイ？\"\n[ns2] \"何か気づいたことある……？\""
"10026030-15-ウイ" = "い、いえ……そうでは、ないのですが……"
"10026030-16-ウイ" = "ただ、少し考え事を……#nここがユスティナ聖徒会の遺跡だと仮定すると……"
"10026030-17-ウイ" = "うーん……地図に記された位置や規模感……それに迷路のような構造……"
"10026030-18-ウイ" = "……おそらく、試験場か訓練場のようなもの、かもしれません。#nもしくは、その両方でしょうか。"
"10026030-19-ウイ" = "とにかく、手分けして調査してみましょう。#n区切りの良いところで、またここに……"
"10026030-20-ウイ" = "では、私はあちらの方へ――"
"10026030-21-ヒナタ" = "う、ウイさん……？"
"10026030-22-ハナコ" = "ふふ。ウイさんは元気なお方ですね。#nお一人で奥まで積極的に♡"
"10026030-23-ハナコ" = "とりあえず、ウイさんが言っていたように……"
"10026030-24-ハナコ" = "私たちも続きましょうか？"
"10026030-25" = "（さっそく奥に進み、手がかりを探し始めた）"
"10026030-26" = "（苔むしていたり、木の柱が倒れていたり、複雑に道が入り組んでいるようだ）"
"10026030-27" = "（ところで……）"
"10026030-28" = "[ns3] \"……今は手分けして調査するはずじゃ？\"\n[ns4] \"そんなに強く握られると、袖が伸びちゃうんだけど……。\""
"10026030-29-コハル" = "な、何か問題でもあるの！？"
"10026030-30-コハル" = "さっきも言ったでしょ！？先生とハナコを監視するのが私の使命なの！"
"10026030-31-コハル" = "本当なら、ハナコも監視しないといけないんだけど……"
"10026030-32-コハル" = "身体がひとつしか無いんだから、仕方ないじゃん！#nそれに、こんな遺跡で一人にされたら……"
"10026030-33-コハル" = "……ん？"
"10026030-34-コハル" = "ハナコじゃなくて、先生と一緒に居る理由……？"
"10026030-35-コハル" = "な、なんでそんな質問するの！？エッチ！変態！！"
"10026030-36-コハル" = "……ひっ！？"
"10026030-37-ウイ" = "……あっ。"
"10026030-38-ウイ" = "……あれ……？"
"10026030-39" = "[s5] \"ウイだ。\"\n[s6] \"他にも誰かと会った？\""
"10026030-40-ウイ" = "はい。先ほど、ヒナタさんともすれ違いましたよ。"
"10026030-41-ウイ" = "興味深い造りですね。なぜ、わざわざ迷路にしたのか。その意図は……？"
"10026030-42-ウイ" = "そういえば先生、隣の方は……"
"10026030-43-コハル" = "……！？"
"10026030-44-コハル" = "あ、わっ、私？……えっと、その……"
"10026030-45" = "[s7] \"さっき、そこで偶然ね。\"\n[s8] \"コハルには、私が頼んでついてきてもらったんだ。\""
"10026030-46-ウイ" = "……なるほど、そうでしたか。"
"10026030-47-ウイ" = "では、私はこれで……"
"10026030-48-ウイ" = "……え？私も、一緒に……ですか？"
"10026030-49-ウイ" = "一緒に……うーん、一緒に…………。"
"10026030-50-ウイ" = "いえ……すみません。私は一人で行動します。#n会ったばかりの方と行動するのは、まだ、ちょっと……"
"10026030-51-ウイ" = "それに、今は仕事に集中しないといけませんし……"
"10026030-52-ウイ" = "すみません……コハルさんが苦手、とかでは、ありませんので……で、では。"
"10026030-53-コハル" = "ふぅ……びっくりした……。"
"10026030-54-コハル" = "……ん？悪い人じゃないのは、分かるけど……"
"10026030-55-コハル" = "べ、別に緊張なんかしてないわよ！？誰かに聞かれたらどうするつもりなの！#n私がすぐ緊張するような人に思われちゃ……"
"10026030-56-コハル" = "ひぃっ！？"
"10026030-57-ヒナタ" = "……ん？"
"10026030-58-ヒナタ" = "あっ、先生。後ろの方は……コハルさん、ですよね？"
"10026030-59-コハル" = "……。"
"10026030-60-コハル" = "……あ……こ、こんに……ちは。"
"10026030-61-ヒナタ" = "はい、こんにちは。#n先ほどはウイさんともお会いしましたし、面白い遺跡ですね！"
"10026030-62-コハル" = "は、はい……。"
"10026030-63" = "[ns] \"…………。\""
"10026030-64" = "（その後も石造りの迷路のような遺跡を歩いていると、何度もウイたちと会った）"
"10026030-65" = "[ns9] \"この辺りを調べたら、集合場所に戻ろうか。\"\n[ns10] \"お疲れ様。頑張ったね、コハル。\""
"10026030-66-コハル" = "ふぅ……って、そこまで疲れてるように見えた！？"
"10026030-67-コハル" = "みんなに話しかけられてたから……？"
"10026030-68-コハル" = "べ、別に私、人見知りじゃないからね！#n途中からは、ちゃんと挨拶できてたでしょ……？"
"10026030-69-コハル" = "さ、流石にもう何回も会ったんだし……"
"10026030-70-コハル" = "……！"
"10026030-71-コハル" = "よ、よしっ。今度は私から挨拶するんだからっ！"
"10026030-72-コハル" = "そこで見ててよね、先生！"
"10026030-73-コハル" = "こ、こ……"
"10026030-74-コハル" = "こんにち……わっ！？"
"10026030-75-？？？" = "…………。"
"10026030-76-コハル" = "…………。"
"10026030-77-？？？" = "…………。"
"10026030-78-コハル" = "きゃぁぁあああっ！！！！！！"
