[translation]
"1011706-1" = "ガール・イン・ペイン"
"1011706-2-ヒカリ" = "ヒカリさんじょー。"
"1011706-3" = "[s] \"調子良さそうだね、ヒカリ。\""
"1011706-4-ヒカリ" = "うん－絶好調ー。"
"1011706-5-ヒカリ" = "ヒカリ先生と遊びたいー。"
"1011706-6-ヒカリ" = "仕事忙しー？"
"1011706-7" = "[s] \"すっごく……\""
"1011706-8-ヒカリ" = "ぶー。"
"1011706-9" = "[s] \"……と見せかけて！今日は早めに終わったよ。\""
"1011706-10-ヒカリ" = "うぉー。"
"1011706-11-ヒカリ" = "先生えらい、なでなでー。"
"1011706-12-ヒカリ" = "おやつ買いにいこー？#nヒカリお金あるー。"
"1011706-13" = "[s] \"うん。ちょうど外の空気も吸いたかったし。\""
"1011706-14" = "（ヒカリと外に出た）"
"1011706-15-ヒカリ" = "やっぱこれー、団子アイスクリーム。"
"1011706-16-ヒカリ" = "うおー、パチパチキャンディのデイジーカッター味ー！"
"1011706-17" = "（ヒカリといろんなお菓子を楽しんでいると、いつの間にか日が暮れていた）"
"1011706-18-ヒカリ" = "うー食べすぎたー。"
"1011706-19-ヒカリ" = "口のなかあまあまー。"
"1011706-20" = "[s] \"確かに結構食べたよね……。\""
"1011706-21-ヒカリ" = "あっ！"
"1011706-22" = "[s] \"どうしたのヒカリ？\""
"1011706-23-ヒカリ" = "……。"
"1011706-24-ヒカリ" = "……歯がいたい……かも。"
"1011706-25-ヒカリ" = "もうだめだー……。"
"1011706-26" = "[s] \"だ、大丈夫？\""
"1011706-27-ヒカリ" = "ちょっと見てー。 "
"1011706-28" = "[wa:900]― [log=히카리]ここ、[wa:1200]ここー……[/log]"
"1011706-29" = "[ns] \"どこだろ……？奥歯？\""
"1011706-30" = "[wa:950]― [log=히카리]そ～[wa:920]……[wa:350]おくのほ～[/log]"
"1011706-31" = "[wa:3290]― [log=히카리]はがー[wa:1120]いたいー[/log]"
"1011706-32" = "― [log=히카리]せんせー、[wa:1400]みえるー？[/log]"
"1011706-33" = "[ns] \"大丈夫そうに見えるけど……。\""
"1011706-34" = "[wa:900]― [log=히카리]みぎのおくばがねー[wa:2590]いたいのー[/log]"
"1011706-35" = "[wa:570]― [log=히카리]うう、[wa:1080]そこ……[wa:1580]ズキズキー。[/log]"
"1011706-36" = "[ns1] \"たしかに……\"\n[ns2] \"あんまり触るとよくないよ……。\""
"1011706-37" = "[wa:670]― [log=히카리]えー[wa:1150]どうすればいいのー[wa:2250]ヒカリ[wa:850]死亡フラグー？[/log]"
"1011706-38" = "[wa:3950]― [log=히카리]たすけてー[wa:1670]せんせー……。[/log]"
"1011706-39" = "[ns] \"甘いもの食べ過ぎかも……\""
"1011706-40-ヒカリ" = "うー欲望に負けたー。"
"1011706-41-ヒカリ" = "悪魔の囁きによわいー……。"
"1011706-42" = "[s] \"今日寝る前にしっかり歯磨きして、明日歯医者に行こう！\""
"1011706-43-ヒカリ" = "歯医者、ウルトラデンジャラスー。"
"1011706-44-ヒカリ" = "ヒカリ歯医者やだー。"
"1011706-45" = "[s3] \"でも、ずっと痛いの嫌でしょ？\"\n[s4] \"歯医者に行けばすぐ治るし！\""
"1011706-46-ヒカリ" = "ううー。"
"1011706-47-ヒカリ" = "ううぅ……。"
"1011706-48-ヒカリ" = "ヒカリ長生きする。"
"1011706-49-ヒカリ" = "まだ遊びたいし……先生と……"
"1011706-50-ヒカリ" = "歯医者……行くー。"
"1011706-51" = "[s] \"よし、その調子！\""
"1011706-52" = "（翌日、一緒に歯医者に行って治療を受けた）"
"1011706-53" = "（ヒカリが治療を受けている間、ずっと手を握ってあげた）"
