[translation]
"3003-1" = "缶詰の残影（３）"
"3003-2-モエ" = "……これ、いつからこんなに膨らんでたんだ？"
"3003-3-モエ" = "それが、分かりません。しばらく放置していたら、こんなことに……。"
"3003-4-ミヤコ" = "それより、これ本当に食べて大丈夫？"
"3003-5-ミヤコ" = "まともな状態の缶詰が、ここまで膨らむかなぁ。"
"3003-6-ミユ" = "やっぱり普通の缶詰じゃなかったんだ……きっと、恐ろしい生き物が封印されたりするんだよ……"
"3003-7-ミユ" = "クラーケンの触手とか、巨大なウミヘビの尻尾とか……"
"3003-8-ミユ" = "もしかしたら、深海の未確認生命体とかなのかも……"
"3003-9-ミユ" = "工場で大量生産される戦闘食糧だぞ。得体の知れない物なわけあるか。"
"3003-10-サキ" = "とりあえず……成分を確認しよう。"
"3003-11-サキ" = "「……当社の「海鮮混ぜソース」缶は風味と触感を最大限に維持するため、フレッシュな海鮮を丸ごと入れております。」"
"3003-12-サキ" = "「中身はニシン、イワシ、タコ等で、海鮮固有の味を活かすべく別途の殺菌処理は加えておりません……」"
"3003-13-サキ" = "十中八九、中の海鮮が腐ったか発酵したんだろうな……。"
"3003-14-サキ" = "うええ、気持ち悪い……"
"3003-15-サキ" = "じゃあ、いまこの缶詰の中は、魚のガスでいっぱいになってるってこと？"
"3003-16-モエ" = "一歩間違えたら缶詰が爆発……なんてことも……"
"3003-17-ミユ" = "ひぃ……そんなの、考えたくもない……"
"3003-18-サキ" = "流石にこれはどこかに捨てるしか……"
"3003-19-ミヤコ" = "皆さん、ちょっと待ってください。"
"3003-20-ミヤコ" = "サキの話が本当なら、この缶詰は少し触れただけでガスを吹き散らす爆発物に相違ありません。"
"3003-21-ミヤコ" = "もし私たちがこの缶詰を無責任にゴミ箱にでも捨てたら……知らずに触れた清掃員や近所の住民たちに大きな被害が及ぶかもしれません。"
"3003-22-ミヤコ" = "じゃ、じゃあ、コレどうするんだ？食べるわけにもいかないし……"
"3003-23-サキ" = "キヴォトス内の不発[ruby=即席爆発装置]弾とIEDを解[/ruby]除[ruby=爆発物処理]するEOD任務[/ruby]もまた、SRTが遂行すべき作戦の1つ……"
"3003-24-サキ" = "このような極悪非道な生化学爆弾が、人の手に渡るところを見過ごすなど、できません。"
"3003-25-サキ" = "ミヤコ、まさか……"
"3003-26-モエ" = "ひょっとして、あれを……？"
"3003-27-ミヤコ" = "ええ……この海鮮缶詰は、私たちが責任を持って処理します！"
"3003-28-ミヤコ" = "これより、缶詰を安全処理する「腐敗ニシン」作戦を開始します。"
"3003-29-ミヤコ" = "爆発物処理の基本は、被害を最低限に抑え、爆発物を作動不能にすること……"
"3003-30-ミヤコ" = "魚から発生する悪臭成分の大半は水溶性です。従って、缶詰を水槽に入れた状態でゆっくりとガスを除去し、処理しましょう。"
"3003-31-サキ" = "やり方はなんだっていいんだが……"
"3003-32-ミヤコ" = "……それではサキ、お願いします。"
"3003-33-サキ" = "待ってくれ、どうして私が処理する流れになってるんだ？"
"3003-34-サキ" = "それは……RABBIT小隊でEOD教育を修了した者は、サキだけだからです。"
"3003-35-サキ" = "EOD教育なら確か、モエも受けたはずだ。"
"3003-36-ミヤコ" = "それはそうですが、モエに爆発物の処理を任せるのは……"
"3003-37-モエ" = "なになに、私に助けてほしい？爆弾なら任せなって、くひひ。"
"3003-38-ミヤコ" = "……仕方ないな。"
"3003-39-ミヤコ" = "……はい、仕方ありません。"
"3003-40-ミヤコ" = "ですがサキ、心配は要りません。私たちも万が一の時に備え、隣でサポートしますので。"
"3003-41-ミユ" = "私たちは運命を共にしている、戦友だから……！"
"3003-42-サキ" = "缶詰1つ開けるのに、そこまで大袈裟にならなくても……"
"3003-43-サキ" = "……と思ったけど、いざ処理するとなると、緊張するな。"
"3003-44-サキ" = "まずは、缶底にガス抜き用の小さな穴を空けます。"
"3003-45-ミユ" = "も、もし失敗してパーン！ってなったらどうしよ……？"
"3003-46-モエ" = "臭くてぬるぬるした液体を浴びて迎える破滅、というのもなかなか……はぁ、はぁ……"
"3003-47-サキ" = "えっと、それは……"
"3003-48-サキ" = "待ってください、サキ。膨らみきった缶底に穴を空けるときは、圧力による缶の破損を避けるため、最も厚い底の端を空けないといけません。"
"3003-49-サキ" = "うう、怖い……私たちはもう終わりです……"
"3003-50-モエ" = "こうなったら、いっそのこと一気にやっちゃおうよ！はあ、はあ……"
"3003-51-サキ" = "うう、うるさい！！そんなに話しかけられたら集中できな――"
"3003-52-サキ" = "あ。"
"3003-53" = "（爆発した缶詰の中身は飛散し、#n子ウサギ公園に莫大な生物学的災害をもたらした)"
"3003-54" = "（その後、やっとの思いで残骸を片付けたものの、RABBIT小隊員たちの身体についた悪臭は4日以上抜けずにいたという……）"
"3003-55" = "缶詰の残影"
