[translation]
"33160-1" = "第16話;いくつかの欠片たち"
"33160-2" = "アズサ……。"
"33160-3" = "その判断にどれだけ苦しんだのだろうね……君が本当に、命のように大事にしていたプレゼント。それを、殺人の道具として使うとは……。"
"33160-4" = "元々は、私のヘイローを破壊するために用意された爆弾……。"
"33160-5" = "あの時使わなかったそれを、このタイミングで……。"
"33160-6-サオリ" = "げほっ、げほっ！うっ、くっ……！"
"33160-7-サオリ" = "っ！"
"33160-8-サオリ" = "姫、姫っ！！！！"
"33160-9" = "……。"
"33160-10-セイア" = "……しかしサオリは無事だ。大怪我ではあるものの、ヘイローは壊れていない。"
"33160-11" = "だが、彼女をかばったアツコは……？"
"33160-12-サオリ" = "姫！！ダメだ、アツコっ！しっかりしろ！！"
"33160-13" = "アツコ、あの姫という子は……。"
"33160-14-セイア" = "サオリにとって、大事な人なのだろうね。"
"33160-15-マエストロ" = "……。"
"33160-16-マエストロ" = "ロイヤルブラッドの力が弱まった。これは、生命に異変が……？"
"33160-17-マエストロ" = "ふむ、実験に支障が出るだろうか……しかしまだ……。"
"33160-18-マエストロ" = "……。"
"33160-19-マエストロ" = "……嗚呼、そうか。"
"33160-20-マエストロ" = "彼女が既に備えを用意していた、と……成る程、貴重なロイヤルブラッドゆえか。"
"33160-21-マエストロ" = "まあ良い、少々時間はかかるだろうが……仮にも同志だ。これくらいのことはな。"
"33160-22-マエストロ" = "さて、やっていくとしよう。"
"33160-23-アツコ" = "っ……。"
"33160-24-サオリ" = "姫、無事か！？"
"33160-25-アツコ" = "（こくり）"
"33160-26-サオリ" = "ああ、良かった。姫……。"
"33160-27" = "……許せない。"
"33160-28-サオリ" = "アズサ……よくも姫にこんな怪我を……。"
"33160-29-サオリ" = "絶対に許さないぞ、アズサ！！"
"33160-30-セイア" = "アツコは死んでいない……。"
"33160-31-セイア" = "あの爆弾、たしかに私だったら間違いなくヘイローが「壊れていた」だろうね。"
"33160-32-セイア" = "直撃していないサオリでさえ、あのダメージだ。"
"33160-33-セイア" = "あのアツコという子のヘイローは……誰かによって守られているようだね。"
"33160-34-セイア" = "……。"
"33160-35-セイア" = "……しかしアリウススクワッドの計画には、大きな支障が生じつつある。"
"33160-36-セイア" = "トリニティ襲撃は未だできておらず、アツコの負傷によりユスティナ聖徒会の力も弱まっている。"
"33160-37-セイア" = "古聖堂での戦闘は落ち着きつつあることに加え……"
"33160-38-セイア" = "両学園は膠着状態、そして負傷者の搬送も始まりつつある。"
"33160-39-セイア" = "……アズサ。これで君の絶望が、少しでも和らぐなら良いのだけれど……。"
"33160-40-救急医学部の部員A" = "負傷者を発見、搬送します！！"
"33160-41-救急医学部の部員B" = "こちらに担架を！"
"33160-42-救急医学部の部員C" = "向こうです、まだ負傷者が何名か！"
"33160-43-救急医学部の部員D" = "部長！湖に落ちた飛行船から、万魔殿の議員たちを救出しました！マコト議長も含まれていたとのことです！"
"33160-44-セナ" = "さすがは議長、いつも通り運が良いですね。湖に落ちたことも幸運……"
"33160-45-セナ" = "各地の救助を続けてください。基本的には全員、強制的に集中治療室へ。"
"33160-46-救急医学部の部員" = "はいっ！"
"33160-47-セナ" = "風紀委員会の方は？"
"33160-48-救急医学部の部員" = "現在、行政官のアコさんが取りまとめているとのこと。委員長は情報によると、重傷で意識不明とのことです。"
"33160-49-セナ" = "……。"
"33160-50-セナ" = "風紀委員長……この条約を一番望んでいたであろう彼女が……。"
"33160-51-救急医学部の部員" = "……部長？"
"33160-52-セナ" = "……いえ、何でもありません。引き続き負傷者たちの救出を行ってください。"
"33160-53-セナ" = "……。"
"33160-54-セナ" = "……雨が降るかもしれませんね。急ぎましょう。"
"33160-55-シスターフッドの行政官A" = "正義実現委員会のツルギ委員長が重傷！ハスミ副委員長の方は重体とのこと！"
"33160-56-シスターフッドの行政官B" = "サクラコ様も重体です！救護騎士団の救護室は現在満床とのことで、古書館の寝室の方へ搬送中！"
"33160-57-マリー" = "あ、ああ……サクラコ様……。"
"33160-58-ハナコ" = "……ナギサさんは？"
"33160-59-シスターフッドの行政官A" = "彼女については、まだ捜索中とのこと！"
"33160-60-ハナコ" = "……。"
"33160-61-シスターフッドの行政官C" = "……っ！一部の過激派が、もうすぐゲヘナに宣戦布告をするとの情報が！！"
"33160-62-マリー" = "はいっ！？"
"33160-63-ハナコ" = "ダメです、今ここでそんなことをしては……！"
"33160-64-シスターフッドの行政官A" = "正義実現委員会が、大聖堂に進入を試みているとの情報あり！これを阻もうとするシスターたちと、中央ホールで衝突が発生しました！"
"33160-65" = "なっ……！？"
"33160-66-ハナコ" = "混乱があちこちで……。"
"33160-67-ハナコ" = "早く戦闘を中止させて、救助の方に専念しないと……！"
"33160-68-ハナコ" = "（変数が多すぎる上にこの状況、私はいったいどうすれば……）"
"33160-69-ハナコ" = "（セイアちゃん……）"
"33160-70-ハナコ" = "（先生……）"
"33160-71" = "ゲヘナ・保健室"
"33160-72-アコ" = "委員長がいなくなった！？"
"33160-73-風紀委員会の医務官" = "は、はい……先ほどまでこちらに横になっていたのですが……。"
"33160-74-アコ" = "今すぐに探してください！あの怪我でいったいどちらへ……！"
"33160-75-風紀委員会の医務官" = "は、はいっ！"
"33160-76-アコ" = "委員長……。"
"33160-77-セイア" = "……風紀委員長は、姿を消したようだね。"
"33160-78-セイア" = "これまでずっと頑張り続けてきた彼女の心は、どうなってしまったのか……"
"33160-79" = "ティーパーティー・教室"
"33160-80-ティーパーティー傘下の幹部" = "宣戦布告の文章はできましたか！？"
"33160-81-ティーパーティーの行政官" = "はい、大丈夫です！"
"33160-82-ティーパーティー傘下の幹部" = "良し、ではすぐにでも……！"
"33160-83-ハナコ" = "待ってください！"
"33160-84-ティーパーティーの行政官" = "なっ、[ruby=うらわ]浦和[/ruby]ハナコさん……？どうしてここに！？"
"33160-85-ハナコ" = "宣戦布告は校則上、ホスト無しでは宣言できないはずです！"
"33160-86-ティーパーティー傘下の幹部" = "……。"
"33160-87-ハナコ" = "あの映像をご覧になったでしょう！？相手はゲヘナではありません！"
"33160-88-ハナコ" = "あれはきっと、アリウスが操っている「別の何か」です！"
"33160-89-ハナコ" = "トリニティ自治区内の各地にある遺跡、そしてその地下に繋がっているカタコンベを通って――"
"33160-90-ティーパーティー傘下の幹部" = "……捕えてください。"
"33160-91-ハナコ" = "っ！？"
"33160-92-ティーパーティー傘下の幹部" = "浦和ハナコさん……こんなことになってしまい残念です。"
"33160-93-ハナコ" = "何を……！？"
"33160-94-ティーパーティー傘下の幹部" = "映像なら確かに確認しました。あの正体不明の集団、「ユスティナ聖徒会」。"
"33160-95-ティーパーティー傘下の幹部" = "あれがシスターフッドと関係あることくらいは把握しています。だからこそこうして動こうとしているのです。"
"33160-96-ティーパーティー傘下の幹部" = "探偵ごっこはお終いです、ハナコさん。"
"33160-97-ハナコ" = "……！"
"33160-98-ティーパーティー傘下の幹部" = "巡航ミサイルの発射位置についても確認しました。シスターフッドの管理下にある、聖堂の遺跡でしたね。"
"33160-99-ティーパーティー傘下の幹部" = "アリウスがその下にあるカタコンベを通じて、勝手に私たちの自治区に侵入した……確かにそういう可能性もあるでしょう。"
"33160-100" = "ですがそもそも、アリウスとシスターフッドが最初から手を組んでいたという線は？"
"33160-101-ハナコ" = "……っ！そんなことは……！"
"33160-102-ティーパーティー傘下の幹部" = "あそこまで徹底的な秘密主義集団です。それくらいはできても不思議ではありません。"
"33160-103-ティーパーティー傘下の幹部" = "私たちパテル分派はこの危険な事態に対し、迅速に対応することを決めました。"
"33160-104-ハナコ" = "それはつまり、まさか……。"
"33160-105-ティーパーティー傘下の幹部" = "はい。私たちの決定に反対、或いは判断を留保したフィリウス分派ならびにサンクトゥス分派については、既に身柄を拘束しています。"
"33160-106-ハナコ" = "クーデターですか……！"
"33160-107" = "いえ、違います。何せそもそも、まだれっきとしたティーパーティーが1名いらっしゃいますから。"
"33160-108-ハナコ" = "……！？"
"33160-109-ティーパーティー傘下の幹部" = "パテル分派の首長にして、ティーパーティーのメンバーであるミカ様。"
"33160-110-ティーパーティー傘下の幹部" = "あのお方を解放し、本来のお望み通りゲヘナとの全面戦争を始めるのです。"
"33160-111-ハナコ" = "……！！！"
"33160-112-ミカ" = "……。"
"33160-113-刑務官" = "ミカさん、こちらへ。"
"33160-114-ミカ" = "……ふうん？"
"33160-115-セイア" = "アズサ……君はこの後どうするつもりだい？"
"33160-116-セイア" = "君の覚悟によって、多くの人々が救われた。しかし戒律は弱まったが、「ユスティナ聖徒会」は依然として存在する。"
"33160-117-セイア" = "ゲヘナの風紀委員長ヒナはどこかへと消えてしまい、ハナコは逮捕されようとしている。"
"33160-118-セイア" = "そして、ミカが釈放されつつある。"
"33160-119-セイア" = "やはりこれが結末だ。"
"33160-120-セイア" = "結局全ては無意味で、あまりにも虚しい夢のような物語……。"
"33160-121" = "……まだだ。"
"33160-122-セイア" = "アズサ……？"
"33160-123-アズサ" = "まだ挫折してる場合じゃない、アズサ。"
"33160-124-アズサ" = "動いて、考えて。挫折して悲しんでいる暇があったら、今からでも方法を探して、どうにか……"
"33160-125-アズサ" = "次の計画……次は……"
"33160-126-アズサ" = "止まっていられない、動かないと……何か方法を……。"
"33160-127-アズサ" = "「ユスティナ聖徒会」が消えてない……サオリも、アツコも無事……それは……いや、でも……"
"33160-128-アズサ" = "行かないと……何をしてでも、サオリを……。"
"33160-129-アズサ" = "でないと……"
"33160-130-セイア" = "アズサ……君はまだ戦うつもりかい？"
"33160-131-セイア" = "全てが虚しいと知っていて、それでも君は……"
"33160-132-セイア" = "全てを失って、どうしてそんなに……"
"33160-133-正義実現委員会部員A" = "向こうの方で暴力沙汰が！誰か止めてきて！"
"33160-134-正義実現委員会部員B" = "第5校舎にて事件が発生！どうしますか！？"
"33160-135-コハル" = "う、うぅ……。"
"33160-136-コハル" = "わ、私は……。"
"33160-137-正義実現委員会部員A" = "あれ？あなた……今は補習授業部じゃなかったっけ、どうしてここにいるの？まだ復帰しちゃいけないんじゃなかった？"
"33160-138-コハル" = "そ、それは、えっと……。"
"33160-139-正義実現委員会部員A" = "まあ今はそんな場合じゃないか。やることないなら、監獄の方にでも行ってもらえる？何か変な集まりが出てきそうとか言ってたし……。"
"33160-140-コハル" = "わ、私は……っ！"
"33160-141-ヒヨリ" = "さ、サオリさん……。"
"33160-142-ミサキ" = "リーダー……。"
"33160-143-サオリ" = "今すぐ、トリニティへの攻撃を……！"
"33160-144" = "その前に、やらなきゃいけないことがある。"
"33160-145-ヒヨリ" = "ひ、姫ちゃんが怪我をして、「ユスティナ聖徒会」の顕現に問題が生じてますし……。"
"33160-146-ミサキ" = "……あの古聖堂に戻って、戒律を更新しないと。"
"33160-147-ミサキ" = "……。"
"33160-148-ミサキ" = "……分かった、古聖堂へ向かうとしよう。"
"33160-149-ミサキ" = "すぐに出発だ。"
"33160-150-ミサキ" = "……。"
"33160-151" = "行くぞ！"
"33160-152-ティーパーティー傘下の主戦派A" = "ミカ様、こちらへ。"
"33160-153-ティーパーティー傘下の主戦派B" = "ミカ様！！"
"33160-154-ティーパーティー傘下の主戦派C" = "お待たせしました、もう自由です！"
"33160-155-ミカ" = "ふーん……なるほどね？うん、大体状況は分かったよ。つまり……"
"33160-156-ミカ" = "みんな、私のファンってところかな？やー、仕方ないなあ。サインでもしてあげよっか？"
"33160-157-ティーパーティー傘下の主戦派B" = "い、いえそうではなく。ご覧になったかと思いますが、現在トリニティは――"
"33160-158-ミカ" = "うん、だいたい分かってる。で、ここのみんなは何？まさかとは思うけど、ゲヘナに宣戦布告しようとか考えてたり？"
"33160-159-ティーパーティー傘下の主戦派B" = "はい、その通りです！今こそゲヘナのやつらを消し去るチャンスかと！"
"33160-160-ティーパーティー傘下の主戦派B" = "あなた様が望んでいた通り、ゲヘナとの全面抗争を……！"
"33160-161-ティーパーティー傘下の主戦派C" = "さあ、今すぐトリニティ全域に戦闘命令を！"
"33160-162" = "……あはっ。"
"33160-163-ミカ" = "みんな記憶力良いね。うん、私はゲヘナが大っ嫌いだよ。"
"33160-164-ミカ" = "……それで？だから何？どうしてそんな、命令を欲しがって来たわけ？"
"33160-165-ティーパーティー傘下の主戦派B" = "……はい？"
"33160-166-ミカ" = "他の派閥を抑えたんでしょ？実際のところ、宣戦布告なんて手続きもう要らないじゃん。今すぐにゲヘナに殴りかかれば良いのに、自分たちの代わりに怒って、命令してくれって……何それ、面白いことするね？"
"33160-167-ティーパーティー傘下の主戦派A" = "み、ミカ様！？何を……！"
"33160-168-ミカ" = "あははっ、気に障ったらごめん。"
"33160-169-ミカ" = "うん、私はゲヘナが嫌いだよ。機会があれば、どうにかしてやりたいと思うくらいにはね。"
"33160-170-ミカ" = "でもさ、今の私はあんまりそういう気分じゃないんだよね。だから悪いんだけど、帰ってもらえるかな？"
"33160-171-ティーパーティー傘下の主戦派B" = "き、気分……？"
"33160-172-ティーパーティー傘下の主戦派A" = "今がどれだけ重大なタイミングなのか、分かっていらっしゃるのですか。それを、たかが気分の問題で……"
"33160-173-ミカ" = "……「たかが」？何言ってるの、それが一番大事なことでしょ？"
"33160-174-ミカ" = "私は私の気分とか気持ちの問題で、ゲヘナが嫌いなの。そのことの何が悪いのさ。別に、その裏に隠れた理由とか目的なんて無いんだよ？"
"33160-175-ミカ" = "こんな状況で宣戦布告なんて、別に要らないって分かってるよね？なのに自分たちの代わりに憎んでくれだなんて、変なこと言って……。"
"33160-176-ミカ" = "もう帰ってくれないかな？今はそういう気分じゃないし、そろそろ面倒になってきちゃうから。"
"33160-177-ティーパーティー傘下の主戦派A" = "……何だと？"
"33160-178-ミカ" = "お耳掃除でもしてあげようか？命令されなきゃ憎むこともできないの、って言ってるの。"
"33160-179-ティーパーティー傘下の主戦派A" = "この、言わせておけば……っ！"
"33160-180-ミカ" = "……っ。"
"33160-181-ティーパーティー傘下の主戦派B" = "世間知らずのお嬢様が！わざわざ牢屋から出してあげようっていうのに、調子に乗って……！"
"33160-182-ミカ" = "あー、もう……。"
"33160-183-ミカ" = "……痛いなあ。"
"33160-184-ティーパーティー傘下の主戦派A" = "自分の立場を理解しろ！もうティーパーティーから解任直前の身で！"
"33160-185-ティーパーティー傘下の主戦派B" = "わざわざ来てあげたというのに、それを……！"
"33160-186-ミカ" = "……。"
"33160-187-コハル" = "な、何してんのっ！？"
"33160-188-コハル" = "な、なんだお前は！"
"33160-189-コハル" = "い、いじめはダメっ！どうして、こんなに大勢で寄ってたかって……！"
"33160-190-コハル" = "こ、こんなの、私が許さないんだからっ！！"
"33160-191-ミカ" = "……！"
"33160-192" = "[ns] 目を開ける。"
"33160-193" = "[ns] 身体を起こす。"
"33160-194-セリナ" = "せ、先生！？目が覚めたんですね……！！"
"33160-195-ハナエ" = "まだ動いちゃダメです！先生、どこに行くつもりなんですか……！？"
"33160-196-セイア" = "……先生、君はあくまで立ち向かうつもりかい？"
"33160-197-セイア" = "生徒たちが他の何でもなく……。"
"33160-198-セイア" = "……ただ、生徒たちであるために？"
"33160-199" = "[s] \"そうあるべきだって、私は信じてるから。\""
"33160-200-セイア" = "……だが、先生。"
"33160-201-セイア" = "君の前に立ちふさがるのは憎悪と不信。長きにわたって久遠に近い集積を経た、それらの具現だ。"
"33160-202" = "[ns] \"じゃあまずは、それと相対してくるよ。\""
"33160-203" = "次回;憎しみの正体"
