[translation]
"33180-1" = "第18話;迷わずに"
"33180-2-ハスミ" = "……。"
"33180-3" = "[s] ハスミの方に目をやる。"
"33180-4-ハスミ" = "……先生。"
"33180-5-ハスミ" = "ここは……いったい何が……。"
"33180-6" = "[s] \"ハスミ、良かった……。\""
"33180-7-ハスミ" = "……はい。危ういところでしたが……。"
"33180-8-ハスミ" = "ツルギは、他のみんなは……。"
"33180-9-ツルギ" = "……。"
"33180-10" = "[s] ツルギの方に目をやる。"
"33180-11-ツルギ" = "……？"
"33180-12-ツルギ" = "ぎゃああぁぁぁっ！？"
"33180-13-ツルギ" = "せ、せせせ先生！？ど、どうしてこちらに……！？"
"33180-14-ハナエ" = "あ、ツルギさん！って、もう動けるんですか！？さすがは正義実現委員会の委員長さんですね！"
"33180-15-セナ" = "……ご無事で何よりです、先生。"
"33180-16" = "[s] \"セナのおかげだよ。\""
"33180-17-セナ" = "いえ。大人の治療は初めてでしたが、どうにかなって何よりです。"
"33180-18-チナツ" = "先生……。"
"33180-19-セナ" = "チナツ、まだ動いてはダメです。横になってなさい、先輩命令です。"
"33180-20-チナツ" = "私、今は風紀委員会所属ですが……。"
"33180-21-セナ" = "今から救急医学部に戻ってきても良いのですよ？質の良い死た……いえ、負傷者たちに好きなだけ触れますし。"
"33180-22-チナツ" = "いえ、私は別に……丁重にお断りしておきますね。"
"33180-23-アコ" = "先生……。"
"33180-24-イオリ" = "アコちゃんまだ動いちゃ、ぐっ……！"
"33180-25" = "[s] \"アコもイオリも、怪我はともかく無事で良かった……。\""
"33180-26-アコ" = "委員長がいなくなってしまい……。"
"33180-27-アコ" = "部室にもおらず、連絡もつかなくて……。"
"33180-28-アコ" = "先生、委員長を……。"
"33180-29" = "[s] \"うん、任せて。\""
"33180-30-アコ" = "……はい。よろしくお願いします。"
"33180-31-ヒフミ" = "先生……。"
"33180-32" = "[s] \"ヒフミ……。\""
"33180-33-ヒフミ" = "先生、アズサちゃんが……。"
"33180-34-ハナコ" = "……。"
"33180-35-コハル" = "……。"
"33180-36-ヒフミ" = "アズサちゃんがひとりで戦っています……まだ、ひとりでずっと……。"
"33180-37" = "[s] \"……うん。\""
"33180-38" = "居場所が違うんだ、って……それで私、何も分からなく……。"
"33180-39-ヒフミ" = "こんな大変なことになってしまって……もう、私みたいな普通の学生にできることなんて……。"
"33180-40-ヒフミ" = "どうすれば、アズサちゃんを……だって、私は……。"
"33180-41-コハル" = "……。"
"33180-42-コハル" = "それでも、放っておくわけにはいかないでしょ！？"
"33180-43-ヒフミ" = "コハルちゃん……。"
"33180-44-コハル" = "立ち位置なんて関係無い！わ、私は知ってる……！ひとりでいることとか、置いてかれることとか、それがすごく悲しいって！だから、アズサをひとりにさせられない……！"
"33180-45-ハナコ" = "……はい。そういうのは、寂しいですからね。"
"33180-46" = "[s] \"ここまでずっと、ヒフミが引っ張ってきてくれた。\""
"33180-47-ヒフミ" = "……？"
"33180-48" = "[s1] \"みんなの努力は勿論だけど、ヒフミがここまで頑張ってくれたから。\"\n[s2] \"たとえ平凡でも、自分たちの目指すものを諦めなかったから。\""
"33180-49-コハル" = "私は頑張った。でもその陰で、あんたがたくさんの面倒なこととか、部長として色んな事をしてくれたのも……そのおかげで頑張れたのも、ちゃんと知ってる。"
"33180-50-コハル" = "私は頑張った。でもその陰で、あんたがたくさんの面倒なこととか、部長として色んな事をしてくれたのも……そのおかげで頑張れたのも、ちゃんと知ってる。"
"33180-51-ハナコ" = "そうですよ。ヒフミちゃんが諦めずにいてくれたから、私も今こうしてここにいられるんです。"
"33180-52-ヒフミ" = "コハルちゃん、ハナコちゃん……。"
"33180-53" = "[s3] \"だから大丈夫。どうしても分からないときは、私もいるから。\"\n[s4] \"今はダメだとしても。一緒に悩んで、相談して、解決しよう。\""
"33180-54-ヒフミ" = "……。"
"33180-55-ヒフミ" = "……。"
"33180-56-ヒフミ" = "……はい、ありがとうございます。"
"33180-57-ヒフミ" = "私もちゃんと学びました。諦めません、いつまでも悩みません。"
"33180-58" = "私は、私にできることを……！"
"33180-59-ヒフミ" = "……アズサちゃんを助けに行きます。"
"33180-60" = "[s5] \"……ヒフミは、いつもそうだったもんね。\"\n[s6] \"私も同じように、ヒフミを手伝うよ。\""
"33180-61-ハナコ" = "では、みんなで行きましょうか。"
"33180-62-コハル" = "う、うん！友達を、助けないと……！"
"33180-63-ヒフミ" = "アズサちゃんに会って、今度こそ……"
"33180-64-ハナコ" = "……言いたいことは、伝えないとですね？"
"33180-65-ヒフミ" = "……はい。"
"33180-66-ヒフミ" = "しっかり、伝えないといけません。"
"33180-67-ヒフミ" = "同じ世界にいられないだなんて、私は……。"
"33180-68-コハル" = "ヒフミ……？"
"33180-69" = "[ns] \"友達でも、言わないと伝わらないからね。\""
"33180-70-ヒフミ" = "……はい！今度こそ、はっきり言ってみせます……！"
"33180-71-ハナコ" = "そうですね。私も、ちゃんとすぐそばにいます。"
"33180-72-コハル" = "えっと……と、とにかく行くんでしょ？じゃあほら、早く！"
"33180-73-セイア" = "みんなを集めて、話して……そして繋がって、理解する。"
"33180-74-セイア" = "トリニティとゲヘナの生徒たちが、徐々に……"
"33180-75-セイア" = "アリウスの憎しみがこもったユスティナ聖徒会が、トリニティとゲヘナに進撃してきている今。"
"33180-76-セイア" = "誰かに助けを求めて、求め合って……"
"33180-77-セイア" = "そうして少しずつ、寄り添おうとしている。"
"33180-78-セイア" = "そんな中、単身アリウススクワッドを防ごうとするアズサは……"
"33180-79" = "古聖堂。"
"33180-80-セイア" = "楽園の名前が掲揚されながら、今は廃墟となったあの場所へ。"
"33180-81-セイア" = "アズサ、アリウススクワッド。そして先生もまた、そこへと向かう……"
"33180-82-ミサキ" = "……。"
"33180-83-ヒヨリ" = "……。"
"33180-84-ヒヨリ" = "アズサ……。"
"33180-85-アズサ" = "……。"
"33180-86-サオリ" = "よくも、よくも姫を……！絶対に許さない……！"
"33180-87-アズサ" = "私は、サオリを止めてみせる。刺し違えてでも。"
"33180-88-サオリ" = "お前にそんなことができるか！！"
"33180-89-サオリ" = "私たちの怒りに、憎しみに、恨みに！耐えられるとでも思うのか！！"
"33180-90-アズサ" = "……私は、人殺しになる。"
"33180-91" = "アズサぁっ！！"
"33180-92" = "……たとえもう、あの世界に戻れないとしても。"
"33180-93" = "次回;私たちの物語"
