[translation]
"33190-1" = "第19話;私たちの物語"
"33190-2-アズサ" = "はぁ、はぁ……。"
"33190-3-アズサ" = "くっ……"
"33190-4-サオリ" = "……何故だ、アズサ。"
"33190-5-サオリ" = "何故そこまで足掻く。そこに何の意味がある？何を証明しようとしている？"
"33190-6-サオリ" = "思い出せ、全ては――"
"33190-7-サオリ" = "……たとえ虚しくても、足掻くと決めた。"
"33190-8-サオリ" = "そこに、何の意味がある！！！"
"33190-9-アズサ" = "ぐっ……！！"
"33190-10-アズサ" = "……！？"
"33190-11-ヒフミ" = "……。"
"33190-12-アズサ" = "ヒフ、ミ……？"
"33190-13-ヒヨリ" = "増員、ですね……数は4、いえ、後ろにそれ以上……。"
"33190-14-ミサキ" = "あれは……。"
"33190-15-サオリ" = "……なんだ、お前は？"
"33190-16-ヒフミ" = "普通の、トリニティの生徒です。"
"33190-17-アズサ" = "ヒフミ、ダメだ……どうしてこんなところに……。"
"33190-18-アズサ" = "ここはヒフミみたいな、普通の人が来るべきところじゃ……。"
"33190-19-ヒフミ" = "……。"
"33190-20-ヒフミ" = "……はい、確かに私は普通で平凡です。"
"33190-21-ヒフミ" = "先日見せてくれたガスマスクの姿が、本当のアズサちゃんなのだと。そのことも理解しました。"
"33190-22-ヒフミ" = "そんなアズサちゃんは本当なら、私なんかには手の届かない世界に生きてるのだと……そう言いたいのも分かりました。"
"33190-23-アズサ" = "ヒフミ……？"
"33190-24-ヒフミ" = "でも！！！"
"33190-25-ヒフミ" = "アズサちゃんは一つ、大きな間違いをしています！！！"
"33190-26-アズサ" = "……！？"
"33190-27-ヒフミ" = "今ここで、私の本当の姿をお見せします！！！"
"33190-28-ヒフミ" = "私の正体、それは……"
"33190-29-ヒフミ" = "「覆面水着団」のリーダー、ファウストです！！"
"33190-30-ヒフミ" = "……え？"
"33190-31-ヒフミ" = "見てください、この恐ろしさ！アズサちゃんと並んだって、全然見劣りしないほど不気味でしょう！こっちの方が恐ろしくて怖いと言う人だっているはずです！"
"33190-32-アズサ" = "ひ、ヒフミ……？"
"33190-33-サオリ" = "……。"
"33190-34-ヒヨリ" = "……！？"
"33190-35-ミサキ" = "……。"
"33190-36-ヒフミ" = "ヒフミ、いったい何を――"
"33190-37-ヒフミ" = "だからっ！！"
"33190-38-ヒフミ" = "だから私たちは、違う世界にいるなんてことはありません！"
"33190-39-アズサ" = "……。"
"33190-40-ヒフミ" = "同じです！隣にだっていられます！"
"33190-41-ヒフミ" = "だから世界が違うだなんて、一緒にいられないだなんて……そんなことを言わないでください！"
"33190-42-ヒフミ" = "拒絶されても、すぐ近くに行ってみせます！私は……！"
"33190-43-ヒフミ" = "……私は、アズサちゃんのそばにいます！"
"33190-44-ヒフミ" = "こうやって、すぐ触れられるところに……！"
"33190-45-アズサ" = "ヒフミ……"
"33190-46-アズサ" = "でも、私のためにそんな嘘を言ってくれたところで……"
"33190-47" = "誰が嘘だって！？"
"33190-48-ホシノ" = "いや～、何だか大事なところみたいだね？"
"33190-49-ハナコ" = "あの覆面、まさか……！？"
"33190-50-アズサ" = "！？"
"33190-51-コハル" = "っ！？"
"33190-52-ホシノ" = "目には目を、歯には歯を。無慈悲に、孤高に、#n我が道の如く[ruby=まきょう]魔境[/ruby]を行く……"
"33190-53-シロコ" = "ん、それが私たちのモットー。"
"33190-54" = "普段はアイドルとして活動してますが、夜になると悪人を倒す副業をしてるグループなんです♧"
"33190-55-セリカ" = "別にそれ私たちのモットーじゃないから！？あと変な設定付けないで！"
"33190-56-アヤネ" = "覆面水着団のリーダーであるファウストさんのご命令で、集合しました！"
"33190-57-ハナコ" = "……！？"
"33190-58-コハル" = "え、えっ！？"
"33190-59-ハナコ" = "じ、実在したんですね……？"
"33190-60-ヒヨリ" = "あいつらは……。"
"33190-61-ミサキ" = "……分からない。詳細なデータは無し。"
"33190-62-ヒヨリ" = "ふ、覆面水着団……噂に過ぎないと思ってましたが、本当にいたんですねえ……。"
"33190-63-ミサキ" = "……リーダー、あいつらヘラヘラしてるけど注意した方が良さそう。少なくとも舐めてかかると痛い目に遭う。"
"33190-64-サオリ" = "……。"
"33190-65-ホシノ" = "なーにうちのリーダーを泣かせようとしてるのかな～？ねぇ、そこの君たち？"
"33190-66-ホシノ" = "どこの誰なのか知らないけど、知らないよ？うちのファウストさんは怒ると怖いんだから。"
"33190-67-ノノミ" = "何せファウストちゃんは最終的に、カイザーコーポレーションの幹部を倒しちゃったようなものなんですよ♧"
"33190-68" = "ブラックマーケットの銀行だって襲える。朝飯前みたいに。"
"33190-69-セリカ" = "それにこの間なんて、カイザーPMCを砲撃で吹っ飛ばしたんだからね！"
"33190-70-ホシノ" = "そうだよ、恐ろしいんだよ～？生きて動く災いと言っても過言じゃないし、暗黒街を支配するボスみたいなものなんだから。"
"33190-71-シロコ" = "うん、それがファウスト。"
"33190-72-みんな" = "ファウスト！ファウスト！！ファウスト！！！"
"33190-73-シロコ" = "……。"
"33190-74" = "ああっ、ファウストちゃんが紙袋を取ってしまいました！？"
"33190-75-ホシノ" = "あ～、流石に恥ずかしかったのかなー……？"
"33190-76-セリカ" = "せ、せっかく乗っかってあげたのに！"
"33190-77-シロコ" = "私は何も恥ずかしくないけど。"
"33190-78-シロコ" = "シロコ先輩も、堂々としてないで早く取って！"
"33190-79" = "ん……。"
"33190-80-アヤネ" = "ま、まあとにかく、あらためて……。"
"33190-81-セリカ" = "対策委員会、今度はヒフミさんのことを助けに来ました！！"
"33190-82-ヒフミ" = "ありがとうございます、対策委員会のみなさん……。"
"33190-83-ハスミ" = "ひひひひひひ……。"
"33190-84-ハスミ" = "正義実現委員会、助けに参りました。"
"33190-85-正義実現委員会部員" = "い、委員長、怪我は……？"
"33190-86-ツルギ" = "完治した。"
"33190-87-正義実現委員会部員" = "さ、さすがです！"
"33190-88-ツルギ" = "私はツルギほど丈夫ではないので、まだですが……とはいえ少しは役立つはずです。力になると、約束しましたから。"
"33190-89-イオリ" = "この間はよくも……！無事に帰れると思うなよ！"
"33190-90-イオリ" = "……委員長は？"
"33190-91-イオリ" = "……。"
"33190-92-ヒナ" = "っ、先生……。"
"33190-93-ヒナ" = "無事だった、のね……良かった……。"
"33190-94-ヒナ" = "どうやってここを……？まあ先生には、今さらか……。"
"33190-95" = "[s] \"ヒナ……。\""
"33190-96-ヒナ" = "私は……もう……。"
"33190-97-ヒナ" = "ごめん、先生……私には、もう無理。"
"33190-98-ヒナ" = "私はもうダメ……だから……ガッカリさせて、悪いのだけど……。"
"33190-99-ヒナ" = "今は、帰ってほしい……私はもう、引退したと思ってもらって……。"
"33190-100" = "[ns] \"……ヒナ。\""
"33190-101" = "[ns] \"違うよ。私はここに、お礼を言いに来た。\""
"33190-102-ヒナ" = "お、お礼……？どうして……。"
"33190-103-ヒナ" = "先生を助けたことについてなら、気にしなくて良い……。"
"33190-104-ヒナ" = "それは当然私がやるべきことで、それにあの時私は……。"
"33190-105" = "[s1] \"ううん。いつも頑張ってくれてありがとうって。\"\n[s2] \"もう頑張り過ぎなくても良いって、早く言ってあげたかった。\""
"33190-106-ヒナ" = "……っ！"
"33190-107-ヒナ" = "……っ！"
"33190-108" = "[s] \"ヒナは、ずっと頑張ってたから。\""
"33190-109-ヒナ" = "……。"
"33190-110" = "[s] \"それを言いたかった。だから休んでて、あとは私が何とかする。\""
"33190-111-ヒナ" = "ま、待って、何とかって……。"
"33190-112-ヒナ" = "でも、私は……。"
"33190-113-ヒナ" = "私……。"
"33190-114-ヒナ" = "……。"
"33190-115-ヒナ" = "私は……[ruby=たかなし]小鳥遊[/ruby]ホシノみたいには、なれない……。"
"33190-116" = "[s] \"……ホシノ？\""
"33190-117-ヒナ" = "私はあの、アビドスの副会長みたいな……強い人じゃない……。"
"33190-118-ヒナ" = "アビドスの生徒会長……その遺体を発見したのは、小鳥遊ホシノだった。すごく、ものすごく大切な人だったはずなのに……。"
"33190-119-ヒナ" = "あれだけの苦しみを味わっておきながら、彼女はまだアビドスで戦ってる……私には、そんなことできない……。"
"33190-120-ヒナ" = "私は、そこまで強くなれない……あの瞬間私は、もう……。"
"33190-121" = "[s] \"ヒナ……。\""
"33190-122-ヒナ" = "私だって頑張った！！"
"33190-123-ヒナ" = "いつも頑張って、どうにかしようとして……。"
"33190-124-ヒナ" = "分かってもらえなくても、それでも……。"
"33190-125-ヒナ" = "けど私は、大事なところで……。"
"33190-126-ヒナ" = "先生は、ズルい……私はあの瞬間もう、ダメで……なのに、そんなことを言って……。"
"33190-127-ヒナ" = "私だって、小鳥遊ホシノや補習授業部みたいに……"
"33190-128-ヒナ" = "先生に構ってほしかった、褒められたかった！！"
"33190-129" = "[s] \"…………。\""
"33190-130-ヒナ" = "……あっ。"
"33190-131-ヒナ" = "ご、ごめん……今のは、その……。"
"33190-132" = "[s] \"ヒナ、本当にごめん！\""
"33190-133-ヒナ" = "！？"
"33190-134" = "[s3] \"ヒナも今度、補習授業しよう！\"\n[s4] \"それで成績が良かったらもちろん、たくさん褒めるから！\""
"33190-135-ヒナ" = "……。"
"33190-136-ヒナ" = "……。"
"33190-137-ヒナ" = "え、いや私、成績は元々良いし……だいたい満点だけど……。"
"33190-138" = "[s] \"それとも水着パーティする！？すぐにでも準備するよ！\""
"33190-139-ヒナ" = "えっと、それも別に……。"
"33190-140-ヒナ" = "……。"
"33190-141-ヒナ" = "……はぁ。"
"33190-142-ヒナ" = "ふふっ……。"
"33190-143-ヒナ" = "……ところで先生、実は私に頼みたいことがあるんじゃない？"
"33190-144" = "[s] \"でも、ヒナは引退したって考えると……\""
"33190-145-ヒナ" = "……それは言ってみただけ。少し、みんなに甘えてみたかっただけ。"
"33190-146-ヒナ" = "行こう、先生。"
"33190-147-アコ" = "委員長……！"
"33190-148-ヒナ" = "……待たせてごめん、アコ。みんなも無事で良かった。"
"33190-149-アコ" = "いえ……はいっ！！"
"33190-150" = "準備はできてるわね。先生の指示を待とう。"
"33190-151-ヒヨリ" = "包囲、されてしまいましたねぇ……。"
"33190-152-ミサキ" = "これはちょっと厳しいんじゃない、リーダー？"
"33190-153-サオリ" = "知ったことか。無限に増殖する「ユスティナ聖徒会」の前では等しく無意味。"
"33190-154-サオリ" = "……むしろ好都合だ。アズサだけでなく、この場の全員に知らせてやれ。"
"33190-155-サオリ" = "この世界の真実を……殺意と憎しみに満ちたこの世界で、あらゆる努力は無駄なのだと。"
"33190-156" = "足掻こうと何の意味もない、全ては無駄なのだということを！！"
"33190-157-ヒフミ" = "……。"
"33190-158" = "[s] 頷く。"
"33190-159-アズサ" = "ヒフミ……。"
"33190-160-ヒフミ" = "アズサちゃん、私は今すごく怒ってます。すっごくです。"
"33190-161-アズサ" = "……。"
"33190-162-ヒフミ" = "ですが……それ以上に、無事でよかったです。"
"33190-163-ヒフミ" = "すっごく怒ってましたが、よく考えてみればそれはアズサちゃんのせいではありません。ですから、私はもう怒っていません。"
"33190-164-アズサ" = "ヒフミ……。"
"33190-165" = "ですが、あの方々についてはまだ怒っています。"
"33190-166-ヒフミ" = "殺意ですとか、憎しみですとか……それが、この世界の真実ですとか……"
"33190-167-ヒフミ" = "それを強要して、全ては虚しいのだと言い続けてましたが……"
"33190-168" = "それでも、私は……！"
"33190-169" = "ヒフミ"
"33190-170" = "[7cd0ff]補習授業部[-]"
"33190-171" = "アズサちゃんが人殺しになるのは嫌です……。"
"33190-172" = "ヒフミ"
"33190-173" = "[7cd0ff]補習授業部[-]"
"33190-174" = "そんな暗くて憂鬱なお話、[wa:2300]私は嫌なんです。"
"33190-175" = "ヒフミ"
"33190-176" = "[7cd0ff]補習授業部[-]"
"33190-177" = "それが真実だって、[wa:2000]この世界の本質だって言われても、[wa:2300]私は好きじゃないんです！"
"33190-178" = "ヒフミ"
"33190-179" = "[7cd0ff]補習授業部[-]"
"33190-180" = "私には、好きなものがあります！"
"33190-181" = "ヒフミ"
"33190-182" = "[7cd0ff]補習授業部[-]"
"33190-183" = "平凡で、大した個性もない私ですが……自分が好きなものについては、絶対に譲れません！"
"33190-184" = "ヒフミ"
"33190-185" = "[7cd0ff]補習授業部[-]"
"33190-186" = "友情で苦難を乗り越え"
"33190-187" = "ヒフミ"
"33190-188" = "[7cd0ff]補習授業部[-]"
"33190-189" = "努力がきちんと報われて"
"33190-190" = "ヒフミ"
"33190-191" = "[7cd0ff]補習授業部[-]"
"33190-192" = "辛いことは慰めて、お友達と慰め合って……！"
"33190-193" = "ヒフミ"
"33190-194" = "[7cd0ff]補習授業部[-]"
"33190-195" = "苦しいことがあっても……誰もが最後は、笑顔になれるような！"
"33190-196" = "ヒフミ"
"33190-197" = "[7cd0ff]補習授業部[-]"
"33190-198" = "そんなハッピーエンドが[wa:1200]私は好きなんです！！"
"33190-199" = "ヒフミ"
"33190-200" = "[7cd0ff]補習授業部[-]"
"33190-201" = "誰が何と言おうとも、[wa:1200]何度だって言い続けてみせます！"
"33190-202" = "ヒフミ"
"33190-203" = "[7cd0ff]補習授業部[-]"
"33190-204" = "私たちの描くお話は、私たちが決めるんです！"
"33190-205" = "ヒフミ"
"33190-206" = "[7cd0ff]補習授業部[-]"
"33190-207" = "終わりになんてさせません、[wa:1500]まだまだ続けていくんです！"
"33190-208" = "ヒフミ"
"33190-209" = "[7cd0ff]補習授業部[-]"
"33190-210" = "私たちの物語……"
"33190-211" = "ヒフミ"
"33190-212" = "[7cd0ff]補習授業部[-]"
"33190-213" = "私たちの、"
"33190-214" = "私たちの、青春の物語を！！"
"33190-215" = "Blue Archive"
"33190-216-ヒヨリ" = "あ、雨雲が……。"
"33190-217-ミサキ" = "気象の操作……？いや、これは……。"
"33190-218-ヒヨリ" = "き、奇跡、ですか……？"
"33190-219-ミサキ" = "っ、奇跡なんて無い！何これ……！"
"33190-220-ミサキ" = "まさか、戒律が……？"
"33190-221" = "[ns] \"ここに宣言する。\""
"33190-222" = "[ns] \"私たちが、新しい[ruby=ETO]エデン条約機構[/ruby]。\""
"33190-223-サオリ" = "なっ……！？"
"33190-224-セイア" = "まさか……"
"33190-225-セイア" = "これはエデン条約……先生、君は……"
"33190-226-セイア" = "元々は、連邦生徒会長が作るはずだった条約……"
"33190-227-セイア" = "そしてその連邦生徒会長が設立した、超法規的機関「シャーレ」……"
"33190-228-セイア" = "まさか「シャーレ」が連邦生徒会長を代行すると？いや、そう解釈できるように捻じ曲げた……？"
"33190-229-セイア" = "アリウスと、同じ……。"
"33190-230-セイア" = "条約の主体であるゲヘナ、ティーパーティー、正義実現委員会、そして風紀委員会たちが集まって……"
"33190-231-セイア" = "かつて古聖堂があった廃墟で……"
"33190-232-セイア" = "条約の発起人である連邦生徒会長の代わりに、先生が……"
"33190-233-セイア" = "楽園の名を冠する約束を、再現した……？"
"33190-234-セイア" = "……。"
"33190-235-セイア" = "契約を曲解し、歪曲し、望み通りの結果を捏造する……"
"33190-236-セイア" = "「大人」のやり方には「大人」のやり方で、か……"
"33190-237-ミサキ" = "……リーダー、ユスティナの統制がおかしくなってる。"
"33190-238-サオリ" = "！！"
"33190-239-ヒヨリ" = "こ、混乱してますね……[ruby=ETO]エデン条約機構[/ruby]を助けるというのが戒律、しかし今はETOが二つあって……。"
"33190-240-サオリ" = "っ、知ったことか！！！！"
"33190-241-サオリ" = "ハッピーエンドだと！？ふざけるな！そんな言葉で、世界が変わるとでも！？"
"33190-242-サオリ" = "それだけでこの憎しみが、不信の世界が変わるとでも言うつもりか！？何を夢のような話を……！"
"33190-243" = "[s] \"生徒たちの夢を……その実現を助けるのは、大人の義務だから。\""
"33190-244-サオリ" = "……っ！"
"33190-245" = "[s5] \"私は生徒たちが願う夢を信じて、それを支える。\"\n[s6] \"生徒たち自身が心から願う夢を。\""
