[translation]
"33250-1" = "第25話;エピローグ"
"33250-2-マコト" = "よくも、よくもこのマコト様を騙したなあああぁぁぁぁぁっ！！！"
"33250-3-マコト" = "イロハ、イロハはどこだ！今すぐにアレを用意しろ！このままやられっぱなしでたまるものか……！"
"33250-4-イロハ" = "「アレ」と言われましても何のことかサッパリですが、もう少し横になってた方が良いと思いますよ。"
"33250-5-イロハ" = "あと喋るなら、その面白い頭をどうにかしてからにしてください。そもそも既に色々決着してますし。"
"33250-6-マコト" = "何だと……頭？"
"33250-7-マコト" = "な、何だこれはあああぁぁぁ！？"
"33250-8-イロハ" = "それはだってあの時、火に包まれましたし……はぁ。"
"33250-9-ティーパーティーの行政官" = "……お身体の具合はいかがですか、ナギサ様。"
"33250-10-ナギサ" = "ヘイローが砕けるかと思いましたが……どうやら無事のようですね。"
"33250-11-ティーパーティーの行政官" = "はい、幸いです……本当に何よりでした。どうかご無理なさらず。"
"33250-12-ナギサ" = "……ありがとうございます。ところでいらっしゃったのは、何かご用件が？"
"33250-13-ティーパーティーの行政官" = "あ、実はその、ミカ様からお手紙が……。"
"33250-14-ナギサ" = "……中には何と？"
"33250-15-ティーパーティーの行政官" = "えっと、ですね……"
"33250-16-ミカ" = "やっほーナギちゃん！何か聞いたところによると、ミサイルが撃ち込まれてからずっと気を失ってたんだって？"
"33250-17-ミカ" = "あんなに色々あったのに気楽にすやすや寝てたなんて、ホストとして中々みんなには見せられない姿だね？"
"33250-18-ミカ" = "まっ、ずっと頑張ってたんだし休んでほしいとは思ってたけどさ。まさかそこまでぐっすりだなんて思わなかったよ。"
"33250-19-ミカ" = "無事に目覚めたみたいだし、ちょっとお願い聞いてくれない？早めにホストに復帰して、どうにかしてくれると嬉しいんだけど！"
"33250-20-ミカ" = "まずここのテレビ、普通の放送しか見られないじゃん？24時間色んなのが見られるアレ入れてくれない？"
"33250-21-ミカ" = "あとハンドクリームが切れちゃったの。私いつものブランドじゃないとダメだから、買ってきてくれる？売ってるところは後で伝えるね！"
"33250-22-ミカ" = "それとヘアドライヤーが何か弱くなってきたんだよね。もうちょっと高いやつに変えてもらえないかな？"
"33250-23-ミカ" = "あ、せっかくだしナギちゃんとお揃いのにしよっと！すっごく良いブランドの最上級モデル使ってるんでしょ、あの髪質良くなったタイミングで変えたやつ。私知ってるんだから！"
"33250-24" = "あとさあとさ――"
"33250-25-ナギサ" = "……。"
"33250-26-ティーパーティーの行政官" = "えっと……どういたしましょう。やはり監獄ではなく……"
"33250-27" = "ミカさんのお食事は今後、全てロールケーキだけで構いません。"
"33250-28-ティーパーティーの行政官" = "はい……はいっ！？"
"33250-29-ミネ" = "みなさん。"
"33250-30-セリナ" = "だ、団長……！？"
"33250-31-セリナ" = "団長！！！"
"33250-32-ミネ" = "……何も言わずにいなくなって、ごめんなさい。"
"33250-33-セリナ" = "うわああぁぁぁぁん！！団長ーーーー！！"
"33250-34-ミネ" = "お待たせしてしまってごめんなさい……遅ればせながら、ただいま戻りました。"
"33250-35-正義実現委員会部員" = "ミカさん……。"
"33250-36-正義実現委員会部員" = "ナギちゃん、何でまだそんな顔してるの？上手く行った……ことはまあ、少ないかもしれないけどさ。"
"33250-37-正義実現委員会部員" = "それは……。"
"33250-38-セイア" = "まだ私たちには、解決できていない宿題が山積みだから……だろう？"
"33250-39" = "セ、セイアさん……?"
"33250-40-正義実現委員会部員" = "セイアちゃん！？"
"33250-41-セイア" = "……やあ、ナギサ、ミカ。"
"33250-42-セイア" = "久方ぶりの集合だね。"
"33250-43-セイア" = "長い時間が経ち、色々なことがあったが……"
"33250-44-セイア" = "私たちはそろそろ、お互いに話すべきだろう。"
"33250-45-セイア" = "言わなかったことや、言えなかったこと。"
"33250-46-セイア" = "そして、本当は言いたかったことを。"
"33250-47-セイア" = "誤解もあるだろう、信じられないこともあるだろう。たとえどこにも到達できないとしても……それでも、他者の心という証明不可能な問題に向かうしかない。"
"33250-48-セイア" = "私たちは皆、進まねばならない。その宿題をずっと背負いながら、それでもこの闇の中を……ただ、その先を目指して。"
"33250-49-ナギサ" = "……ですね。"
"33250-50-ミカ" = "うん、それはすごく同感……だけど、相変わらず難しいことばっかり。セイアちゃん、だから友達がいないんでしょ？ちょっとは自覚してる？"
"33250-51-ミカ" = "……。"
"33250-52" = "先ずミカはその良く鳴りそうな頭に、教養と品格を入れてもらった方が良さそうだね？"
"33250-53-ミカ" = "あの、お二人とも……。"
"33250-54" = "[ns] \"えっと……前の補習授業部は一旦全員卒業したはずで……。\""
"33250-55" = "[ns] \"今度はまた新たに補習授業部が、って聞いて来たんだけど……？\""
"33250-56-ヒフミ" = "……。"
"33250-57-ハナコ" = "……。"
"33250-58-ヒフミ" = "……。"
"33250-59-ハナコ" = "……。"
"33250-60-ハナコ" = "[ns] \"同じメンバーだね！？\""
"33250-61-ヒフミ" = "あ、あはは……それが、その……。"
"33250-62" = "ペロロ様のコンサートに参加してたのですが、実は試験日だったようで……。"
"33250-63-アズサ" = "次の試験範囲はまだ習ってない。"
"33250-64-コハル" = "えっと、その……3年生の試験を受けてみたんだけど……。"
"33250-65-ハナコ" = "ひとりだけ放置プレイなんて、寂しいじゃないですか♡"
"33250-66-コハル" = "あ、あの、すみません先生……何だかまたこんなことになって……。"
"33250-67-コハル" = "で、ですが今回は退学もありませんし、試験範囲もちゃんと普通の……！"
"33250-68" = "[ns] くらっと来て倒れる。"
"33250-69-ヒフミ" = "せ、先生！？"
"33250-70-アズサ" = "先生！"
"33250-71-コハル" = "な、何それ！そんな反応しなくても良いじゃん！？"
"33250-72-ハナコ" = "あら、これは……"
"33250-73-ハナコ" = "ちょっと！今「ちょうど良さそうですね、この隙に」みたいな顔したでしょ！？"
"33250-74" = "バカっ、エッチなのは禁止！！死刑っ！！！"
"33250-75" = "……。"
"33250-76" = "あなたはこれからも、たくさんのことを学んでいくでしょう。これからもずっと、友人たちと一緒に。"
"33250-77" = "勉強し、努力をし、様々な可能性を見つけるのでしょう。"
"33250-78" = "……あなたは強いから。"
"33250-79" = "例えすべてが虚しくても、この世界が暗く寂しいものでも……"
"33250-80" = "たとえ、コンクリートの隅であっても……。"
"33250-81" = "……アズサ。"
"33250-82" = "あの時見せてくれた花のこと……今は少し、理解できたかもしれない。"
"33250-83" = "もう二度と会うことは無いかもしれないけれど。"
"33250-84" = "どうか、幸せに。"
"33250-85-？？？" = "……左様でしたか。"
"33250-86-？？？" = "あのロイヤルブラッド、逃げたのですね。"
"33250-87-？？？" = "……捕まえてきてください。怪我の無いように、丁重に。"
"33250-88-？？？" = "彼女以外は、全員処理しても構いません。"
"33250-89-？？？" = "……ええ。「ヘイローを破壊」しても構わない、という意味です。"
