[translation]
"10047105-1" = "ワイルドハント寮監隊の寮の廊下"
"10047105-2" = "[ns] \"あれ？こっちには寮監隊がいないね。\""
"10047105-3-カノエ" = "イヒッ……追っ手は全部、まいたから……。"
"10047105-4-ツムギ" = "みんな、鐘の方に向かったのでしょう。"
"10047105-5-エリ" = "レナちゃん……うまく逃げられたでしょうか。"
"10047105-6-カノエ" = "鐘の音が止まった……もうじき、寮監隊が戻ってくる……。"
"10047105-7" = "[ns] \"みんな、急ごう！\""
"10047105-8-エリ" = "あとは、この入口にテープを……！"
"10047105-9-寮監隊員C" = "こいつら、いつの間にうちまで……！"
"10047105-10-寮監隊員B" = "全員止まれっ！もう小細工は通用しないぞ！！"
"10047105-11-エリ" = "……にゅふふふ、一足、遅かったですね。#n既に魔法陣の構築は完了しました。"
"10047105-12-エリ" = "時が来ました！月が満ちた今、真理の扉が開きます……！"
"10047105-13-寮監隊員B" = "魔法陣と満月？ま、まさかあいつ……！"
"10047105-14-寮監隊員B" = "学院の言い伝えを再現する気か！？"
"10047105-15-エリ" = "ええ！お見せしましょう！！"
"10047105-16-エリ" = "魔法錬成陣、発動……！！"
"10047105-17-寮監隊員A" = "ぐ、ぐあああっ……！か、体から力が抜けていく……！！"
"10047105-18-寮監隊員B" = "こ、ここまでか……！"
"10047105-19-寮監隊員C" = "……明かりが点いただけでは？"
"10047105-20-寮監隊員A" = "うん。"
"10047105-21-寮監隊員B" = "乗っかったほうがいいのかなって……。"
"10047105-22-エリ" = "あ、あれ？どうして何も起こらないのでしょう……？"
"10047105-23-エリ" = "魔法陣はちゃんと、描いたはず……！"
"10047105-24-エリ" = "願いが叶う魔法は……なかった、のかぁ……。"
"10047105-25-ツムギ" = "でも、美しい光景です。学院中がキラキラと輝いて……。"
"10047105-26-ツムギ" = "……ふむ。"
"10047105-27-ツムギ" = "私たちは、宝石を扱う方々に敬意を込めて「光の細工師」と呼ぶことがあります。"
"10047105-28-ツムギ" = "宝石とは、物質だけを称する言葉ではありません。#n……夢に向かう少女たちの情熱。#nこれもまた、美しい宝石ではないでしょうか。"
"10047105-29-ツムギ" = "ゆえに、立ち会う一人として、私は思うのです。#n今、ここにあるのは――"
"10047105-30-ツムギ" = "――美しき光の細工である、と。"
"10047105-31-寮監隊員B" = "御託はいいから投降しろ！"
"10047105-32-寮監隊員B" = "あんたらのせいで寝不足なんだよ！明日も朝から検問なんだ！"
"10047105-33" = "[ns] \"……ここまで、か。\""
"10047105-34-？？？" = "お待ちください。"
"10047105-35" = "[ns] \"君は……。\""
"10047105-36-ミリア" = "少しよろしいでしょうか？"
"10047105-37-ミリア" = "評議会長からみなさんに、言伝がありまして。"
"10047105-38-エリ" = "そ、そんな偉い方が私たちに……？"
"10047105-39-ミリア" = "ええ。"
"10047105-40-評議会長" = "こんばんは。評議会長の[ruby=うるわし]雲類鷲[/ruby]マナミと申します。"
"10047105-41-評議会長" = "こんな真夜中までご苦労様です。"
"10047105-42-評議会長" = "現場に駆けつけたいところでしたが……#nこのような形になること、ご了承ください。"
"10047105-43-評議会長" = "さて、率直に申し上げますと……。"
"10047105-44-評議会長" = "……感服いたしました。"
"10047105-45-評議会長" = "実は私、前々から404号室のみなさんに興味を持っておりまして。"
"10047105-46-評議会長" = "きっとこの方々ならば、型破りな芸術を体現できるだろう……と。"
"10047105-47-評議会長" = "今宵、みなさんはその期待に応えてくださいました。"
"10047105-48-評議会長" = "学院の過去と現在を光で結び、美しき図形に昇華させた……#nこれまで類を見ない前衛芸術です。"
"10047105-49-評議会長" = "こちらの作品は、404号室のみなさんの名と共に、#nこの先も展示させていただきたいと考えております。"
"10047105-50-評議会長" = "そうですね……学院の誰もが鑑賞できるよう、#n展望台の新設を働きかけましょう。"
"10047105-51-評議会長" = "その光景を収めた写真は、私の「コレクション」として遜色ないでしょう。"
"10047105-52-評議会長" = "ふふふ……これからのご活躍が楽しみです。#n次の機会には、ぜひ正式にお伺いさせてください。"
"10047105-53-評議会長" = "此度の創作と、新たな芸術の誕生に感謝を。#n……それでは。"
"10047105-54-エリ" = "私たちの魔法陣が……見事な芸術作品？"
"10047105-55-カノエ" = "ですから、言いましたよね。美しき光の細工だと。"
"10047105-56-カノエ" = "君らも……本当は綺麗だと思ったよねぇ？"
"10047105-57-寮監隊員B" = "まぁ……うん。"
"10047105-58-寮監隊員B" = "たしかに片づけるのは勿体ないかもな……。"
"10047105-59-エリ" = "私は……みんなに認められる作品を作りたかった。"
"10047105-60-エリ" = "落ちこぼれじゃなく、愛されるアーティストになりたかった。"
"10047105-61-エリ" = "いつも自信満々に笑っていたのも、焦りを誤魔化すためで……。#nだから――"
"10047105-62-エリ" = "ありがとうございます。すべてみんなのおかげです。"
"10047105-63-エリ" = "私一人では、とても……。"
"10047105-64" = "[ns1] \"ううん、エリが頑張ったからできたことだよ。\"\n[ns2] \"だから、自信を持ってね。\""
"10047105-65" = "[ns3] \"ここは夢と希望のワンダーランド。\"\n[ns4] \"みんなの夢が叶う場所だから。\""
"10047105-66-エリ" = "マスター……。"
"10047105-67-エリ" = "はい……！私、これからも頑張ります！"
"10047105-68-エリ" = "みんなと一緒なら……何でもできる気がするんです！"
"10047105-69-エリ" = "やはり……実在しました。"
"10047105-70-エリ" = "私が追い求めていた――願いを叶える魔法は！"
"10047105-71-エリ" = "願っています。"
"10047105-72-エリ" = "ここでみんなが……夢を叶えられるように。"
"10047105-73-エリ" = "そして、ずっと、ずっと――"
"10047105-74-エリ" = "こんな魔法みたいな日々が、続きますように！"
