[translation]
"10047100-1" = "第10話;願いが叶う魔法"
"10047100-2-寮監隊員B" = "そ、そういえば……「滅亡の日、鐘はひとり[ruby=うた]謳[/ruby]いだす」って……。"
"10047100-3-寮監隊員A" = "そんなこと本気で信じてんのか？よくある都市伝説だろ？"
"10047100-4-寮監隊員C" = "で、でもほんとに鳴ってるじゃないですか……！#nあの不吉な鐘が！"
"10047100-5-ツムギ" = "この音色……不吉さは感じませんね。"
"10047100-6-ツムギ" = "むしろ、私たちを想うあの子の、純粋な気持ちが……。"
"10047100-7-ツムギ" = "意見が合わなくとも、大切な仲間。#nそんな友人たちを見送る側に立った、無念と不安。"
"10047100-8-ツムギ" = "それらの感情が合わさり生じた、自分への罪悪感と無力感。"
"10047100-9-ツムギ" = "でもあなたなら、成し遂げたい真の物語を見つけられると、#n信じておりました。"
"10047100-10-ツムギ" = "ふふ。聞こえますよ、私たちを想うあなたの優しさが。"
"10047100-11" = "名もなき鐘塔のてっぺん"
"10047100-12-レナ" = "シャーッ！！！何で私がこんなこと！"
"10047100-13-レナ" = "みんな結局捕まってるし！"
"10047100-14-レナ" = "ここまでしたんだから――"
"10047100-15-レナ" = "成功させなきゃ許さないから！バカ先輩ども――！！！"
"10047100-16-カラス" = "ガァァッ！ガァァァッ！"
"10047100-17-寮監隊員A" = "ひっ！カラスの群れが……！！"
"10047100-18-カノエ" = "みんな怯えてる……この隙に突破しよう。"
"10047100-19-エリ" = "マスター、手を！"
"10047100-20-エリ" = "願いが叶う魔法を、みんなで完成させましょう！"
