[translation]
"10047095-1" = "[ns] \"はぁ……はぁ……！\""
"10047095-2-エリ" = "あっ、マスター！こっちです！"
"10047095-3-エリ" = "念のため、カラスを送っておいてよかったぁ……。"
"10047095-4-エリ" = "ふふっ。ですが……まだ試練は続きそうです。"
"10047095-5-寮監隊員A" = "よし！追い詰めたぞ！"
"10047095-6-寮監隊員B" = "もう逃げ場はない、全員投降しろ！"
"10047095-7-エリ" = "うぅ、あとは寮監隊の宿舎だけなのに……。"
"10047095-8-カノエ" = "思ったより……警備が厳しかった……。"
"10047095-9-ツムギ" = "……ふふ、[ruby=あまた]数多[/ruby]の失敗の果てに、美しい成功があるもの。"
"10047095-10-ツムギ" = "本来、芸術の道とは険しいものですから。"
"10047095-11-ツムギ" = "簡単には手に入らずとも、いつか答えを見つけられると信じて進む。#nそれこそが、芸術への――"
"10047095-12-カノエ" = "――挑戦。"
"10047095-13-エリ" = "……ですから！"
"10047095-14-寮監隊員A" = "何をうだうだと……！#n全員、現行犯で確――"
"10047095-15-寮監隊員B" = "な、何だ？鐘の音？"
"10047095-16-寮監隊員B" = "この方向は、まさか……？"
"10047095-17-ツムギ" = "……「名もなき鐘」の方ですね。"
"10047095-18-カノエ" = "鳴ってる……滅亡を謳う――"
"10047095-19-エリ" = "伝説の鐘が！！"
