[translation]
"1008303-1" = "休息の重要性"
"1008303-2-キキョウ" = "約束通り来たよ。"
"1008303-3" = "[s1] \"急に驚いたよ……\"\n[s2] \"約束と言うには一方的だったような……\""
"1008303-4-キキョウ" = "ふうん。"
"1008303-5-キキョウ" = "生徒が来たのに嬉しくないんだ？"
"1008303-6-キキョウ" = "……シャーレはどんな生徒でも歓迎してるって聞いたんだけど。"
"1008303-7-キキョウ" = "ああ……つまり「生徒」は歓迎だけど……"
"1008303-8-キキョウ" = "「私」とは会いたくなかったんだ？"
"1008303-9" = "[s3] \"いやいや！そんな事これっぽっちも思ってないよ！？\"\n[s4] \"むしろ、毎日でも来てほしいくらい！\""
"1008303-10-キキョウ" = "……そう。"
"1008303-11-キキョウ" = "まあ……"
"1008303-12-キキョウ" = "ちょっとした冗談だから。"
"1008303-13-キキョウ" = "そんなに身構えなくても大丈夫。"
"1008303-14" = "[s] \"キキョウの冗談はちょっと分かりづらいよ……。\""
"1008303-15-キキョウ" = "……はいはい、悪かったですね。"
"1008303-16-キキョウ" = "はぁ……とにかく、雑談は終わり。"
"1008303-17-キキョウ" = "用事があって来ただけだから。"
"1008303-18-キキョウ" = "……一体なにかって？"
"1008303-19-キキョウ" = "単純な話だよ。"
"1008303-20-キキョウ" = "この前、あんたが調停室を直してくれたでしょう？#nそれが結構、委員会の間で好評だったの。"
"1008303-21-キキョウ" = "「雨が降ってもバケツを用意する必要がありませんの！」とか「もう歩く時に踏み抜く心配をしなくて良いのですね」とか。"
"1008303-22-キキョウ" = "「ドアには雨風を凌ぐ役割がちゃんとあったんだな！」とか……"
"1008303-23" = "[s] \"今までどうやって生活してたの！？\""
"1008303-24-キキョウ" = "まあ、今のはちょっと大げさだけど……みんなが感謝してるのは本当。#n……もちろん、私も。"
"1008303-25-キキョウ" = "だから今日は、あんたに借りを返しに来たの。"
"1008303-26-キキョウ" = "百花繚乱の参謀担当、[ruby=きりゅう]桐生[/ruby]キキョウがあんたの仕事を手伝ってあげる。"
"1008303-27-キキョウ" = "今なら何だってお願いできるチャンスだよ。"
"1008303-28-キキョウ" = "どう？いい機会じゃない？"
"1008303-29" = "[s5] \"元からお礼をもらうつもりは無かったから。\"\n[s6] \"お礼の話をするなら、こっちが夕食のお返しをしないとね。\""
"1008303-30-キキョウ" = "……嘘。"
"1008303-31" = "[s] \"……え？\""
"1008303-32-キキョウ" = "最初から報酬は要らないとか、手料理で満足だとか。"
"1008303-33-キキョウ" = "本当に、そんなもので十分なわけないでしょう。"
"1008303-34-キキョウ" = "遠慮しなくていいよ。"
"1008303-35-キキョウ" = "人と人の関係は、いつだって利害の一致で成り立っている。"
"1008303-36-キキョウ" = "一方が与えるだけの関係は望ましくない。#n利害のバランスが崩れてしまえば人間関係もいずれ破綻する。"
"1008303-37-キキョウ" = "誰しも大なり小なり欲望を持っているでしょう？#nだから、先生が何らかの損得勘定を持っていても否定はしない。"
"1008303-38-キキョウ" = "本音を隠そうとしたって、私の目は欺けないよ。"
"1008303-39-キキョウ" = "これ以上、無意味な会話を続けてもお互い疲れるだけ。#n早く素直になったら？"
"1008303-40-キキョウ" = "「どんな手段だって厭わない」――私があんたを利用したように、今度は桐生キキョウを利用するチャンスだよ。"
"1008303-41-キキョウ" = "こんな機会、二度と無いかもしれないけど？"
"1008303-42" = "[ns7] \"……そこまで言うなら分かったよ。\"\n[ns8] \"せっかくのチャンスだからね。\""
"1008303-43-キキョウ" = "……そう。#nやっぱり、あんたも所詮……"
"1008303-44-キキョウ" = "……いいよ、好きにして。#nどんな内容だろうと必ず期待に応えてみせるから。"
"1008303-45-キキョウ" = "（……これで良い）"
"1008303-46-キキョウ" = "（大人しく言われた通りにすれば、借りを返せる）"
"1008303-47-キキョウ" = "（それで私たちの関係は元に戻る……）"
"1008303-48" = "[ns] \"じゃあ、今日は一日ゆっくり休んでもらおうかな。\""
"1008303-49-キキョウ" = "……え？"
"1008303-50-キキョウ" = "ちょっと待って、それは何の冗談？"
"1008303-51-キキョウ" = "ちゃんと聞いてた？"
"1008303-52-キキョウ" = "私を「利用」できるチャンスだって言ったはずだけど。"
"1008303-53-キキョウ" = "……それとも、私のことを馬鹿にしてるの？"
"1008303-54" = "[s] \"ううん、承知の上で「利用」してるだけだよ。\""
"1008303-55" = "[ns] \"作戦参謀なら、休息の重要性を知ってるでしょ？\""
"1008303-56-キキョウ" = "そ、それくらい分かってるけど！"
"1008303-57-キキョウ" = "万全な状態で作戦に臨むには、補給や休息も大切……"
"1008303-58-キキョウ" = "でも今はそんな話、してないでしょう？"
"1008303-59-キキョウ" = "私をからかって何がした……"
"1008303-60" = "[s] \"私は言われた通り、お願いしただけだよ。\""
"1008303-61-キキョウ" = "選択権は私にあるって言うの？"
"1008303-62-キキョウ" = "……呆れた。理解できない。"
"1008303-63" = "[s] \"それとも、さっきの言葉を撤回する？\""
"1008303-64-キキョウ" = "……！"
"1008303-65-キキョウ" = "はぁ……。"
"1008303-66-キキョウ" = "いいよ。それがあんたの望みなら――"
"1008303-67" = "[ns] \"う、うわっ！キキョウさん……！？\""
"1008303-68-キキョウ" = "……何言ってるの？"
"1008303-69-キキョウ" = "まあ……今のは、あんたの後ろにある本を取っただけ。"
"1008303-70" = "[s] \"それはつまり……？\""
"1008303-71-キキョウ" = "あんたのお願いに付き合ってあげる。"
"1008303-72-キキョウ" = "……今日は一日、おとなしくしてるわよ。"
"1008303-73-キキョウ" = "しばらくの間、この本とソファ借りるから。#nいいでしょう？"
"1008303-74" = "[s] \"あ、うん！そうだ、キキョウもコーヒーでいいかな？\""
"1008303-75-キキョウ" = "……うん。"
"1008303-76-キキョウ" = "はぁ……せっかくのチャンスを、こうやって無駄にするなんて。"
"1008303-77-キキョウ" = "先生……"
"1008303-78-キキョウ" = "あんたって、本当に……"
"1008303-79-キキョウ" = "…………変な人。"
"1008303-80" = "（そうして、キキョウの隣で静かな一日を過ごした）"
