[translation]
"1008302-1" = "調停室の番猫"
"1008302-2-キキョウ" = "……以上が、今後の運営方針と訓練計画。"
"1008302-3-キキョウ" = "これをたたき台にして詰めていけば、より良い協力関係が築けると思う。"
"1008302-4-キキョウ" = "私からの話は終わり。"
"1008302-5-キキョウ" = "……質問があるなら聞くけど。"
"1008302-6" = "[s1] \"うーん、今のところは特にないかな。\"\n[s2] \"資料も説明も分かりやすかったし、完璧だったよ。\""
"1008302-7-キキョウ" = "そう。"
"1008302-8" = "[s] \"流石はキキョウだね。\""
"1008302-9-キキョウ" = "お世辞はいらない。"
"1008302-10-キキョウ" = "百花繚乱の作戦参謀だもの、これくらい当然。"
"1008302-11-キキョウ" = "……それに私たちにとって、今が一番大事な時期だから。"
"1008302-12-キキョウ" = "百花繚乱を以前のような活気に戻すためなら、どんな手段だって厭わない。"
"1008302-13-キキョウ" = "先は長いけど、できることから順番にやっていくよ。"
"1008302-14" = "[s] \"キキョウが居るなら、百花繚乱は安泰だね。\""
"1008302-15-キキョウ" = "……私の話、聞いてなかったの？#n先生を利用するって言ったつもりなんだけど。"
"1008302-16-キキョウ" = "それでも構わない？"
"1008302-17-キキョウ" = "……お人好し。"
"1008302-18-キキョウ" = "あんたがいいなら、ありがたく利用させてもらうけど。#nじゃ、今日の話はここまで。"
"1008302-19" = "[s] \"あ、うん。お疲れ様、キキョウ。\""
"1008302-20-キキョウ" = "…………。"
"1008302-21-キキョウ" = "まあ……"
"1008302-22-キキョウ" = "その……"
"1008302-23-キキョウ" = "わざわざこっちまで来てくれて、ありが……"
"1008302-24-キキョウ" = "……忘れ物が無いか、ちゃんと確認して帰って。"
"1008302-25" = "[s] \"えっと……なんだか天井が崩れたような？\""
"1008302-26-キキョウ" = "別に、あんたが気にすることじゃない。"
"1008302-27-キキョウ" = "はい、出口はあっち。"
"1008302-28-キキョウ" = "そこ、気をつけて。"
"1008302-29-キキョウ" = "下手に体重をかけたら……"
"1008302-30" = "[ns] \"今度は床板が！？\""
"1008302-31-キキョウ" = "……大したことじゃないから。"
"1008302-32-キキョウ" = "あんたが気にする必要は……"
"1008302-33" = "[ns] \"いや、気にしないわけにはいかないけど！？\""
"1008302-34-キキョウ" = "……はぁ。"
"1008302-35" = "[ns] \"……調停室の老朽化？\""
"1008302-36-キキョウ" = "……うん。"
"1008302-37-キキョウ" = "調停室は、百花繚乱が設立してからずっと使ってる建物なんだけど……#nあんまり修繕されてなくて。"
"1008302-38-キキョウ" = "それに、色んなゴタゴタでしばらく人がいなかったからね。#n急速に老朽化が進んだみたい。"
"1008302-39-キキョウ" = "ここだけじゃなく、全体的に修繕しないといけないかも。"
"1008302-40-キキョウ" = "でも、これはあくまで私たち百花繚乱の事情。#n先生が気にする必要は無い。"
"1008302-41-キキョウ" = "だから、大人しく帰っ……"
"1008302-42" = "[s] \"いや、手伝うよ。\""
"1008302-43-キキョウ" = "え？"
"1008302-44-キキョウ" = "……見て見ぬふりはできない？"
"1008302-45-キキョウ" = "……どうして？"
"1008302-46" = "[s] \"どうしてと言われても……\""
"1008302-47-キキョウ" = "調停室を直したところで、あんたに何の得があるの？"
"1008302-48-キキョウ" = "あんたが忙しいのは知ってる。"
"1008302-49-キキョウ" = "なのに、わざわざ面倒事に首を突っ込むなんて……"
"1008302-50" = "[s] \"生徒が困ってるなら助けたいから。\""
"1008302-51-キキョウ" = "はあ……分かった。"
"1008302-52-キキョウ" = "まあ、そんなにお節介を焼きたいなら勝手にして。"
"1008302-53-キキョウ" = "私は他の仕事があるから手伝えないけど。"
"1008302-54-キキョウ" = "……仕事が終わったら自分で直そうと思ってたのに、あんたが勝手に言い出したんだし。"
"1008302-55-キキョウ" = "じゃあ、そういうことだから。#n工具なら好きに使っていいよ。"
"1008302-56" = "[s] \"分かった、任せて！\""
"1008302-57-キキョウ" = "（理解できない）"
"1008302-58-キキョウ" = "（生徒が困っているなら助けるのが当たり前、なんて……）"
"1008302-59-キキョウ" = "（どうせ、口先だけでしょ）"
"1008302-60-キキョウ" = "（見て見ぬふりができないなんて言葉も、保身のためだろうし）"
"1008302-61-キキョウ" = "（ずっと放置されてきた建物が、簡単に直るわけないのに）"
"1008302-62-キキョウ" = "……ふん。"
"1008302-63-キキョウ" = "どうせすぐに音を上げるはず。"
"1008302-64" = "（そうして修理を始めてから5時間が経過し……）"
"1008302-65" = "[ns] \"床の応急処置は済んだから、次は天井だね。\""
"1008302-66-キキョウ" = "……ちょっと待って、まだ続けるの？"
"1008302-67" = "[s] \"うん？まだ天井は終わってないよ？\""
"1008302-68-キキョウ" = "もうこんな遅い時間なのに？#nあんたって、実は暇なの？"
"1008302-69-キキョウ" = "たしかに、修繕を手伝うとは言ったけど……"
"1008302-70-キキョウ" = "あと3時間で終わらせるから大丈夫？"
"1008302-71-キキョウ" = "……本当、呆れた。"
"1008302-72-キキョウ" = "…………。"
"1008302-73-キキョウ" = "……分かった。"
"1008302-74-キキョウ" = "……ハシゴくらいなら、押さえておいてあげるから。"
"1008302-75-キキョウ" = "必要な道具があれば言って。下まで降りるのも大変でしょ。"
"1008302-76" = "[s] \"仕事は大丈夫なの？\""
"1008302-77-キキョウ" = "……私を誰だと思ってるの？もう終わってる。"
"1008302-78-キキョウ" = "それに……あんた一人だと時間かかるでしょ。"
"1008302-79-キキョウ" = "……だから、私も手伝う。"
"1008302-80" = "[s] \"うん、ありがとう。\""
"1008302-81-キキョウ" = "……ふん。"
"1008302-82" = "[ns] \"よし、これで大丈夫そうだね。お疲れ様、キキョウ。\""
"1008302-83-キキョウ" = "……あんたこそ、お疲れ様。"
"1008302-84-キキョウ" = "本当に……今日だけで全部直しちゃうなんて……"
"1008302-85-キキョウ" = "……私の負け。"
"1008302-86" = "[s] \"そう言われると、ちょっと恥ずかしいかな。\""
"1008302-87" = "[ns] \"とりあえず、今度こそ用は済んだし帰るね。\""
"1008302-88" = "[ns] \"そんなに強く握られると、シワが……\""
"1008302-89-キキョウ" = "……あ。"
"1008302-90-キキョウ" = "……いや、その。"
"1008302-91-キキョウ" = "もう時間も遅い、し……"
"1008302-92-キキョウ" = "シャーレに戻る頃には、お店も閉まってるだろうから……"
"1008302-93-キキョウ" = "……だから、今日のお礼に夕食くらい……"
"1008302-94-キキョウ" = "……私が作ってあげる。"
"1008302-95-キキョウ" = "それだけ。"
"1008302-96-キキョウ" = "本当は相応の代価を支払うべきだし、急に夕食に誘われたところで迷惑かもしれないけど――"
"1008302-97" = "[ns] \"キキョウの手料理！！！！！\""
"1008302-98-キキョウ" = "……誘った私が言うのも何だけど、そこまで嬉しいもの？"
"1008302-99-キキョウ" = "さっきから思っていたけど、あんたって本当に……"
"1008302-100-キキョウ" = "……変な人。"
"1008302-101" = "[s] \"……え！？だって、キキョウの手料理が食べられるんだよ？\""
"1008302-102-キキョウ" = "……分かったから。"
"1008302-103-キキョウ" = "手でも洗って待ってて。"
"1008302-104-キキョウ" = "腕によりをかけて作ってあげる。"
"1008302-105" = "（その後、他愛もない話をしながらキキョウと食卓を囲んだ）"
