[translation]
"31080-1" = "第8話;第1次特別学力試験"
"31080-2" = "（あっ、これ、補習授業でやったところです……！）"
"31080-3" = "（先生に解説していただいた内容や、みんなで勉強した問題が、ほとんどそのまま……！）"
"31080-4" = "（それに、難易度としては初級……いえ、基礎のレベル！）"
"31080-5" = "（これまで色々と怖いことを言われてしまいましたが、もしかしてこれは、私たちへの救済措置ということでしょうか……！？）"
"31080-6" = "こ、これは……え、えぇっと……。"
"31080-7" = "ふふっ……。"
"31080-8" = "……ふむ。"
"31080-9-ヒフミ" = "（ですが油断は禁物……！みなさん、最後まで気を抜かずに、笑顔でこの補習授業部を卒業しましょうね！）"
"31080-10" = "[ns] 試験の結果が届いた。"
"31080-11-ヒフミ" = "み、みなさんお疲れ様でした……！"
"31080-12-ヒフミ" = "えっと、100点満点で60点以上でしたら合格だそうです！高得点は取れなくても、取り合えずそのラインだけ超えられれば大丈夫です。"
"31080-13-ヒフミ" = "それに内容も結構簡単でしたし……では、結果発表と行きましょう！"
"31080-14-ヒフミ" = "先生、お願いします！"
"31080-15" = "[s] 結果を発表する。"
"31080-16" = "ヒフミ：72点"
"31080-17" = "結果――合格"
"31080-18-ヒフミ" = "あ、ありがとうございます！何だか無難な点数ですが、良かったです！では、次に……"
"31080-19" = "アズサ：32点"
"31080-20" = "結果――不合格"
"31080-21-ヒフミ" = "……はいぃっ！？"
"31080-22-アズサ" = "ちっ、紙一重だったか。"
"31080-23-ヒフミ" = "……ま、待ってください！「紙一重」っていう点数じゃないですよ！？結構足りてないですよ！？"
"31080-24" = "コハル：11点"
"31080-25" = "結果――不合格"
"31080-26-コハル" = "！？"
"31080-27-ヒフミ" = "コハルちゃんんんんっ！？ち、力を隠してたんじゃないんですか！？今回はちゃんと1年生用の試験を受けたんですよね！？ま、まさかまた2年生用の……いえその点数、3年生用の試験を受けたんですか！？"
"31080-28-コハル" = "やっ、その……！か、かなり難しかったし……。"
"31080-29-ヒフミ" = "すっごく簡単でしたよ！？小テストみたいなレベルでしたよ！？"
"31080-30" = "あらあら……。"
"31080-31-ヒフミ" = "うぅ……合格したのは私とハナコちゃんだけ、ということでしょうか……となるとまた次の、二次試験を受けないと……。"
"31080-32" = "ハナコ：2点"
"31080-33" = "結果――不合格"
"31080-34-ヒフミ" = "2点！！？！？！？！？"
"31080-35-ヒフミ" = "2点、2点ですか！？20点ではなく！？いえ、20点でもダメなのですが……！むしろ何が正解だったんですか！？と言いますか待ってください、ハナコちゃんものすごく勉強ができる感じでしたよね！？"
"31080-36-ハナコ" = "確かに私、そういう雰囲気あるみたいですね。まあ成績は別なのですが。"
"31080-37-ヒフミ" = "雰囲気！？雰囲気だけだったんですか！？成績とは別ってどういうことですかっ！？"
"31080-38-ヒフミ" = "う……。"
"31080-39-ヒフミ" = "あうぅ……。"
"31080-40" = "[ns] \"ヒフミ！しっかり……！\""
"31080-41" = "第1次特別学力試験、結果――"
"31080-42" = "ハナコ――[FF6666]不合格[-]"
"31080-43" = "アズサ――[FF6666]不合格[-]"
"31080-44" = "コハル――[FF6666]不合格[-]"
"31080-45" = "ヒフミ―――[007eff]合格[-]"
"31080-46" = "補習授業部の合宿が決定した！"
"31080-47" = "次回;水面下に揺らめく影"
