[translation]
"31100-1" = "第10話;合宿、スタート！"
"31100-2" = "トリニティの別館「合宿所」"
"31100-3-ハナコ" = "ようやく着きましたね、ここが私たちの……"
"31100-4-ヒフミ" = "はい、合宿の場所です。ようやく着きましたね、ふぅ……。"
"31100-5-ハナコ" = "しばらく使われていない別館の建物と聞いたので、冷たい床で裸になって寝ないといけないのかと思ってましたが……。"
"31100-6-ハナコ" = "広いですし、きちんとしてますし、可愛いベッドもあって何よりです。"
"31100-7-ハナコ" = "これならみんなで寝られそうですね、裸で♡"
"31100-8-コハル" = "さっきから何でちょいちょい「裸」を強調するの！？それにベッドの数もちゃんとあるんだから、みんなで寝る必要無いでしょ！？"
"31100-9-ハナコ" = "せっかくの合宿ですし、そういうお勉強も必要ではないでしょうか？"
"31100-10-コハル" = "ダメ！エッチなのは禁止！死刑！！"
"31100-11-コハル" = "まあ今はまだ明るいですし、そういうことにしておきましょう。夜は長いですからね……♡"
"31100-12-ハナコ" = "えっ、は、ど、どういう意味！？！！？"
"31100-13-ヒフミ" = "その、これから一週間寝食と勉強を共にするので、みなさん仲良く……"
"31100-14-ヒフミ" = "って、あれ？アズサちゃんは……？"
"31100-15-ハナコ" = "あら、先ほどまでは一緒にいたのですが……。"
"31100-16-アズサ" = "偵察完了だ。"
"31100-17-ヒフミ" = "て、偵察……？"
"31100-18-アズサ" = "トリニティの本校舎からはかなり離れてるし、流石に狙撃の危険は無さそう。"
"31100-19-アズサ" = "外への入口が二つだけというところも気に入った。"
"31100-20-アズサ" = "いざという時は片方の入り口を塞いで、襲撃者たちを1階の体育館に誘導した上での殲滅戦が有効になるかな。"
"31100-21-アズサ" = "まあ他に幾つかセキュリティ上の脆弱性も確認できたけど、改修すれば問題無い範囲だ。"
"31100-22-ヒフミ" = "え、えっと……。"
"31100-23-アズサ" = "それから、ここが兵舎……いや、居住区か。……綺麗だな。"
"31100-24-アズサ" = "こんな施設を使わずに放置していたなんて……無駄遣いも良いところだ。"
"31100-25-ヒフミ" = "あの、アズサちゃん……私たちはここへ戦いに来たのではなく、勉強をしに来たんですよ……？"
"31100-26-アズサ" = "うん、分かってる。一週間の集中訓練だろう？外出禁止、自由時間は皆無、24時間一挙手一投足まで油断することは許されないハードなトレーニング。"
"31100-27-ヒフミ" = "そ、そこまででは無いと思いますが……。"
"31100-28-アズサ" = "きちんと準備もしてきた。体操着や細かい着替え、衛生面の歯ブラシや歯磨き粉、石鹸、非常食、毛布、水筒……"
"31100-29-ハナコ" = "さすがはアズサちゃん、用意周到ですね。"
"31100-30-アズサ" = "当然だ。徹底した準備こそ成功への糸口。"
"31100-31-ハナコ" = "うふふっ。みんなで一緒に食欲を満たし、睡眠欲を満たし、そしてみんなが欲する目標へと向かって脇目も振らず手を動かす……良いですね、合宿。"
"31100-32" = "……。"
"31100-33-アズサ" = "……うん、そうだね。"
"31100-34-アズサ" = "あ、でも任務は確実に遂行する。きちんと勉強をして、第2次特別学力試験にはどうにか合格する。その目標のためにここに来たんだ。"
"31100-35-アズサ" = "……迷惑は、かけたくない。"
"31100-36-ヒフミ" = "アズサちゃん……。"
"31100-37-アズサ" = "大丈夫、万が一の敵襲に備えて対人地雷とクレイモアも用意してきた。あとは[ruby=IED]即席爆発装置[/ruby]の材料になりそうなもの一式と、対戦車地雷も多少――"
"31100-38-ヒフミ" = "あ、アズサちゃん！ですからそういうのは……！"
"31100-39-ヒフミ" = "……というわけで、あらためて。"
"31100-40-ヒフミ" = "ナギサ様から言われた通りです。第1次特別学力試験には残念ながら落ちてしまったので……"
"31100-41-ヒフミ" = "この別館で合宿をすることになりました。私たちは2次試験までの一週間、ここに滞在することになります。"
"31100-42-ヒフミ" = "長い間放置されていたそうですが、少しお掃除すれば全然使えそうですし、体育館やシャワー室なども充実しているようですし……。"
"31100-43-アズサ" = "うん、そういえば外にプールもあった。しばらく使われていないようだったけれど。"
"31100-44-ヒフミ" = "あ、そうだったんですね。あと、ここはトリニティの本校舎からも頑張れば歩ける距離ですし、地下に食堂設備のようなものもありましたから、特にお腹を空かせる心配もなさそうです。"
"31100-45-ヒフミ" = "それに私たちがここにいる間、[USERNAME]先生もずっと一緒にいてくれる予定ですので、何かあっても大丈夫だと思います！"
"31100-46" = "[s] \"うん、任せて。\""
"31100-47-ヒフミ" = "ありがとうございます。えっと、通路を挟んで向かい側にもお部屋があるのですが、先生は――"
"31100-48-コハル" = "ダメっ、絶対ダメ！！同衾とかエッチじゃん！！！！死刑！！！"
"31100-49-ハナコ" = "えっと、コハルちゃん？私、まだ何も言っていませんが……？"
"31100-50-コハル" = "何を言い出すのかだいたい分かるわよ！！ダメったらダメ！そういうことはさせないんだから！"
"31100-51-ハナコ" = "コハルちゃんは厳しいですねぇ……。"
"31100-52-アズサ" = "私は先生もここで一向に構わないけど？ベッドも余ってるし、無駄に部屋をいくつも使うこともない。"
"31100-53" = "[s] \"みんなで交流を深めておいて。何かあったら呼んでくれれば。\""
"31100-54-ヒフミ" = "で、では一旦そういうことで。そうしたら、荷物を片付けて早速お勉強を……"
"31100-55-ハナコ" = "あら、でもその前にやることがあると思いませんか？ヒフミちゃん？"
"31100-56-ヒフミ" = "えっ……？"
"31100-57-アズサ" = "なるほど、敵襲を想定してトラップの設置を？"
"31100-58-ハナコ" = "いえ、そうではなく……"
"31100-59-ハナコ" = "お掃除、ですよ♡"
"31100-60-ヒフミ" = "……お、お掃除、ですか？"
"31100-61-ハナコ" = "はい。管理されていた建物とはいえ、長い間使われていなかったこともあって、埃なども多いように見えませんか？"
"31100-62-ハナコ" = "このままここで過ごすというのも健康に良くなさそうですし、今日はまずお掃除から始めて、気持ち良い環境で勉強を始めるというのはいかがでしょう？"
"31100-63-ヒフミ" = "なるほど、確かにそうですね。まずは身の回りの整理整頓から始めるのは定石ですし、そうでないと途中で気になってしまいますし……。"
"31100-64" = "うん、衛生面は大切。実際、戦場でもすごく士気に関わりやすい部分だ。"
"31100-65-コハル" = "お、お掃除……？えっと、まあ、普通のお掃除なら……。"
"31100-66-ヒフミ" = "はい、ハナコちゃんの言う通りかもしれません。やる気が空回りしても困りますし……。"
"31100-67-ヒフミ" = "私たちがするのは一夜漬けではなく、きちんと用意された期間の中での試験勉強……つまりは長距離走のように、順番やペース、作戦も考えないとです。"
"31100-68-ヒフミ" = "それではまず、大掃除から始めるとしましょう！"
"31100-69" = "[s] \"よし、頑張ろう！\""
"31100-70-ヒフミ" = "それでは汚れても良い服に着替えてから、10分後に建物の前に集合としましょう！"
"31100-71-ヒフミ" = "分かった。"
"31100-72-ヒフミ" = "はい♪"
"31100-73-コハル" = "よ、汚れても良い服……た、体操着で良い……？"
"31100-74" = "10分後……"
"31100-75" = "合宿所・正門"
"31100-76-ヒフミ" = "先生、お待たせしました！"
"31100-77" = "[s1] \"おお、体操着姿。\"\n[s2] \"掃除って感じがするね。\""
"31100-78-ヒフミ" = "はい、服装から入るのも大事ですからね。体操着の方が動きやすいですし、汚れた時に洗濯もしやすいですし。"
"31100-79-ヒフミ" = "はい、服装から入るのも大事ですからね。体操着の方が動きやすいですし、汚れた時に洗濯もしやすいですし。"
"31100-80-ヒフミ" = "……で、私は何をやれば良いの？"
"31100-81-コハル" = "あっ、コハルちゃん早かったですね。"
"31100-82-コハル" = "お待たせ。"
"31100-83-コハル" = "アズサちゃんも――って、どうして銃を……？"
"31100-84-コハル" = "肌身離さず持っていないと、銃の意味が無い。襲撃はいつ来るか分からないものだ。"
"31100-85-コハル" = "いえ、それはその、何と言いますか、その通りかもしれませんが……。"
"31100-86-ハナコ" = "お待たせしました、みなさん早かったですね？"
"31100-87-コハル" = "アウトーーーーーー！！！"
"31100-88-ハナコ" = "あら……？"
"31100-89-コハル" = "何で掃除するのに水着なの！？バカなの！？バカなんでしょ！？バーカ！！"
"31100-90-ハナコ" = "ですが動きやすいですし、何かで汚されても大丈夫ですし、洗い流すのも簡単で――"
"31100-91-コハル" = "そういう問題じゃないでしょ！？水着はプールで着るものなの！っていうか、だっ、誰かに見られたらどうするの！？"
"31100-92-ハナコ" = "誰かも何も、ここには私たち以外いませんよ……？"
"31100-93-コハル" = "と、とにかくダメ！アウトったらアウト！あんたはもう水着の着用禁止！"
"31100-94-ハナコ" = "あら……それはそれで、まあ……。"
"31100-95-ヒフミ" = "あうぅ……。"
"31100-96" = "その後ハナコは、きちんと体操着に着替えて出てきた。"
"31100-97" = "次回;大掃除！"
