[translation]
"70007020-1" = "出会いは突然に（２）"
"70007020-2-アケミ" = "しち！はち……！"
"70007020-3-スミレ" = "（100回を超えてもフォームが乱れません。まるで、軽いランニングでもしているかのよう……）"
"70007020-4-アケミ" = "きゅう！じゅう！さて……これで40回目、でしたかしら？"
"70007020-5-スミレ" = "（よ、よんじゅう！？どう見ても100回はやっています！）"
"70007020-6-アケミ" = "んー……まだ負荷が足りていませんわ。30回としておきましょう……いち！に！"
"70007020-7-アケミ" = "あ、あのっ……！"
"70007020-8-アケミ" = "あら、どうなさいましたの？"
"70007020-9-スミレ" = "（思わず声をかけてしまいました……！）"
"70007020-10-スミレ" = "い、いえ！なんでもありません。トレーニングの邪魔をしてしまい、失礼しました。"
"70007020-11-アケミ" = "うふふ、面白いお方。"
"70007020-12-スミレ" = "……"
"70007020-13-アケミ" = "はち！きゅう、これで20回ですわ！"
"70007020-14-スミレ" = "（さっきは30回だったはず！あきらかに減ってますよね！？）"
"70007020-15-アケミ" = "これで……100回！ふう、爽快ですわね！"
"70007020-16-スミレ" = "（正確には785回です……！途中で気を失うかと思いました……！）"
"70007020-17-スミレ" = "（筋肉だけでなく、体力も鋼のようですね……）"
"70007020-18-アケミ" = "次はランニングマシンで足をほぐしますわ！"
"70007020-19-スミレ" = "（ランニングマシンの傾斜をこれほど高く！？……ほぼ垂直の壁です！）"
"70007020-20-アケミ" = "続いてローイングマシン、行きますわ！……ふんっ！"
"70007020-21-スミレ" = "（この速さで漕いだら、もはやモーターボートです！）"
"70007020-22-アケミ" = "次はレッグプレスで下半身を！"
"70007020-23-アケミ" = "では次は……！"
"70007020-24-スミレ" = "（ついていくだけで、もう限界です……！）"
"70007020-25-スミレ" = "（この感覚……私が長い間忘れていた「疲労感」ですね）"
"70007020-26-スミレ" = "（それでも、損傷した筋繊維の奥から、マグマのように情熱が湧いてきます！）"
"70007020-27-ジムのオーナー" = "あ、あの、お客様がた！"
"70007020-28-ジムのオーナー" = "もう11時です！そろそろ閉店時間となりますので、お片付けをお願いします！"
"70007020-29-アケミ" = "あら、もうそんなお時間なのですね。てっきり、まだお昼頃かと思いました。"
"70007020-30-スミレ" = "11時……？まだまだ……いけます……。"
"70007020-31-アケミ" = "見ているこちらが筋肉痛になりそうです！ どうかお引き取りください……！"
"70007020-32-アケミ" = "全ての運動には終わりがあるもの……少し名残惜しいですが、今日はお開きといたしましょうか。うふふ。"
"70007020-33-アケミ" = "それでは、私はこれにて失礼いたしますわ。"
"70007020-34-スミレ" = "うぅ……"
"70007020-35-スミレ" = "全身を洗濯機で回されたような気分です……。"
"70007020-36-アケミ" = "あの……"
"70007020-37-スミレ" = "はいっ！？"
"70007020-38-スミレ" = "こうして直接お声をかけるのは、少々照れますわね……。"
"70007020-39-スミレ" = "今日、トレーニングを共にすることができたこと、とても嬉しく思いますわ。"
"70007020-40-スミレ" = "実は、朝からあなたの視線を感じていましたの。"
"70007020-41-スミレ" = "品格と清らかさを尊びつつ、さらなる力を追求するその熱いまなざし……"
"70007020-42-スミレ" = "直接肌で感じられて、とても光栄でしたわ。"
"70007020-43-スミレ" = "申し訳ありません。つい、見惚れてしまいまして……。"
"70007020-44-スミレ" = "まあ、謙虚でもいらっしゃる！この荒れた世の中で、これほど高貴な方にお会いできるだなんて！"
"70007020-45-スミレ" = "そ、そんな……恐縮です！"
"70007020-46-スミレ" = "うふふ。はにかむ姿も可愛らしいですわね。"
"70007020-47-スミレ" = "まあ、もうこんな時間でしたのね！"
"70007020-48-スミレ" = "この後、仲間からヘルメット団を「3分割」してほしいと頼まれておりますの……。"
"70007020-49-スミレ" = "名残惜しいですが、これにて失礼させていただきますわ。"
"70007020-50-スミレ" = "3分割……曜日ごとに鍛える部位を分ける、定番のトレーニング法ですね。"
"70007020-51-スミレ" = "こんな遅くまで他の方のトレーニングを気にかけるなんて、本当に真摯な方です。"
"70007020-52-スミレ" = "……？"
"70007020-53-スミレ" = "あの、もしご迷惑でなければ、お名前をお伺いしてもよろしいでしょうか？"
"70007020-54-スミレ" = "私はミレニアムのトレーニング部部長、[ruby=おとはな]乙花[/ruby]スミレと申します。"
"70007020-55-スミレ" = "まあ、私ったらとんだ失礼を。あらためて、ご挨拶させていただきます。"
"70007020-56-スミレ" = "私は[ruby=くりはま]栗浜[/ruby]家のアケミと申します。[ruby=おとはな]乙花[/ruby]スミレさん。今日はお会いできてとても光栄でしたわ。"
"70007020-57-スミレ" = "あらあら、本当にせっかちですこと。"
"70007020-58-スミレ" = "それでは、名残惜しいですが……"
"70007020-59-スミレ" = "有酸素運動メニューをご一緒できたこと、心より感謝します。"
"70007020-60-スミレ" = "またこうしてお会いできることを願っておりますわ！"
"70007020-61-スミレ" = "あれほどまでに、身も心も鍛え上げた方とトレーニングができるなんて……"
"70007020-62-スミレ" = "予期せぬ工事から遠くのジムまで足を運んだことで、"
"70007020-63-スミレ" = "素晴らしい出会いがありました……"
"70007020-64-スミレ" = "？"
"70007020-65-アケミ" = "それでは、名残惜しいですが……"
"70007020-66-スミレ" = "あの方、まさか……！"
"70007020-67-アケミ" = "有酸素運動メニューをご一緒できたこと、心より感謝します。"
"70007020-68-スミレ" = "17時間ものウェイトトレーニングが……有酸素運動だったんですか……！？"
"70007020-69-スミレ" = "……これが、先日私が経験した奇妙な出来事です。"
"70007020-70-スミレ" = "恐ろしくもあり、眩しくもあり……記憶に残る一日となりました。"
"70007020-71-レイ" = "……怪談か何かですか？"
"70007020-72-レイ" = "すごいですね、先輩を疲れさせるなんて。"
"70007020-73-スミレ" = "疲れてなどおりません！ "
"70007020-74-スミレ" = "ただ、いつもより負荷が高かった。それだけですよレイさん。 "
"70007020-75-レイ" = "はいはい。それで、その方のお名前は？ミレニアムの生徒ですか？"
"70007020-76-スミレ" = "[ruby=くりはま]栗浜[/ruby]アケミさんと名乗っていました。"
"70007020-77-レイ" = "[ruby=くりはま]栗浜[/ruby]……アケミ……"
"70007020-78-レイ" = "ええっ！？ "
"70007020-79-レイ" = "……野球選手にはいませんね。 "
"70007020-80-スミレ" = "一度も野球選手だとは言っておりませんが……"
"70007020-81-レイ" = "友達になったなら、連絡先とかは交換してないんです？"
"70007020-82-スミレ" = "レイさん、私とあの方は同じ道を往く「仲間」なのです。もちろん、私には学ばなければならないことも多いですが……。"
"70007020-83-スミレ" = "同じ道を歩む以上、またどこかで必ず出会う。そういう運命なんですよ。"
"70007020-84-スミレ" = "よければ、レイさんも一緒にどうですか？あの方と私の力が合わせれば、レイさんをより優れた野球選手に鍛え上げられるかと。"
"70007020-85-レイ" = "せ、先輩？さっきまで練習してきたばかりですけど……？"
"70007020-86-レイ" = "先輩……？"
"70007020-87-レイ" = "スミレ先輩ーー！"
"70007020-88" = "出会いは突然に"
