[translation]
"10013010-1" = "第1話;やるべきことは一つ！"
"10013010-2-アヤネ" = "みんな、ストッープ！止まってくださーい！"
"10013010-3-ホシノ" = "あれ……アヤネちゃん？"
"10013010-4-ノノミ" = "ちょっ、なんでここにいるの！？"
"10013010-5-シロコ" = "悪党に足止めされてるのかな。"
"10013010-6-ノノミ" = "あら、それは大変ですね～。"
"10013010-7-アヤネ" = "ち、違います！そうじゃなくて……"
"10013010-8-シズコ" = "あの……もしかして、先生のお知り合いですか……？"
"10013010-9" = "[s] \"た、たぶん……？\""
"10013010-10-イズナ" = "覆面を被った見るからに怪しい方ともお知り合いだなんて……さすが主殿です！"
"10013010-11-イズナ" = "なっ！？誰が怪しいって！！"
"10013010-12" = "[s] \"とりあえず、一旦状況を整理しようか。\""
"10013010-13" = "（こうして互いに自己紹介をした）"
"10013010-14-シズコ" = "えっと……つまり、この人たちはアビドス高校の生徒ってこと？"
"10013010-15-シズコ" = "その覆面ってお祭り用品か何かですか？#nそれとも、アビドスにしかない独自の文化とか！？"
"10013010-16-シズコ" = "ゲヘナでは仮面をつけて参加するお祭りがあるらしいですが、アビドスは覆面なんですね！実にユニークです……ね、社長？"
"10013010-17-アヤネ" = "あはは……別にそういうわけではないんですけど……"
"10013010-18-シズコ" = "だから、何度も言ってるけど私は委員長！社長じゃないわよ！"
"10013010-19-シズコ" = "それで、どうしてアビドスが襲ってくるわけ？私たちが何したって言うのよ！"
"10013010-20-シズコ" = "それはこっちの台詞よ！"
"10013010-21-セリカ" = "お祭り運営委員会ってことは、今回の「リゾート狩り」を起こした主犯でしょ？#nそれなのに、どうして先生はそんなやつらと一緒に――"
"10013010-22-セリカ" = "だから！それは誤解だって――"
"10013010-23-イズナ" = "あの……ひとまず落ち着いて……。"
"10013010-24-ミモリ" = "あわ、あわわわ……い、イズナは……一体どうすれば……。"
"10013010-25-チセ" = "あっ……ニヤ部長から電話だよ、先生。"
"10013010-26-ニヤ" = "にゃはは～。ハロハロー、皆さん。お元気ですか～？"
"10013010-27-チセ" = "私が席を外している間に、何やらトラブルの気配がプンプンしますねぇ～。#nそれは困るなぁ～。面白くならないか心配しとるんですけど。"
"10013010-28" = "[s] \"心配してるようには見えないんだけど……。\""
"10013010-29-ニヤ" = "ふむ。雰囲気から察するに、既に一悶着あったように見えますが～？"
"10013010-30-ニヤ" = "……大事な時にちっとも顔を見せないくせによく言うわよ。#nそれで、陰陽部のトップが何の用？"
"10013010-31-ニヤ" = "うふふっ、本題の前に棘のある言葉で盛り上げちゃうとこ、気に入りましたわぁ。"
"10013010-32-ニヤ" = "とまぁ雑談はさておき……"
"10013010-33-シズコ" = "――実は先生がそちらへ出向いている間に、あれこれ調べてみたんですけどね。"
"10013010-34-ニヤ" = "[ruby=かわわ]河和[/ruby]シズコさん、あなたが今巻き込まれてる騒動の大まかな概要が掴めましたよ～♪"
"10013010-35-シズコ" = "私が巻き込まれている……騒動……？"
"10013010-36-シズコ" = "最近、百夜堂で大きな事業に手を出してましたよね？"
"10013010-37-シズコ" = "……！なんでそれを知ってるのよ！？"
"10013010-38" = "[s] \"大きな事業？シズコが？\""
"10013010-39-シズコ" = "先日、お祭り運営委員会が百鬼夜行の各サークルから調達した資金で、あるものを購入したことが判明しました。"
"10013010-40" = "[s] \"投資……。\""
"10013010-41-ニヤ" = "ただ、ここで問題なのは……シズコさんが買ったものが「架空の商品」だったということです。"
"10013010-42-シズコ" = "架空って……どういうこと？"
"10013010-43-ニヤ" = "資料には、最近お祭り運営委員会が「ロスト・パラダイス・リゾートの使用権」を購入したと書いておりますけど……"
"10013010-44-ニヤ" = "そもそも、この「ロスト・パラダイス・リゾート」は20年ほど前に倒産した会社の名前なんです。"
"10013010-45-シズコ" = "えっ……？"
"10013010-46-ニヤ" = "さらに、この正体不明の使用権……お祭り運営委員会だけでなく他の人も手にしているという状況……"
"10013010-47-ニヤ" = "おそらく、アビドスの皆さんもそうだったのではないですか？"
"10013010-48-セリカ" = "そ、そうよ！私たちも、商品が当たってここに……"
"10013010-49-シズコ" = "本当に私たちだけじゃなくて、アビドスも使用権を……？けど、そんなことって――"
"10013010-50-シズコ" = "……ここを見てください。私たちの契約書に、お祭り運営委員会の名前が……"
"10013010-51-シズコ" = "なになに……「ロスト・パラダイス・リゾートの投資及び経営統括：百鬼夜行連合学院 お祭り運営委員会」……？"
"10013010-52-シズコ" = "ちょ、ちょっと待って！なんで他の人が持ってる書類に私たちの名前が！？#nこれ、どう見てもニセモノ――"
"10013010-53-シズコ" = "って、あれ！？なんでうちの委員会のハンコが押されてるの！？#nえ、ええっ！？"
"10013010-54-ニヤ" = "つまり、あなたは騙されたんですよ、シズコさん。"
"10013010-55-ニヤ" = "お祭り運営委員会が購入した使用権が他のところにもばら撒かれ、不当条項と解釈せざるを得ない文章によって――"
"10013010-56" = "[s] \"「リゾート狩り」が起きてしまった……？\""
"10013010-57-ニヤ" = "つかぬことを聞きますが、その使用権……どこで買ったものなんです？"
"10013010-58-シズコ" = "それは……"
"10013010-59-シズコ" = "あとはここにハンコを……よし、これでいいのよね？"
"10013010-60-銀行職員" = "ええ！これで、お祭り運営委員会の基金は私ども「オクトパスバンク」が管理する特別商品に投資されました！"
"10013010-61-銀行職員" = "お客様は今夏、複合リゾート施設「ロスト・パラダイス」にて海の家を経営されたいとのことでしたね！素晴らしい計画だと思います！"
"10013010-62-銀行職員" = "近々、リゾート施設の運営責任者も募集いたしますので、そちらも何卒よろしくお願いいたします。"
"10013010-63-シズコ" = "どこに問題があるの？ちゃんと契約書は隅から隅まで読んだわよ！？"
"10013010-64-シズコ" = "その契約書自体がお遊びだった、ってことですねぇ。"
"10013010-65-ニヤ" = "こちらで調査した情報によると、そもそもオクトパスバンク自体に使用権を売る権利があるのかすら怪しいと申しますか……"
"10013010-66-シズコ" = "か、仮にそうだったとしても架空の商品なら、書類自体が違法って事でしょ？#nそれなら、このまま帰って契約を取り消せば……！"
"10013010-67-ホシノ" = "ちょっと待って――今、オクトパスバンクって言った？"
"10013010-68-シズコ" = "えっ？う、うん……"
"10013010-69-アヤネ" = "あー、そっかぁ……だとすると、そう簡単に事は進まないと思う。"
"10013010-70" = "[s] \"ホシノ、どういう意味？\""
"10013010-71-シロコ" = "……"
"10013010-72-ノノミ" = "実は、そのオクトパスバンクという社名は……"
"10013010-73-アヤネ" = "……「カイザーローン」のダミー会社の一つです。"
"10013010-74" = "[s] \"カイザーローン！？\""
"10013010-75-アヤネ" = "はい。今、お話していたやり口は私たちもよく知っています……間違いなくカイザーローンの手法です。"
"10013010-76-シロコ" = "うん……おそらく、ここで起きている事件の背後にはカイザーコーポレーションがいる。"
"10013010-77-セリカ" = "あいつら全ッ然手口が変わってないじゃん！#n私ら、カイザーに何度も騙されたんだよ！"
"10013010-78-ノノミ" = "まさか、こんなところで出くわすなんて……"
"10013010-79-ホシノ" = "なるほどねぇ……そっか、あいつらが……"
"10013010-80-ニヤ" = "おそらく、カイザーコーポレーションは最初からお祭り運営委員会を狙っていたんでしょうねぇ。"
"10013010-81-ニヤ" = "お祭り運営委員会が持っている百鬼夜行連合学院の学園祭開催権限は、向こうにとっては美味しい獲物でしょうし――"
"10013010-82" = "[s] \"アビドスの時みたいに、今度は百鬼夜行が……。\""
"10013010-83-ニヤ" = "いやぁ～、やられちゃいましたね、シズコさん♪"
"10013010-84-ニヤ" = "うぐぅ……！"
"10013010-85-ニヤ" = "でも、ちょっと意外です。シズコさんらしくないと言いますかぁ……"
"10013010-86-ニヤ" = "なんでそんな胡散臭いものに投資なんてしたんです？"
"10013010-87-ニヤ" = "まさか――お金が必要だった、とか？"
"10013010-88-シズコ" = "それは……"
"10013010-89-ウミカ" = "違います！社長は――"
"10013010-90-シズコ" = "……いや、いいよ、ウミカ。ニヤの言う通りだし。"
"10013010-91" = "[s] \"シズコ？\""
"10013010-92-シズコ" = "……認めたくはないけど、もう起きちゃったことは仕方ないから。"
"10013010-93-シズコ" = "お金が必要だから事業に投資して……結局はこんなことになっちゃった。"
"10013010-94-シズコ" = "本当にそれだけのこと。言い訳をするつもりもないですし。"
"10013010-95-ウミカ" = "社長……"
"10013010-96-シズコ" = "私のせいでこうなったのは事実だからね。だから――みんな、ごめんなさい。"
"10013010-97-セリカ" = "あ、いや、その……まあ、謝ってくれるなら……"
"10013010-98-セリカ" = "過ぎたことを責めても仕方ないよ、セリカ。"
"10013010-99-セリカ" = "真っ先に走っていった先輩がそれ言う！？"
"10013010-100" = "[s] \"問題はこれからどうするか、だね。\""
"10013010-101-ニヤ" = "ふむ……そうですねぇ、ひとまず学院に帰ってきてください、シズコさん。"
"10013010-102-ニヤ" = "……えっ？"
"10013010-103-ニヤ" = "外部勢力がお祭り運営委員会を狙ったということは、百鬼夜行連合学院への攻撃に他なりません。"
"10013010-104-シズコ" = "ですので、ここからは私たち陰陽部が引き継ぎます。向こうが汚い手を使うのなら、こちらも相応の対処をするまで。"
"10013010-105-ニヤ" = "というわけで、そちらはすぐにでも帰還を――"
"10013010-106-シズコ" = "それはできない。"
"10013010-107-ニヤ" = "……はい？"
"10013010-108-ニヤ" = "……どういうことですか？"
"10013010-109-ニヤ" = "たしかに、ここを離れたら問題は回避できるかもしれない。"
"10013010-110-ニヤ" = "ええ。ですから、まずは帰還し、状況を整理してから次の手を――"
"10013010-111-シズコ" = "でも、それじゃあ何も解決しないのよ。"
"10013010-112-ニヤ" = "……？"
"10013010-113-シズコ" = "もちろん、ニヤの言ってることも分かってるつもり。"
"10013010-114-ニヤ" = "でも、学院に帰った所で契約書に百夜堂の名前が残っている限り、どんどん百鬼夜行の名前が……ブランド価値が下がってしまう。"
"10013010-115" = "[s] \"それはかなり深刻だね……。\""
"10013010-116-シズコ" = "そうなんです！この件は、学院はもちろんの事、百鬼夜行の観光事業に対する信頼にも直結する問題なんです！"
"10013010-117-シズコ" = "だから、このまま黙って引き下がるわけにはいきません。私が直接解決します！"
"10013010-118-シズコ" = "つまり……ブランド価値が下がるのが嫌だから意地を張る、ということですか？"
"10013010-119-シズコ" = "そ、その言い方はないでしょ！"
"10013010-120-ニヤ" = "やれやれ、理解できませんねぇ。なんでそんなに苦労して回りくどいことを……"
"10013010-121-シズコ" = "それは、私がそうしたいからよ。"
"10013010-122-シズコ" = "それに、ブランド価値以外にも理由があるというか……"
"10013010-123-シズコ" = "と、とにかく！そういうことなの！"
"10013010-124-シズコ" = "もちろん、今回の件はあくまで私のミスで起きたことだから――"
"10013010-125-シズコ" = "私一人で対処するわ。だから、みんなは何も心配しないで……"
"10013010-126" = "[s] \"私たちも手伝うよ。\""
"10013010-127-シズコ" = "えっ……？いや、先生の手を借りなくても……"
"10013010-128-ミモリ" = "何を言ってるんですか、シズコちゃん。#n私たちはシズコちゃんを手伝うためにここに来たんですよ。"
"10013010-129-チセ" = "そうだよ～部長はケチだから、代わりに手伝ってあげる。"
"10013010-130-ニヤ" = "ちょっ、チセ！？"
"10013010-131-シズコ" = "みなさん……！"
"10013010-132-シズコ" = "もちろん、イズナもお手伝いしますよ！主殿が一緒なら、百人力です！"
"10013010-133-ニヤ" = "……一応聞きますけど、何か策はあるんです？"
"10013010-134-シズコ" = "彼女たちの話から、オクトパスバンクを問い詰めても無駄ってことは分かった。"
"10013010-135-シズコ" = "でも、ここで泣き寝入りしていても「リゾート狩り」が続くだけ……"
"10013010-136-シズコ" = "なら、発想を逆転させればいいのよ！"
"10013010-137-ウミカ" = "発想を逆転、ですか……？"
"10013010-138-シズコ" = "やることは単純明快。私たちが直接「リゾート狩り」を乗っ取るだけよ！"
"10013010-139-ホシノ" = "おー、大胆だねぇー。"
"10013010-140" = "[s] \"そんなことして大丈夫なの！？\""
"10013010-141-シズコ" = "もちろん、ただ奪おうってわけじゃないですよ！"
"10013010-142-シズコ" = "「リゾート使用権」の権利者が私たちの名前になっているということは、裏を返せば、他の契約者たちは私たちの権利を一部譲り受ける形で契約してるって事です。"
"10013010-143-シズコ" = "おそらく、あの時銀行員が話していた「リゾート施設の運営責任者」っていうのが、これに該当するんだと思います。"
"10013010-144-ノノミ" = "ふむふむ……たしかに、書面上ではそんな感じに書いてありますね～。"
"10013010-145-ノノミ" = "この運営責任者って、元々はあの廃墟を管理するのが役目だったってこと？"
"10013010-146-シズコ" = "おそらくそうですね……現在、この群島にいる問題児たちは、"
"10013010-147-シズコ" = "各々何らかの形でオクトパスバンクと契約を結んでいると見ていいでしょう。"
"10013010-148-シズコ" = "ですが、運営責任者は私……つまり、彼女らはこのリゾートを不法占拠しているとも言い換えられます。"
"10013010-149-シズコ" = "――そう、契約書の隙を突きます！"
"10013010-150-シズコ" = "私たちが「リゾート狩り」をし、問題児から契約書を回収する！#nいわば敵対的[ruby=合併・買収]M&A[/ruby]、というやつです！"
"10013010-151-シズコ" = "それに、このまま退くなんてもっての外ですからね。#nこのままでは私の[ruby=こけん]沽券[/ruby]に関わります！"
"10013010-152-シズコ" = "今こそ百夜堂の実力を見せてやりましょう！"
"10013010-153-シズコ" = "ロスト・パラダイス・リゾートの全てを吸収して、"
"10013010-154-シズコ" = "百夜堂楽園リゾートという名前に変えてやります！"
"10013010-155" = "[s] \"うん、一緒に頑張ろう！\""
"10013010-156-シズコ" = "……はい！"
"10013010-157-ホシノ" = "うへ～……それじゃあ私たちも、ちょっとだけ手を貸そうか～"
"10013010-158-ノノミ" = "はい！みんなでお手伝いしましょう～！"
"10013010-159-セリカ" = "まぁ……相手があのカイザーなら仕方ないわね。#nやられた分はきっちり返してやりたいし！"
"10013010-160-シズコ" = "みんな……"
"10013010-161-シズコ" = "ありがとう！それじゃ、まずは情報交換からしましょ！"
