[translation]
"10013065-1" = "イズナ流忍法！超強力シュート！です！"
"10013065-2-ニャテ・マサムニェ" = "ぐぅぅぅぅっ！？この力は……一体……！？"
"10013065-3-ニャテ・マサムニェ" = "イズナは、主殿に出会ったことでもっと強くなりました！"
"10013065-4-イズナ" = "主殿はイズナの夢を理解し、認めてくれた！"
"10013065-5-イズナ" = "そのおかげでイズナは一皮むけて成長したんです！"
"10013065-6-イズナ" = "なるほど……だから、水着姿なのか……！"
"10013065-7" = "[s] \"いや、それはちょっと違うけど！\""
"10013065-8-ニャテ・マサムニェ" = "ぐぁぁぁぁぁっ！！"
"10013065-9-シズコ" = "さあ、これで終わりよ！"
"10013065-10-イズナ" = "イズナたちの勝利です！"
"10013065-11-ニャテ・マサムニェ" = "な、なぜだぁぁぁ！！なぜ儂らが後れを取る！？"
"10013065-12-ニャテ・マサムニェ" = "以前とは何もかも違ったはずなのだ！！"
"10013065-13-ニャテ・マサムニェ" = "黒亀組だけでなく、カイザーPMCの兵力まで雇って備えていたというのに！！"
"10013065-14" = "[s] （カイザーPMC……？）"
"10013065-15-黒亀組の組員A" = "そのことなんですけど……#n実は昨日の夕方に来たお客さんの中に、キツネのお面を被ったやつがいまして……"
"10013065-16-黒亀組の組員B" = "そいつに椅子に座った分の料金を請求しようとしたんですよ。#nそしたら、いきなり襲いかかってきまして……"
"10013065-17-黒亀組の組員A" = "そのせいで、カイザーPMCから雇った兵力の大半を失っちゃいました……"
"10013065-18-黒亀組の組員A" = "なぜそれを早く言わん！？仕事において最も重要なのは報連相だろう！#nそんなことも知らんのか！？"
"10013065-19" = "[s1] \"何か……デジャヴのような……。\"\n[s2] \"キツネのお面を被ったお客さんって……。\""
"10013065-20-ニャテ・マサムニェ" = "さあ、ここまでよ！ニャン天丸！"
"10013065-21-ニャテ・マサムニェ" = "正義と忍者は常に勝つものです！ニンニン！"
"10013065-22-シズコ" = "うぐぐぐ……！……いや、そうか。なるほど……そうくるか。"
"10013065-23-シズコ" = "ふ……ふふふ……はははは！はははははははは！"
"10013065-24" = "[s] \"その笑い……切り札でもあるの？\""
"10013065-25-ウミカ" = "みんな、油断しないで！"
"10013065-26-シズコ" = "はい！なんたって相手は、あの百鬼夜行商店街の会長ですからね！"
"10013065-27-シズコ" = "（ごくり！）"
"10013065-28-ニャン天丸" = "あー、コホン。"
"10013065-29-ニャン天丸" = "シズコ君、おぬしの手腕にはいつも感心しているよ。"
"10013065-30-ニャン天丸" = "聞くところによると、この群島でフランチャイズ事業を展開しておるそうじゃないか。"
"10013065-31-ニャン天丸" = "ははは！それは実に良い姿勢だと思うぞ！そこで、どうかね？#nこのニャン天丸とも契約を結ぶというのは！"
"10013065-32-ニャン天丸" = "おぬしは金が必要なんじゃろう？"
"10013065-33-ニャン天丸" = "ならば、ちょうど儂の手元に黒亀組という兵力がいる。こいつを活用すれば、もっと効率よく事業が回せるぞ！"
"10013065-34-ニャン天丸" = "過ぎし日のわだかまりは全て水に流して、共に金を稼ごうじゃないか！"
"10013065-35-ニャン天丸" = "互いに手を取り合い、より広い世界へ羽ばたこう！"
"10013065-36-ニャン天丸" = "ええ、それは嬉しい申し出ね。"
"10013065-37-ニャン天丸" = "おぉ！さすがシズコ君！話がわかる！"
"10013065-38-ニャン天丸" = "おかげで迷わずにこいつをキメられるわ！"
"10013065-39-シズコ" = "寝言は寝て言えぇぇぇぇっ！#nシズコ[ruby=マジギレ]本気の[/ruby]看板娘パーーンチ！夏バージョン！！"
"10013065-40-シズコ" = "――ってな感じで、ここを管理していた勢力がバラバラに逃げちゃってね。#n少し人手を貸してほしいの。"
"10013065-41-カスミ" = "まあ、そういうことなら構わんよ。ちょうど手が空いてる子もいるしな。"
"10013065-42-シズコ" = "ありがとう。それじゃ、お願いね。"
"10013065-43-シズコ" = "くっそぉ、ニャン天丸め……ちょっと目を離した隙に逃げ出すなんて……"
"10013065-44-イズナ" = "イズナもびっくりしました！すごく逃げ足が速くて！#nあれはまるで忍者……じゃなくて、その……"
"10013065-45-チセ" = "……ムカデ？"
"10013065-46-ウミカ" = "たしかにそれっぽいですね！"
"10013065-47-ミモリ" = "あはは……"
"10013065-48" = "[s] \"またどこかで会う日が来るかもね……。\""
"10013065-49-シズコ" = "それだけは……勘弁願いたいです……"
"10013065-50-シズコ" = "よし！ひとまず、この話はここまで！"
"10013065-51-シズコ" = "やることはまだ残ってるし、どんどんいきましょう！"
