[translation]
"80000052-1" = "スカルマン、変身！"
"80000052-2-アズサ" = "……来たね、先生。尾行はちゃんと撒いた？"
"80000052-3-アズサ" = "どうしてこんなところに呼んだのか、って？"
"80000052-4-アズサ" = "理由は簡単。無防備な状態になると分かっていて、敵に狙われやすい場所を選ぶことは無い。"
"80000052-5-アズサ" = "もちろんその、先生がそういうのをあまり気にしなくて良いって言ってくれたのは覚えてるけれど……。"
"80000052-6-アズサ" = "でも今日は違う。今は、気にしないなんてわけにはいかない。"
"80000052-7-アズサ" = "……何か、変なことを言ってる気がしてきた。"
"80000052-8" = "[s1] \"ううん、そんなことないよ。\"\n[s2] \"何も変なことじゃないと思うよ。\""
"80000052-9-アズサ" = "そうか……。"
"80000052-10-アズサ" = "そうか……。"
"80000052-11-アズサ" = "……まあ、それはどうでも良い。要はただ、静かで落ち着ける環境を構築したかっただけ。"
"80000052-12-アズサ" = "その目標は達成した、あとは……。"
"80000052-13-アズサ" = "……先生、これを貰ってほしい。"
"80000052-14" = "[s3] \"これは……！\"\n[s4] \"もしかして……。\""
"80000052-15-アズサ" = "……ふふっ。"
"80000052-16-アズサ" = "……ふふっ。"
"80000052-17-アズサ" = "やっぱり、先生なら分かってくれると思ってた。"
"80000052-18-アズサ" = "この死神……スカルマンの可愛さを！"
"80000052-19-アズサ" = "限定品で且つこれが最後の一品だったから、もう手に入らないらしいけど。今日は特別。"
"80000052-20-アズサ" = "先生には今まで、たくさんのものを貰ったから。"
"80000052-21-アズサ" = "すごく貴重なものだけど、先生には渡したいと思ったんだ。食べ物だから、いつかは無くなるけど。それでも……"
"80000052-22-アズサ" = "……って、先生？"
"80000052-23-アズサ" = "先生！？"
"80000052-24-アズサ" = "な、何でそんな勢いで食べて……！？"
"80000052-25-アズサ" = "それ、限定品だからその、もう少しゆっくり見るとか……！"
"80000052-26" = "[s5] \"ふふっ……これで、私がスカルマンになったと言っても過言ではない！\"\n[s6] \"ふふっ、スカルマンは消えない。いつまでも私は、君と共に！\""
"80000052-27-アズサ" = "……！？"
"80000052-28-アズサ" = "……！？"
"80000052-29-アズサ" = "せ、先生……？"
"80000052-30-アズサ" = "……。"
"80000052-31-アズサ" = "……ふふっ。"
"80000052-32-アズサ" = "な、なるほど……。"
"80000052-33-アズサ" = "……理解した。じゃあ、ずっと一緒だね。流石は先生。"
"80000052-34-アズサ" = "じゃあこうなったら、先生には私にとってのスカルマンとしても、一緒にいてもらおうかな。"
"80000052-35-アズサ" = "……じゃあ帰ろう、スカルマン。"
"80000052-36-アズサ" = "もう、隠れる必要も無いね。"
"80000052-37" = "（その後アズサと一緒に堂々と、ゆっくりと時間を過ごした）"
