[translation]
"80000049-1" = "甘くて柔らかい夢の中で"
"80000049-2" = "[ns] \"ここはこれで、あっちの方は……。\""
"80000049-3" = "（いつの間に良い時間になっていた）"
"80000049-4" = "[ns1] \"こっちはだいたい終わったし、あとは……。\"\n[ns2] \"……終わりが見えない。\""
"80000049-5" = "（何日も仕事を処理し続けていたのだが、依然として片付かない仕事の山を見つめていた）"
"80000049-6" = "（何日も仕事を処理し続けていたのだが、依然として片付かない仕事の山を見つめていた）"
"80000049-7" = "[ns] \"……そろそろ身体が危ないかも。\""
"80000049-8" = "（疲労を感じ、横になろうかと思ったその時……）"
"80000049-9-ツバキ" = "あ、先生。"
"80000049-10" = "[s] \"ツバキ？どうしてここに？\""
"80000049-11-ツバキ" = "この近くに来たタイミングで、ちょうど「寝不足オーラ」を感じたの。"
"80000049-12" = "[s] \"寝不足オーラ……？\""
"80000049-13-ツバキ" = "その顔色……先生、しばらく寝てないでしょ。ダメだよ～？"
"80000049-14-ツバキ" = "仕事は大切だけど、身体の方も大事。"
"80000049-15-ツバキ" = "身体を壊しちゃったら、私も一緒に修行できなくなっちゃう。"
"80000049-16" = "[s] \"でも、仕事が終わらなくって……。\""
"80000049-17-ツバキ" = "めーっ。"
"80000049-18" = "[s] \"めっ……？\""
"80000049-19-ツバキ" = "ダメなのはダメ。"
"80000049-20-ツバキ" = "睡眠は大事なんだから、それを疎かにしたら全部ダメになっちゃうよ？"
"80000049-21-ツバキ" = "普段からせっかく一緒に「完璧な睡眠」を目指して修行してるんだから、活かしてもらわないと。"
"80000049-22-ツバキ" = "……うん、これは良くない。"
"80000049-23" = "[s3] \"ですがツバキ先生……！\"\n[s4] \"ど、どうしよう……。\""
"80000049-24-ツバキ" = "うーん、よっぽど追い詰められてるんだね……。"
"80000049-25-ツバキ" = "うーん、よっぽど追い詰められてるんだね……。"
"80000049-26-ツバキ" = "大丈夫、心配しないで。"
"80000049-27-ツバキ" = "どれだけ追い詰められても、私がそばにいるから。"
"80000049-28-ツバキ" = "あ、先生のためにこれを持ってきたの。"
"80000049-29-ツバキ" = "はい、これ。"
"80000049-30" = "[s] \"これは……？\""
"80000049-31-ツバキ" = "先生、今日はバレンタインデーだよ？"
"80000049-32-ツバキ" = "だから、熟睡できるチョコレートと安眠セット。"
"80000049-33-ツバキ" = "このチョコはキヴォトスでも特殊な、食べるとだんだん眠くなるやつなの。"
"80000049-34-ツバキ" = "一口食べると、象さんでも寝ちゃうんだって。「チョコレートはカフェインで眠れなくなる」っていう通念の逆側へ一直線な、最近話題のチョコ。"
"80000049-35" = "[s] \"それ、色々と危ないのでは……？\""
"80000049-36-ツバキ" = "まあまあ、とにかくお疲れの先生には必要だと思うから。"
"80000049-37-ツバキ" = "先生にはきちんと健康でいてもらわないと。先生が倒れると、みんな困るし……"
"80000049-38-ツバキ" = "……もちろん、私も。"
"80000049-39" = "[s] \"ツバキ……。\""
"80000049-40-ツバキ" = "だから、はい。"
"80000049-41-ツバキ" = "先生、横になって？"
"80000049-42-ツバキ" = "私のここ、結構柔らかくて気持ち良いと思うよ？"
"80000049-43" = "[ns] \"ちょっ、ツバキ近い……！？\""
"80000049-44-ツバキ" = "んー？膝枕は、嫌？"
"80000049-45-ツバキ" = "私の修業道具を貸してあげられたら良かったんだけど、ちょうど今は洗濯中で……。"
"80000049-46-ツバキ" = "え、膝枕以外の方法？うーん……"
"80000049-47-ツバキ" = "私が持ってるもので、何か柔らかいもの……。"
"80000049-48-ツバキ" = "……お尻？"
"80000049-49" = "[s] \"膝枕でお願いします。\""
"80000049-50-ツバキ" = "そう？じゃあ……"
"80000049-51-ツバキ" = "ゆっくり寝ようね？"
"80000049-52-ツバキ" = "はい、チョコレートも。これですぐ眠れるよ。あーん……"
"80000049-53" = "[ns] \"あ……。\""
"80000049-54-ツバキ" = "ふふっ、ぐっすり休んでね。"
"80000049-55-ツバキ" = "お休み、先生。"
"80000049-56" = "（そうして、久しぶりに気持ちの良い熟睡ができた）"
