[translation]
"80000093-1" = "終わらないもの"
"80000093-2-アユム" = "うう、もしこの書類が間に合わなかったら……"
"80000093-3-アユム" = "きっとリン先輩……じゃなかった、行政官にすっごく怒られて……。"
"80000093-4-アユム" = "これが終わったら、次は……"
"80000093-5-アユム" = "あれ……スケジュール表は……？"
"80000093-6-アユム" = "うぅっ……身体が二つあれば良いのに……。"
"80000093-7" = "[s1] \"その気持ちはすごくわかる……。\"\n[s2] \"身体が二つあっても、休んでくれるかは怪しいけど……。\""
"80000093-8-アユム" = "あ、せっ、先生……！"
"80000093-9-アユム" = "あ、せっ、先生……！"
"80000093-10-アユム" = "すみません……せっかくお越しいただいたのに、こんな状況で……。"
"80000093-11" = "[s] \"ううん、無理しないで。ゆっくりで大丈夫だから。\""
"80000093-12-アユム" = "ありがとうございます……。"
"80000093-13-アユム" = "ですが、先生をお待たせしてゆっくり、というのも……。"
"80000093-14" = "[s] \"じゃあ、そんなにゆっくりじゃない程度にゆっくりで。\""
"80000093-15-アユム" = "え、えっ……？"
"80000093-16-アユム" = "それは一体、どうすれば……？"
"80000093-17-アユム" = "……先生もそのご様子ですと、お疲れみたいですね？"
"80000093-18-アユム" = "何だか危なさそうですし、先生の方こそゆっくりなさった方が良さそうですが……。"
"80000093-19" = "[s] \"大丈夫大丈夫、お互い様ってことで……。\""
"80000093-20-アユム" = "ふぅ……そろそろ一段落つきそうです……。"
"80000093-21-アユム" = "大変ですが、結局は誰かがやらねばなりませんし……。"
"80000093-22-アユム" = "他の連邦生徒会の方々も、きっとお忙しいはず。"
"80000093-23-アユム" = "弱音を吐いている場合ではありませんね……！"
"80000093-24" = "[s] （暇そうに明太子味のポテチを貪る誰かさんが向こうに見えたが、見なかったことにした）"
"80000093-25" = "[ns] \"はい、コーヒーでもどう？\""
"80000093-26-アユム" = "えっ、あ、淹れてくださったんですか？"
"80000093-27-アユム" = "あ、ありがとうございます。それでは、せっかくですし……"
"80000093-28-アユム" = "……！"
"80000093-29-アユム" = "味の調整が、ピッタリ……ど、どうして……！？"
"80000093-30" = "[s3] \"いつもコーヒーを淹れてるところ、よく見てたから。\"\n[s4] \"似たような立場だからかな、何となくね。\""
"80000093-31-アユム" = "う、ううぅ……"
"80000093-32-アユム" = "う、ううぅ……"
"80000093-33-アユム" = "ありがとうございます、先生……こんな、優しくしていただき……"
"80000093-34" = "[s] \"そ、そこまで喜んでもらえるとは……落ち着いたらもう少し頑張ろうか。\""
"80000093-35-アユム" = "ううううぅ……それを聞いたらまた、別の意味でちょっと悲しくなってきました……。"
"80000093-36" = "[ns] \"お疲れ様。そういえば今日は、何の用件で？\""
"80000093-37-アユム" = "あ、そうでした！えっとですね、その……"
"80000093-38-アユム" = "あの、一先ずおやつでもいかがでしょうか……！？さ、先ほどのコーヒーのお礼も兼ねて……"
"80000093-39-アユム" = "……？あ、たしかにあまり見ない商品かもしれません。"
"80000093-40-アユム" = "薄切りにして乾燥させたグレープフルーツに、チョコレートをコーティングしたお菓子です。"
"80000093-41-アユム" = "カフェインとテオブロミン、ビタミンまで摂取できて疲労が軽減され――"
"80000093-42-アユム" = "る、らしいのですが……。"
"80000093-43" = "[s5] \"ま、まあまあ……。\"\n[s6] \"か、簡単には疲れ、取れないよね。効いてるんだろうけど。\""
"80000093-44-アユム" = "そうなんですよね……うぅ……。"
"80000093-45-アユム" = "そうなんですよね……うぅ……。"
"80000093-46-アユム" = "せっかくのバレンタインなのに、何だかすみません……。"
"80000093-47" = "[s] \"そういえば今日、バレンタインだったね。\""
"80000093-48-アユム" = "業務に追われ、お買い物に出かける時間も取れず……。"
"80000093-49-アユム" = "手元にあったチョコレートが、これくらいしかなく……。"
"80000093-50-アユム" = "やっぱり要らない、ですかね……？"
"80000093-51" = "[s] \"そんなことないよ、ありがとう。すごく美味しい。\""
"80000093-52-アユム" = "ほ、本当ですか……！？"
"80000093-53" = "[s] \"うん、甘酸っぱくて良い感じ。疲れも取れそう。\""
"80000093-54-アユム" = "そ、それは良かったです……！"
"80000093-55-アユム" = "先生のそばにいると、何だか疲れを忘れてしまいそうです……えへへ。"
"80000093-56" = "（その後もアユムと一緒にチョコレートを摘まみつつ、様々な苦労話を聞いたのだった）"
