[translation]
"80000003-1" = "行政官のおやつ"
"80000003-2" = "連邦生徒会・オペレーションルーム"
"80000003-3-リン" = "ああ、お疲れ様です。先生。"
"80000003-4-リン" = "先生を本日お呼びした理由は……言わなくても、分かっていますよね？"
"80000003-5" = "[s] \"何となく……。\""
"80000003-6-リン" = "はい、恐らくはお察しの通りかと。"
"80000003-7-リン" = "昨日お送りいただいたシャーレの業務報告書……正しく記入されている箇所の方が少ないくらい、無茶苦茶でしたが？"
"80000003-8-リン" = "誤記や記入場所の間違いは勿論、なぜか報告書の最後にはおもちゃ屋の領収書がありますし……。"
"80000003-9-リン" = "……全部指摘しますから、今すぐに直してください。"
"80000003-10" = "[s] \"はい……。\""
"80000003-11" = "（その後リンに指摘してもらいつつ、ふたりで頑張って修正した。）"
"80000003-12-リン" = "……何とか終わりそうですね。"
"80000003-13-リン" = "ああ、こことここにも署名を……。"
"80000003-14" = "[s] 不意にあくびが出る。"
"80000003-15-リン" = "……お疲れのようですね、先生。"
"80000003-16-リン" = "……？シャーレのお仕事でしばらく寝てない……？"
"80000003-17-リン" = "そうでしたか。それで手書き部分もめちゃくちゃだったと……。"
"80000003-18-リン" = "十分な睡眠を取ることも業務の一環ですし、効率に大きく影響します。お忙しいからと睡眠を取らないのでは本末転倒。"
"80000003-19-リン" = "どうしてもという場合は、カフェインなどの摂取も方法としてはありますが……"
"80000003-20-リン" = "少々お待ちください。何か残っていたような……。"
"80000003-21-リン" = "……ありました。"
"80000003-22-リン" = "どうぞ、先生。"
"80000003-23-リン" = "……何ですか、その表情は。チョコレートくらい知っていますよね、なぜそんな顔を……？"
"80000003-24" = "[s] \"だって今日は……。\""
"80000003-25-リン" = "今日？今日が何ですか？"
"80000003-26-リン" = "今日……？"
"80000003-27-リン" = "…………。"
"80000003-28-リン" = "……………………。"
"80000003-29-リン" = "……そんな訳ないでしょう。"
"80000003-30-リン" = "私はただ、先生にいち早く書類を片付けてもらって、お帰りいただきたいだけです。"
"80000003-31" = "[s] \"はい、すみません……。\""
"80000003-32-リン" = "……では報告書を仕上げるとしましょう。"
"80000003-33" = "[s] \"はい……。\""
"80000003-34-リン" = "……。"
"80000003-35-リン" = "……本当に違いますからね。"
"80000003-36" = "[s] \"……はい。\""
"80000003-37" = "（その後、変な沈黙の中で最後まで作業をしていた）"
