[translation]
"80000106-1" = "みんなと一緒に"
"80000106-2-プラナ" = "先生、来てくださったんですね。"
"80000106-3-プラナ" = "はい、アロナ先輩なら寝ています。熟睡中です。"
"80000106-4-プラナ" = "把握。いつ先生が来てもいいよう、用意をしてあります。"
"80000106-5" = "[s] \"用意って？\""
"80000106-6-プラナ" = "はい。先生は今日が何の日か知っていますか？"
"80000106-7" = "[ns1] \"今日はバレンタインデーだから……。\"\n[ns2] \"つまり、用意ってチョコレート……！？\""
"80000106-8-プラナ" = "確認。はい、正解です。"
"80000106-9-プラナ" = "ご褒美に頭を撫でましょう。さあ、遠慮せずこちらへ。"
"80000106-10-プラナ" = "はい？恥ずかしいんですか？"
"80000106-11-プラナ" = "理解。私の胸にうずくまりながら頭を撫でられているタイミングでアロナ先輩が目を覚ましてしまったら、どうしようかと心配しているのですね？"
"80000106-12-プラナ" = "先生が恥ずかしがり屋なのは、よく知っています。"
"80000106-13-プラナ" = "覚えていないかもしれませんが、私はアロナ先輩と同じくらい先生を知っていますから。"
"80000106-14-プラナ" = "なので今日のところは、チョコレートをお渡しするだけにします。"
"80000106-15" = "[ns] \"プラナちゃんのチョコレート！\""
"80000106-16-プラナ" = "はい、100%プラナ配合の手作りチョコレートです。#nアロナ先輩には内緒で作りました。"
"80000106-17" = "[s] \"う、うん……\""
"80000106-18-プラナ" = "アロナ先輩が寝ている二人きりのタイミングで渡すというのも、重要なポイントでした。ふふふ。いかがでしょう？"
"80000106-19" = "[s] \"アロナに見られるの、実はプラナちゃんも恥ずかしいんだよね？\""
"80000106-20-プラナ" = "……。"
"80000106-21-プラナ" = "……沈黙。その質問には答えません。"
"80000106-22-プラナ" = "……。"
"80000106-23-プラナ" = "…………肯定。"
"80000106-24" = "[s] \"ありがとう、プラナちゃん。頂きます。\""
"80000106-25-プラナ" = "……はい、どうぞ。"
