[translation]
"80000105-1" = "認識の差"
"80000105-2-アオイ" = "……やっと見つけた。"
"80000105-3-アオイ" = "ここに居たのね、先生。探したじゃない。"
"80000105-4-アオイ" = "……ん？"
"80000105-5-アオイ" = "すぐに終わるわ……私にとって大事な用ではあるけれど。"
"80000105-6-アオイ" = "……それじゃあ、さっそくだけど本題に。"
"80000105-7" = "[ns1] \"……もしかして、チョコレート？\"\n[ns2] \"バレンタインの……？\""
"80000105-8-アオイ" = "……意外そうね？まぁ、予想はしていたけど。"
"80000105-9-アオイ" = "私に対する印象なんて、そんなものだろうと思っていたわ。#nでも、だからこそ……"
"80000105-10-アオイ" = "せっかくの機会を逃す手は無いと思って。"
"80000105-11-アオイ" = "もっと前から感謝を伝えておきたかったところではあるけれど……"
"80000105-12-アオイ" = "それに……"
"80000105-13-アオイ" = "私は別に、先生を嫌ったり警戒してるわけではないもの。"
"80000105-14-アオイ" = "……余計なことを言ったわね。今のは忘れてちょうだい。"
"80000105-15-アオイ" = "私なりに、あなたとの関係をどう築いていこうか、これでも気にしてたのよ。"
"80000105-16-アオイ" = "だから、気に入ってもらえたのなら嬉しいわ。"
"80000105-17" = "[s3] \"もちろん、とっても嬉しいよ！\"\n[s4] \"アオイのバレンタインチョコ！！\""
"80000105-18-アオイ" = "そんなに喜ぶことかしら……"
"80000105-19-アオイ" = "……ん？お礼にコーヒーを奢ってくれるの？"
"80000105-20-アオイ" = "ありがたく頂くけど……何というか、拍子抜けね。"
"80000105-21-アオイ" = "ただのチョコレートよ？それに、まだ中を見てすらいないのに。"
"80000105-22-アオイ" = "私たちって、そんなに親しかったかしら……"
"80000105-23" = "[s5] \"……ん？\"\n[s6] \"そんなに親しくなかった？\""
"80000105-24-アオイ" = "…………？"
"80000105-25-アオイ" = "……そう。"
"80000105-26-アオイ" = "……なるほど。"
"80000105-27-アオイ" = "…………ふぅ。"
"80000105-28-アオイ" = "そうだったのね……先生。"
"80000105-29-アオイ" = "あなたって人は……"
"80000105-30" = "[s7] \"……アオイ、大丈夫？\"\n[s8] \"何か悩みでもあるの……？\""
"80000105-31-アオイ" = "…………。"
"80000105-32-アオイ" = "いえ……私だけ気にしすぎて、損しているみたいね。"
"80000105-33-アオイ" = "……ん？"
"80000105-34-アオイ" = "悩みがあったら、いつでも聞くから……？"
"80000105-35-アオイ" = "……分かったわ。"
"80000105-36-アオイ" = "悪いのは、私じゃなくて先生の方だったのだと。"
"80000105-37" = "[s] \"……え？\""
"80000105-38-アオイ" = "……いえ、独り言よ。気にしないで。#nそれじゃあ、私は用事があるから……ま、また……"
"80000105-39" = "（なぜか急にアオイは居なくなってしまったが……）"
"80000105-40" = "（……もらったチョコレートは、とても美味しかった）"
