[translation]
"80000017-1" = "甘い残業"
"80000017-2" = "シャーレ・入口"
"80000017-3-チヒロ" = "はあ……やっとサーバーの点検が終わった……。"
"80000017-4-チヒロ" = "単なる定期メンテナンスだったはずなのに、日付が変わった途端急にすごい量のメッセージが飛んできて……。"
"80000017-5-チヒロ" = "キャパオーバーにならないように対応してたら、結局ほぼ一日中サーバー室に釘付けになって疲れた……。"
"80000017-6" = "[s] \"こんな遅くまでお疲れ様。\""
"80000017-7-チヒロ" = "ありがと。でもハッカーにとっては、まだまだ遅い時間帯ではないよ。"
"80000017-8-チヒロ" = "……体が疲れてること自体は、否定できないけど。"
"80000017-9-チヒロ" = "先生、良かったらコーヒーでも一杯奢ってくれない？"
"80000017-10-チヒロ" = "自販機の缶コーヒーでもいいから、とにかくカフェインを体に入れたい……。"
"80000017-11" = "[ns] チヒロに缶コーヒーを渡す。"
"80000017-12-チヒロ" = "……はぁ、これでちょっとはマシになった。"
"80000017-13-チヒロ" = "それにしても、どうして今日に限って急に、あそこまで先生宛のメッセージが……。"
"80000017-14-チヒロ" = "そういえばサーバー室にこもってるうちに、街の風景も変わったような……。"
"80000017-15-チヒロ" = "……バレンタインデー？"
"80000017-16-チヒロ" = "ああ、なるほどね。"
"80000017-17-チヒロ" = "だからシャーレに、DDoS攻撃レベルの通知が……。"
"80000017-18-チヒロ" = "……知ってるつもりだったけど。やっぱり人気者なんだね、先生。"
"80000017-19" = "[s] \"何だかごめん……。\""
"80000017-20-チヒロ" = "ううん。先生のせいでもないし。"
"80000017-21-チヒロ" = "それより……結局サーバーの点検に釘付けで、チョコとか用意できてなかったな……。"
"80000017-22-チヒロ" = "こんな時間じゃ開いてるお店も……。"
"80000017-23-チヒロ" = "うーん、仕方ない。"
"80000017-24-チヒロ" = "はい、先生。受け取って。"
"80000017-25" = "[s] \"これは……。\""
"80000017-26-チヒロ" = "私からのバレンタイン。"
"80000017-27-チヒロ" = "厳密には「チョコレート」じゃないかもしれないけど……貰ってくれるよね？"
"80000017-28-チヒロ" = "私はこの飲み物、結構好きでさ。"
"80000017-29-チヒロ" = "真夜中に糖分とカフェインを欲した時に選べる、数少ない選択肢なんだ。"
"80000017-30-チヒロ" = "普段は気づかないけど、困った時には頼れる。まるで私の……"
"80000017-31-チヒロ" = "……なんて言ったら、受け取りづらいかな？"
"80000017-32-チヒロ" = "ハッピーバレンタイン。ほら、気楽に飲んで。"
