[translation]
"80000057-1" = "慣れた様子で"
"80000057-2" = "（夜も更けた頃。仕事の途中だったものの、少し用事があって休憩室へと向かった）"
"80000057-3" = "[ns1] \"……？\"\n[ns2] 電気を点けて確認する。"
"80000057-4" = "（足元に落ちてる何かが目に入った）"
"80000057-5" = "[ns] \"……。\""
"80000057-6" = "[ns3] \"セリナ。\"\n[ns4] \"隠れないでも大丈夫だよ。\""
"80000057-7-セリナ" = "え、えっと……こんばんは、先生。"
"80000057-8-セリナ" = "休憩の間に召し上がっていただくために、そっと置いて帰ろうかと思ったのですが……。"
"80000057-9-セリナ" = "と、糖分は仕事にも良いですから！お忙しい先生のために、その……！"
"80000057-10-セリナ" = "それからもちろん、今日はバレンタインデーだからということもありますが……。"
"80000057-11-セリナ" = "……ごめんなさい、後者の方が本音です。はい……。"
"80000057-12-セリナ" = "す、すみません何だか色々と、その……。"
"80000057-13-セリナ" = "……はい？"
"80000057-14-セリナ" = "え、まずは座って……？は、はい。"
"80000057-15-セリナ" = "の、飲み物ですか？えっと、何でも嬉しいですが……。"
"80000057-16-セリナ" = "せ、先生、何だか慣れてきましたね……？もうここにいたことを、何も気にされていないと言いますか……。"
"80000057-17" = "[s5] \"まあそろそろね……。\"\n[s6] \"私のためにしてくれてるって、分かってるから。\""
"80000057-18-セリナ" = "そ、そうでしたか……。"
"80000057-19-セリナ" = "そ、そうでしたか……。"
"80000057-20-セリナ" = "あ、そのチョコレート……は、はい。どうぞ。"
"80000057-21-セリナ" = "お仕事中でしたもんね。はい、糖分はもちろんのこと、栄養がたっぷりのチョコレートなんです。"
"80000057-22-セリナ" = "あ、美味しいですか？それは良かったです！"
"80000057-23-セリナ" = "で、では私はこれで……また必要になったら来ますね？"
"80000057-24" = "[s] \"セリナ。\""
"80000057-25-セリナ" = "は、はい！"
"80000057-26" = "[s7] \"普通にエントランスからでも大丈夫だよ。\"\n[s8] \"いつもありがとね。チョコも、すごく嬉しい。\""
"80000057-27-セリナ" = "……。"
"80000057-28-セリナ" = "……。"
"80000057-29-セリナ" = "……ふふっ。"
"80000057-30-セリナ" = "……はい、では。無理はしないでくださいね？"
"80000057-31-セリナ" = "……では、また今度。"
