[translation]
"1012303-1" = "停滞の先へ"
"1012303-2" = "シャーレ執務室"
"1012303-3" = "（セイアが来るというので、散らかった室内を慌てて片付けていた）"
"1012303-4-？？？" = "ほう……ここまで念入りに準備してくれるとはね。"
"1012303-5-？？？" = "これでは、かえって気軽に足を運びづらくなってしまうじゃないか。"
"1012303-6" = "[s1] \"……セイア？\"\n[s2] \"よ、よく来たね。\""
"1012303-7-セイア" = "……。 "
"1012303-8-セイア" = "いや、むしろ光栄というべきかな。#n私に対する先生の気遣い。その証左なのだからね。"
"1012303-9-セイア" = "これはつまり、先生の中で私の存在感が一層増した……という解釈でいいのかな？"
"1012303-10" = "[s3] \"……セイア？\"\n[s4] \"その格好でここまで来たの？\""
"1012303-11-セイア" = "……ふふ、気になるかい？"
"1012303-12-セイア" = "案ずることはないさ。この格好は、誰にも見咎められていないはずだ。#n今日は車で来たからね。"
"1012303-13-セイア" = "……うん？"
"1012303-14-セイア" = "この服が気に入っているのか、と？#nああ、たしかに。最近はこればかり着ているからな。"
"1012303-15-セイア" = "答えは――当然だ。#n自分で見立てたのだから。"
"1012303-16-セイア" = "そういえば、まだ感想を聞いていなかった。"
"1012303-17-セイア" = "君は、どんな言葉を尽くしてくれるんだい？"
"1012303-18" = "[s5] \"もちろん、よく似合ってるよ。\"\n[s6] \"いいファッションセンスだね。\""
"1012303-19-セイア" = "……ふむ。"
"1012303-20-セイア" = "期待通りではあるが……#n期待を裏切らないというのも、考えものだ。"
"1012303-21-セイア" = "……照れ隠しだ。そう気にしないでくれ。"
"1012303-22-セイア" = "ファッションセンス……か……。"
"1012303-23-セイア" = "私とて、密かに一家言あるんだ。"
"1012303-24-セイア" = "季節の趣を損なわず、凡庸さを避ける一工夫を施す――#nそれが醍醐味だと思っている。"
"1012303-25-セイア" = "出来の良い物語や洒落た謎解きを仕掛けるような感覚……#nとでも言えばいいだろうか。"
"1012303-26-セイア" = "とはいえ立場上、周囲の目は中々無視できないものだ。#n実践の機会は滅多にないのが実情だけれどね。"
"1012303-27-セイア" = "だからこそ機会が巡ってきた時には、存分に活用しなければ。"
"1012303-28-セイア" = "自慢の着こなしを見てもらいたいと思うのは、#n何もおかしくないだろう？"
"1012303-29-セイア" = "そういうわけで、君の褒め言葉は実に良かった。#n嬉しかったよ。"
"1012303-30-セイア" = "……おや、意外かな？"
"1012303-31" = "[s7] \"少しだけ。でも、いいことだと思うよ。\"\n[s8] \"新しい一面を知れて、私も嬉しいよ。\""
"1012303-32-セイア" = "先生……君は否定の語彙をどこかに捨ててきてしまったのかい？"
"1012303-33-セイア" = "欲を言えば、先生と水遊びでもと思わないでもないが……#nもっとも、先生がその様子ではね。"
"1012303-34-セイア" = "安心してくれ。仕事の邪魔まではしないさ。"
"1012303-35-セイア" = "……いや、いいんだ。#n我儘も、あまり頻繁では輝きを失ってしまう。"
"1012303-36-セイア" = "今日はここで、静かに時を過ごすとしよう。#nこれくらいの贅沢は、許されると願いたいが……。"
"1012303-37" = "[s9] \"もちろんだよ。\"\n[s10] \"どこでも、好きなだけどうぞ。\""
"1012303-38-セイア" = "…………。"
"1012303-39-セイア" = "…………。"
"1012303-40" = "[s11] \"セイア？\"\n[s12] \"ど、どうしたの……？\""
"1012303-41-セイア" = "……気にせず仕事を続けてくれ。"
"1012303-42-セイア" = "君がそういう人間だと知っていながら、#n性懲りもなく同じ手を講じる私の落ち度だ。"
"1012303-43-セイア" = "先生がそのつもりならば、こちらとしても一歩踏み込む他あるまい。"
"1012303-44" = "[ns13] \"……セ、セイア！？\"\n[ns14] \"これは勘弁して欲しいかな……って。\""
"1012303-45-セイア" = "どこでも、と言ったのは君だろう？#n今日は、ここでしばし休むとしよう。"
"1012303-46-セイア" = "もしくは……ご所望とあらば、何か手伝おうか。#n「単なる雑務」や「機密書類」の類でなければの話だが。"
"1012303-47-セイア" = "一応は、仕事となればそれなりに手際はいい方でね。"
"1012303-48-セイア" = "……ん？"
"1012303-49-セイア" = "怒っている？私が？なぜそんなことを聞くんだい？#nそれは君……まさか、私が怒っていると思っていたのか……？"
"1012303-50-セイア" = "……ふふっ。"
"1012303-51-セイア" = "これしきで腹を立てるほど、私の了見は狭くないつもりだ。"
"1012303-52-セイア" = "……まあ。"
"1012303-53-セイア" = "多少なり苛立ちを覚えてはいたが……お陰様で、どうでもよくなってしまった。"
"1012303-54-セイア" = "いやはや、実に座り心地が良いじゃないか。"
"1012303-55-セイア" = "……君の膝の上は。"
"1012303-56-セイア" = "さあ、先生。早速業務に取り掛かろうか。#nさっさと片付けて、心置きなく寛ぐとしよう。"
"1012303-57-セイア" = "でないと――"
"1012303-58-セイア" = "私に費やされるべき貴重な時間を、業務に奪われてしまうからね。"
"1012303-59" = "（セイアの協力もあり、その日の仕事は想定より早く終わった）"
"1012303-60" = "（休憩室のソファで気持ちよさそうに昼寝をしてから、セイアは帰っていった）"
