[translation]
"10018070-1" = "第7話;それなら対決だ！"
"10018070-2-ハルナ" = "……そんなことがあったんですね。"
"10018070-3-ジュンコ" = "なんか段々話が大きくなってきてるけど……本当にいいんだよね？"
"10018070-4-ハルナ" = "ですが、諦めるつもりはありません。"
"10018070-5-ハルナ" = "一度でもやると決めたら、途中で投げ出したりしませんわ。"
"10018070-6-アカリ" = "そうだね！食べかけだと捨てることになっちゃうからね！"
"10018070-7-アカリ" = "ハルナはそういう意味で言ったわけではないはず……。"
"10018070-8-ハルナ" = "まあ良いでしょう。これも試練の一つだと思うことにしますわ。"
"10018070-9-ハルナ" = "究極の美食を求める私たちに立ちはだかる壁は、これから先いくつもあることでしょうし。"
"10018070-10-ハルナ" = "それに試練を突破した後に味わう食事は、きっと比べ物にならないほどの美食に違いありませんわ。"
"10018070-11-ハルナ" = "それでは皆さん、ニャオフードに向かいましょう。"
"10018070-12-グルメヘルメット団E" = "会長、報告がございます。"
"10018070-13-ニャオモト・カン" = "ムッフフフ。今度は何だね？"
"10018070-14-グルメヘルメット団E" = "美食研究会がニャオフードの本社に向かっています。"
"10018070-15-ニャオモト・カン" = "だにぃ！？どうして位置が分かったんだ！？"
"10018070-16-グルメヘルメット団E" = "会社のホームページに記載されています。"
"10018070-17-ニャオモト・カン" = "だにぃ！誰がホームページに住所を書けだなんて言ったんだ！"
"10018070-18-グルメヘルメット団E" = "……会長です。"
"10018070-19-ニャオモト・カン" = "なぜバカ正直に従ったんだ！"
"10018070-20-グルメヘルメット団E" = "いえ……命令通り正確に遂行しろと仰ったので……。"
"10018070-21-ニャオモト・カン" = "……。"
"10018070-22-ニャオモト・カン" = "ムッフフフフ……。"
"10018070-23-ニャオモト・カン" = "わざわざ会社のホームページを見て訪ねてくる熱烈なお客様なんだ。"
"10018070-24-ニャオモト・カン" = "ちょっとばかし歓迎してやるのが礼儀というものだろう。ムッフフフフ。"
"10018070-25-グルメヘルメット団E" = "何だか当初とお話が違うような……。"
"10018070-26-ニャオモト・カン" = "うるさい！予備隊は応戦準備にかかれ！"
"10018070-27-グルメヘルメット団E" = "よろしいんですね？"
"10018070-28-ニャオモト・カン" = "構わん！ニャオフードは私の会社だからな！"
