[translation]
"10018105-1" = "エピローグ;あけましておめでとうございます！"
"10018105-2" = "（そうして、年末年始を混乱の渦に巻き込んだ一連の騒動は一段落した）"
"10018105-3-フウカ" = "あ、先生！早く来てください！ちょうどお祭りの屋台が準備できたみたいです！"
"10018105-4-ハルナ" = "お祭りの食べ物もいいですが、私たちの用意したおせちもまだまだありますわ。#n残ったとしても、日持ちするので明日以降も召し上がっていただけますけれど。"
"10018105-5-ジュンコ" = "そもそもおせちって、年明け前に日持ちする料理を作り置きしておくためでもあったみたいだし。"
"10018105-6-イズミ" = "わ～、すごい！新年って楽しいね！"
"10018105-7-アカリ" = "あんなにおいしいおせちが残るとは思いませんが★"
"10018105-8-ジュンコ" = "……アカリの場合、本当に食べ尽くしてしまいそうなのよね。"
"10018105-9-アカリ" = "皆さんが召し上がるまでは我慢しますよ★"
"10018105-10-ジュリ" = "今年はどうか平穏に過ごせますように……。"
"10018105-11-ジュリ" = "そして、おいしい料理が作れるようになりますように……。"
"10018105-12-フウカ" = "先生！これ、食べてみてください！"
"10018105-13-フウカ" = "その、恥ずかしいけど……せっかく頑張ったので、食べてもらいたくて……。"
"10018105-14-ハルナ" = "うふふ。最高の料理を、最高の場所で。良い結末を迎えることもできましたわ。"
"10018105-15-ハルナ" = "究極の美食とは何か、その一端が覗けたような気がします。"
"10018105-16-ハルナ" = "今日は私にとっても美食研究会にとっても、大切な一日となりましたわ。"
"10018105-17" = "[ns] \"そういえば、ニャオモト会長は？\""
"10018105-18-ジュリ" = "「これで勝ったと思うなよ！」と叫びながらいなくなりましたね。"
"10018105-19-フウカ" = "大丈夫でしょうか？なんだか心配になるけど……。"
"10018105-20" = "気にすることありませんわ。そのようなセリフを残した人のなかに、まともな事例を見たことがありませんから。"
"10018105-21-アカリ" = "いざとなれば、また私たちで解決しましょう★"
"10018105-22-ジュンコ" = "グルメヘルメット団のやつらはどうするの？"
"10018105-23-ハルナ" = "気になりますか、フウカさん？"
"10018105-24-フウカ" = "先生……。"
"10018105-25" = "[ns] \"その子たちのことなら、私がどうにかしてみるよ。\""
"10018105-26" = "[ns] \"しっかり反省してからの話だけど。\""
"10018105-27-女将" = "もし当てがなければ、スズメ亭のアルバイトとして雇いましょうか。"
"10018105-28-イズミ" = "ええっ、いいの？"
"10018105-29-女将" = "どうも根が悪い子たちには思えませんでした。"
"10018105-30-女将" = "それに、先生と話してみたんです。"
"10018105-31" = "[ns] \"生徒の失敗は、大人がなんとかするものだからね。\""
"10018105-32-ジュンコ" = "もう……みんな、本当に人が良すぎるんだから。"
"10018105-33-ハルナ" = "先生、今年も一年、ありがとうございました。"
"10018105-34-フウカ" = "私もいつも感謝しています。"
"10018105-35-フウカ" = "先生がいらっしゃらなければ、きっと最後までやり遂げられませんでした。"
"10018105-36-フウカ" = "先生、あけましておめでとうございます！"
"10018105-37-ジュリ" = "あけましておめでとうございます。"
"10018105-38-ジュリ" = "あけましておめでとう、先生！"
"10018105-39-ジュリ" = "あけましておめでとう！おせちの続き食べよ～！"
"10018105-40-アカリ" = "もう年が明けたんですね？"
"10018105-41-アカリ" = "ハッピーニューイヤー★"
"10018105-42" = "（キヴォトスに新しい一年がやってきた）"
"10018105-43" = "[ns] （今年一年が、多くの人にとって幸せな時間になるよう願って）"
"10018105-44" = "[ns] （自分の決めた道を歩む人も）"
"10018105-45" = "[ns] （そして、今は道を違えた人も）"
"10018105-46-イズミ" = "うわわっ！？鯛の焼き物が暴れだしたよ！"
"10018105-47-ジュリ" = "ううっ、すみません！また私のせいで……！"
"10018105-48-ジュンコ" = "何をどうすれば焼いた魚が生き返って暴れるのよ！？"
"10018105-49-ハルナ" = "うふふ。"
"10018105-50-ハルナ" = "これは美食研究会として見逃せませんわ。"
"10018105-51-フウカ" = "ハルナ？まさか、私が考えているアレじゃないよね？ねえ、違うよね……？"
"10018105-52-アカリ" = "ハルナ、準備できましたよ★"
"10018105-53-フウカ" = "やめてって、ねえ！何しようとして――ここには先生もいるんだよ！今日はおめでたい日なんだよ！"
"10018105-54-アカリ" = "えいっ★"
"10018105-55-フウカ" = "ハルナあああああ！？"
"10018105-56" = "[ns] （……どうか今年もみんなにとって幸せな一年になりますように）"
"10018105-57" = "喰積の前にいささか～一番勝負～"
