[translation]
"10018090-1" = "第9話;二人の覚悟"
"10018090-2-フウカ" = "ふぅ……。"
"10018090-3" = "[s] \"フウカ、大丈夫？\""
"10018090-4-フウカ" = "あ、先生。"
"10018090-5-フウカ" = "はい、大丈夫です。それにまだやることもたくさん残っていますから。"
"10018090-6" = "[s1] \"あまり無理をするのも良くないよ。\"\n[s2] \"せめて少し休憩してきたらどうかな？\""
"10018090-7-フウカ" = "それでは……"
"10018090-8-フウカ" = "お言葉に甘えて。少し散歩でもしてきます。"
"10018090-9-ハルナ" = "……。"
"10018090-10" = "[s] \"ハルナもフウカに負担をかけすぎてないか心配なんだよね？\""
"10018090-11-ハルナ" = "まだ何も言っていませんが……。"
"10018090-12" = "[s] \"でもハルナがフウカを見守っていたのは知ってるよ。\""
"10018090-13-ハルナ" = "先生に隠し事はできませんね。"
"10018090-14-ハルナ" = "ええ、傍目に見ても明らかに限界ですわ。"
"10018090-15-ハルナ" = "しかし、何を思い悩んでいるのか、それが分かりません。"
"10018090-16" = "[s] \"ハルナの気持ちは？\""
"10018090-17-ハルナ" = "……私の気持ち、ですか。"
"10018090-18-ハルナ" = "先生には意表を突かれてばかりのような気がします。"
"10018090-19-ハルナ" = "私は……負けたくありません。いえ、負けてはいけないと思います。"
"10018090-20-ハルナ" = "美食のためだけではありません。スズメ亭には、多くの人の思いがかかっています。"
"10018090-21-ハルナ" = "しかし、この対決で勝つために必要なのは……私の力ではありません。"
"10018090-22-ハルナ" = "それが、その事実が悔しいですわ。"
"10018090-23" = "[s] \"ハルナにできること、きっと残っているよ。\""
"10018090-24-ハルナ" = "そう……でしょうか？"
"10018090-25" = "[s] \"うん、私はそう思うよ。\""
"10018090-26-ハルナ" = "……教えていただけませんか？"
"10018090-27" = "[ns] \"それはね……。\""
"10018090-28-ジュリ" = "だ、誰かフウカ先輩に何かあったか知りませんか？"
"10018090-29-ジュリ" = "スクーターに乗ってゲヘナのほうに行ったみたいなんですが、心配で……。"
"10018090-30-ジュリ" = "なるほど。気分転換に出たんですね。それなら安心です。"
"10018090-31" = "[s] \"フウカの場所に心当たりはある？\""
"10018090-32-ジュリ" = "はい……たぶん、あそこだと思います！"
"10018090-33-ハルナ" = "本当に……フウカさんはここにいるのでしょうか？"
"10018090-34" = "[s] \"ジュリが言うんだから、私は信じてるよ。\""
"10018090-35-ハルナ" = "それは私もですが……"
"10018090-36-ハルナ" = "気晴らしに訪れる場所が、いつも働いている給食部の屋上とは信じがたくて……。"
"10018090-37-ハルナ" = "……あら、驚きました。本当にあそこにいますわ。"
"10018090-38" = "[s] \"それじゃあ、後はハルナに任せるよ。\""
"10018090-39-ハルナ" = "な、なぜでしょう？こういうときこそ、先生の出番なのではないでしょうか？"
"10018090-40" = "[s] \"今日はハルナに行ってほしいんだ。\""
"10018090-41-ハルナ" = "……理由を、聞いてもよろしいでしょうか？"
"10018090-42" = "[ns] \"ハルナは同じ生徒の立場として、\""
"10018090-43" = "[ns] \"フウカのことを理解しているはずだから。\""
"10018090-44-ハルナ" = "そう言っていただけるのは、素直にありがたいものですが……。"
"10018090-45-ハルナ" = "しかし、フウカさんにとっての料理、私にとっての食事のように、ここは先生が適任なのではないでしょうか？"
"10018090-46-ハルナ" = "はい？だからこそ私が適任と……？"
"10018090-47-ハルナ" = "……。"
"10018090-48-ハルナ" = "……分かりました。"
"10018090-49-ハルナ" = "先生がそこまで仰るのなら……。"
"10018090-50-フウカ" = "……誰か登ってくる音が聞こえると思ったら、ハルナだったんだ。"
"10018090-51-ハルナ" = "失礼しますわ。"
"10018090-52-フウカ" = "よくここが分かったね。ジュリが教えてくれたんでしょう？"
"10018090-53-ハルナ" = "その通りですわ。迷惑でしたか？"
"10018090-54-フウカ" = "仕事の続きなら心配しないで。すぐに戻るよ。"
"10018090-55-フウカ" = "でも少しだけ……時間をちょうだい。"
"10018090-56-ハルナ" = "屋上がお好きなのですね。"
"10018090-57-フウカ" = "そうだね。いつも給食部の仕事が忙しいから、遠くに行く余裕もなくって。"
"10018090-58-フウカ" = "息抜きするとなったら、ここくらいのものだから。それで、いつの間にか落ち着ける場所になったの。"
"10018090-59-ハルナ" = "料理対決……やはりフウカさんとしては複雑ですか？"
"10018090-60-フウカ" = "嫌じゃないと言えば嘘になるかな。"
"10018090-61-フウカ" = "私は何と戦っているのか悩んで……。"
"10018090-62-ハルナ" = "当然、人々を騙して美食の道を乱すニャオフードですわ。"
"10018090-63-フウカ" = "私、グルメヘルメット団とハルナの話を聞いたよ。"
"10018090-64-ハルナ" = "……アカリからですか？"
"10018090-65-フウカ" = "うん。"
"10018090-66-ハルナ" = "そうでしたか……それで悩んでいたのですね。"
"10018090-67-フウカ" = "私たちが勝てば、ニャオフードで働く人たちは職を失うことになるのかな？"
"10018090-68-ハルナ" = "……その可能性がないとは言いませんわ。"
"10018090-69-ハルナ" = "スズメ亭がニャオフードの圧力を跳ね除けることになれば、"
"10018090-70-ハルナ" = "周りも自分の店を守ろうと諦めなくなるでしょう。"
"10018090-71" = "それが結果としてニャオフードの業績を下げることにつながれば……。"
"10018090-72-ハルナ" = "仕事量も減って、解雇される人も出てくるはずですわ。"
"10018090-73-フウカ" = "うん……。私が気になってるのはそこなんだ。"
"10018090-74-フウカ" = "それに商人のなかには、ニャオフードの肩を持つ人がいるのも確かだよ。"
"10018090-75-フウカ" = "直接言われたわけじゃないけど、余計なことをするなって視線を感じたのも確かだし。"
"10018090-76-ハルナ" = "ありのままが良い人もいるものですから。"
"10018090-77-ハルナ" = "もちろん、私は変化を好みますが。"
"10018090-78-フウカ" = "ふふっ。ハルナの言う変化のせいで、私は苦労することも多いんだけどね。"
"10018090-79-ハルナ" = "あら。そうでしたか？"
"10018090-80-フウカ" = "私はスズメ亭を助けたいと思っただけなのに。"
"10018090-81-フウカ" = "どうしてこんな大事になったんだろう。"
"10018090-82-ハルナ" = "フウカさんが一番気にしていることは何でしょうか？"
"10018090-83-フウカ" = "私たちが勝つことで、負けて何かを失う人たちのこと。"
"10018090-84-フウカ" = "私は誰かが苦しんでいるのは嫌なの。それで給食部に入ったところもあるから。"
"10018090-85-ハルナ" = "……私たちについては、どう思っていますか？"
"10018090-86-フウカ" = "ハルナたちも同じだよ。私にとって食堂に来てくれる人たちは、みんな面倒を見なくちゃいけない生徒だよ。"
"10018090-87-ハルナ" = "グルメヘルメット団も似たような存在ということですね。"
"10018090-88-フウカ" = "変だよね。私たちを邪魔してきてるのに。"
"10018090-89-ハルナ" = "フウカさん。"
"10018090-90-フウカ" = "ん？"
"10018090-91-フウカ" = "美食に犠牲はつきものです。#n躊躇っていては、素晴らしいお店はこうしてどんどん消えていってしまう――"
"10018090-92-ハルナ" = "それを、ただ指を咥えて見ているだけなんてできません。#nだから私たちは戦っているのでしょう？"
"10018090-93-フウカ" = "……そう、だね。"
"10018090-94-ハルナ" = "ええ。それに、ニャオフードは手加減しないはずですわ。"
"10018090-95-ハルナ" = "あちらは手段を選ばずに潰してこようとしています。"
"10018090-96-ハルナ" = "それにあちら側は、この勝負で負けたところで失うものは少ないです。"
"10018090-97-ハルナ" = "社員の待遇が悪くなったり、解雇される人が出るかもしれません。ですが、それらは可能性の話ですわ。"
"10018090-98-ハルナ" = "それに対してスズメ亭の女将は、負けたら全てを失います。"
"10018090-99-ハルナ" = "可能性などではなく、確実に。"
"10018090-100-フウカ" = "それは……そうだね。"
"10018090-101-ハルナ" = "そして被害を受けるのは、スズメ亭の女将だけではありません。"
"10018090-102-ハルナ" = "商店街の人たちです。彼らも被害者と呼べますわね。"
"10018090-103-フウカ" = "どうして？"
"10018090-104-ハルナ" = "真の美食を味わえなくなってしまうわけですから、当然でしょう？"
"10018090-105-フウカ" = "……ふふっ。"
"10018090-106-ハルナ" = "な、なぜ笑うのですか！？"
"10018090-107-フウカ" = "いや、なんかハルナらしいなって思って。"
"10018090-108-ハルナ" = "こほん。"
"10018090-109-ハルナ" = "とにかく、私は美食においてだけは本気ですわ。一歩も譲る気などありません。"
"10018090-110-ハルナ" = "そして、それはあなたも同じですよね、フウカさん。"
"10018090-111-フウカ" = "私……？"
"10018090-112-ハルナ" = "あなたは本当の実力を見せたことがほとんどありませんよね。"
"10018090-113-ハルナ" = "そういう機会がなかったといえば、そうなんでしょうが。"
"10018090-114-ハルナ" = "ですが今こそチャンスです。あなたの実力を見せる絶好の機会ですわ。"
"10018090-115-ハルナ" = "そうだね。"
"10018090-116-フウカ" = "ハルナが本気を出すんだから、私も頑張らなきゃね。"
"10018090-117-ハルナ" = "ええ、ここまで来てしまいましたから。"
"10018090-118-フウカ" = "ふふっ、そこに隠れている先生のおかげでね。"
"10018090-119-フウカ" = "先生、出てきてください。"
"10018090-120-フウカ" = "そこにいらっしゃいますよね？"
"10018090-121" = "[s] \"バレてたの？\""
"10018090-122-フウカ" = "なんとなく、近くにいるような気がしたんです。"
"10018090-123-フウカ" = "卵に出汁を混ぜて……"
"10018090-124-フウカ" = "後は砂糖と醤油、みりん……。"
"10018090-125-フウカ" = "数の子はどうなってますか？"
"10018090-126-女将" = "はい、漬け込みました。次はお魚を焼いて……。"
"10018090-127-フウカ" = "エビもふっくら仕上がってますね。"
"10018090-128-フウカ" = "食べる直前まで煮汁に浸しておいて……。"
"10018090-129-ジュリ" = "先輩！にんじんを切り終わりました！"
"10018090-130-フウカ" = "ありがとう！"
"10018090-131-フウカ" = "あ、サトイモのこと忘れてた……。"
"10018090-132-ハルナ" = "ふふっ。素敵な光景ですね。"
"10018090-133-ハルナ" = "女将さんと給食部が力を合わせておせちを作り、美食研究会がそれをサポートするなんて。"
"10018090-134-イズミ" = "味見するという建前でたくさん食べてるだけですけどね★"
"10018090-135-ジュンコ" = "これも仕事なんだからね。味見が終わったら次に使う食材を運ぶわよ。"
"10018090-136-イズミ" = "わぁ～幸せ！毎日こんな風に食べられたらいいのに！"
"10018090-137-ニャオモト・カン" = "ムッフフフ。おせちの生産ラインはどうかね？"
"10018090-138-グルメヘルメット団E" = "順調に進んでいます。煮沸ライン、漬物ライン、焼き物ライン、全て稼働中です。"
"10018090-139-ニャオモト・カン" = "大量生産！大量消費！ベルトコンベア！"
"10018090-140-ニャオモト・カン" = "これこそがニャオフードの食品工場！"
"10018090-141-ニャオモト・カン" = "さあ、働け働け！仕事があってこその人生だろう！"
"10018090-142-グルメヘルメット団E" = "すでにみんな時間外勤務なんですが……。"
