[translation]
"10018060-1" = "第6話;売り切れですって？そんなわけ……"
"10018060-2" = "（食材を探すため、ニャオフードに占領（？）された商店街を回ることになった一行）"
"10018060-3" = "（そこは、これといった特徴のない、よくある商店街だった）"
"10018060-4-ジュリ" = "ここの商店街は賑わってますね。"
"10018060-5-ジュリ" = "年末年始ですから、当然かもしれませんが。"
"10018060-6-ジュリ" = "なんだか私たちまで楽しくなってきますね？"
"10018060-7" = "[s] \"そうだね。食材選びを引き受けてありがとう。\""
"10018060-8-ジュリ" = "いえ、給食部では毎日の日課なので！"
"10018060-9-ジュリ" = "むしろいつもと違うところでの買い物なので、楽しみですね。"
"10018060-10-ジュリ" = "あっ、給食部の仕事が楽しくないということではないですよ！"
"10018060-11-ジュリ" = "先輩の腕前を見てると、いつも感心することばかりで、惚れ惚れするというか……。"
"10018060-12-ジュリ" = "私までうれしくなってくるんです。"
"10018060-13-ジュリ" = "じゃあ、もっとおいしい給食を作ってよ！"
"10018060-14-ジュリ" = "いろいろ心当たりはありますけど……"
"10018060-15-ジュリ" = "味が悪いのも事実ですね★"
"10018060-16-ジュリ" = "うう……。"
"10018060-17-ジュリ" = "そうですね。給食部としては、いつもおいしくなるように頑張ってはいるのですが……。"
"10018060-18" = "[s] \"イズミとアカリも、手伝ってくれてありがとう。\""
"10018060-19-ジュリ" = "うん！食材を見るのも好きなんだ！どれもおいしそうだから！"
"10018060-20-ジュリ" = "でも見てると食べたくなってくるね……ごくり。"
"10018060-21-ジュリ" = "ジュリさんだけ仕事しているのがちょっと気になっただけですよ★"
"10018060-22-ジュリ" = "それに食材を持ち帰るなら、人手は多いほうがいいですし。"
"10018060-23" = "[s] \"そう言ってもらえると助かるよ。\""
"10018060-24-ジュリ" = "それでは本格的に食材選びをしましょう！"
"10018060-25-ジュリ" = "安い食材でも、おいしいものはありますよ！"
"10018060-26-ジュリ" = "わぁ、このキャベツは良さそうです。"
"10018060-27-ジュリ" = "色も形もきれいですし、ぎっしり中が詰まってそうですね。"
"10018060-28-ジュリ" = "すみません、こちらのキャベツを買いたいのですが……。"
"10018060-29-八百屋" = "あぁ、悪いな。もう売り切れたんだ。"
"10018060-30-ジュリ" = "はい？ですが、まだたくさん並んでいますよね……？"
"10018060-31-八百屋" = "さっき、在庫を全部くれって連絡と入金があったもんでね……。"
"10018060-32-ジュリ" = "で、でも……それでしたら、他の食材は大丈夫ですよね？"
"10018060-33-八百屋" = "いや、そっちもなんだ。悪いね。"
"10018060-34-八百屋" = "申し訳ない……。#nただ、こっちにも事情があるってことを分かってくれ……。"
"10018060-35-イズミ" = "ふーん……？"
"10018060-36-イズミ" = "そんなのってないよ！"
"10018060-37-ジュリ" = "今度はお肉を見てみましょうか。"
"10018060-38-ジュリ" = "……こちらの豚肉が良さそうです！"
"10018060-39-ジュリ" = "色もきれいな赤ですし、脂の割合も問題ありませんね。"
"10018060-40-肉屋" = "今日はもう終わったんだが……何か用かい？"
"10018060-41-ジュリ" = "えっ、もうですか？"
"10018060-42-肉屋" = "今日用意した分のお肉が全部売れたんだ。"
"10018060-43-ジュリ" = "もしかして……誰かに入金されて、在庫をすべて抑えられたということでしょうか？"
"10018060-44-肉屋" = "そう、よく分かったね。なんかすっきりしないんだけどな。こんなこと、今までなかったからさ……。"
"10018060-45-肉屋" = "すまないね。今度はもっといいものを仕入れるから、また来てくれると助かるよ。"
"10018060-46-アカリ" = "なんだか怪しい匂いがしますね。"
"10018060-47-ジュリ" = "醤油と料理酒も買わないといけないのですが……嫌な予感がしますね。"
"10018060-48-ジュリ" = "調味料は賞味期限が長いので、ある程度の在庫があると思いますが……。"
"10018060-49-ジュリ" = "すみません。醤油と料理酒を見たいのですが……あ、サラダ油もありますか？"
"10018060-50-スパイス商人" = "それが次の仕入れまで、お店を休むつもりなんです。"
"10018060-51-ジュリ" = "まさか……売り切れたのですか？"
"10018060-52-スパイス商人" = "はい、そうなんです。来ていただいたのに申し訳ありません。"
"10018060-53-イズミ" = "一度はまだしも、二度、三度と同じことが起きるって……？"
"10018060-54-イズミ" = "わざと誰かが買い占めてるってこと？なんで？"
"10018060-55-イズミ" = "ひどいよ！"
"10018060-56" = "[s] \"確かに不自然だね。\""
"10018060-57-ジュリ" = "き、気を取り直して次の食材を探しましょう！"
"10018060-58-ジュリ" = "どこも一緒でした……。"
"10018060-59" = "[s] \"全部の商品が売り切れてたわけじゃないよね。\""
"10018060-60-ジュリ" = "そうですね。ですが、どれも私たちが使おうとしてる食材ばかりでした。"
"10018060-61-ジュリ" = "きっと私たちの邪魔をしてるんだよ！もう、どうして！"
"10018060-62-？？？" = "それは……お前らが目障りだからさ。"
"10018060-63" = "[ns] \"誰だ？\""
"10018060-64-グルメヘルメット団E" = "お前らは深入りしすぎたんだ。"
"10018060-65-グルメヘルメット団E" = "言っても聞かないだろうが、忠告しておく。"
"10018060-66-グルメヘルメット団E" = "ここで手を引くなら、これ以上悪いようにはしない。"
"10018060-67-アカリ" = "答えるまでもないですが、どうしてそんな提案を？"
"10018060-68-グルメヘルメット団E" = "お互い面倒だろう？私たちも大変なんだ。"
"10018060-69-イズミ" = "でも、そしたらスズメ亭を好き勝手するんだよね？それはダメだよ！"
"10018060-70-グルメヘルメット団E" = "結局、店を譲る気はないってことだな……。"
"10018060-71-グルメヘルメット団E" = "まあ、いいだろう。"
"10018060-72-グルメヘルメット団E" = "その返事も予想してたからな。……出てこい。"
"10018060-73-アカリ" = "うわ！今度は何なの！？"
"10018060-74-アカリ" = "ふふっ、そういうことですね。"
"10018060-75-ロボットA" = "お前たちが悪いんだからな。"
"10018060-76-ロボットA" = "覚悟しろ。今回は一味違うぞ。"
