[translation]
"2201-1" = "不健全な事業計画"
"2201-2" = "トリニティ・商店街"
"2201-3-トリニティの女子生徒A" = "あらっ、そうなのですか？"
"2201-4-トリニティの女子生徒B" = "はい、あちらの商店街の先にあるカフェで……"
"2201-5-ムツキ" = "ふ～ん……あっちもこっちも平和ボケしてそうな子ばっかりだね。"
"2201-6-ムツキ" = "言葉遣いからして、ザ・お嬢様って感じ？"
"2201-7-ムツキ" = "な、なんか、キラキラしてますね。"
"2201-8-ハルカ" = "ほ、本当に私みたいなのがここにいて、良いのでしょうか……。"
"2201-9-ムツキ" = "あ、良いこと思いついた。この往来のど真ん中で爆発起こさない？"
"2201-10-カヨコ" = "……いやいやいや。"
"2201-11-アル" = "よしなさい、ムツキ。トリニティの商店街を爆発させてって依頼で来たのであれば別だけど。"
"2201-12-アル" = "今日は別件よ、ここで騒ぎを起こすのは得策じゃないわ。"
"2201-13-ムツキ" = "そもそもアルちゃん、急にトリニティに来るなんて、今回は何の用事なの？"
"2201-14-アル" = "ふふふ、聞いて驚かないでちょうだい？"
"2201-15-ムツキ" = "それは大丈夫～、どうせ今さらアルちゃんの言うことに驚いたりしないし。"
"2201-16-カヨコ" = "それは確かに。"
"2201-17" = "わ、私は驚くかもしれませんので！こ、心の準備をしてます……！"
"2201-18-ハルカ" = "あ……でも驚くなと仰いましたし……ど、どうしましょう！？"
"2201-19-アル" = "ああもう、うるさいわよ！？"
"2201-20-アル" = "こほん、とにかく今日私たちがこうしてトリニティを訪れているのは……"
"2201-21-アル" = "ここで、新規事業説明会があるからよ！"
"2201-22" = "事業説明会？"
"2201-23-カヨコ" = "……こんなお嬢様学園のふもとで？"
"2201-24-アル" = "ええ、そうよ。知り合いのコネで聞いた話なのだけど……。"
"2201-25-ムツキ" = "アルちゃんのコネぇ？"
"2201-26-カヨコ" = "……はぁ、多分もうダメだこれ。"
"2201-27-ムツキ" = "ど、どうして、話を聞く前からそんな反応するのよ！？"
"2201-28-アル" = "ちゃんと確かな情報なんだから！この前の依頼主から、"
"2201-29-アル" = "「良い話があるんだけど、これはアル社長にだけ教えるからね？内緒だよ、分かった？」って紹介してくれて……。"
"2201-30" = "キヴォトスの裏世界でも一部にしか知られていない、トップシークレットな情報なのよ！"
"2201-31-アル" = "アウトローたちだけが共有している秘密の事業……！"
"2201-32-アル" = "すごいと思わない！？"
"2201-33" = "ふ～ん……まあアルちゃんがそれで良いなら良いけど。"
"2201-34-ハルカ" = "さ、さすがアル様です！すごいです！"
"2201-35-アル" = "あはっ、もっと褒めてもいいのよ！"
"2201-36-アル" = "こんな貴重な機会を得られたのも、すべてこの私の経営手腕のおかげ！"
"2201-37-カヨコ" = "……せめて面倒なことにならないと良いけど。"
"2201-38-アル" = "さあっ、遅れるわけにはいかないわ。説明会に向かうわよ！"
"2201-39-ムツキ" = "わ～お、すっごい人の数。"
"2201-40-カヨコ" = "この人たちみんなその、新規事業説明会……？に参加する人なんだ。"
"2201-41-アル" = "すごいのは数だけじゃないわよ。"
"2201-42-アル" = "ここに集まった事業家は、裏世界でも指折りの……各分野で成功を収めた事業家の人たちばかりなんだから！"
"2201-43-アル" = "ここで顔を覚えてもらって私たちの名前が広がれば、それだけで大きな成果になるわ。"
"2201-44-アル" = "それに、この説明会の事業に投資して利益も得られれば……私たち便利屋の未来はますます明るくなるってものでしょう？"
"2201-45-ハルカ" = "あっ、壇上に誰かが……。"
"2201-46-司会" = "まずは御礼を、本日はこうして当社の事業説明会に参加してくださり、誠にありがとうございます。"
"2201-47-司会" = "先に申し上げましょう、今回のような機会は滅多にあることではございません。"
"2201-48-司会" = "ここに立ち会えたことそのものが、まず幸運と言っても過言ではないでしょう。"
"2201-49-司会" = "そう、ここにいる皆様は、既に選ばれたも同然！"
"2201-50" = "ふ～ん……？"
"2201-51-カヨコ" = "……？"
"2201-52-ムツキ" = "や、やっぱり！私たちは事業のチャンスを掴んだのよ！"
"2201-53-司会" = "それでは我が社の細かい話などはさておき、発表いたしましょう。"
"2201-54-司会" = "当社から皆様へ、自信を持ってお届けするアイテム。"
"2201-55-司会" = "それは……！"
"2201-56" = "（ジャジャーン！）"
"2201-57-司会" = "「カシミヤ仕立てのエコ・モバイルバッテリー」です！"
"2201-58-ムツキ" = "カシミヤ……？"
"2201-59-カヨコ" = "エコ……？"
"2201-60-アル" = "……バッテリー？"
"2201-61-ハルカ" = "……？？？"
"2201-62-司会" = "こちらはただのモバイルバッテリーではございません！"
"2201-63-司会" = "AIを使ったディープラーニングにより、最も効率的な素材を選び出し、それをふんだんに使って構成……"
"2201-64-司会" = "最高級の素材で、どんなバッテリーよりも優れた効率性を実現！"
"2201-65-ムツキ" = "アルちゃん、これさあ……。"
"2201-66-カヨコ" = "……はぁ。"
"2201-67-アル" = "ま、まだ分からないじゃない！もうちょっと聞くわよ……！"
"2201-68-アル" = "あの事業家の人が言ってたんだから……！"
"2201-69-司会" = "しかも当社が提供するのはこの製品だけではありません！"
"2201-70-司会" = "当社では独自のマーケティングシステムを用いて、利益を最大化するため……"
"2201-71-司会" = "リスクヘッジを十分考慮した事業戦略で……"
"2201-72-ハルカ" = "し、システム……リスクヘッジ……（めもめも）"
"2201-73-アル" = "……。"
"2201-74-司会" = "変動幅の大きいキヴォトスにおける経済指標を注意深く観察しながら、いかなる状況にも柔軟に対応できるよう……。"
"2201-75-ハルカ" = "け、経済指標……？"
"2201-76-ムツキ" = "（プルプル……）"
"2201-77-カヨコ" = "……ふぅ。"
"2201-78-ムツキ" = "（えぇ……）"
"2201-79-司会" = "では、ご説明はここまでにしましょう。"
"2201-80-司会" = "それではお待ちかねの、実際に私共への事業投資の方法ですが……。"
"2201-81-司会" = "難しいことは要求致しません。皆様は私共のサービスシステムに加入するため、この会員カードを購入するだけで大丈夫です！"
"2201-82-司会" = "会員カードを購入するだけで、自動的にこのシステムを利用できるようになります！"
"2201-83-司会" = "さらに今ならなんと！この500万円の会員カードを購入されると、天使としての階級が「セラフィム」まですぐに上昇！"
"2201-84-司会" = "お客様はすぐに、100人の天使を従えることができるのです！"
"2201-85-アル" = "盛りすぎでしょ！？マルチ商法まがいの怪しいビジネスに、オカルトまで混ぜるんじゃないわよっ！！！"
"2201-86-ムツキ" = "あはははっ！ついに言っちゃったねアルちゃん！"
"2201-87-ムツキ" = "マルチ商法まがいって認めちゃってるじゃん、あははっ！"
"2201-88-カヨコ" = "はあ……社長、ここのことを教えてきたその知人って……。"
"2201-89-ムツキ" = "分かってるから！もう何も言わないで！！"
"2201-90-ハルカ" = "あの、私がその知人の方、消しちゃいましょうか？"
"2201-91-ハルカ" = "うぅ……。"
"2201-92-カヨコ" = "まあ、トリニティで開かれる事業説明会って聞いた時から、もしかしてって思ったけど。"
"2201-93-カヨコ" = "世間知らずのお嬢様たちを狙ったものみたいだね。"
"2201-94-ムツキ" = "ぷははははっ！！それ自体はともかく、お嬢様たち狙いで引っ掛かったのがアルちゃんって……！ぷふっ！"
"2201-95-ムツキ" = "信じてたのに……私だけに教えるって言うから、信じてたのに……！"
"2201-96-アル" = "よくも、恩を仇で！！！"
"2201-97-司会" = "そ、そこのお客様！？何の騒ぎですか！？"
"2201-98-司会" = "私共はあくまでも健全な事業計画に基づいた機会を皆様に……"
"2201-99-アル" = "もういいわ。"
"2201-100-アル" = "よくも私たちの貴重な時間を、無駄にしてくれたわね。"
"2201-101-司会" = "お、お客様、何を……？これは二度とないチャンスで……！"
"2201-102-司会" = "夢と希望のチャンスをここで共に……！"
"2201-103" = "（ガッ）"
"2201-104-司会" = "え、いや、私の肩ではなく、チャンスを掴……"
"2201-105-司会" = "ハルカ。"
"2201-106-司会" = "は、はいっ！"
"2201-107-アル" = "やりなさい。"
"2201-108" = "はいっ！"
"2201-109" = "アル様のご命令なら！"
"2201-110-司会" = "うわあああっ！？な、何を！？"
"2201-111-ハルカ" = "あ、アル様の貴重な時間を……！全部、全部消します！！"
"2201-112-アル" = "……よくも私たち便利屋を騙そうとしてくれたわね。"
"2201-113-アル" = "一歩間違えたら、その巧妙な手口のせいで便利屋の資金が全部なくなるところだったじゃない！"
"2201-114-ムツキ" = "素直だねえアルちゃん。"
"2201-115-アル" = "ああもう！ムツキ！カヨコ！"
"2201-116-ムツキ" = "ま、十分楽しめたし、始めよっか！"
"2201-117-カヨコ" = "はあ……仕方ない。"
"2201-118" = "やってしまいなさい！！"
"2201-119-ハスミ" = "正義実現委員会です！"
"2201-120-ハスミ" = "こちらで違法な事業説明会が開かれてると通報を受けて来ました！"
"2201-121-マシロ" = "来ました！"
"2201-122-ハスミ" = "……？"
"2201-123-マシロ" = "……誰もいませんね？"
"2201-124-カヨコ" = "あっぶな～、よりにもよってトリニティの正義実現委員会！"
"2201-125-カヨコ" = "風紀委員会と同レベルに面倒な相手だね……そもそも接触しないのが吉。"
"2201-126-ムツキ" = "ま、あそこと絡むとうちの風紀委員長がすっごい顔するだろうから、それはそれで面白そうだけどね～。"
"2201-127-ハルカ" = "い、行ってきましょうか？ご命令いただければ、私が全部……！"
"2201-128-アル" = "ああもう！話をややこしくしないで！"
"2201-129-アル" = "はぁ……。"
"2201-130-アル" = "よし、今日のことはもう終わったこと！"
"2201-131-アル" = "これからは知人がむやみに勧めてくる事業とか……もう絶対に信じないんだから！"
"2201-132-アル" = "他人に頼る必要なんてないわ、私たちの事業は私たちの手で成功させる！！"
"2201-133-ムツキ" = "あはっ、アルちゃんらし～！"
"2201-134-カヨコ" = "はあ……まあ、こうなると思ってたけど。"
"2201-135-アル" = "ほら、早く離れるわよ！"
"2201-136-ハルカ" = "は、はいっ！"
"2201-137" = "（そして正義実現委員会から逃げるようにして、便利屋68はトリニティ地区の夜道を駆けていった）"
"2201-138" = "不健全な事業計画"
