[translation]
"1010705-1" = "書記の趣味生活"
"1010705-2" = "（いつものように仕事をしていると……）"
"1010705-3-チアキ" = "おはようございます、先生～！"
"1010705-4-チアキ" = "あっ、お仕事中でしたね。お邪魔でした……？"
"1010705-5" = "[s] \"大丈夫。ちょうど休憩に入ろうとしてたとこだよ。\""
"1010705-6-チアキ" = "そうですか。私もちょうど今週は休みを取ってまして！"
"1010705-7-チアキ" = "ん？特になにかあったわけではないですよ！"
"1010705-8-チアキ" = "定期休刊です！"
"1010705-9" = "[s] \"定期、休刊？\""
"1010705-10-チアキ" = "はい！"
"1010705-11-チアキ" = "「週刊万魔殿」は週刊誌ですから、普段は休む時間がないので、定期的に休刊する週を設けているんです！"
"1010705-12-チアキ" = "長く走るためには、リフレッシュが必要不可欠！"
"1010705-13-チアキ" = "好きだからこそ、長続きさせたい！って感じですかね～"
"1010705-14-チアキ" = "なので、2ヶ月に1回くらいは休刊しています！"
"1010705-15-チアキ" = "といっても他の仕事もあるので、休めるのは今日だけですけどね。"
"1010705-16-チアキ" = "あ、あれ？なんだかすごく羨ましそうな眼差しが……。"
"1010705-17-チアキ" = "はい？最近は休日すら休んでない？"
"1010705-18-チアキ" = "そ、そうでしたか……。"
"1010705-19-チアキ" = "じゃあ、今日は先生も休むことにしましょう！"
"1010705-20" = "[s] \"で、でもまだ仕事が……！\""
"1010705-21-チアキ" = "さっきも言った通り、リフレッシュは大事ですよ！"
"1010705-22-チアキ" = "一度ぐっすり休んだほうが、仕事のパフォーマンス的にも良いんですから！"
"1010705-23" = "[s] \"たしかに……一理あるかも……？\""
"1010705-24-チアキ" = "でしょでしょ？"
"1010705-25-チアキ" = "では、お休みスタート～！"
"1010705-26-チアキ" = "まず、机から離れて、ストレッチから～"
"1010705-27-チアキ" = "次は思いっきり昼寝をしたり、本を読んだり、ゲームをしたり～"
"1010705-28-チアキ" = "普段できなかった運動をするのもいいですね！趣味に全振り～！"
"1010705-29-チアキ" = "……え？休むのが久々すぎて何をすればいいか分からない……？"
"1010705-30" = "[s] \"チアキは普段、休みの日に何をするの？\""
"1010705-31-チアキ" = "私ですか？"
"1010705-32-チアキ" = "うーん……普通に好きなことをやってますね。"
"1010705-33" = "[s1] \"じゃあ、今日はチアキに合わせるね。\"\n[s2] \"チアキの趣味を教えてほしいな。\""
"1010705-34-チアキ" = "あ、いいですね、それ！"
"1010705-35-チアキ" = "先生と一緒だなんて、もうワクワクしてきます！"
"1010705-36-チアキ" = "もしかすると、次号の「週刊万魔殿」のネタになるかも！"
"1010705-37-チアキ" = "では、出発～！"
"1010705-38" = "[s] \"どこに行くの？\""
"1010705-39-チアキ" = "今から、私が趣味を楽しむ姿をお見せしますね！"
"1010705-40-チアキ" = "何をするのかは……ふふっ！"
"1010705-41-チアキ" = "行ってみれば分かります！"
"1010705-42" = "歴史研究部の部室"
"1010705-43-チアキ" = "やっほ～歴史研究部の皆さん、お久しぶりです～！"
"1010705-44-歴史研究部の部員A" = "あっ！チアキちゃん！"
"1010705-45-歴史研究部の部員B" = "久しぶり！元気してた？"
"1010705-46-チアキ" = "もちろん！超元気してましたよ～！"
"1010705-47" = "[ns] （チアキの趣味って……歴史研究？）"
"1010705-48-チアキ" = "部活はどうですか？"
"1010705-49-歴史研究部の部員A" = "まぁまぁかな？あ、そうだ！この前、チアキちゃんが探してくれた古書なんだけどさ。"
"1010705-50-歴史研究部の部員A" = "あれ、ニセモノらしいよ？"
"1010705-51-チアキ" = "えっ、本当ですか？お宝発見って感じだったのに！"
"1010705-52-歴史研究部の部員B" = "ははっ！いいのいいの！"
"1010705-53-歴史研究部の部員B" = "せっかくだし、なか入って。今お茶だすからね。"
"1010705-54-チアキ" = "ありがとうございます～！先生の分もお願いできますか？"
"1010705-55-歴史研究部の部員A" = "いいよ～！先生も入ってください！"
"1010705-56" = "[ns] \"チアキって、歴史研究部の所属でもあるの？\""
"1010705-57-チアキ" = "うーん。正確に言うと、客員メンバーですかね。"
"1010705-58-歴史研究部の部員A" = "正式な部員じゃないんですけど、たまに来てくれるんですよ。"
"1010705-59-チアキ" = "ですです！一[ruby=パンデモニウム・ソサエティー]応、万魔殿所属[/ruby]なんで！"
"1010705-60-チアキ" = "片足突っ込んでるって感じですかね？"
"1010705-61" = "[s] \"へぇ、そうなんだ。\""
"1010705-62-チアキ" = "あっ、もうこんな時間！"
"1010705-63-チアキ" = "そろそろ行かなきゃ！ではまた！"
"1010705-64-歴史研究部の部員A" = "うん！また来てね～！"
"1010705-65-チアキ" = "は～いっ！"
"1010705-66" = "[ns3] \"もっとゆっくりしても良かったのに。\"\n[ns4] \"せっかくの休日なのに。\""
"1010705-67-チアキ" = "うーん、そうしたい気持ちは山々ですが……。"
"1010705-68-チアキ" = "でも、歴史は趣味じゃないんで！"
"1010705-69" = "[s] \"違うの……？\""
"1010705-70-チアキ" = "さて、次行きましょうか！"
"1010705-71" = "キャッチボール同好会の練習会場"
"1010705-72-キャッチボール同好会のメンバーA" = "あ！チアキちゃん！"
"1010705-73-チアキ" = "おはようございます～今日も頑張ってますね！"
"1010705-74-キャッチボール同好会のメンバーB" = "久しぶり！チアキちゃん居ないと寂しいんだもん。"
"1010705-75-キャッチボール同好会のメンバーB" = "今日はちょっとだけプレイしてかない？"
"1010705-76-チアキ" = "はい！喜んで～！"
"1010705-77" = "[s] \"実は運動が趣味だったり？\""
"1010705-78-チアキ" = "あははっ、まあ、ここでも客員メンバーですね！#n正式な部員になるほどの腕はないので！"
"1010705-79-キャッチボール同好会のメンバーA" = "でも、チアキちゃん居ると部も盛り上がるからさ！"
"1010705-80-キャッチボール同好会のメンバーB" = "そうそう！なんなら毎日来てほしいくらい。"
"1010705-81-チアキ" = "あはっ！善処します！"
"1010705-82-チアキ" = "それじゃ！プレイボール！"
"1010705-83" = "ボードゲーム研究部の部室"
"1010705-84-チアキ" = "ぐぬぬ……ここでは、このカードが……。"
"1010705-85-ボードゲーム研究部の部員" = "ふふふっ、チアキちゃんってリアクションは一流だよね。#nゲームは下手なんだけど。"
"1010705-86-チアキ" = "ひっど～い！一世一代の悩みだったのにぃ！"
"1010705-87" = "グルメ巡り同好会の定例会"
"1010705-88" = "火力研究部の実験場"
"1010705-89-チアキ" = "いやぁ～これで一周しましたね！"
"1010705-90-チアキ" = "ふぅ、スッキリした！これぞまさに最高の休日！"
"1010705-91-チアキ" = "って、あれ。先生、疲れてるような……ちょっと、やりすぎましたか？"
"1010705-92" = "[s] \"ううん、大丈夫。それより……。\""
"1010705-93" = "[ns] \"結局、チアキの趣味って一体……？\""
"1010705-94-チアキ" = "お見せした通りですよ？"
"1010705-95-チアキ" = "色んな部活を掛け持ちして、何が本当の趣味なのか分からなくなった……？"
"1010705-96-チアキ" = "あはっ！そう思われたんですね！"
"1010705-97-チアキ" = "私の趣味は――人と会うことです！"
"1010705-98-チアキ" = "色んな人と会って、色んなことを喋る――"
"1010705-99-チアキ" = "そのために、様々な部活を掛け持ちしているんですよ～"
"1010705-100" = "[s5] \"そういえばチアキって、どの部活でも……。\"\n[s6] \"本格的に活動しているようには見えなかったね……。\""
"1010705-101-チアキ" = "ええっ、ひどいです！ま、事実ですけど。"
"1010705-102-チアキ" = "それではここで、本日のご感想をお聞きしましょう～！今日は先生のお休みでもありましたし。"
"1010705-103-チアキ" = "どうでしたか、私との休日は？"
"1010705-104" = "[s] \"うん、とても新鮮だったよ。\""
"1010705-105-チアキ" = "えへへ、さすがです！色んな人と会うの、やっぱり楽しいですよね？"
"1010705-106-チアキ" = "さて、そろそろお別れとしますか。"
"1010705-107-チアキ" = "執務室に戻って、次号の「週刊万魔殿」の編集をしなくちゃ！"
"1010705-108" = "[s7] \"い、今から仕事しに行くの？\"\n[s8] \"休みじゃなかったの？\""
"1010705-109-チアキ" = "ん？もう十分休みましたよ？"
"1010705-110-チアキ" = "友達とお喋りして、身体を動かす！#n私にとっては、これがリフレッシュですからね～！"
"1010705-111" = "[s] \"す、すごい……。\""
"1010705-112-チアキ" = "そうですかね？"
"1010705-113-チアキ" = "では！お先に失礼します～！"
