[translation]
"10020035-1-ホシノ" = "ぐっ……！！"
"10020035-2-ホシノ" = "と、止まって！……君は、一体誰？"
"10020035-3-アヤネ" = "また、逃げてしまいました……。"
"10020035-4-セリカ" = "ほ、ホシノ先輩……今のって……。 "
"10020035-5-ノノミ" = "私たちの知るシロコちゃんじゃないとは、一体どういう意味ですか……？"
"10020035-6-ホシノ" = "……。"
"10020035-7-ホシノ" = "シロコちゃんは……あんな目をしない。"
"10020035-8-ホシノ" = "アレは……"
"10020035-9-ユウカ" = "待たせたわね！ヒマリ先輩のおかげで、第4エリアの通信網をハッキングできたわよ！"
"10020035-10-アヤネ" = "第4エリアは、たしか……。"
"10020035-11-ユウカ" = "「[ruby=彼女]シロコ[/ruby]」の信号を捉えた位置よ。#n画面を映すから待ってちょうだい。"
"10020035-12-アヤネ" = "こ、ここは……。"
"10020035-13-アヤネ" = "し、シロコ先輩！？"
"10020035-14-ノノミ" = "シロコちゃん……？"
"10020035-15-シロコ" = "ん。やっと見つけてくれた。#n先生、みんな……待ってた。"
"10020035-16" = "[ns] \"シロコ、大丈夫！？怪我はない！？\""
"10020035-17-ノノミ" = "ん、大丈夫。#n自転車に乗って学校に向かってたら、拉致されただけ。"
"10020035-18-シロコ" = "人質になるのはセリカみたいな子だと思ってたから、油断してた。ごめん。 "
"10020035-19-セリカ" = "な、なっ！？ちょっとシロコ先輩？どういう意味！？"
"10020035-20-シロコ" = "でも、助けに来てくれるって分かってたから……大丈夫。#nちょっと体の節々が痛いだけ。"
"10020035-21-シロコ" = "それに……危害を加えてこないから、身代金目的みたい。"
"10020035-22-ホシノ" = "いやぁ、それにしてもシロコちゃん。人質なのにその格好はどうしたのさ？"
"10020035-23-シロコ" = "ん、これは……いつもバッグに入れてるから。#nチャンスは、準備された者に訪れるもの。"
"10020035-24-シロコ" = "少し前から、ここが襲撃を受けてるみたいだったから……#n脱出する時、隙を見て高そうな物を――"
"10020035-25-セリカ" = "こんな状況なのに……そんな計画を……"
"10020035-26-シロコ" = "う……んん……。 "
"10020035-27-ホシノ" = "うへ～……シロコちゃんは本当に、ピンチからチャンスを生み出す天才だねぇ。 "
"10020035-28-ホシノ" = "……でもさ、シロコちゃん。#nおじさん言ったでしょ。"
"10020035-29-シロコ" = "ん……。 "
"10020035-30-シロコ" = "「こんな方法に慣れちゃうと……ゆくゆくは、きっと平気で同じことをするようになる」……"
"10020035-31-シロコ" = "「そうやって学校を守ったって、何の意味があるのさ」って……言ってた。 "
"10020035-32-アヤネ" = "……。"
"10020035-33-ノノミ" = "……シロコちゃん。"
"10020035-34" = "シロコ先輩……本当に、シロコ先輩だ……"
"10020035-35-ホシノ" = "うへ～、よく覚えてるね。 "
"10020035-36-ホシノ" = "そこでじっとしてるんだよ？#nすぐ助けに行くから。"
"10020035-37-シロコ" = "ん。"
"10020035-38-ホシノ" = "積もる話は後で、ね。#nシロコちゃんが居ない間、本当いろんなことがあったんだよ？ほんっと、涙なしでは聞けないような話がいっぱいあるからさ……"
"10020035-39-シロコ" = "ん、待ってる。 "
"10020035-40-シロコ" = "ホシノ先輩、みんな、先生……#n助けに来てくれるって、知ってた。"
"10020035-41" = "[s] \"…………うん、当たり前だよ。\""
"10020035-42-シロコ" = "それじゃ――ここで――――ってるから―― "
"10020035-43-ホシノ" = "……。"
"10020035-44-ノノミ" = "シロコちゃん……。"
"10020035-45-ホシノ" = "……それじゃ、ちゃちゃっと次のエリアに行こっか。"
"10020035-46-ホシノ" = "――シロコちゃんがいる、第4エリアに。"
"10020035-47-アヤネ" = "はい！まだ、何が何だか分かりませんが…… "
"10020035-48-ノノミ" = "ですが、状況を理解するよりも、シロコちゃんを助ける方が先決です！"
"10020035-49-セリカ" = "待ってて、シロコ先輩……すぐに行くから！！"
"10020035-50-リン" = "残るはあと1つ――箱舟の最終エリア、中心部の第4エリアです。"
"10020035-51-アユム" = "あとは、ここを占領すれば……箱舟の管制システムを掌握できます。"
"10020035-52" = "これで「アトラ・ハシースの箱舟」もおしまいってわけ！#nとっとと自爆シーケンスを稼働させちゃお！"
"10020035-53-ヒマリ" = "本物のシロコさんがいる場所は、第4エリアの閉鎖されたセクションです。"
"10020035-54-ヒマリ" = "ですが、ここへ通じるゲートを開くには、箱舟の上層階に存在する「特別エリア」――その中にある制御室を破壊しなくてはなりません。"
"10020035-55-アヤネ" = "「特別エリア」……。"
"10020035-56-ヒマリ" = "はい。特別エリアは、物理的に箱舟と離れているため、ハッキングの影響を受けないのです。"
"10020035-57-ノノミ" = "つまり……誰かが「特別エリア」の制御室を破壊しなければ、シロコちゃんのいる部屋に辿り着けないのですね。"
"10020035-58-ヒマリ" = "ええ。破壊に成功すれば、シロコさんのいる第4エリアが開放されるでしょう。"
"10020035-59-ホシノ" = "……ま、それならやっぱり私たちの出番かな。"
"10020035-60-ホシノ" = "先生はその間に「次元エンジン」を破壊して、第4エリアの占領をお願いね。"
"10020035-61-ホシノ" = "シロコちゃんがちゃんと脱出できるよう、周りを綺麗にしておかないと。"
"10020035-62" = "[s] \"了解。みんな気を付けてね。\""
"10020035-63-ノノミ" = "はい、任せてください！"
"10020035-64-セリカ" = "「次元エンジン」は頼んだわよ！"
"10020035-65-ホシノ" = "んじゃ、私たちは「特別エリア」に行ってくるね。#nまた後で～"
"10020035-66-リン" = "さあ――「アトラ・ハシースの箱舟」占領戦、最後の戦いです。 "
"10020035-67-アユム" = "これが……本当に最後の戦いになるんですね。"
"10020035-68" = "それなんだけどさぁ……敵さんもこれが「最後」だって分かってるみたいだよ？"
"10020035-69-アユム" = "……？"
"10020035-70-モモカ" = "うわぁ……ものすごい数の敵がこっちに向かってきてる。 "
"10020035-71-アユム" = "はっ、はい！？ "
"10020035-72-リン" = "……もう一度、船の防衛が必要そうですね。"
"10020035-73-ハルナ" = "ふふっ。心配はご無用です。"
"10020035-74-ハルナ" = "ここの防衛は、私たちが担当いたします。"
"10020035-75-ジュンコ" = "ここまで来ちゃったんだし、しょうがないわね。"
"10020035-76" = "ええ、派手にいきましょうか★"
"10020035-77-イズミ" = "ところで、宇宙食はいつになったら食べれるの～？"
"10020035-78-ユズ" = "こっちは、わたし達がなんとか守ります……！"
"10020035-79-アリス" = "はい。ここはアリスたちに任せてください、先生。 "
"10020035-80-アリス" = "アリスちゃん……体は大丈夫？"
"10020035-81-アリス" = "はい。まだHP全快とまではいきませんが、みんなと一緒なら戦えます！"
"10020035-82-アリス" = "でも無理はしないでね、アリス！ "
"10020035-83-アリス" = "はい！"
"10020035-84-リン" = "先生……では、最後の占領戦もよろしくお願いします。"
