[translation]
"70015010-1" = "イブキ家出事件（１）"
"70015010-2" = "万魔殿・執務室"
"70015010-3-イブキ" = "うわーん！！"
"70015010-4-イブキ" = "マコト先輩なんてもう知らない！！！"
"70015010-5-マコト" = "イブキィー！"
"70015010-6-イロハ" = "はぁ……またですか。"
"70015010-7-イロハ" = "またとはなんだ！またとは！"
"70015010-8-マコト" = "イロハ！なぜプリンに名前を書いていない！？"
"70015010-9-イロハ" = "いや、書いたら私のを食べるじゃないですか。"
"70015010-10-マコト" = "当たり前だ！イブキのを食べるわけにはいかんからな！"
"70015010-11-イロハ" = "誰のでもダメです！自分で買ってきてください。"
"70015010-12-イロハ" = "くっ……！このマコト様が同じ過ちを繰り返すとは……！"
"70015010-13-サツキ" = "どうするの？イブキちゃん、どこかへ行っちゃったわよ。"
"70015010-14-サツキ" = "あの様子を見る限り、今回は長引きそうね。"
"70015010-15-マコト" = "くっ……。"
"70015010-16-チアキ" = "イブキちゃん、一人で大丈夫でしょうか？"
"70015010-17-チアキ" = "学園内にいる限りは大丈夫だと思うけど……。"
"70015010-18-サツキ" = "そ、そうですよね！"
"70015010-19-マコト" = "い、イブキ……許してくれ……。"
"70015010-20-투명" = "抜け殻のようになってますね……。"
"70015010-21-투명" = "イブキちゃんが行きそうな場所を探してみましょう！#nきっと寂しい思いをしているはずです！"
"70015010-22-マコト" = "あ、ああ！イブキィー！どこにいるー！"
"70015010-23-サツキ" = "そんなに遠くへは行っていないと思うけど……。#nキッズスペースや、イロハのアジト辺りにいるんじゃないかしら？"
"70015010-24-イロハ" = "そうですね、早いところ見つけてあげましょう。"
"70015010-25" = "（マコトたちは辺りをしらみ潰しに探したが……）"
"70015010-26-マコト" = "イブキィー！"
"70015010-27-マコト" = "イブキィーー！！"
"70015010-28-マコト" = "イブキィーーー！！！"
"70015010-29" = "（イブキは見つからなかった……）"
"70015010-30-？？？" = "くふふっ、今日は運が良かったね～"
"70015010-31-？？？" = "う、運じゃないわ！実力よ！"
"70015010-32-？？？" = "そうだね～、そういうことにしとこっか！"
"70015010-33-アル" = "最近は実入りのいい仕事がたくさん入ってきているのよ！#nふふっ、とうとう私たちが世間に認められたんだわ！"
"70015010-34-アル" = "えへへ……アル様は世界一のアウトローですから……。"
"70015010-35-アル" = "あ、ありがとう……！でも、今日はハルカが大活躍だったじゃない！#nその調子でこれからもよろしくね！"
"70015010-36-ハルカ" = "そ、そんな、身に余るお言葉……！"
"70015010-37-ハルカ" = "ありがとうございます、ありがとうございます、ありがとうございます……！"
"70015010-38-ムツキ" = "おかげで今月は余裕ありそうだよね♪"
"70015010-39-ムツキ" = "ええ。事務所の家賃もバッチリよ！"
"70015010-40-ムツキ" = "前に野宿してたところも好きだったけどね。#n風もあんまり当たらなかったし。"
"70015010-41-アル" = "あ、あれは忘れていいの！目標はもっと高く持たないと！"
"70015010-42-アル" = "そう？なら今度の依頼主の事務所みたいに……。#n都心の個室付き最高級ペントハウスにするのはどう？"
"70015010-43-アル" = "（ゴクリ……）"
"70015010-44-アル" = "え、ええ！いいわ！そのくらい余裕よ！……多分。"
"70015010-45-カヨコ" = "あれ？あの子……。"
"70015010-46-イブキ" = "……むぅ。"
"70015010-47-イブキ" = "マコト先輩の嘘つき。"
"70015010-48-イブキ" = "もうイブキのプリン食べないって約束したのに。"
"70015010-49-イブキ" = "マコト先輩のバカ。"
"70015010-50-イブキ" = "……。"
"70015010-51-イブキ" = "うぅ……いじわる言ってごめんなさい……。"
"70015010-52-イブキ" = "……ううん！イブキのプリンを食べたマコト先輩が悪いんだもん！"
"70015010-53-イブキ" = "……。"
"70015010-54-イブキ" = "ひぐっ。"
"70015010-55-イブキ" = "あれ？ここ、どこだろう……。"
"70015010-56-イブキ" = "知らないところだ。"
"70015010-57-イブキ" = "うぅ……。"
"70015010-58-カヨコ" = "カヨコ？何を見てるの？"
"70015010-59-カヨコ" = "えっと、あそこに……。"
"70015010-60-アル" = "あら、小さい子ね。一人かしら。"
"70015010-61-アル" = "迷子なら保護者を探してあげないと！"
"70015010-62-カヨコ" = "社長……あの子は――"
"70015010-63-カヨコ" = "行っちゃった。"
"70015010-64-カヨコ" = "……なんでイブキがこんなところに？"
"70015010-65-アル" = "こんにちは、かわいいお嬢ちゃん。どうしたのかしら？"
"70015010-66-イブキ" = "……あ、こんにちは。綺麗なおねえちゃん。"
"70015010-67-アル" = "き、綺麗……。"
"70015010-68-アル" = "こ、この子見る目あるじゃない！気に入ったわ！"
"70015010-69-アル" = "安心してね。お姉ちゃんがちゃんと元いたところに連れていってあげるから。"
"70015010-70-イブキ" = "おねえちゃん、イブキがどこから来たのか知ってるの？"
"70015010-71-アル" = "それはこれから……。"
"70015010-72-イブキ" = "待って、あなた……。"
"70015010-73-イブキ" = "もしかして……。"
"70015010-74-アル" = "[ruby=パンデモニウム・ソサエティー]万魔殿！？[/ruby]"
"70015010-75-イブキ" = "うん、そうだよ！"
"70015010-76-アル" = "万魔殿！？！？"
"70015010-77-アル" = "どこかで見たことあると思ったけど……あそこの子だったなんて……。"
"70015010-78-アル" = "ど、どうしましょう……？"
"70015010-79-アル" = "どうするも何も、できるだけ関わらない方が良いに決まってるじゃない。"
"70015010-80-アル" = "ゲヘナ学園の近くまで連れて行ったら、勝手に帰るわよ。"
"70015010-81-アル" = "ダメよ！この子は今一人で不安になっているはず。私たちが助けないと！"
"70015010-82-アル" = "バカなこと言わないで！ゲヘナとはもう関わらないって決めたでしょ！"
"70015010-83-アル" = "しかも、よりにもよってあの万魔殿と！一体なにが起こるか……。"
"70015010-84-アル" = "子どもが一人の時どれだけ心細いか、あなたは知っているでしょう？#nそばにいてあげないとダメよ。"
"70015010-85-アル" = "う、うーん……。"
"70015010-86-イブキ" = "おねえちゃん、すごい汗だよ？どこか痛いの？"
"70015010-87-アル" = "（この子……一人で不安なはずなのに、私のことを気にかけて……）"
"70015010-88-アル" = "いいわ……あなたを、万魔殿まで送ってあげる！"
"70015010-89-カヨコ" = "……アルちゃん、本気で万魔殿に行くつもり？"
"70015010-90-アル" = "……ええ！だって、私がやるべきことだもの！"
"70015010-91-カヨコ" = "そう思った経緯は大体予想がつくけど……一度落ち着いて、社長。"
"70015010-92-アル" = "ハードボイルドなアウトローたるもの……迷える子羊を見たら、正しく導かないと！"
"70015010-93-カヨコ" = "ハードボイルドかどうかはともかく、アウトローではないと思うけど……。"
"70015010-94-イブキ" = "やだ！帰らない！"
"70015010-95-イブキ" = "マコト先輩がイブキのプリン食べちゃったんだもん！"
"70015010-96-イブキ" = "だからもう帰らない！"
"70015010-97-アル" = "……そ、そう……？"
"70015010-98-アル" = "ど、どうするのよ……これ……。"
