[translation]
"1300606-1" = "誰かからの特別な依頼"
"1300606-2-ムツキ" = "やっほー、先生！こっちこっち～。"
"1300606-3" = "[s] \"変な依頼って、どんなの？\""
"1300606-4-ムツキ" = "あははっ、それがさあ、すっごい変っていうか～。"
"1300606-5-ムツキ" = "何て言えばいいんだろ、うーん……。"
"1300606-6-ムツキ" = "どうしても先生に手伝ってほしい依頼って感じ？"
"1300606-7" = "[s1] \"ムツキがすっごい変って言うほどの依頼って一体……。\"\n[s2] \"ムツキが手伝ってって言うほどの依頼って一体……。\""
"1300606-8-ムツキ" = "くふふっ。さあ、どうでしょう～？"
"1300606-9-ムツキ" = "くふふっ。さあ、どうでしょう～？"
"1300606-10-ムツキ" = "ほらほら、こんなに生徒が困ってるんだから、先生としてはもちろん放っておけないよね？付き合ってあげるしかないよね？"
"1300606-11" = "[s] \"ところで便利屋の依頼なのに、どうしてムツキ一人で……。\""
"1300606-12-ムツキ" = "付　き　合　っ　て　く　れ　る　よ　ね　？"
"1300606-13-ムツキ" = "ね　？\n"
"1300606-14-ムツキ" = "まあ先生だってわざわざここまで来てくれたんだし、そもそも最初から先生に拒否権はないんだけど～！"
"1300606-15" = "[s3] \"……拒否権、ないんだ。\"\n[s4] \"まあ、仕方ないかな……。\""
"1300606-16-ムツキ" = "あははっ、うん！でもどう転んでもきっと、先生は助けてくれたでしょ？"
"1300606-17-ムツキ" = "あははっ、うん！でもどう転んでもきっと、先生は助けてくれたでしょ？"
"1300606-18" = "[s] \"うーん……ところで依頼って、何からすれば良いの？\""
"1300606-19-ムツキ" = "この依頼書の中にやることがリストで書かれてるから、その通りにやろっか？"
"1300606-20" = "[s] \"そっか、ちょっと見せてくれる？\""
"1300606-21-ムツキ" = "あはっ、それはダメかな～！"
"1300606-22-ムツキ" = "顧客の個人情報は大事でしょ～？"
"1300606-23-ムツキ" = "いくら先生とは言っても、これは簡単には見せられないなぁ。"
"1300606-24" = "[s] \"さすが……ムツキもプロなんだね。\""
"1300606-25-ムツキ" = "くふふっ。そうそう、こう見えてもプロだも～ん。"
"1300606-26-ムツキ" = "それじゃあお待ちかね、1つ目の依頼ね。ふむふむ……。"
"1300606-27-ムツキ" = "その内容は～……。"
"1300606-28" = "自家製デザートのお店・アマッタルィ"
"1300606-29" = "[ns] \"……本当に、そういう依頼なの？\""
"1300606-30-ムツキ" = "うん！依頼の内容によると、「このお店で売ってる全てのクレープを食べた後……」"
"1300606-31-ムツキ" = "「その中でナンバーワンの、『最高』のクレープを選んでください」だって！"
"1300606-32" = "[s5] \"最高のクレープ……！\"\n[s6] \"メニュー、10種類以上あるけど……？\""
"1300606-33-ムツキ" = "あはっ。ナンバーワンを決めるのは大事だからね～。問題は予算だけど……。"
"1300606-34-ムツキ" = "うーん。まっ、大丈夫かな？"
"1300606-35-ムツキ" = "大丈夫大丈夫、全部食べられるよ。それに……。"
"1300606-36-ムツキ" = "お金については、先生に経費として処理してもらえばいいもんね～～♪"
"1300606-37" = "[s] \"えっ……。\""
"1300606-38-ムツキ" = "ん～？生徒のお願いなんだから、もちろん聞いてくれるよね？先生～？"
"1300606-39-ムツキ" = "大切な生徒が依頼を解決しようと、こ～んなに頑張ってるんだから。"
"1300606-40-ムツキ" = "もしかして……。"
"1300606-41-ムツキ" = "ダメ、なの……？"
"1300606-42" = "[s] \"くっ……！お、大人の財布を甘く見ないで！\""
"1300606-43-ムツキ" = "あはははっ！ありがとっ、先生！"
"1300606-44-ムツキ" = "はむっ、ん～♪やっぱりイチゴは美味し～！"
"1300606-45-ムツキ" = "もぐもぐ、バナナも優しい甘さでさいこ～！"
"1300606-46-ムツキ" = "先生はどう？"
"1300606-47" = "[s7] \"イチゴ、バナナ、チョコ……クレープがこんなに……。\"\n[s8] \"口の中が甘さだらけで、甘さのゲシュタルト崩壊が……。\""
"1300606-48-ムツキ" = "くふふっ、先生頑張って！もうそんなに残ってないよ！ファイト～！"
"1300606-49-ムツキ" = "くふふっ、先生頑張って！もうそんなに残ってないよ！ファイト～！"
"1300606-50" = "[s] \"う、うん……！\""
"1300606-51" = "（そうして、ムツキと一緒に大量のクレープを食べ尽くした）"
"1300606-52-ムツキ" = "あははっ、最高のクレープか～。う～ん、やっぱりそんな簡単に決められないかもね～？"
"1300606-53" = "[s] \"うぅ……まだ口の中が甘い……。\""
"1300606-54-ムツキ" = "まっ、それは一旦置いといて～。次の依頼に行こっか！"
"1300606-55" = "[s] \"次の依頼、この遊園地に関係してるの？\""
"1300606-56-ムツキ" = "2つ目の依頼も簡単だよ～。"
"1300606-57-ムツキ" = "えっとね……。"
"1300606-58-ムツキ" = "「この遊園地にあるメリーゴーランドの中で、どの馬が一番速いのかを調査してほしい」、だって！"
"1300606-59" = "[ns9] \"……メリーゴーランド？\"\n[ns10] \"……一番速い馬？\""
"1300606-60" = "[ns] \"それ……速さの違い、あるのかな？\""
"1300606-61-ムツキ" = "ほらほら、先生。そんなこと言わないで取り合えず試してみよっ、私はあの赤い馬にする！"
"1300606-62-ムツキ" = "きっと他の馬より三倍ぐらい早いよ！"
"1300606-63-ムツキ" = "あ！動き始めた！"
"1300606-64" = "[s] \"う、うーーん……？\""
"1300606-65" = "（当たり前ながら、メリーゴーランドの馬たちはみんな同じ速度だった……）"
"1300606-66-ムツキ" = "あははっ。速さはみんな同じだったね！まっ、それもそっか～。"
"1300606-67-ムツキ" = "くふふっ。じゃあ3つ目の依頼を始めよう、先生！"
"1300606-68" = "[s] \"う、うん……。\""
"1300606-69" = "ゲヘナ・第13図書館"
"1300606-70-ムツキ" = "さて。今度の依頼の場所はここ、図書館だよ。（ひそひそ）"
"1300606-71" = "[s] \"次の依頼はどんな内容なの？（ひそひそ）\""
"1300606-72-ムツキ" = "それは、えっとね……。"
"1300606-73-ムツキ" = "「誰にもバレないように、本棚の本を全部、上下逆さまにしてください」だって。"
"1300606-74" = "[s] \"えっと、それはただの迷惑な行為なのでは……。\""
"1300606-75-ムツキ" = "依頼だから、ね？全部終わったらまた戻しておけばいいでしょ？ねっ、お願い先生？"
"1300606-76" = "[s11] \"まあ依頼でもあるし、後でまた戻しておくなら……\"\n[s12] \"はあ、仕方ないね……。\""
"1300606-77-ムツキ" = "あはっ♡ありがと～先生！"
"1300606-78-ムツキ" = "あはっ♡ありがと～先生！"
"1300606-79" = "（その後も、ムツキに連れ回されるまま、あちこちで色々な依頼を実行した）"
"1300606-80" = "（そうして、どれぐらい歩いた頃だろう）"
"1300606-81" = "[ns] \"もう結構な数の依頼をやった気がするね。\""
"1300606-82-ムツキ" = "くふふっ、そうだね～。"
"1300606-83" = "[s] \"あとどれぐらい？\""
"1300606-84-ムツキ" = "うーん、えっとね……。"
"1300606-85-ムツキ" = "残りの依頼は確か……。"
"1300606-86-ムツキ" = "あっ！紙が……！"
"1300606-87" = "（ムツキの手から離れた紙が、空へと舞い上がった）"
"1300606-88" = "[ns13] \"大丈夫！このくらいの高さなら……！\"\n[ns14] \"……ふぅ、取れてよかった。えっと、残りの依頼が……。\""
"1300606-89-ムツキ" = "あっ、先生、中は見ちゃ……！"
"1300606-90-ムツキ" = "あっ、先生、中は見ちゃ……！"
"1300606-91" = "[ns] \"ん？これ、依頼人の名前……。\""
"1300606-92" = "[ns] \"依頼人の名前が、ムツキ……？\""
"1300606-93-ムツキ" = "もー、見ちゃダメっ！"
"1300606-94" = "[ns] \"あっ、あれっ！？ムツキ！？\""
"1300606-95" = "[wa:100]― あ～あ、[wa:1050]ざーんねんっ。"
"1300606-96" = "― くふふっ、[wa:1120]バレちゃったかぁ～♪"
"1300606-97" = "[wa:100]― 何を隠そう、[wa:1300]今日の[wa:300]可愛い依頼人の正体は[wa:2150]他でもない、"
"1300606-98" = "― このムツキちゃんなのでした～。"
"1300606-99" = "― 考えても[wa:600]みてよ先生～。"
"1300606-100" = "― そもそも便利屋の依頼を、[wa:1250]私一人で[wa:700]解決しに行くわけないじゃん？"
"1300606-101" = "[wa:100]― あはっ、[wa:700]どうだった？[wa:600]先生？"
"1300606-102" = "― 私のいたずら、[wa:1200]ほぼ完璧だったでしょ？"
"1300606-103" = "[wa:50]― きゃはっ、[wa:1050]なぁに先生、[wa:1450]その間抜けな顔。"
"1300606-104" = "[wa:200]― うける！[wa:900]あはは～っ♪"
"1300606-105" = "[wa:900]― 今日は[wa:400]先生と、[wa:750]いろんなことしたねー。"
"1300606-106" = "― クレープ食べて、[wa:1200]遊園地にも行って、"
"1300606-107" = "― あ、[wa:600]図書館では[wa:700]共犯にもなっちゃったし……！"
"1300606-108" = "[wa:100]― あ～あ、[wa:1150]最後まで[wa:500]完璧に騙せると思ったのに、[wa:2100]残念だな～。"
"1300606-109" = "― でも[wa:500]今度は、[wa:700]絶対に最後まで[wa:850]騙し通してみせるから、"
"1300606-110" = "― 楽しみにしといてね～！"
"1300606-111" = "[wa:100]― あーっ、[wa:1400]今日は[wa:500]ほんっと、[wa:1400]楽しかった！"
"1300606-112-ムツキ" = "それじゃ、今日はもういたずらもバレちゃったことだし～、私はこれで！"
"1300606-113" = "[ns] \"やられた……。\""
"1300606-114" = "（けらけらと楽しそうに笑いながら手を振るムツキが見えなくなるまで、その場で固まったまま動けなかった）"
