[translation]
"1001206-1" = "デート"
"1001206-2" = "ミレニアム近郊・ショッピングモール"
"1001206-3-スミレ" = "……。"
"1001206-4-スミレ" = "あっ、トレーナー！"
"1001206-5-スミレ" = "お待ちしておりました！"
"1001206-6-スミレ" = "え？筋トレグッズ……？"
"1001206-7-スミレ" = "いえいえ！今日はそうではなく……。"
"1001206-8-スミレ" = "その、ここ以外にちょうど良い場所が思い浮かばず、ここにしてしまったのですが。"
"1001206-9-スミレ" = "なんだか、トレーナーとは毎回運動のことしか話してない気がしていたので……。"
"1001206-10-スミレ" = "今日は運動とは関係ないお話もしたいな、と……。"
"1001206-11-スミレ" = "……。"
"1001206-12-スミレ" = "す、すみません！トレーナー！"
"1001206-13-スミレ" = "ただでさえお忙しいのに、私の都合でお呼びしてしまい！"
"1001206-14" = "[s1] \"ううん、スミレと他のことも話してみたいな。\"\n[s2] \"……デート？\""
"1001206-15-スミレ" = "ほ、本当ですか？"
"1001206-16-スミレ" = "ありがとうございます、トレーナー！"
"1001206-17-スミレ" = "！？"
"1001206-18-スミレ" = "え？で、デートですか？い、いや、わ、私がそんな……！"
"1001206-19-スミレ" = "いえその、嫌というわけでは……！"
"1001206-20-スミレ" = "う、うぅ……。"
"1001206-21" = "[s] \"どこに行こっか？\""
"1001206-22-スミレ" = "あ、実は今日、糖分や脂肪を好きなだけ摂取しても問題ない日なんです。"
"1001206-23-スミレ" = "いわゆるチートデー、というものですね。"
"1001206-24-スミレ" = "なのでよろしければ、何か食べに行きませんか？"
"1001206-25" = "[s] \"じゃあ甘いもの食べに行こう！\""
"1001206-26-スミレ" = "はい！"
"1001206-27-スミレ" = "わあ……。"
"1001206-28-スミレ" = "友人から話を聞いたり、外から見たりはしていましたが。"
"1001206-29-スミレ" = "こういうところは、私にはあまり縁のないところだなと思っていました。"
"1001206-30-スミレ" = "こうして来てみると、可愛いものでいっぱいですね。"
"1001206-31-スミレ" = "もうすでに、ここに来て良かったです、トレーナー。"
"1001206-32-店員" = "ご注文はいかがなさいますか？"
"1001206-33-スミレ" = "あっ、ちょっと待ってください。"
"1001206-34-スミレ" = "うーん……。"
"1001206-35-スミレ" = "あっ、このケーキ……。"
"1001206-36-スミレ" = "すごく可愛いです……！"
"1001206-37" = "[s] \"それにする？\""
"1001206-38-スミレ" = "はい！"
"1001206-39-スミレ" = "あっ、すみませんその前に。"
"1001206-40-スミレ" = "店員さん、質問してもよろしいでしょうか？"
"1001206-41-店員" = "はい、なんでしょう？"
"1001206-42-スミレ" = "この可愛いマスコットが付いたケーキについてなのですが、"
"1001206-43-スミレ" = "成分表はありますか？"
"1001206-44-店員" = "……はい？"
"1001206-45-スミレ" = "全体のカロリー、糖分、脂肪分、それぞれどのくらいなのか。"
"1001206-46-スミレ" = "こういったものに求めるものではないかもしれませんが、たんぱく質の含有量も気になります。"
"1001206-47-店員" = "え、えっと……それは……。"
"1001206-48" = "[s] \"あの、スミレ……？\""
"1001206-49-スミレ" = "はい、なんでしょう？"
"1001206-50-スミレ" = "……あっ。"
"1001206-51-スミレ" = "わ、私また……す、すみません！"
"1001206-52-スミレ" = "すみません、今言ったことは気にしないでください……。"
"1001206-53" = "（その後、頼んだスイーツを受け取って、カフェの中の席に座った）"
"1001206-54-スミレ" = "すみませんトレーナー、つい……。"
"1001206-55-スミレ" = "ダイエット中というわけではないのですが、食事の成分を把握することはトレーニングの基礎と言いますか……。"
"1001206-56-スミレ" = "筋肉を鍛えるためにも、そうでなくても体の健康を維持するためにも、正しい知識に基づいた食生活は大切なんです。"
"1001206-57-スミレ" = "そういえば、以前お送りしたプロテインはちゃんと飲まれてますか？"
"1001206-58-スミレ" = "ご存知かと思いますが、一般的な食事でのたんぱく質の摂取量には自ずと限界があります。"
"1001206-59-スミレ" = "そこで、プロテインを飲むことで手軽に、そして非常に生物価の高いタンパク質が得られるんです。"
"1001206-60-スミレ" = "ここでいう生物価とは、健康の維持と身体の成長に使われる栄養素における――"
"1001206-61" = "[s3] \"あの、スミレ……？\"\n[s4] \"スイーツが……。\""
"1001206-62-スミレ" = "……あ。"
"1001206-63-スミレ" = "……あ。"
"1001206-64-スミレ" = "つ、つい……！"
"1001206-65-スミレ" = "すみません、トレーナー。"
"1001206-66-スミレ" = "また私、ひとりで興奮してしまって……。"
"1001206-67-スミレ" = "運動の話になるとどうしても……。"
"1001206-68-スミレ" = "申し訳ありません。トレーナー。"
"1001206-69" = "[s] \"ううん、とりあえず食べよっか。\""
"1001206-70-スミレ" = "……はい、トレーナー。"
"1001206-71" = "（スミレと一緒に、美味しくスイーツを頂いた）"
"1001206-72" = "[ns] \"さて、そろそろ帰ろっか？\""
"1001206-73-スミレ" = "……はい。"
"1001206-74-スミレ" = "え？顔色……？"
"1001206-75-スミレ" = "そ、それは……。"
"1001206-76-スミレ" = "結局、今日もつい運動の話ばかりしてしまったなと、思いまして……。"
"1001206-77-スミレ" = "今日だけは、普通の会話をしたかったのに。"
"1001206-78" = "[s5] \"普通の会話が出来て楽しかったよ。\"\n[s6] \"スミレと私の、普通の会話。\""
"1001206-79-スミレ" = "……ふふっ。"
"1001206-80-スミレ" = "……ふふっ。"
"1001206-81-スミレ" = "はい、そうかもしれませんね。"
"1001206-82-店員" = "あの、お客様！"
"1001206-83-スミレ" = "……私ですか？"
"1001206-84-店員" = "お客様が購入されたケーキが現在イベントの対象になっておりまして、先着でぬいぐるみをお渡ししているんです。"
"1001206-85-店員" = "もう無いと思っていたのですが、あらためて在庫を確認してみたらまだ一つ残ってまして。どうぞ！"
"1001206-86-スミレ" = "か、可愛い……。"
"1001206-87-店員" = "それでは、またお越しください！"
"1001206-88-スミレ" = "トレーナー……！"
"1001206-89-スミレ" = "この子、すごく可愛いです……！"
"1001206-90" = "[s] \"うん、良かったね。\""
"1001206-91-スミレ" = "ふふっ、はい！"
"1001206-92-スミレ" = "トレーナーと一緒にいると、いつも最後には楽しくて幸せになります。"
"1001206-93-スミレ" = "あの、トレーナー。"
"1001206-94-スミレ" = "これからもトレーナーと一緒に、トレーニングを含め、色々なことをしていきたいです。"
"1001206-95-スミレ" = "なので、あらためて。"
"1001206-96-スミレ" = "よろしくお願いします、トレーナー。"
