[translation]
"1001205-1" = "トレーナーも一緒に"
"1001205-2" = "ミレニアム・ジム"
"1001205-3-スミレ" = "トレーナー！いらっしゃいましたか。"
"1001205-4-スミレ" = "お待ちしておりました。"
"1001205-5-スミレ" = "今日の身体の調子はいかがですか？"
"1001205-6" = "[s] \"ん？良いと思うけど。\""
"1001205-7-スミレ" = "はい、確かに良さそうですね。"
"1001205-8-スミレ" = "「実行」するのには、最適な状態のようです。"
"1001205-9-スミレ" = "はい？何を実行するのか、ですか？"
"1001205-10-スミレ" = "ふふっ。それは、これです！"
"1001205-11" = "（スミレが渡してきたスマホの中に、トレーニングのメニューが書いてあった）"
"1001205-12" = "[s] \"また別のトレーニングメニューを作ったの？\""
"1001205-13-スミレ" = "私のいつものメニューでは少し難しそうでしたので。"
"1001205-14-スミレ" = "はい？いつも私がやってるトレーニングは、って？"
"1001205-15-スミレ" = "……それは、いつも通りですが？"
"1001205-16" = "[s] \"一日にトレーニングメニューを2つもこなすってこと？\""
"1001205-17-スミレ" = "えーっと……。"
"1001205-18-スミレ" = "すみません、トレーナー。仰ってる意味がよく分かりませんでした。"
"1001205-19-スミレ" = "そもそもそのメニューは私のためのものではありません。もう一度読んでみてください。"
"1001205-20" = "[s] スミレが言った通り、メニューをもう一度確認する。"
"1001205-21" = "（トレーナーのトレーニングメニュー、か……おかしい所は……ん？！待って！？）"
"1001205-22" = "[s] \"ここに書いてある「トレーナー」ってもしかして……？\""
"1001205-23-スミレ" = "はい！[USERNAME]トレーナーのためのメニューです！"
"1001205-24-スミレ" = "ふふっ、いかがですか？お気に召しましたか？"
"1001205-25-スミレ" = "私が今まで培ってきたトレーニングの知識を使って、全身全霊で作ったメニューです！"
"1001205-26-スミレ" = "まずは、トレーニングを始める前に軽くストレッチを10分ほど、ですね。"
"1001205-27-スミレ" = "その後は、ランニングマシンでウォームアップを20分ほど行って……。"
"1001205-28" = "[s1] \"ちょ、ちょっと待って！！\"\n[s2] \"異議あり！！\""
"1001205-29-スミレ" = "はい？どうされましたか？"
"1001205-30-スミレ" = "はい？どうされましたか？"
"1001205-31-スミレ" = "もしかして……やはりトレーナーにとっては楽すぎるメニューでしたか？"
"1001205-32-スミレ" = "ウォームアップ後、軽いウェイトトレーニングをメインに組んでいたのですが……。"
"1001205-33-スミレ" = "しかし！こんなこともあろうかとプランBのメニューも作っておきました。"
"1001205-34-スミレ" = "見てください、トレーナー！こちらの方にですね……。"
"1001205-35" = "[s] \"い、いや、さっきのがちょうどいいと思う！\""
"1001205-36-スミレ" = "え？本当ですか？"
"1001205-37-スミレ" = "何となく、少しだけご不満そうな表情をされている気がしますが。"
"1001205-38" = "[s] \"違うよ！さっきのすごく良い！やっぱりスミレは最高！\""
"1001205-39-スミレ" = "あはは、変なトレーナーですね。"
"1001205-40-スミレ" = "さあ、そうしたら今日は特別に！"
"1001205-41-スミレ" = "私がトレーナーの「トレーナー」になってあげましょう。"
"1001205-42-スミレ" = "はい？私のトレーニングはどうするのか、ですか？"
"1001205-43-スミレ" = "さすがトレーナー、いつも私のことを気にかけてくれますね。ありがとうございます。"
"1001205-44-スミレ" = "もちろん、トレーナーがいらっしゃる前に私の今日の分の運動はすでに終わらせておきました。"
"1001205-45-スミレ" = "ん？大丈夫ですか、少し顔色が悪いですが……。"
"1001205-46-スミレ" = "ああ！早くトレーニングをしたいということですね？"
"1001205-47-スミレ" = "分かりました！それでは今すぐ始めましょう！"
"1001205-48-スミレ" = "さあさあ、早く、今すぐに！！"
"1001205-49" = "（結局スミレのメニュー通り、ストレッチをした後ランニングマシンで走った）"
"1001205-50-スミレ" = "はあ、はあ……。"
"1001205-51-スミレ" = "軽いランニングならいけそうかと思って、トレーナーと一緒に走ってみましたが……。"
"1001205-52-スミレ" = "トレーニングをした後だからか、すぐに疲れてしまいました……。"
"1001205-53-スミレ" = "トレーナーもお疲れのようですし、少し休みますか？"
"1001205-54" = "[s] \"はあ、はあ……そうしよう……。\""
"1001205-55" = "― どうですかトレーナー、[wa:3200]運動は、[wa:1300]楽しいでしょう？"
"1001205-56" = "― 健康になる感じが、[wa:1500]しませんか？"
"1001205-57" = "― あ、[wa:1000]えっと……[wa:1500]あ、[wa:1000]あまり見つめないでください。"
"1001205-58" = "― （トレーニング中はひどい見た目だし……）"
"1001205-59" = "― ど、[wa:1000]どこを見てるんですか……？"
"1001205-60" = "― ……トレーナー、[wa:2500]お願いがあります。"
"1001205-61" = "― これからも、[wa:2500]ずっと一緒に運動をしましょう。"
"1001205-62" = "― 私は[wa:1000]トレーナーが[wa:1000]健康でいてほしいです。"
"1001205-63" = "[wa:300]― り、[wa:700]理由ですか？[wa:2000]そ、[wa:500]それは……[wa:3000]ふふっ。"
"1001205-64" = "― 当ててみてください。"
"1001205-65" = "（その後スミレに付き合ってもらいながらトレーニングをして、残りのメニューを終わらせた）"
"1001205-66" = "ミレニアムサイエンススクール"
"1001205-67-スミレ" = "トレーナー、今日の私と一緒のトレーニングは楽しかったですか？"
"1001205-68" = "[s3] \"はあ、はあ……う、うん……。\"\n[s4] \"ふう、まだ足りないかな。\""
"1001205-69-スミレ" = "ふふっ、楽しかったのでしたら良かったです。"
"1001205-70-スミレ" = "一生懸命悩みながら作ったメニューですから。"
"1001205-71-スミレ" = "！？"
"1001205-72-スミレ" = "す、すごいです、トレーナー。"
"1001205-73-スミレ" = "やはり、念のため用意していたプランBの、より高強度のトレーニングメニューに変えなくては……。"
"1001205-74" = "[s5] \"あ、あはは、冗談だよ！？冗談！\""
"1001205-75-スミレ" = "ふふっ。私も、冗談です。"
"1001205-76-スミレ" = "一緒にトレーニングをしたら、普段よりずっと楽しかったです。"
"1001205-77-スミレ" = "トレーナーが日々色々とお忙しいのは知っていますので、強要はできませんが。"
"1001205-78-スミレ" = "できればぜひ、これからも一緒に運動をしましょう。"
"1001205-79-スミレ" = "ね、トレーナー。"
