[translation]
"1005002-1" = "ココナちゃんじゃないです。教官なんです！"
"1005002-2" = "山海経訓育支援部・梅花園"
"1005002-3-梅花園の園児A" = "ココナちゃん～！私これほしい～"
"1005002-4-梅花園の園児B" = "ココナちゃん、今日のおやつは何？"
"1005002-5-ココナ" = "「ココナちゃん」じゃなくて「ココナ教官」！"
"1005002-6-梅花園の園児C" = "ココナちゃん～これわかんない。教えて！"
"1005002-7-梅花園の園児D" = "ねぇねぇ、ココナちゃん。#n本当にリーマンゼータ関数の零点が素数計数関数の振動を決定するの？"
"1005002-8-ココナ" = "「ココナちゃん」って呼ばないでって何回言ったら分かるの？"
"1005002-9-ココナ" = "そして最後の質問は一体なに……。"
"1005002-10" = "[s1] \"お疲れ様。\"\n[s2] \"梅花園の教官ってすごいんだね……。\""
"1005002-11-ココナ" = "あっ、先生！"
"1005002-12-ココナ" = "あっ、先生！"
"1005002-13-ココナ" = "みんな先生に挨拶は？"
"1005002-14-梅花園の園児たち" = "こんにちは、先生～"
"1005002-15-ココナ" = "もう……先生のことは、迷わず先生と呼ぶのに。"
"1005002-16-ココナ" = "何で私だけ「ココナちゃん」って呼ばれるのでしょう？"
"1005002-17-ココナ" = "あっ、いけない。"
"1005002-18-ココナ" = "立派なレディーであり、一人の教官として。"
"1005002-19-ココナ" = "頼もしい姿をお見せするために先生を招待したというのに……！"
"1005002-20" = "[s] \"少し頼りない所もあるけど、十分頼もしいよ。\""
"1005002-21-ココナ" = "少し頼りない所ってなんですか！"
"1005002-22-ココナ" = "いや、こんなことですぐ怒ったらダメですね。"
"1005002-23-ココナ" = "レディーは些細なことで揺れる姿を見せてはいけませんから。"
"1005002-24-梅花園の園児A" = "レディーが偏食するのは大丈夫なの？ココナちゃん？"
"1005002-25-ココナ" = "れ、レディーでも、一つや二つくらい嫌いなものがあるの！だから大丈夫！"
"1005002-26-梅花園の園児B" = "じゃあ、私たちも嫌いなもの食べなくてもいい？"
"1005002-27-ココナ" = "それはダメ！まんべんなく食べないと！"
"1005002-28-梅花園の園児C" = "なんでココナちゃんはよくて、私たちはダメなの？変なの～"
"1005002-29-ココナ" = "それは私が教官だからだよ！"
"1005002-30-梅花園の園児D" = "教官ならお手本を見せなきゃいけないんじゃないの、ココナちゃん？"
"1005002-31-ココナ" = "そ、それはそうだけど……！"
"1005002-32-ココナ" = "先生も見てないで、何か一言いってください！"
"1005002-33" = "[ns3] \"みんな、ココナ教官様の言うことをよく聞かないと。\"\n[ns4] \"ココナ教官様も、もう偏食しないと思うよ。\""
"1005002-34-梅花園の園児A" = "先生がココナちゃんのこと「教官様」って呼んでる～"
"1005002-35-梅花園の園児A" = "先生がココナちゃんのこと「教官様」って呼んでる～"
"1005002-36-梅花園の園児B" = "えー……でもココナちゃんはココナちゃんなのに……。"
"1005002-37-梅花園の園児C" = "先生がそう呼んでるなら、それで合ってるんじゃない？"
"1005002-38-梅花園の園児D" = "じゃあ……ココナ教官なのかな？#nいくらなんでも「教官様」は変だし……"
"1005002-39-ココナ" = "そうだよ！私はココナ教官。#n何回も言ってるでしょう？"
"1005002-40-梅花園の園児たち" = "ココナ教官……？"
"1005002-41-梅花園の園児たち" = "ココナ教官！"
"1005002-42" = "[s] \"嬉しそうだね、ココナ教官様。\""
"1005002-43-ココナ" = "そ、そこまでじゃないですよ？"
"1005002-44-ココナ" = "でも……えへん。#nこれで十分、分かったでしょう？"
"1005002-45-ココナ" = "私が立派な梅花園の教官だという事を。"
"1005002-46-梅花園の園児A" = "ココナ教官～私、トイレ行きたい～"
"1005002-47-梅花園の園児B" = "ココナ教官～私、家族に会いたい～#nいつ来るの？"
"1005002-48-ココナ" = "ちょ、ちょっと待って！"
"1005002-49-ココナ" = "まったく子供たちは……一度勝手に動き出すと言うことを聞かないんだから……。"
"1005002-50" = "[s] （ココナもまだまだ子供だけどなぁ……）"
"1005002-51-ココナ" = "……なんですかその顔は？"
"1005002-52-ココナ" = "……そう、ですか。なんでもないならいいんですけど。#nお疲れ様、ですか？"
"1005002-53-ココナ" = "いえ、子どもたちを一人前の園児に育てることは、山海経教官の責務ですから。"
"1005002-54-ココナ" = "これくらいのことで文句は言えません。"
"1005002-55-梅花園の園児C" = "ココナ教官～！#n早くおやつ食べたい。"
"1005002-56-梅花園の園児D" = "あーでもーココナ教官が作ったおやつは嫌いー#nまずいから！"
"1005002-57-ココナ" = "みんな、おやつの時間は全然まだだよ？"
"1005002-58-ココナ" = "あと、いつかシュン姉さんよりおいしい料理を作ってみせるから見てて。"
"1005002-59-ココナ" = "その時に、みんなを後悔させてあげるんだからね！"
"1005002-60-梅花園の園児たち" = "わぁ～ココナちゃんが怒った～！"
"1005002-61-ココナ" = "なんでまたココナちゃんに戻ってるのよ！"
