[translation]
"1010003-1" = "変わったもの、変わらないもの"
"1010003-2" = "[ns1] \"つまり、向こう側で知った宝くじの番号で……。\"\n[ns2] \"当選金を狙うってこと……！？\""
"1010003-3-シロコ" = "ん。#nちょうど覚えてる番号が、次の抽選で当たる。"
"1010003-4" = "[s3] \"うーん。\"\n[s4] \"でも、それは……。\""
"1010003-5-シロコ" = "ん、私にしかできない方法。#n何でも挑戦でしょ？"
"1010003-6" = "[s] \"挑戦は大事だけど……。\""
"1010003-7" = "[ns5] \"色々と、大丈夫なのかな……。\"\n[ns6] \"教育者としては……。\""
"1010003-8" = "[ns7] \"……これはシロコのため！\"\n[ns8] 宝くじを購入する。"
"1010003-9" = "（後日、結果を確認したが、シロコが覚えていた番号とは異なっていた）"
"1010003-10-シロコ" = "……ごめん、先生。#n私のせいでお金を無駄に……。"
"1010003-11" = "[s] \"大丈夫だよ、結果を待つ時間は楽しかったから。\""
"1010003-12-シロコ" = "……ん。#nやっぱり、ここは私が知ってる世界と少し違うのかも。"
"1010003-13" = "[s] \"たとえば、どの辺が？\""
"1010003-14-シロコ" = "……なんて言ったら良いんだろう。"
"1010003-15-シロコ" = "そこまで細かい記憶がなくって。"
"1010003-16-シロコ" = "……うまく説明できない、ごめん。"
"1010003-17-シロコ" = "……私は、昔の私じゃないし、#nこの世界[ruby=すなおおかみ]の砂狼シ[/ruby]ロコでもない。"
"1010003-18-シロコ" = "宝くじの番号みたいに、色々なものが違うのかもしれない。"
"1010003-19" = "[s] \"でも、変わらないものもあるよ。\""
"1010003-20-シロコ" = "ん、そうだね。#n不思議だけど……先生だけは、変わらない。"
"1010003-21" = "[s] \"シロコがライディングを好きなところも、ね。\""
"1010003-22-シロコ" = "……。"
"1010003-23" = "[s] \"どうして辞めちゃったのか、聞かせてくれる？\""
"1010003-24" = "[ns9] \"自転車を漕いで発電するくらいなのに。\"\n[ns10] \"部屋には自転車用のガレージまであるのに。\""
"1010003-25-シロコ" = "ん……。"
"1010003-26-シロコ" = "特別な理由はないよ。#nただ、しばらく乗ってなかったから。"
"1010003-27-シロコ" = "昔は数千kmくらい、軽く走ってたけど……。"
"1010003-28-シロコ" = "走りきれる自信は、もうないし……。"
"1010003-29-シロコ" = "ペダルを踏んでも、昔みたいに戻れないと気づいちゃったら……。"
"1010003-30" = "[s] \"どうしてそう思ったの？\""
"1010003-31-シロコ" = "……怖いの。"
"1010003-32-シロコ" = "私がアビドスにいるのも、先生と一緒にいるのも……#n全部、夢だとしたら。"
"1010003-33-シロコ" = "ごめん、先生。#nまた変なこと言って。"
"1010003-34" = "[ns] \"私は夢じゃないよ、シロコ。\""
"1010003-35" = "[ns] \"ずっとシロコのそばにいるよ。\""
"1010003-36-シロコ" = "……ち、ちょっと近い。"
"1010003-37-シロコ" = "……ん、分かってる。#n[ruby=・   ・]先生[/ruby]は、いつも隣にいてくれた。"
"1010003-38-シロコ" = "変わらないものは、ちゃんとある。"
"1010003-39-シロコ" = "この道も覚えてるよ。"
"1010003-40-シロコ" = "キヴォトス縦断の初日に通った場所。"
"1010003-41-シロコ" = "……そこの信号機で捕まって、先生にモモトークを送った。"
"1010003-42-シロコ" = "……ん。#n全部、記憶にある。"
"1010003-43-シロコ" = "先生、こっち。"
"1010003-44" = "[ns] \"し、シロコ？\""
"1010003-45-シロコ" = "ここからなら、一望できる。"
"1010003-46" = "[ns11] \"ま、待って……シロコ。\"\n[ns12] \"はぁ……はぁ、もう体力が。\""
"1010003-47" = "[ns] シロコが立っている場所に並ぶ。"
"1010003-48" = "[wa:1800]― [log=시로코 테러 무소속]……いつも通りだね、[wa:1230]ここは。[/log]"
"1010003-49" = "[wa:3260]― [log=시로코 테러 무소속]変わったのは、[wa:1190]私だけか。[/log]"
"1010003-50" = "[wa:550]― [log=시로코 테러 무소속]ん……[wa:1140]でも、[wa:860]変わってないものもあって、[wa:1630]少し安心した。[/log]"
"1010003-51" = "[wa:1540]― [log=시로코 테러 무소속]先生、[wa:1560]私、[wa:1280]また自転車に乗ってみたいと思う。[/log]"
"1010003-52" = "[wa:1170]― [log=시로코 테러 무소속]色々と壁はあるかもしれないけど……[/log]"
"1010003-53" = "[wa:3720]― [log=시로코 테러 무소속]でも、[wa:940]先生が居てくれたら……[wa:2250]できる気がするの。[/log]"
"1010003-54" = "[ns] \"うん。応援してるよ、シロコ。\""
"1010003-55" = "[wa:820]― [log=시로코 테러 무소속]ん、[wa:1110]ありがとう。[wa:990]先生。[/log]"
