[translation]
"1010002-1" = "専門家"
"1010002-2-シロコ" = "おはよう、先生。"
"1010002-3" = "[s] \"おはよう、意外な場所で驚いたよ。\""
"1010002-4-シロコ" = "……そう？"
"1010002-5-シロコ" = "買い物は必要。"
"1010002-6-シロコ" = "商店街に寄ったら、色々と買っておいたほうが効率的。"
"1010002-7-シロコ" = "先生も何か必要？#n最近お金をたくさん手に入れたから、買ってあげる。"
"1010002-8" = "[s1] \"…………。\"\n[s2] \"……たくさんのお金を、どうやって？\""
"1010002-9-シロコ" = "ん。"
"1010002-10" = "[s] \"まさか、銀行から……？\""
"1010002-11" = "……ち、違うよ。#n銀行は襲ってない。"
"1010002-12-シロコ" = "……ち、違うよ。#n銀行は襲ってない。"
"1010002-13-シロコ" = "対策委員会に迷惑はかけたくないし。#nもし逮捕されたら、こっちのシロコが誤解されるかもしれないから。"
"1010002-14-シロコ" = "もちろん、私は捕まるわけないけど。"
"1010002-15-シロコ" = "これは、ちゃんと自分で稼いだお金。#n心配しないで、先生。"
"1010002-16" = "[s] \"アルバイトでもしてるの？\""
"1010002-17-シロコ" = "……ん、大体そんな感じ。"
"1010002-18-シロコ" = "最近アビドスにも人が増えてきたおかげで、#n稼げるようになってきた。"
"1010002-19" = "[ns] \"良かったね。\""
"1010002-20" = "（シロコと買い物をしてから、商店街をあとにした）"
"1010002-21-シロコ" = "買い物、楽しかった……ありがとう。"
"1010002-22-シロコ" = "あっ、荷物は私が持つよ。"
"1010002-23" = "[s] \"大丈夫、シロコも両手いっぱいでしょ？\""
"1010002-24-シロコ" = "でも……。"
"1010002-25" = "[s] \"シロコの家まで運べば良い？\""
"1010002-26-シロコ" = "私の、家……？"
"1010002-27-シロコ" = "……そ、それは。"
"1010002-28-シロコ" = "散らかってるから、ちょっと……。"
"1010002-29" = "[s] \"どんな風に暮らしてるのか気になったんだけど……。\""
"1010002-30-シロコ" = "……ん、分かった。"
"1010002-31-シロコ" = "家庭訪問みたいなものだよね。"
"1010002-32-シロコ" = "こっち、先生。"
"1010002-33" = "[ns] シロコに付いていく。"
"1010002-34" = "廃ビルの入口"
"1010002-35-シロコ" = "ん。"
"1010002-36" = "[s3] \"廃墟だよね……？\"\n[s4] \"ここに住んでるの……？\""
"1010002-37-シロコ" = "ううん、近道だよ。"
"1010002-38-シロコ" = "この廃墟を通り抜ければ、時間が短縮できる。"
"1010002-39" = "[s] \"……なるほど。\""
"1010002-40-シロコ" = "まだ、もう少し歩くよ。"
"1010002-41-シロコ" = "狭いから気を付けて。"
"1010002-42" = "[s] \"……まさか、ここで暮らしてるの？\""
"1010002-43-シロコ" = "ここは前の仮住まい。#n今はもっとちゃんとした所に住んでるよ。"
"1010002-44" = "[s] \"ま、前の家！？\""
"1010002-45-シロコ" = "……い、行こうか。"
"1010002-46" = "砂に埋もれた住宅街"
"1010002-47" = "[ns5] \"捨てられた住宅街……。\"\n[ns6] \"そっか、どこも空き家になってるから……。\""
"1010002-48-シロコ" = "ん、有効利用。"
"1010002-49" = "[s7] \"大変じゃない？\"\n[s8] \"電気とか水道とか通ってないと思うけど……。\""
"1010002-50-シロコ" = "ん？#nたしかに、この家は不便だね。"
"1010002-51" = "[s] \"……うん？\""
"1010002-52-シロコ" = "あ、私が住んでるところはまだ先。"
"1010002-53-シロコ" = "ごめん、説明が足りなかった。"
"1010002-54" = "[ns] \"……。\""
"1010002-55-シロコ" = "到着、ここだよ。"
"1010002-56-シロコ" = "入って。"
"1010002-57-シロコ" = "ここが、私の部屋。"
"1010002-58-シロコ" = "何日か掃除できてないから、散らかってるけど。"
"1010002-59" = "[ns9] \"ここがシロコの部屋なんだね。\"\n[ns10] \"普通の生活をしてるんだね。\""
"1010002-60-シロコ" = "普通……そうかも？"
"1010002-61" = "[s] \"買ってきた物は、どこに置けば良い？\""
"1010002-62-シロコ" = "あ、牛乳は冷蔵庫で……洗剤はあっちの棚に……。"
"1010002-63" = "[s11] \"電気が通ってるんだね！\"\n[s12] \"水道も使えるんだ！\""
"1010002-64-シロコ" = "暑いし、クーラー点けるね。"
"1010002-65" = "[ns] \"クーラーまで……！？\""
"1010002-66-シロコ" = "……どこか変？"
"1010002-67" = "[s] \"ううん、しっかりしてて安心したよ！\""
"1010002-68-シロコ" = "元々は、電気も水道も通ってなかったけど……。"
"1010002-69-シロコ" = "昔の生徒会が設置した太陽光発電が近くにあったから、#nそれを借りてる。"
"1010002-70-シロコ" = "非常時のために、自転車で発電する仕組みもあるよ。#n燃料を使って発電もできる。"
"1010002-71" = "[s] \"す、すごい……。\""
"1010002-72-シロコ" = "上水は通ってないけど、タンクが数十個あるから大丈夫。"
"1010002-73-シロコ" = "ちゃんと浄水してるから、そのまま飲めるよ。"
"1010002-74-シロコ" = "あっちの車庫は、自転車を修理する用。#n上の階には、ジムを作った。"
"1010002-75-シロコ" = "捨てられてる自転車のパーツを集めたら、#nわざわざ買わなくても組めるの。"
"1010002-76" = "[s] \"おぉ、すごいね！\""
"1010002-77-シロコ" = "廃品を修理して市場で売れば、結構儲かる。"
"1010002-78" = "[s] \"な、なるほど……。\""
"1010002-79-シロコ" = "ん。#n最近はアビドスに人が増えたおかげで、需要があるみたい。"
"1010002-80" = "[ns] \"心配いらなかったね。\""
"1010002-81-シロコ" = "ん。"
"1010002-82-シロコ" = "専門家だから、任せて。"
"1010002-83" = "（遅くならないうちに、帰ることにした）"
"1010002-84" = "[ns] \"それじゃあ、また連絡するね。\""
"1010002-85-シロコ" = "……もしかしたら、繋がらないかもしれないけど。#nしばらく、ここを離れるから。"
"1010002-86" = "[s13] \"離れるって？\"\n[s14] \"ロングライドでもするの？\""
"1010002-87-シロコ" = "ロングライド……懐かしいね。#n……もう、ライディングは辞めたんだ。"
"1010002-88" = "[s] \"えっ。\""
"1010002-89-シロコ" = "……。"
"1010002-90" = "[ns] \"ど、どうして……？\""
"1010002-91-シロコ" = "……探しているものがあって。"
"1010002-92-シロコ" = "すぐ出るわけじゃないから、また会いに来てほしい。"
"1010002-93-シロコ" = "それじゃ……。"
