[translation]
"63040-1" = "第4話;ロイヤルブラッド"
"63040-2-アツコ" = "ロイヤルブラッド。"
"63040-3-アツコ" = "特別な血、特別な家系。"
"63040-4-アツコ" = "思い返せば昔から、色々な人に持ち上げられてきた。"
"63040-5-アツコ" = "でも……そこに、大した意味なんてなかった。"
"63040-6-アツコ" = "どんなに特別でも、酷い目に遭うのは同じだったから。"
"63040-7-アツコ" = "それどころか、できないことと、言えないことばかり増えていった。"
"63040-8-アツコ" = "ありがとう、サッちゃん。"
"63040-9-アツコ" = "サッちゃんがいてくれたから、私は耐えられたんだ。"
"63040-10-アツコ" = "ありがとう、[USERNAME]先生。"
"63040-11-アツコ" = "先生に出会って、やっと私は自分になれた気がするんだ。"
"63040-12-アツコ" = "ミサキも、ヒヨリも。"
"63040-13-アツコ" = "みんながいなかったら私は、ただの喋らない人形か、生贄として――"
"63040-14-アツコ" = "一生、誰かと何かの象徴として、生き続けていたんだろうね。"
"63040-15-アツコ" = "アリウスの秘儀に触れて、勘違いしちゃったのかな？"
"63040-16-アツコ" = "この地に眠るもの。その答えに近づいたからって、何でもできると思った？"
"63040-17-アツコ" = "――残念。"
"63040-18-アツコ" = "その程度のことはね、私はずっと前から知ってたんだよ。"
"63040-19-アツコ" = "でも、先輩のお陰で確信できたことがある。"
"63040-20-アツコ" = "黙示録の天使。あるいは、その現象――あれは、[ruby=・   ・   ・]先輩が[/ruby]引き起こしたんだね。"
"63040-21-アツコ" = "しかも、最初は無自覚に。ある意味では[ruby=・   ・   ・   ・]召喚した[/ruby]と言ってもいいのかな。"
"63040-22-アツコ" = "先輩にとっては不本意かもしれないけど――"
"63040-23-アツコ" = "あれは、経典に記された「7人のラッパ吹きの天使」なんかじゃない。"
"63040-24-アツコ" = "でもね、昇華する可能性はあった。#n[ruby=・   ・   ・   ・   ・   ・   ・]本物になりうる[/ruby]存在だった。"
"63040-25-アツコ" = "先輩が、完全無欠の審判者でいられたなら、ね。"
"63040-26-サオリ" = "完全無欠の……「審判者」？"
"63040-27-アツコ" = "何度も言ってるけど、先輩だけがアリウスなわけじゃない。"
"63040-28-アツコ" = "アリウスの秘儀を知ってるのは、先輩だけじゃないんだよ。"
"63040-29-アツコ" = "先輩にとっては初めて知ったことでも、私には「知らなきゃいけないこと」だったから。"
"63040-30-アツコ" = "ただ、それを口に出すのが禁じられていただけ。#n……それは今も変わらないけどね。"
"63040-31-アツコ" = "――アリウスのロイヤルブラッドって、そういうものだから。"
"63040-32-アツコ" = "でも、お礼は言わせて。"
"63040-33-アツコ" = "先輩が暴いてくれたおかげで、やっと話せるようになったから。"
"63040-34-アツコ" = "ふふっ、自分だけが知ってて……#nそれを誰にも話せないのって、すごく苦しいんだよ。"
"63040-35" = "[ns] \"つまり……どういうことなの……？\""
"63040-36-アツコ" = "あの天使……いや、天使のようなもの。"
"63040-37-ラッパ吹きの天使" = "あれはね、アリウスに積もったあらゆる感情が形を成した「現象」なんだ。"
"63040-38-ラッパ吹きの天使" = "前に話したよね？アリウスは、「何か」が起こる土地になったって。"
"63040-39" = "[ns] \"あ……！\""
"63040-40-アツコ" = "ここには、もともと「何か」があった。"
"63040-41-アツコ" = "怒り、嘆き、恨み、絶望、諦念……そういう思念が積もり積もって、ここに集まってる。"
"63040-42-ミサキ" = "アリウスは世界の滅亡を望んでいたのか、って？"
"63040-43-ミサキ" = "その通りだよ。"
"63040-44-ウイ" = "温もりを得られなかった子どもが、温もりを得るために村を燃やす――そんな話があるくらいですから。"
"63040-45-ウイ" = "失うものがない人にとって……世界の終わりは「救済」なのかもしれません。"
"63040-46" = "[ns1] \"昇華する可能性があったっていうのは？\"\n[ns2] \"完全無欠の審判者なら可能だったって言ってたよね。\""
"63040-47-アツコ" = "そうだね。アリウスに堆積したものは、それだけの結果を導くに足る「何か」だった。"
"63040-48-アツコ" = "……少なくとも、トリニティに「何らかの報い」を返す程度なら、十分だった。"
"63040-49-アツコ" = "でもそれは、スバル先輩が「完全無欠」だった場合の話。"
"63040-50-ミサキ" = "つまり、何かが欠けてたってこと？"
"63040-51-アツコ" = "そう。"
"63040-52-アツコ" = "それが、この子。"
"63040-53-ヒヨリ" = "あ……！"
"63040-54-スバル" = "わ……たし……は……。"
"63040-55-アツコ" = "やっと分かったみたいだね。"
"63040-56-アツコ" = "先輩がこの子を「捨てた」瞬間……先輩の行動は、正当性を失った。"
"63040-57-アツコ" = "先輩を[ruby=・]媒[/ruby][ruby=・]体[/ruby][ruby=・]に[/ruby][ruby=・]し[/ruby][ruby=・]て[/ruby]、この現象を構築していたなら、まだ良かったかもしれない。"
"63040-58-アツコ" = "でも先輩は、[ruby=・]自[/ruby][ruby=・]分[/ruby][ruby=・]が[/ruby]「ラッパ吹きの天使」になろうとした。"
"63040-59-アツコ" = "気持ちは分かるよ。先輩だけじゃなく、アリウスに残ったみんなは――どんな形であれ、審判者になりたかったはずだから。"
"63040-60-アツコ" = "でもね。"
"63040-61-アツコ" = "審判者っていうのは、本来――完全無欠じゃなきゃいけないの。"
"63040-62-アツコ" = "『お前が仕掛けた罠に、お前自身がかかって倒れるだろう』"
"63040-63-アツコ" = "先輩なら、この経典の一節……覚えてるよね？"
"63040-64-アツコ" = "せめてマイアが、私たちを……先生を、頼らなかったら。"
"63040-65-アツコ" = "まだ、先輩は審判者になれたかもしれなかった。"
"63040-66-マイア" = "私を――見捨てないでください！"
"63040-67-スバル" = "あ……。"
"63040-68-スバル" = "あ……ああ……。"
"63040-69-サオリ" = "スバル？"
"63040-70-ミサキ" = "かすかに声が聞こえた。もしかして……！"
"63040-71-ヒヨリ" = "……。"
"63040-72-ヒヨリ" = "ヒ、ヒヨリさん……？"
"63040-73-ヒヨリ" = "い、言いたいことがあるなら……言わなきゃダメです。"
"63040-74-ヒヨリ" = "わ、私たち……ちゃんと話をしようって……だからここまで来たんですよね？"
"63040-75-マイア" = "……。"
"63040-76-マイア" = "……そう、ですよね。ヒヨリさん……ありがとうございます。"
"63040-77-マイア" = "あの、先輩……？#nその、ずっと、伝えたいことがあったんです。あの時から、ずっと……。"
"63040-78-マイア" = "大丈夫ですよ、先輩。"
"63040-79-マイア" = "全部……大丈夫ですから。"
"63040-80-スバル" = "……！"
"63040-81-マイア" = "あ、いや、全部ってわけじゃ……ないかもしれないですけど……。#n[ruby=・]そ[/ruby][ruby=・]れ[/ruby][ruby=・]で[/ruby][ruby=・]も[/ruby]、私は先輩を信じてます。"
"63040-82-マイア" = "先輩も、スクワッドの皆さんも。アリウスのみんなも。"
"63040-83" = "そして、[USERNAME]先生も。#n私は、みんなが大好きなんです。"
"63040-84-マイア" = "私は今でも、アリウスが残っててほしいって思ってます。"
"63040-85-マイア" = "そして……アリウスが、もっと良い学校に変わってほしい。"
"63040-86-マイア" = "だ、だから……！"
"63040-87-マイア" = "すー……はぁ……。#nすー……っ！！"
"63040-88-マイア" = "助けてください、先輩！！！！"
"63040-89-スバル" = "……！"
"63040-90-マイア" = "私……先輩のハーモニカ、本当に大好きなんです！！！"
"63040-91" = "次回;あの日のハーモニカ"
