[translation]
"63050-1" = "第5話;あの日のハーモニカ"
"63050-2-マイア" = "これ、ハーモニカ……。#n先輩が落としたみたいだったので、拾っておきました……。"
"63050-3-マイア" = "あっ、でも、今すぐ吹いてほしいとかじゃなくて……！"
"63050-4-マイア" = "今はきっと、いろいろ大変でしょうし……！"
"63050-5-マイア" = "でも、いつかまた……あの時みたいに……。"
"63050-6-マイア" = "先輩の演奏、聴かせてほしいです……。"
"63050-7-スバル" = "あ……ああ……。"
"63050-8-スバル" = "（こんな結末を望んだ訳じゃなかった）"
"63050-9-スバル" = "（責任から目を背けてはいけない）"
"63050-10-スバル" = "（それは、当然のことなのに）"
"63050-11-ミサキ" = "消えた……！？"
"63050-12-マイア" = "先輩！"
"63050-13-アツコ" = "探そう。アリウス分校の外には出られないはずだから。"
"63050-14" = "[ns] \"もしもし？どうしたの？\""
"63050-15-アリウスの生徒たち" = "天使が……3体目の天使が現れました！"
"63050-16-アリウスの生徒たち" = "で、でも……なんて説明すれば……。#nえっと、えっと、3体目が現れたと思ったら、それまでいた2体は消えたんです！"
"63050-17-アリウスの生徒たち" = "3体目の天使に吸収されたようにも見えて……。"
"63050-18-アリウスの生徒たち" = "で、でもそれよりも！#n天使の中に、人みたいなのが見え隠れしてて……。"
"63050-19-アリウスの生徒たち" = "信じてもらえないかもですが……スバル先輩そっくりなんです！"
"63050-20-サオリ" = "先生！"
"63050-21" = "[ns] \"スバルだ！\""
"63050-22" = "[ns] \"ありがとう、みんな！また何かあったら連絡して！\""
"63050-23-アリウスの生徒たち" = "はい！"
"63050-24-スバル" = "（……）"
"63050-25-スバル" = "（ここから見える空は、こんなにも曇ってるのに）"
"63050-26-スバル" = "（たしか、サオリの記憶で見た空は……）"
"63050-27-スバル" = "そうか。"
"63050-28-スバル" = "サオリ。"
"63050-29-スバル" = "君の見ていた空は……こんな光景だったのか。"
"63050-30-スバル" = "（アリウスの風景は、いつも同じだった）"
"63050-31-スバル" = "（そこに生きる私たちも、やはりそうだった）"
"63050-32-スバル" = "（すべてが流れ着き、堆積して、忘れ去られる場所）"
"63050-33-スバル" = "（アリウスはきっと、そんな場所だったんだ）"
"63050-34-スバル" = "（たとえ違ったとしても、いつの間にか、そうなってしまっていたのだろう）"
"63050-35-スバル" = "（世界はアリウスを隔離し、ついには忘れることを選んだ）"
"63050-36-スバル" = "（いや、それすら甘い評価かもしれない）"
"63050-37-スバル" = "（世界は横柄で、勝手気ままで。予想もつかない方向へ、無遠慮に進んでいくものなのだから）"
"63050-38-スバル" = "（……煩わしいものや邪魔なものを、簡単に払い捨てながら）"
"63050-39-スバル" = "（それなら……。#n忘れられた者たちは、誰が覚えていてくれるのか）"
"63050-40-スバル" = "（届かぬ声を、誰が覚えていてくれるのか）"
"63050-41-？？？" = "先輩、先輩！ハーモニカ吹いてくださいよ！"
"63050-42-スバル" = "廃墟で、ひとり感傷にひたりながらハーモニカを吹くなんて……。"
"63050-43-スバル" = "それって、ちょっと……カッコつけすぎのような……。"
"63050-44-マイア" = "あの、私も……。"
"63050-45" = "[log=스바루]やめて……。[/log]"
"63050-46-マイア" = "久しぶり、ですし……。"
"63050-47" = "[log=스바루]……お願い、です。やめてください。[/log]"
"63050-48-マイア" = "先輩の演奏……聴きたいです。"
"63050-49" = "[log=스바루]！！！[/log]"
"63050-50" = "[log=스바루]！？！？[/log]"
"63050-51-アツコ" = "後悔してる？"
"63050-52-スバル" = "アツ……コ……。"
"63050-53-アツコ" = "大丈夫だよ。私たちだって、そうだったんだから。"
"63050-54-スバル" = "でも、アリウスは……。"
"63050-55-スバル" = "……トリニティがアリウスにしてきたことは……！"
"63050-56-アツコ" = "うん、そうだね。"
"63050-57-アツコ" = "でも、それはそれ。"
"63050-58-アツコ" = "そのせいで今こうして先輩が苦しんでるのって、ちょっと不公平なんじゃない？"
"63050-59-アツコ" = "……この言葉、覚えてる？"
"63050-60-アツコ" = "『とげのあるむちをければ、傷を負うだけである』"
"63050-61-スバル" = "……！"
"63050-62-アツコ" = "一緒にやろう。"
"63050-63-アツコ" = "全部をひとりで背負わないで。"
"63050-64-スバル" = "今……さら？"
"63050-65-アツコ" = "うん。#n[ruby=・]そ[/ruby][ruby=・]れ[/ruby][ruby=・]で[/ruby][ruby=・]も[/ruby]――"
"63050-66-アツコ" = "正直に話せば、先生はきっと助けてくれる。"
"63050-67-スバル" = "……！"
"63050-68-アツコ" = "あ、でも私たちは、ちょっと矯正局にお世話になるかもしれないから……その間はよろしくね？"
"63050-69-スバル" = "……。"
"63050-70-スバル" = "いや……だめですよ。そんなのは……。"
"63050-71-スバル" = "そんなの、できません。"
"63050-72-スバル" = "私は。"
"63050-73-スバル" = "私たちは。"
"63050-74-スバル" = "アリウスは、まだ……納得していないんです。"
"63050-75-スバル" = "あなたが言ったように、ここはもう「そういう場所」に成り果ててしまったのですから。"
"63050-76-スバル" = "何の断罪も、裁きもないまま、すべてを葬ってしまおうだなんて、許されません。"
"63050-77-スバル" = "それは、アリウスに生きたもの達への冒涜に他ならない！"
"63050-78-アツコ" = "そういうつもりじゃないんだけどな……。"
"63050-79-アツコ" = "もう自分自身に飲み込まれちゃってるんだね。#nこれじゃあ、どんな言葉も届かない。"
"63050-80-アツコ" = "でも大丈夫。私たちも、そうだったから。#nそして、こういう時どうすればいいか……アリウスは知ってる。"
"63050-81-スバル" = "……？"
"63050-82-アツコ" = "さあ。"
"63050-83-アツコ" = "アリウス式で、お話しよっか。"
"63050-84-サオリ" = "アツコ？大丈夫か？#n祈るような仕草をしていたが……。"
"63050-85-アツコ" = "うん。ちょっと……[ruby=・]お[/ruby][ruby=・]話[/ruby]してただけ。"
"63050-86-ヒヨリ" = "話……？"
"63050-87-ヒヨリ" = "そ、それって……そういうこと、ですか……？"
"63050-88-アツコ" = "うん、そういうこと。"
"63050-89-アツコ" = "それじゃあ、先生。"
"63050-90" = "[s] \"うん。\""
"63050-91-アツコ" = "夢に囚われたままの先輩を、起こしてあげよう。"
"63050-92-アツコ" = "アリウスらしいやり方で。"
"63050-93" = "[s] \"何をすればいい？\""
"63050-94-アツコ" = "いつもと同じだよ。先生にしかできないこと。"
"63050-95-アツコ" = "マイアも、手伝ってくれる？"
"63050-96-マイア" = "……もちろんです。"
"63050-97-マイア" = "先輩のためなら、なんでもします！"
