[translation]
"10048070-1" = "第7話;盗みと貿易の狭間"
"10048070-2" = "とあるカフェ"
"10048070-3-依頼人" = "もう日が暮れます。"
"10048070-4-依頼人" = "夜が明ければ、ベロニカ特別展が開催される。"
"10048070-5-依頼人" = "展示場の光景が、想像できますか？"
"10048070-6-カフェの店員" = "さあ……。"
"10048070-7-依頼人" = "観客はまるでベルトコンベアに載せられたかのように、作品の前を通り過ぎていくでしょう。"
"10048070-8-依頼人" = "そして有名と言われる作品の前に集まり、#nさも何かを感じ取ったかのように頷いていく。"
"10048070-9-カフェの店員" = "本当に何かを感じ取ったのでは？"
"10048070-10-依頼人" = "いいえ、誰も何もわかっていない……。#n本物の風格を。偽物が作り出す粗悪さを。"
"10048070-11-依頼人" = "彼らは絵なんて見ていませんよ。"
"10048070-12-依頼人" = "絵の知名度や取引価格にのみ、価値を見出している。"
"10048070-13-依頼人" = "彼らはただ、絵を取り巻く情報を鑑賞しているだけに過ぎません。"
"10048070-14-依頼人" = "私は、疑問を抱くことがあります……。#nあらゆる者が芸術そのものの価値に気が付く――"
"10048070-15-依頼人" = "――そんな日は、果たして訪れるのでしょうか？"
"10048070-16-依頼人" = "……私には、到底信じられません。"
"10048070-17-依頼人" = "あなたは、どう思いますか？"
"10048070-18-カフェの店員" = "あのー、そろそろ閉店のお時間なので……。"
"10048070-19-依頼人" = "……あっ！"
"10048070-20-依頼人" = "し、失礼しました！"
"10048070-21" = "ワイルドハントの収蔵庫"
"10048070-22-寮監隊員" = "ふぅ……いよいよ明日、か。"
"10048070-23-寮監隊員" = "今までもここの警備は何度かしたことがあるが、今回は特に厳重だな。"
"10048070-24-ミリア" = "……。"
"10048070-25-寮監隊員" = "いつもの警備でさえ手一杯なのに、慈愛の怪盗だなんて……。"
"10048070-26-寮監隊員" = "まあ、今日大丈夫ならもう来ないでしょう。"
"10048070-27-寮監隊員" = "いくら怪盗と言っても、こんな厳戒態勢を突破できるわけ――"
"10048070-28-ミリア" = "ところで。"
"10048070-29-寮監隊員" = "ん？"
"10048070-30-ミリア" = "私たちは、何を守っているのでしょうか？"
"10048070-31-寮監隊員" = "ん……？#n泥棒から作品を守っているはずですが。"
"10048070-32-ミリア" = "観客から作品を守っている……のではなく？"
"10048070-33-寮監隊員" = "何言っているんですか。明日から展示ですよ？#n作品なんて、誰でも自由に鑑賞できます。"
"10048070-34-ミリア" = "公開する作品を決めているのは、ベロニカ財団です。"
"10048070-35-ミリア" = "財団が選んだものが飾られるだけ。観客は何を見るかなんて選べません。"
"10048070-36-ミリア" = "誰もがアートを楽しめるなど――錯覚でしかない。"
"10048070-37-寮監隊員" = "……今回の展示会は、収蔵庫の作品全部が展示されると聞いていますが。"
"10048070-38-ミリア" = "ええ。ですがそれは、ベロニカ財団が保有する内の、ほんの1割。"
"10048070-39-ミリア" = "他の芸術品は、今もなお財団の倉庫に閉じ込められている。"
"10048070-40-ミリア" = "……その美しさを、誰にも見せることなく。"
"10048070-41-ミリア" = "果たして、本当にそれで良いのでしょうか。"
"10048070-42-寮監隊員" = "それは……財団が持ち主なのですから、仕方ないのでは？"
"10048070-43-寮監隊員" = "どれを見せるかは所有者の自由かと。"
"10048070-44-ミリア" = "どうでしょう。#nたとえば世界中の湖や川を買い上げた方が、飲み水の供給を止めると宣言したとして……貴女はそれを受け入れられますか？"
"10048070-45-寮監隊員" = "それは……流石に別の話だと思いますが。"
"10048070-46-ミリア" = "いいえ、同じことですよ。"
"10048070-47-ミリア" = "芸術は――美しさは。#nあらゆる者に共有されるべきなのです。"
"10048070-48-寮監隊員" = "なっ、なんだ……！？"
"10048070-49" = "ボン！！"
"10048070-50-寮監隊員" = "え、煙幕っ……！？"
"10048070-51-寮監隊員" = "ま、まさか慈愛の怪盗が……！？"
"10048070-52-ミリア" = "二手に分かれましょう、私は裏門へ！"
"10048070-53-寮監隊員" = "は、はい！こっちは正門に向かいます！"
"10048070-54-ミリア" = "ええ、慈愛の怪盗――"
"10048070-55-慈愛の怪盗" = "――[ruby=わたくし]私[/ruby]が、参りましたよ。"
"10048070-56" = "ワイルドハント・空き地"
"10048070-57-ヒロミ" = "慈愛の怪盗、出現！1・2・3分隊、A区域にて集合！"
"10048070-58-ヒロミ" = "訓練通りに動け！地の利は我々にある！"
"10048070-59-寮監隊員C" = "はっ！すぐにそちらへ――"
"10048070-60-寮監隊員C" = "えっ！？"
"10048070-61-ヒロミ" = "どうした！？"
"10048070-62-寮監隊員C" = "先遣隊が穴に落ちました！"
"10048070-63-ヒロミ" = "穴？なぜそんなところに！？"
"10048070-64-寮監隊員C" = "お、おそらく誰かが罠を……！"
"10048070-65-ヒロミ" = "罠？私たちは何も仕掛けていな――"
"10048070-66-寮監隊員C" = "煙幕！？"
"10048070-67-寮監隊員C" = "なんでさっきから煙幕が……！"
"10048070-68-ヒロミ" = "わっ！？なんだこれはっ……！！"
"10048070-69-ヒロミ" = "一体何が起きている……！？"
"10048070-70-ミヨ" = "うぅぅぅ……ごめんなさい。#n寮監隊の皆さん、ヒロミちゃん……。"
"10048070-71-ミヨ" = "でも、怪我はしないはずですから……。"
"10048070-72-リツ" = "どう？ミヨちゃん、ちゃんと罠発動してる？"
"10048070-73-ミヨ" = "う、うん！ありがとね、リッちゃん。"
"10048070-74-フユ" = "ねえ、私にお礼はないの？"
"10048070-75-ミヨ" = "フユにはもう少し付き合ってもらいますけど。#n3番、5番、アクション。"
"10048070-76-フユ" = "ラジャー。3番、5番、オン。"
"10048070-77-寮監隊員D" = "また煙幕っ！？"
"10048070-78-寮監隊員E" = "助けてください！こっちにいます、穴の中！"
"10048070-79-寮監隊員D" = "どこですか！？何も見えません！"
"10048070-80-ミヨ" = "気をつけて、罠にかかってないヤツがそっちに向かったよ。"
"10048070-81-ミヨ" = "了解。フユのいる北東の斜面も、攻められやすいので注意してください。"
"10048070-82-フユ" = "確認しました。あっ、収蔵庫の西側に兵力が移動しています。"
"10048070-83-ミヨ" = "12番、アクション。"
"10048070-84-フユ" = "了解。12番、ON。"
"10048070-85-フユ" = "……クリア。そっちに合流するね。"
"10048070-86-ミヨ" = "ラジャー。"
"10048070-87-ミヨ" = "ふぅ……。"
"10048070-88-ミヨ" = "……うぅっ。"
"10048070-89-フユ" = "来ましたよっと。"
"10048070-90-フユ" = "……って大丈夫？顔色悪いよ。"
"10048070-91-ミヨ" = "……理由はどうあれ、犯罪の手伝いをしていますから。"
"10048070-92-フユ" = "ミヨ、そんな苦しい時こそ思い出して。"
"10048070-93-ミヨ" = "なにを？"
"10048070-94-フユ" = "寮監隊のせいでことごとく失敗してきた、過去のビジネスを！"
"10048070-95-ミヨ" = "依頼を受けなきゃよかった話ですよね！？"
"10048070-96-フユ" = "ふふっ……まあ、そう言わないでさ。"
"10048070-97-フユ" = "今回の件を成功させれば、贋作を真作に正すのはもちろん……#n慈愛の怪盗という犯罪者に一杯食わせることもできる。"
"10048070-98-フユ" = "ミヨが書いた話が、ハッピーエンドを迎えられるんだよ？"
"10048070-99-ミヨ" = "ハッピー、エンド……。"
"10048070-100-ミヨ" = "そうですね……それに、ここまで来て筆を折るわけにはいかない。"
"10048070-101-ミヨ" = "……結末まで辿り着かないと。"
"10048070-102-ミヨ" = "それでフユ、罠は残りいくつ？"
"10048070-103-フユ" = "全部使い切ってるよ。"
"10048070-104-ミヨ" = "そう……やれることはやりましたね。 "
"10048070-105-ミヨ" = "あとは、慈愛の怪盗がちゃんと盗めれば……。"
"10048070-106-フユ" = "ここまで手伝って失敗するなら、怪盗向いてないんじゃないかな？"
"10048070-107-ミヨ" = "……それもそうですね。"
"10048070-108-ミヨ" = "うん……フユ、例の真作は持ってきたよね？"
"10048070-109-フユ" = "もちろん。カバンに大事にしまってありますとも。"
"10048070-110-ミヨ" = "じゃあ、この辺で下がろうか。"
"10048070-111-ミヨ" = "日も暮れてきたし……。 "
"10048070-112-？？？" = "ええ――今宵の舞台の幕を下ろすには、良い頃合いでしょう。"
"10048070-113-フユ" = "……！"
"10048070-114-フユ" = "夜の帳が下りれば、偽りの[ruby=かお]表情[/ruby]は闇に溶け――真実の声のみがこだまする。"
"10048070-115-慈愛の怪盗" = "ごきげんよう。名も知らぬお嬢さん方。"
"10048070-116-慈愛の怪盗" = "お初にお目にかかります――「慈愛の怪盗」と申します。"
"10048070-117-慈愛の怪盗" = " 少々――[ruby=・]お[/ruby][ruby=・]話[/ruby]していきませんか？"
