[translation]
"70009020-1" = "されど寮監隊は走り続ける（２）"
"70009020-2-寮監隊員" = "はぁ……ただいま。"
"70009020-3-寮監隊員" = "つ、疲れた～"
"70009020-4-寮監隊員" = "寮監隊長のおかげでなんとかなったけど……。#nもし間に合わなかったら……うぅ。"
"70009020-5-寮監隊員" = "あ、そうだ。課題も進めないと……。"
"70009020-6-寮監隊員" = "……明日でいいや～"
"70009020-7-寮監隊員" = "ふあぁ……ベッド最高。"
"70009020-8-寮監隊員" = "……最後に絵を描いたの、いつだっけ？"
"70009020-9-寮監隊員" = "やめやめ、早く寝よう。"
"70009020-10-寮監隊員" = "ふぁあ……おやすみなさ～い。"
"70009020-11" = "ババババ～ン！！ババババ～ン！！"
"70009020-12-寮監隊員" = "うわっ！？な、なんだ！？"
"70009020-13-寮監隊員" = "こんな時間に路上ライブをやるような奴らといえば……。"
"70009020-14-寮監隊員" = "またかよ！！こっちは寝不足なんだ！！"
"70009020-15-寮監隊員" = "誰か！背景音楽部を止めて！！"
"70009020-16-寮監隊員" = "総員起床！5分以内に廊下へ整列せよ！#n繰り返す！総員起床！5分以内に廊下へ整列せよ！"
"70009020-17-寮監隊員" = "はあああああ……。"
"70009020-18-寮監隊員" = "……仕方ないな。"
"70009020-19-寮監隊の幹部" = "……およそ7分前、学院のフェンスを越える自由外出部の姿が目撃された。"
"70009020-20-寮監隊の幹部" = "もう！また自由外出部かよ。"
"70009020-21-寮監隊の幹部" = "今月でもう4回目……いつ寝てんだよ、あいつら。"
"70009020-22-寮監隊の幹部" = "現時刻をもって、脱走の阻止を最優先任務とする。#nまた、自由外出部の部長は発見次第身柄を確保せよ。以上、質問は？"
"70009020-23-真面目な寮監隊員" = "あの……一ついいですか。"
"70009020-24-真面目な寮監隊員" = "外の背景音楽部は放っておいていいんでしょうか。#n各寮からいっぱい苦情が来てて……。"
"70009020-25-寮監隊の幹部" = "ふむ、背景音楽部はそのままでいい。#nまだ逮捕命令が下りていない。"
"70009020-26-真面目な寮監隊員" = "ですが、生徒の安眠が……。"
"70009020-27-寮監隊の幹部" = "仮にだ。オーケストラの奏者が指揮を無視し、#n勝手に音を奏でだしたらどうなる？"
"70009020-28-真面目な寮監隊員" = "え？#n……[ruby=めちゃくちゃ]不協和音[/ruby]になりますね。"
"70009020-29-寮監隊の幹部" = "その通り。寮監隊長が逮捕命令を出していないのなら、我々が動く必要はない。#n大事なのは、「背景音楽部は今回の対象ではない」ということだけだ。"
"70009020-30-寮監隊の幹部" = "命令は頭で理解せず……心で感じるんだ！"
"70009020-31-真面目な寮監隊員" = "な、なるほど……！"
"70009020-32-寮監隊員" = "（……早く終わらないかなあ）"
"70009020-33-寮監隊の幹部" = "では、総員出動せよ！全速前進！"
"70009020-34" = "ワイルドハント学院のフェンス近所"
"70009020-35-寮監隊員" = "はぁ、はぁ……。"
"70009020-36-寮監隊員" = "なんでこんな夜中に……でも、あとちょっとだ……。"
"70009020-37-寮監隊の幹部" = "はい！？い、いえ、承知しました。"
"70009020-38-寮監隊の幹部" = "総員、止まれ！"
"70009020-39-寮監隊の幹部" = "……？"
"70009020-40-寮監隊の幹部" = "これより、背景音楽部の逮捕に向かう！"
"70009020-41-寮監隊員" = "……え？"
"70009020-42-寮監隊員C" = "自由外出部はどうするんです？ここまで来たんですよ……？"
"70009020-43-寮監隊員C" = "っていうか、背景音楽部の逮捕はさっきできましたよね？#n私たちが行進してるとき、応援歌を演奏してたし……。"
"70009020-44-寮監隊の幹部" = "これは寮監隊長の命令だ！#n生徒の安眠のため、背景音楽部の逮捕を最優先とする！"
"70009020-45-寮監隊の幹部" = "……だが、不満を持つのもわかる。"
"70009020-46-寮監隊員" = "……おお？"
"70009020-47-寮監隊の幹部" = "ここまで来て引き返せと言われても、納得できないだろう。"
"70009020-48-寮監隊員" = "（今さら……？）"
"70009020-49-寮監隊員" = "（いやでも……あなたなら、この状況をきっと……！）"
"70009020-50-寮監隊の幹部" = "だが……そこにこそ、寮監隊長の真意が秘められているのだ！"
"70009020-51-寮監隊の幹部" = "総員、引き返すぞ！全速前進！"
"70009020-52-寮監隊員" = "ああ……！"
"70009020-53-寮監隊員" = "もうー！！！"
"70009020-54-寮監隊員" = "なんなんだよ、この学院は～～～！！！"
"70009020-55" = "されど寮監隊は走り続ける"
