[translation]
"70009010-1" = "されど寮監隊は走り続ける（１）"
"70009010-2-寮監隊員" = "鳥はさえずり、花は咲き乱れる……なんて素晴らしい日なんだ。"
"70009010-3-寮監隊員" = "こんな日は――"
"70009010-4-寮監隊員" = "カフェテラスでエスプレッソを一杯やれたら、最高だろうなあ。"
"70009010-5-寮監隊員" = "まあ、現実は……丸一日検問所の中だけど。"
"70009010-6-寮監隊員" = "……感傷に浸るのも贅沢、か。"
"70009010-7-寮監隊員" = "はいはい、分かりました。#nこれより、検問所を開放します。"
"70009010-8-寮監隊員" = "外出証をご提示ください。"
"70009010-9-ワイルドハントの生徒A" = "はい。"
"70009010-10-ワイルドハントの生徒A" = "申告した物は……ないですね。#nでは、ボディチェックにご協力ください。"
"70009010-11-ワイルドハントの生徒A" = "またやるの？#n制服のどこに隠すっていうの……。"
"70009010-12-寮監隊員" = "こちらも仕事ですので。"
"70009010-13-寮監隊員" = "ちょ、ちょっと！どこ触ってるのよ！？"
"70009010-14-寮監隊員" = "最近、禁制品の持ち込みが多発していまして。#nボディチェックをより厳しくするよう、上からの指示です。"
"70009010-15-寮監隊員" = "うわっ……く、くすぐったい！#nも、もうやめてぇ！"
"70009010-16-寮監隊員" = "……問題なさそうですね。#nご協力ありがとうございました。"
"70009010-17-ワイルドハントの生徒A" = "最初からそう言ってるでしょ！"
"70009010-18-寮監隊員" = "これだから、寮監隊は……！"
"70009010-19-寮監隊員" = "真面目に仕事してるだけなんだけどなぁ……。"
"70009010-20-寮監隊員" = "はぁ……愚痴ってもしょうがないか……。"
"70009010-21-寮監隊員" = "次の方、どうぞ。"
"70009010-22-ワイルドハントの生徒B" = "はい、外出証とカバン。"
"70009010-23-寮監隊員" = "では、中身を確認させていただきます。"
"70009010-24-寮監隊員" = "これは……明太子ポテチですか。"
"70009010-25-ワイルドハントの生徒B" = "そうだよ？"
"70009010-26-寮監隊員" = "没収です。"
"70009010-27-ワイルドハントの生徒B" = "嘘でしょ！？"
"70009010-28-寮監隊員" = "学院の食品安全基準を満たしていません。"
"70009010-29-ワイルドハントの生徒B" = "あんぜん……何？"
"70009010-30-寮監隊員" = "袋内の窒素が少なく、#n輸送中に破れる恐れがあるため……とのことです。"
"70009010-31-寮監隊員" = "で、でもっ……。#n食べる分には平気でしょ！？"
"70009010-32-寮監隊員" = "ルールはルールですので。"
"70009010-33-寮監隊員" = "えっと、人形ですね。これもたしか……。"
"70009010-34-寮監隊員" = "ああ、リストにありました。#nモモフレンズのペロロ人形……はい、没収です。"
"70009010-35-ワイルドハントの生徒B" = "……これはなんで？"
"70009010-36-寮監隊員" = "ええと、最新エピソードで公式がキャラブレを起こしたため、外交的抗議があり……。#n……ってなにこれ？"
"70009010-37-寮監隊員" = "……とりあえず、モモフレンズのグッズは当面の間、#n持ち込み禁止です。"
"70009010-38-ワイルドハントの生徒B" = "あんたもピンと来てないじゃん！"
"70009010-39-寮監隊員" = "え、これって……。"
"70009010-40-寮監隊員" = "パイナップルですか？"
"70009010-41-ワイルドハントの生徒B" = "そうだけど？"
"70009010-42-寮監隊員" = "……いえ、カバンから出てくるとは、と。#nこれも没収します。"
"70009010-43-ワイルドハントの生徒B" = "なんでよ！ただの果物だよ！？"
"70009010-44-寮監隊員" = "パイナップルピザ根絶のため、全面禁止にしています。"
"70009010-45-ワイルドハントの生徒B" = "誰が決めてるの、それ……？"
"70009010-46-寮監隊員" = "私です。#nパイナップルピザ、嫌いなので。"
"70009010-47-寮監隊員" = "自分の都合じゃん！"
"70009010-48-寮監隊員" = "犯罪に使用される可能性の高い物品は、#n検問官の判断で没収できるんですよ。"
"70009010-49-ワイルドハントの生徒B" = "パイナップルピザのどこが犯罪なのよ……。"
"70009010-50-寮監隊員" = "最後に……こちらは？"
"70009010-51-ワイルドハントの生徒B" = "あ、ゲヘナの生徒会長の自伝……だったかな？#n派手な本なのに、投げ売りされてたから、逆に面白そうだなって。"
"70009010-52-寮監隊員" = "未登録の書籍ですね。没収します。"
"70009010-53-ワイルドハントの生徒B" = "これ、めっちゃ重かったんだよ！？#n苦労して持ってきたのに！"
"70009010-54-寮監隊員" = "正式に調査し、問題がなければ告知されるかと。#nその後、正式に書類手続きをしてお受け取りください。"
"70009010-55-寮監隊員" = "これで全部ですね。どうぞお入りください。"
"70009010-56-ワイルドハントの生徒B" = "全部没収じゃん！どういう基準なの！？#n他校じゃ全然みんな持ってるのに！"
"70009010-57-寮監隊員" = "禁制品はルールブックに全て記載してありますよ？"
"70009010-58-寮監隊員" = "そんなの、あんたらしか読まないでしょ！"
"70009010-59-寮監隊員" = "はぁ、それが問題なんだよ……。"
"70009010-60-寮監隊員" = "押収品は倉庫行き、と……はい、次の方。"
"70009010-61-寮監隊員" = "よいしょっ……と。"
"70009010-62-寮監隊員" = "多いですね。では、中身を確認します。"
"70009010-63-アトリエのオーナー" = "はい！申告通りのはずですよ！"
"70009010-64-寮監隊員" = "どれどれ……レッドフラワーの筆6本入りが50セット、クルーガーSBの4号から8号が50セット、キャンバスは3号が100枚に4号が100枚、あとは塗膜剥離剤が1缶と……。"
"70009010-65-寮監隊員" = "ん？キャンバスの裏に何か……。"
"70009010-66-アトリエのオーナー" = "あっ……！"
"70009010-67-寮監隊員" = "……こちらは？"
"70009010-68-アトリエのオーナー" = "ご覧の通り……ミレニアム製のナパーム弾です。"
"70009010-69-寮監隊員" = "SMGに手榴弾……未申告のものばかりですが。"
"70009010-70-アトリエのオーナー" = "あ～……私物でして。#nどうせなら一緒に運ぼうかなと。"
"70009010-71-アトリエのオーナー" = "でも、こんなものまで申告がいるんですか？"
"70009010-72-寮監隊員" = "……たしかに、銃までいちいち申告していてはキリがないですね。#n衣服まですべてチェックするようなものです。"
"70009010-73-寮監隊員" = "はい、問題ありません。お進みください。"
"70009010-74-アトリエのオーナー" = "どうもありがとうございます～"
"70009010-75-寮監隊員" = "全員、今のような感じなら、この仕事も楽なのに。#n……はぁ、次の方どうぞ。"
"70009010-76-無謀なワイルドハントの生徒" = "ほら！外出証と今回の搬入品だ！早くしてくれ！#n今、インスピレーションが湧いてきたところなんだ！"
"70009010-77-寮監隊員" = "は、はい。少々お待ちください……。"
"70009010-78-寮監隊員" = "これは……一体何でしょう？"
"70009010-79-無謀なワイルドハントの生徒" = "トリニティから持ってきた彫像だよ！#nこれをすりつぶして絵の具にすれば、繊細で柔らかい白色になるんだ！"
"70009010-80-寮監隊員" = "あの……持ち主の許可は取っていますか？"
"70009010-81-無謀なワイルドハントの生徒" = "え？置いてあったから貰ったんだよ。#nどう見ても骨董品だろ？"
"70009010-82-寮監隊員" = "たしかに古いもののようですが。"
"70009010-83-無謀なワイルドハントの生徒" = "作ったやつなんて、どこにいるやら……。"
"70009010-84-寮監隊員" = "ひとまず没収します。#n色々とお聞きしたいことがあるので、こちらでお待ち――"
"70009010-85-無謀なワイルドハントの生徒" = "は、はあ！？#nインスピレーションは待ってくれないんだぞ！"
"70009010-86-無謀なワイルドハントの生徒" = "……さては、私のアイデアを盗むつもりだな！？  "
"70009010-87-寮監隊員" = "盗んでるのはあなたの方でしょう。#n制裁の対象になりますよ。"
"70009010-88-無謀なワイルドハントの生徒" = "制裁……？芸術を弾圧する気か！！"
"70009010-89-寮監隊員" = "いや、ですから……これは犯罪で……。"
"70009010-90-無謀なワイルドハントの生徒" = "私は権力に屈しない！#n芸術は、世界との終わりなき闘争から生まれるんだ！！"
"70009010-91-寮監隊員" = "あっ！#nこちら検問所！不法侵入者です！"
"70009010-92-寮監隊員A" = "なに！？どこだ！？"
"70009010-93-寮監隊員B" = "すぐ追いかけろ！"
"70009010-94-ワイルドハントの生徒たち" = "なんだ？騒がしいね。"
"70009010-95-ワイルドハントの生徒たち" = "あの子は持ち込んでいいの？#nじゃ、私のも返してよ！"
"70009010-96-ワイルドハントの生徒たち" = "今のうちにこっそり入っちゃえ……！"
"70009010-97-寮監隊員B" = "な、なんだ、こいつら！？下がれ！！"
"70009010-98-寮監隊員B" = "こちら検問所！非常事態です！#n生徒が集団で検問を突破しようと……！増援を求めます！"
"70009010-99-ワイルドハントの生徒たち" = "今だ！自由を弾圧する寮監隊を追い出せ！"
"70009010-100-ワイルドハントの生徒たち" = "ビバ！ワイルドハント！我々は奴隷にはならない！  "
"70009010-101-寮監隊員" = "あ……。"
"70009010-102-寮監隊員" = "鳩だ。"
