[translation]
"2004506-1" = "断れない申し出"
"2004506-2" = "（一人の観光客として、フィーナのツアーに参加した）"
"2004506-3-フィーナ" = "ここから先は、現地ガイドの方の案内に従って入場しマス！"
"2004506-4-フィーナ" = "集合時間までにバスへ戻ってきてクダサイね！"
"2004506-5-観光客A" = "うわぁ……立派なお城だ……！"
"2004506-6-運転手" = "何度来てもここはすごいね。"
"2004506-7-運転手" = "いつか、じっくり見て回りたいもんだ。"
"2004506-8" = "[s1]（せっかくだし、フィーナの様子を見に行ってみようかな）\n[s2] \"よかったら、私の代わりに見てきませんか？\""
"2004506-9-運転手" = "えっ、ほんとかい？"
"2004506-10-運転手" = "悪いね。じゃあ、お言葉に甘えようかな……！"
"2004506-11" = "（フィーナの様子を見るために、バスに戻ることにした）"
"2004506-12-フィーナ" = "雨予報だから、傘も準備シテ……。"
"2004506-13-フィーナ" = "配布用のパンフレットはココ……。"
"2004506-14-フィーナ" = "ペットボトルは1本、2本、3本……。もう一度！1本、2本……"
"2004506-15-フィーナ" = "念には念を入れマス！1本、2本……。"
"2004506-16" = "[s] \"フィーナ、お疲れ様。\""
"2004506-17-フィーナ" = "あっ！センセイ！"
"2004506-18-フィーナ" = "次の行き先の準備をしていマシタ！"
"2004506-19-フィーナ" = "センセイはどうしてココに……ま、また何かやらかしマシタ！？"
"2004506-20" = "[s] （フィーナの様子を見に来たことを説明する）"
"2004506-21-フィーナ" = "そういうことデスネ！でも、もう昔の未熟なフィーナとは違いマス！"
"2004506-22-フィーナ" = "ミスをしないように、石橋を何度も叩いて渡りマス！"
"2004506-23-フィーナ" = "トリプルチェック、デス！1本……2本……。"
"2004506-24" = "[s3] \"もうその辺で十分じゃないかな？\"\n[s4] \"少し一緒に休憩しない？\""
"2004506-25-フィーナ" = "で、でも……やらかしが怖クテ……"
"2004506-26-フィーナ" = "念には念をデス……。"
"2004506-27" = "[s5] \"フィーナは十分頑張ってるから。\"\n[s6] \"休むことも、大事な仕事の一つだよ。\""
"2004506-28-フィーナ" = "身に余るお言葉、大変恐縮デス！"
"2004506-29-フィーナ" = "センセイにそう言われては断れマセン……！"
"2004506-30" = "（フィーナと一緒にバスの中で休むことにした）"
"2004506-31" = "[wa:630]― [log=피나 가이드]うーん、[wa:2080]ハッ！[/log]"
"2004506-32" = "― [log=피나 가이드]……なんだか、[wa:1100]緊張していたみたいデス。[/log]"
"2004506-33" = "[wa:1000]― [log=피나 가이드]お客さんと一緒の間は[wa:1440]夢中だったから、[/log]"
"2004506-34" = "― [log=피나 가이드]気づかなったのデスが……[/log]"
"2004506-35" = "[wa:1000]― [log=피나 가이드]こうして先生と一緒にいると、[/log]"
"2004506-36" = "― [log=피나 가이드]なんだか[wa:920]心が落ち着きマス。[/log]"
"2004506-37" = "[wa:1000]― [log=피나 가이드]軽やかに動くためには[wa:1110]ストレッチは必須デス！[wa:1380]もう一度！[/log]"
"2004506-38" = "― [log=피나 가이드]ん、[wa:880]んん、[wa:1160]うーん！[/log]"
"2004506-39" = "[wa:570]― [log=피나 가이드]え？[wa:1060]肩の力を抜いた方がイイ……[wa:2700]デスか？[/log]"
"2004506-40" = "[wa:2400]― [log=피나 가이드]そ、[wa:700]その……[wa:1720]これは[wa:960]ガイドとして[/log]"
"2004506-41" = "― [log=피나 가이드]気合いを入れているといいマスか……。[/log]"
"2004506-42" = "― [log=피나 가이드]二人っきりだと……[wa:1900]その……。[/log]"
"2004506-43" = "[wa:1330]― [log=피나 가이드]つい、[wa:1070]リラックスしてしまうから……。[/log]"
"2004506-44-観光客A" = "あれ？"
"2004506-45-観光客B" = "集合時間まだだっけ？"
"2004506-46-フィーナ" = "Oops！？"
"2004506-47-フィーナ" = "急いでお迎えしなければ！"
"2004506-48-フィーナ" = "お帰りなサイ！お疲れ様でシタ！"
"2004506-49-フィーナ" = "楽しかったです～"
"2004506-50-フィーナ" = "先生のおかげでしっかり見て回れたよ！ありがとう！"
"2004506-51-フィーナ" = "！！！"
"2004506-52-フィーナ" = "……ど、どうぞ、ご乗車クダサイ！"
"2004506-53" = "[ns] \"フィーナ？どうかしたの？\""
"2004506-54-フィーナ" = "エット……。"
"2004506-55-フィーナ" = "フィーナ、バスの中に靴が置きっぱなしデシタ……！"
"2004506-56" = "[s7] \"……！とりあえず平然としておこう！\"\n[s8] \"バレないようにね……！\""
"2004506-57-フィーナ" = "し……承知デス！"
"2004506-58" = "（全員が乗車した後、フィーナは誰にも気付かれないように素早く靴を履き直した）"
