[translation]
"2004503-1" = "エリートガイドの掟"
"2004503-2" = "（フィーナが担当するバスツアーに参加した）"
"2004503-3" = "（百鬼夜行の名所を順繰りに巡るコースだった）"
"2004503-4-フィーナ" = "それでは皆さま、ご乗車クダサイ！"
"2004503-5-フィーナ" = "センセイもどうぞ！"
"2004503-6" = "[s1] \"フィーナ、すっかりガイドが板についてきたね。\"\n[s2] \"一度に大勢を引率するのは大変そう。\""
"2004503-7-フィーナ" = "心配ご無用！人々をまとめ上げるのもまた、任侠道デス！！"
"2004503-8-フィーナ" = "予定より押してるケド、まだギリギリ間に合いマス！"
"2004503-9-フィーナ" = "レッツゴーデス！"
"2004503-10-フィーナ" = "こちらが本日最後のスポットデース！皆サン、お足元には気を付けてクダサイ！"
"2004503-11-フィーナ" = "一人……二人……。"
"2004503-12-フィーナ" = "十一人……十二人……。"
"2004503-13-フィーナ" = "……。"
"2004503-14-フィーナ" = "……。"
"2004503-15-フィーナ" = "What！？"
"2004503-16" = "[s3] \"どうしたの？\"\n[s4] \"お、落ち着いて！\""
"2004503-17-フィーナ" = "た、た……！！"
"2004503-18-フィーナ" = "大変デス！お頭……いえセンセイ！ "
"2004503-19-フィーナ" = "お客様が……一人足りマセン……！"
"2004503-20" = "[s] \"か、数え間違いではないんだよね……？\""
"2004503-21-フィーナ" = "ええ、しっかり数えマシタ！"
"2004503-22-フィーナ" = "それにガイドの掟として、お客様の顔は全て覚えていマス！"
"2004503-23-フィーナ" = "き、きっと乗り遅れてしまったんデス……！"
"2004503-24" = "[s5] \"まずは落ち着こう……！\"\n[s6] \"とりあえず、さっきの場所に戻ってみようか。\""
"2004503-25-フィーナ" = "ハ、ハイ！"
"2004503-26" = "（道中、フィーナは焦りを隠しきれずそわそわしていた）"
"2004503-27-フィーナ" = "急いで探さないとデス……！"
"2004503-28-フィーナ" = "この落とし前、どうつければいいのか……不肖フィーナ、面目次第もありマセン！"
"2004503-29-観光客A" = "あのー、ガイドさん？"
"2004503-30-フィーナ" = "キ、キャーッ！！"
"2004503-31" = "[ns] \"う、うわあっ！？\""
"2004503-32-観光客A" = "び、びっくりした……どうしたの？"
"2004503-33-フィーナ" = "そ、それがですね……エット……。"
"2004503-34-観光客A" = "あっ！……私一番乗りだった？"
"2004503-35-フィーナ" = "そ、そうではなく……その……！"
"2004503-36" = "[s7] （フィーナが完全にパニック状態だ……なんとかしないと！）\n[s8] \"実は、タクシーツアーに切り替えるのはどうかと思いまして！\""
"2004503-37-観光客A" = "タクシー……ツアー？"
"2004503-38-フィーナ" = "……。"
"2004503-39" = "[s9] \"目的地まで、特別にタクシーを手配しています。\"\n[s10] \"ゆったりと、目的地までの風景を楽しみませんか？\""
"2004503-40-フィーナ" = "！！"
"2004503-41-フィーナ" = "……！"
"2004503-42-フィーナ" = "すみマセン……既に、バスが出発していマシテ……。"
"2004503-43-フィーナ" = "他の皆様は、既に次の目的地へ向かっているんデス……。"
"2004503-44-フィーナ" = "すべてワタシの不手際デス！……今すぐタクシー乗り場にご案内しマス！"
"2004503-45-観光客A" = "……。"
"2004503-46-観光客A" = "……ううっ。"
"2004503-47-観光客A" = "……。"
"2004503-48-観光客A" = "あっ、なーんだ。そういうこと？"
"2004503-49-観光客A" = "ついお土産選びに夢中になっちゃっててさ……。"
"2004503-50-観光客A" = "戻ったら誰もいないなーって思ってたんだ。"
"2004503-51-フィーナ" = "！！"
"2004503-52-観光客A" = "遅刻したのは私のせいなのに、わざわざありがとう！"
"2004503-53-観光客A" = "それじゃガイドさん、よろしくね。"
"2004503-54-フィーナ" = "了解デス！お任せクダサイ、姐さん！"
"2004503-55-観光客A" = "あ……姐さん……？"
"2004503-56-フィーナ" = "集合時間ピッタリデス！"
"2004503-57-観光客A" = "みんな～、ただいま！"
"2004503-58-観光客B" = "あんた、どこ行ってたの？"
"2004503-59-観光客A" = "ふふっ、ちょっと……別のコースをね！"
"2004503-60-フィーナ" = "任務……完遂デス……。"
"2004503-61" = "[ns] \"フィーナ、大丈夫！？\""
"2004503-62" = "（その後、ツアーは無事終了した）"
"2004503-63" = "（再び元気を取り戻したフィーナは、誰一人欠けることなく参加者全員を見送った）"
