[translation]
"1002702-1" = "思わぬ角度"
"1002702-2" = "（お願いされたものを持って、アスナがいると聞いた場所に来たのだけれど、辺りには誰もいない……）"
"1002702-3" = "[ns] \"……？\""
"1002702-4-カリン" = "こちらカリン。"
"1002702-5-カリン" = "えっと、先生？"
"1002702-6-カリン" = "その、ごめん……今聞いたんだけど、どうやら手違いがあったみたいで……。"
"1002702-7-カリン" = "アスナ先輩がまたどこか、見当もつかない場所に……。"
"1002702-8-カリン" = "本当に申し訳ない、忙しい中こっちから頼んだのに……。"
"1002702-9-カリン" = "どうしようか……。"
"1002702-10-カリン" = "……とりあえず、そこに置いておいてもらえる？これ以上迷惑をかけるわけにはいかないし……。"
"1002702-11-カリン" = "あとで落ち着いた頃に、私が取りに行くから。"
"1002702-12" = "[s1] \"それでも全然良いんだけど……。\"\n[s2] \"カリンは今、どこにいるの？\""
"1002702-13-カリン" = "……ん？"
"1002702-14-カリン" = "……ん？"
"1002702-15-カリン" = "私？"
"1002702-16-カリン" = "えっと……今先生がいる位置から一つ横の道に入った先に、廃墟が見えると思うのだけど。"
"1002702-17-カリン" = "今はそこの最上階にいる。ただ、今は監視対象から注意を逸らすわけにはいかなくて……。"
"1002702-18" = "[s] \"じゃあ、そこまで持っていくね。\""
"1002702-19-カリン" = "え？"
"1002702-20-カリン" = "そ、そこまでしてもらうのは、申し訳ないような……。"
"1002702-21-カリン" = "何だか、先生をこき使っているみたいで……。"
"1002702-22" = "[s] \"全然大丈夫だよ、ちょっと待ってて。\""
"1002702-23-カリン" = "それなら……うん。"
"1002702-24-カリン" = "じゃあ、お願いしようかな。"
"1002702-25-カリン" = "ありがとう、先生。"
"1002702-26" = "（その廃墟はかなり荒んでいて、だいぶ前に打ち捨てられた場所のようだった）"
"1002702-27" = "（自分の足音だけが、やたらと大きく響く）"
"1002702-28-カリン" = "先生、迷子になってたりしない？"
"1002702-29-カリン" = "……あ、先生の足音聞こえた。"
"1002702-30-カリン" = "もう迷う心配は無さそうだね、じゃあ。"
"1002702-31" = "[s] そのまま真っすぐに進む。"
"1002702-32" = "……あ、先生？"
"1002702-33" = "[s] \"……っ！？\""
"1002702-34" = "……？"
"1002702-35" = "先生、どうかした？"
"1002702-36" = "姿勢……？"
"1002702-37" = "……うぇっ！？"
"1002702-38" = "[wa:50]― ……うぇっ！？"
"1002702-39" = "[wa:700]― せ、[wa:1200]先生！？[wa:1700]ちがっ、[wa:870]これはその……！"
"1002702-40" = "[wa:50]― 待って！[wa:1250]今は、[wa:480]姿勢を変えるわけにいかなくて……！"
"1002702-41" = "[wa:1050]― えっと、[wa:1450]今は狙撃任務中で……！"
"1002702-42" = "[wa:100]― ターゲットから[wa:400]狙いを外すわけにはいかないし、"
"1002702-43" = "― だから……！"
"1002702-44" = "[wa:550]― ……え、[wa:1700]こっちは大丈夫……？"
"1002702-45" = "― ……むしろ、[wa:880]そのままでお願い？[wa:2150]ちょっ……！"
"1002702-46" = "[wa:1000]― な、[wa:1020]何だか[wa:480]喜んでるみたいだけど、[wa:2530]これは流石に……！"
"1002702-47" = "― やっぱり[wa:500]無理だ、[wa:1300]恥ずかしい……っ！"
"1002702-48" = "[wa:650]― え、[wa:1100]気にせず続けて……？"
"1002702-49" = "― き、[wa:1000]気にせずにいられるか！[wa:1770]バカっ！"
"1002702-50" = "（カリンが任務を終えるまで、そのまま後ろでおとなしく待っていた）"
"1002702-51-カリン" = "……とりあえず、任務完了。"
"1002702-52-カリン" = "ん？この格好……？"
"1002702-53-カリン" = "ああ、その、今日は誰とも会わない任務だからせっかくだし、と思って……。"
"1002702-54-カリン" = "それより……はぁ、ごめん。ちょっと、こうなるとは思ってなかった。"
"1002702-55-カリン" = "先生が来るって分かってたのに、そこまで頭が回らなくって……。"
"1002702-56-カリン" = "えっと、私はもう少しここにいる予定だけど、とにかくありがとう。先生はそろそろシャーレに戻る？"
"1002702-57-カリン" = "……もう少し一緒にいる？"
"1002702-58-カリン" = "ふふっ。もしかして先生、私がひとりで寂しがってるんじゃないかとか思って、そんな優しいことを言ってるのか？"
"1002702-59-カリン" = "大丈夫だ、スナイパーはひとりで待機してるなんてことしょっちゅうだし……"
"1002702-60-カリン" = "……そういうことじゃない？それって、もしかしてその……"
"1002702-61-カリン" = "……目の保養？"
"1002702-62-カリン" = "……はぁ。"
"1002702-63-カリン" = "先生は本当に、全くもう……。"
