[translation]
"1002703-1" = "思わぬ誤解"
"1002703-2-カリン" = "……あ、先生。こっちこっち、待ってたよ。"
"1002703-3-カリン" = "……？"
"1002703-4" = "[s] \"……。\""
"1002703-5-カリン" = "……すごい顔をしてるけど、どうしたんだ？"
"1002703-6-カリン" = "ああ、この格好？"
"1002703-7-カリン" = "これはこのカフェに合わせて……。"
"1002703-8-カリン" = "そういえばこの前も、先生はこの衣装に結構反応してたけど……。"
"1002703-9-カリン" = "そんなに好きなのか？何だったら私はこれ――"
"1002703-10-カリン" = "気にしないで？"
"1002703-11-カリン" = "何だかその反応も怪しい気が……。"
"1002703-12-カリン" = "……先生。"
"1002703-13-カリン" = "一応聞くのだけど、もしそんなにこの格好が好きなら、その……。"
"1002703-14" = "[s1] \"いやその、何て言うか、えっと……。\"\n[s2] \"と、とりあえず案内してもらおうかな。\""
"1002703-15-カリン" = "やっぱり、珍しい反応をしてるな……？"
"1002703-16-カリン" = "やっぱり、珍しい反応をしてるな……？"
"1002703-17-カリン" = "もしかして、そこまで好きなのか？"
"1002703-18-カリン" = "そうか、そこまでバニーガールが好きだったなんて……。"
"1002703-19-カリン" = "意外というか何と言うか……。"
"1002703-20-カリン" = "ああいや、もちろん趣味はそれぞれだし、私も可愛くて気に入ってる。"
"1002703-21-カリン" = "先生がどんな趣味を持っているとしても、絶対に悪くは言わない。むしろどんなものでも、理解したいとすら思ってる。"
"1002703-22-カリン" = "だからそんなに好きなら、この衣装で協力してあげたいというか……その、今までもたくさん助けてもらったわけだし……。"
"1002703-23-カリン" = "……ん？何をそんなに慌ててるんだ？"
"1002703-24-カリン" = "……ふふっ。"
"1002703-25-カリン" = "先生がそんなに動揺するなんて、よっぽどだな。"
"1002703-26-カリン" = "まあ、今はこの辺にしておこう。そういうのはまた今度。"
"1002703-27" = "[s] \"また今度……！？\""
"1002703-28-カリン" = "気にしないで良い、先生。私は先生のためなら構わない。"
"1002703-29-カリン" = "別にそうなっても、先生のことを変な目で見たりはしないし……。"
"1002703-30-カフェのオーナー" = "あらあら、もうカリンちゃん。また抜けちゃってるわよ？"
"1002703-31-カリン" = "……あ。"
"1002703-32" = "[s] \"？？？\""
"1002703-33-カフェのオーナー" = "全くもー、お客様のことは「ご主人様」でしょ？"
"1002703-34-カリン" = "そ、そうだった……。"
"1002703-35-カリン" = "つい……。"
"1002703-36-カリン" = "すみません、気を付けます。"
"1002703-37-カフェのオーナー" = "ふふっ、このお店で呼び方はすっごく大事だからね。"
"1002703-38-カフェのオーナー" = "頑張ってるのは分かってるから、それさえできれば完璧よ。"
"1002703-39-カリン" = "は、はい。"
"1002703-40-カリン" = "……ふぅ。"
"1002703-41-カリン" = "……危うくバレるところだった。"
"1002703-42" = "[s3] \"その……。\"\n[s4] \"カリン、さっきの話だけど……。\""
"1002703-43-カリン" = "確かによく考えると……。"
"1002703-44-カリン" = "確かによく考えると……。"
"1002703-45-カリン" = "こういう話を、公的な場所で話すのは良くないな。ごめん、先生。気を付けるよ。"
"1002703-46-カリン" = "でも心配しないで、先生……"
"1002703-47-カリン" = "いや、ご主人様。"
"1002703-48-カリン" = "私を信じて。誰にも言ったりしないから。"
"1002703-49-カリン" = "ではあらためて……いらっしゃいませ、ご主人様？"
"1002703-50" = "[ns] \"……。\""
"1002703-51" = "（結局、モヤモヤしたままお店を後にした）"
