[translation]
"1013908-1" = "ニコのいなり寿司"
"1013908-2" = "（ニコの言っていた保存食が気になって、昼休みに少しだけ調理室を覗いてみた）"
"1013908-3" = "シャーレ建物内調理室"
"1013908-4" = "（扉を開けた瞬間、油がぽつぽつ跳ねる音と香ばしい匂いがふわりと鼻をくすぐった）"
"1013908-5" = "[ns] \"この匂いは……。\""
"1013908-6-ニコ" = "あ、先生。いらしてたんですね。\r\n"
"1013908-7-ニコ" = "仕上がるまでは、まだもう少しかかるので……ちょっと早かったかもしれません。"
"1013908-8" = "[s1] \"すごく美味しそうな匂いがしてるけど。\"\r\n[s2] \"戦闘糧食を作るって言ってなかった？\""
"1013908-9-ニコ" = "はい、戦闘糧食ですよ。"
"1013908-10-ニコ" = "今作っているのは、昔の兵士が携帯していた伝統的な戦闘糧食――"
"1013908-11-ニコ" = "そう、いなり寿司です！\r\n"
"1013908-12" = "[s] \"いなり寿司が、戦闘糧食になるの？\""
"1013908-13-ニコ" = "はい。いなり寿司は戦闘糧食の条件を満たしているんです。\r\n\r\n"
"1013908-14-ニコ" = "油で揚げてあるので高カロリーですし、水分が少なく傷みにくい。#nそれにお酢には抗菌作用がありますから――"
"1013908-15-ニコ" = "火が使えない状況下で、これほど頼れる糧食はありません。"
"1013908-16-ニコ" = "欠点は、美味しすぎてすぐに食べてしまうところでしょうか。ふふ。\r\n"
"1013908-17" = "[ns] \"言われてみれば……そうかも。\""
"1013908-18" = "[ns3] \"わざわざ時間をとってまで作るってことは――\"\r\n[ns4] \"いつものいなり寿司とは違うの？\""
"1013908-19-ニコ" = "はい。今回はお豆腐を揚げるところから中の具材まで全部手づくりしようと思って。"
"1013908-20-ニコ" = "いつもFOX小隊のお弁当に詰めているのは、市販の油揚げを使っているんですが――"
"1013908-21-ニコ" = "一度くらい、自分で揚げた油揚げで作ってみたくて。\r\n"
"1013908-22-ニコ" = "あ……もうこんな時間。\r\n"
"1013908-23-ニコ" = "少し、失礼しますね……。\r\n"
"1013908-24" = "[wa:390]― [log=니코]ふふ、[wa:1470]よく揚がっていますね。[/log]"
"1013908-25" = "― [log=니코]ふっ[wa:310]くらしていて……[wa:1890]仕上がりが楽しみです。[/log]"
"1013908-26" = "[ns] \"これは……おいしそうだ。\""
"1013908-27" = "[wa:860]― [log=니코]あ、[wa:880]まだダメですよ。[/log]"
"1013908-28" = "[wa:480]― [log=니코]この後、[wa:530]もう1回揚げるんですから。[/log]"
"1013908-29" = "― [log=니코]最初は低い温度で。[/log]"
"1013908-30" = "― [log=니코]次に高い温度で揚げると、[wa:2080]水分が抜けて美味しい油揚げになるんです。[/log]"
"1013908-31" = "[ns] \"油揚げって、こんなに手間がかかるんだね……。\""
"1013908-32" = "[wa:1220]― [log=니코]油揚げって実は、[/log]"
"1013908-33" = "― [log=니코]すごく時間と手間のかかる料理なんですよ。[/log]"
"1013908-34" = "― [log=니코]それこそ昔は、[/log]"
"1013908-35" = "― [log=니코]1年の豊作と安寧を願う[wa:2620]お供え物だったんだとか。[/log]"
"1013908-36" = "[wa:2050]― [log=니코]私の願いは、[/log]"
"1013908-37" = "― [log=니코]周りのみんなが幸せで、[wa:2420]平穏無事に過ごせること。[/log]"
"1013908-38" = "― [log=니코]油揚げに込めた私の気持ちが伝わってくれたら……[/log]"
"1013908-39" = "― [log=니코]嬉しいですね。[/log]"
"1013908-40-ニコ" = "二度揚げした油揚げ、完成です！"
"1013908-41-ニコ" = "これから煮たりしないといけないので、まだいなり寿司にはなりませんが……。"
"1013908-42-ニコ" = "先生、一口、味見していただけませんか？"
"1013908-43" = "[s5] \"私でよければ……。\"\r\n[s6] \"初めての手作り油揚げを、もらっちゃっていいの？\""
"1013908-44-ニコ" = "もちろんです。#n先生に食べていただけるのなら、とても嬉しいです。"
"1013908-45" = "[s] \"それじゃあ……いただきます。\""
"1013908-46" = "[ns7] \"あつあつでふかふかだね！\"\n[ns8] \"このふわっとした食感、本当にいいね！\""
"1013908-47-ニコ" = "お口にあったならよかったです。#nどんな厚さでも作れるのが手作りの良さですね。"
"1013908-48-ニコ" = "少し欲張ってしまったから、油揚げというより厚揚げに近くなった気もしますけど……。\r\n"
"1013908-49-ニコ" = "でも、初めてにしては上出来だと思います。"
"1013908-50-ニコ" = "……ところで先生。#n今日、このあとお食事のご予定はありますか？"
"1013908-51-ニコ" = "よければ、この油揚げでいなり寿司を作るので……#nお夕飯に、いかがでしょう？"
"1013908-52" = "[s] \"もちろん、喜んで！\""
"1013908-53-ニコ" = "はい。それではすぐ用意しますので、先生はゆっくり待っていてくださいね。\n"
"1013908-54" = "[s] \"でも……。\""
"1013908-55-ニコ" = "手伝わなくて大丈夫です。#nこれはあくまで、私が作りたくて作っているものですから。\r\n"
"1013908-56-ニコ" = "……それに、先生へ捧げる私の「初の供物」でもありますし。"
"1013908-57" = "（その後、ニコが作ってくれた手作りのいなり寿司を食べながら穏やかで満ち足りた夕食の時間を過ごした）"
"1013908-58" = "（ニコの油揚げは、どこか柔らかくて、温かい味がした）"
