[translation]
"1004903-1" = "こう見えても放課後スイーツ部の一員"
"1004903-2" = "（仕事の途中、息抜きに散歩をすべく外へ出た）"
"1004903-3" = "（道路の片側にあるバス停で、見慣れた人影が見えた）"
"1004903-4" = "[s1] \"あれ？カズサ？\"\n[s2] \"こんばんは。\""
"1004903-5-カズサ" = "……あれ、先生？"
"1004903-6-カズサ" = "……あれ、先生？"
"1004903-7-カズサ" = "どうしたのこんな遅い時間に……もしかして散歩？"
"1004903-8-カズサ" = "……ん？私？"
"1004903-9-カズサ" = "えっと……見ての通りバス待ち中。"
"1004903-10-カズサ" = "ここから寮に向かうバスは間隔がすごく長くて。#n運が悪かったらまるまる20分は待たないといけないの。"
"1004903-11-カズサ" = "まあ、地下鉄乗ればちょっと早く帰れるけど……。"
"1004903-12-カズサ" = "……人混みは苦手で。#nほら、この辺人いないでしょ？バスも同じでガラガラだから。"
"1004903-13-カズサ" = "時間が少しかかっても、人が少ないほうが好き。その方が余裕も出るし。"
"1004903-14-カズサ" = "それに、このバス停には椅子がある。"
"1004903-15-カズサ" = "つまり……。"
"1004903-16-カズサ" = "ご覧のとおり、座っておやつを食べる時間もある……ということだよ。ふふ。"
"1004903-17-カズサ" = "はい、先生もどうぞ。"
"1004903-18" = "[s3] \"いいの？\"\n[s4] \"カズサのジュースでしょ？\""
"1004903-19-カズサ" = "私の心配はしなくていいよ。他にもあるから大丈夫。"
"1004903-20-カズサ" = "私の心配はしなくていいよ。他にもあるから大丈夫。"
"1004903-21-カズサ" = "ジャーン！こういう風に、マカロンとかも持ち歩いているの。"
"1004903-22-カズサ" = "ふふっ。こう見えても放課後スイーツ部の一員だよ。#nカバンの中のおやつはジュースだけじゃないって事。"
"1004903-23-カズサ" = "「スイーツは一人で食べるより、みんなで食べる方がもっとおいしいもの」……。"
"1004903-24-カズサ" = "……って、あいつらが言ってたし。ははっ。"
"1004903-25-カズサ" = "あ、今のはうちのスイーツ部の話。"
"1004903-26" = "[s5] \"カズサもスイーツが好きなんだね。\"\n[s6] \"部活のそういう雰囲気だけ楽しんでいるのかと思った。\""
"1004903-27-カズサ" = "ん～……やっぱそう見えるのかな。#nそりゃ自分でもちょっと不思議だとは思うけど……。"
"1004903-28-カズサ" = "ん～……やっぱそう見えるのかな。#nそりゃ自分でもちょっと不思議だとは思うけど……。"
"1004903-29-カズサ" = "でもスイーツが嫌いな女子高生って、この世にいると思う？#n好きなスイーツの種類が違うだけだと思うな。"
"1004903-30-カズサ" = "本当に、他のメンバーにただ付き合うために食べてるわけじゃないからね。#nイチゴが乗ったショートケーキも好きだし、マカロンも大好き。"
"1004903-31-カズサ" = "むしろスイーツが好きすぎて……安物の量産品は避けるぐらいっていうか。"
"1004903-32-カズサ" = "話が出たついでに。いつか、先生にも私の「オススメ店」を教えてあげたいな。"
"1004903-33-カズサ" = "きっと先生も好きだと思う……#nあ、まあ……甘いものが好みじゃなかったら、まあまあかもしれない。"
"1004903-34-カズサ" = "……うーん、でも意外と大丈夫かも。くどい甘さじゃないし。"
"1004903-35-カズサ" = "それかもう少しあっさりした方が……。"
"1004903-36-カズサ" = "……あ。"
"1004903-37-カズサ" = "話してたらバス来ちゃった。もうちょっと後で来ると思ってたのに……"
"1004903-38-カズサ" = "これに乗らないと、また20分くらい待たないといけないし……"
"1004903-39-カズサ" = "……仕方ない。まだおやつもジュースも結構残ってるけど、行かなきゃ。"
"1004903-40-カズサ" = "んー……。"
"1004903-41-カズサ" = "先生、その……一応、念のため。本当に何の他意もないんだけど。"
"1004903-42-カズサ" = "えっと……その。"
"1004903-43" = "[s7] \"今日の仕事は全部終わってるから。\"\n[s8] \"20分ぐらいは大丈夫だよ。\""
"1004903-44-カズサ" = "……はぁ。"
"1004903-45-カズサ" = "本当に……先生は……"
"1004903-46-カズサ" = "……いつも思うけど、他の子にもそんな風に言ってるの？"
"1004903-47-カズサ" = "いつか誰かが先生に襲いかかったとしても、その時は自業自得だからね。#n肝に銘じておきなよ、分かった？"
"1004903-48-カズサ" = "うーん……でも、まあ……。"
"1004903-49-カズサ" = "もし本当にそんな事が起きたら……。#n連絡してきてもいいよ。授業時間じゃなければ助けてあげるから。"
"1004903-50-カズサ" = "……ん？"
"1004903-51-カズサ" = "冗談に聞こえた？"
"1004903-52-カズサ" = "はぁ、またそんな風に……"
"1004903-53-カズサ" = "ま、いいよ。今はそういう事にしといてあげる。"
"1004903-54-カズサ" = "それじゃ……"
"1004903-55-カズサ" = "……続けよっか、先生？"
