[translation]
"10057030-1" = "第3話;何の用事で来たのか"
"10057030-2-アンナ" = "エリナって、本当に変な子だと思いません？"
"10057030-3-アンナ" = "いっつも、あの調子なんです。口を開いたら皮肉ばっかり！"
"10057030-4-アンナ" = "言ってることがめちゃくちゃなんです！エリナが開発した安っぽいプリンみたい！"
"10057030-5-エリナ" = "あのー、全部聞こえてるんですけど～？#nカーテンごしの声ってよーく通るんだよね～？"
"10057030-6-エリナ" = "というか、それ言うならアンナが言ってることの方がおかしいっての～"
"10057030-7-エリナ" = "それに……#nアンナの安っぽい機械より、私の「H2O過剰添加プリン」のほうがマシだし？"
"10057030-8-アンナ" = "安っぽいんじゃなくて、最適化って言ってちょうだい。「費用対効果」って言葉、知らないの？"
"10057030-9-アンナ" = "というか……冷たい風が入ってきてるから、ストーブを強くしてちょうだいよ！"
"10057030-10-アンナ" = "そもそもエリナがガスバルブを閉め忘れたから、#nキッチンの壁が吹き飛んでこんな目にあってるんでしょーが！"
"10057030-14-エリナ" = "う、うるさーい！ズルーッ！！"
"10057030-18-ラナ" = "……「意見交換」1回目。"
"10057030-20" = "[ns] \"2人とも、落ち着いて！\""
"10057030-22" = "[ns1] \"もう少し、みんなのことを教えてくれる？\"\n[ns2] \"みんなは、普段何しているの？\""
"10057030-26-アンナ" = "やっぱり、先生には正直にお話しします。"
"10057030-27-エリナ" = "別に嘘はついてないんだけどね～"
"10057030-28-ラナ" = "編集も加工の一種だから、完全な事実とは言えない。全部話したほうがいいと思う。"
"10057030-29-ラナ" = "「科学者は事実で勝負する」って本で読んだ。"
"10057030-30-アンナ" = "うーん……。"
"10057030-31-エリナ" = "ん～……。"
"10057030-35-アンナ" = "……実は、183号特別クラスは懲戒処分を受けた生徒が送られるクラスなんです。"
"10057030-36-アンナ" = "訳あって、停学処分の代わりに事務局から依頼された研究をしています。"
"10057030-37-アンナ" = "私はクラスの研究課題を管理しながら……#n個人の課題として、最低限の設備で安価な物を設計し――"
"10057030-38-アンナ" = "余った時間は、#nみんなで外部からの依頼を受けてお小遣いや戦車製作の費用を稼いでいるんです。"
"10057030-39" = "[s] \"停学処分？\""
"10057030-40-アンナ" = "ううっ、お話しするのも恥ずかしいのですが……。"
"10057030-41-アンナ" = "私はチェリノ会長専用の戦車を設計する、主席エンジニアでした。"
"10057030-42-アンナ" = "低予算の中、無茶な要求どおり作ったものが……#nよりにもよってパレード中に壊れてしまって――"
"10057030-43-アンナ" = "泥に落ちてしまったチェリノ会長に特別クラスへの降格を命じられたんです。"
"10057030-44-アンナ" = "100回上手くやっても、一度失敗したら左遷だなんて……。"
"10057030-45-エリナ" = "できないならできないって言えばよかったのにね～"
"10057030-46-エリナ" = "まぁ、私はちょっと挑戦しすぎちゃっただけっていうか……。"
"10057030-47-エリナ" = "公衆衛生を化学で解決しようとしたら、#nあのニセ髭に問答無用でぽいっとされちゃったんですよね～あははっ！"
"10057030-48" = "[s] \"何があったの？\""
"10057030-49-エリナ" = "私は、事務局に……あ～あれ、何だっけ……？"
"10057030-50-エリナ" = "ほら、あるでしょ？蛇口をひねると出てくるもの……！"
"10057030-51" = "[s] \"水道水？\""
"10057030-52-エリナ" = "それそれ！もー、す～ぐ単語が出てこなくなっちゃう……。"
"10057030-53-エリナ" = "と、とにかく！水道水を化学処理で浄化する研究をしろって言われたんですよ。"
"10057030-54-エリナ" = "たしかに、水道水がきれいなら風邪をひくこともなくなるし……ってわけでやってみることにしたんですけど……。"
"10057030-55-エリナ" = "問題は……オゾンや塩素で処理する設備が、予算の100倍以上するってことです！"
"10057030-56-エリナ" = "だから代わりに、エタノールで消毒しました！#n消毒効果はすごく良かったんですが――"
"10057030-57-エリナ" = "消毒後、エタノールを抜くのをうっかり忘れて、そのまま水道設備を稼働させてしまい――"
"10057030-58" = "[s] \"エタノールって……あ……。\""
"10057030-59-アンナ" = "学園全体を揺るがす、とんでもない大事件でした。#n先生にも、あの時の秘書室長の顔を見てもらいたかったです。"
"10057030-60-アンナ" = "うっ……！思い出すだけで頭が痛くなる……。"
"10057030-61-アンナ" = "あの時は本当に大変だったのよ……！？"
"10057030-62-エリナ" = "悪いのは、私じゃなくて予算をケチった事務局側でしょ！"
"10057030-63-アンナ" = "エリナがちゃんと勉強してなかったからじゃないの？"
"10057030-64-エリナ" = "ちゃんと勉強しましたけど～？#n化学者でもないのに適当なこと言うな！"
"10057030-65-アンナ" = "メスフラスコを加熱する化学者様、ねぇ……。"
"10057030-66-アンナ" = "メスフラスコは混合と滴定にのみ使用するって、#n教科書にも書いてあるレベルの知識じゃないかしら？"
"10057030-67-エリナ" = "わ～、知りませんでしたぁ～#n化学専攻の人間に講義までしてくださるなんて～#n学級委員長のアンナ様はすっばらしいですねぇ～"
"10057030-68-アンナ" = "ふんっ、分かってるならこれで勘弁してあげる。"
"10057030-69-エリナ" = "エリナはバカだからぁ～#n今アンナ様が飲んでいるカップにアンモニアを入れたことも忘れてましたぁ～"
"10057030-74-アンナ" = "ブーッ！！！"
"10057030-78-アンナ" = "よくもやったわね！？覚悟しなさい！！！"
"10057030-79-エリナ" = "べーだ！覚悟するのはそっちだよ～"
"10057030-84-ラナ" = "……今日はお客さんがいるから、2人とも元気がいいですね。"
"10057030-88-エリナ" = "はぁっ……はぁっ……。"
"10057030-89-アンナ" = "ぜーっ……はーっ……。"
"10057030-94-ラナ" = "説得を目的としていないので非公式試合となり、勝敗も無し。"
"10057030-101-エリナ" = "……今はここで、#n「水でかさ増しした、見た目だけはまともなプリン」を研究しています。"
"10057030-102-エリナ" = "水の量が多すぎて、軽く息を吹きかけるだけでどろっと……。"
"10057030-103-エリナ" = "うあー！こんな何もない山奥なんて、もぉーやだー！"
"10057030-104-エリナ" = "ラナは可愛いからいいけど、このゴチャゴチャうるさいのが学級委員長なんて最悪！"
"10057030-105-アンナ" = "私だって！エリナが副学級委員長なんて本当に最悪よ！"
"10057030-106-エリナ" = "ふんっ！！"
"10057030-107" = "[s] \"じゃあ、ラナは？\""
"10057030-108-ラナ" = "私は、何かミスをしたわけではありません。"
"10057030-110-アンナ" = "たしかに、ラナはそうよね……。"
"10057030-111-エリナ" = "この中だと、ラナが一番かわいそうかも……。"
"10057030-112-エリナ" = "入学してすぐこっちに連れてこられたんだから。"
"10057030-114-ラナ" = "そのとおりです。私は入学してから何か問題を起こしたわけではありません。"
"10057030-115-ラナ" = "ただ――入学試験を受けただけです。"
"10057030-116" = "[s] \"受験しただけでここに？\""
"10057030-117-ラナ" = "実は、試験のマークシートに欠陥があったんです。"
"10057030-118-ラナ" = "具体的には、点数を任意で入力できるようになっていました。#nなので、自分で点数をマークしました。"
"10057030-119-ラナ" = "結果――42億9496万7295点だったので、ここに連れてこられたんです。"
"10057030-120-ラナ" = "システムが32ビットだったのが残念でした。#n64ビットなら1844京6744兆737億955万1615点だったのに。"
"10057030-122-アンナ" = "ひどいと思いませんか？#nそこにやれる土壌があるのなら、試したくなるものでしょう？"
"10057030-123-アンナ" = "183号に来てなかったら、ラナは私に続くアカデミーのホープだったのに！"
"10057030-124-エリナ" = "どう考えても、悪いのはラナじゃなくてマークシートの方なのにね！"
"10057030-126-ラナ" = "その結果、ここに来て……#nやることといったらレッドウィンター内の電算管理くらいです。"
"10057030-127-ラナ" = "そうだ。頼まれていたもの、ちゃんと買ってきたよ。"
"10057030-128-エリナ" = "おお～！ラナ、ありがと～！"
"10057030-133-エリナ" = "ん……？牛乳が……6本？あれ？"
"10057030-134-ラナ" = "「牛乳を買ってきて。もしアボカドがあれば6つ買ってきて」って言ってたよね。"
"10057030-135-ラナ" = "だから、アボカドがあったので、牛乳を6本買ってきた。"
"10057030-136-エリナ" = "条件文どおりに実行したってこと……？"
"10057030-137-ラナ" = "何か間違えてた？"
"10057030-138-エリナ" = "……いや～、全然！流石ラナだね～！"
"10057030-139-ラナ" = "……ということで、183号特別クラスはここにいる3人で全員です。"
"10057030-140" = "[s] \"3人……？どうして立てている指は2本なの？\""
"10057030-141-ラナ" = "3人だから、です。"
"10057030-142" = "[s] \"？？？？？？\""
"10057030-143-アンナ" = "3人で十分な研究成果を出せば解放してくれるというので、#nこの山奥で毎日研究ばかりしているんです。あは、あはは……。"
"10057030-144-エリナ" = "私たち……どうしたら恩赦をもらえるか、ずっと考えてたんだよね～"
"10057030-145-エリナ" = "研究はちゃんとやってるけど、それだけじゃダメっぽいし～？"
"10057030-146-エリナ" = "そしたら、チェリノ会長がこの間ラジオでこう言ってたんです！"
"10057030-147-エリナ" = "「次のゲヘナカップでは、絶対にレッドウィンターが勝つのだ！」って。"
"10057030-148-エリナ" = "優勝した生徒には最高の報酬を出すと聞いて、これはチャンスだー！って。"
"10057030-149" = "[s] \"ゲヘナカップ？\""
"10057030-150-アンナ" = "ああ、ゲヘナカップというのはキヴォトス各地の強豪が集まる戦車のリーグ戦です。"
"10057030-151-アンナ" = "種目は戦車レースだけ。主催が毎回変わる晄輪大祭とは違い、ゲヘナ学園が主催しています。#nかなりの賞金が出るので、キヴォトス中の学園が参加するんですよ。"
"10057030-152-アンナ" = "予選からレベルが高くて、出場するだけでもかなり大変なんですが……#nもし仮に優勝したら――"
"10057030-153-アンナ" = "――キヴォトス最高の戦車として認められるんです！"
"10057030-154-エリナ" = "化学者として、こんな栄誉を逃すなんてあり得ません！"
"10057030-155-エリナ" = "それに、ここから抜け出せる絶好のチャンスだし！"
"10057030-159-エリナ" = "けど問題は……レッドウィンターの予選まであと4日ってこと！"
"10057030-160-エリナ" = "砲塔も、装備もない。それに、仮に部品を作ったとしても――"
"10057030-161-エリナ" = "肝心の設計が決まっていないんです。"
"10057030-162-アンナ" = "だから、私の言うとおりにやればいいのに！"
"10057030-163-エリナ" = "そんなことしたら、失敗作しかできないじゃん！"
"10057030-164-エリナ" = "「変なデザイン協会」の会長にもなりたいわけ！？"
"10057030-165-アンナ" = "ほんっと、憎まれ口だけは勲章ものよね！"
"10057030-169-ラナ" = "こうしてすぐに喧嘩を始めるので、先生に助けていただこうと思ったのです。"
"10057030-170-ラナ" = "先生は奇跡を起こせて、キヴォトス中の生徒を助けていると聞きましたから。"
"10057030-172-アンナ" = "今回は私の言う通りにすべきですよね、先生？"
"10057030-173-エリナ" = "いやいや！私でしょ～！？"
"10057030-178" = "[ns] \"一方の肩を持つことはできないよ。\""
"10057030-180" = "[ns] \"その代わり、科学的で公平な方法があるんだけど……。\""
"10057030-184-アンナ" = "そんな方法があるんですか！？"
"10057030-185-エリナ" = "何か分からないけど、めっちゃ良さそう！"
"10057030-189" = "[ns] 「大人の解決策」を提示する。"
"10057030-193-アンナ&エリナ" = "え？"
