[translation]
"10057070-1" = "第7話;何もそこまで"
"10057070-8-親衛隊" = "うわあああっ！！"
"10057070-12-マリナ" = "よくも事務局の公務を妨害してくれたな！！コソ泥反乱分子め！！"
"10057070-13-アンナ" = "コソ泥なんかじゃありません！スローガンに徹しているだけです！！"
"10057070-14-マリナ" = "親衛隊！！親衛隊！！反逆だ！！クーデターだ！！"
"10057070-15-マリナ" = "現在地は、えっと――"
"10057070-19-マリナ" = "ええいっ！！このポンコツ無線機！！！"
"10057070-21-エリナ" = "ここで応援が来ちゃったらアウトだよ！"
"10057070-22-アンナ" = "弾薬はもうないし、どうしよ……。"
"10057070-25-アンナ" = "「チョップブロック」やるわよ！！私は「ラリアット」で行くから！！！"
"10057070-26-エリナ" = "「アレ」を！？う、うわあああ！！もう知らないよ～！！！"
"10057070-37-アンナ&エリナ" = "うおおおおおっ！！！"
"10057070-39-マリナ" = "い、一体何を。"
"10057070-41-アンナ&エリナ" = "「High and Low」！！！"
"10057070-56-アンナ&エリナ" = "っしゃー！"
"10057070-61-マリナ" = "ぐあああっ！"
"10057070-66-アンナ" = "やっちゃった！？"
"10057070-70-親衛隊無線" = "マリナ委員長！？どちらですか！？"
"10057070-71-エリナ" = "やっちゃったね！"
"10057070-72-アンナ" = "早く逃げないと！材料は揃った？"
"10057070-73-エリナ" = "もち！じゃあ逃げよう！！"
"10057070-76-エリナ" = "ちょ、ちょっと待った！いっこ忘れてた！待ってて！！"
"10057070-82-アンナ" = "早く行かないと！急いで！"
"10057070-83-エリナ" = "よしっ！"
"10057070-84-エリナ" = "行こう！！急げ～！！"
"10057070-85-アンナ" = "むぐぐ……重いんだから、一緒に持ちなさいよ！"
"10057070-94-ラナ" = "ふむ……。"
"10057070-95-ラナ" = "バランスもこれでよし、と。かっこいいですよ、会長。"
"10057070-96-ラナ" = "銅の確保、完了。"
"10057070-100-アンナ" = "ラナ！ちゃんと集められた！？もう行くよ！"
"10057070-101-ラナ" = "あ、もう少し調整したい……。"
"10057070-103-エリナ" = "そんな時間ないって！ほら、急いで～！"
"10057070-104-アンナ" = "逃げろー！！！"
"10057070-116" = "[log]戦車レース予選まで[/log]"
"10057070-118" = "[log]D-2[/log]"
"10057070-124-チェリノ" = "うむ！今日も素晴らしい朝だな！"
"10057070-125-マリナ" = "は、はい！非常に素晴らしい朝です！"
"10057070-126-チェリノ" = "ん？どうした、マリナ委員長？顔色が良くないな。"
"10057070-130-マリナ" = "何でもありません！事務局員はこのくらいのことでへこたれませんので！"
"10057070-131-マリナ" = "（昨日侵入者にコテンパンにやられた挙句、そのまま取り逃がしたとは言えない！！）"
"10057070-132-チェリノ" = "マリナ委員長。事務局員といえども、疲れない日などないだろう。"
"10057070-133-チェリノ" = "トモエ秘書室長がゲヘナカップの準備で忙しい中、#nマリナ委員長がその分頑張ってることは知っているぞ。"
"10057070-134-チェリノ" = "昨夜も巡回があったと聞いている。ご苦労だったな。"
"10057070-135-マリナ" = "ちぇ、チェリノ会長……！"
"10057070-138-マリナ" = "（チェリノ会長、今日は機嫌が良さそうだ！）"
"10057070-139-マリナ" = "（このまま何もなかったということで通してしまおう！）"
"10057070-140-マリナ" = "（これまで散々迷惑をかけたのに、こんなにも慈悲深い賞賛をいただけるなんて……）"
"10057070-141-マリナ" = "（会長、このマリナは不変の忠誠を誓います……！）"
"10057070-142-チェリノ" = "そういえば。"
"10057070-146-マリナ" = "はい！"
"10057070-147-チェリノ" = "ここにあったおいらの等身大銅像は、どこにいったのだ？"
"10057070-152-マリナ" = "は、はいぃ！？ど、銅像ですか！？"
"10057070-153-チェリノ" = "そうだ。昨日の夕方までは威厳ある銅像が立っていたのだが。"
"10057070-164-チェリノ" = "……。"
"10057070-165-マリナ" = "……。"
"10057070-166-チェリノ" = "これは……フィギュア、か……？"
"10057070-168" = "183号研究室"
"10057070-172-ラナ" = "銅線の加工、終わった。"
"10057070-173-エリナ" = "すご～い！こんな良い銅、事務局にあったんだ！"
"10057070-174-エリナ" = "これだけあったら、スターターモーターも新しく作れるね！"
"10057070-176-アンナ" = "どこから持ってきたの？"
"10057070-181-ラナ" = "あえて言うなら、会長からの慈愛に満ちたプレゼント。"
"10057070-185-マリナ" = "（あの不審者、廊下の壁を削ったのか！？）"
"10057070-189-チェリノ" = "マリナ委員長。これは何だ？廊下のペンキが剥がれてしまっているではないか。"
"10057070-190-マリナ" = "そ、それはですね！"
"10057070-194-マリナ" = "チェリノ会長のオーラをさらに引き立てるために、#nより適したペンキを塗る準備をしていたんです！"
"10057070-195-チェリノ" = "そうなのか？そんな報告はなかったが。"
"10057070-196-マリナ" = "は、はは！！サプライズですので！"
"10057070-197-チェリノ" = "広場の銅像がフィギュアになったのもサプライズか？"
"10057070-198-マリナ" = "そのとおりです！最近は生徒会長を象徴するミニグッズが流行しているようなので！"
"10057070-199-チェリノ" = "……。"
"10057070-200-マリナ" = "あ、あはは！！"
"10057070-206-エリナ" = "はい！アンナが欲しがってたチタン！まだ熱いから気を付けてね！"
"10057070-207-アンナ" = "うわっ！チタンなんて、どこで手に入れたの？持ってくるとこ見てないけど。"
"10057070-208-エリナ" = "ふっふっふ……化学者を見くびってもらっちゃあ困るな～！"
"10057070-209-エリナ" = "これはあの時削り取った白いペンキから作ったんだよ。"
"10057070-210-アンナ" = "あれで！？ペンキがどうやってチタンになるの？"
"10057070-211-エリナ" = "クロール法を使ったの！#n白いペンキの主成分は二酸化チタンでしょ？#n四塩化チタンを生成して、そこから金属チタンを分離して完成。"
"10057070-212-エリナ" = "ポンコツ設備でこれだけ取り出すのは大変だったんだから、大切に使ってよ！"
"10057070-213" = "[s] \"友達と仲良くなったね。\""
"10057070-219-アンナ&エリナ" = "友達ではありません！！"
"10057070-220-アンナ" = "単なる協力関係です。研究のために仕方なくですから！"
"10057070-221-エリナ" = "こっちだってそう！優勝して解散したら、永遠にサヨナラ～！"
"10057070-227-アンナ&エリナ" = "ふんっ！"
"10057070-228" = "[s] \"ああっ……仲良かったのに……。\""
"10057070-230-アンナ&エリナ" = "ふんっ！！"
"10057070-233-チェリノ" = "……どうやら、マリナが一晩の間にあれこれやってくれたようだな。"
"10057070-234-マリナ" = "ち、チェリノ会長の気分転換になればと思ってのことです！"
"10057070-235-チェリノ" = "そうか……。"
"10057070-236-チェリノ" = "誰かが侵入して[ruby=サボタージュ]破壊活動[/ruby]でもしたのかと心配したが――"
"10057070-237-チェリノ" = "マリナが鉄壁となって守ってくれていたおかげで、何もなくて良かった。"
"10057070-238-チェリノ" = "たとえあったとしても、髭の権威に逆らうやつらを放っておくはずがないからな。"
"10057070-243-マリナ" = "（昨夜のこと、バレたら終わりだ！）"
"10057070-244-チェリノ" = "まあ、休みながらのんびりやってくれ。"
"10057070-245-チェリノ" = "ときにマリナ、今日はずいぶんと爽やかな朝だと思わないか？"
"10057070-246-マリナ" = "おっしゃるとおりです！会長の傑出したご指導により、#nレッドウィンターの気候も徐々に改善されているようです。"
"10057070-247-チェリノ" = "そうだな。今日は空気も清々しい。"
"10057070-248-マリナ" = "会長の卓越したご指導で空気まで改善されたのでしょう！"
"10057070-252-チェリノ" = "おいらが言いたいのは――"
"10057070-253-チェリノ" = "この清々しくて爽やかな空気が……#nどうして今、この執務室に流れているかということだ。"
"10057070-254-マリナ" = "はい！？"
"10057070-260-チェリノ" = "窓ガラスは一体どこにいったのだ！！！"
"10057070-271" = "183号研究室"
"10057070-274-アンナ" = "よし！照準器の加工も終わり！"
"10057070-275-アンナ" = "ホウケイ酸ガラスなんて、会長の執務室は窓ガラスも良いものを使ってるのね！"
"10057070-276-アンナ" = "窓ガラスを持ってくるなんて、正直驚いたわ。さす――"
"10057070-283-エリナ" = "すぅ……すぅ……。"
"10057070-284-アンナ" = "ストーブつけると、すぐ熟睡しちゃうんだから……。"
"10057070-285-アンナ" = "徹夜で大騒ぎしたあと、今の今まで作業したんだから……そりゃ疲れるか。"
"10057070-289-アンナ" = "もう、80％ぐらいは進んだかな。"
"10057070-293-アンナ" = "……完成はもう目の前。"
"10057070-294-アンナ" = "さすが、シャーレの先生……。"
"10057070-295-アンナ" = "……。"
"10057070-297-アンナ" = "……本当に「奇跡」を起こしちゃうなんて思わなかった。"
