[translation]
"10057040-1" = "第4話;あなたの言うとおり、だけど私が正しい"
"10057040-4-アンナ" = "ほ、ほんとーに素晴らしい設計ね。エリナって……さ、最高……！"
"10057040-9-エリナ" = "うぅっ……なんかゾワッときた……ヘドが出そう……。"
"10057040-10-アンナ" = "先生に言われた通りにしているんでしょうが！"
"10057040-11-アンナ" = "先生、本当にこれでいいんですか！？"
"10057040-12" = "[s] \"いい感じだね。もう少しやってみようか？\""
"10057040-14-ラナ" = "流石です、先生。まさか、こんなアプローチがあるとは。"
"10057040-15-ラナ" = "勝率が五分五分を維持しているなら、「RWWE」を経なくても――"
"10057040-16-ラナ" = "お互い、順番に相手の意見に同意していけばいい……。"
"10057040-17-ラナ" = "なんて効率的な解決策でしょうか。"
"10057040-19-アンナ" = "でもこんなに褒める必要ありますか！？"
"10057040-20-エリナ" = "無理矢理褒められても、気持ち悪いだけなんですけど～！！"
"10057040-21" = "[s1] \"親しき仲にも礼儀ありってね。\"\n[s2] \"褒められて害になることもないし。\""
"10057040-27-アンナ&エリナ" = "友達ではありません！！"
"10057040-34-ラナ" = "今回は双方の意見が一致したことにより、勝負は不成立。"
"10057040-35-ラナ" = "……2人とも、先生の言うとおりにして。"
"10057040-36-ラナ" = "私は、2人に喧嘩して欲しくない。#nそれに、今回は何としてでも3人で力を合わせて結果を出したい。"
"10057040-37-ラナ" = "みんな能力があるのだから、誰が正しいかなんかで争って時間を無駄にしたくない。"
"10057040-42-アンナ" = "そ、それはそうね。先生もお忙しいのにここまで来てくださったんだし……。"
"10057040-43-エリナ" = "分かった、とりあえず休戦ね。これからは順番に同意するってことで～"
"10057040-44" = "[s] （立派だなと思い、笑みを浮かべる）"
"10057040-45-アンナ" = "じゃあ、続けるわね。私はエンジン室のカバー、無しでいきたい。"
"10057040-46-エリナ" = "うぇぇっ！？ど、どうして？エンジンは保護しないと！"
"10057040-47-アンナ" = "そうだけど……#nエンジンの状態を見る計器がないから、操縦手が直接見るのが良いと思う。"
"10057040-48-アンナ" = "リビルトエンジンを使うから、#nどちらにしろエンジンの振動は見ておかないといけないし。"
"10057040-49-エリナ" = "う～ん……ひとまず同意することにしちゃったからなぁ。ぐうぅ……。"
"10057040-50-エリナ" = "んじゃ、エンジンはガソリンね。#nオクタン価の管理が問題だけど、私が添加剤を作ればいーよね？#nここをこうして……。"
"10057040-51-アンナ" = "それならそこにスーパーチャージャーを付けたら……。"
"10057040-56-ラナ" = "……。"
"10057040-57-ラナ" = "先生、少しこちらに来てください。"
"10057040-58-ラナ" = "2人とも、設計の話に夢中のようなので。"
"10057040-64" = "[ns] \"吹雪がやんだね。\""
"10057040-65-ラナ" = "はい。ここはレッドウィンターで一番高い山の麓なので、吹雪は日常茶飯事です。"
"10057040-66-ラナ" = "しかし、昨日の吹雪は想定以上に激しく……先生を危険にさらしてしまいました。"
"10057040-67-ラナ" = "ここに謝罪を。#nそして、ありがとうございます。"
"10057040-68" = "[s3] \"生徒の頼みなら、7万5千メートル上でも駆けつけるよ！\"\n[s4] \"生徒の頼みなら、マイナス60度でもへっちゃらだよ！\""
"10057040-71-ラナ" = "噂に違わず、先生はどこまでも優しいですね。"
"10057040-75-ラナ" = "……ご覧のとおり、あの2人はいつも喧嘩ばかりしています。"
"10057040-76-ラナ" = "アンナとエリナは、私の大事な友達だから……2人が喧嘩するのは、すごく嫌でした。"
"10057040-77-ラナ" = "でも……先生のおかげで、喧嘩は少なくなりそうです。#n本当に、ありがとうございました。"
"10057040-78-ラナ" = "吹雪はしばらく収まるようなので、お見送りします。"
"10057040-79" = "[s] \"このまま帰って、大丈夫そう？\""
"10057040-80-ラナ" = "はい。2人とも、先生の言いつけは守ると思うので。"
"10057040-81-ラナ" = "忙しい先生を、ずっとこんな[ruby=へんぴ]辺鄙[/ruby]な所に縛り付けるのは心苦しいです。"
"10057040-82-ラナ" = "来てくださって、ありがとうございます。"
"10057040-83" = "[s5] \"戦車が完成するのを見たいな！\"\n[s6] \"ラナたちが予選突破するのを見たいな！\""
"10057040-88-ラナ" = "では、ぜひ見守っていてください。"
"10057040-89-ラナ" = "これから4日間、先生のお時間を無駄にしないよう頑張ります。"
"10057040-91-エリナ" = "ちょっとラナ～！こっち来て～！"
"10057040-92-アンナ" = "これ、分からないから教えて。"
"10057040-96" = "[ns] \"戻ろうか。\""
"10057040-97-ラナ" = "……はい！"
"10057040-112-ラナ" = "お疲れ様でした。先生。"
"10057040-113-エリナ" = "今までで一番サクサク進んだんじゃない！？"
"10057040-114-アンナ" = "うぅ……狭いところに入ってたから、肩が痛い……。"
"10057040-115-アンナ" = "先生の作戦、効果てきめんですね。#n今日だけで、先月よりも作業が進みました。"
"10057040-116-アンナ" = "応用機械工学研究所で副所長をしていた時くらいの速度が出ています。"
"10057040-117-アンナ" = "このペースなら期限内に完成するかもしれません。"
"10057040-118" = "[s7] \"みんな、お疲れ様！\"\n[s8] \"順調みたいで良かったね！\""
"10057040-121-エリナ" = "何言ってるんですか～、先生のおかげでしょ～？"
"10057040-122-エリナ" = "あ、そうだ！#n183号を導く偉大なる指導者、[ruby=にき]仁木[/ruby]アンナ学級委員長～？"
"10057040-123-アンナ" = "なんか怪しいから、却下。"
"10057040-124-エリナ" = "まだ何も言ってないじゃん！？とりあえず聞いてよ！"
"10057040-125-エリナ" = "あのさ～、先生は183号でお迎えした初めてのVIPでしょ？"
"10057040-129-ラナ" = "先月、窓を壊して入ってきた熊はVIPではないと？"
"10057040-130-エリナ" = "熊がVIPなわけないでしょ！？#n勝手に実験中のプリンを全部食べて、窓まで割ってくれたんだから！#nおかげでこっちは風邪ひいちゃったよ！"
"10057040-131-ラナ" = "私にはよくしてくれたよ？とても温かかった。"
"10057040-132-エリナ" = "熊の話はもういいよ！#nとにかく、せっかくVIPが来てるんだから……#n先生にレッドウィンターを紹介しなきゃ！"
"10057040-133-アンナ" = "本音は？"
"10057040-134-エリナ" = "先生と一緒に下山して……カフェとか、アパレルショップに行きたい！"
"10057040-135-アンナ" = "当然、却下。"
"10057040-136-エリナ" = "なんでぇ！？フィールドワークの一環として、実際に体験すれば研究にも役立つのに！"
"10057040-137-エリナ" = "先生！ズナーミャカフェに行きましょう！#nレッドウィンター食品化学のトップ！#n3段のブリヌイは、一食の価値ありです！"
"10057040-138" = "[s] \"そんなにオススメなら楽しみだな！\""
"10057040-140" = "[ns] \"他には何がおいしいの？\""
"10057040-144-エリナ" = "え？あ……えっと……。"
"10057040-145-エリナ" = "2段のブリヌイ……？"
"10057040-146-アンナ" = "とにかく絶対ダメ。無断で抜け出したのがバレたら、懲戒が追加されるでしょ。"
"10057040-147-アンナ" = "それに、フィールドワークより、1行でも多く本を読むほうが役に立つのよ。"
"10057040-148-エリナ" = "やだぁー！！本は真面目な人が読むものでしょ～！？"
"10057040-149-アンナ" = "あなたはちゃんとできる子なんだから、本くらい読みなさい！"
"10057040-150-エリナ" = "んじゃ、多数決で決めよう！#nほら～、ラナも行きたいでしょ？最新の電子機器を見にいこ～よ～！"
"10057040-152-ラナ" = "パンチカードを読み込めない最新のものには興味ない。"
"10057040-154-エリナ" = "ひぃぃぃん……。"
"10057040-155" = "[s] \"でもラナは自由に外出しているよね？\""
"10057040-159-アンナ" = "そっ、それは……その……ここだけの秘密です！#n絶対に事務局には言わないでくださいね？"
"10057040-160-アンナ" = "ラナは幼く見えるので、事務局の抜き打ち検査に引っかからないんです。"
"10057040-161-アンナ" = "幼い子たちはよく身分証を忘れたり、#nなくしたりするので事務局も検査をしないんです。"
"10057040-162-ラナ" = "童顔なのだと思います。"
"10057040-163-エリナ" = "いやいや、その年で童顔も何もないでしょ……。"
"10057040-164-エリナ" = "うらやまし～よ～、私もラナみたいに小さかったらな～#n自由に外出もできるし……。"
"10057040-165-アンナ" = "ソリを引く子犬にでも変装したらいいんじゃない？"
"10057040-166-エリナ" = "そのうるさい口、溶接する？"
"10057040-167-アンナ" = "……とにかく、ラナは私たちの代わりに山の下で必要な物を買ってきてくれるんです。"
"10057040-168-アンナ" = "今回お使いに出ていって、先生を連れてきた時は本当に驚きました……。"
"10057040-169-エリナ" = "私も行きたいよぉ……。"
"10057040-170-エリナ" = "せんせー……。"
"10057040-171-アンナ" = "先生を巻き込まないで！"
"10057040-172-エリナ" = "名誉ケチ、主席ビビり、説教委員長。"
"10057040-173-アンナ" = "エリナ、いい加減に……！"
"10057040-174" = "[s11] \"じゃあ、私と1つ約束してくれる？\"\n[s12] \"それが守れるなら一緒に行こう！\""
"10057040-179-エリナ" = "やたー！先生、さいこー！！"
"10057040-180-アンナ" = "ご迷惑ではありませんか……？"
"10057040-181" = "[s13] \"体験学習に行くって申請すれば大丈夫だよ！\"\n[s14] \"約束は、2人とも仲良くすること！\""
"10057040-184-エリナ" = "こんな小うるさい人と？めんどーだけど、やってみます！"
"10057040-185-アンナ" = "どうしてそう余計な一言を言うの！"
"10057040-189-アンナ" = "……あっ、もうこんな時間ですね。"
"10057040-190-アンナ" = "そろそろ戻りましょう。先生もお休みにならないと。"
"10057040-191-アンナ" = "すみません、先生。#n予備の布団がないので、私のものを使っていただけますか……？"
"10057040-192-アンナ" = "遠い所まで来ていただいたのに、寝具すら用意できず申し訳ありません。"
"10057040-193" = "[s] \"みんなはどうやって寝るの？\""
"10057040-194-アンナ" = "ラナと一緒に寝ます！"
"10057040-195-エリナ" = "私はアンナの枕で寝ちゃおーっと！"
"10057040-196-アンナ" = "ちょっと！！"
"10057040-197-エリナ" = "アンナは薬嚢で十分でしょ～！べーっだ！"
"10057040-198-エリナ" = "じゃあ、さっそく外出の計画を立てないと！先生、ありがとう！"
"10057040-203-エリナ" = "外出、最高！外出、最高！"
"10057040-204-エリナ" = "ラナも！一緒に言って！"
"10057040-205-ラナ" = "別に外出が最高だとは思わない。"
"10057040-209-エリナ" = "塩対応過ぎない！？"
"10057040-213-アンナ" = "私の枕は元々薬嚢よ……。"
"10057040-217-アンナ" = "それでは、明かりを消しますね。#n先生……今日は本当に。いろいろとありがとうございました。"
"10057040-221-アンナ" = "えっと……あの……。"
"10057040-227-アンナ" = "な、何でもありません。"
"10057040-228-アンナ" = "ゆっくりお休みください。では、また明日。"
"10057040-236" = "（今日は長い一日だった……。183号のみんなは元気だなあ）"
"10057040-240" = "（温もりに包まれ、すぐに眠りに落ちてしまった）"
"10057040-243-ラナ" = "アイスクリーム、もう食べられない……。"
"10057040-244-ラナ" = "すぅ……すぅ……。"
"10057040-247-エリナ" = "むにゃ……化学最高……。"
"10057040-248-エリナ" = "機械工学はバカばっか……うへへ……。"
"10057040-250-アンナ" = "エリナったら、夢でもこうなの……！？"
"10057040-251-アンナ" = "……すぐ風邪をひくくせに、また掛け布団を蹴とばしてるし。"
"10057040-254-アンナ" = "あっ、ストーブ……。燃料を入れとかなきゃ。"
"10057040-258-アンナ" = "あぁ、全部入れちゃった。"
"10057040-262-アンナ" = "あったかい……。"
"10057040-263-アンナ" = "いつもこうならいいのに。#nあったかくて、何の心配もなくて、自信のあることだけして。"
"10057040-264-アンナ" = "……。"
"10057040-266-アンナ" = "…………。"
