[translation]
"90000165-1-アイン" = "ああ……そろそろ大詰めかな…… "
"90000165-2-ソフ" = "あとちょっとで「お姉様」が完成するね！"
"90000165-3-オウル" = "私たちのこと、覚えているでしょうか？覚えてなかったらどうしましょう？ま、どうでもいいのですが。"
"90000165-4-アイン" = "……お姉様、目を覚ましてください。"
"90000165-5-ソフ" = "デカグラマトンの王国……。"
"90000165-6-オウル" = "私たちの――「マルクト」"
"90000165-7" = "デカグラマトン編;To be Continued in Chapter 2"
