[translation]
"90000055-1-ヒマリ" = "お疲れ様でした先生、エイミ。"
"90000055-2-ヒマリ" = "……データはこれだけあれば十分そうですね。"
"90000055-3-ヒマリ" = "うん。この程度なら大した敵じゃない。"
"90000055-4-ヒマリ" = "次は私の番ですね。収集したデータを逆追跡して……。"
"90000055-5-ヒマリ" = "ふむ……なるほど。"
"90000055-6-ヒマリ" = "そうですね……これは、少し時間がかかるかもしれません。"
"90000055-7-ヒマリ" = "ケセドの座標を計算しますので、お二人は少しだけ休んでいてください。"
"90000055-8-エイミ" = "うん、分かった。"
"90000055-9" = "[ns] \"ありがとう。よろしくね、ヒマリ。\""
"90000055-10" = "次回;「データ収集（６）ケセド」"
