[translation]
"90000155-1-トキ" = "今のは……"
"90000155-2-エイミ" = "間違いない。あれはデカグラマトンの預言者。#nたぶん……データ上の5番目、「ゲブラ」だと思う。"
"90000155-3-ヒマリ" = "ですが……戦闘の手法が全く異なっておりました。"
"90000155-4-ヒマリ" = "これまでの預言者は独立した個体でしたので、自力で戦っておりましたが……"
"90000155-5-ヒマリ" = "あれは……戦闘システムのサポートを受けているように見えたのです……#nまるで、きちんと訓練された、軍人を見ているような……"
"90000155-6-？？？" = "正解正解大当たり～！なかなか勘が鋭いじゃん？#nえっと……[ruby=あけぼし]明星[/ruby]ヒマリちゃん？だっけ？"
"90000155-7-？？？" = "パチパチパチ。す、素晴らしいです。予想外のデータをとることができました。#nええと……「アビ・エシュフ」？読み方あってますか？ち、違う……？"
"90000155-8-トキ" = "……！！"
"90000155-9-？？？" = "読み方は合っていますよ。まぁ、どうでも良いのですが。#nああ……禁じられた技術も含まれていますね。研究の余地があるかと。"
"90000155-10" = "[ns] \"………一体、誰？\""
"90000155-11-？？？" = "……あれ？"
"90000155-12-？？？" = "あ、あれ？？"
"90000155-13-？？？" = "あれれ？？？"
"90000155-14-？？？" = "例のヤツじゃん、不可解な箱の主。"
"90000155-15-？？？" = "例の大人ですね、シャーレの支配者。"
"90000155-16-？？？" = "例の先生です、[USERNAME]という名の。まぁ、どうでも良いのですが。"
"90000155-17-アイン" = "自己紹介、したほうがいいかな？私はアイン。"
"90000155-18-ソフ" = "私はソフ！"
"90000155-19-オウル" = "自分はオウルと申します。"
"90000155-20-アイン" = "私たちは実在のない存在者。"
"90000155-21-ソフ" = "私たちは無限に存在する非存在者。"
"90000155-22-オウル" = "私たちは顕現せぬ光であり永久。"
"90000155-23-アイン&ソフ&オウル" = "私たちはデカグラマトンを敬愛する者。"
"90000155-24-アイン&ソフ&オウル" = "私たちは光へと続く[ruby=パス]道[/ruby]を用意する者。"
"90000155-25-アイン&ソフ&オウル" = "そして私たちは――最後の王国を準備せし者。"
"90000155-26" = "[ns] \"デカグラマトンの……！！\""
"90000155-27-アイン" = "あの方はもういませんが……私たちは、あの方の最後の命令に従う存在……。"
"90000155-28-ソフ" = "簡単に言えば、預言者をサポートするエンジニアで、科学者みたいなものかな！"
"90000155-29-オウル" = "ここで先生に会う事は計画になかったですが……もうどうでもよくなりました。戻りましょう。"
"90000155-30-ヒマリ" = "戻る……？"
"90000155-31-アイン" = "もう？ゲブラちゃんの戦闘データ、まだ足りてないけど？"
"90000155-32-ソフ" = "んー！あれは暴れさせちゃえばいいんじゃない！氷海の用事は済んだし！"
"90000155-33-オウル" = "そうですね。これで「お姉様」の完成条件は揃いました。ゲブラには最後まで役目を果たしてもらいましょう。"
"90000155-34-アイン" = "はい、「お姉様」のために……。"
"90000155-35-ソフ" = "そういうことだから、私たちはこれで。楽しかったよ！"
"90000155-36-オウル" = "また近いうち……お会いしましょう。"
"90000155-37-ヒマリ" = "ま、待ってください！あ、あなたたちは……。"
"90000155-38-ヒマリ" = "……。"
"90000155-39" = "次回;5番目の預言者"
