[translation]
"90000090-1" = "第10話;「データ収集（８）ケテル」"
"90000090-2" = "特異現象捜査部・部室"
"90000090-3-ヒマリ" = "お待たせいたしました。#nそれでは、新しい任務の会議を始めましょう。"
"90000090-4-エイミ" = "わぁーい！"
"90000090-5" = "[s1] \"わぁい！\"\n[s2] （拍手する）"
"90000090-6-ヒマリ" = "……なんですか、この雰囲気は。"
"90000090-7-ヒマリ" = "……なんですか、この雰囲気は。"
"90000090-8-ヒマリ" = "ケテルの分析が終わりましたので、#n次の潜入ルートを話すだけなのですが……。"
"90000090-9-エイミ" = "うん。#nでもそれはヒマリ部長だからできることでしょ、なので拍手。"
"90000090-10" = "[s] \"いつもありがとう、ヒマリ。\""
"90000090-11-ヒマリ" = "……なるほど。"
"90000090-12-ヒマリ" = "私の天賦の才は隠しきれなかったということなのですね。#nこの美貌に負けず劣らず誰もが一目で納得するような状況であった――と。"
"90000090-13-ヒマリ" = "ふふ……エイミもついに私の輝かしい才能に気づいてしまいましたか。#nうふふ。"
"90000090-14-エイミ" = "……そうだね、うん。#n気づいてるよ、色々。"
"90000090-15-ヒマリ" = "うふふ、そうでしたか……。"
"90000090-16" = "[s] （エイミは優しいなぁ……）"
"90000090-17-ヒマリ" = "まず、ケテルが出没する座標から、おおよその守っているエリアを絞ってみました。"
"90000090-18-ヒマリ" = "廃墟水没地区の中でもかなり外郭に位置しており、研究室や実験室などがあるエリア――"
"90000090-19-ヒマリ" = "便宜上、「研究地区」と呼びましょう。"
"90000090-20-エイミ" = "「研究地区」……そこが私たちの目的地なんだね。"
"90000090-21-ヒマリ" = "ええ。正確にはデカグラマトンの信号を捉えた地点が最終目標ですが……"
"90000090-22-ヒマリ" = "そこに到達するためには、預言者ケテルを引き離さなければなりません。"
"90000090-23-ヒマリ" = "さらに、上手くケテルを撒いたとしても、エリアの捜索を進めなければならないので……"
"90000090-24-ヒマリ" = "ケテルに追われての遂行は厳しいでしょう。"
"90000090-25-ヒマリ" = "ですから、ここでケテルを無力化することが必須となります。"
"90000090-26-エイミ" = "結局、ケテルを倒すってことだよね？"
"90000090-27-ヒマリ" = "ええ。これから始めるのは、そのためのデータ収集です！"
"90000090-28-ヒマリ" = "今までやっていたことが「かくれんぼ」ならば、#nこれから行うのは「鬼ごっこ」です！"
"90000090-29-エイミ" = "ケテルが「鬼」じゃないんだ。"
"90000090-30" = "[s] \"今度は私たちが鬼？\""
"90000090-31-ヒマリ" = "ええ、そういうことです。#nそれでは……ケテル攻略のための、データ収集を始めましょう！"
