[translation]
"90000045-1-エイミ" = "ビナーのデータ、集めてきたよ。"
"90000045-2-ヒマリ" = "はい、確認しました。確かにデカグラマトン3番目の預言者『ビナー』のデータですね。"
"90000045-3-ヒマリ" = "それでは分析に入ります、お疲れ様でした。"
"90000045-4" = "[s] \"ありがとう、よろしく。\""
"90000045-5-エイミ" = "部長のアルゴリズムのおかげで、スムーズだった。"
"90000045-6-ヒマリ" = "当然です。あ、分析完了しました。モニターに出力しますね。"
"90000045-7-エイミ" = "……これで全部？"
"90000045-8-ヒマリ" = "今回確保したデータからは、これしか分かりませんでした。"
"90000045-9-ヒマリ" = "全貌には未だ遠いですが、まずは一歩目を踏み出せたというところですね。"
"90000045-10-エイミ" = "千里の道も一歩から、だね。"
"90000045-11-エイミ" = "はい。引き続きできる限りの情報を集めていきましょう。"
"90000045-12-ヒマリ" = "少し休んだら次ですね。"
"90000045-13-ヒマリ" = "次の目的地は……ミレニアム近郊の 「廃墟」です。"
"90000045-14" = "次回;「データ収集（５）廃墟」"
