[translation]
"90000140-1" = "第15話;氷河（１）"
"90000140-2" = "[ns] \"ついた……。\""
"90000140-3-トキ" = "はい、到着しました。"
"90000140-4-トキ" = "気温は低いですが、幸い風が吹いていないので稼働に支障はありません。#nまだ耐えられる寒さです。"
"90000140-5-トキ" = "何を言っているんですか。#n十分寒いですよ？海が凍るほどなんですよ？"
"90000140-6" = "[s] \"防寒対策バッチリだね、ヒマリ。\""
"90000140-7-ヒマリ" = "ええ。私のような清楚系病弱美少女にとって、寒さは最大の敵。#n[ruby=アーチ・エネミー]そう、宿敵なので[/ruby]すから。"
"90000140-8-ヒマリ" = "改造した防寒スーツを2枚着ていますので、万全です。#nあまり機敏には動けなくなってしまいましたが、寒いよりはマシ……"
"90000140-9-トキ" = "やっほ～"
"90000140-10-エイミ" = "いつもよりちょっと身体が軽いかも。涼しいからかな。"
"90000140-11-エイミ" = "コンディションは絶好調だよ。"
"90000140-12-エイミ" = "エイミ……今さらではありますが、何かおかしいと感じませんか？"
"90000140-13-エイミ" = "うん？何の話？"
"90000140-14-エイミ" = "ああ、この格好？"
"90000140-15-エイミ" = "先生が選んでくれたの。いいでしょ？"
"90000140-16-ヒマリ" = "……先生……？"
"90000140-17-トキ" = "先生？"
"90000140-18" = "[s1] \"説明すると長くなるんだけど……。\"\n[s2] \"えっと……そんなところ……かな。\""
"90000140-19-トキ" = "……そうですか。#nまぁ、私は構いません。"
"90000140-20-トキ" = "仲間の幸せが私の幸せです。結果よければすべて良しと教わりました。"
"90000140-21-ヒマリ" = "……そうですか。"
"90000140-22-ヒマリ" = "……はあ、まぁ今さらですので仕方ありません。#n任務に集中しましょう。"
"90000140-23-ヒマリ" = "改めて。私たちはデカグラマトンの信号を追跡し、ここに来ました。#n任務はシンプルです。ここを隈なく調べ、異常を確かめる。"
"90000140-24-ヒマリ" = "2人がこの周辺を捜索する間、私と先生は安全な場所を見つけベースキャンプを確保します。よろしいでしょうか？"
"90000140-25-エイミ" = "了解。"
"90000140-26-トキ" = "イエス、マム。"
