[translation]
"1601502-1" = "シュガーハイ"
"1601502-2" = "（時間を工面し、約束の場所へと向かった）"
"1601502-3" = "（向こうからアイリが走ってくるのが見える）"
"1601502-4-アイリ" = "せんせ～！！！"
"1601502-5-アイリ" = "……じゃーん！！"
"1601502-6" = "[s1] \"じゃーん！！！\"\n[s2] \"今日はテンション高いね！？\""
"1601502-7-アイリ" = "えへへ……たしかに、いつもよりテンション高めかもしれません。"
"1601502-8-アイリ" = "さっきまで練習してて、良い感じの演奏ができたので……！"
"1601502-9-アイリ" = "その時にふと、先生にオススメしたいお店を思い出しまして。"
"1601502-10-アイリ" = "もう居ても立っても居られなくて、先生に連絡しちゃいました！"
"1601502-11-アイリ" = "早く先生に、あのお店のスイーツを味わってほしくて……！"
"1601502-12" = "[s3] （すごい勢いを感じる……）\n[s4] （アイリがそこまで言うお店……気になる）"
"1601502-13-アイリ" = "さあ、急ぎましょう！#n早く行かないと、お店閉まっちゃうかもですし！"
"1601502-14-アイリ" = "こっちです！"
"1601502-15-アイリ" = "……結構混んでますね。"
"1601502-16-アイリ" = "列も長いですし……ちょっと待つかもしれません。"
"1601502-17-アイリ" = "10分くらいとお伝えしていたのに、すみません……。"
"1601502-18-アイリ" = "もう少し早く来られれば……。"
"1601502-19" = "[s5] \"大丈夫だよ。\"\n[s6] \"明日もあるし、急がなくても良いんじゃないかな。\""
"1601502-20-アイリ" = "……え？"
"1601502-21-アイリ" = "また明日、ですか？"
"1601502-22-アイリ" = "うーん……でも、それは……。"
"1601502-23" = "[s] \"……アイリ？\""
"1601502-24-アイリ" = "……いえ！"
"1601502-25-アイリ" = "……今日じゃないとダメです！"
"1601502-26-アイリ" = "とにかく並びましょう！！"
"1601502-27-アイリ" = "そうでないと……！"
"1601502-28-アイリ" = "……。"
"1601502-29-アイリ" = "……またやってしまいました。"
"1601502-30" = "[s7] \"……アイリ？\"\n[s8] \"「また」っていうのは……？\""
"1601502-31-アイリ" = "えっと、その……うぅ……。"
"1601502-32-アイリ" = "ごめんなさい。#n先生のご都合もあるのに、無理に並び続けようだなんて……。"
"1601502-33-アイリ" = "先生には、他のご予定もあるはずなのに……"
"1601502-34-アイリ" = "たまに、こうやってムキになっちゃうんです。#nみんなにも言われてたのに……うう……。"
"1601502-35-アイリ" = "こんな情けない姿を見せてしまって……すみません……。"
"1601502-36-アイリ" = "仰る通り、明日にしましょうか！#nもしくは仕切り直して、別の日でも！"
"1601502-37-アイリ" = "……え？"
"1601502-38-アイリ" = "そんな、他の予定が無いとしても……。"
"1601502-39-アイリ" = "もしかしたら何時間もかかってしまうかも……。"
"1601502-40" = "[s9] \"アイリと一緒なら何時間でも。\"\n[s10] \"心配しないで大丈夫だよ。\""
"1601502-41-アイリ" = "先生……。"
"1601502-42-アイリ" = "……えへへ。"
"1601502-43-アイリ" = "で、ですがやっぱり、この列を見ると……。"
"1601502-44-アイリ" = "うぅ、すみません……押し問答みたいになってしまい……。"
"1601502-45-アイリ" = "先生は、どうしてそこまで……？"
"1601502-46" = "[s11] \"待っている間に、私も聞きたいことができたから。\"\n[s12] \"その「友達によく言われる」って話、詳しく聞かせてくれる？\""
"1601502-47-アイリ" = "えっ。"
"1601502-48-アイリ" = "……ふふっ。"
"1601502-49-アイリ" = "あははっ……！"
"1601502-50-アイリ" = "そんな、大した話じゃないのに……。"
"1601502-51-アイリ" = "ですが、先生が聞きたいというのなら……はい。"
"1601502-52-アイリ" = "私、こだわりが強いってよく言われがちで……。"
"1601502-53-アイリ" = "具体的には、例えば……。"
"1601502-54-アイリ" = "うーん……いざ話そうとすると難しいですね……。"
"1601502-55-アイリ" = "そうですね、ふと思い出した話で行きますと――"
"1601502-56-アイリ" = "……これ、1、2時間くらいかかりますが良いですか？"
