[translation]
"1601505-1" = "シュガークラッシュ"
"1601505-2" = "（アイリがいつも練習していた場所へと向かった）"
"1601505-3-？？？" = "……先生？"
"1601505-4-アイリ" = "こ、こんにちは！#nどうしてこちらに？"
"1601505-5-アイリ" = "今日は何の予定も、無かったはずですが……？"
"1601505-6-アイリ" = "……え？"
"1601505-7-アイリ" = "わ、私……ですか？"
"1601505-8-アイリ" = "た、確かにそうですね……。"
"1601505-9-アイリ" = "無意識でと言いますか、気づけばこの格好ですし……。"
"1601505-10-アイリ" = "そ、それより先生は何のご用事で……！？"
"1601505-11-アイリ" = "私を、探しに……？"
"1601505-12-アイリ" = "そ、それでも、どうしてここにいるって分かったんですか？"
"1601505-13-アイリ" = "な、何となく、ですか……。"
"1601505-14-アイリ" = "だとしても、よくここに来られましたね。"
"1601505-15-アイリ" = "何となくでも、感じたということですか？"
"1601505-16" = "[s1] \"そろそろレンタル期間も終わりだし。\"\n[s2] \"アイリなら、最後に来るだろうなって思って。\""
"1601505-17-アイリ" = "……。"
"1601505-18-アイリ" = "……そうですね。"
"1601505-19-アイリ" = "確かに……名残惜しいと、思っているのかもしれません。"
"1601505-20-アイリ" = "……そこまでお見通しだった、ということですね。"
"1601505-21-アイリ" = "……えへへ。"
"1601505-22-アイリ" = "半分正解ですが……半分は、不正解でしょうか。"
"1601505-23-アイリ" = "名残惜しいのもそうですが……実は……。"
"1601505-24-アイリ" = "……。"
"1601505-25-アイリ" = "ちょっと、辛いと言いますか……。"
"1601505-26" = "[ns3] \"バンドが終わったから？\"\n[ns4] \"元に戻っちゃう気がして……？\""
"1601505-27-アイリ" = "……はい。"
"1601505-28-アイリ" = "あはは……半分不正解なんて言いましたが、そちらも分かってましたか。"
"1601505-29-アイリ" = "別に消えてなくなるわけじゃないって、頭では分かってるんですが。"
"1601505-30-アイリ" = "それでも、気持ちは止められないみたいで。"
"1601505-31-アイリ" = "……居場所が一つ消えてしまう感じ、と言いますか。"
"1601505-32-アイリ" = "やっぱり無理ですよね。#n「放課後スイーツ部」が、そのままバンド活動もするなんて。"
"1601505-33-アイリ" = "続けるには労力が要りますし、全部を同時になんて無理ですし……。"
"1601505-34-アイリ" = "逆に、バンドだけをやりたい！というわけでもなくて……。"
"1601505-35-アイリ" = "……分かってるんです。"
"1601505-36-アイリ" = "私たちは「放課後スイーツ部」ですから。"
"1601505-37-アイリ" = "いつもみたいに集まっておしゃべりをして……スイーツを食べて……。"
"1601505-38-アイリ" = "そういう……いつもの私たちに戻るんです。#nそれが、大好きな私の居場所ですから。"
"1601505-39-アイリ" = "何か問題や、プレッシャーがあるわけでも無い日常……。"
"1601505-40-アイリ" = "も、もちろん嫌とかじゃないんですよ！？"
"1601505-41-アイリ" = "でも……。"
"1601505-42-アイリ" = "後悔でも、好き嫌いでもなくて……。"
"1601505-43-アイリ" = "過ぎ去ると分かっていることが……ただ、ちょっと辛くって。"
"1601505-44" = "[s5] \"確かに、バンドを続けるわけじゃないなら……。\"\n[s6] \"その場にあったものは、一時的にでも無くなっちゃうかもね。\""
"1601505-45-アイリ" = "……はい。"
"1601505-46-アイリ" = "そう、ですよね……。"
"1601505-47" = "[s] \"……それでも。\""
"1601505-48-アイリ" = "……？"
"1601505-49-アイリ" = "それ、でも……？"
"1601505-50-アイリ" = "……全部が無くなるわけじゃない？"
"1601505-51-アイリ" = "それって……。"
"1601505-52-アイリ" = "でも私たちは、放課後スイーツ部で……。"
"1601505-53" = "[s7] \"それに縛られることは無いよ。\"\n[s8] \"今回バンドをやったように、近い将来また何かあるかもしれない。\""
"1601505-54-アイリ" = "………！！"
"1601505-55-アイリ" = "先生……。"
"1601505-56-アイリ" = "ありがとうございます。"
"1601505-57-アイリ" = "そうですね……確かに、終わると分かっていても。"
"1601505-58-アイリ" = "それは、次が無いという意味ではないですよね……。"
"1601505-59-アイリ" = "……ふふっ。"
"1601505-60-アイリ" = "先生が、どこまで本気なのかは分かりませんが……。"
"1601505-61-アイリ" = "それでもやっぱり、落ち着くんです。先生の傍は。"
"1601505-62-アイリ" = "……えへへ。"
"1601505-63-アイリ" = "いずれにせよ……バンド活動は一旦終わりです。#nちゃんと、最後を見届けないと！"
"1601505-64-アイリ" = "……先生。"
"1601505-65-アイリ" = "……次は何をしましょうか？"
