[translation]
"1012706-1" = "夢の終わりから"
"1012706-2" = "ワイルドハント・キャンパス"
"1012706-3" = "（今日も手続きの仕事を終え、建物の外に出た）"
"1012706-4" = "[ns] \"仕事って、どうして急に増えるんだろう……。\""
"1012706-5" = "（一つ片付けると、次は二つ生えてくる……）"
"1012706-6" = "（ひとまず、ワイルドハントの芸術情報館へ向かった）"
"1012706-7" = "ワイルドハント・芸術情報館"
"1012706-8" = "[ns] 空いている席に座った。"
"1012706-9" = "[ns] \"終わりが見えない……。\""
"1012706-10" = "（どれくらい時間が経ったのだろう……）"
"1012706-11-山の精霊" = "……。"
"1012706-12" = "[s] \"どちら様ですか……？\""
"1012706-13-山の精霊" = "寝てる場合か？#n仕事はどうした？"
"1012706-14" = "[s] \"はい？\""
"1012706-15-山の精霊" = "あちらの峰を見たまえ……！"
"1012706-16-山の精霊" = "あと、私にラーメンを持って来い。"
"1012706-17" = "[s] \"す、少しだけ休ませてください……！\""
"1012706-18-山の精霊" = "なにっ？この私に口答えするつもりか！？"
"1012706-19-山の精霊" = "無礼者！"
"1012706-20" = "[ns] \"うああっ……！\""
"1012706-21-ミヨ" = "こちらにいたんですね、先生。"
"1012706-22" = "[wa:610]― [log=미요]……[wa:1740]こんなところで、[wa:1060]何をされているんですか？[/log]"
"1012706-23" = "[wa:80]― [log=미요]ずっと先生を[wa:810]探していたのに……。[/log]"
"1012706-24" = "[ns] \"ミヨ……？\""
"1012706-25" = "[wa:610]― [log=미요]さっきから[wa:1060]少し[wa:800]苦しそうですが……。[/log]"
"1012706-26" = "― [log=미요]もしかして、[wa:1030]あまり[wa:490]体調が[wa:370]良くないのですか……？[/log]"
"1012706-27" = "[ns] \"ちょっと変な夢を見てね……。\""
"1012706-28" = "[wa:2480]― [log=미요]なるほど、[wa:1570]悪夢……。[/log]"
"1012706-29" = "― [log=미요]きっと、[wa:1200]罰が当たったんですよ。[/log]"
"1012706-30" = "[ns] \"そんな悪いことしたかな！？\""
"1012706-31" = "[wa:2300]― [log=미요]最近、[wa:490]よくワイルドハントにいらしてるのに……。[/log]"
"1012706-32" = "― [log=미요]一度も、私に連絡しなかったから。[/log]"
"1012706-33" = "[ns] \"ご、ごめん……。\""
"1012706-34" = "[wa:2390]― [log=미요]……ふふ、[wa:1240]冗談ですよ。[/log]"
"1012706-35" = "― [log=미요]でも、[wa:1190]こうやって先生にお会いできて……[/log]"
"1012706-36" = "[wa:80]― [log=미요]私、[wa:990]嬉しいです。[/log]"
"1012706-37" = "ワイルドハント・芸術情報館"
"1012706-38" = "[ns] \"起こしてくれてありがとう、ミヨ。\""
"1012706-39-ミヨ" = "いいえ。"
"1012706-40-ミヨ" = "ところで、どうしてこんな場所で仕事を……？"
"1012706-41-ミヨ" = "今日先生が訪れた建物の西側に、もっと作業しやすい場所がありましたよ？"
"1012706-42-ミヨ" = "と、とりあえず立ってください。"
"1012706-43-ミヨ" = "それから……コーヒーでも飲みませんか？"
"1012706-44" = "（ミヨと一緒に校内のカフェでコーヒーを飲んだ）"
"1012706-45" = "（ワイルドハントを出た頃……ひとつの疑問が浮かんだ）"
"1012706-46" = "（……ミヨは、なんで私がどこにいるかわかったんだろう）"
