[translation]
"1012703-1" = "デビューを待ちながら"
"1012703-2" = "繫華街"
"1012703-3" = "（翌日、仕事のため早朝からワイルドハントを訪れた帰り道――）"
"1012703-4" = "[ns] \"最近、ワイルドハントによく行くなぁ……。\""
"1012703-5" = "（D.U.シラトリ区を通りがかった）"
"1012703-6-？？？" = "あれ、先生？"
"1012703-7-ミヨ" = "お、おはようございます……。"
"1012703-8" = "[s] \"ミヨ？どうしたの？\""
"1012703-9-ミヨ" = "それが……。"
"1012703-10-ミヨ" = "出版社から声がかかりまして、#n打ち合わせのために外出許可をいただいたんです……。"
"1012703-11" = "[s] \"出版社から！？\""
"1012703-12-ミヨ" = "はい。この前シャーレで書いた恋愛小説の原稿を、#nいろいろな出版社に送ってみたんです。"
"1012703-13-ミヨ" = "そのうちの一社から、出版したいと声をかけていただいて……。"
"1012703-14" = "[s1] \"あれ、恋愛小説だったんだ……。\"\n[s2] \"じゃあ、これでプロデビューだね！\""
"1012703-15-ミヨ" = "ま、まだ出版契約も結んでいませんから……！"
"1012703-16-ミヨ" = "これから打ち合わせなんですよ。"
"1012703-17-ミヨ" = "このあと14時からで――"
"1012703-18-ミヨ" = "――えっ？#n先生も一緒に？"
"1012703-19-ミヨ" = "そんな……私のためにわざわざ……。"
"1012703-20-ミヨ" = "契約書の内容を確認する第三者がいたほうがいい……ですか？"
"1012703-21-ミヨ" = "で、でしたら……。"
"1012703-22-ミヨ" = "よろしくお願いします、先生。"
"1012703-23" = "（ミヨと一緒に出版社へ向かった）"
"1012703-24" = "出版社・会議室"
"1012703-25-ミヨ" = "お待ちしておりました、[ruby=さくらい]桜井[/ruby]先生。"
"1012703-26-ミヨ" = "ところで、なぜシャーレの先生まで……。"
"1012703-27" = "[s] \"私の生徒が出版契約を結ぶと聞いたので、その付き添いです。\""
"1012703-28-出版社の社員" = "ま、まあいいでしょう。"
"1012703-29-ミヨ" = "では、始めましょうか。#nまず、出版契約を結ぶにあたり、弊社の立場についてお伝えしておきます。"
"1012703-30-出版社の社員" = "ご存知の通り、本を出版するまでには、とてもコストがかかります。"
"1012703-31-出版社の社員" = "印刷費はもちろん、編集やデザイン、マーケティング――"
"1012703-32-出版社の社員" = "さらに出版した後、売れ残った本を保管する倉庫の利用料も……。#nここまではわかりますか？"
"1012703-33-ミヨ" = "え、ええ。#n知っています。ですが、どうしてそれを……？"
"1012703-34-出版社の社員" = "我々が桜井先生の小説の出版に際し、いかにリスクを負うか、#nご理解いただきたかったのです。"
"1012703-35" = "[s] \"あの、出版で生じた費用は出版社が負うものでは……。\""
"1012703-36-出版社の社員" = "そう！そこで、弊社から一つご提案があるのです！"
"1012703-37-出版社の社員" = "つまり……桜井先生も共に「投資」していただけないかなと！"
"1012703-38-ミヨ" = "……？"
"1012703-39-出版社の社員" = "ご安心ください！編集、デザイン、印刷……そして、マーケティングの費用を桜井先生にお支払いいただくだけです！"
"1012703-40-出版社の社員" = "あとは我々にお任せを！"
"1012703-41" = "[s] \"それって実質、ミヨが全額負担するんじゃ……。\""
"1012703-42-出版社の社員" = "なるほど……！"
"1012703-43" = "[s] \"ミヨ……？\""
"1012703-44-出版社の社員" = "でも、それだけではありませんよね？"
"1012703-45-出版社の社員" = "はい？"
"1012703-46-ミヨ" = "例えば……本が発売したら、初動を良くするために自費で500冊ほど購入する必要があるのではないでしょうか？"
"1012703-47-出版社の社員" = "え、ええ！その通りです！"
"1012703-48-出版社の社員" = "そして、今後執筆する作品のクオリティ向上のために、#n御社が提供するライティング講座を受講する必要がある……しかも、有料で。"
"1012703-49-出版社の社員" = "よくご存じですね！"
"1012703-50-ミヨ" = "ええ、もちろん。"
"1012703-51-ミヨ" = "――よくある、詐欺の手口ですから。"
"1012703-52-出版社の社員" = "け、契約書が……！？"
"1012703-53-ミヨ" = "行きましょう、先生。"
"1012703-54" = "近くの公園"
"1012703-55-ミヨ" = "……ふぅ。"
"1012703-56-ミヨ" = "そんな顔をしないでください。私は本当に大丈夫ですから。"
"1012703-57-ミヨ" = "どうやって詐欺を見抜いたのか気になっているようですね。"
"1012703-58-ミヨ" = "簡単です。相手の立場で考えればいいんですよ。そうすると、自然と犯罪の手口が浮かんでくる……#n学院への「輸入」方法を考えるときと、同じですね。"
"1012703-59-ミヨ" = "ですので……。"
"1012703-60-ミヨ" = "……ぐすっ。"
"1012703-61" = "[s] \"ミヨ！？\""
"1012703-62-ミヨ" = "なんで、こんなところにばっかり偏るんでしょう……。"
"1012703-63-ミヨ" = "本当にやりたいことの才能は、全然ないのに……。"
"1012703-64-ミヨ" = "犯罪のことばかり頭が回って……。"
"1012703-65-ミヨ" = "これじゃ私、恋愛小説家になるなんて無理ですよね？"
"1012703-66" = "[s] \"それは誰にも分からないことだよ。\""
"1012703-67-ミヨ" = "ぜんぜん慰めになってませんけど……。"
"1012703-68" = "[s] \"でもミヨは、少なくとも……間違った道には進まないはず。\""
"1012703-69" = "[ns] \"――正しくないことに、気づけるんだから。\""
"1012703-70-ミヨ" = "……。"
"1012703-71-ミヨ" = "正しい道を見つけるのと同じくらい……#n間違った道を避けることも大事……。"
"1012703-72-ミヨ" = "私にこの才能がなかったら、先ほどの詐欺にも騙されていたんでしょうね。"
"1012703-73-ミヨ" = "悪いことばかりじゃない……のかも。"
"1012703-74-ミヨ" = "……やっぱり好きにはなれませんけど。"
"1012703-75" = "[s3] \"でも、部活で稼いだお金があるからこそ……。\"\n[s4] \"新しいタイプライターも買えるんだし……。\""
"1012703-76-ミヨ" = "そ、それは……！"
"1012703-77" = "（しばらくの間、ミヨと雑談をして時間を過ごした）"
