[translation]
"2601106-1" = "努力の才能"
"2601106-2" = "（佐天から連絡をもらい、射撃場へ向かうと……）"
"2601106-3" = "（入ってすぐのところに、射撃中の佐天がいた）"
"2601106-4-佐天涙子" = "……よし、今度こそ。"
"2601106-5-佐天涙子" = "……んん？"
"2601106-6-佐天涙子" = "あれぇ？さっきと同じように撃ったつもりなんだけどなあ……。"
"2601106-7-佐天涙子" = "……ふぅ。ま、こんなもんだよね。"
"2601106-8" = "[s1] \"射撃の練習？\"\n[s2] \"ため息なんかついて、どうしたの？\""
"2601106-9-佐天涙子" = "……あれ、先生。なんでここに？"
"2601106-10-佐天涙子" = "あたしのメッセージを読んで……？"
"2601106-11-佐天涙子" = "あはは、まさか来てもらえるとは思ってなくて……"
"2601106-12-佐天涙子" = "えっと、用事があったわけではないんです。#nわざわざ来てもらったのに、すみません。"
"2601106-13-佐天涙子" = "……気にしないで、ですか？#nそう言ってもらえると、助かります。"
"2601106-14-佐天涙子" = "あ、今は射撃の練習中でして……"
"2601106-15-佐天涙子" = "本当に、大した理由があったわけではないんですけどね。"
"2601106-16-佐天涙子" = "…………はぁ。"
"2601106-17-佐天涙子" = "正直、「ひょっとして」って期待してたんですけどね。"
"2601106-18-佐天涙子" = "射撃の才能ならあるのかも！みたいな。"
"2601106-19-佐天涙子" = "普段は銃を撃つ機会なんてありませんし。#nせっかくキヴォトスに来たんだから、試してみようと思って。"
"2601106-20-佐天涙子" = "まあ……ご覧の通りです。"
"2601106-21-佐天涙子" = "あはは、そこまで期待してたわけじゃないから、いいんですけどね。"
"2601106-22-佐天涙子" = "……ちょっと、残念だなーって！"
"2601106-23-佐天涙子" = "元の世界でも、自分の才能を見つけるために色々と挑戦してましたけど……"
"2601106-24-佐天涙子" = "今のところ、これといった収穫はないんです。"
"2601106-25-佐天涙子" = "で、でも、挑戦するのは良いことじゃないですか！#n別に失敗したからって、何も失いませんし！"
"2601106-26" = "[s3] \"佐天はすごいね！\"\n[s4] \"とっても立派なことだよ！\""
"2601106-27-佐天涙子" = "……えっ？"
"2601106-28-佐天涙子" = "そ、そんなに！？"
"2601106-29-佐天涙子" = "これって、褒められるようなことですか？"
"2601106-30-佐天涙子" = "……理由を聞いても、いいですか？"
"2601106-31" = "[s5] \"間違いなく佐天のすごいところだよ。\"\n[s6] \"その向上心は、誰しもが持ってるわけじゃないからね。\""
"2601106-32-佐天涙子" = "なるほど……そう言ってもらえるとは、思いもしませんでした。"
"2601106-33-佐天涙子" = "……先生は、本当にそう思ってくれているんですね。"
"2601106-34-佐天涙子" = "……えへへっ。でもまぁ、悪い気はしないですね！#n素直に嬉しいです。"
"2601106-35-佐天涙子" = "これからも色々と挑戦していれば、何か見つかるかもしれませんし！"
"2601106-36-佐天涙子" = "せっかくなので……"
"2601106-37-佐天涙子" = "最後にもう少しだけ撃ってきます！"
"2601106-38" = "（「もう少しだけ」と言っていたが、佐天はしばらく練習を続け……）"
"2601106-39" = "（銃に慣れて構えが安定すると、集弾率も上がっていった）"
