[translation]
"70005010-1" = "とある2月18日の記録"
"70005010-2" = "[log]2月18日[/log]"
"70005010-3" = "ゲヘナ学園・風紀委員会の教室"
"70005010-4-アコ" = "ケーキはもう注文しましたか？"
"70005010-5-アコ" = "注文のデッドは今日なんですからね！？"
"70005010-6-イオリ" = "アコちゃんそれ何回目？"
"70005010-7-チナツ" = "ご安心ください。予算ギリギリではありますが、注文できました……。"
"70005010-8-アコ" = "……はい？"
"70005010-9-アコ" = "予算ギリギリ……？どうしてですか？"
"70005010-10-アコ" = "このために、先月からお菓子代を一部カットしておいたのですよ。"
"70005010-11-イオリ" = "なんかお菓子少ない気がしてたんだよな……。"
"70005010-12-イオリ" = "とにかく、なぜ予算がひっ迫しているんです？"
"70005010-13-チナツ" = "それ[ruby=パンデモニウム・ソサエティー]が、万魔殿が…[/ruby]…"
"70005010-14-アコ" = "またあのタヌキどもですか？今度は何を……？"
"70005010-15-イオリ" = "プレゼントの請求先を風紀委員会にしておいた、と……。"
"70005010-16-アコ" = "……万魔殿が委員長に！？マコト議長、頭でも打ったんですか！？"
"70005010-17-チナツ" = "いえ……あんこ抜きのどら焼きを用意しようとしたそうです。"
"70005010-18-イオリ" = "あんこ抜きのどら焼きって……そんなもの、どこで見つけてきたのやら……。"
"70005010-19-チナツ" = "わざわざ特注したそうです。"
"70005010-20-アコ" = "もっと注力すべきことがあるでしょうに……。"
"70005010-21-アコ" = "でも、普通のどら焼きが届いたんだって。注文ミスだと思われたとかなんとか。"
"70005010-22-アコ" = "そうですか……はぁ……。"
"70005010-23-アコ" = "ん？待ってください。どのみち、こちらに請求が回ってくるのは変わりないんですよね！？"
"70005010-24-イオリ" = "うん……。"
"70005010-25-チナツ" = "そのせいで、予算がカツカツになってしまって……。"
"70005010-26-チナツ" = "注文は無事できましたが、配送業者は一番下のランクのところになってしまいました。"
"70005010-27-アコ" = "……。"
"70005010-28-アコ" = "まあ、それくらいなら。送料が安いに越したことはありませんし。"
"70005010-29-アコ" = "配送状況はどうなっています？"
"70005010-30-イオリ" = "ちょっと待ってね――はい、追跡サイト。"
"70005010-31-アコ" = "ありがとうございます。#nどれどれ……[ruby=にしかわ]仁志川[/ruby]センターを経由したところ……と。"
"70005010-32-アコ" = "ええ。これなら間に合いそうですね。"
"70005010-33-アコ" = "今から明日が楽しみです。皆さん、お疲れ様でした。"
"70005010-34-チナツ" = "え、えっと……"
"70005010-35-アコ" = "チナツ、どうかしたのですか？"
"70005010-36-チナツ" = "いえ……。"
"70005010-37-チナツ" = "（なんだか嫌な予感がするのですが……）"
"70005010-38-チナツ" = "（少し考えすぎ？……ええ、きっと大丈夫なはずです）"
"70005010-39-チナツ" = "（どうか……なにも起こりませんように……）"
"70005010-40" = "玄龍門・貴賓室"
"70005010-41-ミナ" = "これを見てもらおうか。玄龍門は、かの有名なパティスリーに、門主様の誕生日ケーキを注文した。"
"70005010-42-ミナ" = "お前たち、玄武商会に頼ること無く……だ。"
"70005010-43-ミナ" = "この程度、玄龍門の力を使えば朝飯前だからな。"
"70005010-44-ミナ" = "あ、はい。まあ、良いものを選んだと思います。#nケーキはそれでいいとして……お店に取りに行かなくていいのですか？"
"70005010-45-ミナ" = "安全に、そして確実に手元に届くよう、配送業者を手配したからな。#nもちろん、選定にも抜かりはない。最も安いのに、最も早く届けてくれるところに依頼した。"
"70005010-46-レイジョ" = "……それ、大丈夫ですか？"
"70005010-47-ミナ" = "うん？ケーキ屋が提示した選択肢の一つだ。滅多なことはあるまい。#nそれに安くて早い。文句の付け所が無いじゃないか。"
"70005010-48-レイジョ" = "それを鵜呑みにするのはいかがなものかと……"
"70005010-49-ミナ" = "自信があるからこそ、喧伝するのだろう？"
"70005010-50-レイジョ" = "はぁ……純粋なのか、それとも……。ちょっとそのチラシ貸してください。"
"70005010-51-レイジョ" = "……っ！？よりによってここですか！？"
"70005010-52-ミナ" = "な、なにか問題でもあるのか？"
"70005010-53-ミナ" = "……良い機会ですので、覚えておいてください。#nこの業者は文字通り、一番安くて早いところではあります。……何事もない限り。"
"70005010-54-ミナ" = "やはりな！私の目に狂いはなかったようだ。"
"70005010-55-レイジョ" = "肝心なのは「何事もない限り」ですよ。"
"70005010-56-ミナ" = "……何が言いたい？"
"70005010-57-レイジョ" = "かなりの確率で配送トラブルに巻き込まれる、という意味です。"
"70005010-58-ミナ" = "とはいえ、高が知れているのだろう？"
"70005010-59-レイジョ" = "甘く見てはいけません。#n特に悪名高いのが「仁志川センター」……またの名を、「物流の迷路」です。"
"70005010-60-レイジョ" = "「仁志川センター」はキヴォトス屈指の物流センターであり、あまりにも規模が大きいことから……"
"70005010-61-レイジョ" = "トラブルが後を絶たないんです……。"
"70005010-62-レイジョ" = "と、トラブル……？"
"70005010-63-レイジョ" = "挙げたらキリがないのですが……#n荷物がごちゃごちゃになって、配送先を間違えるとか。ザラですよ。"
"70005010-64-ミナ" = "馬鹿な！そんな会社、どうして潰れずにいられるんだ！？"
"70005010-65-レイジョ" = "あなたの言った通りです。「一番安くて早い」から。これに尽きます。"
"70005010-66-レイジョ" = "……その裏では「正確さ」が損なわれている訳ですが。"
"70005010-67-ミナ" = "……！"
"70005010-68-ミナ" = "げっ、玄龍門、集合っ！！"
"70005010-69-ミナ" = "何をするつもりですか？#nまさか、センターにある荷物を一つ一つ確認するつもりじゃないですよね？"
"70005010-70-ミナ" = "その手があったか！"
"70005010-71-レイジョ" = "だからそれをするなと言ってるんです！"
