[translation]
"70005030-1" = "とある2月19日の記録（２）"
"70005030-2-ヒナ" = "それで、何の用事なの？"
"70005030-3-ヒナ" = "言われるがままにD.U.まできたけど……。"
"70005030-4-イオリ" = "委員長、その……。"
"70005030-5-アコ" = "せ、山海経の玄武商会から、連絡をもらいまして……。"
"70005030-6-ヒナ" = "山海経？玄武商会？"
"70005030-7-ヒナ" = "つまり……学園間の交流会なの？"
"70005030-8-ヒナ" = "そういうのは、私たちの仕事じゃないのよ？"
"70005030-9-アコ" = "ご、ごほん……言い間違えました。"
"70005030-10-アコ" = "実は、その……玄武商会の……そう！「友人」から連絡をもらいまして……。"
"70005030-11-アコ" = "今日、一緒にD.U.で遊ぶ約束を、していたのですが……！"
"70005030-12-ヒナ" = "アコに……玄武商会の友達が……？"
"70005030-13-ヒナ" = "……。"
"70005030-14-ヒナ" = "ごめん、アコ。今まで苦労をかけてしまったわね。"
"70005030-15-ヒナ" = "……休暇取得のために、わざわざ嘘をつく必要はないから……。"
"70005030-16-イオリ" = "ど、どういう意味ですか！？"
"70005030-17-イオリ" = "私にはなんとなく分かるかも……。"
"70005030-18-チナツ" = "はぁ……。"
"70005030-19-イオリ" = "おふたりは黙っていてください！"
"70005030-20-アコ" = "い、委員長！こ、これは、その……"
"70005030-21-アコ" = "……。"
"70005030-22-アコ" = "とにかく、プライベートである、ということが重要なんです。"
"70005030-23-ヒナ" = "（重要……？）"
"70005030-24-ルミ" = "おっ！みんな待ってたよ！"
"70005030-25-ルミ" = "……久しぶりだね、[ruby=・]ア[/ruby][ruby=・]コ[/ruby]？"
"70005030-26-アコ" = "え、ええ！お久しぶりです、ルミさん……。"
"70005030-27-ヒナ" = "……！"
"70005030-28-ヒナ" = "（本当に……玄武商会の友達が……？）"
"70005030-29-ヒナ" = "（でも、この人たちは……玄武商会の会長とマネージャーと、玄龍門の執行部長……#nあの小柄な生徒は……）"
"70005030-30-ミナ" = "その、アコさん……お話は会長から聞きました……。"
"70005030-31-ミナ" = "う、うむ。ゲヘナの風紀委い……ではなく、友よ！#n私は[ruby=このえ]近衛[/ruby]ミナだ。それと、こちらは……。"
"70005030-32-キサキ" = "[ruby=りゅうげ]竜華[/ruby]キサキじゃ。このような場……肩書きを名乗るのは無粋かの。"
"70005030-33-キサキ" = "本題に入る前に……すまぬが、香を焚かせてくれ。"
"70005030-34-イオリ" = "ん？不思議な香りだな……。"
"70005030-35-チナツ" = "ええ、なんだか気持ちが落ち着くような……。"
"70005030-36-ヒナ" = "……。"
"70005030-37-ヒナ" = "（竜華キサキ……間違いない。#n山海経の生徒会長「黒い君主」とも呼ばれる玄龍門の門主……！）"
"70005030-38-ヒナ" = "アコ。"
"70005030-39-アコ" = "は、はい！委員長！"
"70005030-40-ヒナ" = "詳しく、説明してくれる？"
"70005030-41-アコ" = "おっ、お話の通り、私は友達のルミさんと一緒に……！"
"70005030-42-ルミ" = "アコ。せっかくみんな集まってるし、もう隠しごとはいいんじゃない？"
"70005030-43-ルミ" = "事の経緯はあたしが説明するからさ。ね？キサキ。"
"70005030-44-キサキ" = "ああ。[ruby=そなた]其方[/ruby]なら任せられる。特に、こういう場においてはな。"
"70005030-45-キサキ" = "して……ゲヘナの友人たちよ。妾のことは気軽に「キサキ」と呼んでくれ。"
"70005030-46-ヒナ" = "あ、ええと……私も「ヒナ」でいいわ……。"
"70005030-47-ヒナ" = "……。"
"70005030-48-キサキ" = "つまるところ――"
"70005030-49-キサキ" = "誤配が起きたというわけじゃな。双方の荷物が行き違ったが故のこと。"
"70005030-50-キサキ" = "ミナも、風紀委員会も、お互い最善を尽くしたようじゃが……#n運命の悪戯とは、これを指すのやもしれぬ。"
"70005030-51-キサキ" = "ふむ――そろそろ本題に移ろうかの。"
"70005030-52-キサキ" = "ほれ、これが……風紀委員会に本来届くはずだったケーキじゃ。"
"70005030-53-ヒナ" = "……ありがとう。はい、これがあなたのケーキ。"
"70005030-54-ヒナ" = "なんだかこうしているとプレゼント交換会のようね。#nふふっ……なんだか不思議な体験だわ。"
"70005030-55-ヒナ" = "まさか私たちの誕生日が同じだったなんて。"
"70005030-56-キサキ" = "365分の１……歳まで同じとなると、珍しくはあるさな。"
"70005030-57-キサキ" = "縁とは、ほんに不思議なものじゃ。"
"70005030-58-ヒナ" = "ええ……そうね。"
"70005030-59-ヒナ" = "今日は特別な日になりそう。ありがとう、みんな。"
"70005030-60-アコ" = "一時はどうなることかと思いましたが……。"
"70005030-61-レイジョ" = "無事ケーキをお届けできたこと、嬉しく思います。"
"70005030-62-レイジョ" = "最初から協力していれば、大事にならずに済んだんですけどね……。"
"70005030-63-ルミ" = "まぁまぁ、結果オーライなんじゃない？"
"70005030-64-ルミ" = "キサキ、ヒナ。はい、これはあたしから。"
"70005030-65-キサキ" = "また随分な量を作ってきたものじゃな……。皆で食べても余りあるのではないか？"
"70005030-66-キサキ" = "ケーキを食べるまで、満腹にならぬようにせねばな。"
"70005030-67-ヒナ" = "余るようなら、持って帰ればいいわ。"
"70005030-68-ヒナ" = "ふふ、それもそうさな。"
"70005030-69-アコ" = "それでは改めて……ヒナ委員長、キサキ門主！お誕生日おめでとうございます！"
"70005030-70-ミナ" = "おめでとうございます！門主様、委員長。"
"70005030-71-ヒナ" = "うん。ありがとう。"
"70005030-72-ヒナ" = "山海経とゲヘナの交流会――否、「私的」な集まりか。"
"70005030-73-ヒナ" = "今後もまた……非公式でも良い、せめて此度のように……"
"70005030-74-ヒナ" = "一歩ずつでも交流の輪を広げ、より見識を深めていきたいものじゃな。"
"70005030-75-レイジョ" = "ところで……どうして玄武商会名義の予約で誕生日パーティーを？#nしかもカラオケで……？"
"70005030-76-レイジョ" = "会長たっての希望です。"
"70005030-77-ルミ" = "やっぱり誕生日パーティーはカラオケでしょ！"
"70005030-78-イオリ" = "そう言われると、なんかそんな気もしてくるな……。"
"70005030-79-ミナ" = "そうなのか……？"
"70005030-80-ルミ" = "ほらほらっ、誰から始める？誰もやらないなら……あたしから歌っちゃうね！"
"70005030-81-アコ" = "次は私です……！"
"70005030-82-ミナ" = "華麗にバトンをつないで見せよう……！"
"70005030-83-レイジョ" = "ちょっと！この空気、どうするんですか！"
"70005030-84-レイジョ" = "わ、私に言われましても……。"
"70005030-85-チナツ" = "致し方ありません。ここは私が……"
"70005030-86" = "（送られてきた地図を見ながら、皆がいるカラオケに到着した）"
"70005030-87" = "[ns] \"やっほー！\""
"70005030-88-ヒナ" = "せ、先生……！？"
"70005030-89-キサキ" = "先生……！？"
"70005030-90" = "[ns] \"お誕生日おめでとう！ヒナ！キサキ！\""
"70005030-91-アコ" = "べっ、別に？先生を呼ぶつもりはなかったんですけどね！？"
"70005030-92-アコ" = "貸しを作っておけば後々便利だと思って……先生は私に感謝してくださいね？"
"70005030-93-ヒナ" = "アコが連絡してたの……？"
"70005030-94-ヒナ" = "アコ行政官もか？奇遇だな！私は先生に来て欲しくて呼んだのだが……。"
"70005030-95-アコ" = "あ、えっと、その……！"
"70005030-96-キサキ" = "……なるほど。二人とも、先生を招待したのじゃな。ミナ、アコ、感謝する。"
"70005030-97-キサキ" = "……先生、よくぞ参ってくれた。"
"70005030-98" = "[s1] \"誕生日だし、もちろん顔を出さないと！\"\n[s2] \"ミナもアコも、連絡してくれてありがとう！\""
"70005030-99-ミナ" = "フッ……まあ、当然のことだ。"
"70005030-100-アコ" = "……今回は特別ですからね？"
"70005030-101" = "[ns3] \"じゃあ……大人の乱入で冷え込んだ雰囲気を！\"\n[ns4] \"責任を持って、盛り上げていこうかな！\""
"70005030-102-レイジョ" = "はい？別に冷え込んでいないと思いますが……"
"70005030-103-レイジョ" = "まぁまぁ、あれも先生なりのノリだからね。"
"70005030-104-レイジョ" = "は、はあ……。"
"70005030-105" = "[ns] \"ヒナとキサキも、一緒に歌おう！\""
"70005030-106-ヒナ" = "え？でも私……歌はあまり……"
"70005030-107-キサキ" = "妾も大きな声を出すのは……"
"70005030-108-ヒナ" = "ふむ――妾たちが歌うことが肝要である、と？"
"70005030-109-ヒナ" = "そうさな……たまにはそういう姿を見せるのも一興かの。"
"70005030-110-ヒナ" = "わ、分かったわ。じゃあ……。"
"70005030-111" = "[ns] \"盛り上がっていくぞーっ！！\""
"70005030-112" = "（こうして盛り上がった2月19日の誕生日パーティーは、成功裏に幕を下ろした……のだが……）"
"70005030-113" = "（雰囲気に呑まれて、皆と同じテンションで 楽 しんだ結果……）"
"70005030-114" = "（遅れてくる激痛で、自分が「大人」であることを思い知らされてしまった）"
"70005030-115" = "とある2月19日の記録"
