[translation]
"1012502-1" = "\t魔法の絵"
"1012502-2-エリ" = "ようこそいらっしゃいました、マスター！"
"1012502-3" = "[s] \"やあ、エリ！\""
"1012502-4-エリ" = "今日はどのように過ごそうか考えておりましたところ――"
"1012502-5-エリ" = "魔導書の導きがありまして。"
"1012502-6-エリ" = "アトリエで一緒に絵を描くと良い――そうです！"
"1012502-7" = "[s1] \"一緒に描くの？なんだか楽しそうだね。\"\n[s2] \"きっと魔法みたいな絵ができるよ。\""
"1012502-8-エリ" = "はい！マスターとなら、傑作ができそうです！"
"1012502-9-エリ" = "さあ、アトリエへ向かいましょう！"
"1012502-10-エリ" = "本日はテーマを決めずに筆を走らせてみようかと。"
"1012502-11-エリ" = "つまり……画家としての純粋な感性と衝動を――#n魔法のように解き放つんです！"
"1012502-12-エリ" = "今日のようにマナが共鳴している日は……#n感性を重視した方が良いと思いますからね。"
"1012502-13-エリ" = "さぁ、いきますよ！むむん！"
"1012502-14" = "[ns] \"……タロットカード？絵を描くんじゃないの？\""
"1012502-15-エリ" = "はい！これこそが、魔法のような芸術活動に必要な工程なんです。"
"1012502-16-エリ" = "にゅふふ……運命を告げるアルカナの一枚目は――！？"
"1012502-17-エリ" = "ふむふむ、正位置の「塔」ですか。"
"1012502-18-エリ" = "これは「破壊」や「崩壊」を意味します。つまり――"
"1012502-19-エリ" = "キャンバスを突き破るような激しいタッチで描くべし！#n……という啓示ですね！"
"1012502-20-エリ" = "では……いきます！！"
"1012502-21" = "[ns] \"おお……すごい勢いだ。\""
"1012502-22-エリ" = "にゅふふ……。#nでは、次なる一手を占ってみましょう。"
"1012502-23-エリ" = "次に私を導くのは……！"
"1012502-24-エリ" = "むむっ？逆位置の「死神」……？"
"1012502-25-エリ" = "これは変化を拒む「停滞」を表していますが……。"
"1012502-26-エリ" = "引き続き、激しいタッチで描けということですね！"
"1012502-27" = "[ns] \"そ、そんな勢いよく描いちゃって大丈夫……？\""
"1012502-28-エリ" = "ご安心を！私は魔法の力を信じていますから！"
"1012502-29-エリ" = "たとえキャンバスが裂けようとも、#nそれは「力の表現」……立派な芸術ですよ！#n恐れることはありません！"
"1012502-30-エリ" = "このまま描き続けます……！"
"1012502-31" = "（その後もタロットはエリを激しい筆運びへ[ruby=いざな]と誘い[/ruby]続けた）"
"1012502-32" = "（しばらくして……）"
"1012502-33-エリ" = "おお……これは！"
"1012502-34-エリ" = "私がこんな作品を生み出せるなんて……まさに魔法です！"
"1012502-35" = "[s] \"どんな絵ができたの？\""
"1012502-36-エリ" = "どうぞご覧ください！#nマスターと私のマナの共鳴が生み出した、渾身の一作を！"
"1012502-37" = "（雰囲気がある絵に仕上がってる……！）"
"1012502-38-エリ" = "タイトルは『[ruby=とわ]永久[/ruby]に吹き荒れる嵐』！"
"1012502-39-エリ" = "今回用いた魔法を発展させていけば、#n階十位の『世界創造魔法』を使いこなす日もそう遠くはありませんね……！"
"1012502-40" = "[s3] \"階十位って、なんだか凄そう……！\"\n[s4] \"ほんとに迫力があってかっこいい絵だね……！\""
"1012502-41-エリ" = "にゅっふっふ～"
"1012502-42-エリ" = "「芸術は爆発だ」という言葉がぴったりな出来映えかと！"
"1012502-43-エリ" = "やはりマスターをお呼びして正解でした。#nこのような絵を描くのは、私一人では難しかったでしょう。"
"1012502-44-エリ" = "この勢いでいけば、次の実技試験もきっと……！"
"1012502-45-エリ" = "あっ……魔力を使いすぎてしまったかも知れません。"
"1012502-46-エリ" = "マスター、マナの補給をお願いします！"
"1012502-47" = "[s5] \"ま、マナの補給……？\"\n[s6] \"要するに、おやつがほしいってことかな？\""
"1012502-48" = "[ns] 寮監隊の検問をかいくぐって持ち込んだクッキーを取り出す。"
"1012502-49-エリ" = "わあ……！美味しそうなクッキーですね！"
"1012502-50-エリ" = "でも、どうしましょう。手が絵の具まみれで……。"
"1012502-51-エリ" = "にゅふふ、こうなっては仕方ありません。#nマスター……よければ食べさせてくれませんか？"
"1012502-52" = "[s] \"そ、そういうことなら……。\""
"1012502-53-エリ" = "ありがとうございます！"
"1012502-54-エリ" = "それでは、いただきますっ！"
"1012502-55-エリ" = "いや～、マスターから直接いただくマナは格別ですね！"
"1012502-56" = "[s] \"もしかして、これが狙いだったりした……？\""
"1012502-57-エリ" = "にゅふ……それはどうでしょう？"
"1012502-58-エリ" = "きっとこれも、魔法の導きですよ！"
"1012502-59" = "（その後もエリにマナを補給しながら、楽しい時間を過ごしたのだった）"
