[translation]
"1007005-1" = "雨空の色"
"1007005-2" = "（山海経の行政事務を終えて、帰路に着いたところ……）"
"1007005-3" = "[ns] \"あれ……？\""
"1007005-4" = "（ザーザー）"
"1007005-5" = "[ns] \"通り雨かな……？\""
"1007005-6-ミナ" = "傘が入り用だろう、先生？"
"1007005-7" = "[s] \"ミナ！\""
"1007005-8" = "[ns] \"雨が降ること、知ってたの？\""
"1007005-9-ミナ" = "フフッ……古傷が教えてくれてな。"
"1007005-10" = "[s] （……今日のところは触れないでおこう）"
"1007005-11-ミナ" = "さて……こんな天気だし、送っていこうじゃないか。"
"1007005-12" = "（そうして、ミナと一緒に雨のなか山海経を歩いた）"
"1007005-13" = "（ミナの横顔は、どこか楽しそうに見えた）"
"1007005-14" = "[s1] \"もしかして……\"\n[s2] \"ミナは雨が好きなの？\""
"1007005-15-ミナ" = "ん？"
"1007005-16-ミナ" = "どちらかと言えば……"
"1007005-17" = "[wa:1400]― [log=미나]そうだな……[wa:1600]雨の[wa:300]日の[wa:300]景色は好きだ。[/log]"
"1007005-18" = "[wa:100]― [log=미나]色々なものが[wa:1000]シンプルに[wa:300]見える。 [/log]"
"1007005-19" = "[wa:1600]― [log=미나]白と[wa:650]黒――[/log]"
"1007005-20" = "[wa:200]― [log=미나]ノワールの[wa:400]世界。[/log]"
"1007005-21" = "[wa:800]― [log=미나]この世界は、[/log]"
"1007005-22" = "[wa:100]― [log=미나]眩しすぎるほどの光彩で構成されている。[/log]"
"1007005-23" = "[wa:900]― [log=미나]だが、[wa:1100]人々は[wa:900]その事実に[wa:500]気付かない……[/log]"
"1007005-24" = "[wa:400]― [log=미나]私だって[wa:600]例外ではないが。[/log]"
"1007005-25" = "[wa:800]― [log=미나]ノワールの世界は、[wa:2100]違うんだ。[/log]"
"1007005-26" = "[wa:200]― [log=미나]少なくとも……[wa:1300]分かりやすい。[/log]"
"1007005-27" = "[wa:1400]― [log=미나]ただ……[wa:1200]そうだな。[/log]"
"1007005-28" = "[wa:600]― [log=미나]せめて[wa:700]傘くらいは……[wa:2100]道に迷わぬよう、[/log]"
"1007005-29" = "[wa:700]― [log=미나]明るい色のものが良いだろう。[/log]"
"1007005-30" = "[ns3] \"確かに、明るい色の傘があれば……\"\n[ns4] \"[ruby=みちしるべ]道標[/ruby]になるね。\""
"1007005-31-ミナ" = "――門主様のようにな。"
"1007005-32" = "[s] \"キサキ……？\""
"1007005-33-ミナ" = "ああ。私が玄龍門に入ったのは、門主様がいたからだ。"
"1007005-34-ミナ" = "お金や名誉なんてものは、どうだっていい。#nそんなものは、いずれ消えてしまう……虚しいだけだ。"
"1007005-35-ミナ" = "だが、門主様のハードボイルドな心意気は本物だぞ！"
"1007005-36-ミナ" = "思わず跪いてしまうほどのカリスマ！#nそれでいて、皆の意見を聞き入れる懐の深さ！"
"1007005-37-ミナ" = "にもかかわらず、抱きしめれば壊れてしまいそうな、あの華奢な姿！#nそのギャップが最高だろう！？"
"1007005-38-ミナ" = "わ、私だけじゃないぞっ。#n構成員のほとんどは、門主様の魅力に惹かれて集まってるからな！"
"1007005-39" = "[ns] （玄龍門はキサキのファンクラブなのかな……？）"
"1007005-40-ミナ" = "……コホン。#n失礼、少し取り乱してしまった。"
"1007005-41-ミナ" = "とにかく……人生には明るい傘が必要、ということだ。"
"1007005-42" = "[s] \"そうだね。もちろん、雨の日にも。\""
"1007005-43-ミナ" = "……フッ。分かってるじゃないか、先生。"
"1007005-44-ミナ" = "先生と話していると……時々、不思議な気持ちになる。"
"1007005-45-ミナ" = "自分では話そうと思っていなかった部分まで、自然と口から出てしまう。"
"1007005-46-ミナ" = "急に飛び出して、どうしたんだ？#nほら、まだ雨が降ってるぞ、先生。"
"1007005-47" = "[s5] \"実は、私も雨が好きなんだ。\"\n[s6] \"雨に降られながら、歌って、踊って。\""
"1007005-48-ミナ" = "……。"
"1007005-49-ミナ" = "あっ……そうか。"
"1007005-50-ミナ" = "昔、映画で見た記憶がある。"
"1007005-51-ミナ" = "なんだ、やはり先生は映画に詳しいんじゃないか。"
"1007005-52-ミナ" = "ああ……今日は本当に、いい日だな。"
"1007005-53-ミナ" = "タップダンス日和だ……！"
"1007005-54-ミナ" = "あははっ、ははっ……はははっ……！"
"1007005-55" = "（ミナは明るく微笑みながら走ってきた）"
"1007005-56" = "（降り注ぐ雨のなか、私たちは2人だけの舞台で踊った）"
