[translation]
"2004806-1" = "水辺とあなたとお魚と"
"2004806-2" = "ティーパーティーの専用プール"
"2004806-3" = "（ナギサのいるプールに向かった）"
"2004806-4" = "（それにしても、釣りとプールに何の関係があるんだろう……）"
"2004806-5-ナギサ" = "あっ、先生。#nこちらです。"
"2004806-6-ナギサ" = "こんなに早く来てくださるとは……感謝いたします。"
"2004806-7-ナギサ" = "今回先生をお呼びしたのはですね……。"
"2004806-8-ナギサ" = "……いえ、実際にお見せした方が良いでしょう。こちらをご覧ください。"
"2004806-9" = "[ns] プールの中を覗いてみる。"
"2004806-10" = "[ns] \"……魚！？\""
"2004806-11" = "（プールの中を、数十匹の魚が泳いでいた）"
"2004806-12-ナギサ" = "今から、この魚たちを……。"
"2004806-13-ナギサ" = "一匹ずつ釣っていかなくてはなりません。"
"2004806-14-ナギサ" = "しかし、私一人では永遠に終わらない気がしまして……。"
"2004806-15-ナギサ" = "大変お手数ですが、先生にご協力いただきたく……。"
"2004806-16" = "[s] \"一体、誰がこんなことを……？\""
"2004806-17-ナギサ" = "ふふ、それは――"
"2004806-18-ナギサ" = "私ですよ。"
"2004806-19" = "[ns] \"……はい？\""
"2004806-20-ナギサ" = "プールに魚を放したのは、私です。"
"2004806-21-ナギサ" = "正確には、御付きの方にお願いしたことなのですが……。"
"2004806-22" = "[s] \"ど、どうして？\""
"2004806-23-ナギサ" = "帰ってきて早々、水辺で過ごしたひとときが恋しくなりまして……。"
"2004806-24-ナギサ" = "そして、魚も大事ですが――"
"2004806-25-ナギサ" = "私をよく見てください。"
"2004806-26-ナギサ" = "先生なら、すでにお気づきでしょう？"
"2004806-27" = "[s] \"えーっと……？\""
"2004806-28-ナギサ" = "悩みに悩み抜いた末、この水着を私が選んだということに。"
"2004806-29-ナギサ" = "ですが、そんな水着も数日間の休暇でお披露目した後は、次の夏までクローゼットで眠る運命にありました……。"
"2004806-30-ナギサ" = "それを少々もったいなく思っていたのです。"
"2004806-31" = "[s] \"……だったら、泳ぐのもありじゃない？\""
"2004806-32-ナギサ" = "……波のように押し寄せる業務と水泳は、両立できないものです。"
"2004806-33-ナギサ" = "泳ぎながら書類にサインをするのも難しいですし……。"
"2004806-34-ナギサ" = "激しい運動は控えたいなと。"
"2004806-35" = "[s] \"な、なるほど。\""
"2004806-36-ナギサ" = "釣りならば業務と並行できると考え――"
"2004806-37-ナギサ" = "こうして近隣に生息するお魚を手配したのですが……。"
"2004806-38-ナギサ" = "一人で釣るにはあまりにも数が多く、困っていたところです。"
"2004806-39-ナギサ" = "聞くところによれば、車のバッテリーを利用し、一度にたくさんのお魚を気絶させるという漁もあるとか。"
"2004806-40-ナギサ" = "ですが、流石にそれはちょっと……。"
"2004806-41" = "[s] \"う、うん！やめておいたほうがいいね……！\""
"2004806-42-ナギサ" = "ええ。私も同感です。"
"2004806-43-ナギサ" = "ということで先生、せっかくですし……。"
"2004806-44-ナギサ" = "よければ、私と一緒に釣りを楽しみませんか？"
"2004806-45" = "（そうして、世の中で一番優雅な釣りを楽しみ――）"
"2004806-46" = "（魚たちは、元いた場所へ放流してあげた）"
