[translation]
"2300702-1" = "少し変わった女の子"
"2300702-2" = "（ハナコと約束した通り、トリニティ総合学園に到着した）"
"2300702-3" = "（トリニティはいつ見ても相変わらず、古風で上品なキャンパスで……）"
"2300702-4-？？？" = "先生～。"
"2300702-5-？？？" = "こちらですよ～。"
"2300702-6" = "[s] \"……？\""
"2300702-7" = "[s] 音が聞こえた方に振り向く。"
"2300702-8" = "[wa:1000]― こんにちは、[wa:1000]先生。"
"2300702-9" = "[wa:200]― 来ていただいて、[wa:1350]ありがとうございます。"
"2300702-10" = "[ns] \"……何してるの？\""
"2300702-11" = "[wa:400]― こうしていると[wa:800]涼しくて、[wa:1600]とっても[wa:700]気持ち良いんですよ。"
"2300702-12" = "― 私にとっての[wa:1500]特等席なんです、[wa:2000]ふふっ……。"
"2300702-13" = "[wa:900]― せっかくですし、[wa:2450]先生もいかがですか？"
"2300702-14" = "― ここで[wa:450]一緒に、[wa:1850]脱いでしまいません……？"
"2300702-15" = "[ns1] \"ちょっとその誘いに乗るのは何だか……。\"\n[ns2] \"遠慮しておこうかな……。\""
"2300702-16" = "[wa:1650]― こうして、[wa:1400]こんな真っ昼間から素肌をさらしていると、"
"2300702-17" = "[wa:1550]― こうして、[wa:1350]こんな真っ昼間から素肌をさらしていると、"
"2300702-18" = "― 何だか[wa:500]楽しくなってくるんですよ？"
"2300702-19" = "― イケないことをしてる……[wa:2500]そんな感じがして。"
"2300702-20" = "（ハナコは靴を履いて、噴水から降りてこちらの方へと来た）"
"2300702-21-ハナコ" = "ふふ……。"
"2300702-22-ハナコ" = "先生は脱ぐの、お好きではないのですか？"
"2300702-23" = "私は結構好きでして。時々、全部脱いだ状態で校庭を歩いたりもするのですが、そうするとえも言われぬ気持ちになれるんです……。"
"2300702-24-ハナコ" = "普段日常を過ごしている空間で、非日常的な行いをすることはこう、禁忌を犯しているような感覚と言いますか……。"
"2300702-25-ハナコ" = "本で読んだのですが、健康にも良いのだとか。"
"2300702-26-ハナコ" = "先生もいかがですか？意外と自分の欲望の形というのはわからないものです。やってみたら、意外とハマってしまうかもしれませんよ……？"
"2300702-27" = "[s3] \"……靴と、靴下の話だよね？\"\n[s4] \"裸足で過ごす、っていう話だよね？\""
"2300702-28-ハナコ" = "ふふっ……。"
"2300702-29-ハナコ" = "ふふっ……。"
"2300702-30-ハナコ" = "指圧的な効果があるので肉体的な健康にはもちろん、精神的な健康にも良さそうですし。"
"2300702-31-ハナコ" = "いっそ、トリニティ全体で流行ったら面白そうですね。"
"2300702-32-ハナコ" = "みんなで一斉に脱いでしまって、晴れやかな気持ちで登校する……"
"2300702-33-ハナコ" = "ふふっ、想像するだけですごい景色だと思いません？"
"2300702-34" = "[s] \"裸足で登校っていう話だよね……？\""
"2300702-35-ハナコ" = "いえ、裸で登校するお話です。は・だ・か、で♡"
"2300702-36-ハナコ" = "全員が一糸まとわぬ姿で、■■を■■のも■■にして、■■してないかどうか■■で■■■■に■■してもらって■■■■■■■■■■るんです。"
"2300702-37" = "[s] \"…………。\""
"2300702-38-ハナコ" = "……。"
"2300702-39-ハナコ" = "……なんて、冗談ですよ、先生。いくら何でも、このトリニティでそんなことは起きません。"
"2300702-40-ハナコ" = "ですが、もし叶ったらきっと、すごく楽しいでしょうね……。"
"2300702-41" = "[s5] 閑話休題。\n[s6] 本題に移る。"
"2300702-42-ハナコ" = "……あ、はい。そうでした。"
"2300702-43-ハナコ" = "……あ、はい。そうでした。"
"2300702-44-ハナコ" = "聞きたいことがあって先生をお呼びしたのに、何だか先生とこういうお話をしているとつい楽しくなってしまって……。"
"2300702-45-ハナコ" = "それでは場所を移しましょうか。私が「お勉強」にぴったりの場所を確保しておきましたので。"
"2300702-46-ハナコ" = "あれこれと、実技を教わるのにぴったりの……。"
"2300702-47-ハナコ" = "さあ、では行きましょうか。"
"2300702-48-ハナコ" = "……先生、どうかしましたか？そんなところに立ってないで、早く行きましょう？"
"2300702-49" = "[s7] 念のため……\n[s8] その「場所」がどこなのか聞いてみる。"
"2300702-50-ハナコ" = "決まってるじゃないですか、放課後の補習授業といえば……"
"2300702-51-ハナコ" = "決まってるじゃないですか、放課後の補習授業といえば……"
"2300702-52-ハナコ" = "誰も来ない、「体育倉庫」ですよ。安心してください、この通り鍵も借りておきましたので……。"
"2300702-53" = "[s9] \"異議あり！\"\n[s10] \"断固拒否！\""
"2300702-54-ハナコ" = "あら……"
"2300702-55-ハナコ" = "あら……"
"2300702-56-ハナコ" = "それはつまり……ここで、ということですか？"
"2300702-57-ハナコ" = "ここは結構、人も行き来しますし……こんな明るい時間帯から広場でというのはなかなかハードな……。"
"2300702-58-ハナコ" = "ですが、一生に一度のことですし、それくらいインパクトがあっても……？"
"2300702-59" = "[s] \"勉強！ 勉強の話だよね！？\""
"2300702-60-ハナコ" = "はい、お勉強の話ですよ？大人の方に教えていただく「お勉強」……。"
"2300702-61-ハナコ" = "ふふ……すみません、ちょっとからかい過ぎてしまいましたね。先生の反応があまりにも良くって。"
"2300702-62-ハナコ" = "……では。"
"2300702-63-ハナコ" = "本館の図書館にでも行きましょうか。人も多いところなので、心配しなくても大丈夫ですよ。"
"2300702-64-ハナコ" = "さあ、行きましょう。"
"2300702-65" = "（その後、全力で警戒しながらハナコの後についていったものの、行き先は本当に図書館だった）"
"2300702-66" = "（……実際の質問は1、2問だけだったので、図書館に到着するまでの時間よりも、到着してからの時間の方が短かった）"
