[translation]
"1011603-1" = "二人のレッスン"
"1011603-2" = "（送られてきたのは、煌びやかな撮影スタジオの住所だった）"
"1011603-3-サオリ" = "先生、こっちだ。"
"1011603-4" = "[s1] \"ここがスタジオ？\"\n[s2] \"素敵な場所だね。\""
"1011603-5-サオリ" = "ああ。今日はほかに撮影予定もなく、自由に使っていいそうだ。"
"1011603-6-サオリ" = "だから……よろしく頼む。"
"1011603-7-サオリ" = "私にダンスを教えてほしい。"
"1011603-8-サオリ" = "誰かと一緒に踊るなど……想像もつかなくて。"
"1011603-9" = "[s] \"じゃあ、私がサオリの初めてのパートナーかな？\""
"1011603-10-サオリ" = "そうだな。"
"1011603-11-サオリ" = "初めてのパートナーが、先生……。"
"1011603-12-サオリ" = "信頼できる大人でよかった。"
"1011603-13-サオリ" = "お手柔らかに頼む。"
"1011603-14" = "[s] \"もっ、もちろん……！\""
"1011603-15-サオリ" = "ん……？先生も緊張しているのか？"
"1011603-16-サオリ" = "……そうか。正直、私も少し緊張している。"
"1011603-17-サオリ" = "こんな広い部屋の中で……。"
"1011603-18-サオリ" = "互いの息を感じるくらい、近づいているからな……。"
"1011603-19" = "[s] \"そ、それじゃ！ダンスを始めようか！\""
"1011603-20-サオリ" = "……先生もこういう状況は慣れていないのだな。"
"1011603-21-サオリ" = "だが、ほかに頼める人が思い浮かばなかった。"
"1011603-22-サオリ" = "先生さえよければ……撮影の時もパートナーをお願いしたい。"
"1011603-23-サオリ" = "無理は承知だ。難しいようなら、遠慮なく断ってくれ。"
"1011603-24" = "[s3] \"是非お願いします！\"\n[s4] \"むしろ、こちらこそよろしく！\""
"1011603-25-サオリ" = "……感謝する、先生。"
"1011603-26-サオリ" = "覚悟も確かめ合ったところで、始めようか。"
"1011603-27-サオリ" = "……ところで、ダンスはどう始めるものなのだろう？"
"1011603-28-サオリ" = "……挨拶？パートナーに？"
"1011603-29-サオリ" = "ひとつ学ばせてもらおうか。"
"1011603-30-サオリ" = "先生……いや、パートナーへの挨拶を。"
"1011603-31" = "[wa:2530]― [log=사오리 드레스 비무장]こ、[wa:1140]こうすればいいのか……？[/log]"
"1011603-32" = "― [log=사오리 드레스 비무장]先生がいうのなら……[wa:2920]だが、[wa:1300]これは少し……。[/log]"
"1011603-33" = "[wa:3070]― [log=사오리 드레스 비무장]普段は、[wa:1260]絶対取らないポーズだから。[/log]"
"1011603-34" = "[wa:2200]― [log=사오리 드레스 비무장]両手が塞がっていると、[wa:2380]少し不安になる。[/log]"
"1011603-35" = "[wa:4350]― [log=사오리 드레스 비무장]パートナーを[wa:440]信頼していなければ[wa:1600]難しいな。[/log]"
"1011603-36" = "[wa:890]― [log=사오리 드레스 비무장]もしかして……[wa:1940]それを示す挨拶、[wa:2200]だったのか？[/log]"
"1011603-37" = "[wa:830]― [log=사오리 드레스 비무장]ならば……[wa:1620]先生が満足するまで、[wa:2630]こうしていよう。[/log]"
"1011603-38" = "[wa:1250]― [log=사오리 드레스 비무장]それが……[wa:2640]私の信頼の証だ。[/log]"
"1011603-39-サオリ" = "挨拶ひとつにも深い意味があるのだな、良いことを学んだ。"
"1011603-40-サオリ" = "ん？なぜ微笑んで……何か間違えただろうか。"
"1011603-41-サオリ" = "……とにかく、次に移ろう。"
"1011603-42-サオリ" = "次は……パートナーと手を取る？"
"1011603-43-サオリ" = "ふぅ……覚悟はできている。来い、先生！"
"1011603-44" = "[s] \"行くよ、サオリ！\""
"1011603-45-サオリ" = "手を取り合っただけなのに……体が震える……？"
"1011603-46-サオリ" = "そういえば以前、警護中にこのようなダンスを見たことがある。"
"1011603-47-サオリ" = "……まさか自分がやることになるとはな。"
"1011603-48-サオリ" = "すべて先生のおかげだ。"
"1011603-49-サオリ" = "戦うことしか知らなかった私が、こんな経験をするとは。"
"1011603-50-サオリ" = "……！"
"1011603-51-サオリ" = "そうか……さっきの震えは……。"
"1011603-52-サオリ" = "……先生と、触れ合ったからか。"
"1011603-53-サオリ" = "まだ至らない点も多いが、引き続きよろしく――"
"1011603-54-サオリ" = "ま、待てっ！なぜ私の腰に手を……！"
"1011603-55-サオリ" = "まだ心の準備が……！"
"1011603-56-サオリ" = "あっ……だ、ダンスの一環か。誤解してすまない。"
"1011603-57-サオリ" = "いろいろと考えすぎてしまったようだ。"
"1011603-58-サオリ" = "ええと、次は私の手を……先生の肩に？"
"1011603-59-サオリ" = "了解だ……ふぅぅ……"
"1011603-60-サオリ" = "い、行くぞ先生……！"
"1011603-61" = "（二人でダンスの練習に励んだ）"
