[translation]
"1002803-1" = "ウサギの生態"
"1002803-2" = "（業務がいくつも重なり、結構限界が近づいてきた頃……）"
"1002803-3" = "（少し息抜きを兼ねて、近くの川沿いへと訪れた）"
"1002803-4-？？？" = "あれ？ご主人様？"
"1002803-5" = "[s1] \"……あれ？\"\n[s2] \"この声は……。\""
"1002803-6-アスナ" = "やっほーご主人様！こんなところで会うなんて奇遇だね？"
"1002803-7-アスナ" = "アスナと一緒に、ウサギの生態観察する？"
"1002803-8" = "[s] \"アスナ、どうしてその格好で……？\""
"1002803-9-アスナ" = "ん？"
"1002803-10-アスナ" = "格好、って……それはもちろん着るでしょ？"
"1002803-11-アスナ" = "だって今日は、ウサギの生態を確認しに来たんだから！"
"1002803-12-アスナ" = "ウサギについて理解するためには、まずウサギになってみようかなって！ね、良いアイデアでしょ？"
"1002803-13-アスナ" = "ほら、ここにはこうして草もたくさんあるし！ウサギにはぴったりの場所だよ！"
"1002803-14-アスナ" = "……ん？"
"1002803-15-アスナ" = "すごい見られてる……？うん、そうだね。それがどうかしたの？"
"1002803-16-アスナ" = "だってご主人様も、外にウサギがいたら見るでしょ？普通のことだよ！"
"1002803-17-アスナ" = "そういう意味じゃない……？"
"1002803-18-アスナ" = "そうなの？"
"1002803-19-アスナ" = "うーん……。"
"1002803-20-アスナ" = "はっ、もしかして……"
"1002803-21-アスナ" = "ご主人様も、ウサギになってみたい？"
"1002803-22" = "[s3] \"？？？\"\n[s4] \"ごめん、アスナの速さについていけてないかも。\""
"1002803-23-アスナ" = "そういうことだったら、私がご主人様のサイズで同じ服を探してきてあげるよ！"
"1002803-24-アスナ" = "そういうことだったら、私がご主人様のサイズで同じ服を探してきてあげるよ！"
"1002803-25-アスナ" = "……え、大丈夫？そうなの？"
"1002803-26-アスナ" = "もったいないなー。"
"1002803-27-アスナ" = "なんでそんなに慌ててるの？変なご主人様、きっと似合うのに！"
"1002803-28-アスナ" = "でも、じゃあご主人様は何をしよっか？"
"1002803-29-アスナ" = "……はっ。"
"1002803-30-アスナ" = "ご主人様はご主人様だし、今日はメイドのご主人様じゃなくて、ウサギのご主人様になれば良いんだ！"
"1002803-31-アスナ" = "うん、それが良いかも！"
"1002803-32-アスナ" = "となるとー……"
"1002803-33-アスナ" = "ご主人様、はい！ウサギのアスナを撫でて！"
"1002803-34" = "[s5] \"公衆の面前でそれは、ちょっと……。\"\n[s6] \"ごめん、思考回路が速くて全然ついていけてない……。\""
"1002803-35-アスナ" = "良いから早く早くー！"
"1002803-36-アスナ" = "良いから早く早くー！"
"1002803-37-アスナ" = "ほら、撫でて撫でて！"
"1002803-38-アスナ" = "もー、どうして撫でてくれないの？変な方を向いて、あっちに何か面白いものでもあった？"
"1002803-39-アスナ" = "ウサギは寂しくさせちゃダメなんだよ！寂しくなると弱っちゃうんだよ！"
"1002803-40-アスナ" = "だからご主人様は、アスナが寂しがらないように可愛がってくれないと！"
"1002803-41-アスナ" = "む～～～～……。"
"1002803-42-アスナ" = "……こうなったら仕方ない！ご主人様が撫でてくれないなら……"
"1002803-43-アスナ" = "アスナの方から、身体をこすりつけにいってあげる！"
"1002803-44-アスナ" = "あっ、ご主人様が見たこともない速さで！？"
"1002803-45-アスナ" = "待って待ってー！ご主人様～！！"
"1002803-46-アスナ" = "逃がさないよ～～～～！！"
