[translation]
"211050-1" = "第5話;ゲヘナを偉大に……？"
"211050-2" = "[ns] \"はぁ、はぁ……マユミ、足速いんだね……。\""
"211050-3-カレン" = "あ、もう始めてる。生徒も集まってきてるね。"
"211050-4-マユミ" = "――でも、今のゲヘナってどう？"
"211050-5-マユミ" = "まさにカオス！"
"211050-6-マユミ" = "みんなバラバラで好き勝手やってばっかり！！"
"211050-7-ゲヘナの生徒A" = "そのほうが楽しくない？"
"211050-8-ゲヘナの生徒B" = "なんでダメなの？"
"211050-9-マユミ" = "ゲヘナをもう一度偉大にするためだよ！"
"211050-10-ゲヘナの生徒C" = "ならなくてよくない？"
"211050-11-ゲヘナの生徒D" = "偉大だったことなんてある？"
"211050-12-マユミ" = "もちろん！ある！"
"211050-13-マユミ" = "「偉大」を大げさに考えないで。"
"211050-14-マユミ" = "私が言いたいのは、難しい歴史の勉強とか退屈な道徳の話じゃない。"
"211050-15-マユミ" = "偉大とは――強いってこと！！"
"211050-16-ゲヘナの生徒A" = "もう十分強いよね？"
"211050-17-ゲヘナの生徒B" = "キヴォトス三大学園の1つなんだし。"
"211050-18-マユミ" = "三大校なんて、他の学園と並べられてて満足なの？#n昔、ゲヘナはキヴォトスで最強だったんだよ！"
"211050-19-ゲヘナの生徒D" = "そこまで考えたことなかったけど……。"
"211050-20-マユミ" = "ゲヘナはどうして弱くなったと思う？"
"211050-21-マユミ" = "それは、私たちが一つにまとまれてないから！"
"211050-22-マユミ" = "……想像してみて。"
"211050-23-マユミ" = "私たちが一つにまとまって、キヴォトス最強になった姿を！"
"211050-24-マユミ" = "もっとたくさんの予算と弾薬！他のどの学園にも気を遣わなくていい！"
"211050-25-マユミ" = "誰の顔色も窺わなくていい圧倒的な力！#n「偉大になる」っていうのは、それを自分たちの手で勝ち取るって意味！"
"211050-26-マユミ" = "別に今でもあんま気にしてなくない？"
"211050-27-マユミ" = "ちょっと大げさだよね。"
"211050-28-マユミ" = "で、どうやって偉大にするの？"
"211050-29-マユミ" = "そうそう。言うだけじゃ変わるわけないし。"
"211050-30-マユミ" = "それは……。"
"211050-31-マユミ" = "ショウコ！！"
"211050-32" = "[s] \"ノープラン！\""
"211050-33-ショウコ" = "マユミ委員長は細かいことが不得手なので。適材適所です。"
"211050-34-ショウコ" = "ゲヘナ再興委員会の書記、[ruby=いがらし]五十嵐[/ruby]ショウコです。#nここからの話は私から。"
"211050-35-ゲヘナの生徒B" = "おっ……？"
"211050-36-ショウコ" = "「偉大さ」だって1歩ずつ。まずは簡単なところから始めましょう。"
"211050-37-ショウコ" = "ゲヘナで起きていることを例に挙げます。"
"211050-38-ショウコ" = "誰かが撃ったロケットランチャーで、バスケットコートのゴールが破損。#n学園境界哲学部の弾薬庫が爆発し、部室棟が全壊。#nどちらも今日の出来事です。"
"211050-39-ゲヘナの生徒D" = "あー、あれね。マジ笑った。"
"211050-40-ショウコ" = "通常、そういう場合はどうなりますか？"
"211050-41-ゲヘナの生徒D" = "えっと……風紀委員会が来るよね？"
"211050-42-ゲヘナの生徒D" = "反省室に閉じ込められて……。"
"211050-43-ゲヘナの生徒C" = "減点とか、反省文とか……。"
"211050-44-ゲヘナの生徒C" = "うぅ……考えたくもない……。"
"211050-45-ショウコ" = "その通り。風紀委員会は、規則違反者を罰する組織です。"
"211050-46-ショウコ" = "公共の場の騒乱、暴動、銃撃、爆発物の設置――すべて対象です。"
"211050-47-ゲヘナの生徒B" = "いつもいつも、頭カタすぎるんだよ。"
"211050-48-ショウコ" = "では……もしも風紀委員会が手を出してこなくなったら？"
"211050-49-ゲヘナの生徒B" = "は？"
"211050-50-ゲヘナの生徒B" = "そんなのありえないでしょ。"
"211050-51-ショウコ" = "規則違反が問題なのであれば、その行為を「合法」にすればいいのです。"
"211050-52-ショウコ" = "また例を挙げましょう。"
"211050-53-ショウコ" = "「暴れるのを許可された場所」で行うとしたら？"
"211050-54-ゲヘナの生徒B" = "どゆこと？"
"211050-55-ショウコ" = "弾薬を試したくなったり、手榴弾が投げたくなったりした時に行ける場所があったら？"
"211050-56-ショウコ" = "しかもそこは、風紀委員会の目を気にする必要がない。"
"211050-57-ゲヘナの生徒B" = "お？"
"211050-58-ゲヘナの生徒B" = "悪くなさそうだけど……。"
"211050-59-ゲヘナの生徒A" = "そういうのって思いついた時にやるのがいいんじゃん。"
"211050-60-ゲヘナの生徒B" = "そうそう。わざわざ行くのはなぁ。"
"211050-61-ショウコ" = "そこが核心です。ちょっとした手間で、もっと大きな面倒を避ける。"
"211050-62-ショウコ" = "風紀委員会の地下牢で1日中座っていたいですか？"
"211050-63-ゲヘナの生徒B" = "それは嫌だけど……。"
"211050-64-マユミ" = "さっすがショウコ！こういうのホント上手だよね。"
"211050-65-マユミ" = "ひらめいた！"
"211050-66-カレン" = "なに？"
"211050-67-マユミ" = "場所を使ってくれたら、回数と時間に応じてポイントが貯まるようにするの！どう？"
"211050-68-カレン" = "ポイント……？"
"211050-69-マユミ" = "食堂とかお店で貯められるやつあるでしょ？あれと同じ！"
"211050-70-マユミ" = "使えば使うほど貯まって、色んな物に交換できたり、なんか特典が付いたり！"
"211050-71-カレン" = "……それ、うちらで管理できる？"
"211050-72-マユミ" = "……。"
"211050-73-マユミ" = "ショウコ！！"
"211050-74" = "[s] \"ノープラン！\""
"211050-75-ショウコ" = "ポイントを各生徒に紐づけるなら、個人情報が必要になる……#nつまり、体よく収集できて都合がいい……。"
"211050-76-ショウコ" = "統制としての意味合いも強くなりますね。"
"211050-77-カレン" = "個人情報なんて何に使うの？"
"211050-78-ショウコ" = "……制度は悪くありません。一考の価値はあるでしょう。"
"211050-79-マユミ" = "私もポイント欲しさにお店行ったりするし！絶対効果あるって！"
"211050-80-カレン" = "まあ、やるならいいんじゃない？損するような話でもないし。"
"211050-81-マユミ" = "せっかくなら自治区内のお店と提携して、ポイントを使えるようにしましょう。"
"211050-82-マユミ" = "そんなことまでできるの！？"
"211050-83-マユミ" = "ここにいらっしゃる方をお忘れですか？"
"211050-84-マユミ" = "そっか！先生がいるじゃん！"
"211050-85" = "[s] \"え、私？\""
"211050-86-マユミ" = "手伝ってくださるんですよね？"
"211050-87-マユミ" = "先生の助けを欲している生徒がここにいます。#n見て見ぬふりをなさるおつもりですか？"
"211050-88-マユミ" = "だいじょぶだいじょぶ！よく分かんないけど……名義を貸してもらったり？"
"211050-89-カレン" = "保証人になってもらうとか、担保出してもらうとか！"
"211050-90-ショウコ" = "心配するな。私の名誉にかけて最善を尽くそう。"
"211050-91-ショウコ" = "――と、先生は考えました。"
"211050-92" = "[s1] \"名誉をかけた覚えはないんだけど！\"\n[s2] \"でも、一緒にやってみよっか。\""
"211050-93-カレン" = "やっぱ頼りになる～"
"211050-94-ゲヘナの生徒A" = "シャーレの先生も手伝ってるの？"
"211050-95-ゲヘナの生徒B" = "じゃあ信じていいってことだよね。"
"211050-96-ゲヘナの生徒A" = "んー、つまり……？"
"211050-97-ゲヘナの生徒A" = "暴れ放題で、風紀委員会が来なくて、ポイントも貯まるってこと？"
"211050-98-マユミ" = "その通り！リスクを減らして、リターンは増やす！！"
"211050-99-ゲヘナの生徒B" = "面白そうだね。#nそこって今からでも使えるの？"
"211050-100-マユミ" = "もちろん！気になる人はついて来て！"
"211050-101-ゲヘナの生徒B" = "最高じゃん！テンション上がってきた～！"
"211050-102-ゲヘナの生徒A" = "ま、行くだけ行ってみよっかな！"
"211050-103-カレン" = "思ったより反応いいね！"
"211050-104-ショウコ" = "先生もご一緒にどうですか？現場をお見せしたいですし。"
"211050-105" = "[s] \"私も気になってたんだ。\""
"211050-106-ショウコ" = "では、こちらへ……。"
"211050-107-ゲヘナの生徒A" = "へー、思ったよりちゃんとしてるじゃん？"
"211050-108-ゲヘナの生徒B" = "標的も建物もある！狙いがいあるね。"
"211050-109-ゲヘナの生徒A" = "ね、ね、撃っていい？もう撃っていい？"
"211050-110-ショウコ" = "その前に、学生証を見せてもらえますか？"
"211050-111-ゲヘナの生徒B" = "なんで……？"
"211050-112-ゲヘナの生徒A" = "ってか、そんなのあったっけ。#n持ってる？"
"211050-113-ゲヘナの生徒B" = "え、分かんない。無いとダメ？"
"211050-114-ショウコ" = "……。"
"211050-115-ショウコ" = "想定内ではありますが……では、こちらに学年と名前を書いてください。"
"211050-116-ショウコ" = "おっけー！"
"211050-117-マユミ" = "そんなの聞いて何に使うの？"
"211050-118-マユミ" = "ポイント管理のためです。どう構築するかは未定ですが。"
"211050-119-マユミ" = "それにデータ化しておけば、どの生徒が施設を利用したか、どの時間帯にどれだけ利用されたかも管理しやすくなります。"
"211050-120-マユミ" = "将来的に組織が大きくなったときにも、そのまま資産として活かせるでしょう。"
"211050-121-マユミ" = "たしかに！全然そこまで考えてなかった……。"
"211050-122-カレン" = "やっぱ抜け目ないね～"
"211050-123" = "[s] \"ショウコは賢いね。\""
"211050-124-マユミ" = "ゲヘナの未来を背負っていますから。"
"211050-125-ゲヘナの生徒B" = "はい、書いたよ！もういいよね？"
"211050-126-ゲヘナの生徒B" = "楽しみ～！"
"211050-127-ショウコ" = "2人とも3年生で、お名前は……はい、問題ありません。"
"211050-128-ゲヘナの生徒C" = "あははっ！こんなに撃つの久しぶり！"
"211050-129-ゲヘナの生徒D" = "ね！手榴弾も投げてみようよ！あのドラム缶、先に爆破した方が勝ちね！"
"211050-130-ショウコ" = "みんな喜んでる！"
"211050-131-カレン" = "作り込んだ甲斐があったね。刺さる生徒は多いんじゃない？"
"211050-132-ショウコ" = "撃つ、壊す、破壊する。#n抑圧された本能を解放するストレス発散法ですから。"
"211050-133-ショウコ" = "需要と供給を正しくおさえれば良いわけです。"
"211050-134" = "[s] \"全部いい感じなんだけどさ……。\""
"211050-135" = "[ns] \"これ、許可取ってるよね？\""
"211050-136-マユミ" = "いや？"
"211050-137" = "[s] \"取ってないの！？\""
"211050-138-ショウコ" = "既成事実にしてしまうのが楽だと思いました。"
"211050-139" = "[s3] \"私もよくやるけど……！\"\n[s4] \"でもこういうのは手順を踏んだほうが……。\""
"211050-140-カレン" = "だから先生が必要なんだよ！"
"211050-141-カレン" = "いざ始めたはいいけど、今さら許可取りに行くの、ちょっと気まずくて。"
"211050-142-マユミ" = "でも、集まって暴れてる問題児だと思われたらマズいでしょ？#nここの活動を止められたら意味ないし……。"
"211050-143-マユミ" = "だったら、正式な活動にしちゃえば問題なし！"
"211050-144-マユミ" = "だから、その……。"
"211050-145-マユミ" = "先生もついてきて……！"
"211050-146" = "[s] \"いいよ。\""
"211050-147-カレン" = "……毎回即答だけど、後で困らない？"
"211050-148" = "[s] \"え、背中の冷や汗すっごいよ。\""
"211050-149-カレン" = "やはっ！それでも即答しちゃうんだ。"
"211050-150-カレン" = "生徒を助けるのが先生の本分だから？"
"211050-151-カレン" = "……。"
"211050-152-カレン" = "ふ～ん、みんなが頼るわけだねぇ。"
"211050-153-マユミ" = "説得がんばろー！"
"211050-154-カレン" = "ショウコちゃんが立ててくれる計画、頼りにしてるよ。"
"211050-155-ショウコ" = "細かい段取りはお任せください。"
"211050-156-ショウコ" = "たとえ失敗しても、傷つくのは先生の名誉だけですし。"
"211050-157" = "[s] \"私の名誉って何なんだろうね……。\""
"211050-158-マユミ" = "ほら、ハリーハリー！レッツゴー！"
"211050-159" = "次回;交渉"
