[translation]
"211020-1" = "第2話;ゲヘナ再興委員会"
"211020-2-アコ" = "あなた達は……？"
"211020-3-アコ" = "せんぱぁい、無駄なケンカはやめなって。"
"211020-4-ヒナ" = "あなた達は……？"
"211020-5-カレン" = "名を聞かれたなら――"
"211020-6-カレン" = "教えてしんぜよう！"
"211020-7-カレン" = "ゲヘナの誇りを取り戻し、いま再び栄光の時代を打ち立てる革命の旗手！"
"211020-8-？？？" = "ゲヘナ再興委員会――参上！！"
"211020-9-？？？" = "やはっ、みーんな静かになっちゃった。"
"211020-10-カレン" = "うちは[ruby=みょうらく]明楽[/ruby]カレン。#nゲヘナ再興委員会の委員長補佐だよ。"
"211020-11-？？？" = "騒がしくして申し訳ありません。#nですが、変革とは衝撃が伴うもの――"
"211020-12-ショウコ" = "ゲヘナ再興委員会の書記、[ruby=いがらし]五十嵐[/ruby]ショウコです。"
"211020-13-マユミ" = "そして私が委員長、[ruby=ふりはた]降旗[/ruby]マユミ！よろしくね！"
"211020-14-チナツ" = "再興……ゲヘナを再び強くする、という意味でしょうか？"
"211020-15-マユミ" = "その通り！"
"211020-16-マコト" = "キシシッ！その抱負、実に大胆不敵！気骨のある後輩たちだ。"
"211020-17-マコト" = "だが――聞き捨てならないな。"
"211020-18-マコト" = "ゲヘナは今でも十分に誇り高いのだ。最高と評しても過言ではあるまい。"
"211020-19-マコト" = "……なぜ、[ruby=・]再[/ruby][ruby=・]び[/ruby]と考える？"
"211020-20-カレン" = "それは――"
"211020-21-ショウコ" = "当然――"
"211020-22-マユミ" = "今のゲヘナは偉大じゃないから！"
"211020-23-マコト" = "何だと？"
"211020-24-カレン" = "だからー、今のゲヘナはカッコよくないの。"
"211020-25-マコト" = "戯言を！[ruby=・]マ[/ruby][ruby=・]コ[/ruby][ruby=・]ト[/ruby][ruby=・]様[/ruby][ruby=・]が[/ruby][ruby=・]統[/ruby][ruby=・]べ[/ruby][ruby=・]る[/ruby][ruby=・]ゲ[/ruby][ruby=・]ヘ[/ruby][ruby=・]ナ[/ruby]が偉大ではないと言うのか？"
"211020-26-マコト" = "そう！"
"211020-27-マコト" = "なにぃっ！？"
"211020-28-ショウコ" = "私たちが主張したいのは、まさにその点です。"
"211020-29-ショウコ" = "ゲヘナはキヴォトスの笑い物。問題児の吹き溜まりとしての烙印を押されています。"
"211020-30-ショウコ" = "しかし、かつてのゲヘナは違いました。"
"211020-31-ショウコ" = "野望はキヴォトス全土に広がり、全ての学園がゲヘナを畏れ敬っていたというのに。"
"211020-32-マユミ" = "ゲヘナってだけで、どこに行っても問題児扱い。"
"211020-33-マユミ" = "秩序はない！規律もない！あるのはカオスな校風だけ。"
"211020-34-マユミ" = "ゲヘナがこうなっちゃったのは――"
"211020-35-マユミ" = "マコト議長たちの責任なんだから！！"
"211020-36-イロハ" = "くっ……！"
"211020-37-イロハ" = "それは……。"
"211020-38-ショウコ" = "[ruby=パンデモニウム・ソサエティー]万魔殿。貴女方[/ruby]はゲヘナの代表でありながら、それに相応しい働きをしていません。"
"211020-39-ショウコ" = "生徒の無関心につけこんで、奇怪な政策で予算を浪費するばかり。"
"211020-40-イロハ" = "弁明の余地は……まぁ、ほとんどありませんね。#nですが、たまに、本当にたまにですけど良いこともしてたり――"
"211020-41-マユミ" = "たまにじゃダメなの！いつもじゃなきゃ！"
"211020-42-マユミ" = "見てて思うんだけど、風紀委員会いじめに全力投球してるよね？"
"211020-43-イロハ" = "それはマコト先輩だけです。"
"211020-44-マユミ" = "限られた予算を無駄遣いして、肝心なところへの投資はしない。#nだからゲヘナの競争力は下がりっぱなし！"
"211020-45-マユミ" = "エデン条約の一件以来、トリニティに抗議もしてないよね？"
"211020-46-マコト" = "それはシャーレとの関係を最優先に考慮した――"
"211020-47-マユミ" = "結果として「屈した」ようにしか見えないって言ってるの！"
"211020-48-マユミ" = "それが先輩の言う「器」なの？議長として本当に誇れるの？"
"211020-49-マコト" = "ぐっ……！言わせておけばぬけぬけと……！"
"211020-50-アコ" = "こんなにズバッと言ってくれる人がいるなんて……！"
"211020-51-ショウコ" = "いえ。貴女方も同じですよ。"
"211020-52-アコ" = "はい？"
"211020-53-マユミ" = "風紀委員会は、ゲヘナの規律と風紀を守るためにいるんだよね？"
"211020-54-マユミ" = "なのに、「面倒なやつら」くらいにしか思われてない。#nあ、委員長だけは違うか。"
"211020-55-イオリ" = "何だと！？"
"211020-56-マユミ" = "でも、私はそうは思ってない。"
"211020-57-イオリ" = "……え？"
"211020-58-マユミ" = "委員長がいなくたって、風紀委員会はゲヘナ最強の武力集団だよ。"
"211020-59-マユミ" = "だけど！"
"211020-60-マユミ" = "力があるのに、問題児を殴り飛ばしたり、万魔殿とケンカしてるだけだよね？"
"211020-61-イオリ" = "違っ……！まずは言葉で注意して、実力行使はその後だ！"
"211020-62-イオリ" = "や、そういう話じゃなくて。"
"211020-63-イオリ" = "ゲヘナにはとんでもない潜在能力がある。#nなのに一つにまとまらないのは、風紀委員会にも責任があるっしょ。"
"211020-64-イオリ" = "風紀委員会は何がしたいわけ？"
"211020-65-イオリ" = "今みたいな、ゆる～い規律と統制？#nそれとも……風紀委員ごっこしてるだけ？"
"211020-66-イオリ" = "……ごっこ？"
"211020-67-マユミ" = "言い方はちょっとあれだけど、間違ってはないよね。#nだって風紀委員会は、な～んにも決めきれてない！"
"211020-68-マユミ" = "いっつも曖昧。なんでもっと踏み込まないの？"
"211020-69-ヒナ" = "知りたいなら答えてあげる。"
"211020-70-イオリ" = "い、委員長……！"
"211020-71-イオリ" = "委員長……！"
"211020-72-ヒナ" = "曖昧……ね。"
"211020-73-ヒナ" = "そう思いたいのならそれでいいわ。"
"211020-74-ヒナ" = "あなたたちは規律と統制を求めているようだけど。"
"211020-75-ヒナ" = "それは、私たちが目指すゲヘナじゃない。"
"211020-76-ヒナ" = "私たちが目指すのは、自由なゲヘナだから。"
"211020-77-ショウコ" = "耳触りの良い言葉ですね。#n自由が常に良い方向に働くと、本気で信じているような口ぶり。"
"211020-78-ショウコ" = "今のゲヘナでは「放縦」に変質しているというのに。"
"211020-79-ヒナ" = "だからこそ、線を引くために私たちがいる。"
"211020-80-ヒナ" = "越えたいのなら──相手になるわよ。"
"211020-81-ショウコ" = "……。"
"211020-82-マコト" = "ふん……口だけは一丁前だな。"
"211020-83-ヒナ" = "ともあれ結論としては――"
"211020-84-ショウコ" = "風紀委員会は曖昧な立場を堅持する、と。そう解釈して良いのですね？"
"211020-85-ヒナ" = "ええ、構わないわ。"
"211020-86-ショウコ" = "だそうです、委員長。"
"211020-87-マユミ" = "らしいね。"
"211020-88-マユミ" = "万魔殿の考えも！風紀委員会の考えも！よ～く分かった！！"
"211020-89-マユミ" = "つまり、誰もゲヘナをまとめる気がないってことだよね。"
"211020-90-マユミ" = "なら話は早い！あとは実行あるのみ！！"
"211020-91-アコ" = "何をするつもりですか？"
"211020-92-マユミ" = "私たちは「一つになったゲヘナ」を作るために――"
"211020-93-マユミ" = "いろいろ、いーっぱいやるよ！！"
"211020-94-イオリ" = "……は？"
"211020-95-ショウコ" = "細かいことは苦手だから、具体的なことはまだ分かんないけど――"
"211020-96-ショウコ" = "私たちがやること、ちゃんと見ててよね！"
"211020-97-ショウコ" = "ゲヘナの変化は今日、この瞬間から始まるんだよ！！"
"211020-98-ヒナ" = "……元気のいい後輩ね。"
"211020-99-ヒナ" = "威勢はいいが、徒労に終わるだろうな。"
"211020-100-ヒナ" = "年季も経験も足りていないのだ。#nどれだけ足掻こうと、このマコト様の天下にはヒビ1つ入らない！キシシッ！"
"211020-101-ゲヘナの生徒A" = "な……なんか面白くなってきた！"
"211020-102" = "次回;ゲヘナを偉大に！"
