[translation]
"211070-1" = "第7話;カレン"
"211070-2-スケバンA" = "やぁやぁ。こ～ん～に～ち～は～？"
"211070-3-ゲヘナの生徒" = "無視ってのはひどいじゃんよ。"
"211070-4-ゲヘナの生徒" = "……何か用？"
"211070-5-スケバンA" = "いや～あたし、ゲヘナの奴が大っ嫌いでさ。"
"211070-6-スケバンA" = "もう見るだけでアレルギー出んの。"
"211070-7-スケバンA" = "で、お前を見ちゃったじゃん？#nだから……ほらここ、蕁麻疹。"
"211070-8-スケバンA" = "……あれ、消えてない？"
"211070-9-スケバンA" = "ちっ、水性かよ。もっかいペン貸して。"
"211070-10-スケバンA" = "ほら、見ろ。お前のせいで腕にホクロが7個もできた。#nこれ、どう責任取ってくれんだ？"
"211070-11-ゲヘナの生徒" = "いま自分で描いたよね！？"
"211070-12-スケバンB" = "うるせぇな！つべこべ言わずに慰謝料払え！"
"211070-13-ゲヘナの生徒" = "無茶苦茶な……。"
"211070-14-スケバンB" = "さっさと財布出すのが身のためだと思うぜ？"
"211070-15-ゲヘナの生徒" = "うぅ……あんた達……。"
"211070-16-スケバンA" = "はーっ、ゲヘナったって1人で歩いてりゃ楽な獲物だぜ。"
"211070-17-スケバンB" = "結束力はねぇし、風紀委員会は自治区内のことで手一杯。"
"211070-18-スケバンB" = "つまり、誰もあんたを助けない！"
"211070-19" = "[ns] 前へ出る。"
"211070-20" = "[ns] \"ん……？あれは……。\""
"211070-21-？？？" = "やはっ！マジうけんね。"
"211070-22-スケバンB" = "あぁん？今なんつった？"
"211070-23-スケバンB" = "誰だテメェ？"
"211070-24-スケバンB" = "なんだ、またゲヘナか？"
"211070-25-スケバンB" = "そう。ゲヘナ。"
"211070-26-カレン" = "だからさ――"
"211070-27-カレン" = "うちの生徒から手ぇ離して、とっとと消えてくれる？"
"211070-28" = "[ruby=みょうらく]明楽[/ruby]カレン"
"211070-29" = "ゲヘナ再興委員会の委員長補佐"
"211070-30" = "見た目に反して短気で、暴力に一切のためらいがない"
"211070-31-スケバンB" = "あぁん？"
"211070-32-スケバンA" = "なになに、あんた何様？#n腕章……はつけてねぇし、風紀委員会じゃなさそうだな。"
"211070-33-スケバンA" = "てこたぁ、お前の[ruby=ダチ]友達[/ruby]か？"
"211070-34-ゲヘナの生徒" = "えっ、違っ……別に、そういうんじゃ――"
"211070-35-ゲヘナの生徒" = "今から友達だから。よろしく。"
"211070-36-ゲヘナの生徒" = "えぇっ……。"
"211070-37-スケバンA" = "ま、なんでもいいけどよ。1人で何ができる。#n世の中の理不尽ってやつを教えてやるよ！"
"211070-38-スケバンA" = "キヴォトスの苦みと冷たさ体験コースだぁっ！"
"211070-39" = "[ns] \"ちょ、ちょっと……！\""
"211070-40-スケバンA" = "ぐはっ！こ、この……！"
"211070-41-スケバンA" = "うぐっ！痛っ――！！"
"211070-42-スケバンA" = "お、覚えてやがれ……！"
"211070-43-ゲヘナの生徒" = "一瞬で終わった……。"
"211070-44-カレン" = "だいじょぶ？"
"211070-45-ゲヘナの生徒" = "え、あ……うん。"
"211070-46-カレン" = "固い固い。もっとフランクでいいって。#n怪我はしてなさそうだし、取られたものもなさそうだね。"
"211070-47-ゲヘナの生徒" = "ホントにありがとね。助けてくれなかったらどうなってたか……。"
"211070-48-カレン" = "さっき言ったっしょ？もう友達って。#nうちの友達いじめるやつは絶対許さないから。"
"211070-49-ゲヘナの生徒" = "かっこいい……。"
"211070-50-カレン" = "あ、全然話変わるんだけどさ、ゲヘナ再興委員会って知ってる？"
"211070-51-ゲヘナの生徒" = "……聞いたことあるかも。なんか最近有名だよね？"
"211070-52-カレン" = "うち、そこ入ってるんだ。"
"211070-53-ゲヘナの生徒" = "え、マジ？私、部活とか入ってなくてさ。"
"211070-54-カレン" = "やはっ、じゃあ入っちゃいなよ！"
"211070-55-カレン" = "はい、うちのモモトーク。何かあったら連絡ちょうだい。"
"211070-56-カレン" = "うちらは「外」でもゲヘナの生徒を守ってるから。風紀委員会とは違ってね。"
"211070-57-ゲヘナの生徒" = "めっちゃカッコいいじゃん……。"
"211070-58-ゲヘナの生徒" = "入会届だしちゃおっかな！"
"211070-59-カレン" = "ゲヘナを再び偉大に！"
"211070-60-ゲヘナの生徒" = "ゲヘナを再び偉大に！"
"211070-61-カレン" = "やはっ、今日も一件落着！"
"211070-62-カレン" = "あれ、先生？"
"211070-63" = "[s] \"やぁ。\""
"211070-64-カレン" = "わっ、本物だ！"
"211070-65-カレン" = "何してんの？ってか、うちの活躍見てた？"
"211070-66" = "[s1] \"かっこよかったよ。\"\n[s2] \"友達を守ったんだね。\""
"211070-67-カレン" = "マジ？見てくれてたんだ！"
"211070-68-カレン" = "えー、ヤバ。嬉しいかも。"
"211070-69-カレン" = "じゃ、なでなで！良いことしたら褒められるのが当然でしょ？"
"211070-70" = "[s] 撫でる。"
"211070-71-カレン" = "やはっ。"
"211070-72-カレン" = "ん～？いつもこういうことしてるのかって？"
"211070-73-カレン" = "まあ、そこそこ？"
"211070-74-カレン" = "自治区の外だとたまにあるんだよね。風紀委員会は中だけだから。"
"211070-75-カレン" = "1人で歩いてるゲヘナ生は狙われやすいんだよ。#nや、それはどの学園も似たようなもんか。"
"211070-76-カレン" = "でも、ゲヘナの生徒に手ぇ出したやつは絶対逃がさない。"
"211070-77-カレン" = "え？いつでも呼んでね、って……先生を？"
"211070-78-カレン" = "やっさし～そういうこと言われたの久しぶりだなぁ。"
"211070-79-カレン" = "だけどねぇ、うち、けっこう強いんだよ？#n数が多くても大抵はなんとかなるし。"
"211070-80-カレン" = "負けそうだなって思ったら、一回引いてから奇襲かければオッケー。"
"211070-81-カレン" = "てか、危ないのは先生のほうじゃない？#nさっきみたいに、ここの治安結構ガタガタだから。"
"211070-82-カレン" = "せっかくだし、先生の用事が終わるまでエスコートしてあげる！"
"211070-83-カレン" = "あ、気にしないで。やることなくて暇だったから。"
"211070-84" = "（道中、他にも何度か脅されたが……）"
"211070-85" = "（カレンが撃退してくれた）"
"211070-86" = "[ns] \"今日はありがとね。\""
"211070-87-カレン" = "なんのなんの。力になれたならよかったよ。"
"211070-88-カレン" = "一緒にあちこち回れて、うちも楽しかったし。"
"211070-89-カレン" = "でも先生、やっぱ絡まれやすいタイプだよね。今日だけでも狙われ過ぎ。"
"211070-90" = "[s] \"困っちゃうよね……。\""
"211070-91-カレン" = "今度からは遠慮なく呼んでいいからね？"
"211070-92-カレン" = "あ、モモトーク教えとこっか。メッセでも電話でも、好きなほうで～"
"211070-93-カレン" = "よし、登録完了！"
"211070-94-カレン" = "なんか繋がった感じしていいよね。"
"211070-95-カレン" = "うち、大人とこういうことするの初めてでさ。やはっ、めっちゃ楽しい。"
"211070-96-カレン" = "あ、そろそろ戻らないと。"
"211070-97-カレン" = "最後に、何か聞きたいこととかある？"
"211070-98-カレン" = "今日は出血大サービス。何でも答えたげるよ？"
"211070-99" = "[ns] \"カレンはどうしてゲヘナ再興委員会の活動をしてるの？\""
"211070-100-カレン" = "おっ、予想外の質問。"
"211070-101-カレン" = "うーん……。"
"211070-102-カレン" = "ゲヘナが好きだから？"
"211070-103-カレン" = "たぶんそれが一番！"
"211070-104-カレン" = "みんなと一緒に何かやるのも楽しいし。#n先生も見て分かったでしょ？うちのメンツ、みんな面白いからさ。"
"211070-105-カレン" = "んー？ゲヘナが好きな理由？"
"211070-106-カレン" = "……。"
"211070-107-カレン" = "うーん……うぅ～ん……。"
"211070-108-カレン" = "難しいなぁ。いろいろあるとは思うんだよね。"
"211070-109-カレン" = "まず……後腐れのない空気？っていうの？"
"211070-110-カレン" = "偽善ってマジで嫌いなんだよね。#n表じゃニコニコしておいて、裏でごちゃごちゃ言うとか。#nああいうの、ホント無理。"
"211070-111-カレン" = "でも、うちってそうじゃないでしょ？#nやる時は派手にやるけどそれっきり。表も裏もない。"
"211070-112-カレン" = "あとは～好き勝手していい感じかな。自由な感じ。あれが好き。"
"211070-113-カレン" = "委員会の方向性とちょっと違くないかって？"
"211070-114-カレン" = "それねー、たしかに。ゲヘナに秩序と統制を、ってね。"
"211070-115-カレン" = "こう言うと聞こえ悪いかもだけど……それ、[ruby=うちのブレイン]ショウコちゃん[/ruby]の受け売りなの。"
"211070-116-カレン" = "でも……やっぱマユミちゃんの見てる景色が気になるからかな。#nうちもそれを見たいから一緒に走ってるんだ。"
"211070-117-カレン" = "めちゃくちゃなゲヘナも嫌いじゃないけどさ。"
"211070-118-カレン" = "マユミちゃんって、うちが知ってる中で1番ゲヘナを愛してるから！"
"211070-119-カレン" = "そんなマユミちゃんが作りたい学園ってどんな場所なんだろう、って。"
"211070-120-カレン" = "突っ走って事故るタイプだけど、そこが良いっていうか。"
"211070-121-カレン" = "ショウコちゃんはたまに変なこと言うけど、ゲヘナ好きなのは同じだし。"
"211070-122-カレン" = "見てみたくない？#nみんなが一つになったゲヘナ。"
"211070-123-カレン" = "バラバラじゃなくて、みんなが同じ方向を見てるの。"
"211070-124-カレン" = "どんな感じかは全然想像つかないけどさ。"
"211070-125-カレン" = "やはっ、それかな。うちが再興委員会で頑張ってる理由。"
"211070-126-カレン" = "どう？ちゃんと答えになってた？#nまとまってなかったらごめんね。勉強苦手なんだ。"
"211070-127" = "[s] \"大丈夫、十分伝わったよ。\""
"211070-128-カレン" = "そっか。よかった。#n……あ！あとこれも言わなきゃ。"
"211070-129-カレン" = "手伝ってくれてありがとね、先生。"
"211070-130-カレン" = "うちらだけじゃ、きっともっと大変だったと思う。#n先生のおかげでスムーズに進んでる。"
"211070-131-カレン" = "最近は入会してくる生徒も増えてきたんだよ。"
"211070-132-カレン" = "だから、これからもよろしくね！"
"211070-133" = "（カレンのおかげで、安全に予定を終えられた）"
"211070-134" = "（ゲヘナへの想いも「本気」だと感じた）"
"211070-135" = "次回;トリガー・ハッピー・ゾーン"
