[translation]
"211120-1" = "第12話;お悩み解決"
"211120-2" = "ゲヘナ再興委員会"
"211120-3-マユミ" = "それでは――"
"211120-4-マユミ" = "第28回「ゲヘナを再び偉大にするための会議」を開始しま～す！"
"211120-5" = "[s] \"わ～い！\""
"211120-6-カレン" = "もう28回なんだ。うちらも結構やってきたんだね。"
"211120-7-ショウコ" = "ほとんど雑談でしたけどね。"
"211120-8-ショウコ" = "中身のない議事録を書かされる身にもなって欲しいのですが。"
"211120-9-カレン" = "ちょい。ショウコちゃん、そのお菓子2袋目じゃない？#nあたしまだ1個も食べてないんだけど！"
"211120-10-ショウコ" = "書記の権限で私が全部食べます。"
"211120-11-カレン" = "書記は力なく踏まれるだけの存在だ、って言ってなかったっけ。"
"211120-12-ショウコ" = "お菓子に関しては無敵です。石をも砕くチョキみたいなものですよ。"
"211120-13-カレン" = "じゃあ本当に砕けるか試してみよっか？"
"211120-14-マユミ" = "はいはい、注目！"
"211120-15-ショウコ" = "は～い。"
"211120-16-ショウコ" = "ふぁ～い。"
"211120-17-カレン" = "喋るなら飲み込んでからにしなって。"
"211120-18-マユミ" = "私が持ってきた議題は――"
"211120-19-マユミ" = "「私たちの進むべき道」だよ！"
"211120-20-ショウコ" = "いつも通り、大仰ですね。"
"211120-21-マユミ" = "そう！私たち、大仰なのが問題だと思うの！"
"211120-22-マユミ" = "私たちの活動って、ひとまずは順調だと思うんだ。"
"211120-23-マユミ" = "再興委員会を知ってる生徒も増えたし、プロジェクトの参加者も集まってきた。"
"211120-24-カレン" = "みんな頑張れて偉い偉い。"
"211120-25-マユミ" = "これ自体はいいことなんだけどさ。"
"211120-26-マユミ" = "でも思ったんだ。本当にこれだけでいいのかなって。"
"211120-27-ショウコ" = "また思いつきですか……。"
"211120-28-マユミ" = "私たちはゲヘナを根本から変えようとしてきたじゃん？"
"211120-29-マユミ" = "だけど本当に大事なのは、もっと些細なところなんじゃない？"
"211120-30-カレン" = "どゆこと？"
"211120-31-マユミ" = "えっと、つまり……。"
"211120-32-マユミ" = "例えばさ、みんな色んな悩みがあるじゃん？#n感受性も豊かだしさ。先生もそうだし。"
"211120-33" = "[s] \"呼んだ？\""
"211120-34-マユミ" = "なのにゲヘナには、悩みをちゃんと受け止めてあげられる場所も組織も無いの！"
"211120-35-マユミ" = "万魔殿は話にならないし、風紀委員会は治安維持組織だから役割が違う。"
"211120-36-マユミ" = "……じゃあ、誰が立ち上がるべきだと思う？"
"211120-37-マユミ" = "そう！！[ruby=私たち]ゲヘナ再興委員会[/ruby]！！"
"211120-38-ショウコ" = "ってことは……。"
"211120-39-カレン" = "うちらでお悩みを解決してあげようってこと？"
"211120-40-ショウコ" = "お悩み窓口みたいな部署を、兼任しようというわけですね。"
"211120-41-マユミ" = "そう！千里の道も一歩から――偉大なゲヘナもお悩み相談から、ってね！#n……どうかな？"
"211120-42-カレン" = "悪くないアプローチです。巨大な秩序は些細な規則によって成り立つのですから。#n統制可能な小単位から管理するのは、効率的な行政の基本です。"
"211120-43-カレン" = "うちも賛成。何でもやってみる価値はあるでしょ。"
"211120-44-マユミ" = "もしかしたら先生の役割なのかもだけど、今回は任せてみて欲しいんだ。#n私たちの実力を見せてあげる！"
"211120-45" = "[s] \"じゃあ私は何のためにここに……？\""
"211120-46-マユミ" = "応援！私たちを見守って、応援して！"
"211120-47-カレン" = "言うなればお守りです。"
"211120-48-カレン" = "いるだけで助かるーってやつ！やはっ！"
"211120-49-ゲヘナの生徒A" = "最近の悩み？"
"211120-50-マユミ" = "つらいこととか、学園に対する不満とか。"
"211120-51-マユミ" = "なんか胸がモヤモヤする……とかでも大丈夫！カウンセリングもやってるから！"
"211120-52-ゲヘナの生徒A" = "特には……ないかな？"
"211120-53-マユミ" = "えぇっ！？よーく思い出してみてよ！何かあるでしょ？ストレス溜まってることとか！"
"211120-54-ゲヘナの生徒A" = "えっと……この状況、かな……？"
"211120-55-マユミ" = "そっか……うん、何もないなら良かった。"
"211120-56-ゲヘナの生徒A" = "う、うん。じゃあ私もう行くね。"
"211120-57-マユミ" = "だいぶ声かけたのに、みんなあんまり悩みないんだね。"
"211120-58-ショウコ" = "ある意味ゲヘナらしいかも。"
"211120-59-ショウコ" = "私たちの活動で、生徒のストレス指数が下がっているのも一因でしょうね。"
"211120-60-マユミ" = "自分たちの成果が足を引っ張ってくるなんて……！"
"211120-61-ショウコ" = "なに言ってるのさ。悩みがないならいいことでしょ。"
"211120-62-ショウコ" = "「生徒の悩みを解決する」という目的に囚われすぎて判断力が落ちていますね。#n哀れで見ていられません。"
"211120-63-マユミ" = "あ～糖分切れてきた。ショウコ、お菓子ちょうだい。"
"211120-64-ショウコ" = "最後の1個なので嫌です。"
"211120-65-マユミ" = "あとで倍にして返すから！"
"211120-66-マユミ" = "半分くれたっていいじゃん！悩まないでよ！"
"211120-67-ショウコ" = "私も今食べたいんです！"
"211120-68-ショウコ" = "……あれ？#nいま我慢すれば、後で倍の喜びになって返ってくる……？"
"211120-69-ショウコ" = "あ、これ、あれですね。マシュマロ実験。"
"211120-70-ショウコ" = "……いいでしょう。委員長に差し上げます。"
"211120-71-マユミ" = "うーん。"
"211120-72-マユミ" = "踏み倒すか。"
"211120-73-ゲヘナの生徒B" = "ねえ、悩み相談ってまだやってる？"
"211120-74-マユミ" = "あい！やってうよ！"
"211120-75" = "[s] \"飲み込んでから喋ろうね。\""
"211120-76-ショウコ" = "ちゃんと倍にして返してくれるんですよね！？"
"211120-77-カレン" = "も～、しっかりしてよ……。"
"211120-78-カレン" = "うるさくてごめんね。何かあった？"
"211120-79-ゲヘナの生徒B" = "あ、うん……。"
"211120-80-ゲヘナの生徒B" = "えっと……うちのクラスで、変な声を聞いたって子が何人かいるんだ。"
"211120-81" = "どんな声？"
"211120-82-ゲヘナの生徒B" = "それがゾッとするような話なんだけど……。"
"211120-83-ゲヘナの生徒" = "はっ！？うわ……授業終わってんじゃん。誰か起こしてくれてもいいのに……って。#nあれ？みんなどこ行ったんだろ？"
"211120-84-ゲヘナの生徒" = "はぁ……とっとと帰ろ……。"
"211120-85-？？？" = "――つ。"
"211120-86-？？？" = "……。"
"211120-87-ゲヘナの生徒" = "気のせいかな……。"
"211120-88-？？？" = "――じょ。"
"211120-89-ゲヘナの生徒" = "気のせいじゃない！？"
"211120-90-ゲヘナの生徒" = "教室、私しかいないのに……！"
"211120-91-ゲヘナの生徒" = "お助けー！"
"211120-92-ゲヘナの生徒B" = "……って話。"
"211120-93-ショウコ" = "もしかしなくても幽霊騒ぎ！？"
"211120-94-カレン" = "いや、気のせいでしょ。そういうの、わりとあるじゃん。"
"211120-95-ゲヘナの生徒B" = "違うんだって！声を聞いた生徒、結構多いみたいで。"
"211120-96-ショウコ" = "声を聞いた場所は分かりますか？"
"211120-97-ゲヘナの生徒B" = "もちろん！"
"211120-98" = "噂の場所"
"211120-99-マユミ" = "この教室だね。"
"211120-100-カレン" = "見た感じ変なところはなさそうだけど……。"
"211120-101-ショウコ" = "……。"
"211120-102-マユミ" = "何それ。"
"211120-103-ショウコ" = "電磁波を測定する装置です。"
"211120-104-マユミ" = "何に使うの？"
"211120-105-ショウコ" = "妙な音の発生源を探ります。#n設備不良によるノイズが原因なら、これで特定できるはずです。"
"211120-106-マユミ" = "ロマンがないな～、幽霊の方が面白くない？"
"211120-107-ショウコ" = "幽霊は「一つになったゲヘナ」には不要ですし、そもそも存在しません。"
"211120-108-カレン" = "ん？本物見たことあるよ？"
"211120-109-ショウコ" = "……嘘です。"
"211120-110-カレン" = "ほんとだってば。マジで出たもん。"
"211120-111-ショウコ" = "ゆ、幽霊なんて……いるわけがありません。#n私は電磁波を追いますので。"
"211120-112" = "なに、幽霊怖いの～？"
"211120-113-ショウコ" = "うるさいです。そんなことより、お菓子を倍にして返すの忘れないでくださいね。"
"211120-114-ショウコ" = "……こっちで信号が強くなっています。"
"211120-115-マユミ" = "幽霊が近くにいると電気製品が変になるっていうよね。"
"211120-116-マユミ" = "電気がチカチカしたり、ノイズが走ったりするんだっけ。"
"211120-117-カレン" = "そうそう。まさに今みたいに……。"
"211120-118-ショウコ" = "ふん、子供じみたイタズラですね。そんなもので――"
"211120-119-カレン" = "わっ！！！！！！！"
"211120-120-カレン" = "やはっ！びっくりした？固まっちゃってたよ～？"
"211120-121-ショウコ" = "やめてくださいって言ったじゃないですか！！"
"211120-122-マユミ" = "うわー！こんなに怒るショウコ初めて見た！"
"211120-123-カレン" = "やはっ、幽霊怖いんだ～ショウコちゃん、か～わいい～！"
"211120-124-ショウコ" = "怖がってませんけど！？#n大きい音にびっくりしただけですから！"
"211120-125-カレン" = "そだねー驚いただけだもんね～！"
"211120-126-ショウコ" = "うぅ……。"
"211120-127-？？？" = "――とう。"
"211120-128-マユミ" = "今……聞こえた？"
"211120-129" = "[s] \"何か、音が……。\""
"211120-130-カレン" = "うちも聞こえた……。"
"211120-131-マユミ" = "ここ、私たちしかいないのに……ほ、本当に幽霊かな……？"
"211120-132-ショウコ" = "……。"
"211120-133-ショウコ" = "こちらで反応が強くなりました。"
"211120-134-カレン" = "ショウコ……全然怖がってないね。"
"211120-135-カレン" = "さっきまであんなにピリピリしてたのに。"
"211120-136-ショウコ" = "しーっ、静かに。"
"211120-137-ショウコ" = "強い反応は……この壁の向こう……？"
"211120-138-ショウコ" = "それと、さっき聞こえた単語は、たしか……。"
"211120-139-マユミ" = "あっ、どこ行くの？"
"211120-140-カレン" = "何か分かったっぽくない？"
"211120-141-ショウコ" = "ノイズの発生源は……。"
"211120-142-カレン" = "ここ……？"
"211120-143-カレン" = "放送室だね。"
"211120-144-ショウコ" = "……。"
"211120-145-マユミ" = "なんか、あんま使われてる感じなくない？"
"211120-146-マユミ" = "そういえば。校内放送もしばらくお休みだし。"
"211120-147-ショウコ" = "この中に何かあるのは間違いありません。"
"211120-148-ショウコ" = "ですが……さすがに鍵がかかってますか。"
"211120-149-マユミ" = "さっきの変な声はここから漏れてるってこと？"
"211120-150-カレン" = "じゃあ確かめてみよっか！"
"211120-151-マユミ" = "どうやって？"
"211120-152-カレン" = "え、ドアぶっ壊して──"
"211120-153-ショウコ" = "ダメです！放送室の設備が壊れるかもしれません。暴力は禁止です。"
"211120-154-マユミ" = "えー。"
"211120-155-ショウコ" = "せっかく見つけた手がかりが台無しになったら困るでしょう？"
"211120-156" = "それに、私たちがどんな委員会だったか忘れた？"
"211120-157-マユミ" = "むやみに壊したり、迷惑をかける行為はしない。#nまずは自分たちが有言実行しないと。"
"211120-158-カレン" = "そうだった……ごめん。"
"211120-159-カレン" = "先生の前で恥ずいことしちゃった。"
"211120-160" = "[s] \"よしよし、我慢できて偉いね。\""
"211120-161-マユミ" = "入れないのはどうしよっか。"
"211120-162-マユミ" = "記念すべき第1号の依頼なのに「解決できませんでした」とは言えないし……。"
"211120-163-カレン" = "「原因は放送室でした～」って報告すればいいんじゃない？"
"211120-164-ショウコ" = "依頼人の望む結果と言えるかは微妙ですが……手がかりは見つかりましたね。"
"211120-165" = "[ns1] \"そういえば、なんか……。\"\n[ns2] \"似たような話を聞いた覚えが……。\""
"211120-166-マユミ" = "えっ、どこで聞いたの？"
"211120-167" = "[s] \"えっとね……。\""
"211120-168" = "次回;森の中の木"
