[translation]
"1602006-1" = "ある狙撃手の迷彩服"
"1602006-2" = "コーギータウン・入口"
"1602006-3-オトギ" = "あ、先生。こっちこっち。\r\n"
"1602006-4-オトギ" = "外で待ち合わせするのは初めてだからか、なんか不思議な気分。"
"1602006-5-オトギ" = "せっかくの休み、邪魔しちゃってない？"
"1602006-6-オトギ" = "先生、今週はずっと忙しかったみたいだし……。"
"1602006-7" = "[s1] \"ちょうど私もショッピングをしたい気分だから。\"\r\n[s2] \"SRTの迷彩服が、どんなものかも気になるし。\""
"1602006-8-オトギ" = "……あれ？見たことなかったっけ？"
"1602006-9" = "[s3] \"他の生徒が着ている迷彩服は、見たことはあるけど――\"\r\n[s4] \"迷彩服専門店は、一度も見たことがなくて。\""
"1602006-10-オトギ" = "あ、でも……今から行くのって――"
"1602006-11-オトギ" = "ミリタリー専門じゃなくて普通のアパレルショップだよ。"
"1602006-12-オトギ" = "街中での「迷彩服」は、普通の服を改造するほうが効果的なんだぁ。"
"1602006-13-オトギ" = "この前の作戦でもらった商品券使おうと思って。"
"1602006-14-オトギ" = "ふふ。幅広く使える色は、どれかな～"
"1602006-15" = "[s5] \"迷彩服と言って思い出す、あのモジャモジャの……。\"\r\n[s6] \"そういう服も、街中で使えるの？\""
"1602006-16-オトギ" = "あぁ、ギリースーツのこと？"
"1602006-17-オトギ" = "あれは網目の骨組みがあるから、茂みの中の作戦では緑や茶色の布や落ち葉を編みこんだり――"
"1602006-18-オトギ" = "原色の広告看板が多い街中の作戦では、あえて派手な色の布を使ったり。"
"1602006-19-オトギ" = "人混みでも目立たないように、使わなくなった制服で作ったりもするけど……。"
"1602006-20-オトギ" = "学園が閉鎖された今、制服って貴重だからなぁ……。"
"1602006-21-オトギ" = "ああ、しばらくギリースーツ作ってないかも。"
"1602006-22" = "[s] \"……結構手間がかかるんだね。\""
"1602006-23-オトギ" = "そりゃそうだよ。作戦の準備は、いつでも完璧じゃなきゃね。"
"1602006-24-オトギ" = "んじゃ見に行こっか。"
"1602006-25-オトギ" = "うーん、この服は色が派手過ぎる。"
"1602006-26-オトギ" = "こっちは柄が目立つし……。"
"1602006-27-オトギ" = "お、これはいいかも。髪の色にぴったり。"
"1602006-28-オトギ" = "どう？似合う？"
"1602006-29" = "[s7] \"うん……。\"\r\n[s8] \"いいね……。\""
"1602006-30-オトギ" = "え？リアクション、薄っ。"
"1602006-31-オトギ" = "……やっぱり、こういうフワフワした服は、私に合わないかなぁ。\r\n"
"1602006-32-オトギ" = "しょうがない。無難なデニムかコーデュロイで――"
"1602006-33" = "[s9] \"そ、そういう意味じゃないんだ！\"\r\n[s10] \"本当によく似合ってると思ったんだけど……。\""
"1602006-34-オトギ" = "なら、どうして？"
"1602006-35" = "[s] \"これで迷彩服を作るには、もったいないよ。\""
"1602006-36-オトギ" = "え？"
"1602006-37-オトギ" = "それって、どういう……。"
"1602006-38-オトギ" = "先生、もしかして勘違いしてる？"
"1602006-39-オトギ" = "今日買いに来た「迷彩服」は、潜入の時に着る私服だよ。"
"1602006-40-オトギ" = "見慣れない制服で歩いてたら目立つでしょ？"
"1602006-41-オトギ" = "そういう意味での「迷彩服」で、存在感ゼロレベルの偽装じゃないよ。"
"1602006-42-オトギ" = "いくら私が作戦重視だからって、私服を破いたりしないよ。"
"1602006-43" = "[ns] \"勘違いなら良かった……。\""
"1602006-44" = "[ns11] \"本当に引き裂く生地が必要なら――\"\n[ns12] \"着なくなった私の服をあげようかなって思って。\""
"1602006-45-オトギ" = "あ、それはいいアイデアかも。"
"1602006-46-オトギ" = "さっき言ったこと、取り消してもいい？"
"1602006-47" = "[s] \"ダメです。\""
"1602006-48-オトギ" = "ちぇ、冗談なのに。"
"1602006-49-オトギ" = "んで、この服はどう？"
"1602006-50" = "[s] \"私は、さっき着ていたほうが好きかな。\""
"1602006-51-オトギ" = "へぇ、意外と好みがはっきりしてるんだねぇ。"
"1602006-52-オトギ" = "オッケー。じゃあ、こっち着よ～"
"1602006-53" = "（その後、オトギと一緒にいろんな服を試しながら楽しい時間を過ごした）"
