[translation]
"10024090-1" = "第9話;[ruby=かいじゃきせい]改邪帰正[/ruby]"
"10024090-2" = "玄龍門・内部"
"10024090-3-玄龍門の構成員A" = "……。"
"10024090-4-玄龍門の構成員B" = "……。"
"10024090-5-ルミ" = "さて、真相は話した通りだよ。"
"10024090-6-レイジョ" = "密輸に関わった構成員には、玄龍門が厳正な処罰を与えると信じて良いのですよね。"
"10024090-7-玄龍門の幹部A" = "そ、それじゃあ事件は解決したわけだ？"
"10024090-8-玄龍門の幹部A" = "良かったじゃないか。#nこれで玄武商会の無実は証明され――"
"10024090-9-ルミ" = "言うことはそれだけ？"
"10024090-10-レイジョ" = "玄龍門には、失望せざるを得ませんね。"
"10024090-11" = "[s] \"確証もなく、玄武商会を問い詰めたのは……\""
"10024090-12-玄龍門の幹部A" = "……これ以上、話すことはない。#n個人の問題を我々に持ち出されても困るな。"
"10024090-13-玄龍門の幹部A" = "お前たちは一部の構成員が行った事を玄龍門全体の責任だと言いたいのか？"
"10024090-14-玄龍門の幹部A" = "尤も、そんなことを言われては玄龍門が麻痺してしまう。#nそうなったら、困るのは私たちだけじゃないぞ？"
"10024090-15-ルミ" = "はあ……なにを言っても通じそうにないね。"
"10024090-16-レイジョ" = "ここまで清々しく開き直られるとは……呆れて言葉が出ません。"
"10024090-17-玄龍門の構成員A" = "門主様の、おなーりー！！！"
"10024090-18-玄龍門の構成員B" = "おなーりー！！！"
"10024090-19-キサキ" = "――何の騒ぎじゃ。"
"10024090-20-玄龍門の幹部A" = "も、門主様！あの者たちが……！"
"10024090-21-キサキ" = "もうよい、全て分かっておる。"
"10024090-22-玄龍門の幹部A" = "門主様……！"
"10024090-23-玄龍門の幹部A" = "門主様！？#nお、おやめください！！"
"10024090-24-レイジョ" = "頭を……下げた？"
"10024090-25-ルミ" = "キサキ……。"
"10024090-26-キサキ" = "玄龍門は、玄武商会に対して公式に謝罪しよう。"
"10024090-27-キサキ" = "確たる証拠もなく玄武商会を犯人であると述べ――汚名を被せたこと。"
"10024090-28-キサキ" = "延いては、其方たちだけでなく、山海経に混乱を招いたこと。#nそして、妾の目が行き届いておらぬこと。"
"10024090-29-キサキ" = "玄龍門の門主として、かような事は二度と起こさぬと約束しよう。"
"10024090-30-キサキ" = "これが玄龍門の門主、[ruby=りゅうげ]竜華[/ruby]キサキの裁決じゃ。"
"10024090-31-キサキ" = "し、しかし門主様……"
"10024090-32-キサキ" = "下がれ。"
"10024090-33-玄龍門の幹部A" = "私たちは、あくまで……"
"10024090-34-キサキ" = "――二度は言わぬ。"
"10024090-35-キサキ" = "し、失礼しましたっ！"
"10024090-36-ミナ" = "さ、さあ、謝罪したぞ？#n玄龍門が公式に表明したのだからな！"
"10024090-37-ミナ" = "なんだ、その目は……#n私も悪かったと言っただろうが！"
"10024090-38-ミナ" = "まったく、門主様は優しすぎる。#nこんなのちょっとした捜査ミスじゃないか、何も頭を下げなくても……"
"10024090-39-ルミ" = "やはり納得できません、会長！"
"10024090-40-ルミ" = "まあ……キサキの考えてることは、なんとなく分かったよ。"
"10024090-41-レイジョ" = "ルミ会長は、本当にこれで良いんですか！？"
"10024090-42-ルミ" = "良いか悪いかで言ったら微妙だけど……#nまあ、これで一件落着ということで。"
"10024090-43-レイジョ" = "もしかしたら、玄武商会が解散するかもしれなかったのに……！"
"10024090-44" = "[s1] \"私もなんとなく分かったような……。\"\n[s2] \"スッキリとしない終わり方の日もあるよね。\""
"10024090-45-ルミ" = "さ、この話はこれで終わりにしよっか。"
"10024090-46-ルミ" = "キサキの考えは分かったし……#n玄武商会としては、またお客さんが安心して来られるようになるなら十分。"
"10024090-47-ルミ" = "いくら門主とはいえ、生徒会である以上、どうしようもない事情はあるからね。"
"10024090-48-レイジョ" = "うーん……分かりました。#n今日のところは、会長の意志を尊重します。"
"10024090-49-レイジョ" = "ですが、私は納得してるわけではありませんからね！"
"10024090-50-ルミ" = "あはは。ありがとう、レイジョ。#n美味しいもの作ってあげるから、それで許してよ。"
"10024090-51-キサキ" = "一つ、[ruby=そなた]其方[/ruby]と玄武商会に、お願いがあるのじゃが。"
"10024090-52" = "[s] \"もちろん、力になるよ。\""
"10024090-53-キサキ" = "礼を言う。#nどうやら、今回の騒ぎを聞きつけた生徒たちが、不安を抱いているようでの。"
"10024090-54-キサキ" = "彼女らの不安を払拭するのも、玄龍門の大事な役目じゃ。#n……そこで、力を貸してはくれぬか？"
"10024090-55-キサキ" = "これは、玄龍門の門主からの――正式な依頼じゃ。"
"10024090-56-ミナ" = "も、門主様！？"
"10024090-57-キサキ" = "騒ぐでない、ミナ。#n玄武商会も山海経じゃ。"
"10024090-58-ミナ" = "そう……ですね。分かりました、門主様。"
"10024090-59-ルミ" = "それで、依頼って何？#nどんな内容でも受けるつもりだけどね。"
"10024090-60-キサキ" = "そんなことを口にして、後悔せぬようにな？"
"10024090-61-ルミ" = "玄武商会が依頼を断ることはないよ。#n物理的に不可能な場合を除いてね。"
"10024090-62-キサキ" = "その言葉、努々違えるでないぞ？"
"10024090-63-ルミ" = "もちろん、報酬さえ十分ならね。#nそれが玄武商会だから。"
"10024090-64-キサキ" = "それは重畳――では、宴の準備を頼めるかの？"
"10024090-65-キサキ" = "山海経の全生徒……そして、先生を招待して執り行う、盛大な宴じゃ。"
"10024090-66" = "[s] \"私もいいの？\""
"10024090-67-キサキ" = "無論。#nなにを言う、其方は此度の事件を解決に導いた立役者じゃろうて。"
"10024090-68-キサキ" = "この機会に、「山海経」の「おもてなし」を存分に味わうが良い。"
"10024090-69-ルミ" = "山海経のみんなと……先生を……？"
"10024090-70-ルミ" = "費用なら心配せずとも良い。#n全て、玄龍門が負担しよう。"
"10024090-71-キサキ" = "それとも……妾のお願いなど、引き受けるに値しないと？"
"10024090-72-ルミ" = "ううん、そんなわけないよ！#nあははっ、楽しくなりそうだね。"
"10024090-73-ルミ" = "久しぶりに商会のみんなを集めないと！"
"10024090-74-キサキ" = "ああ。手が足りぬようじゃったら、ミナたちも使ってくれて構わぬぞ？"
"10024090-75-ルミ" = "大丈夫、玄武商会に集まってくれた子たちは、みんな一人前の料理人だからね！"
