[translation]
"10024025-1-玄龍門の下級幹部" = "そ、そんなバカな……！"
"10024025-2-レイジョ" = "玄龍門も一枚岩じゃないってことかな。#nキサキの意志に反して、こんな勝手なことしていいの？"
"10024025-3-玄龍門の下級幹部" = "き、貴様に門主様の何が分かるというのだ！"
"10024025-4-ルミ" = "たしかに、人の心を理解するのは難しいけど……"
"10024025-5-ルミ" = "言葉にされてたって、それが本心とも限らないし。"
"10024025-6-ルミ" = "でも、少なくともこの場でキサキのことを一番分かってるのは、あたしだと思うけど？"
"10024025-7-玄龍門の下級幹部" = "どの口が！！"
"10024025-8-レイジョ" = "それはこちらのセリフです。"
"10024025-9-ルミ" = "あなた達の独断専行……正式に玄龍門に抗議したら、どうなるのでしょうね。"
"10024025-10-玄龍門の下級幹部" = "誰が犯罪者の言葉に耳を傾けるか！"
"10024025-11-玄龍門の下級幹部" = "クソッ、覚えてろ。"
"10024025-12-レイジョ" = "ありゃ、行っちゃった……"
"10024025-13" = "[s] \"追わなくていいの？\""
"10024025-14-ルミ" = "放っといていいんじゃない？それに、ここはまだ玄龍門の敷地内だからね。#n気をつけないといけないのはあたし達の方。"
"10024025-15-ルミ" = "応援を呼んでこないといいんだけど……#nあ、でもそしたらキサキの耳に入るからしないか……。"
"10024025-16" = "[s] \"これからどうしよっか？\""
"10024025-17-レイジョ" = "まずは「萬年参」に詳しい人を当たろうかな。#nこういう時に頼りになる人がいてね。"
"10024025-18-ルミ" = "玄龍門に抗議するのは、後からでも遅くないし……"
"10024025-19-ルミ" = "まずは容疑を晴らさないと。"
"10024025-20-ルミ" = "それじゃ、行こっか！"
