[translation]
"10024080-1" = "第8話;[ruby=はじゃけんしょう]破邪顕正[/ruby]"
"10024080-2-玄龍門の下級幹部" = "ぐっ！？"
"10024080-3-ブローカー" = "うわっ！？"
"10024080-4-レイジョ" = "ルミ会長、制圧完了しました。"
"10024080-5-ミナ" = "はぁはぁ……酷い腕だな。銃が泣いてるぞ？"
"10024080-6-レイジョ" = "そちらこそ、そんな体力でよく執行部長が務まりますね。"
"10024080-7-ミナ" = "カンフー映画しか見てないような脳筋に言われて[ruby=たま]堪[/ruby]るものか！"
"10024080-8-レイジョ" = "あなたこそ、どうせマフィア映画ばっかりのくせに！"
"10024080-9" = "[s] （口を挟むと面倒なことになりそうだ……）"
"10024080-10-ルミ" = "よしっ。これで一件落着、かな。"
"10024080-11-ルミ" = "サヤ、聞いておきたいことがあるんだっけ？"
"10024080-12-サヤ" = "あ、そうだったのだ。"
"10024080-13-サヤ" = "お前たちは、誰の指示で動いてるのだ？"
"10024080-14-ブローカー" = "！？"
"10024080-15-ブローカー" = "！？"
"10024080-16-玄龍門の下級幹部" = "しっ、知らない！#n本当だ、何も知らないっ！！"
"10024080-17-サヤ" = "……。"
"10024080-18-サヤ" = "いや、お前たちが言わなくても分かってるのだ……"
"10024080-19-サヤ" = "「[ruby=ごじん]五塵[/ruby]の[ruby=びこう]獼猴[/ruby]」――[ruby=しんたに]申谷[/ruby]カイだろう？"
"10024080-20-ブローカー" = "……！"
"10024080-21-ブローカー" = "なっ、何のことだか……ッ！"
"10024080-22-サヤ" = "その反応じゃ、正解だと言ってるようなものなのだ。"
"10024080-23-ミナ" = "いったい誰なの？#nその「五塵の獼猴」って。"
"10024080-24-レイジョ" = "私も初めて聞きますね。"
"10024080-25-ミナ" = "ちょ、ちょっと待ってくれ！"
"10024080-26-ミナ" = "「五塵の獼猴」だと！？"
"10024080-27-ミナ" = "かつて、錬丹術研究会の会長だった……あの申谷カイのことか？"
"10024080-28-サヤ" = "知ってる人がいて良かったのだ。"
"10024080-29-サヤ" = "そう、錬丹術研究会の元会長で――「七囚人」の1人。"
"10024080-30-サヤ" = "秘薬の密輸に関与した容疑で、永久に山海経から追放されたのだ。"
"10024080-31" = "[s] \"七囚人ってことは、たしか……\""
"10024080-32-ミナ" = "うん……7人とも、脱獄したんだよね。"
"10024080-33-レイジョ" = "そのうちの1人が、今回の事件の黒幕とは。"
"10024080-34-レイジョ" = "私たちが想像していたよりも、規模が大きくなってきましたね。"
"10024080-35-サヤ" = "さあ、白状するのだ！#n申谷カイと、どんな取引をしたのだ！"
"10024080-36" = "……私たちも、詳しくは知らない。"
"10024080-37-ブローカー" = "受け子に過ぎないからな。#n指定の場所まで「萬年参」を運んで、報酬を受け取っただけ。"
"10024080-38-玄龍門の下級幹部" = "（カイさんのことは話したらマズいよな？）"
"10024080-39-ブローカー" = "（当たり前だろ！それだけは何としても隠し通さないと、私たちの身が……）"
"10024080-40-サヤ" = "うう……こいつ等、絶対に何か知ってるはずなのだ……！"
"10024080-41-ミナ" = "ここは私に任せてくれ。"
"10024080-42-ミナ" = "お前たちの言葉が本当かどうかは、玄龍門の名において詳らかにしてやろう。"
"10024080-43-ルミ" = "錬丹術研究会にも……複雑な過去があったんだね。"
"10024080-44-レイジョ" = "……山海経の多くは、何かしらの事情を抱えていますから。#n私たち、玄武商会も……"
"10024080-45-ルミ" = "その話は今度にしよっか、レイジョ。#nこれから大変なことになる人が、まさに目の前に居るわけだし。"
"10024080-46-ミナ" = "……玄龍門のことを言ってるのか？"
"10024080-47-ルミ" = "あれ、違った？「萬年参」の密輸が、玄龍門の身内問題だって知られたら大騒ぎになるよね。関与してる人がどれくらい居るのかだって、これから調べるわけだし……"
"10024080-48-ミナ" = "そ、それくらい言われなくても分かってる！"
"10024080-49" = "[s] \"これからどうするの？\""
"10024080-50-ミナ" = "まずは、迅速に「萬年参」の回収をしなくてはな。"
"10024080-51-ミナ" = "それが終わり次第、「玄龍門」として責任を問う。#nいつまでも続く尋問に、果たして耐えられるのか……"
"10024080-52-ミナ" = "玄龍門の名を汚した罪は軽くないぞ……フッフッフ。"
"10024080-53-レイジョ" = "何か言うべきことを忘れていませんか？"
"10024080-54-ミナ" = "うっ！？"
"10024080-55-レイジョ" = "結局、「萬年参」の密輸犯は、玄龍門の構成員だったわけですが……"
"10024080-56-ミナ" = "そ、それは……玄龍門にも事情があってだな……"
"10024080-57-レイジョ" = "玄龍門の事情など、玄武商会からすれば関係ありません。"
"10024080-58-レイジョ" = "それとも、何か？ご自身の管轄外だから関係ないとでも？#n最初にうちの言い分を聞かなかったのは、玄龍門の方だったかと。"
"10024080-59-レイジョ" = "っ、その……そうかもしれないが、言い方ってものがあるだろう！"
"10024080-60-レイジョ" = "私たちが玄龍門を訪れた時の扱いを忘れたとは言わせませんよ？"
"10024080-61-ミナ" = "き、聞いてくれ。#nこの件は、玄龍門が責任を持って真相を……！"
"10024080-62-レイジョ" = "玄龍門の責任など、私たちにとってはどうでもいい事です。"
"10024080-63-レイジョ" = "だが、あなた達が玄武商会にしてきた不当な扱いを、忘れることはない。#nそれとも、今ここで謝罪してくれるのですか？"
"10024080-64-ミナ" = "そ、それは……"
"10024080-65-ミナ" = "私だけで決められる問題ではない！#nだが、決めつけたことは悪かったと思っている！改めて謝罪の場を設けさせてくれ！"
"10024080-66-ミナ" = "後でちゃんと、場を用意するから……それまで待っていてくれ！"
"10024080-67-ルミ" = "逃げられてしまいました……！あんなの謝罪ではありません！"
"10024080-68-ルミ" = "あはは……まあ、あんまり追い詰めすぎてもね。"
"10024080-69-レイジョ" = "会長は、これで良かったのですか？#n自分たちの責任だと分かった途端……"
"10024080-70-ルミ" = "いいのいいの。あたしは無実が証明できれば、それで十分だよ。"
"10024080-71-ルミ" = "玄龍門には、どうせ後で行くことになるし。"
"10024080-72-ルミ" = "それに、うまく転べば商売がやりやすくなるかもしれないからね。"
"10024080-73-ルミ" = "サヤ、来てくれて助かったよ。ありがとう。"
"10024080-74-サヤ" = "いつもご馳走になってるから、これくらい何でもないのだ！#nでも、ぼく様も早く帰って、色々と対策を……"
"10024080-75-ルミ" = "心配になる気持ちも分かるけど、まずは帰ってお祝いしよっか。"
"10024080-76-ルミ" = "先生もありがとう、お疲れ様。"
"10024080-77" = "[s] \"ルミこそ、お疲れ様。\""
"10024080-78-ルミ" = "ふふっ、ありがとう。#nそうだ、帰ったらお礼に、新しい試作品を振る舞ってあげる！"
"10024080-79-レイジョ" = "はい！？#nそれのどこがお礼に……っ、何でもありません！"
"10024080-80-レイジョ" = "（会長の試作品は……）"
"10024080-81-レイジョ" = "（いつも、言葉では言い表せない謎の味がして……）"
"10024080-82" = "[ns] \"ルミの料理、早く食べたいね！\""
"10024080-83-サヤ" = "新作……！チーズ南煎丸子をかけた焼き刀削麺みたいな奴か！？#n思い出しただけでも、お腹が空いてきたのだ！！"
"10024080-84-レイジョ" = "（やはり、ここは2人に本当のことを伝えるべきでは……！しかし、私の口からルミ会長の料理を悪く言うのは……！）"
"10024080-85-レイジョ" = "（だが、玄武商会の恩人に、あんな料理を食べさせるわけにも……！）"
"10024080-86-レイジョ" = "（うう、私は一体どうすれば……）"
"10024080-87-カイ" = "そう……「萬年参」の密輸が、もう見つかってしまったとは。"
"10024080-88-カイ" = "あの子たちがねぇ……ククッ、成長しているようで、先輩としては喜ばしい限りさ。#nいや、それともシャーレの「先生」の力なのかね。"
"10024080-89-カイ" = "でも、残念なことに後一歩遅かった。#nすでに新薬の実験は終えたところさ。"
"10024080-90-カイ" = "欲を言えば、もう少しばかり実験データを集めたかったところではあるけど……"
"10024080-91-カイ" = "まあ、構わないさ。これもまた一興。#nここは後輩の成長に免じて、大人しく引き下がろうじゃあないか。"
"10024080-92-カイ" = "ククッ、あの子たちの顔を見るついでに、#n今度は山海経まで「挨拶」に行くとしようかな。"
"10024080-93-カイ" = "それに……「先生」との出会いが、#n一体どんな化学反応を起こすのかも気になるところだねぇ。"
"10024080-94-カイ" = "先生、先生か……"
"10024080-95-カイ" = "いつ以来だろうか、こんなにも心が踊るのは――ククッ。"
