[translation]
"10024020-1" = "第2話;[ruby=こうしらんしょう]嚆矢濫觴[/ruby]"
"10024020-2" = "六和閣・入口"
"10024020-3" = "[ns] \"これが……\""
"10024020-4-レイジョ" = "うん、玄龍門の[ruby=りくわかく]「六和閣」[/ruby]だよ。"
"10024020-5-ルミ" = "久しぶりに来たけど、あんまり変わってないね。"
"10024020-6-ルミ" = "さて、そろそろ「手厚いお出迎え」が来る頃かな……"
"10024020-7-玄龍門の構成員A" = "おい、止まれ。何者だ！"
"10024020-8-レイジョ" = "こちらは玄武商会のルミ会長とシャーレの先生。#n私は護衛のレイジョです。"
"10024020-9-ルミ" = "先生がキサキに会いたいみたいだから、連れてきたよ。#n通してもらえるかな？"
"10024020-10-玄龍門の構成員A" = "門主様に？#n来客があるとは聞いていないが……アポイントなしの来訪を通すわけには――"
"10024020-11-玄龍門の構成員A" = "――待て、シャーレの先生と言ったか？#n玄武商会め、先生を盾にするとは、いかにも卑怯な連中の考えそうなことだ。"
"10024020-12-ルミ" = "まあ、あながち間違いじゃないし、否定はできないね。"
"10024020-13-ルミ" = "それで、どうするの？#nこのまま門前払いするつもり？"
"10024020-14-レイジョ" = "そうなれば、「シャーレの先生でさえ門前払いされた」という噂がキヴォトス中に轟くことになるでしょうね。"
"10024020-15-玄龍門の構成員A" = "――玄龍門の秘密主義にさぞかし箔がつくのでは？"
"10024020-16" = "[s] \"それは皮肉なんだよね……？\""
"10024020-17-レイジョ" = "さあ？伝わらなければ皮肉にはならないのではないでしょうか？"
"10024020-18-玄龍門の構成員A" = "……バカにしてるのか？"
"10024020-19-ルミ" = "レイジョ、あたし達はケンカしに来たわけじゃないでしょ。"
"10024020-20-玄龍門の構成員A" = "ここまで見くびられては、我々のメンツが……"
"10024020-21" = "[s] \"ごめんね。とりあえず、確認してきてもらえるかな？\""
"10024020-22-玄龍門の構成員A" = "ゴ、ゴホンッ。#n少々お待ちを。門主様にお伝えしてきます。"
"10024020-23-ルミ" = "先生がいてくれると、話が早いね。"
"10024020-24-レイジョ" = "ええ、噂通りです。"
"10024020-25" = "[s] \"……ちょっと強引じゃなかったかな？\""
"10024020-26-ルミ" = "まあまあ、細かいこと気にしてたら商売なんかやっていけないって。"
"10024020-27-レイジョ" = "先生、顔色が悪いようですが……大丈夫ですか？"
"10024020-28" = "[s1] \"秘密組織に招待された気分だよ……。\"\n[s2] \"マフィアのアジトみたいで……。\""
"10024020-29-ルミ" = "当たらずとも遠からず、ってところかな。"
"10024020-30-ルミ" = "ホント、相変わらずだね。"
"10024020-31-玄龍門の構成員A" = "門主様の、おなーりー！！！"
"10024020-32-玄龍門の構成員B" = "おなーりー！！！"
"10024020-33-キサキ" = "……。"
"10024020-34-キサキ" = "[ruby=そなた]其方[/ruby]のことは聞いておる。"
"10024020-35-キサキ" = "会えて嬉しくないと言えば嘘になるのじゃが……このような形で会いとうなかったな。"
"10024020-36" = "[s] \"えっと……はじめまして、キサキちゃん。\""
"10024020-37-玄龍門の構成員A" = "無礼な！#nいくら先生とはいえ、そのように気安くお呼びして許される方ではないぞ……！"
"10024020-38-玄龍門の構成員B" = "時と場[ruby=わきま]を弁え[/ruby]ることもできないのか！"
"10024020-39-キサキ" = "そう騒ぐでない――[ruby=わらわ]妾の[/ruby][ruby=・   ・]客人[/ruby]ぞ。"
"10024020-40-玄龍門の構成員A" = "はっ！失礼いたしました、門主様！"
"10024020-41-玄龍門の構成員B" = "門主様！どうかお許しを！"
"10024020-42-キサキ" = "シャーレの先生は人望が厚く――"
"10024020-43-キサキ" = "目的のためであれば手段を選ばぬ、権謀術数に長けた策士だと聞き及んでおるぞ。"
"10024020-44" = "[ns] \"一体どこで聞いたのソレ！？\""
"10024020-45-キサキ" = "案ずるでない。#n妾の見立てでは、其方はそのような類ではなかろうて。"
"10024020-46-キサキ" = "寧ろ――人の良さが[ruby=たた]祟[/ruby]って、振り回されている姿が目に浮かぶからの。"
"10024020-47" = "[s] \"それは褒めてる……の……？\""
"10024020-48-キサキ" = "さあ、どちらじゃろうな？#nそれを想像するのもまた、一興。"
"10024020-49-キサキ" = "其方の心には、いったい何が秘められておるのやら。"
"10024020-50-キサキ" = "して、これは執行部長のミナじゃ。#n皆の先頭に立ち、妾の警護を務めてくれておる。"
"10024020-51-ミナ" = "……。"
"10024020-52-ルミ" = "……。"
"10024020-53-ミナ" = "――本題に移ろうではないか、先生。"
"10024020-54-キサキ" = "昨今、山海経の外で無許可の「萬年参」が流通しておるようでな。"
"10024020-55" = "[s] \"何か、玄武商会と関与してる証拠が見つかったの？\""
"10024020-56-キサキ" = "……ミナ、持ってくるのじゃ。"
"10024020-57-ルミ" = "これは……？"
"10024020-58-キサキ" = "見ての通りじゃ――まさか知らぬとは申すまい？"
"10024020-59-ルミ" = "……玄武商会で扱ってるダンボールだね。"
"10024020-60-レイジョ" = "会長……！"
"10024020-61-キサキ" = "これが証拠じゃよ――我らとて暇ではないからの。#n証拠もなく疑うような真似はせぬ。"
"10024020-62-キサキ" = "萬年参は山海経でも貴重ゆえ、採取するのにも許可が必要での。"
"10024020-63-キサキ" = "かような特産物が山海経の外に――#nそれも玄龍門の預かり知らぬところで流れておると聞けば、当然、黙ってはおれん。"
"10024020-64-キサキ" = "門主として、看過するわけにはいかぬからな。#nして――これに対しての申し開きはあるかの？"
"10024020-65-ルミ" = "玄武商会のみんなのことなら、あたしが一番よく知ってる。"
"10024020-66-ルミ" = "どの流通担当も萬年参を扱ってなんかいないし、あたしに隠れてそんなことをする子もいない。"
"10024020-67-レイジョ" = "もしも、玄武商会内部で違法取引に手を出している者がいるのであれば――#n必ずここに連れてきます。"
"10024020-68-レイジョ" = "私の力にかけて――お約束いたします。"
"10024020-69-キサキ" = "……期待外れじゃの。"
"10024020-70-キサキ" = "此方は証拠を提示したのじゃ――であれば、#n其方も反証を提示するのが道理ではないのかえ？"
"10024020-71" = "[s3] \"今すぐ立証するのは……\"\n[s4] \"少し時間をくれないかな？\""
"10024020-72-玄龍門の構成員A" = "これ以上、何を聞くことがありますか、門主様！"
"10024020-73-玄龍門の構成員B" = "玄武商会は創作料理を出すことで有名ではありませんか！"
"10024020-74-玄龍門の構成員A" = "萬年参だって、学外の食材を仕入れるための道具として使われたに違いありません！"
"10024020-75-玄龍門の構成員B" = "受け継がれてきた伝統には、それ相応の価値と理由があるというのに！"
"10024020-76-玄龍門の構成員A" = "伝統の大切さを理解できないヤツらのことです！これ以上の申し開きなど不要！"
"10024020-77-玄龍門の構成員B" = "早く頭を垂れて謝罪しろ！"
"10024020-78-ルミ" = "あはは……全部を否定は流石にできないかな。"
"10024020-79-ルミ" = "伝統の重要性が分からないとは言わないけどね。"
"10024020-80-ルミ" = "でも、新しい文化を取り入れなくちゃ――#nいつまで経っても変わらないままだから。"
"10024020-81-キサキ" = "――そこまで。"
"10024020-82-キサキ" = "今は玄武商会にかかっておる嫌疑を伝え、申し開きを聞くための場じゃ。#n口論の場ではないぞ。"
"10024020-83-玄龍門の構成員B" = "甘すぎます、門主様！#n玄武商会が犯人に決まっています！"
"10024020-84-玄龍門の構成員B" = "そうです！#n時間を与えては、証拠隠滅を図るに違いありません……！"
"10024020-85-キサキ" = "山海経の生徒には自由が保障されておる。#n……学園の害にならぬという条件下での。"
"10024020-86-玄龍門の構成員A" = "今まさに！玄武商会は害を及ぼしているではありませんか！！"
"10024020-87-キサキ" = "害かどうか、まだ詳らかにはなっておらんじゃろうて――早計は禁物。#n妾の言っておる意味が分かるな？"
"10024020-88-キサキ" = "――玄武商会よ、聞くがよい。#n其方の容疑が晴れぬ限り、監視を解く事はできぬ。"
"10024020-89-キサキ" = "とはいえ、今すぐ反証を示せというのも理不尽じゃろうて。"
"10024020-90-ルミ" = "そこで――しばし猶予を与えよう。"
"10024020-91-ルミ" = "期日までに妾が納得する証拠が見つかれば、改めて審議の場を設けるとしようかの。"
"10024020-92-キサキ" = "じゃが――努々忘れるでないぞ。"
"10024020-93-キサキ" = "もしも、状況が悪化するのであれば――玄武商会の取り潰しも、致し方ないからの。"
"10024020-94-キサキ" = "以上を、玄龍門の門主――[ruby=りゅうげ]竜華[/ruby]キサキの裁決とする。"
"10024020-95-ルミ" = "お待ちください、門主様！#nこれは何者かが玄武商会を罠に……ッ、ルミ会長！？"
"10024020-96-ルミ" = "レイジョ、玄武商会の箱に「萬年参」が入ってた事実は変わらない。"
"10024020-97-ルミ" = "こうなった以上……悔しいけど、あたし達の手で犯人を捕まえるしかないよ。"
"10024020-98-ルミ" = "それでどうかな、キサキ[ruby=・  ・]門主[/ruby]？"
"10024020-99-キサキ" = "嗚呼、構わぬよ。認めぬ理由はどこにも無いからのう、ルミ[ruby=・  ・]会長[/ruby]。"
"10024020-100" = "[ns] \"じゃあ、何から始めようか？\""
"10024020-101-ルミ" = "まずは、「萬年参」の情報を集めないとだね……"
"10024020-102-玄龍門の下級幹部" = "玄武商会め、止まれ！"
"10024020-103-レイジョ" = "先生、下がってください！"
"10024020-104-玄龍門の下級幹部" = "[ruby=うち]玄龍門[/ruby]の敷地を跨いでおいて、そう簡単に帰れると思ったのか？"
"10024020-105-玄龍門の下級幹部" = "門主様は甘すぎる……！"
"10024020-106-玄龍門の下級幹部" = "犯罪者がノコノコ現れたというのに、そのまま放免するだなんて……。"
"10024020-107-玄龍門の下級幹部" = "容疑者は、証拠が出揃うまで身柄を拘束すべきじゃないのか？"
"10024020-108-ルミ" = "さっきのキサキの話、聞いてなかったのかな？"
"10024020-109-玄龍門の下級幹部" = "玄武商会が門主様の言葉を語るな！#n罪人の言葉など誰が聞くか！"
"10024020-110-玄龍門の下級幹部" = "お前たち、出てこい！"
"10024020-111-レイジョ" = "……先生、私の後ろから出ないでくださいね。"
"10024020-112-ルミ" = "そういえば……先生の指揮があれば、#nどんな状況でもひっくり返せるって聞いたんだけど、本当？"
"10024020-113" = "[s] \"どこでそんな噂が……。\""
"10024020-114-ルミ" = "あははっ、噂って自分じゃどうしようもないからね。"
"10024020-115-ルミ" = "それじゃ、指揮は任せたよ。#n先生の力、あたし達にも見せてちょうだい！"
