[translation]
"1006703-1" = "バニーの噂"
"1006703-2" = "シャーレ・オフィス"
"1006703-3-トキ" = "本日もシャーレは平和ですね。良いことです。"
"1006703-4-トキ" = "あ、先生。そちらのポテチを取っていただけますか？"
"1006703-5" = "[ns1] \"トキが気を許してくれるのは嬉しいけど……\"\n[ns2] \"流石に緩みすぎじゃない！？\""
"1006703-6-トキ" = "ん？#nそれは重大な問題でしょうか？"
"1006703-7-トキ" = "……違うのでしたら、気にする必要はありませんね。#n分かっています、ポテチの補充はお任せください。"
"1006703-8" = "（最近、一つ悩みができた）"
"1006703-9" = "（それは……トキがシャーレに馴染みすぎているということだ）"
"1006703-10" = "（数日前、それとなくトキに話を振ってみたが……）"
"1006703-11-トキ" = "どうして毎日のようにシャーレで過ごしているのか、ですか？"
"1006703-12-トキ" = "理由はいくつかありますが……#n一番は私の所属が明確になっていない事にあります。"
"1006703-13-トキ" = "C&C所属、コールサインゼロフォーとして、#nいまだ先輩方と行動を共にできない状況ですので。"
"1006703-14-トキ" = "そんな私にとって、ここシャーレに優る場所はありません。"
"1006703-15-トキ" = "キヴォトスの様々な情報が集まってきますし、#n有事の際は迅速に対応が可能です。"
"1006703-16-トキ" = "エージェントとして自身の立場を顧みるのであれば、#n誰しもシャーレで過ごすと思いますが……間違っておりましたか？"
"1006703-17" = "（トキの言い分には一理あるため、何も言い返す事ができず……）"
"1006703-18" = "（今日に至るまでズルズルと……）"
"1006703-19-トキ" = "あむ……しょっぱいものを食べ続けていたら、喉が渇きました。#n先生のお茶を頂きます。"
"1006703-20-トキ" = "あ、茶柱が立っていますね。今日は良いことがあるかもしれません。"
"1006703-21-トキ" = "落ち着く香り……飲みやすいですね。#n先生が緑茶にも造詣が深いとは知りませんでした。"
"1006703-22" = "[s] \"えっと……贈り物だから、あんまり詳しくはないんだよね。\""
"1006703-23-トキ" = "そうでしたか。想定通りの答えで、少しガッカリしました。"
"1006703-24" = "[ns] \"勝手にガッカリされたんだけど！？\""
"1006703-25-トキ" = "本日のランチは――"
"1006703-26-トキ" = "……いえ、何でもありません。私のことはお気になさらず。#n先生が自分の分だけ注文し、お腹を空かせた私の隣で食事を堪能されたとしても……"
"1006703-27-トキ" = "私の心は極めて穏やかです。何も思うところはありません。#nええ……何も思うところはありませんとも。"
"1006703-28" = "[ns3] \"すみません、シャーレですが……\"\n[ns4] \"スペシャルヘルシーランチセット、2人前で……\""
"1006703-29-トキ" = "おや、2人前を注文されたのですね。#n先生には量が多いでしょうに。"
"1006703-30-トキ" = "……仕方ありませんね。私が一緒に食べて差し上げます。"
"1006703-31" = "[s] \"うん……健康のためには野菜とタンパク質も大切だからね。\""
"1006703-32-トキ" = "まるで、普段の私が不健康な食生活をしているかのような言い草ですね。"
"1006703-33" = "[s] \"違った……？\""
"1006703-34-トキ" = "……。"
"1006703-35-トキ" = "……過去は過去です。#nいつまでも過ぎたことを気にしていても仕方ありませんよ。"
"1006703-36" = "[s] \"せめて取り繕おうよ！？\""
"1006703-37" = "[ns] \"そういえば、トキ……\""
"1006703-38-トキ" = "……お呼びでしょうか？"
"1006703-39-トキ" = "もちろん、日が暮れたら自分のオフィスに戻る予定です。"
"1006703-40-トキ" = "具体的な帰る時間、ですか……？"
"1006703-41-トキ" = "……。"
"1006703-42-トキ" = "もしかして、私がここにいては……邪魔、でしょうか……？"
"1006703-43" = "[s5] \"いやいや！そうじゃないんだけど！\"\n[s6] \"ここにいても暇じゃないのかなって！\""
"1006703-44-トキ" = "退屈など致しません。"
"1006703-45-トキ" = "……ここに居ても問題ないのですね？"
"1006703-46" = "[s] \"……うん、トキが大丈夫なら。\""
"1006703-47-トキ" = "それでは遠慮なく……"
"1006703-48-トキ" = "……え？シャーレに変な噂が？"
"1006703-49" = "（その噂とは……）"
"1006703-50-通行人A" = "聞きました？#n最近、シャーレの先生が……"
"1006703-51-通行人B" = "ええ、近所で噂になってますからね！#n生徒たちに、毎日バニーガールの格好をさせているんだとか。"
"1006703-52-通行人A" = "私たちと街で会った時は、あんな優しそうに挨拶してくれるのに……"
"1006703-53-通行人B" = "ついさっきも、バニー服でシャーレを訪れる生徒がいたみたいですよ？"
"1006703-54" = "（……のような内容だった）"
"1006703-55" = "（それをトキに話すと……）"
"1006703-56-トキ" = "毎日バニーガールの格好でシャーレを出入りしているのは、私だけです。#n先生が聞いた噂は、「生徒たち」だったのでしょう？"
"1006703-57-トキ" = "つまりは事実無根の噂話ですね。"
"1006703-58-トキ" = "先生が私にバニーガールの格好をさせている、というのも間違っていると思いますが……"
"1006703-59-トキ" = "……それとも、私が気づいていないだけで、本当は着てほしかったんですか？"
"1006703-60" = "[ns] \"それはないから！！\""
"1006703-61-トキ" = "では、何も気にする必要はありませんね。"
"1006703-62-トキ" = "そのような噂話、無視していればそのうち収まります。#n人の噂も七十五日と言いますから。"
"1006703-63-トキ" = "よって、この問題は解決したという事で。"
"1006703-64" = "[s] \"本当に大丈夫なのかな……？\""
"1006703-65-トキ" = "ええ、大丈夫ですとも。"
"1006703-66-トキ" = "世間体……？#n……よく分かりません。この話はそろそろ終わりにいたしましょう。"
"1006703-67-トキ" = "あ、出前が届いたようですね。もうお腹が限界……"
"1006703-68-トキ" = "私が受け取ってきます。"
"1006703-69-トキ" = "先生、ペンを落としましたよ……#nえ？先生が取りに行かれるのですか？"
"1006703-70-トキ" = "……"
"1006703-71-トキ" = "私の方が扉に近いですが……承知しました。"
"1006703-72" = "（ギリギリ世間体は保たれたが、食事はあまり喉を通らなかった……）"
