[translation]
"2600602-1" = "運が良い日"
"2600602-2" = "キヴォトス・住宅街"
"2600602-3" = "道を歩いていたら、500円玉が落ちているのを見つけた。"
"2600602-4" = "[s] 500円玉を拾う。"
"2600602-5-？？？" = "待ってぇぇー！"
"2600602-6-ノドカ" = "はあ、はあ……先生、その小銭は私のです！"
"2600602-7" = "[s] \"ノドカが落とした小銭なの？\""
"2600602-8-ノドカ" = "いいえ、そうではありませんが……。"
"2600602-9-ノドカ" = "私が先に！発見しました！"
"2600602-10-ノドカ" = "1km先から！！"
"2600602-11" = "[s] \"い、1km先から……？\""
"2600602-12-ノドカ" = "はい！この望遠鏡は、数百メートル離れたところにいる蟻も見ることができるんです！"
"2600602-13-ノドカ" = "朝の占いも良かったですし、今日は何か良いことが起きるんじゃないかなと、午前中ずっと望遠鏡を覗いていましたが……やっぱり運が良かったです！"
"2600602-14-ノドカ" = "旧校舎の227号特別クラスは、補給も少なく、おやつもあまり食べられませんから……。"
"2600602-15-ノドカ" = "ですがこの500円さえあれば、コンビニのパンも飲み物も、お腹いっぱい食べられます！"
"2600602-16-ノドカ" = "さあ先生、その小銭を私に！"
"2600602-17" = "[s1] 口笛を吹く。\n[s2] 聞かなかったことにする。"
"2600602-18-ノドカ" = "どうしてですか、先生！？"
"2600602-19-ノドカ" = "どうしてですか、先生！？"
"2600602-20-ノドカ" = "え？誰が先に見つけたかは重要じゃなくて、先に拾った人が持ち主、ですか？"
"2600602-21-ノドカ" = "ずるい！ケチ！ひどいです！"
"2600602-22" = "[s] \"代わりに、「ルワゾー・ブッレ」でケーキを奢ってあげる。\""
"2600602-23-ノドカ" = "は、はいっ？「ルワゾー・ブッレ」といえば……一番安いケーキでも1000円を超えるという、高級スイーツのお店じゃないですか！？"
"2600602-24-ノドカ" = "ほ、本当にいいんですか？"
"2600602-25" = "[s] \"もちろん。\""
"2600602-26-ノドカ" = "あ……ありがとうございます。"
"2600602-27-ノドカ" = "本当に……今日は「運が良い日」でした。"
"2600602-28" = "その後、大人のカードを使って、「ルワゾー・ブッレ」で一番高いケーキを奢ってあげたのだけれど……。"
"2600602-29" = "プレッシャーが大きかったのか、ノドカは半分も食べられなかった。"
