[translation]
"10037060-1" = "第6話;雪中の竹は曲がらず"
"10037060-2" = "[ns] \"すごい光景だね……。\""
"10037060-3-キサキ" = "ふふ、ここの竹林は圧巻じゃろう？"
"10037060-4-キサキ" = "時期によっては、タケノコを収穫することもできるのじゃが。"
"10037060-5-チェリノ" = "タケノコ……？"
"10037060-6-キサキ" = "竹の若芽のことじゃ。#n甘くて柔らかい食感が特徴での。様々な料理に使われておる。"
"10037060-7-キサキ" = "昨日の玄武商会の料理でも使われていたはずじゃが……。"
"10037060-8-チェリノ" = "ああ！あの黄色で薄いアレか！香ばしかったな！"
"10037060-9-ミナ" = "フッ、山海経のタケノコは特に上質だからな。#n朝食に出しても良いと言われるほどだ。"
"10037060-10-トモエ" = "今日はお元気そうでなによりです。"
"10037060-11-キサキ" = "昨日は失礼した。チェリノ書記長も不愉快な思いをさせてしまったの。#nここに謝罪を。"
"10037060-12-チェリノ" = "ん？何のことだ、キサキ門主。"
"10037060-13-キサキ" = "交流会の主催であるというのに、客人のもてなしを怠ってしまったからの。#nすまなかった。"
"10037060-14-ミナ" = "も、門主様……！"
"10037060-15-キサキ" = "ああ、まだそんなこと気にしてたのか。"
"10037060-16-チェリノ" = "せっかくだし、ここで宣言しておくか。"
"10037060-17-チェリノ" = "おいらは、そんな些細なこと気にも留めておらん！"
"10037060-18-マリナ" = "流石です、チェリノ会長！"
"10037060-19-キサキ" = "ふ、ふむ……。"
"10037060-20-キサキ" = "（どこまでが真意なのかはさておいて、これで良かろう。幸い、書記長の気分を害してはいないようじゃ）"
"10037060-21-キサキ" = "書記長の寛大な心に感謝を。#nして、昨日はよく眠れたかの？"
"10037060-22-マリナ" = "ええ、とても素晴らしい寝心地でした。"
"10037060-23-マリナ" = "しかし……なんだか嗅いだことがない匂いがするような……？"
"10037060-24-キサキ" = "ふふ、この香のことかの。マリナ委員長は鼻が利くようじゃな。#nこれは、錬丹術研究会に調合してもらった[ruby=こうやく]香薬[/ruby]じゃ。"
"10037060-25-キサキ" = "心身の疲れを癒す効果があっての……[ruby=そなた]其方[/ruby]らに合えば良いのじゃが……。"
"10037060-26-マリナ" = "うーん……よく、分かるような、分からないような……。"
"10037060-27-キサキ" = "まあ良い。せっかく竹林まで足を運んでくれたのじゃ。良いものを見せてやろう。"
"10037060-28-トモエ" = "良いもの、ですか？"
"10037060-29-ミナ" = "――門主様の言う「良いもの」だと……？あ！"
"10037060-30-キサキ" = "――竹林の名物じゃ。"
"10037060-31-ミナ" = "フッ、期待していいぞ。皆が好きな「あれ」だからな！"
"10037060-32-キサキ" = "さて、行こうかの。"
"10037060-33-マリナ" = "あ、あれは……まさか……！！"
"10037060-34-ミナ" = "どうだ？とても可愛いだろう？"
"10037060-35-マリナ" = "パンダだ！！"
"10037060-36-マリナ" = "マリナ委員長、あまり大きな声を出すと、パンダが驚いて逃げてしまうかもしれませんよ……？"
"10037060-37-マリナ" = "はっ、そうだった！"
"10037060-38-キサキ" = "あやつらはそこまで機敏ではないからの。"
"10037060-39-トモエ" = "（実は山海経に着いた日に牢屋で幼いパンダを見てはいるのですが……）"
"10037060-40-トモエ" = "（その話は……今はしない方がよさそうですね）"
"10037060-41-チェリノ" = "改めて見ても、あの白黒の模様は不思議だなぁ……。"
"10037060-42-キサキ" = "ん？パンダを見たことがあるのか？"
"10037060-43" = "は、はい、資料や写真などで見たことがあります。#n特にマリナ委員長は、熊なら種類を選ばず好んでおりまして。"
"10037060-44-キサキ" = "ふふ、そうか。あやつらも熊じゃからのう。"
"10037060-45-マリナ" = "そういえば、パンダは竹しか食べないと……。"
"10037060-46-キサキ" = "うむ。その上、食べる竹を選り好みするほど偏食での。"
"10037060-47-ミナ" = "一日中ずっと、食っちゃ寝を繰り返すばかりでな……"
"10037060-48" = "[s] \"いいなぁ……そんな生活羨ましいっ！\""
"10037060-49-キサキ" = "せ、先生？"
"10037060-50-ミナ" = "な、なんだか今、深い闇を感じたような……。"
"10037060-51-キサキ" = "……パンダは可愛い。そうじゃろう？"
"10037060-52-マリナ" = "はい！こうやって見ているだけで……！"
"10037060-53-マリナ" = "なんだか、心が落ち着くような気が……！"
"10037060-54-キサキ" = "ふふ、存分に楽しんでくれ。#nもう少し近づいても良いぞ？"
"10037060-55-マリナ" = "本当ですか！？"
"10037060-56-キサキ" = "ミナ、案内を頼む。#nあやつらなら、ある程度は人に慣れておるはずじゃ。"
"10037060-57-ミナ" = "はい、門主様。"
"10037060-58-マリナ" = "では、慎重に近づいてみるとしようか。"
"10037060-59-ミナ" = "あまり近づくと危ないし……距離をとっていけば……。"
"10037060-60-キサキ" = "さて、先生――"
"10037060-61-キサキ" = "……っ！？！？"
"10037060-62-キサキ" = "（いきなり、身体が……！）"
"10037060-63-キサキ" = "（呼吸が……苦しい。頭が……重い……力が……）"
"10037060-64-キサキ" = "（よりによって、何故……今……？）"
"10037060-65" = "[ns] \"き、キサキ！？大丈夫！？\""
"10037060-66-キサキ" = "（先生の声が……遠い。距離が離れておるのか？）"
"10037060-67-キサキ" = "（それとも……）"
"10037060-68-キサキ" = "……先生。"
"10037060-69-キサキ" = "もう……夜かえ？真っ暗じゃ……。"
"10037060-70" = "[ns] （……！）"
"10037060-71" = "[ns] \"…………うん。もう、日が暮れてるよ……。\""
"10037060-72-キサキ" = "……。"
"10037060-73-キサキ" = "…………そう、じゃったか。"
"10037060-74-キサキ" = "……。"
"10037060-75-キサキ" = "先生、頼みが、あるのじゃ。"
"10037060-76-キサキ" = "錬丹術研究会のサヤを……呼んでくれぬか。"
"10037060-77" = "[ns] \"サヤを……？\""
"10037060-78-キサキ" = "ああ……今は、それしか……。"
"10037060-79-キサキ" = "それと……チェリノ書記長と、レッドウィンターの一行を……頼むぞ……。"
"10037060-80-キサキ" = "ミナと一緒に……六和閣まで、案内してくれぬか……。"
"10037060-81" = "[ns1] \"うん……私に任せて。\"\n[ns2] \"でも……もう、夜なのに……？\""
"10037060-82-キサキ" = "……ふふ。"
"10037060-83-キサキ" = "……ふふ。"
"10037060-84-キサキ" = "先生は、やはり、親切じゃのう……。"
"10037060-85-キサキ" = "じゃが……そこまでして…[ruby=わらわ]…妾に[/ruby]、話を合わせる、必要は……ないのじゃぞ……。"
"10037060-86-サヤ" = "……キサキ門主、申し訳ないのだ。"
"10037060-87-サヤ" = "（……？もう着いたのか……？）"
"10037060-88-サヤ" = "でも、門主がはっきり述べるようにと言うから、#nぼく様は素直に答えるしかないのだ……。"
"10037060-89-サヤ" = "（いいや……これは、あの時の記憶……）"
"10037060-90-サヤ" = "だから、よく聞いてほしいのだ。"
"10037060-91-サヤ" = "門主はこれから……一日において動ける時間が極端に少なくなる。"
"10037060-92-サヤ" = "（ああ……あの日、其方はそう言っておった……）"
"10037060-93-サヤ" = "六和閣中まではいかなくても、せめて私室くらいには[ruby=こうやく]香薬[/ruby]を焚いておくのだ。#n効果は薄くても、少しは役に立つかもしれないのだ……。"
"10037060-94-サヤ" = "それと、これからは毎朝この薬を服用するのだ。一日たりとも忘れてはダメなのだ。"
"10037060-95-サヤ" = "他の方法……？うーん……"
"10037060-96-サヤ" = "毎日ストレッチするのをオススメするのだ。#nたとえば、体操とか。全身に血を巡らせることで、多少はマシになるかもしれないから……。"
"10037060-97-サヤ" = "ぼく様の言ったこと、必ず守ってほしいのだ。"
"10037060-98-サヤ" = "ぼく様も……このまま、門主を失いたくないのだ。"
"10037060-99-キサキ" = "（しかし、妙じゃな）"
"10037060-100-キサキ" = "（今朝もちゃんと薬を飲んだはずなのに……）"
"10037060-101-キサキ" = "（……）"
"10037060-102-キサキ" = "（ということは……）"
