[translation]
"10037005-1" = "プロローグ;遠方からの手紙"
"10037005-2" = "今までのあらすじ"
"10037005-3" = "（山海経の特産物――「[ruby=まんねんじん]萬年参[/ruby]」が外部へと密売されていた）"
"10037005-4-レイジョ" = "山海経では、「[ruby=まんねんじん]萬年参[/ruby]」という植物が採れるのですが――"
"10037005-5-レイジョ" = "収穫量が少なく、#n希少価値が高いから外部への持ち出しが厳しく制限されているんです。"
"10037005-6-レイジョ" = "昨今、「萬年参」を[ruby=うち]玄武商会[/ruby]が学園外に密売しているという噂が広まっておりまして……"
"10037005-7" = "（山海経の生徒会に該当する「玄龍門」の門主、[ruby=りゅうげ]竜華[/ruby]キサキは、玄武商会を萬年参の密売犯とし――）"
"10037005-8-キサキ" = "萬年参は山海経でも貴重ゆえ、採取するのにも許可が必要での。"
"10037005-9-キサキ" = "かような特産物が山海経の外に――#nそれも玄龍門の預かり知らぬところで流れておると聞けば、当然、黙ってはおれん。"
"10037005-10-キサキ" = "門主として、看過するわけにはいかぬからな。#nして――これに対しての申し開きはあるかの？"
"10037005-11" = "（玄武商会の会長、[ruby=あけしろ]朱城[/ruby]ルミは、濡れ衣を晴らすべく、#n　シャーレの先生に助けを求めた）"
"10037005-12-ルミ" = "相談というか、お願いというか……"
"10037005-13-ルミ" = "あたしたち玄武商会から、シャーレに依頼があってね。"
"10037005-14" = "（しかし、萬年参を密売したのは、玄龍門の幹部の一人で――）"
"10037005-15-玄龍門の下級幹部" = "あぁ。前々から目障りだったんだ。"
"10037005-16-玄龍門の下級幹部" = "どうにかしてお前を陥れようと思ったが、協力を集めるには金が必要でな。"
"10037005-17" = "（幹部が取引したのは、秘薬の密輸に手を染め、山海経から追放された）"
"10037005-18" = "（七囚人の一人――[ruby=しんたに]申谷[/ruby]カイだった）"
"10037005-19-カイ" = "でも、残念なことに後一歩遅かった。#nすでに新薬の実験は終えたところさ。"
"10037005-20-カイ" = "欲を言えば、もう少しばかり実験データを集めたかったところではあるけど……"
"10037005-21-チェリノ" = "むにゃむにゃ……"
"10037005-22-チェリノ" = "ダメだ、トモエ……プリンの川に、プリンのダムを建てては……プリンが食べられなくなるだろう……"
"10037005-23-チェリノ" = "うぅーん……だが、カステラも、イチゴミルクも……バナナエクレアも……。"
"10037005-24-チェリノ" = "チェリノちゃん？#nまだ、おねむなんですか？"
"10037005-25-チェリノ" = "むにゃむにゃ……。"
"10037005-26-トモエ" = "ふふっ、チェリノちゃんの寝顔は可愛いですね。"
"10037005-27-トモエ" = "もうお目覚めの時間ですよ？"
"10037005-28-チェリノ" = "う～ん……？トモエ……？#nお昼寝中は起こすなと……言ったはずだが……。"
"10037005-29-トモエ" = "もうお昼寝の時間は終わりましたよ？"
"10037005-30-チェリノ" = "んん……？"
"10037005-31-チェリノ" = "うぅーん……あと、5分……。"
"10037005-32-トモエ" = "チェリノちゃん、いえ、チェリノ書記長宛に書類が届いております。#nすぐに処理していただかないと。"
"10037005-33-チェリノ" = "しょるい……？そんなもの、トモエがテキトーにやっておけぇ……#nそれとも、またクーデターか？"
"10037005-34-トモエ" = "いえ、山海経高級中学校の生徒会――玄龍門からの公文書です。"
"10037005-35-チェリノ" = "せんがいきょう……こうきゅうちゅうがっこぉ……？"
"10037005-36-チェリノ" = "なるほど――交流会の申し入れか。"
"10037005-37-チェリノ" = "断る理由などない。おいらが盛大に迎えてやろう！"
"10037005-38-チェリノ" = "しかし、山海経からレッドウィンターまで来るのはなかなか大変そうだな。"
"10037005-39-トモエ" = "いえ、書記長。#nそれが……[ruby=・   ・   ・   ・]私たちが[/ruby]山海経に招待されたのです。"
"10037005-40-チェリノ" = "んん？おいらたちが山海経に行くのか？"
"10037005-41-トモエ" = "そうなります。"
"10037005-42-チェリノ" = "めんどくさ……いや、おいらは忙しいのだ！#nそれに他所の自治区に行ってる間にクーデターでも起こされたらどうするんだ！"
"10037005-43-トモエ" = "チェリノちゃん……これは滅多にないチャンスですよ？#n交流会という名の旅行だと思ってみては？"
"10037005-44-チェリノ" = "りょ、旅行！？"
"10037005-45-チェリノ" = "う、うむ！山海経との交流会だったか？#nおいらに任せておけ！"
"10037005-46-トモエ" = "流石はチェリノ書記長です。#nその毅然としたお姿は、生徒の模範となるに違いありません。"
"10037005-47-チェリノ" = "当然だ！おいらはレッドウィンター連邦学園の生徒会長であり、環境美化部部長兼、書記長兼、運動部代表兼、掃除部部長兼、風紀委員長兼、給食部長兼、そして――"
"10037005-48-チェリノ" = "――今月の最優秀プリン試食家兼、#nカステラ工場を直接指導するチェリノ様だからな！"
"10037005-49-トモエ" = "ええ、その通りです、チェリノ書記長！"
"10037005-50-トモエ" = "うむ……ところで、トモエ。一つ聞きたいんだが。"
"10037005-51-トモエ" = "はい、なんでしょう。"
"10037005-52-チェリノ" = "その……山海経は……どこにあるんだ？"
"10037005-53" = "#video;10037"
