[translation]
"10037020-1" = "第2話;流れ行く水は一処に集まりて"
"10037020-2-チェリノ" = "おぉ……ここが……！"
"10037020-3-トモエ" = "[ruby=せんがいきょう]山海経な[/ruby]のですね！"
"10037020-4-トモエ" = "事前の調査に間違いはないようですね。"
"10037020-5-チェリノ" = "トモエ！あの瓦はなんだ？#n不思議な形をしているぞ！"
"10037020-6-山海経の生徒A" = "（あれが噂の……！）"
"10037020-7-山海経の生徒B" = "（まさか、本当に来るなんて……！）"
"10037020-8-チェリノ" = "ん？おいらたち注目されてないか？"
"10037020-9-マリナ" = "チェリノ会長の威光に目を惹きつけられているのでしょう！流石会長です！"
"10037020-10-チェリノ" = "そ、そうか？へへっ悪い気はしないな。"
"10037020-11-トモエ" = "この雰囲気は……なるほど、やはりそうなのですね。"
"10037020-12-トモエ" = "（やはり……心の準備をしておく必要がありそうですね）"
"10037020-13-玄龍門の構成員A" = "門主様、ご報告いたします。"
"10037020-14-玄龍門の構成員B" = "レッドウィンター連邦学園からの訪問客が、ただいま正門に到着したとのことです。"
"10037020-15-キサキ" = "……そうか。"
"10037020-16-キサキ" = "改めて皆の前で宣言しよう。"
"10037020-17-キサキ" = "此度の交流会は、レッドウィンターにとって――#nひいては山海経にとって重要な意味を持つ場じゃ。"
"10037020-18-キサキ" = "我らの一挙手一投足を見られていると思い――最善を尽くすように。"
"10037020-19-玄龍門の構成員A" = "はっ！かしこまりました、門主様！"
"10037020-20-玄龍門の構成員B" = "肝に銘じます！"
"10037020-21-キサキ" = "……うむ。"
"10037020-22-キサキ" = "では――最初の命じゃ。"
"10037020-23-キサキ" = "訪問客を「玄龍門式」で手厚く迎えるのじゃ。"
"10037020-24-玄龍門の構成員A" = "承知いたしました、門主様っ！"
"10037020-25-玄龍門の構成員B" = "はっ！お任せくださいっ！門主様！"
"10037020-26" = "[s] （みんな、気合いが入りすぎているような……）"
"10037020-27-ミナ" = "始まりましたね、門主様。"
"10037020-28-キサキ" = "うむ。"
"10037020-29-キサキ" = "……。"
"10037020-30-キサキ" = "先生、少し耳を貸してくれるかの？"
"10037020-31" = "（キサキに近づく）"
"10037020-32-キサキ" = "頼みがある。"
"10037020-33-キサキ" = "皆がきちんと任務を全うしているか、先生が見守っていてくれぬか？"
"10037020-34-キサキ" = "無論、信用しておらぬわけではない。"
"10037020-35-キサキ" = "[ruby=わらわ]妾[/ruby]が心配性なだけでの。"
"10037020-36" = "[s] （静かに頷く）"
"10037020-37-ミナ" = "門主様、頼み事なら私に……"
"10037020-38-キサキ" = "（……ミナに任せて、万が一があれば、事をより大きくする可能性があるからのう……）"
"10037020-39-キサキ" = "[ruby=そなた]其方[/ruby]には、より大事なものを任せておるじゃろう？"
"10037020-40-ミナ" = "何のことでしょうか……？"
"10037020-41-キサキ" = "――門主を護衛する任務じゃ。"
"10037020-42-ミナ" = "……！は、はい！お任せください！#n何人たりとも門主様には指一本触れさせませんので！"
"10037020-43-キサキ" = "うむ、頼もしい答えじゃ。任せたぞ。"
"10037020-44-ミナ" = "門主様……！"
"10037020-45-キサキ" = "（……何事もなければ良いのじゃが）"
"10037020-46-玄龍門の構成員A" = "門主様は「玄龍門式」で迎えるようにと仰っていた。"
"10037020-47-玄龍門の構成員B" = "となれば、「アレ」しかないよな？"
"10037020-48-玄龍門の構成員A" = "ああ！「アレ」だな！"
"10037020-49-玄龍門の構成員B" = "ふっふっふっ……山海経式の歓迎を存分に味わってもらおうじゃないか……！"
"10037020-50-玄龍門の構成員A" = "交流会を絶対に成功させなければ！"
"10037020-51-玄龍門の構成員B" = "門主様を失望させるわけにはいかない！行こう！"
"10037020-52" = "取調記録：092-H-8"
"10037020-53" = "担当者：玄龍門の構成員"
"10037020-54" = "容疑者：レッドウィンター連邦学園　3年、[ruby=れんかわ]連河[/ruby]チェリノ。"
"10037020-55-玄龍門の構成員" = "名は？"
"10037020-56-チェリノ" = "ま、待ってくれ！マリナとトモエは？#nみんなどこに行ったんだ？"
"10037020-57-チェリノ" = "おいらは旅行に……いや、交流会に来たんだが！#nまさか……これはクーデターか！？おいらを嵌めたな！？"
"10037020-58-玄龍門の構成員" = "黙れ！聞かれたことにだけ答えろ！"
"10037020-59-チェリノ" = "お、おいらはレッドウィンターの生徒会長であり、環境美化部部長兼、書記長兼、運動部代表兼、掃除部部長兼、風紀委員長兼、給食部長兼――"
"10037020-60-チェリノ" = "そして、今月の最優秀プリン試食家兼、カステラ工場を直接指導するチェリノ様だ！"
"10037020-61-玄龍門の構成員" = "長ったらしい自己紹介だな。#n名前だけでなく、肩書きまで……。"
"10037020-62-玄龍門の構成員" = "というか、兼任が多すぎるだろ……。"
"10037020-63-玄龍門の構成員" = "まあいい。#n趣味は？"
"10037020-64-チェリノ" = "なんて無礼なやつだ！#n交流会を申し入れたのは、お前ら山海経だというのに……！"
"10037020-65-チェリノ" = "おいらをこんな場所に連れてきて、一体何が目的なんだ！？"
"10037020-66-玄龍門の構成員" = "どうしてここに「案内」しているのか、だと？#nそれは門主様から直々に――"
"10037020-67-玄龍門の構成員" = "「玄龍門式」で手厚く迎えるようにと、命じられたからだ！"
"10037020-68-チェリノ" = "これが「玄龍門式」の歓迎なのか！？"
"10037020-69" = "[ns] （……これは）"
"10037020-70" = "[ns] （結構マズいかも……）"
"10037020-71" = "[ns] \"き、キサキ、大変だ！\""
"10037020-72-キサキ" = "何事じゃ？騒々しい。"
"10037020-73-キサキ" = "……一体何が起きておる。"
"10037020-74" = "（取調室で起きたことをキサキに話した）"
"10037020-75-キサキ" = "……ふむ。"
"10037020-76-キサキ" = "ご苦労じゃった、先生。一先ず、事を収めねばな。"
"10037020-77-キサキ" = "今すぐ[ruby=ことづて]言伝[/ruby]を……いや、命令の訂正を。"
"10037020-78-キサキ" = "訪問客を「大切な客人」のように迎えろ、と。"
"10037020-79-ミナ" = "……。"
"10037020-80-ミナ" = "（ま、マズい……訪問客は取調室に連行するものだとばかり！）"
"10037020-81-キサキ" = "先生。少し耳を貸してくれぬか？"
"10037020-82" = "（キサキに近づく）"
"10037020-83-キサキ" = "また、頼み事なのじゃが……。"
"10037020-84" = "[s] （静かに頷く。）"
"10037020-85-キサキ" = "うむ……礼を言う。"
"10037020-86-キサキ" = "……話が早いのは其方の美徳じゃの。"
"10037020-87-キサキ" = "ミナ。"
"10037020-88-ミナ" = "あ、ふぇ、は、はいっ！！門主様！"
"10037020-89-キサキ" = "其方なら……別の対処をしておったかの？"
"10037020-90-ミナ" = "ももももも、もちろんです、門主様！わわわわ、私があのようなヘマをするわけ……！"
"10037020-91-キサキ" = "……うむ。"
"10037020-92-玄龍門の構成員A" = "うぅぅ……門主様に叱られてしまった……。"
"10037020-93-玄龍門の構成員B" = "門主様のあのお声……相当お怒りになってるに違いない……。"
"10037020-94-玄龍門の構成員A" = "で、でも！次をちゃんとすれば、許してくれるって仰ってたからな！"
"10037020-95-玄龍門の構成員B" = "ああ！落ち込んでいる場合じゃない！"
"10037020-96-玄龍門の構成員A" = "大切な客人のように、か……それなら簡単だ！"
"10037020-97-玄龍門の構成員B" = "今度こそ、門主様のためにっ！"
"10037020-98-チェリノ" = "取調室の次は牢屋！？#n一体なんなんだ！？"
"10037020-99-マリナ" = "なぜでしょう……馴染みのある場所のような……"
"10037020-100-マリナ" = "これは一体……交流会自体が最初から私たちを陥れる罠だったのでしょうか。"
"10037020-101-マリナ" = "これが、黒い君主の策……？"
"10037020-102-玄龍門の構成員" = "黙れ！素直に吐いた方が身のためだぞ！"
"10037020-103-玄龍門の構成員" = "さもなければ……！"
"10037020-104-マリナ" = "はっ……！それは、まさか！？"
"10037020-105-チェリノ" = "ど、どうしたのだ？マリナ委員長。"
"10037020-106-玄龍門の構成員" = "レッドウィンターの生徒といえど、この動物が何かは知っているはずだ！"
"10037020-107-玄龍門の構成員" = "そう、山海経名物――パンダだ！"
"10037020-108-玄龍門の構成員" = "お前たちが陰謀を吐かないのであれば……"
"10037020-109-玄龍門の構成員" = "パンダが食っている竹を、この場で奪ってやるっ！"
"10037020-110-マリナ" = "な、なんて邪悪な……！パンダに罪はないというのに！？"
"10037020-111-マリナ" = "何故パンダを……まだ幼いのに……！#n貴様に人の心はないのか――！"
"10037020-112-玄龍門の構成員" = "それがイヤなら全部白状するんだな！#nふふ……こうやって、こいつが食っている竹を……！"
"10037020-113-子パンダ" = "キュゥ！？"
"10037020-114-マリナ" = "やめろぉぉぉぉぉぉぉぉ！"
"10037020-115" = "[ns] （マズい！マズい！）"
"10037020-116-ミナ" = "も、門主様！？"
"10037020-117" = "[s1] \"キサキ！しっかりして！\"\n[s2] \"まだ交流会は始まったばかりだよ！？\""
"10037020-118-キサキ" = "……ああ、そうじゃったな。"
"10037020-119-キサキ" = "ミナ。"
"10037020-120-ミナ" = "はいっ！門主様！"
"10037020-121-キサキ" = "こう伝えるのじゃ。#n#nレッドウィンターの訪問客を「玄龍門の門主」のように迎えろ、と。"
"10037020-122-ミナ" = "そ、それはつまり……！？"
"10037020-123-キサキ" = "時間が無い。はよう行け。"
"10037020-124-ミナ" = "は、はいっ！"
"10037020-125-キサキ" = "……一つ、聞きたいのじゃが。"
"10037020-126" = "[s] \"うん、何でも聞いて。\""
"10037020-127-キサキ" = "妾の命令は、分かりにくいかの？"
"10037020-128-キサキ" = "そんなに理解しづらいのじゃろうか？"
"10037020-129" = "[s] \"そういうわけじゃないと思うよ……。\""
"10037020-130-キサキ" = "であれば、何故……理由が分かるかの？"
"10037020-131" = "[s] \"……。\""
"10037020-132-キサキ" = "はぁ……"
"10037020-133-キサキ" = "皆に賓客をもてなしてほしいだけなのじゃが……。"
"10037020-134-チェリノ" = "一体なんなんだ！おいらは牢屋を体験するために山海経まで来ているのではないぞ……！"
"10037020-135-トモエ" = "落ち着いてください、チェリノちゃん……いいえ、チェリノ書記長。#nこういう時こそ、寛大な心を見せる時です。"
"10037020-136-トモエ" = "なにやら[ruby=・   ・   ・]些細な[/ruby]誤解があったようですが、今は疑いも晴れていますから。"
"10037020-137-マリナ" = "些細、ですか……トモエ秘書室長……。"
"10037020-138-マリナ" = "パンダを……あんな目に遭わせるなんて……#nしかも、まだ幼いのに……！"
"10037020-139-トモエ" = "ふふっ、言葉には様々な意味が含まれるものですよ。"
"10037020-140-トモエ" = "それに、一連の出来事は、いずれ交渉材料として使えるかもしれませんから。"
"10037020-141-トモエ" = "ひとまず、玄龍門からいただいたこの服を着てみましょう。"
"10037020-142-チェリノ" = "たしかに、レッドウィンターの制服だと暑いな。"
"10037020-143-トモエ" = "さあ、お着替えの時間ですよ、チェリノちゃん。"
"10037020-144-玄龍門の構成員A" = "レッドウィンター連邦学園御一行様、ご到着！"
"10037020-145-玄龍門の構成員B" = "ご到着！！"
"10037020-146-マリナ" = "うぅ……ほ、本当にこれでいいのか……？裾が開きすぎているが……！"
"10037020-147" = "[ns] \"えっ、別人……！？\""
"10037020-148-マリナ" = "ど、どうして先生がここに……！って、私のことを忘れたのか！？#nまさか、先生も酷い仕打ちを受けて！？！？"
"10037020-149" = "[s] \"あ、そういう意味ではなくて……似合ってるね、マリナ。\""
"10037020-150-マリナ" = "なっ……か、からかわないでくれ！先生！"
"10037020-151-トモエ" = "マリナ委員長。あれは先生なりの褒め言葉なんですよ。"
"10037020-152" = "[s3] \"トモエは、なんというか……。\"\n[s4] \"着こなしてるね！すごく似合ってるよ。\""
"10037020-153-トモエ" = "ふふ、ありがとうございます先生。"
"10037020-154-トモエ" = "以前から思っていたのですが……先生は人心掌握に長けているのですね。#n先生にもアジテーションの素質があるのかもしれません。ふふ。"
"10037020-155" = "[s] \"それは遠慮しておくね……。\""
"10037020-156-チェリノ" = "むぅ……！カムラッド！おいらのこと忘れてないか！？"
"10037020-157" = "[s5] \"チェリノもよく似合っているよ。\"\n[s6] \"特に、三つ編みが新鮮でいいね！\""
"10037020-158-チェリノ" = "そ、そうか？えへへ……やはりカムラッドは見る目があるな！"
"10037020-159-チェリノ" = "ん？髭……？#nはっ！と、トモエ！"
"10037020-160-チェリノ" = "……誰も何も見ていない。そうだな、トモエ？"
"10037020-161-トモエ" = "はい、書記長。"
"10037020-162-キサキ" = "（あのつけ髭は、レッドウィンターの文化なのじゃろうか……）"
"10037020-163-キサキ" = "（嗚呼、交流会を開いた甲斐があった。早速見聞を広げることができたからの）"
"10037020-164-キサキ" = "遠路はるばるよく山海経に参った――其方らを歓迎しよう。"
"10037020-165-キサキ" = "妾の申入れを承諾してくれたこと、感謝する。#nチェリノ書記長、トモエ秘書室長、マリナ委員長。"
"10037020-166-キサキ" = "妾は「玄龍門」の門主、[ruby=りゅうげ]竜華[/ruby]キサキじゃ。"
"10037020-167-チェリノ" = "お初にお目にかかります、キサキ門主。"
"10037020-168-トモエ" = "さあ、チェリノちゃん。ここは書記長としての威厳を見せる時です！#n事前に教えた……いえ、練習していた通りに……。"
"10037020-169-チェリノ" = "う、うん！？あ、ああ……！"
"10037020-170-チェリノ" = "手厚い歓迎、感謝するぞ！キサキ門主。"
"10037020-171-チェリノ" = "おいらは、レッドウィンター連邦学園の生徒会長であり、環境美化部部長兼、書記長兼、運動部代表兼、掃除部部長兼、風紀委員長兼、給食部長兼――"
"10037020-172-チェリノ" = "そして、今月の最優秀プリン試食家兼、カステラ工場を直接指導するチェリノ様だ！"
"10037020-173-キサキ" = "（長い自己紹介……そして「手厚い歓迎」、か……言葉に棘があるが……）"
"10037020-174-キサキ" = "（致し方あるまい。此方の落ち度じゃからの）"
"10037020-175-キサキ" = "（戦いの火蓋は落とされたも同然、か。話に聞いてはおったが、只者ではないの。チェリノ書記長）"
"10037020-176-チェリノ" = "どうだった？おいら、ちゃんと言えてたよな？"
"10037020-177-トモエ" = "はい、よくできました。"
