[translation]
"10037100-1" = "第10話;天を抱き、麓へ辿りし"
"10037100-2-？？？" = "――何をめそめそしている！"
"10037100-3-カグヤ" = "なんだ！？"
"10037100-4-チェリノ" = "そんなの、どうだっていいだろう！"
"10037100-5-チェリノ" = "すべての生徒には、意見を表する権利がある！"
"10037100-6-チェリノ" = "そしてすべての生徒会長には、その意見を聞き入れ、学園を導く権利がある！"
"10037100-7-カグヤ" = "い、一体何を！？"
"10037100-8-チェリノ" = "つまり――お前らのやっていることは、朝の挨拶にもならないということだ！"
"10037100-9-チェリノ" = "伝統を守らない？変化を起こした？"
"10037100-10-チェリノ" = "お前たちがやっている行為だって、「変化」じゃないのか！？"
"10037100-11-カグヤ" = "わ[ruby=わたし]、私た[/ruby]ちは、ただ門主様に諫言を述べているだけで……！"
"10037100-12-トモエ" = "しかし、その手段として選んだのが「極端な方法」と「変化」である、と。#nそうは思いませんか？"
"10037100-13-京劇部員A" = "い、言われてみれば、たしかに……！？"
"10037100-14-トモエ" = "玄龍門の門主は山海経を守護すべき……ええ、たしかに仰る通りです。"
"10037100-15-トモエ" = "であれば、京劇部の部長は京劇部を守るべきではありませんか？"
"10037100-16-トモエ" = "今のカグヤ様がやっていることは――本当に京劇部のためになるのでしょうか？"
"10037100-17-トモエ" = "私からすれば、少し疑問ですけれど。"
"10037100-18-京劇部員A" = "え、あ、その……。"
"10037100-19-トモエ" = "玄龍門の皆さんも同じです。#n山海経を守るのは大切です。"
"10037100-20-トモエ" = "ですが、皆さんは山海経の一部である「玄龍門」という組織の構成員です。"
"10037100-21-トモエ" = "であれば、まず組織のトップを守るのが、皆さんの真の義務ではありませんか？"
"10037100-22-玄龍門の構成員D" = "それは……そうだな……。"
"10037100-23-玄龍門の構成員D" = "一理あるけど……彼女はどうして山海経と玄龍門の事情に詳しいんだ……？"
"10037100-24-トモエ" = "それは、さきほど書記長も仰っていた通り――"
"10037100-25-トモエ" = "レッドウィンターではこの程度の騒動など、挨拶にもならないくらい――いつもの事、ですから。"
"10037100-26-マリナ" = "我らレッドウィンターの厳冬の前では、みなが公平である……"
"10037100-27-マリナ" = "そして、それは我らの心を熊のように強靭なものとするのだ！"
"10037100-28-マリナ" = "チェリノ会長！私が道を開きます！"
"10037100-29-チェリノ" = "うむ！頼もしいな、マリナ委員長！#n我がレッドウィンターの流儀を見せてやるのだ！"
"10037100-30-マリナ" = "はい！さぁ、突撃だ！#nウラー！"
