[translation]
"10053010-1" = "第1話;ツチノコ探し"
"10053010-2-コノカ" = "長い間！！大変！お世話になったっす！！！\r\n\r\n\r\n"
"10053010-3-カンナ" = "……何のつもりだ？\r\n"
"10053010-4-コノカ" = "今日から旅に出るっす。"
"10053010-5-コノカ" = "1週間経っても音沙汰がなかったら、そのままいなくなったものとして――"
"10053010-6-コノカ" = "……って、隣の方はどなたっすか？#nはじめまして～"
"10053010-7-コノカ" = "お前が騒々しく入ってこなければ、今頃は紹介が済んでいたんだがな。\r\n"
"10053010-8-カンナ" = "こちらはシャーレの[USERNAME]先生だ。"
"10053010-9-コノカ" = "そして、こっちのだらしないのが我々公安局の副局長、[ruby=しま]志真[/ruby]コノカです。"
"10053010-10-カンナ" = "先生！おぉ～この方が！#nいやぁ、話は姉御からよく聞いてるっすよ！"
"10053010-11-コノカ" = "てか先生……なんで手錠はめられてるんすか？"
"10053010-12" = "[s1] \"その……誤解しないでほしいんだけど……。\"\n[s2] \"ちょっとした行き違いがあったというか。\""
"10053010-13-カンナ" = "ブラックマーケットで、生徒の卒業アルバムを取引していたと連絡がありまして……#n「誤解」について詳しくお話を伺いたく。\r\n"
"10053010-14-カンナ" = "とはいえ先生の事ですので、業務上必要なものだったのかもしれませんし……。"
"10053010-15-カンナ" = "…………。\r\n"
"10053010-16-カンナ" = "お話を伺ったうえで、対応を決めようかと。\r\n"
"10053010-17" = "[s3] \"大丈夫、探られて痛い腹はないよ！\"\r\n[s4] \"イオリなら分かってくれる！\""
"10053010-18-カンナ" = "はぁ……まだ詳細を何も伺っていませんのでなんとも。#n発言にはお気をつけください。\r\n"
"10053010-19-カンナ" = "それで、コノカ。"
"10053010-20-カンナ" = "旅とは何のことだ？\r\n"
"10053010-21-コノカ" = "ああ、その話っすか。\r\n\r\n"
"10053010-22-コノカ" = "笑わないで聞いてほしいんすけど――\r\n\r\n"
"10053010-23-コノカ" = "1週間以内にツチノコを捕まえなきゃならないんすよ！！\r\n\r\n"
"10053010-24-コノカ" = "ツチノコ……？\r\n\r\n"
"10053010-25-コノカ" = "それは……都市伝説の？\r\n\r\n"
"10053010-26-コノカ" = "そうっす！そのツチノコっす！\r\n\r\n\r\n\r\n\r\n"
"10053010-27-コノカ" = "伝説の未確認生物……だったか。\r\n"
"10053010-28-コノカ" = "ですです！目撃談はあるものの、未だに捕まっていない……まさに未確認生物界のラスボス的な存在っす！\r\n\r\n\r\n\r\n\r\n"
"10053010-29-コノカ" = "それに、莫大な懸賞金がかけられてて……なんと総額1億円！#n歩く……いや、這う金塊と言っても過言じゃないっす！\r\n\r\n\r\n"
"10053010-30-コノカ" = "……なるほど。\r\n\r\n"
"10053010-31-コノカ" = "少し踏み込んだ質問になるが……。\r\n"
"10053010-32-コノカ" = "もしかして、金銭的な事情を抱えていたりするのか？\r\n"
"10053010-33-コノカ" = "え？まさかぁ。#nあたしが金目当てで動くように見えます？\r\n\r\n\r\n\r\n"
"10053010-34-コノカ" = "……まぁ、違うだろうな。\r\n"
"10053010-35-コノカ" = "はぁ……となると……#nまたジンクス絡みか……。\r\n\r\n\r\n"
"10053010-36-コノカ" = "仕事に穴を開けることになってしまうんすけど……。\r\n\r\n\r\n"
"10053010-37-コノカ" = "あぁ、心配しなくていい。#n端から止めるつもりはない。\r\n"
"10053010-38-コノカ" = "どちらかといえば、お前は働きすぎだ。休息は大切だ。\r\n"
"10053010-39-コノカ" = "ただし――\r\n\r\n"
"10053010-40-コノカ" = "ただし……？\r\n\r\n\r\n"
"10053010-41-コノカ" = "行くなら先生と一緒に、だ。\r\n"
"10053010-42-コノカ" = "はぇ？\r\n\r\n\r\n\r\n"
"10053010-43" = "[s] \"……私？\""
"10053010-44-コノカ" = "先生、少しよろしいですか？\r\n"
"10053010-45" = "この旅に同行していただけるのであれば、今回の件は不問にいたします。\r\n\r\n"
"10053010-46" = "[s5] \"し、司法取引か！？\"\r\n[s6] \"私は無実だよ！イオリに電話させて！\"\r\n"
"10053010-47-カンナ" = "違います。これは私の個人的なお願いです。\r\n\r\n"
"10053010-48-カンナ" = "あれでいて、コノカは問題児というわけではありません。まあ、行動に多少問題はありますが。\r\n\r\n"
"10053010-49-カンナ" = "見かけによらず真面目で、2年生で副局長を務めるほど優秀です。#n私とは違って社交的ですし、部下からの信頼も厚い。\r\n\r\n"
"10053010-50-カンナ" = "ただ、特定の話になると途端に目の色が変わ……過敏になる傾向がありまして。#nそれが――\r\n\r\n"
"10053010-51-カンナ" = "「迷信」の話、です。"
"10053010-52-コノカ" = "いや～、まさか先生が同行してくださるとは。\r\n"
"10053010-53-コノカ" = "念のため、とか言ってたけど姉御もほんと過保護っすよねぇ。"
"10053010-54-コノカ" = "あたしってば愛されてるな～"
"10053010-55-コノカ" = "そう思いません？あははっ！\r\n"
"10053010-56" = "[s7] \"そ、そうだね！\"\r\n[s8] （お目付け役だけど……）"
"10053010-57-コノカ" = "あ、そうそう。"
"10053010-58-コノカ" = "今回、一人旅じゃないんすよ。#nまぁ先生がいるから一人旅じゃないんすけど。\r\n"
"10053010-59-コノカ" = "「ぐるみん」と「モー所長」が一緒っす。"
"10053010-60" = "[s9] \"ぐるみんとモー所長……？\"\r\n[s10] \"すごく個性的な名前だね……。\""
"10053010-61-コノカ" = "名前じゃなくてIDっすよ、ID。\r\n"
"10053010-62" = "[s11] \"ネットの知り合いってこと？\"\r\n[s12] \"危ない人だったらどうするの……？\""
"10053010-63-コノカ" = "はぇ？\r\n"
"10053010-64-コノカ" = "…………。"
"10053010-65-コノカ" = "ぷっ、あははっ！あははははっ！！！\r\n\r\n"
"10053010-66-コノカ" = "はーっ、すみません、笑いすぎたっす。\r\n"
"10053010-67-コノカ" = "先生、あたしを誰だと思ってるんすか？"
"10053010-68-コノカ" = "そういう危ない連中を捕まえるのが、あたしの仕事っすよ。\r\n"
"10053010-69-コノカ" = "まぁ、でも。今回は完全に初対面ってわけでもないんすけどね。"
"10053010-70-コノカ" = "知り合ったのはSNSですけど、何回かオフ会もしてるんで。"
"10053010-71-コノカ" = "先生はこういうの、興味ないっすか？"
"10053010-72-コノカ" = "都市伝説とか不思議体験とか、そういう話題が好きな人向けのSNSがあるんすよ。"
"10053010-73-コノカ" = "最初は事件のモニタリング目的で始めたんすけど、意外と掘り出し物も多くて……。\r\n"
"10053010-74-コノカ" = "お、着いたみたいっすね。#nんじゃ、続きはまた後ほど。"
"10053010-75-コノカ" = "はぁ……。"
"10053010-76-コノカ" = "聞いてはいたけど……ほんとド田舎っすねぇ。\r\n"
"10053010-77-レナ" = "あ、来た。\r\n\r\n\r\n\r\n\r\n"
"10053010-78-レナ" = "おや……1人、増えていないかい？\r\n\r\n\r\n\r\n\r\n"
"10053010-79-レナ" = "あれ、本当だ。\r\n\r\n\r\n\r\n\r\n"
"10053010-80-レナ" = "ん……？\r\n"
"10053010-81-レナ" = "えっ！？なんで先生がここにいるの！？\r\n\r\n\r\n"
