[translation]
"10053130-1" = "後日談その4;アイアン・メイデン"
"10053130-2-カンナ" = "……それで。\r\n"
"10053130-3-公安局の生徒A" = "これは何の騒ぎだ？\r\n\r\n"
"10053130-4-公安局の生徒A" = "その……問題児が自首しに来たそうです。\r\n\r\n\r\n\r\n"
"10053130-5-公安局の生徒A" = "自首？そんな酔狂なことをするやつがいるわけ――\r\n\r\n"
"10053130-6-公安局の生徒A" = "いえ、それが、コノカ副局長が送ってきたみたいなんです。\r\n\r\n\r\n"
"10053130-7-チンピラA" = "うちらは生まれ変わることに決めたんだ！\r\n\r\n\r\n\r\n"
"10053130-8-チンピラA" = "まぁ、あんな怪物みたいなヤツとはもう戦いたくないってだけなんだけど……。\r\n\r\n\r\n"
"10053130-9-公安局の生徒A" = "……あいつ、休暇中じゃなかったか？\r\n"
"10053130-10-公安局の生徒A" = "まあ、コノカが寄越したなら間違いないだろう。\r\n\r\n"
"10053130-11-公安局の生徒A" = "自首を申し出た生徒は一時的に拘留。犯した罪を確認して、適切に処理するように。\r\n"
"10053130-12-公安局の生徒A" = "分かりました。\r\n\r\n\r\n\r\n"
"10053130-13-公安局の生徒A" = "……あれ？局長が尋問しないんですか？いつもなら――\r\n"
"10053130-14-公安局の生徒A" = "今は大事なお客様を応対中だろ。\r\n\r\n\r\n"
"10053130-15-公安局の生徒A" = "大事なお客様？……誰？\r\n\r\n"
"10053130-16-ミスズ" = "……失礼。外が少々騒がしくて。\r\n\r\n"
"10053130-17-ミスズ" = "いえいえ、とはいえ、むしろ感心しましたよ。#nえへへ……さすがはヴァルキューレの誇り、公安局と言うべきでしょうか……。\n\n\n\n\n"
"10053130-18-ミスズ" = "副局長さんも、休暇中なのに仕事熱心みたいで……。\r\n\r\n\r\n"
"10053130-19-ミスズ" = "あまりからかわないでください。\r\n\r\n\r\n"
"10053130-20-ミスズ" = "激務という点では、ヴァルキューレのどの部署も変わりませんよ。\r\n\r\n\r\n"
"10053130-21-ミスズ" = "ましてや「火に落ちれば消防局、人に落ちれば矯正局」と呼ばれる2局です。\r\n\r\n"
"10053130-22-ミスズ" = "謙遜も過ぎれば、聞く方も困るものですよ――[ruby=・]矯[/ruby][ruby=・]正[/ruby][ruby=・]局[/ruby][ruby=・]長[/ruby]殿。"
"10053130-23-ミスズ" = "えへへ……他の方々も、公安局長みたいに考えてくだされば嬉しいんですけどねぇ。\r\n"
"10053130-24-ミスズ" = "もしも、外にいらした皆さんが……まとめて矯正局に来ることになったら……。"
"10053130-25-ミスズ" = "もしかすると……ちょっとだけ忙しくなるかも……えへへ……。\r\n"
