[translation]
"2005705-1" = "肩を並べて"
"2005705-2" = "（アカネとの待ち合わせ場所に到着した）"
"2005705-3" = "（そこは、人の気配が感じられない空き教室だった）"
"2005705-4-？？？" = "――私は誰でしょう？"
"2005705-5" = "[s] \"！？！？！？\""
"2005705-6" = "[ns] \"あ、アカネ！！？？\""
"2005705-7-アカネ" = "ふふ、正解です♪"
"2005705-8-アカネ" = "いらっしゃいませ、先生。お待ちしておりました。"
"2005705-9-アカネ" = "あらあら……ずいぶんと驚かせてしまったみたいですね。#n失礼しました。"
"2005705-10" = "[s1] \"大丈夫だよ。\"\n[s2] \"ところでここは？\""
"2005705-11-アカネ" = "ああ、この教室は……。"
"2005705-12-アカネ" = "……ふふ。"
"2005705-13-アカネ" = "今から、2時間ほど貸切申請をしたので――誰も来ません。"
"2005705-14-アカネ" = "どうされたのですか、そんなに戸惑って……。"
"2005705-15-アカネ" = "もしかして私、信用されていないのでしょうか？"
"2005705-16" = "[s] \"違うよ！信用していないわけじゃなくて……！\""
"2005705-17-アカネ" = "それなら――問題ないのでは？"
"2005705-18-アカネ" = "私も……先生を、誰よりも信じておりますから。"
"2005705-19" = "（アカネの有無を言わさぬやわらかな声に、頷くことしかできなかった……）"
"2005705-20-アカネ" = "ここへ先生をお呼びしたのは……。"
"2005705-21-アカネ" = "前回、先生にご指導いただいたおかげで変わることができた私の姿をお見せしたいと思ったからです。"
"2005705-22-アカネ" = "でも、口で伝えるだけでは十分に表現できないと思ったので……#n先生には、少し特別な方法でお伝えしようかな、と。"
"2005705-23" = "[s3] \"それなら、なおさら二人きりの教室じゃない方が……。\"\n[s4] \"いいんじゃないかな？\""
"2005705-24-アカネ" = "そこで、私はこう考えたのです。"
"2005705-25-アカネ" = "百聞は一見に如かず、と言うではありませんか？"
"2005705-26-アカネ" = "ですので、先生には直接お見せしようと思いまして。"
"2005705-27-アカネ" = "方法は――"
"2005705-28-アカネ" = "ふふ。"
"2005705-29-アカネ" = "先生……。"
"2005705-30-アカネ" = "今から、私たちは――"
"2005705-31-アカネ" = "[ruby=・]同[/ruby][ruby=・]級[/ruby][ruby=・]生[/ruby]、ということで。"
"2005705-32" = "[ns] \"！？！？！！！！！\""
"2005705-33" = "（そうしてアカネと「同級生ごっこ（？）」をすることになった）"
"2005705-34" = "（果たしてこれが、生徒との正しい付き合い方なのか悩んでいたところ――）"
"2005705-35-？？？" = "だーれだ？"
"2005705-36" = "[s] \"アカネ……？\""
"2005705-37-アカネ" = "ふふ、せいかーい。"
"2005705-38-アカネ" = "どうしたの？"
"2005705-39-アカネ" = "[USERNAME]さん？"
"2005705-40-アカネ" = "ああ、メガネ？"
"2005705-41-アカネ" = "ちょっとイメチェンしてみたんだけど……。"
"2005705-42-アカネ" = "[USERNAME]さんは、メガネの方がよかった？#n頑張ってコンタクトつけたのになぁ。残念。"
"2005705-43" = "[s] \"そんなことはないです。\""
"2005705-44-アカネ" = "ふふっ。良かった。"
"2005705-45-アカネ" = "そういえば、さっき――"
"2005705-46" = "（アカネは楽しそうに、話を続けていった）"
"2005705-47" = "（話していると、本当に自分がアカネの同級生になったような感じがした）"
"2005705-48-アカネ" = "……こんな風に接せるなら、どうして今までやってこなかったのかって思ってたりする？"
"2005705-49-アカネ" = "……。"
"2005705-50-アカネ" = "私、今でもそんなに自信ないんだよ。"
"2005705-51-アカネ" = "今こうして[USERNAME]さんに見せてる姿だって、演じてる自分だと思ってる。"
"2005705-52-アカネ" = "……見せたい自分を演じるのって、きっと当たり前のことだと思う。#nでも――"
"2005705-53-アカネ" = "私はたぶん……怖いんだと思う。"
"2005705-54" = "[s] \"みんなに本当の姿を知られることが？\""
"2005705-55-アカネ" = "似てるけど……ちょっと違うかな。"
"2005705-56-アカネ" = "……自分自身が一体誰なのか。#n「私が分かっていないこと」をみんなに知られるのが、怖いの。"
"2005705-57-アカネ" = "他人の期待に応えることは、できると思う。"
"2005705-58-アカネ" = "だけど自分がどんな人間なのか、いくら知ろうとしても見えてこない。"
"2005705-59-アカネ" = "空気を読んで話すことは、たぶんできてるんじゃないかな。#nその人の気分が悪くならないように言葉を選ぶとか、そういうの。"
"2005705-60-アカネ" = "……メイドとして、欠かせないことでもあるし。"
"2005705-61-アカネ" = "でも、それは相手が望むものであって、私の中身を見せているわけじゃないでしょ？"
"2005705-62-アカネ" = "……私の中に何があるのか、自分でもまだよく分かってないんだもん。"
"2005705-63-アカネ" = "だから空っぽなんだと思う。いくら会話をしても、適切な言葉を口にしても。"
"2005705-64-アカネ" = "……そこから先に、進めない。"
"2005705-65-アカネ" = "見えない壁を作っているのは自分自身……それくらい分かってる。#nでも、どうやったらそれを壊せるのか分からないの。"
"2005705-66-アカネ" = "[USERNAME]さんの言う通り、少しずつ歩み寄ってみたりもした。#nだから少しずつ変わっているような気はしているけど。"
"2005705-67-アカネ" = "でも、それもその場しのぎに過ぎないって思ったりするんだよね。"
"2005705-68-アカネ" = "……ごめんね。せっかく相談に乗ってもらったのに。"
"2005705-69-アカネ" = "一緒に色々考えてくれたのに、こんなことしか言えなくて。"
"2005705-70-アカネ" = "……全部、無駄になっちゃった。"
"2005705-71-アカネ" = "どうして、こうなっちゃうのかな……。"
"2005705-72" = "[ns] \"こうして話してくれて、ありがとう。\""
"2005705-73-アカネ" = "……うん。"
"2005705-74-アカネ" = "だって……。"
"2005705-75-アカネ" = "……[USERNAME]さんは、特別だから。"
"2005705-76-アカネ" = "数少ない、心の内を打ち明けても大丈夫な――"
"2005705-77-アカネ" = "ううん、たぶん唯一の……。"
"2005705-78-アカネ" = "人、だから……。"
"2005705-79" = "[s5] \"うん。少しずつ、私のような存在を増やせていけたらいいね。\"\n[s6] \"もちろん時間はかかるだろうし、大変だけど。\"\n[s7] \"それに、私だってアカネの悩みに対して自信を持って答えられるわけでもない。\""
"2005705-80-アカネ" = "……[USERNAME]さんも……？"
"2005705-81-アカネ" = "……。"
"2005705-82-アカネ" = "そっか……。"
"2005705-83-アカネ" = "[USERNAME]さんも……同じ立場で話せるような人は――"
"2005705-84" = "[s] \"アカネがこうやって私に悩みを打ち明けてくれて、本当に嬉しい。\""
"2005705-85-アカネ" = "……。"
"2005705-86-アカネ" = "ふふ。"
"2005705-87-アカネ" = "あのね、時々考えるんだ。"
"2005705-88-アカネ" = "私たちが違う形で、違う時間に、違う関係で出会っていたらって。"
"2005705-89-アカネ" = "そうしたら――どんなふうに過ごしていたのかな。"
"2005705-90" = "[s] \"今は違うの？\""
"2005705-91-アカネ" = "ふふっ。"
"2005705-92-アカネ" = "そうだね、うん。#nたしかに、今はそう。"
"2005705-93-アカネ" = "……。"
"2005705-94-アカネ" = "あの……[USERNAME]さん。"
"2005705-95" = "[s] \"どうしたの？\""
"2005705-96-アカネ" = "そこにいてね。"
"2005705-97" = "（なぜかと聞こうとした瞬間――）"
"2005705-98-アカネ" = "えいっ♪"
"2005705-99" = "[ns] \"！！？？！！！！！？？？\""
"2005705-100" = "（五感全てがアカネで満たされていく――）"
"2005705-101-アカネ" = "しーっ。"
"2005705-102-アカネ" = "声、あんまり出さないでね。#n聞かれちゃうかもしれないから。"
"2005705-103-アカネ" = "……ありがとう、[USERNAME]さん。"
"2005705-104-アカネ" = "そう言ってくれて――"
"2005705-105-アカネ" = "こうして私の話をずっと聞いてくれて。"
"2005705-106-アカネ" = "本当に、嬉しかった。"
"2005705-107-アカネ" = "うん……心の底からそう思う。"
"2005705-108-アカネ" = "……。"
"2005705-109" = "[s] \"……。\""
"2005705-110-アカネ" = "こんにちは、先生。"
"2005705-111" = "[s] \"やあ、アカネ。\""
"2005705-112" = "[wa:350]― [log=아카네 교복]ふふっ。[/log]"
"2005705-113" = "― [log=아카네 교복]思っていたより……[/log]"
"2005705-114" = "― [log=아카네 교복]気恥ずかしいものですね。[/log]"
"2005705-115" = "[wa:1530]― [log=아카네 교복]自分に対して、[wa:2200]素直になる……。[/log]"
"2005705-116" = "― [log=아카네 교복]どうにも[wa:1100]慣れない感覚です。[/log]"
"2005705-117" = "[ns] \"ま、まあ初めてのことだろうし……？\""
"2005705-118" = "[wa:520]― [log=아카네 교복]ええ、[wa:1330]仰る通りです。[/log]"
"2005705-119" = "― [log=아카네 교복]私にとって、[/log]"
"2005705-120" = "― [log=아카네 교복]必要なことだったのだと思います。[/log]"
"2005705-121" = "[wa:530]― [log=아카네 교복]先生には[wa:1630]色々と[wa:900]ご迷惑をおかけしてしまいました。[/log]"
"2005705-122" = "― [log=아카네 교복]それでも、[wa:1910]先生と出会えた私は[wa:3240]やはり――[/log]"
"2005705-123" = "― [log=아카네 교복]ええ、[wa:1240]本当に[wa:1550]幸運だったと思っています。[/log]"
"2005705-124" = "[wa:1850]― [log=아카네 교복]すべては流れ、[/log]"
"2005705-125" = "― [log=아카네 교복]いずれ[wa:360]忘れられていくのでしょう。[/log]"
"2005705-126" = "― [log=아카네 교복]今[wa:810]この瞬間でさえ、[wa:2830]いつかは……。[/log]"
"2005705-127" = "[wa:1700]― [log=아카네 교복]ですが、[wa:1550]私は覚えています。[/log]"
"2005705-128" = "― [log=아카네 교복]たとえ[wa:530]先生が[wa:470]忘れてしまったとしても。[/log]"
"2005705-129" = "― [log=아카네 교복]本当に大切なものは、[/log]"
"2005705-130" = "― [log=아카네 교복]決して失われませんから。[/log]"
"2005705-131" = "（教室に入った時と同じように）"
"2005705-132" = "（アカネは初めからこの場にいなかったかのように、いなくなっていた）"
"2005705-133" = "（全てが夢だったのではないか、とも思ったけれど）"
"2005705-134" = "（アカネが残していったものが、決してそうではないと無言で語っていた……）"
