[translation]
"2005706-1" = "最高のお掃除方法"
"2005706-2-アカネ" = "それで、設置しておいたブロック型爆薬が――"
"2005706-3" = "[s] \"えっと……それはいつ設置したの……？\""
"2005706-4-アカネ" = "もちろん、作戦に突入した際に。"
"2005706-5" = "[s1] （最初から爆破する気満々だったんだ）\n[s2] （と返すのは流石に……）"
"2005706-6-アカネ" = "「お掃除」自体は問題なく進められたのですが……。"
"2005706-7-アカネ" = "どうしても、事後処理の費用が嵩むと怒られてしまって……。"
"2005706-8-アカネ" = "部長はそんなこと気にしなくていいと仰るのですが、いつまでもこのままではいられません。"
"2005706-9-アカネ" = "私自身も、パターンが固定化するのは望ましくありません。"
"2005706-10-アカネ" = "それに、「お掃除魔」だと思われたくもないですし……。"
"2005706-11" = "[s] （一応、自覚はあったんだ……）"
"2005706-12-アカネ" = "一体どうすれば良いのでしょう……。"
"2005706-13-アカネ" = "私としても、平和的解決を望む気持ちはあるのですが……。"
"2005706-14-怯える市民A" = "ひゃぁ！？な、なんだ一体！？"
"2005706-15-怯える市民C" = "ブラックマーケットの近くだって分かっていたのに――"
"2005706-16-怯える市民C" = "うう……早く帰りたい。誰か助けてくれー！"
"2005706-17-組織の行動隊長" = "うるせえぞ！騒いでるのはどいつだ！"
"2005706-18-組織の行動隊長" = "静かにしねえと、新作ライフル弾の――"
"2005706-19-組織の行動隊長" = "死ぬまで脇腹と足の裏がくすぐったくなる、「こちょこちょ弾」をぶっ放すぞ！"
"2005706-20-怯える市民A" = "ひえええ……それだけは勘弁してくれ～！"
"2005706-21-アカネ" = "あの……先生……？"
"2005706-22" = "[s] \"どうしてこんなことに……。\""
"2005706-23-アカネ" = "申し訳ありません……。#n私が不甲斐ないばかりに……。"
"2005706-24" = "[s] \"このままだと、大勢の市民が巻き込まれてしまう……。\""
"2005706-25-ヴァルキューレの生徒" = "そこまでだ！お前たちは既に包囲されている！#nそこにいる人たちを早く解放しなさい！"
"2005706-26-組織の行動隊長" = "どうしましょう、ボス？"
"2005706-27-組織のボス" = "ここまで来て白旗を上げるなんて、できるか！我々はやり遂げる！#nそれしか道はない！"
"2005706-28-組織の行動隊長" = "ってなわけだからヴァルキューレのお巡りさんよぉ！#nこっちの要求を飲まねえと、ここにいる奴らの安全は保障できないぞ！"
"2005706-29-アカネ" = "先生……。"
"2005706-30" = "[s3] \"アカネ――\"\n[s4] \"今こそ、C&Cの出番だよ！\""
"2005706-31-アカネ" = "はい。"
"2005706-32-アカネ" = "……。"
"2005706-33-アカネ" = "今こそ、新しいやり方を試す時、ですね。"
"2005706-34-アカネ" = "あの……。"
"2005706-35-組織の行動隊長" = "あ？誰だお前？"
"2005706-36-アカネ" = "ヴァルキューレの方々と、まずは一度話し合ってみてはいかがでしょうか？"
"2005706-37-アカネ" = "言葉を交わせば、何か良い着地点を見つけられるのではないかと。"
"2005706-38-組織の行動隊長" = "は？何いってんだ？"
"2005706-39-組織の行動隊長" = "「テロリストとは交渉しません」って、あいつらが掲げてるの知らねぇのか？"
"2005706-40-組織の行動隊長" = "こっちだって同じだ！サツなんかと交渉してたまるか！いつ裏切られるか分かったもんじゃない！"
"2005706-41-組織の行動隊長" = "部外者はすっ込んでろ！"
"2005706-42-アカネ" = "あら……。"
"2005706-43" = "[s] （そう甘くはないか……）"
"2005706-44-アカネ" = "私、ヴァルキューレ側にツテがありまして。#nいかがでしょう？私が連絡いたしましょうか？"
"2005706-45-アカネ" = "もしかしたら、円満に解決できるかもしれません。"
"2005706-46-組織のボス" = "はぁ？信用できるわけないだろう。"
"2005706-47-組織のボス" = "一目見れば分かるとも。君の顔にそう書いてある。"
"2005706-48-アカネ" = "……なるほど。 "
"2005706-49" = "[s] （アカネの顔が……！？）"
"2005706-50-アカネ" = "でしたら、情状酌量を求めてみては？#n事情を伝えればあるいは――"
"2005706-51-組織の行動隊長" = "今さら引き下がれるわけねぇだろ！"
"2005706-52-組織の行動隊長" = "何も知らねえ民間人のくせに！"
"2005706-53" = "[ns] （アカネが本気になったら、そんなこと言ってられないような……）"
"2005706-54-アカネ" = "ヴァルキューレの方々も、円満解決を望まれているかと。その方が双方にとって良いと思うのですが……。"
"2005706-55-アカネ" = "[ruby=・]取[/ruby][ruby=・]引[/ruby]を――"
"2005706-56-組織のボス" = "ふざけないでくれるか！"
"2005706-57-組織のボス" = "連中が我々に屈服しない限り、円満解決など望むべくもないだろう！"
"2005706-58-組織のボス" = "ブラックマーケットは我々の管轄。ヴァルキューレを歓迎する者など一人もいないのだよ！"
"2005706-59-組織のボス" = "ああ、いや？君がその一味か？"
"2005706-60-アカネ" = "ふふ……うふふ……。"
"2005706-61" = "[s] （どうなっても知らない……）"
"2005706-62-アカネ" = "もう夜になってしまいましたね、先生。"
"2005706-63" = "[s] \"そうだね。\""
"2005706-64-アカネ" = "明日は学園に行かなければなりませんし、復習もまだ終わっていません……。"
"2005706-65" = "[s] \"そうだね。勉強が本分だし。\""
"2005706-66-アカネ" = "先生も明日の準備がありますよね……。"
"2005706-67-アカネ" = "いかがしましょう……？"
"2005706-68" = "[s] \"アカネ。\""
"2005706-69-アカネ" = "はい、先生。"
"2005706-70" = "[s] \"行っていいよ。\""
"2005706-71-アカネ" = "え？"
"2005706-72-アカネ" = "……。"
"2005706-73-アカネ" = "よろしいのですか？"
"2005706-74" = "[s5] \"あれこれ試してダメなら……。\"\n[s6] \"諦めも肝心っていうからね。\""
"2005706-75-アカネ" = "かしこまりました。"
"2005706-76-アカネ" = "[ruby=・]ご[/ruby][ruby=・]主[/ruby][ruby=・]人[/ruby][ruby=・]様[/ruby]。"
"2005706-77-組織員たち" = "うわああああっ！？！？！？"
"2005706-78-組織員たち" = "何だ、こりゃ！一体何が起きて――！！！"
"2005706-79-組織員たち" = "に、逃げろ！あいつ、いかれちまった！！！"
"2005706-80-組織員たち" = "待ってくれ！ひいぃぃぃっ！！！"
"2005706-81-組織員たち" = "ヴァルキューレ！た、頼む！助けてくれ！無条件降伏する！"
"2005706-82-組織員たち" = "だから我々をあいつから守ってください！！！"
"2005706-83-アカネ" = "ふう。"
"2005706-84-アカネ" = "やはり、爆弾こそ――最高の「お掃除」方法、ですね。"
