[translation]
"1008206-1" = "青春に感謝を込めて"
"1008206-2" = "[ns] \"レンゲが来る前に仕事を片付けておこう。\""
"1008206-3" = "[ns] \"えっと、次の作業は……\" "
"1008206-4" = "（気づけばレンゲと約束した時間になっていた）"
"1008206-5" = "[ns] \"……そういえば、今日は何も食べてなかった。\""
"1008206-6" = "（カップラーメンを作ろうと立ち上がったところで……）"
"1008206-7-レンゲ" = "せんせ……！"
"1008206-8-レンゲ" = "いや、師匠！お待たせ！"
"1008206-9-レンゲ" = "今日も元気に「青春活動」を……！"
"1008206-10-レンゲ" = "……師匠、どうしたんだ？#n死んだ魚のような目をしてるけど……"
"1008206-11" = "[s] \"ううん、大丈夫だよ。ちょっと疲れただけ。\""
"1008206-12-レンゲ" = "そうなのか？"
"1008206-13-レンゲ" = "なら、いいけど……"
"1008206-14" = "[s] \"うん、レンゲの顔を見て元気が出たから。\""
"1008206-15-レンゲ" = "なっ！？"
"1008206-16-レンゲ" = "その不意打ち、やっぱ只者じゃないな……"
"1008206-17-レンゲ" = "アタシみたいな「青春経験者」じゃなかったら、今のでノックアウトされてたはずだ……！"
"1008206-18-レンゲ" = "さすがは師匠！"
"1008206-19" = "[s1] \"わ、わざとじゃないから……\"\n[s2] \"青春初心者からレベルアップしてたんだ……\""
"1008206-20-レンゲ" = "まぁ……そんなことはさておき、今日も新しいイベントを始めようと思う！"
"1008206-21-レンゲ" = "さ、張り切っていこう！"
"1008206-22" = "[s] \"うん、行こっか。\""
"1008206-23" = "（こうして今日も私たちは「青春活動」に励んだ）"
"1008206-24" = "（そして……）"
"1008206-25-レンゲ" = "んんっ～～！"
"1008206-26-レンゲ" = "いや～今日も充実したな！師匠！"
"1008206-27-レンゲ" = "色々な「青春活動」を通して、経験値が溜まった！"
"1008206-28-レンゲ" = "これでまた一歩、青春マスターに近づいた気がする！"
"1008206-29" = "[s3] \"青春経験者の次は一気にマスターなんだ！？\"\n[s4] \"ちゃんと成長してきたね！\""
"1008206-30-レンゲ" = "地道にコツコツやってきたおかげだね。"
"1008206-31-レンゲ" = "それはそうと、今日も付き合ってくれてありが――"
"1008206-32-レンゲ" = "……師匠？どうしたんだ？"
"1008206-33" = "[s] \"あ、ごめん。ちょっと……\""
"1008206-34-レンゲ" = "し、師匠！？"
"1008206-35-レンゲ" = "大丈夫か！？師匠……！"
"1008206-36-レンゲ" = "………………へ？"
"1008206-37" = "（レンゲのおかげで、なんとかシャーレに帰ってこられた）"
"1008206-38-レンゲ" = "ええと、つまり……"
"1008206-39-レンゲ" = "ずっと忙しくて、食事を忘れてたのか？"
"1008206-40-レンゲ" = "それで空腹のあまり倒れた、と……？"
"1008206-41" = "[s] \"……はい。\""
"1008206-42-レンゲ" = "……………………。"
"1008206-43" = "[s] \"えっと、その表情は……？\""
"1008206-44-レンゲ" = "そんなんじゃダメだ！先生！！"
"1008206-45" = "[ns] \"うわっ！？\""
"1008206-46-レンゲ" = "どれだけ忙しくても、ちゃんと食べないと！！"
"1008206-47-レンゲ" = "何事も体力があってこそだ！#n食事を抜くなんて言語道断！"
"1008206-48-レンゲ" = "今日はアタシが居たから良かったけど、もしそうじゃなかったら……"
"1008206-49-レンゲ" = "あ、でも……先生が忙しくて食べる余裕が無かったのは……"
"1008206-50-レンゲ" = "もし、かして……"
"1008206-51-レンゲ" = "……アタシのせい？"
"1008206-52" = "[s] \"ううん、レンゲのせいじゃないよ。\""
"1008206-53-レンゲ" = "……違う、いくらアタシでも分かる。"
"1008206-54-レンゲ" = "ただでさえシャーレの仕事で忙しいのに、アタシが「青春師弟」を無理に頼んだせいだ。"
"1008206-55-レンゲ" = "先生は快く受けてくれたけど……"
"1008206-56-レンゲ" = "「青春活動」で余計に忙しくなったのは事実だし……そのせいで……"
"1008206-57" = "[s] \"本当に大丈夫だよ、私も楽しかったし。\""
"1008206-58-レンゲ" = "先生……"
"1008206-59-レンゲ" = "……。"
"1008206-60-レンゲ" = "まったく、そんな風に言われたら……"
"1008206-61-レンゲ" = "アタシが青春エキスパートじゃなかったら倒れてたところだ！"
"1008206-62" = "[s] \"……次はマスターじゃなかったっけ？\""
"1008206-63-レンゲ" = "細かいこと気にする元気はあるんだな！？"
"1008206-64-レンゲ" = "（青春活動のせいでこうなったんだ……何かアタシにできることは……）"
"1008206-65-レンゲ" = "あ。"
"1008206-66-レンゲ" = "……よし、今日は解散しよう！"
"1008206-67-レンゲ" = "アタシはこれで帰るから、先生はゆっくりご飯を食べてくれ！"
"1008206-68-レンゲ" = "じゃ、また！"
"1008206-69" = "[ns] \"あ、うん……ま、またね？\""
"1008206-70" = "[ns] \"気を遣わせちゃったかな……\""
"1008206-71" = "（レンゲが帰ってから、今日の出来事を振り返っていると……）"
"1008206-72" = "[ns] \"はい、もしも……\""
"1008206-73-レンゲ" = "あ！先生！アタシアタシ！レンゲなんだけど！"
"1008206-74-レンゲ" = "はぁ？詐欺？そう簡単には騙されないって！？"
"1008206-75-レンゲ" = "本物のレンゲだから安心して！#nまぁ、自分で言ってて怪しいなとは思ったけどさ……"
"1008206-76-レンゲ" = "それよりさ、聞きたいことがあって……"
"1008206-77-レンゲ" = "その、先生の好きな食べ物とか……苦手な食べ物とか……"
"1008206-78-レンゲ" = "ほら、アレルギーがあったら大変だと思って？"
"1008206-79-レンゲ" = "……ん？ああっ、今ちょっと百花繚乱の全員に聞いて回っててさ！"
"1008206-80-レンゲ" = "ついでだから先生にも聞いとこうと思って！"
"1008206-81" = "[ns] 丁寧に答える。"
"1008206-82-レンゲ" = "……そっか。ありがとね。"
"1008206-83-レンゲ" = "それじゃ……首を洗って待っててくれ！"
"1008206-84" = "[s] \"えっ！？\""
"1008206-85-レンゲ" = "じゃ、また明日！"
"1008206-86" = "（そうして、レンゲの電話に戸惑っていたのも束の間……）"
"1008206-87" = "（次の日がやってきた）"
"1008206-88" = "（昨日と同じように、シャーレの仕事を片付けていると……）"
"1008206-89" = "[ns] \"あ、レンゲ。今日は何時に来るの？\""
"1008206-90-レンゲ" = "それが、その……心の準備が必要というか。"
"1008206-91-レンゲ" = "いくら青春レベルが上がったとはいえ、ハードルが高くてな……"
"1008206-92-レンゲ" = "……先生、今は一人か？#n周りに誰か居たりしないか？"
"1008206-93-レンゲ" = "よ、よし……そ、そしたら……ちょっとだけ、出てきてほしいんだが……"
"1008206-94-レンゲ" = "シャーレの近くにある公園で待ってる。"
"1008206-95-レンゲ" = "それじゃ……！"
"1008206-96" = "[ns] \"ここのはずだけど……\""
"1008206-97-レンゲ" = "あ！先生！こ、こっちだ……"
"1008206-98-レンゲ" = "その……"
"1008206-99-レンゲ" = "ここ最近、先生は……ご飯を食べる暇もないくらい忙しかったじゃん？#nそんな中アタシに付き合ってくれてさ……"
"1008206-100" = "[s] \"その事なら本当に大丈夫だけど……\""
"1008206-101-レンゲ" = "先生は大丈夫かもしれないけど、アタシは大丈夫じゃない！"
"1008206-102-レンゲ" = "だから、その……ほら、これを！"
"1008206-103" = "[ns] \"えっ……\""
"1008206-104" = "[ns] \"これは、お弁当……？\""
"1008206-105" = "[wa:300]― [log=렌게]そ、[wa:650]そう！[/log]"
"1008206-106" = "― [log=렌게]一目で[wa:400]気がつくなんて！[wa:1150]さすが師匠！[/log]"
"1008206-107" = "― [log=렌게]し、[wa:850]師匠のために、[wa:1500]用意してきたものなんだ……！[/log]"
"1008206-108" = "[ns] \"嬉しいけど、どうして急に……？\""
"1008206-109" = "[wa:750]― [log=렌게]これまで先生には、[wa:1400]ワガママを言ってばかりで、[/log]"
"1008206-110" = "― [log=렌게]ちゃんとしたお礼は、[wa:650]できてなかったし……。[/log]"
"1008206-111" = "― [log=렌게]迷惑を[wa:500]かけちゃったから……[/log]"
"1008206-112" = "― [log=렌게]その、[wa:1650]感謝の気持ちというか……。[/log]"
"1008206-113" = "[wa:600]― [log=렌게]は、[wa:800]初めて作ったから……[/log]"
"1008206-114" = "[wa:100]― [log=렌게]あんまり、[wa:650]味は保証できない、[wa:1800]かも……。[/log]"
"1008206-115" = "― [log=렌게]こういうの、[wa:1100]アタシには[wa:600]ちょっと早い気も、[wa:900]するけど……。[/log]"
"1008206-116" = "― [log=렌게]で、[wa:600]でも、[wa:1250]頑張ったんだ……！[/log]"
"1008206-117" = "[ns] \"……ありがとう、レンゲ。美味しく頂くね。\""
"1008206-118" = "[wa:400]― [log=렌게]あ、[wa:1400]う、[wa:1100]うん……。[/log]"
"1008206-119" = "― [log=렌게]じゃあ、[wa:1150]お、[wa:1100]おいしく……[/log]"
"1008206-120" = "― [log=렌게]め、[wa:1300]召し上がって[wa:1250]ください……。[/log]"
"1008206-121-レンゲ" = "……ち、ちゃんと渡したからな！？"
"1008206-122-レンゲ" = "これで青春レベルも上がったはず！"
"1008206-123-レンゲ" = "じゃ……もう行くから……！"
"1008206-124" = "（シャーレに戻って食べたレンゲの弁当は、とても暖かかった）"
