[translation]
"10028020-1" = "第2話;日常茶飯事"
"10028020-2-イチカ" = "はぁ……はぁ、はぁ……"
"10028020-3-イチカ" = "ちょっと……息が……ふぅ……"
"10028020-4-イチカ" = "でも……なんとか、乗れたっすね……はは……"
"10028020-5-イチカ" = "……先生？だ、大丈夫っすか？#nもしかして具合が悪くなったとか……！"
"10028020-6" = "[s1] \"き、気にしないで、大丈夫……\"\n[s2] \"もう、ちょっと、体力を……つけないと、かな……\""
"10028020-7-イチカ" = "よ、良かったっす……"
"10028020-8-イチカ" = "はぁ……先生には帰りの列車で休んでもらいたかったんすけど……"
"10028020-9-イチカ" = "申し訳ないっす……こんな事になってしまって……"
"10028020-10-イチカ" = "大丈夫、って……？#nそう言ってもらえると、私はありがたいっすけど……"
"10028020-11-イチカ" = "でもやっぱり、幸先は悪いっす……"
"10028020-12-イチカ" = "ううっ……どこで間違えたんすかね……"
"10028020-13-イチカ" = "で、でも……！カバンはこの列車にあるはずっすから！"
"10028020-14-イチカ" = "最悪の事態は免れたっす！"
"10028020-15" = "[s3] \"大丈夫、気にしないで。\"\n[s4] \"これくらい日常茶飯事だからね。\""
"10028020-16-イチカ" = "そ、そうっすよね！！これくらい、日常茶飯事っすよ！ははっ！"
"10028020-17-イチカ" = "カバンが見つかったら途中下車してトリニティ行きに乗り換えればいいわけだし……"
"10028020-18-イチカ" = "時間はたーっぷりあるっすから！今日中にさえ帰れれば問題ないっす！"
"10028020-19-イチカ" = "まぁ「ゲヘナ行き」ってのがちょっと引っかかるっすけど――"
"10028020-20-イチカ" = "…………？"
"10028020-21-搭乗客A" = "何だ？あいつ、トリニティじゃないか？#nどうしてここにトリニティが……？"
"10028020-22-搭乗客B" = "しかもあの腕章……アレ、正義実現委員会だよな？"
"10028020-23-搭乗客B" = "何でトリニティの奴が、ゲヘナ行きの列車にいるんだよ？"
"10028020-24-イチカ" = "……えーと。"
"10028020-25-イチカ" = "ちょっと、この雰囲気は……"
"10028020-26-イチカ" = "歓迎されてないっす、よね……"
"10028020-27" = "[s5] \"どうしても学園間の相性が……\"\n[s6] \"仕方ないとはいえ……\""
"10028020-28-？？？" = "おい、そこ！何の騒ぎだ！！"
"10028020-29-？？？" = "ったく、ゲヘナの連中はいつも問題を起こすよな！？"
"10028020-30-列車乗務員の生徒A" = "……ん？何だ？ "
"10028020-31-列車乗務員の生徒A" = "トリニティの生徒じゃないか！？#n何でこの列車にいるんだ？これはゲヘナ行きだぞ？"
"10028020-32-列車乗務員の生徒A" = "……いや、まあ知ったことか。乗車券を見せろ。"
"10028020-33-イチカ" = "え、えーっと……乗車券っすか……？#nそれが……"
"10028020-34-列車乗務員の生徒A" = "……ん？乗車券がないのか？"
"10028020-35-列車乗務員の生徒A" = "じゃあ、こっちの大人は？"
"10028020-36-列車乗務員の生徒A" = "……2人とも持ってないって……ふざけてるのか？"
"10028020-37-イチカ" = "あっ……いや、ちょっと待ってほしいっす。これにはワケが――"
"10028020-38-列車乗務員の生徒A" = "ワケって何だ、もしかしてアレか？"
"10028020-39-列車乗務員の生徒A" = "どうせゲヘナ行きの列車なんだから、まともなものじゃないだろうって？"
"10028020-40-イチカ" = "……えっ。"
"10028020-41-イチカ" = "いや――"
"10028020-42-列車乗務員の生徒A" = "うるさい乗客ばかりだから、乗務員の目を誤魔化せるとか……！"
"10028020-43-イチカ" = "その、待っ――"
"10028020-44-列車乗務員の生徒A" = "無賃乗車くらい許されるとか思ったんだろ……？"
"10028020-45-イチカ" = "そうじゃなくて、一旦こっちの話を――"
"10028020-46-列車乗務員の生徒A" = "言い訳なんて、もう分かってんだよ！"
"10028020-47-イチカ" = "いや、私たちは――"
"10028020-48-列車乗務員の生徒A" = "どうせ無法地帯だろうなんて考えで……"
"10028020-49-列車乗務員の生徒A" = "白昼堂々、無賃乗車をしようってんだろ！！"
"10028020-50-イチカ" = "だから私たちは、乗車券を買わせてほ……"
"10028020-51-列車乗務員の生徒A" = "もう限界だ！！トリニティまで馬鹿にしてくるなんて！！！"
"10028020-52-列車乗務員の生徒A" = "ピーッ！ピィイイイイイッ――！！全員集合！！！！！"
"10028020-53-列車乗務員の生徒A" = "無賃乗車の二人組を発見！マニュアルCで対応しろ！！"
"10028020-54-列車乗務員の生徒B" = "なっ、無賃乗車！？コイツらが……！！"
"10028020-55-列車乗務員の生徒C" = "もう我慢ならない……問答無用だ、捕らえてやる！！"
"10028020-56-列車乗務員の生徒B" = "全員、早く集合しろ！！！！"
"10028020-57-イチカ" = "……えーと。"
"10028020-58-イチカ" = "うーーん。"
"10028020-59-イチカ" = "おかしいな……"
"10028020-60-イチカ" = "……。"
"10028020-61-イチカ" = "こんなはずじゃ、なかったんすけどね……"
