[translation]
"70006020-1" = "美食とクッキー、そして救護（２）"
"70006020-2-ミネ" = "……事の発端は、些細なことでした。"
"70006020-3" = "聖テレサ総合病院・ロビー"
"70006020-4-ミネ" = "うーん……。"
"70006020-5-セリナ" = "団長？何かありましたか？元気がないようですが……。"
"70006020-6-セリナ" = "あっ！じゃあ元気が出るように、ハナエがエールを送ってあげます！"
"70006020-7-ミネ" = "いえ、大丈夫です。少々、変な噂を耳にしただけですので……。"
"70006020-8-セリナ" = "変な噂？"
"70006020-9-セリナ" = "もしかして……「医薬品を集めるのは、湿布の匂いが好きだから」という噂ですか？"
"70006020-10-ミネ" = "違います。"
"70006020-11-ハナエ" = "じゃあ、「お茶会にみんなを招くのは、次の救護対象を見つけるため」という噂？"
"70006020-12-ミネ" = "違います……。"
"70006020-13-セリナ" = "「筋力を上げるために、ひっそりプロテインクッキーを食べている」という噂……？"
"70006020-14-ミネ" = "違いますよっ……！"
"70006020-15-ミネ" = "えっ、いやっ、なんですか、次から次へと……！全部気になってくるじゃないですか！"
"70006020-16-ハナエ" = "心配しないでください！本当の団長は違うってみんな知ってますから！"
"70006020-17-ミネ" = "それならば、これほどまでに噂が立つのはおかしいではないですか。"
"70006020-18-ミネ" = "私はただ……一人でも多くの方に、救護の精神を届けたくて……。"
"70006020-19-ハナエ" = "どうしてこんなことに……。"
"70006020-20-ハナエ" = "どうすれば団長が変な噂から解放されるのでしょうか？"
"70006020-21-ハナエ" = "あ……！こういうのはどうでしょう？"
"70006020-22-セリナ" = "手作りのクッキーを配るんです！"
"70006020-23-セリナ" = "心のこもったクッキーを貰えば、自然と誤解も解けるんじゃないでしょうか？"
"70006020-24-ハナエ" = "いいですね！せっかくなら可愛いのにしませんか？ひよことか！"
"70006020-25-ミネ" = "ひよこのクッキー……それは、可愛いですね……。"
"70006020-26-ミネ" = "……そんなわけで、ひよこのクッキーを作ることになったものの……問題がありまして。"
"70006020-27-ミネ" = "私は……クッキーを作ったことがありません。"
"70006020-28-ミネ" = "セリナとハナエが作るのを手伝ってくれましたが、結果は惨憺たるものでした。"
"70006020-29-ミネ" = "ひよこではなく、こう……別の世界の生き物というか、何か違うものが生まれてしまい……。"
"70006020-30-ミネ" = "なので、伝手をたどって、トリニティの有名なパティスリーにもご教示いただいたのですが……。"
"70006020-31-ミネ" = "なぜか、難易度の高いレシピを教えられてしまって……。"
"70006020-32-ハルナ" = "ミネさんはひよこのクッキーがよかったのですよね？"
"70006020-33-ミネ" = "ええ。可愛いは正義ですから。"
"70006020-34-ミネ" = "そんな折に、ここでフウカさんと出会ったのです。"
"70006020-35-ハルナ" = "シャーレの近くですから、ゲヘナとトリニティの生徒が会うのもおかしくはありませんが……不思議な組み合わせですね。"
"70006020-36-ハルナ" = "一体どんな風の吹き回しですか？"
"70006020-37-フウカ" = "きっかけ……いや、うん。#nうわっ、また変なのに絡まれた……って思ったんだよね……。"
"70006020-38-フウカ" = "うん！今日の買い出しも上手くいったかな。"
"70006020-39-フウカ" = "これでしばらくはよし、っと。"
"70006020-40-フウカ" = "……またあいつらに邪魔されなければだけど。"
"70006020-41-ミネ" = "ふむ……。"
"70006020-42-フウカ" = "ど、どうも……何かご用ですか……？"
"70006020-43-ミネ" = "こんにちは。救護活動に興味はありませんか？"
"70006020-44-フウカ" = "……えっ？"
"70006020-45-フウカ" = "失礼。私はトリニティ総合学園の救護騎士団団長、[ruby=あおもり]蒼森[/ruby]ミネと申します。"
"70006020-46-フウカ" = "と、トリニティ？しかも救護騎士団の団長！？"
"70006020-47-ミネ" = "はい。あなたを見つけたその時、シンパシーを感じまして。"
"70006020-48-ミネ" = "食材を見定めるその鋭い眼差し……まるで医療用品を選ぶ時の私のようでした。"
"70006020-49-フウカ" = "そ、そうなんですね……。"
"70006020-50-ミネ" = "特に、たくさんの人を想うその表情。あなたも「救護」に携わる方なのでしょう？"
"70006020-51-フウカ" = "救護……？えっと……給食部の部長ならやってますけど……。"
"70006020-52-フウカ" = "やはり……！私の目に狂いはありませんでした！"
"70006020-53-フウカ" = "少しお時間を頂けませんか？#nあなたとなら通じ合える気がするのです。"
"70006020-54-フウカ" = "でも、私はゲヘナの生徒ですよ……？"
"70006020-55-ミネ" = "「救護」の前では、所属など意味を成しません。#nそう思いませんか？"
"70006020-56-フウカ" = "まあ……はい。#nお腹が空いているなら、それが誰であれご飯を振る舞いたいですけど……。"
"70006020-57-フウカ" = "ちょっとだけ手のかかる奴らもいますけど……。"
"70006020-58-ミネ" = "「手のかかる奴ら」……？"
"70006020-59-ハルナ" = "――なるほど。それで私たちの話を。"
"70006020-60-フウカ" = "クッキー作りも手伝うつもり。"
"70006020-61-フウカ" = "救護騎士団と仲良くなって困ることはないと思うし。"
"70006020-62-フウカ" = "だから今日は諦めて。ほら、帰った帰った。これからクッキーの材料を買いに行くんだから。"
"70006020-63-ハルナ" = "……いいでしょう。フウカさんにお昼を作っていただく計画は保留とします。"
"70006020-64-ハルナ" = "その代わり、と言ってはなんですが。"
"70006020-65-ハルナ" = "ミネさん。差し支えなければ、私たち「美食研究会」にひよこクッキーの試食を任せていただけませんか？"
"70006020-66-ハルナ" = "事情を伺ったあの時から、美食の気配を感じたのです。"
"70006020-67-ハルナ" = "フフッ。どんな味か気になります★"
"70006020-68-ハルナ" = "クッキー好き！だーいすき！"
"70006020-69-ハルナ" = "試食ならタダってことでしょ？助かるー！"
"70006020-70-フウカ" = "あんた達、相変わらず復活早いよね……。"
"70006020-71-ミネ" = "試食ですか……。確かに、私たちよりは美食研究会の皆さんの方が詳しそうですね。"
"70006020-72-フウカ" = "関わらせたら碌なことにならないと思いますよ……。"
"70006020-73-ハルナ" = "ご心配には及びません。あくまで「試食係」に徹するつもりですから。"
"70006020-74-ハルナ" = "フウカさんが手伝うということなら、変なクッキーになる心配もないでしょうし。"
"70006020-75-フウカ" = "まあ、そうならないように頑張るけど……。"
"70006020-76-セリナ" = "ミネ団長、どうしますか？"
"70006020-77-ハナエ" = "私は賛成です！皆さんとのお菓子作り、今から楽しみです～！"
"70006020-78-ミネ" = "そうですね、ここはお言葉に甘えて……皆さん、よろしくお願いいたします。"
"70006020-79-フウカ" = "不安だなぁ……。"
"70006020-80" = "（しばらくして……）"
"70006020-81" = "トリニティの調理実習室"
"70006020-82-イズミ" = "あっ！いい匂いしてきた！クッキー、そろそろかなぁ？"
"70006020-83-イズミ" = "もうできるから。大人しく待ってて。"
"70006020-84-ジュンコ" = "だそうですよ？私たちも準備をしましょうか。"
"70006020-85-ジュンコ" = "トリニティの調理実習室に来ちゃったけど……本当に大丈夫なんだよね？"
"70006020-86-ハルナ" = "ええ、もちろん。計画通り楽しめばいいのです。"
"70006020-87-ハルナ" = "計画通りに。"
"70006020-88-ジュンコ" = "計画通りって……美味しくなかったら爆破するつもり！？"
"70006020-89-ハルナ" = "ふふっ、さあ。どうでしょうか。"
"70006020-90-セリナ" = "みなさん！お待たせしました！"
"70006020-91-セリナ" = "ミネ団長のクッキーが完成しましたよ！"
"70006020-92-ミネ" = "ふぅ……。"
"70006020-93-セリナ" = "団長、みなさんに見せてあげてください！"
"70006020-94-セリナ" = "きっと驚きますよ。"
"70006020-95-ミネ" = "わ、分かりました。"
"70006020-96-ミネ" = "……こちらです！"
"70006020-97-ハルナ" = "あら。これはこれは……。"
"70006020-98-アカリ" = "見た目はバッチリですね。"
"70006020-99-ハルナ" = "かわいいじゃない！食べるのが勿体ないくらい！"
"70006020-100-イズミ" = "すごいすごい！もう食べていい！？"
"70006020-101-ミネ" = "そんなに褒められては、少々照れくさいですね……#nでも、私が作ったと言って信じてもらえるでしょうか。"
"70006020-102-ハルナ" = "火のない所に煙は立たぬ、とは言いますが……。"
"70006020-103-ハルナ" = "噂は所詮、噂。すべて鵜呑みにしていては、本質を見落としてしまうもの。#n眼の前の人を見てこそですわ。ミネさんの噂の方が間違っていると分かります。"
"70006020-104-ミネ" = "本当ですか……！！"
"70006020-105-セリナ" = "わあ！良かったですね、団長！"
"70006020-106-セリナ" = "これで他の人にも、本当の団長を知ってもらえると思います！"
"70006020-107-ミネ" = "そうだと良いのですが……。"
"70006020-108-ハルナ" = "では……いざ実食といきましょうか。"
"70006020-109-イズミ" = "えへへっ。頭から食べようかな？それとも体？"
"70006020-110-アカリ" = "頭からの方が苦しみが少なくて済むんじゃないでしょうか★"
"70006020-111-ジュンコ" = "それじゃ、いただきます……！"
"70006020-112-ハルナ" = "こ、この味は……！"
"70006020-113-アカリ" = "あらあら……"
"70006020-114-イズミ" = "こんなクッキー、生まれて初めて……！"
"70006020-115-ジュンコ" = "なんというかこれ……"
"70006020-116-アカリ" = "おいしいっっ……！！"
"70006020-117-ジュンコ" = "口の中に広がる、卵の香ばしさと甘さ……たまんない！"
"70006020-118-アカリ" = "サクッとした歯ごたえ……焼き加減も完璧ですね。"
"70006020-119-イズミ" = "可愛い味がする！私、今までいろんなもの食べてきたけど可愛い味は初めて！"
"70006020-120-ハルナ" = "……料理とは、作り手の想いも共に味わうもの。"
"70006020-121-ハルナ" = "このクッキーから、ミネさんの真心が伝わってきます。"
"70006020-122-ハルナ" = "嗚呼、確かな美食でございます。"
"70006020-123-ミネ" = "そ、そのようなお言葉……。"
"70006020-124-ミネ" = "すごく嬉しいです。美食研究会の皆さんから認められて自信がつきました。"
"70006020-125-ミネ" = "正直、失敗したらどうしよう、と心配していたので……。"
"70006020-126-ハルナ" = "ふふっ。ここを爆破せずに済んでよかったです。"
"70006020-127-ハルナ" = "やっぱりそのつもりだったの！？"
"70006020-128-アカリ" = "でも、美味しかったですね～？"
"70006020-129-イズミ" = "うんうん！ねえ、これ全部食べていい？"
"70006020-130-ミネ" = "もちろんです。たくさんありますので、好きなだけお召し上がりください。"
"70006020-131-イズミ" = "やったー！"
"70006020-132-ハナエ" = "これならきっと、たくさんの方に思いを伝えられるはずです！"
"70006020-133-ハナエ" = "はい！正義実現委員会のハスミさんも喜ぶと思います！"
"70006020-134-ミネ" = "ハスミ副委員長ですか……笑われないといいのですが。"
"70006020-135-セリナ" = "デザートに関しては一貫しているお方ですし、このクッキーを笑うはずありません！"
"70006020-136-セリナ" = "このクッキーで、お二人の溝が埋まるかもしれませんね！"
"70006020-137-ミネ" = "ふ、ふむ……。"
"70006020-138-ミネ" = "ともかく、皆さんありがとうございました。おかげで一歩踏み出せた気がします。"
"70006020-139-ミネ" = "特にフウカさんには大変お世話になり、素晴らしいクッキーが――"
"70006020-140-ミネ" = "フウカさん？"
"70006020-141-ハナエ" = "あれ？どこに行かれたのでしょうか？さっきまでこちらにいらしたはずですが……。"
"70006020-142-ハナエ" = "そういえば試食の時からいなかったような……。"
"70006020-143-ハルナ" = "では救護騎士団の皆さん、私たちはそろそろ……。"
"70006020-144-ハルナ" = "んっ……！んんーーっ！！"
"70006020-145-ハナエ" = "フウカさん！？なんで縛られて！？"
"70006020-146-ミネ" = "いつの間にフウカさんを……！"
"70006020-147-アカリ" = "皆さんがクッキーの感想を聞いていらした時ですよ。"
"70006020-148-アカリ" = "完成したクッキーに、すっかり夢中になっていたようですね★"
"70006020-149-ミネ" = "あの一瞬で、ですか……？"
"70006020-150-ハルナ" = "うふふっ。私たちはフウカさんと長い時間を一緒に過ごしてきたのです。この程度、朝飯前ですわ。"
"70006020-151-ジュンコ" = "自慢げに言うことじゃ無くない……？"
"70006020-152-ジュンコ" = "んんっ！んーーっ！！"
"70006020-153-イズミ" = "早くお昼を作りたい！ってフウカが言ってるよ！"
"70006020-154-ハルナ" = "では行きましょうか。まずはジュリさんに連絡をして……"
"70006020-155-ジュリ" = "あっ、ハルナさん。どうですか？先輩、見つかりました……？"
"70006020-156-ジュリ" = "ええ、無事に「保護」いたしましたわ。"
"70006020-157-ハルナ" = "フウカさんは食材選びで忙しかっただけのようです。"
"70006020-158-ジュリ" = "そうでしたか！お手間をおかけしますが、引き続き先輩をよろしくお願いしますね！"
"70006020-159-ハルナ" = "お任せください。これから送り届けますので。"
"70006020-160-ハルナ" = "では、私たちはこれにて。"
"70006020-161-アカリ" = "クッキーご馳走さまでした★"
"70006020-162-ミネ" = "友人に対して、なんたる仕打ち……！"
"70006020-163-ミネ" = "追います！――救護が必要な場に救護を！！"
"70006020-164-ハナエ" = "か、壁に穴が……。"
"70006020-165-セリナ" = "あはは……皆さんの誤解を解くのは、当分難しそうですね。"
"70006020-166-ミネ" = "美食研究会……！逃がしませんよ！！"
"70006020-167-ハルナ" = "うふふっ、今度は捕まりませんわ……！"
"70006020-168-フウカ" = "んんっ！んんーーーーーっ！！！"
"70006020-169" = "（その後、凄まじい追走劇が繰り広げられた）"
"70006020-170" = "美食とクッキー、そして救護"
