[translation]
"10030050-1" = "第5話;夕食の準備"
"10030050-2-ハレ" = "……遅かったね、どこまで行ってたの？"
"10030050-3-ハレ" = "ずっと一人で待ってたから、暇で――"
"10030050-4-ハレ" = "みんな、どうしたの……？鬼ごっこでもしてたの？"
"10030050-5-マキ" = "たしかに、鬼ごっこかも……"
"10030050-6-マキ" = "……詳しく話すと、ちょっと長くなるかな。"
"10030050-7-コタマ" = "森の中で、特訓中のスミレ部長と会いました。"
"10030050-8-ハレ" = "なるほど……"
"10030050-9" = "[s] \"……納得するんだ！？\""
"10030050-10-ハレ" = "あ、うん。なんとなく想像がついたから……"
"10030050-11-チヒロ" = "一応言っておくけど、別にスミレ部長と鬼ごっこしてたわけじゃないよ。"
"10030050-12-コタマ" = "私たちが、トレーニング部の新入部員と話していたら……"
"10030050-13-マキ" = "いきなりでっかいクマが出てきたの！"
"10030050-14-ハレ" = "く、クマ！？"
"10030050-15-ハレ" = "だ、大丈夫なの……？#nここにやって来たりとか……"
"10030050-16-マキ" = "心配しないで、もうどこかにいったから。"
"10030050-17-チヒロ" = "トレーニング部が誘導してくれたおかげで、なんとかなりましたが……"
"10030050-18-チヒロ" = "森の奥には行かない方がいいと思う……"
"10030050-19-マキ" = "というか、トレーニング部はまだ山で訓練を続けるんだ？"
"10030050-20-チヒロ" = "場所を変えて続けるみたいだね。"
"10030050-21-チヒロ" = "来シーズンまでに体力をつけるためには、1分1秒も無駄にはできないんだって。"
"10030050-22-コタマ" = "レイは想像以上に本気のようですね。"
"10030050-23-マキ" = "来年はミレニアム野球部の活躍を期待していいのかな？"
"10030050-24" = "[ns] \"なんだか私の記憶と違うような……\""
"10030050-25-レイ" = "もう無理です！"
"10030050-26-レイ" = "ホームランを打てる秘訣を教えてもらえると思ったら、野球とは関係ない訓練ばっかり……しかもクマに追いかけられるなんて！"
"10030050-27-レイ" = "私、もう辞めます！"
"10030050-28-スミレ" = "レイさんが退部を希望しているのなら、引き留めませんが……"
"10030050-29-スミレ" = "一度訓練を始めた以上、このメニューが終わるまでレイさんを解放することはできません。"
"10030050-30-スミレ" = "クールダウンなしに中断すれば、筋肉痛の原因になる可能性がありますから！"
"10030050-31-スミレ" = "フィットネスセンターの安全責任者として、会員を放っておくわけにはいきません！"
"10030050-32-レイ" = "それで私を引き留められると思ってるんですか！"
"10030050-33-レイ" = "止める気なら、意地でも先輩を倒して行きますから！"
"10030050-34-スミレ" = "レイさん、その意気です。"
"10030050-35-レイ" = "え？"
"10030050-36-スミレ" = "先ほどはクマによる「スピードトレーニング」を行いましたので……"
"10030050-37-スミレ" = "これより、私と「パワートレーニング」に移りたいと思います！"
"10030050-38-スミレ" = "弱音を吐いたとしても訓練は終わりませんよ！"
"10030050-39-レイ" = "う……うううっ……！"
"10030050-40-レイ" = "トレーニングなんて嫌いだーっ！！"
"10030050-41-ハレ" = "……んー、これから何する？まだ16時だよ。"
"10030050-42-マキ" = "えっ！？まだこんな時間？"
"10030050-43-コタマ" = "……やっぱり外に居ると、いつもより時間の流れが遅い気がします。"
"10030050-44-マキ" = "そうだよね。部室だとちょっとゲームしてるだけで1日が終わっちゃうのに。"
"10030050-45-マキ" = "……これが特殊相対性理論ってやつ？"
"10030050-46-ハレ" = "いや、こういうのじゃないでしょ。"
"10030050-47-チヒロ" = "そうだね……そろそろ夕飯の準備をしようか。"
"10030050-48-マキ" = "もう！？"
"10030050-49-ハレ" = "お昼を食べてから、まだ3時間しか経ってないよ……？"
"10030050-50-コタマ" = "副部長、満腹中枢がおかしくなったのでは――"
"10030050-51-チヒロ" = "お腹すいたから急いでるわけじゃないから！？"
"10030050-52-チヒロ" = "家での調理と違って、火起こしも必要だし、食材の下ごしらえ1つとっても手間がかかるの。"
"10030050-53-チヒロ" = "日が暮れる前に完成させたいなら、そろそろ始めないと……"
"10030050-54-チヒロ" = "むしろ、今から始めても遅いような気もするけど……"
"10030050-55-マキ" = "え？下ごしらえっていっても野菜洗って切るだけじゃん？"
"10030050-56-マキ" = "そんなのすぐ終わるでしょ。"
"10030050-57-コタマ" = "持ってきた野菜も、一般的なものばかりですし……"
"10030050-58-ハレ" = "みんなでやれば、すぐじゃないかな。"
"10030050-59-チヒロ" = "そうだね……みんなでやれば早いと思う。ちゃんと協力してね。"
"10030050-60-チヒロ" = "それじゃ、3人で野菜を洗って皮を剥いたら、一口サイズに切っておいて。"
"10030050-61-チヒロ" = "私はそこで火を起こしておくから。#n洗うのはあっちの水場でね。"
"10030050-62-マキ" = "任せて！"
"10030050-63" = "（約1時間後……）"
"10030050-64-マキ" = "うううっ……！"
"10030050-65" = "うわっ！？"
"10030050-66-マキ" = "うわっ！？"
"10030050-67-ハレ" = "マキ、大丈夫？怪我してない？"
"10030050-68-マキ" = "うん、怪我はしてないけど……"
"10030050-69-マキ" = "何このニンジン！あんなに力を入れたのに全然切れない！"
"10030050-70-マキ" = "どんだけ硬いの！"
"10030050-71" = "[s1] \"キャンプナイフは小さくて扱いにくいから……\"\n[s2] \"いつもの感じだと難しいかも。\""
"10030050-72" = "[ns3] \"切るのは私に任せて。\"\n[ns4] \"その代わり、マキは皮を剥いてくれる？\""
"10030050-73-マキ" = "うん……それじゃお願い、先生。"
"10030050-74-マキ" = "コタマ先輩はどう？#nジャガイモの皮剥きおわった？"
"10030050-75-コタマ" = "いえ……ようやく3個目です……"
"10030050-76-コタマ" = "表面がでこぼこしてるので、思ったより難しくて……"
"10030050-77-コタマ" = "疲れてきたからか、あまり力が入りません……"
"10030050-78-ハレ" = "川が遠いから野菜を洗うのも一苦労……水、冷たいし。"
"10030050-79-ハレ" = "このままじゃ、手が凍りそう……"
"10030050-80-マキ" = "チヒロ先輩の言う通り、たしかに時間がかかるね……"
"10030050-81-マキ" = "……というか、本当にここまでして作らなきゃダメ？"
"10030050-82-チヒロ" = "野菜の下ごしらえ終わった？"
"10030050-83-ハレ" = "ま、まだ……"
"10030050-84-コタマ" = "も、もう少し、時間と予算をもらえれば……"
"10030050-85-チヒロ" = "予算……？"
"10030050-86-マキ" = "ねえ、チヒロ先輩。"
"10030050-87-マキ" = "持ってきた荷物に、カップ麺とかレトルトカレーは無いの？"
"10030050-88-チヒロ" = "非常用に持ってきてるけど……なんで？"
"10030050-89-マキ" = "じゃあ、それを食べようよ！"
"10030050-90-マキ" = "ここ、ネットも繋がらないしコンビニも遠いし不便じゃん？#nだから、ご飯くらい楽しよう？"
"10030050-91-チヒロ" = "ダメ。"
"10030050-92-チヒロ" = "いつもインスタントばっかでしょ……それに、ここまで準備したんだからちゃんと作るよ。"
"10030050-93-マキ" = "う、うっ……"
"10030050-94-チヒロ" = "来る前にも言ったけど、このキャンプの意義は日常から離れて健康的な1日を過ごすことにあるからね？"
"10030050-95-チヒロ" = "多少手間がかかってもちゃんとした食事を摂ろう。食材の手入れ、私も手伝うから。"
"10030050-96-マキ" = "ちゃんとした料理って言ったって、屋外で作れるものなんて限られてるじゃん……"
"10030050-97-マキ" = "カレーとか、スープとかさぁ……"
"10030050-98-チヒロ" = "そうね……まぁ、何ができるのかは楽しみにしてて。"
"10030050-99-チヒロ" = "今日のために色々準備してきたから。"
"10030050-100-一同" = "色々……？"
