[translation]
"101040-1" = "第4話;日常の亀裂（２）"
"101040-2" = "アリウス自治区・某所"
"101040-3-シスターフッドの生徒A" = "こ、こちらです……！見つけました！"
"101040-4-シスターフッドの生徒B" = "サクラコ様、こちらに。"
"101040-5-サクラコ" = "……なるほど、やはりここでしたか。"
"101040-6" = "最後の聖徒会長が残した……「ユスティナ聖徒会の礼装」。"
"101040-7-サクラコ" = "アリウスを弾圧しながらも、彼らの[ruby=エクソダス]トリニティ自治区外脱出[/ruby]を助け、復興を支援した、かの聖徒会長は――"
"101040-8-サクラコ" = "後継者に渡るはずの礼装を……ここ、アリウス自治区に隠していたのですね。"
"101040-9-サクラコ" = "……何故、これを手放したのですか？"
"101040-10-サクラコ" = "後悔……それとも責任感ですか？#n……その後、ここで起きた悲劇を、あなたは――"
"101040-11-サクラコ" = "――いえ、私がその理由を知る術はありませんね。"
"101040-12-サクラコ" = "ユスティナ聖徒会の最後の意志は、シスターフッドの代表である私が……#n正当な継承権限をもって引き継ぎます。"
"101040-13-サクラコ" = "……これ以上、ユスティナ聖徒会の権威が失墜するのを看過する事はできません。"
"101040-14-シスターフッドの生徒C" = "さ、サクラコ様……！こちらに……！"
"101040-15-サクラコ" = "分かりました。"
"101040-16-シスターフッドの生徒C" = "こ、これを……。"
"101040-17-サクラコ" = "これは……"
"101040-18-サクラコ" = "……すぐにシスターフッドの司祭をここに。"
"101040-19-シスターフッドの生徒C" = "は、はい……！"
"101040-20-サクラコ" = "……。"
"101040-21-サクラコ" = "アリウス自治区で、例のアレが起きていたとすれば……。"
"101040-22-サクラコ" = "事態は思ったよりもずっと……深刻かもしれません。"
"101040-23" = "トリニティ・議事堂"
"101040-24-聴聞会の議長" = "――では、[ruby=みたび]三度[/ruby]にわたって行われた本聴聞会により、ティーパーティーの[ruby=みその]聖園[/ruby]ミカに次の結論を下す。"
"101040-25-ミカ" = "……。"
"101040-26-聴聞会の議長" = "一つ、聖園ミカのティーパーティーとしての全権限を剥奪する。 "
"101040-27-聴聞会の議長" = "個人邸宅及び個人の活動費、特別校舎での授業など……#nティーパーティーとしてのすべての特権はこれより提供されない。"
"101040-28-聴聞会の議長" = "二つ、パテル分派内で行われた会議にて、#n聖園ミカのパテル分派における代表性について疑問が呈されたため、"
"101040-29-聴聞会の議長" = "パテル分派は固有の権限を行使し、新しい代表を選出する。#nただし、新しい代表が選出されるまでは聖園ミカの権限を維持する。"
"101040-30-ミカ" = "……。"
"101040-31" = "三つ、聖園ミカの拘禁は現時間をもって終了とし、学業に復帰することを許可する。"
"101040-32-聴聞会の議長" = "ただし、己の立場を常に意識し、学業以外の自粛を求めるものとする。"
"101040-33-聴聞会の議長" = "以上、これが聴聞会によるトリニティ生の意見である。"
"101040-34-聴聞会の議長" = "聖園ミカ、異議があれば申し出るよう。"
"101040-35-ミカ" = "ううん、無いよ。"
"101040-36-聴聞会の議長" = "では最後に、何かあれば発言を。 "
"101040-37-ミカ" = "……。 "
"101040-38-ミカ" = "……与えられた機会に感謝し、決定に従います。"
"101040-39" = "……では、これにて閉会。"
"101040-40" = "補習授業部・教室"
"101040-41-アズサ" = "重大発表がある。"
"101040-42-ヒフミ" = "アズサちゃん……？"
"101040-43-ハナコ" = "重大発表、ですか？"
"101040-44-コハル" = "な、何？そんな怖い顔して……どうしたの。"
"101040-45" = "みんなよく聞いてくれ。#nこの前、情報屋を通じて極秘情報を入手した……これは非常に重大な事件だ。"
"101040-46-ヒフミ" = "ご……極秘情報……？"
"101040-47-ハナコ" = "情報屋？"
"101040-48-コハル" = "重大な、事件……？"
"101040-49-アズサ" = "記録上にしか存在しない、伝説の――#n「ペロロジラ」のぬいぐるみがある場所を発見した。"
"101040-50-アズサ" = "……。"
"101040-51-ハナコ" = "ペロロジラ……？"
"101040-52-アズサ" = "ああ。よく聞いてくれ、ペロロジラとは――"
"101040-53" = "ペロロジラですか――！？ "
"101040-54-ヒフミ" = "アズサちゃん、それは本当ですか？ペロロジラのぬいぐるみって……輸送中に船が沈没してしまって、市場に流通される事がなかったという、伝説の……！？"
"101040-55-ヒフミ" = "その事件で、ぬいぐるみの下請け業者は破産してしまい……再販されることはなかったという、オーパーツみたいなものなのに！？#nそれが、存在してるってことですか！？"
"101040-56-ハナコ" = "さすがですね、ヒフミちゃん。"
"101040-57-アズサ" = "ああ、さすがヒフミ。その通りだ。"
"101040-58-アズサ" = "今は消失してしまった商品だが……大量生産の前にデザイン監修用として作られたサンプルがあったとかで――"
"101040-59-アズサ" = "これまではコレクターの手に渡っていたのだが……最近、その内の1つが市場に出回ったそうだ。"
"101040-60" = "な、なるほど……それなら確かに、あり得る話です。"
"101040-61-ヒフミ" = "で、ですが、それってお高いのでは……私の貯金じゃ……#nいえ、私たち4人のお金を合わせてもおそらく入手は難しいような…… "
"101040-62-コハル" = "え！？私たち4人！？なんで！？"
"101040-63-ヒフミ" = "の、残された方法は……あ、あうう……#nやっぱり、手っ取り早いのは――"
"101040-64-コハル" = "な、何でスマホを出すの？誰に連絡するつもり？#nやめて！とりあえずやめて！"
"101040-65-ハナコ" = "あらあら♡ヒフミちゃん、本気の目をしていますね。"
"101040-66-ヒフミ" = "で、でも伝説のグッズを手に入れるためには……色々なものを犠牲にすることもやむなしでして……"
"101040-67" = "何言ってんのヒフミ！しっかりして！！"
"101040-68-アズサ" = "いや……私はただ、一緒に見に行こうという話をしたかっただけなんだが…… "
"101040-69-ヒフミ" = "は、はい！？そ、そうだったんですか？#nあ、いえ、それが普通だとは……思いますが……"
"101040-70-アズサ" = "……必ず手に入れなければならないのか？"
"101040-71-アズサ" = "……分かった。ヒフミが望むのなら、そうしよう。"
"101040-72-ヒフミ" = "へっ！？"
"101040-73-アズサ" = "私はこの類の訓練は受けていないから、専門家に比べたら上手くないと思う……#nだが、なんとかなるはずだ。"
"101040-74-ヒフミ" = "え！？あ、いえ大丈夫ですアズサちゃん！#n私も目を覚ましたから、そこまでしなくても大丈夫です！ "
"101040-75-アズサ" = "……そ、そうか？"
"101040-76-アズサ" = "はい！見るだけで大丈夫です！#n伝説の「ペロロジラ」のぬいぐるみを見る事ができるなんて、幸せです！"
"101040-77-アズサ" = "そうか。なら、こうしてる時間がもったいないな。すぐに出発しよう。"
"101040-78-ヒフミ" = "はい！行きましょう！ "
"101040-79-コハル" = "……。"
"101040-80-ハナコ" = "うふふっ、いいですね。#n今日の補習はこれで■■ですね♡"
"101040-81-コハル" = "……うう、何よそれ……。"
"101040-82-コハル" = "ま、待って！置いてかないでよ！"
"101040-83" = "怪しげな店"
"101040-84-ヒフミ" = "ここですか？"
"101040-85-ハナコ" = "トリニティ郊外にこんな場所があったなんて…‥知りませんでした。"
"101040-86-コハル" = "うぅ……私は何でここに……。"
"101040-87-アズサ" = "マスター、ここに例の物があると聞いた。"
"101040-88-マスター" = "ふふ……やれやれ。あなたもまた、伝説の代物に惹かれてやってきたお客様ですか……"
"101040-89-マスター" = "本来なら、一目見る事さえ叶わない逸品ですが……#nお客様方には、特別にお見せしましょう。"
"101040-90-アズサ" = "（ドキドキ）"
"101040-91-ヒフミ" = "（ごくり）"
"101040-92" = "……！？"
"101040-93-ヒフミ" = "……あれ？#nこ、これは……"
"101040-94-アズサ" = "ふふふ、いかがでしょう？#nこれが、伝説のペロロジラ1/1000スケールぬいぐるみです！#n驚いて言葉も出ないでしょう？"
"101040-95-アズサ" = "これは……ペロロジラじゃない。"
"101040-96-ヒフミ" = "はい、これはペロロサウルスです。"
"101040-97" = "な、何ですって！？"
"101040-98-ハナコ" = "うーん……似たようなものじゃないんですか？"
"101040-99-ハナコ" = "違います、全ッ然違います！"
"101040-100-ヒフミ" = "これだから素人は困る。"
"101040-101-アズサ" = "よく見てください！#nペロロジラは、もっとふくよかで、長い舌が特徴なんです。"
"101040-102-ヒフミ" = "そしてこれがペロロサウルス。#n服を着ているように見える、顔の描写がポイントです。"
"101040-103-アズサ" = "この2つは完全に異なるものだ。類似品ですらない。"
"101040-104-マスター" = "そんな……！？#n闇市で大枚はたいて仕入れたのに、違うだと！？"
"101040-105" = "トリニティ・第5ゲート"
"101040-106-アズサ" = "ペロロジラ……実物を見たかった……。"
"101040-107-ヒフミ" = "元気出してください、アズサちゃん……#nたとえペロロジラには会えなくても……私たちの心の中に生きています。"
"101040-108" = "うふふ……お二人とも、元気を出してください。"
"101040-109-コハル" = "あれ……？"
"101040-110-トリニティの生徒A" = "聴聞会の判決を撤回せよ！ "
"101040-111-トリニティの生徒B" = "裏切り者に情けなどいらない！"
"101040-112-トリニティの生徒C" = "魔女を吊るし上げろ！！"
"101040-113-イチカ" = "み、皆さん発砲は禁止っす。空に向かって撃たないでください……#nあ、隣の人にも撃っちゃダメっす。"
"101040-114-ヒフミ" = "あれは……？"
"101040-115-ハナコ" = "……聴聞会の判決に納得していない生徒たち、ですね。 "
"101040-116" = "……なるほど。聖園ミカの処遇について反対する者か……。"
"101040-117-コハル" = "もう何日目よ！まだ飽きないの？#nホントもういい加減にしてよね！"
"101040-118-ヒフミ" = "あう……でも、集会の自由というものもありまして……"
"101040-119-ハナコ" = "……パテル分派代表の座が空席となり、その後に訪れる政治的混乱を利用しようとする勢力……"
"101040-120-ハナコ" = "そして権威が失墜したティーパーティーの地位を狙う政治家…… "
"101040-121-ハナコ" = "この状況を面白がり、便乗して石を投げる者……"
"101040-122" = "ハナコちゃん……？"
"101040-123-ハナコ" = "うふふ……結局、トリニティは毒蛇の巣窟という事です♡ "
"101040-124-ヒフミ" = "あ、あうう……。"
"101040-125-ハナコ" = "……この先、ミカさんは険しい道を歩むでしょう。"
"101040-126-ハナコ" = "た、たしかにやった事は悪いことかもしれないけど……#nなにもあんな風にしなくたって……"
"101040-127-ハナコ" = "アズサちゃんは大丈夫ですか？"
"101040-128-アズサ" = "私は……"
"101040-129-アズサ" = "……ミカは、先生と一緒にアツコを助けたと聞いた。"
"101040-130" = "それだけじゃない。#nサオリも、ヒヨリも、ミサキも――スクワッド全員を助けた、と。"
"101040-131-アズサ" = "……その事実がある以上、私がミカを憎む理由はない。"
"101040-132-アズサ" = "むしろ、こうして寄ってたかって一人を攻撃する状況の方が嫌だ。"
"101040-133-ヒフミ" = "だからといって、この人たちを攻撃しちゃダメですよ、アズサちゃん……。"
"101040-134-アズサ" = "分かってる……"
"101040-135-ハナコ" = "……そうですね。#nここにいる方々も、アズサちゃんのような気持ちを持てたら良いのですが。"
"101040-136-ハナコ" = "「赦しと慈悲を知らない私たちであったとしても――いつか救われる日が来るのでしょうか？」"
"101040-137-アズサ" = "それは私にも分からない。"
"101040-138-アズサ" = "だが、たとえどのような結末が待っていようと……"
"101040-139-アズサ" = "「努力しなければならない」……でしょ！"
"101040-140-ハナコ" = "あら？コハルちゃん、よくご存じですね。"
"101040-141-アズサ" = "ま、まあね。アズサがいつも言ってるから覚えたの。"
"101040-142-ハナコ" = "……ふふっ。さすがコハルちゃん、友達のことは知り尽くしているんですね♡"
"101040-143-アズサ" = "はっ！？わ、私は……！"
"101040-144-ハナコ" = "ありがとう、コハル。私もコハルの事、もっと知りたい。"
"101040-145-ハナコ" = "また今度、あの時みたいに一緒にお風呂に入ろう。"
"101040-146-ハナコ" = "な、なっ……！？"
"101040-147-アズサ" = "あら♡私もそこに混ざっても？"
"101040-148" = "あ、あんたはダメ！！あんたが混ざったら絶対変な事するでしょ！ダメ！禁止！"
"101040-149-ヒフミ" = "あ、あうぅ……。"
"101040-150-トリニティの生徒B" = "結果を撤回しろ！あんな判決認めてなるものか！"
"101040-151-トリニティの生徒B" = "裏切り者には罰を！"
"101040-152-ナツ" = "んん……一体、これは何事？"
"101040-153-ヨシミ" = "何これ！？アイリ、ちゃんと確認した？"
"101040-154" = "えっ！？見てみるね……午後3時トリニティ第5裏門……#n限定ショコラアイスクリーム、先着100個販売……うん、ここで合ってるよ。"
"101040-155-カズサ" = "……アイスクリームトラックは見当たらないし、デモ中の生徒しかいないけど……"
"101040-156-ナツ" = "うーん……そうだ。#nそこのお嬢さんたち、ちょっと聞いてもいい？"
"101040-157" = "何？あたしらの邪魔しないでほしいんだけど！"
"101040-158-トリニティの生徒B" = "もしかして、あんたらミカの支持者！？"
"101040-159-ナツ" = "ミカ……？"
"101040-160-カズサ" = "支持……？"
"101040-161-ナツ" = "……何それ？"
"101040-162" = "ミカ派じゃないならここで一緒にデモしない？#nあのムカつく聖園ミカが引きずり下ろされる様を見届けようよ！"
"101040-163-トリニティの生徒B" = "あははっ！きっと胸がスカッとするよ！ "
"101040-164-カズサ" = "……理解した人ー？"
"101040-165-カズサ" = "（ふるふる）"
"101040-166-ヨシミ" = "（ふるふる）"
"101040-167" = "あ、分かった！#n聖園ミカ様……！ティーパーティーの！"
"101040-168-ヨシミ" = "ティーパーティー？急にどうしたの？"
"101040-169-カズサ" = "今日はショコラアイスクリームじゃないの？"
"101040-170" = "いや、そうじゃなくて……ティーパーティーは……"
"101040-171-ナツ" = "それって生徒会の？"
"101040-172-ヨシミ" = "え、どういうこと？ "
"101040-173-ヨシミ" = "カズサ、知ってた？"
"101040-174-カズサ" = "……いや。"
"101040-175-ナツ" = "やれやれ……学園のパンフレットも読んでないのかね君たちは。"
"101040-176-ヨシミ" = "うるさいナツ！あんたもどうせ、おやつタイムの事だと思ってた口でしょうが！"
"101040-177-ナツ" = "……。"
"101040-178-カズサ" = "図星じゃん。"
"101040-179-アイリ" = "と、とにかく！ "
"101040-180-アイリ" = "ティーパーティーには、ミカ様っていうすごく綺麗な人がいるんだけど……#nなんか、事件に巻き込まれちゃったらしくて……"
"101040-181" = "ここ最近、デモも多いし……それが関係してるのかも？"
"101040-182" = "そうなの……？ "
"101040-183-ヨシミ" = "あんま気にしたことなかったわ……"
"101040-184-ナツ" = "まぁ、あんまり生徒会に興味を持つ人はいないんじゃない？#n大体の人はこのデモもよく分かってないと思うし。"
"101040-185" = "まぁね。だから、もっとたくさんの生徒に知ってもらうためにデモを起こしてるんじゃん！"
"101040-186-トリニティの生徒B" = "そうそう！私も聖園ミカを見たことないけど、なんか面白そうだし！#nあはは！"
"101040-187-トリニティの生徒B" = "……ところで、アイスクリームトラック見てない？#nここで限定販売の予定だったんだけど。"
"101040-188-トリニティの生徒B" = "あ～、キッチンカーなら、デモの邪魔だから追い出したよ。"
"101040-189-ヨシミ" = "お、追い出した！？"
"101040-190" = "その……どこに行ったかとか分かりますか？"
"101040-191-トリニティの生徒A" = "そんなの知らないよ、ウザったいなぁ！#nデモに参加しないならどっか行って！邪魔！"
"101040-192" = "きゃぁっ！？"
"101040-193-アイリ" = "……。"
"101040-194-アイリ" = "あ、ありがとう、カズサちゃん……。"
"101040-195-アイリ" = "ちょっとアンタ何よ！！"
"101040-196-アイリ" = "……君、うちのアイリを突き飛ばしたりした？"
"101040-197-トリニティの生徒A" = "それなら何だって言うのよ？"
"101040-198-ヨシミ" = "……。"
"101040-199-カズサ" = "……。"
"101040-200-アイリ" = "あっ、私大丈夫だから……！カ、カズサちゃん、ナツちゃん、ヨシミちゃん！#n……そ、そんなに怒らなくても…… "
"101040-201" = "カズサ。"
"101040-202-カズサ" = "うん。"
"101040-203-ナツ" = "人は糖分が不足すると、思考が明瞭にならないよね？"
"101040-204-カズサ" = "そうだね。"
"101040-205-ナツ" = "甘さとほろ苦さが共存するチョコレートは、まさに人生といえる……#nつまり、今から起こることは全部、チョコレートのせいなんだ。"
"101040-206-カズサ" = "どういうことか全然分かんないけど、チョコレートのせいね。分かった。"
"101040-207-ナツ" = "そういうこと……つまり――"
"101040-208-ヨシミ" = "……。"
"101040-209-カズサ" = "……。"
"101040-210" = "……ん？"
"101040-211-トリニティの生徒B" = "な、何……あんたら！"
"101040-212" = "あ、あああ……。"
"101040-213-ヨシミ" = "うちのアイリに何すんのよ！！ "
"101040-214-カズサ" = "全部、チョコレートが悪い。"
"101040-215-ヨシミ" = "ただでさえ、うるさいのに、あんたらマナーもモラルもないの！？"
"101040-216-ナツ" = "よく見ておくんだ……これが糖分欠乏症に陥った、獣たちの危険性を証明したものだ、友よ。"
"101040-217-アイリ" = "み、みんな……！"
"101040-218-トリニティの生徒C" = "あんた達何なのよ！"
"101040-219-カズサ" = "相手が増えたよ！ナツはあっちをお願い！"
"101040-220-ナツ" = "はいはい、任せて。"
"101040-221-イチカ" = "皆さん、デモ中に戦闘はダメっす……はぁ……終わった。"
"101040-222-イチカ" = "あ、あー聞こえますか。第5裏門で生徒たちのトラブル発生。#n至急支援を……いえ、いつものことなので3～4人くらいで……"
"101040-223-正義実現委員会部員B" = "た、戦わないでくださーい！"
"101040-224-正義実現委員会部員A" = "落ち着いてください！"
"101040-225-カズサ" = "ちっ、サツ――じゃなくて、正義実現委員会だよ！#nみんな走って！"
"101040-226-ヨシミ" = "逃げてアイリ！こっち！"
"101040-227-アイリ" = "あ、えっ、ちょっとみんな……！？"
"101040-228-ナツ" = "この戦いの果てには……そして私たちの未来には、一体何が待ち受けているのだろうか――それはおそらく、ショコラアイスクリームだろう。それでは……アディオス。"
"101040-229" = "はやく走ってってば！"
"101040-230" = "次回;日常の亀裂（３）"
