[translation]
"101100-1" = "第10話;衝突（２）"
"101100-2-モモカ" = "リン先輩の不信任決議案が可決……？#nおやおや、これは穏やかじゃないねぇ……"
"101100-3-アユム" = "そ、そんな……リン先輩は行政官であると同時に、生徒会長代行なんですよ……！#nリン先輩の権限が停止されたら――"
"101100-4-リン" = "連邦生徒会は麻痺するでしょう――生徒会長が失踪した直後のように。"
"101100-5" = "……あなたの暴走を止めるためには、仕方ないじゃない。"
"101100-6" = "少なくとも、先生や防衛室長を見つけるまではこうするしかないわ。"
"101100-7-リン" = "……。"
"101100-8-アオイ" = "……詳細はまた明日話しましょう。#n室長全員を招集するつもりなので。"
"101100-9-アオイ" = "今日はもう休んでください、リン先輩。#n――明日は長い一日になるでしょうから。"
"101100-10-リン" = "……。"
"101100-11-アオイ" = "そこの行政官も、ぼうっとしてないで動きなさい！"
"101100-12-連邦生徒会の行政員B" = "……はっ、はい！"
"101100-13-連邦生徒会の行政員B" = "い、行くよ……！"
"101100-14-アオイ" = "モモカ、アユム。#nあなた達も帰りなさい。これは行政命令よ。"
"101100-15" = "……そ、そんな。"
"101100-16-モモカ" = "うー……ええっと……。"
"101100-17" = "……私でしたら大丈夫です。#n二人を巻き込んでしまってごめんなさい。"
"101100-18" = "あの……で、では……明日は早く来ますからね、先輩……！"
"101100-19-モモカ" = "はぁ……本当、この雰囲気しんどいなぁ……"
"101100-20-リン" = "……また明日、改めて話しましょう。アオイ。"
"101100-21-アオイ" = "……。"
"101100-22" = "……！？#nな、何者ですか……！"
"101100-23-ジェネラル" = "これはこれは。思ったよりとんとん拍子に進んだな。#nこんなにガラガラの連邦生徒会だなんて。"
"101100-24-ジェネラル" = "最悪、あの「狐」との遭遇も想定していたのだが……#nまあ、それでも結果に影響は無かっただろうが。"
"101100-25-ジェネラル" = "ここにいるのは、行政官一人か。"
"101100-26-リン" = "……！#nあなたたちは……カイザーコーポレーション……！？"
"101100-27-ジェネラル" = "……よりによって、首席行政官とはな。"
"101100-28-ジェネラル" = "ああ、無駄な抵抗はよせ。#n通信網と警報装置は全て処理済みだ。"
"101100-29-リン" = "……っ！"
"101100-30-ジェネラル" = "これより、連邦生徒会の全権限は、#n我々カイザーコーポレーションが引き継がせてもらおう。"
"101100-31" = "サンクトゥムタワーの方はどうだ？"
"101100-32-PMC兵士" = "コントロールを確保しました！"
"101100-33-ジェネラル" = "いいだろう、プレジデントに繋げろ。"
"101100-34-プレジデント" = "コホン。首尾は上々だな。こちらの通信確認も終わった。#nだが、権限掌握には少々時間が掛かりそうだ。"
"101100-35-プレジデント" = "まずは、D.U.全域に戒厳令を公布するとしよう。"
"101100-36-ジェネラル" = "これよりD.U.を行き来する全ての通信・交通・物流はシャットダウンされる。#nそれと同時に、行政機関も全て停止だ。"
"101100-37-ジェネラル" = "外部からはこのD.U.で何が起きたか分からないように……そして――"
"101100-38-リン" = "カイザーコーポレーション、一体何を企んでいるのですか？"
"101100-39-プレジデント" = "サンクトゥムタワーを掌握するのだよ。"
"101100-40-リン" = "……！"
"101100-41-プレジデント" = "……超古代兵器が手に入ったものでね。サンクトゥムタワーの力が必要になった、というわけさ。"
"101100-42-プレジデント" = "これでキヴォトスは、カイザーコーポレーションの支配下になる。#nゲマトリアでも、連邦生徒会でもない……我々が学園都市の主となるのだ。"
"101100-43-リン" = "……！"
"101100-44-プレジデント" = "君らもこれでよかったんじゃないかね？#n「学園都市」よりは「企業都市」の方が響きが良いだろう。クックック――"
"101100-45" = "[ns] \"カイザーコーポレーションが……\""
"101100-46-カンナ" = "室長は散り散りになり、連邦生徒会は事実上解散、連絡も途絶えました……#n今のサンクトゥムタワーの様子は誰にも分からない状態です。"
"101100-47-キリノ" = "うぅっ……こんな状況で、出動できないなんてあんまりです……。"
"101100-48-フブキ" = "うわぁ……面倒な事になってる……。"
"101100-49-PMC兵士A" = "おい、ドアが開いてるぞ！"
"101100-50-PMC兵士B" = "調べろ！"
"101100-51-フブキ" = "ゲッ…PMCの奴らがこっちに来る。急がないと。"
"101100-52-キリノ" = "い、行きましょう！"
"101100-53-カンナ" = "……くっ｡"
"101100-54" = "[ns] \"カンナ、傷が……\""
"101100-55-カンナ" = "……私はここまでです、先生。"
"101100-56" = "[ns] \"……！？\""
"101100-57-キリノ" = "ど、どうしてそんなことを……！"
"101100-58-フブキ" = "ちょっと、なに言ってんの！？"
"101100-59-カンナ" = "ふっ……ここは変わっていませんね……新入生合宿の時の姿そのものだ……"
"101100-60-カンナ" = "あの頃の私は、正義の味方であろうと夢を見ていたものですが……#nどうやら、変わってしまったのは私だけのようです。"
"101100-61-カンナ" = "生活安全局には……世話になったな。"
"101100-62-キリノ" = "カンナ局長……。"
"101100-63-フブキ" = "ちょ、ちょっと……こういう雰囲気、嫌なんだけど。"
"101100-64-カンナ" = "この建物を出て少し進むとD.U.外部に向かう高速鉄道駅に出ます。#n「子ウサギ公園」の近郊なので、先生もおそらくご存じかと……その後――"
"101100-65-カンナ" = "――っと、忘れるところでした。こちら、押収されていた先生の所持品の……"
"101100-66-カンナ" = "タブレットPCとスマートフォンです、どうぞ。"
"101100-67" = "[ns] \"シッテムの箱……これをどうやって？\""
"101100-68-カンナ" = "……ヴァルキューレ内部の極秘情報を収集し……先生の居場所と……#nこの機器が置いてある場所を突き止めました…… "
"101100-69-カンナ" = "カイザーグループは私のことを、企業と手を組んで腐敗しきった警官だと思っていますので……疑われずに済みました。受け取って、ください……"
"101100-70" = "[ns] シッテムの箱を受け取る。"
"101100-71-カンナ" = "現在……カイザーコーポレーションは連邦生徒会を襲撃し、#nサンクトゥムタワーの行政制御権を奪取しました……"
"101100-72-カンナ" = "このままでは、この都市は……かつてないほどの混乱に陥るでしょう……"
"101100-73-カンナ" = "これが現実だと妥協し、腐敗しきった警官の私にできる、最大限の抵抗でした……#n先生の教えがなかったら……私はまた、踏み出せずに終わっていたでしょう。"
"101100-74-カンナ" = "先生。ヴァルキューレの者が皆、私のような人間というわけではありません。"
"101100-75-カンナ" = "今もなお、正義のために闘う人が……まだまだいるはず。#nこの二人のように……"
"101100-76-キリノ" = "……。"
"101100-77-フブキ" = "……。"
"101100-78" = "[ns1] \"そんな事はない。カンナだって、立派な警官だよ。\"\n[ns2] \"ちゃんと自分の信念に従って、諦めずに行動しているからね。\""
"101100-79-カンナ" = "……。"
"101100-80" = "[s3] \"それに、これがあればもう大丈夫。\"\n[s4] \"なんとかなると思う。\""
"101100-81-カンナ" = "……？"
"101100-82-キリノ" = "先生……？"
"101100-83-フブキ" = "ん？それ、大事な物なの？"
"101100-84" = "[ns5] \"……我々は望む、七つの[ruby=なげ]嘆[/ruby]きを。\"\n[ns6] \"……我々は覚えている、ジェリコの[ruby=こそく]古則[/ruby]を。\""
"101100-85-アロナ" = "先生！！うわぁぁああん！！！ "
"101100-86-アロナ" = "ご無事でしたか！？心配したんですよ！#n急に電源も消えてしまって、本当にビックリして……！ "
"101100-87-アロナ" = "しかも今、大変な事になっていて……！"
"101100-88" = "[s7] \"うん、知ってるよ。\"\n[s8] \"アロナが無事でよかった。\""
"101100-89-アロナ" = "ぐすっ……はい。#n私は大丈夫です、先生……。"
"101100-90" = "[ns] \"それじゃもう一度、指揮を始めよっか。\""
"101100-91" = "次回;脱出（１）"
