[translation]
"10033070-1" = "第7話;それぞれに抱えるもの"
"10033070-2-魑魅一座A" = "あーもう、あれどういうこと？"
"10033070-3-魑魅一座B" = "展望台の床、頑張って「掃除」したのにね。"
"10033070-4-魑魅一座B" = "まさかそれで遊び始めるなんて……。"
"10033070-5-魑魅一座A" = "「これを好む者はこれを楽しむ者に如かず」……だっけ。"
"10033070-6-魑魅一座B" = "あー……まあ「楽しんだもん勝ち」って言葉もあるしね。#nいやぁ、爆弾がどうとか言い出した時はヒヤッとしたけど。"
"10033070-7-魑魅一座A" = "そんなことされたら、後片付けが大変だもんね……。"
"10033070-8-アラタ" = "呑気にそんなこと言ってる場合かっ！！"
"10033070-9-アラタ" = "あ、リーダーお帰りなさい！"
"10033070-10-魑魅一座A" = "どうでした、#n「肝試しコースで本物が出たらゲヘナも腰を抜かすんじゃないか計画」は？"
"10033070-11-アラタ" = "……撤退だよ！#n戦略的な撤退！"
"10033070-12-魑魅一座A" = "帰りがけに見ましたけど……#nゲヘナの奴ら、何かそれも楽しまれてませんでした？"
"10033070-13-魑魅一座B" = "あー、何か花火が上がってたのってそれですか？#n確かに遠目から見ても楽しそうでしたね。"
"10033070-14-魑魅一座A" = "にしても、工房でいきなり温泉を掘ろうとしてたのはビビった……。"
"10033070-15-魑魅一座B" = "やっぱりゲヘナはネジ飛んでるよ……。"
"10033070-16-魑魅一座A" = "分かる……#nあ、でもクサヤジャムトーストはちょっと食べたい。"
"10033070-17-魑魅一座B" = "お前もネジ飛んでるなぁ！？#n作る過程で三途の川が見えたぞあれ！？"
"10033070-18-魑魅一座A" = "でも、美味しそうに食べてる奴いたし……。"
"10033070-19-魑魅一座B" = "いや、あれはバケモンだろ……#n逆に、何なら食べられないのか直接聞きに行くか？"
"10033070-20-アラタ" = "だーーーーっ！#n楽しそうに話してる場合かっての！！"
"10033070-21-アラタ" = "どいつもこいつも弛んでる！#n神木祭はもう明日なんだぞ！？"
"10033070-22-アラタ" = "年に一回しかない、あたしたち百鬼夜行の大事なお祭り……。"
"10033070-23-アラタ" = "なのに、「ゲヘナが来たから開催日をそこに合わせる」だなんて！"
"10033070-24-アラタ" = "ご神木だって悲しんでるだろ絶対！"
"10033070-25-魑魅一座B" = "まあ……でも、ゲヘナの生徒だって、#nお祭りを見に来た観光客なんじゃないですか？"
"10033070-26-魑魅一座B" = "百鬼夜行は元々、観光客は大歓迎！な学区ですし……。"
"10033070-27-魑魅一座A" = "神木祭も最近じゃ、#n「今年も良い年になると良いね！」くらいのお祭りになってますしね……。"
"10033070-28-魑魅一座B" = "それにほら、ご神木としては、#nどんな名目でも人が集まるのは喜んでくれてそうじゃないです？"
"10033070-29-アラタ" = "お前らは何で向こうの肩持ってんだ！#n敵か！？敵なのか！？"
"10033070-30-魑魅一座A" = "ま、まぁまぁ……#n「本当は百鬼夜行のもののはず」って意味では、#n概ねリーダーに同意はしてますから。"
"10033070-31-アラタ" = "はぁ……よし、とにかく神木祭は明日。#n必ずやあたしたち魑魅一座で、お祭りを取り戻してやるんだから！"
"10033070-32-魑魅一座B" = "一応なんですけどリーダー……#nある意味、そのお祭りを私たちが妨害する感じなんですが、#nそれはオッケーなんです？"
"10033070-33-魑魅一座B" = "それもそうだし、何か雲行き怪しいし……。"
"10033070-34-アラタ" = "だ、大丈夫！#n最近は儀式の形式も違うし、#n少しくらい滅茶苦茶になってもあんまり問題無いはず！"
"10033070-35-アラタ" = "とにかく「百鬼夜行の祭りは百鬼夜行のものだ」って伝われば良い！#nそれをゲヘナの奴らにも見せつけてやる！"
"10033070-36-魑魅一座B" = "それはそうっすね。#n百鬼夜行のもので……つまりは、私たち魑魅一座のものでもある。"
"10033070-37-魑魅一座B" = "ま、ここまでゲヘナにやられっぱなしなのも癪ですしね。"
"10033070-38-魑魅一座A" = "うん、明日は気を引き締めて頑張ろうか？"
"10033070-39-魑魅一座B" = "あ、そういえば神木祭ってことは、チセ様も来るじゃん！#n楽しみ～！"
"10033070-40-魑魅一座A" = "舞をやってくれるんでしょ、絶対見たい！"
"10033070-41-アラタ" = "だ～か～ら～～！！"
"10033070-42-ウミカ" = "お、お疲れ様です、先生。"
"10033070-43-ウミカ" = "想像より、もめ事が起きずに助かりました……。"
"10033070-44" = "[s1] \"そうだね、血で血を洗う枕投げしたりとか……。\"\n[s2] \"夜の街に繰り出す生徒とかがいなくて助かった……。\""
"10033070-45-ウミカ" = "皆さん、昼間に色々あって疲労がたまってたんでしょう。"
"10033070-46-ウミカ" = "同じように疲れてるはずなのに、#n先生は夜のパトロールまでしてくださって……。"
"10033070-47" = "[s] \"ううん、少しでもウミカたちの手伝いをと思ってね。\""
"10033070-48-ウミカ" = "いえ、私の方こそダメなところばっかりで……。"
"10033070-49-ウミカ" = "……ほんと、目も当てられないくらい。"
"10033070-50-ウミカ" = "計画通りに進んだものの方が少ないくらいでしたし……。"
"10033070-51-ウミカ" = "こういう時、社長だったら……。"
"10033070-52" = "[ns3] \"頑張ることは、もちろん大事だけどね。\"\n[ns4] \"計画は、どうしようもなくズレることもあるから……。\""
"10033070-53-ウミカ" = "せ、先生？#nなんだか悲壮な目をされていますが……？"
"10033070-54-ウミカ" = "とんでもない事情でやむを得ないこともある……？#nは、はぁ……。"
"10033070-55" = "[s] \"お祭りも、毎回計画通りには行かないんじゃない？\""
"10033070-56-ウミカ" = "た、確かに……。"
"10033070-57-ウミカ" = "完璧に上手くいった、という記憶はほとんど無いですね……。"
"10033070-58-ウミカ" = "やはり現場は、突発的な出来事の連続ですし……。"
"10033070-59-ウミカ" = "……今回の、問題は。"
"10033070-60-ウミカ" = "私が今まで、#nそういった場面の対処をしてこなかったところにあるんだと思います。"
"10033070-61" = "[s] \"そうなの……？\""
"10033070-62-ウミカ" = "そういう時は、社長が何とかしてくださいますから。"
"10033070-63-ウミカ" = "情けないです……#nお祭りが好きだって言っておいて、準備は頑張ってるようでいて……。"
"10033070-64-ウミカ" = "一番大事な、一番大変なことは社長任せで……#n私、無意識の内に甘えてたんです。"
"10033070-65-ウミカ" = "今だってそうです。#n頑張らなきゃって、本当に思ってるんですけど……。"
"10033070-66-ウミカ" = "同時に心のどこかでは……社長が早く、帰ってこないかなって。#nそんなことを、考えてるんです。"
"10033070-67" = "[s5] \"どっちも本当で、良いんじゃないかな。\"\n[s6] \"投げ出したいって思ってるわけじゃないんでしょ？\""
"10033070-68-ウミカ" = "それは……。"
"10033070-69-？？？" = "隙ありぃ！"
"10033070-70" = "[ns] \"のわっ！？\""
"10033070-71-ウミカ" = "き、キララさん？エリカさん？"
"10033070-72-キララ" = "やっほ！#n二人とも脇が甘いよ～？"
"10033070-73-エリカ" = "まったく、怪我とかさせないでよ？"
"10033070-74-キララ" = "手加減したから大丈夫！#nで、何でそんな顔してんの？"
"10033070-75-ウミカ" = "それは……。"
"10033070-76-キララ" = "えー、ウミカちゃん頑張ってると思うけど？"
"10033070-77-ウミカ" = "そう、でしょうか……#nですが、計画はズレてばっかりで、上手くいってないことの方が多くて……。"
"10033070-78-エリカ" = "……私が言うのもアレだけどさ。"
"10033070-79-エリカ" = "相手はゲヘナの生徒なんだから、#nむしろこれくらいで済んで凄いと思うよ。"
"10033070-80-キララ" = "そーそー！#n自信持ってよ、ね？"
"10033070-81-キララ" = "展望台で神木もすごかったし、工芸品体験も楽しかった！#nあとご飯も最高だったよ！"
"10033070-82-エリカ" = "肝試し、は……。"
"10033070-83-ウミカ" = "び、微妙でしたか……！？"
"10033070-84-エリカ" = "あ、いや、私たちが変な楽しみ方しちゃったから。#n今更だけど申し訳ないなってだけ。"
"10033070-85-ウミカ" = "……私は。"
"10033070-86-ウミカ" = "私はもっと、もっと上手くやりたくって……#n他の人だったら、やれるはずで……。"
"10033070-87" = "[s] \"……。\""
"10033070-88-ウミカ" = "（だって、社長だったらきっと……）"
"10033070-89-キララ" = "ま、完璧なんてそうそう無いじゃん？"
"10033070-90-エリカ" = "全部事前に把握できてるならまだしも、#nそれは土台無理な話だし。"
"10033070-91-キララ" = "とにかく、あたしは今日楽しかったよ！#n明日もすっごく楽しみ！それで良いんじゃないかな？"
"10033070-92-ウミカ" = "お、お世辞でも、嬉しいです……。"
"10033070-93-エリカ" = "あはは、お世辞じゃないってば―。"
"10033070-94-エリカ" = "今更だけど、先生もウミカもお疲れ様。#nこんな時間にパトロールなんて。"
"10033070-95-キララ" = "だね、ガイドさんは大変だぁ。"
"10033070-96" = "[ns] \"まあまあ。と言うか、全然別の話なんだけど……。\""
"10033070-97-エリカ" = "んー？"
"10033070-98" = "[ns] \"もう、とっくに門限過ぎてない？\""
"10033070-99-エリカ" = "……誤魔化せなかったか。"
"10033070-100-キララ" = "あはー、逃げろ～！"
"10033070-101" = "[ns] \"待てぇー！\""
"10033070-102-ウミカ" = "（……）"
"10033070-103-ウミカ" = "（「全部事前に把握できてるならまだしも」……）"
"10033070-104-ウミカ" = "（私は、何が起きるか知ってるはず……）"
"10033070-105-ウミカ" = "（その上で、だからこそやれることが、ある……？）"
