[translation]
"10033065-1-アラタ" = "痛ぁっ！？"
"10033065-2-マコト" = "やったか！？"
"10033065-3" = "[ns] \"それはフラグ！\""
"10033065-4-イロハ" = "……まぁ、マコト先輩が黙ってても変わらなかったでしょう。"
"10033065-5-イロハ" = "まだ全然動けそうです。"
"10033065-6-イロハ" = "……仕方ありませんね。#n百鬼夜行との政治的摩擦がどうこう言ってられません、こうなったら……！"
"10033065-7-チアキ" = "イロハちゃん！？#n何かヤバいこと考えてない！？"
"10033065-8-ウミカ" = "と、とりあえず、万魔殿の方は一度お下がりください！#nフィーナ、こちらはお願いします！"
"10033065-9-フィーナ" = "ウミカはどうするんデス！？"
"10033065-10-ウミカ" = "私は……！"
"10033065-11-？？？" = "わっ、何あれ？#n何かすごいのがいるんだけど？"
"10033065-12-ウミカ" = "っ！？"
"10033065-13-カエデ" = "えーっと、時間になったから連れてきたんだけど……#nこれどういう状況！？"
"10033065-14-エリカ" = "ふぅ……キララちゃん。"
"10033065-15-キララ" = "うん、また何か起きてるねー。#nこういう時は――"
"10033065-16-キララ" = "何あれヤバーい！きもーい！！"
"10033065-17-エリカ" = "幽霊とかじゃないでしょ、あれ。#nねぇみんな、どう思う？"
"10033065-18-ゲヘナの生徒B" = "え、なにあれ幽霊？"
"10033065-19-ゲヘナの生徒B" = "いや、百鬼夜行だし「妖怪」じゃない？"
"10033065-20-ゲヘナの生徒C" = "ま、とりあえず撃ってみようよ。"
"10033065-21-ゲヘナの生徒D" = "確かに。それじゃ……！"
"10033065-22-アラタ" = "あ痛たたたたた！？#nちょっ、どうして怖がらないんだよ！？"
"10033065-23-ゲヘナの生徒D" = "あれ、当たったっぽい。#nじゃあやっぱ怪物じゃなくない？"
"10033065-24-ゲヘナの生徒B" = "まあ、もう少し撃ってみれば分かるでしょ。"
"10033065-25-ゲヘナの生徒B" = "そうそう、せっかくなら派手にやろうよ！"
"10033065-26-ゲヘナの生徒C" = "妖怪だかお化けだか知らないけど、#nせっかくなら楽しくしないとね！"
"10033065-27-ゲヘナの生徒D" = "どうせだし、お祭り騒ぎと行こうよ！#nね、怪物さん！"
"10033065-28-ウミカ" = "お祭り！？"
"10033065-29-イブキ" = "……お祭り？"
"10033065-30" = "[s] \"……そう、お祭り！だからイブキ、怖がらないで！\""
"10033065-31-イロハ" = "！！"
"10033065-32-イロハ" = "そうです、こういった催しなんです！"
"10033065-33-マコト" = "な、なるほど！#nお祭りだったのか……！"
"10033065-34-サツキ" = "そ、それなら仕方ないわね、私の催眠術が通じないのも！"
"10033065-35-チアキ" = "ほらイブキちゃん、お祭りは楽しまないと損だよ！"
"10033065-36-アラタ" = "こ、こいつら、何なんだ一体……！"
"10033065-37-アラタ" = "とにかく撤退だ！"
"10033065-38-ゲヘナの生徒たち" = "あ、逃げた！追えー！"
"10033065-39-ゲヘナの生徒B" = "逃げるな卑怯者ー！逃げるな―！"
"10033065-40-ゲヘナの生徒B" = "良いから追いかけよう、それか別の道から回り込む？"
"10033065-41-ツバキ" = "じゃあ、道はこっちだよ～……#n案内するねー。"
"10033065-42-ツバキ" = "はーい。"
"10033065-43-ウミカ" = "本当にありがとうございました、ご迷惑も沢山……。"
"10033065-44-マコト" = "キキキッ、構わん！#nこのマコト様にかかれば、大したことではない！"
"10033065-45-イロハ" = "……結構危なかったですけどね。"
"10033065-46-イブキ" = "あははっ、楽しかった～！"
"10033065-47-ウミカ" = "こんなことになってしまいましたが、#nこの後の肝試しは是非楽しんでもらえればと……。"
"10033065-48-エリカ" = "りょーかい！#nあ、そしたら幽霊と写真撮っても良い？"
"10033065-49-エリカ" = "仮に良いんだとしても、幽霊が出てきてくれないと……。"
"10033065-50-キララ" = "あははっ、優しい幽霊さんだ！"
"10033065-51-エリカ" = "……何だかすみません。"
"10033065-52-キララ" = "じゃあ行くよー、はいチーズ！"
"10033065-53-ウミカ" = "（……）"
"10033065-54-ウミカ" = "（何とか今日一日は終わった……楽しんでくれてる、みたいだけど……）"
"10033065-55-ウミカ" = "（色んなことが、めちゃくちゃで……）"
"10033065-56-ウミカ" = "（明日から、大丈夫かな……？）"
