[translation]
"10033040-1" = "第4話;ね、簡単でしょう？"
"10033040-2-ウミカ" = "こちらは、百鬼夜行の伝統工芸コーナーです！"
"10033040-3-ウミカ" = "その中でもここは、粘土を使った工芸品を作っている場所でして。"
"10033040-4-ウミカ" = "百鬼夜行のお土産として、かなりの知名度を誇っている工房なんです！"
"10033040-5-ウミカ" = "皆さんには今回、粘土を捏ねながら実際に体験をしていただきつつ――"
"10033040-6-ゲヘナの生徒B" = "何を作っても良いってこと？"
"10033040-7-ゲヘナの生徒B" = "じゃあとりあえず、こうやって……。"
"10033040-8-ゲヘナの生徒A" = "何それ、塔？#nなんで顔と両腕が付いてるの？"
"10033040-9-ゲヘナの生徒B" = "塔だからだよ！"
"10033040-10-ゲヘナの生徒B" = "まあ見てなって、こうやって頂上にも付けたら……！"
"10033040-11-ゲヘナの生徒B" = "……「塔」って言葉の意味知ってる？"
"10033040-12-ゲヘナの生徒B" = "「タワー」の「塔」でしょ！？#n知ってるけど！？"
"10033040-13-ゲヘナの生徒A" = "仕方ないな……私が手本を見せてあげるよ。#nまずクラゲと、恐竜の足を作って……。"
"10033040-14-ウミカ" = "え、えぇっと……！？"
"10033040-15" = "[ns1] \"伝統工芸と、不確定な未来が混ざり合ってる。\"\n[ns2] \"これ、放置しても大丈夫でしょうか……？\""
"10033040-16-陶磁器職人" = "だ、大丈夫ですよ。#nこれもまた、新しい文化の礎ですから。"
"10033040-17-陶磁器職人" = "文化とは混ざり合い、衝突し、変化しながら発展していくものですから。"
"10033040-18-ゲヘナの生徒C" = "手榴弾とー、白リン弾とー、あと仕上げに……。"
"10033040-19-ゲヘナの生徒D" = "対戦車地雷はどう？"
"10033040-20-ゲヘナの生徒C" = "それだ！#nあとは焼夷剤と榴散弾を混ぜてー。"
"10033040-21-ゲヘナの生徒D" = "……今更だけど、これって伝統工芸なのかな？"
"10033040-22-ゲヘナの生徒C" = "大丈夫、芸術は爆発だから！"
"10033040-23" = "[ns] \"……本当に大丈夫でしょうか？\""
"10033040-24-陶磁器職人" = "うーん……。"
"10033040-25-キララ" = "キララちゃんは何作るの？"
"10033040-26-キララ" = "んー、せっかくならバッグとか？"
"10033040-27-エリカ" = "キララちゃんらしいね……って、先生？どうしたのその顔？"
"10033040-28" = "[s3] \"ううん、癒されてただけ……。\"\n[s4] \"良し悪しではなく、癒しの問題で……。\""
"10033040-29-キララ" = "あははっ、先生はやっぱ面白いなー！"
"10033040-30-ウミカ" = "ど、どうして皆さん、一斉に爆発物を取り出して……！？"
"10033040-31-ゲヘナの生徒D" = "あー、これコンポジション爆薬だから大丈夫。#n燃えても爆発しないし、多分。"
"10033040-32-ゲヘナの生徒D" = "見た目だけなら粘土っぽくない？？"
"10033040-33-ウミカ" = "そういう問題ですかねぇ……！？"
"10033040-34-キララ" = "……いつも通りだね。"
"10033040-35-キララ" = "まぁ先生もいるんだし、問題が起きても大丈夫でしょ？#nあたしは先生のこと、信じてるから！"
"10033040-36" = "[s] \"頑張るね……。\""
"10033040-37-ゲヘナの生徒E" = "ナント、これはもしかして「刀」……！？"
"10033040-38-ゲヘナの生徒E" = "あーうん、何かここに来る途中に見かけてさ。#nかっけーなーって。"
"10033040-39-カエデ" = "すごいすごーい！#nじゃあせっかくだし、ここにカブトムシ足さない！？"
"10033040-40-ゲヘナの生徒E" = "カブトムシの武士……「カブト武士」か！#nそれなら、こっちにはクワガタ将軍も立てて……！"
"10033040-41-ツバキ" = "夢中になって、時間オーバーしないようにね……#nすぅ、すぅ……。"
"10033040-42-ウミカ" = "はっ！そ、そういえば次の移動時間は……！？#nま、まだ何とか……。"
"10033040-43" = "（そうして、各位が夢中になり始めた頃……）"
"10033040-44-アラタ" = "……今だ！"
"10033040-45" = "[ns] \"……あれ、工芸品だよね？\""
"10033040-46-カエデ" = "動いたぁ！？"
"10033040-47-フィーナ" = "歩いてマスね！？"
"10033040-48-フィーナ" = "『任侠ニャンニャン伝～再び動き出した人形たちの夜～』にも、#nこういうシーンがありマシタ！"
"10033040-49-ゲヘナの生徒B" = "え、何あれ。#nどうして動いてんの？"
"10033040-50-ゲヘナの生徒B" = "これも体験の一環？"
"10033040-51-ウミカ" = "み、皆さん落ち着いて……！#n急に立ち上がると危ないですよ！"
"10033040-52-ウミカ" = "それに、あと23分でここを出発しないと……！"
"10033040-53-カエデ" = "そっち！？"
"10033040-54-ウミカ" = "そ、「そっち」というのは……？"
"10033040-55-ウミカ" = "……な、なんで工芸品が動いてるんですかぁ！？"
"10033040-56-ゲヘナの生徒D" = "えー何これ、どういう仕組み？"
"10033040-57-ゲヘナの生徒C" = "ちょっとバラしてみない？#n誰か雷管ちょーだい。"
"10033040-58-アラタ" = "な、何だこいつら！？どうしてビビらない！？"
"10033040-59-陶磁器職人" = "な、長い工房生活の中でも、ここまでのドタバタは初めてだよ……。"
"10033040-60-メグ" = "その謎、全部お見通しだー！！"
"10033040-61" = "[ns] \"メグ！？\""
"10033040-62-温泉部の部員B" = "ふふっ……#n私たち温泉開発部の目は騙せないよ！"
"10033040-63-メグ" = "カスミ部長は追われる身……#nじゃなくて、忙しくて修学旅行には参加できなかったけど……！"
"10033040-64-温泉部の部員B" = "部長がいたら、こう言ってるはず！#n「どんな時でも、夢と温泉の手掛かりは必ずある」と！"
"10033040-65-カスミ" = "その通り！"
"10033040-66" = "[ns] \"えぇっと……つまり？\""
"10033040-67-メグ" = "なぜ、工芸品の人形が動いてるのか……。"
"10033040-68-メグ" = "それはこの地下に、温泉の水脈があるからだよ！#nその気配にあてられたってわけ！"
"10033040-69-ウミカ" = "……はいぃ？"
"10033040-70" = "[s] \"マズい、この流れは……！\""
"10033040-71-メグ" = "そこに温泉があるから我々がいる！#nいや、たとえ温泉がなくても我々がいる！"
"10033040-72-温泉部の部員A" = "水脈があるなら、あとは掘り起こすだけ！"
"10033040-73-温泉部の部員B" = "……結局、この工芸品はどうする？"
"10033040-74-メグ" = "温泉が出てくれば、きっと落ち着くよ！#nそしたらここのマスコットとして採用しちゃおう！"
"10033040-75-温泉部の部員B" = "なるほど！"
"10033040-76-メグ" = "さぁ、爆破して掘削して開発しよう！#nみんな、機材は持ったかな！？"
"10033040-77-温泉部の部員B" = "温泉の時間だーー！！！"
"10033040-78-アラタ" = "こいつら正気か！？"
"10033040-79-キララ" = "あー……また始まった。"
"10033040-80-キララ" = "あははっ、温泉開発部はヤバいねぇ？"
"10033040-81-ウミカ" = "こ、これは、大変な事態なのでは……！？"
"10033040-82-陶磁器職人" = "……。"
"10033040-83-陶磁器職人" = "起きることには、全て理由がある……。"
"10033040-84-陶磁器職人" = "これもまた、新しい文化が生まれる瞬間なのか……！"
"10033040-85-ウミカ" = "そうなのですか！？"
"10033040-86" = "[ns] \"違うと思うよ！？\""
"10033040-87" = "[ns] \"とりあえず、ガイドチーム集合！\""
"10033040-88-ウミカ" = "で、ですよねっ！"
"10033040-89-フィーナ" = "行きマスか、お頭ぁ！"
"10033040-90-カエデ" = "いやぁ参ったねー！"
"10033040-91-ツバキ" = "みんな、一旦私の後ろに……。"
"10033040-92-エリカ" = "お待たせ、先生！ウミカちゃん！"
"10033040-93-エリカ" = "はぁ……本当にごめんね。"
"10033040-94" = "[s] \"キララ、エリカ！\""
"10033040-95-キララ" = "とりあえず、温泉開発部の子を頼んでも良い？"
"10033040-96-キララ" = "他の子はあたしたちで何とかするからさ！"
