[translation]
"10033090-1" = "第9話;このお祭りは誰のもの？"
"10033090-2-ウミカ" = "い、一体何を……！？"
"10033090-3-アラタ" = "決まってる……#nこの神木祭を、魑魅一座の手で取り戻すんだ！"
"10033090-4-魑魅一座A" = "神木祭は、百鬼夜行の平和と安寧を祈る大事なお祭り……。"
"10033090-5-魑魅一座A" = "なのに、いくら招待客だからって、部外者が入り込むなんて許せない！！"
"10033090-6" = "[ns] \"……具体的な要望は？\""
"10033090-7-魑魅一座A" = "ふっふっふ……聞いて驚け見て[ruby=わなな]戦慄け[/ruby]。#n泣く子も黙る壮大な計画――"
"10033090-8-魑魅一座A" = "題して！"
"10033090-9-ウミカ" = "……ごくり。"
"10033090-10-魑魅一座A" = "神木祭のクライマックスに使われる花火、それを利用した……！"
"10033090-11-アラタ" = "「超大型花火、明るい真っ昼間に全部打ち上げちまおう計画」！！"
"10033090-12-フィーナ" = "……ハイ？"
"10033090-13-魑魅一座A" = "ふっふっふ……真っ暗な空に打ち上げてこその花火。#nそれをお昼にやっちゃえば全部台無し！"
"10033090-14-魑魅一座A" = "どうだ、ビビったか？泣いても良いぞー、謝っても良いぞ！#nまあそれで止めるかはこっち次第だけどなっ！"
"10033090-15-カエデ" = "……。"
"10033090-16-ツバキ" = "……。"
"10033090-17" = "[ns] \"……。\""
"10033090-18-魑魅一座A" = "何だその優しい視線は！？"
"10033090-19-魑魅一座A" = "ま、まさか「そうは言っても単なる脅しで、何だかんだ実行しないでしょ」#nみたいなこと考えてるのか！？"
"10033090-20-アラタ" = "あたしたちは魑魅一座だ！#n舐めるなよ！？"
"10033090-21" = "[s] \"舐めるなよと言われましても……。\""
"10033090-22-アラタ" = "優しい言葉を掛けるなよぉ！？"
"10033090-23-ゲヘナの生徒" = "何なに、今度は何の騒ぎ？"
"10033090-24-ゲヘナの生徒A" = "人が増えてるけど、これも儀式の一環？"
"10033090-25-ゲヘナの生徒B" = "そういえば百鬼夜行には、#n観客参加型のエンタメがあるって聞いたことある。"
"10033090-26-ゲヘナの生徒A" = "あー、「和楽姫」だっけ？"
"10033090-27-ゲヘナの生徒B" = "まあ、とにかく見てれば分かるんじゃない？"
"10033090-28-キララ" = "……。"
"10033090-29-キララ" = "……ねぇねぇエリカちゃん？"
"10033090-30-エリカ" = "まぁ……動いた方が良さそうだね。"
"10033090-31-キララ" = "だよねー？"
"10033090-32-エリカ" = "とりあえず、先生のところ行く？"
"10033090-33-キララ" = "うん、きっとウミカちゃんもそこにいるはず！"
"10033090-34-アラタ" = "やめてください！#nこれ以上めちゃくちゃになったら……！"
"10033090-35-ウミカ" = "花火を勝手に打ち上げるなんて、絶対に許しません！"
"10033090-36-アラタ" = "うるさい！#n許されようと許されまいと構わないから「勝手」なんだよ！"
"10033090-37-カエデ" = "ふふっ……それは残念だったね！"
"10033090-38-フィーナ" = "ハイ！#nそもそも今回の花火は、夜の打ち上げ直前まで運び込まれマセンから！"
"10033090-39-アラタ" = "な、なにぃ！？#n昔のお祭りだったら、もうとっくに運び込んでたじゃんか！#nこれだから伝統を無視する奴らは……！"
"10033090-40-ウミカ" = "っ！？"
"10033090-41-ウミカ" = "ウミカ？#nどうしマシタか？"
"10033090-42-ウミカ" = "じ、実は……！"
"10033090-43-魑魅一座A" = "ねぇリーダー、あそこにあるの花火じゃないですか？"
"10033090-44-カエデ" = "……え？"
"10033090-45-ウミカ" = "（私が前もって運び込んだせいで、逆効果に……！？）"
"10033090-46-ウミカ" = "だ、ダメなものはダメです！"
"10033090-47-ウミカ" = "ゲヘナの皆さんのためにも、先生のためにも、#nこのお祭りを支えてくれる人のためにも……！"
"10033090-48-ウミカ" = "花火には指一つ触れさせませんっ！！"
"10033090-49-フィーナ" = "お、落ち着いてクダサイ、ウミカ！"
"10033090-50-カエデ" = "こ、ここで暴れても大丈夫！？#n神木祭なのに？儀式の場所なのに！？"
"10033090-51-ツバキ" = "……やる時は、やらないと。#nそうしないと……もっと大変なことが起きちゃう。"
