[translation]
"10054110-1" = "第11話;花火"
"10054110-2-ナゴミ" = "うわぁーん！？"
"10054110-3-ナゴミ" = "どうしてぇ……！"
"10054110-4-ナゴミ" = "次は絶対痛い目に遭わせてやる！覚えてろよ……！！"
"10054110-5-ココナ" = "待ちなさーい！"
"10054110-6-ルミ" = "逃げ足はっや！"
"10054110-7-ココナ" = "まったくもう！これだから最近の子供は！"
"10054110-8" = "[ns] \"みんな、怪我はない？\""
"10054110-9-ミナ" = "ああ、無事だ。"
"10054110-10" = "[ns] （キサキは……？）"
"10054110-11-キサキ" = "雛鳥組のお行儀は今後も心配じゃが……。"
"10054110-12-キサキ" = "また縁があれば、成長していてくれると嬉しいのう。"
"10054110-13-キサキ" = "……。"
"10054110-14-キサキ" = "先生。そう心配するでない。"
"10054110-15-キサキ" = "今回のことは、妾にも非があるのじゃから。"
"10054110-16-シュン" = "皆さん、お疲れ様でした。"
"10054110-17-シュン" = "特にココナちゃん、とてもすごかったですよ。"
"10054110-18-ココナ" = "い、いきなりどうしたの……？"
"10054110-19" = "[s] \"まさにレディーだったよ。偉い。\""
"10054110-20-ココナ" = "もう……先生まで。"
"10054110-21-ココナ" = "そもそも、私は前から立派なレディーです！"
"10054110-22" = "[s] \"うん、うん！\""
"10054110-23" = "（頭を撫でながら、みんながココナを褒めた）"
"10054110-24" = "（ココナは照れながらも、満面の笑みを見せてくれた）"
"10054110-25-ココナ" = "――ですから！あの子もそうでしたけど、小さい頃のしつけが大事なんです！"
"10054110-26-ココナ" = "褒めすぎるのは、かえって悪影響だと思います。"
"10054110-27-ココナ" = "なのに最近、みんなそれを看過しすぎているようで、心配なんですから！"
"10054110-28-ココナ" = "私だって、シュン姉さんから……。"
"10054110-29-ココナ" = "……うっ……。"
"10054110-30" = "[s] \"……大丈夫？\""
"10054110-31-ココナ" = "シュン姉さん、怒ると……怖くて……。"
"10054110-32-ココナ" = "でも怒らせなければ、本当に優しいんですよ！"
"10054110-33-ココナ" = "……シュン姉さんと遊びに来れるなんて思ってもみませんでした。"
"10054110-34-ココナ" = "昔はよく遊んでくれましたけど、シュン姉さんが教官になってからは忙しくて。"
"10054110-35-ココナ" = "だから……私も教官を目指したんです。"
"10054110-36" = "[s] \"本当によく頑張ったね。\""
"10054110-37-ココナ" = "そ、それほどでもないですよ？大したことなかったですし！"
"10054110-38-ココナ" = "……たくさん勉強してた時は、最低でも7時間は寝なさいって、#nよくシュン姉さんに叱られましたね。"
"10054110-39-ココナ" = "私も教官になってからは、お互いにもっと忙しくなってしまって……。"
"10054110-40-ココナ" = "でも……今がいいんです。"
"10054110-41-ココナ" = "先生も一緒ですし。"
"10054110-42" = "[s] \"ココナは偉いね。\""
"10054110-43-ココナ" = "（あれ……？いま、[ruby=・   ・   ・]ココナ[/ruby]って……！？）"
"10054110-44-ココナ" = "ふふん、ようやく私の魅力に気づいたみたいですね！"
"10054110-45" = "[s] \"うん！ココナちゃん最高！\""
"10054110-46-ココナ" = "あれ！？またココナちゃんですか！？"
"10054110-47-ココナ" = "さっきは呼び捨てにしてくれたのに……。"
"10054110-48" = "[s] \"そうだったかなぁ～？\""
"10054110-49-ココナ" = "もう！からかわないでください！"
"10054110-50-シュン" = "先生、ココナちゃん。"
"10054110-51-ココナ" = "シュン姉さん！"
"10054110-52-シュン" = "うふふ、夜のデート中でしたか？"
"10054110-53-ココナ" = "で、ででで、デート！？！？"
"10054110-54" = "[ns] \"そう。ココナとデートしてたんだ。\""
"10054110-55-ココナ" = "先生！？"
"10054110-56-シュン" = "それは羨ましい。お姉さんも混ぜてくれますか？"
"10054110-57-ココナ" = "……！"
"10054110-58-ココナ" = "い、いいよ！シュン姉さんだから特別ね！"
"10054110-59-シュン" = "ありがとうございます。"
"10054110-60" = "（そうして、ココナを間に挟んで3人で一緒に歩いた）"
"10054110-61" = "（たまに手つなぎブランコをして、ココナは楽しそうにしていた）"
"10054110-62-ルミ" = "お、楽しそうなことしてるね。"
"10054110-63-ミナ" = "うん？先生、私たちが何をしていたか気になるのか？"
"10054110-64-ミナ" = "フッ……夏の風物詩――花火だ！"
"10054110-65-ココナ" = "わあ！花火！すごいです！"
"10054110-66-ミナ" = "さっそく火をつけるぞ！"
"10054110-67-渓谷の商人A" = "上手くいってるかな？"
"10054110-68-ルミ" = "おかげさまで！"
"10054110-69-渓谷の商人A" = "ここから観る花火は絶景なんだ。川に映るのが綺麗でね。"
"10054110-70-ココナ" = "それは楽しみですね。"
"10054110-71-ココナ" = "一緒に観ましょう！"
"10054110-72-渓谷の商人A" = "……ありがとう。#nここを満喫してくれてるみたいで嬉しいよ。"
"10054110-73-ミナ" = "それは私たちが感謝すべきだと思うのだが……。"
"10054110-74-渓谷の商人A" = "これは、投資に対する感謝でもあるんだよ。玄武商会さん。"
"10054110-75-ルミ" = "おっと。最後まで秘密にするつもりだったんですけど……いつから？"
"10054110-76-渓谷の商人A" = "はっはっはっ……商人には、地域のネットワークがあってね。"
"10054110-77-シュン" = "……最初から言うべきでしたね。ごめんなさい。"
"10054110-78-渓谷の商人A" = "いやいや。すべての物事には理由があって……巡りめぐるものさ。"
"10054110-79-渓谷の商人A" = "巡りめぐって……今があるんだよ。"
"10054110-80-ルミ" = "物資も資金も、経済を回すことが大事ですよね。"
"10054110-81-渓谷の商人A" = "水も同じだ。"
"10054110-82-ルミ" = "あはは！たしかに。"
"10054110-83-渓谷の商人A" = "雛鳥組の件……ここを救ってくれてありがとう。"
"10054110-84-渓谷の商人A" = "いや、あの子たちはきっかけに過ぎないな。#nずっと変化を恐れていたら……ここは人々から徐々に忘れられていただろうね。"
"10054110-85-ルミ" = "ここの可能性を信じて投資を決めたのはあたしたち、玄武商会です。#nですが――"
"10054110-86-ルミ" = "玄龍門の協力がなかったら、ここまでのことは難しかったと思います。"
"10054110-87-ミナ" = "いや、それは門主様のお力であって……！"
"10054110-88-ミナ" = "って、あれ！？門主様がいない！？門主様ー！！"
"10054110-89-渓谷の商人A" = "……玄武商会と玄龍門は、あまり仲が良くないと聞いていたが。"
"10054110-90-ルミ" = "今もそうですよ。"
"10054110-91-渓谷の商人A" = "少しずつでも、改善を願っているのか？"
"10054110-92-ルミ" = "ええ。商売をするのに、敵対は何も生みませんから。"
"10054110-93-渓谷の商人A" = "それなら、さっきの発言にも納得がいく。"
"10054110-94-ルミ" = "どうでしょう？そこは秘密ということで。"
"10054110-95-渓谷の商人A" = "……君こそ先が楽しみだよ。いや、同業者として、恐ろしいというべきか。"
"10054110-96-ルミ" = "褒めすぎですよ。まだまだ学ぶべきことだらけです。"
"10054110-97-シュン" = "……あら？始まったようですね。"
"10054110-98-ココナ" = "わあ……！"
"10054110-99-渓谷の商人A" = "実は……体験してもらってないアクティビティがまだたくさん残ってるんだ。"
"10054110-100-渓谷の商人A" = "ラフティングに、洞窟ツアー、ボートツアー……。"
"10054110-101-ミナ" = "明日、体験させてもらうつもりだ。"
"10054110-102-渓谷の商人A" = "門主様は見つかったのかい？"
"10054110-103-ミナ" = "ああ。もうすぐここにいらっしゃる。"
"10054110-104-渓谷の商人A" = "何か、別の仕事をされていたのかい？#n花火で邪魔をしてしまったかな。"
"10054110-105-キサキ" = "気に病むことは無い。花火はいつやっても楽しいものじゃ。"
"10054110-106-ルミ" = "遅いよ、キサキ。"
"10054110-107-キサキ" = "すまぬ。少し昼寝をしておった。"
"10054110-108-ルミ" = "すっかり寝坊助だね！"
"10054110-109-キサキ" = "休暇に来ておるのじゃ。思う存分、心身を癒すべきじゃろう？"
"10054110-110" = "[ns] \"……キサキ？\""
"10054110-111-キサキ" = "そんなに心配せずとも大丈夫じゃよ。"
"10054110-112-キサキ" = "……ああ、この問題については、後で話をする約束じゃったな。"
"10054110-113-キサキ" = "……。"
"10054110-114-キサキ" = "案ずるでない。"
"10054110-115-キサキ" = "嘘偽りのない本心じゃ。"
"10054110-116-キサキ" = "あまりに調子が良かったものでな。ついはしゃぎすぎてしまったのじゃ。"
"10054110-117" = "[s] \"どういう意味……？\""
"10054110-118-キサキ" = "うむ、つまり……。"
"10054110-119-キサキ" = "……。"
"10054110-120-キサキ" = "遊びに夢中になり……。"
"10054110-121-キサキ" = "……薬の時間を失念しておったのじゃ。"
"10054110-122" = "[s] \"……え？\""
"10054110-123-キサキ" = "そのような目を向けんでくれ……それに、飲んでおらんかったわけではない。"
"10054110-124-キサキ" = "ただ……時間がずれて、効き目が出るのが遅くなっただけなのじゃ……。"
"10054110-125" = "[s] \"……。\""
"10054110-126-キサキ" = "実は……前にも薬を飲み忘れて、サヤに怒られたことがあったのじゃ。"
"10054110-127-キサキ" = "しかし、毎日決まった時間に飲むのも、体操をするのも……#n生きていれば、たまには疎かになることもあるじゃろう……？"
"10054110-128" = "[s] \"今度また忘れたら、本当に怒るからね……？\""
"10054110-129-キサキ" = "うっ……サヤと同じことを申すのじゃな……。"
"10054110-130-キサキ" = "……以後、気をつけよう。"
"10054110-131-キサキ" = "……うむ？約束の証明がほしい？"
"10054110-132-キサキ" = "それは構わぬが……妾は何をすればいいのかえ？"
"10054110-133-キサキ" = "なっ……サヤに自分で報告する？#nい、いくらなんでもそれは……！"
"10054110-134" = "[s] \"全部キサキのためだよ！\""
"10054110-135-キサキ" = "はぁ……それは理解しておるつもりじゃ。"
"10054110-136-キサキ" = "妾が皆の模範となるべきじゃと？そ、その通りではあるが……！"
"10054110-137-キサキ" = "う、うむ……。"
"10054110-138-キサキ" = "致し方あるまい……。"
"10054110-139-サヤ" = "キサキ門主。休暇……いや、査察は上手くいっているのか？#n錬丹術研究会のことなら心配しなくていいのだ！"
"10054110-140-サヤ" = "うん？話がある？ぼく様に？"
"10054110-141-サヤ" = "……門主？"
"10054110-142-キサキ" = "待つのじゃ。これにはそれなりの理由が……！"
"10054110-143-サヤ" = "昔、ぼく様は言ったのだ。"
"10054110-144-サヤ" = "医者の指示よりも大事な「理由」などないのだ！！"
"10054110-145-サヤ" = "しっかりしているように見えて、門主は変なところでサボるクセがあるのだ。"
"10054110-146-サヤ" = "帰ってきたら、ぼく様が直々に出迎えに行くから！ちゃんと待ってろなのだ！"
"10054110-147-キサキ" = "うぅ……。"
"10054110-148" = "[ns] \"はい、よくできました。\""
"10054110-149-キサキ" = "先生にも少し原因があると思うのじゃが！？"
"10054110-150-キサキ" = "……否。すべては妾の失念によるもの……。"
"10054110-151" = "[s] \"おいで。\""
"10054110-152-キサキ" = "……。"
"10054110-153-キサキ" = "もっと撫でてくりゃれ……。"
"10054110-154" = "（キサキが元気を取り戻すには、少し時間がかかった）"
"10054110-155-キサキ" = "山と川辺で盃を掲げ、"
"10054110-156-キサキ" = "共に酌み交わす。"
"10054110-157-キサキ" = "手を挙げ月を迎えれば、"
"10054110-158-キサキ" = "影を合わせ五つとなる。"
"10054110-159-キサキ" = "此の景色が皆を酔わせ、"
"10054110-160-キサキ" = "共に楽しみ、やがて散らん。"
"10054110-161-キサキ" = "道は川のほとりに続き、"
"10054110-162-キサキ" = "遥かな銀河にて、必ずやまた逢わん。"
