[translation]
"10054100-1" = "第10話;時には必要なもの"
"10054100-2-シュン" = "門主様の、おなりです。"
"10054100-3-ナゴミ" = "門主……？"
"10054100-4-ヨウコ" = "様……？"
"10054100-5-スイコ" = "ま、まさか！？"
"10054100-6-ルミ" = "そのまさかだよ。"
"10054100-7-ルミ" = "門主様のー！おな～り～！！！"
"10054100-8-ココナ" = "おな～り～！！"
"10054100-9" = "[ns1] \"門主様の御前だ！\"\n[ns2] \"早[ruby=こうべ]く首を[/ruby]垂れるがいい！\""
"10054100-10-キサキ" = "先生まで……堪忍してくりゃれ……。"
"10054100-11-ヨウコ" = "門主ということは、まさか、山海経の……？"
"10054100-12-ヨウコ" = "その名を軽々しく口にするな！"
"10054100-13-スイコ" = "今度は誰！？"
"10054100-14-ミナ" = "弱気を助け、強きをくじく。恩を忘れず、正義のためにひた走る！"
"10054100-15-ミナ" = "天に従い義を為せば、その道こそが我が任侠！"
"10054100-16-ミナ" = "世に言う我らは山海経――玄龍門だ！"
"10054100-17-ミナ" = "（くぅ～！決まった……！今のは最高にイカしたぞ！）"
"10054100-18-ルミ" = "……あれ、仲間外れ？"
"10054100-19-ナゴミ" = "知ってる！頭が固くて融通の利かないバカ連中でしょ！？#nお金でも動かないらしいじゃん！"
"10054100-20-ナゴミ" = "まさか、雑魚大人が生意気になったのはこいつらのせい……？"
"10054100-21-ミナ" = "……バカ……連中？"
"10054100-22-スイコ" = "なんで山海経のバカ連中がこんなとこに……？"
"10054100-23-ココナ" = "あなたたちが自分勝手すぎるからだよ！"
"10054100-24-ヨウコ" = "なんですって……？"
"10054100-25-ココナ" = "そもそもね、人は人らしい行動を見せてこそ、人なんだよ。"
"10054100-26-ココナ" = "梅花園の園児が同じことしたら、とっくにお尻ペンペンだったからね！"
"10054100-27-スイコ" = "ふ、ふん！あんただって子供のくせに！"
"10054100-28-ココナ" = "一緒にされてる！？"
"10054100-29-ココナ" = "叱るのも、しつけをするのも！全部あなたたちのためなの！"
"10054100-30-ココナ" = "私たちだって、やりたくてやってるわけじゃないんだよ？"
"10054100-31-ナゴミ" = "だったら放っといてよ！"
"10054100-32-ココナ" = "それじゃあ悪い子になっちゃうでしょ！#nあなたたちだって、トラブルばっか起こして！"
"10054100-33-ヨウコ" = "私たちは、やりたいことをするまでです……！#n大人には子供の気持ちなんて分からないんですよ！"
"10054100-34-ココナ" = "大人だって昔は子供だったんだよ？"
"10054100-35-ココナ" = "先に言っておくけど、叱られて済むうちにやめたほうがいいからね？"
"10054100-36-ココナ" = "大人になったら誰も叱ってくれなくなるんだよ？"
"10054100-37-スイコ" = "まだ子供なんだけど！？"
"10054100-38-ココナ" = "若さは免罪符にならないよ。#nそれに、あなたたちも、いつかは大人になるんだから。"
"10054100-39-キサキ" = "ココナ教官。もう十分じゃよ。"
"10054100-40-キサキ" = "言われて気づけるのなら、子供とは呼べないじゃろうて。"
"10054100-41-キサキ" = "これは妾の持論じゃが……。"
"10054100-42-キサキ" = "成熟しすぎた子は、その分、悲しみも抱えているものじゃ。"
"10054100-43-キサキ" = "故に、ここで雛鳥組を過度に叱責するのは――"
"10054100-44-キサキ" = "げほっ……！"
"10054100-45" = "[ns] \"キサキ！？\""
"10054100-46-ミナ" = "門主様！？"
"10054100-47-スイコ" = "ぜ、全員動くな！#nもし動いたら……こいつを――"
"10054100-48-ヨウコ" = "ね、ねぇ……大丈夫なの……？"
"10054100-49-ヨウコ" = "少しマズいような気が……。"
"10054100-50-スイコ" = "ビビるな！全部……他のヤツらが悪いんだから！"
"10054100-51-スイコ" = "こうなったら……全部支配してやる！#n山海経だって、何だって、全部！"
"10054100-52-ミナ" = "こいつら……。"
"10054100-53-ミナ" = "子供だからと我慢していたが……門主様に手をかけるならば……！"
"10054100-54-ミナ" = "……子供とはいえ、越えてはならない一線があります。#nそれを教える必要があるみたいですね。"
"10054100-55-ミナ" = "！？"
"10054100-56-シュン" = "子供にも許されないことはあるんですよ。"
"10054100-57-スイコ" = "えっ……？"
"10054100-58-シュン" = "ひとつ、人様に迷惑をかけてはなりません。"
"10054100-59-スイコ" = "あーっ！？"
"10054100-60-シュン" = "ふたつ。人を利益のために利用してはなりません。"
"10054100-61-スイコ" = "いったぁーい！"
"10054100-62-シュン" = "今から習慣づけしないと、後で大変な目に遭いますよ。"
"10054100-63-スイコ" = "ご、ごめんなさい！許してぇぇ！！！"
"10054100-64-シュン" = "……そこの2人も。"
"10054100-65-ヨウコ" = "ひぃっ……！？"
"10054100-66-ヨウコ" = "あうあうあう……！"
"10054100-67-シュン" = "友達が道を踏み外しても、同調してはいけません。"
"10054100-68-ナゴミ" = "うわぁーん！お尻がぁ！！"
"10054100-69-シュン" = "ダメなことはダメだと言ってあげるのが、本当の友達です。"
"10054100-70-ヨウコ" = "んぐっ……！ひぃっ……！"
"10054100-71-シュン" = "赤信号はみんなで渡れば怖くないものではありません。みんな[ruby=・   ・]でも[/ruby]、赤信号なら待つべきなんです。"
"10054100-72-ナゴミ&ヨウコ" = "あううぅぅぅぅ……！！"
"10054100-73-シュン" = "分かりましたか？"
"10054100-74-ナゴミ" = "うっ……ううぅっ……。"
"10054100-75-ナゴミ" = "あうぅぅぅ……。"
"10054100-76-ナゴミ" = "ぐすっ……うぅぅ……。"
"10054100-77-シュン" = "門主様、大丈夫ですか？"
"10054100-78-キサキ" = "……シュン教官か。世話になった。"
"10054100-79-シュン" = "いいえ。急によろめいて、びっくりしました。"
"10054100-80-キサキ" = "大丈夫じゃ。ふふ……どうやら、少し浮かれすぎてしまったようじゃ。"
"10054100-81" = "[ns] \"キサキ……。\""
"10054100-82-キサキ" = "先生……。"
"10054100-83-キサキ" = "……ふふ。"
"10054100-84-キサキ" = "あとで、二人きりでちゃんと話そう。"
"10054100-85-スイコ" = "あんたたち！よくも……よくもお尻を叩いたな！"
"10054100-86-スイコ" = "もう絶対に許さないからっ！！！"
"10054100-87-ルミ" = "……まだそんなこと言ってるの？"
"10054100-88-ココナ" = "シュン姉さんにあそこまでされたのに、まだ……！"
"10054100-89-ルミ" = "ま……これは仕方ないね！"
