[translation]
"10054030-1" = "第3話;水遊びと査察、総合的に休暇（１）"
"10054030-2-シュン" = "川は、「文明のゆりかご」とも言えます。"
"10054030-3-シュン" = "遥か昔から農業や交通、暮らしの拠点として多くの役割を果たしてきました。"
"10054030-4-キサキ" = "そうじゃな。そして、山海経にとっても大きな意味を持つ。"
"10054030-5-キサキ" = "例えば、「治める」という字。本来は、水の流れを調整するという意味だったのじゃ。"
"10054030-6-キサキ" = "洪水の後、境界線が曖昧になった土地を如何にして再分配するかが大事だったそうじゃな。"
"10054030-7-シュン" = "このことから、治水とは即ち、世を治めるという意味に拡張されたのです。"
"10054030-8-シュン" = "この査察が渓谷で行われるのも、何かしらの意味を感じますね。"
"10054030-9" = "[ns] \"わぁ……。\""
"10054030-10-ルミ" = "どう？先生。いいところでしょ。#nしばらくここで待っててくれる？"
"10054030-11-ルミ" = "あたしたちは水着に着替えてくるから。#nふふっ、楽しみにしててね？"
"10054030-12" = "（楽しそうに走っていく後ろ姿を眺めながら）"
"10054030-13" = "（自分なりの準備をして待つことにした）"
"10054030-14-ココナ" = "ココナちゃん？#nはしゃぎすぎて転ばないように気をつけてくださいね。"
"10054030-15-ココナ" = "大丈夫！私はもう立派なレディーだから！"
"10054030-16-ココナ" = "先生ー！！！"
"10054030-17" = "[s] \"ココナちゃん！\""
"10054030-18-ココナ" = "もう！またココナちゃんって呼んで～！"
"10054030-19-ココナ" = "でも、それも今日までです！#n私はもう立派なレディーですから！"
"10054030-20" = "[s] \"おぉっ！すっごく大人っぽい！\""
"10054030-21-ココナ" = "ふふん、当然です！"
"10054030-22-ココナ" = "って！違います！#n大人[ruby=・]っ[/ruby][ruby=・]ぽ[/ruby][ruby=・]い[/ruby]ではありません！レディーです！"
"10054030-23-ココナ" = "えっへん！レディーな私に似合う水着を用意したんですよ。"
"10054030-24" = "[ns] （そういうところがココナちゃんだよね！）"
"10054030-25" = "（喜びを隠しきれていないココナちゃんに……）"
"10054030-26" = "（高い高いをしてあげた！）"
"10054030-27-ココナ" = "わあ！あははっ！"
"10054030-28-ココナ" = "先生！すごいです！"
"10054030-29-ルミ" = "お～、ココナちゃん、楽しんでるね。"
"10054030-30-ココナ" = "ルミお姉さんまで「ちゃん付け」だなんて……！"
"10054030-31-ココナ" = "だって、あたしたちは査察に来てるんだから。"
"10054030-32-ココナ" = "できる限り「普通の生徒」を装うべきでしょ？"
"10054030-33-ルミ" = "あ、たしかに……！"
"10054030-34-ルミ" = "仕方ありませんね！#n特別にココナちゃん呼びを許可します！"
"10054030-35-ココナ" = "うん、うん。やっぱりココナちゃんは大人だなぁ。"
"10054030-36-ルミ" = "当然です！ルミお姉さんも分かってますね！"
"10054030-37-ルミ" = "それで……どう？"
"10054030-38" = "[s] \"な、何が？\""
"10054030-39-ルミ" = "ここでとぼけられるのは、ちょ～っと寂しいなぁ。"
"10054030-40-ルミ" = "先生のリクエスト、反映したつもりだけど……？"
"10054030-41" = "[s] \"私、リクエストしたっけ……？\""
"10054030-42-ルミ" = "してなくてもさ、あたしたちの仲でしょ？"
"10054030-43-ルミ" = "先生の好きそうなやつにしたんだけど……どうかな。"
"10054030-44" = "[s1] \"なんで私の好みが分かったの……すごく良い。\"\n[s2] \"うん、良いと思うよ。すごく似合ってる。\""
"10054030-45-ルミ" = "え、うん。ありがとう。"
"10054030-46-ルミ" = "や、あはは……率直な反応されると照れちゃうね。"
"10054030-47-ルミ" = "これだから先生は……。"
"10054030-48-ルミ" = "ま、今日のところはこれで良しかな。"
"10054030-49-ルミ" = "あらら、大人な対応。残念。"
"10054030-50-ルミ" = "まあ、先生のことはこれから知っていけばいいわけだもんね。"
"10054030-51-ルミ" = "だけど、その、似合ってるってストレートに言われると……あはは……うん。"
"10054030-52-ルミ" = "あ、ありがとう。"
"10054030-53-キサキ" = "妾も輪に入れてもらえるかの？"
"10054030-54-ココナ" = "門主様？"
"10054030-55-キサキ" = "はて。妾はキサキじゃが……。"
"10054030-56-ココナ" = "あ、そうでした！ごめんなさい、キサキお姉さん。"
"10054030-57-キサキ" = "ふふ。ココナからそう呼ばれる日がくるとは。#nこれもまた一興じゃな。"
"10054030-58" = "[ns] \"キサキ……。\""
"10054030-59-ルミ" = "おっ、気合入れたね！"
"10054030-60-キサキ" = "妾はただの高校生、[ruby=りゅうげ]竜華[/ruby]キサキ。"
"10054030-61-キサキ" = "この程度の着こなしは普通じゃよ。"
"10054030-62-キサキ" = "それで……どうじゃろうか。"
"10054030-63-キサキ" = "思いは、言葉にせんと伝わらんぞ？"
"10054030-64" = "[s] \"色々と、夢みたい……。\""
"10054030-65-キサキ" = "なるほど。好意は示しつつも明言は避け、解釈は相手に委ねる……。"
"10054030-66-キサキ" = "よかろう。合格点じゃ。"
"10054030-67-キサキ" = "ん？なんじゃ、体の調子か？ふむ……。"
"10054030-68" = "（一瞬、キサキとルミの目が合った）"
"10054030-69-ルミ" = "心なしか、いつもより軽く感じる。皆には感謝しておるぞ。"
"10054030-70-シュン" = "それはなによりです。門し――キサキさん。"
"10054030-71-シュン" = "うふふ。こんな呼び方、なんだか失礼なことをしている気分ですね。"
"10054030-72-キサキ" = "シュンか。#n……ほう？これはまた。"
"10054030-73-シュン" = "せっかくの機会ですから。キサキさんもよくお似合いですよ。"
"10054030-74-シュン" = "それで、先生は見ているだけなんですか？#nたとえありきたりな言葉でも、言ってもらうと嬉しいのですよ？"
"10054030-75" = "[s3] \"その前振りの後だとあれだけど……。\"\n[s4] \"すごく似合ってるよ。\""
"10054030-76-シュン" = "ありがとうございます。嬉しいです。"
"10054030-77-シュン" = "これで水着の感想は満足したので……この機会に、もう1つ。#n前々から言ってみたかったことがあるんです。"
"10054030-78-シュン" = "なになに？"
"10054030-79-ルミ" = "皆さん、帰るまでが遠足ですよ？"
"10054030-80-ルミ" = "シュン姉さんらしいね……。"
"10054030-81-キサキ" = "そうじゃな。"
"10054030-82-ミナ" = "さて、準備はできたようだな！#nこの場の安全は私に任せて、それぞれの役割を果たしてくれ！"
"10054030-83" = "[ns] \"よ～っし……。\""
"10054030-84-キサキ" = "わあ～川だ～！！"
"10054030-85-キサキ" = "遊びに来ているわけではないんだぞ……！"
"10054030-86" = "[ns] \"行こう！！！\""
"10054030-87-ミナ" = "まあ、いいか……観光客を演じる必要もあるし……。"
"10054030-88-ココナ" = "……冷た～い！"
"10054030-89-ココナ" = "ココナちゃん？まずは準備体操ですよ？"
"10054030-90-ココナ" = "水に入る前の体操って何をしたらいいんだっけ。"
"10054030-91-ミナ" = "私も詳しくは……。"
"10054030-92-キサキ" = "ふむ。"
"10054030-93" = "（キサキが目くばせをしてきた）"
"10054030-94-キサキ" = "では……ここは妾がお手本を見せるとしよう。"
"10054030-95-ミナ" = "もっ――キサキ……様！？"
"10054030-96-シュン" = "あら。"
"10054030-97-ココナ" = "あれ？でも……。"
"10054030-98-ルミ" = "よろしく！"
"10054030-99" = "（キサキのお手本にあわせて、みんなで「水辺のばんざい体操」をした）"
"10054030-100" = "（査察という名の休暇が始まった！）"
