[translation]
"2300206-1" = "トリニティ式の外科手術"
"2300206-2" = "トリニティ・救護騎士団の治療室"
"2300206-3-ハナエ" = "運ぶの手伝ってくれてありがとうございます、先生！"
"2300206-4-ハナエ" = "書類から抜けてる医薬品が思ったより多かったですし、もし私一人で倉庫を整理してたら一日はかかるところでした。"
"2300206-5" = "[s] \"どういたしまして、大したことじゃないよ。\""
"2300206-6-ハナエ" = "そう言ってくれると嬉しいです、えへへ。"
"2300206-7-ハナエ" = "あっ、先生、そこはさっき水拭きをしたばかりなのでご注意を……。"
"2300206-8" = "ツルッ、ドサッ！"
"2300206-9-ハナエ" = "せ、先生！大丈夫ですか！？"
"2300206-10" = "[ns] \"いたた……少し擦りむいたけど、大丈夫……。\""
"2300206-11-ハナエ" = "膝から血が出てます！早く治療をしないと……！"
"2300206-12-ハナエ" = "今すぐ足を切断して、感染を防ぎましょう！！"
"2300206-13" = "[s] \"切断！？\""
"2300206-14-ハナエ" = "えっ？#n何をそんなに驚いているんですか、先生？"
"2300206-15-ハナエ" = "早く足を切らないと、悪いばい菌が侵入して、傷口が膿んでしまうかもしれません。"
"2300206-16-ハナエ" = "前に読んだ古い医学書にも、そう書いてありました！"
"2300206-17" = "[s] \"その医学書、どれぐらい古い本……？\""
"2300206-18-ハナエ" = "えっと……だいたい500年ほど前のものかと！"
"2300206-19-ハナエ" = "大丈夫です！その本によれば、熟練の医者は1分以内に切断ができるそうなので……！"
"2300206-20-ハナエ" = "痛くないようにすぐに終わらせますから！"
"2300206-21" = "[s] \"絆創膏一つで十分だから！切らなくても大丈夫！ね！？\""
"2300206-22-ハナエ" = "本当に大丈夫ですか？"
"2300206-23-ハナエ" = "うーん……まあ今回はそうしましょうか。では、ここに座ってください！"
"2300206-24" = "[wa:400]― さあ、[wa:800]ではまず[wa:800]傷口を消毒するので、"
"2300206-25" = "― 靴下を脱いで[wa:800]大人しくしていてください！"
"2300206-26" = "[wa:400]― きちんと[wa:400]消毒しないと、"
"2300206-27" = "[wa:100]― 傷口から炎症を起こして[wa:1600]大変なことになってしまうかも[wa:1200]しれません。"
"2300206-28" = "[wa:600]― 少し痛いかもですけど、[wa:1500]我慢してくださいね！"
"2300206-29" = "― ん、[wa:400]しょっ……！[wa:900]きれい[wa:400]きれいにっ……[wa:800]と！"
"2300206-30" = "[wa:400]― はい、[wa:700]よく我慢できました！"
"2300206-31" = "― もう少しですよー。"
"2300206-32" = "[wa:500]― 特別におまけで、"
"2300206-33" = "― 傷が早く治る[wa:1100]魔法の呪文を[wa:700]かけてあげましょう！"
"2300206-34" = "― では、[wa:1300]痛いの[wa:800]痛いの、[wa:1200]飛んでけ～！"
"2300206-35" = "― どうですか？[wa:900]痛くなくなりましたか？"
"2300206-36-ハナエ" = "あとは傷に薬を塗って、その上に絆創膏を貼れば～……。"
"2300206-37-ハナエ" = "終わり！お疲れ様でした、先生！"
"2300206-38-ハナエ" = "絆創膏が剥がれないよう、気を付けてくださいね！"
"2300206-39" = "[s] 可愛い絆創膏だね。"
"2300206-40-ハナエ" = "はい、私のお気に入りの絆創膏です！色も綺麗ですし、表面から甘い香りがするんですよ！"
"2300206-41-ハナエ" = "でも小さいので、大きな傷や切断された部位には貼れないんです。"
"2300206-42-ハナエ" = "それを考えると、やっぱり足を切るわけにはいかないですよねー……。"
"2300206-43" = "[s] \"さっき考え直してくれたのって、それが理由！？\""
