[translation]
"2600302-1" = "トリニティの天使"
"2600302-2" = "（一日中仕事をしていたら体のあちこちが痛くなってしまったので、気分転換がてら外の空気を吸いに公園に来た）"
"2600302-3" = "（何となくリンゴジュースが飲みたい気分……）"
"2600302-4-セリナ" = "あっ、先生！こんにちは、こんなところでお会いできるなんて、奇遇ですね。"
"2600302-5-セリナ" = "気分転換にお散歩ですか？健康的で良いことだと思います！"
"2600302-6-セリナ" = "え、私ですか？私は、えっと……。"
"2600302-7-子供たち" = "お姉ちゃんありがとう！"
"2600302-8-子供たち" = "ありがとー！"
"2600302-9-セリナ" = "はい、どういたしまして。……ああいえ、大したことはしてないですよ。ただこの子たちが困っていたので、ちょっと手助けをしていただけで……。"
"2600302-10-子供たち" = "お姉ちゃんがね、木に引っかかった風船を取ってくれたの！"
"2600302-11-子供たち" = "ボール遊びで怪我した時も手当てしてくれた！お姉ちゃんありがとう！！"
"2600302-12-セリナ" = "いえいえ、本当に大したことじゃ……ここまで言ってもらえると、ちょっと照れてしまいますね。"
"2600302-13-セリナ" = "優しい……ですか？いえいえ、これぐらい普通ですよ。こう見えて私も、救護騎士団の一員ですし。"
"2600302-14-セリナ" = "それに……。"
"2600302-15-セリナ" = "困っていた人が喜ぶ姿を見るのは、やっぱり嬉しいことですから。"
"2600302-16-セリナ" = "なんて、ちょっとベタかもしれませんが。元々、そういう性格だったからかもしれません。"
"2600302-17-セリナ" = "それより先生、何だかお疲れのご様子ですが……大丈夫ですか？"
"2600302-18-セリナ" = "大したことないって……先生、私にそんな言い訳は通じませんよ？"
"2600302-19-セリナ" = "ちゃんと全部知ってるんですから。毎晩遅くまでお仕事をして、食事はてきとうなもので済ませて……。"
"2600302-20-セリナ" = "それでいて、人のために危ないところに行っては助けたりもして……最後のは良いことですが、このままではそのうち倒れてしまいますよ？"
"2600302-21-セリナ" = "いつでも救護できるように備えてはいますが、本当は私たちの出番が無いのが一番なんですから。"
"2600302-22-セリナ" = "……あ。"
"2600302-23-セリナ" = "す、すみません……先生相手にこんな、小言みたいなことを……。"
"2600302-24-セリナ" = "……ですが、思えば今まできちんと先生の生活を気にしたり、健康を気遣ったりということがあまりできていなかったかもしれません。"
"2600302-25-セリナ" = "大人だからと思って、無意識に疎かにしてしまっていたのでしょうか……。"
"2600302-26-セリナ" = "ごめんなさい、反省しないといけませんね。"
"2600302-27" = "[s1] \"大丈夫だよ、大人だから。\"\n[s2] \"みんなのことを気にしなきゃで大変だよね。\""
"2600302-28-セリナ" = "うう……ですから、大人だからとかそういう話ではありません！"
"2600302-29-セリナ" = "そうですね、ありがとうございます……ですが、それでもすみません。"
"2600302-30-セリナ" = "……その代わりというわけではありませんが、こちら如何ですか？リンゴジュースです。"
"2600302-31-セリナ" = "えっ、ちょうど飲みたかったんですか？それは良かったです！"
"2600302-32-セリナ" = "先生に喜んでいただけると、私も嬉しいです。"
"2600302-33-セリナ" = "……えへへ。"
"2600302-34-セリナ" = "それでは今日の残りもファイトです！でも無理せずほどほどに、ですよ！"
"2600302-35-セリナ" = "ちょっとでも辛いなと思った時には、私のことを呼んでくださいね。"
"2600302-36-セリナ" = "すぐに先生のところに駆けつけますから！"
"2600302-37" = "[s]\"うん、ありがとね。\""
"2600302-38-セリナ" = "……ふふっ。"
"2600302-39-セリナ" = "約束、ですよ？"
"2600302-40-セリナ" = "いつでも、呼んでくださいね！"
