[translation]
"10027110-1" = "第11話;特別な取引"
"10027110-2" = "レッドウィンター連邦学園・雪山"
"10027110-3-メル" = "うわぁあ！遅れる！遅れちゃう！"
"10027110-4-モミジ" = "でも、なんとかなりましたね……お疲れ様でした、先生……。"
"10027110-5" = "[ns] \"直感が言っている……これは不吉だと……！\""
"10027110-6-モミジ" = "急にどうしたんですか先生？"
"10027110-7-メル" = "え？二度あることは三度ある？#nまたまた、そんな。"
"10027110-8-モミジ" = "そうですよ！偶然が重なっただけなんじゃないですか？"
"10027110-9-ノドカ" = "「知識解放戦線」で「同人誌」を作っていると聞きました！"
"10027110-10-シグレ" = "私はいい考えがあるってノドカに言われたから付いてきたよ。"
"10027110-11-メル" = "まさか……？"
"10027110-12-シグレ" = "同人誌の内容はよく分かりませんが、とにかくそれが貴重で価値のあるものだとお聞きしましたので！"
"10027110-13-シグレ" = "それを手に入れてチェリノ会長と取り引きしたら、ストーブがもらえるかもしれないじゃん？"
"10027110-14-ノドカ" = "シグレちゃん！227号特別クラスの生活に慣れないで！？#n停学から抜け出すことを考えないと！"
"10027110-15-ノドカ" = "とにかく……チェリノ会長は欲張りですからね！#n他人が貴重だと言うのなら、何が何でも自分のものにしようとするでしょう。"
"10027110-16-ノドカ" = "私たちはチェリノ会長のそういう部分を利用して停学から抜け出し……きちんとした暖房器具があって、虫がいなくて、布団があって……飢えた熊も出てこない……「普通」の生活に戻りたいんです！"
"10027110-17-メル" = "人の同人誌をそんなことに使うな！"
