[translation]
"1000503-1" = "怠け者の朝"
"1000503-2" = "対策委員会・教室"
"1000503-3" = "（ホシノを探しに来たけど、誰もいなかった）"
"1000503-4-？？？" = "ふにゃ……くぅ……。"
"1000503-5" = "（隣の教室から声が聞こえる）"
"1000503-6" = "[s] 隣の教室に行ってみる。"
"1000503-7" = "アビドス高等学校・教室"
"1000503-8-ホシノ" = "…………。"
"1000503-9-ホシノ" = "…………ふにゃ、くぅ。"
"1000503-10" = "（机を一か所に集めて作った簡易ベッドの上で、ホシノが横になっている）"
"1000503-11" = "[s] 肩を揺らしてみる。"
"1000503-12" = "……う、うん？"
"1000503-13-ホシノ" = "わ、わあっ？！ビックリした！"
"1000503-14-ホシノ" = "先生？急にどうしたの？"
"1000503-15" = "[s] 事情を説明する。"
"1000503-16-ホシノ" = "……私のメールを見て助けにきた？"
"1000503-17-ホシノ" = "……うへ。そうだったっけ？寝ぼけてたかも、ごめんごめん。"
"1000503-18-ホシノ" = "何とか起きて登校はしたんだけど、その後はあまり記憶にない……。"
"1000503-19-ホシノ" = "気が付けばこんなところで眠ってたってことか。うへ、これまたすごいな。"
"1000503-20-ホシノ" = "心配で来てくれて、そんなセリフを聞く時が来るなんて。おじさん感激だ～。"
"1000503-21-ホシノ" = "来たついでに宝探しでもする、先生？"
"1000503-22-ホシノ" = "ほら、遠慮しないで。今日はグラウンド側の雑草の中を探してみよう！"
"1000503-23" = "（その後グラウンドの雑草の山を3時間も探してみたけど、これといった成果はなかった）"
"1000503-24" = "（ホコリまみれになったまま見送るホシノを後に、シャーレへと帰った）"
