[translation]
"1601005-1" = "マイスターの殺伐とした応援"
"1601005-2" = "シャーレ・オフィス"
"1601005-3-ヒビキ" = "おかえり、先生。"
"1601005-4-ヒビキ" = "待ってたよ。"
"1601005-5" = "[s1] \"……た、ただいま？\"\n[s2]\"その格好はどうしたの？\""
"1601005-6-ヒビキ" = "今日は先生を応援しにきたの。"
"1601005-7-ヒビキ" = "今日は先生を応援しにきたの。"
"1601005-8-ヒビキ" = "だから……前と同じように、その場に適した格好をしてるだけ。"
"1601005-9-ヒビキ" = "今日は先生を応援するんだから、この装いを着るのは当然。"
"1601005-10-ヒビキ" = "……どう？やる気、出てくる？"
"1601005-11" = "[ns3] \"……よく分からない。\"\n[ns4] \"あんまり働きたいとは思えないかな……。\""
"1601005-12-ヒビキ" = "安心して、先生。#nこの発明品を使えば、すぐに働く意欲が湧くはず。"
"1601005-13-ヒビキ" = "この前はデスク作業の性質と特性を理解できてなかったから、応援するどころか先生の集中力を乱してしまったけど……。"
"1601005-14-ヒビキ" = "……今度は大丈夫。少なくとも気が散るような事はしないから。"
"1601005-15-ヒビキ" = "……じゃーん！#nこれが用意してきた究極の応援道具だよ。"
"1601005-16" = "[s] \"……ワープロ？\""
"1601005-17-ヒビキ" = "うん。ほとんどの機能はワープロとそう変わらないよ。#n文書作成に特化したパソコン。"
"1601005-18-ヒビキ" = "……ただ、このワープロにはある特別な機能が追加されてるんだ。"
"1601005-19-ヒビキ" = "さ、先生。これ使って残りの仕事を進めてみて。"
"1601005-20-ヒビキ" = "締め切りが近ければ近いほど効果的だよ。"
"1601005-21" = "[s] \"締め切り間近の報告書を作成してみようかな。\""
"1601005-22" = "[ns] \"今のところ効果はあんまり感じられないけど……。\""
"1601005-23-ヒビキ" = "ふふっ。心配無用だよ。"
"1601005-24-ヒビキ" = "この道具の真価は、集中力が乱れた時に発揮されるから。"
"1601005-25-ヒビキ" = "……いつも通り仕事を続けてみて。"
"1601005-26" = "（約10分後……)"
"1601005-27" = "[ns] \"うーん、あんまり進まないな……。\""
"1601005-28" = "『警告。1分以上新しい文章が入力されていません』"
"1601005-29" = "『新たな文章の入力が行われなければ……2分後にデリートされます』"
"1601005-30" = "[s] \"……デリート？\""
"1601005-31-ヒビキ" = "うん。さっき言った特別な機能のことだよ。"
"1601005-32-ヒビキ" = "一度ファイルを立ち上げてから、3分間入力せずに放置したら……。"
"1601005-33-ヒビキ" = "……自爆する設定なんだ。"
"1601005-34" = "[s5] \"自爆！？\"\n[s6] \"どうしてそんな機能を？\""
"1601005-35-ヒビキ" = "締め切りが近いほど、いつも以上に集中できて、効率よく作業が進むっていうから。"
"1601005-36-ヒビキ" = "締め切りが近いほど、いつも以上に集中できて、効率よく作業が進むっていうから。"
"1601005-37-ヒビキ" = "同じ作業でも、人は環境次第で効率も変わってくるでしょ。"
"1601005-38-ヒビキ" = "この機器は作業者に、常に締め切りと同じ環境を提供してくれるんだ。"
"1601005-39-ヒビキ" = "せっかく書き進めた報告書のデータが消えてしまうという危機が迫っていたら、いくら仕事が嫌でも手を動かすしかないかなって。"
"1601005-40" = "[s] \"あ、悪魔的発想……！\""
"1601005-41-ヒビキ" = "あ、先生。自爆実行までもう1分切ってるよ。"
"1601005-42" = "[ns] \"と、とりあえず何か打てば……。\""
"1601005-43" = "『警告。先ほど入力した文章は、現在作成中のデータとは関係ない文章と判断されました』"
"1601005-44" = "『この文章は、文章を入力した時間とみなされません』"
"1601005-45" = "[s] \"……どうして？\""
"1601005-46-ヒビキ" = "このワープロには、入力済みの文章をAIが読み取って、次に想定される文を判断してるんだ。"
"1601005-47-ヒビキ" = "ただ時間を更新するために入力された文字は、カウントされないよ。"
"1601005-48-ヒビキ" = "ほら、先生。 ここまでせっかく進めた報告書、消したくないよね。"
"1601005-49-ヒビキ" = "もう少しやる気を出して、キーボードに向き合おう。"
"1601005-50" = "[s] \"……無理だって。\""
"1601005-51-ヒビキ" = "フレ～、フレ～、先生。"
"1601005-52" = "（ヒビキの発明品のおかげで、とても早く報告書を完成できたのはいいが……）"
"1601005-53" = "（悪用を防ぐために、自爆機能付きワープロは押収した）"
