[translation]
"1601002-1" = "マイスターの密やかな趣味"
"1601002-2" = "芝タウン・外郭生地市場"
"1601002-3" = "（シャーレ近くの市場で、偶然ヒビキと出会った）"
"1601002-4-ヒビキ" = "……あ、先生。"
"1601002-5-ヒビキ" = "休日にこんな人がまばらなところで先生に会えるなんてね。"
"1601002-6-ヒビキ" = "なんの生地を買いにきたの？"
"1601002-7-ヒビキ" = "……シャーレの事務所にかかってるカーテンが傷んでるから、交換しようと思って？"
"1601002-8-ヒビキ" = "……うん、そっか。カーテン用の大きい生地は、#nD.U.の近くだとあんまりないからね。"
"1601002-9-ヒビキ" = "もしカモフラージュ機能が必要だったら、オススメの手芸店があるんだけど……"
"1601002-10" = "[s] \"普通の生地で大丈夫だよ。\""
"1601002-11" = "[ns] \"ヒビキは何を買いに来たの？\""
"1601002-12-ヒビキ" = "……私？"
"1601002-13-ヒビキ" = "私は新しい服を作ろうと思って、生地を見にきたんだ。"
"1601002-14-ヒビキ" = "色や材質の情報ならインターネットでも分かるけど……"
"1601002-15-ヒビキ" = "肌と触れるものは、やっぱり手触りも大切だから。"
"1601002-16" = "[s1] \"マイスターは自分で服も作るの？\"\n[s2] \"すごいね、ヒビキ。\""
"1601002-17-ヒビキ" = "普段の私服とかじゃなくて……。"
"1601002-18-ヒビキ" = "私が作ってるのは、コスプレ用の衣装だよ。"
"1601002-19" = "[s] コスプレ……？"
"1601002-20-ヒビキ" = "うん。先生はコスプレとか好き？"
"1601002-21" = "[s3] \"コスプレなら詳しいよ！\"\n[s4] \"よく分からないかも……。\""
"1601002-22-ヒビキ" = "……良かった。説明する手間が省けて。"
"1601002-23-ヒビキ" = "コスプレはキャラクターと同じ衣装を着て、役になりきるものだよ。"
"1601002-24-ヒビキ" = "アニメや漫画……あとはゲームなんかのキャラクターが着てるものだからね。#n既製品にはないデザインが多くて、ユーザーが自分で作ることも多いんだ。"
"1601002-25-ヒビキ" = "最初は歩行用ダミーに服を着せようと思って、参考映像を見ながら作る程度だったんだけど……"
"1601002-26-ヒビキ" = "試行錯誤してたら、ハマっちゃって。"
"1601002-27" = "[s] \"服を作るのが楽しいの？\""
"1601002-28-ヒビキ" = "……うーん、正確に言えば、誰かになりきるのが楽しいんだと思う。"
"1601002-29-ヒビキ" = "コスプレは衣装を着るだけじゃなくて、実際のキャラクターだったらこうやって動くんだろうなって考えなきゃいけないから。"
"1601002-30-ヒビキ" = "普通に生活してるだけだと、キャラクターの立場を考えて演技する機会なんてないよね。"
"1601002-31-ヒビキ" = "でもコスプレは、いくつもの可能性を考慮して実験を繰り返す、エンジニアとしての活動にも通じるところがあるんだ。"
"1601002-32-ヒビキ" = "それに……興味があった職業をちょっとだけ体験できたりもするし……。"
"1601002-33" = "[s5] \"大運動会の時みたいに？\"\n[s6] \"……チアリーダーだっけ？\""
"1601002-34-ヒビキ" = "……先生、からかわないで。"
"1601002-35-ヒビキ" = "あの時は時間がなかったから、チアリーダーの気持ちになりきれなかっただけ。"
"1601002-36-ヒビキ" = "それにあの服は、まだコスプレを始めたばかりに作ったものだから……#n誰かに見せるのはちょっと恥ずかしくて……。"
"1601002-37-ヒビキ" = "次またチアリーダーのコスプレをする時は、前よりもうまくできると思う。"
"1601002-38" = "[s7] \"それって……。\"\n[s8] \"またチアリーダーの衣装を着る予定があるの？\""
"1601002-39-ヒビキ" = "ちゃんとした予定があるわけじゃないけど……。"
"1601002-40-ヒビキ" = "ちゃんとした予定があるわけじゃないけど……。"
"1601002-41-ヒビキ" = "誰かを応援する必要があれば……また着ることもあるんじゃないかな？"
"1601002-42-ヒビキ" = "コスプレに大事なのは、衣装もだけどキャラクターになりきれる状況もだから。"
"1601002-43" = "[s] \"そうだね……今日はどんな服を作る予定なの？\""
"1601002-44-ヒビキ" = "……いい質問だね、先生。"
"1601002-45-ヒビキ" = "今日は人気アニメの「異世界軍需工場」に登場するヒロインの衣装を作ろうと思ってるんだ。"
"1601002-46-ヒビキ" = "この子は現代世界で科学者として働いてたから、中世風の異世界でも実験用の白衣を着てるのが特徴なの。"
"1601002-47-ヒビキ" = "異世界に化学繊維はないみたいだから、ポリエステルの混紡素材は使われてないはず。"
"1601002-48-ヒビキ" = "中世の技術で作れる繊維だと、亜麻で作られたリネン生地の可能性が高いんだけど……。"
"1601002-49-ヒビキ" = "ここで取り扱ってる生地は、キービジュアルのイラストと比べて少し質感が荒い感じ。"
"1601002-50-ヒビキ" = "……先生はどう思う？どんな素材の生地なら、このキャラクターの雰囲気に近づけるかな？"
"1601002-51" = "[ns] \"適当に近い色を選ぶとか……？\""
"1601002-52-ヒビキ" = "ダメだよ、先生。物語の背景を考えるのも、コスプレのリアリティを上げる重要な要素だよ。"
"1601002-53-ヒビキ" = "それにミレニアムのマイスターとして、妥協するなんてありえない。"
"1601002-54" = "[s] \"ヒビキらしいね。\""
"1601002-55-ヒビキ" = "うーん……あっちに天然繊維の専門店があるみたい。"
"1601002-56-ヒビキ" = "遮光率が高そうな色の生地も多いから、カーテンにもちょうどいいと思う。"
"1601002-57-ヒビキ" = "……それじゃあ、一緒に行こうか。"
"1601002-58" = "（その後、しばらくヒビキと生地を選びながら、楽しい時間を過ごした）"
