[translation]
"10031080-1" = "エピローグ;パーティー開始"
"10031080-2" = "（全ての問題が解決されると、パーティーを始めから仕切り直すことになった）"
"10031080-3-ヒナ" = "じゃあ、行ってくる。先生、アコ。"
"10031080-4-アコ" = "はい！が、頑張ってください！委員長！"
"10031080-5" = "[ns] \"いってらっしゃい、ヒナ。\""
"10031080-6-マコト" = "くっ！そ、[ruby=そらさき]空崎[/ruby]ヒナ……！風紀委員長め……！"
"10031080-7-マコト" = "この私の狙いが全て打ち砕かれるとは……！"
"10031080-8-マコト" = "ヒナ先輩、かっこよかった～！"
"10031080-9-マコト" = "い、イブキ！？"
"10031080-10-イロハ" = "先輩、そろそろ認めましょうよ。#n今回も結局、万魔殿の……いえ、マコト先輩の負けだって。"
"10031080-11-チアキ" = "あははっ！イロハちゃん！直球すぎじゃない？"
"10031080-12-サツキ" = "まあ、いつも通りのマコトちゃんね。"
"10031080-13-マコト" = "いや！まだだ！まだ終わりじゃない……！"
"10031080-14-マコト" = "ここ数日、あれだけ忙しいなかロクに練習できたとは思えない！"
"10031080-15-マコト" = "自分から恥をかきに来たようなものだ！"
"10031080-16-イロハ" = "マコト先輩、その言葉はフラグなのでは……"
"10031080-17-ヒナ" = "…………。"
"10031080-18-ヒナ" = "（一生懸命、練習をしてきた……）"
"10031080-19-ヒナ" = "（他の誰でもない、あなたの期待に応えるため）"
"10031080-20-ヒナ" = "（だから私は、あなたを想って……）"
"10031080-21-ヒナ" = "……今の自分にできる全力を出すだけ。"
"10031080-22" = "#video;11003"
"10031080-23" = "[ns] \"……すごい。\""
"10031080-24-マコト" = "……ぐあぁっ！な、なんだと！？"
"10031080-25-マコト" = "こ、こんな演奏を披露するとは……！#n弾けないのではなかったか……！？"
"10031080-26-マコト" = "いや、まさか……#nあの情報は、最初からこちらを欺くために仕組まれていた……？"
"10031080-27-マコト" = "ふ、風紀委員会め……！#nいつまでこの私を邪魔すれば気が済むんだ……！"
"10031080-28" = "[s] \"この舞台を用意したのはマコトだよね……\""
"10031080-29-イロハ" = "はい、これもマコト先輩が自ら招いたんですよ。"
"10031080-30-マコト" = "……はっ！ぐあぁっ！！な、なんてことだ……！！"
"10031080-31-ヒナ" = "……ふぅ。"
"10031080-32-アコ" = "委員長！素晴らしい演奏でした！"
"10031080-33-イオリ" = "いつからそんなに上手に弾けるように！？"
"10031080-34-チナツ" = "すごく素敵な音……美しかったです。"
"10031080-35-ヒナ" = "あ、うん。みんな……ありがとう。"
"10031080-36-ヒナ" = "間に合って、良かったわ……"
"10031080-37" = "[s] \"お疲れ様。ヒナの演奏……しっかり胸に届いたよ。\""
"10031080-38-ヒナ" = "せ、先生……"
"10031080-39-ヒナ" = "……うん。#nあなたがそう言ってくれるなら……頑張った甲斐があった。"
"10031080-40-ヒナ" = "ありがとう、先生。"
"10031080-41" = "[s1] \"本当にお疲れ様。事件の解決も演奏の準備も……\"\n[s2] \"心配になるから、あまり無理はしないでね？\""
"10031080-42-ヒナ" = "ん？"
"10031080-43-ヒナ" = "いや、先生が言うほど無理なんてしてない。"
"10031080-44" = "[s] \"かなり大変だったと思うんだけど……\""
"10031080-45-ヒナ" = "ああ、マコト議長が企んでた一連の問題ね。"
"10031080-46-ヒナ" = "まあ、大変じゃなかったと言ったら嘘になるけど……"
"10031080-47-ヒナ" = "万魔殿が問題を起こすのは、いつものことだから。#n今回が特別大変だったとは感じてない。"
"10031080-48-アコ" = "はい。マコト議長の暴走は、いつものことです。#nもう慣れてしまいましたね。"
"10031080-49" = "[s] \"……こういう問題って、どのくらいの頻度で起きるの？\""
"10031080-50-ヒナ" = "数えてはいないけど、大体……"
"10031080-51-ヒナ" = "年に4回くらい……？"
"10031080-52-イオリ" = "ゲヘナでは、日常のようなものだからな。"
"10031080-53-イオリ" = "議長がジッとしていると、むしろ心配になってきますから。"
"10031080-54" = "[s] \"これが……ゲヘナの日常……！\""
"10031080-55-ヒナ" = "さあ、それよりもパーティーは始まったばかりでしょう？"
"10031080-56-ヒナ" = "先生……良かったら、エスコートしてくれる？"
"10031080-57" = "[s] \"私でよければ、喜んで。\""
"10031080-58-ヒナ" = "ふふっ、じゃあ……"
"10031080-59-ヒナ" = "――よろしくね、先生。"
"10031080-60" = "（こうして騒動が収束を迎えると、楽しいパーティーの時間が始まった）"
"10031080-61" = "陽ひらく彼女たちの小夜曲"
