[translation]
"1011402-1" = "ウェイトレスの楽しさ"
"1011402-2" = "（ジュリのアルバイト先を訪れると……）"
"1011402-3-ジュリ" = "あ、先生！いらっしゃいませ！"
"1011402-4" = "[s] \"おはよう、ジュリ！お店の前でどうしたの？\""
"1011402-5-ジュリ" = "あ、その……。"
"1011402-6-ジュリ" = "先生がいらしてくるのが見えたのでつい……。"
"1011402-7-ジュリ" = "さ、さあ、中に入りましょうか！"
"1011402-8-ジュリ" = "ご注文はお決まりでしょうか、[ruby=・   ・   ・]お客様[/ruby]？"
"1011402-9" = "[s1] \"じゃあ、コーヒーで！\"\n[s2] \"じゃあ、パフェで！おすすめってありますか？\""
"1011402-10-ジュリ" = "アイスとホットがございますが……。"
"1011402-11-ジュリ" = "どちらになさいますか？"
"1011402-12-ジュリ" = "……はい、アイスコーヒーですね。#nミルクとシロップはご利用でしょうか？"
"1011402-13-ジュリ" = "かしこまりました、少々お待ちください。"
"1011402-14-ジュリ" = "おすすめですか……そうですね。"
"1011402-15-ジュリ" = "今の季節ですと、期間限定のチェリーチョコレートパフェがおすすめです。#nいかかでしょうか？"
"1011402-16-ジュリ" = "はい、ありがとうございます！"
"1011402-17-ジュリ" = "それでは、すぐお持ちいたしますね。"
"1011402-18" = "（フードやドリンクを楽しみながら、ジュリの働く姿を見守った）"
"1011402-19" = "（お店側に迷惑にならない程度に追加で注文をしていると……）"
"1011402-20-ジュリ" = "……粉砂糖の在庫が切れてしまった。"
"1011402-21-ジュリ" = "近くのスーパーで買ってきますね！"
"1011402-22-ジュリ" = "売り切れ、ですか……？"
"1011402-23-ジュリ" = "だ、大丈夫です！#nお砂糖を砕いて、でんぷんを加えれば……。"
"1011402-24-ジュリ" = "砂糖もでんぷんもないんだ……。"
"1011402-25-ジュリ" = "再入荷は明日になると言われてしまった……。"
"1011402-26-ジュリ" = "ど、どうしましょう……？"
"1011402-27-ジュリ" = "そうです、ドラッグストアに行きましょう！"
"1011402-28-ジュリ" = "ど、ドラッグストア？"
"1011402-29-ジュリ" = "はい！ブドウ糖のキャンディーがあるはずです！"
"1011402-30-ジュリ" = "これを砕いて、粉状にすれば……。"
"1011402-31-ジュリ" = "シュガーパウダーの代わりになるはず……！"
"1011402-32-ジュリ" = "お砂糖より溶けやすいですし……。"
"1011402-33-ジュリ" = "食感が違うので、もしかしたら気づかれてしまうかもしれませんが……。"
"1011402-34-ジュリ" = "お食事を提供できないよりは……！"
"1011402-35-ジュリ" = "バターが在庫切れ……？#nあんバタートースト、売り切れですか？"
"1011402-36-ジュリ" = "……バターの代わりにマーガリンをのせるのはいかがでしょう？"
"1011402-37-ジュリ" = "もちろん、味は少し違いますが……。"
"1011402-38-ジュリ" = "バターに似ていますし！"
"1011402-39-ジュリ" = "良いアイデアだけど、マーガリンも残り少なくて……。"
"1011402-40-ジュリ" = "えぇ？#nど、どうしましょう……あっ！"
"1011402-41-ジュリ" = "では、牛乳とレモン汁はありますか？"
"1011402-42-ジュリ" = "ああ、それなら冷蔵庫に……。"
"1011402-43-ジュリ" = "でしたら、何とかなるかもしれません！"
"1011402-44-ジュリ" = "まずは牛乳を温めて……。"
"1011402-45-ジュリ" = "ここにレモン汁を加えて混ぜると、牛乳が固形分と液体に分離されるので……。"
"1011402-46-ジュリ" = "これを絞るとカッテージチーズができます！#nこれなら、クリームチーズの代用として使えるはずです！"
"1011402-47-ジュリ" = "すごい……私もやってみよう！"
"1011402-48-ジュリ" = "……。"
"1011402-49-ジュリ" = "このパン、味が落ちています！"
"1011402-50-ジュリ" = "えぇ？#n仕入先からは、今日焼き上げたって聞いているのだが……。"
"1011402-51-ジュリ" = "サワードウで作ったパンは、当日焼いたのなら微かにアルコールの匂いがします。"
"1011402-52-ジュリ" = "ですが、このパンからは感じられません！#n一度、仕入先に連絡してみてください！"
"1011402-53-ジュリ" = "わ、分かった。"
"1011402-54-ジュリ" = "ジュリさんの言う通りだったよ、二日前の売れ残り品だって……。"
"1011402-55-ジュリ" = "そうでしたか……。"
"1011402-56-ジュリ" = "はあ、新しい仕入先を探さなきゃ。#nそれより、よく気づいてくれたね！ありがとう！"
"1011402-57-ジュリ" = "い、いえ、そんな……。"
"1011402-58" = "[ns] \"ジュリの食材管理は素晴らしいですから。\""
"1011402-59-ジュリ" = "せ、先生まで！？"
"1011402-60-ジュリ" = "さっきまでは混んでいましたが、だいぶ落ち着きましたね……。"
"1011402-61-ジュリ" = "ピークタイムが終われば、大体こんな感じです。#n忙しくて席に伺えませんでしたが……その、大丈夫でしたか？"
"1011402-62-ジュリ" = "えっ、私の仕事ぶりを見ていたらあっという間だったなんて……#nえへへっ、嬉しいです。"
"1011402-63-ジュリ" = "ジュリさん、休憩に入って良いよ。#n今日はとても助かった！"
"1011402-64-ジュリ" = "分かりました、ありがとうございます！"
"1011402-65-ジュリ" = "先生……お隣、失礼しても良いですか？"
"1011402-66" = "[s] \"うん、もちろん。\""
"1011402-67-ジュリ" = "では……遠慮なく。"
"1011402-68-ジュリ" = "ちょ、ちょっと近いかもしれませんね。#nあはは……。"
"1011402-69" = "[s] \"カフェの仕事、大変じゃなかった？\""
"1011402-70-ジュリ" = "そうですね……大変なこともありますが、楽しいですよ。"
"1011402-71-ジュリ" = "カフェは、給食部の仕事とは違う楽しさがあります。"
"1011402-72-ジュリ" = "例えば――ホール仕事の場合、どの料理を先に運ぶか考えなくてはいけません。"
"1011402-73-ジュリ" = "それに、カフェを利用するお客様は、甘いものを頼まれるケースが多いので……。"
"1011402-74-ジュリ" = "付け合わせの飲み物をおすすめすると、喜んでくださるんです。"
"1011402-75-ジュリ" = "中にはブラックコーヒーだけを注文するお客様もいらっしゃるので、#n無理にデザートを勧めたりはしませんが。"
"1011402-76-ジュリ" = "あと、おすすめを聞かれた時……。"
"1011402-77-ジュリ" = "お客様がよく開くメニューのページを参考にすると、だいたい当たるんです。"
"1011402-78-ジュリ" = "注文前からお水をたくさん飲む方には、冷たいドリンクをご紹介したりもしますね。"
"1011402-79-ジュリ" = "たまに、お腹からぐ～っと音が聞こえてくると、とても分かりやすいんです！"
"1011402-80-ジュリ" = "……他にも、新商品を誰よりも先に試食できたり！"
"1011402-81-ジュリ" = "この間は、桃とシャインマスカットとココナッツゼリーのジュースをいただきました！#nまだ商品名は決まっていませんが。"
"1011402-82-ジュリ" = "フルーツの甘い味とゼリーの滑らかな食感が相まって……とっても美味しかったです！"
"1011402-83-ジュリ" = "他にも……！"
"1011402-84" = "（ジュリの話を聞いていると、あっという間に時間が経ち……）"
"1011402-85-カフェのマネージャー" = "もう退勤時間だよ！みんな、お疲れ様！"
"1011402-86-アルバイトたち" = "お疲れ様でした！"
"1011402-87-ジュリ" = "お、お疲れ様でした！"
"1011402-88" = "[ns] \"お疲れ、ジュリ。とっても頑張ってたね。\""
"1011402-89-ジュリ" = "あ、ありがとうございます……。"
"1011402-90-ジュリ" = "そう言っていただけると、嬉しいです。"
"1011402-91-ジュリ" = "私もずっと見てたけど……やっぱり、ジュリさんならいけると思うんだ。"
"1011402-92-ジュリ" = "な、何がですか……？"
"1011402-93-ジュリ" = "それは……。"
"1011402-94-ジュリ" = "――「今月のウェイトレス選抜大会」！"
"1011402-95-ジュリ" = "……はい？"
"1011402-96-ジュリ" = "地域ごとに一番優秀で魅力的なカフェのウェイトレスを決める大会……？"
"1011402-97-ジュリ" = "選ばれた店は、その地域で有名になれる……？"
"1011402-98-ジュリ" = "そ、そそそそ、そんなの、私には無理です！"
"1011402-99" = "[ns] \"やりたくないんだ？\""
"1011402-100-ジュリ" = "……まだ、よく分かりません。#n少し、考える時間を……。"
"1011402-101-ジュリ" = "……。"
"1011402-102-ジュリ" = "えっと、本当に嫌いなわけではありませんが……。"
"1011402-103-ジュリ" = "でも、うまくやれるか、心配で……。"
"1011402-104" = "[s3] \"じゃあ、一緒にやってみよう。私も手伝うから！\"\n[s4] \"今日みたいに頑張れば、きっといけると思う！\""
"1011402-105-ジュリ" = "ほら、先生もこう言ってくれてるから、お願いできないかな？"
"1011402-106-ジュリ" = "……。"
"1011402-107-ジュリ" = "え、えええええ！？"
