[translation]
"1011405-1" = "ウェイトレスのサービス"
"1011405-2" = "（ジュリを待っていると、慌ただしいノック音が聞こえてきた！）"
"1011405-3-ジュリ" = "せんせぇ～！"
"1011405-4" = "[s] \"ジュリ、ひとまず落ち着いて！\""
"1011405-5-ジュリ" = "は、はい……ぐすん。"
"1011405-6-ジュリ" = "……？"
"1011405-7-ジュリ" = "い、いえ……ストーカーとかではありません。"
"1011405-8-ジュリ" = "先に話してから来るべきでしたね。"
"1011405-9-ジュリ" = "その、「今月のウェイトレス」に選ばれたおかげか……。"
"1011405-10" = "[ns1] \"カフェを訪れるお客さんが……\"\n[ns2] \"10倍も増えちゃったの！？\""
"1011405-11-ジュリ" = "最初は何とか対応していました。"
"1011405-12-ジュリ" = "売上が伸びてマネージャーさんは喜んでくれましたし、#n新しい常連客もできたんですが……。"
"1011405-13-ジュリ" = "その、ツーショット写真なんかも頼まれるようになってしまいまして……。"
"1011405-14-ジュリ" = "めっちゃ可愛いです、ジュリさん！#nこういうポーズをお願いして良いですか？"
"1011405-15-ジュリ" = "その、えっと……はい。"
"1011405-16-ジュリ" = "おぉ、最高です！#nもう少し照れた表情ください！"
"1011405-17-ジュリ" = "うぅ……。"
"1011405-18-ジュリ" = "チャンネルをご覧の皆さん、こんにちは！#nクロノス報道部です！"
"1011405-19-ジュリ" = "今日は最近話題の[ruby=うしまき]牛牧[/ruby]ジュリさんにインタビューを行っていきます！#nではまず、自己紹介からお願いします！"
"1011405-20-ジュリ" = "は、はじめまして、ジュリと言います……。"
"1011405-21-ジュリ" = "噂によりますと、ジュリさんは有名なウェイトレス選抜大会で……。"
"1011405-22-ジュリ" = "大きなグラスを振り回し、ライバルを一撃で倒したと聞きましたが、それは本当でしょうか！？"
"1011405-23-ジュリ" = "はい！？そ、そんなことしてませんよ！#nたしかに重たいグラスを運ぶ種目はありましたが……。"
"1011405-24-ジュリ" = "なんとっ！#nチャンネルをご覧の皆さん、どうやら噂は本当でした！"
"1011405-25-ジュリ" = "いやはや、さすがは大会優勝者です。"
"1011405-26-ジュリ" = "ち、違います！#nですから、私は……！"
"1011405-27-ジュリ" = "それでは次の質問へ！#nこれも噂によると、ジュリさんはミレニアム製のロボットと対決して……。"
"1011405-28-ジュリ" = "「いつか終焉は訪れ、私のようなウェイトレスは消え去る」。"
"1011405-29-ジュリ" = "「しかし、まだその時ではない。人類が敗北するには、まだ早い」――というハードボイルドなセリフを残し……。"
"1011405-30-ジュリ" = "生意気なミレニアム製のロボットに打ち勝ち、自爆を命じたのは本当ですか！？"
"1011405-31-ジュリ" = "はい！？そ、それも違います！#n私はただ……！"
"1011405-32-ジュリ" = "あのロボットが急に自爆しようとしたので、止めようと……。"
"1011405-33-ジュリ" = "なるほど、やはり噂は本当のようですね！！"
"1011405-34-ジュリ" = "皆さんご存知の通り、私たちクロノススクールはキヴォトスで最も迅速に真実のみを報道しております！"
"1011405-35-ジュリ" = "今回も無事、ジャーナリスト精神に則り取材できたことを心より嬉しく思います！"
"1011405-36-ジュリ" = "インタビューに快く応じてくださり、ありがとうございました！"
"1011405-37-ジュリ" = "ですから、話を聞いてくださいっ！"
"1011405-38-ジュリ" = "ぐすん……。"
"1011405-39" = "[ns3] \"……。\"\n[ns4] \"大変だったね……。\""
"1011405-40-ジュリ" = "いつの間にかネットにも噂が広まっていたらしくて……。"
"1011405-41-ジュリ" = "あのクロノスの方は、一応ポジティブな記事を書いてくださったようで、マネージャーさんからもお祝いしてもらいましたけど……。"
"1011405-42-ジュリ" = "でも急に名前が広まったせいで、町を歩いているとサインを求められたり……。"
"1011405-43" = "[s] \"みんなに注目されて嫌だった……？\""
"1011405-44-ジュリ" = "……。"
"1011405-45-ジュリ" = "いえ、そういうわけではありません。"
"1011405-46-ジュリ" = "親切な方ばかりですし、皆さん好意的ですから……。"
"1011405-47-ジュリ" = "決して嫌では……。"
"1011405-48-ジュリ" = "ただ、ウェイトレスの仕事に縛られているような気がして……。"
"1011405-49-ジュリ" = "こちらが忙しくなった分、給食部の仕事に出られなくなってしまい……。"
"1011405-50-ジュリ" = "先輩にも、申し訳ない気持ちが……。"
"1011405-51-ジュリ" = "そろそろウェイトレスを辞めて、給食部に戻るべきではないかと思ったんです。"
"1011405-52-ジュリ" = "私のせいで、カフェにも少なからず迷惑はかかっているはずですし……。"
"1011405-53" = "[s] \"ジュリ、よければ場所を変えようか？\""
"1011405-54-ジュリ" = "……場所、ですか？"
"1011405-55-ジュリ" = "ここは先生の休憩室では……？"
"1011405-56" = "[s5] \"そうだよ。\"\n[s6] \"ここなら落ち着けると思って。\""
"1011405-57-ジュリ" = "はい……？"
"1011405-58" = "[s] \"それに騒ぎなら、いずれ収まるからね。\""
"1011405-59-ジュリ" = "私がその気になれば、給食部にはいつでも戻れる、と……？"
"1011405-60-ジュリ" = "……たしかに、そうですね。"
"1011405-61-ジュリ" = "私に寄せられている関心は、いずれ収まるはずですし。"
"1011405-62-ジュリ" = "クロノス報道部の方が訪れた時は、驚いてしまいましたが……。"
"1011405-63-ジュリ" = "あの方たちは、常に面白そうなものを探しているだけですからね……えへへ。"
"1011405-64-ジュリ" = "それで先生？#nどうして私をここに連れてきたんですか？"
"1011405-65" = "[s] \"今ジュリに必要なのは、一人の時間だと思ってね。\""
"1011405-66-ジュリ" = "一人の時間……。"
"1011405-67-ジュリ" = "そういえば、最近ずっと忙しくて休む暇もありませんでしたね。"
"1011405-68-ジュリ" = "もちろん給食部の時も、お昼休みの前後はバタバタしていましたけど。"
"1011405-69-ジュリ" = "今に比べると、たしかに……。"
"1011405-70-ジュリ" = "ありがとうございます、先生。#n少し気持ちが楽になりました。"
"1011405-71" = "（その後も、しばらく他愛もない話が続いた）"
"1011405-72" = "（必ずしも、すべての物事に意味を見出す必要はないのだから）"
"1011405-73-ジュリ" = "あれ……もうこんな時間ですか！？"
"1011405-74" = "[s7] \"あっという間だね。\"\n[s8] \"仕事の時も、こんな感じだと良いのになぁ……。\""
"1011405-75-ジュリ" = "……そういえば、つい先生のお時間を奪ってしまいましたね。"
"1011405-76-ジュリ" = "気にしなくても大丈夫、と先生は仰いますが……。"
"1011405-77-ジュリ" = "……。"
"1011405-78-ジュリ" = "あの、先生？"
"1011405-79-ジュリ" = "もしよろしければ、パフェはいかがですか？"
"1011405-80-ジュリ" = "カフェで色々と教わったので……。"
"1011405-81" = "[s] \"……ジュリのパフェ？\""
"1011405-82-ジュリ" = "はい！#nあっ、その……無理に、食べる必要は……ありませんよ？"
"1011405-83" = "[s9] \"ここは「カフェ・シャーレ」ということで……。\"\n[s10] \"店員さん、ジュリのスペシャルパフェを一つください。\""
"1011405-84-ジュリ" = "！！！"
"1011405-85-ジュリ" = "は、はい！"
"1011405-86-ジュリ" = "少々お待ちください、[ruby=・   ・   ・]お客様[/ruby]！"
"1011405-87-ジュリ" = "食材は……あっ、すぐに買ってきます！"
"1011405-88" = "（休憩室でジュリのスペシャルパフェを待っていると……）"
"1011405-89" = "[wa:950]― [log=주리 아르바이트]「カフェ・シャーレ」にご来店くださり[/log]"
"1011405-90" = "[wa:1690]― [log=주리 아르바이트]ありがとうございます！[/log]"
"1011405-91" = "― [log=주리 아르바이트]はい、[wa:720]ご注文のスペシャルパフェです！[/log]"
"1011405-92" = "[wa:800]― [log=주리 아르바이트]ふふっ……[wa:1550]不思議な気分です。[/log]"
"1011405-93" = "[wa:1610]― [log=주리 아르바이트]ここは先生のためのカフェで――[/log]"
"1011405-94" = "― [log=주리 아르바이트]私はそのカフェの……[wa:1930]たった一人のウェイトレス……。[/log]"
"1011405-95" = "[wa:960]― [log=주리 아르바이트]先生、[wa:1210]ご存知ですか？[/log]"
"1011405-96" = "― [log=주리 아르바이트]パフェって……[wa:1640]「完璧」という意味なんだそうです。[/log]"
"1011405-97" = "[wa:1430]― [log=주리 아르바이트]お料理の腕は[wa:930]まだ完璧どころか……[/log]"
"1011405-98" = "[wa:2150]― [log=주리 아르바이트]まだまだですけど……[/log]"
"1011405-99" = "― [log=주리 아르바이트]いつかは……[wa:1570]私も作れたらなと思います。[/log]"
"1011405-100" = "― [log=주리 아르바이트]「パフェ」……[wa:1970]完璧なお料理を。[/log]"
"1011405-101" = "[ns] \"それじゃあ、いただきます！\""
"1011405-102-ジュリ" = "ど、どうぞ……！"
"1011405-103" = "（一瞬、食べるのを躊躇してしまったが、勇気を振り絞ってみると……）"
"1011405-104" = "[ns11] \"あれ……意外といけるかも？\"\n[ns12] \"甘いのに塩気もあって……美味しい！\""
"1011405-105-ジュリ" = "本当ですか！？"
"1011405-106-ジュリ" = "ど、どうして塩気も感じるのか、よく分かりませんが……。"
"1011405-107-ジュリ" = "でも先生が美味しく食べてくださって……私、幸せです！"
"1011405-108" = "[ns] \"わっ、ジュリ！？\""
"1011405-109" = "（抱きついてきたジュリを何とか落ち着かせて……）"
"1011405-110" = "（その後もパフェを食べながら、楽しい時間を過ごした）"
