[translation]
"2004905-1" = "日光浴だって……つまらない"
"2004905-2" = "（サンベッドを抱えてミサキの元へ向かった）"
"2004905-3-ミサキ" = "やっぱり来たんだ……。"
"2004905-4-ミサキ" = "それ……サンベッド？しかも二つ？"
"2004905-5-ミサキ" = "日光浴だっけ？#n……やるなんて一言も言ってないんだけど。"
"2004905-6-ミサキ" = "はぁ……分かった。"
"2004905-7" = "[s] \"……え？本当に？\""
"2004905-8-ミサキ" = "……何？"
"2004905-9-ミサキ" = "……答えるのが早くてビックリ、って。"
"2004905-10-ミサキ" = "やるって言うのも駄目なの？"
"2004905-11-ミサキ" = "……気分が乗ってるわけじゃないよ。#nどうせやるなら、さっさと済ませたいってだけ。"
"2004905-12-ミサキ" = "どうせ、無意味なんだから。"
"2004905-13-ミサキ" = "……で、ここに横になればいいの？"
"2004905-14" = "（ミサキと並んで横になり、空を見上げた）"
"2004905-15-ミサキ" = "……暑い。"
"2004905-16" = "[s] \"暑さには慣れてるって言ってなかった？\""
"2004905-17-ミサキ" = "「好き」と「慣れてる」は別でしょ。"
"2004905-18-ミサキ" = "何でわざわざこんなこと……。"
"2004905-19" = "[s1] \"セロトニンが分泌されて、気持ちが落ち着いたり……。\"\n[s2] \"体の中でビタミンDを作れるとも言われてるかな……？\""
"2004905-20-ミサキ" = "なにそれ。"
"2004905-21-ミサキ" = "どうせ変わらないよ。"
"2004905-22" = "[s] \"そうかなぁ……。\""
"2004905-23-ミサキ" = "……。"
"2004905-24-ミサキ" = "……ねえ、先生。"
"2004905-25" = "[s3] \"通り雨……！？\"\n[s4] \"とりあえず、そこの海の家に避難しよう！\""
"2004905-26-ミサキ" = "はぁ、はぁ……。"
"2004905-27" = "[s] \"座ろっか。\""
"2004905-28-ミサキ" = "結局、こうなるんだよ。"
"2004905-29-ミサキ" = "[ruby=はな]最初[/ruby]から、私は何かを楽しむのに向いてない。"
"2004905-30-ミサキ" = "どうせ、こうやって裏切られる。"
"2004905-31-ミサキ" = "それなら期待なんてしない方がいい……。"
"2004905-32-ミサキ" = "そうすれば、失望することもないから。"
"2004905-33-ミサキ" = "感情が揺らぐことも……無駄な苦労をする必要も……。"
"2004905-34" = "[ns] \"……。\""
"2004905-35-ミサキ" = "雨……止んだね。"
"2004905-36-ミサキ" = "それで、どうする？"
"2004905-37-ミサキ" = "日光浴……続けるの？"
"2004905-38" = "[s] \"……うん、続けよう。\""
"2004905-39-ミサキ" = "えっ……本気？"
"2004905-40" = "[s5] \"具体的な効果を得られなかったとしても……。\"\n[s6] \"ミサキとの思い出は残るからね。\""
"2004905-41-ミサキ" = "……。"
"2004905-42-ミサキ" = "なにそれ。"
"2004905-43-ミサキ" = "思い出って……。"
"2004905-44-ミサキ" = "虚しさに勝るものなの？"
"2004905-45" = "[s7] \"だから、一緒に続けてみない？\"\n[s8] \"答えが見つかるかもしれないよ。\""
"2004905-46-ミサキ" = "またそんなこと言って……。"
"2004905-47-ミサキ" = "……。"
"2004905-48-ミサキ" = "はぁ……。"
"2004905-49-ミサキ" = "正直、よく分からないけど……。"
"2004905-50-ミサキ" = " ……いいよ、つきあってあげる。"
