[translation]
"10021015-1-シロコ" = "……。"
"10021015-2-シロコ" = "だめ……私には……"
"10021015-3-シロコ" = "できない……"
"10021015-4-シロコ" = "これだけは……私には……"
"10021015-5-シロコ" = "先生、ごめんなさい……私には……無理……"
"10021015-6-シロコ" = "こんなことを、望んだわけじゃないの……"
"10021015-7-シロコ" = "……。"
"10021015-8-シロコ" = "……そっか。"
"10021015-9-アロナ" = "プレナパテス、沈黙――そして、別の時間軸のシロコさんは、倒れました。"
"10021015-10-シロコ" = "はぁ……はぁ……。"
"10021015-11-アロナ" = "か、勝ったのでしょうか……私たち。"
"10021015-12" = "そうみたいだね……"
"10021015-13-シロコ" = "どうして……私の方がたくさん経験を積んできたはずなのに……"
"10021015-14-シロコ" = "戦って、藻掻いて、生き抜いて……なのにどうして……#nこうなってしまったんだろう。"
"10021015-15-シロコ" = "まだ……足りなかったのかな……。"
"10021015-16" = "[ns] 倒れているシロコに近づく。"
"10021015-17" = "先生……"
"10021015-18" = "[ns] \"大丈夫。あのシロコに伝えたいことがあるんだ。\""
"10021015-19" = "うん……。"
"10021015-20-シロコ" = "ああ……そうだった。"
"10021015-21-シロコ" = "伝えたいことがあるって……言ってたよね、先生。"
"10021015-22-シロコ" = "何を――"
"10021015-23" = "[s] \"それじゃあ今度は教えてほしいんだ、シロコ。\""
"10021015-24-シロコ" = "……何を？"
"10021015-25" = "[ns1] \"一体、「何」があったの？\"\n[ns2] \"「何」が、起きたの？\""
"10021015-26-シロコ" = "どうして……"
"10021015-27-シロコ" = "そんなことを、聞くの……？"
"10021015-28-シロコ" = "言ったでしょ……私は、世界を滅ぼす存在……"
"10021015-29-シロコ" = "世界を滅亡に導いて……先生を殺して……「箱舟」を利用して、"
"10021015-30-シロコ" = "今度は、別の時間軸の世界までも滅亡させるためにやってきた、と……。"
"10021015-31-シロコ" = "そんな私に、「何」があったか……聞く、の？"
"10021015-32-シロコ" = "何か、事情があると、思ってるの？#n世界を滅亡させようとする……私に。"
"10021015-33" = "[ns] \"…………。\""
"10021015-34-ハナコ" = "……たとえその結果として、誰かに裏切られても？"
"10021015-35-シロコ" = "どうして……先生はどうして、そんなに……。"
"10021015-36" = "[s3] \"先生が生徒を信じないと、何も始まらない……。\"\n[s4] \"大人だから、みんなを信じたい。\""
"10021015-37-シロコ" = "………………………………。"
"10021015-38-アヤネ" = "先生！お待たせしました！！"
"10021015-39-ノノミ" = "助けに来ましたよ、先生！！"
"10021015-40-セリカ" = "急いで！そろそろ爆発するわよ！！"
"10021015-41-ホシノ" = "先生、シロコちゃん……大丈夫？"
"10021015-42" = "ホシノ先輩に、みんな……"
"10021015-43-ホシノ" = "シロコちゃん、お待た――"
"10021015-44-ホシノ" = "……ん？"
"10021015-45-シロコ" = "……。"
"10021015-46-ホシノ" = "君は……"
"10021015-47-シロコ" = "う……ううっ…………っ…………！"
"10021015-48-シロコ" = "うあああぁぁぁあああ――――！！！！"
"10021015-49" = "あああぁぁぁあああああああ――――！！！！"
"10021015-50-セリカ" = "あああぁぁぁぁぁあああああああ――――！！！！"
"10021015-51-セリカ" = "……。"
"10021015-52-ノノミ" = "……！？"
"10021015-53-ホシノ" = "あっ……！？"
"10021015-54-シロコ" = "……。"
"10021015-55-シロコ" = "わ、たし……わたし、の、せい、なの……！"
"10021015-56-シロコ" = "わたし、が、いるから、せかいが……滅亡、した……#nそんな、こと、望んで、ないのに……"
"10021015-57-シロコ" = "こんな結末、望んで、なかった……"
"10021015-58-シロコ" = "先生を、殺したく、なかった……！"
"10021015-59-シロコ" = "ごめん、なさい……わたし、は、こんな……"
"10021015-60-シロコ" = "最後、まで、やり通せもしない、意気地なしで、ごめんなさい。#nでも、私は、もう……だめ……むり、だよ、もう……"
"10021015-61-シロコ" = "わたしの、せい……すべて、は、わたし、がアビドスに、いたせい……"
"10021015-62-シロコ" = "わたし、が、いなければ……"
"10021015-63-シロコ" = "わたし、さえ、いなければ――！！"
"10021015-64-シロコ" = "こうなると、分かって、いたら……もらう、べきじゃ、なかった……"
"10021015-65-シロコ" = "さむくて、おなかへってて、……なんで、ここにいるのかも、分からなくて……"
"10021015-66-シロコ" = "でも、あたたかくて……"
"10021015-67-シロコ" = "あたたかい、から……もう、これ以上、さむいのは、イヤ、だから……"
"10021015-68-シロコ" = "さみしい、のは、イヤ、だから……！"
"10021015-69-シロコ" = "私が、間違っていたの……あの時、マフラーをもらわずに、そのまま、倒れていたら……"
"10021015-70-シロコ" = "どうせ、こうなって、しまうのなら……"
"10021015-71-シロコ" = "そうしたら……私が……早く、そのことに気付いていたら、先生は――みんなは、生きて、いたかも、しれないのに。"
"10021015-72-シロコ" = "私が、ここにいるから……私が、間違ったせいで……！"
"10021015-73" = "ごめんなさい……"
"10021015-74" = "先生を殺して……世界を滅ぼして……ごめんなさい……"
"10021015-75" = "先生が……色彩に、飲み込まれて……"
"10021015-76" = "私を、ここに呼んだの……すべての世界を、消すために。"
"10021015-77-シロコ" = "私……わたし、は……"
"10021015-78-アヤネ" = "……！"
"10021015-79-セリカ" = "ど、どういうことなの……！？"
"10021015-80" = "……ま、まさか。"
"10021015-81-シロコ" = "……別の時間軸の私が経験したこと、みたい。"
"10021015-82-アヤネ" = "はい……？"
"10021015-83-セリカ" = "なっ……それって……！"
"10021015-84-ノノミ" = "世界が滅亡……？#n先生が……？"
"10021015-85-ホシノ" = "……。"
"10021015-86" = "[ns] \"シロコは……\""
"10021015-87" = "[ns] \"ずっと、苦しんでいたんだね。\""
"10021015-88-ホシノ" = "……そっか。"
"10021015-89-ホシノ" = "おじさんさ、「シロコ」の眼差しが、ずっと気になってたんだよね……"
"10021015-90-ホシノ" = "でも、今の先生の言葉を聞いて、やっと分かったよ。"
"10021015-91" = "あれは……「シロコちゃん」は絶対にしない眼差し。"
"10021015-92" = "でも、どこかで見たことがあって……懐かしい感じがしたんだ。"
"10021015-93" = "誰だったかな……似てる人が、いたんだよね。"
"10021015-94" = "うーん……"
"10021015-95-ホシノ" = "ああ……"
"10021015-96-ホシノ" = "思い出した。"
"10021015-97-ホシノ" = "ここに居たんですね。"
"10021015-98-ホシノ" = "まったく……探しましたよ、"
"10021015-99-ホシノ" = "……ユメ先輩。"
"10021015-100-ホシノ" = "……私と同じ。"
"10021015-101-ホシノ" = "見覚えがあると思ったんだけど……それもそうだよね。#nアレは、私と同じだったんだよ。"
"10021015-102-ノノミ" = "……。"
"10021015-103-アヤネ" = "……え、ええっと……#nこちらのシロコ先輩は、別の世界から来た、んですよね？"
"10021015-104" = "うん、そう。"
"10021015-105-アヤネ" = "箱舟の「多次元解釈」の能力で……？#nあれ、それでは……"
"10021015-106-セリカ" = "で、でもそういうことなのよね……！？"
"10021015-107-シロコ" = "この「シロコ」は、私がそうなる可能性の一つ……"
"10021015-108-シロコ" = "……マフラー。"
"10021015-109-シロコ" = "あなたは、まだ持ってるんだね。"
"10021015-110-シロコ" = "私は……どこにやったんだっけ。"
"10021015-111-シロコ" = "思い出せない……いつ、それを失くしたのかも……もう、分からない。"
"10021015-112-シロコ" = "すごく大切だったのに、どうしてだろ……"
"10021015-113-シロコ" = "ホシノ先輩が、死んだ後だったっけ……"
"10021015-114-シロコ" = "セリカが行方不明になった時……？"
"10021015-115-シロコ" = "それとも、アヤネが生命維持装置を外した時？"
"10021015-116-シロコ" = "ノノミが、アビドスを離れて「そうなった」と連絡をもらった時？それとも――"
"10021015-117-シロコ" = "――先生が、もう蘇生の可能性がないという連絡を、もらった時？"
"10021015-118-シロコ" = "いつ、だったかな……私――"
