[translation]
"2000315-1" = "過去から学ぶ真理"
"2000315-2" = "（トリニティ・スクエアを歩いている途中で、ベンチに座るマシロを見つけた）"
"2000315-3" = "[ns1] \"読書中かな……？\"\n[ns2]（ひとまず、挨拶することにした）"
"2000315-4" = "[ns] \"こんにちは、マシロ。\""
"2000315-5-マシロ" = "あっ、先生。"
"2000315-6-マシロ" = "トリニティにいらっしゃっていたのですね。#n言ってくだされば私からご挨拶に伺ったのに。"
"2000315-7-マシロ" = "まあ、こうして会えたので構いませんが。"
"2000315-8" = "[s3] \"会えてよかったよ。\"\n[s4] \"ところで、どんな本を読んでいたの？\""
"2000315-9-マシロ" = "あ、これですか？"
"2000315-10-マシロ" = "ええと、少しお恥ずかしいのですが……"
"2000315-11-マシロ" = "こういう本です……"
"2000315-12-マシロ" = "タイトル通り、色々なことわざや四字熟語の成り立ちが#n物語で紹介されていまして。"
"2000315-13-マシロ" = "……面白そう？"
"2000315-14-マシロ" = "……。"
"2000315-15-マシロ" = "ふふっ、そうです。とても面白いのです！"
"2000315-16-マシロ" = "あまりに面白くて、ハスミ先輩にもおすすめしました。"
"2000315-17-マシロ" = "……読んでくれそうには、なかったのですが。"
"2000315-18" = "[s] \"マシロはこういうのが好きなんだね。\""
"2000315-19-マシロ" = "はい。ことわざや四字熟語そのものも好きですが、#nなにより元になった物語に興味があるのです。"
"2000315-20-マシロ" = "そのような物語には、#n長い間受け継がれてきた教訓が込められていますから。"
"2000315-21-マシロ" = "「過去を見て未来を見据える」という言葉通り、#n昔話を学べば未来への道筋も見いだせますし。"
"2000315-22" = "[s] \"おお……！\""
"2000315-23-マシロ" = "そしてなんと言っても、ここに載っている昔話には――"
"2000315-24-マシロ" = "改邪帰正、勧善懲悪のメッセージが含まれているのです！！"
"2000315-25" = "[s] \"確かに、そういう話が多いよね。\""
"2000315-26-マシロ" = "ええ、まさに「正義は勝つ」という真理そのものです。"
"2000315-27-マシロ" = "なので昔から、ことわざや四字熟語に興味を持っていまして。"
"2000315-28" = "[s5] \"なるほどね。\"\n[s6] \"マシロがはまる理由がわかったよ。\""
"2000315-29-マシロ" = "私は普段の会話でもことわざなどを使っていますが……"
"2000315-30-マシロ" = "その度に、誰も理解してくれなかったり、#n考えが古い人扱いされたりするんです。"
"2000315-31-マシロ" = "けれど……先生は、わかってくださるのですね。"
"2000315-32-マシロ" = "……貸してほしい？この本をですか？"
"2000315-33-マシロ" = "もちろんです！是非読んでみてください！ "
"2000315-34-マシロ" = "ふふっ……"
"2000315-35-マシロ" = "私が好きなものに先生が興味を持ってくださるなんて。なんだか……"
"2000315-36-マシロ" = "……ええと……"
"2000315-37-マシロ" = "ふ、不思議な気持ちと、いいますか……"
"2000315-38-マシロ" = "……と、とにかく、そんな感じです！"
"2000315-39" = "（その後もマシロとことわざや昔話のことで盛り上がり、#nたくさん話をしてからシャーレに戻った）"
