[translation]
"2001505-1" = "大人になりたい理由"
"2001505-2-カエデ" = "先生、手伝いに来たよー！"
"2001505-3-カエデ" = "……あれ、誰もいない。"
"2001505-4-カエデ" = "トイレかな？"
"2001505-5-カエデ" = "って、ああっ！机の上がめちゃくちゃ！こんなのミモリ先輩とかに見られたら怒られちゃうやつだよ！"
"2001505-6-カエデ" = "あっ、コーヒーだ。先生の飲みかけかな。"
"2001505-7-カエデ" = "……。"
"2001505-8-カエデ" = "ゴクッ……。"
"2001505-9-カエデ" = "苦っ！！！"
"2001505-10-カエデ" = "えぇ、大人ってこういうのを飲むものなの……？バナナミルクとか飲めばよいのに……。"
"2001505-11-カエデ" = "大人って大変だなぁ……というか、コーヒー冷めてる。"
"2001505-12-カエデ" = "……あ、良いこと思いついた！"
"2001505-13-カエデ" = "先生のために、熱々のコーヒーを淹れなおしてあげれば……"
"2001505-14-カエデ" = "それってまさしく、「素敵なレディー」って感じがするんじゃない！"
"2001505-15-カエデ" = "昨日見たちょっと大人っぽいドラマでも、"
"2001505-16-カエデ" = "そんな感じのシーンがあったし！"
"2001505-17-カエデ" = "よし、そうとなったら「カエデちゃん特製ブレンド」を作っちゃおーっと！"
"2001505-18-カエデ" = "ふんふん～♪"
"2001505-19-カエデ" = "これをこうしてー……"
"2001505-20-カエデ" = "うーん……これくらいで良いかな？"
"2001505-21-カエデ" = "できた、カエデちゃん特製ブレンドウルトラバージョン！"
"2001505-22-カエデ" = "先生が戻ってきてこれを見たら、きっと……"
"2001505-23-カエデ" = "えへへっ！先生ったらそんな～、いきなり欲しいオモチャはって聞かれても～！"
"2001505-24-カエデ" = "……うん、とにかくOK！これを先生の席に置いて……。"
"2001505-25-カエデ" = "のあっ！？"
"2001505-26-カエデ" = "あ、ああぁぁっ！？"
"2001505-27-カエデ" = "コーヒーがーーー！？"
"2001505-28" = "[ns] \"……とりあえず、この惨状を説明してもらって良い？\""
"2001505-29-カエデ" = "えっと、その……あくまで私は、先生のお手伝いに来ただけで……。"
"2001505-30-カエデ" = "それでシャーレに来たら先生はいないし、先生の席はめちゃくちゃだしで……。"
"2001505-31-カエデ" = "と、とりあえずコーヒーが冷めてるなって思って、淹れなおしたら先生が喜ぶかなって……。"
"2001505-32-カエデ" = "それでその、頑張ってはみたんだけど……。"
"2001505-33" = "[s] \"カエデ。\""
"2001505-34-カエデ" = "ひゃいっ！ごめんなさい！"
"2001505-35-カエデ" = "ほ、褒めてくれるかなって、上手く行けばおもちゃとか買ってくれるんじゃないかなって思ったけど……！"
"2001505-36-カエデ" = "それが出来たら、素敵なレディーになれるんじゃないかなって……"
"2001505-37-カエデ" = "でもその、上手く行かなかったっていうか、えっと……。"
"2001505-38-カエデ" = "その、手伝うはずではあったんだけど……。"
"2001505-39-カエデ" = "めちゃくちゃにしようと思って、来たわけでは……。"
"2001505-40" = "[s] \"えっと、カエデ。\""
"2001505-41-カエデ" = "うぅ……！"
"2001505-42-カエデ" = "うわあぁぁぁぁん！ごめんなさい！"
"2001505-43-カエデ" = "勝手に来て、色々荒らして……！"
"2001505-44-カエデ" = "めちゃくちゃにしちゃったのは本当だし……。"
"2001505-45-カエデ" = "ごめん、なさい……。"
"2001505-46-カエデ" = "先生、ただでさえ忙しいのに……。"
"2001505-47-カエデ" = "結局迷惑かけちゃって……。"
"2001505-48-カエデ" = "何の役にも立ってなくて……。"
"2001505-49-カエデ" = "うぅ……。"
"2001505-50" = "[s] \"カエデ、落ち着いて。\""
"2001505-51-カエデ" = "……？"
"2001505-52" = "[s] \"ごめん、聞き方が悪かったね。とりあえずちょっと待ってて。\""
"2001505-53-カエデ" = "？？？"
"2001505-54" = "[ns] \"はい、ココア。これ飲んで少し落ち着こっか。\""
"2001505-55-カエデ" = "わ、私は、レディーとしてブラックコーヒーを……。"
"2001505-56" = "[s] \"ココアは嫌い？\""
"2001505-57-カエデ" = "…………好き。"
"2001505-58-カエデ" = "（ゴクンッ）"
"2001505-59" = "[s] \"せっかくだし、一つ聞いてみても良い？\""
"2001505-60-カエデ" = "……うん。"
"2001505-61" = "[s] \"カエデはいつも、素敵なレディーになろうと頑張ってるよね。\""
"2001505-62-カエデ" = "…………はい。"
"2001505-63" = "[s] \"それはどうして？\""
"2001505-64-カエデ" = "……。"
"2001505-65-カエデ" = "それは……。"
"2001505-66" = "[s] \"うん。\""
"2001505-67-カエデ" = "……。"
"2001505-68-カエデ" = "昔は私、ずっといたずらっ子で……。"
"2001505-69" = "[s] \"いたずらっ子？\""
"2001505-70-カエデ" = "ずっと、田舎の方で……。"
"2001505-71-カエデ" = "山とか海とか、あちこち走り回ってたの。"
"2001505-72-カエデ" = "中学生の時まではそうやって色んな所に行ったり、いたずらしたりして、過ごしてて。"
"2001505-73-カエデ" = "ただ面白いなって思うことを、たくさんしてた。"
"2001505-74-カエデ" = "そこは百鬼夜行の中でもすっごい田舎の場所だったんだけど、"
"2001505-75-カエデ" = "高校進学で、初めてこの辺りに来て。"
"2001505-76-カエデ" = "電車にも、こっちに来てから初めて乗ったの。"
"2001505-77-カエデ" = "でも初めて見たらあれ、靴を脱いで乗る物だと思わない！？色んな人に変な目で見られたんだけど！"
"2001505-78-カエデ" = "あ。"
"2001505-79-カエデ" = "えっと、この話じゃなくて……。"
"2001505-80" = "[s] \"うん、それで？\""
"2001505-81-カエデ" = "それで、この辺に来て。"
"2001505-82-カエデ" = "すごいなって思ったの。"
"2001505-83-カエデ" = "特に、ツバキ先輩とミモリ先輩！二人はかっこよくて、綺麗で、とにかくすごくて！"
"2001505-84-カエデ" = "私もそうなりたいなって思った。"
"2001505-85-カエデ" = "今のままじゃなくて、修行部の一員としてふさわしいレディーになれるように。"
"2001505-86-カエデ" = "頑張りたいなって思ったの。"
"2001505-87-カエデ" = "すごく、すっごく頑張れば、私も先輩たちみたいに素敵なレディーになれるはずだからって。"
"2001505-88-カエデ" = "……。"
"2001505-89-カエデ" = "……でも、違った。"
"2001505-90-カエデ" = "結構頑張ったはずなのに、私は何回もこうやって……。"
"2001505-91-カエデ" = "みんなに変って言われて、問題ばっかり起こして……。"
"2001505-92-カエデ" = "……私、変わってないかも。"
"2001505-93-カエデ" = "やっぱり私みたいな子どもは、いくら頑張ったところで……"
"2001505-94-カエデ" = "先輩たちみたいには、なれないのかなって。"
"2001505-95" = "[s] \"そんなことは無いよ。\""
"2001505-96-カエデ" = "……先生？"
"2001505-97" = "[s1] \"カエデがいつも努力してるのは、\"\n[s2] \"私だって、よく知ってる。\""
"2001505-98-カエデ" = "……？"
"2001505-99-カエデ" = "……？"
"2001505-100" = "[s3] \"今日みたいに時々ミスがあるのは確かだけど。\"\n[s4] \"そういうのは誰にだってあることだよ。\""
"2001505-101-カエデ" = "…………。"
"2001505-102-カエデ" = "…………。"
"2001505-103" = "[s5] \"だから大丈夫。\"\n[s6] \"カエデはカエデのペースで、成長してるはずだから。\""
"2001505-104-カエデ" = "成長……。"
"2001505-105-カエデ" = "成長……。"
"2001505-106" = "[s] \"辛かったら先輩のところでも、私のところに来ても良いから。\""
"2001505-107-カエデ" = "……良いの？"
"2001505-108" = "[s] \"私はカエデの先生だからね。\""
"2001505-109-カエデ" = "……。"
"2001505-110-カエデ" = "……そっか。"
"2001505-111-カエデ" = "うん、分かった！"
"2001505-112-カエデ" = "そうだね、確かにそうかも！"
"2001505-113-カエデ" = "うーん、何であんなに悩んでたのか分かんなくなっちゃったかも！？"
"2001505-114-カエデ" = "ばばん、カエデ完全復活！"
"2001505-115-カエデ" = "ありがとね、先生。私、ちょっとずつでも頑張るよ！"
"2001505-116-カエデ" = "だから、見守っててね。"
"2001505-117" = "[s7] \"それはもちろん見守ってるんだけど……。\"\n[s8] \"……その前に、一緒に片づけを手伝ってくれる？\""
"2001505-118-カエデ" = "あっ、忘れてた！？"
"2001505-119-カエデ" = "あっ、忘れてた！？"
"2001505-120-カエデ" = "よーし！じゃあまずは素敵なレディーになるために、片付けから！"
"2001505-121" = "（そうしていつもより色んな話をして、カエデとシャーレの大掃除をした）"
"2001505-122" = "（次の日……）"
"2001505-123" = "[ns9] \"な、何とかギリギリ終わるかも……。\"\n[ns10] \"……カエデ、大丈夫かな。\""
"2001505-124-カエデ" = "先生！非常事態！！"
"2001505-125" = "[s] \"カエデ！？どうしたの！？\""
"2001505-126-カエデ" = "実はね、実はね……！"
"2001505-127-カエデ" = "百鬼夜行のムサビの森に、ヘラクレスオオカブトが大量発生したんだって！！"
"2001505-128" = "[s] \"……ん？\""
"2001505-129-カエデ" = "こうしてる場合じゃないよ、虫取り網と、かごと、カメラを持って……！"
"2001505-130-カエデ" = "あ、水分補給用に飲み物も持っていかないと。"
"2001505-131-カエデ" = "よし、準備OK！完璧！"
"2001505-132-カエデ" = "行こう、先生！カブトムシを捕まえに！"
"2001505-133" = "[s11] \"……よし、行こっか！\"\n[s12] \"いつものカエデで安心した。\""
"2001505-134-カエデ" = "？？？"
"2001505-135-カエデ" = "？？？"
"2001505-136" = "（相変わらず元気で明るいカエデと一緒に、虫採取に出かけたのだった）"
