[translation]
"1014703-1" = "サツキの海対策 "
"1014703-2" = "[ns] \"楽しそうなことをしてるね、サツキ。\""
"1014703-3-サツキ" = "あら、先生。"
"1014703-4-サツキ" = "ふふ、私が何をしていたか気になる？"
"1014703-5-サツキ" = "いいわ、教えてあげる。"
"1014703-6-サツキ" = "私は今――"
"1014703-7-サツキ" = "海を克服するトレーニングをしていたのよ！"
"1014703-8" = "[s] \"海を克服するトレーニング？\""
"1014703-9-サツキ" = "1つ、海の秘密を教えてあげる。"
"1014703-10-サツキ" = "見て頂戴。"
"1014703-11-サツキ" = "波がきているでしょう？"
"1014703-12-サツキ" = "さっき海辺を観察していて気づいたのよ。"
"1014703-13-サツキ" = "波を観察すれば、規模をある程度予測できる、って。"
"1014703-14-サツキ" = "例えば……遠くで大きく崩れている波は、#nこちらに届く前に勢いがなくなってしまうけど……。"
"1014703-15-サツキ" = "静かな波は違うの。"
"1014703-16-サツキ" = "……あっ！ちょうど来るわ、見ていて頂戴。"
"1014703-17-サツキ" = "えいっ！"
"1014703-18-サツキ" = "ふふっ、どうかしら？"
"1014703-19-サツキ" = "打ち寄せる波を、華麗に避ける私は。"
"1014703-20-サツキ" = "この見分け方、結構当たるのよ。危険な海で生存率を上げるのに役立つはずだわ。"
"1014703-21-サツキ" = "先生もやってみない？"
"1014703-22" = "[s1] \"確かに面白そうだけど――\"\n[s2] \"もう少し海の中に入ってもいいんじゃない？\""
"1014703-23-サツキ" = "海の中に……？"
"1014703-24-サツキ" = "い、嫌よ。そんなの危ないじゃない。"
"1014703-25" = "[s3] \"この辺りは浅いから大丈夫だよ。\"\n[s4] \"せっかく海に来たんだし。\""
"1014703-26-サツキ" = "……その油断が命取りになっても知らないわよ。"
"1014703-27-サツキ" = "海はと～っても危なくて恐ろしい場所なんだから！"
"1014703-28-サツキ" = "……。"
"1014703-29-サツキ" = "そんなキラキラした目で見てもダメなものはダメ！"
"1014703-30-サツキ" = "でも……先生は万魔殿の協力者だし……。"
"1014703-31-サツキ" = "先生と海に入るのも、ちょっと楽しいかもしれないし……。"
"1014703-32-サツキ" = "……う～ん。"
"1014703-33-サツキ" = "はぁ……完敗よ。今回だけ、先生の提案に乗ってあげるわ。"
"1014703-34" = "[s] \"やった～！\""
"1014703-35-サツキ" = "うぅ……波が……。"
"1014703-36-サツキ" = "……いいわ。誘ってきた先生に責任を取ってもらうから。"
"1014703-37-サツキ" = "どんな緊急事態でも私を守るよう、催眠をかけておかないと。"
"1014703-38-サツキ" = "そーれそれ……ぐ～るぐる……ぐ～るぐる……。"
"1014703-39-サツキ" = "先生は私を守る、先生は私を守る……。"
"1014703-40" = "[ns5] \"ちょ、ちょっと待ってサツキ……！\"\n[ns6] \"あの波、なんだか大きくない……？\""
"1014703-41-サツキ" = "きゃあああっ！！"
"1014703-42-サツキ" = "あ、危なかったわ……ありがとう、先生。"
"1014703-43-サツキ" = "あら？そういえば……なんで先生は守ってくれたのかしら。#nまだ催眠は不完全だったのに……。"
"1014703-44-サツキ" = "まさか……。"
"1014703-45-サツキ" = "私の能力がレベルアップしたのかしら！？#n言葉だけで催眠をかけられるように！？"
"1014703-46" = "[s] \"……催眠なんてなくても、サツキのことは守るよ。\""
"1014703-47-サツキ" = "え？催眠にかかったわけじゃないの？ならどうして……。"
"1014703-48-サツキ" = "……。"
"1014703-49-サツキ" = "わ、分かったわ。万魔殿の協力者としてってことね？"
"1014703-50" = "[s7] \"違うよ。サツキ、痛いの嫌いでしょ。\"\n[s8] \"怖いのも。\""
"1014703-51-サツキ" = "……。"
"1014703-52-サツキ" = "そうね。#n先生は、この[ruby=きょうごく]京極[/ruby]サツキの秘密を知る数少ない人物……。"
"1014703-53-サツキ" = "いつか……この秘密を種に脅すつもりかしら？"
"1014703-54-サツキ" = "……いえ、答えは分かりきっているわね。先生がそんなことするはずない。"
"1014703-55" = "[s] \"うん、絶対しない。\""
"1014703-56-サツキ" = "……ええ、知っているわ。"
"1014703-57-サツキ" = "ねぇ先生、これからも……私を守ってくれる？"
"1014703-58" = "[s] 頷く。"
"1014703-59-サツキ" = "……いいわ。"
"1014703-60-サツキ" = "っ！また大きな波が……！"
"1014703-61-サツキ" = "頼んだわ、先生！"
"1014703-62" = "（サツキが浅瀬を怖がらなくなるまで、一緒に過ごした）"
