[translation]
"1007803-1" = "私は爆破作業が好きだ"
"1007803-2" = "（夕方、カスミの呼び出しを受けて、放置された工事現場に向かった）"
"1007803-3" = "[ns1] \"人の出入りは無さそうで安心したけど……\"\n[ns2] \"今度はここで騒ぎを……？\""
"1007803-4-カスミ" = "お～、さすがだな、先生！時間ピッタリだ！"
"1007803-5-カスミ" = "今月の第89秘密アジトにようこそ来てくれた！"
"1007803-6-カスミ" = "うん？数字が増えてないかって？"
"1007803-7-カスミ" = "ハーハッハッハ！当然だ！前のアジトは放棄することになったからな！"
"1007803-8-カスミ" = "まあ、重要なのは数字ではない。"
"1007803-9-カスミ" = "来てくれたところ悪いが、移動しよう。あまり長居もしていられないのだ。"
"1007803-10-カスミ" = "早く付いてきてくれ、先生！#n私の素晴らしい計画を聞いてもらわなくては！！"
"1007803-11-カスミ" = "うむ、この辺なら見つからないだろう。"
"1007803-12-カスミ" = "毎度毎度、狭苦しい場所に呼び出して悪いが……身を隠さなくてはならなくてな。"
"1007803-13-カスミ" = "こう見えても私は結構な人気者でね、あちこちからお客さんが来るのだ。"
"1007803-14-カスミ" = "風紀委員会とか武装企業とか……爆破作業中に水道管を破裂させて巻き込んだスケバンとか、ヘルメット団とか……"
"1007803-15-カスミ" = "ハッハッハ。みんな最初は不満げな顔をしているが、いざ温泉が湧き出たら喜んでいるというのにな！"
"1007803-16-カスミ" = "……先生？どうした、そんな顔して。"
"1007803-17-カスミ" = "……？"
"1007803-18-カスミ" = "なぜ毎回そんな風に追われてまで続けてるのかって？"
"1007803-19-カスミ" = "失敗したときに挫折したり悔しく思わないのかって？"
"1007803-20-カスミ" = "……ハハッ。"
"1007803-21-カスミ" = "先生よ、もしかしたら認識が少し異なっているのかもしれないな。"
"1007803-22-カスミ" = "どうやら先生は、私が「温泉開発を成功させること」が好きだと思っているようだが……"
"1007803-23-カスミ" = "もちろん、常に成功を目指している事には違いないが……#n「成功しなければ意味がない」とは思っていないぞ。"
"1007803-24-カスミ" = "……先生。"
"1007803-25-カスミ" = "私は爆破が好きなんだ。この言葉の意味を――理解してくれるか？"
"1007803-26-カスミ" = "そこには……「失敗」も含まれているという事だよ。"
"1007803-27-カスミ" = "大規模なもの、小規模なもの……成功、失敗したもの。"
"1007803-28-カスミ" = "追われる身になる原因、妨害工作に阻まれるもの、あるいは障害を突き破ってようやく成功したもの……！"
"1007803-29-カスミ" = "誰も想像できない場所で爆破を行い、新たな景色を生み出すのが好きだ。"
"1007803-30-カスミ" = "せっかく緻密に計算して準備した爆薬が、風紀委員会の妨害で処理されてしまうときもある。そんな悲しみさえも、私は愛している！"
"1007803-31-カスミ" = "温泉が湧き上がりそうな場所ならどこでも構わん！#nいや、「ここで温泉が湧き上がったら綺麗だろうな」という願望さえあれば良い！"
"1007803-32-カスミ" = "大事なのは結果じゃない。温泉を作り上げるまでの全て！#nその過程にこそ「温泉開発」の素晴らしさが詰まっている！"
"1007803-33-カスミ" = "掘れるのか？いや、掘りたい！掘ってみせる！#n――この気持ちが、分かるか？"
"1007803-34-カスミ" = "そして、私の目には……"
"1007803-35-カスミ" = "……「シャーレ」の建物も、しっかりと映っている。"
"1007803-36" = "[ns3] \"……待って、今なんて言った！？\"\n[ns4] \"……えっ！？\""
"1007803-37-カスミ" = "ハーハッハッハッハ！！驚いたようだな。"
"1007803-38-カスミ" = "……やっと理解できたか、先生？"
"1007803-39-カスミ" = "私は――これらの行動に関与してもらいたいのだ。"
"1007803-40-カスミ" = "これは、脅迫だと思ってもらって構わない。#n警戒されるのは慣れているからな。"
"1007803-41-カスミ" = "問題児だと分かって、見る目が変わったか？私のことが嫌いになったか？#nだが、重要なのは相手がどう思うかではなく――私がどう感じるか、だと考えている。"
"1007803-42-カスミ" = "いつ切り出そうか、以前から悩んでいたのだ。"
"1007803-43-カスミ" = "だから……真剣に考えてほしい。"
"1007803-44-カスミ" = "……事の重大さが伝わったかな、先生？"
"1007803-45-カスミ" = "私のために、そして先生のために。"
"1007803-46-カスミ" = "これから一緒に、次の温泉ポイントを議論してほしい。"
"1007803-47-カスミ" = "今日のために、そして明日からのために。"
"1007803-48-カスミ" = "……どんなに時間がかかろうとも、付き合ってもらうぞ、先生。"
"1007803-49" = "[s] \"…………。\""
"1007803-50" = "[ns5] \"……分かった、その提案を受けるよ。\"\n[ns6] \"やるからには、とことんやろう。\""
"1007803-51-カスミ" = "ハーハッハッハッハッハッハ―！！！#nよし、よし！そう来なくてはな！！"
"1007803-52-カスミ" = "では、真剣に探してみるとしよう！"
"1007803-53-カスミ" = "私も、先生も……そしてみんなが幸せになれる！"
"1007803-54-カスミ" = "幻の温泉ポイントを！！"
"1007803-55" = "（その後、地図上で次の温泉ポイントをカスミと遅くまで議論した）"
"1007803-56" = "（どうにか「安全な場所」に誘導しようと、陽が昇るまで意見を交わし……）"
"1007803-57" = "（……ようやく納得できる場所を見つけたカスミは、地図の上で満足気な寝顔を見せた）"
