[translation]
"2002102-1" = "良い子？悪い子？"
"2002102-2-ハナエ" = "先生、お待たせしました！"
"2002102-3" = "[s] \"いらっしゃい、ハナエ。珍しい恰好だね。\""
"2002102-4-ハナエ" = "はい、サンタさんの服装です！"
"2002102-5-ハナエ" = "そしてこの衣装になっているからには……"
"2002102-6-ハナエ" = "私は、サンタさんとしての義務を果たさなければなりません！"
"2002102-7" = "[s1] \"そ、そうなの……？\"\n[s2] \"は、ハナエがそう言うなら……。\""
"2002102-8-ハナエ" = "そして、モモトークでお伝えした「悩み」の件については……"
"2002102-9-ハナエ" = "そして、モモトークでお伝えした「悩み」の件については……"
"2002102-10-ハナエ" = "実は、この服と密接な関係があるんです。"
"2002102-11" = "[s3] \"何と。\"\n[s4] \"気になってきた。\""
"2002102-12-ハナエ" = "それでは発表の前に、深呼吸をして……"
"2002102-13-ハナエ" = "それでは発表の前に、深呼吸をして……"
"2002102-14-ハナエ" = "私は……「真のサンタ」さんとしては、力不足なのではないでしょうか！？"
"2002102-15" = "[s] \"真の、サンタさん……？\""
"2002102-16-ハナエ" = "真のサンタさんはまず、良い子と悪い子を厳しく見定めなければいけません！"
"2002102-17-ハナエ" = "プレゼントに関わる、大事なことです。"
"2002102-18-ハナエ" = "そして、自分の体重より重いものも軽々持てなくてはなりません。"
"2002102-19-ハナエ" = "なにせサンタさんは、プレゼントの袋を持って屋根の上に登らないとですから。"
"2002102-20-ハナエ" = "そして何より……"
"2002102-21-ハナエ" = "マッハ2で飛べないといけません！"
"2002102-22-ハナエ" = "そうなって初めて、キヴォトス全域にプレゼントを配れるので！"
"2002102-23" = "（それは何かを勘違いしているのではと言いかけたが）"
"2002102-24" = "（ハナエの無邪気な笑顔を前に、つい言葉に詰まってしまった)"
"2002102-25-ハナエ" = "……？"
"2002102-26-ハナエ" = "本物じゃないなら、そこまでやらなくても大丈夫なんじゃ……って？"
"2002102-27-ハナエ" = "先生！そんな考え方はめっ、です！"
"2002102-28-ハナエ" = "本当かどうかではなく、この格好をしているからには#n真剣に取り組む必要があります！"
"2002102-29-ハナエ" = "子どもたちの夢と希望を、守るために！"
"2002102-30" = "[s5] \"な、なるほど……！\"\n[s6] \"それはそうかもしれない……！\""
"2002102-31-ハナエ" = "分かってくれましたか！"
"2002102-32-ハナエ" = "分かってくれましたか！"
"2002102-33-ハナエ" = "つまり、そういう事情なのですが……#nどうしたら良いと思いますか、先生？"
"2002102-34" = "[s] \"うーん……ハナエとしては、まず何がしたい？\""
"2002102-35-ハナエ" = "私はまずマッハ2で――"
"2002102-36" = "[s7] \"それはちょっと……。\"\n[s8] \"別のから始めよう！\""
"2002102-37-ハナエ" = "そうなんですか？試してみたかったのですが……"
"2002102-38-ハナエ" = "そうなんですか？試してみたかったのですが……"
"2002102-39-ハナエ" = "では、一旦プレゼントはゆっくり配っても良いとして……。"
"2002102-40-ハナエ" = "良い子と悪い子を、見抜けるようにするのはアリかもしれません。"
"2002102-41-ハナエ" = "どうしたら良いと思いますか？"
"2002102-42" = "[s9] \"じゃあ、試しに私の話を聞いてもらって。\"\n[s10] \"それを嘘かどうか見抜いてもらうっていうのは？\""
"2002102-43-ハナエ" = "なるほど、嘘かどうかを判定するんですね！"
"2002102-44-ハナエ" = "なるほど、嘘かどうかを判定するんですね！"
"2002102-45-ハナエ" = "良いと思います、時に悪意無く嘘をついちゃう子もいますし！"
"2002102-46-ハナエ" = "ドキドキしてきました……では、いつでもどうぞ！"
"2002102-47" = "[s] \"実は私、毎年この時期になると袋を持って……\""
"2002102-48" = "[ns] \"マッハ2で飛び回りながら、プレゼントを配ってるんだ。\""
"2002102-49-ハナエ" = "そうだったんですか！？#n先生、まるでサンタさんみたいですね！"
"2002102-50-ハナエ" = "え、嘘なんですか？#nでも、先生は何でもできますし……。"
"2002102-51-ハナエ" = "え、そんなことないんですか？できないこともある？"
"2002102-52-ハナエ" = "そ、そうだったんですね……。"
"2002102-53" = "[s] \"ぐはっ、突然腹痛と頭痛が！！\""
"2002102-54-ハナエ" = "大変です、すぐに手当てを！#n早く横になってください！"
"2002102-55-ハナエ" = "えっと、こういう時は前に本で読んだ通り……#nまず空気を燃やして、邪気を無くして。"
"2002102-56-ハナエ" = "鞭を打ちながらそれに耐えれば治ります！"
"2002102-57" = "[s] \"本当に治るかなあ！？\""
"2002102-58" = "（その後も、色々と嘘をついてみたものの）"
"2002102-59" = "（ハナエは人の話をしっかり信じてくれる、とても良い子であることがあらためて分かった……）"
