[translation]
"1006602-1" = "メイド大ピンチ！"
"1006602-2" = "（ゲーム開発部の部室に駆けつけた）"
"1006602-3" = "ゲーム開発部・部室"
"1006602-4" = "[ns] \"アリス、大丈夫！？\""
"1006602-5-アリス" = "勇者よ、本当に来てしまったのですね……。"
"1006602-6" = "[s1] \"もちろん、心配だからね。\"\n[s2] \"でも、一体どこにいるの……？\""
"1006602-7-アリス" = "勇者よ、すぐに元いたところへ戻るがよい……#n今のアリスはそなたの前に姿を現すことが許されないのだ……。"
"1006602-8" = "[s] \"本当に、どうしたの？\""
"1006602-9-アリス" = "……。"
"1006602-10" = "[s3] \"何かあったのなら、聞かせてほしい。\"\n[s4] \"アリスの力になりたいから。\""
"1006602-11-アリス" = "…………ずるいです、先生。#nそんなことを言われたら、アリスは従うほかありません。"
"1006602-12" = "[s] \"え……？メイド服……？\""
"1006602-13-アリス" = "うう……そんな顔で見ないでください……。"
"1006602-14-アリス" = "アリスも、メイド服はまだ少し無理なんです……。"
"1006602-15-アリス" = "だから着るつもりもなかったのに、先生が来ると言うから――！"
"1006602-16-アリス" = "先生！こうなった責任を取ってください！"
"1006602-17-アリス" = "まずはアリスの頭をナデナデするのです！"
"1006602-18" = "（アリスのあたまをなでなでした）"
"1006602-19" = "（アリスはすこしおちついた！）"
"1006602-20" = "[ns] \"改めて……何があったの？\""
"1006602-21-アリス" = "実は……。"
"1006602-22" = "[ns5] \"つまり、着るものが……。\"\n[ns6] \"メイド服しかなかったってこと？\""
"1006602-23-アリス" = "はい、他の服はすべて洗濯中なのです……。"
"1006602-24-アリス" = "ですが、アリスはまだメイド服に抵抗があるのです……。"
"1006602-25-アリス" = "これを見ていると様々なことを思い出しますから。#n激しい戦い、倒れゆく仲間たち、向かってくるネル先輩――"
"1006602-26-アリス" = "心に残ったシーン、感動的なカット、#n夕焼けに浮かぶクジラ雲、そしてCMが流れていき……。"
"1006602-27" = "[s7] \"確かに色々あったね……。\"\n[s8] \"なんか他のも混ざってる気が……。\""
"1006602-28-アリス" = "とにかくあの時のことがあるからか、メイド服を着ると#nアリスは思うように身体を動かせなくなってしまうのです。"
"1006602-29-アリス" = "装備すると全ステータスに[ruby=弱くなる]デバフがかかる[/ruby]#n呪いのアイテムみたいに……。"
"1006602-30-アリス" = "今はネル先輩も怖い人じゃないって分かってますし、#n先輩が着ているものなら好きになりたいのですが……#nどうしたらいいか、分からなくて……ぐすん。"
"1006602-31" = "[s] \"それなら、アリス！\""
"1006602-32-アリス" = "……？"
"1006602-33" = "[s] \"メイドにジョブチェンジしよう！\""
"1006602-34-アリス" = "ジョブチェンジ、ですか？"
"1006602-35-アリス" = "突然どうして……？"
"1006602-36" = "[s9] \"メイドにジョブチェンジして経験値を稼げば、\"\n[s10] \"専用スキルを覚えてデバフを打ち消せるはず！\""
"1006602-37-アリス" = "そうすればメイドを克服できる……ほ、本当でしょうか……？"
"1006602-38-アリス" = "……ですが、先生が言うなら信じたいです！"
"1006602-39-アリス" = "でも、何から始めればいいんでしょう？"
"1006602-40" = "[s] \"メイドがやりそうなことをしてみるとか？\""
"1006602-41-アリス" = "メイドがやりそうなこと……？"
"1006602-42-アリス" = "そうですね……メイドといえば……#nよくお掃除をしています。"
"1006602-43-アリス" = "他には、戦闘や破壊……潜入なども……"
"1006602-44-アリス" = "……え？それは気にしなくていい、ですか？"
"1006602-45-アリス" = "ではアリス、お掃除から始めてみます！"
"1006602-46-アリス" = "うわーん！片付けるものが多すぎます！"
"1006602-47-アリス" = "転がるペットボトル、散乱したお菓子の袋、ホコリまみれの床……。"
"1006602-48-アリス" = "本当に……綺麗になるのでしょうか……？"
"1006602-49" = "[s] \"少しずつやっていこう……。\""
"1006602-50-アリス" = "はい……アリス、頑張ります……。"
"1006602-51-アリス" = "先生、ゴミ袋を用意してください。#n一枚……いえ、三枚くらい欲しいです。"
"1006602-52-アリス" = "ああっ、お菓子のくずがこぼれてしまいました！#n掃除機も必要です！"
"1006602-53-アリス" = "くしゅんっ！少しはたいただけでホコリまみれです……。#nええと、まずはバケツで水を……。"
"1006602-54-アリス" = "え？……それより乾拭きした方がいい？"
"1006602-55-アリス" = "なるほど……。"
"1006602-56" = "（アリスと懸命に部室を掃除して……）"
"1006602-57-アリス" = "……。"
"1006602-58-アリス" = "先生、部室が綺麗になりました！お掃除クエスト完了です！"
"1006602-59" = "[ns] \"そしてアリスも、普通に動けるようになったね。\""
"1006602-60-アリス" = "え……？"
"1006602-61-アリス" = "ほ、本当です！アリス、もう手も足も震えてません！絶好調です！"
"1006602-62-アリス" = "これはクエスト完了でレベルアップし、#n専用スキルを手に入れたからですね！？"
"1006602-63" = "[s] \"きっとそうだよ、良かったね。\""
"1006602-64-アリス" = "先生のおかげです！アリスもメイド服を#n着たまま動けるようになりました！"
"1006602-65-アリス" = "やっぱり先生はすごいです！"
"1006602-66" = "（その後、ご機嫌なアリスと一緒にゲームを楽しんだ）"
