[translation]
"1012905-1" = "閃光弾不発事"
"1012905-2-スズミ" = "先生、こちらです。"
"1012905-3" = "[s] \"スズミ！もう来てたんだ！\""
"1012905-4" = "[ns] \"かわいい！\""
"1012905-5-スズミ" = "か、からかわないでください！"
"1012905-6-スズミ" = "「現場に合わせた服装」とおっしゃっていたので……。"
"1012905-7" = "[s1] \"Tシャツとかがいいかな？って思ったんだけど。\"\n[s2] \"むしろ、その格好がベストだね。\""
"1012905-8-スズミ" = "う、うぅぅうう……！"
"1012905-9-マニアA" = "あ、あのすみません……。#n「魔法少女ヘヴィキャリバー」の「テルミットホワイト」……ですよね？"
"1012905-10-スズミ" = "あっ、はい！そう、ですが……。"
"1012905-11-マニアA" = "わ、私っ、ホワイト推しなんです！#n写真……一緒に撮らせてもらっても良いですか！？"
"1012905-12-スズミ" = "しゃ、写真？"
"1012905-13" = "[s] \"自然にして、スズミ……！\""
"1012905-14-スズミ" = "ええと、こう、ですか……？"
"1012905-15-マニアB" = "すみません、私もいいですか……！？"
"1012905-16-マニアC" = "こっちもお願いしまーす！"
"1012905-17-マニアJ" = "ありがとうございます！家宝にしますね！！"
"1012905-18-スズミ" = "このキャラクター、大人気ですね……。"
"1012905-19" = "[s] \"スズミが可愛いからだよ。\""
"1012905-20-スズミ" = "……パトロールに集中します。"
"1012905-21-スズミ" = "（先生はまた……平気でそんなことを……）"
"1012905-22-スケバンA" = "おいおい、イケてるカメラじゃねぇか。こっちによこせよ。"
"1012905-23-スケバンB" = "借りるだけだよ。#nあとでちゃ～んと郵送してやるからさ。"
"1012905-24-マニアF" = "そんなご[ruby=むたい]無体[/ruby]な！！#nこ、これは拙者の命よりも大事な[ruby=カメラ]神器[/ruby]で……！"
"1012905-25-スケバンA" = "いいから貸せって！"
"1012905-26-スズミ" = "イベントを荒らしている不良とは……あの方々のことですね。"
"1012905-27-スズミ" = "先生はこちらでお待ちを。"
"1012905-28-スズミ" = "そこまでです！"
"1012905-29-スケバンA" = "ああん？コスプレイヤーか？"
"1012905-30-スケバンB" = "撮ってほしいってか？#nいまこいつからカメラ奪うとこだから、待ってな！"
"1012905-31-マニアF" = "なっ……！いま！奪うと言ったでござるか！？"
"1012905-32-スケバンB" = "借りるも奪うも似たようなもんだろうが！"
"1012905-33-スズミ" = "二人、ですか。"
"1012905-34-スズミ" = "二人がかりで来ていただいたほうが都合が良いですね。#n手早く済みますので。"
"1012905-35-スケバンA" = "あぁん？……閃光弾でも食らっとけ！"
"1012905-36-スケバンA" = "く、くぅっ！て、手がっ……！#nこいつ、なんて握力してやがる！"
"1012905-37-スケバンA" = "は、放せって！閃光弾が手の中で爆発する……っ！"
"1012905-38-スズミ" = "お手伝いしましょう。"
"1012905-39-スケバンA" = "い、いたたたたたっ！！！"
"1012905-40-スケバンA" = "うわああ！！手が！！"
"1012905-41-スケバンB" = "く、くそっ、覚えてろよ……！"
"1012905-42-スズミ" = "閃光弾は神聖なものです。#nみだりにピンを抜いてはいけません。"
"1012905-43-マニアA" = "いま……閃光弾を素手で潰してたよね……？"
"1012905-44-マニアB" = "うん……爆発する前に、グシャ！って……。"
"1012905-45-マニアA" = "小道具かな……？実はなんかのショーだったとかさ。"
"1012905-46-スズミ" = "目標は達成しました。先生、帰りましょう。"
"1012905-47" = "[s3] \"あ……。\"\n[s4] \"は、はい……。\""
"1012905-48" = "（スズミとイベント会場を後にした）"
"1012905-49" = "（何故かみんなが道をあけてくれて、スムーズに移動できた……）"
