[translation]
"10034130-1" = "5日前：グッパージャス？"
"10034130-2-ヨシミ" = "んー……ちゃんと弾けてるつもりなんだけど。"
"10034130-3-ヨシミ" = "もしかしたら私、持ち方が変だったり……？"
"10034130-4-カズサ" = "なら二人組を作って、お互いの姿勢をチェックしてみるのはどう？"
"10034130-5-カズサ" = "自分で鏡を見ながら演奏するのも難しいし。"
"10034130-6-ヨシミ" = "偶には良いこと言うじゃない。それじゃ、グッパージャスでいいわね？"
"10034130-7-カズサ" = "……？"
"10034130-8-アイリ" = "グッパー……？"
"10034130-9-ナツ" = "ジャス……？"
"10034130-10-ヨシミ" = "……え。"
"10034130-11-カズサ" = "……ぷっ。"
"10034130-12-カズサ" = "……くっ、くくっ……くふふふふっ……！"
"10034130-13-アイリ" = "……そこまでカズサのツボに入ったとは。"
"10034130-14-アイリ" = "か、カズサちゃん……。"
"10034130-15-ヨシミ" = "ぐっ……！何よ、うちではこうだったの！悪い！？"
"10034130-16-カズサ" = "ふふっ……ふっふふっ……あー、めっちゃ笑った……はぁ、ごめんごめん。"
"10034130-17-カズサ" = "でも普通、「ぐっとっぱーで分かれましょ」じゃない？"
"10034130-18-ヨシミ" = "いや地域差でしょ、普通とか知らないわよ！！"
"10034130-19-アイリ" = "わ、私は可愛いと思うよ！ヨシミちゃんのも！"
"10034130-20-ナツ" = "じゃあ、そろそろ始めよっか……「ヨシミ流」で。"
"10034130-21-ヨシミ" = "あああもうっ！！"
"10034130-22-カズサ" = "それじゃ、いくよ。ぐっとっぱー……じゃなくて何だっけ？"
"10034130-23-ヨシミ" = "もうそれで良いってば！！！"
"10034130-24-一同" = "ぐっとっぱーで分かれましょ！！"
