[translation]
"10034080-1" = "エピローグ;物足りなくない"
"10034080-2" = "[log=???]\"本当にそのままで良いの？\"[/log]"
"10034080-3-アイリ" = "……。"
"10034080-4-アイリ" = "あっ、ごめん。#n私から聞いたのに、ぼーっとしちゃってた……。"
"10034080-5-クラスメイトA" = "だから、「お化け屋敷カフェ」だけで良いのかなって。"
"10034080-6-クラスメイトA" = "あ、アイリのアイデアが悪いとかじゃないよ！"
"10034080-7-クラスメイトB" = "けど学園祭の出し物でカフェを開くなら、もう一工夫欲しくない？"
"10034080-8-クラスメイトA" = "もっとユニークで面白そうなこと……#nあっ、アイリが背負ってるそれは？"
"10034080-9-アイリ" = "……これ？キーボード？"
"10034080-10-クラスメイトA" = "それだよ、アイリ！"
"10034080-11-クラスメイトB" = "お化け屋敷のバンドカフェとかどう？今までに無さそうで良くない？"
"10034080-12-アイリ" = "お化け屋敷のバンドカフェ……。"
"10034080-13-アイリ" = "う～ん……。"
"10034080-14-アイリ" = "……。"
"10034080-15-アイリ" = "……ふふっ。"
"10034080-16-アイリ" = "……アイリ？"
"10034080-17-アイリ" = "どうかした……？"
"10034080-18-アイリ" = "あははっ……ううん。"
"10034080-19-アイリ" = "やっぱり、今のままで行こうかな！"
"10034080-20-クラスメイトA" = "うん、まあアイリがそう言うなら！"
"10034080-21-クラスメイトB" = "何だか、いつの間にスッキリした顔してるね。"
"10034080-22-クラスメイトA" = "じゃあ頑張ってね！#nアイリたちのところにも顔出すから！"
"10034080-23-クラスメイトB" = "そうそう、友達にも声かけとくから。楽しみにしてるよ。"
"10034080-24-アイリ" = "……うん、期待してて！"
"10034080-25-アイリ" = "あ、次もう降りないと。"
"10034080-26-アイリ" = "じゃあ、またね！"
"10034080-27-クラスメイトA" = "ばいばーい。"
"10034080-28-クラスメイトA" = "また明日ー！"
"10034080-29-アイリ" = "うんっ！！"
"10034080-30-アイリ" = "……ふぅ。"
"10034080-31-アイリ" = "あれ、なんかこの状況……前にもあったような。"
"10034080-32-？？？" = "アイリ！こっち、こっち！！"
"10034080-33-アイリ" = "……？"
"10034080-34-ヨシミ" = "何ボーッとしてるの？ほら、本番前に一回合わせるわよ！"
"10034080-35-カズサ" = "そんな急かさなくてもいいでしょ。"
"10034080-36-ヨシミ" = "はぁ？"
"10034080-37-ヨシミ" = "もし間に合わなくなったらどうするの！？#nセムラ食べられなくなるわよ！？"
"10034080-38-ナツ" = "過酷な練習の毎日も、もう一週間になる。#nみんな、覚悟して臨もう。血を吐くほどのロックを……。"
"10034080-39-カズサ" = "いやいや、血を吐いたら演奏どころじゃないけど……。"
"10034080-40-カズサ" = "けどまあとにかく、練習の成果を見せる時だね。"
"10034080-41-カズサ" = "……行こう、アイリ。"
"10034080-42-アイリ" = "……。"
"10034080-43-カズサ" = "アイリ？"
"10034080-44-ヨシミ" = "ほら、もう時間無いわよ！"
"10034080-45-ナツ" = "我々にとっては小さな一歩だが、#nキヴォトスのバンド界を大きく揺るがす一日になるだろう！"
"10034080-46-アイリ" = "…………。"
"10034080-47" = "\"本当にそのままで良いの？\""
"10034080-48" = "\"……もう大丈夫。\""
"10034080-49" = "-ive aLIVE!"
