[translation]
"11034050-1" = "#K-04"
"11034050-2-カズサ" = "……今の、良い感じだったかも。"
"11034050-3-カズサ" = "本番もこれくらい上手く歌えれば……。"
"11034050-4-カズサ" = "まぁ、流石に緊張しちゃうだろうけど……。"
"11034050-5-カズサ" = "見よ、私のスティック捌き～！"
"11034050-6-カズサ" = "な、ナツちゃん！？"
"11034050-7-カズサ" = "あんた、セムラ食べる気あんの？"
"11034050-8-カズサ" = "……ふふっ。"
"11034050-9-カズサ" = "……ここまで緊張感が無いのは、どうかと思うけど。"
