[translation]
"11034020-1" = "#N-02"
"11034020-2-ナツ" = "こうやって、大きな目標に向かって―……っていうのも、何だか久しぶり。"
"11034020-3-ナツ" = "……やはり全ては、きっかけがあってこそ。"
"11034020-4-ナツ" = "これからは私が、ありとあらゆるきっかけを作っていかないと……。"
"11034020-5-ヨシミ" = "ちょっと、誰かナツのこと止めて。"
"11034020-6-ヨシミ" = "あんたが止めなさいよ。"
"11034020-7-アイリ" = "あはは……。"
