[translation]
"11034040-1" = "#A-03"
"11034040-2-アイリ" = "そういえばあのお菓子、そろそろ無くなっちゃいそうだったような……。"
"11034040-3-アイリ" = "もしかして、ついにみんなもチョコミントが好きに！？#nこのまま行けば、きっと……！！"
"11034040-4-ヨシミ" = "あんなに買ってきて、全部自分で食べきるとか……。#nほんとアイリ、チョコミントが好きなのね……。"
