[translation]
"11134010-1" = "#K-01"
"11134010-2-カズサ" = "まさか、人前で歌う日が来るなんてねぇ……。"
"11134010-3-ナツ" = "へぇ、意外ね。あんたバンドとか似合うのに。"
"11134010-4-カズサ" = "え、そんなイメージ付いてんの……？"
"11134010-5-ヨシミ" = "他にも色々イメージはあるけどねぇ。"
"11134010-6-カズサ" = "……それは言わなくて良いから。"
