[translation]
"11134030-1" = "センス;付け焼刃の勉強作戦（１）"
"11134030-2-ヨシミ" = "アイリが言ってた通り、効果あるっぽいわね。"
"11134030-3-アイリ" = "効果って……。"
"11134030-4-アイリ" = "教本で勉強したこと？"
"11134030-5-カズサ" = "……たしかに、私も実感してる。"
"11134030-6-カズサ" = "文武両道とは結果ではなく手段、即ち両輪であると。"
"11134030-7-カズサ" = "それはそれとして、どうして急にその話を？"
"11134030-8-ヨシミ" = "いや、何ていうか……。"
"11134030-9-ヨシミ" = "せっかくだし、ちゃんとマスターした方が良いのかなって。"
"11134030-10-ナツ" = "なるほど、教本を一周終えてしまうと。"
"11134030-11-カズサ" = "まぁ、悪くないんじゃない？"
"11134030-12-カズサ" = "途中で飽きないなら、の話だけど。"
"11134030-13-ヨシミ" = "何、自分がそうなるのが怖いの？"
"11134030-14-カズサ" = "あんたの話だっての！"
"11134030-15-ヨシミ" = "ま、何とかなるでしょ。実感はできてるし。"
"11134030-16-カズサ" = "うわ、何か先に進んでます感が出ててムカつく。"
"11134030-17-アイリ" = "ま、まぁまぁ……。"
"11134030-18-アイリ" = "それならとりあえず、譜面と教本持ってくるね。"
"11134030-19-ナツ" = "さーて、なら気合入れて始めよっか。名付けて……"
"11134030-20-ナツ" = "……「一夜漬け作戦」！！"
