[translation]
"2005206-1" = "経営の心理学"
"2005206-2-ヤクモ" = "先生は売上のためなら、なんでもできますか～？"
"2005206-3" = "[s1] \"また怖いことを言うね……。\"\n[s2] \"何かあったの？\""
"2005206-4-ヤクモ" = "実は最近、ちょ～っと厳しくてですねぇ……。"
"2005206-5-ヤクモ" = "まあ出版業界の悩みなんて、今に始まったことではないのですが。"
"2005206-6-ヤクモ" = "ご存じですか？先生。"
"2005206-7-ヤクモ" = "「経営者はいつの時も危機だと主張できる」という話。"
"2005206-8-ヤクモ" = "売上が伸びれば、それでも未来は不確定だから危機、と言い張ることができ――"
"2005206-9-ヤクモ" = "売上が落ちたら、それはただの危機で。"
"2005206-10-ヤクモ" = "過去最高の売上を叩き出した後は、必ず相対的な低下が来るものだから、"
"2005206-11-ヤクモ" = "売上比率の下落を大危機と言える根拠になるんですよねぇ。"
"2005206-12-ヤクモ" = "まったく……経営者って人種は信用ならないですねぇ、ムフフ。"
"2005206-13" = "[s] \"じゃあ、ヤクモも信用できないね～\""
"2005206-14-ヤクモ" = "えっ。"
"2005206-15-ヤクモ" = "……そ、そう、なるんですか……？"
"2005206-16-ヤクモ" = "い、今のは冗談ですよぉ冗談。へへ、へ……。"
"2005206-17-ヤクモ" = "と、とにかく。"
"2005206-18-ヤクモ" = "オフラインの書籍はもはやお土産扱いですし、"
"2005206-19-ヤクモ" = "オンライン書籍は……予測不能の混沌の中。"
"2005206-20-ヤクモ" = "むむ……なにか事態を一転できる妙案、転がってないんですかねぇ。"
"2005206-21-ヤクモ" = "あったとしても、その場しのぎにしかならないでしょうけど。"
"2005206-22-ヤクモ" = "でも、その場しのぎも積み重ねていけば、解決策になったりしますから。"
"2005206-23" = "[s] \"まずはみんなに、本を読んでもらわないと。\""
"2005206-24-ヤクモ" = "まさにそれが、我が出版部の基本方針なんです。"
"2005206-25-ヤクモ" = "あ～あ、大雪でも降ってくれないかなぁ～"
"2005206-26-ヤクモ" = "どうしてって？大雪で外出できなくなれば、部屋にこもってコンテンツを消費するのが最善だと世論操作を……。"
"2005206-27-ヤクモ" = "おっと失礼……「健全な推奨」が、できるからです。"
"2005206-28" = "[s] \"もう隠す気、ないんだね……。\""
"2005206-29-ヤクモ" = "……コンプラをちゃんと守っている、と言ってください。"
"2005206-30-ヤクモ" = "そして、ここで問題が一つ。"
"2005206-31-ヤクモ" = "レッドウィンターはいつも雪で覆われてるんですよねぇ……。"
"2005206-32-ヤクモ" = "降雪なんて日常茶飯事ですので、豪雪になると言ったところで説得力が……。"
"2005206-33" = "[s] \"つまり、大雪をアピールしたいってことだよね？\""
"2005206-34-ヤクモ" = "結論からいえば、そうなりますが。"
"2005206-35-ヤクモ" = "え？良い案がある……？"
"2005206-36-ヤクモ" = "……あのぉ、先生？"
"2005206-37-ヤクモ" = "理解が追いつかないのですが、もう一度説明をお願いしても……？"
"2005206-38" = "[s3] \"ヤクモがスノーエンジェルを作っている写真を――\"\n[s4] \"次の表紙にしよう！\""
"2005206-39-ヤクモ" = "なぜ……。"
"2005206-40" = "[s] \"積雪量が多くないと、スノーエンジェルはできないからね。\""
"2005206-41-ヤクモ" = "だからどうしてそれを私が……？"
"2005206-42-ヤクモ" = "私は人前に出るのが苦手なんですが。"
"2005206-43-ヤクモ" = "自他ともに認めるインドア派ですし……。"
"2005206-44" = "[s5] \"それ！\"\n[s6] \"そんなヤクモが雪に埋もれた姿を見れば、\"\n[s7] \"相当の大雪が降ったって、みんな思うはず。\""
"2005206-45-ヤクモ" = "えっ……普段外に出ない出版部部長が埋もれるほどの雪となれば――"
"2005206-46-ヤクモ" = "みんな只ならぬ事態だと思ってくれるって……？"
"2005206-47-ヤクモ" = "先生的にも、その絵は面白そうだから撮りたい……？"
"2005206-48-ヤクモ" = "……先生が撮りたいだけじゃないですか。"
"2005206-49" = "[s] \"売上のためならなんでもできる、だっけ？\""
"2005206-50-ヤクモ" = "うっ……これが、因果応報……。"
"2005206-51-ヤクモ" = "致し方ない……口は災いの元……。"
"2005206-52" = "[wa:470]― [log=야쿠모]おお……[wa:1590]ふかふかですねぇ。[/log]"
"2005206-53" = "― [log=야쿠모]意外と[wa:840]良い……[wa:1460]かもしれません。[/log]"
"2005206-54" = "[wa:330]― [log=야쿠모]……と[wa:560]思いましたが、[wa:2550]寒いですね[wa:780]やっぱ。[/log]"
"2005206-55" = "― [log=야쿠모]はくしょん！[/log]"
"2005206-56" = "[ns] \"目線くださ～い！\""
"2005206-57" = "[wa:1910]― [log=야쿠모]撮れました？[/log]"
"2005206-58" = "― [log=야쿠모]では[wa:400]次は[wa:450]先生の番です。[/log]"
"2005206-59" = "― [log=야쿠모]あれ？[/log]"
"2005206-60" = "― [log=야쿠모]……まさか[wa:530]私にだけ[wa:720]やらせるつもりですかぁ？[/log]"
"2005206-61" = "[wa:650]― [log=야쿠모]やれやれ、[wa:1570]それはあまりにも[/log]"
"2005206-62" = "― [log=야쿠모]安易だと[wa:390]思いますけどねぇ？[wa:1730]先生？[/log]"
"2005206-63" = "[wa:980]― [log=야쿠모]レッドウィンターの[wa:850]冬将軍は、[/log]"
"2005206-64" = "― [log=야쿠모]みんなに[wa:680]平等ですよぉ？[wa:1920]ムフフ。[/log]"
