[translation]
"1014605-1" = "照れ屋な議長の夏"
"1014605-2" = "（マコトの様子が気になり、万魔殿を訪ねた）"
"1014605-3" = "（すると……）"
"1014605-4" = "[ns] \"みんな、もしかして……。\""
"1014605-5-万魔殿の部員B" = "い、いいえ！"
"1014605-6-万魔殿の部員B" = "私たちは何も知りません！"
"1014605-7-万魔殿の部員B" = "はい、マコト議長の姿は見ていません！"
"1014605-8" = "[ns] \"……？\""
"1014605-9" = "（そして……）"
"1014605-10-ゲヘナの生徒" = "ん？マコト議長？誰、それ？"
"1014605-11-ゲヘナの生徒" = "ああ、いつも派手な格好で親衛隊を連れている人のこと？"
"1014605-12-ゲヘナの生徒" = "あの人なら、保健室に向かったのを見たよ。"
"1014605-13-ゲヘナの生徒" = "あ～羨まし～#n私も授業サボっちゃおうかな～"
"1014605-14" = "（さらに……）"
"1014605-15-救急医学部の部員" = "マコト議長ですか？"
"1014605-16-救急医学部の部員" = "さっきまでこちらにいたのですが……。"
"1014605-17-救急医学部の部員" = "なんだか緊張して、焦っているみたいでした。#n特に怪我とかはなかったみたいですが……。"
"1014605-18-救急医学部の部員" = "急いで出ていってしまったので、戻ってくるかはちょっと分かりません。"
"1014605-19-救急医学部の部員" = "戻ってきたら、先生が探していたとお伝えしておきますね。"
"1014605-20" = "（一日中マコトを捜し回ったが、入れ違う事が多く、会えなかった）"
"1014605-21" = "[ns] \"……？\""
"1014605-22-万魔殿の部員B" = "本当にこれで大丈夫なのかな……？"
"1014605-23-万魔殿の部員B" = "こんな時間まで残ってる生徒もいないと思うけど？"
"1014605-24-万魔殿の部員B" = "それもそうだけど……。"
"1014605-25" = "[ns] \"これは……。\""
"1014605-26-マコト" = "ん？何だ？また先生が来たのか？"
"1014605-27-マコト" = "だが、このマコト様がここに隠れていることは――"
"1014605-28-マコト" = "……？"
"1014605-29-マコト" = "せ、先生！？どういうことだ？"
"1014605-30" = "[s1] \"これが貼ってあったから。\"\n[s2] \"「プール貸切中」って……。\""
"1014605-31" = "[ns3] \"こんなことをするのは……。\"\n[ns4] \"マコトしかいないと思って。\""
"1014605-32-マコト" = "な、何だと！？"
"1014605-33-マコト" = "くうっ！このマコト様の策が裏目に出るとは……！"
"1014605-34" = "[s5] \"偶然聞こえちゃったんだけど……。\"\n[s6] \"もしかして、私を避けていたの？\""
"1014605-35-マコト" = "そ、それは……！"
"1014605-36-マコト" = "……。"
"1014605-37-マコト" = "こうなった以上、何を言っても無駄だろう。"
"1014605-38-マコト" = "……その通りだ。先生を避けていた。"
"1014605-39-マコト" = "理由はモモトークでも伝えた通り――"
"1014605-40-マコト" = "――己の感情を、自覚したからだ。"
"1014605-41-マコト" = "……シャーレの先生よ。"
"1014605-42-マコト" = "以前、取引を提案したことがあっただろう？"
"1014605-43-マコト" = "あの時は断られてしまったが……#n今、改めてマコト様の新しい提案を聞いてもらえないだろうか？"
"1014605-44" = "[wa:1590]― [log=마코토 수영복]私は――[/log] "
"1014605-45" = "― [log=마코토 수영복]いつも、[wa:230]万魔殿と[wa:1800]ゲヘナの代表として立っている。[/log] "
"1014605-46" = "― [log=마코토 수영복]だからこそ、[/log] "
"1014605-47" = "― [log=마코토 수영복]自身の欲望や感情と[wa:1280]向き合えていなかったのだろう。[/log] "
"1014605-48" = "[ns] （そうだったのか……？）"
"1014605-49" = "[wa:1070]― [log=마코토 수영복]だが、[wa:1200]シャーレの先生よ。[/log]"
"1014605-50" = "― [log=마코토 수영복]この提案は、[wa:2030]万魔殿の議長としてではなく、[wa:3700]個人的なものだ。[/log]"
"1014605-51" = "― [log=마코토 수영복]認めよう。[wa:1530]先生は私にとって……[/log] "
"1014605-52" = "― [log=마코토 수영복]少し[wa:1030]特別な存在になったのかもしれない。[/log] "
"1014605-53" = "[wa:1240]― [log=마코토 수영복]例え代償を支払ったとしても――[/log] "
"1014605-54" = "― [log=마코토 수영복]必ず獲得しなければ[wa:1010]ならない対象となっている。[/log] "
"1014605-55" = "[ns] \"獲得しなければならない対象……？ \""
"1014605-56" = "[wa:1200]― [log=마코토 수영복]いや、[wa:950]確保……？[wa:1170]捕獲か……？[/log] "
"1014605-57" = "― [log=마코토 수영복]……この感情をどう表現すべきなのかは、[wa:2560]分からない。[/log] "
"1014605-58" = "[wa:550]― [log=마코토 수영복]そうだな。[wa:1050]強いていうのなら――[/log] "
"1014605-59" = "― [log=마코토 수영복]――私のモノに[wa:1960]なってくれ。[/log] "
"1014605-60-マコト" = "……悪い提案ではないはずだ。"
"1014605-61-マコト" = "以前、このマコト様はキヴォトスの半分を譲ると提案したが、先生はそれを断った。"
"1014605-62-マコト" = "同じ過ちを繰り返すほど愚かではない。それに、この提案の方が価値がある。"
"1014605-63-マコト" = "そうだ……キヴォトスなんか目じゃない。"
"1014605-64-マコト" = "先生を私のモノにするということは――先生も、この私を手中に収めることができるのだ。"
"1014605-65-マコト" = "これほど魅力的な提案は他にないだろう？"
"1014605-66" = "[ns7] \"……気持ちはありがたいけど。\"\n[ns8] \"誰かの「モノ」になるつもりはないよ。\""
"1014605-67" = "[ns] \"私は、みんなの先生だからね。\""
"1014605-68-マコト" = "ゲホ、ゲホッ……！"
"1014605-69-マコト" = "ゲホゲホッ……。"
"1014605-70-マコト" = "そ、そうか……。"
"1014605-71-マコト" = "いや、安心したぞ。先生はそうであるべきだ。"
"1014605-72-マコト" = "このマコト様は、全く……#n少しも、動じてなどいない。"
"1014605-73-マコト" = "……ずいぶんと遅くなってしまったな。#nシャーレまでリムジンで送るとしよう。"
"1014605-74-マコト" = "……これは断らないでもらいたい。"
"1014605-75" = "（これ以上、断るのは難しいので、マコトが用意してくれたリムジンに乗って戻ることにした）"
