[translation]
"2601505-1" = "ノーティ・ガール"
"2601505-2-イチカ" = "あ、先生。"
"2601505-3-イチカ" = "すみません、こんな時間に呼び出しちゃって。"
"2601505-4-イチカ" = "この前の散歩……じゃなくて。"
"2601505-5-イチカ" = "面談のことなんすけど～"
"2601505-6" = "[s1] \"ああ！それのことなら！\"\n[s2] \"心配しなくて大丈夫だよ！\""
"2601505-7-イチカ" = "さすが！話が早くて助かるっす～"
"2601505-8-イチカ" = "夜の海の雰囲気にやられた……んすかね？"
"2601505-9-イチカ" = "私としたことが、おしゃべりがすぎたっす。"
"2601505-10-イチカ" = "とにかく、あの日のことは忘れてほしいっす……。"
"2601505-11" = "[s3] \"私はイチカのどんな姿も！\"\n[s4] \"全部受け入れるよ！\""
"2601505-12-イチカ" = "え？"
"2601505-13-イチカ" = "いや、そういうことじゃ……。"
"2601505-14-イチカ" = "……。"
"2601505-15-イチカ" = "ふぅ……。"
"2601505-16-イチカ" = "やっぱ、普通に話しても通じないっすね。"
"2601505-17-イチカ" = "……先生。"
"2601505-18-イチカ" = "私がどんな姿でも受け入れるって……。"
"2601505-19-イチカ" = "……嘘じゃないっすね？"
"2601505-20" = "[s] \"い、イチカ……？\""
"2601505-21" = "[wa:770]― [log=이치카 수영복]もしかして私のこと、[wa:2260]勘違いしてませんか？[/log]"
"2601505-22" = "― [log=이치카 수영복]トリニティだから、[wa:1590]温室育ちの心優しい[/log]"
"2601505-23" = "― [log=이치카 수영복]お嬢様なんじゃないか[wa:1610]って。[/log]"
"2601505-24" = "[wa:1460]― [log=이치카 수영복]正義実現委員会は、[wa:2470]トリニティの荒事を[/log]"
"2601505-25" = "― [log=이치카 수영복]一手に引き受ける[wa:870]集団なんですよ？[/log]"
"2601505-26" = "― [log=이치카 수영복]私がいつもつけてる[wa:1250]チョーカー。[/log]"
"2601505-27" = "― [log=이치카 수영복]あれ、[wa:1400]実は「首輪」[wa:940]だって[wa:710]言ったら……[/log]"
"2601505-28" = "― [log=이치카 수영복]どうします？[/log]"
"2601505-29" = "― [log=이치카 수영복]何かに「首輪」をつける[wa:1290]理由は一つ。[/log]"
"2601505-30" = "[wa:1140]― [log=이치카 수영복]察しのいい先生なら、[/log] "
"2601505-31" = "― [log=이치카 수영복]分かると思うんですけど。[/log] "
"2601505-32" = "― [log=이치카 수영복]そしてその「首輪」が外れたとき、[/log]"
"2601505-33" = "― [log=이치카 수영복]何が起こるのかも――[wa:40] [/log]"
"2601505-34" = "― [log=이치카 수영복]想像、[wa:2000]できますよね？[/log]"
"2601505-35" = "[wa:610]― [log=이치카 수영복]……って、[wa:810]すみません。 [/log]"
"2601505-36" = "― [log=이치카 수영복]ちょっとやりすぎたっすね。[/log]"
"2601505-37" = "― [log=이치카 수영복]これに懲りたら、[/log]"
"2601505-38" = "― [log=이치카 수영복]滅多なこと言っちゃダメっすよ？[wa:240] [/log]"
"2601505-39" = "― [log=이치카 수영복]私が[wa:580]本当に危ないヤツだったら、[/log]"
"2601505-40" = "― [log=이치카 수영복]どうするつもり[wa:750]だったんすか？[/log]"
"2601505-41" = "[ns5] \"びっくりした……。\"\n[ns6] \"イチカも、イタズラするんだね。\""
"2601505-42" = "[wa:2260]― [log=이치카 수영복]はは……[wa:860]まぁ、[/log] "
"2601505-43" = "― [log=이치카 수영복]こんなのは[wa:500]先生の前でだけっすから。[wa:2520]それと……[/log] "
"2601505-44" = "― [log=이치카 수영복]今日のことは、[wa:1400]墓まで持ってくっすよ。[/log]"
"2601505-45" = "― [log=이치카 수영복]二人で。[/log]"
"2601505-46-イチカ" = "……。"
"2601505-47" = "[s7] \"……。\"\n[s8] （き、気まずい）"
"2601505-48-イチカ" = "こういう展開は狙ってなかったんすけど……。"
"2601505-49-イチカ" = "やってしまったっす……。"
"2601505-50-イチカ" = "え、ええと……。"
"2601505-51-イチカ" = "今日はお互い部屋に戻って、また今度話したいっす。"
"2601505-52" = "（イチカにやや強めに背中を押されながら、宿の部屋に戻った……)"
