[translation]
"2601506-1" = "デジャヴ・ガール"
"2601506-2" = "[ns1] \"私はイチカのどんな姿も！\"\n[ns2] \"全部受け入れるよ！\""
"2601506-3-イチカ" = "……あ、あれ？"
"2601506-4-イチカ" = "聞き間違い……？"
"2601506-5-イチカ" = "……どういうことだろ？"
"2601506-6-イチカ" = "先生、まったく同じこと前にも言ったっすよ。"
"2601506-7" = "[s] \"わかってるよ。\""
"2601506-8-イチカ" = "えっ。"
"2601506-9-イチカ" = "……どうしてっすか？"
"2601506-10-イチカ" = "私の話、聞いてなかったっすか…？"
"2601506-11-イチカ" = "……いや、先生に限ってそんなことないっす。"
"2601506-12-イチカ" = "この前は、気まぐれで危ないヤツになってみたんすけど……。"
"2601506-13-イチカ" = "……本当は、あんまり「手のかかる子」になりたくないんす。"
"2601506-14" = "[s] \"イタズラしてたのに？\""
"2601506-15-イチカ" = "……それは、そうなんすけど。"
"2601506-16-イチカ" = "あー……もう「手のかかる子」枠、入ってるっす？"
"2601506-17-イチカ" = "それだと困るっすね……。"
"2601506-18-イチカ" = "……あれ？"
"2601506-19-イチカ" = "また面談みたいになってるっす……！"
"2601506-20" = "[s3] \"「いい子」じゃなくても、平気だよ。\"\n[s4] \"私の前では、隠さなくていいから。\""
"2601506-21-イチカ" = "……あー。"
"2601506-22-イチカ" = "そ、そうすか……。"
"2601506-23-イチカ" = "え……ええと……。"
"2601506-24-イチカ" = "……はは。参っちゃうっすね～"
"2601506-25-イチカ" = "これ、先生にもっと世話焼かれちゃうやつっす？"
"2601506-26-イチカ" = "あ、嫌じゃないっすよ！？"
"2601506-27-イチカ" = "嫌じゃないんすけど……先生も忙しそうなんで……。"
"2601506-28-イチカ" = "気を遣わせるのもなって思うんすよ。#nだから、はぐらかしてみたりするんすけど……。"
"2601506-29-イチカ" = "結局、いろいろ見せちゃってるっすね……。"
"2601506-30-イチカ" = "いや～……参ったっすね。"
"2601506-31-イチカ" = "いまさら誤魔化しても、しょうがないか……。"
"2601506-32-イチカ" = "やっぱ私、「いい子」にはなれないっすね。"
"2601506-33" = "[s5] \"責めてるわけじゃないよ。\"\n[s6] \"私の前で肩の力を抜いても大丈夫。\""
"2601506-34-イチカ" = "……そういうとこっすよ。"
"2601506-35-イチカ" = "……。"
"2601506-36-イチカ" = "了解っす。"
"2601506-37-イチカ" = "そうおっしゃるなら……。"
"2601506-38-イチカ" = "これから先生の前では、もう少し素直になろうかな。"
"2601506-39-イチカ" = "言っとくっすけど――"
"2601506-40-イチカ" = "……全部、先生の責任っすからね？"
