[translation]
"1005403-1" = "ベンチの片隅の修道女"
"1005403-2" = "スタジアムのトラック横"
"1005403-3" = "（心配になったので、マリーを探しにきた）"
"1005403-4" = "（ベンチの片隅に、燃え尽きたような表情のマリーが座り込んでいる）"
"1005403-5-マリー" = "はぁ、はぁ……はぁ……はぁ……。"
"1005403-6-マリー" = "世界が……真っ白……です。"
"1005403-7-マリー" = "なんだかぼんやりして……誰でしょうか？#n私に手を振ってくださる、あちらの方は……。"
"1005403-8" = "[ns1] \"マ、マリー……！？\"\n[ns2] \"だ、大丈夫！？\""
"1005403-9-マリー" = "……！？"
"1005403-10-マリー" = "あ……えっ！？#nせ、先生！？い、いつからそこに……！"
"1005403-11" = "[wa:500]― はぁ、[wa:1300]はぁ……"
"1005403-12" = "[wa:1300]― すみません、[wa:700]先生……。"
"1005403-13" = "[wa:1400]― こんな姿を……[wa:1700]はぁ……"
"1005403-14" = "[wa:1300]― お見せする[wa:500]つもりでは[wa:700]なかったの[wa:400]ですが……。"
"1005403-15" = "[wa:2200]― すみません、"
"1005403-16" = "[wa:1600]― まずは……[wa:1600]落ち着いてから、[wa:900]続きを……。"
"1005403-17" = "[wa:200]― はぁ……[wa:2500]ふぅ……。"
"1005403-18" = "[ns3] \"もう少し休もうか。何か欲しいものはある？\"\n[ns4] \"大丈夫？必要なものがあれば何でも言って。\""
"1005403-19" = "[wa:200]― えっ……！？"
"1005403-20" = "[wa:200]― えっ……！？"
"1005403-21" = "[wa:600]― あっ、[wa:500]その、[wa:800]別に[wa:500]そういう[wa:300]意味では……！"
"1005403-22" = "[wa:300]― お、[wa:400]お言葉[wa:400]だけでも[wa:1000]とても[wa:300]ありがたいです……[wa:1700]ええ……。"
"1005403-23" = "[wa:1300]― （先生が……[wa:1400]私のことを[wa:800]気に[wa:200]かけてくださるなんて……。）"
"1005403-24" = "[wa:1600]― （そんな事、[wa:1500]思いも[wa:300]して[wa:200]おりませんでした……。）"
"1005403-25" = "[wa:2500]― あの……"
"1005403-26" = "[wa:1500]― こんな事を、[wa:1000]口に[wa:100]して[wa:300]良いのか[wa:1200]分かりませんが……。"
"1005403-27" = "[wa:1000]― 先生を[wa:600]独り占めして[wa:600]いる[wa:200]みたいで……"
"1005403-28" = "[wa:1800]― こんな事、[wa:1100]罰が[wa:400]あたって[wa:300]しまうかも[wa:500]しれません……[wa:2000]でも、"
"1005403-29" = "[wa:1000]― 私……[wa:1500]この時間が、"
"1005403-30" = "[wa:1500]― とても[wa:500]幸せ……[wa:1000]なんです……。"
"1005403-31-マリー" = "ありがとうございます、先生。#nおかげで楽になりました。"
"1005403-32-マリー" = "どうしてこうなったのか……？#nえっと、何か特別な事があったわけではないんですが……"
"1005403-33-マリー" = "その……競技の合間に助けを必要としている方がいて、お手伝いを……。"
"1005403-34" = "[s5] \"自分の種目をこなしながら、人助けまで！？\"\n[s6] \"無理は禁物だよ。マリーのことが心配。\""
"1005403-35-マリー" = "すみません……どうしても気になってしまって……。"
"1005403-36-マリー" = "やはり困っている方々を見かけては放っておけず、つい……。"
"1005403-37-マリー" = "……ですが、先生のおっしゃる通りですね。#nこうしてご心配をおかけしてしまいました。"
"1005403-38-マリー" = "次からは無理せず、実行委員の方々や先生を頼ろうと思います。"
"1005403-39-マリー" = "……えっ？"
"1005403-40-マリー" = "楽しめているのか、と？"
"1005403-41-マリー" = "……はい、とても楽しいです！それはもう、想像以上に！#nこうして力尽きてしまうほどです！"
"1005403-42-マリー" = "正直に申し上げますと、最初は不安で胸がいっぱいでしたが……。"
"1005403-43-マリー" = "いざ競技が始まってしまえば、そんな事吹き飛んでしまいました！"
"1005403-44-マリー" = "大運動会が終わってからも、時間を見つけて運動してみようと思うほどです。"
"1005403-45-マリー" = "……あ。"
"1005403-46-マリー" = "い、今さらですが……先生は競技に出場されていませんよね。"
"1005403-47-マリー" = "ずっと私たち生徒の面倒を見てくださって……。"
"1005403-48-マリー" = "その……申し訳ございません。私たちばかり楽しんで……。"
"1005403-49" = "[s7] \"マリーが楽しめてるみたいで良かった。\"\n[s8] \"大丈夫、私も楽しんでるよ。\""
"1005403-50-マリー" = "先生……。"
"1005403-51-マリー" = "そう、ですか……？#nそれなら良いのですが。"
"1005403-52-マリー" = "先生は、いつもそうやって私たちのことを見守ってくださって……#n感謝の気持ちでいっぱいです……。"
"1005403-53-マリー" = "……先生。"
"1005403-54-マリー" = "この先、何もないのが一番ではありますが……。"
"1005403-55-マリー" = "もし私でお力になれることがありましたら、いつでもお呼びください。#n私も先生のお役に立ちたいんです。"
"1005403-56-マリー" = "それとも、お邪魔でしょうか……？"
"1005403-57" = "[s9] \"ううん、そんな事ないよ。楽しみにしているね。\"\n[s10] マリーと指切りをした。"
"1005403-58-マリー" = "……！"
"1005403-59-マリー" = "約束です！#n……忘れないでくださいね。"
"1005403-60-マリー" = "ふふっ。"
"1005403-61-マリー" = "……その時を楽しみにお待ちしていますね。"
"1005403-62" = "（元気を取り戻したマリーは勢いよく立ち上がり、次の種目へ向けて準備にかかった）"
"1005403-63" = "（その背中を見送ってから、マリーが座っていた場所に腰を下ろそうとしたところ……）"
"1005403-64" = "（……どこからかボールが飛んできて顔に当たった）"
