[translation]
"1000303-1" = "バッグの秘密"
"1000303-2" = "トリニティ総合学園・校庭"
"1000303-3-ヒフミ" = "ルン、ルンルン～♪ルンルン、ルンルン～♬"
"1000303-4-ヒフミ" = "あっ、先生！"
"1000303-5-ヒフミ" = "あぁっ！"
"1000303-6-ヒフミ" = "あいたたたた……。"
"1000303-7" = "[s] \"大丈夫？\""
"1000303-8-ヒフミ" = "えへへ……だ、大丈夫です。私、おっちょこちょいで、転ぶことには慣れてますから！"
"1000303-9-ヒフミ" = "でも、変ですね。この辺りには引っかかるような石とかもなかったのに、急にバランスを崩すなんて……。"
"1000303-10" = "[s] \"バックが重すぎるんじゃない？\""
"1000303-11-ヒフミ" = "このペロロ様のバックですか？確かに、そうかもしれません。"
"1000303-12-ヒフミ" = "最近バックにあれこれ入れていたので、振り回されそうなくらい重たくなっちゃって……そろそろ整理しようかと思っていたところです。"
"1000303-13-ヒフミ" = "これを機に、今から整理しようかな……。"
"1000303-14" = "[ns] \"……これは？\""
"1000303-15-ヒフミ" = "あ、先生も気になりましたか！それはペロロ様の顔がプリントされた特製の絆創膏です！"
"1000303-16-ヒフミ" = "友達が怪我した時、手元に絆創膏がないと困るでしょう？"
"1000303-17-ヒフミ" = "ですから絆創膏を1セット、バックに入れてるんです！"
"1000303-18" = "[ns] \"………これは？\""
"1000303-19-ヒフミ" = "あ、それはビッグブラザー様の形のクッションです！"
"1000303-20-ヒフミ" = "中に羽毛がたくさん入ってるので、触るとふかふかなんですよ。"
"1000303-21-ヒフミ" = "公園のベンチに座る時などに、背中に置くと楽に座れるんです！"
"1000303-22" = "[ns] \"…………これは？\""
"1000303-23-ヒフミ" = "それはピンキーパカさんがプリントされた、折り畳み傘です！"
"1000303-24-ヒフミ" = "今日は雨の予報ではありませんでしたが、たまには天気予報が外れる時もありますよね？"
"1000303-25-ヒフミ" = "そんな時に備えて、傘は必須かなと！"
"1000303-26-ヒフミ" = "うーーん……何か要らない物はないかなと思って整理してみましたが、全部大事な物ばかりです。"
"1000303-27-ヒフミ" = "仕方ないですね、しばらくはこの重いバックを持ち歩くしか……。"
"1000303-28" = "[s] \"ヒフミは徹底して準備するタイプなんだね。\""
"1000303-29-ヒフミ" = "そ、そうですか？そうかもしれません、えへへ……。"
"1000303-30-ヒフミ" = "私は平凡な人間ですから、友達の役に立つためには、普段から普通以上に努力しなきゃいけないと思ってるんです。"
"1000303-31-ヒフミ" = "このバックは、その努力の象徴なんです！"
"1000303-32-ヒフミ" = "あっ、急に雨が……。"
"1000303-33-ヒフミ" = "見てください、本当に使うタイミングが来ました。#nふふっ。"
"1000303-34-ヒフミ" = "先生、このピンキーパカさんの傘に入ってください。さあ、もっとこっちへ。"
"1000303-35-ヒフミ" = "恥ずかしがらなくていいですよ。さ、早く！"
"1000303-36" = "その後、駅までヒフミと相合傘をして帰った。"
