[translation]
"1010803-1" = "電気羊をめぐる冒険"
"1010803-2" = "（エラーメッセージが気になり、ミレニアムの寮に向かった）"
"1010803-3" = "（いつも通り、平和に見えたが……）"
"1010803-4-ユウカ" = "ん……誰よ、こんな時間に。"
"1010803-5-ユウカ" = "はぁ、書類の受付なら――"
"1010803-6-ユウカ" = "[USERNAME]先生！？#nこんな時間にどうしてミレニア……いや、私の部屋に！？"
"1010803-7-ユウカ" = "そこで待っててください！"
"1010803-8-ユウカ" = "5分！5分だけで良いですから！"
"1010803-9" = "[s1] \"大丈夫……？\"\n[s2] \"何かトラブルがあったわけじゃないの？\""
"1010803-10-ユウカ" = "えっ、どういうことですか？"
"1010803-11-ユウカ" = "そんなメッセージを送った覚えはありませんが……。"
"1010803-12-ユウカ" = "返信が止まったので、#nもうお休みになったのかと思い寝ようとしていたところです。"
"1010803-13" = "[ns] ユウカにモモトークの内容を見せる。"
"1010803-14-ユウカ" = "これは……。"
"1010803-15-ユウカ" = "なるほど、理解しました。"
"1010803-16-ユウカ" = "また誰かが[ruby=でんきひつじ]電気羊[/ruby]を使ったようですね。"
"1010803-17" = "[s] \"……「電気羊」？\""
"1010803-18-ユウカ" = "ミレニアムタワーで使われている節電ドローンの別名です。"
"1010803-19-ユウカ" = "ミレニアムには高電力の設備が多いので、一日の電気代だけでもかなりの額になります。なので、生徒がいない夜間は節電のために、電子機器を制御するドローンが校内の見回りをしてるんです。"
"1010803-20-ユウカ" = "そして、そのドローンの出す音が「羊の鳴き声」に似ているため、電気羊と呼ばれるようになりました。"
"1010803-21-ユウカ" = "寮やサーバー室には近づけないようにセンサーを設置しているのですが、誰かが片付けてしまったんでしょう。"
"1010803-22" = "[s3] \"なるほど。\"\n[s4] \"ユウカに何かあったわけじゃなくて良かったよ。\""
"1010803-23-ユウカ" = "わ、わざわざ確認に来ていただく必要は……。"
"1010803-24-ユウカ" = "……あの、先生。#nひとつお願いをしても良いでしょうか？"
"1010803-25" = "[s] \"どんなお願い？\""
"1010803-26-ユウカ" = "いち早く羊を回収して、「檻」に入れたいんです。"
"1010803-27-ユウカ" = "このままでは、研究設備まで落とされてしまうかもしれませんし、#nみんなの大事なデータが破損する恐れもあります。"
"1010803-28-ユウカ" = "……手伝っていただけませんか？"
"1010803-29" = "[s] \"もちろんだよ、任せて。\""
"1010803-30-ユウカ" = "ありがとうございます。#n調べたところ、20匹ほど脱走してるようです。急ぎましょう。"
"1010803-31" = "（その後、ユウカと一緒に節電ドローンを探し回った）"
"1010803-32-節電ドローン" = "メエエエエエ――"
"1010803-33-ユウカ" = "19匹目……。"
"1010803-34-ユウカ" = "……20匹目！"
"1010803-35-ユウカ" = "これで全部です！お疲れ様でした、先生！"
"1010803-36-ユウカ" = "幸い、被害があったのはサーバー室だけのようです。"
"1010803-37-ユウカ" = "先生が来てくれなかったら、どれだけ被害が大きくなっていたことか……。"
"1010803-38" = "[s] \"解決できて良かったよ。\""
"1010803-39" = "[ns] \"羊を数えてたからか、何だか眠気が……。\""
"1010803-40-ユウカ" = "漫画や映画では寝る前に羊を数えるシーンがありますよね。"
"1010803-41-ユウカ" = "私は不眠症が完全には治ってないので、そこまで感じませんが……。"
"1010803-42-ユウカ" = "実際に羊をイメージした睡眠導入剤やデカフェ飲料を見かけたような。"
"1010803-43" = "[s] \"ユウカも眠れない時に羊を数えたりするの？\""
"1010803-44-ユウカ" = "はい……実は一度やってみたのですが、効果はありませんでした。"
"1010803-45-ユウカ" = "前に本で読んだのですが、眠れない時に羊を数える行為は、日常の近くに牧畜が存在していた中世の習わしのようです。"
"1010803-46-ユウカ" = "草原いっぱいに広がる大量の羊は富の象徴だったそうで、思い浮かべると満たされた気持ちになってよく眠れるから、だとか。"
"1010803-47-ユウカ" = "……まぁ、市街地では羊どころか野生の動物すら珍しいですし、#nなかなか想像できませんよね。"
"1010803-48" = "[s] \"確かに、そうだね。\""
"1010803-49" = "[ns] \"現代人は羊の代わりに何を思い浮かべるんだろう。\""
"1010803-50-ユウカ" = "……口座残高でしょうか？"
"1010803-51" = "[s5] \"それは少し寂しいような……。\"\n[s6] \"もうちょっと夢のあるなにかが良いなぁ。\""
"1010803-52-ユウカ" = "夢、ですか……。"
"1010803-53-ユウカ" = "日当たりの良い一軒家で、好きな人と暮らす毎日、とか。#n例えば、せんっ……。"
"1010803-54" = "[s] \"「せん」？\""
"1010803-55-ユウカ" = "なっ、何でもありません！"
"1010803-56-ユウカ" = "大きくて素敵な家に住めたら良いな、と思っただけです！"
"1010803-57" = "[s] \"ユウカの夢、もっと聞きたいな。\""
"1010803-58-ユウカ" = "もう遅いですから……！"
"1010803-59-ユウカ" = "今日は助けてくださって、ありがとうございました！"
"1010803-60-ユウカ" = "お、おやすみなさいっ！"
"1010803-61" = "（ユウカに追い出されるように寮を出て、シャーレに帰った）"
