[translation]
"10039025-1-ノノミ" = "皆さん、お疲れ様でした～！"
"10039025-2-シロコ" = "ん、捕獲した。"
"10039025-3-シロコ" = "アヤネちゃんたちを「捕獲」する日が来るとは思わなかったけどね～。"
"10039025-4-ノノミ" = "思えば対策委員会は、何かあるたびに誰かを捕獲しているような……。"
"10039025-5" = "[s1] \"……そうかも。\"\n[s2] \"となると、次は……。\""
"10039025-6-マリー" = "……？"
"10039025-7-マリー" = "それはどういう意味で……？"
"10039025-8-マリー" = "……あ、ただの独り言でしたか。"
"10039025-9-ノノミ" = "さて、二人とも！"
"10039025-10-ノノミ" = "そろそろお披露目の時間ですよ～！"
"10039025-11-ノノミ" = "わ、分かったわよ……！"
"10039025-12-ノノミ" = "うぅ……！"
"10039025-13-ノノミ" = "笑ったら絶対に許さないんだからね！"
"10039025-14-ノノミ" = "じゃ、じゃあ……。"
"10039025-15" = "[ns3] \"……！？\"\n[ns4] \"……わぁ。\"\n[ns5] \"……ビックリした。\""
"10039025-16-マリー" = "…………！"
"10039025-17-マリー" = "……すごい、です。"
"10039025-18" = "[ns6] \"マリー？\"\n[ns7] \"大丈夫……？\""
"10039025-19-アヤネ" = "何も言わなくていいからっ！"
"10039025-20-アヤネ" = "皆さんの前で、こんな恥ずかしい格好を……。"
"10039025-21-ノノミ" = "うんうん、二人ともよく似合ってますね！"
"10039025-22-ノノミ" = "……はあぁ、何度もデザインを修正してもらった甲斐がありました。"
"10039025-23-アヤネ" = "そ、そこまで嬉しいものなの……？"
"10039025-24-セリカ" = "これ、布面積が……！"
"10039025-25-アヤネ" = "……せ、せせせ先生！？"
"10039025-26-セリカ" = "っっ、どうして先生がいるのよ！"
"10039025-27-セリカ" = "ちょっと、聞いてないんだけど！"
"10039025-28-アヤネ" = "そんなに見られると……！"
"10039025-29" = "[s8] \"二人とも、可愛いね。\"\n[s9] \"よく似合ってるよ。\""
"10039025-30-アヤネ" = "うぅ……。"
"10039025-31-セリカ" = "お世辞なんていらないんだから！"
"10039025-32-セリカ" = "いえ、すごく似合ってますよ！"
"10039025-33-マリー" = "……私も着てみたい、と思うくらいです。"
"10039025-34-セリカ" = "本当に……？#nって先生、この人は？"
"10039025-35-マリー" = "シスターフッドの？ど、どうしてシスターさんがここに？"
"10039025-36-セリカ" = "……え？"
"10039025-37-セリカ" = "私たちからアイドルについて教わるために来たの……？"
"10039025-38-セリカ" = "先生だけなら信じられなかったけど、#nシスターさんが言うなら嘘じゃなさそうね。"
"10039025-39" = "[ns10] \"……えっ？\"\n[ns11] \"ひどい言われような気が……。\""
"10039025-40-セリカ" = "……？"
"10039025-41-セリカ" = "当たり前じゃない！#n先生ってば、いつも褒めてばかりなんだから！"
"10039025-42-ノノミ" = "あはは……。"
"10039025-43-ホシノ" = "これは先生が悪いねぇ～。"
"10039025-44" = "[s12] \"正直に言ってるだけなのに……。\"\n[s13] \"全部本心だから！二人のライブを応援してるよ！\""
"10039025-45-セリカ" = "まったく……。"
"10039025-46-アヤネ" = "せ、先生……。"
"10039025-47-アヤネ" = "……セリカちゃん。"
"10039025-48-アヤネ" = "その、まだ嫌かもしれないけど……。"
"10039025-49-セリカ" = "ああもう、分かったわよ！#nやれば良いんでしょう、やれば！"
"10039025-50-セリカ" = "約束したわけだし、仕方なくなんだから！"
"10039025-51-アヤネ" = "実はアイドルに興味があったとか、#n可愛い衣装を着てみたかったわけじゃないですから！"
"10039025-52-アヤネ" = "そうだよね、セリカちゃん！"
"10039025-53-セリカ" = "そっかそっか、後輩の言葉は信じてあげないとね～。"
"10039025-54-セリカ" = "う、うるさいっ！"
"10039025-55-シロコ" = "ん、私も手伝う。"
"10039025-56-ノノミ" = "そういうことにしておきましょうか☆"
"10039025-57-ノノミ" = "ふふ……。"
"10039025-58-ノノミ" = "先生、マリーさん、助けていただいて本当にありがとうございました！"
"10039025-59-ノノミ" = "お礼と言っては何ですが……。"
"10039025-60-ノノミ" = "衣装作成をしている業者さんの連絡先と指示書のコツをお教えしますね！"
"10039025-61" = "（その後、ノノミからアイドルについて色々と教えてもらった）"
"10039025-62" = "衣装、クリア"
