[translation]
"10039090-1" = "後日談その1;対策委員会の緊張"
"10039090-2" = "（アイドルコンテストのリハーサル当日）"
"10039090-3" = "（普段とは違う生徒たちの姿を楽しみにしていると……）"
"10039090-4" = "[ns1] \"やあ、セリカ。\"\n[ns2] \"どうかしたの？\""
"10039090-5-セリカ" = "先生、大変なのよ！"
"10039090-6" = "（セリカに連絡をもらい、急いで対策委員会のもとへ向かった）"
"10039090-7-セリカ" = "せ、先生……。"
"10039090-8" = "[s] \"何があったの？\""
"10039090-9-セリカ" = "アヤネちゃんが……。"
"10039090-10-セリカ" = "急にいなくなったの！"
"10039090-11" = "[s] \"えっ！？\""
"10039090-12-ホシノ" = "もうすぐリハーサルが始まるのに、困ったねぇ。"
"10039090-13-ノノミ" = "電話もつながりませんし、何かあったのでしょうか？"
"10039090-14-シロコ" = "まさか、拉致された？"
"10039090-15-セリカ" = "学園の中にいたのに！？"
"10039090-16-ホシノ" = "おじさんの勘だと、違う気がするなぁ。"
"10039090-17-セリカ" = "とにかく、いろんな場所を探してみたけど、見つからないのよ。"
"10039090-18-セリカ" = "先生、どうしよう……。"
"10039090-19" = "[s] \"もう一度、虱潰しに探してみよう！\""
"10039090-20-セリカ" = "……ありがとう、先生！"
"10039090-21" = "（アヤネがいそうな場所を探し続けていると……）"
"10039090-22" = "[ns] \"……アヤネ。\""
"10039090-23-アヤネ" = "……。"
"10039090-24-アヤネ" = "せ、先生！？"
"10039090-25-アヤネ" = "どうして、ここに……。"
"10039090-26" = "[s3] \"……やっと見つけた。\"\n[s4] \"もうすぐリハーサルだけど、何かあったの？\""
"10039090-27-アヤネ" = "……うぅ。"
"10039090-28-セリカ" = "はぁ、はぁ……アヤネちゃん！"
"10039090-29-ノノミ" = "大丈夫ですか？"
"10039090-30-ホシノ" = "急にいなくなったら、おじさんも心配だよ。"
"10039090-31-シロコ" = "ん、怪我はないみたい。"
"10039090-32-アヤネ" = "皆さん……。"
"10039090-33-セリカ" = "どうしたの、みんなビックリしたわよ。"
"10039090-34-アヤネ" = "う、うぅ……。"
"10039090-35-セリカ" = "アヤネちゃん？"
"10039090-36-アヤネ" = "こ、怖いんです……。"
"10039090-37-セリカ" = "何が……？"
"10039090-38-アヤネ" = "……が。"
"10039090-39-ノノミ" = "はい？"
"10039090-40-アヤネ" = "……ステージが大きすぎます！"
"10039090-41-アヤネ" = "さっき、ステージを見てみたら……。"
"10039090-42-アヤネ" = "想像以上の広さで、観客席の数も……。"
"10039090-43-セリカ" = "マンモス校の一番大きいホールなんだから、当然でしょう？"
"10039090-44-アヤネ" = "けど、あそこまで大きいとは……。"
"10039090-45-ノノミ" = "そういえば、アヤネちゃんは目立つのが苦手でしたね……。"
"10039090-46-シロコ" = "うーん、どうする？"
"10039090-47-アヤネ" = "私、ダンスの振り付け覚えきれてないんだけど！"
"10039090-48-セリカ" = "アヤネちゃんを見ながら踊ろうと思ってたのに……。"
"10039090-49-アヤネ" = "……ごめん、セリカちゃん。"
"10039090-50-アヤネ" = "ステージに立つと思ったら、頭が真っ白になって、呼吸も苦しくなるの……。"
"10039090-51-アヤネ" = "私のせいで、計画が台無しになったら……。"
"10039090-52" = "[s] \"計画……？\""
"10039090-53-セリカ" = "賞金を学校の借金返済に充てようと思ってたのよ。"
"10039090-54-シロコ" = "ん、短時間でお金がいっぱい手に入る。"
"10039090-55-ノノミ" = "二人なら、勝てる可能性は大いにあると思うのですが……。"
"10039090-56-アヤネ" = "……うぅ。"
"10039090-57-ホシノ" = "賞金と言っても、そこまで高額じゃないから、気負う必要はないよ。"
"10039090-58-シロコ" = "そうだったの……！？"
"10039090-59-アヤネ" = "で、ですが……。"
"10039090-60-アヤネ" = "このステージは、ホシノ先輩と交わした約束を守る場でもあるのに……。"
"10039090-61-ホシノ" = "……気にしてたんだね、アヤネちゃん。"
"10039090-62-セリカ" = "とりあえず、起きよっか！座り込んでたらどんどん落ち込んじゃうよ！"
"10039090-63-シロコ" = "……うーん、目隠し状態で踊るとか？"
"10039090-64-ノノミ" = "それは危ないかと……。"
"10039090-65-ノノミ" = "おそらく、アヤネちゃんのなかで恐怖心が根付いてしまったのでしょう。"
"10039090-66-ホシノ" = "おじさんにできることがあるなら言ってほしいな。"
"10039090-67-ノノミ" = "今はアヤネちゃんが抱えているプレッシャーを……。"
"10039090-68-ノノミ" = "……先生、何か良い方法はないでしょうか？"
"10039090-69" = "[ns] \"アヤネ、ちょっと良い？\""
"10039090-70-アヤネ" = "先生……？"
"10039090-71" = "[s5] \"緊張するよね。\"\n[s6] \"大勢の前に立つんだから。\""
"10039090-72-アヤネ" = "はい。実際のステージが大きくて……教室とは全然違って……。"
"10039090-73-アヤネ" = "たくさんの観客が私を見ていると思うと……。"
"10039090-74-アヤネ" = "心臓が破裂しそうになって、体が動かなくなるんです。"
"10039090-75" = "[s] \"じゃあ、こう考えたらどうかな？\""
"10039090-76" = "[ns7] \"対策委員会のみんなが観客席にいるから……。\"\n[ns8] \"そこだけを見てパフォーマンスするんだ。\""
"10039090-77-アヤネ" = "は、はい！？"
"10039090-78" = "[s9] \"集中すると、視野が狭くなるって言うでしょ？\"\n[s10] \"ほかの観客の存在も気にならなくなるよ。\""
"10039090-79-アヤネ" = "できるんでしょうか……。"
"10039090-80" = "[s] \"私も見守ってるから。\""
"10039090-81-アヤネ" = "……先生も。"
"10039090-82-アヤネ" = "ん、試す価値はあると思う。"
"10039090-83-アヤネ" = "シロコ先輩……？"
"10039090-84-シロコ" = "私も何かに集中してる時は、ほかのものが見えなくなった。"
"10039090-85-シロコ" = "例えば、ドローンを通風孔から潜入させる時とか、#n銀行警備員の巡回ルートを把握する時とか……。"
"10039090-86-アヤネ" = "少し特殊な事例のような気もしますが、#n良い方法かもしれませんね……。"
"10039090-87-セリカ" = "やってみよう、アヤネちゃん！"
"10039090-88-セリカ" = "それに、リハーサルなんだからミスしたって大丈夫よ！"
"10039090-89-アヤネ" = "セリカちゃん……。"
"10039090-90-セリカ" = "最初は嫌々だったけど、せっかく練習頑張ってきたんだから。"
"10039090-91-セリカ" = "ここで逃げたら、もったいないでしょ。"
"10039090-92-セリカ" = "とりあえず、やってみようよ！"
"10039090-93-セリカ" = "それでダメだったら、その時また考える！まずはできることから！"
"10039090-94-アヤネ" = "……。"
"10039090-95-アヤネ" = "うん……分かった！"
"10039090-96-ノノミ" = "アヤネちゃん！"
"10039090-97-アヤネ" = "……ここで諦めるわけにはいきません。"
"10039090-98-アヤネ" = "たとえ、ステージが想像以上に広くて、観客席の数が多かったとしても……。"
"10039090-99-アヤネ" = "今まで流した血と汗を無駄にはできないですから！"
"10039090-100-セリカ" = "血は流してないけど……。"
"10039090-101-アヤネ" = "やってみせましょう、ステージを爆発させる勢いで！"
"10039090-102-セリカ" = "本当に爆発させちゃダメだからね！？"
"10039090-103-ホシノ" = "うへ～、元気になったみたいだね。"
"10039090-104-ノノミ" = "はい、張り切って行きましょう！"
"10039090-105-シロコ" = "ん、良かった。"
"10039090-106-シロコ" = "このまま観客を捕まえる。"
"10039090-107-ホシノ" = "……心を掴むって意味ですよね？"
"10039090-108-ホシノ" = "それじゃ、準備に戻ろうか。"
"10039090-109-アヤネ" = "はい……もう逃げたりはしません。"
"10039090-110-アヤネ" = "皆さん……どうか見守っていてください！"
"10039090-111" = "[s11] \"うん、頑張って！\"\n[s12] \"二人なら、きっと大丈夫だよ。\""
"10039090-112-アヤネ" = "あ、ありがとうございます……。"
"10039090-113-アヤネ" = "セリカちゃん、さっき忘れたって言ってた振り付け、どの部分？"
"10039090-114-セリカ" = "えっと、ここなんだけど……。"
"10039090-115-ノノミ" = "そろそろリハーサル、始まりますよ～☆"
"10039090-116" = "（最初は緊張していたアヤネだったが、段々と自然なパフォーマンスを見せてくれた）"
"10039090-117" = "（距離があって顔はよく見えなかったけれど……）"
"10039090-118" = "（とても楽しいライブの時間だった）"
