[translation]
"10003105-1" = "第10話;この夏はまだ終わらない"
"10003105-2" = "（そうして熱く燃え上がった海辺の事件は、ヒナの活躍で鎮静化）"
"10003105-3" = "（合宿もこれにて終了、学園に戻る時間が近づいていた……と思いきや）"
"10003105-4" = "夏季合宿用オペレーションルーム"
"10003105-5-アコ" = "す、すみませんでした、委員長！ただ、その……何とか事態を大きくしないように、解決しようとしていたと言いますか……！"
"10003105-6-ヒナ" = "それなりに大きくなってたけど……？"
"10003105-7-アコ" = "その、委員長にバレないように解決すれば万事OKかなと……。"
"10003105-8-ヒナ" = "そもそも、どうしてバレないようにしようとしたのかが全然理解できない。"
"10003105-9-ヒナ" = "こういうのは、私に言ってくれればすぐに解決したはず……違う？"
"10003105-10-アコ" = "それは、その……そうしたら……"
"10003105-11-ヒナ" = "ん？"
"10003105-12-アコ" = "そんなことしたら、また委員長は頑張ってお仕事をされちゃうじゃないですかぁ！"
"10003105-13-ヒナ" = "……え？"
"10003105-14-アコ" = "私はただ、委員長にお休みをとって欲しかっただけでしたのに……！うわぁぁぁん！"
"10003105-15-ヒナ" = "ちょ、ちょっと待って……何の話？お休み？"
"10003105-16" = "えっと、委員長。アコちゃんが言うには、その……。"
"10003105-17-チナツ" = "委員長のストレスがすごいことになっているから、と……。"
"10003105-18-ヒナ" = "ストレス？私が？……どうして？"
"10003105-19-アコ" = "この前、私が淹れたコーヒーを委員長が「美味しい」って……ヒナ委員長、そんなこと滅多に仰らないのに……。"
"10003105-20-ヒナ" = "コーヒー……ってあの、シャーレとの共同作戦のことを話してた時の……？"
"10003105-21-ヒナ" = "えっと……アコ、それは誤解。"
"10003105-22-アコ" = "……？"
"10003105-23-ヒナ" = "あの時、私が美味しいって言ったのはストレスのせいじゃなくて、その、逆に気分が悪くなかったからと言うか……。"
"10003105-24" = "[s1] \"どういうこと……？\"\n[s2] \"海辺で食べるトウモロコシって美味しいよね、みたいな？\""
"10003105-25-ヒナ" = "せ、先生はちょっと静かにしてて……！"
"10003105-26-ヒナ" = "せ、先生はちょっと静かにしてて……！"
"10003105-27-ヒナ" = "その、何て言うか、えっと……。"
"10003105-28-ヒナ" = "こ、細かいことは気にしないで！とにかく、私のことを気遣っての行動だったのは分かったけれど……他にもやり方があったでしょう。"
"10003105-29-アコ" = "はい、すみません……。"
"10003105-30-ヒナ" = "まあでも……この一泊二日、結構ゆっくりできたのは確かだし……うん、色々と悪くなかった。"
"10003105-31-ヒナ" = "……でもそれはそれ、これはこれ。"
"10003105-32-ヒナ" = "それに私はやっぱり、何もせずにじっとしてるより、仕事をしてる方が落ち着くってことも分かったし……。"
"10003105-33" = "[s] \"完全にワーカーホリック……。\""
"10003105-34-ヒナ" = "……何か言った、先生？"
"10003105-35" = "[s] \"何でも無いです……。\""
"10003105-36" = "はぁ。とにかく、どうやら今回の夏の合宿訓練はめちゃくちゃになったみたいだし……。"
"10003105-37" = "このまま帰っ[ruby=パンデモニウム・ソサエティー]たら万魔殿のや[/ruby]つらに、どれだけ嫌味を言われるか分からない。"
"10003105-38-ヒナ" = "……うん、仕方ない。決めた。"
"10003105-39-ヒナ" = "今からあらためて、夏の合宿訓練を始める。"
"10003105-40-イオリ" = "えっと、委員長、訓練はある程度っていうか、もうボロボロっていうか……。"
"10003105-41-ヒナ" = "現時点をもって、海への出入りは禁止。元々私が準備してたスケジュールの通りに、これから36時間の地獄の訓練を始める。"
"10003105-42-イオリ" = "……。"
"10003105-43-チナツ" = "……。"
"10003105-44-アコ" = "……。"
"10003105-45-ヒナ" = "自由時間は一切なし、このくらいの長さだから当然徹夜。この二日間みんな夏を満喫したみたいだし、少しくらい辛くても耐えられるはず。"
"10003105-46-ヒナ" = "これなら万魔殿のタヌキ共も、文句は言えないでしょう。"
"10003105-47-イオリ" = "うっそだろ……！？"
"10003105-48-チナツ" = "私たちは、もうすでに疲労困憊なのですが……まあ、こうなっては何を言っても言い訳ですね。"
"10003105-49-アコ" = "うぅ、承知しました……。"
"10003105-50-ヒナ" = "……ふう。"
"10003105-51-チナツ" = "先生は？何か言いたいことある？"
"10003105-52" = "[s] \"ありません！\""
"10003105-53-ヒナ" = "うん、良い返事。"
"10003105-54-ヒナ" = "……すっぽかした約束の埋め合わせは、また訓練の後で……ね？"
"10003105-55" = "（そうしてゲヘナ風紀委員会のみんなと一緒に過ごした、短いようで長い夏は……まだもう少し終わりそうになかった）"
"10003105-56" = "ヒナ委員長のなつやすみっ！"
