[translation]
"10003045-1" = "第4話;海で稀によくあること"
"10003045-2" = "（それからも風紀委員たちと先生は一丸となって、委員長のために奮闘を続けた）"
"10003045-3-ヒナ" = "ふう……やっぱり部屋は少し退屈ね。"
"10003045-4-ヒナ" = "そうね……先生、もし良かったら一緒に、このボードゲームでも……"
"10003045-5-イオリ" = "先生、海岸が今大混乱でマズい！助けに来て！委員長にはバレないように！"
"10003045-6" = "[ns] \"ご、ごめんヒナ！ちょっと急用で、戻ってきたらやろう！\""
"10003045-7-ヒナ" = "あ、う、うん。待ってる。"
"10003045-8" = "（やっと海辺のスケバンを片付けて帰ってきた後……）"
"10003045-9-ヒナ" = "おかえり、先生。お疲れ様。"
"10003045-10-ヒナ" = "それにしても、今度は外から爆発音も聞こえてきたけど……これ本当に、戦術訓練？"
"10003045-11-ヒナ" = "まあ何にせよ、頑張ってるのなら良いけど……なんだか私だけこうしているのが、申し訳なくなってくる。"
"10003045-12-ヒナ" = "……そうだ、先生。なんだか暑いし、もしよかったら下に行って一緒にアイスクリームでも――"
"10003045-13-チナツ" = "先生、チナツです。現在スラム街近郊で、ヘルメット団と熾烈な戦闘中なのですが……！"
"10003045-14-チナツ" = "重戦車の数が思ったよりも多く、このままではジリ貧でして……。"
"10003045-15-チナツ" = "突破口が見つからないので、助けに来ていただけませんか……！？"
"10003045-16" = "[ns1] \"ヒナごめん、またちょっと急用が……！\"\n[ns2] \"ユーレカ！\""
"10003045-17-ヒナ" = "せ、先生……！？"
"10003045-18-ヒナ" = "せ、先生……！？"
"10003045-19-アコ" = "先生！イオリの方もチナツの方も戦線の状態が怪しいので、指揮をお願いできますか！あっ、委員長にはご内密に！"
"10003045-20-ヒナ" = "先生……？"
"10003045-21-イオリ" = "なんであいつら海から飛び出てくるんだ！？お化けかっ！？先生、どうにかして！"
"10003045-22-ヒナ" = "先生……。"
"10003045-23-チナツ" = "ヘルメット団、戦車に引き続きオートマタ軍団とヘリを出してきました！一体どうすれば……！"
"10003045-24-ヒナ" = "せ――"
"10003045-25-ヒナ" = "えっと、先生……。"
"10003045-26-ヒナ" = "……大丈夫？なんだか顔色があまり良くないけど……。"
"10003045-27" = "[s] \"だ、大丈夫……それよりごめん、ヒナ、その……。\""
"10003045-28-ヒナ" = "別に、私は……シャーレとしてのお仕事なんでしょう？"
"10003045-29-ヒナ" = "いってらっしゃい、気を付けて。私は、大人しく待ってるから……。"
"10003045-30" = "[s] \"うん、頑張って早めに戻ってくる……！\""
"10003045-31" = "（そうして、約2時間にわたる死闘が繰り広げられた）"
"10003045-32" = "夏季合宿用オペレーションルーム"
"10003045-33-イオリ" = "ふぅ、ふぅ……。"
"10003045-34-チナツ" = "はぁ……。"
"10003045-35-アコ" = "皆さん、生きてますか……？"
"10003045-36" = "[s] \"ギリギリ……。\""
"10003045-37-イオリ" = "もう身体も水着もボロボロだけど……まあ、何とか……。"
"10003045-38-チナツ" = "……ここまでの勢いとは、予想外でしたね。"
"10003045-39-アコ" = "ですが、これで――"
"10003045-40-イオリ" = "うん。"
"10003045-41-チナツ" = "……そうですね。"
"10003045-42-アコ" = "スケバン集団「破茶滅茶」並びに「びしょびしょヘルメット団」、どちらも完全な退却を確認しました。インターネット上でも、全面戦争は中断という話が広まっているようです。"
"10003045-43-アコ" = "無事に作戦終了です、お疲れ様でした。"
"10003045-44-イオリ" = "あぁもう、ようやく終わったー！"
"10003045-45-チナツ" = "本当に……せっかくビーチまで来たのに大変でしたね。"
"10003045-46-ホテルの支配人" = "風紀委員会の皆様！ありがとうございます、本当にありがとうございます……！"
"10003045-47-ホテルの支配人" = "これで当ホテルはもちろん、周辺のお店の方々も戻ってこられるはずです！"
"10003045-48-ホテルの支配人" = "お礼と言っては何ですが、今度当ホテルの管轄区でのオープンを予定している温泉チケットをプレゼントしますので、どうか後日お使いください……！"
"10003045-49-アコ" = "いえいえ、私たちはやるべきことをやっただけですから。一応そちらは頂くとして……あらためまして、風紀委員会一同、お疲れ様でした。"
"10003045-50-アコ" = "次の予定である歩行訓練まで残り約1時間、ゆっくり休息を取っておいてください。"
"10003045-51" = "[s] \"ようやくヒナと一緒に、海辺のお散歩ができそうかな。\""
"10003045-52-アコ" = "そうですね。先生もお疲れのところ申し訳ないのですが、委員長の元へ行っていただいて……"
"10003045-53-万魔殿のメンバー" = "こんにちは、アコ行政[ruby=パンデモニウム・ソサエティー]官。万魔殿です[/ruby]。"
"10003045-54-万魔殿のメンバー" = "海の方にいる皆さんは、しっかり訓練を行っておりますでしょうか？まさかとは思いますが、全然別のことをされたりなどはしていませんよね？"
"10003045-55-アコ" = "な、なぜ今……！えっとですね、今私たちは正にその訓練で忙しいので――"
"10003045-56-万魔殿のメンバー" = "おや……？後ろにいらっしゃるイオリさん、どうして水着を――"
"10003045-57-アコ" = "指が滑りましたっ！"
"10003045-58-チナツ" = "こんな時に万魔殿とは……全く、危なかったですねイオリ。"
"10003045-59-イオリ" = "何その私のせいみたいな言い方！？"
"10003045-60-チナツ" = "まあそれにしても、相変わらず邪魔ばかりしてきますね……。"
"10003045-61-イオリ" = "いつものことだし、アコちゃんなら大丈夫でしょ。"
"10003045-62" = "[s] \"じゃあ、私はとりあえずヒナの部屋に戻るね。\""
"10003045-63-チナツ" = "はい。よろしくお願いしますね、先生。"
"10003045-64-イオリ" = "でももうあいつらは退散したんだし、そんなに気にすること無いんじゃないか？"
"10003045-65-イオリ" = "さっきは無理やり中断させちゃったし、委員長をまた海まで連れて行ってあげたら？もう流石に何も起きないでしょ……。"
"10003045-66-チナツ" = "イオリ、「フラグ」って知ってますか……？"
"10003045-67" = "[ns] \"あー……。\""
"10003045-68-イオリ" = "……。"
"10003045-69-チナツ" = "今さら口をつぐんでも遅いですよ、イオリ……。"
"10003045-70-チナツ" = "はぁ……それで、今度は何ですか！？"
"10003045-71-風紀委員" = "しゅ、襲撃です……！相手は――"
"10003045-72-ジュンコ" = "ねえどうして誰もいないわけ！？ここでお祭りが始まるって言ってたじゃん！"
"10003045-73-アカリ" = "お祭りと言いますか、全面戦争ですけどね。まあ似たようなものですけど★"
"10003045-74-ジュンコ" = "どっちでも良いわよ！とにかく、この状況どういうこと！？"
"10003045-75-ハルナ" = "確かにこれでは、今回の目標である「夏の海岸やお祭り騒ぎの中で食べる焼きトウモロコシは、どうしてこんなにも美味しいのか？」が研究できませんわね……。"
"10003045-76-イズミ" = "ねえねえ～いつになったら焼きトウモロコシ食べられるのー！？"
"10003045-77-ジュンコ" = "食べに来たんじゃなくて、売りに来たの！！"
"10003045-78-ジュンコ" = "わざわざこんなに重たい荷物を抱えてここまで来たのに！"
"10003045-79-ジュンコ" = "スケバン集団もヘルメット団もどこに行ったわけ！？どうなってるのよぉ！！"
"10003045-80" = "[s] \"どうして、美食研究会がここに……！？\""
