[translation]
"1013408-1" = "帰ってきた勇者様？"
"1013408-2" = "（それは鋼鉄大陸の事件を解決してから、しばらく経った頃のこと）"
"1013408-3" = "（アリスが送ってくれた住所に向かった）"
"1013408-4" = "（すごい人混みだ）"
"1013408-5" = "（どうやら有名なゲームイベントが開催されているらしい）"
"1013408-6" = "（この人混みからアリスを見つけるのは難しそうだ）"
"1013408-7" = "（今いる場所の情報をアリスに連絡した）"
"1013408-8-アリス" = "先生、どこですか？"
"1013408-9-アリス" = "アリスはここにいます！"
"1013408-10" = "[ns1] \"アリス？\"\n[ns2] \"ここだよー！\""
"1013408-11-アリス" = "あっ、先生発見です！"
"1013408-12-アリス" = "アリスがそちらに行きます！待っていてください！"
"1013408-13-アリス" = "パンパカパーン！"
"1013408-14-アリス" = "先生がパーティーに合流しました！"
"1013408-15" = "[s3] \"その姿は……。\"\n[s4] \"アビ・エシュフ！？\""
"1013408-16-アリス" = "そうです！勇者アリス、完全復か――"
"1013408-17-アリス" = "今、空飛んでなかった！？"
"1013408-18-アリス" = "それ構造どうなってるの！？コスプレってレベルじゃないけど！？"
"1013408-19-アリス" = "それ何のゲームですか？どこのブース？"
"1013408-20-アリス" = "うわぁん！逃げている途中なのを忘れていました！"
"1013408-21-アリス" = "先生、説明は後です！逃げましょう！"
"1013408-22-アリス" = "それで、ゲーム開発部も新作で参加しよう！という流れになったんです。"
"1013408-23-アリス" = "周りのブースよりも目立つにはどうすればいいかを考えた結果――"
"1013408-24-アリス" = "作戦は上手くいきました。大成功です！#nただ、ちょっと上手くいきすぎてしまって……。"
"1013408-25-アリス" = "みなさんブースはそっちのけで、アリスにばっかり興味津々なのです！"
"1013408-26-アリス" = "これでは本末転倒です！"
"1013408-27" = "[s5] \"たしかに目立つ上に飛び回るから……。\"\n[s6] \"私もついつい見ちゃうかも。\""
"1013408-28-アリス" = "先生もですか！？"
"1013408-29-アリス" = "このままだと永遠に部室に帰れません！"
"1013408-30-アリス" = "あっ、見つけた！！"
"1013408-31-アリス" = "あの、もしよければポーズを取っていただけませんか？"
"1013408-32-アリス" = "ああっ！気づかれてしまいました！"
"1013408-33-アリス" = "ひ、1人ずつ話してください！！うわぁん！"
"1013408-34" = "（イベントが終わるギリギリの時間まで、対応は引っ切り無しに続いた）"
"1013408-35-アリス" = "なんとか終わりました……。"
"1013408-36-アリス" = "なんだかもう……記憶も、曖昧です……。"
"1013408-37" = "[s7] \"お疲れ様……。\"\n[s8] \"私も、ずっと写真を撮ってた記憶しか……。\""
"1013408-38" = "[ns9] \"……あっ、そういえば！\"\n[ns10] \"アビ・エシュフは壊れたんじゃなかったっけ。\""
"1013408-39-アリス" = "あまりの忙しさで説明を忘れていました！"
"1013408-40-アリス" = "パンパカパーン！勇者アリス、完全復活です！"
"1013408-41-アリス" = "――と、言いたいところですが。"
"1013408-42-アリス" = "これはレプリカです。"
"1013408-43-アリス" = "オリジナルを忠実に再現してもらいました。"
"1013408-44-アリス" = "その……鋼鉄大陸を出る前に、アビ・エシュフの残骸を見つけたんです。"
"1013408-45-アリス" = "残骸といっても、手のひらサイズの破片でしたが……。"
"1013408-46" = "[s11] \"連れて帰ってきてあげたんだね。\"\n[s12] \"アビ・エシュフも仲間だからね。\""
"1013408-47-アリス" = "……はいっ！"
"1013408-48-アリス" = "それで、もしかしたら……と思ってミレニアムのみなさんに見せてみました。"
"1013408-49-アリス" = "とはいえ、流石に手のひらサイズからの復元はできないと言われてしまいました。"
"1013408-50-アリス" = "でもその代わりに、なるべくオリジナルを[ruby=・]再[/ruby][ruby=・]現[/ruby]してくれるということになったんです！"
"1013408-51-アリス" = "おかげでアビ・エシュフは元の姿を取り戻しました！"
"1013408-52-アリス" = "……オリジナルのパーツは一部だけですが。"
"1013408-53-アリス" = "それにあくまでレプリカなので、前に比べれば出力が大幅に減りました。#n長時間の飛行や機動的な動きなどはもうできません。"
"1013408-54-アリス" = "前ほど耐久度も高くないので、戦闘には使わないようにと念を押されました。"
"1013408-55" = "[s13] \"それでレプリカなんだね。\"\n[s14] \"せっかく再現できたのに残念だね。\""
"1013408-56-アリス" = "？"
"1013408-57-アリス" = "アリスは少しも残念に思いません！"
"1013408-58-アリス" = "魔王との戦いが終わったら力が封印されてしまう勇者はたくさんいます。#nむしろよくあるエンディングです。"
"1013408-59-アリス" = "それに……。"
"1013408-60-アリス" = "今日、アビ・エシュフを着てたくさんの人の前に立ちました。"
"1013408-61-アリス" = "そしてみなさんはアビ・エシュフを見て「カッコイイ」と、「好きだ」と言ってくれました。"
"1013408-62-アリス" = "それは、空を飛んだり、魔王を倒すことよりもずっとずっと、素敵なことです。"
"1013408-63-アリス" = "だからアリスは今日、すごく幸せでした！"
"1013408-64" = "（アリスと手をつないで、ゲーム開発部の部室に戻った）"
"1013408-65" = "（帰り道にも、道行く人から何度も写真撮影をお願いされた）"
