[translation]
"1301306-1" = "本に包まれて"
"1301306-2" = "（モミジに招待されて、レッドウィンターの図書館に向かった）"
"1301306-3" = "図書館内部"
"1301306-4-モミジ" = "お待ちしてました、先生！"
"1301306-5" = "[s] \"あれ、他の利用者は？\""
"1301306-6-モミジ" = "あ、それが……今日は休館日なんです。"
"1301306-7-モミジ" = "休館日なのに先生を呼んだ理由、ですか……？"
"1301306-8-モミジ" = "……。"
"1301306-9-モミジ" = "とりあえず、奥に来てください！"
"1301306-10-モミジ" = "どうですか？外は寒かったですよね？"
"1301306-11" = "[s1] \"うん、ここは暖かいし居心地がいいね。\"\n[s2] \"それで、休館日に呼んでくれた理由は……？\""
"1301306-12-モミジ" = "そ、それは……！"
"1301306-13-モミジ" = "えっと……実は臨時休館にしたんです。"
"1301306-14-モミジ" = "こ、答えになってない……ですか？すみません。"
"1301306-15-モミジ" = "……先生。"
"1301306-16-モミジ" = "その……図書館でお昼寝をしてみませんか……？"
"1301306-17" = "[s] \"えっ、司書さんがそんなこと言っていいの！？\""
"1301306-18-モミジ" = "せ、説明させてください！"
"1301306-19-モミジ" = "時々……チェリノ会長や利用者の生徒が、図書館でお昼寝をしてるんです。"
"1301306-20-モミジ" = "その度に注意したり、追い出したりしていたんですが……"
"1301306-21-モミジ" = "……。"
"1301306-22-モミジ" = "図書館ってそんなに寝心地がいいのかな、と気になって試してみたら……"
"1301306-23" = "[s] \"思ってた以上に気持ち良かったんだね。\""
"1301306-24-モミジ" = "……はい。"
"1301306-25-モミジ" = "わざわざ休館日にした理由ですか……？"
"1301306-26-モミジ" = "そ、それは……！"
"1301306-27" = "[s] \"司書として、いつもは注意してる立場だもんね。\""
"1301306-28-モミジ" = "うう……！"
"1301306-29-モミジ" = "間違っては、いないんですが……"
"1301306-30-モミジ" = "やっぱり、変ですよね……ダメですよね。"
"1301306-31-モミジ" = "図書館の管理を任されている司書が、私用で臨時休館にしてしまうなんて……"
"1301306-32-モミジ" = "い、一応、このようにパーティーションで区切ってはおきました。"
"1301306-33-モミジ" = "他の学園には、図書館に仮眠室があると聞いたので、それなら私たちも、休館にして擬似的な仮眠室を作っちゃおうと思って……！"
"1301306-34-モミジ" = "……。"
"1301306-35-モミジ" = "ごめんなさい、先生……言い訳ばかり……"
"1301306-36" = "[s3] \"あ～、徹夜続きで眠くなってきたなぁ！\" \n[s4] \"図書館が温かいからかな？急に眠気が……\""
"1301306-37-モミジ" = "ほ、本当ですか！？"
"1301306-38-モミジ" = "……私に気を遣って、そう言ってくださったわけではなく？"
"1301306-39-モミジ" = "わ、笑ってないで返事してください、先生！恥ずかしいじゃないですか……！"
"1301306-40-モミジ" = "……。"
"1301306-41-モミジ" = "あの、先生。"
"1301306-42-モミジ" = "それでは……一緒にお昼寝、しましょう……？"
"1301306-43" = "[s] \"うん、すぐにでも眠っちゃいそうだよ。\""
"1301306-44-モミジ" = "えへへ……じゃあ、こちらへどうぞ。#nゆっくりお休みください。"
"1301306-45" = "（モミジの言う通り、とても寝心地が良く……）"
"1301306-46" = "（本の優しい香りに包まれながら、ゆっくりと眠りに落ちた）"
"1301306-47-モミジ" = "どうですか、先生？"
"1301306-48-モミジ" = "……もう寝息が……お疲れだったんですね。"
"1301306-49-モミジ" = "……。"
"1301306-50-モミジ" = "ねえ、先生。"
"1301306-51-モミジ" = "いつも、私に寄り添ってくださって……ありがとうございます。"
"1301306-52-モミジ" = "……おやすみなさい。"
