[translation]
"10041070-1" = "第7話;エピローグ"
"10041070-2-トキ" = "……ヴァルキューレへの引き渡し、完了しました。ミッションコンプリートです。ブイ。"
"10041070-3-アスナ" = "すごい数だったな……ミレニアムEXPOが中止になっていてもおかしくなかった。"
"10041070-4-アスナ" = "楽しかったね～！トリニティ生たちもみんな「これぞミレニアム！」とか言ってさ！"
"10041070-5-カリン" = "ミレニアムのイメージは、少し歪んだ気もするが……。"
"10041070-6-アカネ" = "それでも事態の規模に比べれば、この程度で片を付けたのは上出来だと思いますよ。"
"10041070-7-ネル" = "……あの会計からは？なんか言われなかったか？"
"10041070-8-アカネ" = "もちろんお怒りの様子ですが……結果的には上手くいきましたので。#n先生との合同作戦でもありましたし。"
"10041070-9-カリン" = "次からは可能な限りの情報共有を、と。先生には一言あるらしい。だがそれくらいだな。"
"10041070-10" = "[s1] \"結局怒られるのは私なんだね……。\"\n[s2] \"ふ、ふふ……怒られるのは慣れてるから大丈夫。\""
"10041070-11-カリン" = "ちなみに、私たちからも言いたいことがある。"
"10041070-12-カリン" = "セミナーはともかく、せめて私たちには言って欲しかった。トリニティのVIPと組む作戦だと。"
"10041070-13-カリン" = "それも知らずに私たちは……。"
"10041070-14-セイア" = "済まない、それは私の都合だ。ネルや先生が判断できるものではなかった。"
"10041070-15-セイア" = "私の我儘を聞いてくれただけに過ぎない。 "
"10041070-16-セイア" = "この場を借りて、謝罪させてくれ。"
"10041070-17-カリン" = "あ、いや……。"
"10041070-18-カリン" = "そ、そういうつもりで言ったわけでは……！"
"10041070-19-アカネ" = "ふふっ。すごいじゃないですか。ティーパーティーから謝罪の言葉をいただくなんて。"
"10041070-20-ネル" = "あたしからも……悪かったな。こっちも頼まれて仕方なかったんだよ。"
"10041070-21-ネル" = "この件はまた今度埋め合わせするからよ。そんな怒んなって。"
"10041070-22-カリン" = "いやっ、だからそんなつもりじゃなくて……！"
"10041070-23-セイア" = "……先生。"
"10041070-24" = "[s3] \"大丈夫？怪我はない？\"\n[s4] \"どうだった？大丈夫だった？\""
"10041070-25-セイア" = "……本当に全部知っているのだな。"
"10041070-26-セイア" = "証明するため、と心に決めていたはずが……。"
"10041070-27-セイア" = "……いや。先生がいなければ、最悪の結末を迎えていたはずだ。"
"10041070-28-セイア" = "ありがとう、先生。"
"10041070-29-セイア" = "それに……勝手をして済まなかった。"
"10041070-30" = "[s5] \"まだだよ！\"\n[s6] \"帰るまでもう少し待って。\""
"10041070-31-セイア" = "それは構わないが……"
"10041070-32-セイア" = "私よりも構うべき相手がいるのではないかね。"
"10041070-33-セイア" = "先生は……あの子の元に行ってやらなくていいのかい？"
"10041070-34-セイア" = "まだ遅くないはずだ。今頃は荷物をまとめているところだろう。"
"10041070-35-セイア" = "……大丈夫？ "
"10041070-36-セイア" = "そうか。意外だな。"
"10041070-37" = "[s7] \"まだ大丈夫。\"\n[s8] \"言葉にもタイミングがあるから。\""
"10041070-38-セイア" = "……そうか。"
"10041070-39" = "[s9] \"それより、セイアのことを考えてみない？\"\n[s10] \"なぜここに来たのか、もう少し考えてみよう。\""
"10041070-40-セイア" = "……？"
"10041070-41-セイア" = "……ああ。"
"10041070-42-セイア" = "そうだな。"
"10041070-43" = "（一時間後）"
"10041070-44-セイア" = "来たよ、リオ。"
"10041070-45-ネル" = "こっちも大まかな整理が終わったぜ。そっちは――"
"10041070-46-セイア" = "……もう帰るのか。"
"10041070-47-ネル" = "まあ……だろうよ。最初からそのつもりだったし。"
"10041070-48-セイア" = "そうか……。"
"10041070-49-ネル" = "……へぇ。"
"10041070-50-ネル" = "なんだ？そのしけたツラは。らしくねぇ。"
"10041070-51-セイア" = "……いや。"
"10041070-52-セイア" = "……そうだな。正直残念に思う。"
"10041070-53-セイア" = "ただ……どこか気持ちが冴えない。そんなところだろうか。"
"10041070-54-ネル" = "冴えない？"
"10041070-55-セイア" = "ああ。私は……"
"10041070-56-セイア" = "リオが口にしていた「証明」について。実のところ必要ないと思っている。"
"10041070-57-セイア" = "本人こそ気づいてないものの、すでに周りは……"
"10041070-58-セイア" = "……？"
"10041070-59-ネル" = "……？何だよ！また言いかけてやめんのかよ！"
"10041070-60-セイア" = "すでに周りは、彼女のことを受け入れている。"
"10041070-61-セイア" = "受け入れられないのは……彼女自身だけだ。"
"10041070-62-セイア" = "……そうか。"
"10041070-63-セイア" = "……それで先生は、あの言葉を。"
"10041070-64-ネル" = "今度は自問自答かよ？リオに似てきてねえか？マジでイライラしてくるから勘弁してくれ。"
"10041070-65-セイア" = "……すまない。悪いクセでね。"
"10041070-66-セイア" = "……それより。"
"10041070-67-セイア" = "ネル、よければ最後にもう一つだけ、助力を乞いたい。"
"10041070-68-ネル" = "あん？なんだ？"
"10041070-69-セイア" = "それは……。"
"10041070-70-セイア" = "リオ、君に話がある。"
"10041070-71-リオ" = "何かしら？"
"10041070-72-セイア" = "もう1週間ほど、ミレニアムに逗留して欲しいのだよ。"
"10041070-73-セイア" = "私やネルも残る。"
"10041070-74-セイア" = "君が守り抜いたイベントを見届けてはくれまいか。"
"10041070-75-リオ" = "何を言うかと思えば……。"
"10041070-76-リオ" = "それは無理よ、終わった話だわ。私にEXPOを楽しむ資格など無いもの。"
"10041070-77-セイア" = "……これは資格の話ではない。"
"10041070-78-リオ" = "どういう意味かしら。"
"10041070-79-セイア" = "君はすべて無事に解決したと思っているようだが、EXPOはまだ一日目だ。"
"10041070-80-セイア" = "今後も問題に見舞われないという保証はない。大小に差こそあれ、何かしらは起きるだろう。"
"10041070-81-セイア" = "そのほとんどは、つつがなくセミナーが処理するはずだ。けれど全部がそうとは限らない。"
"10041070-82-セイア" = "往々にして、例外は発生しうるものだ。"
"10041070-83-セイア" = "君ができないと言うなら、結局はセミナーや……それこそ先生が担うのだろうが。"
"10041070-84-セイア" = "果たして、それを望むのかな？"
"10041070-85-リオ" = "それは……。"
"10041070-86-リオ" = "……どう思う？ネル。"
"10041070-87-ネル" = "あたしに振んのか？"
"10041070-88-ネル" = "ま、いいんじゃん？堂々と出歩かなければバレないだろ。"
"10041070-89-ネル" = "これも生徒会長としての仕事ってやつなんじゃねえの？知らねえけど。"
"10041070-90-リオ" = "はぁ……。"
"10041070-91-リオ" = "なんだか、乗せられている気がするけれど。"
"10041070-92-セイア" = "それは違う。"
"10041070-93-ネル" = "嫌なら無理強いはできねえよな。"
"10041070-94-リオ" = "い、いえ……嫌とは言ってないわ。"
"10041070-95-リオ" = "そう、ね……"
"10041070-96-リオ" = "ええ、わかったわ。"
"10041070-97-リオ" = "1週間だけ――イベントが終わればすぐに帰る。"
"10041070-98-セイア" = "それで十分だ。私たちも力を貸そう。"
"10041070-99-リオ" = "……荷を解いてくるわ。"
"10041070-100-セイア" = "……うまくいったようだ。"
"10041070-101-ネル" = "ハハッ！なかなかのやり手じゃんか。やっぱ今回の件で仲良くなったんだろ？"
"10041070-102-セイア" = "そうとも言えるだろうか。"
"10041070-103-セイア" = "彼女は、何かにかこつけないと納得できないタイプだ。"
"10041070-104-セイア" = "誰よりもよく知っている……鏡越しで見てきたのだからね。"
"10041070-105-ネル" = "ほんっと、めんどくせえ奴だよ。"
"10041070-106-セイア" = "……ふふ。"
"10041070-107-セイア" = "そうだな。"
"10041070-108-セイア" = "……めんどうなタイプさ。"
"10041070-109" = "Code:BOX　ミレニアムに迫る影"
