[translation]
"10041080-1" = "後日談;スポンサー"
"10041080-2-ヘルメット団員A" = "はあ……結局こうなるのか。"
"10041080-3-ヘルメット団員B" = "どこに送られるんだ？やっぱ矯正局？"
"10041080-4-ヘルメット団員A" = "多分ね。聞いた感じそうだったよ。"
"10041080-5-ミライ" = "はぁぁ……。"
"10041080-6-ヘルメット団員A" = "すげーため息。"
"10041080-7-ヘルメット団員A" = "まあまあそんな落ち込むなって。あのC&C相手じゃ仕方ないだろ。私たちじゃ無理だって。"
"10041080-8-ミライ" = "いえ、そういう意味ではなかったのですが……。"
"10041080-9-ヘルメット団員A" = "にしても見直したよ。正直、美甘ネルに捕まった時は見捨てられると思った。"
"10041080-10-ミライ" = "……え？"
"10041080-11-ヘルメット団員B" = "そうそう！本当ビックリ！"
"10041080-12-ヘルメット団員B" = "雇い主に裏切られないとか、いつぶり？また今度なんかあったら呼んでくれよな！"
"10041080-13-ミライ" = "そう、ですか……はは。いい印象だったならよかったです。"
"10041080-14-ミライ" = "それに対し、こちらの雇い主は……。"
"10041080-15-ヘルメット団員B" = "ん？雇い主？"
"10041080-16-ヘルメット団員A" = "あ、そういやそっちもスポンサーがいるとか言ってたよな？そんな変わらない立場か。"
"10041080-17-ミライ" = "はい。どんな人かはよく分かっていませんが、私の目的に力を貸すと言われ従っているだけです。"
"10041080-18-ミライ" = "ですが……どうやら見捨てられたようですね。"
"10041080-19-ヘルメット団員A" = "えっ……？"
"10041080-20" = "おっと……。"
"10041080-21-ミライ" = "大丈夫です。分かっていたことなので。ビジネスの関係ってそういうものですし。"
"10041080-22-ミライ" = "それに私も任務を失敗したので……とやかく言える立場じゃありません。"
"10041080-23-？？？" = "誰が見捨てたと言うのです？"
"10041080-24-ミライ" = "……ん？"
"10041080-25-ヘルメット団員B" = "あれ？何だ……？何か聞こえなかったか？"
"10041080-26-ヘルメット団員B" = "だよな……？"
"10041080-27-ヘルメット団員B" = "ドアが開いた……！？"
"10041080-28-ミライ" = "ここは……。"
"10041080-29-ヘルメット団員A" = "……地下？"
"10041080-30-？？？" = "「安全な場所」ですよ。皆さんを助けるべく、特別にご用意しました。"
"10041080-31-ヘルメット団員B" = "……！？この声は……。"
"10041080-32-ミライ" = "……雇い主ですね。"
"10041080-33-ヘルメット団員A" = "え……！？"
"10041080-34-ニヤニヤ教授" = "まったく、寂しいものです。契約相手を見捨てると思われるなんて。"
"10041080-35-ニヤニヤ教授" = "もちろん他の方を誘導することもありますが……それなりに責任は負いますよ？"
"10041080-36-ミライ" = "……あなたが。"
"10041080-37-ニヤニヤ教授" = "ええ、「ニヤニヤ教授」と申します。"
"10041080-38-ミライ" = "実際にお会いするのは初めてですね。"
"10041080-39-ニヤニヤ教授" = "おや、緊張されてますか？もう少し信用してくださってもいいと思いますよ。矯正局行きを止めてあげたのに。"
"10041080-40-ミライ" = "そうですね……でも、だからこそ意外といいますか。だって私は任務を失敗したのですよ。"
"10041080-41-ニヤニヤ教授" = "失敗……？"
"10041080-42-ニヤニヤ教授" = "ほむ……認識のズレがあったようですね？"
"10041080-43-ミライ" = "認識のズレ……？"
"10041080-44-ニヤニヤ教授" = "ご心配なく。あなたは十分にやってくれました。これだってそのご褒美なのですよ？"
"10041080-45-ミライ" = "……？"
"10041080-46-ミライ" = "それはどういう……？ハナから別の狙いがあったと？"
"10041080-47-ニヤニヤ教授" = "……ふふ。それについては伏せておきましょう。今皆さんにやっていただいていることとは関係ありませんから。"
"10041080-48-ニヤニヤ教授" = "とにかく、楽しいお時間でしたよ。"
"10041080-49-ニヤニヤ教授" = "所用のため失礼しますね。では、お足元に気を付けて。"
"10041080-50-ヘルメット団員B" = "な……"
"10041080-51-ヘルメット団員A" = "何者だ、あいつ？"
