[translation]
"1012102-1" = "海の正装ですの！"
"1012102-2-ユカリ" = "[ruby=かでのこうじ]勘解由小路[/ruby]ユカリ！参上ですの！"
"1012102-3-ユカリ" = "おや……？#n机の上が書類でいっぱい……。"
"1012102-4-ユカリ" = "もしや……今日は特別お忙しい日でしたか……！？"
"1012102-5" = "[s1] \"生徒の相談はいつでも歓迎だよ！\"\n[s2] \"ちょうど休憩しようと思ってたところだし。\""
"1012102-6-ユカリ" = "なるほど……ないすたいみんぐ！ですの！"
"1012102-7-ユカリ" = "お邪魔になっていたらどうしようかと……#n思い過ごしでよかったですわ！"
"1012102-8-ユカリ" = "……では、改めて。"
"1012102-9" = "[s3] \"琵琶と舞で悩んでるんだっけ？\"\n[s4] \"……海に行くんだよね？\""
"1012102-10-ユカリ" = "ふふっ。身共、勘解由小路家の者として、#n最低限の教養は叩き込まれてきましたから。"
"1012102-11-ユカリ" = "当然、海での遊び方も心得ております！"
"1012102-12" = "[s] \"なるほど……？\""
"1012102-13-ユカリ" = "小舟を出して潮風を愛でつつ、海の幸に舌鼓を打ち……。#n波の音に耳を傾けながら静かに時を過ごす――"
"1012102-14-ユカリ" = "海で遊ぶとはこういうことですのよね！"
"1012102-15-ユカリ" = "……あら？"
"1012102-16-ユカリ" = "多少の違いこそあれ、毎年このような流れであったはず……。#n身共、何やら勘違いしておりますか？"
"1012102-17-ユカリ" = "はい？いえ。百花繚乱の先輩方からは特に伺っておらず……。"
"1012102-18-ユカリ" = "もしや先生、すでに何かお気づきですの？"
"1012102-19-ユカリ" = "なんと！ぜひとも身共にご教示いただけませんか？"
"1012102-20-ユカリ" = "何を着ていくつもりだったのか……#nそれはもちろん、着物を――"
"1012102-21-ユカリ" = "先生？急にどちらへ……？"
"1012102-22-ユカリ" = "ここは……ぶてぃっく、ですの？"
"1012102-23-ユカリ" = "水着？いえ、用意はしておりません。"
"1012102-24-ユカリ" = "ふふっ、おかしな事を仰るのですね。#nまるで、これから水に入るかのような――"
"1012102-25-ユカリ" = "……え？"
"1012102-26-ユカリ" = "入りますの？"
"1012102-27-ユカリ" = "海に……！？"
"1012102-28" = "[s5] \"あれ、海水浴は苦手？\"\n[s6] \"泳いだことなかったりする？\""
"1012102-29-ユカリ" = "より一層、楽しみになってまいりました！"
"1012102-30-ユカリ" = "海で泳ぐ！#nであればたしかに、水着が必要ですの！"
"1012102-31-ユカリ" = "……。"
"1012102-32-ユカリ" = "して、水着はどちらに？"
"1012102-33-ユカリ" = "好きなものを選べばいい……？"
"1012102-34-ユカリ" = "ここに並ぶもの、すべてが水着……！？"
"1012102-35-ユカリ" = "まったく気づきませんでしたわ！#nこれほど、ばらえてぃ豊かだなんて！"
"1012102-36-ユカリ" = "この中から一着……目移りしてしまいます……。"
"1012102-37-ユカリ" = "ふふん～ふふっん～♪#nど～れに～いたしましょう？"
"1012102-38-ユカリ" = "こちらの水着、ふりるがついておりますの！"
"1012102-39-ユカリ" = "こちらは艶やかで、まるで紙細工のような美しさ！"
"1012102-40-ユカリ" = "そして、こちらは……。"
"1012102-41-ユカリ" = "こちらは……本当に水着ですの……？"
"1012102-42-ユカリ" = "先生、助けてくださいまし！#nどれも素敵で一つになど絞れません！"
"1012102-43" = "（しばらく悩んだ末、ユカリはついに一着の水着を選び取った）"
"1012102-44-ユカリ" = "先生……？#n着替え終わったのですが……。"
"1012102-45-ユカリ" = "正しく着こなせておりますでしょうか……？"
"1012102-46-ユカリ" = "少々、布が……少ないような……？"
"1012102-47-ユカリ" = "皆さん、こういったものを着て、海を楽しんでおられるのですね……。"
"1012102-48-ユカリ" = "ですが、これはこれで気に入りましたわ！"
"1012102-49-ユカリ" = "普段の装束を思えば、なんと動きやすいことでしょう！#nまるで身共に翼が生えたかのようですの！ふふっ♪"
"1012102-50-ユカリ" = "身共、妙案を思いつきましたの！"
"1012102-51-ユカリ" = "着慣れていないならば、慣れるまで着続ければいいだけのこと！"
"1012102-52-ユカリ" = "つまり、本日はこのまま街を――！"
"1012102-53" = "[s7] \"私はユカリを信じてたのに！\"\n[s8] \"街歩きに水着は不適切です！\""
"1012102-54-ユカリ" = "そ、そうなんですの……？"
"1012102-55-ユカリ" = "……。"
"1012102-56-ユカリ" = "完璧に理解いたしました！"
"1012102-57-ユカリ" = "たしかに、街中を水着で歩いている方はいらっしゃいません！"
"1012102-58-ユカリ" = "名残惜しいですが、本日の「水着たいむ」はここまで、ということで。"
"1012102-59" = "（その後、帰り道のユカリはずっと楽しそうにしていた）"
