[translation]
"2005305-1" = "忍者少女は秘訣が知りたい！"
"2005305-2" = "説明会会場"
"2005305-3" = "（ミチルが心配になって……）"
"2005305-4" = "（同席することに決めた）"
"2005305-5-ミチル" = "あっ、先生殿ーっ！#nこっちこっちー！"
"2005305-6-ミチル" = "……ん？"
"2005305-7-ミチル" = "いやいや、先に行ったりなんかしないって。"
"2005305-8-ミチル" = "……あ、これ？"
"2005305-9-ミチル" = "いや、ちゃんとした格好のほうが良いのかな～って……。"
"2005305-10-ミチル" = "ほらほら、周りをよく見て。"
"2005305-11-ミチル" = "ここは、選ばれし者が秘訣を伝授される場……！"
"2005305-12-ミチル" = "なら、それに見合う格好で来るのが礼儀！"
"2005305-13-ミチル" = "だから、ドレスを引っ張り出してきたーってわけ！#nふっふっふ……！"
"2005305-14-ミチル" = "ほら、あの人たちもスーツとかドレスでしょー？"
"2005305-15" = "[s] \"確かに……？\""
"2005305-16" = "（そう簡単に、秘訣を教えてくれるとは思わないけど……）"
"2005305-17" = "（ひとまず、ミチルに付いていった）"
"2005305-18" = "[ns] \"ところで、この説明会はどうやって知ったの？\""
"2005305-19-ミチル" = "えーっとね、ちょっと前に動画を見てたらー……。"
"2005305-20-ミチル" = "画面に広告が出てきたの。"
"2005305-21-ミチル" = "それが、この説明会！"
"2005305-22" = "[s] \"ど、動画広告……。\""
"2005305-23-ミチル" = "すごいんだよー、びっくりしちゃった！"
"2005305-24-ミチル" = "どうしたらチャンネルが伸びるのかなーって悩んで、色々検索してたら……。"
"2005305-25-ミチル" = "そのすぐ後に！"
"2005305-26-ミチル" = "ババーンってここの広告が出てきたの！"
"2005305-27-ミチル" = "まるで私に、悩みの答えを教えてくれるみたいに！"
"2005305-28-ミチル" = "それでビビッと来たの！#nこれが運命なんだって！"
"2005305-29" = "[s] \"や、やっぱり……。\""
"2005305-30-ミチル" = "あーっ、信じてない！？"
"2005305-31-ミチル" = "とにかく、始まるから中に入ろっ！"
"2005305-32" = "会場の中"
"2005305-33-怪しげな司会" = "皆さん、本日はお越しいただきありがとうございます。"
"2005305-34-怪しげな司会" = "ここへ来場されたということは、共通してある悩みをお抱えのことでしょう？"
"2005305-35-怪しげな司会" = "どうすれば再生数が伸びるのか、どうすれば登録者を増やせるのか……。"
"2005305-36-怪しげな司会" = "……その悩みは、今日ここで解決してしまいましょう！"
"2005305-37-ミチル" = "やっぱり……！"
"2005305-38-ミチル" = "全てが見抜かれている……！"
"2005305-39" = "[s] \"……。\""
"2005305-40-怪しげな司会" = "心配は要りません。"
"2005305-41-怪しげな司会" = "皆さんが望む再生数も、登録者数も……。 "
"2005305-42-怪しげな司会" = "私たちの会社が、バッチリ保証いたします！"
"2005305-43-ミチル" = "……ん？"
"2005305-44-怪しげな司会" = "100万円さえお支払いいただければ、#n皆さんの動画の平均再生数を100万回まで引き上げましょう！"
"2005305-45-怪しげな司会" = "そしてなんと今なら、登録者数100万人のおまけ付きです！"
"2005305-46-ミチル" = "んん……！？"
"2005305-47-怪しげな司会" = "不安に思う方もいるかもしれませんが、ご安心ください。"
"2005305-48-怪しげな司会" = "我々はキヴォトスクラッカー協会に認定された、#n安全なマクロプログラムを使用しております！"
"2005305-49-ミチル" = "た、ただの違法ツールじゃん……！"
"2005305-50-ミチル" = "先生殿、ごめん……私が間違ってたみたい……。"
"2005305-51-ミチル" = "真っ当な方法で増やせると思ったのにぃ……。"
"2005305-52-ミチル" = "……ただの詐欺だったなんて。"
"2005305-53-ミチル" = "行こ、先生殿。"
"2005305-54-ミチル" = "……ん？"
"2005305-55-怪しげなスタッフ" = "どうされましたか？"
"2005305-56-怪しげなスタッフ" = "説明会はまだ途中ですが……。"
"2005305-57-ミチル" = "えっと、もう帰ろうかなーって……。"
"2005305-58-怪しげなスタッフ" = "ふむ……それは少々困りますねぇ。"
"2005305-59-怪しげなスタッフ" = "規約上、途中退室は禁止しておりまして……。"
"2005305-60" = "[ns] \"すみません、少し気になったんですが……。\""
"2005305-61-ミチル" = "はい、何でしょう？"
"2005305-62-怪しげなスタッフ" = "も、もしかしてあなたは、シャーレの……？"
"2005305-63-怪しげなスタッフ" = "しししし失礼しましたぁ！#n気をつけてお帰りくださいっ！"
"2005305-64" = "[ns] \"行こっか、ミチル。\""
"2005305-65-ミチル" = "う、うんっ！"
"2005305-66" = "（こうして、ミチルと会場を後にした）"
"2005305-67" = "近くの公園"
"2005305-68-ミチル" = "うぅぅ、恥ずかし～……。"
"2005305-69-ミチル" = "あんな詐欺に騙されるとこだったぁ……。"
"2005305-70-ミチル" = "というか先生殿、もしかして……。"
"2005305-71-ミチル" = "最初から気づいてた、とか？"
"2005305-72" = "[s] \"ある程度だけどね。\""
"2005305-73-ミチル" = "うぅぅぅ……ひどいよぉ、先生殿……！"
"2005305-74" = "[s] \"ええっ！？\""
"2005305-75-ミチル" = "も、もちろん釣られた私が悪いんだけどぉ……！"
"2005305-76-ミチル" = "それなら教えてくれたって……！"
"2005305-77" = "[s] \"時には失敗も、大事な経験になるからね。\""
"2005305-78-ミチル" = "……？"
"2005305-79" = "[s1] \"もし説明会に行かなかくても、頭のどこかで気になってただろうし。\"\n[s2] \"でも、実際に行ったおかげでスッキリしたでしょ？\""
"2005305-80-ミチル" = "……た、たしかに。"
"2005305-81-ミチル" = "これで同じ失敗はしないだろうし……。"
"2005305-82-ミチル" = "うん、やっぱ先生殿には感謝しなくっちゃ！"
"2005305-83-ミチル" = "それに、踏ん切りがついたし。"
"2005305-84-ミチル" = "怪しいものには頼らず、自分の力でチャンネルを大きくしてみせる……！"
"2005305-85-ミチル" = "だからこれからも見守っててね、先生殿！"
"2005305-86" = "（ミチルを家に送ってからシャーレに戻り……）"
"2005305-87" = "（ヴァルキューレに説明会の件を通報した） "
