[translation]
"103080-1" = "第8話;ブリーフィング"
"103080-2-モモカ" = "はい、これ。作戦計画書。 "
"103080-3-アユム" = "皆さんに協力していただいて、作成したものです。"
"103080-4-リン" = "作戦名は――「アトラ・ハシースの箱舟占領戦」。"
"103080-5-リン" = "……おそらく、これが最後の作戦となるでしょう。"
"103080-6-アヤネ" = "さ、最後……"
"103080-7-カヨコ" = "成功したらサンクトゥムは作られないわけだし、#n失敗したらキヴォトスは終わる……。"
"103080-8-ハナコ" = "そうですね、いずれにしても最後の作戦になります。"
"103080-9-アコ" = "成功させればいいだけの話ですよね！？#n不安を煽るような事を言わないでください、カヨコさん！"
"103080-10-ユウカ" = "それに、専門家が集まって検証したんでしょ？"
"103080-11-ユウカ" = "これ以上ない、完璧な作戦のはずよ。"
"103080-12-リン" = "……では、作戦の説明に移ります。 "
"103080-13-リン" = "私たちの目標は、キヴォトス上空にある「アトラ・ハシースの箱舟を破壊する」こと。"
"103080-14-モモカ" = "無事破壊できたら、「虚妄のサンクトゥム」の出現を阻止できるよ～"
"103080-15-リン" = "しかし、箱舟は物理的な介入を無効化する「状態の共存」によるバリアで保護されています。"
"103080-16-リン" = "このバリアが存在する以上、箱舟に対しての物理的なアプローチは不可能とされていました――ですが、"
"103080-17-リン" = "「ウトナピシュティムの本船」を同様の状態にすれば、理論上はバリアを通過する事が可能です。"
"103080-18-モモカ" = "要は、相手と同じ存在になったら、干渉できるって事～"
"103080-19-小型AMAS" = "そのための計算は、私がこの船の演算装置を用いて進行する予定です。"
"103080-20-カヨコ" = "……計算に失敗したら？"
"103080-21-小型AMAS" = "そうですね……万が一、計算に失敗した状態でバリアが展開されている空間に進入した場合――"
"103080-22-ヒマリ" = "運が悪ければ原子単位でバラバラに、運が良い場合でも、船から弾き出されて地上75,000mの高さから墜落することになります。"
"103080-23-アコ" = "そ、その高さからの自由落下……流石にヘイローが壊れてしまうのでは……"
"103080-24-カヨコ" = "いや、その前に肉体が耐えきれないと思うよ。"
"103080-25-カヨコ" = "高度75,000mもあればマイナス60度は優に超える。#n呼吸をしたら肺が凍るだろうから。"
"103080-26-カヨコ" = "体液も一瞬で気化するだろうし……#nどのみち、その環境下じゃ2分足らずでヘイローは壊れる。"
"103080-27-アコ" = "あ、ありがとうございます、カヨコさん。#nと～っても、参考に……なります。"
"103080-28-リン" = "――続けます。失敗の想定をしたところで、不毛ですので。 "
"103080-29-リン" = "バリア通過後、箱舟に物理的な衝撃を与え――内部に侵入します。"
"103080-30-リン" = "無事に侵入できたら、主要施設のハッキングを行い、 これ以上作動しないよう徹底的に破壊します。"
"103080-31-リン" = "もちろん、箱舟内にいる敵から抵抗を受けるでしょう。"
"103080-32-リン" = "攻撃を防ぎつつ、箱舟の各エリアを少しずつ[ruby=ハッキング]占領[/ruby]、最終的に箱舟の制御権を奪う――それがこの作戦の最終目標です。"
"103080-33-小型AMAS" = "……制御権を掌握したら、箱舟自体を自爆もしくは、地上に墜落させることが可能になるでしょう。"
"103080-34-小型AMAS" = "ええ……箱舟をハッキングし、奪う――それが私たちの勝利条件。"
"103080-35-アコ" = "ご説明くださりありがとうございます。目標は至極シンプルですね。"
"103080-36-アコ" = "ところで――"
"103080-37-ヒマリ" = "……えっと、私はサポート型AMASで――"
"103080-38-ユウカ" = "リオ会長～～！？"
"103080-39-ヒマリ" = "……一瞬でバレましたね。"
"103080-40-ユウカ" = "急に行方を眩ませて、一体どこに行ったのかと思ったら……#nこんな所に！？というか、今本体はどこで何してるんですか！？"
"103080-41-ヒマリ" = "そ、それは…… "
"103080-42-ユウカ" = "……ここには、アリスちゃんとゲーム開発部がいるんですよ。#n一体何のつもりですか？"
"103080-43-ヒマリ" = "……リオは私を手伝ってくれているだけですよ。 "
"103080-44-ヒマリ" = "私が監視しておりますからご心配なく。#n少しでも不審な動きがあれば、すぐに破壊しますので。"
"103080-45-ユウカ" = "はぁ……"
"103080-46-ユウカ" = "何を企んでるのかは知らないですけど、絶対ゲーム開発部には近づかないでくださいね！"
"103080-47-ユウカ" = "会長に言いたいことは山ほどあるけど……#nそうね……後であの横領の件から、事細かくお話を聞かせてもらいますからね！"
"103080-48-小型AMAS" = "……分かったわ。"
"103080-49-小型AMAS" = "万が一の場合に備えて、地上に戻る方法を探してみるわ。#n……もちろん、許可してくれるのなら、だけど。"
"103080-50-ヒマリ" = "そうですね、お願いします。#n船が壊れてしまった場合、私たちは箱舟に閉じ込められますので。"
"103080-51-小型AMAS" = "――では、すぐに取りかかるわ。"
"103080-52-リン" = "アユム、私たちに残された時間は？"
"103080-53-アユム" = "えっと、サンクトゥムの再出現まで……約12時間と予想されています。"
"103080-54-モモカ" = "うう～っ……それまでに箱舟を占領しなきゃいけないんだよね？"
"103080-55-モモカ" = "言いたかないけど……これって本当に実現できる作戦なんだよね？"
"103080-56-ヒマリ" = "はい。何度もシミュレートした結果、成功確率は――"
"103080-57-ヒマリ" = "なんと、3%もあります。"
"103080-58-モモカ" = "さん、パーセント……？ "
"103080-59-ハナコ" = "……奇跡みたいな確率を味方にするしかありませんね。"
"103080-60" = "[s] \"それでも、やる価値は十分あると思うよ。\""
"103080-61-リン" = "……はい、先生のおっしゃる通りです。 "
"103080-62-リン" = "キヴォトスに到来した未曾有の事態……私たちは、不可解な問題に立ち向かい――そうして、ここまで至ったのです。"
"103080-63-リン" = "最初の兆候だった、[ruby=ゆりぞの]百合園[/ruby]セイアの「予言」。"
"103080-64-リン" = "そして、6つの超高濃度エネルギーが探知されましたが、当初は目に見えない不可解な現象でしかありませんでした。"
"103080-65-リン" = "続いて出現した「虚妄のサンクトゥム」は、今までのキヴォトスで発生した全ての「神秘」を集結させて、攻撃してきました。"
"103080-66-リン" = "制御不能のAI「デカグラマトン」、記憶を再現するという「[ruby=ミメシス]複製[/ruby]」、「名もなき神」という名の超古代技術―― "
"103080-67-リン" = "――そして、生徒の存在を歪曲させる「色彩」。"
"103080-68-リン" = "連合作戦で守護者を攻略し、全サンクトゥムの破壊に成功したものの……"
"103080-69-リン" = "今、再び最初と同様にサンクトゥムが発生しようとしている……けれど、今度は指を咥えて見ているだけではありません。私たちは、その解決法に至ったのです。"
"103080-70-リン" = "――今までに起きた現象に、何ひとつ解明できているものなどありません。"
"103080-71-リン" = "予言、デカグラマトン、[ruby=ミメシス]複製[/ruby]、色彩、名もなき神、Divi:Sion、虚妄のサンクトゥム、守護者――そして、色彩の嚮導者であるプレナパテス……"
"103080-72-リン" = "成功率が3%だろうと構いません。#n私たちは、今まで通り作戦を遂行するしかないのです。"
"103080-73" = "[s] \"そうだね。みんなで力を合わせて、やってみよう。\" "
"103080-74-ハナコ" = "……そうですね。#nこれ以外に方法がないのですから、最初から選択肢は存在していません。"
"103080-75-ユウカ" = "ええ、そうね……"
"103080-76-アヤネ" = "……はい。シロコ先輩を連れ戻すためにも。"
"103080-77-アコ" = "はぁ……やるしかないよね。"
"103080-78-アコ" = "そうですね……ここまで来て、他の道はありません。"
"103080-79-リン" = "それでは「ウトナピシュティムの本船」を8時間以内に発進できるよう、準備をお願いします。"
"103080-80-モモカ" = "えっ、ちょっと待って！#n出発って8時間後！？ "
"103080-81-リン" = "マニュアルはありますので。これを覚えていただきます。"
"103080-82-モモカ" = "いやいやいや、こんな分厚いマニュアルを数時間で覚えろだなんて無茶だよ！？"
"103080-83-リン" = "できるできないの問題ではなく、[ruby=・   ・   ・   ・   ・   ・   ・   ・   ・   ・]やらなければならない[/ruby]のです。#nマニュアルを把握し終えた方にオペレーターをお願いします。"
"103080-84-モモカ" = "はぁ……っていうか、オペレーターって最低10人は必要だよね……"
"103080-85" = "[s] \"じゃあ、私が総責任者になるよ。\""
"103080-86-モモカ" = "えっ、先生が？"
"103080-87" = "[s] \"シッテムの箱があるから、きっとなんとかなるよ。\""
"103080-88-リン" = "……私も先生をサポートします。"
"103080-89-アユム" = "り、リン先輩？"
"103080-90-リン" = "ここまで来たのですから、私も最後までご一緒します。#n一番危険な部分を先生だけに負担させるのは、忍びないので。"
"103080-91" = "[s] \"リン、ありがとう。すごく頼りにしてる。\""
"103080-92-アユム" = "ま、マニュアルを覚えるだけで良いのでしたら、#n私でもなんとかなりそうです……"
"103080-93-モモカ" = "アユム先輩まで！？"
"103080-94-ユウカ" = "まあ、先生がそう言うのなら、私が降りるわけにはいかないわね。#n私もやるわ。"
"103080-95-ハナコ" = "私もご一緒します。#nええ、覚えるのは得意なんです。色々と……♡"
"103080-96-アコ" = "はぁ……ゲヘナ風紀委員会の行政官である私が、責務を放棄するわけにはいきません。"
"103080-97-アコ" = "私もやりますよ。"
"103080-98-アヤネ" = "私も、ご一緒させてください！ "
"103080-99-アヤネ" = "怖くないと言ったら嘘になりますが……"
"103080-100-アヤネ" = "シロコ先輩を、助けに行きたいので。"
"103080-101-カヨコ" = "そういうつもりでここに来たんじゃないんだけど、はぁ……#nこの流れで帰るなんて、できなさそうだし。私もやるよ。"
"103080-102-モモカ" = "うわぁ……みんなやる気満々だね。"
"103080-103-モモカ" = "あ、ちなみに私は無理だからね？"
"103080-104-アユム" = "モモカちゃん……ここまで来たのに、私たちと別行動を……？"
"103080-105-アユム" = "以前、「宇宙の果てまでついていくよ」と言ってくれたのに……"
"103080-106-モモカ" = "わ、わわわっ！そんな顔しないでよアユム先輩！？ "
"103080-107-モモカ" = "……分かった、分かったってば！"
"103080-108-モモカ" = "やるから！#nまぁ……なんとか、なるよね……？"
"103080-109-ハナコ" = "ふふっ、宇宙戦艦の乗務員だなんて、良い響きですね♡"
"103080-110-ハナコ" = "ところで、コスチュームはあるんですか？"
"103080-111-アヤネ" = "こ、コスチューム……？"
"103080-112-ハナコ" = "あら。だって宇宙戦艦の乗務員ですよね？#n専用の衣装があるのでは？ "
"103080-113-ユウカ" = "ま、待って。専用衣装……？"
"103080-114-ヒビキ" = "うん、それは用意できると思う。"
"103080-115" = "なっ、ヒビキ！？#nそれを用意する時間があるのかい？"
"103080-116-ヒビキ" = "だって宇宙戦艦の乗務員だよね。"
"103080-117-ヒビキ" = "できるできないじゃない……"
"103080-118-ヒビキ" = "やるしかないよ。 "
"103080-119-コトリ" = "ええ！エンジニア部のロマンを裏切るわけにはいきませんからね！「発進！」とか、「高度上昇！」とか、「エネルギーチャージ！」とか、そういった台詞を言うのに、普段の制服ではカッコ悪いじゃありませんか！"
"103080-120-ウタハ" = "……それもそうだね。"
"103080-121-ウタハ" = "よし、ひと仕事しようじゃあないか。"
"103080-122-コトリ" = "はい！私も資料を探してみます！#nマンガやアニメにたくさん出てきますからね！"
"103080-123-ヒビキ" = "うん。じゃあ私は早速制作に入るね。まずはみんなのサイズ測定から――"
"103080-124-ハナコ" = "あらあら、まぁまぁ♡……とっても楽しみです。#nところで、デザインについてなんですが、よろしければ私と熱い議論を交わしませんか？"
"103080-125-ヒマリ" = "では、私はその衣装に機能を追加してパイロットスーツ風に改造するとしましょうか♪"
"103080-126-アユム" = "先生からも何か、ご意見ありますか？"
"103080-127" = "[s] \"はいはーい、あります！！やっぱり宇宙戦艦といえば――\""
"103080-128-アコ" = "一気に不安になってきますね……"
"103080-129" = "[ns1] \"やっぱり制帽だよね！！\"\n[ns2] \"定番だけどスカーフは外せない！！\"\n[ns3] \"やっぱ艦長はロングコートだよね！！\""
"103080-130-アヤネ" = "お、思ったより具体的ですね……"
"103080-131-ヒビキ" = "なるほどね。一応参考にはしておく。"
"103080-132-カヨコ" = "（何でこんなことになったんだか……）"
"103080-133-モモカ" = "ふぅ、大体まとまったね。 "
"103080-134-モモカ" = "それじゃ、今から発進準備を始めて、#n8時間後には「箱舟」に向かって出発って事で。"
"103080-135-アユム" = "オペレーター、航空管制担当、ハッキング担当……#n調理担当に治療担当……"
"103080-136-モモカ" = "うん。他にも、占領戦で実際に戦ってくれる生徒も集めないと。#nはぁ、やることが山積みだよ～"
"103080-137-アユム" = "……リン先輩、"
"103080-138-アユム" = "先輩はもちろん、先生、そしてシャーレの生徒の皆さんがここまで休まずに駆け抜けて来ました。"
"103080-139-アユム" = "ですが、今は作戦開始まで時間があります。#nこの機会に、少しでも休息をとってはいかがでしょうか？リン先輩は、特に……"
"103080-140-リン" = "……そうですね。"
"103080-141-リン" = "寝不足では判断が鈍る事もあるでしょう……#n今後の作戦に影響が出ないよう、お言葉に甘えさせていただきます。"
"103080-142-リン" = "それでは皆さん。#nこれより8時間後、夜明けと共に出発といたします。 "
"103080-143-リン" = "それまでに……できる限り各自、休息を取るようにしてください。"
"103080-144-リン" = "では、解散します。"
"103080-145" = "次回;地上最後の夜"
