[translation]
"10017070-1" = "第７話;嵐ノ丘"
"10017070-2" = "カフェ「White&Mason」入口"
"10017070-3-チンピラA" = "ちっ、やっぱりきついな……！"
"10017070-4-チンピラB" = "とはいえ、あいつらもほぼ限界だ！#nこのまま押し切れる！"
"10017070-5-ハナエ" = "な、何がどうなっているんですか！？"
"10017070-6-チンピラA" = "ははっ、知りたいか！？"
"10017070-7-チンピラB" = "なら答えてやるのが世の情けってな！#nまあ簡単なことだ！正義実現委員会は、私たちの「チキン」を奪った！"
"10017070-8-チンピラA" = "それを利用して、救護騎士団と正義実現委員会を衝突させただけさ！"
"10017070-9-チンピラB" = "まさかここまで上手くいくとは思わなかったけどな！はははっ！"
"10017070-10" = "[s] \"っていうことはハスミ、本当に奪ったの……？\""
"10017070-11-ハスミ" = "……はい、それは事実です。"
"10017070-12-ハスミ" = "しかしその「チキン」については、各位で認識の相違があるようです。"
"10017070-13-チンピラA" = "うるせぇ！"
"10017070-14-チンピラB" = "私たちが作った「ヘルファイアチキン」に文句あんのか！"
"10017070-15-セリナ" = "ヘル……？"
"10017070-16-ハナエ" = "何ですかそれ！？"
"10017070-17" = "[s] \"……どういうこと？\""
"10017070-18-チンピラA" = "説明してやろう！#n「ヘルファイアチキン」ってのは文字通り、地獄の辛さに挑戦したチキンのこと！"
"10017070-19-チンピラB" = "人工カプサイシンだけじゃないぜ！"
"10017070-20-チンピラA" = "キヴォトス最強の唐辛子と言われる「キヴォトス・リーパー」をたっぷり入れたから、そのスコヴィル値は220万オーバー！"
"10017070-21-チンピラB" = "そしてここにも、その残りがある！"
"10017070-22-セリナ" = "うぅっ、ただ見ているだけで何だか、目が……。"
"10017070-23-セリナ" = "な、涙が出てきそうに……！"
"10017070-24-ハナエ" = "うぁっ！？手で触れただけなのに、チクチクします！"
"10017070-25-ハナエ" = "わっ、お肌が腫れてきました！#n湿布、湿布はどこに……！"
"10017070-26" = "[ns1] \"身体のあちこちが痛いんだけど！？\"\n[ns2] \"これはもはや、毒性の化学物質に近いんじゃ……？\""
"10017070-27-ハスミ" = "あのようなもの、誰も食べたがらないでしょう。"
"10017070-28-ハスミ" = "食べられない……という方が正しいでしょうか。"
"10017070-29-ハスミ" = "そんなあのチキンを片っ端から通行人へ押し売りしようとしていたので、正義実現委員会が乗り出したのですが……"
"10017070-30-チンピラA" = "ヘルファイアチキンに罪は無いだろ！#n味にはいつも新しい挑戦が必要なんだ！"
"10017070-31-チンピラB" = "そうだ、ゲヘナのあいつもそう言ってた！"
"10017070-32-ハスミ" = "とにかく……私たち正義実現委員会はその悪質な押し売りと、テロに近い行為……"
"10017070-33-ハスミ" = "それらをやめるよう、対応したのです。"
"10017070-34-ハスミ" = "最終的に、あの産業廃棄物は回収しました。"
"10017070-35-チンピラA" = "産業廃棄物だと！？謝れ！"
"10017070-36-ハスミ" = "ただ売るだけでは飽き足らず、追加の費用をどんどん乗せようとしていましたし……。"
"10017070-37-チンピラB" = "仕方ないだろ！あれを生み出すのに、結構お金がかかったんだから！"
"10017070-38-チンピラA" = "そうだ、投資分は回収させてもらわないと！"
"10017070-39-ハスミ" = "しかしその金額、少なくともチキンの原価400％は超えていましたよね？"
"10017070-40-ハスミ" = "それに、「チキンを買わないなら文字通り『痛い目』に遭わせるぞ」などと脅迫していましたし……。"
"10017070-41-ハスミ" = "……ということなのですが、ミネ団長。"
"10017070-42-ミネ" = "……。"
"10017070-43-チンピラA" = "とにかく、そんな話はもうどうでも良いんだ。"
"10017070-44-チンピラB" = "みんなイイ感じにボロボロじゃねぇか……さあ、続けるか？"
"10017070-45-チンピラA" = "何かを壊すには、まず内側からってのは定石だろ？へっへっへ……。"
"10017070-46-セリナ" = "ひ、ひどいです！"
"10017070-47-ハナエ" = "みなさんを信じていたのに……！"
"10017070-48-セリナ" = "利用して、争わせることが狙いだったなんて！"
"10017070-49-ハナエ" = "それも、みんなが幸せであるべきクリスマスに！"
"10017070-50-ハナエ" = "サンタさんからプレゼント貰えなくても知りませんよ！？"
"10017070-51-チンピラA" = "……は？サンタ？"
"10017070-52-チンピラB" = "お前まさか、まだサンタが――"
"10017070-53-セリナ" = "そこまでです。"
"10017070-54-チンピラA" = "な、なんだよ急に睨んで……。"
"10017070-55-チンピラB" = "悪いけど、逃げながらでもこのまま叫んで――"
"10017070-56-セリナ" = "そこまでにしてくださいと、言っています……！"
"10017070-57" = "[ns3] \"……これ以上、怒らせないでもらえる？\"\n[ns4] \"そんな軽い気持ちで、他人の心に踏み入らないで。\""
"10017070-58-チンピラA" = "せ、先生……！？"
"10017070-59-チンピラB" = "こ、こんな怖い顔してたっけか……！？"
"10017070-60-ミネ" = "セリナ、ハナエ。"
"10017070-61-セリナ" = "団長……"
"10017070-62-ハナエ" = "団長！"
"10017070-63-ミネ" = "私にはもう、団長としての資格は無いのかもしれません。"
"10017070-64-ミネ" = "でも、今だけは……私に力を貸してもらえませんか？"
"10017070-65-セリナ" = "はい、もちろんです！"
"10017070-66-ハナエ" = "私たちは、団長についていくと決めたんですから！"
"10017070-67-ミネ" = "ありがとうございます……それでは、行きましょうか。"
"10017070-68-ツルギ" = "ひひっ……。"
"10017070-69-ツルギ" = "私も、入れてもらおうか……？"
"10017070-70-チンピラA" = "いぃっ！？"
"10017070-71-チンピラB" = "ど、どうなってんだ！？#n倒れてたんじゃないのか！？"
"10017070-72-チンピラA" = "私に聞くな！#nさっきまでは確かに気を失ってたんだ！"
"10017070-73-チンピラB" = "こうなったらあとには引けない！#nいくらあいつらだって、万全の状態じゃないんだから……！"
"10017070-74-ハスミ" = "不本意ながら……結果的に、ツルギという最大戦力を温存できたと。"
"10017070-75-ツルギ" = "きゃはははははははぁっ！！"
"10017070-76-ハスミ" = "さあ、終わらせるとしましょう。"
"10017070-77-ミネ" = "信念と誇りを胸に……！"
