[translation]
"10017040-1" = "第４話;救護・エクスプレス"
"10017040-2" = "キヴォトス市"
"10017040-3-ミネ" = "平和ですね……。"
"10017040-4-ミネ" = "特に問題はありませんでしたし、そろそろ夜更け……。"
"10017040-5-ミネ" = "……。"
"10017040-6-ミネ" = "こうなると、かえって怖くなってきますね。"
"10017040-7-ミネ" = "助けが必要な方々が、ただ私の目に見えていないだけで……どこかに、その叫びが響き渡っているのではないかと。"
"10017040-8-ミネ" = "ふぅ……今一度、誇りと信念を胸に刻み……『救護が必要な場に救護を』！"
"10017040-9-セリナ" = "あっ、団長！"
"10017040-10-ハナエ" = "お疲れ様です、団長……。"
"10017040-11-ミネ" = "セリナもハナエも、お疲れ様です。"
"10017040-12-ミネ" = "先生もありがとうございます。"
"10017040-13-ミネ" = "ところで……お二人とも、随分と落ち込まれているようですが。"
"10017040-14-ミネ" = "何かあったのですか？"
"10017040-15-ハナエ" = "それが、その……"
"10017040-16-セリナ" = "私たちの救護は、届かなかったのかもしれません……"
"10017040-17" = "[s] \"えっと、何から説明しようかな……。\""
"10017040-18-ミネ" = "『救護が必要な場に救護を』……私たちのモットーの一つです。"
"10017040-19-ミネ" = "詳しい事情を聞かせてもらえますか？"
"10017040-20-ミネ" = "なんと……本当なのですか？"
"10017040-21-ミネ" = "正義実現委員会が彼女たちのチキンを奪い……"
"10017040-22-ミネ" = "その彼女たちが、私たち救護騎士団に愚痴を聞いてほしいと訪れた……？"
"10017040-23" = "[s1] \"まあ、おおよそそんな感じかな……？\"\n[s2] \"そのまま寂しそうに帰っちゃったんだけど……。\""
"10017040-24-ハナエ" = "私たちにも何か、手伝えることはないかと伺ったのですが……。"
"10017040-25-セリナ" = "心の傷が深かったのか、ただそれを覚えていてくれれば良いとだけ……。"
"10017040-26-ミネ" = "なるほど……その気持ちは理解できます。#n何はともあれ、記憶に残ってほしいという願いも。"
"10017040-27-ミネ" = "声に出しても届かない悲鳴……"
"10017040-28-ミネ" = "……私が遅すぎたせいです。#n申し訳ありません。"
"10017040-29-セリナ" = "い、いえ、団長のせいでは……！"
"10017040-30-ハナエ" = "でも、どうして正義実現委員会のみなさんは、あんなことをしたのでしょうか?"
"10017040-31-セリナ" = "えっと、たしか委員長のツルギさんに副委員長のハスミさん、#nそれからマシロさんが……ということでしたっけ？"
"10017040-32" = "[s3] \"何か深い事情があったとか……？\"\n[s4] \"あの三人が、何の理由も無くそんなことはしないと思うけど……。\""
"10017040-33-ハナエ" = "た、確かにそうですよね……？"
"10017040-34-セリナ" = "では、先ほどの方々が言っていたのは……。"
"10017040-35-ミネ" = "セリナ、ハナエ……それから重々承知かもですが、先生にも。"
"10017040-36-ミネ" = "正義の味方を標榜しているからといって、#nいつも正しいのだと盲信することは危険なことです。"
"10017040-37-ミネ" = "自分たちは正しいという思い込みや、正義が暴走してこそ、被害は生じます。"
"10017040-38-ミネ" = "それでも、いえだからこそ「救護」は……いつどんな時でも、#n誰にでも与えられなければなりません！"
"10017040-39-セリナ" = "はい！"
"10017040-40-ハナエ" = "そうですよね！"
"10017040-41" = "[s] \"うん、たしかに。\""
"10017040-42-ミネ" = "厳格な話に思えるかもしれませんが、大事なのはそこではありません。"
"10017040-43-ミネ" = "重要なのは今この瞬間、「救護」が必要な場所を見定めること。"
"10017040-44-ミネ" = "そして必要な方に、必要な「救護」を提供する事！"
"10017040-45-ミネ" = "そして今、おそらく誰よりも私たちの「救護」が必要なのは……"
"10017040-46-ミネ" = "正義実現委員会、です！"
"10017040-47-ハナエ" = "はいっ！？"
"10017040-48-セリナ" = "そ、それは……。"
"10017040-49" = "[s] \"えっと、ごめん、論理が追えなくなってきた……。\""
"10017040-50-ミネ" = "「救護」とは何も、物質的なものだけを指すわけではありません。"
"10017040-51-ミネ" = "愛する人々、あるいは志を共にする同僚……彼女らが道を違えた時。"
"10017040-52-ミネ" = "それを正そうと諭すこともまた「救護」です。"
"10017040-53-ミネ" = "つまり何においても、問題の原因を取り除くことこそが真の意味での「救護」だといえるでしょう。"
"10017040-54-ミネ" = "セリナ、ハナエ……そして先生。"
"10017040-55-ミネ" = "私はこれから……正義実現委員会の元へ向かいます！"
"10017040-56-セリナ" = "！？"
"10017040-57-ハナエ" = "えっ、えぇっと……！？"
"10017040-58" = "[s5] \"ちょ、ちょっと待った！\"\n[s6] \"もう少し説明を！\""
"10017040-59-ミネ" = "当然、今回のことの真相を知るためです。"
"10017040-60-ミネ" = "真相を突き止めてどうするつもりなのか……？"
"10017040-61-ミネ" = "それは先程申し上げたように、#n正義実現委員会に「正義」を戻すのです。"
"10017040-62-ミネ" = "それが、救護騎士団から親愛なる「仲間」のためにできる……#n最大限の「救護」でしょう！"
"10017040-63-ハナエ" = "でも正義実現委員会のみなさんは今、#nカフェを借りてクリスマス会の最中ですよ？"
"10017040-64-ミネ" = "……。"
"10017040-65-ミネ" = "……好都合です。"
"10017040-66-ミネ" = "自らの行為を顧みず、クリスマスを楽しんでもらっている場合ではありません！"
"10017040-67-ミネ" = "正義の名が泣いています！"
"10017040-68-セリナ" = "あ、あの、団長？"
"10017040-69-ミネ" = "聞いてください。"
"10017040-70-ミネ" = "お二人の行動は任せます。ここで「救護」を行うのも、私と共に「救護」を行いにいくのも。どちらも強制はしません。"
"10017040-71-ミネ" = "どちらであろうと、それは救護の道。#nそれはあなたたちの判断に任せます。"
"10017040-72-ミネ" = "では、私はすぐ向かいますので。"
"10017040-73-ミネ" = "誇りと信念を胸に刻み……『救護が必要な場に救護を』！"
"10017040-74" = "[ns] \"えーっと……。\""
"10017040-75-ハナエ" = "ど、どうしましょう先輩？団長がもうあんなに遠く……！"
"10017040-76" = "[s] \"……とりあえず行こうか！\""
"10017040-77-セリナ" = "はっ、はい！"
