[translation]
"10017065-1" = "カフェ「White&Mason」入口"
"10017065-2-ハスミ" = "（こんな時に、イチカがいたら……！）"
"10017065-3-ハスミ" = "（ですが今は、自分の力だけでやるしかないですね……）"
"10017065-4-ミネ" = "くっ！"
"10017065-5-ハスミ" = "くぅっ……！"
"10017065-6-ミネ" = "……やはり素晴らしいですね、ハスミ副委員長。"
"10017065-7-ハスミ" = "身に余る言葉ですね……ミネ団長。"
"10017065-8-ミネ" = "だからこそ悲しいです、こんな優れた実力の持ち主が……"
"10017065-9-ミネ" = "善人のチキンを奪うだなんて！"
"10017065-10-ハスミ" = "！？"
"10017065-11-ハスミ" = "チキン……。"
"10017065-12-ハスミ" = "もしかしてそれが……救護騎士団が正義実現委員会を襲撃した理由、ですか？"
"10017065-13-ミネ" = "他に何がありますか！"
"10017065-14-ハスミ" = "他に何か、あると思っていたのですが……。"
"10017065-15-ハスミ" = "何かその、正義実現委員会全員を敵に回してもおかしくないような深刻な事態が……"
"10017065-16-ハスミ" = "政治的な問題に発展し得るとしても、それでも動かざるを得ないような事態かと……"
"10017065-17-ハスミ" = "だからこそ、こんなクリスマスにわざわざ来たと思ってたのですが……！"
"10017065-18-ハスミ" = "結局あのチキンですか！？"
"10017065-19-ハスミ" = "言っておきますが、あのチキンは――"
"10017065-20-チンピラA" = "良い様だな、正義実現委員会！"
"10017065-21-チンピラB" = "弱い者いじめをするからそうなるのさ！"
"10017065-22-チンピラA" = "今まで私たちが受けた苦しみ、倍にして返してやる！"
"10017065-23-チンピラB" = "自分たちがやられる番になった気分はどうだ？"
"10017065-24-チンピラA" = "さあ、こっからはあたしたちのターンだ！"
"10017065-25-セリナ" = "それは、どういう……？"
