[translation]
"1008803-1" = "ドレスコード"
"1008803-2" = "（カヨコとの約束時間に合わせ、便利屋の事務所を訪れた）"
"1008803-3-カヨコ" = "……あ、先生。"
"1008803-4-カヨコ" = "入っていいよ。"
"1008803-5" = "[ns1] \"失礼します～\"\n[ns2] ドアを開けて入室する。"
"1008803-6-カヨコ" = "待ってたよ。"
"1008803-7-カヨコ" = "それより珍しいね。こんな時間に寄るなんて。"
"1008803-8-カヨコ" = "……ああ、他のメンバー？"
"1008803-9-カヨコ" = "今は居ないよ。それぞれ仕事があるからね……。"
"1008803-10-カヨコ" = "でも、みんな先生に会いたがってたから、また今度寄ってって。"
"1008803-11-カヨコ" = "さて……。"
"1008803-12-カヨコ" = "探し物があるって言ってたよね？"
"1008803-13-カヨコ" = "ちょっと待ってて。今取ってくるから。"
"1008803-14-カヨコ" = "あれ、この辺に置いてたのに……"
"1008803-15-カヨコ" = "ちょっと、ごちゃごちゃしてて……"
"1008803-16-カヨコ" = "えっと……。"
"1008803-17" = "[ns3] \"カヨコ。その段ボールは……。\"\n[ns4] \"この間、依頼のときに着てたドレス？\""
"1008803-18-カヨコ" = "……うん？"
"1008803-19-カヨコ" = "ああ、これ……。"
"1008803-20-カヨコ" = "まあ……普段着でもないし、着るとしても依頼のときだけだからね。"
"1008803-21-カヨコ" = "だから、事務所の段ボールに入れてるの。"
"1008803-22" = "[s5] \"でも、埃がたまっているけど……。\"\n[s6] \"放置するには勿体なくない？\""
"1008803-23-カヨコ" = "そうかな……？"
"1008803-24-カヨコ" = "別に、普段着るわけでもないし……。"
"1008803-25-カヨコ" = "……似合ってたから、たまに着てほしい？"
"1008803-26-カヨコ" = "……まあ。"
"1008803-27-カヨコ" = "お世辞だと思うけど、褒めてくれたのは……嬉しいかな……。"
"1008803-28-カヨコ" = "でも、そんなこと言わなくていいから。"
"1008803-29-カヨコ" = "自分のことは自分がよく分かってるし。"
"1008803-30-カヨコ" = "……お世辞じゃない？ほ、本心……？"
"1008803-31-カヨコ" = "ほんと……もう……。"
"1008803-32-カヨコ" = "分かった。この話は終わり。#n先生も用があるんでしょ。"
"1008803-33-カヨコ" = "もうちょっと待ってて。すぐ探すから。"
"1008803-34" = "（少しして、カヨコは必要な資料を探し出してくれた）"
"1008803-35-カヨコ" = "あった。"
"1008803-36-カヨコ" = "はい、これ。"
"1008803-37-カヨコ" = "お礼ならいいよ。先生には普段から世話になっているし、これくらい……。"
"1008803-38-カヨコ" = "……え？"
"1008803-39-カヨコ" = "せっかくだから夕飯を奢るって？"
"1008803-40-カヨコ" = "……あの。"
"1008803-41-カヨコ" = "お礼ならいいって、言ったばっかだけど。"
"1008803-42" = "[s7] \"私の顔に免じて、ここは負けてあげて。\"\n[s8] \"大人って、そういうものだからさ。\""
"1008803-43-カヨコ" = "……はあ。"
"1008803-44-カヨコ" = "そのスキル、あまり使い過ぎないようにしてほしいね。"
"1008803-45-カヨコ" = "まあ、でも……いいよ。先生がそこまで言うなら。"
"1008803-46-カヨコ" = "うん、ありがたく貰うね。"
"1008803-47-カヨコ" = "時間になったら言って。私が店まで向かうから。"
"1008803-48-カヨコ" = "……じゃあ、また後で。"
"1008803-49" = "（カヨコから資料を受け取ったあと、シャーレで残りの仕事を済ませた）"
"1008803-50" = "（片方では店を予約し、時間と場所をカヨコに伝えた）"
"1008803-51" = "（予約したレストランに入り、席でカヨコを待っていると……）"
"1008803-52-？？？" = "お待たせ、先生。まだ時間あるのに早いんだね。#n私も結構早めに出たつもりだったんだけど……"
"1008803-53" = "[ns9] \"やあ、カヨコ。\"\n[ns10] \"もう着いたの？早かったね。\""
"1008803-54" = "[ns11] \"……か、カヨコ！？\"\n[ns12] \"……どうしてドレス姿に？\""
"1008803-55-カヨコ" = "そんなに驚くことないでしょ。"
"1008803-56-カヨコ" = "放っておくのは勿体ないって言ってたの先生だし……#nそれに、店の雰囲気にも似合うかなって思って……。"
"1008803-57-カヨコ" = "……それに、こういう時じゃなきゃ、ドレスを着る機会もないし。"
"1008803-58-カヨコ" = "……それとも似合うってのは、やっぱりお世辞だった？"
"1008803-59" = "[s13] \"ううん、違うよ。そんなこと絶対にない。\"\n[s14] \"似合いすぎて、つい言葉を失ったっていうか……。\""
"1008803-60-カヨコ" = "……ふふ、冗談。"
"1008803-61-カヨコ" = "せっかく先生が奢る食事だし、ちゃんとした服装にしたかったの。"
"1008803-62-カヨコ" = "じゃあ……"
"1008803-63-カヨコ" = "いただくね、先生。"
