[translation]
"90100010-1" = "第1話;くねくねくね"
"90100010-2-？？？" = "ねぇ、あの噂……聞いた？"
"90100010-3-？？？" = "え、どの噂？"
"90100010-4-？？？" = "シロウナギ駅の南口にさ、遊歩道があるじゃん？"
"90100010-5-？？？" = "あの川沿いのやつ？日差しを遮るものが全然ないから夏は暑いとこだよね。"
"90100010-6-？？？" = "そうそう。別に街路樹があるわけでもないから、あんまり散歩してる人もいないんだけど……。"
"90100010-7-？？？" = "最近、お昼になるとそこで体操してる人がいるんだって。"
"90100010-8-？？？" = "別にそういう人もいるんじゃない？"
"90100010-9-？？？" = "いや、それがさ……。"
"90100010-10-？？？" = "なんか、白い全身タイツを着てるんだって。#n遠くからだと「白いかかし」みたいに見えるとか。"
"90100010-11-？？？" = "まぁ、変だとは思うけど……言うほどかなぁ。"
"90100010-12-？？？" = "声をかけようとしても、いつの間にかいなくなっちゃうんだって。#n気づいたら陽炎みたいに遠くに行っちゃうから、顔を見た人はほとんどいないんだとか。"
"90100010-13-？？？" = "なんかそれはちょっと……変だね。"
"90100010-14-？？？" = "……あれ？「ほとんどいない」ってことは、顔を見た人もいるの？"
"90100010-15-？？？" = "うん。近くを走ってた陸上部の子が見たって。"
"90100010-16-？？？" = "近づいてもすぐ遠くに行くから、勝負魂に火がついたみたいで……#n必死で追いかけたらしいよ。それで、正面から顔を見たら――"
"90100010-17-？？？" = "――それ以降、口がきけなくなっちゃったんだって。"
"90100010-18-？？？" = "ど、どういうこと！？"
"90100010-19-？？？" = "かかしの顔を間近で見た後、そのまま気を失っちゃったらしいよ。"
"90100010-20-？？？" = "なんか……その日を境に、悪夢でも見てるのかずっと身体を揺すってるらしくて。"
"90100010-21-？？？" = "――くねくね、ってこう……。"
"90100010-22-？？？" = "くねくね……？"
"90100010-23-？？？" = "うん、くねくね。"
"90100010-24" = "次回;超人と狐の間"
