[translation]
"90100040-1" = "第4話;新しい拠点"
"90100040-2" = "シャーレの地下廊下"
"90100040-3-クルミ" = "シャーレに戻る先生と一緒に来たのはいいんだけどさ……。"
"90100040-4-クルミ" = "ここ……どこ？"
"90100040-5-オトギ" = "こんな区域があるなんて知らなかったなぁ。"
"90100040-6-ニコ" = "そうだね。前は目標確保のために最短ルートで動いてたから……。"
"90100040-7" = "[s1] \"ごめん、ちょっと暗いよね？\"\n[s2] \"普段あんまり使わない地下区画でさ……もう少しだけ我慢して。\""
"90100040-8-ユキノ" = "作戦の経験上、暗い場所には慣れていますので。"
"90100040-9-ユキノ" = "ですが、この階段……どこまで続いているのでしょうか。#nシャーレの地下がこれほど深かったとは知りませんでした。"
"90100040-10" = "[s] \"降りたことないから、私もよく知らないんだけど……。\""
"90100040-11" = "[ns] \"戦車も格納できるくらいだし、3階分以上はあると思うよ。\""
"90100040-12-ユキノ" = "先生ですら把握していないほどとは……#nシャーレは一体どんな構造になっているんだ？"
"90100040-13-ユキノ" = "前回の潜入時に、詳細な地図を作っておくべきだったか……。"
"90100040-14-ニコ" = "確認する時間がなかっただけじゃないかな……？#n先生、忙しいし。"
"90100040-15-クルミ" = "……そういえば前にSNSで見かけたんだけどさ。"
"90100040-16-クルミ" = "シャーレの地下深くには当番の生徒ですら近づけない秘密の部屋があって、#n先生に逆らった生徒はそこに閉じ込められて夜な夜なオシオキを受けるって――"
"90100040-17-ニコ" = "監視しやすく、脱出は困難。捕虜を尋問するならシャーレの地下は最適だろう。"
"90100040-18-ニコ" = "いくら何でも大げさじゃないかな？#nそれに「オシオキ」って……。"
"90100040-19-オトギ" = "いや、もしかしたらその噂……本当かも。"
"90100040-20-オトギ" = "前に街で聞き込みしてた時、ゲヘナの生徒が教えてくれたんだ。"
"90100040-21-オトギ" = "先生の個人ロッカーには、首輪とか手錠とかナース服がある、って。"
"90100040-22-クルミ" = "えっ……。"
"90100040-23-オトギ" = "その噂が本当なら、急いで考えなきゃいけない問題があるよ。"
"90100040-24-クルミ" = "な、なに？"
"90100040-25-オトギ" = "……FOX3が着けてる補正下着が、先生にバレるかもしれない。"
"90100040-26-オトギ" = "先生は気づいてないみたいだけど、FOX3の名誉のためにも今すぐ撤退した方が――"
"90100040-27-クルミ" = "なっ、なんで私の話になるのよ！"
"90100040-28-オトギ" = "ほう……盛ってるってことは否定しないんだね？"
"90100040-29-ユキノ" = "……FOX3、FOX4。私たちは[USERNAME]先生に返しきれない恩義があるんだ。"
"90100040-30-ユキノ" = "仮に何かを要求されたとしても、それを拒んで逃げるのは道理に反する。"
"90100040-31-ユキノ" = "……それを思えば、クルミの下着事情など些末な問題だ。"
"90100040-32-クルミ" = "こらっ！ユキノ！！"
"90100040-33" = "[ns3] \"さっきから賑やかだけど……。\"\n[ns4] \"何の話してるの？\""
"90100040-34-ニコ" = "い、いえ……なんでもありませんよ。"
"90100040-35-ニコ" = "久しぶりに外に出たから、ちょっと浮かれてるみたいで。"
"90100040-36" = "[s] \"それならいいけど……。\""
"90100040-37" = "[ns] \"さあ、着いたよ。\""
"90100040-38-オトギ" = "ここは……。"
"90100040-39" = "[ns5] \"FOX小隊の[ruby=HQ]作戦本部[/ruby]だ！\"\n[ns6] \"急いで片づけたから少し散らかってるけど……。\""
"90100040-40-オトギ" = "す、すごい部屋ですね。シャーレの地下にこんな場所があったなんて……。"
"90100040-41-オトギ" = "防爆設計されてて、独立したサーバーもある……。"
"90100040-42-オトギ" = "これだけ整ってればSRT特殊学園にいた頃と同じ規模の作戦も展開できそうだね。"
"90100040-43-オトギ" = "先生、ここは一体……。"
"90100040-44" = "[s7] \"今は使われてない古いサーバールームだよ。\"\n[s8] \"私も連邦生徒会長から聞くまでは知らなかったんだ。\""
"90100040-45" = "[ns9] \"だから、当番の生徒で知ってる子はいないはず。\"\n[ns10] \"安心して整備とか休憩でここを使ってね。\""
"90100040-46-ユキノ" = "……連邦生徒会長が手配してくださったのですね。"
"90100040-47-ユキノ" = "一般の生徒が立ち入れない場所に臨時拠点を設けて、キヴォトスを脅かす特異現象を追う……。"
"90100040-48-ユキノ" = "たしかに、生徒の目を避けて先生のバックアップを受けるならば、#nシャーレの地下に滞在するのが最善ではあります。"
"90100040-49-ユキノ" = "とはいえ先生の居場所を、私たちの作戦で間借りすると思うと、少々気が引けますね。"
"90100040-50" = "[ns] \"君たちだけの作戦じゃないよ。\""
"90100040-51-オトギ" = "……と、言いますと？"
"90100040-52" = "[s11] \"SRTは「キヴォトスの問題」を解決する組織でしょ？\"\n[s12] \"だから今回の作戦は、キヴォトスのみんなのための作戦だよ。\""
"90100040-53-ユキノ" = "以前から思っていたのですが……。"
"90100040-54-ユキノ" = "生徒から「怪しい」と言われませんか？"
"90100040-55" = "[s] \"割とあったような……？\""
"90100040-56-ユキノ" = "美味そうなお肉があからさまに置いてあれば、警戒する獣もいるでしょう。"
"90100040-57-ユキノ" = "大した労力もかけていないのに、都合よく目の前に現れる獲物なんて、#nたいていは罠ですから。"
"90100040-58-ユキノ" = "ですが、それが実は一切害のない――自分のためだけに用意された豪華な晩餐だと知られたなら……。"
"90100040-59-ユキノ" = "「変わった大人」という評価では済まなくなるでしょう。"
"90100040-60" = "[s] \"あれ？私、何か変な事言ったかな？\""
"90100040-61-ユキノ" = "……いえ、お気になさらず。"
"90100040-62-ユキノ" = "FOX小隊を代表して――改めて、惜しみないご支援に感謝申し上げます。"
"90100040-63-ニコ" = "ユキノってほんっと堅いんだから。#nそんなにカッチカチに言わなくてもいいのに。"
"90100040-64-ニコ" = "でも、感謝を伝えるのは大事だよ。"
"90100040-65-クルミ" = "ふふ、久しぶりの作戦だって思うと、なんだかうずうずしてきたわ。"
"90100040-66-ユキノ" = "ではこれより、作戦と情報収集を――"
"90100040-67" = "[s] \"作戦名は決めなくていいの？\""
"90100040-68-ユキノ" = "……最近は簡略化していたので、失念していました。"
"90100040-69-ユキノ" = "では折角ですし、FOX小隊の再始動を記念して「コンコン作戦」ということで――"
"90100040-70-オトギ" = "いやいや、その名前はいくらなんでも子どもっぽすぎるでしょ。"
"90100040-71-クルミ" = "うん。別に捻らないで、いつもみたいにシンプルでよくない？"
"90100040-72-ニコ" = "気持ちは分かるけど……今回だけは分かりやすいほうがいいんじゃないかな？"
"90100040-73-ニコ" = "例えば、「ロア」を追跡する作戦だから「ロア追跡作戦」とか……。"
"90100040-74-オトギ" = "異議なし！"
"90100040-75-ユキノ" = "…………。"
"90100040-76" = "[s] \"……コンコン作戦は、今度どこかで使おっか？\""
"90100040-77-ユキノ" = "……承知しました。"
"90100040-78-ユキノ" = "では――「ロア追跡作戦」を開始する。"
"90100040-79" = "次回;聞き込み"
