[translation]
"13160-1" = "第16話;反撃"
"13160-2-ノノミ" = "……。"
"13160-3-スオウ" = "ご令嬢、不便だろうがここで我慢していてくれ。"
"13160-4-ノノミ" = "あなたは、いったい……。"
"13160-5-スオウ" = "……私だ。 "
"13160-6-スオウ" = "対策委員会は、予定通りそちらに向かうだろう。"
"13160-7-スオウ" = "万全の準備で迎え撃ってくれ。"
"13160-8-？？？" = "それくらい分かっていますよ。#nわざわざ連絡をしてくるくらいですから、ほかにも何かあるのでしょう？"
"13160-9-スオウ" = "……ネフティスが裏切った。"
"13160-10-債権者団体の代表" = "なるほど……。 "
"13160-11-債権者団体の代表" = "やはり、アビドスの者は油断なりません。"
"13160-12-債権者団体の代表" = "……良いでしょう。#n警備をさらに強化します。"
"13160-13-黒亀組の組員A" = "なるほど、そうでしたか。"
"13160-14-黒亀組の組員A" = "裏切るとは思っていましたがね。"
"13160-15-黒亀組の組員A" = "シャーレが絡んでこようと、関係はありませんよ。"
"13160-16-ZK社長" = "……そうか。"
"13160-17-ZK社長" = "バリケードを強化して、対戦車地雷の準備もしよう。"
"13160-18-押収品競売組合長" = "……分かった。#nまた何かあったら連絡してくれ。"
"13160-19-押収品競売組合長" = "はっ……列車砲なんかに興味はない。"
"13160-20-押収品競売組合長" = "私が求めているのは、あくまでも革新的な技術のほうだ。"
"13160-21-押収品競売組合長" = "あの天才「雷帝」が設計した構造を解き明かせば……。"
"13160-22-押収品競売組合長" = "大至急、マーケットガードを増員する。"
"13160-23-私債労働組合長" = "ネフティスが裏切りを……？"
"13160-24-私債労働組合長" = "ふっふっふ、むしろ好都合ですね。"
"13160-25-ノゾミ" = "はぁ、めんどーだから連絡してこないでよ。"
"13160-26-ノゾミ" = "非常事態って何なのさ。"
"13160-27-ノゾミ" = "砂漠横断鉄道の工事なら、始めたばっかじゃん。#n……って、本当か！？"
"13160-28-ノゾミ" = "ヒカリ！"
"13160-29-ノゾミ" = "早く準備して行くよ！"
"13160-30-ヒカリ" = "おー？"
"13160-31" = "[ns] まばたきをする。"
"13160-32-医者" = "……！"
"13160-33" = "[s] 体を起こす。"
"13160-34-医者" = "先生は爆発に巻き込まれたのです。#n奇跡的に傷ひとつなかったとはいえ、どうかご安静に。"
"13160-35-医者" = "せ、先生！？"
"13160-36-医者" = "どこへ行くのですか？"
"13160-37" = "[s1] \"生徒と約束をしたんです。\"\n[s2] \"アビドスに行かないと……。\""
"13160-38-医者" = "……なるほど、何か事情があるのですね。#nですが、せめて簡単な検査だけはさせてください。"
"13160-39" = "[ns] （グラウンドでヘリが燃えている……）"
"13160-40-セリカ" = "先生……。"
"13160-41-アヤネ" = "……。"
"13160-42-シロコ" = "……。"
"13160-43-シロコ" = "先生、ホシノ先輩が……。"
"13160-44" = "[s] \"大丈夫、落ち着いて。\" "
"13160-45-シロコ" = "う、うん……。"
"13160-46-セリカ" = "はい……。 "
"13160-47-セリカ" = "そうね……片付けもしないと。"
"13160-48" = "（学校を軽く片付けてから、対策委員会の教室に集まることにした）"
"13160-49-アヤネ" = "……ホシノ先輩は、一人で行ってしまいました。"
"13160-50-セリカ" = "みんなは付いてくるなって。"
"13160-51-シロコ" = "……私が勝てなかったから。"
"13160-52-セリカ" = "なに落ち込んでるのよ、シロコ先輩らしくないわね。#nホシノ先輩が強すぎただけ。"
"13160-53-シロコ" = "ん、セリカは優しいね。"
"13160-54-セリカ" = "素直になられても、これはこれでやりづらいわね！"
"13160-55-シロコ" = "……う、うん。"
"13160-56-アヤネ" = "……先生。#nどうすればホシノ先輩を止められるんでしょうか？"
"13160-57" = "[s] \"まずは状況を整理しよう。\""
"13160-58-シロコ" = "戦っても、止められなかった……。"
"13160-59-アヤネ" = "最後には、副生徒会長として命令する、とまで……。"
"13160-60-アヤネ" = "今もホシノ先輩は、書類上「アビドス生徒会」の所属になっていますが……。"
"13160-61-アヤネ" = "……もし、アビドス生徒会が存在しなかったとしたら、#n契約そのものがなかったことになります。"
"13160-62-アヤネ" = "先輩は総会で契約の無効を主張して、ノノミ先輩を救い、列車砲を破壊したら……#n責任を取って、私たちのもとから姿を消す、と。"
"13160-63-アヤネ" = "どうすれば、ホシノ先輩を助けられますか？"
"13160-64-アヤネ" = "大切な思い出を、自ら否定しなくてはいけないだなんて……。#n私たちにも、何かできないのでしょうか？"
"13160-65-シロコ" = "……。"
"13160-66-セリカ" = "……。"
"13160-67" = "[s] \"みんな、覚悟はできてる？\""
"13160-68-セリカ" = "当たり前じゃない！ "
"13160-69-シロコ" = "ノノミもホシノ先輩も、私たちの仲間。"
"13160-70-アヤネ" = "シロコ先輩の言う通りです！"
"13160-71" = "[s] \"うん、分かった。\""
"13160-72-アヤネ" = "ホシノ先輩は、また自分だけで解決しようとしています。"
"13160-73-アヤネ" = "ですが、私たちではホシノ先輩に勝てません。"
"13160-74-アヤネ" = "追いかけたところで、説得できなければ意味が……。"
"13160-75-シロコ" = "ん、昔の女が忘れられないみたい。"
"13160-76-セリカ" = "……急に昼ドラみたいなこと言わないでよ。"
"13160-77-セリカ" = "……はぁ、問題が山積みね。"
"13160-78-シロコ" = "先生がいれば大丈夫。"
"13160-79-セリカ" = "それでも、たったの四人で……。"
"13160-80-シロコ" = "私たちでやるしかない。"
"13160-81-セリカ" = "……そう、ね。"
"13160-82-アヤネ" = "一度、問題を整理してみましょう。"
"13160-83-アヤネ" = "まず、ノノミ先輩を助けなければいけません。"
"13160-84-セリカ" = "助けるにも居場所が分からないんだから、#nネフティスに言われた通り「アビドス生徒会」の存在を否定するしか……。"
"13160-85-シロコ" = "総会に出席するためには、#n私募ファンドの妨害を突破しないといけない。"
"13160-86-アヤネ" = "一人で向かったホシノ先輩を止める必要もあります！"
"13160-87-アヤネ" = "ノノミ先輩のことはホシノ先輩一人の問題ではありません……。"
"13160-88-アヤネ" = "私達だって当事者なんですから。"
"13160-89-アヤネ" = "それに、いくらホシノ先輩が強くても、#n数で押されてしまえば手も足も出ないはずです。"
"13160-90-アヤネ" = "そして……アビドス砂漠のどこかにある「列車砲」を#n悪い人たちの手に渡らないようにしなければなりません。"
"13160-91-セリカ" = "そのためには、砂漠横断鉄道の権利問題も解決しないと……。"
"13160-92-アヤネ" = "……そうだね。 "
"13160-93" = "[s3] \"本当に難しいね……。\"\n[s4] \"ややこしい状況だね……。\""
"13160-94-アヤネ" = "……曖昧になっていた、「アビドス生徒会」と「アビドス対策委員会」の扱い。"
"13160-95-アヤネ" = "私たちにとって、#n弱点となる場所ばかり突かれているこの状況には……。"
"13160-96-アヤネ" = "……誰かの執拗な悪意を感じます。"
"13160-97-セリカ" = "悪意なら最初からあったでしょ？"
"13160-98-アヤネ" = "うーん、なんて言ったら良いのかな。"
"13160-99" = "[s] \"……うまく言えないけど、私も感じてる。\""
"13160-100-セリカ" = "先生も……？"
"13160-101-シロコ" = "……大事なことがある。"
"13160-102" = "何ですか、シロコ先輩？"
"13160-103-シロコ" = "ホシノ先輩にも、悲しい思いをしてほしくない。"
"13160-104-シロコ" = "私にとっての対策委員会と同じように、#nホシノ先輩にとってアビドス生徒会は大切な場所。"
"13160-105-シロコ" = "その存在を、先輩自身が否定するのは……。"
"13160-106-セリカ" = "うん、アビドス生徒会もちゃんと残さないと。"
"13160-107-シロコ" = "……ん。"
"13160-108" = "[s] \"そうだね。\""
"13160-109-シロコ" = "……ごめん、先生。#n私のわがままで……。"
"13160-110" = "[s] \"大丈夫だよ、シロコ。\""
"13160-111" = "[ns] \"生徒のわがままを聞くのも、大人の役割だからね。\""
"13160-112-シロコ" = "……うん。"
"13160-113-アヤネ" = "先生……。"
"13160-114-セリカ" = "……ありがとう。"
"13160-115-アヤネ" = "……どうして。"
"13160-116-セリカ" = "アヤネちゃん？"
"13160-117-アヤネ" = "どうして、こんなことに……。"
"13160-118-アヤネ" = "アビドス生徒会は、対策委員会は……。"
"13160-119-アヤネ" = "私たちは、これからどうなるんでしょうか。"
"13160-120-シロコ" = "……。"
"13160-121-シロコ" = "……。"
"13160-122" = "[ns] \"……よし。\""
"13160-123-セリカ" = "先生……？"
"13160-124" = "[s] \"まずは、そこから解決しよう。\""
"13160-125-シロコ" = "……？"
"13160-126-セリカ" = "そこって……？ "
"13160-127-アヤネ" = "先生……？"
"13160-128" = "[s] \"「アビドス生徒会」の会長は、ずっと空席だよね？\""
"13160-129-アヤネ" = "は、はい。"
"13160-130" = "[s5] \"なら、\"\n[s6] \"補欠選挙をしよう。\""
"13160-131-セリカ" = "補欠選挙……？"
"13160-132-セリカ" = "え、選挙？"
"13160-133-アヤネ" = "補欠、選挙……。"
"13160-134-アヤネ" = "……あっ、先生の仰りたい意味が分かりました！"
"13160-135-セリカ" = "アヤネちゃん……？"
"13160-136-アヤネ" = "今ここには、全校生徒の60％がいるでしょ？"
"13160-137-セリカ" = "5分の3だから、間違ってはないけど……それで？"
"13160-138-アヤネ" = "生徒会長がいれば、私たちの問題は解決できるんだよ！"
"13160-139" = "[ns7] \"前にも生徒会長を選出した、\" \n[ns8] \"あの方法がある。\" "
"13160-140" = "[ns] \"「シャーレ」の私が、正当性を保証するよ。\""
"13160-141-シロコ" = "……！！"
"13160-142-アヤネ" = "はいっ！"
"13160-143-アヤネ" = "私[ruby=おくそら]、奥空ア[/ruby]ヤネは――"
"13160-144-アヤネ" = "――生徒会長に立候補します！"
"13160-145-セリカ" = "えっ！？"
"13160-146-アヤネ" = "ユメ生徒会長は本当の生徒会長なので、#nこの選挙も正当性が認められるはずです！"
"13160-147" = "[ns] \"では、挙手投票を行います！\""
"13160-148-セリカ" = "選挙の基本原則みたいなのは大丈夫なの？#nとりあえず、私は賛成！"
"13160-149-シロコ" = "ん、賛成。"
"13160-150-アヤネ" = "私は立候補者なので、当然賛成です！"
"13160-151" = "[ns9] \"それじゃあ……。\"\n[ns10] \"これでアヤネが生徒会長だね。\""
"13160-152" = "[ns11] \"シャーレの顧問でもあり……。\"\n[ns12] \"アビドスの顧問でもある私が――\"\n[ns13] \"――立会人として、選挙結果を保証するよ。\""
"13160-153-セリカ" = "本当に、これでアヤネちゃんが生徒会長に？"
"13160-154-シロコ" = "ん。"
"13160-155-セリカ" = "ま、待って。#nじゃあアヤネちゃんは「アビドス生徒会」になったの？"
"13160-156" = "[s] \"生徒会長、教えてくれる？\""
"13160-157-アヤネ" = "対策委員会は……アビドス生徒会に吸収合併されました！"
"13160-158-セリカ" = "えっ！？"
"13160-159-アヤネ" = "ですが、名前は「対策委員会」とします！"
"13160-160-シロコ" = "ん、分かった。#nこれで完璧。"
"13160-161-セリカ" = "ちょ、ちょっと無理やりすぎない？"
"13160-162-アヤネ" = "生徒会長の決定に不満ですか、黒見セリカさん！"
"13160-163-セリカ" = "い、いえ……ありません。"
"13160-164-アヤネ" = "対策委員会の生徒会長として、#n今後の方針を発表します！"
"13160-165-セリカ" = "て、鉄拳統治って、まさにこれよね……？"
"13160-166-アヤネ" = "これから債権者団体の総会に乗り込み、#n前生徒会長が結んだ契約を維持します！"
"13160-167-アヤネ" = "なぜなら、私たちには正当な権限があるからです！"
"13160-168-アヤネ" = "そして、列車砲の権利はネフティスにも私募ファンドにも渡しません！"
"13160-169-シロコ" = "ん。 "
"13160-170-アヤネ" = "同時に、ネフティスからノノミ先輩を返してもらえるように要求します。"
"13160-171-アヤネ" = "この要求を受け入れなかった場合、#n敵対行為と見なし実力行使に出ます！"
"13160-172" = "[s] \"ノノミの位置は、私が探してみるよ。\""
"13160-173-アヤネ" = "はい！ "
"13160-174-セリカ" = "分かったわ！"
"13160-175-シロコ" = "アヤネ、ホシノ先輩は？"
"13160-176-アヤネ" = "……。"
"13160-177-セリカ" = "あ、アヤネちゃん……？"
"13160-178-アヤネ" = "ホシノ先輩は……。"
"13160-179-シロコ" = "う、うん……。"
"13160-180-アヤネ" = "……書記に降格です！"
"13160-181-セリカ" = "（自分の仕事を先輩に押し付けた……！？）"
"13160-182-シロコ" = "ん、異議なし。"
"13160-183-アヤネ" = "これで先輩が契約に関する話を進めても、効力はないです！"
"13160-184-アヤネ" = "ただの書記に、そのような権限はありませんから！"
"13160-185-アヤネ" = "ありがとうございます、先生。"
"13160-186-アヤネ" = "これで問題解決の糸口が掴めました！"
"13160-187-セリカ" = "えっと、ノノミ先輩の居場所は先生が何とかしてくれて……。"
"13160-188-セリカ" = "ホシノ先輩は副生徒会長じゃなくなったから、契約をどうすることもできないんだよね？あとは私たちが契約を維持すれば、あいつらの手に列車砲は渡らない……？"
"13160-189-シロコ" = "アビドス生徒会も、対策委員会も、なくならずに済む。"
"13160-190-セリカ" = "これなら、全部の問題が解決できそうね。"
"13160-191-アヤネ" = "まずは、本日12時の総会に出席します！"
"13160-192-アヤネ" = "そして、ホシノ先輩を阻止し、ノノミ先輩を助けましょう！"
"13160-193-アヤネ" = "そのためには、#nどうにか私募ファンドの妨害を突破しなくてはいけませんが……。"
"13160-194-セリカ" = "ん、分かった。"
"13160-195-セリカ" = "簡単には行かないだろうけど……。"
"13160-196" = "[s] \"頑張ろう、みんな。\""
"13160-197-アヤネ" = "はい！"
"13160-198-アヤネ" = "[ruby=対策委員会]「アビドス生徒会」[/ruby]として、最初の任務を開始します！"
"13160-199-セリカ" = "アヤネちゃん、急に恥ずかしくなったの……？"
"13160-200" = "[s] \"格好良かったよ？\""
"13160-201-アヤネ" = "……はいぃ。 "
"13160-202-セリカ" = "わ、私はこういうアヤネちゃんも良いと思うけど。"
"13160-203-アヤネ" = "キャラじゃないことしたかなって……。"
"13160-204-セリカ" = "あんなノリノリだったのに？"
"13160-205-シロコ" = "ん。ホシノ先輩捕獲作戦、開始。"
"13160-206-セリカ" = "……さっきからすごく楽しそうね、シロコ先輩。"
"13160-207" = "[ns] \"よし、それじゃあ行こうか。\""
"13160-208-アヤネ" = "はい、先生。#n新生対策委員会――"
"13160-209-アヤネ" = "――出発します！"
"13160-210" = "次回;追跡"
