[translation]
"13210-1" = "第21話;二度目の追跡"
"13210-2-セリカ" = "みんな、大丈夫？"
"13210-3-債権者団体の代表" = "お、おかげで助かりました……。"
"13210-4-質屋連合長" = "これ以上は無理です。手を引きましょう。"
"13210-5-ZK社長" = "アビドスに手を出そうとしたのが間違っていたんだ……。"
"13210-6-私債労働組合長" = "まさか、こうなるとは思いも……。"
"13210-7-私債労働組合長" = "最初から関わっていなければ……。"
"13210-8-アヤネ" = "プレジデントは、じきに兵力を送り込んでくるはずです。#n早ければ、今日の夕方にでも……。"
"13210-9-アヤネ" = "アビドスが戦場と化す前に、皆さんは逃げてください。"
"13210-10-債権者団体の代表" = "わ、分かりました……。"
"13210-11-ネフティス幹部" = "お嬢様……。"
"13210-12-ノノミ" = "執事さん、大丈夫ですか……？"
"13210-13-ネフティス幹部" = "わ、私はなんてことを……。"
"13210-14-ノノミ" = "アビドスは、すぐ戦場になってしまうでしょう。"
"13210-15-ネフティス幹部" = "こんな、はずじゃ……。"
"13210-16-ノノミ" = "分かっています、執事さん。"
"13210-17-ネフティス幹部" = "……お嬢様。"
"13210-18-ノノミ" = "手段こそ違いましたが、#n執事さんもアビドスの復興を願っていたんですよね。"
"13210-19-ネフティス幹部" = "……。"
"13210-20-ノノミ" = "結果はどうあれ……。"
"13210-21-ネフティス幹部" = "……申し訳、ありません。"
"13210-22-ネフティス幹部" = "列車砲の存在を知ってからというもの、#nそれで頭がいっぱいになってしまい……。"
"13210-23-ネフティス幹部" = "アレさえあれば、また過去の栄光を取り戻せる、と。"
"13210-24-ネフティス幹部" = "ネフティスは、再びアビドスに戻れるはずだ、と……。"
"13210-25-ノノミ" = "私から言えることは、何もありません。"
"13210-26-ネフティス幹部" = "……。"
"13210-27-ノノミ" = "では執事さん、お元気で。"
"13210-28-ネフティス幹部" = "ど、どこに行くのですか、お嬢様！"
"13210-29-ノノミ" = "ホシノ先輩を止めに行きます。"
"13210-30-ノノミ" = "このままでは、列車砲を破壊した責任を一人で負って、#n退学するつもりでしょうから。"
"13210-31-ネフティス幹部" = "し、しかしどうやって……？"
"13210-32-ノノミ" = "……まだ、何も。ですが、みんなで考えれば、きっとうまくいきます。"
"13210-33-ネフティス幹部" = "……。"
"13210-34-シロコ" = "また止められなかった。#n私がもっと強かったら……。"
"13210-35-セリカ" = "だから、シロコ先輩のせいじゃないって。#nホシノ先輩が強すぎるんだよ。"
"13210-36-ノノミ" = "……元気出してください、シロコちゃん。"
"13210-37-シロコ" = "……。"
"13210-38-アヤネ" = "このままでは、ホシノ先輩がいなくなってしまいます。"
"13210-39-アヤネ" = "すべて独断の犯行だと証言すれば……。"
"13210-40-アヤネ" = "何か問題が発生した時、アビドスが責任を問われることはないから……。"
"13210-41-セリカ" = "ちょっと変だったわよね、先輩。"
"13210-42-セリカ" = "うまく言えないけど、追い詰められてるような。"
"13210-43-アヤネ" = "いつもの先輩なら、みんなで解決策を考えてたはずなのに……。"
"13210-44-シロコ" = "……あの時と似てる。"
"13210-45-ノノミ" = "ホシノ先輩は、列車砲の破壊をユメ会長の意志だと思っているみたいです。"
"13210-46-セリカ" = "えっ、ユメ会長はそんなこと言ってないはずよね？"
"13210-47" = "うん。でも、ホシノ先輩は「ユメ先輩ならこうするはず」って。"
"13210-48-セリカ" = "どうして……。"
"13210-49-ノノミ" = "これは、私の想像でしかありませんが……。"
"13210-50-ノノミ" = "おそらく……。"
"13210-51-ユメ" = "今日は宝探しをするよ！"
"13210-52-ユメ" = "お～い、ホシノちゃん……？"
"13210-53-ホシノ" = "あっ、先輩。今度はどうしたんですか？"
"13210-54-ユメ" = "それはね……って、ホシノちゃんこそどうしたの？"
"13210-55-ホシノ" = "これは……。"
"13210-56-ユメ" = "もしかして、ついに自分のことをお魚さんだと勘違いしちゃったとか……。"
"13210-57-ホシノ" = "そんなわけないじゃないですか！"
"13210-58-ホシノ" = "水道の修理をしてたら濡れちゃったので、着替えただけです！"
"13210-59-ユメ" = "あっ、グラウンドのところ？#n直してくれたんだね。"
"13210-60-ホシノ" = "いえ、まだ直せてません。#n思ったより難しくて……。"
"13210-61-ユメ" = "ふふっ、ホシノちゃんにもできないことがあるんだ。"
"13210-62-ユメ" = "不器用なおじさんみたいで、ちょっと可愛いね。"
"13210-63-ホシノ" = "そ、"
"13210-64-ホシノ" = "それより宝探しがどうしたんです？"
"13210-65-ユメ" = "あっ、そうなの。見て見て、ホシノちゃん！"
"13210-66-ユメ" = "すごい情報を手に入れたんだ！"
"13210-67-ホシノ" = "先輩の言う「すごい」は、もう信用できないんですけど……。"
"13210-68-ユメ" = "今度こそ大丈夫だから、信じて！"
"13210-69-ホシノ" = "また騙されてないですよね？"
"13210-70-ホシノ" = "「生徒会の谷」……？"
"13210-71-ユメ" = "昔、アビドスの生徒会長が作った展示館があるらしいの！"
"13210-72-ユメ" = "貴重な物が、いーっぱい展示されてるんだって！"
"13210-73-ホシノ" = "もし本当だとしても、#nとっくに売り払ったか盗まれてると思いますよ。"
"13210-74-ユメ" = "ふっふっふ、そう思うよね？"
"13210-75-ユメ" = "でもここは、一般に公開されてない秘密の場所にあるんだって。"
"13210-76-ホシノ" = "つまり……。"
"13210-77-ユメ" = "学校が経営難で売っちゃってたら仕方ないけど、#n少なくとも盗まれてる可能性は少ないよ！"
"13210-78-ホシノ" = "だから……探しに行こう、と？"
"13210-79-ユメ" = "うん！"
"13210-80-ホシノ" = "……誰も場所を知らないのに、どうやって探すんですか？"
"13210-81-ユメ" = "ふふん！"
"13210-82-ユメ" = "昔の書類を漁ってたら、これを見つけたの！"
"13210-83-ホシノ" = "……何ですか、これ。"
"13210-84-ホシノ" = "黒く塗りつぶされてるところが多くて、全然読めませんけど。"
"13210-85-ユメ" = "ほら、ここ見て。"
"13210-86-ホシノ" = "「アビドス砂漠閉鎖地区セクター35-9」？"
"13210-87-ユメ" = "少なくとも、ここに手がかりがあると思うの！"
"13210-88-ホシノ" = "はぁ……。"
"13210-89-ユメ" = "ダメ、かな……？"
"13210-90-ホシノ" = "まったく、ユメ先輩は……。"
"13210-91-ユメ" = "は、はぅ……。"
"13210-92-ホシノ" = "なんでもっと早く言わないんですか！#nすぐ行きますよ！"
"13210-93-ユメ" = "ホシノちゃん！"
"13210-94-ユメ" = "今度こそお宝を見つけましょう！"
"13210-95-ユメ" = "ほ、ホシノちゃん待って。#n先に着替えないと！"
"13210-96-ホシノ" = "あっ！"
"13210-97-ホシノ" = "ユメ先輩、何も見つかりませんよ。"
"13210-98-ユメ" = "……こっちもハズレみたい、うぅ。"
"13210-99-ホシノ" = "……。"
"13210-100" = "アビドス砂漠閉鎖地区・セクター35-9"
"13210-101-ホシノ" = "……変わらないな。"
"13210-102-ノノミ" = "……囚われているんだと思います。"
"13210-103-セリカ" = "それって……。"
"13210-104-ノノミ" = "あるいは、私たちもまた……。"
"13210-105-ノノミ" = "何かに囚われているような……。"
"13210-106-シロコ" = "うーん……。"
"13210-107" = "[s] \"囚われている、か。\""
"13210-108-シロコ" = "それでも、ホシノ先輩を止めないと。"
"13210-109-アヤネ" = "そうですね。#n列車砲を破壊したら、カイザーは莫大な損害賠償を請求してくるでしょう。"
"13210-110-アヤネ" = "このまま見過ごすわけにはいきません。"
"13210-111-アヤネ" = "何か、方法を探さなくては……。"
"13210-112-ノノミ" = "まずはホシノ先輩を追いかけましょう！#nもう、私は迷いません！"
"13210-113-シロコ" = "でも追いかけたところで、ホシノ先輩には敵わないじゃない。"
"13210-114-シロコ" = "うーん……。"
"13210-115-セリカ" = "先生、誰か助けてくれそうな人はいない？"
"13210-116-セリカ" = "ホシノ先輩並みに強い人で……。"
"13210-117" = "[s] \"うーん……。\""
"13210-118-ノノミ" = "良い案ですが、それでは根本的な解決にならないかと。"
"13210-119-ノノミ" = "またいつか、似たような問題が起きた時も、#nユメ会長の背中を追って一人で解決しようとすると思うんです。"
"13210-120-ノノミ" = "これは、私たちで何とかするしかありません。"
"13210-121-セリカ" = "じゃあ、決まりね！"
"13210-122-シロコ" = "ん。"
"13210-123-セリカ" = "すぐに出発……。"
"13210-124-セリカ" = "……って、場所が分からないんだったわ。"
"13210-125-シロコ" = "うーん……。"
"13210-126-ノノミ" = "ホシノ先輩は知っているようでしたが……。"
"13210-127-ネフティス幹部" = "……お嬢様。"
"13210-128-アヤネ" = "……？"
"13210-129-ノノミ" = "どうかしま――"
"13210-130-ノノミ" = "もしかして執事さんは、どこにあるのか知っているのですか！？"
"13210-131-ネフティス幹部" = "「アビドス砂漠閉鎖地区セクター35-9」と、プレジデントは言っていました。"
"13210-132-ネフティス幹部" = "おそらく、ここから480kmほど離れた岩石砂漠地帯のことでしょう。"
"13210-133-ネフティス幹部" = "そこには砂漠横断鉄道の駅があります。"
"13210-134-ホシノ" = "……開いてる。"
"13210-135-ホシノ" = "……管制システムが動いてる。"
"13210-136-ホシノ" = "ただのガラクタだと思ってたけど……。"
"13210-137-ホシノ" = "管理者権限、「[ruby=いざよい]十六夜[/ruby]ノノミ」……。"
"13210-138-ホシノ" = "そっか。"
"13210-139-ホシノ" = "ずっと使われてなかっただけで、機能はそのままだったんだ。"
"13210-140-ホシノ" = "目的地は……「生徒会の谷」っと。"
"13210-141-ホシノ" = "少し前に発車した電車は、#nあの眼帯ちゃんが乗っていったやつだろうね。"
"13210-142-ホシノ" = "どうすれば動かせるんだろ……これかな。"
"13210-143-ホシノ" = "……当たりだね。"
"13210-144-ネフティス幹部" = "ただの閉鎖された駅にも見えますが……。"
"13210-145-ネフティス幹部" = "実は「生徒会の谷」に繋がる分岐駅になっています。"
"13210-146-ネフティス幹部" = "お嬢様のカードを使って権限にアクセスすれば、#n列車のシステムを再起動できるはずです。"
"13210-147-アヤネ" = "ということは……。"
"13210-148-ノノミ" = "執事さん……。"
"13210-149" = "[ns] \"ありがとうございます。\""
"13210-150-ネフティス幹部" = "……いえ。"
"13210-151-ネフティス幹部" = "お嬢様、本当に申し訳ありませんでした。"
"13210-152-ノノミ" = "……執事さん。"
"13210-153-ネフティス幹部" = "どうか急いでください。#nホシノさんもスオウさんも、そこに向かったはずです。"
"13210-154-ノノミ" = "はい……。"
"13210-155-ノノミ" = "ところで……スオウさんは、いったい何者なのでしょうか？"
"13210-156-ノノミ" = "最初はハイランダーの方だと思っていました。#nですが、ネフティスにも私募ファンドにも所属していたようで、#n最終的にはカイザーなのかと思えば、それも裏切り……。"
"13210-157-ノノミ" = "そのうえ、どうしてホシノ先輩に目を……。"
"13210-158-ネフティス幹部" = "元[ruby=あさぎり]々朝霧ス[/ruby]オウは、特定の学園に所属せずふらついていた不良でした。"
"13210-159-ネフティス幹部" = "お嬢様のハイランダー進学に合わせて護衛を探していたところ、#n彼女の存在を知ったのです。"
"13210-160-ノノミ" = "私の護衛ですか……？"
"13210-161-ネフティス幹部" = "はい。しかしお嬢様がアビドスに進学したため、その役目はなくなりました。#nその後、しばらく存在を忘れていましたが……。"
"13210-162-ネフティス幹部" = "気づけば、監督官の座に。"
"13210-163-ネフティス幹部" = "彼女とは、今回の一件で久しぶりに連絡を取ったのです。"
"13210-164-ネフティス幹部" = "……本当は何者なのか、何を考えているのか、#nそれは私にも分かりません。"
"13210-165-ノノミ" = "生徒会の谷に行けば……。"
"13210-166-ネフティス幹部" = "はい、おそらく。#nですが、追いつくためには高速鉄道でも使用しなければなりません。"
"13210-167-アヤネ" = "……そこが問題になってきますね。"
"13210-168-アヤネ" = "どうすれば……。"
"13210-169-？？？" = "パヒャヒャッ、何だか助けが必要そうじゃん？"
"13210-170-ヒカリ" = "ヒーローさんじょー。"
"13210-171-アヤネ" = "あなたたちは……！"
"13210-172-ノゾミ" = "高速鉄道が必要なんでしょ？"
"13210-173-事務官" = "あ、あの……私たちなら砂漠横断鉄道に詳しいですし、#n先ほどはお世話になりましたから……。"
"13210-174-ノゾミ" = "そうそう。#n鉄道のことなら、私たちにも関係あるし。"
"13210-175-ヒカリ" = "そーそー、被害者だしー。"
"13210-176-ノゾミ" = "連れてってやるよ！"
"13210-177-セリカ" = "気が利くじゃない！"
"13210-178-ノノミ" = "うんうん☆#nありがとうございます、ハイランダーの皆さん！"
"13210-179-シロコ" = "ん、ありがとう。"
"13210-180-ノゾミ" = "うぉー、複線ドリフト決めちゃうよー。"
"13210-181-ノゾミ" = "あははっ！#n危ないからちょっとだけにしときなよ？"
"13210-182-アヤネ" = "だ、大丈夫なんですかね？#n安全面的に……。"
"13210-183" = "[ns] \"ありがとう、三人とも。\""
"13210-184-ノゾミ" = "よーし、ちゃっちゃと準備しちゃおうか！"
"13210-185-ノゾミ" = "おーい、準備できたよ！"
"13210-186-ヒカリ" = "ばっちーし。"
"13210-187-セリカ" = "もう乗って良いのね？"
"13210-188-アヤネ" = "ま、待ってください。#nそれ、何を持ってるんですか？"
"13210-189-ヒカリ" = "ヒドラジーン。"
"13210-190-アヤネ" = "えっ、ロケットの推進剤じゃないですか！"
"13210-191-アヤネ" = "どうしてそんな危険な物を！？"
"13210-192" = "あははっ、念のためっしょ。"
"13210-193-ノゾミ" = "ま、使わないと思うけどさー、たぶん。"
"13210-194-ヒカリ" = "メイビー。"
"13210-195" = "だ、大丈夫なんですよね？#n毒物ですし、取り扱いには注意を……。"
"13210-196-セリカ" = "はいはい、大丈夫だってアヤネちゃん。#n何とかなるわよ。"
"13210-197-シロコ" = "ん。"
"13210-198-ヒカリ" = "そ、良いから乗った乗った！"
"13210-199-アヤネ" = "は、はい……分かりました。"
"13210-200-事務官" = "で、では皆さん……ご無事で。"
"13210-201-ヒカリ" = "それじゃ、事務官ちゃんは私らが帰ってくるまで隠れときなよ？#nパヒャヒャッ。"
"13210-202-ヒカリ" = "ゴーゴー。"
"13210-203-アヤネ" = "どこに座りましょう？"
"13210-204-ノノミ" = "わあ～☆#nすごいですね！"
"13210-205-アヤネ" = "あれ……どうして列車にシートベルトが？"
"13210-206-セリカ" = "まあ、ジェットコースターにもあるし、変じゃないでしょ？"
"13210-207-ノノミ" = "うんうん！#nアトラクションに乗ってる気分です！"
"13210-208-ノゾミ" = "全員乗ったぁ？"
"13210-209" = "[s] \"乗ってるよ、運転よろしくね。\""
"13210-210-ヒカリ" = "しゅっぱーつ！"
"13210-211-アヤネ" = "きゃああっ！？"
"13210-212-ノゾミ" = "うぉー。"
"13210-213-ノゾミ" = "この列車、こんなに速度出して良いんだっけ？"
"13210-214-ヒカリ" = "知らなーい。"
"13210-215-ノゾミ" = "パヒャヒャッ！#nま、気にしなくていっか。"
"13210-216-ノゾミ" = "あ、もしかしてピンチの気配ー？"
"13210-217-ヒカリ" = "列車の上に、カイザーPMCのヘリが来てるよー。"
"13210-218-ノゾミ" = "うわっ、"
"13210-219-ノゾミ" = "先頭車両を狙ってるんじゃないの？止めないとやばいっしょ！"
"13210-220-シロコ" = "了解、任せて。"
"13210-221" = "[s] \"出番だね。\""
"13210-222-アヤネ" = "……はい！#n私たちで阻止しましょう！"
