[translation]
"13225-1-PMC兵士A" = "くっ、こいつら……！"
"13225-2-PMC兵士B" = "大破しました！#nど、どうすればっ！"
"13225-3-PMC兵士A" = "くっ……本部に報告しろ！#nこんなところで足止め食らってる場合じゃない！"
"13225-4-PMC兵士C" = "ターゲットです！"
"13225-5-ヒカリ" = "うわっ。降参、降参！"
"13225-6-ヒカリ" = "撃たないでー。#nまずは話し合いでしょー。"
"13225-7-PMC兵士A" = "……違う、こいつらじゃない。#nアビドスの奴らはどこに行った？"
"13225-8-ヒカリ" = "アビドスって？"
"13225-9-ヒカリ" = "孤高の走り屋に乗客はいらなーい。"
"13225-10-PMC兵士C" = "中にも見つかりません！"
"13225-11-PMC兵士C" = "最初から列車に乗っていなかったのでは！？"
"13225-12-PMC兵士A" = "そんなはずは……！"
"13225-13-ヒカリ" = "というか、お茶くらい出してくれたって良いじゃん？"
"13225-14-ヒカリ" = "お菓子食べたーい。"
"13225-15-PMC兵士A" = "な、何だこいつら……。"
"13225-16" = "[ns] \"みんな、大丈夫？\""
"13225-17" = "ん、平気。"
"13225-18" = "……はい、気づかれずに済んだみたいで良かったです。"
"13225-19" = "ちょっとでも飛び降りるのが遅れてたら、見つかってたわね……。"
"13225-20" = "ここからセクター35-9まで、1時間ほどかかる見込みです！"
"13225-21" = "行きましょう！"
"13225-22" = "アビドス砂漠閉鎖地区セクター35-9"
"13225-23-アヤネ" = "……着きました。"
"13225-24-ノノミ" = "ここが執事さんの言っていた分岐駅……。"
"13225-25-セリカ" = "けど、だいぶ前に閉鎖されてるのよね？"
"13225-26" = "ん、あっちの扉が開いてる。"
"13225-27-ノノミ" = "行ってみましょう！"
"13225-28-セリカ" = "ここは……。"
"13225-29-アヤネ" = "管制室でしょうね。"
"13225-30-アヤネ" = "なるほど……これを使えば、色々なエリアへ行けるようになっています。"
"13225-31-アヤネ" = "アビドス市内や大オアシス駅だけでなく、ゲヘナにも。"
"13225-32-アヤネ" = "すでに管理者権限でアクティベートされていますね……。#nおそらく、ノノミ先輩のカードを使って……。"
"13225-33-ノノミ" = "スオウさんだと思います。"
"13225-34-アヤネ" = "……数時間ほど前に、#n二つの列車が生徒会の谷方面に向かっています。"
"13225-35-シロコ" = "片方はホシノ先輩だね。"
"13225-36-アヤネ" = "それでは……。"
"13225-37-アヤネ" = "この車両に乗れば着けるはずです。"
"13225-38-ノノミ" = "もう乗っても大丈夫なんでしょうか？"
"13225-39-アヤネ" = "はい。自動運転で1時間後には、「生徒会の谷」に到着するようになっています。"
"13225-40-シロコ" = "日が暮れる前には着けそうだね。"
"13225-41-セリカ" = "その生徒会の谷に、列車砲があるんだよね？"
"13225-42-シロコ" = "うん。ホシノ先輩が何かする前に追いつかないと。"
"13225-43-セリカ" = "はぁ、手のかかる先輩ね。"
"13225-44-ノノミ" = "スオウさんは、なぜあの場所にホシノ先輩を呼び出したのでしょう。#nいったい何を考えているのか……。"
"13225-45-シロコ" = "行けば分かるはず。"
"13225-46-アヤネ" = "まずは行くしかありません！"
"13225-47" = "[s] \"そうだね、出発しよう。\""
"13225-48-ホシノ" = "ここで合ってるのかな？"
"13225-49-ホシノ" = "もしかして、アレが……。"
"13225-50" = "次回;生徒会の谷"
