[translation]
"13290-1" = "第29話;激戦（２）"
"13290-2-ヒナ" = "……また逃げた？"
"13290-3-ホシノ" = "こっちだよ。"
"13290-4" = "くっ……！"
"13290-5-ホシノ" = "……！"
"13290-6-ホシノ" = "関係者でもない人には……。"
"13290-7-ホシノ" = "[ruby=ど]退[/ruby]いてもらおうかなっ！"
"13290-8" = "ぐっ！"
"13290-9-ホシノ" = "邪魔、しないで……風紀委員長ちゃん！"
"13290-10-ホシノ" = "これは、アビドスの……ううん、私の問題だよ！"
"13290-11-ヒナ" = "関係なら、ある。"
"13290-12-ホシノ" = "……どういうこと？"
"13290-13" = "先生に頼まれたから……とかっ！？"
"13290-14" = "はぁっ……！"
"13290-15" = "#timelineNS;ScCutScene/ScCutScene_13000_03"
"13290-16-ホシノ" = "（このままじゃ、列車がもたない……！）"
"13290-17-ホシノ" = "（……上に出ないと！）"
"13290-18-ホシノ" = "はぁ……はぁ……。"
"13290-19-ヒナ" = "はぁ、はぁ……。"
"13290-20-ホシノ" = "……諦めが悪いねぇ。"
"13290-21-ヒナ" = "そうね、よく言われるかも。 "
"13290-22-ホシノ" = "（風紀委員長ちゃんの目的は、私の大オアシス駅行きの阻止）"
"13290-23-ホシノ" = "（となると……列車を止めるか、私を落とすかの二択が考えられる）"
"13290-24-ヒナ" = "……。 "
"13290-25-ホシノ" = "（先にあっちを落とせば、もう追いつけなくなるはず）"
"13290-26-ホシノ" = "（そのためには……）"
"13290-27" = "#videons2;11006"
"13290-28" = "次回;手帳の存在"
