[translation]
"13365-1-ヒナ" = "――今！"
"13365-2" = "……っ！"
"13365-3-セリカ" = "何この熱さ！"
"13365-4-アロナ" = "先生、熱気は私が何とかします！"
"13365-5-アロナ" = "それよりも、「セトの憤怒」の様子が……急いでください！"
"13365-6" = "[ns] ホシノに手を伸ばす。"
"13365-7-シロコ" = "……先生、どうだった？"
"13365-8" = "[s] \"私じゃダメだ……！\""
"13365-9" = "[ns1] \"[ruby=ひと]他人[/ruby]の死や苦しみは、そう簡単に理解できない……！\"\n[ns2] \"……たとえ、大人であっても！\""
"13365-10" = "[ns] \"けど、みんなだったらきっと……！\""
"13365-11-シロコ" = "……これは、対策委員会にしかできない。"
"13365-12" = "[ns] \"君もだよ、シロコ！\""
"13365-13-シロコ" = "ん、あなたもアビドスでしょ。#n一緒にホシノ先輩を助けて。"
"13365-14-シロコ" = "……覆面水着団の一員として。"
"13365-15" = "そういう意味じゃないから！#nシロコ先輩が調子に乗るじゃない！"
"13365-16-セリカ" = "やっぱりこの人、シロコ先輩だわ……。"
"13365-17" = "急いで！"
"13365-18" = "[ns3] \"みんな、頼んだよ！\"\n[ns4] \"ホシノに、伝えよう！\""
"13365-19" = "次回;伝えなければならないこと"
