[translation]
"1014306-1" = "水遊びの引率"
"1014306-2-シュン" = "こんにちは、先生。#n今日は子供たちのためにお時間を作っていただき、ありがとうございます。"
"1014306-3-シュン" = "みなさん？先生にご挨拶しましょうね。"
"1014306-4-梅花園の園児たち" = "よろしくお願いします、先生！"
"1014306-5" = "[ns] \"よろしくね！\""
"1014306-6" = "（シュンと共に、引率を始めた！）"
"1014306-7-シュン" = "さあ、みなさん。一人ずつプールに入りましょうね。"
"1014306-8-シュン" = "……あら、どうしました？次はあなたの番ですよ？"
"1014306-9" = "[ns] \"具合が悪いの？\""
"1014306-10-梅花園の園児A" = "だって……水怖いもん。プールに入るの、いや。"
"1014306-11-シュン" = "そうだったんですね……。#nでも……水とお友達になれたら、プールはとても楽しいですよ？"
"1014306-12-シュン" = "私もお手伝いするので、チャレンジしてみましょう？"
"1014306-13-梅花園の園児A" = "うん……分かった……。"
"1014306-14-梅花園の園児B" = "これでもくらえー！"
"1014306-15-梅花園の園児C" = "冷たっ！もう……お返しっ！"
"1014306-16-シュン" = "さあ……ここは浅いですから、大丈夫ですよ。"
"1014306-17-シュン" = "私がちゃんと掴んでいてあげますからね。"
"1014306-18-梅花園の園児A" = "ほんと？ぜったいだよ……？"
"1014306-19" = "（子供はシュンの手を握り、ゆっくりとプールの中を歩き始めた）"
"1014306-20" = "（それでもまだ水が怖いようだ……）"
"1014306-21" = "[ns] \"ねぇ、このビート板を両手でしっかり掴んでみてくれる？\""
"1014306-22-シュン" = "先生……？"
"1014306-23-梅花園の園児A" = "こう？"
"1014306-24" = "[ns] \"上手にできてるよ！そしたら、ほらっ……！\""
"1014306-25-シュン" = "せ、先生！？！？"
"1014306-26" = "（ビート板を引っ張って、勢いよく水面を滑らせてあげた）"
"1014306-27-梅花園の園児A" = "わああああああ！？"
"1014306-28-シュン" = "だ、大丈夫！？"
"1014306-29-梅花園の園児A" = "さ、さいこー！"
"1014306-30-シュン" = "えっ……？"
"1014306-31" = "[ns] \"楽しいでしょう！？次はこうだよ！\""
"1014306-32-梅花園の園児A" = "すっごく楽しい！！！"
"1014306-33-シュン" = "……。"
"1014306-34-シュン" = "怖いものを……怖くないものではなく、楽しいものにしてあげるなんて……。"
"1014306-35-シュン" = "さすがは先生です。ふふっ。"
"1014306-36-シュン" = "子供たちがウォータースライダーをやりたいと言うので来たのですが……。#nどうやらみなさん身長が足りないみたいで……。"
"1014306-37-係員" = "さあ、みんな。ウォータースライダーはまだ危ないから、#n他のアトラクションで遊ぼうね。"
"1014306-38-梅花園の園児たち" = "ええー！これやりたい！"
"1014306-39-梅花園の園児A" = "私も、もう水怖くないよ！"
"1014306-40" = "[ns] \"残念だけど、決まりだから仕方ないね……。\""
"1014306-41-梅花園の園児C" = "じゃあ、先生とシュン教官がやってみて！"
"1014306-42-シュン" = "えっ！？"
"1014306-43-梅花園の園児B" = "そうだ！先生とシュン教官はできるんでしょ！どんなのか見てみたい！"
"1014306-44-シュン" = "せ、先生……？"
"1014306-45" = "[ns] \"いいね、やってみようか！\""
"1014306-46-シュン" = "えぇ……！？"
"1014306-47-シュン" = "わ、私もですか……？"
"1014306-48-シュン" = "あのー、先生と一緒にっていうのは……。"
"1014306-49-係員" = "すみません、一人ずつお願いします！"
"1014306-50-シュン" = "ですよね！"
"1014306-51" = "[ns] \"いやっほー！！！\""
"1014306-52" = "（ウォータースライダーを楽しんだ！）"
"1014306-53" = "（大人も十分に満足できるコースだった！）"
"1014306-54-シュン" = "きゃあああぁぁぁっ！？"
"1014306-55" = "[ns] \"シュン！？\""
"1014306-56-シュン" = "た、助けてください！！！"
"1014306-57-シュン" = "はあ、はあ、はあっ……ありがとうございます、先生……。"
"1014306-58-シュン" = "……。"
"1014306-59-シュン" = "ええ。実を言うと、このようなものは苦手で……。"
"1014306-60-シュン" = "た、たしかに……正直に言えば良かったのですが……。"
"1014306-61-シュン" = "子供たちも見ていたので、つい……。"
"1014306-62-梅花園の園児A" = "わあ！シュン教官と先生が抱き合ってる！"
"1014306-63" = "[ns] \"！？！？\""
"1014306-64-梅花園の園児D" = "あれは、吊り橋効果みたいなものだね。"
"1014306-65-梅花園の園児D" = "緊張時のドキドキを、他の感情と勘違いするというものなんだけど……。"
"1014306-66-梅花園の園児D" = "シュン教官なら、それを利用してもおかしくはない……か。"
"1014306-67-シュン" = "！！？？"
"1014306-68-梅花園の園児B" = "君の話は、たまに理解できないよ……。"
"1014306-69-シュン" = "す、すす、すみません！先生！"
"1014306-70" = "[s] \"全然大丈夫だよ！\""
"1014306-71-シュン" = "みなさん、ここが波のプールですよ。"
"1014306-72-シュン" = "まるで本物の海みたいに波が来るんです。"
"1014306-73-シュン" = "今は小さな波が続いていますが、後ですごく大きな波が来ます。"
"1014306-74-シュン" = "そのときは放送案内がありますから、よく聞いていてくださいね。"
"1014306-75-ウォーターパークの案内放送" = "みなさん！大変です！"
"1014306-76-ウォーターパークの案内放送" = "非常に大きな波が近づいています！気をつけてお楽しみください！"
"1014306-77-ウォーターパークの案内放送" = "当ウォーターパークの波の高さは最大2.4メートルなので……。#n十分にご注意ください！"
"1014306-78-梅花園の園児たち" = "おっきな波が来るって！"
"1014306-79-梅花園の園児たち" = "あはははは！"
"1014306-80-梅花園の園児B" = "見て！波乗りできた！"
"1014306-81-シュン" = "みなさん、くれぐれも気を付けてくださいね！"
"1014306-82-梅花園の園児たち" = "先生！シュン教官！お腹が空きました！"
"1014306-83-梅花園の園児たち" = "たこ焼き食べたいです！ホットドッグも！"
"1014306-84" = "[ns] \"順番に買ってあげるから！\""
"1014306-85-シュン" = "みなさん。ちゃんと並んで、いい子で待っていましょうね？"
"1014306-86-梅花園の教官" = "シュン教官も先生も、今日は本当にお疲れさまでした。"
"1014306-87-梅花園の教官" = "こうして時間を作ってくださった先生には、何とお礼を申し上げたらいいのか……。"
"1014306-88" = "[s] \"このくらい、お安い御用ですよ。\""
"1014306-89-シュン" = "いえ、先生には本当に感謝しています……。"
"1014306-90-シュン" = "一日中子供たちの面倒を見ていて、ご自身はほとんど楽しめませんでしたよね……。"
"1014306-91-梅花園の教官" = "では、ここからは私たちで引率するので。"
"1014306-92-梅花園の教官" = "みなさ～ん？[ruby=せんがいきょう]山海経[/ruby]に戻る時間ですよ～"
"1014306-93-梅花園の園児たち" = "ええー……。もっと遊びたいのに……。"
"1014306-94-梅花園の教官" = "わがまま言っちゃダメですよ。みなさんは、時間を守れる良い子ですよね？"
"1014306-95-梅花園の園児たち" = "はーい。"
"1014306-96-シュン" = "……。"
"1014306-97-シュン" = "一日があっという間でしたね。"
"1014306-98" = "[s] \"シュンもお疲れさま。\""
"1014306-99-シュン" = "いえ、私はいつものことですから。"
"1014306-100-シュン" = "あの、先生。"
"1014306-101-シュン" = "先ほど、ふと思いついたんですが……。"
"1014306-102-シュン" = "少しだけでいいので……これからこっそり、遊びま……せんか？"
"1014306-103" = "[ns] \"……！\""
"1014306-104" = "[ns] \"遊ぼう！\""
"1014306-105-シュン" = "はい♡"
"1014306-106" = "（そうしてシュンと一緒に、思い切り楽しんだ）"
"1014306-107" = "（楽しみ過ぎたあまり、終電を逃しそうになった……）"
