[translation]
"1601903-1" = "趣味（仮）"
"1601903-2-トキ" = "では偵察の結果を報告いたします。"
"1601903-3-トキ" = "結論から言えば、特に大したことはありませんでした。"
"1601903-4" = "[s] \"それはよかった。\""
"1601903-5-トキ" = "はい。いくつかを破壊して爆発させ、ついでにストレス発散になりました。"
"1601903-6" = "[s] \"大したことあった！？\""
"1601903-7-トキ" = "ですが、ここは本当に不思議な場所です。"
"1601903-8-トキ" = "偵察に出る度に、同じ座標でも何かが変化しています。"
"1601903-9-トキ" = "唯一の共有点としては、すべてが金属だということですね。"
"1601903-10-トキ" = "座標情報がなければ、遅からず迷子になっていたでしょう。"
"1601903-11-トキ" = "まるで、迷路に立ち入るような気分です。"
"1601903-12" = "[s1] \"なんだかすごく危険そうだけど……。\"\n[s2] \"無理に偵察しなくていいからね……。\""
"1601903-13-トキ" = "それは困ります。"
"1601903-14-トキ" = "先生は前線に出ないのでご存知ないかもしれませんが……。"
"1601903-15-トキ" = "先ほども、金属でできた動物のようなものが3匹、こちらに向かって突進してきました。"
"1601903-16" = "[s] \"危なくなかった！？\""
"1601903-17-トキ" = "はい、たしかに危険でした。"
"1601903-18-トキ" = "可愛さのあまり、気を失うくらいでしたので！"
"1601903-19" = "[s] \"……え？\""
"1601903-20-トキ" = "私が近づくと、地面に転がってお腹を見せてくれたのです。"
"1601903-21-トキ" = "撫でてやると、とても喜んでいました。"
"1601903-22" = "[s3] \"う、羨ましい……！\"\n[s4] \"でも、それって本当に金属の動物なの……？\""
"1601903-23-トキ" = "おそらくは。"
"1601903-24-トキ" = "少なくとも感触は金属そのものでしたので。"
"1601903-25-トキ" = "1匹連れて帰りたかったのですが、遊び終わるとどこかへ去ってしまいました。"
"1601903-26-トキ" = "……以上、報告終了です。"
"1601903-27" = "[s] \"そういうことなら私も混ぜてよ！\""
"1601903-28-トキ" = "残念ですが、これは現場担当の特権です。ぶいっ。"
"1601903-29-トキ" = "とはいえ、ここで見聞きしたことのすべてが機密扱いなのは残念ですね。"
"1601903-30-トキ" = "配信で語れないですから。"
"1601903-31" = "[s] \"配信？\""
"1601903-32-トキ" = "おや、ご存知ないのですか？"
"1601903-33-トキ" = "まさか、先生が時代遅れだったなんて。"
"1601903-34-トキ" = "ですが大丈夫です。私が一生補佐して差し上げますので。"
"1601903-35" = "[s5] \"配信は私も知ってるよ！\"\n[s6] \"トキがそういう話をするのが新鮮だったんだ。\""
"1601903-36-トキ" = "おや、ご存知ないのですか？"
"1601903-37-トキ" = "まさか、先生が生徒に無関心だったなんて。"
"1601903-38-トキ" = "見てください、しょんぼりしてしまった私を。"
"1601903-39-トキ" = "寂しさと悲しみのあまり、体中の力が抜けてしまいました。"
"1601903-40-トキ" = "これは先生が無関心だったせいです。"
"1601903-41-トキ" = "ですので先生は、迅速に私をナデナデすべきです。"
"1601903-42" = "（トキの頭を撫でてあげた……）"
"1601903-43-トキ" = "良いですね。"
"1601903-44-トキ" = "これで元気回復、パーフェクトです。"
"1601903-45" = "[s] \"よかったね……。\""
"1601903-46-トキ" = "では話を戻しましょう。"
"1601903-47-トキ" = "以前、趣味を探してみたら、とアドバイスをいただきましたので、#n色々と試してみたのです。"
"1601903-48-トキ" = "そのうちに、配信というものに興味を持つようになりまして。"
"1601903-49-トキ" = "その中でも、投げ銭という文化が印象的ですね。"
"1601903-50-トキ" = "投げられる金額に応じて、配信者の反応が変わっていくのです。"
"1601903-51-トキ" = "配信者と視聴者の構図がとても興味深いと思いました。"
"1601903-52" = "[s] \"トキ……何か変なことはしてないよね……？\""
"1601903-53-トキ" = "していません。"
"1601903-54-トキ" = "私はただ観ているだけですので。"
"1601903-55-トキ" = "生配信以外にも、動画も面白いものが多いです。たとえば――"
"1601903-56-トキ" = "なんでもゲーム実況まとめ"
"1601903-57-トキ" = "【悲報】ハイランダーのマスコット「シュッポ」実は不人気？"
"1601903-58-トキ" = "またもや敗北、コーギー・ブレーブスファンの反応集"
"1601903-59-トキ" = "ゲルマニウム×マイナスイオンの相関関係について"
"1601903-60-トキ" = "ペロロの正体、実はカバだったｗｗｗ"
"1601903-61" = "[s] \"……。\""
"1601903-62-トキ" = "……。"
"1601903-63-トキ" = "この世は多様性に満ちていますね。"
"1601903-64" = "[s7] \"わ、私はどうすれば……。\"\n[s8] \"トキが変なものに染まってしまった……。\""
"1601903-65-トキ" = "大丈夫です。染まっていません。"
"1601903-66-トキ" = "……まだ。"
"1601903-67-トキ" = "ですが私ですらハードルが高いと感じたチャンネルがありました。"
"1601903-68-トキ" = "……チャンネル名ですか？"
"1601903-69-トキ" = "たしか……。"
"1601903-70-トキ" = "少女忍法帖ミチルっち……とかいう名前でした。"
"1601903-71" = "[s] \"……。\""
"1601903-72-トキ" = "こう……色々なチャレンジをするという内容でして、最後まで観ようとしたのですが……。"
"1601903-73-トキ" = "なかなか難しくて……強敵でした。"
"1601903-74-トキ" = "いつかは私も強くなるはずですが、少なくとも今はまだ早かったようです。"
"1601903-75" = "[s] \"そういうのには強くならなくていいんじゃないかな……。\""
"1601903-76-トキ" = "そうなのですか？#nおっしゃる意味がよく分かりませんが……。"
"1601903-77-トキ" = "はい？他にもあるのか、とは？"
"1601903-78-トキ" = "ああ、趣味ですか。一応あります。"
"1601903-79-トキ" = "ですが先生。配信を観ることも他の趣味も、あくま[ruby=かっこかり]で（仮）で[/ruby]す。"
"1601903-80-トキ" = "差し当たって興味があるだけで、いつかコロッと変わるかもしれません。"
"1601903-81-トキ" = "だって、私の本当の趣味は――"
"1601903-82-トキ" = "……。"
"1601903-83-トキ" = "この話はここまでにしましょう。"
"1601903-84" = "[s] \"話を逸らすのが上手になったね！\""
"1601903-85-トキ" = "これも先生のおかげです。"
"1601903-86-トキ" = "私は日々成長を重ねる[ruby=あすま]飛鳥馬[/ruby]トキですので。"
"1601903-87" = "[s] \"そ、そうだね……。\""
"1601903-88-トキ" = "人は常に周りからの影響を受けています。"
"1601903-89-トキ" = "そうして、少しずつ成長していくのです。"
"1601903-90-トキ" = "ですから……。"
"1601903-91-トキ" = "……。"
"1601903-92-トキ" = "ゲームも面白かったです。"
"1601903-93-トキ" = "マンガも。"
"1601903-94" = "[s] \"ゲーム開発部のみんなと話が合いそうだね。\""
"1601903-95-トキ" = "はい。まさにアリスが良いライバルになっています。"
"1601903-96-トキ" = "今は私が1試合負け越していますが、すぐに巻き返せると思います。"
"1601903-97-トキ" = "それに比べてユズは……。"
"1601903-98" = "[s] \"次元が違うんじゃないかな……。\""
"1601903-99-トキ" = "先生もよくご存知ですね……。"
"1601903-100-トキ" = "あまりにも強い相手を前にすると、悔しいという感情すら湧かないことに気づきました。"
"1601903-101-トキ" = "地震や台風のような自然災害の前で……人はただ無力なだけですから。"
"1601903-102" = "[s] （ユズは自然災害級なのか……）"
"1601903-103" = "（他愛もない話をしながら仕事を終え、トキと一緒に色んなチャンネルを観た）"
"1601903-104" = "（肩に重みを感じて横を見ると、いつの間にかトキは眠っていた）"
