[translation]
"1601906-1" = "朝焼けの記憶"
"1601906-2-トキ" = "――もちろん、私たちの防御システムに隙はありません。#n他でもないリオ様が作りましたので。"
"1601906-3-トキ" = "ですが想定外の事態には常に備えておくべきです。"
"1601906-4-トキ" = "ここは、常識が通用しない場所ですから。"
"1601906-5" = "[s] \"やっぱりトキは頼もしいね。\""
"1601906-6-トキ" = "ありがとうございます。"
"1601906-7-トキ" = "ですが、明け方の偵察には別の理由もあるのです。"
"1601906-8" = "[s] \"それは？\""
"1601906-9-トキ" = "もうすぐ分かります。"
"1601906-10-トキ" = "……ちょうど良いですね。"
"1601906-11-トキ" = "先生。あちらをご覧ください――"
"1601906-12" = "[wa:2060]― [log=토키 결전]綺麗な朝焼けですね。[/log]"
"1601906-13" = "― [log=토키 결전]ここでは毎日、[wa:1670]この景色が[wa:510]観測できます。[/log]"
"1601906-14" = "[wa:730]― [log=토키 결전]といっても、[wa:1120]ここに来てからの[/log]"
"1601906-15" = "― [log=토키 결전]数日分しか[wa:750]記録はないので……。[/log]"
"1601906-16" = "― [log=토키 결전]毎日ではないのかも[wa:920]しれませんが。[/log]"
"1601906-17" = "[ns] \"すごく綺麗だね……。\""
"1601906-18" = "#wait;1000"
"1601906-19" = "[wa:1070]― [log=토키 결전]はい。[wa:1460]でも、[wa:1030]ここからだと[/log]"
"1601906-20" = "― [log=토키 결전]全く違った色に[wa:810]感じられるんです。[/log]"
"1601906-21" = "― [log=토키 결전]空も……[/log]"
"1601906-22" = "― [log=토키 결전]橙色に輝く[wa:1110]大地も……。[/log]"
"1601906-23" = "[wa:890]― [log=토키 결전]私は、[wa:1080]先生と[wa:630]こうして景色を共有する[wa:1140]時間が好きです。[/log]"
"1601906-24" = "― [log=토키 결전]心が動いたものを[wa:1780]こうして伝えられる[wa:1490]このひと時が……。[/log]"
"1601906-25" = "[wa:1900]― [log=토키 결전]この一瞬は、[wa:1410]いまこの時間しか[wa:740]存在しません。[/log]"
"1601906-26" = "― [log=토키 결전]そして、[wa:1190]二度と戻ってこない。[/log]"
"1601906-27" = "[wa:2510]― [log=토키 결전]先生。[/log]"
"1601906-28" = "― [log=토키 결전]もしも今、[wa:1360]「最後」の時が[wa:690]訪れたら――[/log]"
"1601906-29" = "[wa:730]― [log=토키 결전]私は、[wa:1270]先生のそばで[wa:1610]その瞬間を共にする……。[/log]"
"1601906-30" = "― [log=토키 결전]「最後」の一人に[wa:770]なれますか？[/log]"
"1601906-31" = "[ns] \"これが、トキのお気に入りなんだね。\""
"1601906-32-トキ" = "はい。"
"1601906-33-トキ" = "もちろん、これが相反する感情だということは分かっています。"
"1601906-34-トキ" = "どうしたって、ここは敵地です。"
"1601906-35-トキ" = "良いと思えるものを見つけたとしても……次の瞬間には、致命的な結果を招くきっかけになる可能性があります。"
"1601906-36-トキ" = "ですが……人は身勝手な生き物なんですよね。"
"1601906-37-トキ" = "状況に関わらず、自分が良いと感じれば、その状況を良いものだと捉えてしまうのですから。"
"1601906-38" = "[s] \"美しいものを美しいと感じるのは良いことだと思うよ。\""
"1601906-39" = "[ns1] \"だってそれは――\"\n[ns2] \"希望を失わないという証拠だからね。\""
"1601906-40-トキ" = "……なるほど。"
"1601906-41-トキ" = "……はい？#n「最後の時が訪れる」とか「最後の一人」とかの表現は少し怖かった？"
"1601906-42-トキ" = "……。"
"1601906-43-トキ" = "たしかに、そうかもしれません。#n「最後」は怖いものです。"
"1601906-44-トキ" = "でも大丈夫です。先生のそばには私がいます。"
"1601906-45-トキ" = "何より……その訪れは、絶対に私が阻止します。"
"1601906-46-トキ" = "そのために、私は武装をしてまでここにいるのですから。"
"1601906-47-トキ" = "……朝焼けが終わってしまいましたね。#n良い時間はあっという間に過ぎてしまうものです。"
"1601906-48-トキ" = "……。"
"1601906-49-トキ" = "このまま、時が止まればいいのに。"
"1601906-50-トキ" = "大切な記憶を集めて――"
"1601906-51-トキ" = "ずっと大事にとっておくことができたら。"
"1601906-52" = "[ns3] \"そうだね。きっと素敵だと思うよ。\"\n[ns4] \"でも……一緒に居る「今」も素敵じゃない？\""
"1601906-53-トキ" = "……。"
"1601906-54-トキ" = "そう、ですね……。"
"1601906-55-トキ" = "私と、先生と……。"
"1601906-56-トキ" = "……。"
"1601906-57-トキ" = "先生。"
"1601906-58" = "[s] \"うん？\""
"1601906-59-トキ" = "少し、じっとしていてください。"
"1601906-60" = "（トキはそう言うと――）"
"1601906-61" = "（そっと、抱きしめてきた）"
"1601906-62" = "[ns] \"トキ！？\""
"1601906-63-トキ" = "しーっ。誰かが起きてしまうかもしれません。"
"1601906-64-トキ" = "少しだけ……ほんの少しでいいのです。"
"1601906-65-トキ" = "……。"
"1601906-66-トキ" = "時を止めることは叶いませんから……。"
"1601906-67-トキ" = "深く……記憶に刻ませてください。"
"1601906-68-トキ" = "……ありがとうございます、先生。"
