[translation]
"10009020-1" = "第2話;襲撃その二"
"10009020-2" = "矯正局東支部・第6矯正施設"
"10009020-3-ワカモ" = "まさか脱出を試みるとは。"
"10009020-4-ワカモ" = "だが矯正局に着いた以上、もうこれ以上の反抗は無駄だぞ。災厄の狐よ。"
"10009020-5-ワカモ" = "さあ、おとなしく中に入れ！"
"10009020-6-ワカモ" = "……ふむ、"
"10009020-7-ワカモ" = "相変わらず潔癖さの欠片も無い場所ですねぇ。"
"10009020-8-ヴァルキューレの生徒B" = "文句を言える立場か。直に警備局長が来て、尋問を行う。"
"10009020-9-ヴァルキューレの生徒B" = "言い訳は無用。狙いは何だったのか、しっかり説明できるように考えておけよ。"
"10009020-10-ヴァルキューレの生徒A" = "そうでないと、元々の分に加えてどんどん罪状と刑期が増えていくぞ。"
"10009020-11-ワカモ" = "尋問……ですか。まあ構いません。"
"10009020-12-ヴァルキューレの生徒A" = "何だ、思ったより協力的……"
"10009020-13-ワカモ" = "黙秘権を行使します。"
"10009020-14-ヴァルキューレの生徒B" = "なっ、"
"10009020-15-ヴァルキューレの生徒B" = "お前自分の状況が分かってるのか！？"
"10009020-16-ワカモ" = "ふふっ、もちろんです。だからこそ黙秘権を行使します。"
"10009020-17-ワカモ" = "先生以外の誰にも、言葉を紡ぐつもりはありません。"
"10009020-18-ヴァルキューレの生徒B" = "先生……あの、シャーレの？"
"10009020-19-ヴァルキューレの生徒B" = "さっき現場で助けてくれた、あの先生？"
"10009020-20-ヴァルキューレの生徒A" = "おっ、お前はそもそも、その先生を襲撃しようとしていただろう！それを知って、連れてくるとでも思ったか！？"
"10009020-21-ワカモ" = "ふふふ……"
"10009020-22-ワカモ" = "なるほど、そうですか。"
"10009020-23-ヴァルキューレの生徒B" = "ん……？"
"10009020-24-ワカモ" = "あなたたちも、私の「目的」を邪魔するということですね。"
"10009020-25-ワカモ" = "でしたら、私にも考えがあります。ふふふっ……♡"
"10009020-26-ヴァルキューレの生徒たち" = "……？"
"10009020-27" = "（セナと一緒にパトロールを再開し、しばらくした頃……）"
"10009020-28-フブキ" = "先生！今、ワカモが矯正局を脱出したって……！"
"10009020-29" = "[s] \"……また脱出？\""
"10009020-30-ワカモ" = "ふふふっ……"
"10009020-31-ワカモ" = "絶対に、絶対に逃しませんよ。"
