[translation]
"10009055-1-ワカモ" = "……もう少し、もう少しです。"
"10009055-2-ワカモ" = "待っていてください。あと少しすれば、私の手で直に……"
"10009055-3-ワカモ" = "……！"
"10009055-4-セナ" = "そこまでです。"
"10009055-5-ワカモ" = "あなたは、あの時先生のそばにいた……。"
"10009055-6-セナ" = "どうして先生を狙っているのかは分かりませんが……"
"10009055-7-セナ" = "危険は、その芽が出ぬうちに。"
"10009055-8-ワカモ" = "……ふふふっ、左様ですか。"
"10009055-9-セナ" = "余計な抵抗はしないように、すでに――"
"10009055-10-ヴァルキューレの生徒A" = "見つけた、もう逃さないぞ！災厄の狐め！"
"10009055-11-ヴァルキューレの生徒B" = "そこまでだ、ワカモ！"
"10009055-12-ヴァルキューレの生徒A" = "今度こそ……今度こそ逃さないからな！？"
"10009055-13-ヴァルキューレの生徒B" = "これ以上逃したら、成績に影響が……！"
"10009055-14-キリノ" = "お、おっ、おとなしく投降してください！"
"10009055-15-フブキ" = "はぁーっ……もうすでに疲れた……。"
"10009055-16-ワカモ" = "チェックメイト、だと思いますが？"
"10009055-17-ワカモ" = "……なるほど、まあ構いません。"
"10009055-18-ワカモ" = "ふふふっ……どうせ、もうこれっきりです。"
"10009055-19-セナ" = "……？"
"10009055-20-ワカモ" = "もうすぐ……"
"10009055-21-ヴァルキューレの生徒A" = "に、逃がすかっ！"
"10009055-22-ヴァルキューレの生徒B" = "捕まえろーっ！"
"10009055-23-フブキ" = "……ってわけで、無事捕まえられて何より！"
"10009055-24-キリノ" = "何だか、今まで以上に抵抗が激しかったですね……。"
"10009055-25-セナ" = "……どうしても気になりますね、最後の言葉。"
"10009055-26" = "[s] \"セナ？\""
"10009055-27-セナ" = "……いえ、考えすぎかもしれません。"
"10009055-28-セナ" = "それより、これで計五回目の脱出ですか……"
"10009055-29-セナ" = "もしかしてですが、ヴァルキューレ警察学校というのは……"
"10009055-30-チヒロ" = "色んな側面でダメダメだね。セキュリティ意識が低すぎる。"
"10009055-31" = "[s] \"チヒロ！\""
"10009055-32-チヒロ" = "やぁ、先生。ちょうど今、その辺のセキュリティの点検を一通り終わらせてきたところ。"
"10009055-33-チヒロ" = "思ったより早い再会だったね。まあその割に、また色々と起きてたみたいだけど……。"
"10009055-34-チヒロ" = "とりあえず、この辺一帯のセキュリティは大丈夫。ヴェリタスでちゃんと見て、必要な分は微調整しておいたから。"
"10009055-35-チヒロ" = "でも一番大きな問題があって……治安維持の要を担ってるはずのヴァルキューレ、そのセキュリティが酷いのなんのって。"
"10009055-36-チヒロ" = "ねぇ、色々と大丈夫？"
"10009055-37" = "[s] \"まあ、これまでの経緯を見てると多分その通りなんだろうね……。\""
"10009055-38-フブキ" = "ま、まぁ反論の余地は無いけど……で、"
"10009055-39-フブキ" = "でもほら！"
"10009055-40-キリノ" = "そ、そうです！あのようにまた捕まえましたので！"
"10009055-41-キリノ" = "それに先ほどまでの事態を受けて、警備局長もとっておきの対策を行うと仰ってましたし！"
"10009055-42" = "[s] \"とっておきの対策？\""
"10009055-43-フブキ" = "うん。ワカモがこう何度も何度も脱獄を繰り返すせいで、警備局長もついに顔が真っ青になっちゃってさ。"
"10009055-44-フブキ" = "ちゃんと力不足を認めて、他の学校の治安維持組織とかと連携して対応に当たるって言い始めたらしいよ。"
"10009055-45-キリノ" = "ちょうど、経験者と言いますか。以前「災厄の狐」さんが脱獄した際に、先生と一緒に対応されていた方々と連絡が取れまして。"
"10009055-46" = "[s] \"あ、っていうことはもしかして……。\""
"10009055-47-スズミ" = "そういうことです。お待たせしました、先生。"
"10009055-48-ハスミ" = "よりによってバレンタインデーに暴れるだなんて……。"
"10009055-49-スズミ" = "せっかく皆さんが楽しまれているところを、荒らさせるわけにはいきませんから。"
"10009055-50-チナツ" = "「災厄の狐」と交戦したのは数回程度ですが、それでも何かお役に立てるのであれば。そういうことで、風紀委員会より参りました。"
"10009055-51-ハスミ" = "そういうことで……よろしくお願いしますね、チナツさん。"
"10009055-52-チナツ" = "はい、せっかくのイベントですし。"
"10009055-53-ユウカ" = "何だか久しぶりね、この面子……。"
"10009055-54-ユウカ" = "とにかく私たちも協力しますので、安心してください。"
"10009055-55" = "[s] \"みんな、ありがとう！\""
"10009055-56-キリノ" = "よろしくお願いします！"
"10009055-57-キリノ" = "それに、ヴァルキューレ側も勿論警備の規模を拡大していますから、もうネズミ一匹逃がしませんよ！"
"10009055-58-フブキ" = "ってわけで、今度こそ私たちを信じてよ？"
"10009055-59-チヒロ" = "……念のため、私も合流する。"
"10009055-60-チヒロ" = "放っておくには心配すぎるし。"
"10009055-61" = "[s] \"チヒロとユウカのコンビ！\""
"10009055-62-ユウカ" = "えっ、あ、ヴェリタスの……？"
"10009055-63-ユウカ" = "ま、まあ、そうですね。あのヴェリタスの副部長ですから、すっごく心強くは……"
"10009055-64-チヒロ" = "珍しいね、セミナーのごますりなんて。先生の前だからかな？"
"10009055-65-チヒロ" = "まあ、珍しいものとして有難く受け取っておくよ。"
"10009055-66-ユウカ" = "……っ！"
"10009055-67-チヒロ" = "じゃ、"
"10009055-68-チヒロ" = "行ってくるね。先生。"
"10009055-69" = "[s] \"うん、気を付けてね。\""
"10009055-70-セナ" = "あそこまで揃っているなら、それなりに安心できそうですね。"
"10009055-71-セナ" = "では。最後までパトロール頑張りましょうか、先生。"
"10009055-72" = "[s] \"……うん、そうだね。\""
