[translation]
"10009025-1-フブキ" = "いやー、無事に捕まえられて良かったー！"
"10009025-2-キリノ" = "先生、ありがとうございます！本当に助かりました！"
"10009025-3" = "[s] \"今度は矯正局から脱出……？\""
"10009025-4-キリノ" = "はい。どうやらその矯正局の施設は、かなり老朽化が進んでいたとかで……。"
"10009025-5-フブキ" = "その隙を突かれちゃったみたいだね。いやー、怖い怖い。"
"10009025-6-キリノ" = "さすがは「災厄の狐」さんと言ったところでしょうか……。"
"10009025-7" = "[s] \"それ以前の問題のような……？\""
"10009025-8-フブキ" = "まあまあ、流石に予想外のアクシデントだったからしょうがないよ。"
"10009025-9-フブキ" = "でも大丈夫。次は別の、「最新式の設備が導入された施設」に移監することにしたから！"
"10009025-10-キリノ" = "はい、今度こそ大丈夫です！お任せください！"
"10009025-11" = "[s] \"えっと……うん、お疲れ様。頑張ってね。\""
"10009025-12-セナ" = "では先生、パトロールを続けましょうか。"
"10009025-13" = "[s] \"セナは本当に冷静だね……。\""
"10009025-14" = "（若干の不安を残しつつ、パトロールを再開することにした）"
