[translation]
"10035095-1-キリノ" = "はぁ、はぁ……。"
"10035095-2-キリノ" = "メカワニ、完全停止！"
"10035095-3-キリノ" = "無事、倒したようです！"
"10035095-4-フブキ" = "うん、エンジンから煙が出てるね。今度こそ制圧完了か。"
"10035095-5-ラブ" = "ふっ……ふふっ！"
"10035095-6-ラブ" = "はははははっ！"
"10035095-7-ラブ" = "なんだ！ワニのやつ！弱いじゃないの！はははっ！"
"10035095-8-フブキ" = "さっきまで逃げ回ってたくせに……。"
"10035095-9" = "[ns] \"みんな、お疲れさま。\""
"10035095-10-カンナ" = "先生の指揮のおかげです。"
"10035095-11-カンナ" = "今回もありがとうございました。"
"10035095-12-ウォーターパークのオーナー" = "わ、ワニはあそこだ！撃てぇぇっ！！"
"10035095-13" = "オーナー、もう倒れています！"
"10035095-14-ウォーターパークのオーナー" = "……ん？"
"10035095-15-ウォーターパークのオーナー" = "そうか。こ、こほん……。"
"10035095-16-カンナ" = "……メカワニの制圧は完了しました。"
"10035095-17-カンナ" = "後のことは、お任せしてもよろしいですか。"
"10035095-18-ウォーターパークのオーナー" = "え、ええ！"
"10035095-19-ウォーターパークのオーナー" = "お前たち、こっちだ！"
"10035095-20-ウォーターパークのオーナー" = "まず怪我人を医務室に！お客様のサポートを優先しろ！"
"10035095-21-一同" = "はいっ！"
"10035095-22-ウォーターパークの警備兵A" = "いたた……避難する時に、足を挫いてしまって……。"
"10035095-23-ウォーターパークの警備兵A" = "医務室までご案内いたします。"
"10035095-24-ウォーターパークの利用客B" = "す、すみません！はぐれた友人を探しているんです……！"
"10035095-25-ウォーターパークの警備兵B" = "特徴をお教えください。"
"10035095-26" = "[ns1] \"もう大丈夫そうだね……。\"\n[ns2] \"無事に解決したみたい。\""
"10035095-27-フブキ" = "不幸中の幸いってやつだね。"
"10035095-28-フブキ" = "屋内で暴れられたら、大惨事になってたかも。"
"10035095-29-キリノ" = "はい、重傷者もないようで、安心しました。"
"10035095-30-キリノ" = "これで一件落着ですね！"
"10035095-31-ラブ" = "まあ、メカワニを倒したのはいいけどさ。"
"10035095-32-ラブ" = "まだ気になることが残ってるんじゃない？"
"10035095-33-キリノ" = "はい？"
"10035095-34-ラブ" = "さっき、ワニが狂犬の方に突進した時――"
"10035095-35-ラブ" = "ワニのやつ、急に動きを止めてたでしょ。"
"10035095-36-ラブ" = "あれのおかげで制圧する隙ができたけど……。#nなんで止まったの？"
"10035095-37-キリノ" = "偶然じゃないのー？一瞬、バグったとかさ。"
"10035095-38-キリノ" = "局長を見て、怖くなって避けたんじゃないですか？"
"10035095-39-ラブ" = "そんなわけないじゃん。"
"10035095-40-ラブ" = "狂犬、何かやらかしたんじゃないの？"
"10035095-41-カンナ" = "いや、私は何もしていない。"
"10035095-42-ラブ" = "じゃあ、さっきのはどう説明すんのさ？"
"10035095-43-カンナ" = "……私にもよく分からないんだ。"
"10035095-44" = "[s] \"メカワニを分析すれば分かりそう。\""
"10035095-45-キリノ" = "だね。放置するわけにもいかないし、ちょっと解体してみよっか。"
"10035095-46-キリノ" = "勝手に手を出して、いいものなんでしょうか？"
"10035095-47-ラブ" = "別にいいんじゃないの？どうせもう鉄の塊でしょ。"
"10035095-48-フブキ" = "どれどれ……へぇ、結構いい仕上がりだねぇ。"
"10035095-49-キリノ" = "はい。溶接の具合からして、かなり腕のある職人さんが作ったようです……。"
"10035095-50-ラブ" = "職人がこんなもの作るわけないでしょ？"
"10035095-51-ラブ" = "いいから開けてみるわよ。"
"10035095-52" = "[ns3] \"すごく複雑な構造だね……。\"\n[ns4] \"中を見ても、よく分からない。\""
"10035095-53-フブキ" = "いやぁ、こんな配線初めて見たよ……。素人の出る幕じゃないね。"
"10035095-54-キリノ" = "み、見ただけで、目が回りそうです……。"
"10035095-55-ラブ" = "ちっ！作ったやつの名前ぐらい書いておきなさいよ！"
"10035095-56-？？？" = "あっ、あそこだ！"
"10035095-57" = "[ns5] \"あれ……？\"\n[ns6] \"この声は……？\""
