[translation]
"10035160-1" = "後日談その5;局長がいない公安局の一日"
"10035160-2-公安局の生徒" = "副局長、カンナ局長が本日不在ですから。#n代わりに書類の確認をお願いできますか。"
"10035160-3" = "はぁぁ……。"
"10035160-4-コノカ" = "はぁぁ……。"
"10035160-5-コノカ" = "姉御をウォーターパークに送ったのはいいものの……。"
"10035160-6-公安局の生徒" = "まずは、この書類に捺印をお願いします。"
"10035160-7-コノカ" = "はいはい。"
"10035160-8-コノカ" = "姉御のぉぉ～～ハンコぉぉぉ～～どこぉぉぉぉ～～。"
"10035160-9-コノカ" = "あった。"
"10035160-10-コノカ" = "……んあぁ、なんっすか、この書類の山は。"
"10035160-11-コノカ" = "あー、だるっ。"
"10035160-12-コノカ" = "えっとー。公安局の食堂リフォーム計画、はい承認。"
"10035160-13-コノカ" = "地下の取調室に窓を設置する提案？"
"10035160-14-コノカ" = "なんだぁ、これ？却下ぁ。"
"10035160-15-コノカ" = "カツ丼の注文先変更の申請。承認。"
"10035160-16-公安局の生徒" = "（意外に仕事が早い……）"
"10035160-17-公安局の生徒" = "（これなら今日中に終わるかも。）"
"10035160-18-コノカ" = "もー！やりたくない。"
"10035160-19-公安局の生徒" = "ええ？もうですか！？"
"10035160-20-コノカ" = "ってさぁ、書類仕事なんてあたしには合わないっつーの。#nだるすぎるって。"
"10035160-21-公安局の生徒" = "ですが、副局長、これは今日中に終わらせる必要が……。"
"10035160-22-コノカ" = "まぁ、わかってるけどさ……。"
"10035160-23-コノカ" = "ぶっちゃけさぁ。あんたもだるいんじゃない？"
"10035160-24-公安局の生徒" = "は、はい！？"
"10035160-25-コノカ" = "遠慮しなくていいって。#n事務所んなかで書類と睨めっこすんのが、好きなヤツなんていないっしょ。"
"10035160-26-公安局の生徒" = "し、しかし！"
"10035160-27-公安局の生徒" = "こ、これも公安局の大事な仕事で――"
"10035160-28-コノカ" = "んな建前はいいって。"
"10035160-29-コノカ" = "本音で行こう。#nねえ、あんたもさ、プール行きたいっしょ？"
"10035160-30-公安局の生徒" = "……はい？"
"10035160-31-コノカ" = "だよねぇ。あぁ～あ。しゃあねえなぁ！"
"10035160-32-コノカ" = "部下のお願いを聞くのも、副局長の仕事だ！"
"10035160-33-コノカ" = "あ、あ――……。待機中の公安局員の諸君、よく聞け。"
"10035160-34-コノカ" = "ずっと後回しにしていた公安局の必須実習項目、#n「戦闘水泳」――本日午後から実施するぞ！"
"10035160-35-公安局の生徒" = "い、いきなりですか！？"
"10035160-36-コノカ" = "来たぞ！"
"10035160-37-コノカ" = "ヴァルキューレ警察学校が誇る屋外水泳訓練所！"
"10035160-38-コノカ" = "カンナの姉御も今頃夏を満喫してるだろうし、あたしらだって負けちゃいけねえ！"
"10035160-39-コノカ" = "んじゃ、手始めに200往復からスタートだ！"
"10035160-40-コノカ" = "お前らぁ！準備はいいか！"
"10035160-41-公安局の生徒B" = "え？い、いきなり200往復？冗談ですよね？"
"10035160-42-公安局の生徒B" = "副局長はできるかもしれませんが……、私たちには無理ですよ？"
"10035160-43-コノカ" = "あぁ？無理？"
"10035160-44-コノカ" = "公安局の辞書に「無理」なんて単語はねえだろ？"
"10035160-45-コノカ" = "あんなもん、手足をちょこっとパタパタすりゃあ終わりだ！"
"10035160-46-一同" = "あ、はい……。"
"10035160-47-コノカ" = "声が小さいっっ！"
"10035160-48-一同" = "はいっ！副局長！"
"10035160-49-コノカ" = "うっす！それでこそだ！"
"10035160-50-コノカ" = "パパッと終わらせて、豚骨ラーメンでも食いに行くぞ！#nニンニクマシマシでな！あたしが奢ってやる！"
"10035160-51-公安局の生徒A" = "私はケーキか、マカロンがいいのに……。"
"10035160-52-公安局の生徒B" = "副局長の好みなんだから、仕方ないよ。"
"10035160-53-コノカ" = "そこ、私語は禁止だぞ！"
"10035160-54-コノカ" = "んじゃ、あたしがお手本を見せてやるから――"
"10035160-55-コノカ" = "はぇ？あ、あれは――"
"10035160-56-公安局の生徒B" = "あ、可愛い黒猫だ！……うーん、行っちゃったかあ。"
"10035160-57-公安局の生徒B" = "副局長？どうしたんですか。はやくお手本をお願いします。"
"10035160-58-コノカ" = "あ……えっと、その……。"
"10035160-59-コノカ" = "（黒猫……不吉の象徴……）"
"10035160-60-コノカ" = "（そういえば、朝食に出たおかずの豆も、4粒だった……）"
"10035160-61-コノカ" = "（それに、先週見つけた四つ葉のクローバーを持ってこなかったような……）"
"10035160-62-コノカ" = "（不吉だ……）"
"10035160-63-コノカ" = "（不吉だ不吉だ不吉だ不吉だ不吉だ！）"
"10035160-64-コノカ" = "あ、あたしは……やっぱ行かねえ。"
"10035160-65-公安局の生徒A" = "え？どうかしたんですか？"
"10035160-66-公安局の生徒B" = "私たちだけで訓練しろってことですか！？"
"10035160-67-公安局の生徒C" = "そもそも、副局長が言い出した訓練なのに！"
"10035160-68-コノカ" = "と、とにかく、行かねえったら行かねえ！"
"10035160-69-コノカ" = "やるなら、お前らだけでやりな！"
"10035160-70-公安局の生徒A" = "あー、またジンクスかあ……。"
"10035160-71-公安局の生徒B" = "はあ？また？"
"10035160-72-公安局の生徒C" = "ジンクスは覆してあげなきゃ。えいっ！"
"10035160-73-コノカ" = "ちょ、何すんだよ！お前ら！担ぎ上げるな！"
"10035160-74-コノカ" = "こら！放せっ！おい、下ろせってばぁ！"
"10035160-75-コノカ" = "うっ、お前ら！こうなったら容赦しねえからなっ！"
"10035160-76-公安局の生徒B" = "うわ！副局長が怒った！みんな逃げて～。"
"10035160-77-公安局の生徒B" = "副局長ったら！もう、泣かないでくださいよ～！"
"10035160-78" = "（こうして騒がしく、公安局の夏は過ぎていった……）"
