[translation]
"10035140-1" = "後日談その3;河駒風ラブのシークレットバカンス（１）"
"10035140-2-ジャブジャブヘルメット団A" = "この自販機もなかなかだぜ、ひひっ。"
"10035140-3-ジャブジャブヘルメット団B" = "場末の自販機を蹴ってお金を稼ぐ……。"
"10035140-4-ジャブジャブヘルメット団B" = "すげえビジネスモデルだ。やっぱり隊長は頭がいいですね！"
"10035140-5-ラブ" = "あはははっ！"
"10035140-6-ラブ" = "そう！うちこそヘルメット団のブレインよ！"
"10035140-7-ラブ" = "で、今日の収穫はいくらだったの？"
"10035140-8-ジャブジャブヘルメット団A" = "自販機26台を蹴って……"
"10035140-9-ジャブジャブヘルメット団B" = "530円です。"
"10035140-10-ラブ" = "少なくない？"
"10035140-11-ジャブジャブヘルメット団A" = "そりゃあ、こんな場所にある自販機ですから……。"
"10035140-12-ジャブジャブヘルメット団A" = "表の自販機はブラックマーケットの管轄で、うかつに手を出せないし……。"
"10035140-13-ラブ" = "ああもうっ！これじゃ夏休みの計画を大幅修正するしかないじゃない！"
"10035140-14-ジャブジャブヘルメット団B" = "そんな……。"
"10035140-15-ラブ" = "モモトーク？こんな時に誰が……。"
"10035140-16-ラブ" = "知らない番号……。#n「ヘルメット団の本部」？そんなのあったっけ？"
"10035140-17-ジャブジャブヘルメット団A" = "ヘルメット団は普段バラバラに活動してても、規模はデカいですから。#n本部くらいあるかもしれませんよ。"
"10035140-18-ラブ" = "たしかに……入団の時、聞いた覚えがあるような……。"
"10035140-19-ラブ" = "まぁ、確認してみるけど。"
"10035140-20-ラブ" = "え！？「ヘルメット団総連合会」開催決定！？"
"10035140-21-ジャブジャブヘルメット団B" = "総連合会……！って、なんすか？"
"10035140-22-ラブ" = "ヘルメット団の全団員が海辺で一堂に会する集会よ！"
"10035140-23-ラブ" = "フードコートにアミューズメント、それにライブも！#nもうパーティーみたいなもんじゃない、これ！"
"10035140-24-ラブ" = "最高ね！これなら今年の夏休みはバッチリだわ！"
"10035140-25-ジャブジャブヘルメット団B" = "う、うちらも一緒に行けるんですか？"
"10035140-26-ラブ" = "当ったり前でしょ！"
"10035140-27-ラブ" = "参加費も取らないみたいだし。#n残った金で水着を買うわよ！"
"10035140-28-一同" = "やったぁ！"
"10035140-29-ジャブジャブヘルメット団A" = "こ、この水着、高すぎませんか？"
"10035140-30-ジャブジャブヘルメット団B" = "3人分買うには、金が足りませんね……？"
"10035140-31-ラブ" = "うーーん……。"
"10035140-32-ラブ" = "仕方ないわね！1着だけ買って着回しましょ！"
"10035140-33-ラブ" = "予算内で、できるだけ準備するのよ！"
"10035140-34-ラブ" = "あ～、楽しかった！"
"10035140-35-ジャブジャブヘルメット団B" = "たくさんは買えなかったけど。いい買い物ができましたね、隊長！"
"10035140-36-ジャブジャブヘルメット団B" = "貯金がほとんどすっからかんですけど……。#nこれもヘルメット団のパーティーのためですからね！"
"10035140-37-ラブ" = "そう！そのとおり！"
"10035140-38-ラブ" = "うちらの夏は、ここから始まるの！"
"10035140-39-ラブ" = "あれ、新しいメッセージ？"
"10035140-40-ラブ" = "どれどれ……。"
"10035140-41-ラブ" = "は、はぁ？バカにしてるわ。何よ、これ？"
"10035140-42-ジャブジャブヘルメット団B" = "え？どうかしたんですか？"
"10035140-43-ジャブジャブヘルメット団B" = "隊長？顔色が悪いですよ。"
"10035140-44-ラブ" = "……これ見て。"
"10035140-45-ジャブジャブヘルメット団A" = "パーティーの参加者名簿……？"
"10035140-46-ジャブジャブヘルメット団B" = "隊長の名前だけで……う、うちらの名前が……無い？"
"10035140-47-ジャブジャブヘルメット団A" = "え……じゃあ、うちらはパーティーに参加できない、ってことですか？"
"10035140-48-ジャブジャブヘルメット団B" = "そんな……せっかく楽しみにしていたのに……。"
"10035140-49-ラブ" = "ふ、ふざけてるわ！全員じゃなきゃ意味ないでしょ！"
"10035140-50-ラブ" = "待ってなさい！ちゃんと抗議するから……！"
"10035140-51-ジャブジャブヘルメット団A" = "いえ……隊長だけでも行ってきてください。"
"10035140-52-ラブ" = "え？"
"10035140-53-ジャブジャブヘルメット団B" = "仕方ないですよ。#n本部も末端の団員まで呼ぶ余裕はないみたいだし……。"
"10035140-54-ジャブジャブヘルメット団A" = "隊長だって、楽しみにしてたでしょ。#nだから、うちらの分まで楽しんできてください。"
"10035140-55-ジャブジャブヘルメット団A" = "うちらのことは……気にしないで……。"
"10035140-56-ラブ" = "あんたたち……。"
"10035140-57-ラブ" = "……よし、決めたわ。"
"10035140-58-ラブ" = "あんたたち、ついてくるのよ。"
"10035140-59-一同" = "え？ど、どこに行くんですか？"
"10035140-60-ラブ" = "いいからっ！"
"10035140-61-ラブ" = "せっかく水着も買ったんだし！今から水遊びに行くわよ！"
"10035140-62-ラブ" = "あんたたちの夏を、このまま終わりにはさせないわ！"
