[translation]
"10035050-1" = "第5話;ワニ、反応消失！"
"10035050-2-フブキ" = "え～ですから、波のプールを利用中のお客さんは避難を～"
"10035050-3-フブキ" = "慌てなくていいから、転ばないようにね。"
"10035050-4-フブキ" = "なんでかって言うと、うーん……。"
"10035050-5-フブキ" = "ぶっちゃけ、私もよく分かんないけどさ……"
"10035050-6-フブキ" = "ま、とりあえずちゃっちゃと避難しよ～！"
"10035050-7-キリノ" = "いたっ！"
"10035050-8-チンピラA" = "ま、周りの人を押さないように！ゆっくり移動してください！"
"10035050-9-キリノ" = "安全第一ですよっ……"
"10035050-10-キリノ" = "いたっ！"
"10035050-11-カンナ" = "はやくプールから離れろ！"
"10035050-12-カンナ" = "急いで、避難するんだ！"
"10035050-13-ウォーターパーク所属のライフセーバーA" = "どういうことだ？#nどうして客を避難させてるんだ？"
"10035050-14-ウォーターパーク所属のライフセーバーB" = "わかんないけど、緊急事態みたい！"
"10035050-15-ウォーターパーク所属のライフセーバーA" = "はあ……避難誘導を急ぐぞ！"
"10035050-16-ウォーターパークの警備兵A" = "ちょっと！何をしているんです！"
"10035050-17-ウォーターパークの警備兵A" = "一体これは、どういう状況ですか？"
"10035050-18-ウォーターパークの警備兵A" = "何の連絡もなくお客様を避難させるなんて。"
"10035050-19-ウォーターパークの警備兵A" = "まさか、何か事故でも！？"
"10035050-20-キリノ" = "あっ！オーナーさん！"
"10035050-21-キリノ" = "いえ！まだ事故は起きておりません！しかし、その危険がありまして……！"
"10035050-22-ウォーターパークのオーナー" = "あなたはヴァルキューレ警察学校の……って、危険ですって？"
"10035050-23-ウォーターパークのオーナー" = "まさか、波を生成する装置に何か問題でも……？"
"10035050-24-ウォーターパークのオーナー" = "それとも、水質汚染警報器の不具合ですか？"
"10035050-25-フブキ" = "そういうんじゃないんだけどさ～#nえっと……。"
"10035050-26-フブキ" = "フブキ、私から言おう。"
"10035050-27-フブキ" = "ヴァルキューレ警察学校から出向し、ライフセーバーとして#n警備にあたっている[ruby=おがた]尾刃[/ruby]カンナです。"
"10035050-28-カンナ" = "本日11時20分頃――#n波のプールで正体不明の怪物を目撃しました。"
"10035050-29-カンナ" = "よって、利用客の安全を確保するため、避難させています。"
"10035050-30-ウォーターパークのオーナー" = "怪物？"
"10035050-31-ウォーターパークのオーナー" = "それは一体どんな？"
"10035050-32-カンナ" = "水の中だったため、視界は不明瞭でしたが……。"
"10035050-33-カンナ" = "大きな口に、太い四つ脚で……"
"10035050-34-ウォーターパークのオーナー" = "おそらく――"
"10035050-35-カンナ" = "ワニだと思われます。"
"10035050-36-ウォーターパークのオーナー" = "ワニ……？"
"10035050-37-ウォーターパークのオーナー" = "ウォーターパークにワニなんか、いるわけないだろ！"
"10035050-38-フブキ" = "ひぃっ！"
"10035050-39-フブキ" = "わ……ビックリした。"
"10035050-40-ウォーターパークのオーナー" = "ここは海でも川でもない！人工のパークだ！"
"10035050-41-ウォーターパークのオーナー" = "ワニどころか、魚の一匹すらいない！"
"10035050-42-ウォーターパークのオーナー" = "ヴァルキューレ警察学校！#nこれは、立派な営業妨害だぞ！"
"10035050-43-カンナ" = "私は、この目で見たものを報告しただけです。"
"10035050-44-カンナ" = "私が嘘をついていると？"
"10035050-45-ウォーターパークのオーナー" = "ひ、ひぃっ！その顔で凄むのはやめろっ！"
"10035050-46-ウォーターパークのオーナー" = "お、お前が、幻覚を見たに決まってるだろう！？"
"10035050-47-ウォーターパークのオーナー" = "ワケの分からん理由で、客を避難させるなんて！"
"10035050-48-ウォーターパークのオーナー" = "下水道にワニがいるなんて都市伝説を信じているのか？"
"10035050-49-ウォーターパークのオーナー" = "いいか。この件は正式に損害賠償を――"
"10035050-50" = "[s1] \"ちょっと待ってください。\"\n[s2] \"すこし落ち着いて話を。\""
"10035050-51-ウォーターパークのオーナー" = "は？"
"10035050-52-ウォーターパークのオーナー" = "なんですか？あなたは。"
"10035050-53-ウォーターパークのオーナー" = "えっ？シャーレの先生？"
"10035050-54-ウォーターパークのオーナー" = "今日は客として訪れている……ですと？"
"10035050-55-ウォーターパークのオーナー" = "ふむ、これはこれは……。大変失礼いたしました。"
"10035050-56-ウォーターパークのオーナー" = "先生がご利用になられると知っていれば……。#nもっと行き届いたサービスを提供できたのですが……ははは……。"
"10035050-57" = "[s] \"カンナの報告をもう一度検討してください。\""
"10035050-58" = "[ns] \"生徒達が言うのなら、きっと何かがいるはずです。\""
"10035050-59-カンナ" = "……！"
"10035050-60-ウォーターパークのオーナー" = "あまりにも荒唐無稽な話ですよ。"
"10035050-61" = "[s3] \"もう避難も終わっていることですし……。\"\n[s4] \"万が一に備えて、プールを調査してみては？\""
"10035050-62-ウォーターパークのオーナー" = "ふむ、そうですね。#nお客様にプールの安全を保証する必要はありますし……。"
"10035050-63-ウォーターパークのオーナー" = "……いいでしょう。"
"10035050-64-ウォーターパークのオーナー" = "警備員を動員して、プールを調査してみましょう。#nワニがいないことを証明するために！"
"10035050-65" = "[s] \"ありがとうございます。\""
"10035050-66-ウォーターパークのオーナー" = "しかし、もし何もいなかった場合は……"
"10035050-67-ウォーターパークのオーナー" = "この損害の埋め合わせをしてもらう！"
"10035050-68-ウォーターパークのオーナー" = "次は屋外フードコートで、タコ焼き屋台の当番だ！"
"10035050-69-ウォーターパークのオーナー" = "与えた損害の分は、働いて返してもらわないと。"
"10035050-70-フブキ" = "お、屋外～？そ、それだけは……！"
"10035050-71-ウォーターパークの警備兵" = "おい！警備員とライフセーバーを集めてくれ！#nプールに危険生物がいないか捜索するんだ！"
"10035050-72-ウォーターパークのオーナー" = "気をつけるんだぞ！#nぷぷっ。わ、ワニが、いるかもしれないからな！"
"10035050-73-カンナ" = "……ありがとうございます、先生。"
"10035050-74-カンナ" = "また先生に助けられてしまうとは。"
"10035050-75" = "[s5] \"気にしなくていいよ。\"\n[s6] \"生徒を助けるのが、私の仕事だからね。\""
"10035050-76-キリノ" = "でも、良かったですね。#nあの人数で探せば、きっとワニもすぐ見つかります！"
"10035050-77-フブキ" = "本当にいれば、の話だけどねー……。"
"10035050-78-カンナ" = "嘘はついていない。"
"10035050-79-カンナ" = "この目ではっきり見たんだ。黒くて大きな影が、水中を泳いでいる姿を。"
"10035050-80-フブキ" = "本官は、もちろん局長のこと信じています！"
"10035050-81-キリノ" = "きっとすぐに見つかるはずです！"
"10035050-82-キリノ" = "タコ焼き……いかがですか……タコ焼き……。"
"10035050-83-フブキ" = "うあぁぁぁ……タコを焼く前に私たちが焼けちゃうってぇぇぇ！！"
