[translation]
"10035150-1" = "後日談その4;河駒風ラブのシークレットバカンス（２）"
"10035150-2-ジャブジャブヘルメット団A" = "こ、ここはウォーターパーク……？"
"10035150-3-ジャブジャブヘルメット団B" = "今日オープンの？まさか水遊びって、ここで……！？"
"10035150-4-ラブ" = "当ったり前じゃない！"
"10035150-5-ラブ" = "本部のやつら！団員を差別するなんて！"
"10035150-6-ラブ" = "もういいわ！そんな場所に行くのはお断りよ！"
"10035150-7-ラブ" = "ここで海辺のパーティなんてかすんじゃうくらい、楽しく遊べばいいの！"
"10035150-8-ラブ" = "うちだけ呼ばれて、部下が夏を満喫できないなんてあり得ないわ！"
"10035150-9-ジャブジャブヘルメット団B" = "隊長……！"
"10035150-10-ジャブジャブヘルメット団B" = "うちらのために……！"
"10035150-11-ラブ" = "ま、まあ！うちだってウォーターパークってとこ、一度は来てみたかったし！"
"10035150-12-ラブ" = "いいからっ、もう！とにかく入るわよ！"
"10035150-13-一同" = "はい！隊長！"
"10035150-14-ウォーターパークのスタッフ" = "いらっしゃいませ！何名様ですか？"
"10035150-15-ジャブジャブヘルメット団B" = "3名よ！"
"10035150-16-ウォーターパークのスタッフ" = "かしこまりました！#n3名様の入場チケット、合計18000円になります。"
"10035150-17-ラブ" = "げげっ！？"
"10035150-18-ラブ" = "高すぎじゃない？"
"10035150-19-ウォーターパークのスタッフ" = "こちらは通常料金になりまして……。"
"10035150-20-ウォーターパークのスタッフ" = "割引も可能ですよ。"
"10035150-21-ラブ" = "どれぐらい下がるのよ？"
"10035150-22-ウォーターパークのスタッフ" = "まず、学生割引があります。"
"10035150-23-ウォーターパークのスタッフ" = "どこの学園の生徒さんでも学生証のご提示で半額になります！"
"10035150-24-ラブ" = "え、えっと……。"
"10035150-25-ジャブジャブヘルメット団A" = "た、隊長、うちら中退してるから学生証なんて持ってないですよ？"
"10035150-26-ウォーターパークのスタッフ" = "ほ、他の割引はないの！？"
"10035150-27-ウォーターパークのスタッフ" = "そうですね……。#nボランティア活動の証明書があれば、30％割引になります。"
"10035150-28-ジャブジャブヘルメット団B" = "そんなもん持ってるわけが……。"
"10035150-29-ウォーターパークのスタッフ" = "えっと……"
"10035150-30-ウォーターパークのスタッフ" = "それでは、午後4時以降のご入場で20％割引になりますが……。"
"10035150-31-ラブ" = "まだ朝でしょ！？"
"10035150-32-ラブ" = "ここで午後4時になるまで待てってこと？"
"10035150-33-ウォーターパークのスタッフ" = "はぁ……。"
"10035150-34-ウォーターパークのスタッフ" = "ご予算は、どれくらいですか？"
"10035150-35-ラブ" = "えっと……今持ってるお金は……"
"10035150-36-ラブ" = "1500円だけ……。"
"10035150-37-ラブ" = "一人500円にしてくれない？"
"10035150-38-ウォーターパークのスタッフ" = "申し訳ありませんが、料金表にない割引はできません。"
"10035150-39-ウォーターパークのスタッフ" = "では、お次にお並びの方、どうぞ！"
"10035150-40-ラブ" = "待って！"
"10035150-41-ラブ" = "ここまで来ておいて、引き返せるわけないでしょ！？"
"10035150-42-ジャブジャブヘルメット団B" = "そうだそうだ！"
"10035150-43-ジャブジャブヘルメット団B" = "せっかく隊長がここまで連れてきてくれたのに……！"
"10035150-44-ウォーターパークのスタッフ" = "お願いよ、なんとかできないの？"
"10035150-45-ラブ" = "足りないお金は、身体で支払ってもいいわ！"
"10035150-46-ウォーターパークのスタッフ" = "はあ、普段ならお断りするしかないのですが……。"
"10035150-47-ウォーターパークのスタッフ" = "オープン初日で人手が足りていないそうなんです。#n連絡してみるのでお待ちください。"
"10035150-48-ジャブジャブヘルメット団B" = "あ、ありがとう！"
"10035150-49-ジャブジャブヘルメット団B" = "うちら頑張るから！"
"10035150-50-ラブ" = "まあ、プールの掃除なんて簡単よね！"
"10035150-51-ラブ" = "うちがブラシを持つなんて、そうそうないことだけど……！"
"10035150-52-ラブ" = "ま、生きてれば、こんなこともあるわ！"
"10035150-53-ジャブジャブヘルメット団B" = "隊長！こちらは終わりました！"
"10035150-54-ジャブジャブヘルメット団B" = "こっちもです！"
"10035150-55-ラブ" = "よし！そろそろね――"
"10035150-56-ウォーターパークの案内放送" = "ご案内致します。"
"10035150-57-ウォーターパークの案内放送" = "ただ今よりウォーターパークを開場致します。待機中のお客様はゲートからご入場ください。"
"10035150-58-ジャブジャブヘルメット団B" = "つ、ついに！"
"10035150-59-ジャブジャブヘルメット団B" = "時間ですよ！隊長！"
"10035150-60-ラブ" = "よっし！"
"10035150-61-ラブ" = "足りない分は労働で支払った！後は思いっきり遊ぶだけね！"
"10035150-62-ラブ" = "あんたら！"
"10035150-63-一同" = "はい、隊長！"
"10035150-64-ラブ" = "死ぬ気で遊びつくすわよ！"
"10035150-65-ラブ" = "今日だけは無防備になって！思いっきり夏を楽しもうじゃないの！"
"10035150-66-ジャブジャブヘルメット団A" = "ほ、本当に警戒を解いてもいいんですか！？"
"10035150-67-ラブ" = "心配ないわ！だって、人工のウォーターパークには――"
"10035150-68-ラブ" = "ワニなんか現れるはずないんだから！"
