[translation]
"10035080-1" = "第8話;黒幕、逃がしません！"
"10035080-2-利用客A" = "一体どういうことなんだ……ワニが出るなんて……。"
"10035080-3-利用客B" = "ここは安全なんだよね？"
"10035080-4-利用客C" = "ねえ、もう家に帰ろう？ここにいたくないよ。"
"10035080-5-フブキ" = "楽しいはずのウォーターパークが、お通夜みたいだね～。"
"10035080-6-キリノ" = "お客さんたちの顔も暗いですね……。"
"10035080-7-キリノ" = "帰りはじめている方もいますし……。"
"10035080-8-カンナ" = "あんな事件が起きたんだ。仕方ないだろう。"
"10035080-9-カンナ" = "メカワニを捕獲しない限り、この騒ぎは収まらない。"
"10035080-10-カンナ" = "やっぱり、私たちもワニの捜索に当たるべきでしょうか？"
"10035080-11-カンナ" = "いや、この事件の黒幕を突き止めるのが先だ。私たちは――"
"10035080-12-カンナ" = "あのワニを……ウォーターパークに解き放った奴を捕まえる。"
"10035080-13-キリノ" = "え！？あのワニって、誰かが連れて来たものなんですか？"
"10035080-14-キリノ" = "あのワニは生物ではない。ワニ型のロボットだ。"
"10035080-15-カンナ" = "つまり、人の手で作られたものということだ。#nそして、あの攻撃性……。奴らの狙いは想像できる。"
"10035080-16-カンナ" = "テロ、もしくは営業妨害……。動機はわからないが。#n犯人はテロリストと見なすべきだろう。"
"10035080-17-フブキ" = "テロリスト……！"
"10035080-18-キリノ" = "き、局長は、犯人が誰なのかわかっているんですね？"
"10035080-19-フブキ" = "あれあれ、さっき私たちを見て、逃げた奴がいたじゃん？"
"10035080-20-キリノ" = "はっ！それは、まさか！"
"10035080-21" = "[s1] \"もしかしてヘルメット団が……。\"\n[s2] \"まさか、ラブがあのワニを……。\""
"10035080-22-キリノ" = "ヘルメット団の幹部、[ruby=こまかぜ]河駒風[/ruby]ラブ……！"
"10035080-23-フブキ" = "分かりました！発見次第、捕縛します！"
"10035080-24-キリノ" = "本官はさっそく捜索に――"
"10035080-25-キリノ" = "あ？"
"10035080-26-ラブ" = "あ。"
"10035080-27" = "[s] （なんて間の悪い……！）"
"10035080-28-カンナ" = "捕まえろ！"
"10035080-29-ラブ" = "ひぃ！"
"10035080-30-キリノ" = "逃がしません！"
"10035080-31-キリノ" = "うっ！"
"10035080-32-キリノ" = "よ、よし！無事、捕縛しました！"
"10035080-33-キリノ" = "逃がしませんよ！テロリストさん！"
"10035080-34-キリノ" = "誰がテロリストよ！"
"10035080-35-ラブ" = "[ruby=えんざい]冤罪[/ruby]だわ！うちらに非は無い！"
"10035080-36-ラブ" = "冤罪ってー？"
"10035080-37-ラブ" = "あんたがやらかしたことは、全部わかってるって！"
"10035080-38-ジャブジャブヘルメット団A" = "ラブ隊長を放せ！"
"10035080-39-ジャブジャブヘルメット団B" = "ヴァルキューレめ！言いがかりだ！"
"10035080-40-カンナ" = "言いがかりだと？ふっ！"
"10035080-41-カンナ" = "貴様らの犯罪行為……今すぐ逮捕されても文句は言えないはずだ！"
"10035080-42-キリノ" = "うちらが何をしたって言うのよ！！"
"10035080-43-キリノ" = "私たちと目が合った瞬間、逃げたじゃありませんか！"
"10035080-44-キリノ" = "何かやましいことをしたんでしょう！？"
"10035080-45-ラブ" = "そんないい加減な理由で疑うなんて！これだからヴァルキューレどもは！"
"10035080-46" = "[s3] \"はーい！みんな注目！\"\n[s4] \"一旦、落ち着こうか。\""
"10035080-47-ラブ" = "[USERNAME]先生？"
"10035080-48" = "[ns] \"状況を整理する必要がありそうだから。\""
"10035080-49" = "[ns] \"まず、それぞれの事情を説明しようか。\""
"10035080-50-カンナ" = "分かりました。キリノ、フブキ、奴をちゃんと捕まえていろ。"
"10035080-51-カンナ" = "さあ言ってみろ、河駒風ラブ。#nウォーターパークにメカワニを放った理由はなんだ？"
"10035080-52-ラブ" = "ひ、ひぃ……"
"10035080-53-ジャブジャブヘルメット団A" = "こ、これが噂に聞いた公安局の狂犬……。"
"10035080-54-カンナ" = "答えろ。"
"10035080-55-ラブ" = "わ、ワニを放ったって、どういう意味よ！？"
"10035080-56-ラブ" = "シラを切るな！この状況をつくったのは貴様だろう！"
"10035080-57-ラブ" = "……？"
"10035080-58-ラブ" = "誤解よ！ワニを放ったのはうちらじゃない！"
"10035080-59-ラブ" = "あのワニ……その、なんて言うの……？#n「メタル・ウェポン・スピード・クロコダイル」って言うべき？"
"10035080-60-フブキ" = "（局長とネーミングセンスが近いなぁ……）"
"10035080-61-ラブ" = "とにかく、あのワニは、うちらとはなんの関係もないから！"
"10035080-62-ラブ" = "あ、あんたたちも何か言いなさいよ！"
"10035080-63-ジャブジャブヘルメット団A" = "隊長の言う通りだ！こっちも今、避難しているところなんだ！"
"10035080-64-ジャブジャブヘルメット団B" = "ヘルメット団にあんなワニを作る金があるわけないだろ……。"
"10035080-65-カンナ" = "む、無関係、だと……？"
"10035080-66-カンナ" = "では、さっきはなぜ逃げたんだ？#nやましいことがないのに、逃げる理由などないだろう？"
"10035080-67-ラブ" = "[USERNAME]先生に、ヴァルキューレの連中が3人もいるんだから！#n逃げるに決まってるでしょ！"
"10035080-68-キリノ" = "何も悪いことしてないのに、ですか？"
"10035080-69-ラブ" = "これは、うちらの本能みたいなもんなの！"
"10035080-70-フブキ" = "警察を見たらまず逃げる……かぁ。根本が違うよねぇ……。"
"10035080-71" = "[s] \"ラブ、ウォーターパークにはどうして来たの？\""
"10035080-72-ラブ" = "ここに来た理由？"
"10035080-73-ラブ" = "そんなの、遊びに来たに決まってるじゃん？"
"10035080-74-ジャブジャブヘルメット団A" = "そう、そう！"
"10035080-75-ジャブジャブヘルメット団B" = "ヘルメット団にも休暇は必要なんだ！"
"10035080-76-ジャブジャブヘルメット団B" = "見ろ！ちゃんと入場券だって買ってる！"
"10035080-77-ジャブジャブヘルメット団A" = "しかも、金が足りなくて、肉体労働までしたんだぞ！"
"10035080-78-ラブ" = "「ヘルメット団総連合会」に行けない奴らを労うために、#nわざわざ連れてきたってのに……。"
"10035080-79-ラブ" = "夏にプールで遊んで何が悪いっていうの！"
"10035080-80-ラブ" = "うちらだって、いつも騒ぎを起こしてるわけじゃないし！"
"10035080-81" = "[s5] （本当に悔しそうに見える……。）\n[s6] （嘘は言ってなさそうだけど……。）"
"10035080-82-カンナ" = "す、すまない……てっきり、お前たちの仕業かと思って……。"
"10035080-83-カンナ" = "す、すまない……てっきり、お前たちの仕業かと思って……。"
"10035080-84-キリノ" = "本官がまたミスを……"
"10035080-85-フブキ" = "ま、日頃の行いが返ってきた感じでしょー。"
"10035080-86-フブキ" = "はあ！？"
"10035080-87" = "[ns] \"待って。大事なことを忘れてる。\""
"10035080-88" = "[ns] \"それなら、メカワニを放ったのは誰？\""
"10035080-89-利用客A" = "きゃぁぁぁ！ワニが屋内まで！"
"10035080-90-利用客B" = "みんな逃げろ！"
"10035080-91" = "うわっ！皆さん！ひ、避難してください！"
"10035080-92" = "これはちょっとまずったなぁ～。"
"10035080-93" = "う、うぅ。せっかくの休暇が台無しよ……！"
"10035080-94" = "総員、戦闘用意だ！ワニを制圧する！"
