[translation]
"10035040-1" = "第4話;波のプールは、危険がいっぱい！"
"10035040-2-謎の影A" = "よし。施設は一通り見て回ったな。準備運動はこのくらいで十分だ。"
"10035040-3-謎の影B" = "へへっ、それじゃあ波の出るプールから始めましょうか。"
"10035040-4-謎の影C" = "ああ、思いっきり暴れてやろう……！"
"10035040-5-アナウンス" = "キヴォトス最大規模を誇るウォーターパーク――#n「エーギル」にご来園の皆様、大変お待たせいたしました。"
"10035040-6-アナウンス" = "ただいまより、当園自慢の「波のプール」が開始いたします。"
"10035040-7-アナウンス" = "海辺の波を再現したプールで、楽しい時間をお過ごしください！"
"10035040-8-アナウンス" = "……続いて、業務連絡。子供用プールのライフセーバー3名、#n配置変更です。すみやかに、波のプールに移動してください。"
"10035040-9-フブキ" = "……だってさー。"
"10035040-10-フブキ" = "また屋外行きかぁ……やれやれ。"
"10035040-11-カンナ" = "私のせいだな……。本当に面目ない。"
"10035040-12-フブキ" = "いや、局長に言ったんじゃないよ。"
"10035040-13-フブキ" = "あの人使いの荒い、オーナーに言ったの！"
"10035040-14-カンナ" = "大丈夫ですよ！局長！すこしのミスくらい。"
"10035040-15-カンナ" = "本官も以前、脱獄犯を捕え損ねたことがありますが……、#n最後は丸く収まりました！終わりよければすべてよし！です。"
"10035040-16" = "[s1] （たしかに、そういう事もあったような……。）\n[s2] （脱獄犯を捕え損ねるのはさすがに……。）"
"10035040-17-フブキ" = "まっ、面倒だけどさ～。#n今日はここのライフセーバーだし、言われた通りにしないとね。"
"10035040-18-フブキ" = "んじゃ、行こっか。"
"10035040-19-キリノ" = "わぁ！とても広いですね！"
"10035040-20-キリノ" = "まるで本物の海辺を再現したかのようです！"
"10035040-21-フブキ" = "人もやたら多いね～"
"10035040-22-カンナ" = "その分、監視しているライフセーバーの人数も多い。"
"10035040-23-カンナ" = "他の連中との協力が必要なようだ。"
"10035040-24-ウォーターパーク所属のライフセーバー" = "支援に来た人たちね？#nここは広いから、隣のライフセーバーとはできるだけ広く間隔をあけてね！"
"10035040-25-ウォーターパーク所属のライフセーバー" = "ほら、はやく配置について！お客さんどんどん来るよ！"
"10035040-26-キリノ" = "ここでは個人戦ですね！"
"10035040-27-キリノ" = "局長、フブキ、頑張りましょう！"
"10035040-28-キリノ" = "先生も！休憩時間にまたお会いしましょうね！"
"10035040-29-フブキ" = "あんま走んないようにね～#n体力は温存しないと。"
"10035040-30-フブキ" = "んじゃ、私も行こうかな。"
"10035040-31-カンナ" = "個人戦か。"
"10035040-32-カンナ" = "先程のようなことが、また起きなければ良いのだが……。"
"10035040-33" = "[s3] \"さっきの子はきっと驚いただけ。\"\n[s4] \"さっきの子はきっと恥ずかしかっただけ。\""
"10035040-34-カンナ" = "ありがとうございます、先生。"
"10035040-35-カンナ" = "しかし、あの子供が泣いたのは、おそらく私のせいでしょう。"
"10035040-36-カンナ" = "私が、あの子供を怯えさせたんです……。"
"10035040-37-カンナ" = "そこ！はやく移動して！"
"10035040-38-カンナ" = "ひとまず、任務に集中すべきですね。"
"10035040-39-カンナ" = "できるだけ利用客に迷惑をかけないように……。#nプールの奥のほうを担当することにします。"
"10035040-40" = "[ns] \"……。\""
"10035040-41-水におぼれた客" = "あっぷ！あっぷ！"
"10035040-42-水におぼれた客" = "た、助けて！"
"10035040-43-フブキ" = "はいはい、落ち着いて。"
"10035040-44-フブキ" = "この浮き輪につかまって～"
"10035040-45-フブキ" = "げほっ！つ、掴んだ！"
"10035040-46-フブキ" = "んじゃ、いくよ～"
"10035040-47-フブキ" = "は～い、到着。"
"10035040-48-フブキ" = "た、助かった……。ありがとうございます……！"
"10035040-49-フブキ" = "あんま深いとこに行かないようにね。"
"10035040-50-イヤホンをつけた客" = "ふんふふ～♪"
"10035040-51-キリノ" = "あっ！そちらのお客様！"
"10035040-52-キリノ" = "プールでの、電子機器の使用は禁止されています！"
"10035040-53-イヤホンをつけた客" = "え～？なんの曲を聞いているかって？"
"10035040-54-イヤホンをつけた客" = "デス・エンジェルズの「ロック・ザ・シティ」さ。"
"10035040-55-キリノ" = "きょ、曲名ではなくてですね……！"
"10035040-56-キリノ" = "プール内では、イヤホンはお外しください！"
"10035040-57-キリノ" = "感電の危険もありますし、落とし物にもなりやすいので！"
"10035040-58-イヤホンをつけた客" = "ああ、たしかにそうだね。"
"10035040-59-キリノ" = "ご協力ありがとうございます！"
"10035040-60-カンナ" = "（プールの奥のほうに、客が立ち入らないようにする任務か……）"
"10035040-61-カンナ" = "（私にぴったりかもしれないな。）"
"10035040-62-アナウンス" = "これより、波のプールを開始します。"
"10035040-63-カンナ" = "ん？このあたり、周りに誰もいないな……。"
"10035040-64-カンナ" = "まさか、誰かもう奥に行ってしまったか――？"
"10035040-65-カンナ" = "うわっ！"
"10035040-66-カンナ" = "（波にのまれてしまった！）"
"10035040-67-カンナ" = "（動揺するな！溺れないように……！）"
"10035040-68-カンナ" = "（……ん？）"
"10035040-69-カンナ" = "（あ、あれは！？）"
"10035040-70-キリノ" = "せ、先生！#n局長が波にのまれてしまったようです！"
"10035040-71-フブキ" = "落ち着きなよキリノ。局長なら心配いらないって。"
"10035040-72-フブキ" = "カンナ局長、運動神経抜群なんだからさ。"
"10035040-73-キリノ" = "げほっ！キリノ、フブキ……！"
"10035040-74-フブキ" = "？"
"10035040-75-キリノ" = "今すぐ、客とスタッフを全員避難させろ！"
"10035040-76-フブキ" = "避難？なんかあったの？"
"10035040-77-カンナ" = "水の中に何かいる！危険生物の可能性が高い！"
"10035040-78" = "[s] \"危険生物！？\""
"10035040-79-キリノ" = "そ、そんなものがいるはずがありません！#n局長、幻を見たのではありませんか！？"
"10035040-80-フブキ" = "カンナ局長、そろそろ休んだ方がいいんじゃないの？#nストレスが溜まって幻覚でも見たんじゃ――"
"10035040-81-カンナ" = "幻覚などではない！"
"10035040-82-カンナ" = "警報を鳴らせ！一刻もはやく避難させるんだ。"
"10035040-83-カンナ" = "奴が現れてからでは遅い！"
"10035040-84-フブキ" = "きょ、局長がそこまで言うのでしたら……！"
"10035040-85-キリノ" = "分かりました！避難指示を出します！"
"10035040-86-フブキ" = "えぇー？何が起きてるのさ、マジで？"
"10035040-87-フブキ" = "仕方ないかぁ。アナウンスするね。"
"10035040-88-カンナ" = "先生もはやく避難を。"
"10035040-89-カンナ" = "私のことは、信じられないかもしれません。ですが……！"
"10035040-90" = "[s5] \"カンナのこと、信じてるよ。\"\n[s6] \"カンナも一緒に避難しよう！\""
"10035040-91-カンナ" = "私は最後の一人が避難するのを見届けてから行きます。"
"10035040-92-カンナ" = "それが、ライフセーバーの義務ですから。"
"10035040-93-カンナ" = "それでは！"
"10035040-94" = "[ns] キリノとフブキを手伝いに行く。"
"10035040-95-謎の影B" = "あははっ！みんな尻尾を巻いて逃げて行ったわ！"
"10035040-96-謎の影C" = "面白くなってきたじゃない！"
"10035040-97-謎の影A" = "よーし、このまま……"
"10035040-98-ラブ" = "ここで、暴れてやるわっ！"
