[translation]
"2300002-1" = "お昼代わりのスイーツ"
"2300002-2" = "シャーレ・執務室"
"2300002-3" = "（外回りを終えて帰ってくると、シャーレの執務室の机には書類が山のように積まれていた）"
"2300002-4" = "（結局お昼も食べられないまま、机の上の書類を片付け始めた）"
"2300002-5" = "先生、いらっしゃいますか？"
"2300002-6-アイリ" = "あ、先生こんにちは！"
"2300002-7-アイリ" = "この前はお忙しそうでしたが、大丈夫ですか？"
"2300002-8" = "[s1] \"あはは、まあ何とか……。\"\n[s2] 何も言えないまま机の上を見つめる。"
"2300002-9-アイリ" = "わ、これ全部お仕事の書類ですか……？"
"2300002-10-アイリ" = "わ、これ全部お仕事の書類ですか……？"
"2300002-11-アイリ" = "大人って大変なんですね……。"
"2300002-12-アイリ" = "そうだ！先生、お昼はもう食べましたか？"
"2300002-13-アイリ" = "まだでしたか、それはタイミングが良かったです。"
"2300002-14-アイリ" = "ふふふ……。"
"2300002-15-アイリ" = "こんなこともあろうかと、先生のためにスイーツを買ってきました！"
"2300002-16-アイリ" = "ちょうど今日から、「カフェ・ミルフィーユ」の新作が発売されたんです！"
"2300002-17-アイリ" = "先生と一緒に食べたくて、色々買ってきてしまいました。"
"2300002-18-アイリ" = "じゃーん！"
"2300002-19" = "（アイリのカバンから、色んな形のカップケーキが溢れるように出てきた）"
"2300002-20-アイリ" = "これが新作のカップケーキです！"
"2300002-21-アイリ" = "どうですか、すごく美味しそうですよね？"
"2300002-22-アイリ" = "はい、どうぞ！これはラズベリー味です！"
"2300002-23-アイリ" = "試食でちょっと頂いたのですが、すっごく美味しかったんです！"
"2300002-24-アイリ" = "このラズベリーの絶妙な甘酸っぱさは、どこでも味わえるものではありません……！"
"2300002-25-アイリ" = "そしてこっちはバナナ味です！"
"2300002-26-アイリ" = "こっちは試食が無かったんですが、色合いが可愛くて買ってしまいました！"
"2300002-27-アイリ" = "あとこれも……！"
"2300002-28-アイリ" = "チョコミント味です！"
"2300002-29-アイリ" = "これは新作ではなくて前からあったメニューなのですが、"
"2300002-30-アイリ" = "私のお気に入りなんです！目に入った途端つい食べたくなってしまって。"
"2300002-31-アイリ" = "チョコの甘さと、ミントのすっきりしたひんやり感がたまらなくって……！"
"2300002-32-アイリ" = "はぁん……。"
"2300002-33" = "[s3] \"……アイリ？\"\n[s4] \"別世界に飛んでない？大丈夫？\""
"2300002-34-アイリ" = "……はっ！？"
"2300002-35-アイリ" = "……はっ！？"
"2300002-36-アイリ" = "あはははは……すみません、ちょっとトリップしてました……。"
"2300002-37-アイリ" = "えっと、ではあらためて、どれから召し上がりますか？"
"2300002-38" = "（その後、アイリと一緒にカップケーキを食べながら、それぞれの味について解説してもらった）"
"2300002-39" = "（今日は活力を蓄えることにして、積みあがった書類の処理はまた今度頑張ることにしよう）"
