[translation]
"10049050-1" = "第5話;追跡！ヘルメット団！"
"10049050-2-スズミ" = "……。"
"10049050-3-スズミ" = "はぁ……はぁ……。"
"10049050-4-マシロ" = "ステージから観客席を基準に2時の方向、見えますか？"
"10049050-5-マシロ" = "[ruby=こまかぜ]河駒風[/ruby]ラブを始め、ジャブジャブヘルメット団と推定される3人組を発見しました。"
"10049050-6-レイサ" = "！！"
"10049050-7-レイサ" = "身元の特定と、脅威の有無について確認をお願いします。"
"10049050-8-レイサ" = "現在は荷車を引きながら移動中です。"
"10049050-9-レイサ" = "積荷には……ポップコーンバケットと、手榴弾のようなものが見えます……！"
"10049050-10" = "[ns] \"手榴弾！？\""
"10049050-11-マシロ" = "ここからでは不明瞭で、たしかなことが言えません。"
"10049050-12-マシロ" = "接近し、現場での確認をお願いします。"
"10049050-13-ジャブジャブヘルメット団A" = "隊長、これで全部ですか？"
"10049050-14-ラブ" = "そんなわけないじゃない。やるからには徹底的にやるわよ。"
"10049050-15-ジャブジャブヘルメット団B" = "さすが隊長！これで大儲けですね！"
"10049050-16-ラブ" = "次はこの辺のはずだけど……なんか急に混んできてない？"
"10049050-17-ジャブジャブヘルメット団A" = "ですね。#n……おい、道を塞ぐなよ！"
"10049050-18-スズミ" = "あ……。"
"10049050-19-ラブ" = "え……？"
"10049050-20-ジャブジャブヘルメット団A" = "隊長？どうかしました？"
"10049050-21-ラブ" = "いや、その……。"
"10049050-22-ラブ" = "ステージに立ってる、あのピンク色の服を着たやつ。"
"10049050-23-ジャブジャブヘルメット団B" = "え？ただのキャストじゃないですか？子供向けのショーだし。"
"10049050-24-ラブ" = "たぶん会ったことはないんだけど……。"
"10049050-25-ラブ" = "ここからでも分かる。"
"10049050-26-ラブ" = "強いわね、あいつ。"
"10049050-27-ラブ" = "逃げろ！！"
"10049050-28-ジャブジャブヘルメット団B" = "はい！？"
"10049050-29-スズミ" = "河駒風ラブを確認しました！その他に、ヘルメット団が2名！"
"10049050-30-スズミ" = "ゲヘナエリアのほうへ逃走しました。追跡を開始します！"
"10049050-31-レイサ" = "スズ――テルミットホワイト！ショーはまだ……！"
"10049050-32-観客B" = "ステージから飛び降りた！？"
"10049050-33-観客B" = "どういうこと！？"
"10049050-34-子供A" = "テルミットホワイト！"
"10049050-35-観客A" = "こ、これも演出なのか！？"
"10049050-36" = "[ns] \"ついて行こう！\""
"10049050-37-レイサ" = "はい！"
"10049050-38-マシロ" = "スズミさん！確認だけで十分です！"
"10049050-39-マシロ" = "ゲヘナエリアに入られたら、正義実現委員会は支援をできません！"
"10049050-40-スズミ" = "分かっていますが……事態は一刻を争います。"
"10049050-41-スズミ" = "積荷に、大量の手榴弾……のような物が見えました。"
"10049050-42-スズミ" = "支援は大丈夫です。"
"10049050-43-スズミ" = "私が、なんとかします。"
"10049050-44-レイサ" = "ピンクもいますよ！"
"10049050-45-ジャブジャブヘルメット団A" = "ぜぇ……ぜぇ……！"
"10049050-46-ジャブジャブヘルメット団B" = "隊長！あいつら何者なんですか！？"
"10049050-47-ラブ" = "知らないわよ！でも、追ってくるってことは敵なんでしょ！"
"10049050-48-ジャブジャブヘルメット団A" = "ステージの上でショーをやってたみたいですし……。"
"10049050-49-ジャブジャブヘルメット団A" = "もしかして、これも演出なのかも……？"
"10049050-50-ラブ" = "そんな危ないこと、子供向けでやる！？"
"10049050-51" = "止まってください。"
"10049050-52-ジャブジャブヘルメット団B" = "うわっ、いつの間に！？"
"10049050-53-ジャブジャブヘルメット団A" = "追い越されたってこと！？"
"10049050-54-レイサ" = "退路はテルミットピンクが塞ぎました！#n大人しくヘヴィキャリバーズに投降してください！"
"10049050-55-ラブ" = "ヘヴィキャリバーズ……？"
"10049050-56-ラブ" = "街の子供らが遊んでるおもちゃだっけ？"
"10049050-57-ラブ" = "あんたらって……あれなの？何かに熱中してる――"
"10049050-58-ジャブジャブヘルメット団B" = "マニアですよ。いや、オタク……かも？"
"10049050-59-ジャブジャブヘルメット団B" = "それより、なんでピンクなんだ？紫色だし、パープルじゃない？"
"10049050-60-レイサ" = "理由を説明したらネタバレになってしまいますので、本編を見るのをおすすめします！"
"10049050-61-スズミ" = "（私たちの正体には気づいていないようですね。それは助かりますが……）"
"10049050-62-観客A" = "あっ！イマーシブ・シアターが始まったみたい！"
"10049050-63-観客B" = "何それ？"
"10049050-64-観客A" = "ステージを飛び出して、色んな場所を舞台にするショーだよ！"
"10049050-65-子供A" = "あ！ピンクとホワイト！ここにいた！"
"10049050-66-子供B" = "悪いヤツとたたかってる！"
"10049050-67-スズミ" = "（困りました……観客がどんどん集まってきていますね……）"
"10049050-68-スズミ" = "（子供もいる状況では、閃光弾を使えません）"
"10049050-69-スズミ" = "（ひとまず、話し合いでなんとかするしか……）"
"10049050-70-スズミ" = "少々確認したいことがありますので、ご同行願えますか？"
"10049050-71" = "[s] \"ちょっとお話しない？\""
"10049050-72-ラブ" = "げっ、シャーレの先生！？"
"10049050-73-ラブ" = "そこまでして邪魔したいってこと？#nそれなら――"
"10049050-74-ラブ" = "お前ら！準備はいいか？"
"10049050-75-ジャブジャブヘルメット団B" = "はい！隊長！"
"10049050-76-ジャブジャブヘルメット団B" = "いつでも！"
"10049050-77-ラブ" = "じゃあ――"
"10049050-78-ラブ" = "攻撃、開始！"
