[translation]
"10049030-1" = "第3話;魔法少女ヘヴィキャリバーとは！"
"10049030-2" = "[log]3日前、図書委員会・休憩室[/log]"
"10049030-3-レイサ" = "これです！！"
"10049030-4-スズミ" = "これ……？"
"10049030-5-シミコ" = "はい？"
"10049030-6-レイサ" = "魔法少女に――なってください！"
"10049030-7-レイサ" = "えへへっ……このセリフを言える日がくるとは思いませんでした……！"
"10049030-8-シミコ" = "この……「魔法少女ヘヴィキャリバー・ボーダーランドスペシャル」……ってなんですか？"
"10049030-9-レイサ" = "魔法少女ヘヴィキャリバーが、ボーダーランド遊園地で特別なショーをするんです！"
"10049030-10-シミコ" = "えっと、具体的には……？"
"10049030-11-スズミ" = "キャラクターに扮したキャストが遊園地内の各所で行うショーです。"
"10049030-12-スズミ" = "敷地が広いため、複数のチームに分かれているようですが……。"
"10049030-13-スズミ" = "レイサさん、それと任務に一体何の関係が……？"
"10049030-14-レイサ" = "潜伏する際に、魔法少女に変装してみるのはどうでしょうか！"
"10049030-15-レイサ" = "チームが複数あるなら、一組くらい増えてもバレないはずです！"
"10049030-16-レイサ" = "それに、遊園地のどこにいても違和感はないと思います！"
"10049030-17-シミコ" = "キャストさんは外部から招待されることも多いですし……#n初対面でも、遊園地のスタッフさんに疑われる心配は少ないかもしれませんね。"
"10049030-18-スズミ" = "なるほど……。"
"10049030-19-スズミ" = "まだ小さかった頃、似たようなアニメを見た記憶があります。#nたしか、朝の時間に放送されていたような……それと一緒ですか？"
"10049030-20-レイサ" = "違います！！#nあ、いえ、朝のテレビアニメではあるのですが！"
"10049030-21-レイサ" = "魔法少女ヘヴィキャリバーは、悪の幹部「エラ」の侵略からキヴォトスを守る――#n選ばれし少女たちの物語なんです！"
"10049030-22-スズミ" = "な、なるほど……。"
"10049030-23-スズミ" = "ですがこの衣装は、戦闘には不向きだと思います。"
"10049030-24-スズミ" = "装備を整えるのも難しくなるでしょうし……。"
"10049030-25-スズミ" = "なにより、私はこういったジャンルのことはほとんど分かりません。"
"10049030-26-シミコ" = "私も、全く触れてこなかったので……。"
"10049030-27-スズミ" = "それに……少し恥ずかしいと言いますか……。"
"10049030-28-レイサ" = "あっ……。#nそう、ですよね。"
"10049030-29-レイサ" = "すみません……その、私なりに力になれるかなって思って、つい。"
"10049030-30-レイサ" = "えへへ、で、では、別の方法を考えてみますね！"
"10049030-31-スズミ" = "い、いえ！ですから、私が言いたいのは……。"
"10049030-32-スズミ" = "逆に、こういう衣装なら相手の油断を誘えますし――"
"10049030-33-スズミ" = "せ、潜入に適しているのではないでしょうか！"
"10049030-34-シミコ" = "スズミさん……？"
"10049030-35-レイサ" = "ですが、魔法少女ってやっぱ子供っぽいですし……。"
"10049030-36-スズミ" = "そんなことはありません。#n魔法少女ハッピー……カリバー？はとても良いと思います。"
"10049030-37-シミコ" = "「ヘヴィキャリバー」では？"
"10049030-38-スズミ" = "と、とにかく。遊園地という場所柄にもあっているかと。"
"10049030-39-スズミ" = "ただ……変装するなら、それ相応の知識が必要になります。"
"10049030-40-スズミ" = "レイサさんはその作品について、お詳しいのでしょうか？"
"10049030-41-レイサ" = "はい！大好きです！"
"10049030-42-レイサ" = "世界の平和を守る姿が自警団みたいで――"
"10049030-43-レイサ" = "今までで一番好きな作品と言ってもいいくらいです！！"
"10049030-44-レイサ" = "最近公開された劇場版も観てきました！"
"10049030-45-レイサ" = "誰かとヘヴィキャリバーの話をしたりは……できないんですけど……。"
"10049030-46-スズミ" = "……。"
"10049030-47-スズミ" = "ええと、今すぐ衣装の手配をお願いしてもいいでしょうか？"
"10049030-48-スズミ" = "どれにするのかはレイサさんにお任せします。"
"10049030-49-シミコ" = "スズミさん！？"
"10049030-50-レイサ" = "いいんですか！？すぐ用意しますね！！"
"10049030-51-スズミ" = "（なぜ、あんなことを言ってしまったのでしょうか……）"
"10049030-52-スズミ" = "（レイサさんがやる気になっていますし、潜入にも適しているとは思いますが……）"
"10049030-53-スズミ" = "（やはり、恥ずかしいですね……）"
"10049030-54-レイサ" = "似合ってますよ！恥ずかしがる必要なんてありません！"
"10049030-55-レイサ" = "主役を譲って正解でした！主人公としての貫禄がありますよ、スズミさん――"
"10049030-56-レイサ" = "――いえ、「テルミットホワイト」！"
"10049030-57-スズミ" = "テ、テルミットホワイト……？"
"10049030-58-レイサ" = "スズミさんが担当する役の名前です！#n本名を言ったら、正体がバレてしまいますから！"
"10049030-59-レイサ" = "そして私は「テルミットピンク」です！#n「テルミットホワイト」をサポートする相棒ですね！"
"10049030-60-スズミ" = "そ、そうですか。レイ――"
"10049030-61-スズミ" = "いえ、テルミットピンク……。"
"10049030-62-スズミ" = "ところで……なぜテルミット[ruby=・   ・   ・]ピンク[/ruby]なのでしょうか？"
"10049030-63-スズミ" = "レイサさんの衣装は紫色ですから、「パープル」では？"
"10049030-64-レイサ" = "あっ！それはですね！"
"10049030-65" = "[log=레이사 매지컬]魔法少女ヘヴィキャリバーの本編のお話になるのですがもともと#nテルミットピンクは名前の通りハートのジュエルやピンクのドレスが[/log]"
"10049030-66" = "[log=레이사 매지컬]メインのデザインだったんです。でもエラの忠実な[ruby=しもべ]僕[/ruby]「シルバープレート」#nとの決戦があった「ボルトキャッチ！ヘヴィキャリバー！」の回で危機に[/log]"
"10049030-67" = "[log=레이사 매지컬]陥ってしまって！そこでホワイトと共に力を合わせた際に新たな能力に#n目覚めたんですが、それでもシルバープレートを倒すことは叶わずそ#nのまま二人は倒れてしまうんです宿敵を倒したシルバープレートは――[/log]"
"10049030-68-スズミ" = "あ、あの……。"
"10049030-69-レイサ" = "[log=레이사 매지컬]――友情エネルギーを憎悪の星へ送ろうとしたその瞬間！#nこの姿のピンクが現れて敵を制圧するんです！それで――[/log]"
"10049030-70-レイサ" = "――ということがありまして！そのときピンクが特殊変身した姿がこれでして私はその回がとても大好きなのでこの衣装にしたんです！なのでこれは通常形態のピンクではなく真の力を解放した姿なんですよ！"
"10049030-71-スズミ" = "そ、そうですか……参考になりました……。"
"10049030-72-スズミ" = "ところで、レイ――テルミットピンク。シミコさんと連絡は取れましたか？"
"10049030-73-レイサ" = "悪の幹部「エラ」です！"
"10049030-74-スズミ" = "……あ、エ、エラは今どこに？"
"10049030-75-レイサ" = "それが……私にも分からなくて……。"
"10049030-76-レイサ" = "もしかして、寝坊でしょうか……？"
"10049030-77-スズミ" = "私たちだけでも現場はなんとかできると思いますが……。"
"10049030-78-スズミ" = "少し心配ですね。"
"10049030-79-マシロ" = "皆さん、聞こえますか？正義実現委員会のマシロです。ただいま配置につきました。"
"10049030-80-レイサ" = "はい、聞こえます。"
"10049030-81-レイサ" = "テルミットピンク、問題ありません！"
"10049030-82-マシロ" = "こちらも感度良好です。#n支援が必要な時は、このチャンネルでご連絡ください。"
"10049030-83-マシロ" = "ちなみに、私の現在位置はトリニティ側の展望塔です。"
"10049030-84-レイサ" = "分かりました。視野の確保にも注意しておきます。"
"10049030-85-マシロ" = "……先生も、ちゃんと聞こえていますか？"
"10049030-86" = "[s] \"うん、ばっちり。\""
"10049030-87-マシロ" = "私が必要な時は、先生もご遠慮なくお呼びください。"
"10049030-88-レイサ" = "ひとまず、通信状態に問題はありませんね。"
"10049030-89-スズミ" = "支援、ありがとうございます。マシロさん。"
"10049030-90-スズミ" = "せ、先生！？"
"10049030-91-レイサ" = "先生！"
"10049030-92" = "[s1] \"おはよう。スズミ、レイサ。\"\n[s2] \"やあ、テルミットホワイト、ピンク。\""
"10049030-93-スズミ" = "せ、先生！？？いっ……一体いつから！？"
"10049030-94-スズミ" = "あっ、こ、この衣装は、えっと、その……！"
"10049030-95" = "[s3] \"心の準備が……ってあたりかな。\"\n[s4] \"大丈夫。よく似合ってるよ。\""
"10049030-96-マシロ" = "話はハスミ先輩から聞いています。"
"10049030-97-マシロ" = "今日の支援要員は、私と先生の2名です。"
"10049030-98-スズミ" = "先生がいらっしゃるとは聞いていないのですが……。"
"10049030-99-レイサ" = "あれ？スズミさんも知らなかったんですか？"
"10049030-100-スズミ" = "知っていれば、もっと色々と……！"
"10049030-101-マシロ" = "ハスミ先輩は「可能な限りの支援」として、先生に協力を仰いだと言っていました。"
"10049030-102-マシロ" = "私も詳しいことまでは知りませんが。"
"10049030-103-スズミ" = "なるほど……まさかシャーレの支援を受けることになるとは……。"
"10049030-104" = "[s5] \"助けが必要みたいだったからね！\"\n[s6] \"面白そうだったからね！\""
"10049030-105-スズミ" = "（久々に先生とご一緒できるのは嬉しいですが……）"
"10049030-106-スズミ" = "（でも、この格好はさすがに……）"
"10049030-107-マシロ" = "待機に入る前に、一つお聞きしたいことがあります。"
"10049030-108-マシロ" = "お二人の衣装、ずいぶん独特ですが――"
"10049030-109-マシロ" = "それは自警団のユニフォームでしょうか？"
"10049030-110-マシロ" = "正義実現委員会の制服とは違って、派手で素敵だと思います。"
"10049030-111-スズミ" = "いえ、違います。#n自警団はそもそも組織ではないので、当然、指定のユニフォームはありません。"
"10049030-112-スズミ" = "これは、えっと……現場をパトロールするための、潜入衣装です……。"
"10049030-113-レイサ" = "「魔法少女ヘヴィキャリバー」の仲良し主人公！テルミットホワイトとピンクの衣装です！"
"10049030-114-レイサ" = "世界の平和を守り、正義を貫く魔法少女なんです！"
"10049030-115-スズミ" = "……。"
"10049030-116-マシロ" = "……。"
"10049030-117-マシロ" = "……なるほど、理解しました。"
"10049030-118-マシロ" = "正義を貫くための衣装……とても良いですね。"
"10049030-119-スズミ" = "……。"
"10049030-120-マシロ" = "あれ？コールサイン上、スズミさんは「テルミットホワイト」となっていますが……#n「ピンク」の間違いでは？こちらからはピンク色に見えますが……。"
"10049030-121-レイサ" = "あ！その理由はですね！まず3期7話を観る必要がありまして！簡単に説明すると――"
"10049030-122-スズミ" = "こ、コールサインに問題はありません！ご確認くださりありがとうございます！"
"10049030-123-スズミ" = "レイサさん。せっかくですから、後で映像を一緒に観ませんか？#nそれまでは、ネタバレ禁止ということで。"
"10049030-124-レイサ" = "おぉっ！いいですね！今度、円盤を全部持ってきますね！"
"10049030-125-マシロ" = "では、現時刻より待機に入ります。"
"10049030-126-マシロ" = "見張りや狙撃は私にお任せください。"
"10049030-127-マシロ" = "ただ、狙撃については正義実現委員会の発砲許可が必要なことをご留意ください。"
"10049030-128-スズミ" = "はぁ……。"
"10049030-129-スズミ" = "今からでも普段着に着替えるべきでしょうか……。"
"10049030-130-レイサ" = "ええっ！？せっかく似合ってるのに！"
"10049030-131-スズミ" = "ですが、やはり恥ずかしくて……。"
"10049030-132-公演のマネージャー" = "お二人とも、何やってるんですか！"
"10049030-133-公演のマネージャー" = "そろそろ開演なんですから、控え室で待機しててもらわないと！"
"10049030-134-スズミ" = "わ、私たちですか？"
"10049030-135-レイサ" = "はい？"
"10049030-136-公演のマネージャー" = "まったく困りますよ。列車の乗務員がどうのこうのって、時間に間に合わないって連絡を寄こしておいて。"
"10049030-137-公演のマネージャー" = "まぁ、ちゃんと間に合ってるので、もういいですが。さあ、早く始めますよ！"
"10049030-138-スズミ" = "始める……何をですか？"
"10049030-139-公演のマネージャー" = "「魔法少女ヘヴィキャリバー」のショーですよ！"
"10049030-140-公演のマネージャー" = "あなた達、キャストなんでしょう？早く準備してください！"
"10049030-141-スズミ" = "キャ、キャスト！？"
