[translation]
"10049040-1" = "第4話;ステージショー開演！"
"10049040-2" = "控え室"
"10049040-3-レイサ" = "わぁっ！！ここが控え室！！"
"10049040-4-レイサ" = "キャストさんになった気分です！！"
"10049040-5-スズミ" = "レイサさん！"
"10049040-6-公演のマネージャー" = "ふーむ……。"
"10049040-7-公演のマネージャー" = "あなた達、本当にキャストですか？"
"10049040-8-公演のマネージャー" = "名簿に載ってなかったような……#nあー、ったく、名簿持ってくるの忘れたな……。"
"10049040-9-スズミ" = "！！"
"10049040-10-スズミ" = "（よくないですね……もし正体がバレてしまえば……）"
"10049040-11-スズミ" = "（潜入もバレて……ターゲットに気づかれてしまうかも……）"
"10049040-12-スズミ" = "（どうしましょう……？）"
"10049040-13-スズミ" = "（なにか……打開策を考えなければ……）"
"10049040-14-レイサ" = "フィードランプよりチャンバーへ……6条右回りの魔法よ！揺るぎなき力をっ！"
"10049040-15-レイサ" = "ボルトフォワード！テルミットピンク！"
"10049040-16-レイサ" = "これで準備完了です！"
"10049040-17-スズミ" = "レイサさん！？"
"10049040-18-レイサ" = "自然にポーズをとれば大丈夫です！"
"10049040-19-スズミ" = "っ……うぅ……。"
"10049040-20-スズミ" = "まじかる、りりかる……#nてるみっとほわいと！"
"10049040-21-公演のマネージャー" = "心配しすぎか……#nショーは10分後から始めますので、よろしくお願いしますね。"
"10049040-22-スズミ" = "はあぁ……。"
"10049040-23-レイサ" = "なんとか誤魔化せましたね！"
"10049040-24-スズミ" = "ひとまずは切り抜けられましたが……問題はこれからです。"
"10049040-25-スズミ" = "まさかこんな事になるだなんて……このままでは、10分後にはステージの上ですよ！"
"10049040-26" = "[s1] \"むしろ好都合じゃないかな？\"\n[s2] \"ステージの上だと、見晴らしが良くなるし。\""
"10049040-27-スズミ" = "そ、そうでしょうか……。"
"10049040-28-スズミ" = "ですが、私……魔法少女の作品は子供のころに観たっきりですし……。"
"10049040-29-スズミ" = "なにより、大勢の前に立つのは……想像するだけで怖いです……。"
"10049040-30-レイサ" = "スズミさんはカッコいいですから！心配する必要なんてありません！"
"10049040-31-レイサ" = "自警団として、いつも堂々としてるじゃないですか！"
"10049040-32-スズミ" = "それとこれとは別問題です！"
"10049040-33-スズミ" = "私はどうしたら……。"
"10049040-34" = "[ns3] \"それっぽいセリフを言うのはどう？\"\n[ns4] \"時間稼ぎだと思ってさ。\""
"10049040-35-スズミ" = "ですが、どんなセリフを言えばいいか……。"
"10049040-36-レイサ" = "ふふん、テルミットホワイトのセリフですね！"
"10049040-37-レイサ" = "私にお任せください！"
"10049040-38-スズミ" = "それは……ペンですか？"
"10049040-39-スズミ" = "「ペン」ではありません！"
"10049040-40-レイサ" = "「マジカル・カンニング」です！"
"10049040-41-レイサ" = "今からこれで――"
"10049040-42-レイサ" = "スズミさんの手のひらにセリフを書いてあげます！"
"10049040-43-スズミ" = "ま、待ってください！そんないきなり――きゃっ！"
"10049040-44-スズミ" = "くっ、ふふっ……くすぐったいです！あははっ！！"
"10049040-45" = "[ns] （スズミってあんな笑い方もするんだ）"
"10049040-46-レイサ" = "準備オッケーです！"
"10049040-47-スズミ" = "はぁ、はぁ……。"
"10049040-48-スズミ" = "私、くすぐりには弱くて……。"
"10049040-49-スズミ" = "手のひらは特に……！！"
"10049040-50-レイサ" = "でも、これでなんとかなると思います！"
"10049040-51-スズミ" = "なんとかって……。"
"10049040-52-公演のマネージャー" = "さぁ、ショーが始まりますよ！"
"10049040-53-スズミ" = "はい！！"
"10049040-54-スズミ" = "ま、まだセリフの確認が……！もう少し時間を……！"
"10049040-55-スズミ" = "それに、敵役のシミコさんがいなくていいんですか！？"
"10049040-56-レイサ" = "スケジュールだと……今は私たちだけでいいみたいです！"
"10049040-57" = "[ns5] \"がんばれ！\"\n[ns6] \"ファイト！テルミットホワイト！\""
"10049040-58-スズミ" = "う、うわあぁぁああ！！"
"10049040-59-子供A" = "テルミットホワイトだ！"
"10049040-60-子供B" = "テルミットピンクもいる！"
"10049040-61-子供A" = "かわいいね！お姫さまみたい！！"
"10049040-62-スズミ" = "（さっきよりも観客が増えていませんか！？）"
"10049040-63-スズミ" = "（みなさん、私を見て、歓声を……）"
"10049040-64-スズミ" = "（怖い……どうしよう、足がすくむ。指先の感覚がない、こわい）"
"10049040-65-スズミ" = "（私には……できません。こんな風に、期待されてしまうのは……）"
"10049040-66-レイサ" = "ボルトフォワード！テルミットピンク！"
"10049040-67-スズミ" = "わあああっ！！！"
"10049040-68-スズミ" = "レイサさん！？"
"10049040-69-レイサ" = "スズミさんの番ですよ！"
"10049040-70-レイサ" = "最高にカッコいい姿を見せてくださいっ！！"
"10049040-71-スズミ" = "（レイサさんは、どうして平気なんでしょうか……）"
"10049040-72-スズミ" = "……ふぅ。"
"10049040-73-スズミ" = "ボルトキャッチ！テルミットホワイト！"
"10049040-74-スズミ" = "わあああああぁぁぁぁぁぁ！！！"
"10049040-75-子供B" = "ホワイト！！ホワイト！！"
"10049040-76-子供B" = "わあああぁぁ！！"
"10049040-77" = "[ns] \"テルミットホワイト！！最高だぁーっ！！！\""
"10049040-78-レイサ" = "あははっ！先生の声、ここまで聞こえてますよ！！"
"10049040-79-スズミ" = "先生……！"
"10049040-80-レイサ" = "こほん……。#n大変です！この遊園地に……エラとその手下たちが隠れているみたいです！"
"10049040-81-スズミ" = "えっ、あ、それは本当ですか？"
"10049040-82-レイサ" = "はい！きっと、友情エネルギーを奪おうとしているんです！"
"10049040-83-スズミ" = "（良かった……なんとか乗り切れそうですね……）"
"10049040-84-スズミ" = "（先生の言う通り、ステージの上からだと周りがよく見えます……これなら……）"
"10049040-85-スズミ" = "（あっ、汗が……）"
"10049040-86-スズミ" = "（あっ……つい手で汗を……！）"
"10049040-87-スズミ" = "（書いてもらった字が滲んで……！）"
"10049040-88-レイサ" = "テルミットホワイト！これからどうしますか？"
"10049040-89-レイサ" = "……スズミさん！次のセリフです！"
"10049040-90" = "[ns] \"スズミ……？\""
"10049040-91-スズミ" = "あ、え、えっと……。"
"10049040-92-スズミ" = "ケーキには、バターが必要……ですよね……？"
"10049040-93-レイサ" = "え……？"
"10049040-94" = "[ns] （どういうセリフだろう……？）"
"10049040-95-子供A" = "テルミットホワイト？"
"10049040-96-子供B" = "どういう意味……？"
"10049040-97-子供A" = "あの子ほんとにテルミットホワイトなの？"
"10049040-98-レイサ" = "な、なるほど！ホワイトは「シュガーマジカルパワー」を使うつもりですね！"
"10049040-99-レイサ" = "よーっし、ピンクも準備します！"
"10049040-100-レイサ" = "ちょっと、必殺技の練習をしておきましょう！"
"10049040-101-レイサ" = "みんなー！力を貸してくださいねー！"
"10049040-102-子供B" = "はーいっ！！"
"10049040-103-子供B" = "するー！！"
"10049040-104" = "[ns7] \"レイサがアドリブでフォローした！\"\n[ns8] \"すごいよ、レイサ！\""
"10049040-105-スズミ" = "（必殺技のセリフ、これはまだ滲んでいません。それなのに……）"
"10049040-106-スズミ" = "（どうしましょう……声が、出ません……）"
"10049040-107-スズミ" = "（レイサさんがフォローしてくれたのですから……早く、次のセリフを言わないと……）"
"10049040-108-スズミ" = "み、みんなの平和のために……。"
"10049040-109-スズミ" = "誰ひとり……分かってくれなくても……。"
"10049040-110-スケバンA" = "なんで自警団なんかやってんだ？誰も分かっちゃくれねぇだろ？"
"10049040-111-スズミ" = "……そう、なんですか？#n私の行いは――"
"10049040-112-スズミ" = "やはり……。"
"10049040-113-スズミ" = "私、は……。"
"10049040-114-スズミ" = "私には……できません……。"
"10049040-115" = "[ns] \"スズミ……！\""
"10049040-116-スズミ" = "……。"
