[translation]
"10049055-1-レイサ" = "はぁ……はぁ……。"
"10049055-2-レイサ" = "うっ……はぁ……。"
"10049055-3-スズミ" = "（レイサさんのショットガンも、私の閃光弾も……まともに使えませんでした）"
"10049055-4-スズミ" = "（子供がいる状況では、とても……）"
"10049055-5-スズミ" = "（なにより……迷いがあるせいで、戦闘に集中できませんでした……）"
"10049055-6-スズミ" = "（こんな調子では、何も守れませんね……）"
"10049055-7-スズミ" = "（やはり、私は……）"
"10049055-8" = "[ns] \"マシロ、威嚇射撃ならできる？\""
"10049055-9-マシロ" = "……申し訳ありません。"
"10049055-10-マシロ" = "まだ発砲許可が下りていません。"
"10049055-11-マシロ" = "それに、いま皆さんがいるのはゲヘナのエリアです。"
"10049055-12-マシロ" = "私にはどうすることも……本当に、申し訳ありません……。"
"10049055-13-レイサ" = "正義は……負け、ません……もう一度……！"
"10049055-14-スズミ" = "もう……やめてください……！"
"10049055-15-ラブ" = "こいつら、何なの？全然相手にならないじゃない。"
"10049055-16-ラブ" = "強そうに見えたけど……警戒して損したわ。"
"10049055-17-ラブ" = "じゃ、これでおしまい。"
"10049055-18-スズミ" = "……！"
"10049055-19-観客A" = "え？魔法少女が負けたのか？"
"10049055-20-観客B" = "まっさか～それだとショーがおかしくなっちゃうじゃん？"
"10049055-21-観客A" = "うーん、そうかな？#nそれより、さっきのアクション見た？超リアルだったよね！"
"10049055-22-ラブ" = "……ん？"
"10049055-23-ラブ" = "ショー……？これが……？"
"10049055-24-子供B" = "テルミットホワイト！ピンク！"
"10049055-25-子供B" = "負けるなー！がんばえー！うわぁーん！"
"10049055-26-子供A" = "魔法少女はせいぎの味方、って言ってたじゃん！負けるなー！うわぁーん！"
"10049055-27-子供B" = "うわぁーん！悪いヤツ大っ嫌い！！"
"10049055-28-スズミ" = "うぅっ……はぁ……。"
"10049055-29-スズミ" = "少し……確認したいことがあるだけだと……言ったじゃないですか……。"
"10049055-30-レイサ" = "魔法少女のスーパースター、テルミットピンクは負けません……！"
"10049055-31-ラブ" = "（えー、なによこれ……）"
"10049055-32-ラブ" = "（子供らは泣くし、あいつらはまだ立ち上がるし）"
"10049055-33-ラブ" = "（それに、うちが悪いヤツ……？さっぱり状況が分かんないんだけど……）"
"10049055-34-ラブ" = "ぐぬ……ぐぬぬ……！"
"10049055-35-ラブ" = "ぐあーっ！ヤーラーレーター！"
"10049055-36-ジャブジャブヘルメット団B" = "隊長！？"
"10049055-37-ラブ" = "や、やっぱり、強いなぁ！なんとかホワイト！ピンク！"
"10049055-38-ラブ" = "あ、あんたらがいるなら……えっと……。"
"10049055-39-ラブ" = "――遊園地は安全だな！"
"10049055-40-ジャブジャブヘルメット団A" = "い、いきなりどうしたんですか！？"
"10049055-41-ジャブジャブヘルメット団A" = "勝ったのはうちらですよね！？"
"10049055-42-ラブ" = "バカ！空気読みなさいよ！#nうちらは目的さえ達成すればいいんだから！"
"10049055-43-ラブ" = "早くあれ持って逃げて。お前たちはターゲットに集中しなさい！"
"10049055-44-ジャブジャブヘルメット団A" = "は、はいっ！"
"10049055-45-ラブ" = "あんたらの勝ちだー！"
"10049055-46-子供B" = "わっ――"
"10049055-47-子供B" = "わああぁぁぁ！！！"
"10049055-48-子供B" = "勝ったぁ！"
"10049055-49" = "[ns1] \"ここでいったん休憩でーす！\"\n[ns2] \"二人とも、立てる？\""
"10049055-50-スズミ" = "先生……。"
