[translation]
"10049130-1" = "後日談その3;ヘルメット団ブルース"
"10049130-2" = "[log]5日前[/log]"
"10049130-3-ラブ" = "じゃあ、もう一度整理するわよ。"
"10049130-4-ラブ" = "うちらは今週末、「ボーダーランド遊園地」で詐欺まがいの行商人を捕まえる。"
"10049130-5-ラブ" = "そのためなら、どんな手を使っても構わないわ。#n……何か質問ある？"
"10049130-6-ラブ" = "はい、隊長！"
"10049130-7-ラブ" = "はい、言ってみなさい。"
"10049130-8-ジャブジャブヘルメット団A" = "入園料はどうしますか？遊園地に入らないと話が始まりません！"
"10049130-9-ラブ" = "たしかに……うちらの財布事情じゃ、一番安いチケットも無理ですよ。"
"10049130-10-ラブ" = "今から自販機を蹴って回っても、大したお金にならないですし……。"
"10049130-11-ジャブジャブヘルメット団B" = "遊園地の食べ物とかも、高くて買えないんじゃ……。"
"10049130-12-ジャブジャブヘルメット団A" = "あれ？そもそもうちらの人数で、どうやってあんなに広い場所から探し出せばいいの……？"
"10049130-13-ジャブジャブヘルメット団A" = "どうしよう……。"
"10049130-14-ジャブジャブヘルメット団B" = "無理だぁ……。"
"10049130-15-ラブ" = "ふっ。"
"10049130-16-ラブ" = "ふっふっふ……。"
"10049130-17-ラブ" = "今回は……いつもとは違うわよ？"
"10049130-18-ラブ" = "なんと……依頼主がチケットを用意してくれたわ！"
"10049130-19-ラブ" = "しかも、助っ人で他のヘルメット団からも応援が来る！"
"10049130-20-ジャブジャブヘルメット団B" = "た、隊長！！"
"10049130-21-ジャブジャブヘルメット団B" = "それ、本当ですか！？どこでこんな良い依頼を……！"
"10049130-22-ラブ" = "うちらだって、たまには「良い仕事」をしたっていいでしょ？"
"10049130-23-ラブ" = "それに、驚くのはまだ早いわよ。なんと――"
"10049130-24-ラブ" = "チケットはフリーパス！"
"10049130-25-ラブ" = "フリーパス！！"
"10049130-26-ジャブジャブヘルメット団B" = "あそこのアトラクション、全部乗れるってことですか？一日中！？"
"10049130-27-ラブ" = "しかも、ただのフリーパスじゃないわ！週末のフリーパスよ！"
"10049130-28-ジャブジャブヘルメット団A" = "隊長！一生ついて行きます！！"
"10049130-29-ジャブジャブヘルメット団B" = "応援が来て、しかも入園はタダ！こんなん勝ち確ですよ！"
"10049130-30-ラブ" = "一番乗りで入らないと！"
"10049130-31-ジャブジャブヘルメット団A" = "や、ほら、いつターゲットが現れるか分かりませんからね！"
"10049130-32-ジャブジャブヘルメット団A" = "お弁当の用意しないとね！ターゲットを捜すのに時間かかるかもしれないし！"
"10049130-33-ジャブジャブヘルメット団A" = "手がかりも必要だから……いっぱい写真撮りましょう！"
"10049130-34-ジャブジャブヘルメット団A" = "へへっ！"
"10049130-35-ラブ" = "遊ぶことばっか考えてないで、ちゃんと仕事しなさいよね。"
"10049130-36-ラブ" = "捕まえられたら、褒賞金で焼肉パーティーよ！"
"10049130-37-ジャブジャブヘルメット団A" = "やったぁ！"
"10049130-38-ジャブジャブヘルメット団B" = "隊長サイコー！"
"10049130-39-ラブ" = "うーん……。"
"10049130-40-ラブ" = "うーーん……？"
"10049130-41-ジャブジャブヘルメット団A" = "隊長、もう入園時間ですよ？"
"10049130-42-ジャブジャブヘルメット団B" = "入らないんですか？"
"10049130-43-ジャブジャブヘルメット団A" = "遅れたら、アトラクションの列長くなっちゃいますよ……。"
"10049130-44-ラブ" = "応援に来るはずのやつらがまだなのよ。"
"10049130-45-ラブ" = "うちらの分のチケットも、そいつらが持ってるのに！"
"10049130-46-ジャブジャブヘルメット団A" = "もしかして、裏切られた！？"
"10049130-47-ラブ" = "なんで！？まだお金が動いたわけでもないのに……。#nまさか、依頼を横取りするつもり！？"
"10049130-48-ラブ" = "いま連絡してみるから。もし裏切ってたら、ただじゃ置かないわよ！"
"10049130-49-ジャブジャブヘルメット団B" = "はい！"
"10049130-50-ラブ" = "ねぇ、今どこにいるのよ！？本当に来るんでしょうね？"
"10049130-51-ラブ" = "もし裏切ったんなら――"
"10049130-52-ラブ" = "す、すまん！うちらだってそっちに向かってるんだ！でも……！"
"10049130-53-ラブ" = "全員やられちまったんだよ！！"
"10049130-54-ラブ" = "は？どこで？ターゲットから奇襲でもされたの？"
"10049130-55-ラブ" = "列車だよ！列車に乗ってたのに、途中でいきなり乗務員が！"
"10049130-56-ラブ" = "ハイランダーは狂ったのか！？"
"10049130-57-ラブ" = "お、おい！やめろ！！"
"10049130-58-？？？" = "――しません！"
"10049130-59-？？？" = "定時運行を邪魔する乗客は許しません！"
"10049130-60-デコボコヘルメット団のリーダー" = "うわあああっ！！"
"10049130-61-ジャブジャブヘルメット団A" = "隊長……？"
"10049130-62-ジャブジャブヘルメット団B" = "何が起きてるんですか……？"
"10049130-63-ラブ" = "列車に乗ってたら、乗務員が狂ったって……。"
"10049130-64-ジャブジャブヘルメット団A" = "は？"
"10049130-65-ジャブジャブヘルメット団B" = "え、なんで？"
"10049130-66-ラブ" = "分かんないけど……。"
"10049130-67-ラブ" = "これって、裏切られたってことでいいの……？"
"10049130-68-ジャブジャブヘルメット団A" = "隊長、これ、どこに向かってるんですか？"
"10049130-69-ジャブジャブヘルメット団B" = "遊園地の入場ゲートはこっちじゃないですよ？"
"10049130-70-ラブ" = "はぁ、はぁ……地図によれば、この遊園地には動物園があるみたいなの。"
"10049130-71-ラブ" = "動物園ってのは、中にいる動物が外に出ないように力を入れてる場所。#nつまり、外部からの侵入には脆いのよ。"
"10049130-72-ラブ" = "それに、動物が警報器を触るからって、電源を切ってるところも多い。"
"10049130-73-ラブ" = "で、さっき調べてみたら、今日の動物園は臨時休館中。"
"10049130-74-ラブ" = "潜入するのにピッタリってわけ！"
"10049130-75-ジャブジャブヘルメット団B" = "すげぇ……どうしてそんなことまで知ってるんですか？"
"10049130-76-ジャブジャブヘルメット団A" = "うちらと違って、隊長は勉強が嫌いで逃げたわけじゃないんだよ！"
"10049130-77-ラブ" = "隊長、そうですよね？しかも、前は成績良かったって聞きましたよ。"
"10049130-78-ラブ" = "うるさい。あんな学園、好きで通ってたわけじゃないの。"
"10049130-79-ラブ" = "最初は我慢しようと思ったけど……。#nやっぱり息が詰まって無理だったわ。"
"10049130-80-ラブ" = "でも[ruby=カーニバル]謝肉祭[/ruby]は、一回くらい参加しといても良かったかもしれないわね。#nその前に中退しちゃったから。"
"10049130-81-ジャブジャブヘルメット団A" = "ほんと、隊長の昔話はいつ聞いても不思議ですね。"
"10049130-82-ラブ" = "何か文句でもあるの？"
"10049130-83-ラブ" = "って、無駄話はおしまい。#n――ここにするわよ。"
"10049130-84-ラブ" = "今は手元にないだけで、ちゃんとうちらの分のチケットは用意されてるはず。だから、これは不法侵入じゃないわ。"
"10049130-85-ジャブジャブヘルメット団B" = "言われてみれば！一応、チケットはあるし……？"
"10049130-86-ジャブジャブヘルメット団B" = "隊長、やっぱ頭いいですね！"
"10049130-87-ラブ" = "いいから！あんたらも早くこっちきなさい！"
"10049130-88-ラブ" = "ビンゴ！警報器はないみたいね。"
"10049130-89-ラブ" = "なんか、野生っぽく作られてるんですね。"
"10049130-90-ラブ" = "野生？"
"10049130-91-ラブ" = "よっし、このまま遊園地まで行くわよ！"
"10049130-92-ラブ" = "応援もチケットもないけど、心配ないわ！#nだってこんなところに――"
"10049130-93-ラブ" = "ワニなんか現れるはずないんだから！"
"10049130-94-ラブ" = "ちょっと、どうしたの？#n急に震えて……。"
"10049130-95-ジャブジャブヘルメット団A" = "隊長……！心配ないとか言えないっすよ！"
"10049130-96-ラブ" = "え？"
"10049130-97-ジャブジャブヘルメット団B" = "だって、ここ……ワニの檻です……！"
"10049130-98-ラブ" = "本物のワニ……？#n動物園だから？"
"10049130-99-ラブ" = "まぁ、そりゃそうよね。"
"10049130-100-ラブ" = "うわあああぁぁぁああああっ！"
