[translation]
"10042070-1" = "第7話;LAST GIRL STANDING"
"10042070-2-チナツ" = "ジュリさん！？"
"10042070-3-セナ" = "いけません、チナツ。#n巻き込まれてしまいます。"
"10042070-4-セナ" = "で、でも……！"
"10042070-5-アコ" = "んうっ！んんっ！！！んんーーっ！"
"10042070-6-セナ" = "……ああなりたいのですか？"
"10042070-7-セナ" = "い、いえ……。"
"10042070-8" = "こっちです！"
"10042070-9" = "さあ、あなたの相手は私です！"
"10042070-10" = "それ以上、暴れたいのなら……！"
"10042070-11" = "私を倒してからにしてくださいっ！！！"
"10042070-12-フウカ" = "……止まった！？"
"10042070-13" = "[ns] \"これは……！\""
"10042070-14-セナ" = "自身が囮になって、攻撃のチャンスを作る……。"
"10042070-15-セナ" = "まるで映画のワンシーンのようですね。#n先生も、ポップコーン食べますか？"
"10042070-16-フウカ" = "それ、どこから持ってきたのよ……。"
"10042070-17-フウカ" = "……ジュリ！"
"10042070-18-チナツ" = "ジュリさん……！"
"10042070-19-セナ" = "……（もぐもぐ）"
"10042070-20-ジュリ" = "先生、今です！"
"10042070-21" = "[ns1] \"動きが止まった……！\"\n[ns2] \"今だ、撃てーっ！\""
"10042070-22-フウカ" = "ほ、砲撃の権限を持つ人が……！"
"10042070-23-フウカ" = "行政官の口が触手で塞がれています。#nそれに、どうやら気絶しているようで……。"
"10042070-24-チナツ" = "権限が移譲されない限り、発砲は難しいかと。"
"10042070-25-フウカ" = "えっ、あなたも風紀委員でしょ！？#n代わりに命令しちゃダメなの！？"
"10042070-26-チナツ" = "私も、そうしたい気持ちはやまやまですが……。"
"10042070-27-セナ" = "仕方ありません。#nこういった組織は、指揮系統を何よりも大切にしていますから。"
"10042070-28-フウカ" = "で、でも――"
"10042070-29-？？？" = "話は聞かせてもらったわ。"
"10042070-30-？？？" = "アコが急に砲撃部隊を動かすから、何事かと思ったら……。"
"10042070-31" = "[ns] \"この声は！\""
"10042070-32-ヒナ" = "現時刻をもって、アコが持つ砲撃隊の運用および統制権限を、シャーレの先生へ移譲する。"
"10042070-33-ヒナ" = "動員された全風紀委員は、作戦終了まで先生の指揮に従うように……以上。"
"10042070-34" = "[s3] \"ヒナ！\"\n[s4] \"ナイスタイミング……！！\""
"10042070-35-ヒナ" = "あまり時間がないように見えるけど。"
"10042070-36-ヒナ" = "それじゃあ、先生。#n現場の指揮をお願い。"
"10042070-37-ヒナ" = "……ああ、それと。"
"10042070-38-ヒナ" = "眠っていた人員を、一人向かわせておいたから。"
"10042070-39-チナツ" = "眠っていた人員……？"
"10042070-40-チナツ" = "あっ！"
"10042070-41-イオリ" = "今度こそ油断しないぞ……！！"
"10042070-42-イオリ" = "借りは返させてもらうからな！！"
"10042070-43-イオリ" = "なるほど、フラグ回収ですね。"
"10042070-44-イオリ" = "これで全員揃いました。"
"10042070-45-イオリ" = "では、先生……指揮をお願いします。"
"10042070-46" = "[ns] \"砲撃隊――\""
"10042070-47" = "[ns] \"――発射！！！\""
"10042070-48-セナ" = "巨大パンケーキの動きが鈍くなりました。"
"10042070-49-セナ" = "――早く「とどめ」を刺さなくては。"
"10042070-50-チナツ" = "一斉射撃の後に突撃を行うのは、定石ですからね。"
"10042070-51" = "[s5] \"じゃあ、そろそろ……。\"\n[s6] \"この戦いを、終わらせにいこう。\""
