[translation]
"700" = "先生！"
"701" = "昨日私、すごい本を読んだの！"
"702" = "すごい本？"
"703" = "うん！アスリートの人の自伝だったんだけど……"
"704" = "そこに、食べ物がすっごく美味しくなる方法が書いてあったの！"
"705" = "すっごく美味しくなる方法？"
"706" = "なんでアスリートの自伝にそんなことが……？"
"707" = "これは美食研究会のメンバーとして、試さずにはいられないわね"
"708" = "善は急げだよ、先生！"
"709" = "先生！先生！"
"710" = "今日から中央広場で、屋台がいっぱい出店するフェスが開かれるの！"
"711" = "そうなんだ。イズミ、すごく楽しそうだね"
"712" = "うん！私、ずっとこの日を待ってたの！"
"713" = "今日は特に、プリンですごく有名なあのお店が参加するし……！"
"714" = "あれは絶対に食べないと！"
"715" = "先生！ゲヘナの商店街に新しいラーメン屋ができたんだって！"
"716" = "一緒に行こう！"
"717" = "下見と、偵察に！"
"718" = "それ、どっちも同じ意味じゃない？"
"719" = "あれっ、そうなの？"
"100090010" = "ねえ、先生！"
"100090020" = "先生に食べてほしいものが……"
"100090030" = "ううん、見せたいものがあるの！"
"100090040" = "見せたいもの？"
"100090050" = "うん！"
"100090060" = "だからね先生、ちょっと来てくれる？"
"100090070" = "分かった。行くね"
"100090080" = "やったー！"
"100090090" = "それじゃ、待ってるね！"
