[translation]
"1" = "先生。急だけど話したいことがあるの"
"2" = "私の仕事が終わった後、深夜だけど少し会える？"
"3" = "もちろん、ヒナの頼みなら"
"4" = "深夜まで仕事があるんだね……お疲れ様……"
"5" = "遅い時間にごめん、じゃあ場所は……"
"6" = "私のせいで、睡眠時間が短くなってたりしない？"
"7" = "もしそうだったら言って"
"8" = "迷惑はかけたくないから"
"9" = "ヒナのためならいくらでも"
"10" = "私は大丈夫。ヒナも、ちゃんと寝てね"
"11" = "……ん、ありがとう"
"12" = "おやすみ、先生"
"13" = "先生。今度の休みの日の深夜、時間ある？"
"14" = "こっちは前と同じくらいの時間に仕事が終わる予定"
"15" = "都合が悪かったら大丈夫"
"16" = "全然問題ないよ"
"17" = "あの後も少し考えてみたけど、周りの視線を気にしすぎるのも良くないかも"
"18" = "あくまでも業務上のミーティングだから"
"19" = "今度からは、もっと明るい昼間に時間を作って会うとか……"
"20" = "明るい時間帯からヒナに会えるなんて……"
"21" = "すっごい楽しみ"
"22" = "何を言ってるの……"
"23" = "デートとかじゃないから、分かってる？"
"24" = "これは仕事だから"
"25" = "明るい時間帯から始めるヒナとのお仕事……楽しみだなあ"
"26" = "……"
"27" = "はあ……"
"28" = "もういい。私も、まあ……"
"29" = "少しは、楽しみにしてる"
"30" = "はい、話はこれで終わり。おやすみ、先生"
"31" = "先生"
"32" = "今月の射撃訓練の報告書のことでちょっと……"
"33" = "そんなことより、ヒナちゃん"
"34" = "今はもっと大事なことがあるよ"
"35" = "……？"
"36" = "なに？"
"37" = "何か忘れてる議題でも……"
"38" = "一緒にショッピングにでも行こう"
"39" = "……"
"40" = "……は？"
"41" = "え？"
"42" = "ショッピング？"
"43" = "……どうして？"
"44" = "約束だから"
"45" = "大事な用事だから"
"46" = "でも、ショッピングモールとか夜は閉まってるし……"
"47" = "24時間営業のところか"
"48" = "普通にお昼に"
"49" = "あ"
"50" = "……ごめん、今理解した"
"51" = "……"
"52" = "……うん、約束したんだった"
"53" = "わかった"
"54" = "時間作るから、待ってて"
"55" = "先生"
"56" = "今日は、この間の仕事の"
"57" = "今日は陽射しが気持ちいいね"
"58" = "すごく良い天気"
"59" = "え？"
"60" = "天気……？"
"61" = "別に、天気が良くても何も変わらない"
"62" = "つまり、絶好の散歩日和！"
"63" = "仕事より散歩に行こう！！"
"64" = "散歩……？"
"65" = "えっと……"
"66" = "今から？"
"67" = "……まあ、ちょっとだけなら……"
"68" = "全く……"
"69" = "先生は本当に……"
"70" = "……全くもう"
"71" = "ここ数日、徹夜でバタバタしっぱなし……ほんと面倒"
"72" = "遠出が必要な件も多くて、処理できてない書類は溜まっていく一方だし……"
"73" = "何か起こるとみんな私の方ばっかり見るし……"
"74" = "……ふう"
"75" = "そのせいで、みんなが休んでる日にもこうして一人で仕事……"
"76" = "めんどくさい、ムカつく"
"77" = "はあ……"
"78" = "みんなから頼りにされてるんだね"
"79" = "委員長は大変だね、お疲れ様"
"80" = "……"
"81" = "ごめん、つい愚痴になった"
"82" = "忘れて"
"83" = "えっと……"
"84" = "昨日の夜、私、何か変なこと言ったり……してない？"
"85" = "夢だったのかはっきりしなくて、あまり思い出せないけど……なんだか……"
"86" = "ものすごく恥ずかしいことを……"
"87" = "いや……"
"88" = "そんなことない、よね？"
"89" = "何の話？"
"90" = "夢を見てたんじゃないかな？"
"91" = "……"
"92" = "うん、そういうことにしておく"
"93" = "……ありがとう"
"100040010" = "先生、ちょっと良い？"
"100040020" = "どうかしたの？"
"100040030" = "あ、その……"
"100040040" = "今日はお休みなんだけど……"
"100040050" = "先生さえよければ"
"100040060" = "一緒に過ごしたいなと思って……"
"100040070" = "良かったね、お休みが取れたんだ"
"100040080" = "私が先生に会いたいだけだし……"
"100040090" = "忙しいなら、無理には……"
"100040100" = "むしろ、無理にでも誘って！"
"100040110" = "すぐそっちに行くね！"
"100040120" = "……えっ？"
"100040130" = "ふふっ"
"100040140" = "じゃあ待ってるわ、先生"
