[translation]
"1249" = "気になることがあったら、いつでも何でも何度でも！"
"1250" = "わざわざ調べに行かずとも、ぜひこのコトリに聞いてください！"
"1251" = "コトリの専門は自然科学全般だっけ？"
"1252" = "何でも……？"
"1253" = "えっと、そうですね……"
"1254" = "一応私の専攻は主に自然科学全般ですが、"
"1255" = "基本的には、何でも大丈夫です！"
"1256" = "私に説明出来ることでしたら、何でもどんとこいです！"
"1257" = "先生？どこへ行かれたんですか？"
"1258" = "まさか、逃げたわけではありませんよね？"
"1259" = "……先生？"
"1260" = "気になることがあればいつでも言ってくださいね！"
"1261" = "知的好奇心の傍には、いつもコトリがいますから！"
"1262" = "ありがとうございました、先生！感動しました！"
"1263" = "まさかここまでの速さで理解してくれるなんて！"
"1264" = "……えっと、先生、もしよろしければ時々でも良いので、"
"1265" = "……よろしくお願いしますね！"
"1266" = "先生"
"1267" = "今お時間ありますでしょうか？"
"1268" = "あ、大したことではないのですが"
"1269" = "いえ、個人的には大事なことなのですが……！"
"1270" = "と、とにかくですね……"
"1271" = "その、"
"1272" = "ちょっと、質問と言いますか"
"1273" = "お聞きしたいことがありまして……！"
"1274" = "大丈夫だよ、どうしたの？"
"1275" = "説明じゃなくて質問？"
"1276" = "あ、"
"1277" = "ありがとうございます！"
"1278" = "一も二も無く、さすが先生です！"
"1279" = "アウトプットのためにはインプットが必要ですから"
"1280" = "それに、"
"1281" = "他でもない、先生にこそ聞きたいことなんです！"
"1282" = "ふふっ、ではあの場所で"
"1283" = "待ってますね！"
"1284" = "……えっと"
"1285" = "あ、あらためまして、先ほどはありがとうございました！"
"1286" = "やっぱり先生に尋ねてみて正解でした！"
"1287" = "私の方からきちんと説明してあげられそうです！"
"1288" = "それは良かった"
"1289" = "結局どういうことだったの？"
"1290" = "えへへ……"
"1291" = "はい、本当に良かったです"
"1292" = "ありがとうございました、先生！"
"1293" = "そ、それは……"
"1294" = "その……"
"1295" = "……"
"1296" = "秘密、です……"
"1297" = "えっと、それでは、また"
"160020010" = "おはようございます！何か気になることがありましたら、いつでも仰ってください！"
"160020020" = "疑問や質問があれば、いつでもぜひこのコトリに！"
"160020030" = "……"
"160020040" = "念のためなのですが……"
"160020050" = "その、ミュート設定されてたり、しないですよね……？"
"160020060" = "時々、そういうこともあるので……"
"160020070" = "そんなことはないよ、それにちょうど聞きたいことがあって"
"160020080" = "ナイスタイミング、質問がありますコトリさん！"
"160020090" = "……"
"160020100" = "ほ"
"160020110" = "本当ですか！？"
"160020120" = "お任せください、何でもお答えしますよ！"
"160020130" = "それではコトリ！今すぐそちらへ参りますので！>_<"
"160020140" = "すみま"
"160020150" = "すみませんでした、先生……その、あまりにも予想外の質問だったと言いますか……"
"160020160" = "本当にその、不意を突かれたと言いますか……"
"160020170" = "すみません、前にもこんなことがあった気がしますね……"
"160020180" = "……"
"160020190" = "その"
"160020200" = "今度よろしければ"
"160020210" = "いえ、私の準備ができてないので、すぐではないのですが"
"160020220" = "その時でも、良いですか？"
"160020230" = "ちゃんと"
"160020240" = "ちゃんと答えを、出しますので"
"160020250" = "ふぅ！"
"160020260" = "危ないところでした！"
"160020270" = "コトリ？"
"160020280" = "どうしたの？"
"160020290" = "あ、大したことではありません！"
"160020300" = "実はメガネが壊れてしまい、修理をお願いしていたんです"
"160020310" = "一日ぐらいはなくても大丈夫だろうと思っていたのですが"
"160020320" = "私の視力では無理でしたね！あはは！！"
