[translation]
"1741" = "こんにちは、先生。スズミです。覚えていらっしゃいますでしょうか"
"1742" = "まずは挨拶だけでもと、ご連絡しました。お忙しいところすみません"
"1743" = "またいつかお会い出来たら嬉しいです"
"1744" = "それでは、また"
"1745" = "スズミです。先生、無事にお家に着きましたか？"
"1746" = "うん、おかげさまで。本当にありがとね"
"1747" = "いえ、それでしたら良かったです"
"1748" = "その、"
"1749" = "えっと、"
"1750" = "何と言えばいいのか……"
"1751" = "私が必要な時はいつでも言ってください。すぐにそばに行きます"
"1752" = "……えっと、"
"1753" = "エスコートの話、です"
"1754" = "先生、スズミです"
"1755" = "今日みたいに、エスコートが必要な時はいつでも言ってください"
"1756" = "私が先生の目的地まで安全にお送りしますので"
"1757" = "ありがとう、よろしくね"
"1758" = "女子高生怖い！助けてスズミ！"
"1759" = "はい、お任せください"
"1760" = "……えっと"
"1761" = "その……"
"1762" = "私も一応、女子高生なのですが……"
"1763" = "まあそれはともかく"
"1764" = "では、今日のお出かけの時間までにシャーレ前に行きますので"
"1765" = "また後ほど"
"1766" = "スズミです、今日はありがとうございました。楽しかったです"
"1767" = "また今度お会いしましょう、先生"
"1768" = "こんにちは、先生。スズミです"
"1769" = "よろしければいつでも呼んでくださいね"
"1770" = "今回はエスコートではなく、普通に同行させていただきますので"
"1771" = "えっと"
"1772" = "もちろん、お忙しいようでしたら無理に呼んでいただかなくても……"
"1773" = "スズミからのお呼びであればすぐにでも"
"1774" = "じゃあ、今から会えるかな？"
"1775" = "あｌ%$ｇ3ｒ#$%^"
"1776" = "……"
"1777" = "すみません"
"1778" = "スマホを落としました"
"1779" = "ありがとうございます"
"1780" = "それでは、今回の場所は私が選んでも良いですか？"
"1781" = "いつか、こうして一日中一緒に歩いていても、"
"1782" = "何も問題が起こらない、そんな日が来るといいですね"
"1783" = "……まあ、"
"1784" = "当面そんな日は来ないかもしれませんが……"
"1785" = "だからこそ、私がこうして活動していますので"
"160030010" = "おはようございます、先生。スズミです。"
"160030020" = "今日はどのようにお過ごしの予定でしょうか？"
"160030030" = "大した用事ではないものの、もし大丈夫でしたら少々お時間をいただきたく……"
"160030040" = "暇！！"
"160030050" = "スズミとの用件より大事なことも、そうそう無いよ"
"160030060" = "さ、左様でしたか"
"160030070" = "ではお言葉に甘えて、ありがとうございます"
"160030080" = "なんだか結果的に無理を言ってしまったようで申し訳ありません"
"160030090" = "では、後ほど場所についてはお送りしますね"
"160030100" = "その"
"160030110" = "いえ、何でもありません。では後ほど、よろしくお願いします"
"160030120" = "スズミです。無事に帰られましたでしょうか？"
"160030130" = "遅い時間にも関わらず、わざわざありがとうございました"
"160030140" = "もう深夜ですので、こういったメッセージを送って起こしてしまったら……とも思ったのですが"
"160030150" = "やはり、感謝を伝えねばと"
"160030160" = "……"
"160030170" = "ありがとうございます、先生"
"160030180" = "これからも、どうぞよろしくお願いします"
"160030190" = "こんにちは、先生。スズミです"
"160030200" = "近々、トリニティにいらっしゃるご予定があると伺いました"
"160030210" = "その……"
"160030220" = "もし、よろしければ"
"160030230" = "その際に、エスコートをさせていただけたらと思います"
"160030240" = "私はいつでも大丈夫ですので"
"160030250" = "ご連絡いただけると、とても嬉しいです"
"160030260" = "いつもありがとう、スズミ。お願いしてもいい？"
"160030270" = "じゃあ、久しぶりに二人で歩こうか"
"160030280" = "は、はい"
"160030290" = "ありがとうございます。それでは、また"
"160030300" = "いらっしゃる際に伺いますね"
"160030310" = "今日は本当にありがとうございました"
"160030320" = "先生のおかげで、とても楽しかったです"
"160030330" = "ありがとう。私も楽しかったよ"
"160030340" = "こちらこそ、これからもよろしくね"
"160030350" = "いや"
"160030360" = "それは、その……"
"160030370" = "はい"
"160030380" = "これからもよろしくお願いします、先生"
"160030390" = "何かありましたら、お気軽にご連絡ください"
"160030400" = "いえ"
"160030410" = "理由なんてなくても大丈夫です"
"160030420" = "……先生なら、いつでも"
