[translation]
"200100010" = "本日もお仕事、大変お疲れ様でございました"
"200100020" = "先生さえよろしければ、ぜひお疲れの身体を労わって差し上げたいのですが、いかがでございましょう？"
"200100030" = "……何か変な物でも食べた？"
"200100040" = "ただ気遣ってるだけなのに酷くないですか！？"
"200100050" = "はっ"
"200100060" = "な、何でもありません。お気になさらず、おほほ……"
"200100070" = "大丈夫？何かあったの？"
"200100080" = "いえその、ちょっとした心境の変化と言いますか……"
"200100090" = "以前の温泉郷での運営を通じて、色々なことを学んだんです"
"200100100" = "お風呂を綺麗に掃除する方法から、様々な物品の在庫整理まで……"
"200100110" = "しかし特に接客では色々と至らずに、先生を始めとしてお客様方に失礼なことをしてしまった気がします"
"200100120" = "ですので次は失敗しないように、予行練習をしておこうと思いまして"
"200100130" = "つまりはそう、修行です！"
"200100140" = "この前の修行は完全に失敗でした"
"200100150" = "まさか会席料理というものが、あそこまでのものだったとは……"
"200100160" = "ほぼ毎日配給品だけを食べてきた私としては、あまりにも未知の世界で……"
"200100170" = "ですが私はめげません、まだまだやるべきことがありますから"
"200100180" = "次に取り組むべきは、温泉郷で一番大事な施設……温泉！"
"200100190" = "なるほど"
"200100200" = "温泉郷は文字通り、温泉を中心としたもの"
"200100210" = "立派な温泉があれば、お客様は自然と集まってきてくれるはず"
"200100220" = "なので今度は、お風呂場の掃除を頑張ってみようかと！"
"200100230" = "……どこで？"
"200100240" = "これまでの修行を経て、私は悟りました"
"200100250" = "接客の真髄というのは、料理や施設ではなく……従業員の態度そのものであるということに！"
"200100260" = "なるほど。それに美味しい料理があればバッチリだね"
"200100270" = "なるほど。それに立派な温泉があればバッチリだね"
"200100280" = "そ、そうですね……"
"200100290" = "ですがその、後者はしばらく厳しいと言いますか"
"200100300" = "私たちのお金では、なかなか高い料理や豪勢な施設は用意できないので……"
"200100310" = "とにかくまずはできることから！今回は温泉の女将らしく、気品のある所作を習得したいと思います"
"200100320" = "つまり、礼節の修業です！"
"200100330" = "先生"
"200100340" = "どうしたの？"
"200100350" = "いえ、大したことではないのですが……"
"200100360" = "片足を捻って先生におんぶしていただけたのであれば"
"200100370" = "もしかしてもう片方の足も怪我したら、もっと良いことをしていただけたり……？"
"200100380" = "とりあえず意図的なのはやめてもらえると……"
"200100390" = "あれから足は少しずつ良くなったのですが、まだ全快ではないという感じです"
"200100400" = "日常生活に支障はありませんが、いつも通り歩こうとするには少し痛くて……"
"200100410" = "ちょっとまだ修業は難しそうですね……"
"200100420" = "そういえばこの間、湯治に良いっていう温泉の話を聞いたんだけど"
"200100430" = "送っていくから、良かったら今週末どう？"
"200100440" = "あ、ありがとうございます"
"200100450" = "では週末に"
"200100460" = "ｍ"
"200100470" = "まｔ"
"200100480" = "待ってください、先生と一緒に温泉ですか！？！？"
