[translation]
"200170010" = "先生、こんにちは。えへへ……"
"200170020" = "えっと、先生のアカウントであってますよね？"
"200170030" = "ヒヨリ？"
"200170040" = "えヘヘ……はい。ええと、いま無"
"200170050" = ""
"200170060" = "……？"
"200170070" = "……ヒヨリ？"
"200170080" = "料のwifiを見つけたんです……えへへ"
"200170090" = "なんとか生き延びるすべはあるというか……"
"200170100" = "えっと……それで、先生は今何をしていらっしゃいますか？"
"200170110" = "先生？"
"200170120" = "あれ、どうして答えてくれないのですか？"
"200170130" = "……とうとう、私は先生にもみはなされてしまったんですか"
"200170140" = "そういうことですよね？終わりだ、もうほんとつにおわりでふうわああいあたあい"
"200170150" = "ヒヨリ落ち着いて、通信状態を確認してみよう"
"200170160" = "無料のWi-Fiだとメッセージの受信に時間がかかってるのかも"
"200170170" = "あ、た、たしかに。Wi-Fiが途切れてしまってましたね……"
"200170180" = "そういうことだったんですね……"
"200170190" = "すみません……"
"200170200" = "先生……えへへ、こんにちは"
"200170210" = "今日は運が良い日です"
"200170220" = "傷んだコンビニ弁当から咲いた、キノコのような私の人生にも……こんなことが起きるんですね"
"200170230" = "何か良いことでもあったの？"
"200170240" = "はい！実は今日……"
"200170250" = "あ、見た方が早いかもしれません。少々お待ちください……"
"200170260" = "写真を送りますね"
"200170270" = "先生、これ見られますか？"
"200170280" = "画像が送られてない……？あれ、どうして？"
"200170290" = "うわぁん！またWi-Fiが途切れてます！"
"200170300" = "まさかと思ったらそのまさかです！辛いです……まるで"
"200170310" = "……待って、会って話そうか"
"200170320" = "私の人生みたいな、画像の送信もろくにできないこのスマホ……って、ええ！？く、来るんですか？"
"200170330" = "……先生。私、考えてみたらお礼が言えてなかったみたいで……"
"200170340" = "あ、ありがとうございます……"
"200170350" = "また先生のお世話になったことをみんなに知られたら、怒られちゃうので……"
"200170360" = "買っていただいた雑誌は、私だけの秘密にしておきますね……"
"200170370" = "先生！今回の「ron-ro」の最新号で……"
"200170380" = "「学校では絶対教えてくれないマル秘知識10選」"
"200170390" = "という特集記事があるらしくて！！"
"200170400" = "えっと……そ、そうなんだ？"
"200170410" = "学校では絶対教えてくれないマル秘知識だなんて……"
"200170420" = "一体何でしょうか……先生はご存知ですか？"
"200170430" = "私もよく分からない……"
"200170440" = "さ、さあ……なんだろうね"
"200170450" = "先生も分からないものとは一体何でしょう！？"
"200170460" = "最新号が古紙になるまで普通数ヶ月はかかるのに……"
"200170470" = "その間どうやって待てばいいんですか……終わりです、完全にこの世の終わりです"
"200170480" = "一人でいる時、雑誌を読む以外にやることないのに……"
