[translation]
"1502" = "先生は注射、怖いですか？"
"1503" = "平気だよ"
"1504" = "注射無理！針怖い！"
"1505" = "そうなんですね、さすが大人です！"
"1506" = "生徒はみんな大抵、注射の針を怖がってしまって……"
"1507" = "やっぱり大人でも注射は怖いんですね……"
"1508" = "注射の針を見てゾッとするのは、大人も子供も関係ないのかもしれません"
"1509" = "でも先輩たち曰く、ベテランの看護師さんの注射は全然痛くないそうです"
"1510" = "注射が痛くなければ、病院を怖がる人も減りそうなのですが……"
"1511" = "どうすれば、痛くなくなるのでしょうか？"
"1512" = "先生、最近きちんと眠れてますか？"
"1513" = "目の下のクマもひどかったですし、すごく疲れた顔をしていましたが"
"1514" = "最近ちょっと不眠症っぽくてね……"
"1515" = "なんだか夜眠れなくって……"
"1516" = "やっぱり、そうだったんですか"
"1517" = "疲れは万病のもと！きちんと睡眠をとらないと病気になってしまうかもです"
"1518" = "先生がぐっすり眠れるよう、何か良い方法を探しておきますね"
"1519" = "明日のお昼、保健室に来てください！"
"1520" = "ハーブティーは良かったのですが眠るまで少し時間がかかってしまいますね"
"1521" = "そこで、ネットでもっと効果のあるものを見つけてきました！"
"1522" = "トリカブトの根っこ……？というもので淹れたお茶が良さそうです！"
"1523" = "殺す気！？"
"1524" = "先生は普段、どこでラジオ体操をしてるんですか？"
"1525" = "公園？学校？それともシャーレで？"
"1526" = "そういえば、先生がラジオ体操をしているところって見たことないですね"
"1527" = "ラジオ体操なんて、小学生以来やってないなあ……"
"1528" = "えっ、ラジオ体操やってないんですか？"
"1529" = "それじゃあ、はなまるスタンプがもらえないじゃないですか！"
"1530" = "先生も一緒に、私のいつもの公園に行ってラジオ体操をしましょう！"
"1531" = "やだ"
"1532" = "朝は眠い"
"1533" = "先生みたいに座りっぱなしの大人こそ、ちゃんと身体を動かさないと！"
"1534" = "さあ、行きましょう！"
"1535" = "久しぶりのラジオ体操の感想はいかがですか、先生？"
"1536" = "朝早く起きて体操をすると、すっきりしませんか？"
"1537" = "確かに、いつもより爽やかな気分"
"1538" = "でしょう？ラジオ体操は普段使わない筋肉もほぐすので健康に良いんです！"
"1539" = "ですので、これからは先生も毎日、朝のラジオ体操に参加してくださいね！"
"1540" = "もし来てなかったら、私がシャーレまで迎えに行きますから！"
"1541" = "せめて休日は勘弁して……"
"1542" = "図書館で古い医学書を見つけたのですが、知らない治療法だらけでした！"
"1543" = "もしかして……現代では秘匿された、禁断の医術なのでしょうか！？"
"1544" = "民間療法みたいなものじゃないかな？"
"1545" = "そういうことでしたか……"
"1546" = "ですが何事も挑戦です。もし先生が今度怪我をされたら試してみましょう！"
"1547" = "楽しみにしててくださいね！"
"1548" = "怪我を楽しみにっていうのはちょっと……"
"1549" = "シャーレの執務室はなんだか、少し殺風景な気がします"
"1550" = "花瓶なんか置いてみたら、素敵になるんじゃないでしょうか？"
"1551" = "先生はどんなお花が好きですか？"
"1552" = "お花ならだいたい好きだよ"
"1553" = "害のある花粉が飛ばなければ何でも"
"1554" = "それでは、私が好きなお花をいくつか見繕ってみますね！"
"1555" = "ハナエは何の花が一番好き？"
"1556" = "うーん……私もお花は何でも好きですが、一番はアサガオですね"
"1557" = "花開いたアサガオは、まるでトランペットで朝を知らせる天使みたいです"
