[translation]
"1558" = "先生、先生"
"1559" = "先生は、何かいつも大事にしているものはありますか？"
"1560" = "パッと思いつくものは無いかな……"
"1561" = "特別に好きで、集めているものは？"
"1562" = "お気に入りで、一日中持ち歩いてるものは？"
"1563" = "肌身離さず持っていて、少し手放すと不安になるもの、何かありませんか？"
"1564" = "そこまで執着するようなものは、私にはないかなあ……"
"1565" = "そうですか……難しいですね"
"1566" = "何が難しいの？"
"1567" = "いえ、何でもありません"
"1568" = "先生、「メリーさんの電話」という怪談をご存知ですか？"
"1569" = "聞いたことないかも"
"1570" = "ある少女の元に、昔捨てたはずのメリーという人形から電話が来るんです"
"1571" = "怖いのは、電話が来るたびにメリーさんが徐々に近づいてくるという……"
"1572" = "そういう話なんだ……ところで、どうして急にそんな怪談を？"
"1573" = "特に意味はありません、何となくです"
"1574" = "……その電話を逆探知したら、メリーさんの居場所が分かりますね"
"1575" = "メリーさん、私のスマホに電話をかけてきてくれないでしょうか"
"1576" = "怖いよ……"
"1577" = "先生、もしかして最近、変な電話がかかってきませんでしたか？"
"1578" = "怖い人から通話がかかってきたとか、怪しい内容の電話が来たとか……"
"1579" = "特に無かったと思うけど、どうして？"
"1580" = "実は……"
"1581" = "いえ、後ほど直接お話します"
"260010010" = "……あ"
"260010020" = "どうしたの？"
"260010030" = "パソコンにイヤホンを繋げたまま立ち上がって、危うく転びそうに"
"260010040" = "夢中になってるとよくあるよね"
"260010050" = "はい。聴覚というものは、繰り返しの刺激には簡単に慣れてしまうものですから"
"260010060" = "コタマは普段、どんな音楽を聴くの？"
"260010070" = "私がよく聞く音楽……"
"260010080" = "えっと、それは……"
"260010090" = "……"
"260010100" = "秘密です"
"260010110" = "なんで！？"
