[translation]
"10008090-1" = "第9話;対策委員会、集結！"
"10008090-2-黒亀組の組員A" = "こ、こいつら、めちゃくちゃ強い……！？"
"10008090-3-ホシノ" = "うへ～、まあおじさんもこういう時はちょっとくらいね～？"
"10008090-4-黒亀組の組員B" = "ぐ、これでは足りない……！支援を要請する！"
"10008090-5-アル" = "これじゃあキリがないわよ……！？"
"10008090-6-？？？" = "大勢で寄ってたかってなんて、ズルいですねー。"
"10008090-7-アル" = "……！"
"10008090-8-黒亀組の組員たち" = "があっ！？"
"10008090-9" = "[ns] \"ガトリング砲ってことは……！\""
"10008090-10-セリカ" = "ノノミ先輩まで！"
"10008090-11-ノノミ" = "お待たせしましたセリカちゃん！それに先生、あけましておめでとうございます☆"
"10008090-12-セリカ" = "っていうことはもしかして……。"
"10008090-13-シロコ" = "セリカ、お待たせ。"
"10008090-14-セリカ" = "シロコ先輩！"
"10008090-15-アル" = "ど、どうしてここにあなたたちが……！？"
"10008090-16-ホシノ" = "それにしても、便利屋のみんながセリカちゃんと一緒だなんてねぇ。"
"10008090-17-ホシノ" = "その上先生まで。意外な組み合わせで、おじさんもびっくりだよ。あ、そういえばあけましておめでと～。"
"10008090-18" = "[s] \"あけましておめでとう……ってそれより、どうしてここが……？\""
"10008090-19-シロコ" = "セリカから連絡があったから。"
"10008090-20-セリカ" = "連絡、って……"
"10008090-21-セリカ" = "あっ！"
"10008090-22-セリカ" = "こうなったら、協力を要請して……！"
"10008090-23-カヨコ" = "ああ、メッセージ送ったって言ってたね。"
"10008090-24-ノノミ" = "用件とかは書かれてなかったんですけどね☆ちょうどセリカちゃんのバイト先が生中継で映ってたので、これはもしかして？と思いまして。"
"10008090-25-ホシノ" = "うん、巻き込まれてたら困るなぁって思ってさ～。"
"10008090-26-シロコ" = "セリカ、こういうのに巻き込まれがちなイメージだし。"
"10008090-27-セリカ" = "そ、そうなの！？"
"10008090-28-アル" = "全てが書かれていなくても、仲間を助けるために飛び出すだなんて……。"
"10008090-29-ムツキ" = "アルちゃん、すっごい感激してるじゃーん♪"
"10008090-30-アル" = "べ、別にそういうのじゃないわよ！？"
"10008090-31-シロコ" = "それに、賽銭箱の中身は早い者勝ちって聞いて。"
"10008090-32-セリカ" = "何で今それ持ってるの！？"
"10008090-33-シロコ" = "ちゃんと準備してきた。"
"10008090-34" = "[s] \"あっ、でもその件についてはその……。\""
"10008090-35-セリカ" = "シロコ先輩、その賽銭箱なんだけど……"
"10008090-36-アル" = "全部嘘だったわよ。"
"10008090-37-シロコ" = "……嘘？"
"10008090-38-ホシノ" = "なるほどね～。今回の騒ぎの主犯はカイテンジャーじゃなくって、黒亀組だったってことかー。"
"10008090-39-ホシノ" = "いやぁ、それは災難だったねぇ。大人の悪意は困ったもんだー。"
"10008090-40-ノノミ" = "そういうことだったんですか……みんなを騙してお金を奪おうだなんて、許せません！"
"10008090-41-ノノミ" = "ですよね、シロコちゃん！"
"10008090-42-シロコ" = "全部、嘘……。"
"10008090-43" = "[s] \"シロコ、大丈夫……？\""
"10008090-44-ホシノ" = "シロコちゃん、すっごい期待してたもんね～。"
"10008090-45-シロコ" = "最初から騙してたなんて、許せない。"
"10008090-46-アル" = "そうよ、許してはおけないわ。だからその大吉殿の管理人とやらに、今からでも一発食らわせてやらないと。"
"10008090-47-アル" = "そういうことで……"
"10008090-48-アル" = "手伝ってくれない？"
"10008090-49-ムツキ" = "あはっ、ここでもう一回共同戦線？"
"10008090-50-アル" = "ええ、相手は雑魚だけれど数が多い。私たちだけでは厳しいわ。"
"10008090-51-ホシノ" = "まあ、特に断る理由は無いかな？"
"10008090-52-ノノミ" = "はい！セリカちゃんと、落ち込んでしまったシロコちゃんのためにも！"
"10008090-53-シロコ" = "……別に落ち込んでない。"
"10008090-54-ホシノ" = "まあまあ、実際にやるのはダメだけど気持ちは分かるよ。"
"10008090-55-ホシノ" = "その分もやり返しに行こ、ね？おじさんも手伝うからさ？"
"10008090-56-アル" = "よし、そうと決まれば……！"
"10008090-57-アヤネ" = "みなさん無事ですか！？"
"10008090-58-アヤネ" = "すみません、何だか接続が不安定で……！あ、先生あけましておめでとうございます！"
"10008090-59-セリカ" = "アヤネちゃん……！って、何でアヤネちゃんまで覆面なの！？"
"10008090-60-アヤネ" = "こ、これはシロコ先輩が必要だからって……！"
"10008090-61-シロコ" = "もう要らなくなった。"
"10008090-62-アヤネ" = "そ、そうなんですか……？"
"10008090-63-ムツキ" = "あはははっ、メガネっ娘ちゃんまで！面白くなってきたねー！"
"10008090-64-ムツキ" = "さーて、じゃあもう一つ仕込んでおこっかな？"
"10008090-65" = "[s] \"ムツキ？\""
"10008090-66-ムツキ" = "全員で力を合わせて反撃！っていうのも勿論悪くないけどー。"
"10008090-67-ムツキ" = "せっかくだし、もうちょっと面白くしようかな～って♪"
"10008090-68-ムツキ" = "送信完了～！"
"10008090-69-ムツキ" = "ムツキ、今のってもしかして……。"
"10008090-70-ムツキ" = "こんな楽しいドタバタ劇、私たちだけで楽しむのはもったいないでしょ？"
"10008090-71-ムツキ" = "だからもっと面白くするためにも、ね？"
"10008090-72-黒亀組の組員たち" = "いたぞ、やつらをここで制圧しろ！"
"10008090-73-ムツキ" = "くふふっ♪さーて、じゃあお祭りを始めよっか？"
"10008090-74-ムツキ" = "ね、先生♡"
