[translation]
"10008115-1" = "（そうして、黒亀組との激闘の末……）"
"10008115-2-亀島五郎" = "くっ、まさか、こんなところで……っ！"
"10008115-3-アル" = "か、勝ったわ！！"
"10008115-4-ハルカ" = "あ、アル様！さすがです！"
"10008115-5-アル" = "ふぅ……"
"10008115-6-アル" = "ようやく終わりか。"
"10008115-7-ムツキ" = "あっ、賽銭箱発見～！"
"10008115-8" = "[s] \"みんなお疲れ様。\""
"10008115-9-ホシノ" = "うへ～、疲れたねぇ。先生もそうだし、便利屋も、ほかのみんなもお疲れ～。"
"10008115-10-アヤネ" = "はい、みなさんお疲れ様でした！"
"10008115-11-セリカ" = "ようやく落ち着いたわね……。"
"10008115-12-シロコ" = "賽銭箱……。"
"10008115-13-ノノミ" = "シロコちゃん、残念ですがダメですよ？それは返さなきゃいけないものですからね？"
"10008115-14-シロコ" = "……分かってる。"
"10008115-15-アヤネ" = "……シロコ先輩、分かったなら視線を賽銭箱から外してください。"
"10008115-16-ホシノ" = "じゃあ事件も終わったみたいだし、私たちは帰るとしよっか。"
"10008115-17-ホシノ" = "あ、セリカちゃんはバイトもお疲れ様～。"
"10008115-18-ノノミ" = "先生、ではまた後日！"
"10008115-19" = "[s] \"うん、みんな気を付けてね。\""
"10008115-20-セリカ" = "じゃあ、賽銭箱を元の場所に戻そっか。"
"10008115-21-アル" = "そ、そうね！？それが目的だったわけだし！？それはもちろん……！"
"10008115-22-ムツキ" = "アルちゃん、声が裏返ってるよ？もしかして、今更もったいなくなってきたとか？"
"10008115-23-アル" = "ふふっ、何を言ってるのかしら。"
"10008115-24-アル" = "私がそんなこと思うわけ――"
"10008115-25-ハルカ" = "あ、さ、賽銭箱の鍵が……！？"
"10008115-26-セリカ" = "え、何で……？もしかして、騒動の間に蓄積したダメージで、とか……？"
"10008115-27-セリカ" = "あれ、賽銭箱の中身……"
"10008115-28" = "[s] \"……空っぽ？\""
"10008115-29-カヨコ" = "……え？"
"10008115-30-ムツキ" = "あははっ！なになに、どういうこと？"
"10008115-31-アル" = "えええぇぇぇぇっ！？なっ、何でよ！？どうして中身が無いの！？"
"10008115-32" = "[ns] \"この音、もしかして……！？\""
"10008115-33-？？？" = "とうっ！！"
"10008115-34" = "正義のヒーロー「カイテンジャー」……ここに参上！！"
"10008115-35-アル" = "……は？"
