[translation]
"10008080-1" = "第8話;危機一髪（2）"
"10008080-2" = "[ns] \"……多いね。\""
"10008080-3-ムツキ" = "うーん、このままだとキリがなさそうだけど……"
"10008080-4-ムツキ" = "アルちゃん、どうする？"
"10008080-5-ハルカ" = "あ、アル様……！"
"10008080-6-アル" = "ちょっ、これ多過ぎない！？"
"10008080-7-アル" = "どうしろって言うのよ！？"
"10008080-8-亀島五郎" = "ははっ！"
"10008080-9-亀島五郎" = "我々「黒亀組」を甘く見てもらっては困る。"
"10008080-10-アル" = "ひゃぁぁっ！？"
"10008080-11-アル" = "ちょっと、マズくない！？"
"10008080-12-カヨコ" = "……っ。"
"10008080-13-亀島五郎" = "ふむ、そろそろ終わりそうですね。"
"10008080-14-黒亀組の組員A" = "ボス、大変です！いつの間に、カイテンジャーが全員逃走してしまいました！"
"10008080-15-亀島五郎" = "……放っておきなさい。賽銭箱は取り戻しましたし、構いません。"
"10008080-16-亀島五郎" = "それに、未だに「カイテンジャーが賽銭箱を持っている」と思っているバカ共が、勝手に追いかけてくれるでしょう。"
"10008080-17-亀島五郎" = "その間に私たちは、予定通りに事を進めれば良いだけです。あとは、ここに倒れてる愚かな方々を……"
"10008080-18" = "[s] \"……こんなことをしたって、すぐにバレるよ。\""
"10008080-19-亀島五郎" = "……そうですね、いつかはバレるでしょう。しかし、その前に逃げてしまえば良いだけの話。そうは思いませんか？"
"10008080-20-亀島五郎" = "ここで正体がバレたところで、他の地域に行ってやり直せば良いのです。"
"10008080-21-亀島五郎" = "次はどこにしましょう？百鬼夜行？ワイルドハント？"
"10008080-22-亀島五郎" = "純粋なお嬢さんでいっぱいの、トリニティも悪くありませんね？"
"10008080-23-亀島五郎" = "くふふっ、ずいぶん自信満々じゃん？"
"10008080-24-亀島五郎" = "それはそうですよ。あなたたちのように、SNSで広がった「願い事が叶う場所」なんて文言を信じてくれるバカたちが、この世には溢れているのですから。"
"10008080-25-アル" = "……っ！"
"10008080-26-亀島五郎" = "そんなバカが減らない限り、何も怖くなどありませんねぇ。はっはっはっはっは！"
"10008080-27-黒亀組の組員B" = "ボス、賽銭箱は車に積みました！"
"10008080-28-亀島五郎" = "では、行くとしましょうか。朝を迎える前に色々と終わらせないといけませんからね。"
"10008080-29-アル" = "ちょ、ちょっと！！"
"10008080-30-亀島五郎" = "では、後片付けは頼みましたよ。"
"10008080-31-亀島五郎" = "それでは。恨むならどうか、こんな美味しい話に易々と首を突っ込んだ自分たちを恨まれますように。"
"10008080-32-黒亀組の組員B" = "命令だ、悪く思うなよ。"
"10008080-33-黒亀組の組員B" = "調子に乗って深入りするからだ！"
"10008080-34-黒亀組の組員C" = "さて、どうやって料理してやろうか……！"
"10008080-35-アル" = "ど、どどどどうすれば……！？"
"10008080-36-ムツキ" = "あははっ！もしかしてピンチって感じ？"
"10008080-37-アル" = "せ、先生……！"
"10008080-38" = "[ns1] \"………！\"\n[ns2] \"落ち着いて、大丈夫。\""
"10008080-39-カヨコ" = "……先生？何を――"
"10008080-40-カヨコ" = "……先生？何を――"
"10008080-41-黒亀組の組員A" = "な、何者だ！？"
"10008080-42-？？？" = "何者、ねぇ……。"
"10008080-43-セリカ" = "この声……！"
"10008080-44-ホシノ" = "強いて答えるなら……大事な後輩とその他諸々を助けに来た、「ヒーロー」ってところかな～？"
"10008080-45" = "[s] \"ホシノ！\""
"10008080-46-ホシノ" = "先生にも年明け早々会えて、おじさんは嬉しいなぁ。"
"10008080-47-ホシノ" = "さて、じゃあ挨拶の前に……とりあえず、邪魔者には退いてもらおっか？"
