[translation]
"10008030-1" = "第3話;ドタバタ追撃戦！"
"10008030-2-アル" = "待ちなさいよぉぉぉぉっ！！"
"10008030-3-アル" = "あはははっ！！待て待て～！"
"10008030-4-ハルカ" = "ま、待ってくださいぃぃ……！"
"10008030-5-カイテンレッド" = "はっはっはっ！誰もヒーローを止めることなどできない！"
"10008030-6-セリカ" = "はぁ、はぁ……何あれ、足はっや……。"
"10008030-7-ムツキ" = "うーん、このままだと逃げられちゃいそうだけど……アルちゃん、どうする？"
"10008030-8" = "あいつら、あんな変な格好して身体能力おかしいでしょう！？"
"10008030-9-アル" = "何なのよあいつら！そもそも、何の目的で賽銭箱を……！"
"10008030-10-カヨコ" = "「カイテンジャー」って言ったら、キヴォトスでも結構有名なやつらだよ。"
"10008030-11-カヨコ" = "「正義のために」って言いながら、あちこちで問題を起こしてるらしいし。"
"10008030-12-ハルカ" = "わ、私も少しですが、聞いたことがあります……。"
"10008030-13-ハルカ" = "走る速度はマッハ3、そしてキック力は5トンを上回るとか……。"
"10008030-14-アル" = "嘘でしょ！？"
"10008030-15-ハルカ" = "ほ、本当かどうかは分かりませんが……それと、カイテンジャーにはどうやら、切り札があるとかで……。"
"10008030-16-ハルカ" = "いざとなると、巨大ロボット「KAITEN FX」を呼び出すとか……。"
"10008030-17-ムツキ" = "へ～。ちなみにハルカちゃん、それどこ情報？"
"10008030-18-ハルカ" = "か、カイテンジャーのホームページに……。"
"10008030-19-アル" = "ホームページがあるの！？私たち便利屋68にもまだ無いのに！？"
"10008030-20-ムツキ" = "あはははっ、何それ！結構本格的じゃん？っていうか少なくとも、私たちよりは本格的かも？"
"10008030-21-アル" = "あ、あんな変なやつらに、このまま負けてたまるもんですか！"
"10008030-22-アル" = "何よ、この忙しいタイミングで！"
"10008030-23-ヘルメット団A" = "そこのお前たち、どうやら我々と同じ獲物を狙っているようだな！"
"10008030-24-ヘルメット団B" = "そうはさせるか！"
"10008030-25-ムツキ" = "なになに、どういうこと？"
"10008030-26-カヨコ" = "あいつら……ヘルメット団？"
"10008030-27-ヘルメット団A" = "カイテンジャーが持って行ったあの賽銭箱は、我々の獲物だ！さっさと消えろ！"
"10008030-28-ヘルメット団A" = "早い者勝ちだからな、邪魔するなら痛い目見るぜ？"
"10008030-29-ヘルメット団B" = "カイテンジャーが華麗に奪ったものを、さらに我々が奪う！"
"10008030-30-ヘルメット団A" = "どうだ、この完璧なアイデア！"
"10008030-31-アル" = "……ふふっ、「飛んで火にいる夏の虫」とはこのことね。"
"10008030-32-アル" = "さっきから走らされてばっかりだし、ちょっと溜まってたのよ。気分転換にはぴったりね。"
"10008030-33-アル" = "ムツキ、カヨコ、ハルカ、それにセリカ。"
"10008030-34-アル" = "……やるわよ。"
"10008030-35-セリカ" = "ちょっと、私はあんたの部下じゃないんだけど！？"
"10008030-36-セリカ" = "ま、まあやるけどっ！"
