[translation]
"10008035-1-ヘルメット団A" = "ぐあぁぁっ……！？"
"10008035-2-ヘルメット団B" = "わ、我々の偉大な夢が、今年の初夢が……。"
"10008035-3-アル" = "ふう、しょうもないやつらね。"
"10008035-4-カヨコ" = "（……どうしてヘルメット団が賽銭箱を？それより、カイテンジャーの逃走ルートをどうやって……？）"
"10008035-5-カヨコ" = "（もしかしてこれ、思ったより複雑な……）"
"10008035-6-アル" = "っていうか、早く追いかけた方が良くない？こうしてる間にもどんどん逃げられちゃうけど。"
"10008035-7-アル" = "そ、そうね！？"
"10008035-8-アル" = "ほら、早く行くわよ！"
"10008035-9-ハルカ" = "は、はいっ！"
