[translation]
"1006906-1" = "気にしてないよ？"
"1006906-2" = "（軽い足取りで玄武商会へ向かった）"
"1006906-3" = "玄武商会"
"1006906-4-ルミ" = "間に合って良かった、先生。"
"1006906-5-ルミ" = "これから、ちょうど餃子を蒸すところだよ。"
"1006906-6-ルミ" = "本当は包むところから見せてあげたかったんだけど、#nそっちは朝の段階で終わっちゃってさ。"
"1006906-7-ルミ" = "それじゃ……はじめよっか。"
"1006906-8-ルミ" = "みんな！火をつけて！"
"1006906-9" = "（ルミの掛け声と同時に、蒸し器が一斉に蒸気を噴き出した)"
"1006906-10-ルミ" = "すごいでしょ？この蒸気。"
"1006906-11-ルミ" = "餃子を蒸してる間は、厨房がサウナみたいになるんだ。"
"1006906-12" = "[s1] \"たしかに……結構な暑さだね。\"\n[s2] \"外で待ってても良いんじゃない？\""
"1006906-13-ルミ" = "んー、それは難しくてね。"
"1006906-14-ルミ" = "蒸し器の位置を調整しないといけなくってさ。"
"1006906-15-ルミ" = "でないと、蒸し加減がバラバラになっちゃうんだ。"
"1006906-16-ルミ" = "暑いから、先生は入り口にいてね。#nあたしは餃子を見てなくちゃいけないから。"
"1006906-17" = "（ルミに言われた通り、入口の近くで待っていると……）"
"1006906-18" = "[ns] \"えっと……る、ルミ？\""
"1006906-19-ルミ" = "……ん？先生、どうかした？"
"1006906-20" = "[wa:1100]― [log=루미]あ……[wa:600]そっか。[wa:1200]ちょっと[wa:300]透けちゃってるのか。[/log]"
"1006906-21" = "[wa:500]― [log=루미]ま、[wa:800]気にしないでよ。[wa:1100]減るもんじゃないしさ。[/log]"
"1006906-22" = "[wa:950]― [log=루미]……こうなると分かってたら、[/log]"
"1006906-23" = "[wa:100]― [log=루미]もっと可愛い下着にしたのに。[/log]"
"1006906-24" = "[wa:600]― [log=루미]ちょっと、[wa:1200]もったいなかったかも？[/log]"
"1006906-25" = "[wa:100]― [log=루미]ははっ、[wa:1600]目そらしちゃって。[/log]"
"1006906-26" = "[wa:600]― [log=루미]あたしは[wa:400]全然[wa:300]気にしてないよ？[/log]"
"1006906-27" = "[wa:550]― [log=루미]先生って[wa:1800]意外とそういうところあるんだね……[/log]"
"1006906-28" = "[wa:100]― [log=루미]ふふっ、[wa:1300]気に入った。[/log]"
"1006906-29" = "[wa:800]― [log=루미]せっかくだし、[/log]"
"1006906-30" = "[wa:100]― [log=루미]もーっと[wa:600]困らせちゃおっかな……？[/log]"
"1006906-31-ルミ" = "よし、キレイに出来上がってる。"
"1006906-32-ルミ" = "先生の分は、「特別」なやつを作ってあるよ。"
"1006906-33" = "[ns3] \"ル、ルミ！？\"\n[ns4] \"こ、これは……！？\""
"1006906-34-ルミ" = "ん～？どうかしたの？"
"1006906-35-ルミ" = "この間トリニティでイワシパイっていうのを食べてね。#nこれが結構美味しくて！"
"1006906-36-ルミ" = "うちでも似たようなものが作れないかなって『イワシ餃子』を作ってみたんだよ。"
"1006906-37-ルミ" = "イワシパイはトリニティでも秘伝のレシピらしくてさ。#n味はあたしが保証するよ。"
"1006906-38-ルミ" = "先生のために作った「特別」な餃子……美味しく食べてくれるよね？"
"1006906-39" = "[ns5] \"ぐはっ……！\"\n[ns6] \"嬉しいけど、これは、ちょっと……！\""
"1006906-40-ルミ" = "どうしたの？トリニティの伝統と歴史が詰まった料理だよ？#nうち風のアレンジは入ってるけどね。"
"1006906-41-ルミ" = "さ、早く召し上がれ。#n特にこの……イワシの形を維持するのが難しかったんだよね。"
"1006906-42" = "[ns] \"ごほっ！？\""
"1006906-43" = "（促されて、恐る恐る餃子に箸を伸ばし、えいやと口に放り込む)"
"1006906-44" = "（想像を絶する味と出会うかと思ったのも束の間……）"
"1006906-45" = "（一度食べたら、忘れられない美味しさだった）"
