[translation]
"12030-1" = "第3話;さよなら、便利屋68"
"12030-2" = "便利屋68・事務所"
"12030-3-アル" = "はあ……。"
"12030-4-ムツキ" = "アルちゃ～ん、さっきからため息ばっかりだよ、テキパキ荷物運ぼう？"
"12030-5-アル" = "はぁぁ……。"
"12030-6" = "え、えっと、これはどこに運べばいいでしょうか？"
"12030-7" = "ん？これ……ああ、アルちゃんが天賦の才を発揮した書道の残骸じゃん、あっちの燃えるゴミでいいよ。"
"12030-8-ムツキ" = "捨てないでよ！！持っていくに決まってるじゃない！"
"12030-9-ムツキ" = "でもこれ、書道の授業の宿題で書いたやつでしょ～？ほんとに要る？それにこれ、「一日一悪」って何？どういう意味？"
"12030-10-アル" = "き、きっと10年後には10億円ぐらいの価値が……。"
"12030-11" = "……はぁ。"
"12030-12-ムツキ" = "打っても響かないし、元気ないねぇアルちゃん……。"
"12030-13-カヨコ" = "社長、どうしたの。"
"12030-14-ムツキ" = "アルちゃん、事務所を引っ越すのがイヤみたい。"
"12030-15-ムツキ" = "でも風紀委員会に場所を知られちゃったし、任務も失敗でクライアントからも狙われるだろうし、仕方ないでしょー？"
"12030-16-ムツキ" = "そういえばアビドスとの戦いも、中途半端な感じで終わっちゃったね。"
"12030-17-アル" = "し、仕方ないでしょ！一緒に背中を合わせて戦った人たちを今になって狙うなんて……できるわけないじゃない！"
"12030-18" = "……はあ。"
"12030-19-カヨコ" = "あのカバンのお金も、残り全部あのラーメン屋の修理代として置いてきたし。本当にこの社長は……。"
"12030-20-アル" = "う、うるさい！うるさい！"
"12030-21-アル" = "だって、だって……！"
"12030-22" = "……。"
"12030-23-アル" = "ハードボイルドなアウトローは……私は……。"
"12030-24-カヨコ" = "……はあ。"
"12030-25-カヨコ" = "本当に、手のかかる社長だ。"
"12030-26-ムツキ" = "でもこういうのがうちのアルちゃんだもんね？一緒にいてすっごく楽しい！"
"12030-27-ハルカ" = "はい、私もそう思います！アル様！わ、私、アル様がいなかったらきっと今こうして生きていないはずなので……。"
"12030-28-ハルカ" = "元気出してください！私が一番尊敬しているのはアル様ですから！"
"12030-29-アル" = "う、うるさい！わかってるわよ！"
"12030-30-ハルカ" = "よっ……と！"
"12030-31-ハルカ" = "これで全部です！積み終わりました！"
"12030-32" = "じゃあどこに行く？"
"12030-33-アル" = "うーん……。"
"12030-34-ムツキ" = "まあ、特に当てもなさそうだし、またゲヘナに戻る？"
"12030-35" = "[s] \"みんな、気を付けてね。\""
"12030-36-ハルカ" = "！！"
"12030-37-アル" = "えっ……！？"
"12030-38-カヨコ" = "シャーレの……！"
"12030-39-ムツキ" = "えっ、あ、先生だ！来てくれたんだね！"
"12030-40-アル" = "な、なんで来たのよ！アビドスのことを手伝っている身でしょう！？"
"12030-41-ムツキ" = "うーん、でもそれはそれとして、先生とは仲良くしたくない？"
"12030-42-ハルカ" = "はい、そうですね。風紀委員会と戦う時も、お世話になりましたし……。"
"12030-43-カヨコ" = "悪意があるようには見えないし……それに私たちはもう行くんだし、わざわざ敵対しなくてもいいでしょ。"
"12030-44" = "[s] \"どこかに行っちゃうの？\""
"12030-45-アル" = "ま、また別の依頼を求めてちょっと移動するだけよ！"
"12030-46" = "[s] \"そっか、また会おうね。アルも、みんなも。\""
"12030-47-アル" = "……ふふっ。"
"12030-48-アル" = "ふふっ、うふふふっ！もちろんよ！先生、あなたとは事業のパートナーとして協業するのも悪くなさそうだし。"
"12030-49-アル" = "ただ今はうちが忙しくてバタバタしてるから、また今度ね、今度。"
"12030-50-ムツキ" = "まあアビドスに二度と来ないってわけでもないし。ここ、良いところだったからね。"
"12030-51-カヨコ" = "まあ……それはそうだね。"
"12030-52-ハルカ" = "はい、本当に。"
"12030-53" = "も、もちろんまた来るわ、ラーメンを食べに！！"
"12030-54-アル" = "……本当に美味しかった、から。"
"12030-55" = "（そして、便利屋68の荷物を積んだトラックは、路地の向こうへと消えてしまった）"
"12030-56-アヤネ" = "こんにちは、大将。お見舞いに来ました。"
"12030-57-セリカ" = "大将、大丈夫？"
"12030-58-柴大将" = "やあ、セリカちゃん。それにアヤネちゃんも。こんな早い時間からありがとう。"
"12030-59" = "[s] \"お体は如何ですか？\""
"12030-60-柴大将" = "ああ、先生まで。大丈夫大丈夫、ちょっと擦りむいただけだ。"
"12030-61-セリカ" = "でも……大将のお店が……。"
"12030-62-柴大将" = "ああ、バイトできなくなっちゃってごめんな、セリカちゃん。"
"12030-63-セリカ" = "そういう問題じゃないわよ……。"
"12030-64-柴大将" = "そもそも、もうすぐお店も畳む予定だったからな。予定がちょっと早くなっただけだ。"
"12030-65" = "え？お店を……？"
"12030-66-柴大将" = "ああ、ちょっと前から退去通知を受け取っていてね。"
"12030-67-アヤネ" = "た、退去通知って、何の話ですか？アビドス自治区の建物の所有者は、アビドス高校で……。"
"12030-68-柴大将" = "……そうか、君たちは知らなかったんだな。"
"12030-69-柴大将" = "……何年か前、アビドスの生徒会が借金を返せなくて、建物と土地の所有権が移ったんだ。"
"12030-70-アヤネ" = "えっ！？"
"12030-71-セリカ" = "う、嘘！？アビドスの自治区なのに！？じゃあ今は一体誰が！？"
"12030-72" = "[s1] \"……カイザーローンですか？\"\n[s2] \"……カイザーコーポレーションですか？\""
"12030-73-柴大将" = "うーん……そんな名前だったような気もするが……悪いな、はっきり覚えてねえや。"
"12030-74-柴大将" = "うーん……そんな名前だったような気もするが……悪いな、はっきり覚えてねえや。"
"12030-75-アヤネ" = "そんな……でも、そういうことなら……。"
"12030-76" = "セリカちゃん、先生。お二人は先に学校へ戻っていてください。私は確認したいことがあるので、ちょっと別のところに寄ってから行きます。"
"12030-77" = "ん、何のこと？よく分からないけど……私も一緒に行く！"
"12030-78-アヤネ" = "では、先生は教室に戻っていてください！私たちもすぐに戻りますので！"
"12030-79" = "[s] \"分かった。私も伝えたいことがあるから、待ってるね。\""
"12030-80-セリカ" = "大将、まだ引退とか考えないでよ！分かった！？"
"12030-81-柴大将" = "お、おお……あっ、そうだセリカちゃん最後に、お店のところにお金が入った変なカバンがあったんだけど、何か知ってるかい？"
"12030-82" = "[s] \"お店の再建のために使ってください。\""
"12030-83-柴大将" = "お、おお？"
"12030-84-アヤネ" = "行こう、セリカちゃん！"
"12030-85-セリカ" = "うん！どこに行くのか分かってないけど……先生、また後でね！"
"12030-86" = "次回;それぞれの物語（１）"
