[translation]
"12080-1" = "第8話;アビドス砂漠へ（３）"
"12080-2-ホシノ" = "ふむ、ドローンにオートマタか……。"
"12080-3-ホシノ" = "この辺り、何でかこういうのが良く集まるんだよね。"
"12080-4-アヤネ" = "……っ！？皆さん、前方に何かあります！"
"12080-5-アヤネ" = "砂埃で、まだはっきりと姿が見えないのですが……！"
"12080-6-アヤネ" = "巨大な町……いえ工場、或いは駐屯地……？と、とにかく、ものすごい大きな施設のようなものが……？"
"12080-7-ホシノ" = "……こんなところに施設？何かの見間違いじゃなくて？"
"12080-8-ホシノ" = "今のところ、こっちからは干からびたオアシスしか見えてないけど……。"
"12080-9-アヤネ" = "恐らく見間違いではないと思うのですが……とりあえず、肉眼で確認できるところまで進んでみてください！"
"12080-10-ホシノ" = "……。"
"12080-11-セリカ" = "何これ……。"
"12080-12-シロコ" = "この張り巡らされてる有刺鉄線、優に数キロメートル先までありそう……。"
"12080-13-ノノミ" = "工場……？石油ボーリング施設、ではなさそうな……一体何なのでしょう、この建物は……？"
"12080-14-ホシノ" = "こんなの、昔は無かった……。"
"12080-15-セリカ" = "うわっ！？なになに！？"
"12080-16-PMC兵士A" = "侵入者だ！"
"12080-17-PMC兵士B" = "捕らえろ、逃がすな！"
"12080-18-アヤネ" = "前方から、正体不明の兵力が攻撃を仕掛けてきています！"
"12080-19-ホシノ" = "よく分からないけど、歓迎の挨拶なら返してあげた方が良さそうだね？"
"12080-20-ホシノ" = "じゃ、派手に行こっか～！"
