[translation]
"12120-1" = "第12話;幾つかの秘密"
"12120-2-？？？" = "じゃーん！"
"12120-3-？？？" = "ホシノちゃん見て見てー！アビドス砂祭りの昔のポスター！やっと手に入れたよー！"
"12120-4-？？？" = "この時はまだ、オアシスが湖みたいに広がってたんだよねー。あ、このポスターは記念にあげる！"
"12120-5-？？？" = "えへへ、すっごく素敵でしょー？もし何か奇跡が起きたら、またこの頃みたいに人がたっくさん集まって――"
"12120-6-ホシノ" = "奇跡なんて起きっこないですよ、先輩。"
"12120-7-ホシノ" = "そんなもの、あるわけないじゃないですか。それよりも現実を見てください！"
"12120-8-？？？" = "は、はう……。"
"12120-9-ホシノ" = "こんな砂漠のド真ん中に、もう大勢の人なんて来るはずがないでしょう！？夢物語もいい加減にしてください！"
"12120-10-？？？" = "うえぇ、だってホシノちゃーん……ご、ごめんね？"
"12120-11-ホシノ" = "……っ。"
"12120-12-ホシノ" = "そうやってふわふわと、奇跡だの幸せだの何だの……。"
"12120-13-ホシノ" = "もっとしっかりしてください！あなたはアビドスの生徒会長なんですよ！？もう少し、その肩に乗った責任を自覚したらどうなんですか！"
"12120-14" = "（ビリビリッ――！）"
"12120-15" = "対策委員会・教室"
"12120-16-ホシノ" = "……ふぅ。"
"12120-17-セリカ" = "もうっ、一体何なのよ！"
"12120-18-シロコ" = "カイザーコーポレーションは、あそこで一体何を企んで……？"
"12120-19-ノノミ" = "「宝物を探している」、と言っていましたが……。"
"12120-20-アヤネ" = "あの砂漠には何も無いはずです。でたらめを言ってるんだと思います。"
"12120-21-アヤネ" = "石油など、お金になりそうな地下資源は何一つ残っていません……はるか昔に、すでにそういう調査結果が出ているんです。"
"12120-22-ノノミ" = "だとすると、どうして……。"
"12120-23-セリカ" = "いやいや、今はそれよりも借金の方でしょ！3000％とか言ってなかった！？"
"12120-24-アヤネ" = "保証金も要求してきましたし……あと一週間で、3億円だなんて……。"
"12120-25-シロコ" = "……行ってくる。あそこで何をしているのか、調べないと。"
"12120-26-アヤネ" = "し、シロコ先輩！？行くって、一体どこへ……？"
"12120-27-シロコ" = "PMCの施設。徹底的に準備すれば、何とか潜入できると思う。行って、何をしてるのか確認する。"
"12120-28-セリカ" = "ま、待ってシロコ先輩！それより今は、借金の話の方が先でしょ！"
"12120-29-シロコ" = "……。"
"12120-30-シロコ" = "……借金はもう、真っ当なやり方じゃ返せない。何か、別の方法を……。"
"12120-31-ノノミ" = "だ、ダメですよ！それではまた……"
"12120-32" = "……私はシロコ先輩に賛成！学校が無くなったら全部終わりなんだから、もうなりふり構ってられない！！"
"12120-33-ノノミ" = "そんな、セリカちゃん……！？"
"12120-34-アヤネ" = "セリカちゃん待って！そんなことしたら、あの時と同じだよ！？"
"12120-35-セリカ" = "そ、そういう意味じゃない！そうじゃなくて、でも……！"
"12120-36-アヤネ" = "あの時ホシノ先輩が止めてくれたのに、自分から進んで犯罪者になるの！？"
"12120-37-セリカ" = "わ、私は……。"
"12120-38-シロコ" = "……。"
"12120-39-ホシノ" = "ほらほら、みんな落ち着いて～。"
"12120-40-ホシノ" = "頭から湯気が出てるよ～？"
"12120-41-シロコ" = "ん……。"
"12120-42-セリカ" = "……。"
"12120-43-ノノミ" = "……。"
"12120-44-アヤネ" = "はい、すみません……。"
"12120-45-シロコ" = "……ごめん、こんな風にしたいわけじゃなかった。"
"12120-46-ホシノ" = "うん、みんな分かってるよ。シロコちゃんも、いい子だからね。"
"12120-47-シロコ" = "……。"
"12120-48-ホシノ" = "まっ、とりあえず今日はこの辺にしとこう。"
"12120-49-ホシノ" = "うへ～、じゃあ解散解散～。一回頭を冷やして、また明日集まることにしようよ。これは委員長命令ってことで。"
"12120-50" = "[s] \"……そうだね。とりあえず、みんな一旦帰ろう。\""
"12120-51" = "（ノノミとアヤネ、セリカは家に帰り、ホシノとシロコだけが残った）"
"12120-52-ホシノ" = "ん～？シロコちゃんは何かまだやることがある感じ？"
"12120-53-シロコ" = "……先輩、ちょっといい？"
"12120-54-ホシノ" = "うへ～、おじさんとお話したいことがあるの？照れるな～。"
"12120-55" = "[s] \"私も。\""
"12120-56-ホシノ" = "……先生も？うへ、おじさんモテモテだ～。"
"12120-57-ホシノ" = "でもさ、今日は疲れたし、色んなことがあったじゃん？"
"12120-58-ホシノ" = "また明日話そう、大体どんな話かは分かってるから。"
"12120-59-シロコ" = "……ん、分かった。"
"12120-60-シロコ" = "先生……。"
"12120-61" = "[s] 頷く。"
"12120-62-シロコ" = "ん、じゃあまた明日……。"
"12120-63" = "うへ～、先生やるねえ？私の可愛いシロコちゃんと、いつの間に目と目で意思疎通ができる仲になったんだ～？"
"12120-64-ホシノ" = "いやいや、やっぱり先生は侮れない大人だな～。おじさんは流れに付いていけなくて何だか寂しいよ。"
"12120-65" = "[ns] \"ホシノ、聞いてもいい？\""
"12120-66-ホシノ" = "ん～、何を？"
"12120-67" = "[s] ホシノの退部・退会届を差し出す。"
"12120-68-ホシノ" = "それって……。"
"12120-69-ホシノ" = "うへ～、いつの間に……！これ、盗ったのはきっとシロコちゃんだよね？"
"12120-70-ホシノ" = "全くシロコちゃんったら、いくら何でも先輩のかばんを漁るのはダメでしょ～。"
"12120-71-ホシノ" = "先生、きちんとシロコちゃんを叱っといてよ～？あのままじゃとんでもない大悪党になっちゃってもおかしくないってー。"
"12120-72" = "[s1] \"うん。それはそれで、また今度ね。\"\n[s2] \"今は、この退部届について聞きたいな。\""
"12120-73-ホシノ" = "……。"
"12120-74-ホシノ" = "……。"
"12120-75-ホシノ" = "そっかー……。"
"12120-76" = "[s] \"聞かせてくれる？\""
"12120-77-ホシノ" = "……。"
"12120-78-ホシノ" = "うーん。逃がしてくれそうには……ないよね～？"
"12120-79-ホシノ" = "……はあ、仕方ないなあ。"
"12120-80-ホシノ" = "面と向かってっていうのも何だし……先生、ちょっとその辺一緒に歩かない？"
"12120-81" = "[s] ホシノと一緒に廊下に出る。"
"12120-82-ホシノ" = "けほっ、けほっ……うわぁ、ここも砂だらけじゃ～ん……。"
"12120-83-ホシノ" = "ま、仕方ないんだけどね。掃除をしようにも、そもそも人数に対して建物が大きすぎて……。"
"12120-84-ホシノ" = "砂嵐が減ってくれれば良いんだけど……。"
"12120-85-ホシノ" = "うへ～、せっかくの高校生活が全部砂色だなんて、ちょっとやるせないと思わない？"
"12120-86" = "[s] \"ホシノは、この学校が好きなんだね。\""
"12120-87-ホシノ" = "……今の話の流れで、本当にそう思う？うへ、やっぱ先生は変な人だね。"
"12120-88-ホシノ" = "……砂漠化が進む前、アビドスはかなり大きくて力のある学校だったって言われてるけど……そんな記憶も実感も、おじさんには全く無いんだよね～。"
"12120-89-ホシノ" = "最初から全部めちゃくちゃで、ちゃんとしたものなんて何一つない学校だった。"
"12120-90-ホシノ" = "おじさんが入学した時のアビドス本館は、今はもう砂漠の中に埋もれちゃったし。当時の先輩たちだって、もうみんないなくなった。"
"12120-91-ホシノ" = "今いるここは、砂漠化を避けて何回も引っ越した結果に辿り着いた、ただの別館。"
"12120-92-ホシノ" = "……ま、でもここに来てシロコちゃんやノノミちゃん、アヤネちゃんにセリカちゃんと会えたから……。"
"12120-93-ホシノ" = "……。"
"12120-94-ホシノ" = "……うへ、やっぱり好きなのかもしれないな～。"
"12120-95" = "[s] \"…………。\""
"12120-96-ホシノ" = "……先生、正直に話すよ。"
"12120-97-ホシノ" = "私は2年前から、変なやつらから提案を受けてた。"
"12120-98" = "[s] \"提案？\""
"12120-99-ホシノ" = "カイザーコーポレーション……。"
"12120-100-ホシノ" = "提案というかスカウトというか……アビドスに入学した直後からずっと、何回もね。"
"12120-101-ホシノ" = "そういえば、ついこの間もあったな～……。"
"12120-102-黒服" = "あなたに、決して拒めないであろう提案をひとつ。"
"12120-103-黒服" = "アビドス高校を退学し、私共の企業に所属する……その条件を呑んでいただければ、今アビドスが背負っている借金の半分近くをこちらで負担しましょう。"
"12120-104-黒服" = "ククッ、ククククッ……さあ、答えを聞きましょう。もしイエスならば、こちらにサインを。"
"12120-105-ホシノ" = "……何度も言ったはずだよ、断るって。"
"12120-106-黒服" = "……。"
"12120-107-ホシノ" = "それは誰から見たって破格の条件だった。でも、当時は私がいなくなったらアビドス高校が崩壊するって思ってたからこそ、ずっと断ってたけど……。"
"12120-108-ホシノ" = "……あいつら、PMCで使える人材を集めているみたい。"
"12120-109" = "[s] \"……その人は、一体何者？\""
"12120-110-ホシノ" = "私も、あいつの正体は知らない……ただ、私は黒服って呼んでる。"
"12120-111" = "[s] \"黒服……。\""
"12120-112-ホシノ" = "何となくぞっとするやつで……キヴォトス広しといえども、ああいうタイプのやつは見たこと無かったし……。"
"12120-113-ホシノ" = "怪しいやつだけど、別に特段問題を起こしたりはしなかった……。"
"12120-114-ホシノ" = "何なんだろうね。あのカイザーの理事ですら、黒服のことは恐れてるように見えたけど……。"
"12120-115" = "[s] \"じゃあ、この退部届は……。\""
"12120-116-ホシノ" = "……うへ。"
"12120-117-ホシノ" = "……まあ、1ミリも悩んでなかったって言ったら嘘だし。ちょっとした気の迷いっていうか。"
"12120-118-ホシノ" = "……うん、もう捨てちゃおっか。"
"12120-119-ホシノ" = "うへ～、スッキリした。"
"12120-120-ホシノ" = "余計な誤解を招いてごめんね。ただ、こんな話をみんなにしたところで、心配させるだけで良いことも何も無さそうだったからさ。"
"12120-121-ホシノ" = "でもまあ、可愛い後輩たちにいつまでも隠しごとをしたままっていうのも良くないし……明日、みんなにちゃんと話すよ。"
"12120-122-ホシノ" = "聞かされたところで困らせちゃうだけだろうけど、隠しごとなんて無いに越したことはないだろうし。"
"12120-123-ホシノ" = "実際のところ、今はあの提案を受ける以外、他の方法は思いついてないんだけどね……。"
"12120-124" = "[s] \"……きっと何か、方法があるはず。\""
"12120-125-ホシノ" = "……。"
"12120-126-ホシノ" = "そうだね、奇跡でも起きてくれれば良いんだけど……。"
"12120-127-ホシノ" = "……奇跡、かあ。"
"12120-128-ホシノ" = "……さ～てと、この話はこれでおしまい。"
"12120-129-ホシノ" = "じゃあ、また明日。先生。"
"12120-130-ホシノ" = "さよなら。"
"12120-131" = "[ns] \"ホシノ！\""
"12120-132-ホシノ" = "な、なに……？"
"12120-133" = "[s] \"私が大人として、どうにかする！だから……！\""
"12120-134-ホシノ" = "……。"
"12120-135-ホシノ" = "……うへへ。私、そんなに元気なさそうだったかな？"
"12120-136-ホシノ" = "うん。ありがとう、先生。"
"12120-137" = "（翌日）"
"12120-138-アヤネ" = "はぁ、お疲れ様です……。"
"12120-139-アヤネ" = "あれ、私が一番乗り……？"
"12120-140-アヤネ" = "……？"
"12120-141-アヤネ" = "これは……？"
"12120-142-アヤネ" = "……嘘、"
"12120-143" = "何でっ……どうしてっ！！！！？？"
"12120-144" = "（机の上にはホシノが残した退部・退会届、そしてみんなへの手紙が置かれていた）"
"12120-145" = "次回;手をすり抜けたもの"
