[translation]
"12195-1-？？？" = "ねえ、ホシノちゃん。"
"12195-2-？？？" = "私ね、"
"12195-3-？？？" = "ホシノちゃんと初めて会った時、これは夢なんじゃないかなって思って、何度も頬をつねったの。"
"12195-4-？？？" = "ホシノちゃんみたいな、可愛くて強くて、頼れる後輩がそばにいてくれるなんていう夢みたいなことが、本当に嬉しくて……。"
"12195-5-？？？" = "うーん、上手く説明できてないかもしれないけど……。"
"12195-6-？？？" = "ただ、こうしてホシノちゃんと一緒にいられることが、私にとっては奇跡みたいなものなの。"
"12195-7-ホシノ" = "……毎日毎日、こうして一緒にいるじゃないですか。"
"12195-8-ホシノ" = "昨日も今日も、明日もそうです。こんな当たり前なことで、何を大袈裟なことを。"
"12195-9-？？？" = "はぅ……だって……。"
"12195-10-ホシノ" = "「奇跡」というのはもっとすごくて、珍しいもののことですよ。"
"12195-11-？？？" = "……ううん、ホシノちゃん。"
"12195-12-？？？" = "私は、そうは思わないよ。"
"12195-13-？？？" = "ねえ、ホシノちゃん。いつかホシノちゃんにも可愛い後輩ができたら、その時は――"
"12195-14-ホシノ" = "……。"
"12195-15-？？？" = "先輩はすぐそこにいるはずです！！"
"12195-16-？？？" = "ん、壊れない……もう一度……"
"12195-17-？？？" = "あ、アヤネちゃん！？どうしてここに！？"
"12195-18-？？？" = "シャーレに貸してもらったヘリで！ホシノ先輩は！？"
"12195-19-？？？" = "ここです！でもドアが開かなくて……！！"
"12195-20-？？？" = "こんのっ！！"
"12195-21" = "（ドカアアアァァァァンッ！！！）"
"12195-22-ホシノ" = "（一体、何が……）"
"12195-23-ホシノ" = "（体が自由に……？夢でも見てるのかな……）"
"12195-24-ホシノ" = "（みんなの声が聞こえたし、夢か……）"
"12195-25-ホシノ" = "（声……）"
"12195-26-ホシノ" = "（こっちの方、かな……）"
"12195-27-ホシノ" = "（夢でもいいから……最後に、もう一度だけ……）"
"12195-28" = "（ガチャン！）"
"12195-29-一同" = "ホシノ先輩！！！！"
"12195-30-ホシノ" = "あ、あれ……どうやって……。"
"12195-31-ホシノ" = "どうして……だって、私は……。"
"12195-32" = "[ns] \"ホシノ。\""
"12195-33" = "ホシノ"
"12195-34" = "……ああ。"
"12195-35" = "ホシノ"
"12195-36" = "そっか……みんなが、先生が……。"
"12195-37" = "ホシノ"
"12195-38" = "大人が、ね……はは。"
"12195-39" = "セリカ"
"12195-40" = "[7cd0ff]対策委員会[-]"
"12195-41" = "……お、おかえりっ！先輩！"
"12195-42" = "ノノミ"
"12195-43" = "[7cd0ff]対策委員会[-]"
"12195-44" = "ああっ、セリカちゃんに先を越されてしまいました！#n恥ずかしいから言わないって言ってたのに、ズルいです！"
"12195-45" = "セリカ"
"12195-46" = "[7cd0ff]対策委員会[-]"
"12195-47" = "う、うるさいうるさいっ！順番なんてどうでも良いでしょ！"
"12195-48" = "シロコ"
"12195-49" = "[7cd0ff]対策委員会[-]"
"12195-50" = "……無事で良かった。"
"12195-51" = "アヤネ"
"12195-52" = "[7cd0ff]対策委員会[-]"
"12195-53" = "ホシノ先輩、おかえりなさい！！"
"12195-54" = "ノノミ"
"12195-55" = "[7cd0ff]対策委員会[-]"
"12195-56" = "おかえりなさい、です！！"
"12195-57" = "シロコ"
"12195-58" = "[7cd0ff]対策委員会[-]"
"12195-59" = "おかえり、ホシノ先輩。"
"12195-60" = "ホシノ"
"12195-61" = "[7cd0ff]対策委員会[-]"
"12195-62" = "あはは……。"
"12195-63" = "ホシノ"
"12195-64" = "[7cd0ff]対策委員会[-]"
"12195-65" = "……何だかみんな、期待に満ちた表情だけど。"
"12195-66" = "ホシノ"
"12195-67" = "[7cd0ff]対策委員会[-]"
"12195-68" = "……求められてるのは、あの台詞？"
"12195-69" = "セリカ"
"12195-70" = "[7cd0ff]対策委員会[-]"
"12195-71" = "ああもうっ！分かってるなら焦らさないでよ！"
"12195-72" = "ホシノ"
"12195-73" = "[7cd0ff]対策委員会[-]"
"12195-74" = "うへ～……"
"12195-75" = "ホシノ"
"12195-76" = "[7cd0ff]対策委員会[-]"
"12195-77" = "全く、可愛い後輩たちのお願いだし、仕方ないなあ……"
"12195-78" = "ただいま"
