[translation]
"2300602-1" = "百夜堂の看板娘！"
"2300602-2" = "（その後、シズコが働いている百鬼夜行の伝統的な喫茶店「百夜堂」を訪れた）"
"2300602-3-シズコ" = "あっ、先生！"
"2300602-4-シズコ" = "……じゃなくて、こほん。"
"2300602-5-シズコ" = "おかえりなさいませ！ご主人様！"
"2300602-6" = "[s] \"えっ、と……ただいま？\""
"2300602-7-シズコ" = "あ、突然のことでビックリさせちゃいましたね。うちは伝統的にみんな「ご主人様」で統一してるんです。"
"2300602-8-シズコ" = "それではこちらへ……はい、メニューをどうぞ！"
"2300602-9-シズコ" = "本日のおすすめは、苺あんみつです！"
"2300602-10-シズコ" = "もちろん、それ以外の和菓子もすっごく美味しいですよ！"
"2300602-11" = "[s1] \"えっと……じゃあ苺大福を。\"\n[s2] \"じゃあ……おすすめの苺あんみつで。\""
"2300602-12-シズコ" = "かしこまりました！少々お待ちくださいませっ！"
"2300602-13-シズコ" = "かしこまりました！少々お待ちくださいませっ！"
"2300602-14" = "（イベントだからか、お店の中は結構混んでいた）"
"2300602-15" = "（お店全体がざわざわと賑わう中でも、シズコは人一倍輝いていて、どこにいてもすぐに見つけることができた）"
"2300602-16-シズコ" = "こちら、ご注文の苺あんぱんセットです！"
"2300602-17-可愛い物には目がない女子生徒" = "シズコちゃん、これはどうやって食べるのがおススメ？"
"2300602-18-シズコ" = "あっ、より美味しく食べられるおススメの方法があるんです！"
"2300602-19-シズコ" = "ご主人様のお手元にあるそのお茶を一口含んでから、あんぱんを小さくちぎってはむっ、ってしてみてください！"
"2300602-20-シズコ" = "そうすると甘みと苦みの調和を、一度に楽しむことができますよ！"
"2300602-21-可愛い物には目がない女子生徒" = "ああもうっ、シズコちゃん、ほんっと可愛い！"
"2300602-22-可愛い物には目がない女子生徒" = "もう所作の全部が可愛い！"
"2300602-23-シズコ" = "こちら、ご注文の苺大福セットです！"
"2300602-24-百夜堂の常連さん" = "あれ、苺大福？"
"2300602-25-百夜堂の常連さん" = "私が頼んだのは大福じゃなく、苺八つ橋だったような……？"
"2300602-26-シズコ" = "あれれっ？"
"2300602-27-シズコ" = "ああっ……！す、すみませんご主人様！"
"2300602-28-シズコ" = "シズコ、ついうっかり……！"
"2300602-29-シズコ" = "す、すぐに新しいものをお持ちしますね……！ごめんなさぁい……！"
"2300602-30-百夜堂の常連さん" = "きっ……！"
"2300602-31-百夜堂の常連さん" = "来たっ！シズコちゃんのおっちょこちょいイベント！！"
"2300602-32-百夜堂の常連さん" = "この申し訳なさそうな表情、ミスをしたことが恥ずかしくてモジモジしてる姿……！"
"2300602-33-百夜堂の常連さん" = "天使はここにいたのね……。"
"2300602-34-シズコ" = "か、からかわないでくださいよぉ……。"
"2300602-35" = "（その後もシズコがミスをする度に、お客さんたちがわっと盛り上がる）"
"2300602-36" = "（どうやらほとんどのお客さんたちは、シズコ目当てで来ているようだった）"
"2300602-37" = "[s] \"すごい盛り上がってるなあ……。\""
"2300602-38" = "（そして少し経った頃……）"
"2300602-39-シズコ" = "お待たせしました、ご主人様！"
"2300602-40-シズコ" = "こちら、先ほどご注文された……"
"2300602-41-シズコ" = "苺饅頭のデラックスバージョンです！"
"2300602-42" = "[s3] \"あれ、たしか苺大福を注文したような……？\"\n[s4] \"あれ、たしか苺あんみつを注文したような……？\""
"2300602-43-シズコ" = "ああっ、シズコってばまたミスを！"
"2300602-44-シズコ" = "ああっ、シズコってばまたミスを！"
"2300602-45-シズコ" = "す、すみませんご主人様！もう一度ちゃんと作り直してきますね……。"
"2300602-46" = "[s] \"ううん、美味しそうだからこれで頂くね、ありがとう。\""
"2300602-47-シズコ" = "……っ！？"
"2300602-48-シズコ" = "……そ、それで終わりですか！？"
"2300602-49" = "[s] （頷く）"
"2300602-50-シズコ" = "……そっ、それでは、引き続きサービスさせていただきますね～？"
"2300602-51-シズコ" = "ああっ、ご主人様危ないです！シズコ、このままじゃぶつかる……！"
"2300602-52-シズコ" = "か、かわされた！？"
"2300602-53" = "[s] \"大丈夫？\""
"2300602-54-シズコ" = "し、シズコは大丈夫ですよ～！"
"2300602-55-シズコ" = "つ、次のサービスを……！"
"2300602-56-シズコ" = "あああっ！シズコ痛恨のミス！"
"2300602-57-シズコ" = "先生……ではなく、ご主人様にお出ししなきゃいけないドリンクに、間違えてチャバスコを入れてしまいました！"
"2300602-58" = "[s] \"間違えてそんなになみなみと入れることある！？\" "
"2300602-59-シズコ" = "せ、先生でも流石にこれは飲めないですよねー……？"
"2300602-60" = "[s5] \"いくらなんでもそれはちょっと……。\"\n[s6] \"……可愛い生徒が作ってくれたんだから！\""
"2300602-61-シズコ" = "もうっ、シズコのおっちょこちょい！"
"2300602-62-シズコ" = "こんなミスをして先生に迷惑をかけるなんて！うぅ、シズコは、シズコは……！"
"2300602-63" = "[s7] \"作り直してもらえる？\""
"2300602-64-シズコ" = "あっさり！？"
"2300602-65-シズコ" = "迷わず一気に！？"
"2300602-66" = "[s8] \"うっ……もう一杯！\""
"2300602-67-シズコ" = "しかもおかわり！？でも今「うっ」って言いましたよね！？"
"2300602-68-シズコ" = "…………。"
"2300602-69-シズコ" = "……ああもうっ、我慢なりません！"
"2300602-70-シズコ" = "先生！こっちに来てください！"
"2300602-71" = "（シズコに腕を掴まれて、百夜堂の隅っこの方に連れていかれた）"
"2300602-72-シズコ" = "さっきからいったい何なんですか先生は！"
"2300602-73" = "[s9] \"それは私の台詞なんだけど……。\"\n[s10] \"シズコこそ、何をしてるの？\""
"2300602-74-シズコ" = "それはもちろん……！"
"2300602-75-シズコ" = "それはもちろん……！"
"2300602-76-シズコ" = "百夜堂名物、「ドジっ子サービス」です！"
"2300602-77-シズコ" = "モモトークで言ったじゃないですか。"
"2300602-78-シズコ" = "「おもてなしする」って。"
"2300602-79" = "[s] \"……ドジっ子サービスで、おもてなし？\""
"2300602-80-シズコ" = "そうです！あのお客さんたちの反応、先生も見ましたよね？"
"2300602-81-シズコ" = "このルックスに、この可愛さ！こーんな魅力的な女の子にサービスされたら、グッときちゃいません？"
"2300602-82" = "[s11] \"う、うん、まあ……。\"\n[s12] \"……。\""
"2300602-83-シズコ" = "微妙な反応！？"
"2300602-84-シズコ" = "何か言ってくださいよ！？その沈黙は人を傷つけますよ！？"
"2300602-85-シズコ" = "とにかく私、ご主人様……お客さんたちからは、ご覧の通り百夜堂の看板娘として結構人気なんですよ。"
"2300602-86-シズコ" = "私はおっちょこちょいな可愛らしさをアピールする、お客さんたちはそれで癒される。"
"2300602-87-シズコ" = "お互いにwin-winな、最高の商売だと思いません？"
"2300602-88-シズコ" = "ということなので、先生も少しは乗ってください！"
"2300602-89-シズコ" = "せっかく先生が来るからって、昨晩はずっと特別な練習をしてきたんですから……！"
"2300602-90" = "[s] \"いや、そう言われても……。\""
"2300602-91" = "[s13] \"別にそんなことしなくてもシズコは可愛いし、\"\n[s14] \"これ以上のリアクションを求められても困るっていうか。\""
"2300602-92-シズコ" = "……はっ、"
"2300602-93-シズコ" = "はいぃ！？そ、そんな恥ずかしい台詞を真顔で……！"
"2300602-94-シズコ" = "も、もしかして先生は天然ですか！？"
"2300602-95-シズコ" = "おっちょこちょいを通り越して、天然ポジを狙ってるんですかっ！？"
"2300602-96-シズコ" = "はぁ、はぁ……ああもう、つい勢いで……。"
"2300602-97-シズコ" = "ついつい無意識にっていうか……先生の前だと色々無意味に思えてくるっていうか……。"
"2300602-98" = "[s] \"そういうのも含めて全部、シズコだもんね。\""
"2300602-99-シズコ" = "……ほんっと。"
"2300602-100-シズコ" = "変な人ですね、先生も。"
"2300602-101" = "（その後、なんだか上機嫌なシズコから、サービスとして和菓子をたくさんもらった）"
