[translation]
"2004608-1" = "天と地と、世の調和"
"2004608-2-ニヤ" = "先生。"
"2004608-3-ニヤ" = "必ず来てくださると思っていました。"
"2004608-4-ニヤ" = " [ruby=私たち]百鬼夜行[/ruby]のもとへ。"
"2004608-5" = "[s] \"今度は何を企んでいるの？\""
"2004608-6-ニヤ" = "企む？いえ、もう一歩先です。#n力を持ち、機会が訪れたなら、それを使うのは当然でしょう？"
"2004608-7-ニヤ" = "あまり風情の無い言い回しですが――"
"2004608-8-ニヤ" = "――天下取りに参ります。"
"2004608-9-ニヤ" = "ああ、またその顔。信じていない時の――いつもの顔です。とはいえ……こと[ruby=このとき]此時[/ruby]だけは、実に望ましい反応ともいえます。"
"2004608-10-ニヤ" = "「陰陽部には百鬼夜行を動かす力などない」とか。"
"2004608-11-ニヤ" = "「そもそも実権すらない」とか。"
"2004608-12-ニヤ" = "あのゲヘナの風紀委員会ですら、そう信じきっていますから。"
"2004608-13-ニヤ" = "でもこの噂、どこから始まったんでしょうね？#n誰が最初に流したか……気になりません？"
"2004608-14-ニヤ" = "答えは――私ですよ。"
"2004608-15-ニヤ" = "もし相手が得物を隠していたら……まぁ当然警戒しますよね。"
"2004608-16-ニヤ" = "裏を返せば、一の得物を見せておくことで、二の得物を懐深くに隠せるというわけです。"
"2004608-17-ニヤ" = "おかげで誰一人――あのシャーレの先生ですら気づかない間に、力を蓄えることができました。"
"2004608-18-ニヤ" = "今や真なる意味で「百鬼夜行連合学院」となった私たち。もはや誰が立ちふさがろうとも、[ruby=百鬼夜行]鬼の行進[/ruby]を阻むことなどできないのです。"
"2004608-19-ニヤ" = "お互いの足を引っ張り合うゲヘナとトリニティ？#n個人主義のミレニアム？"
"2004608-20-ニヤ" = "黒き龍は波風を恐れ扉を閉ざし、赤き熊は烏合の衆。"
"2004608-21-ニヤ" = "ヴァルキューレなんぞ、語る価値すらありませんね。"
"2004608-22-ニヤ" = "私たちに比肩しうるのは、もはや連邦生徒会……より厳密に言えば――"
"2004608-23-ニヤ" = "シャーレの[USERNAME]先生だけ。"
"2004608-24" = "[ns] \"ニヤ……。\""
"2004608-25-ニヤ" = "先生の怖い顔は色々見てきたつもりですが……まだその奥があったとは。"
"2004608-26-ニヤ" = "どうかご安心ください。先生と刃を交えるつもりは毛頭ありません。#n戦って勝つのは下策、戦わずして勝つのが上策ですから。"
"2004608-27-ニヤ" = "それに、先生の力はもう十分に存じております。わざわざ対立するなんて、勿体ない話です。"
"2004608-28-ニヤ" = "月並みですが……どうです？我々と手を組むというのは。"
"2004608-29" = "[ns1] \"ニヤ、本気なの？\"\n[ns2] \"冗談は、ここまでだよ？\""
"2004608-30-ニヤ" = "……お説教ですか？この期に及んでまだそんなことを？"
"2004608-31-ニヤ" = "どうやらまだ、状況を呑み込めていないようですね？"
"2004608-32-ニヤ" = "もはや生徒と先生という枠には収まりません。"
"2004608-33-ニヤ" = "対等なパートナーになるか……敵になるか。"
"2004608-34-ニヤ" = "そして、先生の返答次第では――"
"2004608-35-ニヤ" = "私は迷わずこの引き金を引きます。#n……これで少しは状況を理解していただけましたか？"
"2004608-36" = "[s3] \"ニヤは私の生徒で、\"\n[s4] \"私はニヤの先生だよ。\""
"2004608-37" = "[ns5] \"そして生徒が道を踏み外したなら、\"\n[ns6] \"正すのが先生の役目だ。\""
"2004608-38-ニヤ" = "[ruby=・   ・]先生[/ruby]はブレませんねぇ……。"
"2004608-39-ニヤ" = "はぁ～……なんだか拍子抜けしてしまいますね～"
"2004608-40-ニヤ" = "……サプラーイズ！"
"2004608-41-ニヤ" = "ちょ～っとシリアスモードのニヤさん、楽しんでいただけましたか～？#nにゃはっ♪"
"2004608-42-ニヤ" = "……なんて、まぁこんなんで誤魔化すものでもないですね。"
"2004608-43-ニヤ" = "これ以上ややこしくなる前に……今までのは全部ウソ、フェイクです。"
"2004608-44-ニヤ" = "そもそも戦争なんてしても、得るものがありませんからね。"
"2004608-45-ニヤ" = "百鬼夜行の主な収益源は観光業。平和が一番です。"
"2004608-46-ニヤ" = "ではなぜこんなことをしたのか……。"
"2004608-47-ニヤ" = "簡単なことですよ。百鬼夜行の本質を、先生に知ってもらうためです。"
"2004608-48-ニヤ" = "なんだかんだと、先生は律儀で、お優しい方ですから。"
"2004608-49-ニヤ" = "幸い、これまでの私はじゃれついていただけですけど。"
"2004608-50-ニヤ" = "でも、もし私が先生を利用しようとしていたら？#n話がまったく違っていたかも知れませんよね？"
"2004608-51" = "[s] \"そんなことをする気はないでしょ？\""
"2004608-52-ニヤ" = "でも、これは「仮定の話」ですし……。"
"2004608-53-ニヤ" = "明日ありと思う心[ruby=あだざくら]の仇桜―[/ruby]―"
"2004608-54-ニヤ" = "百鬼夜行連合学院が、明日も同じであるとは限らないでしょう？"
"2004608-55" = "[s7] \"ニヤがいればそうはならない。\"\n[s8] \"ニヤはその道を進まない。\""
"2004608-56-ニヤ" = "ですから、これは仮定の話で……。"
"2004608-57-ニヤ" = "はぁ……実際その気になれば、陰陽部には見た目以上の力があります。"
"2004608-58-ニヤ" = "キヴォトス全体に影響を与えられるかはともかく、百鬼夜行連合学院の掌握くらいなら、あるいは。"
"2004608-59-ニヤ" = "可能か不可能かで言えば、可能である。それが一番の問題なんですよ。"
"2004608-60" = "[s9] \"ニヤがいればそうはならない。\"\n[s10] \"だって、ニヤは百鬼夜行が好きだからね。\""
"2004608-61-ニヤ" = "にゃは……？"
"2004608-62-ニヤ" = " [ruby=・   ・   ・   ・   ・]好きだから[/ruby]、百鬼夜行を守る……と？"
"2004608-63-ニヤ" = "そもそも仮定そのものが間違ってる……？"
"2004608-64-ニヤ" = "……。"
"2004608-65-ニヤ" = "にゃはははっ！"
"2004608-66-ニヤ" = "は～まったくですねぇ。"
"2004608-67-ニヤ" = "いえ、いえ、もうよく分かりました。"
"2004608-68-ニヤ" = "これからは、もう少し自分を信じてみようと思います。そして先生のことも。"
"2004608-69-ニヤ" = "はぁ……なんともお恥ずかしい。#nこんな夜遅くに、自分を――先生を試すようなことをして。"
"2004608-70-ニヤ" = "陰陽の調和だの、バランスだのと難しいことを言いながら……#nご覧の通り私は大きく「陰」に偏った存在ですから。"
"2004608-71-ニヤ" = "「にゃはは～」なんて普段は笑ってますけど、「陽」の力を持つ後輩や友達が周りにいるおかげで、どうにかバランスを保っているだけなんです。"
"2004608-72-ニヤ" = "先生がいてくだされば、より盤石になるのかな～なんて。"
"2004608-73-ニヤ" = "陰陽部は――百鬼夜行連合学院は、いつでも先生を歓迎しますよ♪"
"2004608-74" = "[s11] \"先生はいつだって生徒の味方だから。\"\n[s12] \"調和とかバランスとか、難しいのは苦手で……。\""
"2004608-75-ニヤ" = "にゃははっ！叶いませんねぇ……私は百鬼夜行の調和を取るだけでも大変だというのに。"
"2004608-76-ニヤ" = "どうか先生はそのままでいてください。#n――キヴォトスの先生♪"
