[translation]
"1000206-1" = "真の美食"
"1000206-2" = "D.U.外郭地区"
"1000206-3-ハルナ" = "あら、先生？"
"1000206-4-ハルナ" = "こんなところでまた偶然お会いできるだなんて。"
"1000206-5-ハルナ" = "今日もまた、のんびりとあちこちを歩いていらしたのですか？"
"1000206-6-ハルナ" = "ふふ、でしたら私も同じです。嬉しくもありつつ、ホッとしますわね。"
"1000206-7" = "[s] \"ハルナは何をしてたの？\""
"1000206-8-ハルナ" = "私は新たな美味しいお店の開拓のために、あちこちを歩き回っていました。"
"1000206-9-ハルナ" = "SNSで期待の新参と称されていたお店に行ってみたのですが……。"
"1000206-10-ハルナ" = "あまりにも私の期待とは違っていまして……。"
"1000206-11" = "[s] \"まさか、またお店を爆破させたの？\""
"1000206-12-ハルナ" = "うふふ……いくら私でも毎回そんなことはいたしませんわ。"
"1000206-13-ハルナ" = "……ですが、最近なんだか、食べることに対して少し、考えることが増えてきてしまって……。"
"1000206-14" = "[s] \"色々と悩んでるんだね。\""
"1000206-15-ハルナ" = "……ふふ、優しいお言葉ありがとうございます。"
"1000206-16-ハルナ" = "せっかく先生とお会いできたことですし、お家の方まで少し一緒に歩いてもよろしいでしょうか？"
"1000206-17" = "[s] \"もちろん。\""
"1000206-18" = "（ハルナとあれこれ食べ物の話をしながら歩いていたら、）"
"1000206-19" = "（たい焼きのお店が目に入った）"
"1000206-20" = "[s] \"たい焼き、食べる？\""
"1000206-21-ハルナ" = "……たい焼き、ですか。"
"1000206-22-ハルナ" = "……うふふ。はい、お願いします、先生。"
"1000206-23-たい焼き屋店主" = "どうも、ありがとうございます！"
"1000206-24-ハルナ" = "……ふふ。"
"1000206-25" = "― うふふ、[wa:2000]こうやって一緒に帰宅できるだなんて、"
"1000206-26" = "― たい焼きもこんなにたくさん買ってしまいましたし。"
"1000206-27" = "― たい焼きだと少し質素じゃないか、[wa:2500]ですって？"
"1000206-28" = "[wa:300]― いいえ……[wa:1300]私にとっては[wa:1500]最高に贅沢な瞬間ですわ。"
"1000206-29" = "― では、[wa:1000]先生。[wa:1000]これをさしあげますわ。"
"1000206-30" = "― ……いいえ。[wa:1300]あーん、[wa:500]でなくては。"
"1000206-31" = "[ns] \"あーん。\""
"1000206-32" = "― 一番好きな御方と一緒に、[wa:2500]一番好きな食べ物を頂く。"
"1000206-33" = "― これぞ正しく……。"
"1000206-34" = "[ns] \"なんだか恥ずかしいな……。\""
"1000206-35" = "― うん？[wa:1300]その表情、[wa:1200]どうかなさいまして？"
"1000206-36" = "― うふふっ。[wa:1500]そのような反応も、[wa:1500]嫌いではありませんが。"
"1000206-37" = "― 寒くないか、[wa:1500]ですって？"
"1000206-38" = "― いいえ、[wa:1000]暖かいですわよ。[wa:1800]本当に。"
"1000206-39" = "（ハルナと仲良くたい焼きを分けて食べながら、家に帰った）"
