[translation]
"3301-1" = "全力で振り抜いて（１）"
"3301-2-ロボット審判" = "〈――プレイボール！〉"
"3301-3-ミレニアム野球部長" = "みんな、集まって！"
"3301-4-ミレニアム野球部長" = "今回は練習試合だから、緊張しなくても大丈夫。"
"3301-5-ミレニアム野球部長" = "対戦相手はエンジニア部が作ってくれたロボットだし……#nデッドボールを当ててしまってブーイングされる心配も無いからね。"
"3301-6-ミレニアム野球部員A" = "でも、エンジニア部のロボットってことは、別の危険があるんじゃ……？"
"3301-7-ミレニアム野球部員A" = "あのピッチングロボット、前にエンジニア部の人がテストしたとき、あり得ない剛速球を何度も投げたって……"
"3301-8-ミレニアム野球部員B" = "しかも、ボールを投げる前に挑発してくるんですよ！"
"3301-9-ミレニアム野球部員A" = "たしかに前はそうだったかもしれないけど……"
"3301-10-ミレニアム野球部員A" = "あれからセミナーが改善するよう言ったらしいから、今回は大丈夫なはず。"
"3301-11-ミレニアム野球部員A" = "みんな、楽しんでいこう！"
"3301-12-ロボット審判" = "〈ストライクアウト！〉"
"3301-13-ミレニアム野球部員A" = "うぅ……こんなの当たりっこないよ。"
"3301-14-ミレニアム野球部員B" = "やっぱり、あんなに速かったら……"
"3301-15-レイ" = "〈……4番、[ruby=のまさ]野正[/ruby]レイさん〉"
"3301-16-レイ" = "あの子……新入部員のレイちゃんだよね？"
"3301-17-レイ" = "らしいよ。なんと入部テストで打率0割8分を記録した期待の新人だって……"
"3301-18-レイ" = "そんな好記録を！？"
"3301-19-レイ" = "いやぁ～、先輩方にそうやって褒められたら照れちゃいますね。えへへ……"
"3301-20-レイ" = "レイちゃん、前！！"
"3301-21-レイ" = "〈ピッチャー、大きく振りかぶって――〉"
"3301-22-レイ" = "来るっ……！"
"3301-23-ミレニアム野球部員A" = "打った――！"
"3301-24-ミレニアム野球部員B" = "あの剛速球を打ち返すなんて！？"
"3301-25-ミレニアム野球部員A" = "もしかして、行ったんじゃない……！？"
"3301-26-ミレニアム野球部員A" = "これでミレニアムも、ようやく今シーズン初のホームランを……"
"3301-27-ロボット審判" = "〈……アウト！〉"
"3301-28-レイ" = "はぁ…………"
"3301-29-レイ" = "〈スリーアウト、チェンジ！〉"
"3301-30-ミレニアム野球部員A" = "……みんな、お疲れ！"
"3301-31-一同" = "お疲れ様でした！"
"3301-32-ミレニアム野球部員A" = "レイちゃん、お疲れ！すごい活躍だったね！"
"3301-33-レイ" = "いえ、先輩もお疲れ様でした！"
"3301-34-ミレニアム野球部員A" = "本当に惜しかったね。#nあと少しでホームランだったのに……"
"3301-35-ミレニアム野球部員B" = "だよね！音を聞いた瞬間、これは越えるって思ったくらい！"
"3301-36-レイ" = "その、水を差すようで申し訳ないのですが……"
"3301-37-ミレニアム野球部員A" = "ボールが当たった瞬間、これは届かないなって思ったんです。"
"3301-38-レイ" = "……感覚で？"
"3301-39-レイ" = "まだホームランを打った経験は無いので、感覚というのも少し違うかもしれませんが……"
"3301-40-レイ" = "……芯を捉えた感触が無かったと言いますか……"
"3301-41-ミレニアム野球部員A" = "そうだったんだ？"
"3301-42-レイ" = "で、でも、次の試合もありますから。"
"3301-43-レイ" = "……それで相談なんですが、ホームランを打つためには、何をすれば良いと思いますか？"
"3301-44-ミレニアム野球部員A" = "……やっぱりバットをボールに当てる角度じゃないのかな？"
"3301-45-ミレニアム野球部員A" = "飛んでいくボールは垂直方向に等加速度運動を、水平方向には等速直線運動をするわけで、45度方向のときに最も飛距離が伸びるから……"
"3301-46-ミレニアム野球部員B" = "って、それは重力の影響だけを考えた真空下における方程式じゃん。"
"3301-47-ミレニアム野球部員B" = "物体に作用する力を正確に計算するには、抗力と揚力……#nそれにモーメントも考慮する必要があるよ。"
"3301-48-レイ" = "バットの材質も大事！#n軽くて反発力が高いほどいいに決まってる！"
"3301-49-レイ" = "新素材開発部が新しく作ったバットの研究結果によると、既存の素材よりも飛距離が――"
"3301-50-レイ" = "ここは効率的なバッティングフォームを――"
"3301-51-レイ" = "やはり、ホームランを打つためには……"
"3301-52-レイ" = "もっと筋肉をつける必要があるんじゃないかな、とも思ったんですが……"
"3301-53-ミレニアム野球部員A" = "き、筋トレを……？"
"3301-54-ミレニアム野球部員B" = "でも、運動は大変だし……"
"3301-55-レイ" = "そもそも、ミレニアム野球部は道具の改良とデータを重視する理論派集団の集まりで……"
"3301-56-レイ" = "……ホームランは打てなくても、安打で得点を稼げばいいんじゃないかな？"
"3301-57-レイ" = "もちろん、チームで勝つなら安打の方が大切かもしれません……"
"3301-58-レイ" = "でも、やっぱりホームランを打ちたいんです！"
"3301-59-レイ" = "ごめんね、レイちゃん。ウチの野球部、トレーニングに詳しい人居ないんだ。"
"3301-60-レイ" = "私も理論なら教えられるんだけど、トレーニングは苦手で……"
"3301-61-レイ" = "そう、ですか……"
"3301-62-レイ" = "代わりに、専門家の紹介ならできるよ。"
"3301-63-レイ" = "……トレーニング部って聞いたことある？"
"3301-64-レイ" = "トレーニング部、ですか……？"
"3301-65" = "ミレニアム・ジム"
"3301-66-スミレ" = "……遅いですね、会員の皆さん。"
"3301-67-スミレ" = "これでは、昨日せっかく鍛えた筋肉が……"
"3301-68-スミレ" = "……やはり、昨日のトレーニングが[ruby=こた]堪[/ruby]えてしまったのでしょうか。"
"3301-69-スミレ" = "部員が増える気配もありませんし、会員の数も……"
"3301-70-スミレ" = "こうなったら直接、新入部員を探しに――"
"3301-71-レイ" = "失礼します、トレーニング部はここですか？"
"3301-72-スミレ" = "そうですが……"
"3301-73-レイ" = "あ、自分は野球部の野正レイって言います！"
"3301-74-レイ" = "その、部長からトレーニングの方法が知りたかったら、ここに行くよう言われて……"
"3301-75-スミレ" = "そうでしたか、トレーニングに来たんですね。"
"3301-76-レイ" = "はい。ここなら、ホームランを打つための筋肉が鍛えられると聞きました！"
"3301-77-スミレ" = "……筋肉！"
"3301-78-レイ" = "自分だけじゃトレーニング方法が分からなくて……#nそれなら専門的な知識のある人に教わりたいと思ったんです。"
"3301-79-レイ" = "次の大会まで仮入部したいんですが……いいでしょうか？"
"3301-80-レイ" = "……すみません、急に来られても困りますよね。"
"3301-81-レイ" = "来週、返事を聞かせてもらえれば――"
"3301-82-スミレ" = "すぐに始めましょう！"
"3301-83-レイ" = "は、はい……？"
"3301-84-スミレ" = "トレーニングの成果は、向上心によって大きく変わります！"
"3301-85-スミレ" = "筋肉をつけたいと思ったのなら、1分1秒たりとも無駄にしてはなりません！"
"3301-86-スミレ" = "今！この瞬間にも！あなたの筋肉は少しずつ減っていますから！"
"3301-87-スミレ" = "さあ！早速スクワット10セットから始めましょう！"
"3301-88-レイ" = "ま、待ってください、先輩！#nまだ自分、着替えてすらないんですが！"
"3301-89" = "（……こうして、スミレによるレイの特別トレーニングは始まった）"
