[translation]
"70008030-1" = "何にも縛られぬ者たち（３）"
"70008030-2-？？？" = "さて、皆さんお集まりのようですので――"
"70008030-3-？？？" = "ここに……魑魅一座ナイトの開幕を宣言します！"
"70008030-4-アラタ" = "（うわ……あっちも……こっちも……魑魅一座でも有名なリーダーばっかり……）"
"70008030-5-アラタ" = "（あたし……ここにいていいのか……？）"
"70008030-6" = "ざわざわ……。"
"70008030-7-喧騒流のリーダー" = "おい、あいつじゃないか？"
"70008030-8-瀬戸際流のリーダー" = "マジかよ……今年は荒れそうだな……。"
"70008030-9-アラタ" = "（おいおい、どんなやべぇやつが来てるんだ！？）"
"70008030-10-アラタ" = "あいつ、本当に魑魅一座なのか……？"
"70008030-11-アラタ" = "百鬼夜行の外だと、あんな恰好のやつらがいるって聞いたけど……。"
"70008030-12-初志貫徹流のリーダー" = "皆さん！お静かに～！！"
"70008030-13-初志貫徹流のリーダー" = "積もる話もあるでしょうが……皆さん、私語は慎んでいただきますよう。"
"70008030-14-初志貫徹流のリーダー" = "……では、本題に入りましょう。"
"70008030-15-初志貫徹流のリーダー" = "近頃の我々は、百鬼夜行から無視されている――そうは思いませんか？"
"70008030-16-初志貫徹流のリーダー" = "たしかにね……あたしらのこと、誰も怖がってないし。"
"70008030-17-変転流のリーダー" = "勝手に神木祭を再開するしな……。"
"70008030-18-瀬戸際流のリーダー" = "そうだそうだ！我々のことをバカにしてやがるんだ！"
"70008030-19-初志貫徹流のリーダー" = "ええ、ええ。皆さんのお気持ち……私も痛いほど分かります。"
"70008030-20-初志貫徹流のリーダー" = "幸いにして――先の神木祭においては、路上流のアラタ殿の活躍で、我々が恥をかくことは免れました。"
"70008030-21-アラタ" = "えっ、あたし！？#n……そ、そうだな！神木祭は百鬼夜行――ようは、あたしらの祭りだろ？"
"70008030-22-アラタ" = "邪魔させるわけにはいかなかったっていうか……#nまぁ……陰陽部とか百花繚乱のやつらに超怒られた記憶しかねぇけどよ……。"
"70008030-23-初志貫徹流のリーダー" = "百鬼夜行の物は、すなわち我々魑魅一座の物と同義！#n自分の物を守ろうとして、何がいけないと言うのでしょう！"
"70008030-24-初志貫徹流のリーダー" = "百花繚乱など根拠がない口だけの集団！#n魑魅一座こそ、百鬼夜行の体現者！伝統の守護者なのです！"
"70008030-25-初志貫徹流のリーダー" = "おお！よく言った！"
"70008030-26-アラタ" = "そうだ！そうだ！"
"70008030-27-アラタ" = "（そうだ！これが魑魅一座！あたしらは百鬼夜行の伝統を守ってんだ！）"
"70008030-28-初志貫徹流のリーダー" = "今までは陰陽部の顔を立ててきましたが……もうその必要はありません！"
"70008030-29-初志貫徹流のリーダー" = "日取りは次回のお祭り。我々は――百花繚乱に宣戦布告をするのです！"
"70008030-30-アラタ" = "（……ん？）"
"70008030-31-アラタ" = "うおお！目にもの見せてやれ！！"
"70008030-32-初志貫徹流のリーダー" = "皆さん、今こそ動く時です！"
"70008030-33-初志貫徹流のリーダー" = "百花繚乱は治安維持のために、街中に散らばるはず。#n我々は観光客のふりをして潜伏し……チャンスがきたら、一斉に奇襲するのです！"
"70008030-34-初志貫徹流のリーダー" = "やってやろうぜ！"
"70008030-35-初志貫徹流のリーダー" = "私たちのお祭りを取り戻すんだ！観光客だろうがなんだろうが、そんなの関係ねぇ！"
"70008030-36-アラタ" = "いや、それは……違うんじゃねぇ？"
"70008030-37-初志貫徹流のリーダー" = "……今のはどなたですか？"
"70008030-38-アラタ" = "あっ、おっ、おい！押すなって！#n……ええと、あたしだけど。"
"70008030-39-初志貫徹流のリーダー" = "……アラタ殿。#n誰よりも神木祭の再開に反対していたあなたが……なぜ？"
"70008030-40-アラタ" = "それとこれとはちょっと違うというか……！"
"70008030-41-アラタ" = "いや、その……もちろん、百花繚乱の連中をやっつけようってのはいいんだけどさ……。"
"70008030-42-アラタ" = "今回のお祭りって別に問題ないじゃん？#n無関係の人とか、お祭りのために頑張ってきた人たちまで巻き込むのはどうなんだ？"
"70008030-43-初志貫徹流のリーダー" = "じゃあこっちが悪いっていうのか！？#n我々だってちょっとは悪いけどさ！"
"70008030-44-初志貫徹流のリーダー" = "もう作戦は始まってんだ。自分だけ抜ける気か！？"
"70008030-45-初志貫徹流のリーダー" = "アラタ殿、がっかりです。我々の未来を担う方だと思っていたのに……。"
"70008030-46-初志貫徹流のリーダー" = "集会の内容を知られた以上……このまま帰すわけにはいかなくなってしまいました。"
"70008030-47-アラタ" = "うわっ！近づくな！だ、誰か……！"
"70008030-48-？？？" = "話は聞かせてもらいましたっ！"
"70008030-49-イズナ" = "その計画――イズナが阻止いたします！"
"70008030-50-瀬戸際流のリーダー" = "忍者だと！？"
"70008030-51-瀬戸際流のリーダー" = "陰陽部が忍者を養成してるって噂は本当だったのか！！"
"70008030-52-ニヤ" = "にゃははっ！忍者の良さが分かるだなんて、見る目あるじゃないですか♪"
"70008030-53-ニヤ" = "これほど面白……いや、良い展開はないですからねぇ。"
"70008030-54-初志貫徹流のリーダー" = "これはどういうことです、[ruby=あまち]天地[/ruby]ニヤ……！#nあの陰陽部が中立を破るおつもりか？"
"70008030-55-ニヤ" = "はて、私にはなんのことやら……。#n可愛い後輩が散歩をしていたら……たまたま不思議な集会に迷い込んでしまっただけでして～"
"70008030-56-初志貫徹流のリーダー" = "そんな嘘が通じると本気で思っているのですか……？"
"70008030-57-初志貫徹流のリーダー" = "いや、どのみちもう遅い。#n魑魅一座が団結すれば、いくら陰陽部や百花繚乱であっても――"
"70008030-58-ニヤ" = "はいは～い、わかってますよ～"
"70008030-59-ニヤ" = "野良犬って1、2匹ならどうってことないんですがねぇ。#nこれが群れると厄介で……。"
"70008030-60-ニヤ" = "はぁっ！イズナ流忍法！ペンペンの術！"
"70008030-61-ニヤ" = "ぐあああ、痛い！取れちゃうーっ！"
"70008030-62-ニヤ" = "たった一人に何を苦戦してんだ！#nさっさと片づけ――ぐあああっ！痛いーっ！"
"70008030-63-ニヤ" = "やっぱり、群れる前なら可愛いですね～にゃはは！では、お先に～"
"70008030-64-初志貫徹流のリーダー" = "天地ニヤぁぁあああ！！！"
"70008030-65-初志貫徹流のリーダー" = "リーダー！大変です！百花繚乱が乱入してきました！"
"70008030-66-喧騒流のリーダー" = "忍者の次は百花繚乱だと！？"
"70008030-67-変転流のリーダー" = "にっ、逃げろーっ！"
"70008030-68-初志貫徹流のリーダー" = "お、落ち着いてください！数はこちらが上です！連携すれば我々にも勝機が……！"
"70008030-69-イズナ" = "悪の親玉、発見です！お覚悟……っ！"
"70008030-70-初志貫徹流のリーダー" = "痛っ！！うわああん！せっかく皆を集めたのに！"
"70008030-71-初志貫徹流のリーダー" = "もう知らないんだからー！"
"70008030-72-アラタ" = "はぁはぁ……逃げ切れた……。"
"70008030-73-アラタ" = "あたしは魑魅一座らしい人間になりたかっただけなのに！どうしてこんなことに……。"
"70008030-74-アラタ" = "魑魅一座・路上流のリーダー……#nアラタ……お前は何がしたいんだ……？"
"70008030-75-アラタ" = "くっ……こんなお面――っ！"
"70008030-76-アラタ" = "そこのあんた。"
"70008030-77-アラタ" = "この声は……。"
"70008030-78-アラタ" = "ああ、お面を貸してくれたお姉さまか――"
"70008030-79-ラブ" = "貸した？奪われたの間違いでしょ？"
"70008030-80-ラブ" = "ヘルメット団たるもの、ヘルメットなくしちゃダメでしょ！……ほんと、予備のヘルメットがあってよかったわ。"
"70008030-81-ラブ" = "うちの大事なヘルメット、無事なのよね？"
"70008030-82-アラタ" = "奪って悪かったな……はいよ。"
"70008030-83-ラブ" = "え、ああ、どうも。なんだ、すんなり返してくれるんだ。"
"70008030-84-ラブ" = "はぁ……。#n見つけたら復讐してやるって思ってたのに――"
"70008030-85-ラブ" = "あんたの落ち込みをみたら、そんな気分でもなくなったわね。#n何があったのよ。"
"70008030-86-アラタ" = "話してどうなるもんでもねぇよ。"
"70008030-87-ラブ" = "分からないじゃない。話すだけでも案外スッキリするものよ。"
"70008030-88-アラタ" = "……魑魅一座らしさって何だと思う……？"
"70008030-89-ラブ" = "魑魅一座？なにそれ？"
"70008030-90-アラタ" = "だよな……。"
"70008030-91-ラブ" = "魑魅一座か何だか知らないけど、この町で暮らしてるんだよね？"
"70008030-92-ラブ" = "だったら、普通に楽しんだら？"
"70008030-93-アラタ" = "普通に……楽しむ……か。"
"70008030-94-ラブ" = "勉強とか部活とか、めんどくさいんでしょ？"
"70008030-95-アラタ" = "そりゃ、まぁ……。"
"70008030-96-ラブ" = "やりたいことをやって、やりたくないことはやらない。それだけよ。"
"70008030-97-アラタ" = "ま……たしかにそうかもな……。"
"70008030-98-ラブ" = "それはそれとして――"
"70008030-99-ラブ" = "ヘルメットを奪われた……違う、貸してあげた対価をもらわないとね。"
"70008030-100-ラブ" = "ええっ！？お金なんてあるわけないだろう！"
"70008030-101-ラブ" = "話は最後まで聞きなさい！#n百鬼夜行の案内をしてくれれば、それでチャラにしてあげる。"
"70008030-102-ラブ" = "初めて来たんだけど……何の下調べもしてないのよね。"
"70008030-103-ラブ" = "えっ、じゃあ神木展望台にもまだ行ってねぇのか？"
"70008030-104-ラブ" = "神木？あの大きな木のこと？"
"70008030-105-ラブ" = "あそこは百鬼夜行の必須コースなんだよ！"
"70008030-106-ラブ" = "仕方ねぇ。百鬼夜行の案内、このあたしに任せておきな！"
"70008030-107-ラブ" = "復活早いわね。"
"70008030-108-アラタ" = "こうしちゃいられねぇ！早く行くぞ！"
"70008030-109-アラタ" = "まずは展望台だ！#n日が落ちてからもいいけど、落ちる前も絶景なんだ！！"
"70008030-110-ラブ" = "ちょっ、置いてかないでってば！"
"70008030-111" = "もしかしたら、毎日新たな楽しみを求めるアラタこそ、最も魑魅一座らしいのかもしれない。"
"70008030-112" = "今や誰も覚えていないが……かつてその言葉は「何にも縛られぬ者たち」を指していた。その言葉こそ――「魑魅一座」である。"
"70008030-113" = "何にも縛られぬ者たち"
