[translation]
"2300815-1" = "本当の気持ち"
"2300815-2" = "（約束の時間にショッピングモールへと足を運んだ）"
"2300815-3-マリー" = "ふぅ……やっぱり結構量がありますね。"
"2300815-4-マリー" = "礼拝の時に使うもの、チャリティーに出すもの、ボランティアで配るお菓子……。"
"2300815-5" = "[s] \"すごい量だね。\""
"2300815-6-マリー" = "はい。先生に来ていただけて、本当に助かりました。"
"2300815-7-マリー" = "いつもありがとうございます。"
"2300815-8" = "[s] \"いつもこの量をマリーひとりで準備してるの？\""
"2300815-9-マリー" = "あっ、いえ！#n普段は当番制で持ち回りなんですけど……"
"2300815-10-マリー" = "皆さんお忙しいので、私が引き受けることが多いんです。"
"2300815-11-マリー" = "今日は、他にどなたも行けなかったので私一人ですが……。"
"2300815-12" = "[s] \"大変だね……。\""
"2300815-13-マリー" = "いえ。微力ながら、皆さんにお力添えできるのなら、なによりです。"
"2300815-14-マリー" = "それに、ショッピングモールは見ているだけで楽しいですし。"
"2300815-15-マリー" = "あっ、先生、見てください。#n可愛いぬいぐるみ……"
"2300815-16-マリー" = "あっちには素敵なお洋服が……"
"2300815-17-マリー" = "このアクセサリーも可愛いですね……。"
"2300815-18" = "[ns] （こんなに浮かれてるマリー、初めて見るかも……）"
"2300815-19-店主" = "そこのお二人さん！よかったら見ていきな！"
"2300815-20-マリー" = "えっ、私たちのこと……でしょうか？"
"2300815-21-店主" = "お嬢ちゃんのことだよ！さっきからキラキラした目で見てたじゃないか。"
"2300815-22-店主" = "そんな遠くからじゃなくて、もっと近くで見ていきな！"
"2300815-23-マリー" = "お、お言葉に甘えて……"
"2300815-24-店主" = "これは最近流行りのアクセサリーでね！お値打ち品だ！"
"2300815-25" = "[ns] \"良かったら、これプレゼントさせてくれないかな？\""
"2300815-26-マリー" = "えっ！？わ、私にですか？"
"2300815-27" = "[s1] \"いつも頑張っているマリーに、ね。\"\n[s2] \"他にも気に入ったものがあったら教えて。\""
"2300815-28-マリー" = "あっ、えっと……。"
"2300815-29-マリー" = "い、いえ……大丈夫、です……。"
"2300815-30-マリー" = "せ、先生のお気持ちは、とても嬉しいのですが……。"
"2300815-31-マリー" = "シスターとして、不必要な贅沢は……避けなければならないので……。"
"2300815-32-マリー" = "も、もちろん……このアクセサリーは……とても可愛いのですが……うぅぅ……。"
"2300815-33" = "[s] \"これくらい、いいんじゃないかな。いつもコサージュつけてるでしょ？\""
"2300815-34-マリー" = "あ……これ、ですか……。"
"2300815-35-マリー" = "このコサージュは……。"
"2300815-36-マリー" = "シスターフッドの誓約を忘れないようにと買ったものなんです。"
"2300815-37-マリー" = "この枯れない白い花のように、私も初心を忘れぬよう……。"
"2300815-38" = "[s] \"そうだったんだね。\""
"2300815-39-マリー" = "先生……その、本当のことを、お話しても、よろしいでしょうか。"
"2300815-40" = "[s] \"本当のこと？\""
"2300815-41-マリー" = "ここは懺悔室ではありませんが……#n実は私……ウソをつきました……。"
"2300815-42-マリー" = "このコサージュは……"
"2300815-43-マリー" = "か、可愛いから……買ったんです……。"
"2300815-44" = "[s] \"うん？\""
"2300815-45-マリー" = "も、もちろん……初心を忘れないように、という意味もあるのですが……！！"
"2300815-46-マリー" = "でも……可愛かったから……買っただけなんです……。"
"2300815-47-マリー" = "シスターは、質素倹約を心がけなければならないのに……。"
"2300815-48-マリー" = "でも、アクセサリーを見ていると、私もオシャレをしてみたいと思ってしまって……。"
"2300815-49-マリー" = "な、なので……コサージュをつけてみたんです……。"
"2300815-50-マリー" = "うぅ……見栄を張って先生にウソまでついて……。"
"2300815-51-マリー" = "シスター失格です……。"
"2300815-52-マリー" = "……。"
"2300815-53-マリー" = "でも、少しだけスッキリしました。"
"2300815-54" = "[s] \"マリーなりのオシャレなんだね。\""
"2300815-55-マリー" = "はい……この程度なら大丈夫かな、と……。"
"2300815-56-マリー" = "でも、シスター失格です……よね？"
"2300815-57" = "[s] \"ううん、そんなことないよ。\""
"2300815-58-マリー" = "え、えぇ！？"
"2300815-59" = "[s3] \"その程度なら大丈夫だと思う。\"\n[s4] \"シスターである前に、一人の生徒だからね。\""
"2300815-60-マリー" = "そ、そう、ですかね……。"
"2300815-61" = "[s5] \"生徒だもの。可愛いものが好きだったり、\"\n[s6] \"オシャレをしたくなるのは、普通の気持ちだと思うよ。\""
"2300815-62-マリー" = "先生……。"
"2300815-63-マリー" = "……そう仰っていただいて、少しだけ心が落ち着きました。"
"2300815-64-マリー" = "どこまでが普通で、どこまでが普通ではないのか……"
"2300815-65-マリー" = "私にはまだ、判別が難しいですが……。"
"2300815-66-マリー" = "ふふ、先生のお気持ち、ありがたくいただきますね。"
"2300815-67-マリー" = "私には、このコサージュだけで充分です。"
"2300815-68" = "[s] \"じゃあ、代わりに今から一緒に食事でもどうかな？\""
"2300815-69-マリー" = "もう……先生にはいつも世話になっているのに、これ以上していただくわけには……。"
"2300815-70-マリー" = "……"
"2300815-71-マリー" = "……でも今回は、お言葉に甘えさせていただきますね。"
"2300815-72" = "（そうやって、マリーと一緒に食事をとってシャーレに戻った）"
