[translation]
"2300805-1" = "内なる罰"
"2300805-2" = "（マリーのことが心配になって、彼女の元を訪れた）"
"2300805-3-マリー" = "えっと、どちら様ですか……？"
"2300805-4" = "[s1] \"お見舞いに来たよ。\"\n[s2] \"ごめんね、起こしちゃった？\""
"2300805-5-マリー" = "……っ！？"
"2300805-6-マリー" = "せ、先生……！？ど、どうして先生がこちらに……！？"
"2300805-7-マリー" = "しょ、少々お待ちください！本当に少しで大丈夫ですので……っ！"
"2300805-8-マリー" = "せ、先生、お待たせしました……。"
"2300805-9-マリー" = "すみません、だらしないお部屋をお見せしてしまって……。"
"2300805-10-マリー" = "気にしないで……？"
"2300805-11-マリー" = "で、ですが……。"
"2300805-12-マリー" = "……？い、いえ、先生に来ていただいたのに、ベッドに横になったままなんてわけには……。"
"2300805-13" = "[s3] \"お見舞いに来たんだから。\"\n[s4] \"体調崩してるんだから、無理しないで。\""
"2300805-14-マリー" = "そ、そう、ですか……。"
"2300805-15-マリー" = "そ、そう、ですか……。"
"2300805-16-マリー" = "かえって先生のことを困らせるわけにもいきませんし……。"
"2300805-17-マリー" = "それでは、お言葉に甘えて……。"
"2300805-18" = "（マリーはもう一度ベッドへと戻った）"
"2300805-19-マリー" = "なんだかご心配をおかけしてしまったようで、申し訳ございません。本当に大した症状ではないのですが……。"
"2300805-20" = "[s] \"今は辛くない？\""
"2300805-21-マリー" = "は、はい。それほどでも……。"
"2300805-22-マリー" = "少し休んだら、だいぶ良くなりました。きっと明日には、またいつも通り元気に動けるかと思います。"
"2300805-23-マリー" = "本来は誰かのために動かねばならないシスターが、こうして看病していただく側にというのは……何だか不思議な気分です。"
"2300805-24-マリー" = "ふふっ……。"
"2300805-25-マリー" = "……。"
"2300805-26" = "[ns5] \"……マリー？\"\n[ns6] \"どうしたの？\""
"2300805-27-マリー" = "その、えっとですね……。"
"2300805-28-マリー" = "実は……。"
"2300805-29-マリー" = "ここしばらく、何だか少しだけ疲れを感じていて……実はどこかで一日くらいお休みが欲しいなと、思っていたんです。"
"2300805-30-マリー" = "もしかしたらこれは、そんなことを考えていたせいなのかな、と……。"
"2300805-31-マリー" = "他のシスターの方々は今も頑張っているのに、何だか自分に甘えてしまったようで……。"
"2300805-32-マリー" = "シスターとしてあまり良くないことを考えていたせいで、私の身体が私に対して、罰を下されたのではないかと……。"
"2300805-33-マリー" = "……？"
"2300805-34-マリー" = "罰ではなく、助けてくれた……？私の身体が、ですか？"
"2300805-35-マリー" = "それは、どういった……？"
"2300805-36" = "[s7] \"長く健康でいられる方が良いからね。\"\n[s8] \"できるだけ長くシスターでいられるように、とか。\""
"2300805-37-マリー" = "……。"
"2300805-38-マリー" = "……なるほど。"
"2300805-39-マリー" = "そうですね……そういう考え方もできるかもしれません。"
"2300805-40-マリー" = "ありがとうございます、先生。おかげさまで何だかスッキリしました。"
"2300805-41-マリー" = "身体だけではなく、心の方まで。"
"2300805-42-マリー" = "内心、今日もずっと色々と考えてしまっていたんです。それが、先生とお話している内にスッと……。"
"2300805-43-マリー" = "誰かのために動く者として、ぜひ私も見習わせていただこうと思います。"
"2300805-44-マリー" = "できれば私は、先生のことも、いつか……。"
"2300805-45-マリー" = "……。"
"2300805-46-マリー" = "あ、いえすみません、やはりお気になさらず……"
"2300805-47-マリー" = "もちろん今すぐどうにかという話ではありませんし、今日はせっかくですのでゆっくりさせていただこうかと。"
"2300805-48-マリー" = "明日のためにも、これから先のためにも……ただ……。"
"2300805-49-マリー" = "いつかは……はい。"
"2300805-50" = "（そして少しだけマリーの話し相手になった後、色々と看病をした）"
"2300805-51" = "（その後マリーが再び眠りに落ちたのを見届けてから、シャーレへと戻った）"
