[translation]
"10046270-1-ティーパーティーの下級生" = "あの……。"
"10046270-2-イチカ" = "あれ？役員の皆さんじゃないっすか。"
"10046270-3-イチカ" = "何かご用っすか？"
"10046270-4-ティーパーティーの上級生" = "いえ、その逆です。私たちにも、何か手伝えることはないですか？"
"10046270-5-ティーパーティーの下級生" = "ずっとお一人で……さぞ大変だったことでしょう。"
"10046270-6-イチカ" = "え？あー……お気持ちは嬉しいんすけど……。"
"10046270-7-ティーパーティーの下級生" = "人手、全然足りていないのではなくて？"
"10046270-8-ティーパーティーの下級生" = "あのナギサ様ですから、何かお考えがあるのでは……。"
"10046270-9-ティーパーティーの上級生" = "でも、そのナギサ様は現場のことをあまりご存知ないのよ？"
"10046270-10-ティーパーティーの下級生" = "それは、まあ……。"
"10046270-11-ティーパーティーの上級生" = "あなたもそう思いませんか？"
"10046270-12-イチカ" = "わ、私っすか！？"
"10046270-13-ティーパーティーの下級生" = "ええ、あのお方は毎度あの調子ですから……。"
"10046270-14-ティーパーティーの上級生" = "現場のことをいちいち考えられる立場ではないのでしょうけれど……#nあんまりですよね～"
"10046270-15-イチカ" = "は、ははは……。"
"10046270-16-ティーパーティーの下級生" = "とはいえ文句を言っていても始まりません。"
"10046270-17-ティーパーティーの下級生" = "なので、手伝いに来たんです。"
"10046270-18-イチカ" = "実際、ちょうど困ってたんで、助かるっす。"
"10046270-19-イチカ" = "んじゃ、よろしくお願いするっす！"
