[translation]
"1003620-1" = "風呂敷ピクニック"
"1003620-2" = "（約束の時間に合わせて公園へ行くと、前と同じ場所でヒナタが待っていた）"
"1003620-3" = "（ヒナタは大きなカバンを持ちながら、もう片方の手で大きく手を振ってきた）"
"1003620-4-ヒナタ" = "あっ、先生！"
"1003620-5-ヒナタ" = "すぐそちらに行きますから、"
"1003620-6-ヒナタ" = "待っていてください！"
"1003620-7-ヒナタ" = "いつもお忙しいところ来てくださってありがとうございます！#nお待ちしておりました！"
"1003620-8" = "[s1] \"ごめん、ちょっと遅くなっちゃった。\"\n[s2] \"結構待たせちゃったね……。\""
"1003620-9-ヒナタ" = "……？"
"1003620-10-ヒナタ" = "……？"
"1003620-11-ヒナタ" = "い、いえいええ！そういう意味ではなく……！#n私も到着してからまだ数分しか経っていませんし……！"
"1003620-12-ヒナタ" = "そういう意味で言ったわけではなく、その……ごめんなさい。"
"1003620-13-ヒナタ" = "……？す、すみません、"
"1003620-14-ヒナタ" = "何だかお互いに謝る形に……。"
"1003620-15-ヒナタ" = "……う、浮かれてますでしょうか？"
"1003620-16-ヒナタ" = "そう見えますかね……？"
"1003620-17-ヒナタ" = "いつものように振る舞えていると思ったのですが……。"
"1003620-18-ヒナタ" = "先生にはお見通しでしたね。"
"1003620-19-ヒナタ" = "……ふふっ。"
"1003620-20" = "[s3] \"ヒナタが楽しそうで良かった。\"\n[s4] \"私も、会えるの楽しみにしてたよ。\""
"1003620-21-ヒナタ" = "先生……。"
"1003620-22-ヒナタ" = "先生……。"
"1003620-23-ヒナタ" = "あ、うっかりしていました！お話よりも先にすることがあったのです。"
"1003620-24-ヒナタ" = "お腹は空いていますか？先日と同じように、今日もお弁当を作ってきたんです！#nよろしければご一緒にと……！"
"1003620-25-ヒナタ" = "ありがとうございます！#nではレジャーシートを敷いて、っと……。"
"1003620-26" = "[ns5] \"……お、大きいね？\"\n[ns6] \"これ、かなり大きい百科事典みたいなサイズだね……？\""
"1003620-27-ヒナタ" = "た、足りないと困るかなと……"
"1003620-28-ヒナタ" = "た、足りないと困るかなと……"
"1003620-29-ヒナタ" = "あ、ご心配なく。#n残った分は全て私が食べますから！"
"1003620-30-ヒナタ" = "……。"
"1003620-31-ヒナタ" = "何だか今の言い方ですと、私がすごく大食漢みたいな……。"
"1003620-32-ヒナタ" = "と、とにかく！"
"1003620-33-ヒナタ" = "先生は遠慮せずに召し上がってください！"
"1003620-34-ヒナタ" = "精一杯、心を込めて作って来ましたので……"
"1003620-35-ヒナタ" = "……えっ？"
"1003620-36-ヒナタ" = "あ、あれ……お弁当が……？"
"1003620-37-ヒナタ" = "……本？"
"1003620-38" = "[s7] お弁当かと思いきや、本が……？\"\n[s8] \"すごく分厚い本だ……。\""
"1003620-39-ヒナタ" = "……え？"
"1003620-40-ヒナタ" = "……え？"
"1003620-41-ヒナタ" = "な、なんで……どうして「物品管理台帳」がここに……。"
"1003620-42-ヒナタ" = "た、確かにお弁当を作って入れたはず……？"
"1003620-43-ヒナタ" = "ど、どうして……！？"
"1003620-44" = "[s9] \"お、落ち着いてヒナタ！\"\n[s10] \"大丈夫、私もよくやる！\""
"1003620-45-ヒナタ" = "で、ですがお弁当が……！"
"1003620-46-ヒナタ" = "で、ですがお弁当が……！"
"1003620-47-ヒナタ" = "うぅ、先生のお腹を空かせたままになってしまい……結局またご迷惑を……。"
"1003620-48-ヒナタ" = "……。"
"1003620-49-ヒナタ" = "ご、ごめんなさい……。"
"1003620-50" = "[ns11] 風呂敷に包まれていた「物品管理台帳」を手に取る。\n[ns12] \"すごく分厚い本だね。これ、見ても大丈夫？\""
"1003620-51-ヒナタ" = "あ、それは、その……。"
"1003620-52-ヒナタ" = "見ていただいても大丈夫なのですが、面白くはないかと……。"
"1003620-53-ヒナタ" = "名前通り、私が管理している聖堂の備品を記録したものですので……。"
"1003620-54-ヒナタ" = "……先生？#nそんな真剣に読まれて……何かありましたか？"
"1003620-55-ヒナタ" = "は、はい、確かに細かく記録してはいますね……？"
"1003620-56-ヒナタ" = "私たちの聖堂、すごく大きいので……それに伴い、管理する備品も多くなりがちで……。"
"1003620-57-ヒナタ" = "数千……いや、数万はあるかもしれません。"
"1003620-58-ヒナタ" = "流石に覚えておける量ではないので、こうして記録をつけているのです。"
"1003620-59-ヒナタ" = "そもそも私は、抜けているところが多いのもあって……それで、忘れないようにしておければと。"
"1003620-60-ヒナタ" = "えへへ……。"
"1003620-61" = "[s13] \"几帳面なのは良いことだね。\"\n[s14] \"ヒナタは仕事が丁寧だね。\""
"1003620-62-ヒナタ" = "……？"
"1003620-63-ヒナタ" = "そ、そんなこと初めて言われました……！私、いつもドジをしてばかりなのに……今日もお弁当と台帳を間違えて……。"
"1003620-64-ヒナタ" = "それについても、ただ記録しているだけですし……。"
"1003620-65-ヒナタ" = "……？"
"1003620-66-ヒナタ" = "それが大切……？"
"1003620-67" = "[s15] \"短所をカバーできるのも、几帳面だからだよ。\"\n[s16] \"自分に向き合う姿勢が大切だと思うから。\""
"1003620-68-ヒナタ" = "……！"
"1003620-69-ヒナタ" = "……あれ、先生？それ、どうされたんですか？"
"1003620-70-ヒナタ" = "……あっ。"
"1003620-71-ヒナタ" = "お、お弁当……！？"
"1003620-72-ヒナタ" = "先生も、お弁当を持ってきてたんですか？"
"1003620-73" = "[s17] \"私も、いつもは几帳面って感じではないんだけど……。\"\n[s18] \"ヒナタに、私のお弁当も食べてもらおうかなって。\""
"1003620-74-ヒナタ" = "先生……。"
"1003620-75-ヒナタ" = "何と言うかその、ありがとうございます……。"
"1003620-76-ヒナタ" = "おかげ様で、お腹を空かせずに済みました。"
"1003620-77-ヒナタ" = "……ふふっ。"
"1003620-78-ヒナタ" = "本当に、ありがとうございます……！"
"1003620-79" = "（その後ヒナタと一緒にお弁当を食べながら、物品管理台帳に目を通した）"
"1003620-80" = "（膨大なページには意外な物品も多く、お弁当を食べ終わっても楽しい会話が続いた）"
"1003620-81" = "（時間を忘れるくらい楽しかったが、遅くなる前にヒナタを送り届けた）"
