[translation]
"10001010-1" = "第1話;粛清に染まる夏至祭"
"10001010-2" = "レッドウィンター連邦学園・食堂"
"10001010-3-チェリノ" = "ここが我がレッドウィンター連邦学園の食事を担っている、給食施設だ！"
"10001010-4-チェリノ" = "食事は生命活動の根幹！#n身分の高い低いによって食事内容で差別されるなんてことは、あってはならない……"
"10001010-5-チェリノ" = "そこで我がレッドウィンター連邦学園では、全ての生徒たちにみな同じ量が配られている！"
"10001010-6-チェリノ" = "もちろん、この学園の書記長であり生徒会長であり、環境美化部部長であり、清掃部部長であり……"
"10001010-7-チェリノ" = "えーっと……"
"10001010-8-チェリノ" = "とにかくすごいことを全て引き受けているこのチェリノ様は、とっても偉大だからな。他の生徒たちより、プリンを一つ多く食べられる特権を持っている！"
"10001010-9-チェリノ" = "それ以外の者はみな、平等な食事を楽しめるようになっているのだ。ふははは！"
"10001010-10" = "[s] \"今はここで何を作ってるの？\""
"10001010-11-チェリノ" = "良い質問だ、カムラッド！#nおいらもさっきから、この甘い匂いが気になっていたのだ。"
"10001010-12-チェリノ" = "調理長、今作ってる料理は何だ？"
"10001010-13-給食部の部長" = "あ、会長！今は偉大なる会長の命令に従い、「イワン・クパーラ」のためのプリンを作っていました。"
"10001010-14-給食部の部長" = "今回のイワン・クパーラでは「プリンの配給量を二倍に増やすように」とのご指示があったため、給食部の部員一同、現在昼夜を問わずプリン作りに励んでおります。"
"10001010-15-チェリノ" = "なるほど、給食部として模範的な姿勢だ！良いぞ！"
"10001010-16-チェリノ" = "今回の夏至祭が終わったらお前たちには、「第一級髭勲章」を授与することにしよう！"
"10001010-17-給食部の部長" = "ありがとうございます、会長！"
"10001010-18-チェリノ" = "そして、これが例のプリンか……よし、おいらが一度試食してみよう。"
"10001010-19-チェリノ" = "パクッ、モグモグ……。"
"10001010-20-チェリノ" = "うっ……！な、なんだこのプリンは！#n味は薄いし、触感も柔らかすぎるぞ！？"
"10001010-21-給食部の部長" = "そ、それは……「生産量を増やすように」とのご指示はあったものの、「食材をこれ以上追加することはできない」とのことでしたので……。"
"10001010-22-給食部の部長" = "どうしても牛乳が足りず、それでも量を増やすにはやむを得ないと判断して、水を……。"
"10001010-23-チェリノ" = "ぷ、プリンに水を混ぜただと！？なんということを……！"
"10001010-24-チェリノ" = "生産量を増やすためとはいえ、そんなことが許されてたまるものか！"
"10001010-25-チェリノ" = "マリナ！"
"10001010-26-チェリノ" = "お呼びでしょうか、チェリノ会長。"
"10001010-27-チェリノ" = "粛清だ！プリンに水を混ぜたこのけしからん部員たちを、全員粛清せよ！"
"10001010-28-給食部の部長" = "お、お許しください会長！私たちも、こんなことはしたくなかったのです……！"
"10001010-29-マリナ" = "貴様！チェリノ会長の完璧な計画に対し、このような愚行を働いておいて、タダで済むとでも思っているのか！"
"10001010-30-マリナ" = "それとも、まさか大いなる髭の権威に逆らうつもりか？"
"10001010-31-給食部の部長" = "うう、そんな……そんなっ……！"
"10001010-32-チェリノ" = "ふう、少し騒がしくしてしまったな。"
"10001010-33" = "[s1] \"恐ろしい……。\"\n[s2] \"レッドウィンター連邦学園って、怖いところなんだね……。\""
"10001010-34-チェリノ" = "ははっ。今の騒ぎは忘れてくれたまえ、カムラッド。ちょっとしたハプニングにすぎない。"
"10001010-35-チェリノ" = "ははっ。今の騒ぎは忘れてくれたまえ、カムラッド。ちょっとしたハプニングにすぎない。"
"10001010-36-チェリノ" = "ん？粛清された生徒たちはどうなるのかって？"
"10001010-37-チェリノ" = "それはもちろん……"
"10001010-38-チェリノ" = "とても恐ろしい罰が与えられることになる！"
"10001010-39-チェリノ" = "例えば……トイレ掃除を1週間一人でやらなきゃいけないだとか、"
"10001010-40-チェリノ" = "1か月の間、おやつの配給が中断されるとかな！"
"10001010-41-チェリノ" = "だからカムラッドも、レッドウィンター連邦学園において権威に歯向かうようなことはしない方がいいぞ、はははっ！"
"10001010-42-チェリノ" = "とにかく、引き続き次の視察場所へ行くとしようか！"
"10001010-43" = "レッドウィンター連邦学園・印刷所"
"10001010-44-チェリノ" = "ここは我がレッドウィンター連邦学園内部における、宣伝や広報を担当している日刊紙、『レッドベア』の編集部だ！"
"10001010-45-チェリノ" = "ん？キヴォトスのマスコミ活動は、クロノスがすべて担当してると思ってた……？"
"10001010-46-チェリノ" = "何ということだ……！"
"10001010-47-チェリノ" = "『レッドベア』は、クロノスのあんな扇動的なジャーナリズムとは違うんだぞ！あんなゴシップと虚偽の情報で溢れた記事とは比べものにならないぐらい、速さと正確さとをきっちり備えている！"
"10001010-48-チェリノ" = "カムラッドも機会があれば『レッドベア』を読んでみると良い。#nこれまで知らなかった新しい事実を、たくさん知ることになるはずだ、はははははっ！"
"10001010-49-チェリノ" = "編集長、『レッドベア～イワン・クパーラ特集号～』の準備はどうだ？"
"10001010-50-編集長" = "はい、何も問題ありません、会長。今回のイワン・クパーラ特集号では、特別にカラーインクと最高級の紙を使用して、会長の肖像画を表紙に大きく印刷する予定です。"
"10001010-51-チェリノ" = "それは素晴らしい！お前たちにも、今回の夏至祭が終わったら勲章を授与しよう！"
"10001010-52-編集長" = "身に余る光栄です！ありがとうございます、会長！"
"10001010-53-チェリノ" = "ふむ、それでは少し読ませてもらうとしようか。"
"10001010-54-チェリノ" = "「偉大なるチェリノ会長が、遊園地の増設作業を行っている現場を視察されました……」"
"10001010-55-チェリノ" = "ふむふむ、よし！"
"10001010-56-チェリノ" = "……ん？待て、編集長。この写真……"
"10001010-57-チェリノ" = "マリナとトモエは写っているのに、肝心のおいらの姿が写っていないじゃないか。どういうことだ？"
"10001010-58-編集長" = "そ、それは……その時踏み台も無かったので、どうしても同時に一枚の写真に収めるのが難しく……。"
"10001010-59-チェリノ" = "なっ……！それは、おいらがチビだと言ってるのか！？"
"10001010-60-編集長" = "め、滅相もございません！決してそのようなことは……！"
"10001010-61-マリナ" = "この無礼者め！"
"10001010-62-マリナ" = "例えそうだとしても、合成編集をして会長の背を高く見せるなど、やり方はいくらでもあるだろう！"
"10001010-63-編集長" = "し、しかし私たち『レッドベア』は、いつも事実だけを正確にお伝えする誠実なマスコミとして……。"
"10001010-64-チェリノ" = "うううっ……！マリナ！"
"10001010-65-マリナ" = "はい、会長。"
"10001010-66" = "こいつはレッドウィンター連邦学園において最高の尊厳を持つ、このチェリノ会長を侮辱した！この不届きな編集長を粛清せよ！"
"10001010-67-編集長" = "す、すぐに記事を修正しますから！この通りです、会長！"
"10001010-68-マリナ" = "言葉も記事も、後から修正をすることなどできない……そんなことも知らないのか！"
"10001010-69-チェリノ" = "ふう……最近は特に、不届き者が多い気がするな。"
"10001010-70-チェリノ" = "まあ、みんな粛清してしまえばいいのだから気にしないが。"
"10001010-71-チェリノ" = "ふぁあ……ちょっと働きすぎたな、眠い……。"
"10001010-72-チェリノ" = "トモエ、おいら帰って、お昼寝するね……。"
"10001010-73-トモエ" = "ふふ、分かりました。すぐに寝床をご用意いたします。"
"10001010-74-チェリノ" = "カムラッドも、おいらが昼寝をしている間、十分に休むように……。"
"10001010-75-トモエ" = "先生は休憩室をご利用なさってください。"
"10001010-76-トモエ" = "ご案内いたします。さあ、こちらへ。"
"10001010-77" = "レッドウィンター連邦学園・新館の廊下"
"10001010-78-保安委員" = "お疲れ様でした、マリナ委員長！"
"10001010-79-マリナ" = "うむ！皆もご苦労！"
"10001010-80-マリナ" = "今日も気持ちよく粛清を終えたことだし、寮に戻って休むとするか……。"
"10001010-81-マリナ" = "あっ、うわっ！？"
"10001010-82-マリナ" = "いったた……うっ、腰が……。"
"10001010-83-マリナ" = "こんなところに空き缶が転がってるなんて、環境美化部は何をしているんだ！"
"10001010-84-マリナ" = "サボタージュの疑いで部員全員連行するぞ！？"
"10001010-85-マリナ" = "それはさておき、転んだ時に何かにぶつかった気がするが、"
"10001010-86-マリナ" = "一体何に……？"
"10001010-87-マリナ" = "こ、これは……チェリノ会長の石像！？"
"10001010-88-マリナ" = "しかも倒れたせいで、髭のところが変な形に割れてしまっている！"
"10001010-89-マリナ" = "ど、どうする？接着剤ではくっつけられなさそうだし……。"
"10001010-90-マリナ" = "も、もしチェリノ会長に、このことが知られたら……。"
"10001010-91-チェリノ" = "おいらの石像を割ってしまった？しかも、髭が取れておかしなことになっているだと？"
"10001010-92-チェリノ" = "うう……なんてことを、これは許されない！粛清、粛清だ！"
"10001010-93-チェリノ" = "マリナ委員長を、旧校舎のあの汚いトイレに押送しろ！卒業するまで、ずっとトイレ掃除でもさせておけ！"
"10001010-94-マリナ" = "そ、そんなわけにはいかない！私がこの立場になるまでに、どれだけ努力をしてきたことか……！"
"10001010-95-マリナ" = "何か、何か方法を見つけないと、チェリノ会長に粛清されずに済む方法を……！"
"10001010-96-マリナ" = "……待てよ。"
"10001010-97-マリナ" = "逆に、チェリノ会長さえいなければ、粛清されることもないのでは？"
"10001010-98-マリナ" = "そうだ……！戦術の基本はやられる前にやる事！チェリノ会長を追い出して私が会長になれば、粛清されることもない！"
"10001010-99-マリナ" = "保安委員、全員集合！"
"10001010-100-保安委員" = "委員長、急にどうされたのですか？"
"10001010-101-マリナ" = "……今から私たちは事務局に進撃を行う。そして幹部たちを全員引き下ろし、チェリノ会長を討つ！"
"10001010-102-保安委員" = "委員長、それはつまり……革命、ということですか？"
"10001010-103-マリナ" = "そ、そうだ！これは革命だ！"
"10001010-104-マリナ" = "……決して、チェリノ会長に粛清されるのが怖くて言い出しているわけではない！"
"10001010-105-マリナ" = "おお、マリナ委員長が刀を抜かれた！"
"10001010-106-マリナ" = "腐りきったチェリノ会長とあの腰巾着共に、鉄槌を下す時だ！"
"10001010-107-マリナ" = "（何となくの思い付きで始めてしまったが、これは……悪くないな！）"
"10001010-108-マリナ" = "（よし、このままレッドウィンターの新たな会長となり、全ての権力を享受するとしよう！）"
"10001010-109-マリナ" = "よし！それでは皆の者、事務局に向かって……。"
"10001010-110-マリナ" = "突撃！"
