[translation]
"10023030-1" = "第3話;時計の無い心臓"
"10023030-2-モモイ" = "「慈愛の怪盗」……って、誰？"
"10023030-3-モモイ" = "「慈愛の怪盗」は、かの悪名高き「七囚人」の一人。#n本当の名は存じておりませんが……"
"10023030-4" = "[s1] \"「七囚人」……！？\"\n[s2] \"ワカモと同じ……？\""
"10023030-5-モモイ" = "その通りです。#n「災厄の狐」と呼ばれるワカモは、現れるたびに辺りを焦土と化していきますが……"
"10023030-6-モモイ" = "その通りです。#n「災厄の狐」と呼ばれるワカモは、現れるたびに辺りを焦土と化していきますが……"
"10023030-7-明太郎" = "「慈愛の怪盗」は……ターゲットにしたものは必ず盗んでいくことで有名です。"
"10023030-8-モモイ" = "「怪盗」っていうか……ただの犯罪者じゃん！それに変な名前！"
"10023030-9-ミドリ" = "お姉ちゃん……"
"10023030-10-明太郎" = "ほう……「慈愛の怪盗」に対してそのような反応をされるとは……#n流石はC&C。"
"10023030-11-明太郎" = "ですが……「慈愛の怪盗」の所業は、到底無視できるものではありません。#n予告状が届いたが最後。どのような警備も無意味で、宝は奪われてきました……。"
"10023030-12-明太郎" = "もっとも、予告状があまりにも難解なため、盗られるまで何が狙われているのか分からない、というのも大きいのでしょうが。"
"10023030-13-アリス" = "パンパカパーン！クエスト内容の更新です。次は「慈愛の怪盗」と対決です！"
"10023030-14-ユズ" = "その予告状……わたしたちも見て……良いですか？"
"10023030-15-ユズ" = "ええ、もちろんです。"
"10023030-16-明太郎" = "こちらをどうぞ。"
"10023030-17" = "1日に22回、向き合う2人の旅人。"
"10023030-18" = "正確な2人。計り知れない20。そして半歩。"
"10023030-19" = "月の届かない場所、止まった舞とアンティキティラの裏側。"
"10023030-20" = "一度も授与された事の無い、贅沢であるが不遇な剣のもとへ伺います。#n――慈愛の怪盗"
"10023030-21-一同" = "これは……？"
"10023030-22-明太郎" = "「慈愛の怪盗」の予告状です。まずもって、これを読み解くのが難しく……"
"10023030-23-明太郎" = "にもかかわらず「慈愛の怪盗」は、「堂々と予告状を送り、盗みを成功させた」と自らの犯行を流布するのです。"
"10023030-24-明太郎" = "ああ、何度読んでも分かりません。#n1日に22回、向き合う2人の旅人とは、一体何を指すのでしょう？"
"10023030-25-モモイ" = "この屋敷に、1日22回も顔を合わせてる人が居るってことじゃないかな？"
"10023030-26-モモイ" = "なに言ってるの、お姉ちゃん。#nそもそもどうやって顔を合わせた回数をカウントするの？"
"10023030-27-アリス" = "アリス、分かりました！この旅人たちはNPCのことです。#nクエストカウンターのNPCなら、1日に20回どころか、もっと会えます！"
"10023030-28-アリス" = "アリスちゃん……現実にクエストカウンターのNPCは居ないよ……"
"10023030-29-アリス" = "そんな事ありません！#nユズは特定の場所に行くと会う事ができ、話をしたらクエストをくれます！"
"10023030-30-ユズ" = "ううぅ……完全には否定できないけど……"
"10023030-31" = "[ns] \"1日に22回なら、大体1時間に1回ペースだね……。\""
"10023030-32-アリス" = "1日は24時間だから、2時間は会わないんですね……"
"10023030-33-ユズ" = "24時間……もしかして……？"
"10023030-34-ユズ" = "すみません……明太郎さん。#nこの屋敷に、アナログ時計はありますか……？"
"10023030-35-ユズ" = "え、ええ……ホールの真ん中に、大きな壁掛けの時計があります……"
"10023030-36-ユズ" = "少し……その時計を見ても良いですか……？"
"10023030-37-明太郎" = "はい、それはもちろんです。もしかして、なにか手掛かりが……？"
"10023030-38-ユズ" = "ユズちゃん、何か分かったの？"
"10023030-39-ユズ" = "わたしの考えが正しければ……この予告状は……"
"10023030-40-ユズ" = "やっぱり……！"
"10023030-41-ユズ" = "ど、どうしたのユズ？#n時間ならスマホで分かるよ？"
"10023030-42-ユズ" = "ううん、違うの。スマホ……というか、デジタル時計じゃ分かりにくくて。"
"10023030-43-モモイ" = "……1行目と2行目の途中までは解読できたと、思う……！"
"10023030-44-一同" = "！！！"
"10023030-45-ミドリ" = "えっ！？どういう事？どうやって！？"
"10023030-46-ユズ" = "「1日に22回向き合う2人の旅人」は……#nたぶん、アナログ時計の短針と長針のことを言ってるんだと思う。"
"10023030-47-ユズ" = "ですがユズ、1日は24時間です。2回多いです！"
"10023030-48-ユズ" = "そう……わたしも最初はそう思ってた。でもね、アリスちゃん。#n時計の針は午前と午後でそれぞれ11回……#n[ruby=・   ・    ・   ・  ・ ・  ・    ・   ・   ・   ・   ・    ・   ・]合計して22回しか重ならない[/ruby]。"
"10023030-49-ユズ" = "短針は毎分0.5度ずつ移動して、長針は毎分6度ずつ移動するから……#n12時の所だけ2回重なって、残りの20回は違う時刻に重なるんだけど……"
"10023030-50-ユズ" = "11時から12時の間は、針が重ならないから……"
"10023030-51-明太郎" = "おおっ……流石はC&C、驚きの推理力！#nでは、その続きも既に？"
"10023030-52-ミドリ" = "えーっと#n「そして半歩。月の届かない場所、止まった舞とアンティキティラの裏側」。"
"10023030-53-モモイ" = "「一度も授与された事の無い、贅沢であるが不遇な剣のもとへ伺います」だよね？"
"10023030-54-ミドリ" = "半歩、半歩……ここも時間の事だと思うけど。"
"10023030-55-モモイ" = "半歩……半分……"
"10023030-56-モモイ" = "あ！もしかして30分のことじゃない？"
"10023030-57-ミドリ" = "ユズちゃん、時計の針が重なる瞬間で、30分前後になるのって何時か分かる？"
"10023030-58-ユズ" = "それなら、5時27分から7時38分の間……かな？"
"10023030-59-ユズ" = "つまり、怪盗はその時間に侵入してくるという事ですか？"
"10023030-60-ユズ" = "でも「月の届かない場所、止まった舞とアンティキティラの裏側」が分かってないよ……これってどういう意味だろう？"
"10023030-61-明太郎" = "アンティキティラ……アンティキティラ……"
"10023030-62-明太郎" = "んんっ！？"
"10023030-63-明太郎" = "何か、心当たりでもありましたか？"
"10023030-64-明太郎" = "い、いえ何も！アンティキティラの裏側なんて、本当に突拍子も無い話ですね。しかし……「授与された事の無い、贅沢であるが不遇な剣」でしたら、心当たりがあります。"
"10023030-65-ミドリ" = "おそらく……明後日から展示される美術品の事でしょう。"
"10023030-66-明太郎" = "こちらになります。"
"10023030-67-アリス" = "……！"
"10023030-68-明太郎" = "叙任式の絵です。#n主人から剣を渡される事で騎士となる光景を描いた1枚ですね。"
"10023030-69-明太郎" = "絵画に描かれた剣であれば、「一度も授与された事の無い」に当てはまるのでは？"
"10023030-70-明太郎" = "そういう意味では、「不遇」とも言えるでしょう。"
"10023030-71-ミドリ" = "言われてみれば……？"
"10023030-72-ミドリ" = "……"
"10023030-73-明太郎" = "こちらの絵画は、ちょうどオークションに出品予定の貴重な一品でして、お求めの方も多いはず。"
"10023030-74-明太郎" = "嗚呼、この大切な絵画を狙うだなんて……#n皆様のお力が無ければ、何も出来ずに奪われる様をただ見ているだけでした。"
"10023030-75-明太郎" = "狙われている品も判明したことですし、皆様にはこちらの絵画を全力で守っていただきたく……"
"10023030-76-モモイ" = "え？#n他にも貴重な物があるんじゃ……？"
"10023030-77-明太郎" = "いえいえ！予告状の謎は解けたのですから、後はこれを守っていただければ！#nはっはっは、間抜けな「慈愛の怪盗」め……"
"10023030-78-明太郎" = "まさか奴も、これほど優秀な皆様がいらっしゃるとは、夢にも思わないでしょう！"
"10023030-79-ミドリ" = "あはは。そ、そうかな？"
"10023030-80-ミドリ" = "でも……"
"10023030-81-アリス" = "お、お役に立てて……何よりです……"
"10023030-82-アリス" = "クエストクリアです！#n次は絵を守る連続クエストですね！"
"10023030-83-明太郎" = "そして大変恐縮なのですが、皆様に追加でお願いしたい事がございまして……"
"10023030-84-ミドリ" = "……なんでしょうか？"
"10023030-85-明太郎" = "明日から3日間、この屋敷の警備をお任せしても良いでしょうか？"
"10023030-86-明太郎" = "構いませんが……もし、予告状の解が間違ってたら？"
"10023030-87-明太郎" = "もちろん、怪盗の狙いが別にある可能性も否定できません。#n……ですが、皆様が捕らえてくだされば良いだけのこと。"
"10023030-88-ユズ" = "「慈愛の怪盗」は神出鬼没で有名ですが、C&Cの実力の前では赤子も同然。#nはっはっは、そうですよね？"
"10023030-89-明太郎" = "是非ともお願い致します。報酬は十分にご用意しますので……そうですね、"
"10023030-90-明太郎" = "コレくらいでいかがでしょう？"
"10023030-91-一同" = "！！！？？"
"10023030-92-ミドリ" = "（ほ……本当に、こんな金額を……？）"
"10023030-93-モモイ" = "（1人1台、最新のプライステーションPro7に……ZBOXシリーズZも買えちゃう！いやいや、2台ずつ買ってもお釣りが出るよね！）"
"10023030-94-モモイ" = "（ど、どうしよう？ミドリ！？）"
"10023030-95-ミドリ" = "（私に聞かれても！）"
"10023030-96" = "[ns] （……まずは落ち着こう）"
"10023030-97" = "[ns] \"一度、私たちだけで話し合っても良いでしょうか？\""
"10023030-98-明太郎" = "ああ、これは気が利かず失礼を。それでは、私は席を外しておりますね。"
"10023030-99-モモイ" = "はああああ……ありがとう、先生。#n頭がパンクするところだったよ……。"
"10023030-100-ミドリ" = "ど、どうしましょう、先生？#n「七囚人」だなんて、もう私たちの手には負えません……。"
"10023030-101-ユズ" = "帰りたい……ロッカー……心の故郷……。"
"10023030-102-アリス" = "みんな、どうしてそんな反応をしているのですか……？#nアリス、一体どうすれば良いのでしょう……。"
"10023030-103" = "[s3] \"まずは依頼をどうするか決めようか？\"\n[s4] \"本当の事を話して、辞退しようか？\""
"10023030-104-ユズ" = "……依頼を辞退したら、一体どうなるんでしょうか……？"
"10023030-105-ユズ" = "……依頼を辞退したら、一体どうなるんでしょうか……？"
"10023030-106-ユズ" = "たぶん……依頼人は抗議すると思う。#n今になって嘘でしたなんて言ったら、ミレニアム全体の問題になるかも……"
"10023030-107-モモイ" = "そ、そうなったらネル先輩も、絶対怒る……よね？"
"10023030-108-ミドリ" = "想像したくない……"
"10023030-109-アリス" = "ですがモモイ！これはアリスたちに与えられたクエストです！#n一度受注したクエストは最後までやるべきだと、モモイが言っていました。"
"10023030-110-アリス" = "なのに、破棄しても良いのですか……？"
"10023030-111-アリス" = "あ、アリス……！も、もちろんその通りなんだけど……！"
"10023030-112-アリス" = "でも……私たちには荷が重いよ……"
"10023030-113" = "[s] \"時には、クエストに逆らう事も必要かもしれないね。\""
"10023030-114-モモイ" = "先生？"
"10023030-115-モモイ" = "それは……どういう？"
"10023030-116" = "[s] \"なにも怪盗と戦う必要はないんじゃないかな。\""
"10023030-117-ミドリ" = "戦わなくても、良い……？"
"10023030-118-ミドリ" = "私、先生の言いたい事が分かったかも！"
"10023030-119-モモイ" = "要は怪盗に何も奪われなければ私たちの勝ちって事でしょ？"
"10023030-120-一同" = "！！！"
"10023030-121-モモイ" = "もうここまで来ちゃったし、先生も一緒にいる。#nそれに屋敷の防犯設備もすごいんでしょ？"
"10023030-122-モモイ" = "怪盗と正面から戦ったり、捕まえる必要は無い。#nお宝を盗られなければ良いんだよ！"
"10023030-123-モモイ" = "たしかに、それならまだ可能性はあるかも……"
"10023030-124-モモイ" = "わたし達は……C&C相手に戦った経験もあるし……#nもっと凄い戦いも、してきたから……"
"10023030-125-ユズ" = "それを活かせば……"
"10023030-126" = "[s] \"成功したら、報酬が貰えるかもしれない。でも、リスクはあるよ。\""
"10023030-127-ユズ" = "（確かに、その報酬さえあれば……わたし達ゲーム開発部の……）"
"10023030-128-モモイ" = "じゃあ、決まりだね？"
"10023030-129-ミドリ" = "はあ……本当に大丈夫かな。"
"10023030-130-ミドリ" = "私達ならできるよ！#nそれに、これってC&Cに貸しを作るチャンスじゃない？"
"10023030-131-モモイ" = "本来は、C&Cが受けるはずだったんだし！"
"10023030-132-アリス" = "アリス、頑張ります！#n先生と一緒なら、アリスたちは無敵です！"
"10023030-133-明太郎" = "……お気持ちは固まったのですね。#n引き受けてくださりありがとうございます。"
"10023030-134-明太郎" = "それでは先ほど申し上げた通り、#n[ruby=・  ・   ・]3日間[/ruby]この屋敷と美術品を守っていただきたく思います。"
"10023030-135-ミドリ" = "3日間でいいんですか？"
"10023030-136-明太郎" = "ええ。明日から開催するイベントの期間中だけで構いません。"
"10023030-137-明太郎" = "初日はゲストを集めてパーティーを、2日目は美術品の展示。#nそして最終日に……美術品のオークションを開催する予定です。"
"10023030-138-明太郎" = "……か、怪盗は、その3日のうち、どこかで来る……ということですね……"
"10023030-139-明太郎" = "ええ、おそらく。#n初日はパーティー会場で給仕をしながら守っていただければと思います。"
"10023030-140-モモイ" = "えっ、給仕……？"
"10023030-141-明太郎" = "ええ。木を隠すなら森の中と申しますでしょう？#n正体を隠して会場に紛れるには最適かと。#nちょうど皆様、給仕に最適な格好をなされておりますし。"
"10023030-142-明太郎" = "念のためお伝えしておきますが……ゲストに怪盗が紛れ込んでいる可能性もあります。#n油断なさらぬよう、くれぐれもご注意を。"
"10023030-143-ミドリ" = "（何か、引っかかるような……）"
"10023030-144-ミドリ" = "（予告状の解は、本当に合っているのかな……？#n　他の可能性もありそうなのに……）"
