[translation]
"10023090-1" = "第9話;所有権の移転"
"10023090-2-ユズ" = "ううううぅ……怖かった……"
"10023090-3-ミドリ" = "すごいよ、ユズ！警備に全く気付かれないなんて！"
"10023090-4-ミドリ" = "ユズちゃん、どんな状況だった？"
"10023090-5-ユズ" = "意外と……正門までは監視が厳しくなかった……"
"10023090-6-ユズ" = "警備員は……ほとんど正門の内側にいるみたい……"
"10023090-7-ユズ" = "と、扉の隙間から覗いたら……お屋敷の中は警備でいっぱいだったけど……"
"10023090-8-ミドリ" = "やっぱり……この方法しか無いんでしょうか、先生？"
"10023090-9" = "[s1] \"うん……\"\n[s2] \"まずは敵の意識を分散させないとね。\"\n[s3] \"「慈愛の怪盗」の合図が来たら、正面突破するよ。\""
"10023090-10-モモイ" = "そうすれば、きっと警備員は混乱するはずだし……"
"10023090-11-モモイ" = "今さら悩んでも仕方ないよ！作戦通りいこう！"
"10023090-12" = "（息を潜めて待っていると……）"
"10023090-13" = "（屋敷の裏側から、花火が打ち上がる音がした）"
"10023090-14-警備ロボットA" = "おい、あれ……銅田さん何か言ってたか？"
"10023090-15-警備ロボットB" = "いや、何も聞いてないが……？"
"10023090-16" = "（花火が夜空の真ん中で爆発すると……）"
"10023090-17" = "（「慈愛の怪盗」の5文字が浮かんだ……！）"
"10023090-18-警備ロボットA" = "「慈愛の怪盗」だ！！"
"10023090-19-警備ロボットB" = "集合！全員で「慈愛の怪盗」を追うぞ！！"
"10023090-20-ユズ" = "合図です……先生。"
"10023090-21" = "[s] \"これ以上なく分かりやすい合図だったね……\""
"10023090-22-トキ" = "ええ。少なくとも、間違えることはなさそうです。"
"10023090-23-トキ" = "1分後に私たちも行きましょう。"
"10023090-24-トキ" = "お願いできますか、アリス？"
"10023090-25-アリス" = "もちろんです！今こそ勇者の出番ですね！"
"10023090-26-アリス" = "仲間と一緒にイベントを進めて……#nみんなでレベルアップするのです！"
"10023090-27-警備員A" = "……ん？今度はあっちで騒ぎか？"
"10023090-28-警備員B" = "一体どうなってるんだ……？"
"10023090-29-？？？" = "光よ――！"
"10023090-30-警備員たち" = "！！！"
"10023090-31-モモイ" = "さあ、始めるよ！"
"10023090-32-トキ" = "速やかに制圧します。"
