[translation]
"10023110-1" = "エピローグ;ハッピーエンドは、いつまでも！"
"10023110-2-モモイ" = "……"
"10023110-3-ミドリ" = "……"
"10023110-4-ユズ" = "ひぃ……"
"10023110-5-アリス" = "うわあぁぁぁん！ネル先輩が怒ってます！アリス、怖いです！"
"10023110-6-ネル" = "あのな、お前ら……"
"10023110-7-モモイ" = "許して、ネル先輩！"
"10023110-8-ネル" = "……あぁ？何の事だよ。"
"10023110-9-モモイ" = "わざわざ言わせないと気が済まないの？#nひどいよ先輩！"
"10023110-10-ネル" = "いや、だから何の事だよ……"
"10023110-11-モモイ" = "みんな、ごめんね！#n私が……私が最初から断ってたら……こんな事にはならなかったはずなのに……！"
"10023110-12-モモイ" = "もう終わりだよ……ネル先輩はカンカンだし……ゲーム開発部は廃部に……#nC&Cの名前を騙った罪は重い……"
"10023110-13-モモイ" = "うぅ……頑張って守ってきた部活なのに……#nアリスもユズも、こうして一緒に居られるようになったのに……！"
"10023110-14-ユズ" = "モモイ……"
"10023110-15-アリス" = "な、泣かないでください。モモイ、アリスは……"
"10023110-16-アリス" = "アリスたちは大丈夫です。#n離れていても心は一緒だと、アリスは学びました……！"
"10023110-17-ネル" = "はぁ……お前ら、何か勘違いしてるみたいだけどよ……"
"10023110-18-ネル" = "あたしはまだ何も……"
"10023110-19-ネル" = "って、いつもあたしの事そう思ってたのか！？"
"10023110-20-アカネ" = "ふふ、どうでしょう？"
"10023110-21-ネル" = "おい、自業自得だって言いてぇのか！？"
"10023110-22-トキ" = "先輩方、申し訳ありません。"
"10023110-23-トキ" = "証拠品は確保しましたが、容疑者を捕らえることができず……"
"10023110-24-ネル" = "ああ、それはあたしらが捕まえたから気にすんな。"
"10023110-25-トキ" = "いえ。私の不手際で先輩方のお手を煩わせてしまったので……"
"10023110-26-ネル" = "別に、んなこと気にすんなよ。#n終わり良ければ全て良しっつうだろ。"
"10023110-27-ネル" = "んで……"
"10023110-28-ネル" = "お前ら。"
"10023110-29-ミドリ" = "ひぃっ！？"
"10023110-30-ミドリ" = "い、命だけは……！"
"10023110-31-トキ" = "お待ちください、ネル先輩。"
"10023110-32-ネル" = "あぁん？"
"10023110-33-トキ" = "今回の件……あまりゲーム開発部を責めないでください。"
"10023110-34-ネル" = "ほう？"
"10023110-35-トキ" = "ゲーム開発部は何も悪くありません。"
"10023110-36-トキ" = "本来であれば、先輩方に連絡し、応援を待つべきだったところを、私はしませんでした。"
"10023110-37-トキ" = "そして、ゲーム開発部の仲間として――友人として。#n共に戦う道を選びました。"
"10023110-38-トキ" = "ですから……もし彼女たちに責任があると言うのなら、私も一緒に。"
"10023110-39-アリス" = "そ、そうです。ネル先輩！#nトキとアリスは仲間です。友達です！"
"10023110-40-アリス" = "友達が困っていたら、助け合うとゲームで学びました。#nなので、なので……"
"10023110-41-ネル" = "いや、だから……あたしが言いたいのはな……"
"10023110-42-ネル" = "なんだ、その……"
"10023110-43-ネル" = "よくやった、って。"
"10023110-44-ミドリ" = "えっ……？"
"10023110-45-モモイ" = "はっ！？あなたネル先輩そっくりの偽物とかじゃないよね？"
"10023110-46-ネル" = "なに言ってんだ！"
"10023110-47-ネル" = "ったく、人が褒めてやってんのによ……"
"10023110-48-ミドリ" = "えっと……本当に、許してくれるんですか……？"
"10023110-49-ネル" = "あぁん？"
"10023110-50-ネル" = "許すも何も、結果的にちゃんと解決させたんだろ。"
"10023110-51-ネル" = "ならそれで良いって。容疑者も捕まって、証拠品も揃ってるわけだしな。"
"10023110-52-ネル" = "あとは全部ヴァルキューレに渡すだけだろ？"
"10023110-53-モモイ" = "（ネル先輩……身長は小さいけど器は大きいのかも……）"
"10023110-54-ミドリ" = "（お姉ちゃん！言葉に気をつけて！聞こえたらどうするの！）"
"10023110-55-ネル" = "んで、トキ、お前も……"
"10023110-56-トキ" = "はい、どんな処分も受け入れる覚悟は出来ています。"
"10023110-57-ネル" = "だから、そうじゃねぇって……あぁ、ったくよ！"
"10023110-58-ネル" = "まず、なんでバニーガールなんだ？"
"10023110-59-トキ" = "もちろん潜入作戦だからです。"
"10023110-60-ネル" = "……はぁ。"
"10023110-61-ネル" = "だから、あん時あれほど着たくないって……"
"10023110-62-アスナ" = "ん？リーダー、あんなに似合ってたのに？"
"10023110-63-アスナ" = "あはは！トキちゃんも可愛いね！"
"10023110-64-ネル" = "ありがとう、ございます……"
"10023110-65-ネル" = "とにかく！"
"10023110-66-ネル" = "あたしが言いたいのはだな……"
"10023110-67-トキ" = "はい。自粛、謹慎、監禁、どんな内容でも受け入れますので。"
"10023110-68-ネル" = "だから！"
"10023110-69-ネル" = "あぁもう……"
"10023110-70" = "[s1] \"ネルはトキを褒めてるんだよ。\"\n[s2] \"置いてけぼりにしちゃった事、謝りたいんだよね。\""
"10023110-71-ネル" = "せ、先生！？！？"
"10023110-72-ネル" = "くそ……先生がいる事忘れてた……！"
"10023110-73-トキ" = "それは、一体どういう……？"
"10023110-74-ネル" = "あぁもう！だから！"
"10023110-75-ネル" = "……よくやったな。それと……悪かったよ。"
"10023110-76-ネル" = "だから、なんだ。その……お前を置いていきたかったわけじゃねぇから。"
"10023110-77-ネル" = "今回は急な任務で、お前一人に任せるしか無かったんだよ。#nでも、最後までやり遂げてくれたし……"
"10023110-78-ネル" = "その……お疲れさん。"
"10023110-79-ネル" = "ふふ、そういう事です、トキちゃん。#nリーダーはこういう時、素直じゃないですからね。"
"10023110-80-ネル" = "余計なこと言うんじゃねぇよ！"
"10023110-81-アスナ" = "だってさ、トキちゃん！良かったね！"
"10023110-82-トキ" = "……ありがとうございます。"
"10023110-83-モモイ" = "はぁ……疲れたぁ～#nこんだけ苦労したのに、報酬どころか依頼自体が無くなっちゃったし……無駄骨だよ。"
"10023110-84-ミドリ" = "でも、次回作のネタにはなったんじゃない？"
"10023110-85-モモイ" = "次回作……？"
"10023110-86-モモイ" = "あ～たしかに……ネタだけならたくさんね……"
"10023110-87" = "[s] \"あ、そういえば。ヴァルキューレから懸賞金が貰えるはずだよ。\""
"10023110-88-モモイ" = "え……？懸賞金って、どういう事？#nそんなの初めて聞いたよ？"
"10023110-89" = "[s3] \"私もさっき知ったんだけど、この盗品は……\"\n[s4] \"ヴァルキューレも探してたみたいで。\""
"10023110-90-アリス" = "クエスト達成報酬ですね！#nパンパカパーン！アリスたちは懸賞金を手に入れました！"
"10023110-91-モモイ" = "あっ！じゃあ、そのお金でプライステーションが――"
"10023110-92-ミドリ" = "もっと良い使い道があるよね、お姉ちゃん！？"
"10023110-93-モモイ" = "なんでぇ！私たちはゲーム開発部だよ！#nゲーム開発部がゲームに投資しないで、どこに投資するっていうの！"
"10023110-94-アリス" = "アリス、考えがあります！"
"10023110-95-アリス" = "ゲーム開発部の部長はユズです！ユズに決めてもらいましょう！"
"10023110-96-ユズ" = "……一つ考えが、ある……"
"10023110-97-モモイ" = "え？なになに？"
"10023110-98-ユズ" = "そのお金は……次回作の開発費に使うのはどうかな。"
"10023110-99-モモイ" = "次回作の開発費……？"
"10023110-100-アリス" = "……そういえばセミナーに貰った[ruby=R&D]研究開発費[/ruby]が、そろそろ底を尽きそうだね……"
"10023110-101-アリス" = "流石はユズです！"
"10023110-102-ユズ" = "わたし達が……ここで得た経験を生かせば、"
"10023110-103-ユズ" = "もっと面白い物が作れるかも……"
"10023110-104-モモイ" = "そうだね！私に良いアイデアあるよ！"
"10023110-105-モモイ" = "聞いて聞いて！えっとね――"
"10023110-106-ミドリ" = "口頭じゃなくて、ちゃんと企画書にしてよ……お姉ちゃん。"
"10023110-107-モモイ" = "そ、そんな……私は企画書が苦手なんだぞ、妹よ。"
"10023110-108-ミドリ" = "シナリオライター兼プランナーなのに、企画書が苦手でどうするの！"
"10023110-109-ユズ" = "帰ったら……すぐコーディングの準備をしないと……"
"10023110-110-ミドリ" = "待って！この溢れるアイデアを上手く形にするためにも……"
"10023110-111-ミドリ" = "とりあえずゲームしない？"
"10023110-112-モモイ" = "それはダメ！どうせ遊んでる間にアイデアがどこかに消えてしまった～とか言うでしょ！"
"10023110-113-アリス" = "アリス、いつでも準備できてます！"
"10023110-114-ユズ" = "みんな元気いっぱいだね……ふふっ……"
"10023110-115" = "（そうして、急に訪れた非日常からいつもの日常へと戻っていき――）"
"10023110-116" = "（彼女たちは楽しそうに夜更けまで遊んでいた）"
"10023110-117" = "（そうして、誰もが寝静まる頃……）"
"10023110-118" = "[ns] \"モモイ。\""
"10023110-119-モモイ" = "ん？どうしたの、先生？"
"10023110-120" = "[s] \"本当に大変だったね……\""
"10023110-121-モモイ" = "うん……"
"10023110-122-モモイ" = "一時はどうなる事かと思ったよ……"
"10023110-123-モモイ" = "でもね！"
"10023110-124" = "[s] \"ん……？\""
"10023110-125-モモイ" = "ミドリも、ユズも、アリスも！#n――それに、トキも。一緒にいてくれたから！"
"10023110-126-モモイ" = "大変だったけど、本当にすっごくすっごく楽しかったよ！"
"10023110-127-モモイ" = "先生はどうだった？"
"10023110-128" = "[s] \"うん、私も楽しかったよ。\""
"10023110-129-モモイ" = "へへっ、良かった！"
"10023110-130" = "（モモイたちゲーム開発部の笑顔は、これまで以上に輝いて見えた）"
"10023110-131" = "\"……うん、もちろん。みんな大切な生徒だよ。\""
"10023110-132-アキラ" = "……"
"10023110-133" = "\"……うん、もちろん。みんな大切な生徒だよ。\""
"10023110-134-アキラ" = "……先生。"
"10023110-135" = "\"……うん、もちろん。みんな大切な生徒だよ。\""
"10023110-136-アキラ" = "ふう……"
"10023110-137-アキラ" = "こんなにも、胸が締めつけられるなんて……この鼓動は一体……"
"10023110-138-アキラ" = "ですが苦しくは……むしろ、幸せな気持ちに。"
"10023110-139-アキラ" = "何故でしょう。先生なら、この答えを知っているのでしょうか？"
"10023110-140-アキラ" = "……"
"10023110-141-アキラ" = "私に盗めない物などありません。いつだって……大切な物は皆のために。"
"10023110-142-アキラ" = "人は生まれながらにして名を持つわけでは無い。それは、心も同様です。#n……人生とは、常に選択の連続である、と。"
"10023110-143-アキラ" = "先生、いつの日か――"
"10023110-144-アキラ" = "――この気持ちの名を、頂きに参ります。"
"10023110-145" = "白亜の予告状～一虚飾の館と美学の在り処～"
