[translation]
"1601102-1" = "成長し続ける身体"
"1601102-2" = "（ハスミからもらった場所は、トリニティの空き教室だった）"
"1601102-3" = "（遅い時間帯だからか、人影は全くない）"
"1601102-4-？？？" = "あ、お待ちしておりました先生。こちらです。"
"1601102-5-？？？" = "ちょっと待ってくださいね。#nまずはこの体操服を……着て、から……"
"1601102-6" = "[ns1] \"……ハスミ？\"\n[ns2] \"何の音……？\""
"1601102-7-ハスミ" = "す……すぐ終わります。#nあと少しなので……！"
"1601102-8" = "[ns3] \"ハ、ハスミ……！？\"\n[ns4] \"ど、どうしたの……！？\""
"1601102-9-ハスミ" = "久しぶりに着る服ですが……いけるはずです……！"
"1601102-10" = "[wa:500]― ううん……[wa:1400]うぅっ……[wa:2550]くっ……[wa:2050]ふっ……！"
"1601102-11" = "[wa:1750]― 分かってはいましたが……"
"1601102-12" = "― やはり[wa:250]難しいようですね。"
"1601102-13" = "― 先生、[wa:1200]すみません……"
"1601102-14" = "― ご覧の通り、"
"1601102-15" = "― このような状況と[wa:400]なってしまいまして……"
"1601102-16" = "[wa:1350]― そうでなくても[wa:650]お忙しいのに……"
"1601102-17" = "― 余計にお手間を[wa:750]おかけしてしまって、"
"1601102-18" = "― 申し訳ございません。"
"1601102-19" = "[wa:1250]― 去年までは[wa:450]よく着ていた服のはずなのに……"
"1601102-20" = "― どうして……[wa:1250]一年の間にこのような……。"
"1601102-21" = "[ns5] \"去年までは大丈夫だったの？\"\n[ns6] \"一年の間に何が……。\""
"1601102-22" = "[wa:950]― い、[wa:750]いえ、[wa:1150]あまり大きな違いは……。"
"1601102-23" = "[wa:950]― い、[wa:750]いえ、[wa:1150]あまり大きな違いは……。"
"1601102-24" = "― その……[wa:1700]あまり、"
"1601102-25" = "― 体重は[wa:400]変わってないはず……[wa:2100]なのですが"
"1601102-26" = "― た、[wa:1300]たぶん……。"
"1601102-27-ハスミ" = "おかしいですね……成長したとはいえ、こんな事になるなんて……。"
"1601102-28-ハスミ" = "洗濯した事で服が縮んでしまったのでしょうか……うーん……。"
"1601102-29" = "[ns7] \"それは……ないと思う、たぶん。\"\n[ns8] \"成長……とは、一体……\""
"1601102-30-ハスミ" = "な、なんだか、言い訳みたいになってしまいましたが……。"
"1601102-31-ハスミ" = "とにかく、お願いしていた作業を始めましょう。"
"1601102-32-ハスミ" = "その……このような姿で進行する事になってしまって……申し訳ございません。"
"1601102-33" = "[s9] \"ハスミが大丈夫なら……\"\n[s10] \"えっと……わ、私は大丈夫。気にしないで。\""
"1601102-34-ハスミ" = "ふふ……。"
"1601102-35-ハスミ" = "――それで、これが資料なのですが。"
"1601102-36-ハスミ" = "……先生？"
"1601102-37" = "[ns11] \"う、うん……見てるよ……。\"\n[ns12] （目のやり場がない……）"
"1601102-38-ハスミ" = "……ごめんなさい。#nやはりこの格好、気になりますよね……。"
"1601102-39-ハスミ" = "模範を示すべき正義実現委員会の副部長が、服もまともに着られないなんて……面目ありません。"
"1601102-40-ハスミ" = "やはり新調すべきでしょうか……今買い直しても遅いとも思うのですが……。"
"1601102-41" = "[s13] \"今から注文して大運動会に間に合うのかな……？\"\n[s14] \"間に合わないなら無理に買い直さなくても……？\""
"1601102-42-ハスミ" = "うーん、やはりそうですよね……。"
"1601102-43-ハスミ" = "……ああ、話が脱線して失礼しました。"
"1601102-44-ハスミ" = "作業に集中しましょう。"
"1601102-45-ハスミ" = "この件ですが……。"
"1601102-46" = "[ns] （……集中できない……）"
"1601102-47" = "（その後、ハスミと一緒に大運動会の資料に関して協議し……#n　作業が終わった後は、ハスミを部屋まで送り届けた）"
"1601102-48" = "（別れる瞬間まで、ジャージのファスナーはずっとそのままだった）"
