[translation]
"1601103-1" = "レモンのはちみつ漬け"
"1601103-2" = "（ハスミに指定されたのは家庭科室だった）"
"1601103-3-ハスミ" = "来てくださりありがとうございます、先生。"
"1601103-4" = "[ns1] \"そのジャージ……。\"\n[ns2] \"ファスナー直らなかった……？\""
"1601103-5-ハスミ" = "えっと、その……まだ新しいものが届いておらず……。"
"1601103-6-ハスミ" = "その……"
"1601103-7-ハスミ" = "気にしないでいただけますと、幸いです。"
"1601103-8-ハスミ" = "あ、これですか？"
"1601103-9-ハスミ" = "「レモンのはちみつ漬け」です。"
"1601103-10-ハスミ" = "少し多めに作ったので、もしよろしければ。"
"1601103-11-ハスミ" = "本当は明日お渡ししようと思ったのですが、大運動会当日はお忙しいでしょうし……"
"1601103-12-ハスミ" = "負担でなければ、受け取っていただけると嬉しいです。"
"1601103-13" = "[s3] \"負担なんかじゃないよ！ありがとう。\"\n[s4] \"ありがとう、いただきます。\""
"1601103-14-ハスミ" = "良かったです……"
"1601103-15-ハスミ" = "それではこちらの瓶を……"
"1601103-16-ハスミ" = "……えっ？"
"1601103-17-ハスミ" = "マネージャーとか、みんなのお姉さんみたい……ですか？"
"1601103-18-ハスミ" = "たしかに……"
"1601103-19-ハスミ" = "そういう事を少しはしていますが……。"
"1601103-20-ハスミ" = "あっ……"
"1601103-21" = "[s5] \"……ハスミ？\"\n[s6] （なんだか不吉な予感が……）"
"1601103-22-ハスミ" = "……あの……もしかして。"
"1601103-23-ハスミ" = "そう……見えるのでしょうか？"
"1601103-24-ハスミ" = "生徒というよりは保護者というか……！！"
"1601103-25-ハスミ" = "そんな風に……？"
"1601103-26" = "[s7] \"は、ハスミ、落ち着いて……！\"\n[s8] \"そういう意味じゃないよ！！\""
"1601103-27-ハスミ" = "ち、違うのですか？"
"1601103-28-ハスミ" = "すみません……慌ててしまって。"
"1601103-29-ハスミ" = "ふぅ……"
"1601103-30-ハスミ" = "先生の前で取り乱してしまうなんて……申し訳ありません。"
"1601103-31-ハスミ" = "こんな姿をお見せしたかったわけではないのですが……。"
"1601103-32-ハスミ" = "はぁ……。"
"1601103-33-ハスミ" = "……その。"
"1601103-34-ハスミ" = "そういう意味ではないとしたら……"
"1601103-35" = "[s9] \"そういう面倒見がいいところがハスミの魅力だと思うから。\"\n[s10] \"ハスミに面倒を見てもらえる生徒が羨ましいなって。\""
"1601103-36-ハスミ" = "あ、ありがとうございます……別に大したことはしていませんよ。"
"1601103-37-ハスミ" = "先生も、よろしければいつでも……"
"1601103-38-ハスミ" = "……あ。"
"1601103-39-ハスミ" = "あ、その、"
"1601103-40-ハスミ" = "別に他意があるわけではなく……"
"1601103-41" = "[s11] \"たまにはお願いしようかな？\"\n[s12] \"私はいつも歓迎だよ。ありがとう、ハスミ。\""
"1601103-42-ハスミ" = "先生……。"
"1601103-43-ハスミ" = "本当に、敵わないですね……"
"1601103-44-ハスミ" = "いつもだったら、冗談はやめてくださいと断っていましたが……"
"1601103-45-ハスミ" = "今日は、せっかくなので……"
"1601103-46-ハスミ" = "先生がそう仰ってくださったのですから、前向きに覚えておきます。"
"1601103-47-ハスミ" = "今度また、何か作ってシャーレに伺いますね。"
"1601103-48-ハスミ" = "ふふ……その時は、よろしくお願いします。"
"1601103-49" = "[s13] \"楽しみにしてるね！……普段よりちょっとテンション高い？\"\n[s14] \"制服じゃないからかな？\""
"1601103-50-ハスミ" = "そう、見えるかもしれません。"
"1601103-51-ハスミ" = "……これは格好とは関係ないお話です。"
"1601103-52-ハスミ" = "……これは先生が悪いんですよ。"
"1601103-53-ハスミ" = "とにかく、そういう事ですので。"
"1601103-54-ハスミ" = "今日はお時間をいただき、ありがとうございました。"
"1601103-55-ハスミ" = "それと……私に面倒を見る機会をくださり、ありがとうございます。"
"1601103-56" = "（その後、ハスミと一緒に、正義実現委員会の分のレモンのはちみつ漬けを瓶に詰めた）"
"1601103-57" = "（かなりの量があったものの、ハスミは作業中とても楽しそうだった）"
