[translation]
"2004103-1" = "受取代行"
"2004103-2-配達員" = "――これで最後ですよ、すごい量でしたね。"
"2004103-3" = "（リオから送られてきた荷物の量は、想像以上だった……）"
"2004103-4-配達員" = "ははっ、工房でも開かれるんですか？"
"2004103-5-配達員" = "ああ、そうでした。#nこちらにハンコをお願いします！"
"2004103-6" = "（そしてリオに言われた通り、夜まで待つことにした……）"
"2004103-7-リオ" = "こんばんは、先生。"
"2004103-8-リオ" = "先に謝っておくわ。"
"2004103-9" = "[s] \"急にどうしたの？\""
"2004103-10-リオ" = "来る途中、色々と考えたのだけれど……。"
"2004103-11-リオ" = "やはり、これは……謝罪の必要性を感じて。"
"2004103-12" = "[s] \"何があったのか分からないけど、えらい！\""
"2004103-13-リオ" = "……お、大げさね。"
"2004103-14-リオ" = "実は、追跡を避けるために……。"
"2004103-15-リオ" = "道中の防犯カメラと信号をハッキングして、痕跡を消してきたの。"
"2004103-16-リオ" = "これで私の足跡は辿れないはずだけれど……。"
"2004103-17" = "[s] \"……リオが少しずつ成長してくれると嬉しいな。\""
"2004103-18-リオ" = "……その生暖かい目は何かしら。"
"2004103-19-リオ" = "とにかく、お礼を言わせてちょうだい。料理機能搭載アバンギャルド君の改良に、アジトのコンピューターをアップグレードしたり……。"
"2004103-20-リオ" = "試薬を分析するための道具が必要になったの。"
"2004103-21-リオ" = "今回、急いで手配したのは高性能ベイパーチャンバーとICサプレッサーね。"
"2004103-22-リオ" = "最近始めた研究の分析対象となるイオン溶液が――"
"2004103-23" = "（その後も、しばらく難しい説明が続いた）"
"2004103-24" = "（……勘違いかもしれないが、語っている時のリオはどこか楽しそうに見えた）"
"2004103-25-リオ" = "……それで大規模なパーツ交換をしたかったのだけれど、#nアジトに送るわけにはいかないでしょう？"
"2004103-26-リオ" = "特定されるリスクがあるもの。"
"2004103-27" = "[s] \"だからシャーレを受取先に……。\""
"2004103-28-リオ" = "……ええ。#n面倒をかけたわね。"
"2004103-29" = "[s] \"アジトなんて持ってたんだね。\""
"2004103-30-リオ" = "もちろん、ひとつだけじゃないわ。"
"2004103-31-リオ" = "今は所有している中で、一番立地の良い場所にいるのだけれど……。"
"2004103-32-リオ" = "何かあったら、いつでも移れるように備えてるわ。"
"2004103-33-リオ" = "――AMASで。"
"2004103-34" = "[s] \"大変だね……。\""
"2004103-35-リオ" = "たしかに手間はかかるかしら。"
"2004103-36-リオ" = "でも、合理的よ。"
"2004103-37-リオ" = "……効率的には見えない、と？"
"2004103-38-リオ" = "ええ、その通りね。"
"2004103-39-リオ" = "以前、エイミに言われたわ。"
"2004103-40-リオ" = "私は合理のために、効率を捨てるタイプだと。"
"2004103-41-リオ" = "逆にエイミは、効率のために合理を捨てるタイプ。"
"2004103-42-リオ" = "これまでの私は、それらが相反する概念だと思っていなかった。#n合理性を極めることは効率性を極めることにつながる――そう考えていたわ。"
"2004103-43-リオ" = "……でも、違った。"
"2004103-44-リオ" = "常に合理的な行動を選択できるわけじゃない。#n事件の多くは、人と人の間で発生するもの。"
"2004103-45-リオ" = "かつて私は、人を信用できないのならコントロールすれば良いと考えていた……。"
"2004103-46-リオ" = "……でも、それは間違っていると気づかされたわ。"
"2004103-47-リオ" = "人は代替不能な存在だもの。"
"2004103-48" = "[s] \"代替不可能……？\""
"2004103-49-リオ" = "……そうよ。"
"2004103-50-リオ" = "最近、この概念について考える時間が増えたの。"
"2004103-51-リオ" = "人と機械の明確な違いが、そこに存在する。"
"2004103-52-AMAS A" = "部品が壊れたら、交換すれば良い。#nロジックが誤っていれば、修正すれば良い。"
"2004103-53-AMAS A" = "そうすれば、また正常に動作するのが代替可能な存在。"
"2004103-54-ヒマリ" = "でも、人は違う。#n決して替えがきかない。"
"2004103-55-ヒマリ" = "怪我をしても自然に治りはするけれど、#nそこには限界がある。"
"2004103-56-リオ" = "毎日3300億個の細胞が入れ替わり、#nおよそ1ヶ月から1年程度で全てが別のものに置き換わるとしても……。"
"2004103-57-リオ" = "脳の神経細胞のように、一生同じものもあるでしょう。"
"2004103-58-リオ" = "……貴方は「全部の部品を置き換えた船の話」を知っているかしら？"
"2004103-59" = "[s1] \"うん、知ってるよ。\"\n[s2] \"初めて聞くよ。\""
"2004103-60-リオ" = "老朽化した部品、壊れた部品があるたびに交換し――"
"2004103-61-リオ" = "全部の部品が置き換わった船は、果たして同じ存在と言えるのか、という話ね。"
"2004103-62-リオ" = "老朽化した部品、壊れた部品があるたびに交換し――"
"2004103-63-リオ" = "全部の部品が置き換わった船は、果たして同じ存在と言えるのか、という話ね。"
"2004103-64-リオ" = "私は……機械ならその船の概念を適用できると思っているわ。"
"2004103-65-リオ" = "部品を全部交換しても機能性が保たれるなら、それは以前と同じもの。"
"2004103-66-リオ" = "……けれど、人には適用できない。"
"2004103-67-リオ" = "遠い未来で、脳と神経を完全に分析し、炭素やタンパク質ベースの交換用生体部品が実現されたとしても――"
"2004103-68-リオ" = "今は、そんな思考実験すらしたくないわ。#nそもそも、不可能だもの。"
"2004103-69-リオ" = "……思考実験とは、必要な装置と条件を極度に単純化したうえで、理論上発生する現象を予測することよ。"
"2004103-70-リオ" = "思考実験には二つのパターンがあると、私は考えてるわ。"
"2004103-71-リオ" = "精巧なシミュレーションで、事実に限りなく近い結果を予測できるパターン。"
"2004103-72-リオ" = "想像と仮定の段階に留めて、予測を終了させるしかないパターン。"
"2004103-73-リオ" = "……「人の代替可能性」は、後者に当たるわ。"
"2004103-74-リオ" = "だから、考慮する必要もなければ、考慮したいとも思わない。"
"2004103-75-リオ" = "要するに……。"
"2004103-76-リオ" = "私にとって貴方は……。"
"2004103-77-リオ" = "……「代替不能」な存在ということよ。"
"2004103-78" = "[s] \"それは、どういう……？\""
"2004103-79-リオ" = "……分からなくても、構わないわ。"
"2004103-80-リオ" = "でも、いつかは……。"
"2004103-81-リオ" = "私も貴方にとって、そんな存在でありたい……。"
"2004103-82-リオ" = "……そう思っただけよ。"
"2004103-83-リオ" = "荷物の確認も終わったから、そろそろ行くわ。"
"2004103-84" = "[s] \"どうやって帰るの？\""
"2004103-85-リオ" = "行きと同じようにハッキングをして……。"
"2004103-86-リオ" = "私を追跡できないように――"
"2004103-87" = "[s3] \"却下。\"\n[s4] \"送っていくよ。\""
"2004103-88-リオ" = "えっ、でも……。"
"2004103-89" = "[s] \"たまには先生の言うことを聞きましょうね、会長。\""
"2004103-90-リオ" = "……わ、分かったわ。"
"2004103-91" = "（その後、ワゴンタクシーを呼んでリオを送った）"
"2004103-92" = "（リオはタクシーが完全に離れてから、AMASに物を運ばせた）"
"2004103-93-リオ" = "もう行くわね。#n今日はありがとう……先生。"
"2004103-94" = "[s] \"気をつけて帰ってね！\""
