[translation]
"1003506-1" = "名前も無いまま"
"1003506-2" = "（ウイに言われた通り、コンビニでエナジードリンクとガムを買い、古書館へと向かった）"
"1003506-3" = "（……何となくウイが疲れてそうな気もしたので、湿布なども買っておいた）"
"1003506-4" = "古書館内部"
"1003506-5-？？？" = "……？"
"1003506-6-？？？" = "扉が……誰か、勝手に……？"
"1003506-7" = "[s1] \"……ウイ？\"\n[s2] \"すごい疲れた声してるけど、大丈夫？\""
"1003506-8-？？？" = "……？"
"1003506-9-？？？" = "……？"
"1003506-10-ウイ" = "あ、す、すみません。先生でしたか……すみません、こんな、使い走りみたいなことを……。"
"1003506-11-ウイ" = "どうぞ、こちらへ……。"
"1003506-12" = "[wa:1600]― あ、[wa:1600]ありがとうございました、[wa:1800]先生……"
"1003506-13" = "― その、[wa:1850]助かりました……。"
"1003506-14" = "[wa:700]― ……これ、[wa:1300]ですか？"
"1003506-15" = "― えっと、[wa:2000]解読作業を[wa:1300]していまして。"
"1003506-16" = "― この古書館には……"
"1003506-17" = "[wa:100]― 昔の言葉で書かれた本が、[wa:2600]たくさんあるんです。"
"1003506-18" = "[wa:2700]― この子たちも、[wa:1800]誰かに伝えたいことを[wa:1500]抱えたまま、"
"1003506-19" = "― 待っている[wa:600]はずなので……。"
"1003506-20" = "― 他にやる人もいませんし……[wa:2700]それで、[wa:1400]私が……。"
"1003506-21" = "[wa:700]― ……すみません、[wa:1500]面白くない話……[wa:2100]でしたよね？"
"1003506-22" = "[ns3] \"ううん。素敵だし、大事なことだと思う。\"\n[ns4] \"ウイは本当にすごいね。\""
"1003506-23" = "[wa:200]― ……っ！[wa:1800]あ、[wa:1200]えっと、[wa:1300]その……"
"1003506-24" = "― そこまで褒めていただけると、[wa:2800]その……。"
"1003506-25" = "― 何と返せば良いのか……"
"1003506-26" = "[wa:500]― 言葉が、[wa:1600]見つからなくなってしまいますね……[wa:3500]ふふっ……。"
"1003506-27-ウイ" = "……何だか、変な気分です。"
"1003506-28-ウイ" = "これまで結構長い時間、こういった作業をしていましたが……そんなことを言っていただけたのは、初めてで……。"
"1003506-29-ウイ" = "それも、まさか先生から……。"
"1003506-30-ウイ" = "みんなには、「どうでも良い作業」と思われてるんじゃないかと……そう思っていました。実際、そういう人は少なくないでしょうし……。"
"1003506-31-ウイ" = "それでも良いと、思っていたんです。私は、私がやるべきことをやるだけなので……。"
"1003506-32" = "[s5] \"「どうでも良い」なんてことは無いと思うよ。\"\n[s6] \"そう信じられることもすごいし、良いことだと思う。\""
"1003506-33-ウイ" = "先生……。"
"1003506-34-ウイ" = "先生……。"
"1003506-35" = "[s7] \"それと、私にも分かったよ。\"\n[s8] \"どうしてウイが部長になったのか。みんなに支えられてるのか。\"\n[s9] \"そういうのが、ウイのすごいところだね。\""
"1003506-36-ウイ" = "うっ……。"
"1003506-37-ウイ" = "うっ……。"
"1003506-38-ウイ" = "うっ……。"
"1003506-39-ウイ" = "……。"
"1003506-40-ウイ" = "あ、ありがとうございます……。"
"1003506-41-ウイ" = "外に、先生のような人が多ければ……外に出ようと、思えたかもしれませんね。"
"1003506-42-ウイ" = "……もちろん、分かってます。外の方だって、全員が無神経で悪い人ばかりではない、と。"
"1003506-43-ウイ" = "分かっては、いるのですが……頭では分かっていても、どうにもならない。そういうことはやはり、どうしてもあるので。"
"1003506-44-ウイ" = "私の大切な部員も、外に出るように強要してくることがありますし……。"
"1003506-45-ウイ" = "大切だと思っていることと、そういう強引な部分とは別の話です。"
"1003506-46-ウイ" = "一概にそれを悪いとも思いませんが、先生は……。"
"1003506-47-ウイ" = "先生なのに……いえ、先生だからですかね。"
"1003506-48-ウイ" = "私に合わせてくれて、同じ呼び方をしてくれた……。"
"1003506-49-ウイ" = "……びっくりしたんです。こういう人がいるのか、と。"
"1003506-50-ウイ" = "それからは自然とこう、期待と言いますか……何だか気持ちがフワフワしていて。"
"1003506-51-ウイ" = "「期待」、という言葉で合っているのかも分からない、漠然とした思いなのですが……。"
"1003506-52-ウイ" = "……時が来れば、解読できるでしょう。それについてはまた、その時に。"
"1003506-53" = "[s10] \"もちろん。\"\n[s11] \"何事も、適度に気楽にね。\""
"1003506-54-ウイ" = "……ふう。"
"1003506-55-ウイ" = "……ふう。"
"1003506-56-ウイ" = "……はい、そうします。"
"1003506-57-ウイ" = "……ありがとうございます、先生。"
"1003506-58" = "（その後ウイの作業を手伝わせてもらい、解読業務を横で見ていた）"
"1003506-59" = "（作業が終わるとほぼ同時にウイは寝落ちてしまい、毛布を掛けてから静かに古書館を出た）"
