[translation]
"1601706-1" = "I hate this world (without you) "
"1601706-2" = "（アオバから連絡を受けて車両基地に到着した）"
"1601706-3-アオバ" = "あっ、ああっ……せ、先生……！"
"1601706-4-アオバ" = "ま、また来てくれた……。"
"1601706-5" = "[s1] \"アオバに頼まれたら、来ないわけにはいかないよ。\"\n[s2] \"お役に立てるよう、頑張るね。\""
"1601706-6-アオバ" = "そ、そんな……滅相もないですけど……！"
"1601706-7-アオバ" = "いらっしゃるだけで……す、救われるというか……！"
"1601706-8-アオバ" = "あ、ありがとうございます……！"
"1601706-9-アオバ" = "せ、先生がいると、心強いです……！"
"1601706-10-アオバ" = "それでは……恐縮ですけど……！"
"1601706-11-アオバ" = "今日は作業が山積みなので……よ、よろしくお願いします！"
"1601706-12" = "[s] \"もちろん！\""
"1601706-13" = "（用意した作業着に着替え、すぐにアオバの作業を手伝い始めた）"
"1601706-14" = "（何が何だか分からないまま、とりあえず言われたことを必死にこなした……）"
"1601706-15" = "（時間が経過し……）"
"1601706-16-アオバ" = "あとは……このネジを締めて……っ！"
"1601706-17-アオバ" = "お、終わりましたけど……。"
"1601706-18" = "[s] \"すごい……！やったね、アオバ！\""
"1601706-19-アオバ" = "こ、こんなに早く……！"
"1601706-20-アオバ" = "せ、先生のおかげです……！"
"1601706-21" = "[s] \"私たち、いいコンビかもね。\""
"1601706-22-アオバ" = "は、はいっ！整備に慣れてないはずなのに……大人はすごいです……！"
"1601706-23-アオバ" = "そ、そうだ……もうこんな時間……！"
"1601706-24-アオバ" = "は、早く着替えて帰りましょう……！"
"1601706-25-アオバ" = "……。"
"1601706-26-アオバ" = "（……油の匂い？）"
"1601706-27-アオバ" = "……。"
"1601706-28-アオバ" = "……あ、あれ？"
"1601706-29-アオバ" = "（ま、まさか……？）"
"1601706-30-アオバ" = "ひ、ひゃゃああぁっ……！！"
"1601706-31" = "[ns] \"あ、アオバ！？\""
"1601706-32" = "[wa:680]― [log=아오바]こ、[wa:350]来ないでほしいんです……[wa:1380]けど……！[/log]"
"1601706-33" = "[ns] \"あっ、ご、ごめん！\""
"1601706-34" = "[wa:3450]― [log=아오바]ふ、[wa:870]服に……っ！[/log]"
"1601706-35" = "― [log=아오바]油の匂いが[wa:1300]ついちゃうんで……[/log]"
"1601706-36" = "― [log=아오바]よ、[wa:610]よくないんで……！[/log]"
"1601706-37" = "― [log=아오바]す、[wa:900]すぐ脱ぐので……[/log]"
"1601706-38" = "― [log=아오바]そ、[wa:860]そこで待ってて……[wa:1650]くださいっ！[/log]"
"1601706-39" = "[ns3] \"いやいやいやっ！\"\n[ns4] \"そ、それは困るよ！いろんな意味で！\""
"1601706-40" = "[wa:1210]― [log=아오바]え？[wa:1780]一体……[wa:1310]どういう……？[/log]"
"1601706-41" = "[wa:1210]― [log=아오바]え？[wa:1780]一体……[wa:1310]どういう……？[/log]"
"1601706-42" = "[wa:2220]― [log=아오바]あっ……[wa:1800]えっと……[/log]"
"1601706-43" = "― [log=아오바]あああっ！？[wa:1270]そ、[wa:270]そのっ！[/log]"
"1601706-44" = "― [log=아오바]う、[wa:820]うわぁああああっ！[/log]"
"1601706-45" = "（慌てて宿直室を飛び出し、アオバを外で待つことにした……）"
"1601706-46-アオバ" = "……。"
"1601706-47-アオバ" = "お、お待たせしました……！"
"1601706-48-アオバ" = "油の匂い、大丈夫ですよね！？こ、これで帰れます……！"
"1601706-49" = "[s] \"うん、それじゃ行こうか。\""
"1601706-50-アオバ" = "は、はい……！"
"1601706-51-アオバ" = "退勤後の外の風は気持ちいいです……。"
"1601706-52-アオバ" = "先生……きょ、今日はありがとうございました……。"
"1601706-53" = "[s] \"いつもこんなに仕事が多いの？\""
"1601706-54-アオバ" = "はい……。"
"1601706-55-アオバ" = "このあたりで整備を引き受けているのは、うちくらいで……。"
"1601706-56-アオバ" = "しゃ、車両事故も多いし……依頼がどんどん増えています……。"
"1601706-57" = "[s] \"本当にお疲れ様、アオバ。\""
"1601706-58-アオバ" = "で、でも……不思議と最近は大変じゃなくて……。"
"1601706-59-アオバ" = "なんででしょう……。"
"1601706-60-アオバ" = "……。"
"1601706-61-アオバ" = "あ……。"
"1601706-62-アオバ" = "あ、あぁ……。"
"1601706-63-アオバ" = "へ、へへっ……。"
"1601706-64" = "[s] \"ん？何かいいことでもあったの？\""
"1601706-65-アオバ" = "あ、はひっ……！？な、なんでも……ないです……！"
"1601706-66-アオバ" = "……いいこと、といえばそうかもしれません。"
"1601706-67" = "[s] \"それならよかったよ、アオバ！\""
"1601706-68-アオバ" = "へへ……いいこと……。"
"1601706-69-アオバ" = "うん、あれは……いいこと。"
"1601706-70-アオバ" = "む、昔は……こんなこと、思いもしなかったのに……。"
"1601706-71-アオバ" = "毎晩、布団の中で一日を振り返っていたんですけど……。"
"1601706-72-アオバ" = "そのときも、明日が来なければいいのに……って思ってました。"
"1601706-73-アオバ" = "ど、どうせ……がっかりすることしか起きないから……。"
"1601706-74" = "[ns] \"……。\""
"1601706-75-アオバ" = "でも……！今は違います。"
"1601706-76-アオバ" = "ね、寝る前に……明日を期待しちゃうんです。"
"1601706-77-アオバ" = "もしかしたら、いい日になるのかも……？って。"
"1601706-78-アオバ" = "同じ日常のはずなのに……不思議ですよね……？"
"1601706-79-アオバ" = "仕事の量も減っていないんですけど……。"
"1601706-80-アオバ" = "幹部たちの無茶振りに頭を抱えているのも、同じです。でも――"
"1601706-81-アオバ" = "その……。"
"1601706-82-アオバ" = "それでも、期待で胸がいっぱいになって……明日が待ち遠しく思えるんです……。"
"1601706-83-アオバ" = "誰かがいるだけで……こ、こんなにも景色が変わるだなんて……。"
"1601706-84" = "[s5] \"本当に良かったね！\"\n[s6] \"アオバがそんな日常を送れてるなら、私も嬉しい！\""
"1601706-85-アオバ" = "えへへ……そ、そう、ですね。"
"1601706-86-アオバ" = "こ、これからもずっと……こ、こんな日が……。"
"1601706-87-アオバ" = "続くといいんですけど……。"
