[translation]
"1013505-1" = "クエスト"
"1013505-2" = "（急いでミレニアムに向かった）"
"1013505-3-ミレニアムの生徒A" = "つーかまえたっ！"
"1013505-4-ケイ" = "は、離して……！"
"1013505-5-ミレニアムの生徒B" = "ケイちゃん、私たちのこと嫌い？"
"1013505-6-ケイ" = "それとこれとは違うんです……！"
"1013505-7-ミレニアムの生徒A" = "あっ、照れてるんでしょー？やっぱりアリスとはちょっと違うね！"
"1013505-8-ケイ" = "（なんでアリスはアリスで私はケイ[ruby=・   ・   ・]ちゃん[/ruby]なのか、とても気になります）"
"1013505-9" = "[ns1] \"あれ？緊急事態かと思ったのに……。\"\n[ns2] \"みんなの仲が良いのは素敵なことだよね！\""
"1013505-10-ケイ" = "先生！ちょうどいいところに！#nぜひ教師として、助けを求める生徒を――"
"1013505-11-ミレニアムの生徒A" = "あっ、先生！こんにちは！"
"1013505-12-ミレニアムの生徒B" = "先生も混ざりますか？"
"1013505-13" = "[s] \"私は横で見守らせてもらうよ。\""
"1013505-14-ケイ" = "はいぃ！？"
"1013505-15-ケイ" = "……。"
"1013505-16-ケイ" = "こんな大人を信じた私のバカ――！！"
"1013505-17-ミレニアムの生徒A" = "そういえばケイちゃんってアリスの双子の妹なんだよね？"
"1013505-18-ケイ" = "えっ？ああ、はい……そんなところです……。"
"1013505-19-ミレニアムの生徒B" = "でも髪の色が全然違うよね？色が反対というか。"
"1013505-20-ミレニアムの生徒A" = "あっ、言われてみれば！"
"1013505-21-ケイ" = "あ……はは……そういうこともある……んじゃないですかね……。"
"1013505-22-ミレニアムの生徒A" = "そっかそっか。#nそれじゃあ……今日のクエストをお願いしたいと思いまーす！"
"1013505-23-ケイ" = "また、ですか……。"
"1013505-24-ミレニアムの生徒B" = "あっ、嫌だった……？"
"1013505-25-ミレニアムの生徒A" = "えっ、嫌なわけじゃ……！"
"1013505-26-ケイ" = "……。"
"1013505-27-ケイ" = "……嫌じゃ、ないです。"
"1013505-28-ケイ" = "なんというか、その、慣れないというか……ちょっと恥ずかしいというか……。"
"1013505-29-ミレニアムの生徒A" = "きゃぁああ！"
"1013505-30-ケイ" = "イヤな予感――！"
"1013505-31-ミレニアムの生徒A" = "ケイちゃんっ、か～わ～い～い～～！！！"
"1013505-32" = "[ns] \"かわいい～～～！！！\""
"1013505-33-ケイ" = "なんであなたまで！！！"
"1013505-34-ミレニアムの生徒A" = "すー、はー、ふぅ……それでなんだけどね。#nこれ、隣の棟の講義室に持っていってほしいんだ。"
"1013505-35-ケイ" = "ああ、はい……いわゆるお届け物クエストですね……。"
"1013505-36-ミレニアムの生徒B" = "うん。あと今回は報酬先払いだよ。#nはいこれ、ネックレス。"
"1013505-37-ケイ" = "……！"
"1013505-38-ミレニアムの生徒A" = "綺麗……ですね。 "
"1013505-39-ケイ" = "青みがかったクロムメッキと、黄色の混じった宝石……派手すぎない装飾です。"
"1013505-40-ケイ" = "ですがこんなに高級そうなもの……いいのですか？"
"1013505-41-ミレニアムの生徒B" = "いいのいいの。[ruby=うち]新素材開発部[/ruby]のあり合わせで作ったやつだから。"
"1013505-42-ミレニアムの生徒B" = "その宝石も人工のダイヤモンドで、成分的にはただの炭素だし。"
"1013505-43-ケイ" = "なるほど……たしかに近頃は人工物の方が優れていますからね。"
"1013505-44-ミレニアムの生徒B" = "それじゃあお届け物よろしくね！"
"1013505-45-ミレニアムの生徒B" = "クエストが欲しい時はいつでも言ってね！"
"1013505-46-ケイ" = "いえ……今日はもう十分かなと。"
"1013505-47-ケイ" = "……はぁ。"
"1013505-48-ケイ" = "先生はいつまでそんなことをしてるつもりなんですか……。"
"1013505-49" = "[s] \"ふふふ～\""
"1013505-50-ケイ" = "なんですか。"
"1013505-51" = "[s] \"いいもの見ちゃったな～って。\""
"1013505-52-ケイ" = "どうしていつもいつもこんなタイミングで！！"
"1013505-53-ケイ" = "本当にもう……なんでみなさん、私にばかり――"
"1013505-54-ケイ" = "――待ってください。いま先生が何を言おうとしているかは全部分かってますから。#n私を大事に思ってるだとか、可愛がっているだけだとか、そんなところですよね？"
"1013505-55-ケイ" = "……先読みされたからって落ち込まないでください。#n大人なんですから……。"
"1013505-56" = "[s] \"……学園はどう？\""
"1013505-57-ケイ" = "……。"
"1013505-58-ケイ" = "まあ悪くありません。"
"1013505-59" = "[s] \"そっか、気に入ってるんだね。\""
"1013505-60-ケイ" = "話聞いてましたか！？勝手に意訳しないでください！"
"1013505-61-ケイ" = "はぁ……。"
"1013505-62-ケイ" = "とにかく。私はクエスト中なので、今はあまり構わないでください。"
"1013505-63-ケイ" = "ん……？だから[ruby=・]ク[/ruby][ruby=・]エ[/ruby][ruby=・]ス[/ruby][ruby=・]ト[/ruby]中だって……。"
"1013505-64-ケイ" = "……！！！"
"1013505-65-ケイ" = "お、おつかいです！ただのおつかい！"
"1013505-66-ケイ" = "あー！またそうやって微笑んで！なんなんですかあなたは！"
"1013505-67" = "[s] \"まだ何もしてないよぉ！\""
"1013505-68-ケイ" = "じゃあこれから禁止です！"
"1013505-69" = "[s] \"表情の自由を要求する！！\""
"1013505-70-ケイ" = "先生は例外です！"
"1013505-71-ケイ" = "あっ、ケイだ。なんか楽しそうだね？"
"1013505-72-ケイ" = "楽しくないです！#nそれより、ちょうどよかったです。これを届けてほしいとクエス――お願いされて。"
"1013505-73-ミレニアムの生徒C" = "どれどれ……ああ、やっと実験の結果が出たんだね。"
"1013505-74-ケイ" = "そういったものはインターネットで送受信したほうが効率的なのでは？"
"1013505-75-ミレニアムの生徒C" = "これに限っては難しいかな。"
"1013505-76-ケイ" = "なぜですか？"
"1013505-77-ミレニアムの生徒C" = "セキュリティ上ちょっとね。これも一応は機密情報だから。"
"1013505-78-ミレニアムの生徒C" = "インターネットの致命的な短所は、セキュリティの脆弱性と保管期限にあるっ！"
"1013505-79-ケイ" = "たしかに。未だに磁気テープが廃れない理由でもありますね。"
"1013505-80-ミレニアムの生徒C" = "まぁ、もっと確実な方法が出てきてくれるのが一番ではあるんだけどね。#n使えるものは使っていかないと。"
"1013505-81-ミレニアムの生徒C" = "……よし、それじゃあクエストクリアを祝して一緒にゲーセン行かない？"
"1013505-82-ケイ" = "え、えっと……？"
"1013505-83-ミレニアムの生徒C" = "あれ？前は楽しそうにしてたよね？"
"1013505-84-ケイ" = "ま、前はそうですが……！いや、その……。"
"1013505-85" = "[s] \"あっ、ケイちゃんもゲーム好きなんだ？\""
"1013505-86-ミレニアムの生徒C" = "そうなんですよ！先生も見たらビックリしますよ？"
"1013505-87-ケイ" = "ちがっ……！いや、だからあれは……！"
"1013505-88-ミレニアムの生徒C" = "あれ……じゃああの時は仕方なく付き合ってくれてた感じ……？"
"1013505-89-ケイ" = "そ、それも違います！"
"1013505-90" = "[ns] \"ふふっ、素直じゃないなぁ。\""
"1013505-91-ケイ" = "っ……この……。"
"1013505-92-ケイ" = "この白々しい大人が！！！！"
