[translation]
"2003203-1" = "ファッション実践編"
"2003203-2-エイミ" = "あ、先生、こっち。"
"2003203-3-エイミ" = "早速、お店に入ろう。"
"2003203-4" = "[s] \"あ、うん……水着ね……\""
"2003203-5" = "水着の販売店"
"2003203-6-エイミ" = "ん……"
"2003203-7-エイミ" = "やっぱり、どれが良いのか分からない。#n順番に試着するから、先生が選んでくれる？"
"2003203-8-エイミ" = "……今回は更衣室の外で着替えないで、って？"
"2003203-9-エイミ" = "でも……更衣室の中は狭くて苦手。"
"2003203-10-エイミ" = "それに何回も着替えるし、更衣室まで往復するよりもその場で着替えた方が効率的。"
"2003203-11" = "[s1] \"それはダメ！！\"\n[s2] \"私が取りに行くから！！\""
"2003203-12" = "（更衣室のカーテンを開けたまま着替えようとするエイミを止めるところから、水着選びが始まった）"
"2003203-13-エイミ" = "先生、ちゃんとこっち見て返事して。"
"2003203-14-エイミ" = "ほら、これとかどう？"
"2003203-15-エイミ" = "じゃあ……これは？"
"2003203-16-エイミ" = "あ、それならこっちは？"
"2003203-17-エイミ" = "……今度はそっち？"
"2003203-18-エイミ" = "あれ、持ってきた覚えが無いのも混ざってる。"
"2003203-19-エイミ" = "牛柄の水着……？#nファッションはよく分からないけど、これを選ぶ人は流石に居ないんじゃないかな。"
"2003203-20" = "（その後も、様々な水着を試着し……）"
"2003203-21" = "（そこから気に入った物を購入した）"
"2003203-22-エイミ" = "先生のおかげで可愛い水着が買えた。ありがとう。"
"2003203-23-エイミ" = "氷海用の水着は、これでバッチリ。"
"2003203-24-エイミ" = "今回の作戦も、うまくいきそうだね。"
"2003203-25" = "[ns3] \"今回の作戦……？\"\n[ns4] \"まさか、その水着で行くつもり……？\""
"2003203-26-エイミ" = "そのつもりだよ？"
"2003203-27-エイミ" = "海と言えば水着だから。"
"2003203-28" = "[s] \"そ、そうかもしれないけど……\""
"2003203-29-エイミ" = "だから先生もちゃんと用意してきてね、水着。"
"2003203-30" = "[ns] \"って、大丈夫じゃないでしょ！！！\""
"2003203-31-エイミ" = "先生？"
"2003203-32-エイミ" = "このままじゃ帰せない……？#nいや、まだ帰る気は……"
"2003203-33-エイミ" = "先生、どこ行くの？"
"2003203-34-エイミ" = "ここは……アウトドアウェア用品店……？"
"2003203-35" = "[s5] \"ちょっと待ってて。\"\n[s6] エイミに必要な物を選ぶ。"
"2003203-36-エイミ" = "先生、重いよ……"
"2003203-37-エイミ" = "ダウンジャケットにマフラー……スキー用のパンツ、ブーツ、ニット帽……防寒、対策……？"
"2003203-38-エイミ" = "たしかに可愛いけど……暑そう。#n私、別に寒がりじゃないし大丈夫だよ。"
"2003203-39" = "[s7] \"ダメです！必ず着てください！！\"\n[s8] \"先生との約束！！\""
"2003203-40-エイミ" = "念のため試着した方がいい……？"
"2003203-41-エイミ" = "……うん、分かった。"
"2003203-42-エイミ" = "……そんな目で見ないで。#nちゃんと更衣室で着替えてくるから。"
"2003203-43-エイミ" = "先生、着替えたよ。"
"2003203-44" = "[ns] \"えっと、さっきの服は……？\""
"2003203-45-エイミ" = "ロングパンツまで履いたら、水着じゃないよ。"
"2003203-46" = "[s9] \"水着かどうかってそこじゃなくない！？\"\n[s10] \"まぁ……さっきよりは……\""
"2003203-47-エイミ" = "うん。"
"2003203-48-エイミ" = "ありがとう、先生。"
"2003203-49" = "（買い物を終え、カフェで雑談をしてからシャーレに戻った）"
