[translation]
"10032020-1" = "第2話;よりハードボイルドに"
"10032020-2-アル" = "……ギャング連合のトップ「ドン・アランチーノ」をさらってほしい……？"
"10032020-3-連絡係" = "ああ、その通りだ。"
"10032020-4-連絡係" = "しっかり説明してくれないと。#n自ら「アランチーノ・ファミリー」の一員だと言っておきながら……"
"10032020-5-カヨコ" = "自分たちのボスをさらってほしいなんて……納得いかないね。"
"10032020-6-連絡係" = "理解できないのも当然だな。"
"10032020-7-カヨコ" = "けど、これも組織のため。"
"10032020-8-カヨコ" = "……ボスは暴走している。このままでは、組織が終りを迎えてしまう。"
"10032020-9-カヨコ" = "つまり、その前にボスを止めてほしいってこと？#n結構な規模の作戦になるけど、そっちも分かってるよね？"
"10032020-10-連絡係" = "……もちろんだ。危険性も難易度も相当だとは思う。#nだが安心してほしい、相応の額は用意している。"
"10032020-11-カヨコ" = "単に、お金の問題じゃ……"
"10032020-12-アル" = "問題ないわ！それなら、我々便利屋68が適任ね。"
"10032020-13-連絡係" = "……社長！？"
"10032020-14-連絡係" = "……！？"
"10032020-15-アル" = "危険な依頼ってことは、ハードボイルドじゃない？"
"10032020-16-アル" = "ふふふ……うちにピッタリな仕事ね。#nその依頼、私たちに任せてちょうだい。"
"10032020-17-ムツキ" = "くふふ。アルちゃん、テンション上がってるね～"
"10032020-18-カヨコ" = "……。"
"10032020-19-カヨコ" = "……はぁ。"
"10032020-20-連絡係" = "ははっ、ここまで快く引き受けてくれるとは……"
"10032020-21-連絡係" = "一瞬も躊躇わないその姿勢、噂は本当のようだな……便利屋68。"
"10032020-22-連絡係" = "この件がうまくいったら、前金の4倍を支払おう。"
"10032020-23-連絡係" = "……期待していいんだろうな？"
"10032020-24-アル" = "……疑っているのかしら？私たちの実力を。"
"10032020-25-連絡係" = "まさか。気を悪くしたのなら悪かった……私の悪癖でな。#n組織に身を置いてから長いと、つい用心深くなるものだ。"
"10032020-26-連絡係" = "……ドン・アランチーノは用心深く、何重にも策を弄するのが常。#nくれぐれも気をつけてくれ。"
"10032020-27-アル" = "ふふふ……"
"10032020-28-アル" = "全ての策を上回れば良いだけでしょう？"
"10032020-29-連絡係" = "それを聞けて良かった。では、日程が決まったら詳細な情報を共有しよう。"
"10032020-30-連絡係" = "建物の間取りや参加者のリストも全て準備しておく。"
"10032020-31-連絡係" = "……では、また連絡する。"
"10032020-32-アル" = "……あの、社長？"
"10032020-33-アル" = "あ、アル様……？"
"10032020-34-アル" = "……どうしたのよ、みんな。"
"10032020-35-カヨコ" = "念のため聞くけど……「アランチーノ・ファミリー」って、どういう連中か知ってる？"
"10032020-36-アル" = "……さ、さあ？名前からしてギャングよね？"
"10032020-37-カヨコ" = "ま、まあ……合ってはいるけど……"
"10032020-38-アル" = "……！？"
"10032020-39-アル" = "なななな、なっ、何ですってーーーーーー！！！？？？"
"10032020-40-アル" = "ほ、ほ、本当！？れ、連合のトップだなんて……ただのギャングじゃなくて！？"
"10032020-41-アル" = "と、というか……どうしてそんな巨大組織が私たちの事務所の位置を……！？"
"10032020-42-カヨコ" = "……そもそも隠してないでしょ、広告まで出してるんだし。"
"10032020-43-カヨコ" = "それより、ちょっと意外だね。#n社長が裏世界の人と会うのは、よくあることなのに……"
"10032020-44-ムツキ" = "アルちゃん……もしかして怖気づいちゃった？"
"10032020-45-アル" = "お、怖気づいてなんかいないわよ！ち、ちょっと緊張しただけ！#nそれに巨大組織ってことは、報酬がたんまり入ってくるに違いないわ！"
"10032020-46-アル" = "依頼の内容もハードボイルドだし、これなら……！"
"10032020-47-ムツキ" = "くふふ。アルちゃん、ほんと思った通りの反応で面白い～"
"10032020-48-カヨコ" = "……本当にいいの？"
"10032020-49-カヨコ" = "私が言うのもアレだけど……今回の依頼、結構大変だと思うよ。"
"10032020-50" = "大変だからこそ、請けるに決まってるでしょう！#n猫探しや街の不良を相手にする依頼なんて、いつまでもやってらんないのよ！"
"10032020-51-ムツキ" = "ん？私は別に猫探しでもいいけど？"
"10032020-52-ハルカ" = "わ、私も……！アル様と一緒なら、野宿したって構いません……！！"
"10032020-53-アル" = "わあああっ！その話は持ち出さないで！！#nそれに野宿なんて滅多に無かったじゃない！"
"10032020-54-アル" = "とにかく、これは我々便利屋68の名を知らしめる絶好のチャンスなの！"
"10032020-55-アル" = "みんな、よく聞きなさい。この依頼、絶対に成功させるわよ！"
"10032020-56-アル" = "そうして裏世界で名を轟かせ……極悪非道のハードボイルドになるのよ！"
"10032020-57-アル" = "もっと、もっと……！"
"10032020-58-アル" = "よりハードボイルドに……！！"
"10032020-59-アル" = "……ていうのが、今までの話。"
"10032020-60-ムツキ" = "それで、まずオペラハウスの中を捜索して、ボスの取り巻きを倒してたところ！"
"10032020-61-カヨコ" = "私も一応調べてみたけど……あの話は本当みたい。"
"10032020-62-カヨコ" = "ギャング連合のボスが勢力を伸ばすために、悪巧みを目論んでいるのは事実だし……"
"10032020-63-カヨコ" = "だからこれはある意味、みんなのためって言っていいと思う。"
"10032020-64-カヨコ" = "まあ、言い訳なのは否定しないけど、先生が思うような悪事に手を染めてるわけじゃないから。"
"10032020-65-アル" = "……はっ！"
"10032020-66-アル" = "み、みんなのためになるとか、そんなの関係ないわ！偶然よ！#n私たちは、ただお金を受け取って仕事をする、それだけ！"
"10032020-67-ハルカ" = "そ、その通りです！これはアル様が決定したことなんです！"
"10032020-68-カヨコ" = "……はぁ。"
"10032020-69" = "[ns1] \"ギャングのボスをさらう仕事……\"\n[ns2] \"たしかに、今回の依頼は「ハードボイルド」だね。\""
"10032020-70-アル" = "ふふふ……やっぱり、先生もそう思うわよね？"
"10032020-71-アル" = "ついに我々便利屋68に相応しい仕事が来たのよ！#nだからこうして、みんなで特別な衣装まで用意したわけ。"
"10032020-72-アル" = "もちろん、あらかじめ先生に言ってなかったのは……悪いと思ってるわ。"
"10032020-73-アル" = "でも先生……どうか、このまま依頼を続けさせてほしい。"
"10032020-74-アル" = "……え？本当にいいの？"
"10032020-75-アル" = "そ、そんなあっさり許しちゃって大丈夫？"
"10032020-76-カヨコ" = "社長が聞き返してどうするのよ。"
"10032020-77-ムツキ" = "あはははは！！アルちゃんテンパってる～"
"10032020-78-アル" = "で、でも……ええ、本当に……？"
"10032020-79-アル" = "……どうして？"
"10032020-80" = "[s3] \"今日は指導するために来たわけじゃないからね。\"\n[s4] \"それに、みんなのことは信じてるから。\""
"10032020-81-アル" = "……先生。"
"10032020-82-アル" = "ふふ、ふふふ……"
"10032020-83-アル" = "先生なら分かってくれると思ったわ。#n私たちが歩む、ハードボイルドの道を……"
"10032020-84-アル" = "やはり、私の目に狂いは無かったわけね……ふふふっ。"
"10032020-85-ムツキ" = "さっきまで不安がってたのにね～"
"10032020-86-ムツキ" = "……いいわ。その代わり、私たちも先生を全力でサポートしなくちゃね。"
"10032020-87-ムツキ" = "先生の「オペラ調査」……"
"10032020-88-アル" = "この便利屋68の社長が、責任を持って引き受けたわ。"
"10032020-89-アル" = "あ、もちろんギャングのボスが姿を現すまでね。#nその後は、仕事にかからせてもらうわ。"
"10032020-90-アル" = "じゃあ、潜入してる奴らを捜し出すのは？"
"10032020-91-アル" = "同時に行なえばいいのよ！#nどの道、オペラハウスを回るのは同じなんだし。"
"10032020-92-ムツキ" = "へえ～スパイみたいな？#nじゃあ、私もまたドレスに着替えちゃおうかな～"
"10032020-93-ハルカ" = "ど、ドレス……？ま、まさか私もですか……？"
"10032020-94-ハルカ" = "あ、いえ！決して嫌ってわけじゃありませんが、その……私なんかが着てもいいのか……"
"10032020-95-ハルカ" = "で、でも私だけドレスを着ずに浮いたら、みんなに迷惑を……"
"10032020-96-ハルカ" = "す、すぐ着替えてきます……！！"
"10032020-97-ムツキ" = "くふふ。ちょ～っと待っててね、先生！"
"10032020-98-カヨコ" = "……うーん。"
"10032020-99-カヨコ" = "……先生。"
"10032020-100-カヨコ" = "これ、受け取って。"
"10032020-101" = "[s5] \"……トランシーバー？\"\n[s6] \"やっぱり私も手伝った方がいいのかな……？\""
"10032020-102-カヨコ" = "予備を持ってきておいて良かった。"
"10032020-103-カヨコ" = "別にグルになれって言いたいわけじゃないよ。ただ、身の安全のため。"
"10032020-104-カヨコ" = "大事になるとは思わないけど……一応ね。ギャングもいっぱい居るし。"
"10032020-105-カヨコ" = "私としては……先生に帰ってもらいたいところだけど。"
"10032020-106-カヨコ" = "……まあ、そう言ったところで聞かないよね。"
"10032020-107" = "[s7] \"うん。生徒を残して帰るわけにはいかないから。\"\n[s8] \"心配してるのは、お互い様だね。\""
"10032020-108-カヨコ" = "はぁ……"
"10032020-109-カヨコ" = "……分かってる。だからこそ、渡しておこうと思ったの。"
"10032020-110-カヨコ" = "気を付けて、先生。まだ何も起きてないけど……"
"10032020-111-カヨコ" = "こういう時に油断してると、良くないことが起きるんだから。"
"10032020-112-カヨコ" = "……何か心当たりはあるかって？"
"10032020-113-カヨコ" = "いや、今のところは特に。あったら有無を言わさず帰ってもらってた。"
"10032020-114-カヨコ" = "これは何というか、今までの経験によるもの……かな。"
"10032020-115-カヨコ" = "……まあ、勘みたいなものね。"
