[translation]
"10032015-1-ハルカ" = "はぁ、はぁ……はぁ、はぁ……！"
"10032015-2-ハルカ" = "すっごーい、ほんとに一瞬で終わったじゃん。"
"10032015-3-ムツキ" = "やっぱり先生のおかげだね～このままうまく収まってくれたらいいんだけど。"
"10032015-4-カヨコ" = "収まるわけないじゃん……"
"10032015-5-カヨコ" = "1回勝った程度で、収拾がつくわけない。"
"10032015-6-カヨコ" = "……それに、大変なのはこれから。"
"10032015-7-カヨコ" = "……でしょ、先生？"
"10032015-8" = "[s1] \"……そうだね。\"\n[s2] \"簡単に話を聞かせてもらえる？\""
"10032015-9-ムツキ" = "わっ……先生、ちょっと怖くない？もしかして、反省会でも始まる感じ？"
"10032015-10-ハルカ" = "すみませんすみませんすみませんすみませんすみません……"
"10032015-11-カヨコ" = "……どうする、社長？何か言い訳でもする？"
"10032015-12-カヨコ" = "私が代わりに何か言おうか？"
"10032015-13-アル" = "……いいえ。"
"10032015-14-アル" = "その言い方は間違ってるわ、カヨコ。"
"10032015-15-アル" = "……「言い訳」する必要なんて無いもの。"
"10032015-16-アル" = "これは便利屋が引き受けた正式な依頼よ。"
"10032015-17-アル" = "だから、言い訳も反省会も不要。"
"10032015-18-アル" = "……でも。"
"10032015-19-アル" = "経営顧問を困らせたうえに、サポートまでさせたのは私たちのミスね。#nこれに関しては、謝らせてちょうだい……社長として。"
"10032015-20-アル" = "先生は、私たちと協力関係にあるのだから……"
"10032015-21-アル" = "お詫びに、先生が気にしていた私たちがここに居る理由を教えてあげる。"
"10032015-22-アル" = "けど、これを聞いたら先生も後戻りはできない。"
"10032015-23-アル" = "……覚悟はいいかしら、先生？"
"10032015-24" = "[s3] \"覚悟ならできてるよ。\"\n[s4] \"詳しく教えてもらえるかな。\""
"10032015-25-アル" = "……ふぅ。"
"10032015-26-アル" = "分かったわ……じゃあ、しっかり聞いてちょうだい。"
"10032015-27-アル" = "この依頼は……裏世界の大物から請け負ったのよ。"
"10032015-28-アル" = "そう……まさに私たち便利屋68にしかできない仕事。"
"10032015-29-アル" = "今回の依頼を通じて、私たちは……"
"10032015-30-アル" = "……よりハードボイルドになるの。"
