[translation]
"10032005-1" = "プロローグ"
"10032005-2" = "[i]Blue Archive presents[/i]"
"10032005-3" = "[i]Problem Solver 68 Event[/i]"
"10032005-4" = "Aru Rikuhachima"
"10032005-5" = "Kayoko Onikata"
"10032005-6" = "Mutsuki Asagi"
"10032005-7" = "Haruka Igusa"
"10032005-8" = "and……"
"10032005-9-？？？" = "こ、これで……いいんでしょうか……？"
"10032005-10-？？？" = "仰っていた通り……気絶させて縛っておきました……"
"10032005-11-ムツキ" = "いや～ハルカちゃん、容赦ないね～！"
"10032005-12-ハルカ" = "へへっ……ありがとうございます。#nみんなの役に立てて、嬉しいです……"
"10032005-13-ハルカ" = "と、ところで、この人たちはどう処理すれば……"
"10032005-14-ハルカ" = "このまま放っておくのは……流石にマズいですよね？#nどこかに隠しておきましょうか？"
"10032005-15-ハルカ" = "い、いや！それだと気づかれた時さらに面倒なことに……#n近くの廃工場にでも捨ててきたほうが……"
"10032005-16-ハルカ" = "そ、それも見つかる可能性が……やっぱり、海に沈めた方が……！！"
"10032005-17-アル" = "ふふふ……落ち着きなさい、ハルカ。目的を忘れちゃダメよ。"
"10032005-18-アル" = "まだこれは、ターゲットを確保するための前段階。"
"10032005-19-ムツキ" = "先に潜入してた護衛を始末するんだよね？"
"10032005-20-アル" = "ええ。でも、雑魚どもにかまけている時間なんて無いわ。#nもうじき……"
"10032005-21-アル" = "ターゲットが到着するもの。"
"10032005-22-アル" = "……ついに我々便利屋68の名に相応しい依頼が来たのよ！"
"10032005-23-ムツキ" = "くふふ。久しぶりの大仕事で、アルちゃん浮かれすぎじゃない～？"
"10032005-24-アル" = "ち、違うわよ！#nそれに仕事中は社長でしょう、ムツキ室長！"
"10032005-25-アル" = "それと、これは私たち便利屋68が認められた証拠……#nこれからもどんどん依頼が舞い込んでくるわ。"
"10032005-26-ハルカ" = "今回のターゲットは、ギャング連合のボス「ドン・アランチーノ」でしたよね……？"
"10032005-27-ハルカ" = "すごく悪い人だと聞きましたけど……"
"10032005-28-ムツキ" = "たしかに、いつもの「猫探し」とか「友達の尾行」とかと比べたら、#n雰囲気も違うしね～？"
"10032005-29-アル" = "そ、その話はもういいわよ！"
"10032005-30-アル" = "今度こそ依頼を成功させて、ハードボイルドな便利屋の名を世に知らしめるんだから……！"
"10032005-31-カヨコ" = "……社長。"
"10032005-32-アル" = "ん？カヨコ、どうしたの？"
"10032005-33-アル" = "潜入中は、不必要な通信を避けるよう言ってお……"
"10032005-34-カヨコ" = "ああ、それが……急ぎの報告があってね。"
"10032005-35-アル" = "今、このオペラハウスに……"
"10032005-36-アル" = "先生が来てるの。"
"10032005-37-カヨコ" = "予想外の出来事だし……"
"10032005-38-カヨコ" = "ひとまず移動した方がいいんじゃない？"
"10032005-39-カヨコ" = "…………。"
"10032005-40-カヨコ" = "…………社長？"
"10032005-41-アル" = "………………え。"
"10032005-42-アル" = "…………誰が、来たって？"
"10032005-43" = "#video;10032"
