[translation]
"80000099-1" = "温泉卵？"
"80000099-2" = "（メグに呼び出された場所は、繁華街から離れた路地だった）"
"80000099-3-？？？" = "ふふん。待ってたよ～先生！"
"80000099-4" = "[s1] \"メグ？\"\n[s2] \"こんな所で何してるの？\""
"80000099-5-メグ" = "ふっふ～ん！聞いて驚かないでよ！"
"80000099-6-メグ" = "今日はね、と～っても特別な日なんだよ！"
"80000099-7-メグ" = "まぁ、先生なら知ってそうだけど！私と違って賢いし！"
"80000099-8-メグ" = "とにかく、普段から先生には助けてもらってるから、何かお返しがしたかったの！"
"80000099-9-メグ" = "でも、私にできることって温泉作りくらいだから……"
"80000099-10-メグ" = "割ったり、掘ったり、削ったり……そういう事ばかりで……"
"80000099-11-メグ" = "あ、もちろん建設もできるけど、それは置いといて！"
"80000099-12-メグ" = "それで悩んだんだけど、自分にできる範囲でやろうかなって！"
"80000099-13-メグ" = "というわけで！はい！これ！"
"80000099-14-メグ" = "んん～っ！！"
"80000099-15" = "[ns3] \"これは温泉卵……？\"\n[ns4] \"燻製卵……なのかな？\""
"80000099-16-メグ" = "さあ、どうかな～？"
"80000099-17-メグ" = "それは割ってみるまでのお楽しみ！"
"80000099-18-メグ" = "まぁ、といっても、私に作れそうなのって、温泉卵くらいなんだよね。"
"80000099-19-メグ" = "でも、これはちょ～っと違うよ？卵よりも甘いはず！"
"80000099-20-メグ" = "それじゃあ先生！早く剥いてみて！#nちゃんとできてるのか、私も確認してみたいし！"
"80000099-21-メグ" = "うう～、私もワクワクしてきた！"
"80000099-22" = "[ns] もらった卵を剥いてみる。"
"80000099-23" = "[ns5] \"中にチョコレートが……！\"\n[ns6] \"卵じゃなかったんだ！？\""
"80000099-24-メグ" = "じゃーーーーん！！！"
"80000099-25-メグ" = "温泉卵ならぬ、温泉チョコレートでした～！！！"
"80000099-26-メグ" = "わ～い！パチパチパチ～！！"
"80000099-27-メグ" = "先生先生！食べて食べて！"
"80000099-28-メグ" = "はやくはやく～！"
"80000099-29" = "[ns7] \"おお、本当にチョコレートだ。\"\n[ns8] \"これ、すごく美味しいね。\""
"80000099-30-メグ" = "……！"
"80000099-31-メグ" = "……！！！！"
"80000099-32-メグ" = "おおおおおおおおー！！大成功～！！！"
"80000099-33-メグ" = "えへへ……正直、美味しくなかったらどうしようって心配だったんだけど#n……うまくいって良かった。"
"80000099-34-メグ" = "……ん？自分で食べてみなかったのかって？"
"80000099-35-メグ" = "うん、それしか作ってないからね。"
"80000099-36-メグ" = "……あ。"
"80000099-37-メグ" = "……！たしかに！試作品を作れば良かったんだ！"
"80000099-38-メグ" = "やっぱり先生は賢いね！！……えへへっ。"
"80000099-39-メグ" = "さて、と……"
"80000099-40-メグ" = "……もう1個作って、今度は私も食べてみよ！"
"80000099-41" = "（その後、メグと一緒に大量の「温泉卵チョコレート」を作った）"
"80000099-42" = "（……シャーレの冷蔵庫が、メグのチョコレートで埋め尽くされるほど）"
