[translation]
"80000095-1" = "真相は如何に"
"80000095-2" = "（カスミから連絡をもらい、人通りの少ない場所で待ち合わせをすることになった）"
"80000095-3" = "（しばらくすると、遠くから手を振りながらゆったり歩いてくるカスミの姿が見えた）"
"80000095-4-カスミ" = "おお～、先生！早いな！"
"80000095-5-カスミ" = "ハーハッハッハッハ！悪い悪い、待たせてしまったようだな。#n本来なら私が先に待っている予定だったのだが……"
"80000095-6-カスミ" = "知っての通り、私は人気者でね。#n追いかけてくる奴らを撒いていたら時間がかかってしまった。"
"80000095-7-カスミ" = "ここを選んだのも、そういう理由でな。"
"80000095-8-カスミ" = "……ん？#n何の用事かって？"
"80000095-9-カスミ" = "おいおい、とぼけないでくれよ？#n私でさえ今日が何の日か知ってるくらいなのに。"
"80000095-10-カスミ" = "年に一度のバレンタインデーなんだぞ？"
"80000095-11-カスミ" = "それとも……私にチョコレートをもらったところで嬉しくなかったか？"
"80000095-12-カスミ" = "そうだったのなら謝らなくてはな。#n先生の貴重な時間を無駄にしてしまったのだから。ハーッハッハッハ！"
"80000095-13-カスミ" = "……そうじゃなかったのか？#nそれは良かった！であれば、私も気が楽というもの。"
"80000095-14-カスミ" = "では、こいつを……"
"80000095-15-カスミ" = "ド～～～ン！"
"80000095-16" = "[ns1] \"サン……ダル？\"\n[ns2] \"チョコレート……なの？\""
"80000095-17-カスミ" = "そうそう！先生は覚えてるか？"
"80000095-18-カスミ" = "以前、森で私のサンダルが壊れたときに新しい物を持ってきてくれただろう。"
"80000095-19-カスミ" = "先生にとっては些細な出来事だったかもしれないが……#n私は借りをしっかり返す主義でね。"
"80000095-20-カスミ" = "でも、同じ物を返しても面白くない……というわけで、チョコレートにしてみたのさ！"
"80000095-21-カスミ" = "それっぽくできてるだろう？#n遠目に見れば本物のスリッパと見間違うはずだ。"
"80000095-22-カスミ" = "……ん？"
"80000095-23-カスミ" = "手作りかって？……さあ、どっちだと思う？"
"80000095-24-カスミ" = "フッフッフ。いずれにせよ、私の「痕」は残っているぞ？"
"80000095-25-カスミ" = "それが手なのか……"
"80000095-26-カスミ" = "……それとも足なのかは言わないでおくが。"
"80000095-27" = "[ns3] \"…………え？\"\n[ns4] \"…………足？\""
"80000095-28-カスミ" = "ハーッハッハッハ！まぁまぁ！"
"80000095-29-カスミ" = "そんな細かい話は置いとこうじゃないか！"
"80000095-30-カスミ" = "……おっと。"
"80000095-31-カスミ" = "先生……悪いが、この辺りで失礼する。#nどうやら、居場所がバレてしまったらしい。"
"80000095-32-カスミ" = "私と居るところを見られたら、先生も困るだろう？"
"80000095-33-カスミ" = "それではさらばだ！帰ったらじっくり味わってくれ！"
"80000095-34-カスミ" = "では、また会おう～！！"
"80000095-35-カスミ" = "……あ！！"
"80000095-36-カスミ" = "そうだ。せっかくサンダルとして作ったんだ。#n食べる前に履いてみてもいいからな～！"
"80000095-37-カスミ" = "もちろん、どうするかは先生に任せるが！ハーハッハッハッハ！！"
"80000095-38" = "（その後、シャーレに戻ってからカスミにもらったチョコレートを確認した）"
"80000095-39" = "（……手と足の件からは目を背け、美味しく頂いた）"
