[translation]
"80000097-1" = "特別な対象"
"80000097-2-サクラコ" = "……こちらです、先生。"
"80000097-3-サクラコ" = "こんな時間にご足労くださり、ありがとうございます。"
"80000097-4-サクラコ" = "……え？"
"80000097-5-サクラコ" = "ええと、何か問題があったわけではありませんので、どうか誤解なきよう……"
"80000097-6-サクラコ" = "た、ただ……その……"
"80000097-7-サクラコ" = "……これ、を……"
"80000097-8" = "[s1] \"……チョコレート？\"\n[s2] \"今日はバレンタインデーだもんね。\""
"80000097-9-サクラコ" = "はい……渡すのが遅くなってしまいましたが……"
"80000097-10-サクラコ" = "先生は慕われておりますので、たくさんいただいているかとは思いますし、私も悩んだのです。"
"80000097-11-サクラコ" = "もしかしたら、今日という日を意識していないかも、とも……"
"80000097-12-サクラコ" = "ですが、あまり難しく考えず、自分の心のままに行動すると決めたのです。"
"80000097-13-サクラコ" = "ご迷惑でしたら申し訳ありませんが……#nどうか、お許しくださると……"
"80000097-14" = "[s3] \"そんなことないよ、本当にありがとう。\"\n[s4] \"サクラコこそ、忙しいのにありがとう。\""
"80000097-15-サクラコ" = "……はい。そう仰ってくださって、安心しました。"
"80000097-16-サクラコ" = "その……開ける前に、お伝えしておきたいのですが……"
"80000097-17" = "[s5] \"……ん？\"\n[s6] \"どうしたの？何かあった？\""
"80000097-18-サクラコ" = "それが、ですね……"
"80000097-19-サクラコ" = "これは……いえ、これだけは誰かに相談したり、調べたりせず、自分なりの答えを出したかったので……"
"80000097-20-サクラコ" = "……「エイリアンメガネ」や「チョコタイムダンス」のような流行は、取り入れていないのです。"
"80000097-21" = "[s7] （エイリアンメガネ……？チョコタイムダンス……？）\n[s8] （……なんの話だろう？）"
"80000097-22-サクラコ" = "ですから、その……"
"80000097-23-サクラコ" = "お渡ししたチョコレートは、流行りのものからは……"
"80000097-24-サクラコ" = "少し……いえ、とてもかけ離れているでしょう……"
"80000097-25-サクラコ" = "……申し訳、ございません。"
"80000097-26" = "[ns] \"……サクラコ。\""
"80000097-27" = "[ns9] \"その考え、大切だよ！\"\n[ns10] \"これからは、もっと自分の心を信じて！\""
"80000097-28-サクラコ" = "は、はい？えっと……先生？"
"80000097-29-サクラコ" = "ど、どうして突然そのようなお言葉を……！？#nわ、私……な、何か間違っておりましたか？"
"80000097-30-サクラコ" = "へ、変なことを言ってしまいましたか……？#nあ、あれ……えええ……？？？"
"80000097-31-サクラコ" = "…………こほん。"
"80000097-32-サクラコ" = "ひ、ひとまず……先生が仰りたいことは、理解しました。"
"80000097-33-サクラコ" = "……が……"
"80000097-34" = "[s11] \"……が？\"\n[s12] \"……ん？\""
"80000097-35-サクラコ" = "……です、が……"
"80000097-36-サクラコ" = "そうですね……"
"80000097-37-サクラコ" = "申し訳ありません、先生。#nその……いくら先生のお言葉だとしても……"
"80000097-38-サクラコ" = "全てを心の赴くまま、というのはやはり……"
"80000097-39-サクラコ" = "…………。"
"80000097-40-サクラコ" = "……せ、せん……"
"80000097-41-サクラコ" = "……せい……のことだけに、しようと思います。"
