[translation]
"10055165-1-コノカ" = "おい、さっさと起きねぇか！"
"10055165-2-コノカ" = "天下の公安局のカニが、こんなとこでへばってんじゃねえ！"
"10055165-3-カンナ" = "無茶を言うな。皆がお前みたいにタフなわけじゃない。"
"10055165-4-カンナ" = "……どうやら我々のカニは限界のようだ。"
"10055165-5-チアキ" = "おお！それはつまり！"
"10055165-6-カンナ" = "ああ。おめでとう、そちらの勝利だ。"
"10055165-7-チアキ" = "わあ！やりましたよ、ブラックドリー！"
"10055165-8-マコト" = "キシシッ！公安局の星も我々がいただくとしよう。"
"10055165-9-カンナ" = "では、こちらを。"
"10055165-10-カンナ" = "……最後に、一つだけ忠告を。"
"10055165-11-マコト" = "ふん、敗者の口から聞くことなどない！"
"10055165-12-イロハ" = "はぁ……素直に聞きましょうよ。"
"10055165-13-カンナ" = "あなた方はこの連勝によって、より注目を集める立場となった。"
"10055165-14-カンナ" = "この先出会う敵は、私たちよりも遥かに手強いものになるだろう。"
"10055165-15-マコト" = "何かと思えばそんなことか。……まったく、器の小さい奴だ！"
"10055165-16-マコト" = "むしろ、都合がいいではないか！"
"10055165-17-マコト" = "この機会を利用して、我々ゲヘナが……。#nいや、万魔殿がどれだけ優秀なのか……キヴォトス中に知らしめてやるのだ！"
