[translation]
"10055090-1" = "第9話;塩水の夢"
"10055090-2-スミカ" = "誠に、申し訳ございませんでした！！"
"10055090-3-スミカ" = "わ、私は止めたんです！なのに船員が「絶対に海賊だ」と言って聞かなくて……勝手に戦闘を始めて……。"
"10055090-4-スミカ" = "なのに、まさかのまさか！"
"10055090-5-スミカ" = "か～の有名なシャーレの先生と～！ゲヘナの万魔殿の皆様が、はるばるここまでいらっしゃったなんて！！"
"10055090-6" = "[s1] \"だ、大丈夫。\"\n[s2] \"へっっくしゅん！！\""
"10055090-7-スミカ" = "だ、大丈夫ですか先生！？みんな急いでブランケットとかタオルとか、もうありったけ持って来てください！！"
"10055090-8" = "[s3] \"私は大丈夫だよ。\"\n[s4] \"他のみんなをお願い。\""
"10055090-9-スミカ" = "ええ、ええ！もちろんです！5人ぜ～いん無事救出が終わり、皆さん安定した状態でいらっしゃいますよ。"
"10055090-10-スミカ" = "万魔殿の皆さんにはこう、何卒よろしく……。"
"10055090-11" = "[s5] \"……5人？\"\n[s6] \"あの船には他にも……。\""
"10055090-12-スミカ" = "……あ、先生も見たんですね。"
"10055090-13-スミカ" = "皆さん口を揃えて「他にも人がいる」と言っていたのですが……。"
"10055090-14" = "[s7] \"もしかして行方不明！？\"\n[s8] \"みんな海に！？\""
"10055090-15-スミカ" = "いえ、滅相もない！トライデントで総力を挙げて捜索中ですので！"
"10055090-16-スミカ" = "その……ほんと～に、誤解はしないでいただきたいのですが……。"
"10055090-17-スミカ" = "えっと、おかしなことを言っているように聞こえるかもしれませんが。"
"10055090-18-スミカ" = "……全員、消えてしまった、といいますか。"
"10055090-19-スミカ" = "人どころか、沈没した船さえも無くなってしまいました。"
"10055090-20-スミカ" = "まるで最初から存在なんてしなかったように……板の一枚も見つからないのです。"
"10055090-21-サツキ" = "……ああ、先生。"
"10055090-22-サツキ" = "聞きに来たんでしょ？私が「アレ」の正体について、何か知っているんじゃないかと。"
"10055090-23-サツキ" = "半分は正解よ。"
"10055090-24-サツキ" = "つまりもう半分はまだ推測の段階で、情報としては価値がない。"
"10055090-25-サツキ" = "ただ……どうしてそこまで気にするのかしら？"
"10055090-26" = "[s9] \"あの子たちも、生徒だったから？\"\n[s10] \"だから……。\""
"10055090-27-サツキ" = "生徒とはいえ、所詮初対面の人間でしょう？"
"10055090-28-サツキ" = "先生の考えている事は未だによく分からないわ。"
"10055090-29-サツキ" = "まあでも、先生に貸しを作るのは万魔殿にとってもそれなりに意味があるし……。"
"10055090-30-サツキ" = "いいわ、教えてあげる。私だけが知っている「情報」を、ね。"
"10055090-31-サツキ" = "……これは私たちとは何の関係もない、遠い昔の話だけど。"
"10055090-32-サツキ" = "ある時、ゲヘナ学園が海洋進出を夢見ていた時期があったの。一つの海洋学園を分校として作ろうとしていてね。"
"10055090-33-サツキ" = "当時の生徒会長は自分の名前を船につけ、生徒たちを集め、進水式を行なった。"
"10055090-34-サツキ" = "そして……どうなったと思う？"
"10055090-35-サツキ" = "出航と同時に沈没。"
"10055090-36-サツキ" = "原因はたくさんあったわ。まぁ、結局のところ沈むのが運命の船だったわけ。"
"10055090-37-サツキ" = "当然の結果よね。船なんて作ったこともない学園が、突然大型帆船を作ろうって言うんだもの。"
"10055090-38-サツキ" = "でも……最も有名な原因であり、一番の要因じゃないかと言われていたのは……。"
"10055090-39-サツキ" = "進水式で行われた、一斉祝砲。"
"10055090-40-サツキ" = "そのまま船は沈み、ゲヘナ海洋学園計画は白紙になった。"
"10055090-41" = "[s] \"あの時、私たちが見た校章は……。\""
"10055090-42-サツキ" = "そう、ゲヘナ海洋学園で使うはずだったものよ。"
"10055090-43-サツキ" = "でもマコトちゃんも区別ついてなかったし、分かる人はもうほとんどいないと思うわ。#nただでさえゲヘナ学園の校章に似てるのに、#nそもそも海洋学園の存在は黒歴史としてなかったものにされてしまったのだから。"
"10055090-44" = "[s11] \"でもその船は沈んだんだよね？\"\n[s12] \"学園も無くなって。\""
"10055090-45-サツキ" = "そうよ。だからおかしな話なの。"
"10055090-46-サツキ" = "存在するはずのない船と校章。#nそれが私たちの目の前に、現れたんだから。"
"10055090-47-サツキ" = "……つまり。"
"10055090-48-サツキ" = "あれは、本当の幽霊船……。"
"10055090-49" = "[ns13] \"サツキ！？\"\n[ns14] \"気をしっかりして！！サツキぃ～～！！\""
"10055090-50-マコト" = "そこ、誰か居ないのか？"
"10055090-51-マコト" = "ドリンクのおかわりだ。"
"10055090-52-マコト" = "ああそれと、チェリーが美味だった。一番新鮮なものを持ってくるように。"
"10055090-53-トライデントの部員A" = "……うちら、さっきまで戦ってなかったっけ？"
"10055090-54-トライデントの部員B" = "あいつ何者だ？偉そうに……。"
"10055090-55-トライデントの部員A" = "そこ！手を動かさんか！"
"10055090-56-トライデントの部員A" = "は、はいっ！！"
"10055090-57-イロハ" = "……。"
"10055090-58-イロハ" = "……。"
"10055090-59-イブキ" = "イロハ先輩！"
"10055090-60-イブキ" = "び、ビックリした。"
"10055090-61-イロハ" = "イブキと……先生？"
"10055090-62-イブキ" = "実はね、イブキ知ってるよ。"
"10055090-63-イブキ" = "イロハ先輩、マコト先輩と仲直りしたいんだよね？"
"10055090-64-イロハ" = "えっ？"
"10055090-65-イブキ" = "イブキと先生、応援しててあげる！"
"10055090-66-イブキ" = "はい、イブキが助けるね！"
"10055090-67-イロハ" = "ま、待ってくださいイブキ！"
"10055090-68-イロハ" = "……。"
"10055090-69-イロハ" = "……誰があんな人と。"
"10055090-70-イロハ" = "わがままで自分勝手で、強引で……。"
"10055090-71-マコト" = "ん？誰だ。"
"10055090-72-イロハ" = "イロハ……？そこで何をしている。"
"10055090-73-イロハ" = "……マコト先輩。"
"10055090-74-イロハ" = "単刀直入に、二つ聞きたいことがあります。"
"10055090-75-マコト" = "……。"
"10055090-76-イロハ" = "最初、幽霊船に乗る時こう言いましたよね。"
"10055090-77-マコト" = "不安なら無理についてこなくとも良い。船に居たければ好きにするがいい。"
"10055090-78-マコト" = "こちらに来たい者だけ私の後に続け。#nこのマコト様が先導してやろう。"
"10055090-79-マコト" = "ああ、そうだ。"
"10055090-80-マコト" = "あの時……誰もついていかなかったら、どうするつもりだったんですか？"
"10055090-81-マコト" = "そんなことが気になるのか？"
"10055090-82-イロハ" = "答えはシンプルだ。私も二つ答えを出してやろう。"
"10055090-83-マコト" = "一つ、誰もいなければ私一人で解決していた。"
"10055090-84-マコト" = "二つ、この私に人がついてこないはずがない、とな。"
"10055090-85-イロハ" = "……それが答えなんですか？"
"10055090-86-イロハ" = "本当にめちゃくちゃ……というかその二つの答え、矛盾してるじゃないですか。"
"10055090-87-イロハ" = "私たちはそんなデタラメな計画に巻き込まれてたんですか？"
"10055090-88-マコト" = "そういうイロハ、お前も結局は私についてきただろう？"
"10055090-89-イロハ" = "それは……。"
"10055090-90-イロハ" = "……。"
"10055090-91-イロハ" = "二つ目の質問です。"
"10055090-92-イロハ" = "あの幽霊船は、誰が見ても危険なものでした。でもマコト先輩も気付いてましたよね？"
"10055090-93-イロハ" = "なのになぜあそこに飛び込んだんですか？"
"10055090-94-マコト" = "……。"
"10055090-95-イロハ" = "……そうだと思いました。やっぱり何も考えてなかったんですよね？"
"10055090-96-イロハ" = "期待してた私がバカだった……。"
"10055090-97-イロハ" = "いやそれについては……。"
"10055090-98-マコト" = "そうではない。"
"10055090-99-イロハ" = "え？"
"10055090-100-マコト" = "理由は、ある……しかし。"
"10055090-101-イロハ" = "……またウソですか？先輩の特技でしたね、それ。"
"10055090-102-マコト" = "いいや……違う。"
"10055090-103-マコト" = "ただ、これは他の奴には言いふらすな。絶対にだ。"
"10055090-104-マコト" = "……だから。"
"10055090-105-イロハ" = "え？"
"10055090-106-マコト" = "いやその……私がすべて綺麗に解決すれば……。"
"10055090-107-マコト" = "イロハが謝るのでは、と思ってな……。"
"10055090-108-イロハ" = "……。"
"10055090-109-イロハ" = "……！？"
"10055090-110-イロハ" = "ウソですよね！！？"
"10055090-111-イロハ" = "そんなこと、よく口に出せましたね！？"
"10055090-112-イロハ" = "だから言っただろう！絶対に言うなと！"
"10055090-113-イロハ" = "ほんと、あり得ないですよ！？そもそも発端は全部――"
"10055090-114-チアキ" = "イブキちゃんはすごいね。"
"10055090-115-イブキ" = "うん？"
"10055090-116-チアキ" = "私は不安に思ってあの二人を引き離したのに……#n二人にさせた途端、何もかもうまくいった。"
"10055090-117-チアキ" = "イブキちゃんは、最初から分かってたんだよね？"
"10055090-118-イブキ" = "うん！だってイロハ先輩は～"
"10055090-119-イブキ" = "マコト先輩のこと、だーーーいすきだもん～！"
"10055090-120-チアキ" = "……。"
"10055090-121-チアキ" = "あはははっ！その通り！やっぱりイブキちゃんは天才だね！！"
"10055090-122-チアキ" = "そこうるさいですよ！全部聞こえてます！？"
"10055090-123-チアキ" = "あわわっ！"
"10055090-124-チアキ" = "イブキちゃん、退却するよ！！"
"10055090-125-イブキ" = "わ～たいきゃーく。"
"10055090-126-イロハ" = "まったく……。"
"10055090-127-イロハ" = "誰があんな人……。"
"10055090-128-イロハ" = "わがままで自分勝手で、強引で……。"
"10055090-129-イロハ" = "でもまあ……。"
"10055090-130-イロハ" = "たまには……本当、たまに。"
"10055090-131-イロハ" = "ちょっと格好いいですよね、マコト先輩。"
"10055090-132" = "出航！万魔船　マコト議長の華麗なる避暑"
