[translation]
"10009110-1" = "後日談その4;アメとムチの救護活動"
"10009110-2-ミネ" = "誇りと信念を胸に刻み！"
"10009110-3-ミネ" = "ふぅ……お許しください。#nこれも全て、皆さんのため――"
"10009110-4-ミネ" = "そこに「救護」を必要とする方がいるのならば、#n私たち救護騎士団は決して歩みを止めません！"
"10009110-5-チンピラ２" = "お、おい待てよ！"
"10009110-6-セリナ" = "団長のせいで、どんどん怪我人が増えて――ぐはっ！？"
"10009110-7-セリナ" = "大丈夫ですか？#n消毒するので、そのまま動かさないでくださいね。"
"10009110-8-ハナエ" = "傷口が開いたら大変ですからね！#n先輩、やっぱり全身を固定したほうがいいでしょうか？"
"10009110-9-ヘルメット団A" = "これがアメとムチなのか！？#nそれとも「救護」だなんだの言って、拘束したいだけ！？"
"10009110-10-ヘルメット団A" = "くっ……。#n救護騎士団の奴らが味方じゃないってことくらい分かってたけど……。"
"10009110-11-ヴァルキューレの生徒A" = "ありがとうございます！#n救護騎士団の皆さんのおかげで、この場は収まりそうです！"
"10009110-12-ミネ" = "己の責務を全うしただけですので、お気になさらず。"
"10009110-13-ミネ" = "ですが、いくら巡回を続けてもキリがないですね……。"
"10009110-14-ヴァルキューレの生徒A" = "公安局長さえいれば、こんなことには……！"
"10009110-15-ヴァルキューレの生徒A" = "でも、この件に関して公安局は動けないらしいよ……。"
"10009110-16-ヴァルキューレの生徒B" = "さっき聞いたけど、書類の手続きでトラブルがあったみたいだね。"
"10009110-17-ヴァルキューレの生徒A" = "現場報告書に捺印がなくて、さらに支援要請書の申請に必要な証明書が提出されてなかったんだって……"
"10009110-18-ヴァルキューレの生徒B" = "捺印漏れはともかく、証明書は前の現場でトラブルがあって紛失しちゃったみたいだから仕方ないとは思うけど……。"
"10009110-19" = "現場に出てたら紛失することだってあるよね。"
"10009110-20" = "証明書の発行は毎週水曜日って決まってるし。#n緊急の場合に備えて臨時発行も一応できるけど……。"
"10009110-21-ヴァルキューレの生徒A" = "臨時証明書の発行だって、防衛室から更に許可証をもらわないといけないもんね……。"
"10009110-22-ヴァルキューレの生徒A" = "――それは、どういう事でしょうか？"
"10009110-23-ミネ" = "実際に騒ぎが起きているというのに、#n何故そのような形式にとらわれた手続きが必要なのでしょうか？"
"10009110-24-ミネ" = "規則を重んじることも大切ですが、それゆえに「救護」の手が届いていないのではありませんか！"
"10009110-25-ヴァルキューレの生徒B" = "で、ですが……行政に関わることなので、どうしても手続きを踏まなければ……。"
"10009110-26-ミネ" = "でしたら、私が直接ヴァルキューレ警察学校の上層部に話を通しましょう！"
"10009110-27-ヴァルキューレの生徒B" = "い、いえ、流石にそれは……！"
"10009110-28-ヴァルキューレの生徒B" = "そうです。ミネ団長の立場的にそれは……。#n部外者の内政干渉は、学園間の紛争に発展する恐れが……！"
"10009110-29-ミネ" = "……私はとても悲しいです！#nどうして分かってくださらないのですか。"
"10009110-30-ミネ" = "その「形式」や「手続き」にこだわった結果、「救護」の手が行き届いていないというのに！"
"10009110-31" = "（その後、偶然現場の視察に訪れた警備局長とミネが鉢合わせてしまい――）"
"10009110-32" = "（ヴァルキューレ生の引き止めも虚しく、ミネは警備局長に抗議した）"
"10009110-33" = "（警備局長は「担当部署が違う」と返したが、その言葉でさらにミネの気勢は増し――）"
"10009110-34" = "（ひと悶着起こったものの――それはまた別のお話）"
"10009110-35-ワカモ" = "ふむ……何やら騒がしいようですが。"
"10009110-36-ワカモ" = "例の警備局長も護衛部隊もいない……となれば。"
"10009110-37-ワカモ" = "うふふっ……これは絶好のチャンスです。"
"10009110-38-ワカモ" = "では、仕切り直しと参りましょうか？"
