[translation]
"10015040-1" = "第4話;ミレニアムの応援団？"
"10015040-2" = "[ns] \"疲れた……。\""
"10015040-3-ノア" = "ふふ、お疲れ様でした。"
"10015040-4-ノア" = "ですが、すぐ適応してこなしていましたね。"
"10015040-5-ノア" = "スミレさんも言ってましたが……#n先生がミレニアム生だったら、選手として出場させたいくらいです。"
"10015040-6" = "[s1] \"褒めすぎだよ……。\"\n[s2] \"私は遠くから眺めてるだけで十分だよ。\""
"10015040-7-ノア" = "ふふ、試合は見るより実際に身体を動かしたほうが楽しいと言うじゃないですか。"
"10015040-8-ノア" = "なので、私たちセミナーもできるだけ多くの生徒が平等に出場できるよう、#n名簿を整理していますが……"
"10015040-9-ノア" = "競技への参加を嫌がる生徒が多く、エントリーの調整が難航しています。"
"10015040-10" = "[s] \"ミレニアム生って運動嫌いが多いの？\""
"10015040-11-ノア" = "トレーニング部のような例外もありますが、ほとんどはそうですね。"
"10015040-12-ノア" = "思索と研究を奨励するミレニアムの校風上、#n体力が低く、他人と交わることを嫌うスタイルの生徒が多いんです。"
"10015040-13-ノア" = "比較的名が知られているミレニアムの野球部でさえも、#n点数よりボールが描く放物線の方に興味があるというくらいですから。"
"10015040-14-ノア" = "ですので、今回の機会を通じてミレニアム生の皆さんがスポーツの魅力に気づき、#n互いに切磋琢磨する事で新しいインスピレーションを得てほしいと願っていましたが……"
"10015040-15-ノア" = "もしかしたら……運動が好きではない生徒にとっては、今回の大運動会はただ面倒なだけのお祭りかもしれませんね。"
"10015040-16" = "[s] \"ノアの気持ちがみんなに伝わったらいいね。\""
"10015040-17-ノア" = "ふふ……そのお言葉だけで、とても嬉しいです。"
"10015040-18-ノア" = "あ、やっと戻って来られましたね。#nエンジニア部の皆さんがいる工業実習室です。"
"10015040-19" = "[s3] \"……ちょっと早くないかな？\"\n[s4] \"お願いしてから3時間しか経ってないけど……。\""
"10015040-20-ノア" = "大丈夫ですよ。これまでエンジニア部の皆さんは、#n変な機能を追加する事はあっても、締め切りを破ったことは一度もありませんから。"
"10015040-21-ノア" = "先程も3時間以内に完成できると言っていましたし、大丈夫でしょう。"
"10015040-22-ノア" = "きっと今回も、素敵な応援ロボットを完成させてくれているはずです。"
"10015040-23" = "[s] \"なんか嫌な予感がする……。\""
"10015040-24-ノア" = "それでは、失礼しま～す。"
"10015040-25-ノア" = "あれ……？"
"10015040-26" = "[ns] \"………？\""
"10015040-27-コトリ" = "みんな……準備は良いかい？"
"10015040-28-ヒビキ" = "はい、団長！"
"10015040-29-コトリ" = "うん……"
"10015040-30-ウタハ" = "フレー！"
"10015040-31-コトリ" = "フレー！"
"10015040-32-ウタハ" = "頑張れ！"
"10015040-33-ヒビキ" = "が、がんばれ……"
"10015040-34-ヒビキ" = "ヒビキ、声が小さいぞ！"
"10015040-35-ウタハ" = "が、ガンバレ！"
"10015040-36-ウタハ" = "いけ！いけ！勝て！勝て！――ミレニアム！"
"10015040-37-ウタハ" = "わーー！"
"10015040-38-ウタハ" = "わー……"
"10015040-39-ノア" = "素晴らしい応援ですね。気合と情熱が伝わってきます。"
"10015040-40-ノア" = "先生もそう思いませんか？"
"10015040-41" = "[s5] \"たしかに素敵な応援だったけど……。\"\n[s6] \"……どうして応援団の格好を？\""
"10015040-42-ウタハ" = "明日の大運動会で選手の応援をするためだよ。"
"10015040-43-ウタハ" = "応援が選手の身体能力を向上させてくれるのは、#n科学的にも証明されている事実ですからね！"
"10015040-44-コトリ" = "繰り返される大きな音は大脳皮質に影響を及ぼし、#nアドレナリンの分泌を促進させてくれます。"
"10015040-45-コトリ" = "さらに、この応援服のような原色を目にすると、#n選手たちの興奮を極大化させることができるんです！"
"10015040-46-コトリ" = "あ、ちなみに私たちが着ているこの応援団の服は、ヒビキが作ってくれました。"
"10015040-47-ヒビキ" = "3人とも学ランにしたかったんだけど……#n時間が足りなくて、ウタハ先輩の分しか作れなかった。"
"10015040-48-ヒビキ" = "コトリと私が着てる服は、昔作ったチアリーダーのなんだけど、コスプレを始めたばっかの時に作ったヤツだから……生地も薄いし、縫製や造形も甘くて……"
"10015040-49-ヒビキ" = "こんな完成度の低い服を着て人前に出るなんて……#n恥ずかしさで逃げだしたい……。"
"10015040-50-ウタハ" = "そんなこと言わないでくださいよヒビキ。#nお店で売っている服よりはるかに高いクオリティですよ？"
"10015040-51-コトリ" = "うん。私もこの学ラン、すごく気に入ってるよ。#nできるなら制服の代わりに着たいくらいだ。"
"10015040-52" = "[s] \"私も素敵な格好だと思うけど……。\""
"10015040-53-ノア" = "ええと……盛り上がっているところすみませんが……"
"10015040-54-ノア" = "先ほどお願いしていた応援ロボットの方は、どうなりましたか？"
"10015040-55-コトリ" = "えっと……それが……"
"10015040-56-ヒビキ" = "製作は完璧だったんだけど……事故が起きちゃって……"
"10015040-57-ウタハ" = "ああ……結論から言うと……"
"10015040-58-ウタハ" = "失敗してしまったんだ……！"
"10015040-59" = "[s] \"エンジニア部がロボット作りに失敗した……？\""
"10015040-60-ウタハ" = "ロボットの機能を試演する時までは問題なかったんだけど……"
"10015040-61-ヒビキ" = "セキュリティプログラムをアップデートするために、#n近距離通信モジュールをオンにした瞬間、突然制御から外れて暴走し始めたの。"
"10015040-62-コトリ" = "うぅ……なんとか止めようとしたものの、緊急停止命令も聞かず……#nひとしきり暴れまわった後、全速力で逃げてしまって……"
"10015040-63-ウタハ" = "結果、ここには何も残ってないんだ。"
"10015040-64-ウタハ" = "……約束を守れず面目ない。"
"10015040-65-ウタハ" = "だが、エンジニア部の名誉をかけて約束した以上、依頼は最後まで遂行するよ。"
"10015040-66-ウタハ" = "そう……大運動会の期間中、私たちが応援ロボットの代わりに観客を案内し、選手を応援するとしよう！"
"10015040-67-コトリ" = "どんな状況でも最善を尽くして課題を解決するのが私たちエンジニア部のモットーですからね！"
"10015040-68-ヒビキ" = "チアリーディングは未熟だけど……最善を尽くすよ。"
"10015040-69-ノア" = "妙ですね……近距離通信モジュールを実行した瞬間に、異常行動を見せるなんて。"
"10015040-70-ノア" = "ロボットの設計図を見てもいいですか？"
"10015040-71-ウタハ" = "ああ、これだよ。"
"10015040-72-ノア" = "……ロボットの回路に異常はなさそうですね。#n緊急停止ボタンもきちんと設計されています。"
"10015040-73-ノア" = "この設計図どおり製作されたなら、暴走する原因がありません。"
"10015040-74" = "[s] \"図面だけで分かるの？\""
"10015040-75-ノア" = "一応、特許関連の業務も受け持っていますから。#n図面を見るのは慣れているんです。"
"10015040-76-ノア" = "やはり、どこにも異常がないように見受けられます……#n製作中に重大な何かが生じたのでなければ、やはり……"
"10015040-77-ノア" = "……ハッキングを疑うしかないですね。"
"10015040-78-ウタハ" = "……ハッキング？"
"10015040-79-ウタハ" = "ですが、学園外から近距離無線通信でハッキングするのは不可能なはずですよ！"
"10015040-80-ノア" = "それが……先程ヴェリタスの部室に寄った際、こんなお話を聞いたのです……"
"10015040-81-ウタハ" = "……ミレニアムの内部に、大運動会を邪魔しようとする人が？"
"10015040-82-コトリ" = "何と！やはり、私たちの設計に問題があったわけではなかったんですね。"
"10015040-83-ヒビキ" = "……ハッキングなら仕方ないね。#nエンジニア部のセキュリティモジュールは、通常のプラグインを使ってるから……"
"10015040-84-ノア" = "……犯人を特定するのは大会の後にしようと思っていましたが、#nこうなった以上、野放しにしておくわけにはいかないですね。"
"10015040-85-ノア" = "ハッキングに関することですから、ヴェリタスに助けを求めた方がよさそうです。"
"10015040-86-ノア" = "あまり時間も残ってないですし、急いでヴェリタスの部室に行きましょう！"
