[translation]
"51085-1-アラタ" = "く、くそっ……！！"
"51085-2-アラタ" = "い、今に見てろよ百花繚乱め！！"
"51085-3-カエデ" = "ふんっ！私たちを甘くみるとこうなるんだから！"
"51085-4" = "[s] \"みんな大丈夫？怪我は無い？\""
"51085-5-ミモリ" = "わ、私は大丈夫です。カエデちゃんとツバキちゃんは……？"
"51085-6-カエデ" = "うん！全然平気！"
"51085-7-ツバキ" = "私もだいじょうぶ～"
"51085-8-ユカリ" = "ふふっ。身共も無事ですの！ "
"51085-9-ユカリ" = "修行部の皆様の流れるような連携……すごかったです！ "
"51085-10-ユカリ" = "そして――流石はレンゲ先輩！#n素晴らしいご活躍ですわ！"
"51085-11-レンゲ" = "あれ？"
"51085-12-レンゲ" = "…………ユカリ？"
"51085-13" = "次回;[ruby=ふわ]不破[/ruby]レンゲ"
