[translation]
"51090-1" = "第9話;[ruby=ふわ]不破[/ruby]レンゲ"
"51090-2-レンゲ" = "……なんであんたがここにいるんだ？"
"51090-3-ユカリ" = "[ruby=みども]身共[/ruby]はレンゲ先輩を探して、文化部を回っていたのです！"
"51090-4-ユカリ" = "ですが、まさか修行部の皆様とご一緒だったとは……"
"51090-5-ミモリ" = "レンゲちゃんは、以前から修行部を体験してみたいと言っていたので。"
"51090-6-ツバキ" = "ふぁああ～……それで今……体験入部中、なの……すぅ……"
"51090-7-カエデ" = "これはアレだ！#n私が撮った修行部の宣伝映像が役に立ったって事だね！"
"51090-8-ミモリ" = "お二人はお知り合いだったんですね。#nそういえば、同じ水色の羽織……"
"51090-9-カエデ" = "あ！本当だ！レンゲ先輩も百花繚乱なの？"
"51090-10-レンゲ" = "あぁ……そ、そうだよ。"
"51090-11-レンゲ" = "いや、隠そうとしてたわけではないんだけど……"
"51090-12-ユカリ" = "青春活動のために様々な部活の体験入部をされているのですよね？"
"51090-13-レンゲ" = "……っっ！？"
"51090-14-レンゲ" = "ま、待て。ユカリ、なんであんたがそれを……！"
"51090-15-ユカリ" = "レンゲ先輩を探して、先輩のご自宅へ伺いましたの！"
"51090-16-ユカリ" = "扉に「青春の旅に出る」という紙が残されておりましたので……"
"51090-17-ユカリ" = "レンゲ先輩が体験入部をされているとお聞きして、そういうことなのではないかと……"
"51090-18" = "[s] \"部活動はたしかに青春だもんね。\""
"51090-19-ユカリ" = "ええ！"
"51090-20-ユカリ" = "青春への憧憬……身共も感動いたしました。"
"51090-21-レンゲ" = "ああもう！そんなに連呼しないでくれ！"
"51090-22-レンゲ" = "誰だってそういう置き手紙を残したくなる時があるだろ……"
"51090-23-レンゲ" = "学生時代はあっという間に過ぎていくから気をつけろ――っていうし。"
"51090-24" = "[s] （誰かに言われたのかな……）"
"51090-25-レンゲ" = "あーいや、恥ずかしがる事でもないんだが…… "
"51090-26-レンゲ" = "……そうだよ。あんたの言う通り、アタシは青春を送るために修行部に入ったんだ。"
"51090-27-レンゲ" = "今まで鍛錬の日々で失ってきた青春を……#nアタシの青春を取り戻すために！"
"51090-28-レンゲ" = "……だからユカリ。あんたが何でアタシを探してるのかは知らないけど、もう決めたんだ。この修行部で、アタシは青春を送るって。だから大人しく帰っ――"
"51090-29-レンゲ" = "修行部での青春活動がどのようなものなのか、身共も気になりますわ！"
"51090-30-レンゲ" = "アタシの話、ちゃんと聞いてたか！？"
"51090-31-ユカリ" = "レンゲ先輩がここまでなさるほどの事ですもの……#n身共も気になります！"
"51090-32-レンゲ" = "だ、だから、アタシの青春活動は……"
"51090-33-レンゲ" = "その……"
"51090-34-レンゲ" = "そ、そうだ！修行部でアタシは、「熟睡レディーファイター」になるための修行をやってるんだよ！"
"51090-35-ツバキ" = "ふぇ？"
"51090-36-ツバキ" = "ふぁあ……？"
"51090-37-ミモリ" = "レンゲちゃん……そんな目標を持っていたのですね！？"
"51090-38" = "[s] \"……眠りながら戦うってこと？\""
"51090-39-レンゲ" = "な、何だっていいだろ！"
"51090-40-レンゲ" = "青春には変わりないんだから！"
"51090-41-ユカリ" = "そ……そんな……"
"51090-42-レンゲ" = "たしかにユカリから見たら変な事かもしれないが……"
"51090-43-ユカリ" = "す……素晴らしいですの！目標に向かって真っ直ぐ駆け抜けていくお姿！"
"51090-44-ユカリ" = "流石は身共が尊敬するレンゲ先輩ですわ！"
"51090-45-レンゲ" = "えっ……う、うん？"
"51090-46-ユカリ" = "キキョウ先輩はこのことをご存じでしょうか？"
"51090-47-ユカリ" = "きっとキキョウ先輩なら全力で応援――"
"51090-48-レンゲ" = "するわけないだろ！アイツは絶対笑うに決まってるし、むしろ一番知られたくないんだけど！？"
"51090-49-レンゲ" = "そ、それより！アタシに何か用なのか？"
"51090-50-ユカリ" = "……へ？"
"51090-51-レンゲ" = "へ、じゃないだろ……"
"51090-52-レンゲ" = "そもそも、百花繚乱の活動は休止中だろ？"
"51090-53-レンゲ" = "それに、あんたは今お祭りの準備で一番忙しいんじゃ……"
"51090-54-ユカリ" = "わーわー！！！"
"51090-55" = "[s] \"……？\""
"51090-56-ユカリ" = "こほんっ！レンゲ先輩を探していたのには、もちろん理由がありますの。"
"51090-57-ユカリ" = "身共は、これよりナグサ先輩に「百花繚乱継承戦」を申し込もうと思っております。"
"51090-58-ユカリ" = "ですから……レンゲ先輩のお力をお借りしたいのです。"
"51090-59-レンゲ" = "…………は？継承戦？"
"51090-60-レンゲ" = "一体……どういうつもりだ？"
"51090-61" = "（私たちはレンゲに、陰陽部であったことやユカリの考えを話した）"
"51090-62-ユカリ" = "キキョウ先輩の仰る通りでしたの！"
"51090-63-ユカリ" = "ナグサ先輩は大雪原におりました……！"
"51090-64-レンゲ" = "…………。"
"51090-65-ユカリ" = "ですから、身共は百花繚乱を元に戻すべく――"
"51090-66-ユカリ" = "「継承戦」でナグサ先輩を倒し……"
"51090-67-ユカリ" = "委員長の座を受け継いでみせますの！"
"51090-68-レンゲ" = "…………。"
"51090-69-ユカリ" = "レンゲ先輩、一緒に帰りましょう。"
"51090-70-ユカリ" = "キキョウ先輩のいる百花繚乱に！そして継承戦の証人として――"
"51090-71-レンゲ" = "ユカリ……お前はまだ……"
"51090-72-レンゲ" = "まだそんな……"
"51090-73-ユカリ" = "ええ！"
"51090-74-レンゲ" = "そん[ruby=たわごと]な戯言を[/ruby]言ってるのか。"
"51090-75-ユカリ" = "……えっ。"
"51090-76-レンゲ" = "お前も知っての通り、百花繚乱にはすでに「解散令」が出されている。"
"51090-77-レンゲ" = "キキョウ自ら、参謀の権限を使って決断したんだ。"
"51090-78-ミモリ" = "そんな……百花繚乱が解散令を……？#nえっと、それは……"
"51090-79" = "[s] \"ミモリ、これにはちょっと複雑な事情があって……\""
"51090-80-ユカリ" = "そ、そんなはずありませんわ！"
"51090-81-ユカリ" = "解散令など、すべて間違いで……！"
"51090-82-レンゲ" = "――間違いなんかじゃない。"
"51090-83-レンゲ" = "アヤメ委員長が姿を消したあの日から……いつかはこうなる運命だったんだよ。 "
"51090-84-レンゲ" = "委員長はたしかにすごい人だ……だが、あんたも含めてみんな、いつ委員長がいなくなってもおかしくないと思っていただろう？"
"51090-85-ユカリ" = "……！"
"51090-86-レンゲ" = "座を受け継ぐべきナグサ先輩は、残されたアタシたちには目もくれず委員長を探しに行ってしまった。"
"51090-87-レンゲ" = "あの時点で、百花繚乱は終わってたんだ。"
"51090-88-ユカリ" = "そんなこと……ありませんわ！"
"51090-89-ユカリ" = "そ、それに……レンゲ先輩ご自身が、百花繚乱はまだ終わっていないと証明してくださったじゃないですか！"
"51090-90-ユカリ" = "レンゲ先輩は先ほども[ruby=すだまいちざ]魑魅一座[/ruby]に立ち向かってくださりました！あれは、百花繚乱としての責任を……"
"51090-91-レンゲ" = "それはユカリの勘違いだ。"
"51090-92-レンゲ" = "あれはアタシの青春を邪魔しようとしたヤツらをしばいただけ。アタシはアタシのために戦った。"
"51090-93-ツバキ" = "レンゲちゃん……。"
"51090-94-ツバキ" = "……。"
"51090-95-ユカリ" = "そ、それでは……百花繚乱がいなくなってしまったら、#n百鬼夜行の平和は……"
"51090-96-レンゲ" = "ハッ……それこそ[ruby=うぬぼれ]自惚れ[/ruby]だったんだよ。"
"51090-97" = "[s] \"どういうこと……？\""
"51090-98-レンゲ" = "シャーレの先生、だったな。"
"51090-99-レンゲ" = "空が赤くなった日の事を覚えてるか？"
"51090-100-ユカリ" = "……！"
"51090-101-レンゲ" = "あのとき、百鬼夜行は本当にめちゃくちゃだった。"
"51090-102-レンゲ" = "街に怪物が現れた、あの日――百花繚乱を呼ぶ声がそこかしこから聞こえてきたよな。"
"51090-103-レンゲ" = "だが、委員長も副委員長も不在のアタシたちは、目の前の人を助けるだけで手一杯で、それ以上のことなんて何もできなかった。"
"51090-104-レンゲ" = "アタシもキキョウも……ユカリ、あんたも。#nどうにか事態を収拾しようと駆け回ったよな。"
"51090-105-レンゲ" = "アタシたちが動いた結果、何が変わったか覚えてるか？"
"51090-106" = "[s] \"……どうなったの？\""
"51090-107-レンゲ" = "――何も。#n何一つ……変わらなかったんだよ。"
"51090-108-レンゲ" = "あんたも当事者だったから分かるだろ。百花繚乱がいなくたって問題は解決した。#n――百鬼夜行に、百花繚乱は必要ない。"
"51090-109-レンゲ" = "そう……あのとき百花繚乱が居なかったことで証明されてしまった[ruby=・   ・]事実[/ruby]がこれだ。"
"51090-110-レンゲ" = "委員長が居なかろうが、副委員長が居なかろうが……百花繚乱が解散したって何一つ百鬼夜行は変わらない。誰もアタシたちを必要としていないんだ。"
"51090-111-レンゲ" = "それなら、こんな風に…… "
"51090-112-レンゲ" = "帰ってこない委員長を待ち続けて苦しむ必要も……無いだろ？"
"51090-113-ユカリ" = "ですが……それでも！"
"51090-114-ユカリ" = "れ、レンゲ先輩だって……ナグサ先輩や、百花繚乱での活動が好きだったじゃないのですか！？"
"51090-115-ナグサ" = "レンゲは優秀な子。私みたいな半人前なんかよりも、ずっと。"
"51090-116-ナグサ" = "そんなレンゲを誇らしく思ってる。#nね、ユカリもそう思うでしょ？"
"51090-117-ユカリ" = "ええ！ "
"51090-118-キキョウ" = "ユカリ、今のはナグサ先輩よりもレンゲが優秀だって言ってるんだけど。"
"51090-119-ユカリ" = "ハッ……！？"
"51090-120-ユカリ" = "ちょっ！聞いてるこっちが恥ずかしくなるからやめてくれないか！？"
"51090-121-ユカリ" = "アタシより強いナグサ先輩に言われても素直に喜べないって！"
"51090-122-ナグサ" = "……ふふっ。"
"51090-123-ユカリ" = "いつも先陣を切って道を開くレンゲ先輩を……#nナグサ先輩は誇りに思っていたのに……！"
"51090-124-レンゲ" = "……！！"
"51090-125-レンゲ" = "知るか！結局アタシたちは見放されたんだよ！"
"51090-126-レンゲ" = "過去は過去だ。#nナグサ先輩はもう帰ってこない……それどころか……"
"51090-127-レンゲ" = "あの人は……を返却しようとしたんだ。それでもあんたは……！"
"51090-128" = "[s] （レンゲはなんて言ったんだろう……？）"
"51090-129-ユカリ" = "ですが……"
"51090-130-ユカリ" = "今が苦しくないとは言いません……それでもナグサ先輩が戻ってきて、また皆様と集まれたら……"
"51090-131-ユカリ" = "身共が「継承戦」で勝つことができれば……#n身共の気持ちを、ナグサ先輩に分かっていただければ……もう一度、あの日々を……！"
"51090-132-ユカリ" = "きっと……あの時みたいに……笑えると……"
"51090-133-レンゲ" = "……ユカリは昔からそうだったよな。#n自分が正しいと思ったら、ひたすらにまっすぐ突き進む。"
"51090-134-レンゲ" = "いつだって自信に溢れていて……その気になれば、何だってできると思っていてさ。"
"51090-135-レンゲ" = "本当に――自分を曲げないヤツだ。"
"51090-136-レンゲ" = "会話だけじゃなく、真っ向からぶつからないと納得しないのも……相変わらずだな。"
"51090-137-レンゲ" = "こうなったら、力尽くで分からせてやるよ。"
"51090-138-レンゲ" = "ユカリ……覚悟はいいか？"
