[translation]
"51110-1" = "第11話;ただの一生徒"
"51110-2-アラタ" = "お前ら！囲め！今度こそ逃さないようにな！"
"51110-3-アラタ" = "さっきはち～っとばかし手違いがあったけどなぁ！"
"51110-4-アラタ" = "今度こそ、ようやく見つけたぞ！"
"51110-5-？？？" = "……もぐもぐ。"
"51110-6-アラタ" = "この間は逃しちまったが、今回は諦めるんだな！#nこっちは前よりも人手を増やしてきたんだ！"
"51110-7-？？？" = "……もぐもぐ。"
"51110-8-魑魅一座A" = "リーダー！あいつ何か食ってますよ！"
"51110-9-アラタ" = "ハッ！舐めやがって！"
"51110-10-？？？" = "もぐもぐ……"
"51110-11-？？？" = "ごくっ。"
"51110-12-アラタ" = "最後に何か言い残すことはねぇのか？"
"51110-13-アラタ" = "大人しく謝るなら、少しは手加減してやっても――"
"51110-14-？？？" = "――もぐもぐ。"
"51110-15-魑魅一座B" = "リーダー！あいつ、また何か食べ始めたっすよ！？"
"51110-16-？？？" = "百花繚乱っ……！どこまであたしらをコケに……！"
"51110-17-？？？" = "……前にも言ったけど、私は百花繚乱じゃない。"
"51110-18-？？？" = "たまたまお祭りに来ているだけの……"
"51110-19-？？？" = "……そう、平凡だけど、どこか神秘的で儚げな……ただの百鬼夜行の一生徒。"
"51110-20-アラタ" = "ただの一生徒があんな事できるわけねぇだろうがよ！？"
"51110-21-アラタ" = "もう許さねえ！"
"51110-22-アラタ" = "全員、とつげ――！"
"51110-23" = "[s] \"待って！\""
"51110-24-魑魅一座B" = "リーダー！？"
"51110-25-魑魅一座B" = "い、いきなり撃つなんて……！"
"51110-26-魑魅一座B" = "先輩！？"
"51110-27-魑魅一座B" = "くそっ……"
"51110-28-魑魅一座B" = "ぜ、全員突撃だぁぁあ！！ "
"51110-29-魑魅一座たち" = "うぅっ…………"
"51110-30-アラタ" = "ち、ちくしょう！"
"51110-31-アラタ" = "囲め！！数で押していけ！！"
"51110-32-？？？" = "……！"
"51110-33" = "（一体どれほどの時間が経ったのだろう……）"
"51110-34-アラタ" = "捕まえ……！"
"51110-35-？？？" = "っ！？"
"51110-36" = "[ns] \"右！\""
"51110-37-アラタ" = "分かったぞ……"
"51110-38-アラタ" = "右だ！右を狙うんだ！！ "
"51110-39-アラタ" = "あいつ、右側の反応だけ遅い！"
"51110-40-アラタ" = "相手の弱点を見つけたらそこを重点的に狙い続ける……#nそれが魑魅一座ってもんよ！"
"51110-41-？？？" = "厄介……"
"51110-42-魑魅一座B" = "ロケットランチャーの準備ができたっす！"
"51110-43-アラタ" = "うわっ！な、何も見えねぇじゃねえか！"
"51110-44-？？？" = "けほっ、けほっ……"
"51110-45" = "[ns] \"ここは撤退しよう。\""
"51110-46-？？？" = "……誰？"
"51110-47-？？？" = "ま、待って、私は……"
"51110-48" = "[ns1] \"はぁ、はぁ……ここまで来れば大丈夫かな。\"\n[ns2] \"大きな怪我は無いみたいで良かった。\""
"51110-49-？？？" = "……あなたは誰？"
"51110-50-？？？" = "シャーレの、先生……？"
"51110-51-？？？" = "シャーレの先生って、たしか……"
"51110-52-？？？" = "……助けなくてよかったのに。"
"51110-53-？？？" = "あれくらい、私一人でも――"
"51110-54" = "[ns] \"右腕、怪我してるの？\""
"51110-55-？？？" = "……！"
"51110-56-？？？" = "右側の動きが鈍かった……？"
"51110-57-？？？" = "初対面の人が見て分かるくらい……そっか。 "
"51110-58-？？？" = "……これは。"
"51110-59-？？？" = "…………。"
"51110-60" = "[s3] \"聞かれたくないことだったらごめんね。\"\n[s4] \"無理に聞くつもりは無いから。\""
"51110-61-？？？" = "それで……シャーレの先生が、私に何か用？"
"51110-62-？？？" = "私を探していたわけじゃなくて、百鬼夜行に用事が？#nあそこに居たのはたまたま？……そう。"
"51110-63" = "[s] \"その格好、もしかして君は……\""
"51110-64-？？？" = "あ……その……百花、繚乱は……"
"51110-65" = "[s] \"やっぱり百花繚乱なんだね。\""
"51110-66-？？？" = "…………。"
"51110-67-？？？" = "そっか。そういえば、まだシャーレの先生とは……"
"51110-68-？？？" = "……うん。"
"51110-69-百花繚乱部員" = "あなたの言う通り。"
"51110-70-百花繚乱部員" = "私は……百花繚乱だよ。"
"51110-71-百花繚乱部員" = "いや……正確には、百花繚乱[ruby=・   ・   ・]だった[/ruby]と言うのが正しいかな。"
"51110-72-百花繚乱部員" = "……今は、もう離れてるから。"
"51110-73" = "[s] \"うん、話は聞いてるよ。解散令の時に抜けたメンバーが多かったって。\""
"51110-74-百花繚乱部員" = "解散令……"
"51110-75-百花繚乱部員" = "そっか、もう百花繚乱は……。"
"51110-76-百花繚乱部員" = "……うん、そうだよね。"
"51110-77-百花繚乱部員" = "私がアレを返そうとしたのだから、当然あの子たちは……"
"51110-78-百花繚乱部員" = "…………。"
"51110-79-百花繚乱部員" = "そう。私も百花繚乱を抜けて……ちょっと街に出かけてみたの。"
"51110-80-百花繚乱部員" = "息抜きに、お祭りの準備をしている姿が見たくて。"
"51110-81-百花繚乱部員" = "助けてくれてありがとう。"
"51110-82-百花繚乱部員" = "それじゃ私は――"
"51110-83" = "[s] \"時間も遅いし、ひとまず今日は帰ろっか。\""
"51110-84-百花繚乱部員" = "ん……？何で私が、あなたと……？"
"51110-85-百花繚乱部員" = "ちょっと、待って……！"
"51110-86" = "（喧騒から離れた二人の間には、沈黙が流れていた）"
"51110-87-百花繚乱部員" = "…………。"
"51110-88-百花繚乱部員" = "……………………。"
"51110-89-百花繚乱部員" = "あなたは……百鬼夜行に用事があって訪れた、と言ってたよね。"
"51110-90-百花繚乱部員" = "「解散令」のことも知っていた。"
"51110-91-百花繚乱部員" = "それなら、もしかしてだけど……百花繚乱について……"
"51110-92" = "[s] \"状況が気になるの？\""
"51110-93-百花繚乱部員" = "……ええ。離れてから、だいぶ経ったから。"
"51110-94-百花繚乱部員" = "少し、気になって。"
"51110-95" = "（特に隠す理由はないので、今日の出来事を話した）"
"51110-96-百花繚乱部員" = "……「継承戦」、か。"
"51110-97-百花繚乱部員" = "そっか、私が居ない間にそんなことが。"
"51110-98-百花繚乱部員" = "……どうして、そこまでして。"
"51110-99-百花繚乱部員" = "……いや、私がこんなことを言う資格は無いか。"
"51110-100" = "[s] \"このままじゃダメだとユカリは思ったんじゃないかな。\""
"51110-101-百花繚乱部員" = "そう、ユカリが……。"
"51110-102" = "百鬼夜行の住宅街"
"51110-103-百花繚乱部員" = "ここまでで十分。"
"51110-104-百花繚乱部員" = "送ってくれてありがとう、シャーレの先生。"
"51110-105-百花繚乱部員" = "……それじゃあ。"
"51110-106" = "[s] \"百花繚乱に戻る気は無いの？\""
"51110-107-百花繚乱部員" = "……なるほど。"
"51110-108-百花繚乱部員" = "警戒心が緩んだところで、それを聞くんだ。"
"51110-109-百花繚乱部員" = "思ったより、したたかな人なんだね。"
"51110-110-百花繚乱部員" = "……悪いけど、私は帰れない。"
"51110-111" = "[s] \"もう抜けたから……？\""
"51110-112-百花繚乱部員" = "…………そう。"
"51110-113-百花繚乱部員" = "あの日、私はアレを返そうとした……だからもう、あの子たちは私を許さない。"
"51110-114-百花繚乱部員" = "今さら百花繚乱に帰るだなんて……そんな度胸も無い。"
"51110-115-百花繚乱部員" = "私は、そんなに強くないから。"
"51110-116-百花繚乱部員" = "今の私には……そもそも資格が無いもの。"
"51110-117-百花繚乱部員" = "私は「あの子」じゃないし……"
"51110-118-百花繚乱部員" = "残ったみんなに、失望されたくない……"
"51110-119-百花繚乱部員" = "私が帰れない理由は、それだけ……だから……"
"51110-120" = "[log=???]＜ウソ＞[/log]"
"51110-121" = "＜ウソ＞"
"51110-122" = "＜ウソ＞"
"51110-123" = "＜ウソ＞"
"51110-124-百花繚乱部員" = "……それじゃ。"
"51110-125" = "[ns] \"初対面でいきなり聞くことじゃなかったかもしれない……。\""
"51110-126" = "[ns] \"次に会った時には……せめて、名前を聞けるといいんだけど。\""
"51110-127" = "（先ほどの会話を[ruby=はんすう]反芻[/ruby]しながら、陽が沈むさまを眺めていた）"
"51110-128" = "次回;桐生キキョウと継承戦（１）"
