[translation]
"51160-1" = "第16話;[ruby=ごりょう]御稜[/ruby]ナグサ"
"51160-2" = "（はやる気持ちと期待に満ちた声、軽快な足取り）"
"51160-3" = "（百鬼夜行の街は今、お祭りへの期待に満ちている）"
"51160-4" = "（昔の百鬼夜行ではよく見た光景）"
"51160-5" = "（こんな街を、私たちは……百花繚乱は……）"
"51160-6-ナグサ" = "一緒に警備、したね。"
"51160-7-ナグサ" = "…………ねえ、アヤメ。"
"51160-8-百花繚乱の部員A" = "アヤメ先輩がまた問題児を追い払ったんだって！"
"51160-9-百花繚乱の部員B" = "これでもう127回目？#n全部1人で解決しちゃうなんて！すごい！"
"51160-10-百花繚乱の部員C" = "この間は木から下りられなくなった子猫も助けたんだって！"
"51160-11-百花繚乱の部員A" = "この前なんてさ……！"
"51160-12" = "（アヤメのことを）"
"51160-13" = "（みな口々に話した）"
"51160-14-百花繚乱の部員A" = "本当、すごいよねアヤメ先輩！"
"51160-15-百花繚乱の部員B" = "アヤメ先輩がいたら何の心配もいらなそ～！"
"51160-16-百花繚乱の部員C" = "[ruby=ななかど]七稜ア[/ruby]ヤメ先輩……私もいつかは先輩みたいに！"
"51160-17-一同" = "アヤメ先輩が百花繚乱にいてくれてよかったー！"
"51160-18-ナグサ" = "うん。アヤメがいれば百花繚乱は大丈夫。"
"51160-19-ナグサ" = "アヤメがいれば……私もこのまま百花繚乱の活動を続けられる。"
"51160-20-ナグサ" = "アヤメの幼馴染として……"
"51160-21-ナグサ" = "ずっと、アヤメの隣にいられる。"
"51160-22-ナグサ" = "そう思って――"
"51160-23-ナグサ" = "――いたのに。"
"51160-24-百花繚乱の部員A" = "ねえ、聞いた？アヤメ委員長が姿を消したって。"
"51160-25-百花繚乱の部員B" = "噂ではクズノハ様と会ってから姿を消した、って聞いたけど。"
"51160-26-百花繚乱の部員C" = "えっ、マジ？でもクズノハ様ってただの噂じゃないの？"
"51160-27-百花繚乱の部員A" = "どうなんだろ……ていうか、これからどうしよう？"
"51160-28-百花繚乱の部員B" = "これから百花繚乱はどうなっちゃうの？#n委員長の座が空席になるんだよね？"
"51160-29-百花繚乱の部員C" = "私たち……どうなるんだろ。 "
"51160-30-百花繚乱の部員D" = "それなら大丈夫じゃない？"
"51160-31-百花繚乱の部員A" = "まあ、私たちにはナグサ先輩がいるし。"
"51160-32-百花繚乱の部員B" = "アヤメ先輩がいなくても、優秀なナグサ先輩が残ってくれてるし！"
"51160-33-百花繚乱の部員たち" = "だから大丈夫！"
"51160-34-ナグサ" = "違う……そうじゃない。"
"51160-35" = "（これは、口にできなかった本当の気持ち）"
"51160-36-ナグサ" = "……私には、できないよ。"
"51160-37" = "（残された私に、こ[ruby=あかし]の銃は[/ruby]重すぎる）"
"51160-38-ナグサ" = "だって……私は……"
"51160-39" = "[ruby=■ ■ ■ ■ ■ ■、■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■。]アヤメじゃないから[/ruby]。"
"51160-40" = "[ruby=■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■。]私はアヤメの代わりになれないから[/ruby]。"
"51160-41" = "[ruby=■ ■ ■ ■ ■ ■ ■ ■ ■ ■、■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■。]百花繚乱の委員長としての資格があるのは、アヤメだけだから[/ruby]。"
"51160-42-ナグサ" = "私にはそんな資格……そんなものは……"
"51160-43-ナグサ" = "……あなたが居ない[ruby=ここ]百花繚乱[/ruby]で……私はこれ以上……"
"51160-44" = "[ns] \"やっぱり、君がナグサだったんだね。\""
"51160-45-ナグサ" = "……！"
"51160-46" = "（忍術研究部より「ナグサらしき人を西地区で発見」という連絡を受け、現場に急ぐと）"
"51160-47" = "（以前にも言葉を交わしたことのある少女がいた）"
"51160-48-ナグサ" = "あなたは、この前の……シャーレの先生。"
"51160-49" = "[s] \"そういう君は、あの時の無限焼き鳥の幸せスパイラルっ子！\""
"51160-50-ナグサ" = "幸せスパ……何？"
"51160-51-ナグサ" = "……くだらない冗談はやめて。 "
"51160-52-ナグサ" = "その様子……もう知ってるみたいだね。#n特に隠すつもりもなかったけど。"
"51160-53" = "[s] \"ナグサ。\""
"51160-54-ナグサ" = "そう、私[ruby=ごりょう]が御稜ナ[/ruby]グサ。#n百花繚乱の副委員長。"
"51160-55-ナグサ" = "いや、証を返却した今は……「元」副委員長かな。"
"51160-56-ナグサ" = "それで、何の用？ "
"51160-57-ナグサ" = "用事……？あなたが？"
"51160-58" = "[s] \"以前会った時、継承戦と百花繚乱のことを話したよね。\""
"51160-59" = "（あの後に起きた出来事をナグサに説明した）"
"51160-60" = "（ユカリと共にキキョウに会いに行ったこと、キキョウとの継承戦の結果、そしてユカリがお祭りで巫女として舞うと決めたことを）"
"51160-61-ナグサ" = "……そう。"
"51160-62-ナグサ" = "それが正解じゃないかな。その選択は正しいよ。"
"51160-63" = "[s] \"……本当にそう思うの？\""
"51160-64-ナグサ" = "……どうして、それを聞くの？"
"51160-65" = "[s1] \"ユカリはずっと君の話をしていたよ。\"\n[s2] \"君に憧れて百花繚乱に入った、と。\""
"51160-66" = "[ns3] \"そんな彼女が百花繚乱を抜けて……\"\n[ns4] \"元の場所に帰るべきだと君は本当に思ってるの？\""
"51160-67-ナグサ" = "………………。"
"51160-68-ナグサ" = "私は…………"
"51160-69" = "[s] \"ナグサが委員長の証を返却しようとしたのは聞いたよ。\""
"51160-70-ナグサ" = "何でそうしたのか……"
"51160-71-ナグサ" = "どうして皆のいる場所に帰らず、百花繚乱として活動しないのか……#n聞きたいの？"
"51160-72-ナグサ" = "………………。"
"51160-73-ナグサ" = "答えは単純だよ。"
"51160-74-ナグサ" = "百花繚乱の委員長は「[ruby=ななかど]七稜[/ruby]アヤメ」だから。"
"51160-75-ナグサ" = "委員長の座にはアヤメこそがふさわしい。 "
"51160-76-ナグサ" = "アヤメじゃないとダメなの。"
"51160-77-ナグサ" = "私は、アヤメの代わりにはなれない。#nだから引き下がろうと思った。"
"51160-78-ナグサ" = "あの子たちが思うほど……私にはふさわしくないの。"
"51160-79-ナグサ" = "今は皆、納得できないって言ってるけど。"
"51160-80-ナグサ" = "時間が経てばきっと分かってくれるはず。"
"51160-81-ナグサ" = "委員長代理という肩書は……ただ押しつけられただけ。"
"51160-82-ナグサ" = "そう、本当にそれだけ――"
"51160-83" = "[log=???][ff4444]＜ウソ＞[-][/log]"
"51160-84-ナグサ" = "……！？"
"51160-85" = "[s] \"今のは……？\""
"51160-86" = "[ns] \"あ、お祭りの始まりの合図……\""
"51160-87" = "（空に花が咲く――）"
"51160-88" = "（お祭りが――始まる）"
"51160-89-ナグサ" = "[ruby=すだまいちざ]魑魅一座[/ruby]、あなた達……！"
"51160-90-魑魅一座A" = "ひっ！？"
"51160-91-魑魅一座A" = "ち、違う……アレはあたしらじゃ……！ "
"51160-92-アラタ" = "あたしらは何もしてない！本当だってば！"
"51160-93" = "[s] \"まずは落ち着いて……一体何があったのか教えて。\""
"51160-94-アラタ" = "あたしらはただ、あいつの質問に答えただけで！ "
"51160-95-アラタ" = "助けてほしい？"
"51160-96-アラタ" = "って、言われて「そう」返しただけで……！"
"51160-97-ナグサ" = "……！"
"51160-98" = "[s] \"アレは一体……。\""
"51160-99-ナグサ" = "………………[ruby=かいだん]幻魎百物語[/ruby]。"
"51160-100-ナグサ" = "どうして……ここにあれが……！？"
"51160-101-？？？" = "役者がそろいましたね。"
"51160-102-？？？" = "始めましょうか。"
"51160-103-？？？" = "……手前どもだけの[ruby=かいだん]風流[/ruby]を。"
"51160-104" = "次回;街を歩く怪談（１）"
