[translation]
"51200-1" = "第20話;花鳥風月部の怪談家（２）"
"51200-2-シュロ" = "……ビックリしたぁ。"
"51200-3-シュロ" = "いきなり人に銃口を向けるだなんて……失礼ですよぉ？#nビックリするでしょ？まあ、手前には効きませんが……。"
"51200-4-シュロ" = "盛り上がってきたというのにどうして水を差すんですぅ？"
"51200-5-シュロ" = "シャーレの先生に手前さん方……こういう時に邪魔をするのは無粋ですよぉ？"
"51200-6" = "[s] \"騒ぎを起こした張本人が目の前にいるからだよ。\""
"51200-7-ツバキ" = "私たちは街の平和のためにここにいるからね～"
"51200-8-ツバキ" = "だから、止めないとって思って。"
"51200-9-ツバキ" = "はい！理由はどうあれ、騒動が起きている以上、#nあなたを放っておくわけにはいきません。"
"51200-10-ツバキ" = "そうそう！"
"51200-11-ツバキ" = "修行部みんなで止めるんだから！"
"51200-12-レンゲ" = "みんな……。"
"51200-13-キキョウ" = "あんた達……。"
"51200-14-シュロ" = "……そ～んな理由で、手前の邪魔をしたんですぅ？ "
"51200-15-シュロ" = "あとちょ～っとだったのに。"
"51200-16-シュロ" = "興醒めですよぉ……手前どもの話にケチをつけないでくだ――"
"51200-17-シュロ" = "だからぁ……意味ないって言いましたよねぇ？ "
"51200-18-シュロ" = "今度は手前さんですか……百花繚乱の黒猫さん？"
"51200-19-キキョウ" = "修行部の言う通り、重要なのは騒ぎを鎮めることだからね。"
"51200-20-キキョウ" = "相手がたとえ、目を疑いたくなるような魑魅魍魎だろうと――#n百花繚乱は退くわけにはいかない。 "
"51200-21-キキョウ" = "レンゲ、しっかりして。"
"51200-22-レンゲ" = "……わ、分かってるって！"
"51200-23-キキョウ" = "ナグサ先輩。"
"51200-24-ナグサ" = "……っ。"
"51200-25-キキョウ" = "……あいつが全ての黒幕、でいいんだよね？"
"51200-26-キキョウ" = "はぁ……たしかに、いかにもって感じだね。"
"51200-27-シュロ" = "ちょっとちょっとぉ～ひどくないですかぁ？#nそんな言い方ってないじゃないですかぁ。"
"51200-28-キキョウ" = "先生……あいつへの攻撃なんだけど。"
"51200-29" = "[s] \"うん、水面でも撃ったみたいにすり抜けていったね。\""
"51200-30-シュロ" = "そうですよぉ？だからだから、無駄だと申したでしょ？"
"51200-31-シュロ" = "手前の怪書「[ruby=いのうもののけろく]稲生物怪録[/ruby]」の前では手前さん方は無力。誰であろうと、「百物語」にはもちろん、手前に傷一つつけられないんですぅ！"
"51200-32-シュロ" = "――アヤメでもない限り、ね。"
"51200-33-シュロ" = "あ！でもでもぉ！#nここには半人前の泣き虫ナグサちゃんしか居ないんでしたぁ。ざんね～ん！"
"51200-34-ナグサ" = "…………。"
"51200-35-シュロ" = "へぇ……"
"51200-36-キキョウ" = "安全圏から煽ることしかできない卑怯者なんだ。"
"51200-37-シュロ" = "またまたそんな、ひどいですねぇ～"
"51200-38-シュロ" = "はぁ……まあ、もういいですけどぉ。"
"51200-39-シュロ" = "いくら手前さん方が騒いだところで――"
"51200-40-シュロ" = "物語の幕は切って落とされたのです。#n手前の望む「舞台」と「役者」は揃いました。"
"51200-41-シュロ" = "手前どもの「百物語」は、ゆっくりと確実に――終着点へと向かっているのですから。"
"51200-42" = "[s1] \"……シュロ、花鳥風月部の本当の目的は何なの？\"\n[s2] \"何のためにこんな騒ぎを？\""
"51200-43-シュロ" = "アハハッ、今さら今さら、それを手前に聞くのですねぇ？ "
"51200-44-シュロ" = "……ま、いいでしょう。答えて差し上げますよぉ？"
"51200-45-シュロ" = "全ては――「風流」のため。 "
"51200-46-シュロ" = "花鳥風月部の怪談家として、手前の「百物語」を作り上げるためです。"
"51200-47-キキョウ" = "そんな理由で、あんなものを呼び出したの？"
"51200-48-キキョウ" = "花鳥風月部って思ったより暇なんだね。"
"51200-49-シュロ" = "あは！"
"51200-50-シュロ" = "アハハッ！"
"51200-51-シュロ" = "アハハハハハッ！！"
"51200-52-レンゲ" = "なっ、何だよ……！？"
"51200-53-シュロ" = "愚かですねぇ。"
"51200-54-シュロ" = "本当にそう思ってますぅ？"
"51200-55-シュロ" = "怪物を操り、街を燃やし――#n手前さん方の前に現れるだけで「百物語」が作られる、だなんて。"
"51200-56-シュロ" = "そんなそんなお可愛い勘違いを――バカな誤解をするだなんて。"
"51200-57-シュロ" = "手前どもの「百物語」は、もっとも～っと昔から伝わるお話だというのに。"
"51200-58-シュロ" = "手前さん方が知る由もない――ええ、想像すらできないようなもの。"
"51200-59-シュロ" = "此処に至るまで……たった一つの「うわさ」で良いんですよぉ。"
"51200-60" = "[s] \"……うわさ？\""
"51200-61-シュロ" = "ええ。「うわさ」は、どこで聞いたのか覚えていなくとも、頭の片隅に残っているもの。"
"51200-62-シュロ" = "そう、必要なのは――「うわさ」だけ。"
"51200-63-シュロ" = "そうですねぇ……#n例えば、「継承戦」の存在を教えて無邪気なお嬢さんを動かしたり――"
"51200-64" = "[s] \"……！\""
"51200-65-シュロ" = "「青春は今しかない」と愚鈍な娘を動かしたり――"
"51200-66-レンゲ" = "……へ？"
"51200-67-シュロ" = "そしてそして……"
"51200-68-シュロ" = "思い上がり甚だしい娘に「後輩を思うのなら家に戻すべき」と伝えて、#n無邪気なお嬢様と戦うよう仕向けたり。"
"51200-69" = "[ns] \"……まさか。\""
"51200-70-シュロ" = "最初から、ぜ～んぶ分かっていたんじゃないですかぁ？"
"51200-71-シュロ" = "これができたのは、ぜ～んぶ、シャーレの先生……#n手前様がここに来てくれたからですよぉ？"
"51200-72-シュロ" = "手前様がここに来た理由……心当たりはありますよねぇ？"
"51200-73" = "[ns] \"……陰陽部宛ての、手紙。\""
"51200-74-シュロ" = "あは、アハハッ！"
"51200-75" = "[s] \"もしかして……最初から……。\""
"51200-76-シュロ" = "各々が「最善」の行動をとろうともがき、苦しみ――"
"51200-77-シュロ" = "[ruby=ソレ]最善[/ruby]のせいで、全てが台無しになってしまう……"
"51200-78-シュロ" = "最善であるはずが「最悪」だったなんて……夢にも思わず――ねぇ？"
"51200-79-シュロ" = "ああ、なんということでしょう。"
"51200-80-シュロ" = "こんな愚かで――素晴らしい物語！"
"51200-81-シュロ" = "アハハッ！愚かな手前さん方に感謝しなければねぇ？ "
"51200-82-シュロ" = "手前さん方が馬鹿なおかげで――20年前の怪談を再現できるのですから。"
"51200-83-ツバキ" = "また怪物が……！"
"51200-84-ツバキ" = "カエデちゃん！離れないでくださいね！"
"51200-85-カエデ" = "う、うん……！"
"51200-86-シュロ" = "無駄ですよぉ？もう火蓋は落とされたのですから。"
"51200-87-シュロ" = "手前どもの風流はこれから……ええ、これからがお待ちかねのクライマックスなのです。"
"51200-88-シュロ" = "手前さん方の尽力によって――物語の主役が誕生したのですから。"
"51200-89-シュロ" = "アハハッ！ええ、ええ！あの方に――主役になっていただきましょ。"
"51200-90-キキョウ" = "……まさか、ユカリ！"
"51200-91-レンゲ" = "ハァ！？"
"51200-92-シュロ" = "イヒヒッ！やっぱりそれくらいは気づいてくださらないと。"
"51200-93-シュロ" = "ええ、ええ！そうですとも。手前さん方のおかげで……#n誰よりも深い傷と絶望を抱いた少女――"
"51200-94-シュロ" = "「20年前の舞台を再現しなければならない」という呪縛に囚われてしまった哀れな哀れな少女。"
"51200-95-シュロ" = "ああ……きっと彼女なら……！#nとても素晴らしい風流を……！"
"51200-96-シュロ" = "ええ……最高の百物語になってくれるでしょう！"
"51200-97-ナグサ" = "あなた達は……また、アヤメの時みたいに……"
"51200-98" = "[s] （アヤメの時……？）"
"51200-99-シュロ" = "さてさて、それでは手前はこれにて失礼。"
"51200-100" = "[ns] \"みんな、シュロを――！\""
"51200-101-シュロ" = "無駄ですよぉ？"
"51200-102-シュロ" = "動き出した物語は、もう誰にも止められませんから。"
