[translation]
"51210-1" = "第21話;それでもあなたに"
"51210-2-レンゲ" = "ハァッ！"
"51210-3-ツバキ" = "雑魚はなんとか倒せたけど、やっぱり……"
"51210-4" = "[ns] \"クロカゲには攻撃が通らないね。\""
"51210-5-ミモリ" = "立て直しを図っているのか、向こうも大人しくなりましたが……"
"51210-6-ツバキ" = "またいつ仕掛けてくるか分からないね～"
"51210-7-カエデ" = "これじゃあ、さっきのヤツ倒しに行けないじゃん！"
"51210-8-カエデ" = "うわぁあん！どうしよう～～！？"
"51210-9-キキョウ" = "このままじゃユカリが……"
"51210-10-レンゲ" = "そんなのダメだ、なんとか方法を探さないと……！"
"51210-11-レンゲ" = "なあ、キキョウ！？"
"51210-12-キキョウ" = "…………。"
"51210-13" = "[ns] \"ナグサ。\""
"51210-14" = "[ns1] \"シュロがユカリを狙っている事、そして――\"\n[ns2] \"この状況が、すべて策略によるものだったというのも理解した。\""
"51210-15" = "[ns] \"「百物語」を作るって、どういう意味なのか教えてくれないかな？\""
"51210-16" = "[ns] \"シュロは……ユカリで何をする気なの？\""
"51210-17-ナグサ" = "それは……"
"51210-18-レンゲ" = "ぐだぐだ言ってないで……"
"51210-19-レンゲ" = "今はユカリを助ける方が先じゃないのか！？"
"51210-20-キキョウ" = "ナグサ先輩は「アヤメの時みたいに」って言ってたよね。"
"51210-21-レンゲ" = "キキョウ……？"
"51210-22-キキョウ" = "レンゲ、情報は大事だよ。#n悔しいけど、あいつの言う通り私たちは何も知らない。"
"51210-23-キキョウ" = "何が正しいのか、どう対処しなきゃいけないのか……何も。"
"51210-24-キキョウ" = "情報がないと判断できない。"
"51210-25-キキョウ" = "先生はそれを聞いてるんでしょ？#n今ここで情報持ってるのは、ナグサ先輩だけなんだから。"
"51210-26-ナグサ" = "私、だけ……。"
"51210-27-キキョウ" = "だから教えて。#nあいつの狙いと……私たちはどうすればいいのか。"
"51210-28-キキョウ" = "それが分かるのは、ナグサ先輩――あんたしかいないの。"
"51210-29-ナグサ" = "………………。"
"51210-30-キキョウ" = "……そっか。"
"51210-31-キキョウ" = "こんな状況でも、私たちには――"
"51210-32-ナグサ" = "花鳥風月部は……"
"51210-33-レンゲ" = "ナグサ先輩……？"
"51210-34-ナグサ" = "その昔……百鬼夜行が連合になるよりも前、猛威を振るっていたという……魑魅魍魎の集団。"
"51210-35-ナグサ" = "彼女らのことを指すの――"
"51210-36" = "[ns3] \"「百鬼夜行の連合の今の形態を認めない、極悪非道の部活」\"\n[ns4] \"｢怪書を操り、人々を惑わす魑魅魍魎」……だっけ。\""
"51210-37-ナグサ" = "……そう。"
"51210-38-ナグサ" = "理由も狙いも、何も分からない……でも手段は確実に存在する。"
"51210-39-ナグサ" = "怪書「稲生物怪録」と呼ばれる本を利用して、自分たちの喜悦……#n風流のために……「百物語」という怪談を生み出そうとしている。"
"51210-40-ナグサ" = "実際に、私が行った大雪原で花鳥風月部の部長であるコクリコは……アヤメを……"
"51210-41-ナグサ" = "……「百物語」にして、「黄昏」の向こうへと連れていったの。"
"51210-42-ナグサ" = "私はそれを見ていることしかできなくて……ただただ、無力で……。"
"51210-43-キキョウ" = "アヤメ委員長はそれで……"
"51210-44-キキョウ" = "……。"
"51210-45-ナグサ" = "シュロの言葉が本当なら、今回はユカリを狙っているんだと思う。"
"51210-46-ナグサ" = "このままじゃ、ユカリもアヤメみたいに……。"
"51210-47-レンゲ" = "どうして……アタシたちに何も言ってくれなかったんだ？"
"51210-48-ナグサ" = "怖かったの……本当のことを、言うのが。"
"51210-49-キキョウ" = "……ナグサ先輩。"
"51210-50-ナグサ" = "なっ、誰だ！？"
"51210-51-シュロ" = "あ、あ――手前さん方ぁ、見えますかぁ？"
"51210-52-カエデ" = "あっ、先生！あっちに……！"
"51210-53-シュロ" = "アハハッ！お祭り、楽しんでますかぁ～？"
"51210-54-シュロ" = "楽しんでくださってますよねぇ……？"
"51210-55-シュロ" = "手前どもが全力を尽くして、手前さん方を楽しませるために用意したのですからぁ。"
"51210-56-キキョウ" = "あれは、陰陽部の放送用飛行船……"
"51210-57-ミモリ" = "ネットでも中継されてしまっています……！"
"51210-58-レンゲ" = "なっ、ど、どうやって！？#nそんなことまでできんのかよ！"
"51210-59" = "[s] \"シズコがお祭りのために準備してたやつだ……。\""
"51210-60-キキョウ" = "でも、どうして放送なんか……。"
"51210-61-シュロ" = "アハハッ、手前が用意したのはそれだけじゃないんですよぉ。"
"51210-62-シュロ" = "手前さん方に、ご紹介したいお客さまがおりましてぇ？"
"51210-63-シュロ" = "ご存じの方もいるでしょうけどぉ――20年の時を経て再現されたこのお祭りで、手前さん方から期待を集めている”あの”お方！"
"51210-64" = "[ns] \"ユカリ……！\""
"51210-65" = "アハハッ！よ～く見えてますかぁ？"
"51210-66-シュロ" = "ま、このために準備したんですし？#nよく見えて当然ですけどぉ。"
"51210-67-シュロ" = "この物語の主人公を、ご紹介しますぅ。"
"51210-68-ユカリ" = "…………。"
"51210-69-シュロ" = "今は眠り姫のように静寂を貫いていますが、手前には分かっているのですよぉ。"
"51210-70-シュロ" = "この巫女は……誰よりも何よりも大きな傷を胸に秘めているって、ねぇ？"
"51210-71-シュロ" = "憧れの人には振り向いてもらえず――"
"51210-72-シュロ" = "――元に戻りたいと訴えても、無意味だと一蹴され。"
"51210-73-シュロ" = "帰りたいと声を上げても、別の帰る場所があると否定され――"
"51210-74-シュロ" = "巫女様はとうとう自分の場所へと帰りました……そう、ここに！"
"51210-75-シュロ" = "しかし、しかし、可哀相なことに……#n唯一の帰る場所だと思っていたそこで、巫女様に求められたのは――"
"51210-76-シュロ" = "20年前の汚名を返上してほしい――ただそれだけ。"
"51210-77-ユカリ" = "…………。"
"51210-78-シュロ" = "そうなんです。誰一人、巫女様の気持ちになんて興味がないのです。"
"51210-79-シュロ" = "ああ！ああ！お可哀想に……#n皆が笑顔になるはずのお祭りで、ひとり悲しみに暮れているなんて。"
"51210-80-シュロ" = "……悔しく、ないですかぁ？"
"51210-81-シュロ" = "その感情をひとりで抱えて苦しむくらいなら……#nいっそのこと、みんなで抱えた方が、よくありませんかぁ？"
"51210-82-シュロ" = "ですから、手前さんの代わりに手前が声を上げましょ。#n手前さんの代わりに、その感情を手前さん方に返して差し上げます！"
"51210-83-シュロ" = "さあさ、これより始まるのは、手前ども花鳥風月部の風流――"
"51210-84-シュロ" = "美しく、艶やかに煌びやかに、百鬼夜行を燃やし尽くして差し上げましょ！"
"51210-85-シュロ" = "手前さん方、どうぞご期待くださいなぁ！アハハハッ！ "
"51210-86" = "[ns] \"ユカリ……！\""
"51210-87-ツバキ" = "百鬼夜行を燃やす、って言ってたね。"
"51210-88-ツバキ" = "早く止めないと……今以上に大変な事態になってしまいます。"
"51210-89-ツバキ" = "は、早く行かないと……！"
"51210-90" = "[ns] \"クロカゲが、動き出した……！\""
"51210-91-レンゲ" = "くそっ……！"
"51210-92-レンゲ" = "攻撃が通らないヤツなんて、一体どうしたらいいんだよ！"
"51210-93-レンゲ" = "というか、そもそもコイツをどうにかしたところで……#n銃が効かないあいつをどうやって倒すんだ！？"
"51210-94-キキョウ" = "……方法なら、ある。"
"51210-95-レンゲ" = "キキョウ、本当か……！？"
"51210-96" = "[ns] \"これは……百花繚乱の委員長用の……？\""
"51210-97-キキョウ" = "そう。ナグサ先輩……あなたが私に残していった「百蓮」。"
"51210-98-キキョウ" = "シュロの言葉が本当なら……"
"51210-99-キキョウ" = "シュロを倒せるのはただ一人……証を持つ者だけ。#nつまり――"
"51210-100-キキョウ" = "ユカリを助けられるのは……ナグサ先輩、あなたしかいない。"
"51210-101-キキョウ" = "だからお願い、先輩。#nユカリを助けてあげてほしい。"
"51210-102-レンゲ" = "そ、そうだな……たしかに委員長の資格を持つナグサ先輩なら……"
"51210-103-ナグサ" = "わたし、は…… "
"51210-104-ナグサ" = "でき、ない。"
"51210-105-レンゲ" = "はっ！？な、何でだ！？"
"51210-106-ナグサ" = "シュロが言っていた、「委員長としての資格を備えている者」……#nそれは、アヤメのことであって、私じゃない。"
"51210-107-ナグサ" = "私には……できない。"
"51210-108-ナグサ" = "シュロの言う通り……最初から全部、言い訳だったの。"
"51210-109-ナグサ" = "自分の本当の姿を知られるのが怖くて、私は逃げようとした。"
"51210-110-ナグサ" = "本音を話せずに、アヤメの隣に立つことが精一杯で……#nなんとか隣に立てるよう、「ナグサ」という女の子を演じていた。"
"51210-111-ナグサ" = "みんなを、騙していたんだよ。"
"51210-112-ナグサ" = "私そのものが……「コスプレ」だったんだ。"
"51210-113" = "[s] \"ナグサ……。\""
"51210-114-ナグサ" = "ただアヤメの隣にいたくて……アヤメに[ruby=ふさわ]相応[/ruby]しい存在になりたくて。"
"51210-115-ナグサ" = "優等生を演じただけの――ニセモノ。"
"51210-116-ナグサ" = "……言えなかったの。アヤメを目の前で失って、ここに戻った私が……一人で戻った、なんてみんなに言ったら……"
"51210-117-ナグサ" = "絶対に――後ろ指を差された。"
"51210-118-ナグサ" = "こんな私に、資格なんてない。"
"51210-119-ナグサ" = "こんな私が……ユカリを助けられるわけ――"
"51210-120-キキョウ" = "御稜、ナグサ……！！"
"51210-121-ナグサ" = "あ……。"
"51210-122" = "[ns] \"キキョウ、落ち着いて……！\""
"51210-123-ナグサ" = "キキョウ……？"
"51210-124-キキョウ" = "私、ユカリに酷いこと言った。"
"51210-125-キキョウ" = "あんたには帰る場所があるからって。#n百花繚乱ごっこは要らないでしょって。"
"51210-126-キキョウ" = "そんなの思ったことなかったのに……ユカリのためって、自分を騙して……一方的に突き放したの。"
"51210-127-キキョウ" = "それが……あの子をあんな風にしてしまった。"
"51210-128-レンゲ" = "キ、キョウ……。"
"51210-129-ナグサ" = "……。"
"51210-130-キキョウ" = "あなたが……私たちを見捨てて出てったことは、今でも許せない。"
"51210-131-キキョウ" = "今までずっとあなたを待ってたのに、帰ってこなかったことも……。"
"51210-132-キキョウ" = "……でも。"
"51210-133-キキョウ" = "でもね。"
"51210-134-キキョウ" = "私のせいで……"
"51210-135-キキョウ" = "私の、身勝手な発言で傷つけてしまったあの子を……"
"51210-136-キキョウ" = "ユカリを助けられるのは、あなたしかいないの。"
"51210-137-キキョウ" = "私でもレンゲでもない、そしてアヤメ委員長でもない……#n[ruby=・   ・   ・]あなた[/ruby]しかいない。"
"51210-138-キキョウ" = "だから、お願い。"
"51210-139-キキョウ" = "自分勝手なお願いだって、分かってる。#n今さらムシが良すぎるって。"
"51210-140-キキョウ" = "それでも、お願い……！"
"51210-141-キキョウ" = "あの子に、謝りたいの……！"
"51210-142-キキョウ" = "お願い……ナグサ先輩。"
"51210-143-キキョウ" = "どうか……"
"51210-144-レンゲ" = "ナグサ先輩！"
"51210-145-ナグサ" = "あ……"
"51210-146-レンゲ" = "アタシも……アタシもそうなんだ！"
"51210-147-レンゲ" = "アタシだって、こんなことを言う資格はないって分かってるけど！"
"51210-148-レンゲ" = "キキョウと一緒なんだ！"
"51210-149-レンゲ" = "アタシも、ユカリを傷つけてしまったから……謝りたい。"
"51210-150-レンゲ" = "もう一度、会ってちゃんと話したい。"
"51210-151-レンゲ" = "我が儘を言っているのは承知だ。こんな事態になって今さら謝罪したいなんて、自己満足にもほどがあるけど……"
"51210-152-レンゲ" = "……でも。"
"51210-153-レンゲ" = "ユカリが言うように、あの時に戻れるのなら……アタシも……！"
"51210-154-レンゲ" = "だから頼む、ナグサ先輩。"
"51210-155-ナグサ" = "…………私は、みんなを騙して……"
"51210-156-ナグサ" = "嘘を、ついて……"
"51210-157" = "[ns] \"ナグサ、私からもお願い。\""
"51210-158-ナグサ" = "……分かった。 "
"51210-159-ナグサ" = "やってみるよ。"
"51210-160" = "[ns] \"やっぱり簡単には通してくれなさそうだね。\""
"51210-161-レンゲ" = "先生たちは先に行って……！#nここはアタシらに任せてくれ！"
"51210-162-ツバキ" = "そうだね。やる事が決まったからもう大丈夫～#n最大限、足止めすればいいんだよね？"
"51210-163-ツバキ" = "分かりました。足止めならお任せください！"
"51210-164-ツバキ" = "任せてよ、先生！"
"51210-165-キキョウ" = "ナグサ先輩、先生……ユカリを、どうかお願い。 "
"51210-166" = "[ns] \"うん、行こう！ナグサ！\""
"51210-167-ナグサ" = "……！"
"51210-168" = "次回;炎に包まれた街"
