[translation]
"32060-1" = "第6話;真夜中の大騒ぎ（２）"
"32060-2-ハスミ" = "……美食研究会？"
"32060-3-イチカ" = "ところで先輩、今どちらです？早くご命令を頂かないと、このままだとツルギ先輩が発射……飛び出ちゃいそうっすけど。"
"32060-4-ハスミ" = "つ、ツルギはとりあえず止めてください。私は今その、私用で少々外に……。"
"32060-5-イチカ" = "いやー無理っすよ。ハスミ先輩以外じゃそうそう止められな……"
"32060-6-イチカ" = "あっ、ツルギ先輩！行かないでください！あとそっちはドアじゃなく壁――"
"32060-7-イチカ" = "あー……とりあえずあたしらも一旦追いかけて、出撃しますね。"
"32060-8" = "（ピッ）"
"32060-9-ハスミ" = "……。"
"32060-10-アズサ" = "近いな。爆発音からして、ここから1km以内のところか。"
"32060-11-ヒフミ" = "え、えぇっ……！？"
"32060-12-ハスミ" = "……みなさん。"
"32060-13-ハスミ" = "突然のことですみませんが、みなさんの力が必要です。お願いできますでしょうか？"
"32060-14" = "今はエデン条約を目前に控えて、色々と過敏な時期です。この問題が傍から見て「トリニティの正義実現委員会とゲヘナ間の衝突」と捉えられてしまうと、状況が不利になることは想像に難くありません。"
"32060-15-ハスミ" = "つまり、補習授業部と「シャーレ」が一緒に解決してくださる……そういう構図が望ましいのです。先生、お願いできますでしょうか……？"
"32060-16" = "[s] \"うん。よし、じゃあ補習授業部一同出発。\""
"32060-17-アズサ" = "了解した。先生の指示に従う。"
"32060-18-ヒフミ" = "えぇっ！？い、いきなり戦闘ですか……！？あ、あうぅ……。"
"32060-19-ハナコ" = "ふふっ……まあ、先生がそう仰るのであれば♡"
"32060-20-コハル" = "あっ、わ、私も……？先生と……ハスミ先輩と、一緒に……？"
"32060-21-ハスミ" = "いつかこうして肩を並べる時期が来るとは思っていましたが……想像より早かったですね、コハル。"
"32060-22-コハル" = "は、はい！頑張ります……！"
"32060-23-アズサ" = "そういえば、しっかり先生の指揮の下で戦うのは初めてか。遠慮は要らない、先生。私のことは存分に使って。"
"32060-24" = "あらまぁ……♡"
"32060-25" = "[s] \"じゃあ、安全第一で。\""
