[translation]
"32160-1" = "第16話;激戦"
"32160-2" = "合宿所"
"32160-3-アリウスの生徒A" = "こちらです！ターゲットを連れたまま、この建物に入るのを確認しました！"
"32160-4-アリウスの指揮官" = "なるほど……ここに陣地を築いたということか、白洲アズサめ。"
"32160-5-アリウスの生徒B" = "中に通じる入口は二か所のみ！その内一か所はバリケードで塞がれています！"
"32160-6-アリウスの指揮官" = "開いている入口は一つ……いや、そっちは罠だ。塞がれたバリケードを爆発させて、そちらから侵入せよ！"
"32160-7-アリウスの生徒A" = "騒ぎになりそうですが、大丈夫でしょうか？"
"32160-8-アリウスの指揮官" = "ああ、構わん。ちょうど「スクワッド」からも連絡が来た、すぐに増援部隊がトリニティ自治区に入ってくる。"
"32160-9-アリウスの指揮官" = "こうなってはもはやトリニティとの全面抗争も想定した方が良い。しかしできる限りその前に、ターゲットを回収する！"
"32160-10-アリウスの指揮官" = "行くぞ！"
"32160-11-アリウスの指揮官" = "突入！"
"32160-12-アズサ" = "だと思った。"
"32160-13-アリウスの生徒B" = "なぁっ！？"
"32160-14-アリウスの生徒B" = "ぐあぁぁっ！？"
"32160-15-アリウスの指揮官" = "くっ！退くな退くな！攻め入ってしまえば数がある以上、こちらが有利！"
"32160-16-アリウスの生徒" = "なっ、こっちも！？"
"32160-17-アリウスの生徒" = "く、クレイモアだと！？どわあぁっ！？"
"32160-18-アリウスの生徒" = "なんだ、ビニール袋……？い[ruby=即席爆発装置]や、IED！？[/ruby]ぎゃあぁぁっ！！"
"32160-19-アリウスの指揮官" = "……手こずらせてくれたじゃないか、白洲アズサ。"
"32160-20-アズサ" = "……。"
"32160-21-ハナコ" = "……なるほど、だいぶ減りましたね。さすがはアズサちゃん。"
"32160-22-アズサ" = "うん。"
"32160-23-アリウスの指揮官" = "このまま行けば行き止まり、か……ターゲットはどこだ？"
"32160-24-アズサ" = "隠した。"
"32160-25-アリウスの指揮官" = "……早めに吐いた方が良い。他の部隊がこちらに向かい、今にもこの建物を包囲しようとしている。逃げても抵抗しても、どちらにせよ無意味だ。"
"32160-26-アズサ" = "……増員？"
"32160-27-アリウスの指揮官" = "ああ、それも部隊単位でな！"
"32160-28-アズサ" = "……「スクワッド」は？"
"32160-29-アリウスの指揮官" = "「スクワッド」が来るまでも無いさ。それにどうやら、他にやることがあるみたいでね。"
"32160-30-アズサ" = "なら問題無い。"
"32160-31-アリウスの指揮官" = "くっ、この期に及んで……！この先に体育館しか無いのは把握済みだ！"
"32160-32-アリウスの指揮官" = "それに、これ以上トラップが無いこともな！逃がすか、追え！"
"32160-33-アリウスの指揮官" = "……なるほど、逃げたのではなく待ち伏せだったと。"
"32160-34-アリウスの指揮官" = "だが、それだけか？"
"32160-35-アリウスの指揮官" = "たった四人で私たち相手に、何分耐えられると思っているのだ。こんな退路も無い場所で！"
"32160-36-コハル" = "あうぅ……。"
"32160-37-ヒフミ" = "……っ。"
"32160-38-ヒフミ" = "その通り、もう退路はない。お前たちは逃げられない。"
"32160-39-ヒフミ" = "ですね、一先ず仕上げと行きましょうか♡"
"32160-40" = "[s] \"待ってたよ。\""
"32160-41-アリウスの指揮官" = "っ！"
"32160-42-ヒフミ" = "ご存じかは分かりませんが……補習授業部の担当であり、「シャーレ」の顧問の先生です♡"
"32160-43-ヒフミ" = "殲滅戦を始める。先生、指示を。"
"32160-44" = "[ns] \"じゃあ補習授業部、行こう。\""
