[translation]
"2002703-1" = "ペース配分"
"2002703-2" = "（今日のシロコは、朝からとてもテンションが高いように見えた）"
"2002703-3-シロコ" = "ん。"
"2002703-4-シロコ" = "先生、あっちも。"
"2002703-5" = "（シロコのペースで、海や丘、森など島中を何時間も散策していると……）"
"2002703-6" = "（……体力が尽きて倒れてしまった）"
"2002703-7-シロコ" = "先生……！？"
"2002703-8-シロコ" = "どうしたの、大丈夫？"
"2002703-9-シロコ" = "かぶれちゃった？#n虫に……いや、もしかしたら海で――"
"2002703-10-シロコ" = "――ん、違う？"
"2002703-11-シロコ" = "えっと、それなら……"
"2002703-12" = "[s1] \"少し休めば大丈夫。\"\n[s2] \"歩き回ったから、体力が……。\""
"2002703-13-シロコ" = "……あ。"
"2002703-14-シロコ" = "ごめん、先生……。"
"2002703-15-シロコ" = "朝から休憩してなかったよね。"
"2002703-16-シロコ" = "そんなつもりじゃ、なかったんだけど……"
"2002703-17-シロコ" = "1人で……舞い上がっちゃった。"
"2002703-18-シロコ" = "先生が疲れてるのにも、気付けなくて……"
"2002703-19-シロコ" = "……ごめん。"
"2002703-20-シロコ" = "…………。"
"2002703-21" = "[s3] \"すぐに復活するから……大丈夫。\"\n[s4] \"私も夢中で楽しんでたから、気にしないで。\""
"2002703-22-シロコ" = "……うん。"
"2002703-23-シロコ" = "少し横になった方がいいかも。#nここなら涼しいし風もあるから、休むのにピッタリ。"
"2002703-24-シロコ" = "寝てる間は、見てるから。ゆっくり休んで。"
"2002703-25" = "[s5] \"シロコは疲れてないの？\"\n[s6] \"ずっと歩いてたよね？\""
"2002703-26-シロコ" = "大丈夫、もう一周しても余裕。"
"2002703-27-シロコ" = "それに……"
"2002703-28-シロコ" = "2人とも寝てると無防備になるから……一応、起きておく。"
"2002703-29-シロコ" = "私のことは気にしないで、先生はゆっくり寝て。"
"2002703-30-シロコ" = "先生が元気になってくれたら……私も、気が楽になる。"
"2002703-31-シロコ" = "だから……"
"2002703-32-シロコ" = "ん。"
"2002703-33-シロコ" = "おやすみ、先生。"
"2002703-34" = "（シロコの視線を感じながら、優しい眠りに落ちていった）"
"2002703-35" = "（おかげで、身体の疲れはどこかに吹き飛んだ）"
"2002703-36" = "（……眠りから覚めると、目の前には夕焼けに照らされた海が広がっていた）"
"2002703-37" = "[ns7] \"……あれ、海？\"\n[ns8] \"こんなところで寝てたっけ……？\""
"2002703-38-シロコ" = "……あ。"
"2002703-39-シロコ" = "おはよう、先生。"
"2002703-40-シロコ" = "ぐっすり寝てたから、私が背負ってきた。"
"2002703-41-シロコ" = "森の中は虫が多かったから。"
"2002703-42-シロコ" = "身体はどう……？#nまだ寝てても大丈夫だよ。"
"2002703-43-シロコ" = "……ん、私？"
"2002703-44-シロコ" = "他に行ってみたい場所……？"
"2002703-45-シロコ" = "……ううん、大丈夫。"
"2002703-46-シロコ" = "リゾートじゃないと出来ないことをしたかっただけだから。"
"2002703-47-シロコ" = "でも、こうして先生と過ごす時間も……"
"2002703-48-シロコ" = "…………。"
"2002703-49-シロコ" = "……ん。"
"2002703-50-シロコ" = "……楽しいよ。"
"2002703-51-シロコ" = "でも、先生に無理はしてほしくない。#n私だけ楽しむのは……"
"2002703-52-シロコ" = "……違うと思う。"
"2002703-53-シロコ" = "これからは……2人でゆっくり過ごしたい。"
"2002703-54-シロコ" = "……だから、先生のペースで行こう。"
"2002703-55-シロコ" = "うん。きっと、その方がいい。"
"2002703-56-シロコ" = "……もうこんな時間だし、今日はここまでかな。"
"2002703-57-シロコ" = "帰ろ、先生。"
"2002703-58-シロコ" = "……ん、しっかり掴まってて。"
"2002703-59" = "[ns9] スッと立ち上がる。\n[ns10] \"もう大丈夫、シロコのおかげで元気になったよ。\""
"2002703-60-シロコ" = "…………。"
"2002703-61-シロコ" = "……うん。"
