[translation]
"1001020-1" = "備え有れば憂いなし？"
"1001020-2" = "アビドス自治区通り"
"1001020-3" = "（行政関係の事情で、アビドスを訪れた）"
"1001020-4-シロコ" = "あ、先生。今日はどうしたの？"
"1001020-5-シロコ" = "……アビドスに用事？"
"1001020-6-シロコ" = "ちょうど私も、これから学校に行くところ。"
"1001020-7-シロコ" = "……こんなところで会うとは思わなかったって？"
"1001020-8-シロコ" = "……ん。"
"1001020-9-シロコ" = "……。"
"1001020-10-シロコ" = "偶然、だね。"
"1001020-11-シロコ" = "……。"
"1001020-12-シロコ" = "……うん、偶然。"
"1001020-13" = "[s] \"じゃあせっかくだし、学校まで一緒に行こうか。\""
"1001020-14-シロコ" = "ん。"
"1001020-15" = "[ns] \"何だか、前のことを思い出すね。\""
"1001020-16-シロコ" = "前の……？"
"1001020-17-シロコ" = "あ……先生が倒れてた時の？"
"1001020-18" = "[s] \"うん、シロコのおかげで助かったよ。\""
"1001020-19-シロコ" = "別に、大したことじゃ……。"
"1001020-20-シロコ" = "でも、うん。良かった。"
"1001020-21-シロコ" = "……それ以外にも色々？"
"1001020-22-シロコ" = "それは、うん……。"
"1001020-23-シロコ" = "先生にしてあげられることなら、っていうか……。"
"1001020-24-シロコ" = "……や、何でもない。"
"1001020-25-シロコ" = "自転車で来てるのに歩かせて悪い……？"
"1001020-26-シロコ" = "大丈夫、別に気にしてない。"
"1001020-27-シロコ" = "それにこれ、見た目よりも軽いから。"
"1001020-28" = "（シロコと色々な話をしながら、学校へと向かった）"
"1001020-29" = "[ns1] \"あれは……？\"\n[ns2] \"何かこっちに向かってきてない！？\""
"1001020-30-シロコ" = "……ああ。"
"1001020-31-シロコ" = "大丈夫、私のドローンだから。"
"1001020-32" = "（シロコが慣れた手付きでドローンを回収して、鞄に入れた）"
"1001020-33" = "[s] \"何事かと思った……。\""
"1001020-34-シロコ" = "ん。偶然手に入って、少し改造を……。"
"1001020-35" = "[s] \"偶然ドローンを……？\""
"1001020-36-シロコ" = "うん、偶然。"
"1001020-37-シロコ" = "どうかした？"
"1001020-38" = "[s3] \"な、何でもないです……。\"\n[s4] \"大丈夫、信じてるから……。\""
"1001020-39-シロコ" = "割と、色々使えるんだよ？"
"1001020-40-シロコ" = "ライディング中にGPSをキャッチしたり、撮影用として使ったり。"
"1001020-41" = "[s] \"それは良かった……。\""
"1001020-42-チンピラA" = "だからさぁ、ちょっとでも良いんだって。"
"1001020-43-チンピラB" = "そうそう、何も大金をせびってるんじゃないんだからさぁ！"
"1001020-44-善良な市民" = "も、もう本当にギリギリなんです！勘弁してください！"
"1001020-45-チンピラA" = "うるせぇな、乾いた雑巾でも絞るんだよ！"
"1001020-46-善良な市民" = "も、もう無理です、一滴も出ません……！"
"1001020-47-シロコ" = "……。"
"1001020-48" = "（突然シロコがドローンを始動させた）"
"1001020-49-チンピラA" = "あ痛たたたたた！？"
"1001020-50-チンピラB" = "ど、ドローン？っていうかミサイル！？"
"1001020-51-チンピラA" = "に、逃げるぞ！"
"1001020-52" = "[ns] \"……撮影用のドローンって話だったのでは？\""
"1001020-53-シロコ" = "それは……。"
"1001020-54-シロコ" = "万が一の時に備えて。"
"1001020-55" = "[s] \"そんな「軽くちょろっとね」みたいな言い方でミサイルを……。\""
"1001020-56-シロコ" = "大したことじゃない。"
"1001020-57-ヘルメット団A" = "まあまあ、とにかくサインさえくれれば良いからさ！"
"1001020-58-ヘルメット団B" = "ほら、うちらを信じてくれよ！"
"1001020-59-かわいそうな市民" = "し、信じろって自分から言うやつにろくなのは……。"
"1001020-60" = "……。"
"1001020-61-ヘルメット団A" = "うわぁっ！？ミサイル！？"
"1001020-62-ヘルメット団B" = "おい、早く逃げろ！"
"1001020-63-暴走族A" = "だからちょっとエンジンを借りるだけだって、すぐ返すからよ！"
"1001020-64-暴走族B" = "まあ返した時の状態は保証できないけどな！"
"1001020-65-シロコ" = "……。"
"1001020-66-暴走族A" = "おい、何か飛んできてるぞ！？"
"1001020-67-暴走族B" = "ウチらのマシンがーー！？"
"1001020-68" = "[ns] \"……撮影用、なんだよね？\""
"1001020-69-シロコ" = "……うん。あくまでミサイルはおまけ。"
"1001020-70" = "[s] \"……すごいおまけだね。\""
"1001020-71-シロコ" = "……すごいでしょ。"
"1001020-72" = "[s5] \"あの、一応聞いておくんだけど。\"\n[s6] \"そのドローン、あんまり積極的に使い過ぎないようにね……？\""
"1001020-73-シロコ" = "……大丈夫。"
"1001020-74-シロコ" = "あくまで、万が一のためだから。"
"1001020-75-シロコ" = "銀行を襲う時とか。"
"1001020-76" = "[ns] \"それがダメなの！！\""
