[translation]
"21100-1" = "第10話;再び、廃墟へ"
"21100-2" = "廃墟"
"21100-3-モモイ" = "……先生っ！"
"21100-4-モモイ" = "伏せて！！"
"21100-5" = "（ドカアアァァァン！）"
"21100-6-ユズ" = "うぅ……みんな、大丈夫？"
"21100-7-ミドリ" = "私は平気、でも思ったより火力が……先生、大丈夫ですか！？"
"21100-8" = "[ns] \"うん、大丈夫。\""
"21100-9-ユズ" = "来た、ロボットたち……！"
"21100-10-ユズ" = "大丈夫、まだ引き付けられる……！"
"21100-11-ユズ" = "……よし、"
"21100-12-ユズ" = "アリスちゃん！"
"21100-13-ユズ" = "やっちゃって！"
"21100-14-アリス" = "（こくり）"
"21100-15-アリス" = "今日の私の役割は、光属性広域アタッカー……"
"21100-16-アリス" = "前方のモンスターたちを、殲滅します。"
"21100-17-アリス" = "……光よ！"
"21100-18" = "（ドカアアァァン！）"
"21100-19-モモイ" = "よし、成功！"
"21100-20-ミドリ" = "アリスちゃん、すごい！"
"21100-21-ユズ" = "ま、まだ！敵の第二陣が接近中！"
"21100-22-ユズ" = "ここで立て続けはちょっと……流石に不利だよ、撤退しよう！先生もいるんだし、安全第一で作戦を立て直した方が、きっと……！"
"21100-23-ユズ" = "……ううん。"
"21100-24-ユズ" = "……ここで退くわけにはいかない、突破しよう。"
"21100-25-ユズ" = "ええっ！？"
"21100-26-ユズ" = "多分ここで退いても、状況は悪くなる一方。ロボットは今の戦闘音を聞いて、この後どんどん集まり続けるはず。"
"21100-27-ユズ" = "全部でどれくらい数がいるのか分からないけど、多分今が一番手薄……G.Bibleの座標が示してるあの「工場」に入るには、今が最大のチャンスだと思う。"
"21100-28-ミドリ" = "で、でも……。"
"21100-29-アリス" = "大丈夫です。"
"21100-30-ミドリ" = "アリスちゃん……？"
"21100-31-アリス" = "私たちは今まで一緒に、27回のダンジョン探索と、139回のレイドバトルを成功させてきました。"
"21100-32-アリス" = "今回もきっと……このパーティなら、勝利できるはずです。"
"21100-33-ミドリ" = "で、でも、それはゲームの話でしょ！？"
"21100-34" = "どう転んでも、危険はある……わたしも、頑張るから。"
"21100-35-ミドリ" = "で、でも先生は？私たちと違って、攻撃を受けたら……！"
"21100-36-アリス" = "安心してください。"
"21100-37-ミドリ" = "えっ？"
"21100-38-アリス" = "どれだけ危険な状況であっても、アリスが先生を守ります。"
"21100-39-アリス" = "先生……アリスを信じて、私たちと一緒に来てくれますか？"
"21100-40" = "[s1] \"もちろん。\"\n[s2] \"うん。私も仲間として、私にできることをするね。\""
"21100-41-アリス" = "……！"
"21100-42-アリス" = "……！"
"21100-43-アリス" = "パンパカパーン！先生があらためて、仲間になりました！"
"21100-44" = "ふぅ……分かった、私も覚悟を決める！"
"21100-45-ミドリ" = "ゲーム開発部、敵を突破するよ！"
"21100-46-ミドリ" = "先生、指揮をお願いします！"
