[translation]
"21180-1" = "第18話;G.Bible"
"21180-2" = "ミレニアム・ゲーム開発部"
"21180-3-アリス" = "G.Bible……起動！"
"21180-4" = "[56cd7b]G.Bibleの世界へようこそ。"
"21180-5-モモイ" = "は、始まった！"
"21180-6" = "[56cd7b]最高のゲームとは何か……この質問に対して、#n[56cd7b]世界中で様々な答えが模索され続けてきました。"
"21180-7" = "[56cd7b]作品性、人気、売上、素晴らしいストーリーや爽快感、鳥肌の立つ演出など。"
"21180-8" = "[56cd7b]そういったものが最高のゲームの「条件」として挙げられることは多いですが、#n[56cd7b]それらは全て、あくまで「真理」の枝葉に過ぎません。"
"21180-9" = "[56cd7b]最高のゲームを作る秘訣、それはたった一つです。"
"21180-10" = "[56cd7b]そしてこのG.Bibleには、その真理が秘められています。"
"21180-11-モモイ" = "い、いよいよ！"
"21180-12-ミドリ" = "何だかすごそう……。"
"21180-13" = "[56cd7b]最高のゲームを作るたった一つの真理、秘密の方法……#n[56cd7b]それを今こそお教えしましょう。"
"21180-14-アリス" = "来ます……っ！"
"21180-15" = "[56cd7b]……"
"21180-16" = "[56cd7b]……"
"21180-17" = "[56cd7b]ゲーム"
"21180-18" = "[56cd7b]を"
"21180-19" = "[56cd7b]愛"
"21180-20" = "[56cd7b]し"
"21180-21" = "[56cd7b]な"
"21180-22" = "[56cd7b]さ"
"21180-23" = "[56cd7b]い"
"21180-24-モモイ" = "おお……オープニング、みたいな感じかな。それっぽい！"
"21180-25-ミドリ" = "そ、そう？"
"21180-26" = "[56cd7b]ゲームを愛しなさい"
"21180-27-ユズ" = "……まさか、これで終わり……じゃ、ないよね？"
"21180-28-ミドリ" = "な、何かバグってるんじゃない？"
"21180-29-モモイ" = "ちょっと待って！"
"21180-30-モモイ" = "ええっと、設定変更はどこから……。"
"21180-31" = "[56cd7b]ゲームを愛しなさい"
"21180-32" = "[56cd7b]あなたがこのボタンを押したということは、#n[56cd7b]ファイルが壊れた、もしくは何か問題があったのでは、"
"21180-33" = "[56cd7b]何らかのエラーが生じたのでは……と疑っている状況なのでしょう。"
"21180-34-モモイ" = "あっ、やっぱり！このまま終わるはずないよね！"
"21180-35" = "[56cd7b]しかし、[wa:500]エラーではありません。"
"21180-36-ミドリ" = "嘘ぉ！？"
"21180-37" = "[56cd7b]残念ですが、これが結論です。"
"21180-38" = "[56cd7b]ゲームを愛しなさい！"
"21180-39-モモイ" = "そ、そんなはずはない！きっと何かエラーが……！"
"21180-40-ミドリ" = "ファイルの損傷とか修正も見当たらない……最後の転送情報、ファイルサイズ、それにデータ構成も問題無し。"
"21180-41-ユズ" = "そ、それじゃ、本当に……。"
"21180-42-ユズ" = "こ、これで終わり！？"
"21180-43-ユズ" = "……お、"
"21180-44-ユズ" = "お姉ちゃん……私たち、何か悪い夢でも見て……"
"21180-45-モモイ" = "終わりだああぁぁぁああ！！！"
"21180-46" = "（そして今……）"
"21180-47-アリス" = "あの、モモイ……デイリークエストしないのですか？"
"21180-48-アリス" = "いつも、「デイリークエストより大事なものなんてない」と言っていたのに……。"
"21180-49-アリス" = "アリス……私のHPはもうゼロだよ……。"
"21180-50-アリス" = "えっと……。"
"21180-51-アリス" = "ミドリ……？"
"21180-52-アリス" = "ごめんね、アリスちゃん……知ってたけど、現実って元々こういうものなの……そう、つまりこれがトゥルーエンド……ハッピーエンドとはまた別の到達点……。"
"21180-53-アリス" = "……。"
"21180-54-アリス" = "ゆ、ユズは……ユズはどこに？"
"21180-55-アリス" = "多分、またロッカーの中に引きこもってるんだと思う。よく見て、ロッカーがたまにプルプルしてるでしょ？"
"21180-56-アリス" = "今のみんなの姿は……"
"21180-57-アリス" = "まるで、正気がログアウトしたみたいです。"
"21180-58-アリス" = "うぅっ……。"
"21180-59-モモイ" = "仕方ないじゃん、最後の手段だったのに！それが、あんな誰でも知ってる文章が一つ入ってるだけだなんて！釣りにもほどがある！"
"21180-60" = "知ってた！世界にはそんな、それ一つで全部が変わって上手く行くような、便利な方法なんか無いって！でも期待ぐらいしたっていいじゃん！うああぁぁぁんっ！"
"21180-61-ミドリ" = "はぁ……。"
"21180-62-ミドリ" = "ごめんね、アリスちゃん……私たちは……G.Bible無しじゃ、良いゲームは作れない……。"
"21180-63-アリス" = "……。"
"21180-64-アリス" = "いいえ。"
"21180-65-アリス" = "否定します。"
"21180-66-アリス" = "アリスは『テイルズ・サガ・クロニクル』をやるたびに思います。"
"21180-67-アリス" = "あのゲームは、面白いです。"
"21180-68-ミドリ" = "え？"
"21180-69-アリス" = "感じられるのです。"
"21180-70-アリス" = "モモイが、ミドリが、ユズが……。"
"21180-71-アリス" = "このゲームを、どれだけ愛しているのかを。"
"21180-72-アリス" = "そんな、たくさんの想いが込められたあの世界で旅をすると……"
"21180-73-アリス" = "……胸が、高鳴ります。"
"21180-74-アリス" = "仲間と一緒に新しい世界を旅する、あの感覚は……。"
"21180-75-アリス" = "夢を見るというのが、どういうことなのか……その感覚を、アリスに教えてくれました。"
"21180-76-アリス" = "だから、待望のエンディングに近づくほどに、あんなに苦しんだのに、思ってしまうのです……。"
"21180-77-アリス" = "この夢が、覚めなければいいのに……と。"
"21180-78-アリス" = "アリスは、そう思うのです。"
"21180-79-モモイ" = "アリス……。"
"21180-80-ユズ" = "……。"
"21180-81" = "ってうわっ、ユズちゃん！？いつからそこに！？"
"21180-82-ユズ" = "『テイルズ・サガ・クロニクル』の話が始まった時から……。"
"21180-83-モモイ" = "最初からいたの！？"
"21180-84-ユズ" = "……作ろう。"
"21180-85-ミドリ" = "え？"
"21180-86-ユズ" = "わたしの夢は……わたしが作ったゲームを、みんなに面白いって言ってもらうこと。"
"21180-87-ユズ" = "でも、わたしが初めて作った『テイルズ・サガ・クロニクル』のプロトタイプは……四桁以上の低評価コメントと、冷やかしだけで終わっちゃって……。"
"21180-88-ユズ" = "それが辛くて、ゲーム開発部に引きこもってた時……。"
"21180-89" = "二人が、訪ねてきてくれた。"
"21180-90" = "（6か月前……）"
"21180-91" = "[56cd7b]これがゲーム？"
"21180-92" = "[56cd7b]これを作った人の頭の中、逆に気になる……。"
"21180-93" = "[56cd7b]それはさすがに脳みそ……って言おうと思ったけど、本当に入ってるのか怪しいね。"
"21180-94" = "[56cd7b]ゲームのことをよく知らない人が作ってない？"
"21180-95" = "[56cd7b]身の程を知った方が良い。"
"21180-96" = "[56cd7b]これはゲームなんかじゃない、ゲームによく似たゴミだよ。"
"21180-97-ユズ" = "うぅ……。"
"21180-98-ユズ" = "やめて……ごめんなさい、ごめんなさい……。"
"21180-99-ユズ" = "もうお願いだから……許して……！"
"21180-100" = "（ドンドンドン！）"
"21180-101-ユズ" = "ひぃっ！"
"21180-102-ユズ" = "だ、誰……？"
"21180-103-？？？" = "えっと、ここって『テイルズ・サガ・クロニクル』のプロトタイプを作った、ミレニアムのゲーム開発部で合ってますか？"
"21180-104-ユズ" = "な、何……？今度は直接……？"
"21180-105-ユズ" = "ご、ごめんなさい、ごめんなさい……！もう二度とゲームは作りません、だから、許して……！"
"21180-106-？？？" = "えぇっ！？"
"21180-107-？？？" = "何言ってるんですか、こんなに面白いのに！プロトタイプだけ作ってやめちゃうなんて！"
"21180-108-？？？" = "続き、すごい気になってるんですよ！？ここまでワクワクさせておいて、そんなの無しでしょ！"
"21180-109-ユズ" = "……え？"
"21180-110-？？？" = "『テイルズ・サガ・クロニクル』、すっごく面白かったです！"
"21180-111-？？？" = "お姉ちゃん、徹夜でやってたもんね。"
"21180-112-？？？" = "ミドリだってニヤニヤしながらプレイしてたじゃん！もともとゲームにそんな興味なかったのに！"
"21180-113-？？？" = "え、う、うーん……確かに、ドットだけどキャラとかすごい可愛かったし……。"
"21180-114-？？？" = "とにかく、あの！失礼します！"
"21180-115" = "（ガチャッ！）"
"21180-116-モモイ" = "……！？"
"21180-117-モモイ" = "あなたがUZ様！？"
"21180-118" = "えっ……あ、は、はい……。"
"21180-119-ミドリ" = "ファンです！！"
"21180-120-モモイ" = "私も、ミドリも！UZ様みたいに、面白いゲームが作りたいです！"
"21180-121-ユズ" = "……っ！！"
"21180-122" = "……"
"21180-123" = "……それで、二人が来てくれた。"
"21180-124-ユズ" = "一緒に『テイルズ・サガ・クロニクル』を完成させて……今年のクソゲーランキング1位になっちゃったけど……。"
"21180-125-ユズ" = "うっ……。"
"21180-126-ユズ" = "……。"
"21180-127-ユズ" = "その後、アリスちゃんが訪ねてきてくれて……。"
"21180-128-ユズ" = "面白いって、言ってくれた。それで、わたしの夢は叶ったの。"
"21180-129-ユズ" = "心の通じ合う大事な仲間たちと、一緒にゲームを作って、それを面白いって言ってもらう……ずっと一人で思い描いてるだけだった、その夢が。"
"21180-130-ユズ" = "……。"
"21180-131-ユズ" = "これ以上は、欲張りかもだけど。叶うなら、わたしはこの夢が……この先も、終わらないでほしい。"
"21180-132-ユズ" = "ユズちゃん……。"
"21180-133-ユズ" = "……うん、よし！"
"21180-134" = "ねえ、今からミレニアムプライスまで、時間どれぐらい残ってる？"
"21180-135-ミドリ" = "お姉ちゃん……！"
"21180-136-アリス" = "6日と4時間38分です。"
"21180-137-モモイ" = "……それだけあれば十分。"
"21180-138-モモイ" = "さあ、ゲーム開発部一同！"
"21180-139-モモイ" = "『テイルズ・サガ・クロニクル２』の開発、始めよう！！"
"21180-140-アリス" = "うん！"
"21180-141" = "次回;ダブルオー"
