[translation]
"2004005-1" = "京極サツキは聞いている"
"2004005-2" = "（サツキからの連絡後、しばらくして……）"
"2004005-3-サツキ" = "こんにちは、先生。"
"2004005-4" = "[s] \"なんだかご機嫌だね、サツキ……。\""
"2004005-5-サツキ" = "うふふっ。そりゃあもう、ね？"
"2004005-6-サツキ" = "何を隠そう、偉大なる「NKウルトラ計画」に進捗があったのよ。"
"2004005-7-サツキ" = "だから、その記念すべき1人目の被験者を先生に決めたわ。"
"2004005-8-サツキ" = "ん？先生の意志？もちろんそんなものは関係ないわよ。"
"2004005-9-サツキ" = "[ruby=パンデモニウム・ソサエティー]万魔殿の予[/ruby]備協力者にとって、絶対に喜ばしいことだもの。"
"2004005-10-サツキ" = "人って、だいたい「一番目の」ことを記憶するでしょう？"
"2004005-11-サツキ" = "強化された「NKウルトラ計画」の最初の実験体になる機会はそうないわ。#n光栄に思いなさい？"
"2004005-12" = "[s] \"今、実験体って言わなかった……？\""
"2004005-13-サツキ" = "細かいことを気にしないの。#nそういえば、この間気づいたのよ。"
"2004005-14-サツキ" = "先生には脅しも拷問も効かない……"
"2004005-15-サツキ" = "なら、残された方法は一つ。そう、実験よ！"
"2004005-16-サツキ" = "さあ、心機一転！より強化されたNKウルトラ計画を体験して頂戴！"
"2004005-17" = "（またサツキに促されるまま椅子に座ってしまった……）"
"2004005-18-サツキ" = "今から様々な催眠術を試していくわ。"
"2004005-19-サツキ" = "さあ、先生はどこまで耐えられるかしら？うふふっ。"
"2004005-20-サツキ" = "まずは一つ目……"
"2004005-21-サツキ" = "こっちよ。私の指先を見て集中して。"
"2004005-22-サツキ" = "ぐるぐる……ぐるぐる……"
"2004005-23" = "[ns] \"これは……\""
"2004005-24" = "[ns] \"トンボを捕まえる時の方法……？\""
"2004005-25-サツキ" = "集中しなさい、集中！#n被験者にも頑張ってもらわないと催眠効果が得られないのよ！"
"2004005-26" = "[s] \"それ、なんかおかしくない！？\""
"2004005-27-サツキ" = "そーれそれ……ぐ～るぐる……ぐ～るぐる……。"
"2004005-28" = "（サツキは指を回し続けたが、少しクラクラするだけで催眠効果はなかった……）"
"2004005-29-サツキ" = "フンッ、やっぱりこれじゃダメみたいね。"
"2004005-30-サツキ" = "でもこれはまだ序の口よ。時間もたっぷりあるし……"
"2004005-31-サツキ" = "次に移ろうかしら。先生、集中して。"
"2004005-32-サツキ" = "はい、このスマホの画面を見て頂戴。"
"2004005-33" = "[s] \"これは……\""
"2004005-34-サツキ" = "うふふっ。分かっちゃったかしら？#nこれは情報部の技術の集大成「ぐるぐるアプリ」よ。"
"2004005-35-サツキ" = "視線を逸らさない！真ん中の回る画面に集中！！"
"2004005-36-サツキ" = "これを見たあなたは、どんどん抜け出せなくなぁ～る。"
"2004005-37-サツキ" = "私の言葉に服従するようになぁ～る。なんでも聞くようになぁ～る～"
"2004005-38-サツキ" = "……。"
"2004005-39-サツキ" = "これなら完璧かしら？"
"2004005-40-サツキ" = "先生、立ち上がってバク宙を200回よ。"
"2004005-41" = "[s] \"できるかっ！\""
"2004005-42-サツキ" = "フンッ……今回もダメみたいね。"
"2004005-43-サツキ" = "このアプリならみんなへろへろだと思ったのに……"
"2004005-44-サツキ" = "さすが先生ね。この常人を超越する精神力。"
"2004005-45-サツキ" = "でも私の覚悟と手腕だってすごいんだから！覚悟しておきなさい？"
"2004005-46" = "（その後もサツキの催眠術は続いた……）"
"2004005-47" = "（もちろん、どれも効果はなかった）"
"2004005-48-サツキ" = "……。"
"2004005-49-サツキ" = "ふぅ……いくら先生とはいえ、ここまで「NKウルトラ計画」に耐えるなんて。"
"2004005-50" = "[s] \"サツキ、そろそろ時間も遅いし今日はもう……\""
"2004005-51-サツキ" = "いいえ！諦めないわ！"
"2004005-52-サツキ" = "こうなったからには初心に帰るまでよ。"
"2004005-53" = "[s] \"私はもう無理かも！？\""
"2004005-54-サツキ" = "弱音を言っても無駄よ！今までもちゃんと耐えられていたじゃない？"
"2004005-55" = "（正面にいるサツキが肩に手を乗せてきた）"
"2004005-56-サツキ" = "これで最後よ。これでも効果がないのなら、今日は勘弁してあげるわ。"
"2004005-57-サツキ" = "気持ちを込めれば、前とは違う効果が絶対あるはず。"
"2004005-58-サツキ" = "さあ、こっち見て頂戴。"
"2004005-59-サツキ" = "私の言葉に絶対服従するようになぁ～る……命令に従うようになぁ～る……。"
"2004005-60-サツキ" = "ねえ……ところで……。"
"2004005-61-サツキ" = "コイン、どっちから振ってたかしら……。"
"2004005-62-サツキ" = "左……？右……？"
"2004005-63" = "[s] \"右……？\""
"2004005-64-サツキ" = "……それって逆じゃない！？"
"2004005-65-サツキ" = "えっ、そんな……！？#n私、自分に催眠をかけて――"
"2004005-66" = "[s] \"サツキ……！？\""
"2004005-67" = "[wa:670]― [log=사츠키]うう……[wa:1370]なによ、[wa:810]これ……？[/log]"
"2004005-68" = "[wa:850]― [log=사츠키]へ、[wa:410]変だわ……[wa:2030]先生の[wa:920]命令に、[wa:1000]従わないと[wa:710]いけない[wa:480]気持ちに……[/log]"
"2004005-69" = "[ns] \"私は風紀委員会と仲良くします、って言ってみて？\""
"2004005-70" = "[wa:520]― [log=사츠키]え、[wa:370]えっ……[wa:1830]はい……[/log]"
"2004005-71" = "[wa:200]― [log=사츠키]……[wa:650]私は、[wa:1280]風紀[wa:830]委員会と……[wa:2060]仲良く、[wa:1570]します。[/log]"
"2004005-72" = "[wa:200]― [log=사츠키]……[wa:650]でも[wa:1060]マコトちゃんなら[wa:720]まだしも、[/log]"
"2004005-73" = "[wa:270]― [log=사츠키]私は別に[wa:910]仲が悪いわけじゃないのよ。[/log]"
"2004005-74" = "[ns] \"じゃあ「もう先生に意地悪しません」って約束して！\""
"2004005-75" = "[wa:570]― [log=사츠키]う、[wa:560]うん？[/log]"
"2004005-76" = "[wa:780]― [log=사츠키]くっ……[wa:1800]私は……[wa:1710]先生に……[wa:2090]意地悪……[wa:1640]しませ、[wa:1550]ん……[/log]"
"2004005-77" = "[wa:570]― [log=사츠키]ひ、[wa:750]卑怯よ！[/log]"
"2004005-78" = "[wa:850]― [log=사츠키]大人の[wa:490]くせに、[wa:620]催眠で[wa:620]私に[wa:410]好き勝手して！[/log]"
"2004005-79" = "[ns] \"誤解を招く発言はやめて……\""
"2004005-80" = "[ns] \"そもそも私にしていたことでしょ！？\""
"2004005-81" = "[wa:570]― [log=사츠키]ふん、[wa:1290]この私に[wa:700]催眠を[wa:710]かけるだなんて……[/log]"
"2004005-82" = "[wa:760]― [log=사츠키]油断ならないわね、[wa:1660]先生。[/log]"
"2004005-83" = "[wa:900]― [log=사츠키]どう？[wa:1250]私の[wa:430]NKウルトラ計画に[wa:1340]参加する気はない？[/log]"
"2004005-84" = "[ns] \"いや……もう終わりにしない？\""
"2004005-85" = "[wa:570]― [log=사츠키]は、[wa:830]はい……[wa:1800]ご命令なら……[/log]"
"2004005-86-サツキ" = "うっ……こんな……。"
"2004005-87-サツキ" = "本気の催眠だったから、長引きそう……うぇ……。"
"2004005-88-サツキ" = "先生がどんな命令をしても抵抗できないじゃない……。"
"2004005-89" = "[ns] \"ところでサツキは何でそんなに人を操りたいの？\""
"2004005-90-サツキ" = "え……？"
"2004005-91-サツキ" = "それは……"
"2004005-92-サツキ" = "世界平和のため、よ。"
"2004005-93" = "[s1] \"思ったより壮大だった！？\"\n[s2] \"もう少し詳しく聞かせてくれない？\""
"2004005-94-サツキ" = "世界が平和になったら……痛いこともなくなるもの。"
"2004005-95-サツキ" = "そう……私は……"
"2004005-96-サツキ" = "痛いのがイヤ！大嫌いなの！！"
"2004005-97-サツキ" = "白い服が汚れるよりも、広告をスキップできないことよりも！"
"2004005-98-サツキ" = "銃に撃たれたり、手榴弾の破片で怪我するのがイヤなのよ！"
"2004005-99" = "[s] \"私も同じだけど……それって世界平和と関係が……？\""
"2004005-100-サツキ" = "人を操る事ができたら、そういうことも起きないでしょう？"
"2004005-101-サツキ" = "銃を撃てないようにしたり、むやみに手榴弾を投げないようにしたり……。"
"2004005-102-サツキ" = "イブキやマコトちゃんにも痛い思いをさせずに済むわ。"
"2004005-103-サツキ" = "ふふっ……そういう思いから「NKウルトラ計画」は始まったのよ。"
"2004005-104-サツキ" = "みんなを好きに操って、このキヴォトスを痛みのない世界にすること！！"
"2004005-105-サツキ" = "それが私の――京極サツキの究極目標よ！"
"2004005-106" = "[s] \"やり方はちょっと変だけど……たしかにすごい目標だね！\""
"2004005-107-サツキ" = "……私の究極の目標を教えたのは先生だけよ。"
"2004005-108-サツキ" = "誰にも話すつもりはなかったのだけど。"
"2004005-109-サツキ" = "ふぅ……次は私をどう辱めるつもりかしら？次の命令は？"
"2004005-110-サツキ" = "覚悟はできてるわ、さあ言ってみなさい！"
"2004005-111" = "[s] \"じゃあ、帰ってゆっくり休んでね。\""
"2004005-112-サツキ" = "くっ……やっぱりそうだと思って……"
"2004005-113-サツキ" = "え……？"
"2004005-114-サツキ" = "情報部の秘密を探るとか、マッサージをしてとか、コンビニに買い物に行ってきて、とかじゃなくて……？"
"2004005-115-サツキ" = "せっかく私を操れるのよ……？#nこのまま本当に帰って休んでいいの？"
"2004005-116-サツキ" = "今もこうやって、体が勝手に動いて帰ろうとしているのよ？"
"2004005-117" = "[s] \"うん。お疲れさまサツキ。気をつけてね。\""
"2004005-118-サツキ" = "……。"
"2004005-119-サツキ" = "さすが先生ね。ふふっ……絶好のチャンスなのに一切惑わされない……"
"2004005-120-サツキ" = "この器……さすがは万魔殿の……"
"2004005-121" = "（サツキは何かを言い続けていたけど、オフィスを出ていってしまったので最後までよく聞き取れなかった）"
