[translation]
"1014806-1" = "アウスフルークレリンと夏の巡回？"
"1014806-2" = "（シャーレに向かう途中、巡回中の虎丸と遭遇した）"
"1014806-3" = "[ns] \"やあ、イロハ。\""
"1014806-4" = "（……）"
"1014806-5" = "[ns] \"……イロハ？\""
"1014806-6" = "（……）"
"1014806-7" = "（虎丸に違いないのだが、返事がない）"
"1014806-8-イロハ" = "うーん……。"
"1014806-9-イロハ" = "まあ、いいか。"
"1014806-10-イロハ" = "先生、中まで来てもらえます？"
"1014806-11-イロハ" = "鍵は開いてるので。"
"1014806-12" = "[s1] \"いいけど……。\"\n[s2] （戦車の中に入る）"
"1014806-13" = "[ns3] \"……え？\"\n[ns4] \"どうして……？\""
"1014806-14-イロハ" = "止むにやまれぬ事情がありまして。"
"1014806-15-イロハ" = "こんな暑いのに、エアコンが故障したんです。"
"1014806-16-イロハ" = "修理しようにも、部品が届くまで1週間以上かかるそうで……。"
"1014806-17-イロハ" = "とはいえ巡回しないわけにもいきませんし……。"
"1014806-18" = "[s5] \"それで、水着。\"\n[s6] \"服を脱いじゃっていいの？\""
"1014806-19-イロハ" = "巡回は1人なので。"
"1014806-20-イロハ" = "誰に見られるでもなし、気にすることもないかと。"
"1014806-21" = "[s] \"私がいるよ？\""
"1014806-22-イロハ" = "……黙っていてくれれば問題ないですよね？"
"1014806-23-イロハ" = "それに――"
"1014806-24-イロハ" = "先生にとって、悪い事でもないのでは？"
"1014806-25-イロハ" = "……あの。#n今さらそうやって顔を背けられると……。"
"1014806-26-イロハ" = "私だって恥ずかしいんです、けど……。"
"1014806-27-イロハ" = "……。"
"1014806-28-イロハ" = "……なるほど。"
"1014806-29-イロハ" = "だんまりを決め込むと。"
"1014806-30-イロハ" = "それなら仕方ありません。"
"1014806-31-イロハ" = "このまま海まで行きましょうか。"
"1014806-32-イロハ" = "そもそも、先生が教えてくれたんですから。"
"1014806-33-イロハ" = "夏と言えば海。海と言えば戦車だと。"
"1014806-34" = "[s7] \"イロハ？\"\n[s8] \"巡回中だったんじゃ……？\""
"1014806-35-イロハ" = "大丈夫ですよ。1日くらい。"
"1014806-36-イロハ" = "それでは――"
"1014806-37-イロハ" = "サボるとしましょうか。"
"1014806-38" = "（そのまま海に連れていかれた）"
"1014806-39" = "（シャーレに戻れたのは翌日の昼過ぎだった）"
