[translation]
"10044060-1" = "第6話;死のファンミーティング"
"10044060-2-ノゾミ" = "この調子ならなんとか帳尻は合いそうかな。"
"10044060-3-ノゾミ" = "ざっくり計算だけど。"
"10044060-4-ヒカリ" = "ギリギリー。"
"10044060-5" = "[ns] \"無傷で列車に追いつけて良かったね。\""
"10044060-6-ノゾミ" = "これで後はかっ飛ばすだけ！"
"10044060-7-ノゾミ" = "……のはずだけど、なーんか忘れてる気がするんだよね。"
"10044060-8-暴走族" = "おい！あの列車だぞ！！"
"10044060-9-暴走族" = "ひゃっふー！走れ走れー！"
"10044060-10-ノゾミ" = "あー……。"
"10044060-11-暴走族ボス" = "見つけたぞ――ハイランダーのガキども！"
"10044060-12-暴走族A" = "計画通りだね、総長！"
"10044060-13-暴走族ボス" = "積荷を取り返して、今度こそうちらが配達する――"
"10044060-14-暴走族ボス" = "我ながら天才的な計画だぜ！"
"10044060-15-暴走族ボス" = "これでキヴォトス中に名を売れるはずだ！！"
"10044060-16-暴走族B" = "この業界は結果がすべてだからな！"
"10044060-17-暴走族ボス" = "我らキヴォトス・トランスポーター連盟……略して、ブロロロ疾走連合の出番だぜ！！"
"10044060-18-暴走族ボス" = "……ん？"
"10044060-19-暴走族ボス" = "どうした？"
"10044060-20-暴走族A" = "あ、あのヘリは！？"
"10044060-21-シノン" = "特ダネとあらば、どこにでも駆けつける！#nクロノス報道部の[ruby=かわる]川流[/ruby]シノンです！"
"10044060-22-シノン" = "続報です！今、話題の貨物列車をカメラが捉えました！#nその積荷は、キヴォトスの運命を左右するほどのモノなのだとか……！"
"10044060-23-シノン" = "すでに暴走族が集まっているようです！#nどこからニオイを嗅ぎつけてきたのでしょうか！"
"10044060-24-シノン" = "果たして、あの中には何があるのか！列車はどこに向かうのか！"
"10044060-25-シノン" = "引き続き、チャンネルはそのままで！#nクロノスチャンネルはキヴォトスの皆様に、いちはやく真実をお伝えしていきます！"
"10044060-26-アオバ" = "あ、あんな報道……私たちに恨みでもあるんでしょうか……。"
"10044060-27-ノゾミ" = "クロノスは野次馬根性だろうけど……暴走族の方はどうしてついてくるわけ？"
"10044060-28-ヒカリ" = "ピザの恨みー？"
"10044060-29-アオバ" = "わけが分からないんですけど……この件とクロノスって関係ないですよね！？"
"10044060-30-アオバ" = "こ、こんなことになってるの、半分くらいあの人たちのせいなんですけど……！"
"10044060-31-アオバ" = "い、いっそ撃ち落としてしまえば静かになるはず……。"
"10044060-32" = "[ns] \"あ、アオバ、落ち着いて！\""
"10044060-33-ノゾミ" = "起きたことはもうしょうがないじゃん？"
"10044060-34-ノゾミ" = "これからを考えないと。"
"10044060-35-アオバ" = "そ、それはそう、ですけど……。"
"10044060-36-ノゾミ" = "まっ、ノープランなんだけどね！パヒャッ！"
"10044060-37-アオバ" = "い、いい話だと思ったのに……。"
"10044060-38-ヒカリ" = "土煙ーもくもくー。"
"10044060-39-ヒカリ" = "……。"
"10044060-40-ヒカリ" = "なんか、くるー。"
"10044060-41" = "[ns] \"えっ……。\""
"10044060-42" = "[ns] \"何かがものすごいスピードで追ってくるような……？\""
"10044060-43-チンピラ" = "キャハハッ！見つけたぜ！"
"10044060-44-ヘルメット団" = "あの列車はうちらのもんだ！#nおらっ、退いた退いたーっ！！"
"10044060-45-暴走族ボス" = "そ、総長！なんか変なやつらまできてるけど！？"
"10044060-46-暴走族ボス" = "なっ、誰だあいつら！？まさかクロノスのニュースにつられて……？"
"10044060-47-暴走族ボス" = "くそっ！あの積荷はうちらのだぞ！"
"10044060-48-アオバ" = "にゅ、ニュースのせいで追手が増えてしまいました……！！"
"10044060-49-ノゾミ" = "バイクに、装甲車……うわぁ、戦車までいるよ？"
"10044060-50-ヒカリ" = "ちょー人気ー、死のファンミーティングー。"
"10044060-51-ノゾミ" = "相手してたら日が暮れちゃうし、このまま振り切るよ！"
"10044060-52-アオバ" = "た、ただの貨物輸送だって聞いてたのに……。"
"10044060-53-ノゾミ" = "いやぁ～、どうしよっか、これ。"
"10044060-54-ヒカリ" = "大ピンチー。"
"10044060-55-？？？" = "ワハハッ！その積荷はうちらのもんだ！"
"10044060-56-？？？" = "ひとつ残らず置いてきなぁ！！"
"10044060-57-アオバ" = "ど、どうしてこうなってしまうんですかぁっ！！"
"10044060-58" = "チャンネルをご覧の皆さん！"
"10044060-59" = "状況は混迷を極めています！走る列車！追う群衆！"
"10044060-60" = "果たして、あの列車の行方は――！#n最後まで、まばたき禁止ですよ！！"
"10044060-61-シノン" = "あれ？何か飛んできて……？"
"10044060-62-マイ" = "……ロケット砲じゃない？"
"10044060-63-シノン" = "はっ！皆さん大変です！今、ロケット砲がヘリに向かって――"
"10044060-64-シノン" = "このヘリ！？！？"
"10044060-65-シノン" = "ぎゃぁぁああああーっ！！"
"10044060-66-マイ" = "げ、言論弾圧だぁぁぁっ～！！"
"10044060-67-ヒカリ" = "パヒャヒャッ！いいねいいね！#n大胆なことするヤツもいるじゃん！"
"10044060-68-ヒカリ" = "撃ったのアオバー？"
"10044060-69-アオバ" = "ち、違います……！#n一瞬考えはしましたが撃ってません！！"
"10044060-70-アオバ" = "と、というか……向こうに撃ってるヤツいるんですけど！！あっち！！"
"10044060-71-ブラックマーケット幹部" = "クロノスにはご退場願おうか！"
"10044060-72-ブラックマーケット幹部" = "これ以上雑魚が群がるのは手間だからな！"
"10044060-73-チンピラ" = "キレイな花火だったぜ！やるじゃんか！"
"10044060-74-チンピラ" = "ぎゃふっ！"
"10044060-75-ブラックマーケット幹部" = "ふんっ！道を開けろ！あの列車は我々のものだ！！"
"10044060-76-暴走族A" = "総長、どうする！？仲間がどんどんやられてる！！"
"10044060-77-暴走族ボス" = "くそっ！うちらは配達業者なんだぞ！？"
"10044060-78-ノゾミ" = "おっ、あれはいい判断だね。先にライバルを倒すのは得点高いよ。"
"10044060-79-ヒカリ" = "優勝候補ー、ナンバーワンー。"
"10044060-80-アオバ" = "な、なに悠長なこと言ってるんですかぁ！！#n狙われてるのはこの列車なんですけど！！"
"10044060-81-ヒカリ" = "忘れてないよー？"
"10044060-82-アオバ" = "な、なんか……どんどん距離が詰まってませんか……？"
"10044060-83-アオバ" = "それにこの路線――ゲヘナの自治区を通過しますよね！？"
"10044060-84-アオバ" = "げ、ゲヘナの生徒まで加勢してきたら……#nも、もう輸送は諦めて脱出しませんか……？"
"10044060-85-ノゾミ" = "なに言ってんのさ。任務はやりきるよ。"
"10044060-86-アオバ" = "だ、だって……このままだと任務どころじゃ……！"
"10044060-87" = "[ns1] \"とりあえず落ち着いて考えてみよう。\"\n[ns2] \"打開策はあるはずだから。\""
"10044060-88-アオバ" = "うぅ……ほ、本当にそうなんでしょうか……。"
"10044060-89-アオバ" = "つ、積荷を全部奪われて、列車は破壊されて……#nさ、最後はその責任を問われて、どうせ全員で懲戒処分を受けるんです……。"
"10044060-90-ノゾミ" = "パヒャヒャッ！いい想像力じゃん！"
"10044060-91-アオバ" = "わ、笑ってる場合ですか！？"
"10044060-92-ヒカリ" = "うわーん、しくしくー。"
"10044060-93-アオバ" = "な、泣いたフリならもっと真剣にやって欲しいんですけど！"
"10044060-94-ヒカリ" = "うわーん、ばれたー。"
"10044060-95" = "[ns] \"あれ？なんか向こうの様子が……。\""
"10044060-96-ヒカリ" = "おー、ニューチャレンジャー。"
