[translation]
"2001405-1" = "大は小を兼ねる？"
"2001405-2" = "[ns] \"あれ。サキ、何か良いことでもあった？\""
"2001405-3-サキ" = "ああ、先生。"
"2001405-4-サキ" = "ああ、ちょっとな……これを見てくれ。"
"2001405-5-サキ" = "今朝、近所のフリーマーケットで珍しいものを見つけたんだ。"
"2001405-6-サキ" = "見て驚くなよ……"
"2001405-7-サキ" = "「37mmシャベル迫撃砲」だ！"
"2001405-8" = "[s] \"……何それ？\""
"2001405-9-サキ" = "なるほど、先生は初めて見るものかもしれないな。"
"2001405-10-サキ" = "この迫撃砲は昔、とあるレッドウィンター連邦学園出身の物好きが作ったもので、シャベルとしても使える迫撃砲なんだ！"
"2001405-11-サキ" = "もう生産記録もほとんど残ってない珍しいものだし、知らなくてもおかしくはない。"
"2001405-12-サキ" = "普段はこの砲身を取っ手みたいに握って、シャベルとして使って……敵が現れたらこう構えて、迫撃砲として使うことができる。"
"2001405-13-サキ" = "シャベルにも迫撃砲にもなるなんて、凄いと思わないか？"
"2001405-14-サキ" = "これ一つで色んな事態に対応できる、まさに夢のような発明品！"
"2001405-15-サキ" = "という感じで、素晴らしいものなのに……どうして生産終了になったんだか。全くもって理解できない。"
"2001405-16" = "[s] \"思ったより使い道が無かったから……とか？\""
"2001405-17-サキ" = "む、それは聞き捨てならないな。"
"2001405-18-サキ" = "シャベルに迫撃砲だぞ、機能は多ければ多い方が良い！一度でも塹壕を作ったことがあれば、誰だって共感してくれるはず！"
"2001405-19-サキ" = "そういった経験も無いお偉いさん方のせいで、生産終了に追い込まれたんだろうな……。"
"2001405-20-サキ" = "よし、決めた。私が実際に上手く使うことで、この装備の有用性をあらためて証明してやる！"
"2001405-21" = "[s] \"ならまずは、錆を落とした方が良さそうだね。\""
"2001405-22-サキ" = "たしかに……よく見るとすごいさび付いてるな。まぁ、倉庫にずっと放置されてたらしいから仕方ない。"
"2001405-23-サキ" = "まあ、これくらいなら私の方で手入れできる。まずは分解して、掃除して、油を塗って……"
"2001405-24-サキ" = "ちゃんと整備すれば、新品同然になるはずだ！"
"2001405-25-サキ" = "よし、じゃあ迫撃砲の手入れを開始する！手伝ってくれ、先生！"
"2001405-26" = "[s] \"うん、初めてだけど頑張るね。\""
"2001405-27" = "― んっ、[wa:700]くぅっ……！"
"2001405-28" = "― ……ちっ。"
"2001405-29" = "― 中が詰まってるのか、[wa:1350]全然抜けない。"
"2001405-30" = "[wa:500]― もっと、[wa:600]滑りを良くしないと……。"
"2001405-31" = "[wa:100]― 先生、[wa:1100]そこにある潤滑油を[wa:1450]こっちの方にくれるか？"
"2001405-32" = "[ns] 潤滑油を手渡す。"
"2001405-33" = "[wa:200]― おっ、[wa:800]これならいけるんじゃ……？"
"2001405-34" = "[wa:500]― あぁ……[wa:1500]こうして錆をはがしてる瞬間は、"
"2001405-35" = "[wa:100]― 本当に[wa:800]気持ち良い……"
"2001405-36" = "[wa:200]― ……何だか手つきが気になって、[wa:1950]ちょっと[wa:450]直視できない？"
"2001405-37" = "[wa:150]― っ、[wa:300]はぁぁっ！？"
"2001405-38" = "― これは[wa:200]神聖な[wa:600]手入れの作業だぞ！"
"2001405-39" = "[wa:50]― 何言ってんだ[wa:500]バカ！？"
"2001405-40-サキ" = "終わった！！"
"2001405-41-サキ" = "見てくれ。このきらめく砲身、そしてシャベルの刃……美しい……。"
"2001405-42-サキ" = "やはりクラシカルな武器には、それならではの魅力があるな。"
"2001405-43-サキ" = "さて。綺麗になったところだし、一度射撃テストでもしてみるか。"
"2001405-44-サキ" = "照準良し、装填完了……"
"2001405-45-サキ" = "発射！"
"2001405-46-サキ" = "……。"
"2001405-47-サキ" = "……は？まさか、不発……？"
"2001405-48-サキ" = "そ、そんなはずは……"
"2001405-49-サキ" = "もう一度……！"
"2001405-50-サキ" = "ど、どうしてこんなことに……？威力も弱いし……。"
"2001405-51-サキ" = "どうしてだ、37mm榴弾がダメなのか……？こんな威力じゃトーチカどころか、鉄帽も貫けない……。"
"2001405-52-サキ" = "だ、大丈夫だ。威力はちょっとアレだけど……この迫撃砲には、まだ「シャベルとしても使える」っていうメリットが……！"
"2001405-53-サキ" = "例えばほら、ここの土をこんなに軽々と……"
"2001405-54-サキ" = "軽々と……"
"2001405-55-サキ" = "……ああもう、砲身が邪魔！しかも重い！"
"2001405-56-サキ" = "こんなので塹壕を掘るくらいなら、いっそ素手でやった方が速いだろ！？"
"2001405-57" = "[s] \"やっぱり使われなくなった武器には、それなりの理由があるんだね。\""
"2001405-58-サキ" = "くうっ……でもせっかく手に入れた、珍しい装備なのに……。"
"2001405-59-サキ" = "きっと、きっと何か、使い道が……！"
"2001405-60" = "（その後サキはしばらくの間、シャベル迫撃砲を持ち歩いて使い道を探していたものの……）"
"2001405-61" = "（結局、無理に使うことは諦めたのか、近くの物置でひっそりと埃をかぶることになった）"
