[translation]
"10050020-1" = "第2話;本を大切に"
"10050020-2-ナギサ" = "！？！？！？"
"10050020-3-ティーパーティーの行政官" = "な、ナギサ様……？#nナギサ様――っ！？！？"
"10050020-4-ナギサ" = "これは一体！？"
"10050020-5-ティーパーティーの行政官" = "どど、どうされました！？"
"10050020-6-ナギサ" = "……まだ読んでいないのでしたね。#nまず、お互いの認識を合わせるところから始めましょうか。"
"10050020-7-ティーパーティーの行政官" = "は、はい……。"
"10050020-8-ティーパーティーの行政官" = "なっ、ななっ……！？"
"10050020-9-ナギサ" = "……これであなたも事の重大さを理解していただけたかと思います。"
"10050020-10-ナギサ" = "私が今から話すことを、そのまま実行していただけますか？"
"10050020-11-ナギサ" = "先生には私から連絡いたします。"
"10050020-12-ティーパーティーの行政官" = "は、はいっ、かしこまりました！"
"10050020-13-ティーパーティーの行政官" = "（私は結構好きだったんだけどなぁ……）"
"10050020-14-ティーパーティーの行政官" = "（特にあのシーンとか、その後の展開とか……）"
"10050020-15" = "[ns1] \"重要なお願い、って言われて来たんだけど……。\"\n[ns2] \"何かあったの？すごい剣幕だけど……。\""
"10050020-16-ナギサ" = "ようこそお越しくださいました、先生。#nご多忙のところお時間を頂戴して申し訳ありません。"
"10050020-17" = "[s] \"いや、それは別にいいんだけど……。\""
"10050020-18-ナギサ" = "本題、ですが……。"
"10050020-19-ナギサ" = "トリニティはいま、未曾有の危機にさらされております！"
"10050020-20" = "[s] \"なに！？襲撃！？\""
"10050020-21-ナギサ" = "ええ、いっその事それならよかったのでしょう。#n自分たちで解決できるのですから。"
"10050020-22-ナギサ" = "そう……武力による攻撃ならまだ良いのです。対処法が分かっておりますので。"
"10050020-23-ナギサ" = "しかし。内部からトリニティの風紀を乱す攻撃には、対抗手段がありません。"
"10050020-24-ナギサ" = "こちらをご覧ください。"
"10050020-25" = "[ns3] \"ふつうの本に見えるけど……。\"\n[ns4] \"素朴な表紙のマンガだね。\""
"10050020-26-ナギサ" = "はい。どんな本にも言えることですが、重要なのはその中身でしょう。"
"10050020-27-ナギサ" = "どうぞ、その手でご覧になってください。"
"10050020-28" = "[ns5] （……？特に気になるところはない……）\n[ns6] （トリニティではこういう内容も刺激的なのかな）"
"10050020-29-ナギサ" = "これは紛れもなくトリニティの精神と校風を乱し――"
"10050020-30-ナギサ" = "逸脱行為を扇動する意図で作られた、非公認の書籍です！"
"10050020-31-シミコ" = "こんにちは、ナギサ様……って、あっ！先生もいらしたのですね！"
"10050020-32" = "[s] \"シミコ、こんにちは！\""
"10050020-33-ナギサ" = "こんにちは、シミコさん……？#nええと、ウイさんをお呼びしたはずでは……。"
"10050020-34-ナギサ" = "……。"
"10050020-35-ナギサ" = "いえ、理解しました。シミコさんも大変なのですね。"
"10050020-36-シミコ" = "はい、ナギサ様。ご理解くださりありがとうございます。そういうことです……#nところで、どうかされましたか？"
"10050020-37-ナギサ" = "ああ、そうでした。#nこちらの本はご存じですか？"
"10050020-38-シミコ" = "これは……最近トリニティで流行していると噂のものですね。"
"10050020-39-ナギサ" = "ええ。それなら話は早いです。#n内容についてもご存知でしょうか？"
"10050020-40-シミコ" = "……。"
"10050020-41-シミコ" = "（知ってはいますが……そう答えてはならないような雰囲気がしますね）"
"10050020-42-シミコ" = "いいえ、内容までは知りません。"
"10050020-43-ナギサ" = "そうですか。私もさっきまで知らなかったのですから、当然とも言えますが……。"
"10050020-44-ナギサ" = "この本……トリニティの外から来たもので間違いないかと。"
"10050020-45-シミコ" = "はい。トリニティで作られたものでしたら、私たち図書委員会が管理していますので。"
"10050020-46-ナギサ" = "ええ。しかし残念ながら今この本の出どころは分かっておりません。"
"10050020-47-ナギサ" = "つまり……トリニティを内部から崩壊させようとしている、とある勢力によって……！"
"10050020-48-ナギサ" = "一種の精神的攻撃を受けているのです！"
"10050020-49-シミコ" = "少々論理が飛躍しすぎな気が……先生、どう思いますか？"
"10050020-50" = "[s] \"私もそう思うけど、こうなってしまったナギサは……。\""
"10050020-51-シミコ" = "そうですね……。"
"10050020-52-ナギサ" = "私たちは、この本の出どころを知る必要があります。#n学園の安全がかかっているのです。"
"10050020-53-ナギサ" = "しかしここで問題が……この本がトリニティの外から持ち込まれたと分かった以上。"
"10050020-54-ナギサ" = "私たちティーパーティーが全面的に関与するわけにはいきません。"
"10050020-55-ナギサ" = "最悪の場合、外交問題に発展する可能性がありますから。"
"10050020-56-ナギサ" = "秩序という意味では、正義実現委員会に一任しようかとも思いましたが……。"
"10050020-57-ナギサ" = "それでは学園内の雰囲気に影響を与えてしまいます。"
"10050020-58-ナギサ" = "ですので、図書委員会にお願いしようと思った次第です。トリニティ内の書籍の管理は、図書委員会の仕事ですから。"
"10050020-59-ナギサ" = "それでウイさんとお話ができればと思っていたのですが……そうですね。"
"10050020-60-ナギサ" = "あらためて、よろしくお願いしますね。シミコさん。 "
"10050020-61-シミコ" = "承りました。それで……私たちは具体的に何をしたらいいのでしょうか……？"
"10050020-62-ナギサ" = "お話したようにこの書籍の出どころ、流通量、トリニティに与える影響等を調査し……。"
"10050020-63-ナギサ" = "この件を、「やさしく穏やかに」解決していただけますか？"
"10050020-64-シミコ" = "……。"
"10050020-65-シミコ" = "なんというか、ナギサ様らしいお言葉ですね。"
"10050020-66-ナギサ" = " ……それは、どのような意味で？"
"10050020-67-シミコ" = "あっ、いえ。特に深い意味はありません。"
"10050020-68-ナギサ" = "……？ともかく、図書委員会だけでは大変ですので――"
"10050020-69-ナギサ" = "正義実現委員会との協力を、許可いたします。"
"10050020-70-シミコ" = "なるほど……本格的に正義実現委員会を動かすのは難しいけど……。"
"10050020-71-シミコ" = "図書委員会と協力するやり方なら#n「不要な誤解」は避けられる、ということですね。"
"10050020-72-ナギサ" = "その通りです。ご理解くださり感謝いたします。"
"10050020-73-ナギサ" = "先生とシミコさんに、私たちティーパーティーが[ruby=・]正[/ruby][ruby=・]式[/ruby][ruby=・]か[/ruby][ruby=・]つ[/ruby][ruby=・]秘[/ruby][ruby=・]密[/ruby][ruby=・]裏[/ruby][ruby=・]に[/ruby]お願いする案件となります。"
"10050020-74-ナギサ" = "使えそうな手は自由に使っていただいて構いません。#nそして「秘密」は、秘密のままに。"
"10050020-75-シミコ" = "分かりました、ナギサ様。"
"10050020-76-ナギサ" = "今この瞬間をもって、シミコさんを臨時外部顧問として正義実現委員会にご招待します。"
"10050020-77-シミコ" = "あ、ありがとうございます……。"
"10050020-78-ミカ" = "やっほーナギちゃん、お茶しに来たよ！#nって……あれ、先生！？"
"10050020-79-ナギサ" = "ミカさん？"
"10050020-80" = "[s] \"こんにちは、ミカ。\""
"10050020-81-ミカ" = "あっ、うん！こ、こんにちは先生！……来るって分かってたらもうちょっと色々、きれいにしてきたのに。"
"10050020-82" = "[s] \"今のミカも好きだよ？\""
"10050020-83-ミカ" = "っ！！？そ、そんなこと言ってもらえるのは、胸がはじけそうなくらい、嬉しいけど……。"
"10050020-84-ミカ" = "（そ、そんな意味なわけないでしょ、しっかりして私！）"
"10050020-85" = "やあ、先生。#nはぁ……その言葉に深い意味などないはずだ、それくらい理解しているだろう？ミカ。"
"10050020-86-ミカ" = "セイアちゃんってばもう☆"
"10050020-87-ミカ" = "それよりこの本なあに？初めて見た！"
"10050020-88-ナギサ" = "いけません！！！"
"10050020-89" = "[ns] \"な、ナギサ！？\""
"10050020-90-ナギサ" = "ビックリしたぁ！？どうしたのナギちゃん、ただの本でしょ！？"
"10050020-91-ナギサ" = "し、失礼いたしました、ミカさん。#nですが、この本はその……こ、困りますので！"
"10050020-92-ミカ" = "どうして？"
"10050020-93-ナギサ" = "で、ですから……ええと……。"
"10050020-94-シミコ" = "こちらはシスターフッドからティーパーティーを経て、#n図書委員会に依頼された「外典」の一つなのです。"
"10050020-95-ミカ" = "ん？シスターフッド……？なら仕方ないかぁ。"
"10050020-96-ミカ" = "あの子たちが関わると色々とややこしいんだよねぇ。"
"10050020-97-ナギサ" = "……だが、今のは些か度が過ぎていたのではないか？ナギサ。"
"10050020-98-ナギサ" = "ミカさんにこの本は早すぎます！"
"10050020-99-ナギサ" = "……過保護もすぎれば毒となるものだよ。"
"10050020-100-ミカ" = "もー！ナギちゃんもセイアちゃんも、なに二人でこそこそしてるの？"
"10050020-101-ミカ" = "というかナギちゃん……今のは流石に品がなかったんじゃないかな？"
"10050020-102-ナギサ" = "ミカさんにそれを言われるなんて……なんだかめまいがしてきました……。"
"10050020-103-ミカ" = "ナギちゃん？"
"10050020-104" = "[s] \"えっと……たしかに今のはやり過ぎだったかな？\""
"10050020-105-ミカ" = "そう思うよね！#nやっぱり先生って最高☆"
"10050020-106-ナギサ" = "っ……分かりました……申し訳ありませんでした。"
"10050020-107-シミコ" = "ティーパーティーの全員がいらっしゃるとは……#n最後のあれは、私もヒヤヒヤしてしまいました……。"
"10050020-108-シミコ" = "あれ、先生大丈夫ですか？顔色が……。"
"10050020-109" = "[s] \"なんというか、胃がチクチクするやりとりだった……。\""
"10050020-110-シミコ" = "ああ……トリニティでは日常茶飯事なので、そのうちに慣れますよ。"
"10050020-111-シミコ" = "もちろん、先生に慣れてください、と言いたいわけではありませんが。"
"10050020-112" = "[s] \"あの本のこと、シミコは本当に何も知らないの？\""
"10050020-113-シミコ" = "ええと、それってつまり……。"
"10050020-114-シミコ" = "……。"
"10050020-115-シミコ" = "お察しの通りです。#nこれでも図書委員ですので。"
"10050020-116-シミコ" = "図書委員会は、トリニティで出回るすべての本を把握していますから。"
"10050020-117-シミコ" = "あ、強制されているわけではないんですけどね。"
"10050020-118" = "[s] \"どこまで読んだのか聞いてもいい？\""
"10050020-119-シミコ" = "最後までです。"
"10050020-120" = "[s] \"潔いっ！？\""
"10050020-121-シミコ" = "まぁ、別に先生にまで隠す必要はないと思いますので……。"
"10050020-122-シミコ" = "……えっ？あれをどう思っているのか、ですか……？#nこれはあくまで、私見ですが……。"
"10050020-123-シミコ" = "「グレーゾーン」の作品だと思っています。#n堂々と人に勧められるようなものではないです。"
"10050020-124-シミコ" = "だからといって盲目的に規制すべきでもないのですが……。"
"10050020-125" = "[s] \"そうだね、私もそう思う。\""
"10050020-126-シミコ" = "はい……正直なところ、こういう内容に全く興味がない年頃ではありませんので。"
"10050020-127-シミコ" = "ただ図書委員として感動したのは……そうですね、あの検閲……いえ、編集力でしょうか。"
"10050020-128-シミコ" = "あんなにうまく「切り取る」なんて……本当に感動しました。"
"10050020-129-シミコ" = "ん？すごく落ち着いているように見える、ですか……？"
"10050020-130-シミコ" = "……。"
"10050020-131-シミコ" = "先生。トリニティの「古書館」にはとてもたくさんの本が保管されています。"
"10050020-132" = "[s] \"たしかにそうだね。\""
"10050020-133-シミコ" = "その中に……いわゆる「健全ではない本」は、どれくらいあると思いますか？"
"10050020-134" = "[s7] \"……？\"\n[s8] \"……なるほど。\""
"10050020-135-シミコ" = "はい、お察しの通りです。"
"10050020-136-シミコ" = "じゃあ図書委員は全員慣れているのか、ですか？"
"10050020-137-シミコ" = "皆さんの名誉のためにも、詳細を話すのは難しいですが……。"
"10050020-138-シミコ" = "少なくとも私は、それなりに。"
"10050020-139-シミコ" = "本という媒体は、情報伝達のために存在します。"
"10050020-140-シミコ" = "果たして、私たちがその情報の伝達価値や資格を評し、等級分けしてよいものでしょうか？#nその権利は一体誰から与えられたのでしょう。"
"10050020-141-シミコ" = "「人」にも権利や資格があるのなら、私は「本」にだってそうあるべきだと思っています。"
"10050020-142-シミコ" = "だから本も、人と同じだと思えるのだとも。"
"10050020-143" = "[s] \"だから本を雑に扱う人は……。\""
"10050020-144-シミコ" = "はい。ムチを打ってでも反省させたほうがいいです。"
"10050020-145-シミコ" = "過ちを犯した人には罪を償わせる必要がありますから。"
"10050020-146" = "（……改めてシミコを怒らせてはいけないと実感したのだった）"
