[translation]
"10050090-1" = "第9話;リバー・ランズ・スルー・イット"
"10050090-2-ナギサ" = "……それで、チェリノ会長。こちらが私たちからの提案、トリニティとレッドウィンター間の文化交流協定の詳細です。"
"10050090-3-ナギサ" = "本協定はシャーレの先生が保証人となり、図書委員会の判断の末進められます。そして私たちティーパーティーもこれに異論はありません。"
"10050090-4-ナギサ" = "ただし今回のように、協議が進んでいない状態で、本のような媒体を流通させるのはご遠慮いただきたいです。"
"10050090-5-ナギサ" = "問題ありませんね？ヤクモさんの言う通り、文化は巡るべきですから。"
"10050090-6-チェリノ" = "う、うむむ……。"
"10050090-7-チェリノ" = "めんどくさい……というか、出版部が勝手にしたことだろう。"
"10050090-8-チェリノ" = "待て、カムラッドがいると言ったな？そうだ……それだ！"
"10050090-9-チェリノ" = "理解した。そして今回の件に限り、シャーレはレッドウィンターに代わって発言するとする。"
"10050090-10" = "[s] \"うん？私？\""
"10050090-11-ナギサ" = "えっ……？ということは、シャーレの先生に……？"
"10050090-12-チェリノ" = "そうだ。つまりシャーレはレッドウィンターの代理人だ、今回だけな！レッドウィンターはシャーレに全決定を委任する！"
"10050090-13-チェリノ" = "何よりおいらは、今から大事な用事を済ませなくてはならないのでな！"
"10050090-14-ナギサ" = "だ、大事な用事とは……。"
"10050090-15-チェリノ" = "それは……昼寝だ！"
"10050090-16-ナギサ" = "昼寝……？何かの隠語でしょうか！？"
"10050090-17" = "[s] （たぶん違うと思う……）"
"10050090-18-ナギサ" = "そ、それにシャーレを文化協定の代理人にするって……。"
"10050090-19-ナギサ" = "（そういうことですか！？万一協定が決裂した場合、レッドウィンターの代理人であるシャーレに一定の責任が問われることになる……）"
"10050090-20-ナギサ" = "（そして協定に応じたトリニティにも責任の一端が……）"
"10050090-21-ナギサ" = "（その場合先生は……仕事という面でも、感情の面でも、トリニティに反感を抱くかもしれない……）"
"10050090-22-ナギサ" = "（つまり――これはトリニティへの警告）"
"10050090-23-ナギサ" = "（同時に、レッドウィンターはあらゆる責任から逃れられる――なるほど、これがレッドウィンターの外交力！？）"
"10050090-24-ナギサ" = "ち、チェリノ会長、お待ちください！"
"10050090-25" = "[ns] \"ナギサ、何かあった？\""
"10050090-26-ナギサ" = "い、いえ！なんでもありません、先生！私たちがうまくやればいいのです、ええ！"
"10050090-27-ミカ" = "終わったー？ナギちゃん。暇だったんだからーもー。"
"10050090-28-セイア" = "ミカ。先生もいるのだから、場を弁えたまえ。"
"10050090-29-ミカ" = "そ、そうだった……ごめんね先生。"
"10050090-30-ミカ" = "うん？「そのままのミカでいい」……？先生ありがとう、好き！"
"10050090-31-タカネ" = "ご挨拶申し上げます、ティーパーティーの皆様。#nそして、寛容な対処に厚く御礼申し上げます。"
"10050090-32-ナギサ" = "こんにちは、出版部の皆さん。こうしてお会いできて嬉しいです。"
"10050090-33-ナギサ" = "私たちトリニティは、本件をきっかけに、これからもレッドウィンターとより良い関係を築いていきたいと思っております。"
"10050090-34-ナギサ" = "また良い本がありましたら、みなさんに是非おすすめしていただければと。"
"10050090-35-タカネ" = "はい、そのように。このような場を設けてくださり光栄ですわ。"
"10050090-36-ミカ" = "ねえねえ、ヤクモちゃんだったよね？初めまして！私はティーパーティーのミカ！"
"10050090-37-ミカ" = "その……よかったら、ちょっと二人だけで、話せないかな？"
"10050090-38-ヤクモ" = "ど、どうも……[ruby=あらまき]荒槇[/ruby]ヤクモです。"
"10050090-39-ヤクモ" = "（この人がティーパーティーの一人……）"
"10050090-40-ヤクモ" = "（つまり私は、チェリノ会長を目の前にしている、と）"
"10050090-41-ヤクモ" = "（いっそチェリノ会長ならば、対処法は100種類くらいあるのですが……）"
"10050090-42-ミカ" = "今回ヤクモちゃんが持ってきた本、さっそく読んでみたよ！"
"10050090-43-ヤクモ" = "あっ、はい……。"
"10050090-44-ミカ" = "あの、そのさ……これはあくまで、私の考えなんだけどね。"
"10050090-45-ミカ" = "主人公ってなんというか、先生とちょっと似てる部分があると思うの。だから、良かったと思う。"
"10050090-46-ミカ" = "それでその……これは私の個人的なお願い？というか願望？みたいなものなんだけど……。"
"10050090-47-ミカ" = "ヒロインの性格とか、見た目を変えたらもっと良くなるんじゃないかな？って！"
"10050090-48-ヤクモ" = "……？"
"10050090-49-ヤクモ" = "ほう……ほうほう、へえ……？ムッフフフフ。"
"10050090-50-ヤクモ" = "すばらしいご提案ありがとうございます。ミカ様。"
"10050090-51-ヤクモ" = "そのお話、もう少々詳しくお聞きしたいのですが……どのような変更をご希望で？"
"10050090-52-ミカ" = "うんうん！たとえばね……髪色をもうちょっとピンクっぽくして、くせっ毛にしたらもっとかわいいと思うの！"
"10050090-53-ミカ" = "ちょっと落ち着きはないけど、茶目っ気があって、やるときはやる！そんな子とかどう？"
"10050090-54-ミカ" = "普段は盛り上げ役で、髪は片側をだんごにしてもいいけど、まあそれは別にどっちでも……。"
"10050090-55-ミカ" = "一番好きなのはジャンボパフェ！その次に好きなのは、サミュエラのザ・ビヨンド！"
"10050090-56-ミカ" = "あ、ロールケーキはもういいかな……。"
"10050090-57-ミカ" = "とにかく！そういうのはどうかなーって？"
"10050090-58-ミカ" = "ええ、ええ。理解しましたとも。"
"10050090-59-ヤクモ" = "ただ、ミカ様のご要望をまとめますと……ほぼ一から作り直しになってしまいますねぇ。"
"10050090-60-ミカ" = "そ、そうなんだ……？"
"10050090-61-ヤクモ" = "そしておそらく、ミカ様ただ一人のための、1冊になることでしょう。"
"10050090-62-ミカ" = "えっ……？わ、私だけのため？"
"10050090-63-ミカ" = "いいよ！そういうの大好き！"
"10050090-64-ヤクモ" = "そうですか、私もそちらの方がよりミカ様にピッタリかと。#nただ……一つ問題がありまして。"
"10050090-65-ミカ" = "な、なに……？"
"10050090-66-ヤクモ" = "出版というものは基本的に、分母に左右される業界でして。"
"10050090-67-ヤクモ" = "少数のための作品は、あまり売り上げが立たないのです。"
"10050090-68-ヤクモ" = "特にこのような、一人のために本を作るのは、その希少性から値段の算定が難しく。"
"10050090-69-ヤクモ" = "結論から申しますと……割高になるということです。"
"10050090-70-ミカ" = "ん……？いくらくらい？"
"10050090-71-ミカ" = "このくらいならどうかな？"
"10050090-72-ヤクモ" = "！？！？"
"10050090-73-ヤクモ" = "いっ、いやっ、その半分でも十分ですが……！？"
"10050090-74-ミカ" = "なんだ、高いって言うから緊張した～#nじゃあさ――"
"10050090-75-ミカ" = "ミカさん？"
"10050090-76-ミカ" = "なっ、なに？ナギちゃん。"
"10050090-77-ナギサ" = "最後まで言わないと……分かりませんか？"
"10050090-78-ミカ" = "う、うう……わ、分かったってばもう！ナギちゃんのケチー！"
"10050090-79-シミコ" = "出版部のみなさん、本当にお疲れ様でした。"
"10050090-80-タカネ" = "いえ、図書委員会と正義実現委員会の方々に迷惑をかけてしまいましたわ。申し訳ありません。"
"10050090-81-マシロ" = "そうでもないですよ。出版部さんのおかげで、私たち正義実現委員会が図書館に行く機会が増えました。"
"10050090-82-マシロ" = "みんな、本そのものに興味が湧いたみたいなんです。"
"10050090-83-マシロ" = "私も、正義のこと以外にも興味を持つようになりましたし。"
"10050090-84-シミコ" = "それはよかったです。でも、ちゃんと返却はしてくださいね？"
"10050090-85-マシロ" = "は、はい、気をつけます……それでなんですが、タカネさん。"
"10050090-86-タカネ" = "はい。"
"10050090-87-マシロ" = "今回の本のお話って……まだ完結していないですよね？"
"10050090-88-タカネ" = "ええ、そうですが……。"
"10050090-89-マシロ" = "その……もし次が出たら、ご連絡を頂けないかと……。"
"10050090-90-タカネ" = "ふふっ……お気に召されたようで。"
"10050090-91-マシロ" = "はい、すごく。"
"10050090-92-タカネ" = "分かりました。物語が好きな方は、いつだって歓迎ですわ。"
"10050090-93-マシロ" = "あと……これはトリニティのみなさんからの要望ですが……私にはよく分からない話でして。"
"10050090-94-マシロ" = "「いつか必ず、雪の姫君の評論集を発売してほしい」とのことでした。"
"10050090-95-タカネ" = "……。"
"10050090-96-タカネ" = "ま……前向きに、検討いたしますわ。"
"10050090-97-マシロ" = "ありがとうございます、タカネさん。これからもどうぞよろしくお願いします。"
"10050090-98-タカネ" = "部長～～～っ！！！"
"10050090-99-ヤクモ" = "おや、どうかしましたかタカネ。"
"10050090-100-タカネ" = "聞いていたでしょう！？#nこれどうするおつもりですか！"
"10050090-101-ヤクモ" = "あっ……ええとぉ……。"
"10050090-102-ヤクモ" = "これも全部マーケティングですから！"
"10050090-103-タカネ" = "言い訳になりませんよ！？"
"10050090-104" = "[ns] \"満足した？ヤクモ。\""
"10050090-105-ヤクモ" = "そうですねぇ、ええ。かなり。"
"10050090-106" = "[s1] \"それならいいんだけど……。\"\n[s2] \"これからも、ヤクモのこと見てるからね？\""
"10050090-107-ヤクモ" = "おや？それはどうして……？"
"10050090-108-ヤクモ" = "いろんなことをよく知っているから……ですか？"
"10050090-109-ヤクモ" = "契約の重さが分かっていて、仕事のためにへりくだることができる生徒……？"
"10050090-110" = "[s3] \"そう。すごいスキルだし、うまく生かせばカッコイイけど。\"\n[s4] \"行き過ぎてしまった時に、私が責任をとれなくなるかもしれない。\""
"10050090-111-ヤクモ" = "……。"
"10050090-112-ヤクモ" = "はい、分かってますよ。"
"10050090-113-ヤクモ" = "あまり認めたくありませんが、私ってひねくれているみたいですし。"
"10050090-114-ヤクモ" = "あと、これからも私のことを見るってことは……。"
"10050090-115-ヤクモ" = "興味を示し続けてくださるっていう意味でもありますからね。#n悪いこととは限りませんし？"
"10050090-116" = "[s] \"またそうやって……。\""
"10050090-117-タカネ" = "そうですわ部長！そういう意味はないかと。#n今回のことだってホントにもう……！はぁ……。"
"10050090-118-タカネ" = "先生、本当にお疲れ様でした。心から感謝申し上げますわ。"
"10050090-119" = "[s] \"タカネがいてくれたおかげだよ……。\""
"10050090-120-タカネ" = "そ、そう思ってくださるのは、嬉しいですが……。"
"10050090-121-タカネ" = "はぁ……こうなると分かっていれば、最初から先生に助けを求めていたのに……。"
"10050090-122-タカネ" = "そういえば部長。なんでそうしなかったのですか？"
"10050090-123-ヤクモ" = "ああ、まあ……それも候補にはあったのですが……。"
"10050090-124-タカネ" = "「が」？"
"10050090-125-ヤクモ" = "……怒られそうだし？"
"10050090-126-タカネ" = "部長ーっ！！？"
"10050090-127" = "[s] \"ヤクモーっ！！\""
"10050090-128" = "[ns] \"ふぅ……。\""
"10050090-129" = "[ns] \"今日もよく働いたー！\""
"10050090-130" = "冬空の文芸復興 ～健全なる文化の交流について～"
