[translation]
"10025050-1" = "第5話;未知の恐怖"
"10025050-2-年老いた漁師" = "チッ……こやつら、素人ではなさそうじゃな。"
"10025050-3-年老いた漁師" = "しかし、所詮は捕らわれた魚。網にかかれば逃れることはできまい。"
"10025050-4-年老いた漁師" = "おい、[ruby=くまがい]熊谷[/ruby]。#n第3埠頭の奴らも呼んでこい！"
"10025050-5-年老いた漁師" = "まだ出港前だから、全員揃っとるはずじゃろ。"
"10025050-6-ミユ" = "うぅ……次から次に、人が……！"
"10025050-7-ミユ" = "火力では上回っていても、このままじゃまた包囲されて……！"
"10025050-8-サキ" = "くそっ……遮蔽物が多くて射線が……このまま時間を稼がれると増援が来る！"
"10025050-9-サキ" = "RABBIT1、どうする？#n銃弾も残り少ないぞ。"
"10025050-10-ミヤコ" = "…………。"
"10025050-11-ミヤコ" = "（遮蔽物を使う相手は空から切り崩すのが正攻法だけど、#nそれじゃ周辺施設にまで被害が……）"
"10025050-12-ミヤコ" = "（でも、もしこの村が本当に怪しい存在を崇拝するような、得体の知れない儀式を行っている場所だとしたら……） "
"10025050-13-ミヤコ" = "（被害を考慮する必要はない……）"
"10025050-14-ミヤコ" = "RABBIT3、HE-AB空中爆発弾は残ってますか？"
"10025050-15-モエ" = "うん。こんな事態も想定して、何発か残してあるよ。"
"10025050-16-ミヤコ" = "HE弾を空中で炸裂させて、遮蔽物に隠れている敵を動かします。"
"10025050-17-ミヤコ" = "指定座標は――"
"10025050-18" = "[ns] \"みんな、ちょっと待って！\""
"10025050-19-ミヤコ" = "この声は……"
"10025050-20-ミユ" = "……[USERNAME]先生？"
"10025050-21-ヴァルキューレの海警" = "はぁ……また朝からトラブルですか？#n懲りない方たちですね……"
"10025050-22-ヴァルキューレの海警" = "外部の方と何かあったときは、私たちにご一報くださいと、あれほど申したじゃないですか……苦情がいきなり上層部に飛ぶと、大変なのは私たちなんですよ？"
"10025050-23-漁師" = "ふんっ、たかだかネズミ駆除で何を大げさな。"
"10025050-24-年老いた漁師" = "10分で済む。見てるのは構わんが、邪魔だけはするなよ。"
"10025050-25-サキ" = "はぁ！？誰が誰を駆除するって……！？"
"10025050-26" = "[ns] \"どうやら、誤解があったようです。\""
"10025050-27-年老いた漁師" = "……誤解だと？"
"10025050-28-年老いた漁師" = "人さまの調理場に忍び込んで、魚を盗もうとしてたじゃろ？#nこれのどこが誤解だと言うんだ。"
"10025050-29-サキ" = "調理場……？"
"10025050-30-サキ" = "腐敗した魚を並べてるコレのどこが調理場なんだ！？"
"10025050-31-年老いた漁師" = "じゃから、これは腐った魚ではなく――！"
"10025050-32" = "[s] \"「くさや」ですね。\""
"10025050-33-サキ" = "くさ、や……？"
"10025050-34-ヴァルキューレの海警" = "アジなどを用いて作られる、"
"10025050-35-ヴァルキューレの海警" = "D.U.ではほとんど知られていませんが、[ruby=やとうら]夜戸浦[/ruby]村ではエビに次ぐ特産品です。"
"10025050-36-ヴァルキューレの海警" = "強烈な臭いのせいで、私たちもまだ手を出せてませんけどね……はは。"
"10025050-37-漁師" = "ここに来て随分と経ったのに、まだ食べれないなんて……これだから余所モンは。"
"10025050-38-ヴァルキューレの海警" = "好き嫌いのひとつやふたつ、誰だってあるでしょう！？"
"10025050-39-年老いた漁師" = "……くさやを知ってるとは、大したもんだ。"
"10025050-40-年老いた漁師" = "くさやは卸す数を絞っとるから、D.U.でも取扱店は少ないだろうに。"
"10025050-41" = "[s1] \"美食に目がない生徒が周りにいるもので……\"\n[s2] \"いろいろあって、接する機会が……\""
"10025050-42-サキ" = "で、でも、怪しい点はまだあるぞ！？"
"10025050-43-サキ" = "漁に出た人が怪我をするだとか、村が闇に飲み込まれるだとか……#nそれは一体どう説明するんだ？"
"10025050-44-漁師" = "怪我人……村が闇に……？"
"10025050-45-ヴァルキューレの海警" = "ああ、街灯が故障した件ですね。"
"10025050-46-ヴァルキューレの海警" = "海風で電線がやられたのか、この辺り一帯の街灯がダメになったんですよ……"
"10025050-47-ヴァルキューレの海警" = "それで、日が落ちたら足元も見えないくらいの真っ暗闇になるんです。"
"10025050-48-漁師" = "日の出前に出港準備をしてた新米漁師が、転んでな。おおかたソレのことだろう。"
"10025050-49-ヴァルキューレの海警" = "このままでは事故に直結するので、#n早く修理する人員を送ってほしいと何度も本部に要請しましたが……"
"10025050-50-ヴァルキューレの海警" = "人手不足を理由に、1か月も放置されているんですよ。"
"10025050-51-ミユ" = "陸が沈んだり、真っ暗な海底から謎の生き物が襲ってくるわけじゃないんだ……#nよかったぁ……"
"10025050-52-ミヤコ" = "そういうお前さんたちは、何の目的でこの場所に近づいたんだ？"
"10025050-53-ミヤコ" = "海辺を散歩していたところ、怪しい人影を見つけたので後を追いました。"
"10025050-54-ミヤコ" = "釣り具を持っていたものの、村の住民には思えなかったので、何か不正を働いているのではないかと思い……"
"10025050-55-年老いた漁師" = "ああ、あやつか。"
"10025050-56-年老いた漁師" = "最近、釣りを教えてほしいとせがむ者がおってな。"
"10025050-57-年老いた漁師" = "少し変わったやつだが、釣りの許可証はしっかり持っておるようじゃし……#nあまり気にせんで構わん。"
"10025050-58" = "[s3] \"誤解だったとはいえ、ご迷惑をかけてしまいました。\"\n[s4] \"生徒の代わりに謝らせてください。\""
"10025050-59-年老いた漁師" = "……今日のところは、見逃してやろう。"
"10025050-60-年老いた漁師" = "日が昇る前には出んといけんからの。#nそろそろ出港前の点検をする時間だ。"
"10025050-61-年老いた漁師" = "つまらんことに時間を割いて肝心のエビを逃せば、それこそ村の笑い者になるわい。"
"10025050-62-漁師" = "そうですね……準備してきます。"
"10025050-63" = "[ns] \"みんなにしては、珍しい早とちりだったね。\""
"10025050-64-ミヤコ" = "……申し訳ありません。"
"10025050-65-ミヤコ" = "状況を見極め、不要な衝突を防ぐはずの私たちが、自ら戦闘を招くような行動を……#n私の失態です。"
"10025050-66-ミヤコ" = "冷静さを失わないように注意していましたが、目の前の戦闘に集中するあまり……"
"10025050-67-ミヤコ" = "……この村は怪しいと決めつけてしまいました。"
"10025050-68-サキ" = "いや、それは私も同じだ。いざ戦闘が始まるまでは、#n住民の作り話だと思っていたが……"
"10025050-69-サキ" = "悪臭に惑わされて、いつの間にかあの伝説も本物だと信じ込んでしまった。"
"10025050-70-ミユ" = "ご、ごめん……#n私がずっと不吉なことばかり言ってたから、みんなの判断を鈍らせちゃって……"
"10025050-71-ミユ" = "こうなると分かってたら、静かにしていればよかった……"
"10025050-72-モエ" = "みんな、口では否定してても、どこか頭では同じことを考えてたんだよ。"
"10025050-73-モエ" = "これはミユのせいじゃなくて、みんなの責任だから。"
"10025050-74-ミヤコ" = "……落ち着いて考えれば、私はどうしてあんな考えに至ったのだろう、と。"
"10025050-75-ミヤコ" = "灯りのことも、干物のことも、変に疑いの目で見ていたせいで、誤った判断を下してしまいました。"
"10025050-76-ミヤコ" = "私たちはすっかり、村の伝説や供物に気を取られるばかり……"
"10025050-77-ミヤコ" = "これにも理由があるのでしょうか？"
"10025050-78-ミヤコ" = "もしかして、この村には本当に人を惑わす[ruby=・   ・]何か[/ruby]が存在するのでしょうか？"
"10025050-79" = "[s] \"情報が多すぎたせい、じゃないかな？\""
"10025050-80-ミヤコ" = "情報過多……ですか。"
"10025050-81-サキ" = "たしかに今回の任務では、聞き込みの段階で村の伝説をたくさん耳にしたな。"
"10025050-82" = "本来なら調査内容の話だけで済むはずなのに、何故か信仰や伝説に関する話ばかりが集まってしまったのも原因だったんだろうな。"
"10025050-83-モエ" = "1日目の報告書も「深きもの」に関する内容が中心で、SRTの調査というよりフィールドワークみたいだったねぇ。"
"10025050-84-ミユ" = "でも私は……昼の、海運会社の人の言葉が……気になるような……"
"10025050-85-ミユ" = "まだ、あの人の言葉がぐるぐるしてて……"
"10025050-86-ミヤコ" = "誤った先入観が、正しい判断を邪魔すると頭では分かっていたのですが……"
"10025050-87" = "[s] \"あとは、日頃の疲れもあるんじゃないかな？\""
"10025050-88-サキ" = "疲れって……私たちのことを見くびってないか？"
"10025050-89-サキ" = "SRT特殊学園の過酷な訓練を耐え抜いた私たちが、そんな事でヘマをするとでも？"
"10025050-90" = "[s] \"身体は元気でも、精神は疲れてるのかもしれないね。\""
"10025050-91-サキ" = "精神の疲れ……？"
"10025050-92" = "[s5] \"SRTは常に戦いへ身を投じてるから……\"\n[s6] \"落ち着いて過ごせる時間は少ないよね。\""
"10025050-93-モエ" = "そうだねぇ。本来、人間は本能のままに動くものだからね。"
"10025050-94-モエ" = "キヴォトス全体を危険に巻き込む大事件だって、最初はただの無邪気な欲望がきっかけだったりするし。"
"10025050-95-サキ" = "……それはモエだけだろ。"
"10025050-96-モエ" = "そうでもないよ？上の人が、どれくらい簡単に物事を決めてるのか知ったら……#nみんな、ビックリすると思うよ？……くひひっ。"
"10025050-97" = "[s7] \"[ruby=はいちゅう]杯中[/ruby]の[ruby=だえい]蛇影[/ruby]、だったね。\"\n[s8] \"もっと肩の力を抜いて、村と向き合ってみた方がいいかもね。\""
"10025050-98-ミヤコ" = "しかし……本当に杯の中に蛇がいたら大変ですね。"
"10025050-99-ミヤコ" = "SRT特殊学園の一員として、そのような危険要因を放置するわけにはいきません。"
"10025050-100-ミヤコ" = "杯の中には蛇がいるのか、それとも影なのか……#n確認する良い方法はないでしょうか？"
"10025050-101" = "[s] \"疑問が解消されたら、分かってくるんじゃないかな。\""
"10025050-102-ミヤコ" = "…………。"
"10025050-103" = "[s] \"何はともあれ、まずは休もうか。\""
"10025050-104" = "[ns9] \"せっかくの海だし、今は楽しまなくちゃ！\"\n[ns10] \"深きなんとかさんは、いったん忘れよう！\""
"10025050-105-ミヤコ" = "……分かりました。"
"10025050-106-ミヤコ" = "では、本日の夜間作戦はこれにて終了とします。"
"10025050-107-ミヤコ" = "……皆さん、遅くまでお疲れ様でした。"
"10025050-108-ミユ" = "お疲れ様でした！"
