[translation]
"10025010-1" = "第1話;可愛い水着と不穏な村"
"10025010-2" = "[ruby=やとうら]夜戸浦[/ruby]村・入口"
"10025010-3-サキ" = "……モエ。なんだ、そのやる気のない格好は？"
"10025010-4-モエ" = "ん？どうかしたの？"
"10025010-5-モエ" = "いつものメガネはどうした？#nそれに端末も持ってきてないじゃないか。"
"10025010-6-モエ" = "いやー、メガネをかけてたら泳げないでしょ。#nコンタクトに決まってるじゃん。"
"10025010-7-モエ" = "端末は防水に対応してないから、スマホでアクセスできるようにしたの。"
"10025010-8-モエ" = "まあ、セキュリティはちょっと弱くなるけど。"
"10025010-9-サキ" = "モエ、お前……私たちは遊びに来たんじゃないんだが……"
"10025010-10-サキ" = "これは立派な任務なんだぞ！"
"10025010-11-サキ" = "変装を言い訳に、そんな軽装備で来るなんて……#nひとつでも多く装備を持ち込むべきだろう！"
"10025010-12-ミヤコ" = "いいえ、サキ。今回の作戦においては、モエの判断が正しいです。"
"10025010-13-ミヤコ" = "事前に共有した通り、この作戦はいかに現地住民に疑われないようにするかが重要です。特殊部隊を連想させるような装備は、最小限に抑えるべきです。"
"10025010-14-ミヤコ" = "たしかに戦闘では役に立ちますが、それ以上に情報収集が最優先ですから。#nまだ裏があると決まったわけではありませんし。"
"10025010-15-サキ" = "ミヤコ……その水着……"
"10025010-16-ミヤコ" = "え、ええっと……可愛いと思ったのですが、変でしょうか？"
"10025010-17-サキ" = "いや、可愛いとは思うけど……"
"10025010-18-サキ" = "そんなにフリルがいっぱい付いてたら動きづらくないか？"
"10025010-19-サキ" = "それと、その浮き輪は一体何に使うつもりなんだ？"
"10025010-20-サキ" = "SRTの水泳実習……満点だったよな？"
"10025010-21-ミヤコ" = "で、ですからこれも……その、作戦に必要なので仕方なく……！"
"10025010-22-モエ" = "せっかくの海だし、可愛い姿を先生にお披露目したかったんじゃないの～？"
"10025010-23-サキ" = "……モエ！"
"10025010-24-モエ" = "で、サキの持ってるそれは何？"
"10025010-25-モエ" = "ダッフルバッグにマガジンポーチ、ブーニーハット……"
"10025010-26-モエ" = "そんな格好じゃ、怪しまれるに決まってるでしょ。#n水中で爆破作戦でもするつもり？"
"10025010-27-サキ" = "これでも減らしたんだぞ！？"
"10025010-28-サキ" = "潜入調査とはいえ、戦闘になる可能性もあるわけだし……"
"10025010-29-サキ" = "予備のマガジン、水分補給用の水筒……防弾素材のハット。#n万が一の水中作戦に備えた装備……"
"10025010-30-モエ" = "……。"
"10025010-31" = "せめて、そのいかにもなダッフルバッグをもう少しカジュアルな物に変えられなかったの？"
"10025010-32-サキ" = "これの何が悪いんだ？十分カジュアルだと思うが。"
"10025010-33-ミユ" = "お、お待たせ……！#nごめんね、思ったより時間がかかっちゃって……"
"10025010-34-ミユ" = "狙撃の装備は釣り用バッグにまとめたけど、これでどうかな……？#n大丈夫？"
"10025010-35-ミユ" = "新品だと変に見えちゃうし、少し使用感を出してみたんだけど……"
"10025010-36-ミユ" = "あ、あれ……みんな、どうしたの……？"
"10025010-37-モエ" = "これが本当の潜入装備か……そこまでは頭が回らなかった。"
"10025010-38-モエ" = "潜入といえば、やっぱりミユだよね～"
"10025010-39-ミユ" = "え、えっ。わ、私、変かな……？"
"10025010-40" = "[ns1] \"全員、水着で来たんだね。\"\n[ns2] \"みんな、よく似合ってるよ。\""
"10025010-41-ミヤコ" = "あ、ありがとうございます……。"
"10025010-42-ミユ" = "そ、それなら、良かったです……。"
"10025010-43-サキ" = "バリバリに水泳します～って格好のヤツもいるけど。"
"10025010-44-サキ" = "……空気が読めなくて悪かったな。"
"10025010-45-サキ" = "可愛い格好とは無縁なもんで。"
"10025010-46" = "[s3] \"そんなことはないよ。\"\n[s4] \"サキの水着も可愛いよ？\""
"10025010-47-サキ" = "これは、喜んで良いのか……？"
"10025010-48-サキ" = "普通の観光客に見えるなら、まあ……そうだな、ありがとう。"
"10025010-49-ミヤコ" = "全員揃いましたし、潜入前に最後の確認を。"
"10025010-50-ミヤコ" = "今回の作戦は、[ruby=やとうら]夜戸浦[/ruby]村で聞き込みを行います。#n村でエビが廃棄されたり、普段と異なるルートで搬出された痕跡を探してください。"
"10025010-51-ミヤコ" = "住民の方々にご協力を得なくてはなりません。#nくれぐれも疑いを招くような行動は慎んでください。"
"10025010-52-ミユ" = "あ、あの……ミヤコちゃん。#n作戦会議中にごめん……そ、その……"
"10025010-53-ミユ" = "すでに注目されてるみたい、だけど……"
"10025010-54-ミヤコ" = "……どうやら、海水浴を楽しむのは難しそうですね。"
"10025010-55-サキ" = "ここは漁村なんだし、こんな水着でウロウロしてたらそりゃ怪しいだろ。#n観光客の姿もないしな。"
"10025010-56-ミユ" = "なんか、この村……ホラー映画に出てきそうな雰囲気……"
"10025010-57-モエ" = "……ココ、本当に観光地なの？"
"10025010-58-ミヤコ" = "記録によれば、工場の建設前は自然豊かな景色を楽しめる隠れた名所として人気だったようですが……"
"10025010-59-ミヤコ" = "工場ができてからは村の雰囲気が変わってしまって、#n観光客の足は遠のいてしまったようです。"
"10025010-60" = "[s] \"これなら制服で来た方が良かったかな？\""
"10025010-61-ミヤコ" = "いえ……外部の人というだけで注目を集めているのですから、#n正体を知られれば余計に警戒されていたでしょう。"
"10025010-62-ミヤコ" = "調査は難航するかもしれませんが……ひとまず、計画通り作戦を進めましょう。"
"10025010-63-ミヤコ" = "私は船着き場で漁師の方を当たってみます。#nサキは役所で、ここ最近の事故や事件を調べてください。"
"10025010-64-ミユ" = "了解。"
"10025010-65-ミヤコ" = "モエは村に出入りしている不審者がいないか、防犯カメラの確認を。#nミユは、私たち以外で村に訪れた人がいないか聞き込みをお願いします。"
"10025010-66-モエ" = "う、うん……！"
"10025010-67-モエ" = "任せなって、くひひっ。"
"10025010-68-ミヤコ" = "では、作戦を開始します！"
