[translation]
"10029055-1-御坂美琴" = "結構な数ね……！#n前にあなたが来た時は、これを1人で相手してたの！？"
"10029055-2-エイミ" = "ううん、あの時よりも多い。#n押し切れるとは思うけど、こんなところで時間を使いたくはないかも。"
"10029055-3-エイミ" = "どうにかして、突破口を開ければ……"
"10029055-4-御坂美琴" = "……突破口、か。"
"10029055-5-御坂美琴" = "……！！"
"10029055-6-コトリ" = "なるほど！まさに今がチャンスですね！！"
"10029055-7-御坂美琴" = "[ruby=みこと]美琴[/ruby]さん！私たちが作ったレールガンの準備を！！"
"10029055-8-御坂美琴" = "……ええっ、本当にやるの！？"
"10029055-9-コトリ" = "そろそろ十分な電力がたまってるはずだよ。#n銃をレールガン発射モードに切り替えてみて。"
"10029055-10-ウタハ" = "誰もが一度は憧れる携帯型レールガン……#nこれこそ、エンジニア部の……いや、みんなの夢だ！"
"10029055-11-コトリ" = "ついに、この目で見られるのですね！！"
"10029055-12-佐天涙子" = "あはは……えらく期待されてますね、[ruby=みさか]御坂[/ruby]さん。"
"10029055-13-御坂美琴" = "……わ、分かったわよ！#nここでモードを変更するのね？"
"10029055-14-御坂美琴" = "えっと……こうして、と。"
"10029055-15-エイミ" = "急いで、かなり集まってきたよ。"
"10029055-16-御坂美琴" = "分かってるわ……"
"10029055-17-御坂美琴" = "……よし。"
"10029055-18-御坂美琴" = "モード変更完了！"
"10029055-19-コトリ" = "レ～！"
"10029055-20-ヒビキ" = "ル～！！"
"10029055-21-ウタハ" = "ガン！！！"
"10029055-22" = "[ns] \"……発射！！！\""
"10029055-23-御坂美琴" = "…………？"
"10029055-24-御坂美琴" = "……あれ？"
"10029055-25-ヒビキ" = "……むむ？"
"10029055-26-ヒビキ" = "ん……？"
"10029055-27-ウタハ" = "発射された……のか？"
"10029055-28-食蜂操祈" = "……御坂さん、本当に撃ったのよね？"
"10029055-29-御坂美琴" = "一応、何か発射したような気はするけど……#nなんて言うか、虫の音みたいなのが。"
"10029055-30-佐天涙子" = "ふふっ、こういう御坂さんも可愛いですね。"
"10029055-31-佐天涙子" = "[ruby=しらい]白井[/ruby]さんが見たら、どんな反応したんでしょう？"
"10029055-32-エイミ" = "……来るよ。"
"10029055-33-エイミ" = "時間をかけてたら、どんどん敵が増え続ける。"
"10029055-34-エイミ" = "この道は諦めて、ルートBに切り替えないと。"
"10029055-35-御坂美琴" = "…………。"
"10029055-36-御坂美琴" = "……ったく、仕方ないわね。"
"10029055-37" = "[ns1] \"御坂、何を……？\"\n[ns2] \"そのコインで何をするの？\""
"10029055-38-御坂美琴" = "要するに、あのロボットをまとめてブッ飛ばせば良いんでしょ？"
"10029055-39-御坂美琴" = "……みんな、後ろに下がって。#n本調子とは言えないけど……"
"10029055-40-御坂美琴" = "一発くらいなら、撃てる気がするから。"
"10029055-41-エイミ" = "……？"
"10029055-42-エイミ" = "一発って、何を？"
"10029055-43-佐天涙子" = "……！！"
"10029055-44-佐天涙子" = "みなさーん！下がってくださいねー！#n近くにいると危険ですよー！はい、下がって下がってー！"
"10029055-45-ヒビキ" = "……？わ、分かった。"
"10029055-46-ウタハ" = "な、何ですか！？急に空気が変わりましたよ！"
"10029055-47-ヒビキ" = "重機を扱うような緊張感だね。"
"10029055-48-食蜂操祈" = "まぁ、そうねぇ。"
"10029055-49-食蜂操祈" = "……あながち間違いじゃないと思うわぁ。"
"10029055-50-御坂美琴" = "……失敗の埋め合わせは！"
"10029055-51-御坂美琴" = "……これでッ！！！"
"10029055-52-御坂美琴" = "……ふう。"
"10029055-53-御坂美琴" = "うっ……"
"10029055-54-御坂美琴" = "ここじゃ、そう何度も撃てそうにないわね。#nこんなに頭が重くなるなんて……"
"10029055-55" = "[ns] \"…………。\""
"10029055-56" = "[ns3] \"今のが……。\"\n[ns4] \"レール、ガン……？\""
"10029055-57-食蜂操祈" = "やっぱり初めて見ると、そういう反応になりますよね。"
"10029055-58-食蜂操祈" = "あたしは未だにビックリしますけど……あはは。"
"10029055-59-食蜂操祈" = "はぁ……相変わらず派手ねぇ、あなたの能力。"
"10029055-60-佐天涙子" = "……先生？皆さん？"
"10029055-61-佐天涙子" = "あ、あの～……"
"10029055-62-エンジニア部" = "…………。"
"10029055-63-エンジニア部" = "……………………。"
"10029055-64-ウタハ" = "……銃を使わずに、レールガンを……撃った……？"
"10029055-65-ウタハ" = "言葉のあやなどではなく……本当に、その手でレールガンを？"
"10029055-66-ヒビキ" = "これが……「超能力者」……！"
"10029055-67-コトリ" = "なるほど、だから「レールガン」……！"
"10029055-68-御坂美琴" = "……！？"
"10029055-69-御坂美琴" = "な、何？どうしちゃったの、みんな！？"
"10029055-70-コトリ" = "すごいです……！どういう仕組みになっているのでしょう？#n手のどこかに発電器官があるのでしょうか……"
"10029055-71-ウタハ" = "コトリ、原理を究明したい気持ちは分かるが、そういった質問の仕方は失礼だよ。"
"10029055-72-ウタハ" = "その……もしよろしければ、もう一度見せてもらえないだろうか？"
"10029055-73-御坂美琴" = "え、も、もっかい？"
"10029055-74-御坂美琴" = "あんまり何度も撃つものじゃないんだけど……"
"10029055-75-ウタハ" = "ああ、すまない……配慮が足りなかったね。"
"10029055-76-御坂美琴" = "コインを使うのだろう？#n頼んでいるというのに用意もなく申し訳ない。"
"10029055-77-ウタハ" = "ヒビキ、小銭を貸してくれないかい？あいにく私は今持ち合わせがなくて……。"
"10029055-78-御坂美琴" = "……え？"
"10029055-79-ヒビキ" = "10円玉しかないけど大丈夫……？"
"10029055-80-ウタハ" = "小銭の大きさや値段によって威力が変わる可能性もある……#n色々な種類で試したいところだが……"
"10029055-81-ウタハ" = "……ま、待って！なんでそういう話になるの！？"
"10029055-82-御坂美琴" = "というか、そういう問題じゃなくて……！"
"10029055-83-コトリ" = "むむっ！ウタハ先輩！私のポケットに500円玉が入ってました！"
"10029055-84-ウタハ" = "……！！コトリ、それは流石に……！"
"10029055-85-御坂美琴" = "あの……私の話、聞いてる……？"
"10029055-86-御坂美琴" = "私が使ってるのは、お金じゃなくてゲーセンのメダルなんだけど……？"
"10029055-87-御坂美琴" = "小銭を出さないで……！もったいないでしょ！"
"10029055-88" = "[s5] \"探究心が旺盛なんだよ。\"\n[s6] \"みんな、超能力が見れて嬉しいんだと思う。\""
"10029055-89-食蜂操祈" = "御坂さんの話、聞こえてないみたいですね……？"
"10029055-90-食蜂操祈" = "よかったわねぇ、御坂さん。異世界でもすぐお友達ができてぇ。"
"10029055-91-御坂美琴" = "何もよくないわよ！！"
"10029055-92-ヒビキ" = "お願いコトリの夕飯代のコレで……もう一度やってくれないかな。#n私の10円玉も、一緒に……！"
"10029055-93-コトリ" = "どうか、お願いします！"
"10029055-94-ウタハ" = "受け取ってくれ、私たちの500円を！"
"10029055-95-ヒビキ" = "いや、510円。"
"10029055-96-ウタハ" = "……510円を！"
"10029055-97-御坂美琴" = "いや、ちょっと……。"
"10029055-98-御坂美琴" = "……！"
"10029055-99-御坂美琴" = "……はぁ。"
"10029055-100-御坂美琴" = "今回だけよ！#n使わせてもらうわね500……"
"10029055-101-御坂美琴" = "……510円。"
"10029055-102-御坂美琴" = "……次からは、こういうのナシだからね。"
