[translation]
"10029065-1-御坂美琴" = "何よ、これ！また増えてる……本当、キリがないわね！"
"10029065-2-エイミ" = "それだけ重要な施設ってこと。#n私たちも全力で迎え撃つよ。"
"10029065-3-エイミ" = "まだバリアも残ってるし……"
"10029065-4-ヒビキ" = "ドローンもさらに増え続けてるみたいだ。#n一つひとつは大した問題ではないが……"
"10029065-5-ヒビキ" = "このままじゃ、施設の動きを止められない。"
"10029065-6-コトリ" = "後もう少しだというのに！！#nここまで来て、また最初からやり直しだなんて！？"
"10029065-7-히미키" = "いや、そうでした！#n入り口に飛ばされるとは限りません……下手するともっと遠くに！？"
"10029065-8-コトリ" = "どうにかしなくては……！！"
"10029065-9-佐天涙子" = "はあああぁっ――！！！"
"10029065-10-コトリ" = "……んっ！？"
"10029065-11-ヒビキ" = "いったい何を……"
"10029065-12-ウタハ" = "……！#nいつの間にパネルの前に！？"
"10029065-13-御坂美琴" = "……[ruby=さてん]佐天[/ruby]さん！？"
"10029065-14-佐天涙子" = "アレを壊せば良いんですよね？"
"10029065-15-佐天涙子" = "だったら、あたしが……！"
"10029065-16-コトリ" = "うああぁ！？ま、待ってください……！#nそのバリアに銃弾は通らな……！！"
"10029065-17-佐天涙子" = "銃弾がダメなら……！！"
"10029065-18-佐天涙子" = "……こうやって、壊せば良いんですよ！！！"
"10029065-19-佐天涙子" = "はああぁっ――！！"
"10029065-20-佐天涙子" = "はあっ……はあっ、はあ……はぁ……"
"10029065-21-佐天涙子" = "……はぁ……ふぅ。"
"10029065-22-ヒビキ" = "じ、銃身でバリアを……"
"10029065-23-ウタハ" = "叩き壊すだなんてね……"
"10029065-24-コトリ" = "さ、先ほどの素晴らしいフォームは……？#nもしかして、向こうの世界では有名な野球の選手なのでしょうか！？"
"10029065-25-佐天涙子" = "あはは、選手とかじゃないんですけどね。"
"10029065-26-佐天涙子" = "……静かになったような気がしません？"
"10029065-27" = "[s1] \"……本当だ。\"\n[s2] \"ドローンの動きが止まったね。\""
"10029065-28-御坂美琴" = "……やったのかしら？"
"10029065-29-御坂美琴" = "なんか……"
"10029065-30-御坂美琴" = "こうも呆気なく解決しちゃうと、ちょっと拍子抜けね。"
"10029065-31-食蜂操祈" = "……[ruby=みさか]御坂[/ruby]さん。"
"10029065-32-ヒビキ" = "……あ。"
"10029065-33-ヒビキ" = "そういう言い方はフラグ……"
"10029065-34-ウタハ" = "……ふふっ。"
"10029065-35-コトリ" = "やっぱりこうなると思ってました！！"
"10029065-36-御坂美琴" = "ああ……もうっ！"
"10029065-37-食蜂操祈" = "……御坂さんったら、本当に期待を裏切らないわねぇ。"
"10029065-38-佐天涙子" = "機械から光が……！！"
"10029065-39-エイミ" = "……！"
"10029065-40-コトリ" = "うわああぁぁぁぁ――！？！？"
"10029065-41-コトリ" = "……あれ？"
"10029065-42-ヒビキ" = "……？"
"10029065-43-ウタハ" = "……ん？"
"10029065-44-ヒビキ" = "どういう……こと？"
"10029065-45-佐天涙子" = "みんな、大丈夫……よね？#n全員、揃ってる？"
"10029065-46-佐天涙子" = "は、はい……あたしは大丈夫です。"
"10029065-47" = "[s3] \"みんな無事で良かった。\"\n[s4] \"何も起こらなかったね。\""
"10029065-48-ウタハ" = "……エラーが起きたのかな？"
"10029065-49-コトリ" = "予期せぬ衝撃が加わった事で、ストップしたのでしょうか！？"
"10029065-50-コトリ" = "……これで一件落着ですね！"
"10029065-51-食蜂操祈" = "いや、私たちは施設を直してもらって帰るのが目的だから、何も解決していないのだけどぉ……"
"10029065-52-エイミ" = "……待って。"
"10029065-53-エイミ" = "「施設」は正常に作動したはず。"
"10029065-54-エイミ" = "今のは、私たちを転移させる動きじゃない。"
"10029065-55-エイミ" = "……何かが[ruby=・   ・]来る[/ruby]よ"
"10029065-56" = "[s] \"…………。\""
"10029065-57" = "[ns] \"…………？？？\""
"10029065-58" = "！？！？！？"
