[translation]
"102030-1" = "第3話;作戦準備（１）"
"102030-2" = "第1サンクトゥム"
"102030-3" = "アビドス砂漠エリア"
"102030-4-アヤネ" = "第1サンクトゥムの作戦担当、奥空アヤネです。"
"102030-5-アヤネ" = "皆さん、指定地点に到着しましたか？#n第1部隊、応答願います。"
"102030-6-セリカ" = "大丈夫よアヤネちゃん。準備は終わってるわ。"
"102030-7-セリカ" = "うんうん！待機中です☆"
"102030-8-アヤネ" = "応答ありがとうございます！#nホシノ先輩はどうですか？"
"102030-9-ホシノ" = "うん、おじさんも大丈夫。"
"102030-10-ホシノ" = "あれが――「虚妄のサンクトゥム」なんだね？"
"102030-11-アヤネ" = "はい。#n……そして、「ビナー」をこちらに引きつけなければ、アレを破壊する事ができません。"
"102030-12-アル" = "「囮」役は私たち便利屋がやるわ。いいわね？"
"102030-13-ハルカ" = "は、はい！！壊れた列車を暴走させて、命を散らせばいいんですよね！？わ、分かりました！一生懸命死にます！！"
"102030-14-ムツキ" = "あはは！！ハルカちゃん、相変わらずだね～"
"102030-15-カヨコ" = "いや、死んだらダメでしょ……#n第2部隊はビナーを引きつけたら、第1部隊と合流して対象を挟撃するよ。"
"102030-16-ムツキ" = "列車の上に乗って移動するから、いかに怪我をしないかが大事。"
"102030-17-アル" = "ええ。一番危険なポジションは、私たち便利屋68に任せてちょうだい。#nそれがハードボイルドというものだもの。"
"102030-18-ムツキ" = "くふふっ、すっごい楽しそう！ジェットコースターみた～い！"
"102030-19-アル" = "そうそう。列車は最後に破壊するつもりだけど……"
"102030-20-アル" = "文句はあるかしら？"
"102030-21-ノノミ" = "それについては、お気になさらないでください。#nどうせ今は使われていませんから……"
"102030-22-ノノミ" = "それに――あの列車こそが、アビドスの衰退に拍車をかけたきっかけですし……"
"102030-23-ノノミ" = "それが、世界を救うお役に立てるのなら……"
"102030-24-ノノミ" = "これ以上嬉しいことはないです。"
"102030-25-アヤネ" = "ノノミ先輩……"
"102030-26-カヨコ" = "まさか、"
"102030-27-カヨコ" = "この列車がネフティスグループの――"
"102030-28-ノノミ" = "はいはい、昔話はその辺にして……#nこっちは準備オッケーだよ～"
"102030-29-ノノミ" = "はい！「シャーレコントロール」0号、応答願います！#n第1サンクトゥムはスタンバイ完了です！"
"102030-30-ノア" = "はい、確認しました。#nマキさん、そちらはどうですか？"
"102030-31-マキ" = "問題ないよ！あ、でも1個だけ注意。"
"102030-32-マキ" = "ビナーのレーザーには絶対触らないでね！"
"102030-33-マキ" = "岩を一瞬で消しちゃうくらいの超高温レーザーなんだって。"
"102030-34" = "第2サンクトゥムの方はいかがですか？"
"102030-35" = "第2虚妄のサンクトゥム"
"102030-36" = "ミレニアム郊外の閉鎖地域"
"102030-37-エイミ" = "うん。こちら、第2サンクトゥムの作戦担当､[ruby=いずみもと]和泉元[/ruby]エイミ｡"
"102030-38-エイミ" = "今から、軍需工場にいるケセドと交戦する予定。"
"102030-39-エイミ" = "工場の正面で、ケセドが生み出した兵と戦う部隊と――"
"102030-40-エイミ" = "上空から工場内部に入り込むパラシュート隊が待機中。あと――"
"102030-41-エイミ" = "状況了解しました。ありがとうございます。#nパラシュート部隊のメンバーはどなたに決まりました？"
"102030-42-エイミ" = "それが……ちょっとトラブルが起きちゃって。"
"102030-43-ノア" = "……といいますと？"
"102030-44-ネル" = "あ？てめぇ、話聞いてんのか？"
"102030-45-ツルギ" = "きひひっ……"
"102030-46-ツルギ" = "きひひひ……"
"102030-47-カリン" = "ええと……"
"102030-48-イチカ" = "その……困ったっす…… "
"102030-49-エイミ" = "C&Cのダブルオーと正義実現委員会の委員長が、お互い譲らなくて。"
"102030-50-ノア" = "……。"
"102030-51-アカネ" = "リーダー、そろそろ時間が……#n今はこんな事をしている場合では……"
"102030-52-ネル" = "わーってる！#nだがなぁ、こいつが先にケンカ吹っ掛けてきてんだよ。"
"102030-53-アカネ" = "はぁ……。#nあの……すみません、そちらもどうか宥めていただけますと……"
"102030-54-イチカ" = "すみません、それは難しいっす。#nあの状態のツルギ先輩は誰にも止められなくて……"
"102030-55-アスナ" = "で、なんでケンカしてるの～？#n[ruby=・   ・   ・]強い方[/ruby]が正面を担当すればいいんじゃない？"
"102030-56-カリン" = "あ、アスナ先輩それは……！！"
"102030-57-イチカ" = "あ……終わった。"
"102030-58-ツルギ" = "……おい、表出ろ。#n白黒つけようじゃねぇか。"
"102030-59-ツルギ" = "……けけ、きひゃひゃひゃひゃひゃ！"
"102030-60-アスナ" = "わぁ！ケンカだ～！！#n面白そ～！見にいこーっと！"
"102030-61-アカネ" = "はぁ……結局こうなるのか……。"
"102030-62-アカネ" = "私たちも行きましょうか。"
"102030-63-イチカ" = "あー……"
"102030-64-イチカ" = "……仕方ないっすね。"
"102030-65-エイミ" = "エイミさん？#nそちらで一体何が――"
"102030-66-エイミ" = "……ケンカしに行っちゃった。"
"102030-67-ノア" = "……。"
"102030-68-アカネ" = "正義実現委員会の委員長さん、すっごいね～！"
"102030-69-カリン" = "近接戦でリーダーと互角の人……初めて見た。"
"102030-70-アカネ" = "ツルギ――彼女は、「トリニティの戦略兵器」と呼ばれるほどの方ですから。"
"102030-71-イチカ" = "お、すごいっすね～#nツルギ先輩に怯まない人、久しぶりに見たっす。"
"102030-72-ツルギ" = "くひひっ……"
"102030-73-ツルギ" = "きえええぇぇぇぇぇぇっ！！！"
"102030-74-ネル" = "はははっ！#nいいぞ、次はこいつだ！"
"102030-75-アスナ" = "あははは！リーダー、楽しそう～！"
"102030-76-カリン" = "最近色々あったから、ストレスが溜まってたんだな。"
"102030-77-イチカ" = "ツルギ先輩も今日はテンション高めっすね～"
"102030-78" = "ははっ！悪くねぇ。でもこんなもんで終わりじゃねぇよな？#nそれとも、傷が痛むか？"
"102030-79" = "きひひ……傷なんて――"
"102030-80" = "――全部治ってる。"
"102030-81-ネル" = "……ははっ！流石。#nそう来なくっちゃなぁ！！"
"102030-82-ツルギ" = "きえええええええぇぇぇっ！！"
"102030-83-ユウカ" = "ちょっと、二人とも何してるのよ！！"
"102030-84-アカネ" = "あっ……ユウカ……"
"102030-85-ユウカ" = "チーム分けで、ケンカなんかして……#nあなた達、一体いま何年生？ "
"102030-86-ユウカ" = "すみません、皆さん。#nユウカちゃんなら止めてくれると思いまして……"
"102030-87-ネル" = "……"
"102030-88-ネル" = "ちっ、せっかく面白い展開になってきたってのによぉ……"
"102030-89-アスナ" = "え～？でもでも、誰が一番強いか決めないとチームが分けられないよ？"
"102030-90-ユウカ" = "一体、何を言ってるの……？"
"102030-91-ユウカ" = "もう……そこの二人！"
"102030-92-ツルギ" = "あぁ？"
"102030-93-ツルギ" = "？"
"102030-94-ユウカ" = "じゃんけんして！今すぐ！"
"102030-95-ネル" = "はぁ！？そんなんで決められっかよ！"
"102030-96-ユウカ" = "こっちは時間が無いのよ。#nこのままじゃ計画が失敗してしまうわ。"
"102030-97-ツルギ" = "チッ……分かったよ。"
"102030-98-ネル" = "んじゃ……じゃん――"
"102030-99-ツルギ" = "――けん、"
"102030-100-一同" = "――ぽん！！"
"102030-101-エイミ" = "……。"
"102030-102-エイミ" = "決まりだね。"
"102030-103-アリス" = "モモイ！ミドリ！ユズ！緊急クエストです！#nダンジョン攻略ですよ！"
"102030-104-アリス" = "アリス、しーっ！#n重要な作戦みたいだから、声を落として……！"
"102030-105-アリス" = "お姉ちゃん……だ、大丈夫かな？"
"102030-106-アリス" = "う、うん多分、大丈夫だよ……#n先生が「ここに最強のチームが集まる」って言ってたし……"
"102030-107-アリス" = "はい！アリスも聞きました！今回はとっても強い仲間たちと一緒に戦います！だから、大丈夫です！ "
"102030-108-モモイ" = "とっても強い仲間……"
"102030-109-ミドリ" = "えっと、一つは特殊部隊って言ってたよね？ "
"102030-110-サキ" = "ここがスランピアか？#n思ったよりも不気味な雰囲気だな。"
"102030-111-ミヤコ" = "RABBIT小隊、目標地点に到着。#n本隊と合流しました。"
"102030-112-ミドリ" = "き、来た！SRTだ……！"
"102030-113-ミドリ" = "こ、こんにちは……よろしくお願いします。"
"102030-114-ミヤコ" = "今日はよろしくお願いします、皆さん。"
"102030-115-ミヤコ" = "そして、RABBIT3とRABBIT4は位置の報告を。"
"102030-116-モエ" = "RABBIT3、現在空中支援のスタンバイ完了。命令待機中～。#nミユ、そっちはどう？"
"102030-117-ミユ" = "RABBIT4、し、視界不良……風も南東向きで35ノット……あまりいい環境ではないかな……"
"102030-118-ミヤコ" = "で、でも……狙撃に大きな影響はないよ……"
"102030-119-ヒナ" = "これ、台風級の風速だけど……。"
"102030-120-ミドリ" = "き、来た！とっても強い仲間その2……！#nゲヘナ風紀委員長、[ruby=そらさき]空崎[/ruby]ヒナ……！"
"102030-121-ミドリ" = "よ、よろしくお願いします……！"
"102030-122-ミユ" = "狙撃手、目標との距離はどれくらい？"
"102030-123-ヒナ" = "は、はい！？わ、私ですか？#nあ……えっと、ここから約950mほどです……"
"102030-124-ヒナ" = "銃は何を？"
"102030-125-ヒナ" = "RABBIT39式、狙撃用ライフルです……！#n弾丸は7.62mmx53mmRを使っていて……装弾数は5発、じゅ、銃番号は――"
"102030-126-ミヤコ" = "あの……"
"102030-127-ミユ" = "……申し訳ない、問い詰める意図はなかった。"
"102030-128-ヒナ" = "有効射程の倍の距離、そしてこの悪条件下で狙撃が可能だなんて――流石だね。"
"102030-129-ヒナ" = "は、はい……？ええっと、そう、でしょうか？"
"102030-130-ヒナ" = "うああ……あ、ありがとうございます……！？"
"102030-131-ヒナ" = "ミユは1980m離れた距離からも、狙撃を成功させたことがあります。 "
"102030-132-ヒナ" = "……そう。一目見ただけで、想像できる。#nこれからも成長するだろうね。"
"102030-133-ヒナ" = "先生が大変な時にRABBIT小隊を頼ったこと……#nそして、シャーレ奪還を共に遂行した事も……嘘じゃなさそう。"
"102030-134-サキ" = "ま、まぁ、別に大したことじゃないけどな。"
"102030-135-ヒナ" = "それと――"
"102030-136-ヒナ" = "あなたが、噂の[ruby=てんどう]天童[/ruby]アリス……"
"102030-137-ヒナ" = "（ミレニアムで起きた、例の事件の……）"
"102030-138-アリス" = "パンパカパーン！レベルカンストのガチ勢が仲間になりました！！"
"102030-139-ヒナ" = "……。"
"102030-140-アリス" = "わわっ！あ、アリス！？"
"102030-141-アリス" = "ご、ごめんなさい！#nアリスちゃん、時々変なことを言うんです……"
"102030-142-アリス" = "アリス、ゲヘナの風紀委員長の話、先生から聞いたことがあります！"
"102030-143-ヒナ" = "……先生が私のことを？"
"102030-144-アリス" = "（ひそひそ）ゲヘナの風紀委員長は、すっごく怖い人で……気に入らない人は容赦なく消すっていう噂を聞いたことがあるのに……。"
"102030-145-アリス" = "（ひそひそ）こ、怖い……も、もしかしたら怒られちゃうかも……。"
"102030-146-アリス" = "先生は、風紀委員長はとっても良い人だって言っていました！#nそれから――"
"102030-147-モモイ" = "そ、そうだっけ……？"
"102030-148-アリス" = "先生が？"
"102030-149-ヒナ" = "……それから？"
"102030-150-アリス" = "それから……頼りにしてる一人だと言っていました！#nすっごく頼もしい、と！"
"102030-151-アリス" = "なので、アリスは風紀委員長とパーティーを組めて光栄です！とても嬉しいです！"
"102030-152-ヒナ" = "……えっと。"
"102030-153-ヒナ" = "……いや、何でもない。 "
"102030-154-ヒナ" = "第3サンクトゥム、スタンバイ完了。RABBIT小隊及びゲーム開発部が待機中。#n作戦担当、確認願う。"
"102030-155-ヒナ" = "そういえば、今回の作戦担当は――"
"102030-156-ユズ" = "だ、第3サンクトゥム、作戦担当……は、[ruby=はなおか]花岡[/ruby]ユズ、です……"
"102030-157-ユズ" = "ど、どうして私が……うう。"
"102030-158-ミドリ" = "ユズちゃん、頑張って！ "
"102030-159-モモイ" = "そうだよ！これはユズにしかできない作戦だよ！"
"102030-160-ミヤコ" = "確認いたしました。#nユズさん、よろしくお願いいたします。 "
"102030-161-ユズ" = "は、はい……うう……。"
"102030-162" = "次回;作戦準備（２）"
