[translation]
"102040-1" = "第4話;作戦準備（２）"
"102040-2-ミサキ" = "これは…… "
"102040-3-ミサキ" = "そ、空が赤く染まって……な、何が起こっているんでしょうか……"
"102040-4-ミサキ" = "……先生からメッセージが届いたよ。#n手伝いが必要みたい。"
"102040-5-ミサキ" = "で、でも……私たちが行って助けになるのでしょうか？#n追われている身なのに……むしろ、先生に迷惑をかけるんじゃ……"
"102040-6-アツコ" = "そんなことないよ、きっと大丈夫。#nなんとか手伝えないか、方法を探そう。"
"102040-7-ミサキ" = "私たちでも、手伝えること……"
"102040-8-ミサキ" = "……そこにいるのは誰？"
"102040-9-ヒヨリ" = "ま、まさか追手が！？"
"102040-10-アツコ" = "……。"
"102040-11-怪しいヘルメット団" = "……。 "
"102040-12-ヒヨリ" = "！？"
"102040-13-アツコ" = "……。"
"102040-14-アツコ" = "……。"
"102040-15-怪しいヘルメット団" = "やっと見つけた。#nここにいたのか……"
"102040-16-ヒヨリ" = "み、ミサキさん！？いきなりそんな……"
"102040-17-ミサキ" = "誰？あんた。"
"102040-18-アツコ" = "すごく怪しい人……。"
"102040-19-怪しいヘルメット団" = "ま、待て。私は……！"
"102040-20-怪しいヘルメット団" = "ああ、そうか。このヘルメットはアルバイトで――"
"102040-21-アツコ" = "……なんてね。おはよう、サッちゃん。#n自分探しはお休み中？"
"102040-22-サオリ" = "……ああ。"
"102040-23-ミサキ" = "自分探しだなんて、よく言うよ。#nただの家出でしょ。"
"102040-24-ヒヨリ" = "リーダー……。"
"102040-25-サオリ" = "すまない……積もる話をしたいところだが、今は時間が無い。#n先生を助けなくては。"
"102040-26-ミサキ" = "うん。私たちにも連絡来たよ。"
"102040-27-ミサキ" = "は、はい！そうなんです！"
"102040-28-ミサキ" = "元気そうでよかった、リーダー。"
"102040-29-サオリ" = "……ああ。"
"102040-30-ミサキ" = "じゃ、行こうか。"
"102040-31-ハナコ" = "第4サンクトゥムの作戦担当、[ruby=うらわ]浦和[/ruby]ハナコです♡"
"102040-32-ハナコ" = "みなさん、準備はできましたか？ "
"102040-33-ヒナタ" = "……はい。#nシスターフッド部隊、サンクトゥムのカタコンベ前で待機中です。"
"102040-34-シスターフッド" = "ところで……サクラコ様は一体、どちらに……"
"102040-35-ミネ" = "救護騎士団、作戦地点にて待機しております。"
"102040-36-ミネ" = "よ、よろしくお願いします！"
"102040-37-ノア" = "第5サンクトゥムはいかがですか？#n報告をお願いします。"
"102040-38-チヒロ" = "……こっちは少し問題発生中。"
"102040-39-チヒロ" = "あら、どうされました？"
"102040-40-コタマ" = "「ホド」が要塞都市の地下に潜った。#n現在位置を確認してるけど……"
"102040-41-コタマ" = "要塞都市エリドゥの地下は、リオ会長が作った暗号で保護されています。#nハッキングも、振動も、音の感知も不可能でした。"
"102040-42-ノア" = "……リオ会長の？#nですが、会長はいま……"
"102040-43-ハレ" = "そう。#nだから、今暗号を解読するために演算を進めているところ。"
"102040-44-チヒロ" = "幸い、暗号はそこまで難しくないと思う……でも、時間がかなりかかってしまうのが問題。"
"102040-45-ハレ" = "はぁ……このままだと作戦時間に間に合わないかも……"
"102040-46-ノア" = "えっ、一大事じゃん！#nでも、こっちはサンクトゥムの分析をやってるから手伝えないし――"
"102040-47-ノア" = "マキさんは今まで通り第1サンクトゥムに集中を。#nエンジニア部の皆さん、余力はありますか？"
"102040-48-ウタハ" = "いや、こちらも各エリアのインベイドピラーを破壊しようとしてるけど……こっちも難航してるところでね。"
"102040-49-ヒビキ" = "はぁ……答えが見つからない……近づくことすらできないよ。"
"102040-50-ウタハ" = "サンクトゥムの素材分析も並行しているから、体力的にも限界でね……すまないが、これ以上の仕事は請け負えない。"
"102040-51-ヒビキ" = "もっと睡眠を～……いえ、カフェイン摂取で……妖怪MAXを……"
"102040-52-ヒビキ" = "やっぱ、普段からもうちょっと運動して体力つけておけば良かった……"
"102040-53-ウタハ" = "いま言っても仕方ないさ。"
"102040-54-ノア" = "困りましたね……あちらも余力は無さそうです。 "
"102040-55-ノア" = "流石はビッグシスター……いなくなってなお、問題の種を生むだなんて――"
"102040-56-チヒロ" = "ヒマリ！"
"102040-57-チヒロ" = "以前、ミレニアムの債券が偽造されたことがありましたよね？"
"102040-58-ヒマリ" = "債券発行のセキュリティシステムも、リオが構築したものですが――#nあの時はどのように解決したのですか？"
"102040-59-ヒマリ" = "ん？あれはヒマリの仕業じゃないの？#n私たちは倫理に背くようなことはしないよ。"
"102040-60-ヒマリ" = "あら、心外ですね。私だってしません。#nあの時は忙しくて、そんなイタズラをする暇もありませんでしたので……"
"102040-61-チヒロ" = "……じゃあ、あれは一体誰の仕業なの？"
"102040-62-ノア" = "……ユウカちゃん、聞いていましたか？ "
"102040-63-ユウカ" = "はぁ……聞いてるわよ。"
"102040-64-ユウカ" = "ノア、今から反省部屋の前に来て！"
"102040-65-ノア" = "はい。#n――それでは後ほど。"
"102040-66-ヒビキ" = "……インベイドピラーの攻略は……これが限界、かも。"
"102040-67-ヒビキ" = "……ピラー周辺に穴を掘って、地面から分離……そして焼き尽くす――"
"102040-68-ウタハ" = "本当にこの方法しか無いのかい？"
"102040-69-ヒビキ" = "他の方法を模索したかったけど……現状だとこれが精一杯の最善策、かな……"
"102040-70-ヒビキ" = "だが、この規模の工事は、もはや都市開発レベルの……"
"102040-71-ウタハ" = "うーん、何か別の手は無いだろうか……土木工事用のドローンを今から作るのは――"
"102040-72-コトリ" = "雷ちゃんに火炎放射器を付けるのはどうでしょう？#nスコップとハンマーを……"
"102040-73-ウタハ" = "それだけだと少し……"
"102040-74-？？？" = "はぁ～い！"
"102040-75-コトリ" = "あ、あなた達は一体！？"
"102040-76-温泉部の部員A" = "今日も今日とて、温泉開発日和だねー！"
"102040-77-ヒビキ" = "温泉……"
"102040-78-ウタハ" = "開発部……！？"
"102040-79-コトリ" = "お、温泉ですか？ここにそんなものは――"
"102040-80-？？？" = "ハーハッハッハッハ！そこに温泉があるから我々がいる！いや、たとえ温泉がなくても我々がいる！"
"102040-81-カスミ" = "細かいことは気にするな。#nそこは我々が担当しよう。"
"102040-82-ウタハ" = "う、うん……？"
"102040-83-メグ" = "掘って掘りまくって、建物を撤去して、全てを燃やし尽くしちゃえばいいんだよね？#nさあ温泉開発の時間だよ～！！"
"102040-84-メグ" = "最終的に温泉にたどり着ければ良いのだからな！難しく考える必要など無い！"
"102040-85-温泉部の部員A" = "それに、ミレニアムの地下にはどんな温泉があるのかずっと気になっていてね。つまり、絶好の機会というわけだ！"
"102040-86-一同" = "「「ハーッハッハッハッハ！！！」」"
"102040-87-コトリ" = "な、なんだかすごい方がいらっしゃいましたね……"
"102040-88" = "ミレニアム・反省部屋の前"
"102040-89-ユウカ" = "はぁ…… "
"102040-90-？？？" = "うぇえええっ、せ、先輩方！？"
"102040-91-ユウカ" = "コードネーム「白兎」……いえ、[ruby=くろさき]黒崎[/ruby]コユキ……#n出てきてちょうだい、釈放よ。"
"102040-92-ノア" = "コユキちゃん、元気でしたか？"
"102040-93-？？？" = "わ、私ですか？釈放？#nい、今？何でですか？"
"102040-94-ユウカ" = "時間が無いの。早く出なさい、コユキ。"
"102040-95-？？？" = "い、嫌です！いきなり先輩がやってきて釈放とか、絶対これアレですよね！"
"102040-96-？？？" = "ついに矯正局に送るんですよね！？そうなんですよね！？"
"102040-97-ユウカ" = "……。"
"102040-98-ノア" = "……。"
"102040-99-ユウカ" = "はぁ、これは無理やり連れていくしかないわね。#nノア、手伝ってちょうだい。"
"102040-100-ノア" = "ふふ、仕方ないですね。"
"102040-101-？？？" = "うわああっ！？こ、来ないで！#n先輩怖い！やだ！無理！パワハラ反対！！"
"102040-102-ユウカ" = "な、なんなんですか！今まで大人しくしてたじゃないですか！#n問題も起こしてないし、脱出だってしてないのになんで！酷い！暴力反対！冤罪ですよ！！"
"102040-103-ノア" = "あのねぇ……あんたがここにいるのは、自分で起こした問題のせいでしょうが！#nどこが冤罪だって言うのよ！？"
"102040-104-ノア" = "まあまあ、ユウカちゃん。#nコユキちゃんも反省しているようですし。"
"102040-105-ユウカ" = "反省！？これのどこが反省してるって言うのよ？"
"102040-106-コユキ" = "そうですよ！反省だなんて……まるで私が悪いかのような言い方はやめてください！"
"102040-107-コユキ" = "あれは不可抗力だったというか、ハプニングだったというか……"
"102040-108-ユウカ" = "債券の偽造が、ハプニング！？"
"102040-109-コユキ" = "そ、それに……すっごいコワモテのC&Cの先輩を使って私を捕まえにきたじゃないですか！もう、トラウマですよ！"
"102040-110-ユウカ" = "……。"
"102040-111-ノア" = "コユキちゃん……反省、しているんですよね？"
"102040-112-コユキ" = "へ、へっ……？えっと、その‥…最初から[ruby=ずさん]杜撰[/ruby]な暗号システムがいけないんじゃないですか？なので――"
"102040-113-ノア" = "コ～ユ～キ～ちゃ～ん？"
"102040-114-コユキ" = "ええっと……その……"
"102040-115-コユキ" = "せ、先輩……その顔、マジで怖いんでやめてください……"
"102040-116-コユキ" = "先輩の言う通り、私が間違ってました……"
"102040-117-ノア" = "反省は？"
"102040-118-コユキ" = "は、はい……反省してます……"
"102040-119-ノア" = "ふふっ、いい子ですね。"
"102040-120-ノア" = "ほら、ユウカちゃん。#n見ての通りコユキちゃんも反省しているみたいですよ？"
"102040-121-ユウカ" = "なんでノアに対しては大人しいわけ！？"
"102040-122-ユウカ" = "でもノア先輩は、たまに本当に怖いってか……夢に出てきそうな感じがして……"
"102040-123-コユキ" = "昔の発言を何時何分だったかまで指定して「コユキちゃん、あの時と言ってることが違いますよ？」って言ってきたりするから、マジでちょっと……"
"102040-124-コユキ" = "それで……お二人が訪ねてくるなんて、一体何があったんですか……？"
"102040-125-ノア" = "単刀直入に言うと、コユキちゃんの力が必要なんです。 "
"102040-126-ユウカ" = "そう。あんたのその摩訶不思議な演算能力が必要なの。#n今すぐセミナーに復帰してちょうだい。"
"102040-127-コユキ" = "い、今すぐセミナーに、ですか？#n私クビになったんじゃ……？"
"102040-128-ユウカ" = "そんな事ないわよ。#n詳しいことは行きながら説明するから、急いで。"
"102040-129-ノア" = "はい。コユキちゃんの制服も持ってきたので、こちらに着替えてください。"
"102040-130-コユキ" = "で、でも……この服、結構気に入って――"
"102040-131-ノア" = "コ～ユ～キ～ちゃ～ん？"
"102040-132-コユキ" = "ひっ……わ、分かりました……。"
"102040-133-アユム" = "残るは……D.U.の中心部にある第6サンクトゥムです。"
"102040-134-モモカ" = "おーい、そっちはどう～？"
"102040-135" = "D.U.中心部"
"102040-136-カンナ" = "市民の避難は完了した。#nサンクトゥムタワーから30km離れた場所に複数の避難所を設けている。"
"102040-137-カンナ" = "しかし、人員が足りない。あと、食糧もな。#nヴァルキューレと有志の協力者が避難所に常駐して手伝ってくれてはいるが――"
"102040-138-ジュリ" = "こちらをどうぞ。フウカ先輩が作ったおかゆです。#n温まりますよ。"
"102040-139-市民" = "ありがとうございます……。"
"102040-140-ジュリ" = "ジュリ、これも配ってもらえる？"
"102040-141-ジュリ" = "はい、先輩！"
"102040-142-フウカ" = "ふぅ……次は……"
"102040-143-ジュリ" = "何かお手伝いしましょうか？先輩。"
"102040-144-フウカ" = "大丈夫、炊き出しは慣れてるから。#nジュリは今まで通り配膳をお願い。"
"102040-145-ジュリ" = "はい、先輩！たしかにここは給食部の力が必要ですね！"
"102040-146-フウカ" = "力になれているのならいいけど……"
"102040-147-フウカ" = "でも、このままだと食材が足りなくなっちゃうかも……"
"102040-148-ジュリ" = "あら？"
"102040-149-フウカ" = "ちょっと、どうしたの！？"
"102040-150-イズミ" = "ふふふっ。フウカさん、助太刀に参りました。"
"102040-151-アカリ" = "到着です★"
"102040-152-フウカ" = "美食研究会が、どうして……！？#nというか、何でそんなに濡れて……！？"
"102040-153-ジュンコ" = "炊き出ししてるって聞いて、手伝いに来たのよ！ほら！"
"102040-154-イズミ" = "そうそう！食材持ってきたよー！"
"102040-155-ジュリ" = "あら……新鮮なお魚がこんなに……！"
"102040-156-ジュリ" = "これなら食材は足りそうですね、先輩！ "
"102040-157-フウカ" = "そ、そうだね……これで汁物に揚げ物、焼き物も作れるし……#n栄養バランスも大丈夫そう。"
"102040-158-フウカ" = "でも、何で給食部のトラックにあんた達が乗ってるのか、気になるんだけど……"
"102040-159-フウカ" = "まぁいいや。魚を集めるの、大変だったんじゃない？"
"102040-160-イズミ" = "すっごく大変だったんだよ！近くの水――"
"102040-161-イズミ" = "ンンンッッ！？"
"102040-162-アカリ" = "ま、まあ、細かいことは気にしないでちょうだい！"
"102040-163-ハルナ" = "ふふっ。私たちと給食部の仲ではありませんか。#n困っている時は助け合うべきです。"
"102040-164-フウカ" = "いや、そんな仲じゃないけど……"
"102040-165-フウカ" = "……まぁいいや。#n助けてもらったのは事実だし……ありがとね。"
"102040-166-アカリ" = "ふふっ、とんでもありません。"
"102040-167-ハルナ" = "ま、私たちもやる時はやるのよ！"
"102040-168-アカリ" = "友情って本当に素晴らしいですよね★"
"102040-169-イズミ" = "それで、この魚はいつになったら食べていいの～？"
"102040-170-アユム" = "今のD.U.シラトリ区は誰もいない。#n好きに暴れるがいい。"
"102040-171-アユム" = "ありがとうございます……第6サンクトゥムの守護者はまだ確認できていませんが、6つのサンクトゥムの中では最も強力なエネルギーを持っていますので……"
"102040-172-モモカ" = "守護者が現れたら避難完了したエリアに誘導して、そこで作戦を開始するよ～"
"102040-173-アズサ" = "ヒフミ、私たちはD.U.の外郭を巡回し、守護者を探す――[ruby=いわゆる]所謂[/ruby]、偵察部隊だ。"
"102040-174-アズサ" = "あう……どうして私たちが……"
"102040-175-アズサ" = "それはヒフミの操縦の腕がすごいからだろう。#nヒフミを守るのは私一人で十分だからな。"
"102040-176-アズサ" = "あの時は30人の正義実現委員会を一掃できたが……今ならその2倍来ようと問題ない。"
"102040-177-アズサ" = "そ、そういうつもりではなかったのですが……あうう……"
"102040-178-ヒフミ" = "……今日はペロロ様の特撮映画を観る予定だったのに……"
"102040-179-アズサ" = "うん、私も楽しみにしていた……"
"102040-180-アズサ" = "だから、この作戦が終わったら一緒に観よう、ヒフミ。"
"102040-181-ヒフミ" = "……"
"102040-182-ヒフミ" = "はい、アズサちゃん。この任務……最善を尽くしましょう！"
"102040-183-アズサ" = "ああ。"
"102040-184-ニヤ" = "準備完了かな？にゃはは。"
"102040-185" = "[s] \"ニヤ！どうだった？\""
"102040-186-ニヤ" = "それじゃカホ、後はよろしく～。"
"102040-187-カホ" = "ふぅ……皆さん、準備はよろしいでしょうか？"
"102040-188-イズナ" = "イズナ、主殿の声を聞きつけて参りました！#n特別任務を遂行すべく参上！"
"102040-189-ツクヨ" = "と、到着しました……"
"102040-190-ミチル" = "コホン！忍術研究部の部長、[ruby=ちどり]千鳥[/ruby]ミチル見参！#nここに参戦の意志を宣言するよ！"
"102040-191-イズナ" = "け、見参……ここに……宣言を……"
"102040-192" = "[s] \"忍術研究部……！？\""
"102040-193-ツクヨ" = "ツクヨ、忍術研究部の参戦を知らせる場面だよ！#nもっと存在感アピールしてこ！"
"102040-194-ツクヨ" = "そ、そうなんですか……？#nわ、私は、今でも十分、存在感がある気が……"
"102040-195-ツクヨ" = "んんー、これじゃあ足りないよ！"
"102040-196-ミチル" = "ツクヨ、イズナ！ "
"102040-197-イズナ" = "はい、部長！"
"102040-198-ツクヨ" = "は、はいっ！？ "
"102040-199-ミチル" = "「忍者流ハイパー決めポーズ」いくよっ！"
"102040-200-ツクヨ" = "へっ、こ、ここで、決めポーズ、ですか……！？ "
"102040-201-イズナ" = "さすがです、部長！#n思いっきり突撃するんですね！イズナ、理解しました！"
"102040-202-カホ" = "……。"
"102040-203-ニヤ" = "にゃははは！出ましたねぇ、あの名物決めポーズ～！"
"102040-204-ミチル" = "忍者とは何なのか！そして、忍法とは何なのか！"
"102040-205-ミチル" = "忍者の、真髄……！"
"102040-206-ツクヨ" = "……え、えっと本当に、大丈夫でしょうか……？"
"102040-207-ミチル" = "大丈夫！！その本質を研究し、探究し、そして究明する……"
"102040-208-ミチル" = "これでいいの！自分を信じてツクヨ！"
"102040-209-ミチル" = "忍者の魅力を広めるために暗躍する、キュートな忍者三人組！"
"102040-210-ミチル" = "三人組です～！！ニンニン！"
"102040-211-ミチル" = "泣く子も笑う、百鬼夜行連合学院、"
"102040-212-ミチル" = "最強の忍者集団！"
"102040-213-ミチル" = "その名も、「忍術研究部」！！"
"102040-214-カホ" = "……。"
"102040-215-ニヤ" = "（パチパチパチパチ！）#nにゃははは！流石皆さん。やっぱり忍者が正解だったねぇ～"
"102040-216" = "[s] \"えっと……\""
"102040-217-イズナ" = "イズナ、主殿が頼み事があると伺ったのですが……何をすれば良いでしょう？"
"102040-218-ミチル" = "ね。私たちにしかできないことって、何だろ？"
"102040-219-ニヤ" = "おっほん……ふむ、忍術研究部には、#nこれより別働隊として特別任務を遂行していただきたいのです。"
"102040-220-ミチル" = "特別任務……？"
"102040-221-カホ" = "……はい。#n今から皆さんには、百鬼夜行の最北端にある「大雪原」に向かっていただきます。"
"102040-222-ツクヨ" = "「大雪原」ですか！？"
"102040-223-ミチル" = "そこって雪しかないところじゃん！？何で……！？"
"102040-224-カホ" = "現在行方が分からなくなってしまった、#n「百花繚乱」の委員長を探していただきたいのです。"
"102040-225-イズナ" = "百花繚乱の……？#n委員長、ですか？"
"102040-226-ツクヨ" = "百花繚乱というと……紛争調停委員会の……ですか？#nい、委員会室にはいらっしゃらないのでしょうか……"
"102040-227-カホ" = "それが……"
"102040-228-カホ" = "……！#nたしかに最近、百花繚乱を見かけてないね。"
"102040-229-ミチル" = "何か事情があるんだよね、カホ。"
"102040-230-カホ" = "……はい、おっしゃる通りです。"
"102040-231-ミチル" = "にしても人探しなら、別に私たちがやらなくてもいいんじゃ……？"
"102040-232-ニヤ" = "それはですねぇ～……百花繚乱の姿を覚えている3年生、かつ信用できる方が――#n忍術研究部のルンルンさんしか居ないから、といいますか～？"
"102040-233-ニヤ" = "誰がルンルンさんだぁっ！？"
"102040-234-イズナ" = "おおっ、なんと！部長は百花繚乱の方を知っているのですね？ "
"102040-235-ミチル" = "うーん、何回かすれ違ったくらい……？#nでも、私もちゃんと覚えてないんだよね……"
"102040-236-ニヤ" = "んふふ。それだけで十分です。"
"102040-237-ミチル" = "（あの陰険部長、今度は一体何を企んでるの……？）"
"102040-238-ミチル" = "なるほど。イズナ、理解しました！#n「クズノハ」という方の行方を調べれば良いのですね！"
"102040-239-ミチル" = "その人を知ってるのが「百花繚乱の委員長」ね……#nん～了解、やってみる。"
"102040-240-ミチル" = "部長！百花繚乱は強いのですか？#n忍者みたいにカッコイイのでしょうか！"
"102040-241-ミチル" = "百花繚乱は、エリートばかりの委員会だったからなぁ……"
"102040-242-ツクヨ" = "ひゃ、百花繚乱、紛争調停委員会……その……聞いたことは、あるのですが……"
"102040-243-ミチル" = "まあ、忍者を超える事はないけどね！#nいつだって最後に残るのは、忍者なのさ！"
"102040-244-ミチル" = "そうですよね！さすがは忍者です！"
"102040-245" = "[s1] \"イズナ、ツクヨ、ミチル、よろしくね。大事な任務なんだ。\" \n[s2] \"その人を見つけたら「シャーレに連絡を」と伝えてほしい。\""
"102040-246-ミチル" = "はい、わかりました！"
"102040-247-ミチル" = "はい、わかりました！"
"102040-248-ミチル" = "はぁ、分かったよ……先生殿には色々お世話になったし……"
"102040-249-ツクヨ" = "は、はい……が、がんばります……"
"102040-250-ニヤ" = "こんな未曾有の危機が訪れているのです。百花繚乱が取る行動は決まってるといいますか、推測できるといいますか……"
"102040-251-ニヤ" = "百花繚乱の委員長は……おそらく、大雪原の「黄昏の寺院」に向かっているかと。"
"102040-252-ニヤ" = "私の情報網を総動員して推理した結果……ほぼ確実に、百花繚乱の委員長とクズノハが邂逅するのはそこになります。"
"102040-253-ニヤ" = "なので、そこに行けば会えるかと。にゃはは～。"
"102040-254-カホ" = "……今は、ニヤ様の推理が当たる事を願うばかりです。"
"102040-255-ニヤ" = "ひどいなぁ。それなりに自信がある結論なんですけど～"
"102040-256-カホ" = "幸い、大雪原は「虚妄のサンクトゥム」の影響が少ないので、そこまで危険ではありませんが……"
"102040-257-カホ" = "現状この事態に関して何も分かっていませんので、油断は禁物です。"
"102040-258-カホ" = "ですからどうか……気を付けてください。"
"102040-259-ニヤ" = "そうねぇ。#n状況が状況ですし、寺院に居なかった場合はすぐ帰還してくださいな。"
"102040-260-ニヤ" = "あと、この任務は内密にお願いしますね～"
"102040-261-カホ" = "……そうですね。まだ公にできない部分が多いので……"
"102040-262-イズナ" = "了解。誰も居なかったらすぐ戻るよ。"
"102040-263-ツクヨ" = "な、何かあった際には、ご連絡、します……よろしく、お願いします。"
"102040-264-ミチル" = "では、百花繚乱の委員長を探しに……忍術研究部、「大雪原」にいざ出陣です！"
"102040-265-ニヤ" = "さて、と……私たちは続報を待つとしましょっか。"
"102040-266-カホ" = "……。"
"102040-267-マコト" = "……キキキッ、なるほど。"
"102040-268-マコト" = "重要な情報を掴んだな。忍術研究部が、ねぇ。"
"102040-269-マコト" = "イロハ！どこにいるイロハ！アレを用意しろ！ "
"102040-270-マコト" = "えっ、何をですか？#nというか、私たちはシャーレの呼び出しに応じなくていいんですか？"
"102040-271-マコト" = "……キキキッ、それについては心配するなイロハ。#n全部、既に手配は完了している。"
"102040-272-イロハ" = "はい？また何を言って……"
"102040-273-マコト" = "キキキッ、これは絶好のチャンスということだ。#n逃すわけにはいくまい。"
"102040-274" = "次回;作戦準備（３）"
