[translation]
"102160-1" = "第16話;「ミレニアム」自治区防衛"
"102160-2-ウタハ" = "さあ、私たちの番だよ。"
"102160-3-スミレ" = "はい！準備バッチリです！"
"102160-4-ウタハ" = "ミレニアム自治区の防衛、私も手伝わせていただきます。 "
"102160-5-ヒビキ" = "はぁ……サンクトゥムの素材分析に、データ分析……#nその上、今度は防衛戦……体が10個あっても足りない……"
"102160-6-AMAS A" = "おや、AMASが……？"
"102160-7-コトリ" = "私たちを手伝ってくれるのでしょうか？じゃあ、これはヴェリタスが……？"
"102160-8-ハレ" = "ん、違うよ。あれをハッキングできるのはヒマリ部長だけのはず……"
"102160-9-ヒマリ" = "おや、私でもありませんよ？"
"102160-10-コトリ" = "えっ、そ、それじゃあ一体誰が……#nま、まさか幽霊が動かして……！？"
"102160-11-ウタハ" = "……。"
"102160-12-ヒビキ" = "……。"
"102160-13-ヒマリ" = "……まあ、いいんじゃないんでしょうか。人手はいつも足りてないですし。"
"102160-14-ウタハ" = "……そうだね。じゃ、行こうか。"
"102160-15-ウタハ" = "出発！"
