[translation]
"102130-1" = "第13話;「トリニティ」自治区防衛（１）"
"102130-2-正義実現委員会部員B" = "こちらです！"
"102130-3-正義実現委員会部員A" = "みなさん、こちらに避難を！"
"102130-4-マシロ" = "トリニティ自治区の避難誘導は私たちが務めます！#nマシロ、後方支援を！"
"102130-5-ハスミ" = "はい、ハスミ先輩！"
"102130-6-シミコ" = "こちらにお入りください！#n古書館はトリニティのなかでも歴史の長い建物なので、まだ比較的崩れにくいはずです！"
"102130-7-ウイ" = "私の古書館……私だけのアジトが……うぅ……"
"102130-8-ウイ" = "委員長も！今回はみなさんのために開放しているのですから、#nもっと楽しそうな表情で！"
"102130-9-ウイ" = "ああ……ううぅっ……"
"102130-10-正義実現委員会部員B" = "う、うわぁっ！？"
"102130-11-正義実現委員会部員A" = "こっちにも敵が！？"
"102130-12-スズミ" = "手が足りないようですね、私たちも手伝います。"
"102130-13-レイサ" = "はい！#nトリニティの「走る閃光弾」と、自警団の「スーパースター」が到着しましたよ！"
"102130-14-ハスミ" = "自警団のみなさん……！"
"102130-15-レイサ" = "れ、レイサさん……その呼び名は少し……"
"102130-16-スズミ" = "ああっと！そんな事を言っている間に敵襲が！#nこれは大ピンチ！"
"102130-17-スズミ" = "――ですが！"
"102130-18" = "……この程度でこの私、[ruby=うざわ]宇沢[/ruby]レイサを仕留められると思わないでください！スズミさん、今の見ましたか！私の華麗な――"
"102130-19-スズミ" = "すみません、今はすぐにあちらに向かわなくてはなりません。#n行きましょう、レイサさん。"
"102130-20-レイサ" = "あっ、はい！「走る閃光弾」の本領発揮ですね！"
"102130-21-レイサ" = "スズミさーん！待ってくださーい！"
"102130-22-カズサ" = "……。"
"102130-23" = "カズサちゃんどうしたの？"
"102130-24-アイリ" = "……いや、元気そうだなと思って。"
"102130-25-ヨシミ" = "で、何で私たちは避難しないの？"
"102130-26-ヨシミ" = "おやおや、ヨシミくん。仮にも私たちは放課後スイーツ部だよ？#nこういう非常事態には手を差し伸べるべきじゃないかな。スイーツのように。"
"102130-27-ナツ" = "は？何言ってんの？ってかスイーツ関係ないし。"
"102130-28-カズサ" = "で、でも……正義実現委員会のみなさんも大変そうだし……#nお手伝いしたら喜んでくれるかも……"
"102130-29-アイリ" = "だね。私たちも行こっか。"
"102130-30-カズサ" = "うん！"
"102130-31-ナツ" = "はぁ……仕方ないわね。"
"102130-32-正義実現委員会部員D" = "ああっ！あちらに聖徒会の[ruby=ミメシス]複製[/ruby]が出現しています！"
"102130-33-正義実現委員会部員C" = "なっ！？あっちはまだ防衛体制が整ってないのに……！！"
"102130-34-？？？" = "砲手、支援を。"
"102130-35-ハスミ" = "これは……L118、牽引式榴弾砲……？"
"102130-36-？？？" = "ええ、ハスミさん。その通りです。#n懐かしい響きではありませんか？"
"102130-37-マシロ" = "……ナギサ様……セイア様……。"
"102130-38-ハスミ" = "……私、ナギサ様を外で見るのは初めてです。"
"102130-39-マシロ" = "ティーパーティーの支援に感謝します。 "
"102130-40-ナギサ" = "いえ。#nこの程度もできなければ、ティーパーティーとしての面目が立ちませんから。"
"102130-41-ナギサ" = "ではセイアさん、後はお願いします。"
"102130-42-セイア" = "次は……北東方向、座標は――"
"102130-43-ナギサ" = "……。"
"102130-44-ナギサ" = "セイアさんの予知能力は無くなってしまいましたが……#nその代わりにと言いますか、別の力が与えられたとでもいうのでしょうか。"
"102130-45-セイア" = "能力と呼ぶのかどうかは定かではないが……感覚が鋭くなってね……"
"102130-46-ナギサ" = "……「勘」が良くなった、ということにしておきましょうか。"
"102130-47-セイア" = "……ミカ、そちらの状況はどうだい？"
"102130-48-ミカ" = "うん、こっちは大丈夫。#n私一人で平気だから、そっちの防衛に力を入れちゃって。"
"102130-49-セイア" = "……ああ。無理はしないように。"
"102130-50-ナギサ" = "では、こちらの防衛は私たちが手伝いましょう。#nハスミさん、指揮をお願いします。"
"102130-51-ハスミ" = "……分かりました、では遠慮なく。"
