[translation]
"102110-1" = "第11話;「ゲヘナ」自治区防衛"
"102110-2-アコ" = "私たちの番ですね。#n皆さん、準備はできましたか？"
"102110-3-チナツ" = "はい。いつでも行けます。"
"102110-4-イオリ" = "ところでアコちゃん、委員長はどこに？"
"102110-5-アコ" = "ヒナ委員長は、風紀委員会の代表としてサンクトゥム攻略戦に参加中です。"
"102110-6-アコ" = "風紀委員会の代表……？#nなんで？みんなはここにいるのに？"
"102110-7-イオリ" = "そうやって委員長にばかり頼るから、風紀委員が寄せ集め集団だの、委員長がいなければ敵じゃないだの言われるんですよ！"
"102110-8-イオリ" = "え、えっ？その……私は委員長がどこにいるか知りたかっただけで……"
"102110-9-アコ" = "そうやって甘えるから！委員長が面倒くさがるんです！#n今度こそ、寄せ集めの集団ではないということを証明しますよ。分かりましたね、イオリ！"
"102110-10-イオリ" = "う、うーん……"
"102110-11-チナツ" = "（……そのイメージはきっと、私たちが弱いのではなく、委員長の強さによって作られているのでしょうけど）"
"102110-12-アコ" = "はぁ……ところで、こんな状[ruby=パンデモニウム・ソサエティー]況なのに万魔殿のマコト[/ruby]議長は一体何をしているのでしょうか……？"
"102110-13-万魔殿のメンバー" = "うふふ……風紀委員会の皆さん、わざわざご苦労さま。"
"102110-14" = "あ、あなたは……万魔殿のサツキ議員？"
"102110-15-イオリ" = "お前……"
"102110-16-サツキ" = "まあまあ、落ち着いて頂戴？"
"102110-17-サツキ" = "こんな時に争ったって、あなた達が困るだけでしょう？"
"102110-18-サツキ" = "……っ。"
"102110-19-アコ" = "万魔殿は今まで何をされていたのでしょうか。#nそして、マコト議長はどちらに？"
"102110-20-サツキ" = "マコトちゃんは、ちょ～っと大事な用事があってね。#nま、気にしないで頂戴。"
"102110-21-アコ" = "……あなた達、また何か企んでいるんですか？#n今度はどんな画策を――！"
"102110-22-サツキ" = "ホント勘弁してよねぇ。私たちを何だと思ってるの？#n万魔殿にとって一番大切なものが何か、分かる？"
"102110-23-アコ" = "[ruby=むいとしょく]無為徒食[/ruby]では……？"
"102110-24-サツキ" = "はぁ……「[ruby=・   ・   ・]有権者[/ruby]」よ。#n私たちは今の今まで、ゲヘナ生のために頑張っていたのよ？"
"102110-25-アコ" = "なにを戯言を――"
"102110-26-セナ" = "行政官、これは事実です。"
"102110-27-アコ" = "セナ部長……？"
"102110-28-セナ" = "サツキ議員と万魔殿の方々が、市民を避難所に誘導してくれました。#nおかげで避難誘導の時間短縮に繋がっています。"
"102110-29-セナ" = "やり方はやや珍妙ではありましたが――"
"102110-30-キララ" = "キララちゃん、さっきの見た？"
"102110-31-キララ" = "糸にコインをぶら下げてたやつだよね？#nあれマジで初めて見た～！催眠術ってやつでしょ？"
"102110-32-エリカ" = "そうそう！アレ全然意味なかったよね。超ウケる。"
"102110-33-キララ" = "あははっ！面白そうだったからついてきちゃったけどね～"
"102110-34-アコ" = "……催眠？今度は何のオカルトですか……"
"102110-35-アコ" = "私のNKウルトラ計画は、オカルトではなく科学よ！#nはぁ、これだから素人は困るのよ。"
"102110-36-サツキ" = "ま、今のあなた達には理解できないでしょうけどね、アハッ……！#nでもこれが完成した暁には――"
"102110-37-サツキ" = "雑談は結構。"
"102110-38-アコ" = "それで……万魔殿がこちらに来たのは――#n私たちに協力してくださるということでしょうか？"
"102110-39-サツキ" = "アハッ！そんなわけないでしょ。通りすがりに応援しに来ただけよ。"
"102110-40-サツキ" = "あなたは段々強くなった気分になぁ～る#n万魔殿に忠誠を誓いたくなぁ～る。"
"102110-41-サツキ" = "ほら……っ！"
"102110-42-サツキ" = "……フンッ、効果は無いようね。"
"102110-43-アコ" = "はぁ……"
"102110-44-アコ" = "ゲヘナ自治区の防衛戦を始めます。"
