[translation]
"102200-1" = "第20話;最終防衛戦「シャーレ」"
"102200-2-アユム" = "第1から第5サンクトゥムまでの突入準備、できてます……！"
"102200-3-アユム" = "全自治区の防衛戦も完了してるよ。#nおつかれ～"
"102200-4-リン" = "――全ての準備が整いましたね。"
"102200-5-リン" = "……っ！#n何事ですか！？"
"102200-6-モモカ" = "えーっと……"
"102200-7-モモカ" = "……うえぇっ！？"
"102200-8-モモカ" = "ど、どうしたんですかモモカちゃん……！？"
"102200-9-モモカ" = "しゅ、襲撃！！シャーレ周辺に敵襲！#nい、いつの間にこんな……！"
"102200-10-ヴァルキューレの生徒B" = "正門の防衛は私たちが担当しよう。"
"102200-11-ヴァルキューレの生徒B" = "後門は余力のある者に頼みたい。"
"102200-12-スケバン" = "クックックッ……ちょうど暇してたんだよなぁ。"
"102200-13-スケバン" = "後門側の防衛はあたしらが引き受けた！"
"102200-14-スケバン" = "こわーいお姉さんたちの力を見せてやるぜ！#nクックックックッ！"
"102200-15-スケバン" = "うし、行くぞ！"
"102200-16" = "ダテにツッパってねぇんだよこちとらよぉ！！"
"102200-17-ラブ" = "ヘルメット団、全員集合！！"
"102200-18-ヘルメット団員B" = "ま、そういうこと。#nヘルメット団幹部――[ruby=こまかぜ]河駒風[/ruby]ラブ、助太刀しようじゃないの！！"
"102200-19-ヘルメット団員B" = "ほら、シャーレを守るんだよ！全員突撃！！"
"102200-20-？？？" = "うふふふふ……♡"
"102200-21-ワカモ" = "なんと不憫なあなた様……ですがご安心を。#nこのワカモにお任せください。"
"102200-22-ワカモ" = "果ての果てまで、あなた様をお守りいたしましょう。"
"102200-23-ワカモ" = "うふふっ……では、始めましょうか？"
