[translation]
"10056070-1" = "第7話;ブルーホール"
"10056070-2" = "（波をかき分けながら、船は進み続けた）"
"10056070-3-サユリ" = "先生、着いた。"
"10056070-4-サユリ" = "ここが地図に書いてあったポイント。"
"10056070-5" = "（船が止まったので、外に出てみた）"
"10056070-6" = "（大海原の中、そこだけ別のインクを垂らしたように濃い青色で染まっていた）"
"10056070-7" = "[ns] \"……神秘的だね。\""
"10056070-8-ココロ" = "はい……見る分には。"
"10056070-9-ココロ" = "ブルーホールは洞窟や鍾乳洞が水没して形成されるので、#n奥に入り込んでしまうと抜け出せなくなることもあるんです。"
"10056070-10-ココロ" = "だからこそ挑戦しがいがあるのですが、それだけ危険だとも言えます。"
"10056070-11-ココロ" = "なので、普段よりも準備を徹底しないと……！"
"10056070-12-マキナ" = "いつも細かいのに、それ以上になんてできるの？"
"10056070-13-ココロ" = "も、もちろん！"
"10056070-14-ココロ" = "2回チェックするところを3回、3回を4回にすれば――"
"10056070-15-コトネ" = "そしたら日が暮れちゃう……。"
"10056070-16-コトネ" = "どっちから先に潜るか決めようか。"
"10056070-17-ココロ" = "はい！はいはいはい！#n私とサユリが先に行く！"
"10056070-18-ココロ" = "マキナが？"
"10056070-19-マキナ" = "うん。"
"10056070-20-マキナ" = "今回のことは私の責任でもあるからさ……。"
"10056070-21-ココロ" = "で、でも、どんな危険があるかも分からない場所だし、先に行くなら、#n部長の私のほうが……。"
"10056070-22-マキナ" = "危ないのは、誰が行っても同じじゃん？"
"10056070-23-マキナ" = "だいじょうぶ、心配ないよ。危なかったら急いで上がってくるから。"
"10056070-24-サユリ" = "サユリ・イズ・ファスト～"
"10056070-25-ココロ" = "ふ、浮上する時はゆっくり時間をかけてね！？"
"10056070-26" = "（その後、ココロの必死の頼みを聞きながら、マキナとサユリが海に入っていった）"
"10056070-27" = "（それから1時間ほど過ぎた頃）"
"10056070-28-マキナ" = "ふぅ……。"
"10056070-29-コトネ" = "おかえり。思ったより戻りが早いね。"
"10056070-30-ココロ" = "な、何か問題でもあった？"
"10056070-31-サユリ" = "ううん、ダイビングは問題ないよ。"
"10056070-32-サユリ" = "クジラがいた～"
"10056070-33" = "[s] \"クジラ？\""
"10056070-34-マキナ" = "ザトウクジラの群れが押し寄せてきて、それ以上は潜れなかったんだ。#n水深60メートルくらいかな。"
"10056070-35-マキナ" = "他じゃあんなの見たことないのに……どうしたんだろ？"
"10056070-36-マキナ" = "もっと深い場所に捕食生物がいるのかもね。#n前にサメを見つけた時がそうだったみたいに。"
"10056070-37-マキナ" = "そんな危険な生物がいるようには見えないけどね。"
"10056070-38-サユリ" = "ルスカだ……！"
"10056070-39-マキナ" = "だからそれは[ruby=UMA]未確認生物[/ruby]だってば。"
"10056070-40-ココロ" = "まさか……あの時に聞いたお宝って……。"
"10056070-41-マキナ" = "……部長？"
"10056070-42-ココロ" = "な、なんでもないよ。"
"10056070-43-ココロ" = "とにかくお疲れ様。次は私とコトネが行くね。"
"10056070-44-コトネ" = "了解。"
"10056070-45-サユリ" = "あ、ウミネコ。"
"10056070-46-マキナ" = "……そうだね。"
"10056070-47-サユリ" = "今度はアヤトビウオ～"
"10056070-48-マキナ" = "……ほんとだ。"
"10056070-49-マキナ" = "……。"
"10056070-50" = "[s] \"何か言いたいことでもあるの？\""
"10056070-51-マキナ" = "えっ？あ、ううん。"
"10056070-52-マキナ" = "ただ待ってるだけだと、なんか持て余しちゃって。"
"10056070-53-マキナ" = "……あのさ。"
"10056070-54-マキナ" = "シャーレの先生って、超法規的権限を持ってるんだよね？"
"10056070-55-マキナ" = "生徒に対して自由に命令とか指示を出せるんじゃないの？"
"10056070-56" = "[s1] \"た……ぶん？\"\n[s2] \"制度上はそうかも？\""
"10056070-57-サユリ" = "じゃあ、欲しいものは何でも手に入る？"
"10056070-58-サユリ" = "生徒から無理やり10万円もらうとか。"
"10056070-59" = "[s3] \"そんなことはないよ……。\"\n[s4] \"できるとしても、やりたくはないな……。\""
"10056070-60-マキナ" = "どうしてそんな権限を持ってるのに、生徒の話を聞いてるだけなの？"
"10056070-61" = "[s] \"例えば？\""
"10056070-62-マキナ" = "だって今回のことも、一言で解決できるでしょ？"
"10056070-63-マキナ" = "ダイビングを辞めろって私たちに命令すれば済むのに。"
"10056070-64" = "[s] \"マキナはダイビングを辞めたいの？\""
"10056070-65-マキナ" = "そんなわけない！"
"10056070-66-マキナ" = "でも、アイランドは私たちのせいで困ってるし。"
"10056070-67-マキナ" = "先生にとっては、あっちも「生徒」だよね？"
"10056070-68" = "[s] \"そうだね。\""
"10056070-69-マキナ" = "生徒のためって言うのに、生徒が解決するのを待ってるだけな気がするんだ。"
"10056070-70-マキナ" = "行き詰まってるのに足掻きつづける生徒を見てるだけって――"
"10056070-71-マキナ" = "もどかしくない？"
"10056070-72" = "[s] \"そういう時もあるよ。\""
"10056070-73-マキナ" = "先生が代わりに結論を出したらダメなの？"
"10056070-74" = "[s5] \"ダメだよ。\"\n[s6] \"私にはそんな権限はないから。\""
"10056070-75-マキナ" = "なんで？全生徒に命令して指示する権限があるんでしょ？"
"10056070-76" = "[s7] \"それはあくまで「指示」できるだけ。\"\n[s8] \"指示を受け入れるのは生徒自身だから。\""
"10056070-77-マキナ" = "んー……？#nなんか煙に巻かれたような……。"
"10056070-78-マキナ" = "怪しい大人の香りが……。"
"10056070-79-サユリ" = "マキナ、マキナ。"
"10056070-80-マキナ" = "どしたん？部長たち上がってきた？"
"10056070-81-サユリ" = "違う。水平線のほうから、誰かがこっちに来てる。"
"10056070-82-マキナ" = "この辺は航路じゃないのに？#nトライデントのパトロールにしては沖合過ぎるし……。"
"10056070-83-サユリ" = "……あの旗、知ってる。"
"10056070-84-マキナ" = "あれって――"
"10056070-85-マキナ" = "[ruby=ちょうすい]潮水の[/ruby][ruby=こうりゅう]蛟龍！[/ruby]？"
"10056070-86" = "[s] \"たしか、問題の生徒だっけ。\""
"10056070-87-マキナ" = "問題どころじゃない！"
"10056070-88-マキナ" = "潮水の蛟龍はオデュッセイアで……いや、キヴォトスで最凶の海賊集団の頭なんだよ！"
"10056070-89-マキナ" = "先生、逃げ――"
"10056070-90-マキナ" = "いや、逃げ場ないね、これ。"
"10056070-91-マキナ" = "とりあえず隠れよう！#nサユリ、海賊が出たって部長に連絡して！"
"10056070-92-サユリ" = "メーデー、メーデー！"
"10056070-93-ココロ" = "……[USERNAME]先生！"
"10056070-94-ココロ" = "くっ、いつの間に……。"
"10056070-95-コトネ" = "もうかなり接近されてるね。ボートで戻るのは難しいかな。"
"10056070-96-コトネ" = "部長、どうする？"
"10056070-97-ココロ" = "まずはバディチェックから。問題ない？"
"10056070-98-コトネ" = "問題なし。"
"10056070-99-ココロ" = "サユリ。マキナは「潮水の蛟龍」って言ってたんだよね？"
"10056070-100-サユリ" = "うん。サユリも旗を見た。"
"10056070-101-コトネ" = "いつの間にあんな艦隊を確保したのかは知らないけど……#n喫水が浅いから、装備はそんなに積んでないと思う。"
"10056070-102-ココロ" = "もう一度潜って位置を――"
"10056070-103" = "下手な真似をするより、諦めるほうが身のためだぞ。"
"10056070-104-？？？" = "お主らの相棒と[USERNAME]先生はすでに余の手中にある。"
"10056070-105-コトネ" = "いつの間に……。"
"10056070-106-マキナ" = "ごめん、部長……。"
"10056070-107-マキナ" = "部長たちが上がってくるまで時間稼ぎしようと思ったんだけど……。"
"10056070-108-マキナ" = "先生を守り切れなくて……。"
"10056070-109" = "[s9] \"ごめん、油断してた……。\"\n[s10] \"話が通じる相手じゃないね……。\""
"10056070-110" = "新しい臣下を迎えると聞いたが、まさかシャーレの先生まで含まれているとは。"
"10056070-111-？？？" = "白蛤を開けたら、思いがけず真珠が出てきた気分だな。"
"10056070-112-潮水の蛟龍" = "まずは余とじっくり話し合わぬか？"
"10056070-113-潮水の蛟龍" = "[ruby=とうみ]渡海[/ruby]ココロ。"
