[translation]
"201050-1" = "第5話;記憶の誤り"
"201050-2-リン" = "あなたが……連邦生徒会長？"
"201050-3-連邦生徒会長" = "ええ、そうですよ……どうされましたか、リン。"
"201050-4-連邦生徒会長" = "たしかに長い間、私は席を外していました。#nですが、まるで「初対面」のように接するなんて……。"
"201050-5-リン" = "いいえ。私はあなたを知りません。"
"201050-6-連邦生徒会長" = "……リン。"
"201050-7-連邦生徒会長" = "急に姿を消したことをずっと気にしていたのですか？"
"201050-8-連邦生徒会長" = "何を言っても言い訳にしかならないかもしれません。#nですが――"
"201050-9-リン" = "いいえ、言葉通りです。"
"201050-10-リン" = "初対面のはずです。私はあなたを知りません。#n顔も、声も、何もかも。"
"201050-11-リン" = "私の知る連邦生徒会長は、あなたではありません。"
"201050-12-リン" = "冗談だとしても、笑って流せる範疇を越えています。"
"201050-13-連邦生徒会長" = "……何かあったのですね。"
"201050-14-連邦生徒会長" = "失礼、今すぐアオイ……いえ、財務室長を呼んでくれますか？"
"201050-15-連邦生徒会長" = "行政官に関してお話が――"
"201050-16-リン" = "（この人は何を考えているのでしょうか？）"
"201050-17-リン" = "（人が来ればすぐに明らかになるというのに、財務室長を呼ぶだなんて――）"
"201050-18-アオイ" = "あら……リン行政官。ここにいたのね。"
"201050-19-アオイ" = "昨日は寮に戻らなかったと聞いたから心配していたの。#nまさか、休暇が終わってすぐに徹夜でもしたのかしら？"
"201050-20-アオイ" = "せっかく休みを取ってもらったのに、それでは意味がないじゃない。"
"201050-21-リン" = "今はそれよりもこの部外者を――"
"201050-22-アオイ" = "それで……何の用かしら、[ruby=・   ・   ・   ・   ・   ・]連邦生徒会長[/ruby]？"
"201050-23-リン" = "……え？"
"201050-24-リン" = "アオイ、今なんと……。"
"201050-25-アオイ" = "どうかしたのかしら？"
"201050-26-アオイ" = "連邦生徒会長に話しかけているのだけど。"
"201050-27-リン" = "アオイ……。"
"201050-28-リン" = "あなたは……この人を連邦生徒会長だと！？"
"201050-29-アオイ" = "リン先輩こそ何を言っているの？"
"201050-30-アオイ" = "当然のことを確認するなんて……。"
"201050-31-アオイ" = "この人が、私たちの連邦生徒会長でしょう？"
"201050-32-スモモ" = "……連邦生徒会長？元々あんなだったでしょ？"
"201050-33-スモモ" = "ちょっと雰囲気変わった気がするけど……それくらいじゃない？"
"201050-34-モモカ" = "そりゃ覚えてるよ。明太子味ポテチみたいな白金色を忘れるわけないじゃない。"
"201050-35-モモカ" = "え？髪は水色だった……？"
"201050-36-モモカ" = "勘違いじゃない？"
"201050-37-ハイネ" = "連邦生徒会長の姿？もちろん覚えてるよ！"
"201050-38-ハイネ" = "ピンク髪に緑の瞳をした――"
"201050-39-ハイネ" = "って、これはカヤ元代行だっけ。うーん、たしか連邦生徒会長は……。"
"201050-40-ハイネ" = "黒髪……だったっけ？"
"201050-41-アユム" = "せ、先輩……そう何度も聞かれましても、私にはよく分かりません。"
"201050-42-アユム" = "連邦生徒会長は、今も昔もお変わりありませんよ。"
"201050-43-アユム" = "その……お言葉ですが……。"
"201050-44-アユム" = "最近無理をしすぎたせいで、記憶に混乱が生じているのではないでしょうか？"
"201050-45-連邦生徒会長" = "……少しは落ち着きましたか？"
"201050-46-連邦生徒会長" = "なんだか、今日はリンらしくないですね。"
"201050-47-リン" = "どうして……皆さん覚えていないのですか。"
"201050-48-リン" = "あれほど長い時間を共にしてきたのに……どうして？"
"201050-49-リン" = "いえ、だからこそ……皆さんが連邦生徒会長だと思っているあなたは……#n誰なのですか？"
"201050-50-連邦生徒会長" = "これは……私のせいなのかもしれません。"
"201050-51-連邦生徒会長" = "長らく席を外していたせいで、あまりにも大きな負担をかけてしまいました。"
"201050-52-連邦生徒会長" = "人の記憶は過度なストレスや疲労などで容易に変わってしまうもの。#nですから、リンが私を覚えていなくても――"
"201050-53-リン" = "いいえ。"
"201050-54-リン" = "皆さんが覚えていなくても……彼女が残した痕跡、記録は残っていますから。"
"201050-55-リン" = "会長と一緒に撮った写真を見れば――"
"201050-56-リン" = "どうして……？"
"201050-57-リン" = "会長だけ……消えている……？"
"201050-58-連邦生徒会長" = "……ごめんなさい、リン。"
"201050-59-連邦生徒会長" = "しばらくは業務について考えなくても大丈夫です。#n私が巻き取りますから。"
"201050-60-連邦生徒会長" = "せっかくですし、もう少し休暇を楽しんでください。"
"201050-61-リン" = "たしかに、この写真は……。"
"201050-62" = "[ns1] \"おっはよう！\"\n[ns2] \"昨日はぐっすり眠れた？\""
"201050-63-リン" = "[USERNAME]先生……！"
"201050-64-リン" = "ちょうどいいところにいらっしゃいました。先生にご確認したいことがあります。"
"201050-65-リン" = "この方は……連邦生徒会長ですか？"
"201050-66" = "[ns3] \"この子が……？\"\n[ns4] \"私は知らないかな……。\""
"201050-67-リン" = "……やはり。"
"201050-68-リン" = "そう言ってくださると、信じていました。"
"201050-69-リン" = "私が記憶している連邦生徒会長は……間違っていないのですね？"
"201050-70" = "[s5] \"リン、落ち着いて。\"\n[s6] \"その子も困ってるみたいだから。\""
"201050-71" = "[ns] \"まずは話を聞いてみよう？\""
"201050-72-連邦生徒会長" = "あら……。"
"201050-73-連邦生徒会長" = "リンがここまで大人を頼るだなんて、珍しいですね。"
"201050-74-連邦生徒会長" = "良い変化だとは思いますが、なんだか少し寂しい気もします。ふふっ。"
"201050-75" = "[s] \"……まずは君のことを教えてくれるかな。\""
"201050-76-連邦生徒会長" = "ええ。初めまして。"
"201050-77-連邦生徒会長" = "私はこの学園都市キヴォトスを管理する連邦生徒会の長、連邦生徒会長です。"
"201050-78-連邦生徒会長" = "自分で言うのも気恥ずかしいのですが、キヴォトスではそれなりに顔を知られてまして。#n私を知らないほうが珍しいと思うのですが……。"
"201050-79-連邦生徒会長" = "なかなか面白い反応ですね。"
"201050-80-連邦生徒会長" = "あなたはキヴォトスの外からいらしたのですか？"
"201050-81-連邦生徒会長" = "よければそちらの話も伺いたいのですが。"
"201050-82" = "[s] \"私はシャーレで先生を務めている[USERNAME]だよ。\""
"201050-83-連邦生徒会長" = "シャーレ……？"
"201050-84-連邦生徒会長" = "それはどういった組織で？"
"201050-85" = "[s7] \"超法規的な権限を持つ連邦捜査部。\"\n[s8] \"生徒の悩みを聞いたり解決したりする仕事をしてるよ。\""
"201050-86-連邦生徒会長" = "学園を超越する超法規的機関……。"
"201050-87-連邦生徒会長" = "それほどの権限を持つとなれば、連邦生徒会長の許可が必要なはずです。"
"201050-88-連邦生徒会長" = "ですが、私は許可した覚えがありません。"
"201050-89-連邦生徒会長" = "これは……流石に目を瞑ることはできませんね。"
"201050-90" = "[s] \"……え？\""
"201050-91" = "[ns] \"ええっ！？\""
"201050-92" = "次回;超人の帰還"
