[translation]
"1009003-1" = "思い出す、お祭りの記憶"
"1009003-2-ウミカ" = "わぁ～、先生！"
"1009003-3-ウミカ" = "百夜堂へようこそ～#nご注文は何にしますか？"
"1009003-4-ウミカ" = "おすすめは苺あんみつ、八ツ橋、どら焼き、お饅頭、それから大福も……"
"1009003-5-ウミカ" = "お飲み物は抹茶が一押しですよ！"
"1009003-6" = "[s1] \"じゃあ……あまり甘くないやつ！\"\n[s2] \"じゃあ……一番甘いやつ！\""
"1009003-7-ウミカ" = "はい！ご注文承りました！少々お待ちください！"
"1009003-8" = "[ns] \"今日はお客さんがいないんだね……？\""
"1009003-9-ウミカ" = "そうですね。時々、こんなふうにお客様があまり来ない日もあるんですよ。"
"1009003-10-ウミカ" = "たまに……週に1回か、2回くらいでしょうか？"
"1009003-11-ウミカ" = "そういう時でも、いつお客様が来ても良いように準備しています！#n休んだりはしていませんよ……！"
"1009003-12-ウミカ" = "……えっ？先生が許すから、一緒に休憩しよう……？"
"1009003-13-ウミカ" = "そ、それじゃあ、先生。失礼、しますね……？"
"1009003-14-ウミカ" = "はあぁ～……やっぱり座ると落ち着きます……。#n足も疲れていたので……。"
"1009003-15" = "[s] \"うん、そうだよね。\""
"1009003-16-ウミカ" = "先生は優しいですよね……いつも気遣ってくれて……。"
"1009003-17-ウミカ" = "……じつは3日後に、湖でマリモのお祭りがありまして。#n百夜堂の営業のあと、お祭りの準備もしているんですよ。"
"1009003-18-ウミカ" = "それに授業もありますし、テストに向けて勉強もしないと……。"
"1009003-19" = "[s3] \"百夜堂とお祭りの準備で忙しいのにテスト勉強まで……。\"\n[s4] \"ウミカは頑張り屋さんだね……先生、泣けてくるよ。\""
"1009003-20-ウミカ" = "いえいえ……！#n勉強は学生の本分ですし、当たり前のことですから。"
"1009003-21-ウミカ" = "え、先生……？大げさですよ！？"
"1009003-22-ウミカ" = "ほ、本当に泣かないでください……！先生！"
"1009003-23" = "[ns] \"お祭りの準備は順調に進んでる？\""
"1009003-24-ウミカ" = "はい、順調です。"
"1009003-25-ウミカ" = "えへへ……とはいえ、まだまだやることはたくさんあって大変ですけど。"
"1009003-26-ウミカ" = "でも、この準備期間も含めて、お祭りですから！"
"1009003-27-ウミカ" = "え……？どうしてそんなにお祭りが好きなのか、って……？"
"1009003-28-ウミカ" = "ふふっ、たしかに不思議に思われるかもしれませんね。"
"1009003-29-ウミカ" = "……お祭りに参加していると、昔を思い出すんです。"
"1009003-30-ウミカ" = "幼いころ、私は……田舎で暮らしていたんです。"
"1009003-31-ウミカ" = "空気は澄んでいて、のどかな場所でしたけど……。#nすこし毎日が退屈に感じてしまうこともありました。"
"1009003-32-ウミカ" = "穏やかで、ゆったりしていても、時々は……。#n子供は何かしらエンターテイメントがほしくなるものですよね？"
"1009003-33" = "[s] \"大人だって楽しいことは大好きだよ！\""
"1009003-34-ウミカ" = "そ、そうなんですね……？"
"1009003-35-ウミカ" = "ともかく、田舎の子供にとっては、年に一度のお祭りが一番の楽しみだったんです。"
"1009003-36-ウミカ" = "地元のみんなが総出で、ひと月も前から準備にとりかかって。#nお祭りに使う竹や紙を用意して色を塗ったり、お神輿を作ったり……"
"1009003-37-ウミカ" = "気づいたら、誰よりも張り切ってお祭りを準備する子供になってました。#n今も、あの時の楽しさが忘れられなくて……。"
"1009003-38-ウミカ" = "百鬼夜行に来て、いろいろなことを学んで……。#n私のなかで変化したこともたくさんあります……。"
"1009003-39-ウミカ" = "でも、お祭りが一番好きだという気持ちはずっと変わりません。"
"1009003-40-ウミカ" = "それに、ここではキヴォトス各地のお祭り情報が耳に入ってきますし、#n気になったお祭りには足を運びやすいんですよ！"
"1009003-41-ウミカ" = "実際にお祭りを企画して、準備するのは大変ですし……。#n百夜堂で学ばなければならないことも、山ほどありますが……。"
"1009003-42-ウミカ" = "やっぱり「お祭り」と聞くと、子供のころみたいにわくわくしてしまうんです！"
"1009003-43-ウミカ" = "そのせいで空気が読めないとか、雰囲気を台なしにするとか……#nいろいろ言われてしまうこともありますが……。"
"1009003-44" = "[s] \"気にしなくていいと思うよ。\""
"1009003-45-ウミカ" = "そ、そうですか……？"
"1009003-46" = "[s] \"うん。誰にも迷惑はかけてないし。\""
"1009003-47-ウミカ" = "でも、私……自分でもわかってるんですよ。#nつい周りが見えなくなったり、考えなしに動いてしまったり……。"
"1009003-48" = "[s5] \"何かに没頭できるのはいいことだよ。\"\n[s6] \"私から見たら、羨ましいくらい。\""
"1009003-49-ウミカ" = "……そう、でしょうか？"
"1009003-50-ウミカ" = "先生に言われたら、なんだか自信が出てきました……！"
"1009003-51-ウミカ" = "えへへ、ありがとうございます～先生。#n話を聞いていただいて、すこし気持ちが楽になりました。"
"1009003-52-ウミカ" = "さて……休憩もできましたし、百夜堂のお仕事も張り切らないと！"
"1009003-53-ウミカ" = "……と言っても、先生以外にお客様はいないのですが――"
"1009003-54-百鬼夜行の生徒A" = "こんにちは～。#n本日のおすすめ、まだありますか？"
"1009003-55-ウミカ" = "お、お客様です！#n先生……ちょっと失礼しますね！"
"1009003-56-ウミカ" = "いらっしゃいませ！席までご案内します！"
"1009003-57" = "（百夜堂は再びお客さんで賑わいだした）"
"1009003-58" = "（忙しく働くウミカに手を振ってお会計を済ませると、シャーレに戻ってきた）"
