[translation]
"1301115-1" = "お姉ちゃんの思い出"
"1301115-2-モモイ" = "おっけー！チャージできたよ！"
"1301115-3" = "[s] \"よし！ダウンさせるね……今だ！\""
"1301115-4-モモイ" = "この角度なら――いける！"
"1301115-5-モモイ" = "やあああっ！！"
"1301115-6-モモイ" = "あ、あれっ！？"
"1301115-7" = "[ns1] \"だ、大丈夫……？\"\n[ns2] \"もしかして、ゲームしてると体も動いちゃうタイプ？\""
"1301115-8-モモイ" = "そう！#nゲームとシンクロするのも、ゲーマーの資質だからね――"
"1301115-9-モモイ" = "って、わぁっ！#nあっ、ちょっと待って――！"
"1301115-10-モモイ" = "ぐあああっ！"
"1301115-11-モモイ" = "間に合わなかった……。"
"1301115-12-モモイ" = "あ……うん、大丈夫だよ。#n雑に積んでたのが悪いわけだし……。"
"1301115-13" = "[s] \"気をつけてね……立てそう？\""
"1301115-14-モモイ" = "うん、ありがと……ってあれ？"
"1301115-15-モモイ" = "あっ！こんなところにあったんだ！"
"1301115-16-モモイ" = "これ？#nふっふっふっ……これはね……。"
"1301115-17-モモイ" = "私とミドリが、初めてお揃いにしたゲーム機なんだ。"
"1301115-18" = "[s] \"それじゃあ、二人にとって初めてのゲーム機なの？\""
"1301115-19-モモイ" = "ううん、私はそうじゃないよ。#nもうその時にはバリバリのゲーマーだったからね！"
"1301115-20-モモイ" = "でも、このときはセットで買ったんだよね。"
"1301115-21-モモイ" = "多分、ミドリにとってはこれが初めてのゲーム機じゃないかな。"
"1301115-22" = "[s3] \"大切なものなら……。\"\n[s4] \"もっと大事にしたほうがいいんじゃない？\""
"1301115-23-モモイ" = "いや、ちゃんと大切にしてたんだって！"
"1301115-24-モモイ" = "ほら！スタンドとケースも用意したんだよ！#nばっちりでしょ！？"
"1301115-25-モモイ" = "まあ、どこに置いたか分からなくなってたら、あんまり意味ないかもだけど……。"
"1301115-26-モモイ" = "大事にしようとはしてるんだよ！#n私なりに……。"
"1301115-27" = "[s] \"そんなに特別なものなの？\""
"1301115-28-モモイ" = "そうだね、やっぱり……。"
"1301115-29-モモイ" = "……うん。"
"1301115-30-モモイ" = "これはお姉ちゃんとしての証、だからかな！"
"1301115-31-モモイ" = "今でこそ、こうやって一緒にゲームを作ってるけど……#nもともと、私たちはそんなに仲良くなかったんだ。"
"1301115-32-モモイ" = "だから、どうやったら距離が縮まるかなって色々考えて……#n一緒にゲームすればいいんじゃないかって思いついたの。"
"1301115-33-モモイ" = "それで、私が買ってあげたんだ。"
"1301115-34-モモイ" = "お姉ちゃんからのプレゼントなら、雑には扱えないでしょ？"
"1301115-35-モモイ" = "ふっふっふっ……#nそして、私の「ミドリゲーマー化計画」は華麗なる成功を収めたのだった……。"
"1301115-36-モモイ" = "ミドリとの仲も良くなったし！文句なしだよね！"
"1301115-37-モモイ" = "……あれ？でも、本当に良かったのかな？#nミドリ、私に対して、言葉に遠慮が無い気がするけど……。"
"1301115-38" = "[s] \"ミドリとの対戦の勝率も……。\""
"1301115-39-モモイ" = "い、言わないで！"
"1301115-40-モモイ" = "なんか損してる気がしてきた！"
"1301115-41" = "[s] \"お姉ちゃんは、負けてあげるもの……かな。\""
"1301115-42-モモイ" = "そ、そうだよね？#n本当は私の方がゲーム上手い……と思うし！"
"1301115-43-モモイ" = "……あっ！！"
"1301115-44" = "[s] \"どうしたの？\""
"1301115-45-モモイ" = "画面見て――！"
"1301115-46-モモイ" = "モンスターが逃げてる！"
"1301115-47" = "[ns] \"討伐失敗！？\""
"1301115-48-モモイ" = "うわーん！あいつ探すの大変なのにー！"
"1301115-49" = "（そんなこんなで――）"
"1301115-50" = "（久しぶりに、モモイとたくさんゲームをして過ごした）"
