[translation]
"1403-1" = "GUNS N' PEPPERS（３）"
"1403-2" = "ミレニアム・廊下"
"1403-3-コトリ" = "……まだ気付いてないみたいですね。"
"1403-4-ヒビキ" = "……でも油断は禁物。万が一ネル先輩が引き金を引いたら、その瞬間に全部終わり。"
"1403-5-コトリ" = "それは心配しなくても大丈夫かと思います。ネル先輩は確かに短気ですが、そのせいでミレニアムの生徒は皆さん、日々先輩を刺激しないように気を付けてますし！"
"1403-6-コトリ" = "「わざわざ喧嘩を売りに行くようなよっぽどのおバカさん」でも現れない限り、ネル先輩もそう簡単に引き金に触れないかと。"
"1403-7-モモイ" = "あっ、見つけた！ネル先輩！"
"1403-8-モモイ" = "あん？なんだ、ゲーム開発部の双子の片割れじゃねぇか。#nあたしに何か用か？"
"1403-9-モモイ" = "これ見て！"
"1403-10-モモイ" = "この前、ネル先輩が校内に忍び込んだヘルメット団を鎮圧しようとして暴れた時に、飛んできた流れ弾に当たってゲーム機の中の基板が壊れたの！だから責任取って！"
"1403-11-ネル" = "……あぁ？ふざけてんのか？なんでそれがあたしのせいなんだよ？"
"1403-12-モモイ" = "あの時先輩が銃を乱射しなかったら、ゲーム機は壊れなかったじゃん！#nこれ高かったんだから弁償して！弁償ーー！！"
"1403-13-モモイ" = "てめぇ……いい加減にしろよ……！"
"1403-14" = "ちょーーっと待ったぁ！ここは私たちにお任せください！"
"1403-15-モモイ" = "あれ？なんでこんなところにエンジニア部が？"
"1403-16-ヒビキ" = "ちょっと待ってモモイ、そのゲーム機の状態を見せてくれる……？"
"1403-17-モモイ" = "ふむふむ、接続端子が折れただけの軽微な故障ですね。これぐらいの故障でしたら、私たちエンジニア部が持ってる部品で簡単に直せますよ！"
"1403-18-モモイ" = "本当！？じゃあそれでいいかな……。"
"1403-19-ネル" = "はんっ、ならあたしにもう用はねぇだろ？じゃあな。"
"1403-20-モモイ" = "あっ、ま、待ってくださいネル先輩！"
"1403-21-モモイ" = "これは戻ったらすぐに直すから、一度エンジニア部に行って預けておいてくれる？今はちょっと急ぎの用事があって……。"
"1403-22-モモイ" = "ヒビキ、早く追いかけましょう！ネル先輩がまた他のトラブルに巻き込まれる前に！"
"1403-23" = "……他のトラブル？エンジニア部、何してるんだろ？"
"1403-24" = "しかし、その後も危機は続いた……。"
"1403-25-アスナ" = "ねえ部長。ずっと気になってたんだけどさー、部長が着てるそのちっちゃいスカジャンってどこで売ってるの？子供服売り場？"
"1403-26-ネル" = "てっめぇ……言ってくれるじゃねえか！ぶっ飛ばすぞ！"
"1403-27-コトリ" = "待ってください！ネル先輩、落ち着いて！アスナ先輩も決して悪気があって言ったわけではないと思います！"
"1403-28-ヒビキ" = "……そうだね。アスナ先輩も、謝った方が良いと思う。"
"1403-29" = "んー？さっきの、そんなにショックだった？"
"1403-30-ネル" = "気分悪くさせちゃったらごめんねー、私はただそのスカジャン、カッコいいからどこに売ってるのかなーって。"
"1403-31-ネル" = "ちっ……てめぇはそういうやつだったな。エンジニア部の連中に免じて、今回は許してやらぁ。#nだが、今度子供服だのなんだの言いだしたら、その時は覚えとけよ！"
"1403-32-ミレニアムの生徒" = "あ、ネルー。この扉の鍵、銃で壊してくれない？うっかり鍵かけて外に出ちゃってさ。"
"1403-33-ネル" = "あぁ、それぐらい構わねえぜ。ぶっ放せばいいんだろ？それじゃあ派手に――"
"1403-34-ネル" = "ま、待ってください！扉を開けるなら私たちにお任せを！"
"1403-35-コトリ" = "エンジニア部の技術があれば、ドアノブを壊さなくても簡単に開けられる……。"
"1403-36-ミレニアムの生徒" = "わあっ、針金だけで鍵を開けるなんて映画みたい！すごい！"
"1403-37-ヒビキ" = "こういったことは私たちの専門ですので！扉が開かないからといって、銃を使わなくても大丈夫です！はい！"
"1403-38-ネル" = "……。"
"1403-39-ヒビキ" = "てめぇら……いったい何なんだ？"
"1403-40-コトリ" = "は、はい？わ、私たちはエンジニア部ですが！？"
"1403-41-ネル" = "んなこと知ってるに決まってんだろうがっ！"
"1403-42-ネル" = "あたしが聞いてんのは、なんでずっとあたしに付きまとって、その上、事あるごとに口出ししてくんのかってことだよ！"
"1403-43-コトリ" = "こ、困った人がいたら助けるのは、生徒としての当然の心がけですから！あ、あははは！"
"1403-44-ヒビキ" = "それに暴力は良くないこと……技術だけで解決できれば、何よりじゃない？"
"1403-45-ネル" = "まぁそれも正論だが……なんか怪しいんだよな。"
"1403-46-ネル" = "てめぇらまさか、あたしの銃に何かいたずらでもしたんじゃねぇだろうな……？"
"1403-47-ヘルメット団員A" = "ここにいたのか、[ruby=みかも]美甘[/ruby]ネル！"
"1403-48-ヘルメット団員B" = "前回やられてからというものの、ずっとお前を探してたんだ！"
"1403-49-ネル" = "あぁん？てめぇらか……まぁた凝りもせず現れやがって。"
"1403-50-ヘルメット団員B" = "ふふっ。あの時は突然の襲撃だったせいでやられっぱなしだったが、今回は万全の準備をしてきたからな！"
"1403-51-ヘルメット団員A" = "ヘルメットはもちろんのこと、全ての装備を砲弾にも耐えうる防弾性の素材に変えたのだ！もうお前のそのか弱いサブマシンガンごときでは、私たちのことは倒せまい！"
"1403-52-ヘルメット団員B" = "さあ、覚悟しろC&Cのリーダーめ！前回の借りを返してやる！"
"1403-53-ネル" = "はっ、そこそこ気合を入れて来たみたいじゃねぇか。"
"1403-54-ネル" = "いいぜ、相手をしてやる！"
"1403-55" = "ま、待ってくださいネル先輩！その銃は今――！"
"1403-56" = "タダダダダダダッ！"
"1403-57-ヘルメット団員B" = "ふはは！新しい防弾ヘルメットの強靭さを見せてや……ん？"
"1403-58-ヘルメット団員A&B" = "なっ、ぐあああっ！"
"1403-59-ヘルメット団員A" = "な、なんだこれは？刺激臭……チャバスコか！？"
"1403-60-ヘルメット団員B" = "うっ！隙間から、目にも鼻にも入って……#nげほ、げほっ！い、息ができない！助けてくれ！"
"1403-61-ヘルメット団員A" = "げほっ、うぇっ……！この、卑怯な奴め！爆薬だけでは飽き足りず、特殊弾まで使ってくるとは、やはり血も涙もないC&Cのリーダーというわけか！げほっ！"
"1403-62" = "……は？いや……あたしは何も……。"
"1403-63" = "今回は撤退だ！覚えておけよ！げほっ、げほっっ！！！"
"1403-64-コトリ" = "……い、いや～、本当に危ないところでした。防弾素材を持ち出したヘルメット団によって、危うくネル先輩の不敗神話が破られてしまうところでしたね。"
"1403-65-ヒビキ" = "……事前にチャバスコが噴射できるよう改造しておいて良かった。#nめでたし、めでたし。"
"1403-66-ネル" = "……おい。"
"1403-67-ネル" = "これは一体どういうことか、説明してもらおうか？エンジニア部？"
"1403-68-コトリ" = "その、それはですね……実験の過程における偶然の産物と言いますか……#n銃からチャバスコを噴射できたら何かに役立つんじゃないかと思いまして……。"
"1403-69-ヒビキ" = "……実際に役立ったから、良かったんじゃ？"
"1403-70-ネル" = "……遺言はそれだけか。"
"1403-71" = "タダダダダダダッ！"
"1403-72-コトリ" = "う、うわあっ！先輩！チャバスコを人に向けて噴射してはいけないんですよ！"
"1403-73-コトリ" = "げほっ！げほっ！目に入ると危険なので……！#n本当に危険なので！！"
"1403-74-ネル" = "てめぇらがっ、作ったんだろうがああぁぁぁぁっっ！！"
"1403-75" = "タダダダダダダダダダッ！"
"1403-76" = "GUNS N' PEPPERS"
