[translation]
"1010203-1" = "日焼け止め？"
"1010203-2" = "（ヒヨリがいる場所に急いで向かった）"
"1010203-3-ヒヨリ" = "うぅぅ……痛いです、痒いです。"
"1010203-4-ヒヨリ" = "あれっ、先生。ど、どうしてここに？"
"1010203-5-ヒヨリ" = "い、いてっ……！"
"1010203-6" = "[s1] \"ヒヨリ、大丈夫？\"\n[s2] \"ちょっと見せて。\""
"1010203-7-ヒヨリ" = "うぅ……見てください、先生。こんなに赤く……。"
"1010203-8-ヒヨリ" = "海水で洗い流そうとしても、肌が痛くて……！"
"1010203-9-ヒヨリ" = "うわぁぁああん！#n結局、夏を楽しめずに終わるんです！#nせっかく水着も手に入ったのに……。"
"1010203-10-ヒヨリ" = "私には、真っ暗な廃墟がお似合いなんです……。"
"1010203-11" = "[s] \"落ち着いて。まず、日陰に移動しよう。\""
"1010203-12-ヒヨリ" = "ぐすん……はい。"
"1010203-13-ヒヨリ" = "……え？#nどこからか、香ばしい匂いがする、って？"
"1010203-14-ヒヨリ" = "先生は鼻が良いんですね。"
"1010203-15" = "[s] \"これって……ごま油？\""
"1010203-16-ヒヨリ" = "は、はい。#n日焼け止めを買うお金がなくて……。"
"1010203-17-ヒヨリ" = "雑誌で見たんですけど、ビーチではオイルを塗るみたいなので……えへへ。"
"1010203-18-ヒヨリ" = "そ、そもそもごま油も残りが少なくて、お腹と胸にしか塗れていませんが……。"
"1010203-19-ヒヨリ" = "一応、塗ったので試しに日光浴をしてみたら……。"
"1010203-20" = "[s] \"ごま油じゃ、日焼け止めにはならないよ！？\""
"1010203-21-ヒヨリ" = "そ、そうだったんですね。#n……肌も焼けてヒリヒリしますし、もう私は海を楽しめません。#nやっぱり終わりです……。"
"1010203-22-ヒヨリ" = "もう暗い洞窟の中で、夏が終わるのを待つしかないんです……#nこれからは、一生コウモリと暮らす羽目になるんですよね……！"
"1010203-23-ヒヨリ" = "全部おしまいです！#nうわぁぁぁぁああん！"
"1010203-24" = "（泣いているヒヨリをなんとか宥めて、近くの海の家に入った）"
"1010203-25-ヒヨリ" = "氷で冷やすと少しマシになりました……。"
"1010203-26-ヒヨリ" = "赤くなった肌も完全に元通り……とは言えませんが。#nま、まだ少し痛いですけど……。"
"1010203-27-ヒヨリ" = "え、えへへ、先生。#nお腹の方もお願いして良いですか？"
"1010203-28-ヒヨリ" = "つ、冷たくて気持ち良いです……。"
"1010203-29" = "[s] \"次からは、ちゃんと日焼け止めクリームを塗ろうね？\""
"1010203-30-ヒヨリ" = "えへへ、はい。"
"1010203-31-ヒヨリ" = "でも、先生に手当までしてもらえて、これはこれで良かったのかもしれません。"
"1010203-32-ヘルメット団員B" = "ゴリゴリ君のアイスバー1個くれ！"
"1010203-33-ヘルメット団員B" = "私はコーンポタージュ味を！"
"1010203-34-ヘルメット団員A" = "はい、まいど！"
"1010203-35-ヒヨリ" = "……。"
"1010203-36-ヒヨリ" = "……アイス、美味しそうですね。"
"1010203-37-ヒヨリ" = "私には、ただ見ていることしかできませんが……。"
"1010203-38" = "[s] \"ちょっと待ってて、ヒヨリ。\""
"1010203-39-ヒヨリ" = "えっ、良いんですか……？"
"1010203-40-ヒヨリ" = "あ、ありがとうございます！"
"1010203-41-ヒヨリ" = "お、美味しいです……！"
"1010203-42" = "[s] \"あんまり無理はしないでね。\""
"1010203-43-ヒヨリ" = "は、はい……！"
"1010203-44-ヒヨリ" = "もう元気になったので、日に当たっても……。"
"1010203-45-ヒヨリ" = "あ、あれ……！？"
"1010203-46" = "[wa:700]― [log=히요리 수영복]いたたた……[wa:2930]痛いですぅぅ……[/log]"
"1010203-47" = "[wa:700]― [log=히요리 수영복]ひえっ！？[wa:1000]私のアイスバーが？[/log]"
"1010203-48" = "― [log=히요리 수영복]終わりです！[wa:1550]もう終わりです！[/log]"
"1010203-49" = "[wa:2350]― [log=히요리 수영복]一口しか食べてないのに[wa:1600]砂だらけになってしまうなんて……！[/log]"
"1010203-50" = "[wa:1600]― [log=히요리 수영복]やっぱり[wa:1500]私にはアイスバーさえも[wa:1700]許されないんですね……！[/log]"
"1010203-51" = "[wa:2500]― [log=히요리 수영복]完全に見放されました……！[/log]"
"1010203-52" = "― [log=히요리 수영복]私の人生は[wa:1900]どうしてこんなに[wa:900]苦難に満ちているのでしょうか？[/log]"
"1010203-53" = "[wa:2300]― [log=히요리 수영복]他の人は[wa:1000]夏を楽しんでいるというのに……。[/log]"
"1010203-54" = "[wa:570]― [log=히요리 수영복]どんなに頑張っても、[/log]"
"1010203-55" = "[wa:1950]― [log=히요리 수영복]私にとっては[wa:1600]届かない夢のようなものだなんて……。[/log]"
"1010203-56" = "[wa:80]― [log=히요리 수영복]……え？[wa:1450]もう一つ[wa:800]買ってくださるんですか？[/log]"
"1010203-57" = "[wa:1200]― [log=히요리 수영복]それって……[wa:3100]落としたアイスバーが無事だったら[/log]"
"1010203-58" = "[wa:1420]― [log=히요리 수영복]2倍食べられたってことですよね……？[/log]"
"1010203-59" = "― [log=히요리 수영복]うわぁん！[wa:2100]やっぱり終わりです！[/log]"
"1010203-60-ヒヨリ" = "……ぐすん。"
"1010203-61-ヒヨリ" = "ありがとうございます、先生。#nかき氷まで買ってくださって……。"
"1010203-62-ヒヨリ" = "えへへ……い、いただきます。"
"1010203-63" = "[s] \"少し元気になった？\""
"1010203-64-ヒヨリ" = "は、はい。"
"1010203-65-ヒヨリ" = "先生には、いつもお世話になりっぱなしで……#n嬉しいんですけど、どこか申し訳ない気持ちも……"
"1010203-66-ヒヨリ" = "ど、どうしたんですか、その目は。#nわ、私にだって自覚はあるんですよ……？"
"1010203-67-ヒヨリ" = "ですから、次は何かして差し上げます。"
"1010203-68-ヒヨリ" = "……ざ、雑誌でも拾ってくるとか。"
"1010203-69-ヒヨリ" = "先生はどんなものがお好きですか？#nやっぱり、エッチな雑誌が……。"
"1010203-70" = "[s3] \"いやいや、そういうのは大丈夫だから。\"\n[s4] \"気にしなくて良いんだよ。\""
"1010203-71-ヒヨリ" = "そ、そうですか……。"
"1010203-72-ヒヨリ" = "でも……何かをしてもらったら、お返しをするように教わりましたので……。"
"1010203-73-ヒヨリ" = "その、期待していてくださいね……えへへ。"
