[translation]
"1010202-1" = "当選確率"
"1010202-2" = "（先ほどのモモトークが気になり、ヒヨリのもとを訪れた）"
"1010202-3-ヒヨリ" = "え、えへへ……。"
"1010202-4-ヒヨリ" = "あっ、先生？"
"1010202-5-ヒヨリ" = "き、来てくれたんですね……！#nちょうど、伺おうと思っていたんですが……。"
"1010202-6" = "[s] \"ヒヨリは何をしてるの？\""
"1010202-7-ヒヨリ" = "あ、それがですね……。"
"1010202-8-ヒヨリ" = "えへへ。#n水着が欲しくて、これを書いているところなんです……。"
"1010202-9-ヒヨリ" = "雑誌の懸賞はがきなんですけど……#nエピソードが選ばれると、水着がもらえるみたいで。"
"1010202-10-ヒヨリ" = "こんな真夏に、廃墟で暮らしている私たちの事情を書いて送れば……。"
"1010202-11-ヒヨリ" = "担当の方も、きっと憐れんで水着をプレゼントしてくれるに違いありません。#nえへへ……！"
"1010202-12" = "[s1] \"水着を無料でもらえるかも、とは言ってたけど……。\"\n[s2] \"懸賞はがきだったとは……。\""
"1010202-13-ヒヨリ" = "今日中に投函すれば、海に行くまでに届くかもしれません！"
"1010202-14-ヒヨリ" = "それでシャーレを伺おうと思っていた理由は、#nプレゼントの宛先をシャーレにしても良いか聞くためで……。"
"1010202-15-ヒヨリ" = "ご存知の通り、私たちには住所なんてないですから……えへへ。"
"1010202-16" = "[s] \"もちろん、それくらい構わないけど……。\""
"1010202-17" = "[ns] ヒヨリが手に持っている雑誌を確認してみる。"
"1010202-18" = "（……2ヶ月前に発行された雑誌だった）"
"1010202-19-ヒヨリ" = "先生、どうかされたんですか？"
"1010202-20-ヒヨリ" = "急にそんな目を……#nや、やっぱり先生も、私のことを不憫だと思ってるんですね……！？"
"1010202-21-ヒヨリ" = "……私の人生なんて、この廃墟同然でしょうし。"
"1010202-22-ヒヨリ" = "あっ。#nむしろ今は、そのほうが……"
"1010202-23-ヒヨリ" = "不憫なほど当選確率も上がるはずですし……え、えへへ。"
"1010202-24" = "[s3] \"うーん……。\"\n[s4] （応募期間が過ぎていることは、言わないでおこう……）"
"1010202-25-ヒヨリ" = "えへへ、書き終わりました。"
"1010202-26-ヒヨリ" = "先生、帰りにこれをポストに投函してもらっても良いですか……？"
"1010202-27-ヒヨリ" = "……水着、楽しみです！"
"1010202-28" = "（ヒヨリが送ろうとした懸賞は期限が過ぎていたため、シャーレに持ち帰った）"
"1010202-29" = "[ns] \"ちょっと読ませてもらうね……。\""
"1010202-30" = "はじめまして、私は毎日苦しみながら生きています。"
"1010202-31" = "楽しいことも、嬉しいこともない石ころみたいな人生ですが、#n一度くらい海に行ってみたいんです。"
"1010202-32" = "私の小さな夢が叶うように、どうか助けてください。"
"1010202-33" = "希望する当選品：ゴールデン・ラグジュアリーVIPハイエンド水着"
"1010202-34" = "[ns] \"……う～ん。\""
"1010202-35" = "（その後、ショッピングモールで水着を購入した）"
"1010202-36-ヒヨリ" = "あっ、先生。それはもしかして……！"
"1010202-37-ヒヨリ" = "アレですよね？#nアレが届いたんですよね！？"
"1010202-38" = "[s5] \"そ、そうだよ。\"\n[s6] \"懸賞、当たったみたいだね。\""
"1010202-39-ヒヨリ" = "わあああぁぁぁっ！"
"1010202-40-ヒヨリ" = "待てば海路の日和ありとは、このことですね……！#nついに、私の人生にも幸せが……！"
"1010202-41-ヒヨリ" = "……あれ、「ゴールデン・ラグジュアリーVIPハイエンド水着」ではないような。"
"1010202-42-ヒヨリ" = "まあ、細かいことは良いでしょう……えへへ。"
"1010202-43-ヒヨリ" = "さっそく着てみますね……！"
"1010202-44-ヒヨリ" = "……えへへ、どうですか？"
"1010202-45" = "[s] \"よく似合ってるよ。\""
"1010202-46-ヒヨリ" = "嬉しい、です……。"
"1010202-47-ヒヨリ" = "今までの苦労が、少しだけ報われたような……。"
"1010202-48-ヒヨリ" = "そ、そうでした。"
"1010202-49-ヒヨリ" = "こうしている場合じゃありません！"
"1010202-50" = "[s] \"……これは？\""
"1010202-51-ヒヨリ" = "今まで集めてきた雑誌の懸賞はがきです！"
"1010202-52-ヒヨリ" = "これはサングラスがもらえて、こっちは浮き輪が！#nほかにもかき氷機がもらえるものまで……！"
"1010202-53-ヒヨリ" = "えへへ、全部当たったらどうしましょう……。#n最高に贅沢な夏が過ごせるかもしれません……！"
"1010202-54-ヒヨリ" = "あ、大丈夫ですよ。#n先生の分のはがきもありますから！"
"1010202-55-ヒヨリ" = "えへへ。海、楽しみです……！"
