[translation]
"2005806-1" = "エリカの相談"
"2005806-2-エリカ" = "……。"
"2005806-3" = "[ns] \"こんにちは、エリカ。\""
"2005806-4-エリカ" = "来てくれてありがと、先生……。"
"2005806-5-エリカ" = "こんなすぐに会えると思わなかった……時間大丈夫？"
"2005806-6-エリカ" = "「エリカが相談なんて珍しいと思って」……？"
"2005806-7-エリカ" = "……まあ、そうかも。#nあんまり悩み相談とかしないし。"
"2005806-8-エリカ" = "先生は……頼りになるっていうか、頼っても大丈夫な人だと思ってて。"
"2005806-9-エリカ" = "……なにその顔。嬉しそう。"
"2005806-10-エリカ" = "ま、まあ！とにかくそういうことだから。"
"2005806-11-エリカ" = "待ってる間に色々考えたんだけど……。"
"2005806-12-エリカ" = "ちょっとまだうまくまとまってないから……言葉が変かも。"
"2005806-13" = "[s] \"いいよ、ゆっくりで。\""
"2005806-14-エリカ" = "うん……。"
"2005806-15-エリカ" = "ん～～っ……。"
"2005806-16-エリカ" = "……その、前からなんとなく思ってたんだけど。"
"2005806-17-エリカ" = "私、みんなと遊ぶのが好きなんだけどさ。"
"2005806-18-エリカ" = "一緒におしゃべりしたりカラオケ行ったり、ショッピングに行くのも好き。"
"2005806-19-エリカ" = "でもね……なんか。"
"2005806-20-エリカ" = "たまに……さ。"
"2005806-21-エリカ" = "会話が……途切れちゃうんだよね。"
"2005806-22-エリカ" = "あ、誤解しないでね。友達が悪いとかそういうのじゃなくて。#n私の問題っていうか。"
"2005806-23-エリカ" = "友達といること自体は全然嫌じゃないの、本当に。#n一緒にいると楽しいし。"
"2005806-24-エリカ" = "でもなんというか……。"
"2005806-25-エリカ" = "例えば。みんなでおしゃべりをしている時、誰かが面白いことを言ったとするじゃん？"
"2005806-26-エリカ" = "その時、「普段の私だったらこういうこと言っただろうなぁ」と頭では思うんだけど……。"
"2005806-27-エリカ" = "口から出てこなかったりするんだよね。"
"2005806-28-エリカ" = "どういえばいいのかちょっと分からないんだけど。#n言葉を口にする気力がない？って感じ。"
"2005806-29-エリカ" = "いや本当に気力がゼロってわけではないんだけど……。"
"2005806-30" = "[ns] \"それ、たぶん……。\""
"2005806-31" = "[ns] \"疲れてるんじゃない？\""
"2005806-32-エリカ" = "疲れてるのかな……？"
"2005806-33" = "[s1] \"エネルギーの量は決まってるからね。\"\n[s2] \"それを使い切ったから、疲れたんじゃないかな。\""
"2005806-34-エリカ" = "使い切ることって、あるのかな……？#nあんまり無理したつもりはないんだけどね。"
"2005806-35-エリカ" = "「遊ぶのにも体力がいる」……？"
"2005806-36-エリカ" = "「誰かに会うことにもエネルギーが必要」……？"
"2005806-37" = "[s3] \"そういう時は、一人の時間を持ってみるのもいいかもね。\"\n[s4] \"「充電期間」みたいな。\""
"2005806-38-エリカ" = "充電って……私そんなに、疲れてるのかな……？"
"2005806-39-エリカ" = "別にそんな時間、必要だなんて、考えたことなかったけど……。"
"2005806-40-エリカ" = "みんなに会うと楽しいし、約束がある日は充実した日だったなーって思うんだけど。"
"2005806-41-エリカ" = "……。"
"2005806-42-エリカ" = "あー……？#nもしかして、そういうこと……？"
"2005806-43-エリカ" = "うわぁー……そっか。"
"2005806-44-エリカ" = "いま、ちょっと衝撃だった。"
"2005806-45-エリカ" = "そういうことなのかも……。"
"2005806-46-エリカ" = "私って……一人の時間が必要なタイプだったんだ……。"
"2005806-47" = "[ns] \"たぶん、エリカは一人の時間も好きなんだと思うよ。\""
"2005806-48-エリカ" = "そ、そうなのかな？"
"2005806-49" = "[s] \"一人でいる時によく会うでしょ？\""
"2005806-50-エリカ" = "あー……たしかに、そうだね。"
"2005806-51" = "[s5] \"会った時のエリカは、別に寂しそうじゃなかったし。\"\n[s6] \"結構楽しそうに見えたというか。\""
"2005806-52-エリカ" = "そうだね……。"
"2005806-53-エリカ" = "一人でいる時にしかできないことも多いからね。"
"2005806-54-エリカ" = "だからかな……？#n一人で行く場所もあるんだよね。"
"2005806-55" = "[s] \"エリカだけの秘密基地みたいな？\""
"2005806-56-エリカ" = "秘密基地……。"
"2005806-57" = "[s] \"人には自分だけの秘密基地が必要だから。\""
"2005806-58-エリカ" = "そうかも……。"
"2005806-59-エリカ" = "そこに行くと気が楽になったんだけど……#nなんかようやく繋がった感じがするかも。"
"2005806-60-エリカ" = "私今までずっと、自分は社交的な人間だと思ってた……。"
"2005806-61-エリカ" = "違ったんだなぁ……なんか、ちょっとショック……。"
"2005806-62" = "[s7] \"社交的とか、そうじゃないとか。\"\n[s8] \"あんまり関係ないんじゃないかな。ハッキリ分けられるものじゃないし。\""
"2005806-63-エリカ" = "……そうだね。一面しかないわけじゃない、か。"
"2005806-64-エリカ" = "どんな角度で見ても自分は自分……。"
"2005806-65-エリカ" = "友達と遊ぶのが好きな私も私。一人の時間が好きな私も、私。"
"2005806-66" = "[ns9] \"関係を維持するのも大事だけど、\"\n[ns10] \"無理して他人に合わせて疲れてしまうのは違うからね。\"\n[ns11] \"きっとエリカの友達だって、無理してほしいわけじゃないと思うよ。\""
"2005806-67" = "[ns] \"大事なのは、エリカらしくすることじゃないかな？\""
"2005806-68-エリカ" = "今のちょっと先生っぽかった。たまにいいこと言うよね。"
"2005806-69" = "[s] \"大人ですからね！\""
"2005806-70-エリカ" = "相談してよかったかも。#nあースッキリした！"
"2005806-71-エリカ" = "私、ちょっとは自分に詳しくなれた気がする。"
"2005806-72-エリカ" = "自分で思っていた自分と違ってビックリしたけど……うん。#nこれも悪くない気がする。"
"2005806-73" = "[s12] \"また何か悩みがあったら言ってね。\"\n[s13] \"いつでも相談に乗るから！利用してね。\""
"2005806-74-エリカ" = "利用っていい方はちょっと違うかも。#n私、今まで一度もそんな風に思ったことないよ？"
"2005806-75-エリカ" = "いや、先生の言ってる意味は、分かるけどさ……。"
"2005806-76-エリカ" = "そういう風に言われたら、傷つく生徒もいると思う。"
"2005806-77" = "[s] \"あっ、ごめん。言い方が悪かったね。\""
"2005806-78-エリカ" = "まあ、次も相談に乗ってくれるということで。"
"2005806-79-エリカ" = "約束ね？"
"2005806-80" = "[s] \"うん、約束。\""
"2005806-81-エリカ" = "はいっ、指切った。"
"2005806-82-エリカ" = "……。"
"2005806-83-エリカ" = "やっぱ、先生の手あったかいね。"
"2005806-84" = "[s] \"エリカの手もやっぱり柔らかいよ。\""
"2005806-85-エリカ" = "あははっ、また言ってる。"
"2005806-86" = "（エリカの相談を聞いたあとも、しばらく雑談を楽しんだ）"
