[translation]
"1101-1" = "美食研究会の日常（１）"
"1101-2" = "ゲヘナ・郊外某所"
"1101-3-ジュンコ" = "はあ、はあ……#nもう追ってこないよね？"
"1101-4-アカリ" = "大丈夫そうですね。いくらしぶとい風紀委員長でも、#nこんなに遠くまでは追ってこられないハズです★"
"1101-5-ハルナ" = "ふぅ……あのような美味しくない学生食堂を#nひとつ吹き飛ばしたくらいでこの騒ぎとは、#nゲヘナの風紀委員会はよっぽど暇なようですわね。"
"1101-6-ジュンコ" = "いや……風紀委員って、そもそもそういうのが仕事だから……。"
"1101-7-ハルナ" = "ジュンコさん、例えばですよ？誰も使ってない流し台で水が流しっぱなしになっていたら、どんなお気持ちになりますか？"
"1101-8-ジュンコ" = "えっと……蛇口を締めなきゃって思うかな？"
"1101-9-ハルナ" = "はい、その通りです。#n私は不味いものを出すお店を見ると、そんな衝動に駆られるのですわ。"
"1101-10-ジュンコ" = "……もう説明しなくていいわよ。#nどうせわかんないし。"
"1101-11-ジュンコ" = "ところでさっきからイズミが見当たらないんだけど？#nついてきてたんじゃないの？"
"1101-12-アカリ" = "イズミさんは、だいぶ前に脱落されました。#nきっと今頃、ヒナさんに捕まっているでしょうね。"
"1101-13-ジュンコ" = "ええっ、うそっ！？そんな大事なこと、何で今になって言うの！？"
"1101-14-アカリ" = "言う必要がなかったからですよ。#nイズミさんは、脱落するときに私たちにあることを言い残していきました。心のこもった、熱い魂の叫びを。"
"1101-15-ジュンコ" = "魂の叫び？#nま、まさか……！私たちのために……。"
"1101-16-ハルナ" = "……そうでしたか。彼女の犠牲は忘れません。#nイズミさんは何と言い残されたのですか？"
"1101-17-イズミ" = "ね、ねえ！待って！！#nちょっと、血も涙もないの！？置いていかないでー！"
"1101-18-イズミ" = "ふあっ！？（ズルッ）"
"1101-19" = "（ドサッッッ！！！）"
"1101-20-イズミ" = "置いていかないでってば！うわーん！#n覚えてなさいよっ！死んでも仕返ししてやるんだからっっ！！"
"1101-21-アカリ" = "……だそうです。"
"1101-22-ジュンコ" = "……。"
"1101-23-ハルナ" = "……。"
"1101-24-アカリ" = "うふふっ☆"
"1101-25-ジュンコ" = "くんくん……ん？なんか美味しそうな匂いがする。"
"1101-26-ハルナ" = "こんな公園で、ですか？"
"1101-27-ジュンコ" = "すっごく独特な匂いが……くんくん、こっちよ！"
"1101-28" = "（スタタタッ）"
"1101-29" = "（ゴソゴソ）"
"1101-30-ジュンコ" = "見つけた！このキノコからの匂いよ！"
"1101-31-アカリ" = "あら、これは……。"
"1101-32-ハルナ" = "トリュフ……！これはトリュフですわ！"
"1101-33-ジュンコ" = "トリュフ……？"
"1101-34-ハルナ" = "黒いダイヤとも呼ばれる、とても貴重なキノコなのです……！"
"1101-35-ハルナ" = "希少価値は、幻のマグロと呼ばれるゴールドマグロより上ですわよ！"
"1101-36-ハルナ" = "ひええっ！？そんなに！？"
"1101-37-ハルナ" = "特に、この濃厚かつ独特な香りは、採りたての時しか嗅ぐことができません。"
"1101-38-ハルナ" = "この香りを楽しめただけでも幸運なことですのよ。"
"1101-39-アカリ" = "私も聞いたことがあります。空腹のメス豚の嗅覚にしか見つけ出せない超レアな食材だと！"
"1101-40-アカリ" = "さすがジュンコさん、素晴らしい才能をお持ちですね。"
"1101-41-ジュンコ" = "誉め言葉にかこつけて今微妙な単語をブッ込んだよね。死にたいの？#nトリュフの代わりにあんたを埋めてやるわよ？"
"1101-42-ハルナ" = "こうしている場合ではありませんわ。#nトリュフは採取してから5分以内の下処理が命。#nこの鮮度を維持するには……。"
"1101-43-ハルナ" = "清潔な布が必要です。"
"1101-44-ジュンコ" = "いやいや……こんな土だらけの道の中を走ってきたんだよ、清潔な布なんてあるわけないでしょ。#nみんな泥まみれだし……。"
"1101-45-アカリ" = "でしたら、これはどうでしょう？"
"1101-46" = "ちょっと！！それ下着じゃん！！！"
"1101-47-アカリ" = "まだ開封してない新品ですよ？それに高級シルク100％なので、#n気分的には微妙かもしれませんが、本質的には清潔なハンカチと変わりません。"
"1101-48-ジュンコ" = "そりゃまあ、そうだけど……。#nでも会長、これでいいの？"
"1101-49-ハルナ" = "問題ありませんわ。いえ、むしろ良かったとも言えます。#nこんな時にアカリさんの潔癖症が役に立つとは。"
"1101-50-ハルナ" = "（スッ、スッ……）"
"1101-51" = "さあ、これで良いでしょう。#nあとは戻って、このトリュフを調理するだけですわ……！！"
"1101-52-ハルナ" = "……。"
"1101-53-ハルナ" = "いえ、その前に……囚われたイズミさんから救い出さなきゃいけませんね。#nこのような貴重な食材を味わうのに、研究会員が一人でも欠けてはなりませんもの。"
"1101-54-ハルナ" = "さすが会長！そうよ、このまま戻って風紀委員の連中をぶっ飛ばして、イズミも救い出さないと！！"
"1101-55-ハルナ" = "ラブ＆バイオレンス☆#n女の子同士の友情ですねっ！"
"1101-56-ヒナ" = "誰が誰をぶっ飛ばすって？"
"1101-57-ジュンコ" = "ひ、ひいっ！！？？風紀委員会！いつの間に！？"
"1101-58" = "（ザザッ……）"
"1101-59-ハルナ" = "あら……囲まれてしまいましたね。"
"1101-60-ヒナ" = "はあ、逃げるのもいい加減にして、面倒だから。みんな、始末――"
"1101-61" = "（ビクッ！）"
"1101-62-ヒナ" = "……いや、面倒なことになるから、やっぱり虫の息程度でいい。"
"1101-63-チナツ" = "（コクリ）"
"1101-64-チナツ" = "皆さん、無駄な抵抗はしないでください。"
"1101-65" = "（タタタタタタタタンッ！！）"
"1101-66" = "（この後めちゃくちゃ逮捕された）"
