[translation]
"1104-1" = "給食部襲撃事件"
"1104-2-イズミ" = "今日の給食もまずいんだけど！っていうか目玉焼きって聞いてたのに、目玉焼きはどこ！？"
"1104-3-ハルナ" = "これではないでしょうか、ゆで卵ですけれど。献立表にはたしかに「目玉焼き」と書かれていた気がしますが……。"
"1104-4-ジュンコ" = "うるさい！良いから食べなさい！ゆで卵だって美味しいでしょ！"
"1104-5-アカリ" = "そうですよ、食べないなら私にくれませんか？私、ゆで卵好きなので。"
"1104-6-ハルナ" = "ゆで卵に罪はありませんが、これはまた別の問題ですね。"
"1104-7-ハルナ" = "献立表には間違いなく目玉焼きと書いてありますのに、出てきたのはゆで卵。"
"1104-8-ハルナ" = "食べ物に対する礼儀がなっていません。"
"1104-9-ハルナ" = "さあ、給食部のところに行くとしましょう！"
"1104-10" = "（給食部・調理室）"
"1104-11-フウカ" = "……分かってる、分かってるから。でも、目玉焼き4000枚を私一人で2時間以内に作るのは無理。ジュリも今日お休みだし……。"
"1104-12-フウカ" = "そもそも油も無いし、フライパンも1個しか無いし……。"
"1104-13-ハルナ" = "はい、きっとそういうご事情だとは思っておりました。"
"1104-14-ハルナ" = "仕方ありませんので、私たちが手伝わせていただきます。今からでも目玉焼きを作りましょう。"
"1104-15-ハルナ" = "油も持参いたしました。"
"1104-16-フウカ" = "……え？"
"1104-17-アカリ" = "優しい美食研究会が、困っている給食部を助ける美しい光景……。"
"1104-18-アカリ" = "これぞ友情ですね☆"
"1104-19-ジュンコ" = "はあ、仕方ないなあもう。こういう展開になると思ってたけど。"
"1104-20-ジュンコ" = "じゃ、久しぶりに腕を振るっちゃおうかな。"
"1104-21-フウカ" = "え、ま、待って！？勝手に触ると……！"
"1104-22-イズミ" = "わー！この卵、全部食べてもいいの？"
"1104-23-ジュンコ" = "イズミ待った！まず作らないと！食べるのはその後！"
"1104-24-イズミ" = "大丈夫、卵かけごはん大好きだから！"
"1104-25-イズミ" = "ここからちょっとだけ貰ってー……"
"1104-26-イズミ" = "あ、あれ？"
"1104-27" = "（ガシャーン！！）"
"1104-28-ジュンコ" = "うわああ！卵もったいない！！"
"1104-29-ハルナ" = "ジュンコさん足元！そこに油が……！！"
"1104-30-ジュンコ" = "えっ？うわぁっ！？足元がツルツルして……っ！？"
"1104-31-ジュンコ" = "た、助けてっ！？"
"1104-32-ジュンコ" = "え、ええ？きゃ、キャッチ！"
"1104-33-アカリ" = "あれっ？止まりませんね？"
"1104-34-アカリ" = "ハルナさん、危ないです！避けてください！！"
"1104-35-ハルナ" = "………っ！！！"
"1104-36" = "（グシャッ！）"
"1104-37-アカリ" = "ああ、卵で全身ベタベタに……！"
"1104-38-ジュンコ" = "ちょっ、食器棚傾いてない！？避けて！なんか大きな袋が…！！"
"1104-39" = "（バサバサッ！モクモクモク……）"
"1104-40" = "（けほっ、けほっ！）"
"1104-41-イズミ" = "うわっ！何これ、卵に小麦粉？私たち下ごしらえ状態？"
"1104-42-ジュンコ" = "けほっ、けほっ！動かないでイズミ！ジタバタするとさらに絡まる！"
"1104-43-ハルナ" = "このままですと美食研究会が丸ごと、大きなたこ焼きになってしまいますわね……。"
"1104-44-アカリ" = "たこ焼きの材料ですか……まあ、それはそれで……。"
"1104-45-イズミ" = "たこ焼きは嫌！たこ焼きそのものは好きだけど、なるのは嫌ー！"
"1104-46" = "（ガシャーン！！）"
"1104-47" = "（ガタゴトガシャン！ドサッ！）"
"1104-48" = "（ドーーーーンッッ！）"
"1104-49-フウカ" = "………………。"
"1104-50" = "給食部襲撃事件"
