[translation]
"2001102-1" = "巫女さんのお勉強"
"2001102-2" = "（セリカとの約束の場所に向かうと……）"
"2001102-3-セリカ" = "あっ、先生！こっちこっち。"
"2001102-4-セリカ" = "えっと、とにかく来てくれてありがとう、先生。"
"2001102-5-セリカ" = "先生、最近は今まで以上にシャーレのことで忙しいって聞いたのに……。"
"2001102-6" = "[s1] \"セリカに呼ばれたら、いつでもすぐ来るよ。\"\n[s2] \"セリカに振り回されるの、好きだから！\""
"2001102-7-セリカ" = "そう、なの……？"
"2001102-8" = "[s3] \"もちろん。\""
"2001102-9-セリカ" = "えっ……ちょ、ちょっと待って！？それってもしかして、と、特別、ってこと……！？"
"2001102-10-セリカ" = "そ、そんなこと急に言われても困るっていうか、え、えっ……！？"
"2001102-11" = "[s4] \"大事な生徒だからね。\""
"2001102-12-セリカ" = "…………え？"
"2001102-13-セリカ" = "……それって、言葉通りの意味？"
"2001102-14-セリカ" = "うっ、ううっ……！"
"2001102-15-セリカ" = "ああもう、紛らわしいこと言わないでよ！"
"2001102-16-セリカ" = "全くもう、本当に……！"
"2001102-17-セリカ" = "ちょ、ちょっと待ったぁ！私が先生をいつ振り回……"
"2001102-18-セリカ" = "……いや、それなりにあったかもしれないけど、うん……。"
"2001102-19-セリカ" = "と、とにかくそれはごめん！でも今はその……！"
"2001102-20-セリカ" = "わ、私も反省、してるし……。"
"2001102-21" = "[s5] \"ごめん、冗談。呼ばれたらいつでも来るよ。\""
"2001102-22-セリカ" = "……はぁ？"
"2001102-23-セリカ" = "って、じゃあ今の私の反省は何だったのさ！？"
"2001102-24-セリカ" = "少しでも申し訳ないと思った私がバカだった……！もうっ！"
"2001102-25-セリカ" = "ああもう、始まる前から疲れた……。"
"2001102-26" = "[s] \"えっと、ごめんね？\""
"2001102-27-セリカ" = "はあ、もう良いわよ……先生は相変わらず先生だって分かったし。"
"2001102-28-セリカ" = "それに、先生が私の相談に乗るために、こうやって来てくれたのも事実だし？"
"2001102-29-セリカ" = "そのことは本当にありがたいと思ってるから……。"
"2001102-30" = "[s] \"セリカはやっぱり優しいね！\""
"2001102-31-セリカ" = "ああもう、うるさい！話が進まないから黙って！"
"2001102-32-セリカ" = "とりあえず本題！"
"2001102-33-セリカ" = "モモトークでも言ったけど、巫女さんのバイトをしようと思って。"
"2001102-34-セリカ" = "やっぱり普通のバイトとはちょっと違う感じがするでしょ？"
"2001102-35-セリカ" = "だから少しでも知ってるなら、先生にアドバイスとか貰いたいなって思ったんだけど……。"
"2001102-36-セリカ" = "あっ、でもその前にこれ！とりあえず聞くより先に、私なりに調べてみたの。"
"2001102-37-セリカ" = "まずはね、どうやら巫女さんの起源っていうのは――"
"2001102-38" = "[s6] \"そこから！？\"\n[s7] \"セリカ、時々やることが極端だよね……。\""
"2001102-39-セリカ" = "え、ダメ……？"
"2001102-40-セリカ" = "え、ダメ……？"
"2001102-41-セリカ" = "あ、もしかしてまず、このバイトを選んだ理由を聞きたいってこと？"
"2001102-42-セリカ" = "まあそんなに大した理由じゃないんだけど。"
"2001102-43-セリカ" = "実は今度のその巫女さんのバイトね、「完璧な巫女さんであればあるほど時給が上がる」っていうシステムなんだって！"
"2001102-44-セリカ" = "そうと聞いたら黙ってられないでしょ！？"
"2001102-45" = "[s] \"セリカらしい理由だね……。\""
"2001102-46-セリカ" = "だからとにかく、巫女さんについて詳しくなろうと思って。"
"2001102-47-セリカ" = "より高い時給のために、より完璧な巫女にならないと！だから教えて、先生！"
"2001102-48" = "（セリカの目は凄まじい熱意で輝いていた……）"
"2001102-49" = "[s] \"巫女さんか……まずは、巫女さんといえば――\""
"2001102-50" = "（近くのお店に行って、掃除道具を借りてきた）"
"2001102-51-セリカ" = "……箒？"
"2001102-52-セリカ" = "何で急に……？巫女さんと何か関係あるの？"
"2001102-53" = "[s8] \"巫女さんと言えば箒だよ！\"\n[s9] \"箒といえば、巫女さんか魔女かの二択だよ！\""
"2001102-54-セリカ" = "そ、そうなの……？まあ、先生が言うならそうなんだろうけど……。"
"2001102-55-セリカ" = "そ、そうなの……？まあ、先生が言うならそうなんだろうけど……。"
"2001102-56-セリカ" = "で、これを使って何をしたら良いわけ？"
"2001102-57" = "[s] \"それはもちろん、掃除を！\""
"2001102-58-セリカ" = "……あ、そのまんまなんだ。っていうか、本当にそれだけで良いの？"
"2001102-59-セリカ" = "うーん、まあ考えてても仕方ないし……"
"2001102-60-セリカ" = "うん、とりあえずやってみよっか！"
"2001102-61-セリカ" = "じゃあこっちの方から……"
"2001102-62-セリカ" = "んしょ、んしょ……！"
"2001102-63-セリカ" = "落ち葉とゴミを、かき集めて、っと……。"
"2001102-64" = "[s] \"うん、良い感じ！\""
"2001102-65-セリカ" = "そ、そう？それなら良かったけど……。"
"2001102-66-セリカ" = "あんまり巫女さんへの理解は深まってないような……？"
"2001102-67" = "（セリカの活躍で、公園がかなり綺麗になった）"
"2001102-68-セリカ" = "ふう、まあこんなもんかな？じゃあ先生、次は？"
"2001102-69" = "[s] \"次は……[ruby=ごへい]御幣[/ruby]！\""
"2001102-70-セリカ" = "ごへい……？"
"2001102-71-セリカ" = "え、えっ？先生？"
"2001102-72-セリカ" = "この、棒の先に紙が何枚も付いてるやつ……これが御幣なんだ？うん、見たことはあるかも。名前は知らなかったけど。"
"2001102-73-セリカ" = "で、これでどうしたら良いの？"
"2001102-74-セリカ" = "……振りながら舞ったり、願いを込めたりする？どういうこと……？"
"2001102-75" = "[s] \"とにかくやってみよう！いや、やってください！\""
"2001102-76-セリカ" = "そ、そう言われても……うーんと……。"
"2001102-77-セリカ" = "こ、"
"2001102-78-セリカ" = "こんな感じ……？"
"2001102-79-セリカ" = "うーん、やっぱりよく分かんない……今ので良いの？"
"2001102-80" = "[s] \"バッチリ！じゃあ次は……\""
"2001102-81" = "（その後もセリカと一緒に色んなことを話しながら、「巫女っぽいこと」を次々とやってもらった）"
"2001102-82-セリカ" = "「スペルカード」……？え、何それ、巫女さんと関係あるの？"
"2001102-83-セリカ" = "バラバラになった玉の欠片を集める……？え、弓矢？どういうこと？"
"2001102-84-セリカ" = "……これ、甘酒？え、そのまま飲んじゃダメなの？どうして？"
"2001102-85" = "（そうして、約3時間にわたる熱い語りを経て……）"
"2001102-86" = "[s] \"……こんなところかな？\""
"2001102-87-セリカ" = "つ、疲れた……普通のバイトより疲れた……。"
"2001102-88-セリカ" = "巫女さんとしての心構え……。"
"2001102-89-セリカ" = "それが、こんなに大変なことだったなんて……。"
"2001102-90-セリカ" = "でも、これでもしかして巫女さんのバイトはバッチリよね！？"
"2001102-91-セリカ" = "全部を習得できたわけじゃないけど、これくらいやれば……！"
"2001102-92" = "[s] \"どうだろう……実は、その……\""
"2001102-93" = "（セリカに素直に白状した）"
"2001102-94-セリカ" = "……え、全部ゲームとかアニメの知識？"
"2001102-95" = "[s] \"だからあんまり気にしないで。そういうの好きな人はいるかもだけど。\""
"2001102-96-セリカ" = "……。"
"2001102-97" = "[s] \"えっと……セリカさん？\""
"2001102-98-セリカ" = "……先生？それってつまり……"
"2001102-99-セリカ" = "今までの時間全部、からかってただけってこと！？ねぇっ！？"
"2001102-100-セリカ" = "ううっ、信じてたのに！口に入れて噛む回数とか覚えたのに！"
"2001102-101" = "[s] \"流石セリカ、真面目だね……。\""
"2001102-102-セリカ" = "ああもうっ！！バカ！先生のバカ！"
"2001102-103-セリカ" = "ほんっとにもう………。"
"2001102-104-セリカ" = "何だったのよもう、アニメの知識じゃ無理じゃん……。"
"2001102-105-セリカ" = "偏った知識ばっかり増えた……。"
"2001102-106" = "[s] \"ごめん、少しでも役に立つかなって……。\""
"2001102-107-セリカ" = "えぇ……その言い方はズルいじゃん……。"
"2001102-108-セリカ" = "はあ……。"
"2001102-109-セリカ" = "これじゃ相談って言うか、ふたりっきりで今日一日遊んでただけだし……。"
"2001102-110-セリカ" = "……ふたりっきり、か。"
"2001102-111-セリカ" = "はっ！？"
"2001102-112-セリカ" = "い、いや今のはそういう意味じゃなくて、デートとか言いたかったわけじゃないから！？"
"2001102-113-セリカ" = "誤解しないでよねっ！？"
"2001102-114" = "[s] \"うん、大丈夫。\""
"2001102-115-セリカ" = "……。"
"2001102-116-セリカ" = "それはそれでなんか違くない！？そこは誤解してくれても良いところでしょ！？"
"2001102-117-セリカ" = "ああもうっ、分からず屋！"
"2001102-118" = "（その後背中をぽかぽかと叩かれながら、セリカとしばらく巫女さんの話をした）"
