[translation]
"10043010-1" = "第1話;「絶対」なんて言わないで"
"10043010-2-レイ" = "まさか、ブレーブスの控え室に招待されるなんて……。"
"10043010-3-スミレ" = "……ここは関係者以外、立ち入り禁止のはずでは？"
"10043010-4" = "[s] \"なんで呼ばれたんだろう……。\""
"10043010-5-？？？" = "お越しいただきありがとうございます。"
"10043010-6" = "[ns] \"どちら様ですか？\""
"10043010-7-監督" = "申し遅れました。私はコーギー・ブレーブスで監督を務めております。"
"10043010-8-レイ" = "か、監督！？"
"10043010-9-スミレ" = "この方が……。"
"10043010-10-監督" = "仰る通り、ここは本来、関係者以外立ち入り禁止です。"
"10043010-11-監督" = "ですが、なにぶん緊急事態でして……。"
"10043010-12-監督" = "……どうか、我々を助けてはくださりませんか！"
"10043010-13-レイ" = "い、一体何が……？"
"10043010-14-スミレ" = "それは、トレーニングで解決できることでしょうか？"
"10043010-15-レイ" = "せ、先輩！"
"10043010-16-監督" = "実は――"
"10043010-17-監督" = "監督……「アレ」の準備は？"
"10043010-18-一同" = "！！！"
"10043010-19-監督" = "あ、ああ……。だが一つ聞きたい、目的は金か……？"
"10043010-20-監督" = "金など必要ない。重要なのは試合だ。"
"10043010-21-監督" = "いいか、もう一度作戦を説明する。 "
"10043010-22-監督" = "次の攻撃時……出塁したらバントだ。絶対だぞ。"
"10043010-23-謎の声" = "もし従わなければ、「予告」通り犯行に移る。"
"10043010-24-監督" = "……っ！"
"10043010-25-監督" = "ヴァルキューレに通報でもしてみろ……後はわかるな？"
"10043010-26-謎の声" = "攻守交代の時にまた連絡する。では。"
"10043010-27-スミレ" = "切れちゃった……。"
"10043010-28-スミレ" = "ボイスチェンジャーを使っていましたね……。"
"10043010-29-監督" = "ううぅ……何が目的で……！"
"10043010-30" = "[s] \"犯行予告の内容は？\""
"10043010-31-監督" = "ヤツから脅迫を受けたのは……少し前のことです。"
"10043010-32-スミレ" = "球団の監督に脅迫……なんででしょう……？"
"10043010-33-スミレ" = "さきほどの通話の内容も不可解でした……。"
"10043010-34-監督" = "言う通りに試合をしなかった場合……。"
"10043010-35-監督" = "ヤツは――"
"10043010-36-監督" = "ブレーブスと専属契約中の犬用ガム工場を、爆破すると言っているんです！"
"10043010-37-監督" = "これは未曾有のテロですよ……！"
"10043010-38" = "[ns] \"……今なんと？\""
"10043010-39-レイ" = "犬用、ガム……？"
"10043010-40-レイ" = "ちょ、ちょっとピンとこないのですが……。"
"10043010-41-監督" = "……我々にとっては深刻な問題なんです。"
"10043010-42-監督" = "あそこのガムは、ほど良い歯ごたえで、食感も抜群――"
"10043010-43-監督" = "さらに、噛めば噛むほど旨味が広がっていく傑作で……！"
"10043010-44-監督" = "うちの選手はみんな、あのガムで集中力を高めて試合に臨んでいるんです！"
"10043010-45-監督" = "もはや、あのガムもチームの一員と言って良いくらいに大切なガムなんです！"
"10043010-46-監督" = "あれなしでは打率が驚くほど下がってしまいます！"
"10043010-47-監督" = "防御率だって、信じられないほど悪くなるに違いない！"
"10043010-48-レイ" = "そ、そうなんですか……？"
"10043010-49-レイ" = "（そんなに深刻なんだ……）"
"10043010-50-スミレ" = "私はレイさんほど野球に詳しくはありませんが……。"
"10043010-51-スミレ" = "脅迫行為は、スポーツマンシップに反するものです。"
"10043010-52-レイ" = "たしかにそうですが……先輩がトレーニング以外に目を向けるなんて。"
"10043010-53-レイ" = "野球がきっかけで、先輩も他のスポーツに目覚めたり……？"
"10043010-54-スミレ" = "健康な精神は、健康な身体に宿ります。"
"10043010-55-スミレ" = "トレーニングさえしていれば、犯人も凶行に走ることはなかったでしょうに。"
"10043010-56-レイ" = "……って、結局トレーニングなんですか！？"
"10043010-57" = "[ns] \"事情は分かりました。\""
"10043010-58-監督" = "で、では……力を貸してくださるのでしょうか？"
"10043010-59-レイ" = "神聖な球場で、犯行予告をするだなんて……。"
"10043010-60-レイ" = "野球ファンとして許せません！"
"10043010-61-レイ" = "その上テロ予告まで……！"
"10043010-62-スミレ" = "私としても、このような暴挙は見過ごせません。"
"10043010-63-スミレ" = "こんなことがまかり通っては、スポーツ界全体に悪影響が及びます。"
"10043010-64" = "[s1] \"私も同意見です。\"\n[s2] \"ぜひ協力させていただきます。\""
"10043010-65-監督" = "あ、ありがとうございます……！"
"10043010-66-スミレ" = "でも先生、どうすればいいんでしょう……？"
"10043010-67-スミレ" = "観客席を巡回して犯人を捜そう、ですか。"
"10043010-68-レイ" = "たしかに、シラトリシリーズは中継が行われていないから……。"
"10043010-69-レイ" = "犯人はスタジアムのどこかで試合を見ているはずです。"
"10043010-70-レイ" = "ですが、捜している間にも、また連絡が来る……。"
"10043010-71-スミレ" = "次の攻守交代の時までに――"
"10043010-72-スミレ" = "犯人に対応する必要がありますね。"
"10043010-73-レイ" = "監督と通話を繋いでおいて、犯人との会話を聞きつつ動こう……ですか？"
"10043010-74-スミレ" = "なるほど。"
"10043010-75-スミレ" = "では、交渉はトレーナーとレイさんにお任せします。"
"10043010-76-スミレ" = "私の得意分野ではありませんので。"
"10043010-77" = "筋力と体力を要することなら、自信はあるのですが。"
"10043010-78" = "[s3] \"じゃあ、役割を分担しよう。\"\n[s4] \"まず、交渉班と、捜索班に分かれて……。\""
"10043010-79-レイ" = "では、私は交渉を担当しつつ、捜索も手伝いますね。"
"10043010-80-スミレ" = "私は観客席を見て回ります。"
"10043010-81-監督" = "通話回線を繋いでおきますので、先生、よろしくお願いします。"
"10043010-82-監督" = "ああ、それと……スミレさん、だったかな？"
"10043010-83-スミレ" = "ええ。"
"10043010-84-監督" = "レイさんは問題ないと思うけど……。"
"10043010-85-監督" = "あなたの格好は、観客席だと少々目立つかもしれない。"
"10043010-86-スミレ" = "そんなに変でしょうか……？"
"10043010-87" = "[s] \"変というわけじゃなくて……\""
"10043010-88-スミレ" = "なるほど……球場では珍しい、と。"
"10043010-89-スミレ" = "ですが、着替えもないですし……。"
"10043010-90-レイ" = "……あっ、いいこと思いつきました！"
"10043010-91-レイ" = "球場でおなじみの「アレ」！"
"10043010-92" = "[s] \"「アレ」？\""
"10043010-93-レイ" = "監督、ちょっと……（こそこそ）"
"10043010-94-監督" = "……ああ！なるほど！"
"10043010-95-レイ" = "……お待たせしました！先輩、どうぞ！"
"10043010-96-スミレ" = "これは……着慣れないですね……。"
"10043010-97-スミレ" = "その、トレーナー……。"
"10043010-98-スミレ" = "どう、ですか……？"
"10043010-99" = "[s] \"……！\""
"10043010-100" = "[ns5] \"すごく似合ってるよ！\"\n[ns6] \"いつもとは違う魅力があるね！\""
"10043010-101-スミレ" = "そ、そうですか？"
"10043010-102-スミレ" = "でしたら……この格好も悪くないですね。ふふっ。"
"10043010-103-スミレ" = "それでは、売り子さんとしてプロテインシェイクを提供していきましょう。"
"10043010-104-レイ" = "そ、それはいいですから！"
"10043010-105-レイ" = "もう時間がありません！行きましょう！"
"10043010-106-レイ" = "既に攻守交代してる可能性も……！"
"10043010-107-監督" = "まだ1アウトですし、大丈夫だと思いますよ。"
"10043010-108-レイ" = "え！？レイダースはまだ1アウトしか取られていないんですか！？"
"10043010-109-レイ" = "つまり……ブレーブスは得点を取られ続けて……？"
"10043010-110-監督" = "……。"
"10043010-111-スミレ" = "……。"
"10043010-112" = "[s] \"……。\""
"10043010-113-レイ" = "しょ、勝負は最後までわかりません……から！"
