[translation]
"10043025-1-過激だった観客A" = "はぁっ……はぁっ……。"
"10043025-2-過激だった観客B" = "試合も……トレーニングも……めちゃくちゃだ……。"
"10043025-3-スミレ" = "……本当に、一般の方だったのですね。"
"10043025-4-スミレ" = "……ちょっと残念です。"
"10043025-5" = "[s] \"さ、さあ、他も見て回ろう！\""
"10043025-6-アナウンサー" = "――3アウト！攻守交代です！"
"10043025-7-解説者" = "まだ試合は2回表ですが、今後どうなっていくのでしょうか。#n2回裏、ついにブレーブスの攻撃です。"
"10043025-8-スミレ" = "攻守交代ですね。"
"10043025-9-スミレ" = "つまり……次の連絡が……。"
"10043025-10-スミレ" = "……。"
"10043025-11-スミレ" = "トレーナーはレイさんのところに向かってください。"
"10043025-12" = "[s] \"任せて大丈夫？\""
"10043025-13-スミレ" = "ここはお任せください。"
"10043025-14-スミレ" = "私なりに捜索を続けていきます。"
"10043025-15-スミレ" = "それでは。#n交渉の成功を祈っております。"
