[translation]
"10043030-1" = "第3話;人は野球に夢を見る"
"10043030-2-レイ" = "あ、先生こっちです！"
"10043030-3-レイ" = "なんとか合流できましたね。"
"10043030-4" = "[s] \"様子はどう？\""
"10043030-5-レイ" = "まだ何も起きていないです。"
"10043030-6-レイ" = "……手がかりも、掴めていません。"
"10043030-7-レイ" = "でも、攻守交代なので、このあと……！"
"10043030-8-レイ" = "噂をすれば……！"
"10043030-9-レイ" = "はぁ、はぁ……"
"10043030-10-謎の声" = "動悸がする……聞いてるか？"
"10043030-11-監督" = "あ、ああ。大丈夫だ。"
"10043030-12-謎の声" = "あの守備で大丈夫だと！？#n何を言っているんだ！？"
"10043030-13-謎の声" = "いや、それはいい。#n繰り返しになるが、出塁したら次のバッターはバントだ。"
"10043030-14-謎の声" = "必ず成功させろ。"
"10043030-15-レイ" = "ま、待ってください！#n野球のお約束がありますよね！？"
"10043030-16-レイ" = "正式な規定ではありませんが、暗黙の了解として……"
"10043030-17-レイ" = "例えば、ノーヒットノーランと[ruby=パーフェクトゲーム]か完全試合、[/ruby]あとは、大差がついている局面ではバントを控えるとか……。"
"10043030-18-レイ" = "今バントをしても非難されることはないと思いますが……。"
"10043030-19-レイ" = "まだ2回裏ですよ！？"
"10043030-20-レイ" = "しかも、長打も打てる主力バッターを4番に配置しておいて――"
"10043030-21-レイ" = "その士気を高めてくれる、3番バッターにバントをさせるだなんて！"
"10043030-22-レイ" = "セイバーメトリクスの観点で言えば……ここでのバントは、むしろ得点期待値を下げる行為です！"
"10043030-23" = "[s] \"セイバーメトリクスって何？\""
"10043030-24-レイ" = "野球のデータを分析して、戦略をより科学的に分析する理論です。"
"10043030-25-レイ" = "セイバーメトリクスによると、ノーアウト一塁での得点確率は43.4%で、得点期待値は0.884点になります。"
"10043030-26-レイ" = "でもバントを打ってワンアウト二塁状況にすれば、得点確率は41.6%に減少し、得点期待値も0.714点になります。#nつまり――より不利な結果になるんです！"
"10043030-27" = "[ns1] \"……な、なるほど？\"\n[ns2] （わからない……！）"
"10043030-28-レイ" = "ちなみに、この理論を使って優れたステータスを持つ選手をスカウトし――"
"10043030-29-レイ" = "リーグ最下位のチームを強豪チームに作り変えていく名作映画もありますよ！"
"10043030-30-レイ" = "私の大好きな1作なので、先生もご興味あれば今度――"
"10043030-31-レイ" = "し……"
"10043030-32-レイ" = "し？"
"10043030-33-謎の声" = "素人は黙っとれ！！！"
"10043030-34-レイ" = "こ、これでも野球部なんですけど！"
"10043030-35-レイ" = "机上の空論に何の意味がある！#n目の前の3番バッターの打率を見てみろ！"
"10043030-36-謎の声" = "検索すればすぐ出る！"
"10043030-37-レイ" = "うーん、打率はあてにならないとの見解もありますが……。"
"10043030-38-レイ" = "ええと、ブレーブス3番バッター、打率っと……。"
"10043030-39-レイ" = "え、こっ、これは……！？"
"10043030-40-レイ" = "1割7分！？"
"10043030-41" = "[s] \"打率17％！？\""
"10043030-42-レイ" = "そうだよ。分かったか？"
"10043030-43-レイ" = "まさか、これほどの強打者だったなんて！"
"10043030-44-レイ" = "は……？"
"10043030-45-レイ" = "さすがはブレーブスの3番バッター……悔しいですが、ほんの少しだけ……私より上です。"
"10043030-46-レイ" = "お前の……打率は……？"
"10043030-47-レイ" = "0割8分です！"
"10043030-48" = "[s] \"……。\""
"10043030-49-レイ" = "は、8%……？"
"10043030-50-レイ" = "でも、ダメです！こんな[ruby=・]強[/ruby][ruby=・]打[/ruby][ruby=・]者[/ruby]にバントをさせるなんて！"
"10043030-51-レイ" = "試合の流れを止めないためにも、やっぱり――"
"10043030-52-謎の声" = "うるさい黙れ！#n言うことを聞けーっ！！！"
"10043030-53-レイ" = "ううっ……。"
"10043030-54" = "[s] \"監督、どうしますか？\""
"10043030-55-監督" = "工場の爆破だけはなんとしても阻止したいです……。"
"10043030-56-レイ" = "では、バントを成功させるしか……。"
"10043030-57-レイ" = "そのためには誰かが出塁しなくては……！#nこの回のトップバッターは2番ですが――"
"10043030-58-レイ" = "打った！あっ、いけない！内野ゴロです！"
"10043030-59-レイ" = "あ！レイダースが捕球ミスしました！"
"10043030-60" = "[s] \"これはチャンスかも……！\""
"10043030-61-レイ" = "走って……！一塁まで突っ走れっ！！"
"10043030-62-アナウンサー" = "ブレーブス、エラーによりトップバッターが出塁です！"
"10043030-63-解説者" = "レイダース、守備に回って緊張していたのでしょうか。"
"10043030-64-解説者" = "長かった2回表の疲労が出たのかもしれません。"
"10043030-65-アナウンサー" = "ここから反撃なるか！ブレーブスの攻勢に注目です！"
"10043030-66-選手" = "次、打席に立つのは3番バッターです。"
"10043030-67-選手" = "長打が期待できますね……おや、ここでバント？#nこ、これは……珍しいですね。"
"10043030-68-レイ" = "お願い！成功して……！"
"10043030-69-アナウンサー" = "バントです！ボールが当たって……！三塁線へ！"
"10043030-70-解説者" = "ランナーは二塁へ。ボールが一塁に投げられ……アウト。#nセーフティバントにはなりませんでしたね。"
"10043030-71-解説者" = "ワンアウトですがランナーは進塁できましたね。試合の展開を見ていきたいところです。"
"10043030-72-レイ" = "やったぁ！"
"10043030-73-監督" = "ふぅ……。"
"10043030-74" = "[s] \"緊張したね……。\""
"10043030-75-監督" = "計画通りだ。次は4番、長打に切り替えるタイミングだな。"
"10043030-76-謎の声" = "1点ずつ確実に取っていけ……！"
"10043030-77-レイ" = "チャンス到来です！"
"10043030-78-監督" = "ああ！このまま得点につなげよう！"
"10043030-79-アナウンサー" = "ブレーブスの4番バッター、打席に立ちました。"
"10043030-80-解説者" = "これは楽しみですね。"
"10043030-81-解説者" = "昨今、野球も数字と統計が重視されていますが、やはりマウンドの空気も欠かせない要素となっています。"
"10043030-82-アナウンサー" = "その通り！試合の流れを掴むのも実力です！"
"10043030-83-アナウンサー" = "そして初球を……打ちました！"
"10043030-84-レイ" = "当たった……！けど……これはサード真上のフライ……！#nツーアウトですね……！？"
"10043030-85" = "[s] \"あっ、二塁ランナーが走り出してる……！\""
"10043030-86-レイ" = "えっ！？マズいです！これじゃ[ruby=ゲッツー]併殺[/ruby]になっちゃいます！"
"10043030-87-アナウンサー" = "あーっと！ランナーの帰塁が間に合いません、ダブルプレーになってしまいました！#nブレーブス、3アウトでチェンジです！"
"10043030-88-解説者" = "せっかくのチャンスでしたが、ブレーブスとしては残念な結果になってしまいましたね。"
"10043030-89-謎の声" = "……っ。"
"10043030-90-レイ" = "先生、大丈夫ですか？"
"10043030-91" = "[s] \"私はなんともないよ？\""
"10043030-92-レイ" = "じゃあ監督がショックで？"
"10043030-93-監督" = "いや？"
"10043030-94-レイ" = "じゃあ、一体誰が……。"
"10043030-95-謎の声" = "俺だよ！！！"
"10043030-96-謎の声" = "チャンスだったのに……フライからの[ruby=ゲッツー]併殺[/ruby]で終わりだと！？"
"10043030-97-謎の声" = "4番バッターのくせに長打も打てないわ、ランナーはフライで走り出すわ……！"
"10043030-98-謎の声" = "もう何なんだよ、こいつら！！"
"10043030-99-レイ" = "ほら……ブレーブスも頑張っていますから……。"
"10043030-100-レイ" = "頑張ってるのはみんな同じだろうが！"
"10043030-101-謎の声" = "はぁ、はぁ、くそっ……ま、まだ試合は終わりじゃない。"
"10043030-102-謎の声" = "最後の一球まで……諦めるわけにはいかないんだ！"
"10043030-103-レイ" = "な、なんだかカッコイイ……！"
"10043030-104-謎の声" = "お前は黙ってろ！仕方ない……別パターンでいこう。"
"10043030-105-謎の声" = "3回でピッチャー交代だ！"
"10043030-106-レイ" = "待ってください、5イニングめまで投げた方がいいのでは！？"
"10043030-107-レイ" = "クオリティ・スタートはもう叶いませんが……。"
"10043030-108-レイ" = "あの投手だって、それなりに有望な選手なんですよ！"
"10043030-109-レイ" = "お前の目は節穴か！"
"10043030-110-レイ" = "ちょっと言い過ぎじゃないですか！？"
"10043030-111-レイ" = "防御率7点台が、有望選手なわけあるかーっ！！！"
"10043030-112-レイ" = "超優秀ですよ！"
"10043030-113-レイ" = "……うっ。"
"10043030-114" = "[ns] \"また倒れちゃった……。\""
"10043030-115-レイ" = "な、なんだか……"
"10043030-116-レイ" = "……苦労されてるみたいですね。"
"10043030-117-レイ" = "はぁっ……言った通りにしろ！座席ごと吹っ飛ばされたいのか！？"
"10043030-118-監督" = "まさか観客席に爆弾を！？"
"10043030-119-謎の声" = "いいか？3回でピッチャー交代だ！！"
"10043030-120-レイ" = "ど、どうしましょう……先生？"
"10043030-121" = "[s] \"とりあえず……\""
"10043030-122" = "[ns] \"捜索を再開しよう……。\""
"10043030-123-レイ" = "はい……。"
