[translation]
"2004203-1" = "拡張現実"
"2004203-2" = "（週末、マキと約束した通り、ミレニアム近くの山を訪れた）"
"2004203-3-マキ" = "うっ、うぐぐ……。"
"2004203-4" = "[s1] \"おはよう、マキ。\"\n[s2] \"スマホで何してるの？\""
"2004203-5-マキ" = "あっ、もう来たんだ。"
"2004203-6-マキ" = "ごめん、ちょっと待ってね。#nまだ今日のデイリーが……。"
"2004203-7-マキ" = "曜日ダンジョンもクリアしたし、スタミナも全部消費したから――"
"2004203-8-マキ" = "うん、これで完了！"
"2004203-9" = "[ns3] \"せっかく山まで来たのに……。\"\n[ns4] \"景色を楽しまないの……？\""
"2004203-10-マキ" = "あ、それなら心配しないで。"
"2004203-11-マキ" = "……[ruby=AR]拡張現実[/ruby]ゲームだからね！"
"2004203-12-マキ" = "見て、これ。カメラで撮られた地形に沿って動いてるでしょ？#nだからゲームしながら、周りの景色を楽しめるんだ。"
"2004203-13" = "[s] \"そういう意味で言ったつもりじゃ……。\""
"2004203-14-マキ" = "それにここの登山道は、前のキャンプ場よりも電波が良いからね。"
"2004203-15-マキ" = "実は今日、山に行こうって言ったのも――"
"2004203-16-マキ" = "はっ、こうしてる場合じゃない！#n冬の山は日が短いんだった！"
"2004203-17-マキ" = "先生、早く行こ！#n暗くなると景色が見えなくなるから！"
"2004203-18-マキ" = "うーん、たしかこの辺にあったような。"
"2004203-19" = "[s5] \"ちゃんと前を見て歩いてね。\"\n[s6] \"歩きスマホは危ないよ。\""
"2004203-20-マキ" = "う～、分かったよ。"
"2004203-21-マキ" = "……おかしいなぁ。#n攻略サイトだと、この辺りって書いてあったのに。"
"2004203-22-マキ" = "もしかして、座標を間違えてるのかな？"
"2004203-23" = "[s] \"探し物でもしてるの？\""
"2004203-24-マキ" = "物っていうより、野生動物に近いけど――"
"2004203-25-マキ" = "あった！"
"2004203-26-マキ" = "先生、見て！#n「黄金イタチ」だよ！"
"2004203-27" = "[s] \"私には見えないけど……。\""
"2004203-28-マキ" = "そっちじゃなくて、あたしのスマホ。"
"2004203-29-マキ" = "画面越しだと、金色のイタチが走ってるでしょ？"
"2004203-30-マキ" = "ふふっ。黄金イタチはね、このゲームで一番報酬が美味しいの。#nその分、普通のエリアじゃ全然見つからないんだけどね。"
"2004203-31-マキ" = "あるプレイヤーが、この登山道に現れるって言ってたから来てみたけど――#nまさか本当にいるなんて！"
"2004203-32" = "[s7] \"今日、山に来た理由は……。\"\n[s8] \"もしかして、そのARゲームのために？\""
"2004203-33-マキ" = "うん、そうだよ？"
"2004203-34-マキ" = "な、なんでそんな目で見るの！？"
"2004203-35-マキ" = "チヒロ先輩もARゲームは大丈夫って言ってたよ！？"
"2004203-36-マキ" = "運動になるから、健康にも良いって！"
"2004203-37" = "[s9] \"それはそうなんだけど……。\"\n[s10] \"せっかく山まで来たのに、もったいないような……。\""
"2004203-38-マキ" = "うっ、大人みたいな小言を……って、大人だから当たり前だよね。"
"2004203-39-マキ" = "わざわざ来てもらったのに、スマホばっかり見てたら失礼だし……。"
"2004203-40-マキ" = "何かして遊ぼう！"
"2004203-41-マキ" = "そうだ、レースはどう？#nあっちの渓谷まで先に着いた人の勝ち！"
"2004203-42-マキ" = "負けたらジュースね、先生！"
"2004203-43" = "[ns] \"ま、待って……！\""
"2004203-44-マキ" = "ふふっ、あたしの勝ち～！"
"2004203-45-マキ" = "な～んだ、もしかして運動不足なのは先生のほうじゃない？"
"2004203-46" = "[s11] \"最近ずっと座りっぱなしで体が……。\"\n[s12] \"生徒の体力を侮ってたよ……。\""
"2004203-47-マキ" = "……うーん、ここの渓谷、なんか物足りないような。"
"2004203-48-マキ" = "もうちょっと色が欲しいなぁ。"
"2004203-49" = "[s13] \"調べてみたら、ここって紅葉が有名らしいね。\"\n[s14] \"シーズンが過ぎたせいか、少し寂しいね。\""
"2004203-50-マキ" = "だね……。"
"2004203-51-マキ" = "あっ、良いアイデアを思いついたよ！"
"2004203-52-マキ" = "先生、ちょっと待っててね！"
"2004203-53-マキ" = "はい、先生。#nあたしのスマホで景色を見てみて！"
"2004203-54" = "[ns] \"どれどれ……。\""
"2004203-55" = "[ns15] \"……すごい、きれいな紅葉だ。\"\n[ns16] \"これ、どうやったの？\""
"2004203-56-マキ" = "拡張現実の機能だよ！"
"2004203-57-マキ" = "ゲームのシステムで、特殊なエフェクトもつけられるんだ！"
"2004203-58-マキ" = "その機能を使って、渓谷に紅葉を再現してみたの。"
"2004203-59-マキ" = "拡張現実を通じて見る世界も悪くないでしょ？"
"2004203-60" = "[s17] \"たしかに、すごいね……。\"\n[s18] \"現実よりも色鮮やかだね。\""
"2004203-61-マキ" = "そうでしょ？#nペンとインスピレーションがあれば、もっと楽しい景色にできるよ！"
"2004203-62-マキ" = "せっかくだし、あたしが何でも描いてあげる！"
"2004203-63-マキ" = "先生、どんな景色が見たい？"
"2004203-64" = "[s] \"そうだね、例えば……。\""
"2004203-65" = "（その後、マキが彩った景色を見ながら、楽しい時間を過ごした）"
