[translation]
"1002605-1" = "視線"
"1002605-2" = "（ネルが待っているという、ミレニアムの広場へと向かった）"
"1002605-3" = "（元々生徒たちがたくさんいる場所なのだけど、何だか今日は普段以上に騒がしい）"
"1002605-4-ミレニアムの生徒A" = "ねえねえ、何これ？何か面白いことでもあったの？"
"1002605-5-ミレニアムの生徒B" = "わ、私もよく分からないんだけど……何かのイベント、みたいな？"
"1002605-6-ミレニアムの生徒B" = "でも、今日は他のメンバーはいないし……なんであんな格好で……？"
"1002605-7-ミレニアムの生徒A" = "……？ってあれ、C&Cの先輩……？"
"1002605-8-ミレニアムの生徒A" = "え、なんでバニー姿で……。"
"1002605-9-？？？" = "おぉ、先生。こっちこっち。"
"1002605-10-ネル" = "……まあ時間通りだな、許してやる。"
"1002605-11" = "[s1] \"……ネル？\"\n[s2] \"白昼堂々その格好、なかなかすごいね……。\""
"1002605-12-ネル" = "やっぱ先生でもそういう反応すんのか。"
"1002605-13-ネル" = "やっぱ先生でもそういう反応すんのか。"
"1002605-14-ネル" = "ふーん、やっぱ目立つもんなんだな……。"
"1002605-15-ネル" = "……ん？任務中？"
"1002605-16-ネル" = "いや、別に？ただ何となく着てみただけだ。"
"1002605-17-ネル" = "この靴も慣れてきて、それなりに普通に歩けるようになったからよ。"
"1002605-18-ネル" = "とりあえず、その辺をてきとーに歩いてみっかなって。"
"1002605-19-ネル" = "やっぱ何回も着てみねぇと分かんないこともあんだろーし。"
"1002605-20-ネル" = "……ん？"
"1002605-21-ネル" = "視線？"
"1002605-22-ネル" = "いや、別に。"
"1002605-23-ネル" = "確かに、いつもより見られてる気もするが……。"
"1002605-24-ネル" = "にしても、やっぱり先生でもこの姿で目の前に現れると、ギョッとすんだな。参考になった。"
"1002605-25-ネル" = "っていうか、どいつもこいつも物珍しそうに……見せもんじゃねぇっての。"
"1002605-26-ネル" = "……あん？"
"1002605-27-ネル" = "平然としてる？そりゃそうだろ、"
"1002605-28-ネル" = "別に校則違反でもなければ、何かやべぇことをしてるわけでもねーし。"
"1002605-29-ネル" = "それを言うなら、あたしらは普段からメイド服だしな。"
"1002605-30-ネル" = "ま、どっちにしろ制服より楽だよ。あれ着るの、めちゃくちゃ息苦しいしな……。"
"1002605-31-ミレニアムの生徒たち" = "（ざわざわ……）"
"1002605-32-ネル" = "あー、ったく……。"
"1002605-33-ネル" = "だぁから、見せもんじゃねぇんだっての！さっさと散れ！！"
"1002605-34-ミレニアムの生徒たち" = "ひっ……！？"
"1002605-35-ネル" = "それで逃げるなら、最初っから来んなっての。"
"1002605-36-ネル" = "にしても……。"
"1002605-37-ネル" = "んー……。"
"1002605-38" = "[s3] \"……ネル？\"\n[s4] \"どうしたの？\""
"1002605-39-ネル" = "……いや、何つーか。"
"1002605-40-ネル" = "……いや、何つーか。"
"1002605-41-ネル" = "先生的にこれって、どうなんだ？"
"1002605-42-ネル" = "別に騒がれるのは良いんだけどよ、先生がどう思うかっつーか、変に見えるのかどうかっていうか……。"
"1002605-43-ネル" = "……ん？"
"1002605-44-ネル" = "すごくアリ……？"
"1002605-45-ネル" = "……はっ、そうかよ。"
"1002605-46-ネル" = "お世辞かどうかは分かんねぇけど、まあんなことはどうでも良いや。"
"1002605-47-ネル" = "さーてじゃあ今日は授業も任務も終わってっし……。"
"1002605-48-ネル" = "せっかくだしてきとーに、一緒に遊んでくか？先生。"
"1002605-49" = "（その後ネルと夜まで、ミレニアム校内のあちこちで遊んでからシャーレへと戻った）"
"1002605-50" = "（その間ずっと周りからの視線が突き刺さっていたけど、ネルが全く動じていなくて流石だった）"
