[translation]
"1002602-1" = "支援要請"
"1002602-2" = "（適度に急いで、ネルの部屋を訪れた）"
"1002602-3" = "（中にいたネルは、まだ着方が分からないまま変な怪物みたいになっていた）"
"1002602-4-ネル" = "何だこれ意味わかんねぇ、誰だこんな服考えたやつ……。"
"1002602-5-ネル" = "ん。"
"1002602-6-ネル" = "ああ、来たか。"
"1002602-7" = "[s] \"……？\""
"1002602-8-ネル" = "……え？"
"1002602-9-ネル" = "はぁっ！？先生！？"
"1002602-10-ネル" = "何で！？どうして先生がここに！？"
"1002602-11-ネル" = "いやおかしいだろ、何でいるんだよ！？"
"1002602-12-ネル" = "……は？"
"1002602-13-ネル" = "あたしが呼んだから？んなわけねーだろ！？"
"1002602-14" = "[s1] \"写真も送ってくれたのに。\"\n[s2] モモトークの画面を見せる。"
"1002602-15-ネル" = "いや嘘つけよ、騙されねーぞあたしは……。"
"1002602-16-ネル" = "えぇ……。"
"1002602-17-ネル" = "送ってんじゃん……。"
"1002602-18-ネル" = "くっそまた宛先間違えた！？"
"1002602-19-ネル" = "いや今回は色々見えにくかったせいで……！"
"1002602-20-ネル" = "っていうか写真！消せ！なんだそれダセェ！！"
"1002602-21-ネル" = "は？大丈夫？大丈夫じゃねーのはあたしの方だっ！！"
"1002602-22-ネル" = "そんな写真、誰かに見られたら……。"
"1002602-23-ネル" = "……ん？何だ？"
"1002602-24-ネル" = "は？バニーガールの着方なら知ってる？"
"1002602-25-ネル" = "……？"
"1002602-26-ネル" = "え、は？何で？"
"1002602-27-ネル" = "どうして知ってんだよ、着たことあんのか？"
"1002602-28" = "[s3] \"いつか必要になるかなって。\"\n[s4] \"一般教養。\""
"1002602-29-ネル" = "……？"
"1002602-30-ネル" = "……？"
"1002602-31-ネル" = "はっ、まあ何だって良いや。結果的に助かりそうだしな。"
"1002602-32-ネル" = "じゃあとりあえず、一回これは脱いで……。"
"1002602-33-ネル" = "……あん？どした、先生？"
"1002602-34-ネル" = "待って？やり方だけ先に教えるから自分で？"
"1002602-35-ネル" = "……あんでだよ？"
"1002602-36-ネル" = "まあ別に良いけど――"
"1002602-37-ネル" = "あ。"
"1002602-38-ネル" = "あー……まあ、そりゃ、そうか……。"
"1002602-39-ネル" = "OK、じゃあ教えてくれ。外で待っててくれれば、終わり次第呼ぶからよ。"
"1002602-40" = "[s] 全部の手順を伝えた後、部屋を一旦出る。"
"1002602-41" = "（そうしてしばらく、ネルの着替えを待った）"
"1002602-42-ネル" = "……おい、もう良いぞ先生。"
"1002602-43-ネル" = "ほーん、なるほどな。こういう風に着れば良いわけか。"
"1002602-44-ネル" = "見た目はなんか変な気もするが……やっぱメイド服より動きやすい気もすんな。"
"1002602-45-ネル" = "まさかまた先生に誤送信するとは思わなかったけど、結果オーライってな。ははっ。"
"1002602-46-ネル" = "うーん……ただ、この靴だけは慣れる気がしねーな……。"
"1002602-47-ネル" = "ハイヒール、って言うんだったか？"
"1002602-48-ネル" = "なんか踵とか、あちこちが痛ぇ……。"
"1002602-49-ネル" = "これ、履き方合ってんのか？"
"1002602-50-ネル" = "……まじか。ってことは街中のやつは、これで平然と歩いてんのか？"
"1002602-51-ネル" = "すげぇ、よく歩けんなこんなので……。"
"1002602-52-ネル" = "まあ、とにかく助かった。"
"1002602-53-ネル" = "サンキュな。"
"1002602-54-ネル" = "……ん？"
"1002602-55-ネル" = "必要な時はいつでも連絡してほしい？"
"1002602-56-ネル" = "ついでに写真もくれると嬉しい……？てめっ――"
"1002602-57-ネル" = "……くくっ。"
"1002602-58-ネル" = "ははっ！あー、何をそんな真面目な顔で……やっぱ変なやつだな。"
"1002602-59-ネル" = "……気が向いた時だけな。"
