[translation]
"10045110-1" = "第11話;負けられない戦い"
"10045110-2-ワカモ" = "お相手はナグサさんですか……。"
"10045110-3-ワカモ" = "ええ。相手にとって不足はございません。"
"10045110-4-ワカモ" = "それでは早速――"
"10045110-5-ナグサ" = "悪いけど、あなたの相手は私じゃない。"
"10045110-6-ワカモ" = "はい？では、どなたが……？"
"10045110-7-ナグサ" = "あなたの相手は――"
"10045110-8-キキョウ" = "キキョウだよ。"
"10045110-9-ナグサ" = "私は浮き島の上で戦ったことがないから……絶対勝てるとは言い切れない。"
"10045110-10-ナグサ" = "今、この場において……キキョウこそ、あなたの相手にふさわしい。"
"10045110-11-ユカリ" = "身共も同感ですわ！"
"10045110-12-ユカリ" = "今のキキョウ先輩は、えれがんとでぱわふるな試合を見せてくださるはずですの！"
"10045110-13-ワカモ" = "それは聞き捨てなりませんね。本気で仰っているのですか？"
"10045110-14-キキョウ" = "……否定はしない。"
"10045110-15-キキョウ" = "イズナとレンゲは直前まで試合をしていたし、チセはまだ回復してない。"
"10045110-16-キキョウ" = "準決勝に残った中で、一番体力が残っているのは私。"
"10045110-17-キキョウ" = "……最初に脱落しただけではあるけど。"
"10045110-18-レンゲ" = "さすがキキョウ先輩！その自信に満ちたお姿！頼もしいですの！"
"10045110-19-レンゲ" = "頼んだよ、キキョウ！#n全力の応援は任せとけっ！"
"10045110-20-キキョウ" = "先生も、それでいい？"
"10045110-21" = "[s1] \"もちろん！\"\n[s2] \"よろしくね、キキョウ！\""
"10045110-22-シズコ" = "それではこれより、キキョウ選手対ワカモ選手のエキシビションマッチを開催しますっ！"
"10045110-23-アラタ" = "おおっ！こりゃ絶対に見逃せないな！"
"10045110-24-アラタ" = "なあ、どっちが勝つと思う？"
"10045110-25-魑魅一座A" = "え……うーん、やっぱり七囚人じゃないですか？"
"10045110-26-魑魅一座B" = "あ、あたしは百花繚乱が勝つと思います！明日のおやつを賭けてもいいです！"
"10045110-27-アラタ" = "えっ！？これっておやつを賭ける流れなのか！？#nう～～ん……。"
"10045110-28-アラタ" = "んじゃ、あたしは七囚人に賭ける！"
"10045110-29-アラタ" = "頼む……！勝ってくれよ……！#nあたしのおやつが賭かってるんだ……！"
"10045110-30-キキョウ" = "……みんな、盛り上がってるみたい。"
"10045110-31-キキョウ" = "それじゃ、会場が冷めないうちに始めましょう。#nこちらはいつでも。"
"10045110-32-ワカモ" = "うふふっ、随分と自信がおありのようで？"
"10045110-33-キキョウ" = "自信があるとかないとか、そういう話じゃない。"
"10045110-34-キキョウ" = "私がやらなきゃならない。"
"10045110-35-ワカモ" = "抱える思いはそれぞれですか。いいでしょう。#nそれでは始めましょうか。"
"10045110-36-ワカモ" = "先生に選ばれる者を決する戦いを……！"
"10045110-37-シズコ" = "それでは、試合を始めますっ！"
"10045110-38" = "[ns] \"いざ尋常に……勝負っ！\""
"10045110-39-キキョウ" = "（さすがは災厄の狐……強い！）"
"10045110-40-ワカモ" = "あなた様のため……必ずや勝利を掴んで見せますわ。"
"10045110-41-キキョウ" = "くっ……！"
"10045110-42-シズコ" = "キキョウ選手、どんどん端に追い詰められています！#nこのまま海に落ちてしまうのかーっ！？"
"10045110-43-ナグサ" = "……やっぱり、力と運動神経はワカモが一枚上手だね。"
"10045110-44-ナグサ" = "でも……キキョウなら勝てる。今のキキョウは一味違うから。"
"10045110-45-キキョウ" = "（相手の力は圧倒的。まるで押し寄せる大波のよう……）"
"10045110-46-キキョウ" = "（押し返そうとしても無駄。だったら……）"
"10045110-47-レンゲ" = "もっと腕と脚を大きく動かして！体の力を抜いて！"
"10045110-48-キキョウ" = "力を抜いて動けだなんて……矛盾したことできるわけないでしょ！？"
"10045110-49-レンゲ" = "自然に逆らわず、流れに身を任せるのが大事なんだ。#n泳ぐっていうのは、そういうこと！"
"10045110-50-レンゲ" = "コツさえ掴めばすぐだよ！"
"10045110-51-キキョウ" = "（流れに身を任せればいい）"
"10045110-52-キキョウ" = "（無理に逆らわず、自分の得意な形に誘導する……！）"
"10045110-53-シズコ" = "追い詰められたキキョウ選手、ここで反撃だぁ！#nワカモ選手の攻撃をいなして、足をかけるような動き……！"
"10045110-54-ユカリ" = "そのまま……回転ですの！？"
"10045110-55-レンゲ" = "あの技は……！？"
"10045110-56" = "[ns] \"出た！キキョウのあやとり技！\""
"10045110-57-ワカモ" = "くっ……！？抜け……出せない……！"
"10045110-58-キキョウ" = "これは「あやとり」の基礎。"
"10045110-59-ワカモ" = "こんなあやとりがどこにありますかっ！"
"10045110-60-キキョウ" = "複雑に絡み合うって意味では、似てるかも？"
"10045110-61-シズコ" = "ワカモ選手、さっきまでの勢いはどこにいったのか！#nうまく対処できていないようです！"
"10045110-62-ユカリ" = "さすがキキョウ。効果的に相手を封じる方法がよく分かってる。"
"10045110-63-ユカリ" = "で、ですがさっきのレンゲ先輩はあの技を抜け出して――"
"10045110-64-レンゲ" = "いや。正直に言うと……あの時もギリギリだったんだ。"
"10045110-65-レンゲ" = "なのに、今のキキョウは気迫が違う……！"
"10045110-66-ワカモ" = "う、うううっ……！"
"10045110-67-ワカモ" = "……些か、侮りすぎたようですね。"
"10045110-68-シズコ" = "ワカモ選手、脱出しましたっ！#nだがその様子には疲れが見えるかー？"
"10045110-69-ワカモ" = "いつでもいいよ。何度だって絡め取ってあげる。"
"10045110-70-ワカモ" = "ならば、捕まるより早く仕留めて差し上げます……！"
"10045110-71-ワカモ" = "……！！"
"10045110-72-キキョウ" = "浮き島の上では弾力がある分、動きが大きくなる。"
"10045110-73-キキョウ" = "そんなに大きな動作で飛び込んでくるのは、「また捕まえてください」ってお願いしてるのと同じ。"
"10045110-74-ワカモ" = "……！！"
"10045110-75-シズコ" = "ワカモ選手、再びキキョウ選手に絡めとられてしまいましたっ！"
"10045110-76-ユカリ" = "真っ向勝負だったら、ワカモに軍配が上がったかもしれない。"
"10045110-77-レンゲ" = "でも、絡め手を使えるキキョウなら……！"
"10045110-78-ユカリ" = "キキョウ先輩が押せ押せですわ！"
"10045110-79-シズコ" = "このまま勝負が決まってしまうのか……！？"
"10045110-80" = "（まさに、会場の熱気も最高潮に達したその時……）"
"10045110-81-シズコ" = "……えっ？今度は何！？"
"10045110-82" = "[s] \"足場が爆発したみたいだけど……。\""
"10045110-83-シズコ" = "えっ！？そっちまで！？"
"10045110-84-レンゲ" = "キキョウ！後ろだ！波が……！！"
"10045110-85-シズコ" = "ここで予想外のトラブルが！"
"10045110-86-シズコ" = "試合の行方はビデオ判定をお待ちください……！"
"10045110-87-ワカモ" = "足場が爆発するだなんて……。"
"10045110-88-キキョウ" = "なんにせよ、先に落ちたのはそっちだよね。"
"10045110-89-ワカモ" = "まさか。そんなはずはありません。"
"10045110-90-ワカモ" = "結果が届きました！#n勝者は……[ruby=きりゅう]桐生[/ruby]キキョウ～～～！！"
"10045110-91-キキョウ" = "これは……。"
"10045110-92-ワカモ" = "突然発生した大波に飲まれようと……#n「先に海に落ちたほうが負け」がルールですか。"
"10045110-93-ワカモ" = "先生との約束ですから。本日は潔く引き下がりましょう。#nですが次は――"
"10045110-94-キキョウ" = "挑戦ならいつでも受けてあげる。"
"10045110-95-ワカモ" = "ふむ……#nそれにしても、あなた……。"
"10045110-96-ワカモ" = "なかなか独特な泳ぎ方をされますね。まるで――"
"10045110-97-キキョウ" = "やめて。それ以上は絶対に言わないで。"
"10045110-98-シズコ" = "アクシデントがありつつも、百夜水上祭も残すは決勝戦だけ！#nスタッフさん、再開の準備を――"
"10045110-99-シズコ" = "えええええ！？"
"10045110-100" = "[s] \"壊れたのは一か所だけじゃなかったみたいだね……。\""
"10045110-101-シズコ" = "すっ、すぐに消火作業を……！！"
"10045110-102" = "[ns3] \"もう手遅れな気が……。\"\n[ns4] \"……結局こうなるんだね。\""
