[translation]
"10045005-1" = "プロローグ;百花繚乱の親睦会"
"10045005-2" = "どこまでも澄んだ青い空に、じりじりと照りつける太陽。#n夏は、ここにある。"
"10045005-3" = "これは、友情と青春が織りなす、ひと夏の物語――"
"10045005-4-キキョウ" = "何やってるんだろう、私……。"
"10045005-5-キキョウ" = "部屋で兵法書を読みながら、のんびり過ごしてるはずだったのに。"
"10045005-6-キキョウ" = "どうして海に……。"
"10045005-7-ユカリ" = "先輩方と青い海！白い雲！そして爽やかな水着！#n身共がずーっと夢見てたしちゅえーしょんですの！"
"10045005-8-ユカリ" = "さぁ！のんびりしている場合ではありません！#n早く！早く波打ち際へ参りましょう！"
"10045005-9-キキョウ" = "私は遠慮しとく。"
"10045005-10-レンゲ" = "どうしたんだよ？キキョウも乗り気だっただろ？"
"10045005-11-レンゲ" = "親睦会には賛成したけど……海に来るなんて聞いてない。"
"10045005-12-ユカリ" = "キキョウ先輩は、海がお嫌いなのでしょうか……？"
"10045005-13-レンゲ" = "そ、そんなわけないでしょ。ただ――"
"10045005-14-キキョウ" = "私は、アウトドアが苦手なだけ。"
"10045005-15-ユカリ" = "いんどあ派ですものね、キキョウ先輩。"
"10045005-16-ユカリ" = "ですがここまで来ておいて、海で遊ばないなんて言語道断、ですの！"
"10045005-17-ユカリ" = "さあキキョウ先輩！いざ、参りましょう！"
"10045005-18-ユカリ" = "はぁ……。"
"10045005-19-レンゲ" = "まあまあ、それくらいにしとこう。#n無理に連れ出すのもよくないしさ。"
"10045005-20-レンゲ" = "アタシらは先に行ってるから、気が向いたらいつでも来いよ！"
"10045005-21-ユカリ" = "お待ちしておりますの！"
"10045005-22-キキョウ" = "はぁ……。"
"10045005-23-ナグサ" = "……ごめん。他の場所にすればよかったね。"
"10045005-24-キキョウ" = "いや、みんなは海に来たがってたし。"
"10045005-25-キキョウ" = "せっかく盛り上がってるのに、私の我儘で水を差すわけにはいかないでしょ？"
"10045005-26-ナグサ" = "ふふっ。そっか。"
"10045005-27-キキョウ" = "でも、準備運動くらいはしておいたほうがいいかも。"
"10045005-28-ナグサ" = "もうすぐ始まるから。"
"10045005-29-ナグサ" = "百鬼夜行の、夏の風物詩――"
"10045005-30" = "[log=나구사 수영복][ruby=ももよすいじょうさい]百夜水上祭[/ruby][/log]"
"10045005-31-キキョウ" = "（どこで間違えたの……？）"
"10045005-32-キキョウ" = "（お祭りに参加するつもりもなかったのに……）"
"10045005-33-キキョウ" = "（そもそも、泳げない私がどうして……！）"
"10045005-34-ナグサ" = "全員当選するとは思わなかったよね。#n参加するだけでも、すごい倍率だったのに。"
"10045005-35-キキョウ" = "そう。本当に予想外……。"
"10045005-36-キキョウ" = "（私だけでも落選して欲しかった……）"
"10045005-37-ナグサ" = "キキョウ？大丈夫？何か考え事？"
"10045005-38-キキョウ" = "……秘策を練ってたの。"
"10045005-39-キキョウ" = "華麗に、絶対的な勝利を掴む策を。"
"10045005-40-ナグサ" = "……そっか。"
"10045005-41-ナグサ" = "それじゃ、楽しみにしてるね。キキョウの考えた策。"
"10045005-42-キキョウ" = "（考えないと……。#n百花繚乱の作戦参謀の名に懸けて――）"
"10045005-43-キキョウ" = "（水を怖がってるなんて、絶対バレるわけにはいかない……！）"
