[translation]
"10045060-1" = "第6話;敗者復活戦：ビーチバレー"
"10045060-2-シズコ" = "皆さ～ん！しっかり休憩できましたか～？"
"10045060-3-シズコ" = "それでは今から、敗者復活戦！ビーチバレーの第1試合を始めます！"
"10045060-4-シズコ" = "選手入場！"
"10045060-5-シズコ" = "試合は10点先取の一本勝負！"
"10045060-6-シズコ" = "1点が勝敗を分ける、緊張感のある試合になること間違いなし！"
"10045060-7" = "[ns] \"先攻はジャンケンで決めるよ！\""
"10045060-8-シズコ" = "両チームの代表、一歩前へ！"
"10045060-9-スケバンリーダー" = "へっへっへ、私はグーを出す。"
"10045060-10-レンゲ" = "へぇ、心理戦か。"
"10045060-11-スケバンリーダー" = "勝ちたきゃパーを出すんだな。私は正々堂々グーで勝負する！"
"10045060-12-レンゲ" = "正々堂々、グー。なるほどな。"
"10045060-13" = "[ns] \"最初はグー！じゃんけん――ポン！\""
"10045060-14-レンゲ" = "グー！#n青春は突進だ！ってあれ！？"
"10045060-15-スケバンリーダー" = "へっへっへ、正々堂々。いいと思うぜ？#nまっ、私は勝ちたいからパーを出したけどな！"
"10045060-16-キキョウ" = "……ごめん、キキョウ。"
"10045060-17-キキョウ" = "先攻を取られたぐらいで慌てる必要はないよ。実力はこっちが上なんだから。"
"10045060-18-スケバンリーダー" = "最初はいいけど、この後はどうする？何か策はあるのか？"
"10045060-19-スケバンリーダー" = "もちろんさ。"
"10045060-20-スケバンリーダー" = "あのキキョウってやつ、さっきまで溺れて気を失ってたんだろ？"
"10045060-21-スケバンリーダー" = "あいつを徹底的に狙うんだ。弱点を突けば試合なんて楽勝だ！"
"10045060-22-アラタ" = "えぇ……それはあんまり気が進まねえんだけど……。"
"10045060-23-シズコ" = "それでは試合開始です！"
"10045060-24-シズコ" = "いざ尋常に～勝負！"
"10045060-25-スケバンリーダー" = "喰らえ！野望のスパイクサーブ！"
"10045060-26-キキョウ" = "ぐっ……！"
"10045060-27-シズコ" = "あぁっと！キキョウ選手の身体に当たってボールがラインの外へ！"
"10045060-28-シズコ" = "さっそく先制点が入りました！"
"10045060-29-スケバンリーダー" = "へっ、思った通り動きが鈍ってやがる。#n言っただろ？あいつが弱点だってな！"
"10045060-30-キキョウ" = "私が……弱点？"
"10045060-31-スケバンリーダー" = "そうさ。私は相手の目を見れば、何を考えてんのか一発で分かるんだ。"
"10045060-32-スケバンリーダー" = "お前は今、こう考えているはずだ。"
"10045060-33-スケバンリーダー" = "自分がみんなの足を引っ張っている、と。"
"10045060-34-スケバンリーダー" = "自分はこのチームで役に立っていない、と。"
"10045060-35-スケバンリーダー" = "まあ、お友達はお前のせいで脱落したんだし、そう考えても無理はねぇよな。"
"10045060-36-レンゲ" = "……！"
"10045060-37-レンゲ" = "キキョウ！そんなやつの言うことなんて聞くな！"
"10045060-38-キキョウ" = "……分かってる、大丈夫。"
"10045060-39-スケバンリーダー" = "じゃあ、もう一発いくぜ！"
"10045060-40-キキョウ" = "ぐっ……！"
"10045060-41-レンゲ" = "アタシが拾う！"
"10045060-42-レンゲ" = "キキョウ！"
"10045060-43-キキョウ" = "任せて……！"
"10045060-44-アラタ" = "タヌキ！ブロック！"
"10045060-45-アラタ" = "誰がタヌキだ！"
"10045060-46-アラタ" = "ぐぇっ……！？"
"10045060-47-シズコ" = "アラタ選手、見事な顔面ブロックです！#nこれで早くも2点差となってしまいました！"
"10045060-48-キキョウ" = "あ……。"
"10045060-49-スケバンリーダー" = "よしよし、ナイスブロックだ。"
"10045060-50-アラタ" = "いいわけないだろ！#nうぅ……鼻血でた……。"
"10045060-51-スケバンリーダー" = "百花繚乱もこんなもんか。警戒して損したぜ。"
"10045060-52-スケバンリーダー" = "このままあいつを徹底的に狙えば……！"
"10045060-53-キキョウ" = "……。"
"10045060-54-レンゲ" = "言わせておけば……！"
"10045060-55" = "それからも試合は続き……。"
"10045060-56-シズコ" = "試合終了ー！"
"10045060-57-シズコ" = "瞬きを許さぬ攻防！白熱した試合でしたね！"
"10045060-58-キキョウ" = "はぁ、はぁ……。"
"10045060-59-キキョウ" = "……。"
"10045060-60-アラタ" = "ふっ……ふはは……。"
"10045060-61-アラタ" = "燃え尽きた……真っ白に……。"
"10045060-62-シズコ" = "最終スコアは10対7！"
"10045060-63-シズコ" = "第1試合は、キキョウ・レンゲチームの勝利です～！"
"10045060-64-アラタ" = "なんだ、強いじゃねぇか……。"
"10045060-65-アラタ" = "だから無理だって……言っただろ……。"
"10045060-66-シズコ" = "それではインタビューをしてみましょう！"
"10045060-67" = "[ns] \"レンゲの活躍が目立つ試合だったね！\""
"10045060-68-シズコ" = "やるべきことをやっただけだよ。"
"10045060-69-シズコ" = "途中から試合の流れが大きく変わるタイミングがありましたが……何がきっかけだったのでしょうか？"
"10045060-70-シズコ" = "負けたくない、が負けられない。になったことかな。"
"10045060-71-シズコ" = "友達をバカにするやつは許せないからな。"
"10045060-72-キキョウ" = "……。"
"10045060-73-ナグサ" = "キキョウ先輩、まだ調子が戻ってないみたいですの。"
"10045060-74-ユカリ" = "レンゲ先輩との連携が、上手くかみ合っておりませんでした。"
"10045060-75-ナグサ" = "そっか……。"
"10045060-76-ユカリ" = "キキョウ……まださっきのこと気にしてるんだね。"
"10045060-77-ナグサ" = "実は私も言ってなかったことがあるんだけど……。"
"10045060-78-ナグサ" = "ボートの時に無茶しすぎたみたい。#nちょっと右腕が動かしにくくなってる。"
"10045060-79-ユカリ" = "そっ、それはすぐお医者様に――"
"10045060-80-ナグサ" = "ありがとう。でも、心配はしなくて大丈夫。#n大したことじゃないし、この感じならすぐ治ると思うから。"
"10045060-81-ユカリ" = "分かりました！では、ナグサ先輩の右腕が回復するまで、身共が全力でさぽ～といたしますの！"
"10045060-82-ミモリ" = "……なるほど。"
"10045060-83-百鬼夜行サークル部員A" = "あれ？どうかしたんですか？"
"10045060-84-ミモリ" = "ナグサさん、どうも体調が万全ではないようで。少し心配ですね。"
"10045060-85-百鬼夜行サークル部員A" = "えっ、見ただけで分かるんですか？"
"10045060-86-ミモリ" = "ふふっ、ちょっとした方法があるんです。"
"10045060-87-シズコ" = "さて！第2試合の準備が整ったようです！選手入場～！"
"10045060-88-シズコ" = "それでは、いざ尋常に～#n――勝負！！"
"10045060-89" = "こうして始まった第2試合。"
"10045060-90" = "目を離せない激戦が展開されていた。"
"10045060-91-シズコ" = "おおっと、ミモリ選手！まるで相手の心を読んでいるかのようなプレイっ！"
"10045060-92-シズコ" = "あの百花繚乱を相手に一歩も引きません！"
"10045060-93-ユカリ" = "手の内を見透かされてる感じがするね。"
"10045060-94-ユカリ" = "心を読み取られる……。"
"10045060-95-ナグサ" = "考えすぎても、かえって失敗してしまいますし……。"
"10045060-96-ユカリ" = "ならば――"
"10045060-97-ユカリ" = "頭を空っぽに！"
"10045060-98-ユカリ" = "舞う巫女のごとく、風に身を委ねて。#n春風に乗り、ひらひらと舞い散る桜のように……。"
"10045060-99-ユカリ" = "身共、しなやかで凛とした心で自分と向き合いますの！"
"10045060-100-ユカリ" = "次は百花繚乱チームのサーブ！ユカリ選手が構えました！"
"10045060-101-ユカリ" = "いざ、快進撃のお時間ですわ！"
"10045060-102-レンゲ" = "おっ、ありゃ流れが変わったな。"
"10045060-103-キキョウ" = "うん、ユカリとナグサ先輩、上手にお互いを補い合ってる。"
"10045060-104-キキョウ" = "それに比べて私は……。"
"10045060-105-キキョウ" = "おいおい、いつまで気にしてんだよ。"
"10045060-106-レンゲ" = "誰だって最初っから完璧なわけじゃないんだ。"
"10045060-107-レンゲ" = "悩んで、迷って……それが青春ってもんだろ！"
"10045060-108-キキョウ" = "……。"
"10045060-109-レンゲ" = "分かった。じゃあこうしよう。"
"10045060-110-レンゲ" = "この種目が終わったら、アタシがキキョウに泳ぎを教えてやる！"
"10045060-111-キキョウ" = "私が……泳ぐ？"
"10045060-112-レンゲ" = "キキョウは要領がいいから、すぐに覚えられるって。#n水が怖いなんて、もう言わせないからな。"
"10045060-113-キキョウ" = "何を根拠に……。"
"10045060-114-レンゲ" = "アタシは、ずっと横でお前を見てきた。"
"10045060-115-レンゲ" = "これじゃ不足か？"
"10045060-116-キキョウ" = "……まったく、そういうところは変わらないんだから。"
"10045060-117-シズコ" = "試合……終了ー！"
"10045060-118-シズコ" = "またもまたもや大接戦！"
"10045060-119-シズコ" = "10対8のスコアで試合を制し、決勝進出を決めたのは……！"
"10045060-120" = "[ns] \"ナグサ・ユカリチームです！\""
"10045060-121-キキョウ" = "……。"
"10045060-122-キキョウ" = "（レンゲは幼馴染）"
"10045060-123-キキョウ" = "（他の誰よりも、お互いを熟知してる友達）"
"10045060-124-キキョウ" = "（……だからこそ、私はもっと頑張らなきゃ）"
"10045060-125-キキョウ" = "（これ以上、レンゲの足を引っ張るわけにはいかない）"
"10045060-126-キキョウ" = "（絶対に勝ってみせる）"
"10045060-127-キキョウ" = "（私のためじゃなく、レンゲのために……！）"
