[translation]
"10045040-1" = "第4話;第三回戦：水上障害物レース"
"10045040-2" = "悲鳴あふれる船旅も、やがて終わりを迎えた。"
"10045040-3-シズコ" = "さあ、第二回戦を突破した10人の選手をご紹介します～！"
"10045040-4-シズコ" = "皆さん、大きな拍手でお迎えください！"
"10045040-5-シズコ" = "ここまで残っているということは……その実力は疑うまでもありません！#nもはや誰が優勝してもおかしくない！この先の活躍も期待してます！"
"10045040-6-シズコ" = "それでは、しばらく休憩を挟んで、第三回戦でお会いしましょう！"
"10045040-7-シズコ" = "そしてここで……皆さんに耳寄りな情報を……。#nそろそろ、お腹が空いてくる頃じゃないですか～？"
"10045040-8-シズコ" = "そんな皆さんのために百夜堂出張版、海の家が朝からオープンしております！"
"10045040-9-シズコ" = "シズコが厳選したメニューをお手頃価格で楽しめるので、ぜひお立ち寄りください！"
"10045040-10-シズコ" = "それでは、お待ちしていま～す、にゃんにゃん！"
"10045040-11-シズコ" = "ふぅ……いい仕事した～"
"10045040-12-ユカリ" = "みんな……海の家で何か食べる？"
"10045040-13-レンゲ" = "アタシはパス……今は何も食べたくない……。"
"10045040-14-ナグサ" = "実は、私も……。"
"10045040-15-キキョウ" = "命がけでしたの……。"
"10045040-16-キキョウ" = "もう思い出したくもない……。"
"10045040-17" = "[ns1] \"全員突破おめでとう！\"\n[ns2] \"さすがは百花繚乱だね！\""
"10045040-18-ユカリ" = "あ、ありがとうございます……ですの……。"
"10045040-19-ユカリ" = "先生、次の種目は何？"
"10045040-20-キキョウ" = "（何であれ、水に入るのだけは避けたいけど……）"
"10045040-21" = "[ns] \"次はみんな大好き――\""
"10045040-22" = "[log]早い者勝ち！水上障害物レース！[/log]"
"10045040-23-キキョウ" = "……一難去ってまた一難ね。"
"10045040-24-シズコ" = "決勝戦に続く最後の関門！百夜水上祭の華！#nこれを待っていた方も多いでしょう！水上障害物レースのお時間です！"
"10045040-25-シズコ" = "ルールはシンプル！10人が一斉にスタートし、ゴールを突破した2名だけが決勝戦に進出できます！"
"10045040-26-シズコ" = "今回のコースに待ち受ける障害をご紹介しましょう！"
"10045040-27-シズコ" = "ぐるぐる回る足場！"
"10045040-28-シズコ" = "水風船が降り注ぐ坂道！"
"10045040-29-シズコ" = "浮き輪の飛び石ゾーン！"
"10045040-30-シズコ" = "どこに繋がるかは運しだいの滑り台！"
"10045040-31-シズコ" = "これらの障害を突破し、ゴールを目指してください！"
"10045040-32-キキョウ" = "……はぁ。"
"10045040-33-レンゲ" = "水に濡れたくないなら、落ちなきゃいいだけだろ？"
"10045040-34-キキョウ" = "当然、そのつもり。"
"10045040-35-キキョウ" = "（……そう。無理せず、適当にやり過ごして安全にゴールを目指す。#n水に落ちなければいいんだから）"
"10045040-36" = "一方、その頃……。"
"10045040-37-スケバンリーダー" = "くそっ、どうなってるんだ！？#nあいつら全員残ってるじゃないか！"
"10045040-38-スケバンリーダー" = "このままじゃ勝ち目がない！"
"10045040-39-スケバンリーダー" = "もう諦めようぜ……決勝に進めるのは二人だけなんだぞ。"
"10045040-40-スケバンリーダー" = "私たちが勝ちゃいいだけの話だろ！なんで諦めるんだよ！"
"10045040-41-スケバンリーダー" = "お前は知らないかもしれないけど……。"
"10045040-42-アラタ" = "正直、あいつら本当に強いんだよ。"
"10045040-43-アラタ" = "それに、優しくしてくれたこともあるし……ずっと目の敵にしてるのも悪い気がするんだよな。"
"10045040-44-スケバンリーダー" = "弱気になるな！まだチャンスはある！私の計画通りにやれば勝てる！"
"10045040-45-スケバンリーダー" = "くくっ……くくく……くくくくくっ……！"
"10045040-46-アラタ" = "う、うわ……なんか悪役っぽい笑い方なんだけど……。"
"10045040-47-スケバンリーダー" = "次こそ……次こそは……！"
"10045040-48" = "そしてしばらくして……。"
"10045040-49-シズコ" = "お待ちかね、水上障害物レースを始めます！"
"10045040-50-レンゲ" = "いよいよだね……。"
"10045040-51-レンゲ" = "アタシと決勝で戦うのは誰だろうな？"
"10045040-52-ユカリ" = "一緒にゴールして、全員で決勝戦進出ですの！"
"10045040-53-キキョウ" = "そんなこと、できるわけないでしょ。"
"10045040-54-キキョウ" = "（はぁ……）"
"10045040-55-キキョウ" = "（私は自然に脱落しておくのが一番かな）"
"10045040-56-キキョウ" = "（言い訳も用意しておいたし……）"
"10045040-57-キキョウ" = "（問題は、どうやって自然に脱落するか……考えなさい、キキョウ……！）"
"10045040-58-レンゲ" = "キキョウ。#n……キキョウ？"
"10045040-59-レンゲ" = "すごい考え込んでるな……。"
"10045040-60-シズコ" = "選手の皆さん！ スタートラインにお並びくださ～い！"
"10045040-61-シズコ" = "第三回戦、水上障害物レース……！"
"10045040-62" = "[ns] \"始めっ――！！\""
"10045040-63-シズコ" = "まずトップに躍り出たのは百花繚乱の四人！"
"10045040-64-シズコ" = "ぐるぐる回る足場がその行く手を阻みます！#n果たして無事に渡れるでしょうか～？"
"10045040-65-ナグサ" = "一思いに行くのがよさそうかな。"
"10045040-66-ユカリ" = "足場の回転よりも早く駆け抜ければ問題ないですの！"
"10045040-67-レンゲ" = "いつもの鍛錬に比べれば大したことないな！"
"10045040-68-キキョウ" = "（下は見ない。下は見ない。下は見ない……！）"
"10045040-69-シズコ" = "なんと！全員が一気に飛び越えました！"
"10045040-70-イズナ" = "サササッ！イズナも負けてはいられません！ニンニン！"
"10045040-71-チセ" = "しゅ～ん。"
"10045040-72-ミモリ" = "それっ。"
"10045040-73-シズコ" = "次々と障害を突破していきます！まったく差が開きません！"
"10045040-74" = "[ns] \"さすが、ここまで残った実力者たちですね！\""
"10045040-75-スケバンリーダー" = "いいぞいいぞ……そのままだ……そのまま行け！"
"10045040-76-スケバンリーダー" = "おい、ちゃんと指示通りにやったんだろうな？"
"10045040-77-スケバンリーダー" = "えっと……一応やってはあるんだけど……。"
"10045040-78-シズコ" = "水風船が降り注ぐ坂道に先頭集団が差し掛かりました！！#n当たらないように気をつけてくださいね～！"
"10045040-79-ナグサ" = "ここも一気に――"
"10045040-80-ナグサ" = "うっ……！？"
"10045040-81-ナグサ" = "何……？これ、滑るし、ベタつく……。"
"10045040-82-レンゲ" = "この匂い……ココナッツオイルか！？"
"10045040-83-ユカリ" = "こ、これでは坂道を登れませんの……！"
"10045040-84" = "[ns] \"シズコ？みんなオイルまみれになってるけど……。\""
"10045040-85-シズコ" = "あ、あれ！？そんなはずは……！"
"10045040-86-シズコ" = "スタッフさん、確認をお願いします！"
"10045040-87-スケバンリーダー" = "上手くいったな。これで一気に差をつけられるぜ！"
"10045040-88-スケバンリーダー" = "お先っ！"
"10045040-89-レンゲ" = "な、なんだそれ！？かぎ縄なんて、どっから出したんだよ！"
"10045040-90-アラタ" = "こうなることを見越して用意しておいたのさ！"
"10045040-91-アラタ" = "お前らはそこで仲良くベタベタしてるんだな！"
"10045040-92-ユカリ" = "なっ……！自分たちが使った後は縄を切り落とすなんて……卑怯ですの！"
"10045040-93-イズナ" = "皆さん、まずはオイルを流しましょう！"
"10045040-94-イズナ" = "イズナがお手伝いします！#nイズナ流忍法！噴水の術！"
"10045040-95-キキョウ" = "結局、濡れる運命だったのね……。"
"10045040-96-レンゲ" = "追いかけるよ！まだまだ巻き返せる！"
"10045040-97-スケバンリーダー" = "嘘だろっ！？もう追いついてきたのか！"
"10045040-98-スケバンリーダー" = "大丈夫だ！この先にも仕掛けをしておいたからな！"
"10045040-99" = "[log]次のコース！[/log]"
"10045040-100" = "[log]浮き輪の飛び石ゾーン！[/log]"
"10045040-101-アラタ" = "浮き輪に爆弾を仕掛けてある。#n知らずに踏んだら爆発して海にドボンって寸法よ！"
"10045040-102-スケバンリーダー" = "安全なのは私だけが分かるように印を付けてあるんだ！"
"10045040-103-アラタ" = "な、なら先に行けよ！どれが安全か分かんねぇから！"
"10045040-104-レンゲ" = "さっきはよくもやってくれたな。"
"10045040-105-スケバンリーダー" = "まだまだ、こんなもんじゃ――"
"10045040-106-スケバンリーダー" = "……あれ？"
"10045040-107-アラタ" = "バカ！なんでお前が踏むんだよ……！！"
"10045040-108-アラタ" = "はぁ……。"
"10045040-109-シズコ" = "あーっと、先頭を走っていた二人がリタイアです！"
"10045040-110-シズコ" = "それにしても、誰が浮き輪に爆弾なんて仕掛けたんですか！"
"10045040-111" = "[ns] \"シズコじゃないの？\""
"10045040-112-シズコ" = "私がやるわけないでしょうが！"
"10045040-113-イズナ" = "爆発する足場があるなら、踏まずに通れば問題なし！"
"10045040-114-イズナ" = "イズナ流忍法！水上走りの術！"
"10045040-115-シズコ" = "な、なんと……！イズナ選手、水の上を走っています……！"
"10045040-116" = "[s] \"イズナなら5歩くらいはいける……！\""
"10045040-117-レンゲ" = "負けてられないな！アタシだって……！"
"10045040-118-キキョウ" = "ちょっと！そんな無茶な走り方をしたら……！"
"10045040-119-レンゲ" = "たかが爆弾ごときで、アタシを止められると思うなよ！"
"10045040-120-レンゲ" = "おおっ！レンゲ選手も無事に突破しました！"
"10045040-121-レンゲ" = "ほらっ、キキョウも！"
"10045040-122-キキョウ" = "（レンゲが踏んだ浮き輪なら、問題ないはず……！）"
"10045040-123-キキョウ" = "……え？"
"10045040-124-キキョウ" = "（どうしてっ！）"
"10045040-125-キキョウ" = "（な、何がどうなったの……？ 足場を踏み間違えた……？）"
"10045040-126-キキョウ" = "（こんな大事な場面で……私がミスをするなんて……）"
"10045040-127-キキョウ" = "（はっ早く……上に……）"
"10045040-128-キキョウ" = "（でも……だんだん……意識が……）"
"10045040-129-キキョウ" = "（みんな……ごめん……）"
"10045040-130-レンゲ" = "……キキョウ？"
"10045040-131-レンゲ" = "キキョウ――！！"
