[translation]
"10045020-1" = "第2話;第一回戦：水鉄砲サバイバルゲーム"
"10045020-2-スケバンリーダー" = "押し込め！まずは百花繚乱から叩き潰せ！！"
"10045020-3-アラタ" = "これまでの分、たっぷり仕返ししてやる！！"
"10045020-4-レンゲ" = "ユカリ！そっち抜かれそうだけど、持ち直せる？"
"10045020-5-ユカリ" = "ま、まだ大丈夫ですの！"
"10045020-6-キキョウ" = "どうして……？#n作戦は完璧だったはずなのに……。"
"10045020-7-ナグサ" = "やっぱり私じゃダメなんだ……私じゃみんなの足を引っ張ってしまうばっかりで……。"
"10045020-8-レンゲ" = "ちょっ、二人ともしっかりしてくれ！！"
"10045020-9" = "10分前……。"
"10045020-10-キキョウ" = "四方八方、見晴らしのいいビーチ……。"
"10045020-11-キキョウ" = "まずはみんな隠れられる場所を確保しようとするはず。"
"10045020-12-キキョウ" = "だから私たちも最初は、砂で陣地を作って凌ぐのが最善だと思う。"
"10045020-13-ユカリ" = "では、それまでの時間は身共が稼ぎますの！"
"10045020-14-ナグサ" = "アタシは突撃するのが性に合ってるけど……#nいいよ、キキョウが言うなら、それでいこう。"
"10045020-15-ナグサ" = "決まりだね。何から始める？"
"10045020-16-キキョウ" = "……どこで間違えたんだろう？"
"10045020-17-キキョウ" = "予想通りなら、こんな乱戦にはならないはずだったのに。"
"10045020-18-魑魅一座A" = "うわああっ……！"
"10045020-19-魑魅一座B" = "おい！しっかりしろ！#n一緒に勝ち残って、スイーツ食べに行く約そ――"
"10045020-20-魑魅一座B" = "うわああああっ……！"
"10045020-21-魑魅一座C" = "もう二人やられた！百花繚乱め……絶対に許さないからな！！"
"10045020-22-レンゲ" = "それは言いがかりですの！！"
"10045020-23-レンゲ" = "何でアタシらばっか狙われるんだよ！？"
"10045020-24-アラタ" = "あたしらのために、ここで負けてくれ！！"
"10045020-25-スケバンリーダー" = "そうだそうだ！優勝候補を落とせば、私たちにもチャンスが生まれる！！"
"10045020-26-アラタ" = "お前らのせいで活動資金も底をついた……。#n絶対に優勝賞金を手に入れなきゃならないんだ！！"
"10045020-27-キキョウ" = "優勝したい理由は分かったけど……。"
"10045020-28-レンゲ" = "そんなの、自業自得だろ！！"
"10045020-29-スケバンA" = "あっ！リーダー危ない……っ！！"
"10045020-30-スケバンA" = "ぎゃああっ……！！"
"10045020-31-スケバンリーダー" = "くそっ……！そ、そんな……！"
"10045020-32-スケバンリーダー" = "お、お前ら、絶対許さないからな！！"
"10045020-33-ユカリ" = "これが憎しみの連鎖……！これぞ戦場の悲哀！"
"10045020-34-ユカリ" = "ですが、こんな試練を乗り越えるのも青春ですの！"
"10045020-35-レンゲ" = "青春はそんなに血生臭くない！"
"10045020-36-シズコ" = "開幕早々大乱戦！百花繚乱の皆さんが狙われているようです！#nこの猛攻を耐え切れるのか〜っ！？"
"10045020-37-？？？" = "助けよ～"
"10045020-38-？？？" = "そうですね！これまでのご恩をお返しする時です！"
"10045020-39-？？？" = "ふふっ……では、行きましょうか？"
"10045020-40-スケバンリーダー" = "な、何だ！？"
"10045020-41-アラタ" = "あ、あれはっ……！？"
"10045020-42-イズナ" = "忍術研究部、助太刀いたします……！ニンニン！"
"10045020-43-ミモリ" = "私は忍術研究部ではないのですが……。"
"10045020-44-チセ" = "一緒に戦うよ～"
"10045020-45-スケバンリーダー" = "くっ、あいつらが合流するなんて……！"
"10045020-46-スケバンリーダー" = "みんな慌てるな！数はこっちが多い！！囲んで押しつぶせ！"
"10045020-47-百鬼夜行サークル部員A" = "ひ、百花繚乱の皆さん！私たちも力を貸します！"
"10045020-48-百鬼夜行サークル部員A" = "短い間だったけど……レンゲちゃんは同じ部活の仲間だから！"
"10045020-49-レンゲ" = "お前たち！"
"10045020-50-スケバンリーダー" = "くそっ……なんなんだよ……！？"
"10045020-51-レンゲ" = "これで形勢逆転ですの！"
"10045020-52-レンゲ" = "よーっし、みんな行くよ！一気に蹴散らしてやる！！"
