[translation]
"10045105-1-スケバンリーダー" = "ぐっ……！こんなところで……！"
"10045105-2-ワカモ" = "ふぅ……。"
"10045105-3-ワカモ" = "これでもう邪魔は入りません。"
"10045105-4-ワカモ" = "仕切り直すといたしましょう。"
"10045105-5-ワカモ" = "先生の御前で、誰が真の強者かを決めるのです。"
"10045105-6-シズコ" = "ま、待ってください！乱入は想定してなくて……！"
"10045105-7-ワカモ" = "罪人と呼ばれるこの身では、こういった催しに参加することは叶わぬ運命。"
"10045105-8-ワカモ" = "ですが……たとえ一瞬でも先生と同じ時を過ごし、喜びを感じたい。#nそれすらも許されないのでしょうか？"
"10045105-9-シズコ" = "そ、それは……。"
"10045105-10-ワカモ" = "おおおっ！災厄の狐が参加するのか！？"
"10045105-11-観客たち" = "こりゃ絶対見逃せないな！！"
"10045105-12-観客たち" = "やらせてやれー！"
"10045105-13-ワカモ" = "お客さんは大興奮……。"
"10045105-14-シズコ" = "……待てよ？これはもしかしたら、ビッグチャンスかも？"
"10045105-15-シズコ" = "……分かりましたっ！#n皆さんの声にお応えして……エキシビションマッチを行います！！"
"10045105-16-シズコ" = "わあああっ！！！"
"10045105-17" = "[ns] \"それじゃあ……押し出しゲームをしよう。\""
"10045105-18" = "[ns1] \"これで最強を決めるんだ。\"\n[ns2] \"ワカモもこのルールに従ってもらうよ。\""
"10045105-19-ワカモ" = "ええ、もちろんです。"
"10045105-20-ワカモ" = "このワカモ、喜んで従いましょう。"
"10045105-21-ワカモ" = "それが、あなた様に認めていただける方法であるならば。"
"10045105-22" = "[s] \"ワカモが納得してくれてよかった。\""
"10045105-23-ワカモ" = "うふふっ、決まりですね。では、どなたが私のお相手を？#n誰であろうと負ける気はいたしませんが……。"
"10045105-24-ワカモ" = "その相手なら――"
"10045105-25-レンゲ" = "ナグサ先輩が……。"
"10045105-26-キキョウ" = "……災厄の狐と？"
