[translation]
"1000806-1" = "遅刻大騒動"
"1000806-2" = "ミレニアム郊外・スラム街"
"1000806-3" = "……"
"1000806-4-チンピラ１" = "……。"
"1000806-5-チンピラ２" = "……。"
"1000806-6-チンピラ１" = "……聞いた？"
"1000806-7-チンピラ１" = "噂によれば……。"
"1000806-8-チンピラ１" = "[ruby=みかも]美甘[/ruby]ネル、度重なる遅刻と欠席で……。"
"1000806-9-チンピラ１" = "出席日数がもう、赤信号一歩手前らしい。"
"1000806-10-チンピラ２" = "へえ……と、いうことは……。"
"1000806-11-チンピラ１" = "これ以上遅刻や欠席をすれば留年、もしくは懲戒ってこと？"
"1000806-12-チンピラ１" = "理解が早いね。"
"1000806-13-チンピラ１" = "留年か懲戒にでもなれば……あのエージェント活動も公的に禁止されるよね？"
"1000806-14-チンピラ２" = "そう……まさにその通り。"
"1000806-15-チンピラ１" = "手段も方法も選ばない！どうにかしてネルを遅刻させる！"
"1000806-16" = "ミレニアム・通学路"
"1000806-17-ネル" = "よお、先生。おはよ。"
"1000806-18-ネル" = "あたしの出席日数のことが心配？"
"1000806-19-ネル" = "ははっ、ありがとよ。まあ、実のところあと一回遅刻したら懲戒……ってところでさ。"
"1000806-20-ネル" = "ちゃんと決まった時間に家を出てるのに、なぜか遅刻するんだよな。"
"1000806-21-ネル" = "今日も時間ギリギリだから、話すのは歩きながらにしようぜ。"
"1000806-22-ネル" = "今日は真面目に登校しねぇとな！"
"1000806-23" = "ミレニアム・通学路"
"1000806-24-謎のパティシエ" = "あっ、そこの先生とチビのメイドさ～ん。"
"1000806-25-謎のパティシエ" = "誰がチビだゴルァ！！"
"1000806-26-ネル" = "（ガチャッ！）"
"1000806-27-謎のパティシエ" = "ひいっ！す、すみません！"
"1000806-28-謎のパティシエ" = "うちの店で新メニューを準備したんですが、試食をお願いしたくて……。"
"1000806-29-ネル" = "へえ、試食か。まあちょうど今朝、家を出る時にちゃんと食べなかったってのはあるけど。"
"1000806-30-ネル" = "先生はどうだ？"
"1000806-31" = "[s] \"時間は大丈夫？\""
"1000806-32-ネル" = "すげぇギリギリだけど……まあ、試食ぐらいなら……。"
"1000806-33-ネル" = "……。"
"1000806-34-ネル" = "……いや、いいや。こんなところで道草食ってたら……せっかくの決心が崩れる。"
"1000806-35-ネル" = "悪いけど、今日はパス。"
"1000806-36-ネル" = "さあ、行こうぜ。先生。"
"1000806-37" = "……。"
"1000806-38-謎のパティシエ" = "ちっ！試食の中に下剤を入れておいたのに、引っ掛からないとは！"
"1000806-39-謎のパティシエ" = "次の手段だ！"
"1000806-40-謎の客引き" = "いらっしゃいませ！オープン特価イベントです！"
"1000806-41-謎の客引き" = "被るだけでものすごく強く見えるリーゼントウィッグが、今から5分間！90%オフの激安セール！！"
"1000806-42-ネル" = "……。"
"1000806-43-ネル" = "（や、やべぇ！リーゼントのウィッグだと？めちゃくちゃカッコいいじゃねぇか！）"
"1000806-44-ネル" = "（しかも90%オフ？よく分かんねぇけど、すげぇ安いってことだよな？）"
"1000806-45-ネル" = "さあ、そこのお客さん！このウィッグ、いかがですか？#nお客さんにとてもお似合いだと思いますよ！！"
"1000806-46-謎の客引き" = "そ、そうか……？"
"1000806-47-ネル" = "被るだけで根性が溢れ出る、この最新の流行アイテム！お店の中には、長さ別で色んな種類があります！#n1メートルのものもありますよ！"
"1000806-48-謎の客引き" = "い、1メートル……。"
"1000806-49-ネル" = "さあ、どうぞ中へ。いらっしゃいませ！このチャンスをお見逃しなく！"
"1000806-50-謎の客引き" = "うぅ……。"
"1000806-51" = "[s] \"時間は大丈夫？\""
"1000806-52-ネル" = "だ、大丈夫じゃねぇ！く、ぐううっ……！"
"1000806-53-ネル" = "……パス！早く行くぞ、先生！！"
"1000806-54" = "……。"
"1000806-55-チンピラ１" = "何故だ、何故中に入らないんだ？罠を用意していたというのに……。"
"1000806-56-謎の客引き" = "なかなか引っかからないな、次の手段に移ろう。"
"1000806-57-ネル" = "……。"
"1000806-58" = "[s] \"残念そうだね。\""
"1000806-59-ネル" = "……なあ。あそこの店員、さっき試食を勧めてたヤツじゃね？"
"1000806-60" = "[s1] \"そう？\"\n[s2] \"みんな似た顔だから分からない。\""
"1000806-61-ネル" = "ふーん……なんかおかしいな。"
"1000806-62-ネル" = "ふーん……なんかおかしいな。"
"1000806-63-チンピラ１" = "これからどうする？"
"1000806-64-チンピラ２" = "こうなったら、武装して突撃する。次の路地で襲撃！"
"1000806-65-チンピラ１" = "特攻？あのネルを相手に？#nあまり気分が乗らないな……。"
"1000806-66-チンピラ２" = "心配するな、私たちの目標はネルを倒すことじゃない。何とかして時間を稼ぐことだ！#n計算通りならネルの奴は1分後に、次の路地に到着するはずだ。"
"1000806-67-チンピラ２" = "そこで15分、やつを足止めできれば、ネルは確実に遅刻する！"
"1000806-68-チンピラ１" = "なるほど……そういうことなら、やってみるのもアリか。"
"1000806-69-チンピラ２" = "絶対に成功させる！"
"1000806-70" = "（タッタッタッ）"
"1000806-71-ネル" = "ちょっと、先生！遅れるぞ！もっと早く走れ！"
"1000806-72-チンピラ１" = "さあ、もうすぐ到着する。"
"1000806-73-チンピラ２" = "行こう！！襲撃！"
"1000806-74" = "（バッ！）"
"1000806-75-チンピラ１" = "美甘ネル、覚悟！！"
"1000806-76-チンピラ２" = "これまでよくも私たちの邪魔を……あれ？いない？！"
"1000806-77-チンピラ１" = "さ、さっきまでここにいたのに……。"
"1000806-78-ネル" = "やっぱりそうか。"
"1000806-79" = "え、うわっ！？"
"1000806-80-ネル" = "どっかで見たことある奴らだなと思ったら、この前あたしらにやられた不良どもだな？"
"1000806-81-ネル" = "あたしを遅刻させようとこそこそ企んでたわけか。"
"1000806-82-ネル" = "覚悟してもらおうか。"
"1000806-83-不良１&２" = "ひ、ひいっ！？"
"1000806-84" = "（ドカアアァァァァッン！）"
"1000806-85" = "ミレニアム本校舎・廊下"
"1000806-86-ネル" = "ふぅ……。"
"1000806-87-ネル" = "なんとかセーフか。ったく、登校するだけでこんな目に遭うとか。"
"1000806-88" = "[s] \"慌ただしい登校だったね。\""
"1000806-89-ネル" = "ははっ、そうだな。"
"1000806-90-ネル" = "これから遅刻には少し気を付けなきゃな。"
"1000806-91-ネル" = "一緒に登校してくれてありがとよ、先生。"
"1000806-92-ネル" = "じゃ、また後でな！"
"1000806-93" = "ネルは風のようなスピードで、教室の方へ消えていった。"
