[translation]
"90001280-1" = "第28話;ティファレト"
"90001280-2-アリス" = "せ、先生……何を考えているんですか……？"
"90001280-3-アリス" = "攻撃するなんて……この施設を建てた人に申し訳ないです。#nアリスは……そんなの嫌です……。"
"90001280-4-ケイ" = "それに、無理やりあの扉を破ろうとすれば――"
"90001280-5" = "――先ほどの録音、忘れたとは言わせませんよ？"
"90001280-6-ケイ" = "え？だからこそ……？#nそれはどういう……。"
"90001280-7-ケイ" = "まさか……！"
"90001280-8-アリス" = "け、ケイ？"
"90001280-9" = "（もし、先生の考えが正しければ……！）"
"90001280-10-ケイ" = "銃を持たずに、こんなことをする羽目になるなんて……！"
"90001280-11-ケイ" = "万一があったら恨みますからね、先生……。"
"90001280-12-ケイ" = "ティファレト！聞いているのでしょう？"
"90001280-13-ケイ" = "今から、あなたの種を奪いに行きます。"
"90001280-14-アイン" = "な、何を、しているのでしょうか……？"
"90001280-15-ソフ" = "訳わかんない……。"
"90001280-16-ソフ" = "きっとこういうのを、のれんに腕押しって言うんだろうね！"
"90001280-17-オウル" = "その言葉の意味は分かりませんが……。#n呼べばティファレトが反応するとでも思っているんですかね。"
"90001280-18-オウル" = "仮に扉が開いたとして、どうするつもりなんでしょう？#nまさか本当に種を持ち帰るつもりじゃないですよね。"
"90001280-19-オウル" = "これだから生命体は理解できません。#n自分が何をしているのか、どんな結果をもたらすのかさえ――"
"90001280-20-ソフ" = "！？！？"
"90001280-21-ソフ" = "アイン、これは！？"
"90001280-22-アイン" = "ティ、ティファちゃんからメッセージです……！"
"90001280-23-アイン" = "「第2貯蔵庫への危険行動を検知」"
"90001280-24-アイン" = "「リソースの再配分を実行」"
"90001280-25-アイン" = "「施設の全動力を――第2貯蔵庫の防衛に割り当てる」……！？！？"
"90001280-26-ソフ" = "待機タスクは……隔壁の設置、第2貯蔵庫内部の温度と湿度の再調整……。"
"90001280-27-オウル" = "第3区域へのガスの排出を停止！？"
"90001280-28-ケイ" = "くっ……！？"
"90001280-29-ケイ" = "危うく私までショートするところでしたが――"
"90001280-30-ケイ" = "やはり、ガスの排出は止まりましたね。先生の読み通りですか。"
"90001280-31" = "[ns] \"よくやったよ、ケイ！\""
"90001280-32-ケイ" = "……。"
"90001280-33-ケイ" = "ま、まあ……この程度は。"
"90001280-34-ケイ" = "あれ？……アリス、ちょっとずつ回復してきた気がします！"
"90001280-35-ケイ" = "！！！"
"90001280-36-ケイ" = "みんなが目を覚ましました！"
"90001280-37-モモイ" = "むにゃむにゃ……あと5分……。"
"90001280-38-ユズ" = "あれ……先生？#nアリスちゃん……？"
"90001280-39-リオ" = "私は、なぜこんなところで寝て……？"
"90001280-40-ヒマリ" = "あら、先ほどまでの景色は……？"
"90001280-41-トキ" = "とても気持ちよく眠れました。快眠です。#nなので――"
"90001280-42-トキ" = "[ruby=あすま]飛鳥馬[/ruby]トキ、[ruby=パーフェクトモード]完全無敵状態[/ruby]になりました。"
"90001280-43-ミドリ" = "……先生！先生は大丈夫ですか？#nさっき急に意識が飛んだような……。"
"90001280-44-アリス" = "ぱんぱかぱーん！パーティー全員が完全復活しました！"
"90001280-45" = "[ns] \"みんな無事で良かった。早速だけど状況を説明するね。\""
"90001280-46-ソフ" = "……ごめん、みんな。"
"90001280-47-ソフ" = "私のせいだ……。"
"90001280-48-ソフ" = "ティファレトの言う通りにしたから……。"
"90001280-49-ソフ" = "ううっ……！"
"90001280-50-オウル" = "……。"
"90001280-51-オウル" = "ソフ！！"
"90001280-52-アイン" = "きゃうっ！？"
"90001280-53-ソフ" = "オウル……！？"
"90001280-54-オウル" = "なんですか、らしくない。#nまだ終わったわけではありませんよ。"
"90001280-55-オウル" = "みんな、あなたのことを信じています。アインも、お姉様も、ティファレトも。#n……私だって。"
"90001280-56-オウル" = "他の預言者の意見は知りませんが……。#nまあ、彼らも一応、信じているはずです。"
"90001280-57-ソフ" = "一応……。"
"90001280-58-オウル" = "なにより、ソフがそんなこと言ったら、ティファレトの意志はどうなるんですか？"
"90001280-59-ソフ" = "でも……。"
"90001280-60-アイン" = "い、今はできることを、やれば良いと……思います。"
"90001280-61-アイン" = "み、みんなで協力して……姉妹は、助け合うもの、ですから……！"
"90001280-62-ソフ" = "ええ、その通りです、アイン。#nよくできました、花丸です。"
"90001280-63-ソフ" = "調和とは、全員が同じ形になることではありません。#nそれではもはや、強要や暴力に近しい概念になってしまいますから。"
"90001280-64-ソフ" = "各々の得手不得手を補い合う――それが真の調和なのです。"
"90001280-65-ソフ" = "互いを尊重できないのであれば、前へ進むことはできません。"
"90001280-66-マルクト" = "だからこそ、一人の責任は皆の責任であり、皆の幸せは一人の幸せでもあるのです。"
"90001280-67-ソフ" = "お姉様……。"
"90001280-68-ソフ" = "ううっ……！"
"90001280-69-マルクト" = "独りで強くなれる者などいません。#n生命体であれ、意識体であれ。"
"90001280-70-マルクト" = "誰かが苦難に見舞われたのであれば、我々は手を差し伸べるのです。"
"90001280-71-マルクト" = "罪を憎んで、人を憎まず。"
"90001280-72-マルクト" = "過失を咎めるのではなく、過失が起こらない仕組みを一緒に考えましょう。"
"90001280-73-マルクト" = "ですからアイン、まずはティファレトと話をしてくれませんか？"
"90001280-74-アイン" = "は、はい！お姉様！"
"90001280-75-アイン" = "ティファちゃん……聞いてもらえますか……？"
"90001280-76-マルクト" = "あの人たちは、ティファちゃんの種を奪うふりをしているだけ――"
"90001280-77-アイン" = "ティファちゃんを騙そうとする、意地悪な人たちなんです……！"
"90001280-78-アイン" = "なので……過剰なリソースを防衛にまわす必要はありません。"
"90001280-79-アイン" = "でも、意地悪なあの人たちは何をしでかすか分からないので……。"
"90001280-80-アイン" = "ティファちゃん。#n大切な種を守るためにも……あの人たちを――"
"90001280-81-アイン" = "丁重に、追い出してください……！"
"90001280-82" = "わ、私たちも、お手伝いしますので……。"
"90001280-83-オウル" = "どうやら、分かってくれたようですね。後は任せるとしましょう。#nもう大丈夫ですよ、ソフ。"
"90001280-84-ソフ" = "うん……みんな、ありがとう。"
"90001280-85-オウル" = "いつまでもソフの元気がないと調子が狂いますね……。#n生きていれば、こんな日もあるでしょう？"
"90001280-86-アイン" = "お、オウル……今の、なんか人間っぽかったです……えへへ。"
"90001280-87-オウル" = "ぐはっ！？"
"90001280-88-ソフ" = "そう、だね……うん……よっし！#nそしたら……念のために、他の準備もしていいかな？"
"90001280-89-オウル" = "準備？"
"90001280-90-アイン" = "なんの話、ですか？"
"90001280-91-アイン" = "そ、それは……！"
"90001280-92-ソフ" = "今の私が言うのも気が引けるんだけど……。"
"90001280-93-オウル" = "……。"
"90001280-94-オウル" = "まあ、その時はその時ではありませんか？"
"90001280-95-アイン" = "良いんですか……！？！？"
"90001280-96-ソフ" = "だって……ソフが言った通りですから。"
"90001280-97-オウル" = "「ティファレトを鋼鉄大陸に後退させる案も視野にいれる」と。"
"90001280-98-オウル" = "戦力温存のためにも、妥当な手だとは思いますよ。"
"90001280-99-アイン" = "あっ……そ、そういえば、その判断をするのは私の担当でしたよね……！#nご、ごめんなさい、ソフ……！"
"90001280-100-ソフ" = "ううん、悪いのは私のほうだし……。"
"90001280-101-オウル" = "えっと……お互い謝りあうのはもうやめにしましょう。#n話が前に進みませんし。"
"90001280-102-オウル" = "それに、不測の事態に備えてきたわけですから。想定の範疇で、起こりうることです。#nもちろん、そうならないのがベストではありますが。"
"90001280-103-ソフ" = "……ありがとう、みんな。"
"90001280-104-ソフ" = "みんながいてくれて、本当に……良かった。"
"90001280-105-アイン" = "えへへ……。"
"90001280-106-オウル" = "て、照れくさいこと言ってないで、そろそろ始めますよ！"
"90001280-107-オウル" = "ティファレトの本気を……お見せする時です！"
"90001280-108-ヒマリ" = "今度は何ですか！？"
"90001280-109-リオ" = "これは……新しい預言者「ティファレト」の信号……？"
"90001280-110-リオ" = "……っ！！離れるわよ！急いで！"
"90001280-111-トキ" = "私が道を確保します！"
"90001280-112-トキ" = "先生、こっち！"
"90001280-113" = "[ns] \"みんな、気を付けて！\""
