[translation]
"90001140-1" = "第14話;合流"
"90001140-2-エイミ" = "あれ、先生どうしたの？"
"90001140-3" = "[s] \"そろそろリオが来る時間だなと思って。\""
"90001140-4-トキ" = "あと5分後ですね。"
"90001140-5-トキ" = "おそらくリオ様は――"
"90001140-6-トキ" = "1秒も遅れることなく、正確に到着するかと。"
"90001140-7-ヒマリ" = "ごく稀に、1分早く着くこともありますが。"
"90001140-8" = "[s] \"ヒマリ、寒くない？\""
"90001140-9-ヒマリ" = "ええ。寒いです、とても。崖の上に咲いた一輪の清楚な花に、夜明けの霜が当たるかのように！"
"90001140-10-ヒマリ" = "ですが、中で待つという選択肢はありません。"
"90001140-11-ヒマリ" = "私に面倒事を押しつけて勝手に姿を消したリオが、ようやく顔を出すのですから。"
"90001140-12-ヒマリ" = "出迎えて文句の一つでも言わなければ、と思いまして。"
"90001140-13-ヒマリ" = "そうでないと落ち着かないんですよ。もう！"
"90001140-14-エイミ" = "……早く会いたいって素直に言えば良いのに。"
"90001140-15-ヒマリ" = "誤解です。本当に勘違いしないでくださいね？"
"90001140-16-ヒマリ" = "これだけ一緒に過ごしているのに、まだ私のことを理解できていないのですか！？"
"90001140-17-エイミ" = "（よく分かってるから言ってるんだけど……）"
"90001140-18-トキ" = "……お二人の間には色々あったのですね。"
"90001140-19-トキ" = "もちろん、私は途中から合流した身ではありますが……。"
"90001140-20-トキ" = "私だって、負けていない自信があります。むん。"
"90001140-21" = "[s] \"すごい自信だね。\""
"90001140-22-トキ" = "こういう時は、気合いで何とかなると教わってきましたので。"
"90001140-23-エイミ" = "誰に？"
"90001140-24-トキ" = "モモイに。"
"90001140-25-エイミ" = "ああ、なるほど。"
"90001140-26-ヒマリ" = "リオがそんなこと言うはずないと思っていましたが……。#nああ、そういえば特異現象捜査部は彼女の頼みで始めた部活でしたね。"
"90001140-27-ヒマリ" = "リオ、特異現象捜査部……デカグラマトン"
"90001140-28-ヒマリ" = "『神を研究し、その存在を証明できれば……その構造を分析し、再現できるだろう。#n　すなわちこれは、新たな神を創り出す方法である……』。"
"90001140-29-ヒマリ" = "その仮説を元に作られた、対・絶対者自律型分析システム。"
"90001140-30-ヒマリ" = "つまるところ、「神性を探し出す人工知能」。"
"90001140-31-エイミ" = "最初は部長と私の二人だけだったね。"
"90001140-32-ヒマリ" = "そして、エイミが先生を連れてきてくれました。"
"90001140-33-エイミ" = "砂漠から始まって工場、廃墟……ついには氷河かぁ。"
"90001140-34-トキ" = "じっとしているのは退屈です……手が凍えてしまいそうです。"
"90001140-35" = "[s] \"おいで、トキ。温めてあげる。\""
"90001140-36-トキ" = "……ありがとうございます。"
"90001140-37-エイミ" = "あ、ズルい。私も。"
"90001140-38-ヒマリ" = "あなた達、何やってるんですか……。"
"90001140-39-ヒマリ" = "はぁ……一体リオはいつ来るのでしょうか。"
"90001140-40-ヒマリ" = "ありきたりな回想に浸るだなんて、超天才清楚系病弱美少女ハッカーの私には似合いませんし、時間の無駄ですから。"
"90001140-41-ヒマリ" = "そんな暇があるのなら、少しでも調査を進めたいのですが……。"
"90001140-42-トキ" = "ああ、ようやくお出ましのようですね。"
"90001140-43-ヒマリ" = "……？"
"90001140-44-ヒマリ" = "……。"
"90001140-45-リオ" = "……。"
"90001140-46-エイミ" = "……。"
"90001140-47-トキ" = "？"
"90001140-48-ヒマリ" = "なんですか、その乗り物……？"
"90001140-49-リオ" = "大したものじゃないわ。"
"90001140-50-リオ" = "まだ改良の余地が残っているし、もう少しまともなものを用意したかったのだけれど。"
"90001140-51-ヒマリ" = "あなたなりに準備をしてきてくれたのだと受け取りましょう。"
"90001140-52" = "[s] \"来てくれてありがとう、リオ。\""
"90001140-53-リオ" = "先生……。"
"90001140-54-リオ" = "その、私は……。"
"90001140-55-トキ" = "ようこそ、リオ様。#n5分前からお待ちしておりました。"
"90001140-56-リオ" = "トキ……。"
"90001140-57-リオ" = "……やりたいことは見つかった？"
"90001140-58-トキ" = "やりたいこと、ですか。"
"90001140-59-トキ" = "私は……。"
"90001140-60-リオ" = "答えにくいのであれば結構よ。"
"90001140-61-リオ" = "今の貴女を見ていれば、何となく分かるもの。"
"90001140-62-トキ" = "そうですか？"
"90001140-63-リオ" = "ええ。それと、改めて言わせてちょうだい。"
"90001140-64-リオ" = "……ごめんなさい、トキ。#n貴女に負担をかけすぎたわ。"
"90001140-65-トキ" = "え……？"
"90001140-66-エイミ" = "変わったね、会長。"
"90001140-67" = "[s] \"……胸がじーんとする。\""
"90001140-68-リオ" = "先生……。"
"90001140-69-リオ" = "あまりからかわないでほしいのだけれど。"
"90001140-70-リオ" = "……何かしら？"
"90001140-71" = "[s] \"今から、大切な事を話すね。\""
"90001140-72-リオ" = "もしかして、明日世界が滅亡でもするのかしら？"
"90001140-73" = "[s] \"そこまではいかないけど……。\""
"90001140-74" = "[ns] \"ゲーム開発部の子たちが、もうすぐここに来るよ。\""
"90001140-75-リオ" = "……？"
"90001140-76-リオ" = "……！"
"90001140-77-リオ" = "いっそ世界が滅亡する方がマシなのだけれど！？"
"90001140-78-ヒマリ" = "エイミ、トキ！"
"90001140-79-エイミ" = "うん！"
"90001140-80-トキ" = "対応します。"
"90001140-81-リオ" = "帰らせてもらうわ！"
"90001140-82-リオ" = "トキ、貴女まで私に逆らうの！？"
"90001140-83-トキ" = "申し訳ありません、リオ様。これが私のやりたいことですので。"
"90001140-84-リオ" = "さっきのはそういう意味だったのかしら！？"
"90001140-85-リオ" = "到着は明日だと聞いていたのだけれど……！"
"90001140-86-ヒマリ" = "今日も明日も、大差ありませんよ。"
"90001140-87-リオ" = "心の準備が必要なのよ。事前連絡もなく予定を前倒しするなんて、非合理的な決定すぎるわ！"
"90001140-88-ヒマリ" = "占星術の結果によると、この時間のほうが縁起が良いそうですので。"
"90001140-89-リオ" = "まだ星占いなんて無意味なものを信じているのかしら？"
"90001140-90-ヒマリ" = "いつも言っておりますが、占星術は古代から続く天体と人間の出来事にまつわる統計学と――"
"90001140-91-ヒマリ" = "運命を決めるのは定数なのか変数なのかという哲学と数学と物理学……それらすべてが集約された一つの学問なのですよ？"
"90001140-92-リオ" = "どうでも良いわよ！"
"90001140-93-リオ" = "はぁ、はぁ、はぁ……。"
"90001140-94" = "[s] \"……大丈夫？\""
"90001140-95-リオ" = "……大丈夫に見えるのかしら。"
"90001140-96-リオ" = "もちろん、償うつもりはあるのだけれど……。"
"90001140-97-リオ" = "でも、こんな仕打ちをするなんて……。"
"90001140-98" = "（リオに恨めしい視線を向けられた）"
"90001140-99" = "（ちゃんと連絡すればよかったな……）"
"90001140-100-トキ" = "あ、きましたね。"
"90001140-101-エイミ" = "良いタイミング。"
"90001140-102-ヒマリ" = "さあ、観念してくださいリオ。"
"90001140-103-リオ" = "……！"
"90001140-104" = "（ヘリが到着した）"
"90001140-105" = "（真っ先に飛び出してきたのは……！）"
"90001140-106-アリス" = "先生！"
"90001140-107" = "[ns] \"アリス！\""
"90001140-108" = "（アリスは全力で抱きついてきた！）"
"90001140-109" = "（先生は転びそうになった！）"
"90001140-110-アリス" = "先生、会いたかったです！"
"90001140-111-トキ" = "お久しぶりです、可愛いアリス。"
"90001140-112-アリス" = "トキ、お久しぶりです！"
"90001140-113-エイミ" = "久しぶり、アリス。"
"90001140-114-アリス" = "エイミ、その格好は寒くありませんか？"
"90001140-115-エイミ" = "全然、むしろ涼しくてちょうど良いくらい。"
"90001140-116-アリス" = "そ、それなら良いのですが……。"
"90001140-117-ヒマリ" = "ようこそ、アリス。そしてゲーム開発部の皆さん。"
"90001140-118-アリス" = "ヒマリ先輩！#n黄色いジャケットも似合ってます！"
"90001140-119-ヒマリ" = "あら、ありがとうございます。#nやはりアリスは可愛げのある後輩ですね。"
"90001140-120-モモイ" = "やっほ～来たよ、先生！"
"90001140-121-モモイ" = "他のみんなも、なんか久しぶりだね……。"
"90001140-122-ミドリ" = "こんにちは、先生……ここまですごく……大変でした。"
"90001140-123-ミドリ" = "楽しい列車旅かと思ってたら、何度も乗り換えて、最後はヘリ……。"
"90001140-124-ミドリ" = "……まさか、三日もかかるなんて思ってませんでした。"
"90001140-125-ユズ" = "ゲームで長距離移動してる時ってこんな感じなのかな……。"
"90001140-126-ユズ" = "くしゅん！"
"90001140-127" = "[s] \"大丈夫？\""
"90001140-128-ユズ" = "はい、大丈夫です……ううぅ、仰っていた通り、本当に寒いですね。"
"90001140-129" = "[s] \"ちゃんと暖かい服装で来てくれたんだね！\""
"90001140-130-アリス" = "はい！ミドリが選んでくれました。#nいま作ってるゲームの装備に近いデザインなんです！"
"90001140-131-モモイ" = "氷河を舞台にしたアクションRPG・パズルアドベンチャー・ターン制シューティングゲームだよ！"
"90001140-132" = "[s] \"……ゲーム要素、ちゃんとまとまってる？\""
"90001140-133-モモイ" = "も、も、もちろんだよ！#n私たちを誰だと思ってるの！"
"90001140-134" = "はぁ……。"
"90001140-135-ヒマリ" = "さあ、そろそろ中に入りましょうか……と、その前に。"
"90001140-136-ヒマリ" = "最後の一人を……。"
"90001140-137-小型AMAS" = "こん、にちは。私はこの氷河基地の演算支援A.I.です。#nここまでお越しくださり、ありがとうございます。"
"90001140-138-トキ" = "……。"
"90001140-139-エイミ" = "……。"
"90001140-140-ヒマリ" = "本当に……。"
"90001140-141-モモイ" = "A.I.って、ゲームに出てくる人類を滅ぼそうとする悪役によくいるよね？"
"90001140-142-ミドリ" = "お姉ちゃん、いくら何でもその言い方は……。"
"90001140-143-モモイ" = "だってそうじゃない？"
"90001140-144-モモイ" = "巨大変身怪獣の親玉が何か企んでそうって話なんだよね？"
"90001140-145-ユズ" = "たしかに……？"
"90001140-146-ヒマリ" = "いえ……なんと説明すれば良いのでしょう。"
"90001140-147-小型AMAS" = "私は貴女たちの手助けのために作られましたので、警戒しないでくださ――"
"90001140-148-アリス" = "リオ先輩！リオ先輩ですね？"
"90001140-149-ミドリ" = "ええ！？もしかしてまた……！？"
"90001140-150-ミドリ" = "リオ会長、まさか……。"
"90001140-151-ユズ" = "ドッキリ……？"
"90001140-152-アリス" = "わ、私は[ruby=つかつき]調月[/ruby]リオとは関係なく……。"
"90001140-153-アリス" = "また会えて嬉しいです、リオ先輩。#nお元気でしたか？"
"90001140-154-小型AMAS" = "……。"
"90001140-155-アリス" = "アリスはリオ先輩の顔が見たいです。#nあの時のように、通信でも構いません。"
"90001140-156-小型AMAS" = "それは……。"
"90001140-157-アリス" = "大丈夫です、色々な事情があるのは分かっていますから。"
"90001140-158-小型AMAS" = "……！"
"90001140-159-アリス" = "でも、やっぱり残念です。#nもしかしたらリオ先輩に会えるかもしれないと期待してしまいました。"
"90001140-160-小型AMAS" = "うっ……！"
"90001140-161" = "[ns] \"ちょっと待って！\""
"90001140-162-アリス" = "え……？"
"90001140-163-リオ" = "せ、先生……。"
"90001140-164" = "[ns] \"行こう、リオ。\""
"90001140-165-リオ" = "で、でも……！"
"90001140-166" = "[s1] \"大丈夫、私が一緒にいるから。\"\n[s2] \"勇気を出して、リオ。\""
"90001140-167-リオ" = "……！"
"90001140-168-リオ" = "わ、分かったから……。"
"90001140-169" = "（リオの手を掴んで外に連れ出す）"
"90001140-170" = "（幸い、素直についてきてくれた）"
"90001140-171-モモイ" = "あっ、リオ会長だ！"
"90001140-172-ミドリ" = "だから、お姉ちゃん……。"
"90001140-173-ミドリ" = "……こんにちは、リオ会長。お久しぶりです。"
"90001140-174-ユズ" = "あうぅ……えっと……こん、にちは。リオ会長。"
"90001140-175-アリス" = "リオ先輩！"
"90001140-176-リオ" = "っ……！？"
"90001140-177-トキ" = "良かったですね、リオ様。"
"90001140-178-トキ" = "可愛いアリスの頭を撫でるチャンスですよ。"
"90001140-179-リオ" = "そ、そうなのかしら……？"
"90001140-180-トキ" = "アリスのことだけ「可愛いアリス」って呼ぶんだ？"
"90001140-181-トキ" = "分かりました。#nでは、「騒がしいモモイ」とお呼びしましょう。"
"90001140-182-モモイ" = "普通でいいです……。"
"90001140-183-モモイ" = "ねえ、会長。#n一つ確認したいんだけど……。"
"90001140-184-モモイ" = "また、世界のために誰かを犠牲にしないといけなくなったら……今度はどうするの？"
"90001140-185-リオ" = "……。"
"90001140-186-ユズ" = "お、お姉ちゃん……？"
"90001140-187-ユズ" = "モモイ……。"
"90001140-188-モモイ" = "私は後で事情を聞いただけだから、改めて聞いておこうと思って。"
"90001140-189-モモイ" = "な、なんでそんな目で見るの！？#nゲームでも、忘れた頃に前の話題が掘り起こされるものでしょ！？"
"90001140-190-モモイ" = "会長が何をしようとしてるのか知らないけどさ……。"
"90001140-191-モモイ" = "同じ問題が起きた時どうするのか、聞いておいた方がいいと思って。"
"90001140-192-リオ" = "……。"
"90001140-193-ミドリ" = "お姉ちゃん、もうちょっと言い方を……。"
"90001140-194-モモイ" = "だって、私は気を失ってたからよく知らないんだもん！"
"90001140-195-モモイ" = "あれ、ちょっと待って……あの時私を攻撃したのってアリス……？"
"90001140-196-モモイ" = "でも、あれはケイで……うーん？何がどうなってるの？"
"90001140-197-アリス" = "うぅ、ごめんなさい！全部、アリスのせいです！"
"90001140-198-ユズ" = "だ、大丈夫だよ……！#nもう終わったことだし、こうしてみんな集まってるんだから……！"
"90001140-199-リオ" = "……。"
"90001140-200-モモイ" = "ゲームでさ、よくある話なんだけど……。"
"90001140-201-モモイ" = "みんなのために一人を犠牲にすべきだって主張する人に限って、いざ自分がその立場になったら逃げちゃうんだよね。"
"90001140-202-モモイ" = "でも、会長はそうじゃなかった。"
"90001140-203-AMAS A" = "今からこの都市自体が変貌し、箱舟という新しい概念に歪曲される。#nそうしたら……このキヴォトスは……。"
"90001140-204-AMAS A" = "私のせいよ……。"
"90001140-205-AMAS A" = "私がこの都市を作らなかったら、最初からこんな事にならなかったのに……。"
"90001140-206-AMAS A" = "だから私が、止めないと……。"
"90001140-207-ユズ" = "ど、どういう意味ですか……？"
"90001140-208-AMAS A" = "……私一人で、システムを止めてみせるわ。"
"90001140-209-AMAS A" = "私の命一つで……世界の終焉を防ぐことができるというのなら#nそうするわ――そうしなければならない。"
"90001140-210-リオ" = "そうしなければならないと思っているもの……たとえ、それが自分であろうとも。"
"90001140-211-モモイ" = "うん。だから、会長の意思を聞きたいんだ。"
"90001140-212-モモイ" = "――大事な問題だから。"
"90001140-213-リオ" = "私の命で世界の終焉を防ぐことができるのなら、今でもそうすべきだと思うわ。#nでも……。"
"90001140-214-リオ" = "他の誰かを犠牲にする必要があるのなら……。"
"90001140-215-リオ" = "限界まで、別の解決策を模索するわ。"
"90001140-216-ヒマリ" = "……。"
"90001140-217-リオ" = "いつも、最初に出た結論が合理的だと信じてきた。"
"90001140-218-リオ" = "でも、可能性が残されているのなら、諦めるつもりはない。"
"90001140-219-リオ" = "……取り返しがつかなくなってからでは、遅いもの。"
"90001140-220-アリス" = "ダメです、リオ先輩。"
"90001140-221-リオ" = "あ、アリス……？"
"90001140-222-アリス" = "アリスたちのことを考えてくれるのは嬉しいです。#nでも、その対象にリオ先輩が入っていないのは……。"
"90001140-223-アリス" = "とても、悲しいです。"
"90001140-224-リオ" = "私は……。"
"90001140-225-アリス" = "アリスは、リオ先輩にもチャンスがあってほしいです。"
"90001140-226-アリス" = "どんなに難しいゲームでも、2回目には上達していますから！"
"90001140-227-ヒマリ" = "良い例えですね、アリス。"
"90001140-228-アリス" = "……。"
"90001140-229-アリス" = "だからリオ先輩、アリスは……。"
"90001140-230-アリス" = "アリスは……うぅ！"
"90001140-231-アリス" = "うまく言葉が出てきません……アリスの言語能力に問題が起きたのでしょうか！？"
"90001140-232-ミドリ" = "大丈夫だよ、アリスちゃん。#n気持ちを伝えるのって、難しいよね。"
"90001140-233-ユズ" = "なんだか……こうして話せるようになって、よかった。"
"90001140-234" = "[s3] \"久しぶりに、胸がジーンとする光景を見ている……。\"\n[s4] \"って、さっきも言った気がする。\""
"90001140-235-ユズ" = "どうしたんですか、先生……？"
"90001140-236-リオ" = "……。"
"90001140-237-エイミ" = "それで……お互い言いたいことは言い終わった感じかな？"
"90001140-238-エイミ" = "そろそろ本題に入ろう。ヒマリ部長が凍っちゃう。"
"90001140-239-トキ" = "リオ様に悪気はないのです。そういう方なので。#n代わりに私が謝罪します。"
"90001140-240-ヒマリ" = "その言い方ではリオの立場が……。"
"90001140-241-リオ" = "私がこういう会話に慣れていないのは事実よ。それは否定しないわ。"
"90001140-242-ヒマリ" = "あっ、はい……そうですね、忘れていました。"
"90001140-243-ヒマリ" = "はぁ……調子が狂います。#n早く慣れたいものですが……。"
"90001140-244" = "[s] \"……お疲れ様、ヒマリ。\""
"90001140-245-ヒマリ" = "先生がいてくださって、本当に良かったです……。"
"90001140-246-リオ" = "私はたくさんの過ちを犯した……それは事実。"
"90001140-247-リオ" = "もし、また間違ってしまった時は、教えてちょうだい。"
"90001140-248-リオ" = "その時は可能な限り、最善を尽くすわ。"
"90001140-249-ヒマリ" = "（普通に最善を尽くす、だけで良い気がするけど……）"
"90001140-250-ヒマリ" = "（リオにしては目覚ましい成長ですね）"
"90001140-251-アリス" = "それで……どうしてアリスたちをここまで呼んだのですか？"
"90001140-252-ミドリ" = "そうですよ。しかもすごく迂回してきたし……。"
"90001140-253-リオ" = "それは……。"
"90001140-254" = "[s] \"……その話もしないとね。\""
"90001140-255-ヒマリ" = "せっかく集まったわけですし、ゆっくり話しましょうか。"
"90001140-256-ヒマリ" = "気になったことがあれば、いつでも質問してくださって構いませんよ？#n長くなるかもしれませんから、飴ちゃんでも舐めますか？"
"90001140-257-モモイ" = "飴ちゃんって……ヒマリ先輩ちょっとそれは……。"
"90001140-258-ミドリ" = "しーっ、お姉ちゃん！善意を無駄にしないの！"
"90001140-259" = "次回;雪合戦"
