[translation]
"90001170-1" = "第17話;再会"
"90001170-2-エイミ" = "……それで、あなたを再び起こしたの。"
"90001170-3-トキ" = "はい。特にリオ様の功績が大きいかと。"
"90001170-4-トキ" = "ふんす、2番目に頑張ったのはリオ様の言葉に従った私です。"
"90001170-5-ヒマリ" = "貴女がそこまで言うと、みんなの立場が少し心配になりますが……。"
"90001170-6-ヒマリ" = "トキは何か間違ったことでも言ったかしら？#n正しいと思うのだけれど……。"
"90001170-7-ケイ" = "みなさん、私が眠りについた時とあまり変わっていないようですね……。"
"90001170-8" = "[s1] \"えっと……こんにちは、ケイちゃん。\"\n[s2] \"あの時以来だよね？\""
"90001170-9-ケイ" = "ケイちゃん！？"
"90001170-10-ケイ" = "というか、ここはどこですか？#nキヴォトスの環境を全て把握しているわけではありませんが……。"
"90001170-11-ケイ" = "……どこか異質な感じがします。"
"90001170-12-ケイ" = "ここは氷河よ。"
"90001170-13-ケイ" = "なぜこんなところに……？"
"90001170-14-ヒマリ" = "理由については後ほど。"
"90001170-15-ヒマリ" = "まずは自己紹介からしましょうか？#n私とリオのことは、すでに知っているとは思いますが。"
"90001170-16-ケイ" = "は、はい……。"
"90001170-17-ヒマリ" = "はじめまして。私は[ruby=あすま]飛鳥馬[/ruby]トキと申します。"
"90001170-18-トキ" = "あなたとアリスを拉致したこともあります。ピース、ピース。"
"90001170-19-トキ" = "それ、自己紹介なんですか？"
"90001170-20-ケイ" = "私は[ruby=いずみもと]和泉元[/ruby]エイミ、よろしくね。"
"90001170-21-ケイ" = "……こんにちは。#nえっと……はじめまして、ケイです。"
"90001170-22-ケイ" = "本当は、違う名前ですが……。"
"90001170-23-ケイ" = "……王女が、そう呼ぶので。"
"90001170-24-ケイ" = "私のデータを保管してくださって、ありがとうございました。"
"90001170-25-ケイ" = "キーホルダーの中はよく揺れましたが……。"
"90001170-26-ケイ" = "うっ。モップの先につけられて、粗雑に扱われていたような……。"
"90001170-27" = "[s] \"そ、それは何かの誤解じゃないかな……？\""
"90001170-28-ケイ" = "もっとマシな言い訳をしてください……。"
"90001170-29-ケイ" = "あなたたちのことは多少知っています。"
"90001170-30-ケイ" = "王女から情報を共有してもらっていたので。#nですが、私に関する情報は……。"
"90001170-31-ヒマリ" = "それは、これから知っていけば良いではありませんか。"
"90001170-32-ケイ" = "……そうですね。"
"90001170-33-ケイ" = "そういえば、王女はどちらに？"
"90001170-34" = "[s3] \"そうだ、それなんだけど……。\"\n[s4] \"ケイちゃんに紹介したい子がいるんだ。\""
"90001170-35-ケイ" = "ケイちゃん呼びをやめてほしいのですが……。"
"90001170-36-ケイ" = "はぁ……何でもありません。[USERNAME]先生は、こういう人でしたね。"
"90001170-37-ケイ" = "その顔やめてください……。"
"90001170-38-ケイ" = "それで、紹介したい方々というのは？"
"90001170-39" = "[ns] \"えっと……。\""
"90001170-40-モモイ" = "あれ、先生からモモトーク？"
"90001170-41-モモイ" = "……みんな！"
"90001170-42-モモイ" = "そろそろ戻ろう！"
"90001170-43-モモイ" = "え、もう？"
"90001170-44-アリス" = "そうですよ、モモイ！#nアリスはもっと遊びたいです！"
"90001170-45-ユズ" = "わ、わたしは、もう疲れた……。"
"90001170-46-モモイ" = "ほら、ユズも疲れたって言ってるじゃん。#n戻ったら、先生がココアを作ってくれるって！"
"90001170-47-アリス" = "先生のココア……？#nそれはレアアイテムですね！戻ります！"
"90001170-48-モモイ" = "でしょ？#n早く行こう！"
"90001170-49-ミドリ" = "えっ。ずるいよ、お姉ちゃん！待って！ほら、ユズちゃんも早く！"
"90001170-50-ユズ" = "ココア……美味しそう。"
"90001170-51-モモイ" = "先生、ただいま！"
"90001170-52-アリス" = "もっと遊びたかったですが、回復も大事ですから！"
"90001170-53" = "[s] \"おかえり。はい、冷めないうちに飲んでね。\""
"90001170-54-ミドリ" = "ありがとうございます、先生。#nわぁ、良い香りがします。"
"90001170-55-ユズ" = "先生はコーヒーなんですね。#nそれなのに、わざわざココアを……ありがとうございます。"
"90001170-56-モモイ" = "はぁ～美味しい。"
"90001170-57-モモイ" = "それじゃ……アリス、先に入る？"
"90001170-58-アリス" = "うん？急にどうしたんですか……？"
"90001170-59-モモイ" = "アリスが一番に会った方がいいかなって。"
"90001170-60-ミドリ" = "アリスちゃんが一番に……？"
"90001170-61-ミドリ" = "もしかして……！"
"90001170-62-ユズ" = "……。"
"90001170-63-アリス" = "……？"
"90001170-64-アリス" = "……！"
"90001170-65-アリス" = "ま、まさか……！"
"90001170-66" = "[s] \"その、まさかかも。\""
"90001170-67-アリス" = "その……先生も一緒に行ってほしいです……。"
"90001170-68-アリス" = "それと……。"
"90001170-69-アリス" = "アリスの手を、しっかり握っていてください。"
"90001170-70-アリス" = "アリスは今、体が震えて……まっすぐ立っているのも難しくて。"
"90001170-71-アリス" = "……ありがとうございます、先生。"
"90001170-72-アリス" = "……！"
"90001170-73-ケイ" = "……！"
"90001170-74-アリス" = "…………。"
"90001170-75-ケイ" = "………………。"
"90001170-76-アリス" = "け……ケイ、ですか？"
"90001170-77-ケイ" = "王女……。"
"90001170-78-アリス" = "ほんとうに……ケイ、なんですね……。"
"90001170-79-ケイ" = "王女よ、私は……。"
"90001170-80-アリス" = "ケイ！"
"90001170-81-アリス" = "消えるべき存在だなんて、二度と言わないでください。"
"90001170-82-アリス" = "正しいとか、正しくないとか、そんなものは関係ありません。"
"90001170-83-ケイ" = "それは……。"
"90001170-84-アリス" = "お願いです。#nアリスは今、言葉にできないくらい嬉しいです。"
"90001170-85-アリス" = "……ケイと、また会えました。"
"90001170-86-アリス" = "お話できているだなんて、まだ信じられません。"
"90001170-87-アリス" = "ありがとうございます、ケイ。"
"90001170-88-アリス" = "こうして、帰ってきてくれて……本当に嬉しいんです。"
"90001170-89-アリス" = "だからもう二度と、二度と……。"
"90001170-90-アリス" = "うっ、うぅっ……。"
"90001170-91-ケイ" = "……はい、王女。"
"90001170-92-ケイ" = "私は、大丈夫です。"
"90001170-93-アリス" = "……本当に、ありがとうございました。"
"90001170-94-アリス" = "アリスのお願いを叶えて、こうしてケイに会わせてもらって……どうお礼を伝えれば良いのか分かりません。"
"90001170-95-ヒマリ" = "アリスが喜ぶ姿が見られただけで、十分ですよ。"
"90001170-96-ヒマリ" = "ええ。それに、ケイの存在は私の理論が正しかったという証左だもの。これ以上は必要ないわ。"
"90001170-97-ヒマリ" = "リオ、あなた……。"
"90001170-98-ヒマリ" = "……何かおかしなことを言ったかしら。"
"90001170-99-ヒマリ" = "ケイを生き返らせたのはたしかにあなたですが……はぁ。"
"90001170-100-モモイ" = "じゃじゃーん！モモイ登場！"
"90001170-101-ケイ" = "あっ、あなたは。"
"90001170-102-ミドリ" = "ちょっとお姉ちゃん！？"
"90001170-103-ユズ" = "ご、ごめんなさい……止めようとしたんだけど……"
"90001170-104-モモイ" = "あの時は、よくも私を倒してくれたね！#n忘れたとでも思った！？"
"90001170-105-ケイ" = "いえ、覚えています。#nここは謝るところだとは思いますが……。"
"90001170-106-ケイ" = "あなたに……そうするのはなんだか癪です。[ruby=さいば]才羽[/ruby]モモイ。"
"90001170-107" = "[s] \"ケイちゃん！？\""
"90001170-108-ケイ" = "け、ケイ！？"
"90001170-109-ケイ" = "ほう……その心は？"
"90001170-110-ケイ" = "――あなたが王女に悪影響を与えているからです！"
"90001170-111" = "[s] \"……それは。\""
"90001170-112-ミドリ" = "あっ……。"
"90001170-113-ケイ" = "王女に深夜までゲームをさせておいて、先に眠ったり！"
"90001170-114-ケイ" = "そ、それはゲーム開発部だから……！"
"90001170-115-モモイ" = "コーラを飲ませておいて、歯磨きをさせなかったり！"
"90001170-116-ケイ" = "……ゼロカロリーコーラでもダメかな。"
"90001170-117-ミドリ" = "それに何ですか、あの食生活は！？健康を考えていませんよね！？"
"90001170-118-ユズ" = "ううぅ、野菜はあまり好きじゃないから……。"
"90001170-119-ケイ" = "あなたたちのためにも、生活習慣を大切にしてください！"
"90001170-120-ケイ" = "もっと自分の身体を大事にしてください！#n本当に、もう……！はぁ……はぁ……。"
"90001170-121-リオ" = "今の貴女に、呼吸は必要ないはずなのだけれど……冷却装置の出力を上げた方が良いかしら？"
"90001170-122-ケイ" = "その言い方！ただのデータに過ぎない私よりもデリカシーがありませんよね！#nそういうところですよ[ruby=つかつき]調月[/ruby]リオ！"
"90001170-123-アリス" = "け、ケイ！？"
"90001170-124-アリス" = "うぅ！すみません、リオ先輩！ケイは何も悪くありません！#n全部アリスが悪いんです！怒らないであげてください！"
"90001170-125-リオ" = "王女よ……。"
"90001170-126-リオ" = "気にしないでちょうだい。#nケイの思考回路にノイズが発生したのね。原因を特定してみるわ。"
"90001170-127-エイミ" = "……会長がこういう性格で助かった。"
"90001170-128-ケイ" = "それで……なぜ私は呼ばれたのですか？"
"90001170-129-リオ" = "本題に入る手間が省けて助かるわ。#n単刀直入に言うのだけれど――"
"90001170-130-リオ" = "――貴女とアリスに、もう一度「多次元バリア」を破壊してほしいの。"
"90001170-131-ヒマリ" = "リオ、もう少し詳しく事情を説明しないと……！"
"90001170-132-ケイ" = "待ってください。今、なんと……？"
"90001170-133-ケイ" = "多次元バリア……？#nどうしてまたその話になっているのですか？"
"90001170-134" = "[s5] \"少し長くなるかもしれないけど……。\"\n[s6] \"みんなは復習だと思って聞いてね。\""
"90001170-135-トキ" = "分かりました、先生。#n私はしばらく寝ていますので、話が終わったら呼んでください。"
"90001170-136-エイミ" = "……ちゃんと起きてて。"
"90001170-137-トキ" = "大丈夫です。私と先生の仲ですから何の問題もありません。"
"90001170-138-ミドリ" = "と、トキさん、それは一体どういう意味ですか！？"
"90001170-139" = "（騒がしくなった場を落ち着かせてから……）"
"90001170-140" = "（今まで起きた出来事をケイに一つずつ説明した）"
"90001170-141-ケイ" = "つまり……。"
"90001170-142-リオ" = "先ほどの繰り返しになるのだけれど、貴女とアリスに「多次元バリア」を破壊してほしいの。"
"90001170-143-リオ" = "今回は前回のようにキヴォトス全体が危機に瀕しているわけでは――"
"90001170-144-ケイ" = "お断りします。"
"90001170-145-ヒマリ" = "！？"
"90001170-146-リオ" = "！？"
"90001170-147-アリス" = "……。"
"90001170-148-ケイ" = "ぺろっ……これは、何かが欠落していると主張する味ですね。"
"90001170-149-ケイ" = "どうして急に味の話を……？"
"90001170-150-トキ" = "C&Cの部室に置かれていた資料で知った表現です。"
"90001170-151-ケイ" = "……何を言っているのかよく分かりませんが。"
"90001170-152-トキ" = "話を戻しましょう。"
"90001170-153-ケイ" = "「多次元バリア」の破壊は、王女の命をベットして行う勝率の低い賭けのようなもの。"
"90001170-154-ケイ" = "あの時は、ただ運が良かっただけです。"
"90001170-155-ケイ" = "……私の犠牲だけで済んだのですから。"
"90001170-156-モモイ" = "え！？"
"90001170-157-ミドリ" = "どういうこと！？"
"90001170-158-ユズ" = "あ、アリスちゃんとケイちゃんが……！？"
"90001170-159-ケイ" = "あなたまでケイちゃんと呼ぶのですか……。"
"90001170-160-リオ" = "……詳細を説明してもらえるかしら？"
"90001170-161-ケイ" = "そうですね。いつかは話さなければならないことですし。"
"90001170-162" = "（ケイは落ち着いた口調で、ウトナピシュティムの[ruby=もとぶね]本船[/ruby]で自分とアリスに起きたことについて話した）"
"90001170-163" = "（それを聞いたみんなは……）"
"90001170-164-モモイ" = "うわーん、アリス、ごめんね！そんなことになってたなんて……！"
"90001170-165-ミドリ" = "アリスちゃん、ケイちゃん……。"
"90001170-166-ユズ" = "うっ、ううっ。"
"90001170-167-ヒマリ" = "私たちの考えが軽率でしたね。ごめんなさい、ケイ。#nそうだと知っていたら……。"
"90001170-168-ケイ" = "いえ、大丈夫です。#n知る方法などなかったでしょうから。"
"90001170-169-ケイ" = "無知は罪ではありません。知ったうえで愚行に及ぶのは問題だと思いますが。"
"90001170-170-ケイ" = "……王女よ。"
"90001170-171-ケイ" = "は、はい！？"
"90001170-172-ケイ" = "なぜ、受け入れたのですか？"
"90001170-173-ケイ" = "あなたはこの意味を理解していたはずです。"
"90001170-174-アリス" = "……そうですね。#nごめんなさい、ケイ。"
"90001170-175-アリス" = "たしかに、アリスは知っていました。#nでも、これ以上心配をかけたくなかったのです。"
"90001170-176-ケイ" = "しかし、その過程であなたの身に何かあったら――"
"90001170-177-アリス" = "心配いりません、ケイ。"
"90001170-178-アリス" = "勇気と友情さえあれば大丈夫です！"
"90001170-179-アリス" = "リオ先輩、ヒマリ先輩、エイミ、トキ、ゲーム開発部のみんな……。"
"90001170-180-アリス" = "それに、先生が一緒にいてくれますから！"
"90001170-181-ケイ" = "いえ、それは……。"
"90001170-182-ケイ" = "何でもありません。王女は悪くない……その結論に至ったのは――"
"90001170-183-ケイ" = "全て先生の責任ですから！"
"90001170-184" = "[s] \"なんで！？\""
"90001170-185-ケイ" = "王女に余計な希望を与えたからです！"
"90001170-186" = "[s] \"ええっ！？\""
"90001170-187-ケイ" = "王女に害を与えるものは、全て悪です！"
"90001170-188-アリス" = "落ち着いてください、ケイ！"
"90001170-189-ヒマリ" = "「多次元バリア」の破壊は現実的ではなくなりました。"
"90001170-190-ヒマリ" = "……ですが、依然としてバリアが残っている状況は変わりません。"
"90001170-191-ヒマリ" = "そうね……これから何をすべきかを話し合いましょう。"
"90001170-192-ケイ" = "気になったのですが……「多次元バリア」と預言者の存在の、何が問題になっているのですか？"
"90001170-193-ヒマリ" = "それは……。"
"90001170-194-ヒマリ" = "……たしかに？"
"90001170-195-ヒマリ" = "……！"
"90001170-196-ケイ" = "気づいたようですね。"
"90001170-197-ケイ" = "預言者は殻に閉じこもっているだけです。#n中で何をしようとも、キヴォトスに影響は与えていません。"
"90001170-198-ケイ" = "えっと……殻の中に隠れて怯えてるカタツムリやカメ的な感じ？"
"90001170-199-モモイ" = "良い例えです。もちろん、裏で何をしているのかは気になるところですが。"
"90001170-200-ケイ" = "動きがあるまでは、警戒するだけで良いのではないでしょうか。"
"90001170-201-エイミ" = "そうだね……どうにか対処しなくちゃって思ってたけど。#n別に、攻撃してきているわけじゃないもんね。"
"90001170-202-ケイ" = "その発想に至らないのも理解できます。#n過去に起きた「多次元バリア」の発生は、間違いなくキヴォトスの危機でした。"
"90001170-203-ケイ" = "それが再び現れたのですから、警戒して当然です。"
"90001170-204-ケイ" = "人は過去の経験を教訓とする生き物ですから。"
"90001170-205-トキ" = "そうですね。それはとても良い言葉だと思いますが……。"
"90001170-206-トキ" = "……これから何をすれば良いのでしょう？"
"90001170-207-ミドリ" = "……。"
"90001170-208-ユズ" = "……。"
"90001170-209-アリス" = "……みんなで『テイルズ・サガ・クロニクル』でもプレイしますか？"
"90001170-210-ケイ" = "私は死んでも嫌です！"
"90001170-211-ケイ" = "もう一度やってみたら、違う感想が出てくるかもしれません……。"
"90001170-212-ケイ" = "あり得ません、王女はよくご存知でしょう！"
"90001170-213-アリス" = "そ、それはそうですが……。"
"90001170-214-リオ" = "今後の方針を決めるのは重要よ。"
"90001170-215-リオ" = "そうね……ひとまず、ケイの身体を作りましょうか。"
"90001170-216-アリス" = "……はい？"
"90001170-217-アリス" = "はい……？"
"90001170-218-ケイ" = "ちょっと待ってください、どうしてそんな流れになるのですか！？"
"90001170-219-ヒマリ" = "感情は脳だけで処理しきれないもの。#nこのままでは、不満が積もって会話にならなくなってしまうわ。発散するための肉体は必要不可欠よ。"
"90001170-220-ヒマリ" = "なるほど……たしかに、ケイが感情的になりすぎてしまえば、会話が成立しなくなる。#n合理的な分析ですね、リオ。"
"90001170-221" = "[s] \"言われてみれば、たしかに。\""
"90001170-222-ヒマリ" = "迅速な理解に感謝するわ。"
"90001170-223-ケイ" = "勝手に話を進めないでください……。"
"90001170-224-ケイ" = "そもそも、この話題にリオが参加していること自体、とても不安なのですが。"
"90001170-225-ヒマリ" = "ケイの身体は、どのように作りましょうか？"
"90001170-226-ヒマリ" = "ちょうどAMASを連れてきているし、スペアパーツと素体には困らないと思うわ。#nここは私に任せてちょうだい。"
"90001170-227-ケイ" = "だから、私の話を聞いてください！"
"90001170-228-トキ" = "どのAMASを使うつもりなの？"
"90001170-229-トキ" = "ご心配なく。リオ様の唯一無二のセンスを信じてください。"
"90001170-230-ケイ" = "唯一無二という表現は、前向きな意味以外も含まれますよね！？"
"90001170-231-ケイ" = "そのくらい、皆さんもご存知ですよね！？"
"90001170-232-ケイ" = "ひぃっ！？"
"90001170-233-アリス" = "……本当に、ケイの身体を作ってくれるんですか？"
"90001170-234-アリス" = "アリスは……ケイと触れ合えるようになるのですか……？"
"90001170-235-AMAS A" = "お、王女！？"
"90001170-236-リオ" = "そうね、不安も多いかもしれないだろうけれど……。"
"90001170-237-リオ" = "私を信じてちょうだい、アリス。"
"90001170-238-アリス" = "ありがとうございます、リオ先輩！ヒマリ先輩！"
"90001170-239-ヒマリ" = "はい、最善を尽くしましょう。"
"90001170-240-ケイ" = "早く助けてと言っているんです！"
"90001170-241" = "[s] \"みんな、ケイを助けようとしているんだよ。\""
"90001170-242-ケイ" = "助けられる側の意見を聞いてほしいのですが！？"
"90001170-243-ケイ" = "合理性を盾に自分の美的感覚を押しつけてこないように、見張っていてくれませんか！？"
"90001170-244" = "[ns] \"それ以上動くと危ないから……。\""
"90001170-245-ケイ" = "うわああああ！"
"90001170-246" = "次回;夜明け"
