[translation]
"90001260-1" = "第26話;闇を照らす灯"
"90001260-2" = "[ns] \"……ここが最後の部屋かな？\""
"90001260-3-ユズ" = "な、なんか変な感じ……。"
"90001260-4-エイミ" = "苔だけじゃなくて、ツルも生えてるし。#nここなんて水たまりがあるよ。"
"90001260-5-リオ" = "この状況……普通なら、とっくに閉鎖されているわね。"
"90001260-6-アリス" = "見てください！#n壁全体が引き出しになっています！"
"90001260-7-ヒマリ" = "そのようですね。少し見てみましょうか。"
"90001260-8-ヒマリ" = "……あら？これは驚きです。#n種の保管状況は悪くないですね。"
"90001260-9-モモイ" = "雰囲気的に、ここがシード・ボルトの本体なのかな？"
"90001260-10-ミドリ" = "人が近づかないように普段は隠されてる……神聖な森みたいな場所ですね。"
"90001260-11-トキ" = "どうやら、この施設は三重の密閉構造になっていたようです。"
"90001260-12-リオ" = "建屋と、貯蔵庫までの空間は壊れていたけれど……幸い、種子を保管するシェルターだけはまだ機能しているのね。"
"90001260-13-トキ" = "キヴォトスに誇るミレニアムの技術力ですね。"
"90001260-14-リオ" = "いえ、それだけではないはずよ。"
"90001260-15-ヒマリ" = "他にも要因があると？"
"90001260-16-リオ" = "これまで、預言者と成ったAIは既存の行動パターンと異なる様子を見せていたわ。"
"90001260-17-リオ" = "元々はミレニアムの通信ユニットAIだったホド――"
"90001260-18-ヒマリ" = "コクマーも元は船でしたが、今は原形をとどめていませんね。"
"90001260-19-リオ" = "ええ。でもシード・ボルトの管理AIは、預言者になってからも種の管理を続けている。"
"90001260-20-リオ" = "――まるで、それが使命であるかのように。"
"90001260-21-ヒマリ" = "たしかにこの保管状態は……意図的なものであると考えたほうが自然ですね。"
"90001260-22-リオ" = "ただ、この仮定には、一つ疑問があるの。"
"90001260-23-リオ" = "その意思は、あの三人のものなのか、それとも預言者――ティファレトのものなのか。"
"90001260-24-ヒマリ" = "もしティファレトだとしたら、あなたの見解は？"
"90001260-25-リオ" = "……預言者にも、自意識があるのかもしれないわ。"
"90001260-26-リオ" = "そう考えると――"
"90001260-27-リオ" = "――！？"
"90001260-28-ヒマリ" = "これは……！？"
"90001260-29-アリス" = "リオ先輩、ヒマリ先輩！？"
"90001260-30-アリス" = "モモイ、ミドリ！？みんな……！？#n一体、何が起きているんですか！？"
"90001260-31-アリス" = "何か変な臭いがします……うぅ、アリス、気分が悪くなってきました。"
"90001260-32-アリス" = "せ、先生は大丈夫ですか？"
"90001260-33" = "（視界が暗くなり……）"
"90001260-34" = "（目眩と眠気に襲われた……）"
"90001260-35-アロナ" = "先生！しっかりしてください！！"
"90001260-36" = "[ns1] \"うぅん……。\"\n[ns2] \"あと5分……。\""
"90001260-37-アロナ" = "アロナ先輩、これは……。"
"90001260-38-アロナ" = "大丈夫です、プラナちゃん！#nここは私が何とかします！"
"90001260-39-プラナ" = "お願いします、アロナ先輩。#n私もサポートしますので。"
"90001260-40-アロナ" = "……原因は何かのガスみたいですね。#nそれならまずは――はいっ、これ以上先生が吸い込まないよう対処しました！"
"90001260-41-プラナ" = "分析。無色、無臭。毒性……あり。#n神経細胞に作用しますが、幸い、危険度は比較的低いもののようです。"
"90001260-42-アロナ" = "生徒さんの命に別状はありません。#n少し安静にしていれば、すぐに目を覚ますはずです。"
"90001260-43-プラナ" = "ですが、長時間の吸引は推奨できません。#n毒性を持つことに変わりはありませんから。"
"90001260-44-アロナ" = "うーん、難しい話をしていたら……#n何だか私まで眠くなってきちゃいました……。"
"90001260-45-プラナ" = "アロナ先輩、私たちまで寝てしまったら……。"
"90001260-46-アロナ" = "じょ、冗談ですよ！#n私が本当に寝るわけないじゃないですか！"
"90001260-47-プラナ" = "肯定。#nこういう時のアロナ先輩は、それなりに頼りになるので。"
"90001260-48-アロナ" = "そっ、それなりですか！？"
"90001260-49-アロナ" = "あっ、先生！ケイさんが近づいてきています！"
"90001260-50" = "[ns] \"……ケイ？\""
"90001260-51-ケイ" = "あ、ご無事でしたか。#n思いのほか丈夫ですね。"
"90001260-52-ケイ" = "……うん？いえ、妙ですね。#n私やアリスはともかく、どうして先生も影響を受けていないのでしょう？"
"90001260-53-アリス" = "うわーん！#nみんながまったく目を覚ましません！"
"90001260-54-ケイ" = "ほかの人たちと先生の違い……。"
"90001260-55-ケイ" = "（もしかして……？）"
"90001260-56-ケイ" = "ううぅ、ステータス低下イベントです……。#nパーティーを守れなかったせいで、仲間からのバフが消えてしまいました。"
"90001260-57-アリス" = "このままでは120％の力は発揮できません……。"
"90001260-58" = "[ns] \"みんなは眠ってるの？\""
"90001260-59-アリス" = "……え？あ、はい。バイタルに大きな影響はないかと。#nですが、このままという訳にも……ただでさえ時間がないのに。"
"90001260-60-ケイ" = "とりあえず、先生が目を覚ますまでのことを、要点だけお話しします。"
"90001260-61-ケイ" = "先ほど、貯蔵庫の中央にタッチパネルのようなものを発見しました。"
"90001260-62" = "私には反応を示さなかったものの、アリスが触れてみたところ――"
"90001260-63" = "画面が一瞬光ってから、ずっと点滅を繰り返していて……#nアリス、何かしてしまったのでしょうか……？"
"90001260-64-ケイ" = "他の生徒でも試してみましたが、変化はありませんでした。"
"90001260-65-ケイ" = "きっと、ギミック解除に必要なピースが欠けてしまっているんです……#nアリスには分かります。"
"90001260-66-ケイ" = "そのピースがなんなのか……とにかく、後は先生で最後です。"
"90001260-67-ケイ" = "タッチパネルに触ってもらえますか。"
"90001260-68" = "[s3] \"その前に聞きたいんだけど……。\"\n[s4] \"寝ている子たちの手を勝手に当てたの？\""
"90001260-69-ケイ" = "何か問題でも？#n試せることを実践しただけですよ。"
"90001260-70-アリス" = "アリスは止めようとしたんですが……"
"90001260-71-ケイ" = "……リオなら、合理的な判断だと認めるかと。"
"90001260-72" = "[ns] \"そう言われると、納得するしかないような……。\""
"90001260-73" = "（ケイに促され、タッチパネルに手を当てた）"
"90001260-74" = "（すると……）"
"90001260-75" = "[ns] \"え……？\""
"90001260-76-ケイ" = "このエンブレムは……レッドウィンター連邦学園？"
"90001260-77" = "（軽快なのに威厳を感じられる曲が流れ始めたかと思うと）"
"90001260-78" = "（続いて、録音された音声が聞こえてきた……）"
"90001260-79" = "[56cd7b][log=모니터]歓迎します、同志よ。……同志ではないかもしれませんが。[/log]"
"90001260-80" = "[56cd7b][log=모니터]レッドウィンターの種子貯蔵庫へようこそ。[/log]"
"90001260-81" = "[ns] \"……これは？\""
"90001260-82" = "[56cd7b]歓迎します、同志よ。……同志ではないかもしれませんが。"
"90001260-83" = "[56cd7b]レッドウィンターの種子貯蔵庫へようこそ。"
"90001260-84" = "管理システムの類でしょうね。#n事前に設定した映像を再生しているのかと。"
"90001260-85" = "[56cd7b][log=모니터]ここは世界の滅亡に備えて造られた生命の揺り籠。[/log]"
"90001260-86" = "[56cd7b][log=모니터]煌びやかな文明が残す、最後の灯です。[/log]"
"90001260-87" = "[56cd7b][log=모니터]ご挨拶代わりに、私の大好きな音楽を聞かせてあげたいところですが……。[/log]"
"90001260-88" = "[56cd7b][log=모니터]あいにく昨日、演奏禁止曲に指定されてしまったので、それはまたの機会に。[/log]"
"90001260-89" = "[ns] \"……レッドウィンターらしいね。\""
"90001260-90" = "[56cd7b][log=모니터]この施設は、そこにいるあなたはもちろん、#n[wa:1500][56cd7b]今の我々のために造られた場所でもあります。[/log]"
"90001260-91" = "[56cd7b][log=모니터]「世界が滅んでもやり直せる」[/log]"
"90001260-92" = "[56cd7b][log=모니터]種子貯蔵庫の存在は人々の拠り所となり――[/log]"
"90001260-93" = "[56cd7b][log=모니터]何にも怯えることなく、安心して暮らせるようになりました。[/log]"
"90001260-94" = "[56cd7b][log=모니터]無論、いつかの未来、滅亡が訪れているとして……。[/log]"
"90001260-95" = "[56cd7b][log=모니터]その切っ掛けが何であったのかは知りようがありませんが――[/log]"
"90001260-96" = "[56cd7b][log=모니터]滅亡の時、この録音を聞いている……そこにいるあなたはどんな人なのか。#n[wa:1500][56cd7b]想像するだけでワクワクしてきます。[/log]"
"90001260-97-アリス" = "アリス、よく分かりません。#nここのNPCでしょうか……？"
"90001260-98" = "[56cd7b][log=모니터]この施設を造るにあたって、数々の出来事がありました。[/log]"
"90001260-99" = "[56cd7b][log=모니터]建設費用を賄うためにプリンを水増ししたのも……。#n[wa:1500][56cd7b]今となってはいい思い出ですね。[/log]"
"90001260-100" = "[56cd7b][log=모니터]引き継いだ者には、どうか苦難が訪れないよう願うばかりです。[/log]"
"90001260-101" = "[56cd7b][log=모니터]いずれにせよ、滅亡の時は来たりて。#n[wa:1500][56cd7b]いろいろと切り詰めて成し遂げた我々の苦労は報われたようですね。[/log]"
"90001260-102-ケイ" = "……不愉快です。#n滅亡についてあまりにも軽々しく扱いすぎです。"
"90001260-103" = "[56cd7b][log=모니터]さて、前置きが長くなってしまいましたね。#n[wa:1500][56cd7b]この施設は種子貯蔵庫。滅亡の闇を照らす最後の灯。[/log]"
"90001260-104" = "[56cd7b][log=모니터]来るべき時まで種を安全に保管するため、この施設は防衛機構を備えています。[/log]"
"90001260-105" = "[56cd7b][log=모니터]また、最新の状態を保つために、試験稼働は省略しています。[/log]"
"90001260-106" = "[56cd7b][log=모니터]即ち、あなたが手を出したもの、あるいは手を出そうとしているものは……。[/log]"
"90001260-107" = "[56cd7b][log=모니터]我々ですら触れたことのない代物です。[/log]"
"90001260-108" = "[56cd7b][log=모니터]稼働には、相応のお覚悟を。[/log]"
"90001260-109" = "[ns5] \"最新状態を保つために……。\"\n[ns6] \"テストを行っていない！？\""
"90001260-110" = "[56cd7b]即ち、あなたが手を出したもの、あるいは手を出そうとしているものは……。"
"90001260-111" = "[56cd7b]我々ですら触れたことのない代物です。"
"90001260-112" = "[56cd7b]稼働には、相応のお覚悟を。"
"90001260-113-ケイ" = "設計者は何を考えているんですか！？"
"90001260-114" = "[56cd7b][log=모니터]ああ、それと。ここ、第3区域の管理施設までは立ち入りを許可しますが――[/log]"
"90001260-115" = "[56cd7b][log=모니터]この先の第2貯蔵庫は、指導委員会の手続きなしでは進めません。[/log]"
"90001260-116" = "[56cd7b][log=모니터]全体の7割を占める種が保管されている重要施設なので。[/log]"
"90001260-117" = "[56cd7b][log=모니터]もし施設に危害を加えたり、無理やり侵入しようとした場合――[/log]"
"90001260-118" = "[56cd7b][log=모니터]他の施設を諦めてでも、あなたを……あなたを……うーん……。[/log]"
"90001260-119" = "[56cd7b][log=모니터]……どうにも頭が回りませんね。#n[wa:1500][56cd7b]このところ満足にコーヒーすら飲めていませんし、カフェイン不足でしょうか。[/log]"
"90001260-120" = "[56cd7b][log=모니터]うーん……何か残酷な仕打ちを……。[/log]"
"90001260-121" = "[56cd7b][log=모니터]できれば、あなたが思う一番嫌なことで。#n[wa:1500][56cd7b]……あなたは何が一番嫌ですか？[/log]"
"90001260-122-アリス" = "え、えっと……セーブデータの削除でしょうか？"
"90001260-123" = "[56cd7b][log=모니터]…………なるほど。では、それで。我々はあなたをそのようにさせますから。[/log]"
"90001260-124" = "[56cd7b][log=모니터]あなたが何を言ったのか知る術はありませんが、ご協力に感謝します。[/log]"
"90001260-125" = "[56cd7b][log=모니터]とにかく、第2貯蔵庫にだけは手を出さないでください。[/log]"
"90001260-126" = "[56cd7b][log=모니터]とはいえ……内部をお見せできないのは、少し残念ですね。[/log]"
"90001260-127" = "[56cd7b][log=모니터]元々、貯蔵庫として使うつもりではありませんでしたし……。#n[wa:1500][56cd7b]あそこは第3区域よりも綺麗に整備されていますから。[/log]"
"90001260-128" = "[56cd7b][log=모니터]まあ、これもおそらく、世の摂理でしょう。[/log]"
"90001260-129" = "[56cd7b][log=모니터]最初に焼いたブリヌイの形は、いつも崩れてしまうように――#n[wa:1500][56cd7b]すべては思い通りにいかないもの。[/log]"
"90001260-130" = "[56cd7b][log=모니터]過ぎたことは忘れて、次の滅亡の時は……。#n[wa:1500][56cd7b]もっとうまくできるように頑張りましょう！[/log]"
"90001260-131-ケイ" = "次の……滅亡？"
"90001260-132-アリス" = "うわぁーん、この方が何を言っているのか全然分かりません！"
"90001260-133" = "[56cd7b][log=모니터]以上で、案内と警告を終了します。[/log]"
"90001260-134" = "[56cd7b][log=모니터]訪れた滅亡が、重苦ではないことを祈っています。[/log]"
"90001260-135" = "[56cd7b][log=모니터]そして――[/log]"
"90001260-136" = "[56cd7b]そして―――"
"90001260-137" = "[56cd7b]そして――――"
"90001260-138" = "[FF6666][log=모니터]〈あれ？なんか変な表示が出て……え？もう容量残ってないの？〉[/log]"
"90001260-139" = "[FF6666][log=모니터]〈それがですね――〉[/log]"
"90001260-140" = "[log=모니터]ファイルプレイバック終了[/log]"
"90001260-141" = "ファイルプレイバック終了│"
"90001260-142" = "ファイルプレイバック終了"
"90001260-143" = "ファイルプレイバック終了│"
"90001260-144" = "ファイルプレイバック終了"
"90001260-145" = "[log=모니터]データプレイバック終了[/log]"
"90001260-146" = "ファイルプレイバック終了"
"90001260-147" = "データプレイバック終了│"
"90001260-148" = "ファイルプレイバック終了"
"90001260-149" = "データプレイバック終了"
"90001260-150" = "ファイルプレイバック終了"
"90001260-151" = "データプレイバック終了│"
"90001260-152" = "ファイルプレイバック終了"
"90001260-153" = "データプレイバック終了"
"90001260-154" = "[log=모니터]追加データなし[/log]"
"90001260-155" = "ファイルプレイバック終了"
"90001260-156" = "データプレイバック終了"
"90001260-157" = "追加データなし│"
"90001260-158" = "ファイルプレイバック終了"
"90001260-159" = "データプレイバック終了"
"90001260-160" = "追加データなし"
"90001260-161" = "ファイルプレイバック終了"
"90001260-162" = "データプレイバック終了"
"90001260-163" = "追加データなし│"
"90001260-164" = "ファイルプレイバック終了"
"90001260-165" = "データプレイバック終了"
"90001260-166" = "追加データなし"
"90001260-167" = "ファイルプレイバック終了"
"90001260-168" = "データプレイバック終了"
"90001260-169" = "追加データなし│"
"90001260-170" = "ファイルプレイバック終了"
"90001260-171" = "データプレイバック終了"
"90001260-172" = "追加データなし"
"90001260-173-ケイ" = "……何ですか、これ。"
"90001260-174" = "[ns7] \"重要な内容が含まれてたような……。\"\n[ns8] \"第2貯蔵庫には行くなって言ってたよね？\""
"90001260-175-ケイ" = "いざとなれば、他の施設を諦めてでも防衛するつもりらしいですね。"
"90001260-176-ケイ" = "残酷な仕打ちだとか、明らかな脅しまでして。"
"90001260-177-アリス" = "ううっ、すごく頑張って育ててきたので……。#nセーブデータだけは消さないでください……。"
"90001260-178-ケイ" = "（……ゲームはほどほどにするよう、後でお説教ですね）"
"90001260-179-アリス" = "灯りが……？"
"90001260-180-ケイ" = "……またですか。芸がないですね。"
"90001260-181-アリス" = "うわぁーん！真っ暗です！#n何も見えません……！"
"90001260-182-ケイ" = "アリス、私から離れないでください！"
"90001260-183-ケイ" = "なにか、信号のようなものが……？"
"90001260-184-アリス" = "……！"
"90001260-185-アイン" = "こ、こんにちは……みなさん、先生。#nまた会いましたね……えへへ。"
"90001260-186-ソフ" = "ほんと、しぶといね。"
"90001260-187-オウル" = "いっそ全て諦めてしまえば楽になるというのに。"
"90001260-188" = "[s9] \"それはできないよ。\"\n[s10] \"先生として、生徒を諦めるわけにはいかない。\""
"90001260-189-ソフ" = "私たちも生徒だ！って言ったら……先生は諦めないつもり？"
"90001260-190" = "[s11] \"もちろん。\"\n[s12] \"編入書類は用意してあるから、いつでも連絡してね。\""
"90001260-191-ソフ" = "うわぁ……もしかして冗談が通じないの？"
"90001260-192-オウル" = "こ、こういうのをダメ人間、と言うのでしょうか……？"
"90001260-193-オウル" = "ご期待に沿えず申し訳ないですが……私たちは一切興味ありませんので。"
"90001260-194-オウル" = "編入も、所詮は人間が作ったシステムでしょう？#n私たちとは無関係ですから。"
"90001260-195" = "[ns13] \"編入したくて会いに来たのかなって思ったんだけど……。\"\n[ns14] \"それなら、どうして来てくれたの？\""
"90001260-196-ソフ" = "すごい……全然空気読まないんだ……。"
"90001260-197-ソフ" = "とにかく、私たちが言いたいことは――ここを越えたら、もう取り返しがつかないよ。"
"90001260-198-オウル" = "ええ。文字通り「一線を越える」という意味です。"
"90001260-199-オウル" = "ソフの言葉を借りると……宣戦布告に来ました。"
"90001260-200" = "次回;罪と罰"
