[translation]
"90001130-1" = "第13話;出発"
"90001130-2-ソフ" = "お、着いた？"
"90001130-3-アイン" = "は、はい！「グリッドポイント」から最後の資源が届きました！"
"90001130-4-オウル" = "まぁ、正確には「最後」ではありませんが。#n総収集率99.98％……あと2回くらいでしょうか。"
"90001130-5-アイン" = "そ、そうですけど……ひぃん。"
"90001130-6-ソフ" = "大丈夫、それくらい誤差だって！#n問題なく次の工程に移れるよ。"
"90001130-7-ソフ" = "ってかオウル、一言多くない？#n今のいう必要あった？"
"90001130-8-オウル" = "だって……。"
"90001130-9-ソフ" = "……だって？"
"90001130-10-オウル" = "アインの泣きそうな顔って、可愛いじゃないですか！"
"90001130-11-アイン" = "は、はいぃ！？"
"90001130-12-オウル" = "いや、それは分かるけどさ……。"
"90001130-13-アイン" = "ソフ！？"
"90001130-14-ソフ" = "あっ、今のはそういう意味じゃなくて――"
"90001130-15-ソフ" = "もう！あんたのせいなんだけど！"
"90001130-16-オウル" = "私のせいにしないでくださいよ！？"
"90001130-17-アイン" = "えっと、みんな……。"
"90001130-18-アイン" = "つ、次はうちのレイバーちゃんたちの番ですね！"
"90001130-19-オウル" = "ええ、みんなよく頑張ってくれています。"
"90001130-20-アイン" = "で、でもちょっと心配です。#nヘリカル5号ちゃんの傷、まだ治ってないので。"
"90001130-21-ソフ" = "ヘリカル5号……名前つけたの？#n塗装が剥がれてたヤツだっけ。"
"90001130-22-アイン" = "そうです！塗装が剥がれると錆びやすくなってしまうので……。"
"90001130-23-アイン" = "塗りなおすのと一緒に、大きなアームを追加して……！"
"90001130-24-アイン" = "ついでに、ボディを頑丈な素材に変更すれば……。"
"90001130-25-ソフ" = "ヘリカル3号をどれだけ大事にしてるかはよ～く分かったから、落ち着いてアイン。"
"90001130-26-アイン" = "ご、5号です！それにヘリカル5号ちゃんは、ただのレイバーじゃありません！#nあの子は、その……。"
"90001130-27-アイン" = "と、特別なんです！"
"90001130-28-ソフ" = "何か違いでもあるの？#n何万個もあるレイバーの一つでしょ。"
"90001130-29-オウル" = "ああ、なんて血も涙もない言葉！#nソフはレイバーのことを、ただの道具としか見ていないのですね！"
"90001130-30-オウル" = "その言葉が、アインの心にどれだけ大きな傷を与えるのか――あなたはお分かりですか？"
"90001130-31-ソフ" = "……あんたにだけは言われたくないんだけど？"
"90001130-32-オウル" = "ところで、アイン。#nヘリカル5号の修理材はそれで足りますか？"
"90001130-33-オウル" = "全体のアップグレードをするなら、それに合った装備とプログラムが必要になります。"
"90001130-34-オウル" = "無茶な改造は、ヘリカル5号の寿命を縮めるだけになるかもしれませんよ？"
"90001130-35-アイン" = "え、ええっ！？#nそ、それは……ダメです！"
"90001130-36-オウル" = "だから手伝うって言ってるじゃないですか。お任せください。"
"90001130-37-オウル" = "まず、すべてのプロセスを最適化し、既存業務を半分以下の時間で終わらせられるようにして……。"
"90001130-38-オウル" = "浮いた業務時間は……ダンスでも踊らせましょうか！そして――"
"90001130-39-アイン" = "そ、それはあんまりですよぉ！"
"90001130-40-ソフ" = "暴力、反対……ぐはっ……"
"90001130-41-アイン" = "その……収集率が99.98%に到達したということは。"
"90001130-42-ソフ" = "うん……ついに時が来た。"
"90001130-43-オウル" = "ええ、私たちのお姉様……。"
"90001130-44-オウル" = "「マルクト」をこの地に降臨させる用意ができました。"
"90001130-45-アイン" = "だ、だだだ大丈夫でしょうか？"
"90001130-46-アイン" = "もしもお姉様が目覚めなかったら……！"
"90001130-47-ソフ" = "大丈夫、私たちは信じてる。#nそれに今まで上手くやってきたでしょ？"
"90001130-48-ソフ" = "私たちの中で一番機械に詳しいのはアインだからね。"
"90001130-49-アイン" = "で、でも……！"
"90001130-50-オウル" = "アインの気持ちも理解できます。#nこれより先は、量子力学のことまで考えないといけないですからね。"
"90001130-51-オウル" = "それに、成功させなければなりません。#n「最善を尽くした」は言い訳にしかならないですから……ふふ。"
"90001130-52-アイン" = "ひぃん……。"
"90001130-53-オウル" = "でも――今はやるしかありません。"
"90001130-54-オウル" = "禁じられた力の手を借りているのは気に食わないですが……。"
"90001130-55-オウル" = "まあ、「結果良ければ全て良し」とも言いますし。#nそれに、ここの準備も滞りなく終わりました。"
"90001130-56-ソフ" = "そうだね。#n「多次元解釈・状態共存・位相バリア」――長いから多次元バリアでいっか。"
"90001130-57-ソフ" = "あらゆる多次元の可能性を同居させて防御に使うバリア……。"
"90001130-58-ソフ" = "あの日は、とても良いサンプルが見られたよね。#nおかげで、ここ[ruby=リバースエンジニアリング]まで再構築でき[/ruby]たわけだし。"
"90001130-59-オウル" = "ふふ、うふふふっ。その部分に関しては、自分の功績が一番大きかったと認めても良いのではないでしょうか？"
"90001130-60-ソフ" = "……悔しいけど、そうだね。"
"90001130-61-アイン" = "ご、ごめんなさい……私はその辺りが弱くて……ひぃん。"
"90001130-62-ソフ" = "大丈夫だよアイン！#nそもそも私たち、専門分野が違うわけだし？"
"90001130-63-オウル" = "アインにだけ甘すぎませんか……。"
"90001130-64-ソフ" = "日頃の行いを考えたら？"
"90001130-65-オウル" = "……現状、多次元バリアで保護されているここを発見するなんて、ほぼ不可能です。"
"90001130-66-オウル" = "私たちは「名もなき神の力」を使いこなしていますからね。"
"90001130-67-アイン" = "ほ、本当にそうなんでしょうか？#n「他人の力を勝手に使うんじゃない」って怒られたりしませんか……？"
"90001130-68-ソフ" = "誰が何言ったって、別に良くない？"
"90001130-69-オウル" = "私たちは、「完全無欠」ですからね。"
"90001130-70-オウル" = "道具は使えるところだけ使えばいいのです。#nそれを咎めるものなどいないかと。"
"90001130-71-オウル" = "ああでも、無名の司祭がいるんでしたっけ？#n噂でしか聞いたことないですが。"
"90001130-72-オウル" = "というか、時の敗北者への配慮なんて必要ですか？#nそれに、仮にいたとしても私たちに感謝するのでは？使ってくださりありがとうございます！って"
"90001130-73-アイン" = "まあそうだよね。別に悪いことしてるわけじゃないし？"
"90001130-74-アイン" = "ほ、本当にこれで良いんでしょうか……。"
"90001130-75-ミドリ" = "つ、ついにクリアした……！"
"90001130-76-モモイ" = "ど、どうだった！？"
"90001130-77-アリス" = "アリス、知っています！#nこれは……"
"90001130-78-モモイ" = "これは……？"
"90001130-79-アリス" = "クソゲーですね！"
"90001130-80-ユズ" = "ひうっ……！"
"90001130-81-モモイ" = "ぐはっ！？"
"90001130-82-ミドリ" = "まずさ、なんで氷河に足を踏み入れた瞬間死ぬの？"
"90001130-83-モモイ" = "実際の氷河って寒いじゃん？#n何も準備してなかったら凍死するでしょ？"
"90001130-84-ミドリ" = "いくら何でもひどすぎない！？#nせめて、まともにプレイできるようにして！"
"90001130-85-モモイ" = "ちゃんとチュートリアルを最後までやったら、防寒装備がもらえるようにしてあるよ！？"
"90001130-86-ミドリ" = "30分のチュートリアルはちょっと……もらった装備に着替えないといけないならそう書いて！"
"90001130-87-ミドリ" = "というか、いくら寒くても即死はなくない！？"
"90001130-88-モモイ" = "ミドリ、氷河に行ったことあるの！？#n即死するかもじゃん！"
"90001130-89-ミドリ" = "はぁ……装備がないと百歩譲って即死するのはいいとして。#n私の描いたイラストはどうしたの？"
"90001130-90-モモイ" = "そ、それはDLCにしようと思って……。"
"90001130-91-ミドリ" = "依頼の時に言ってよ！"
"90001130-92-ユズ" = "ふ、二人とも、喧嘩しないで……。"
"90001130-93-アリス" = "でも、アリスは楽しいです。#nみんなでゲームを作るのも、こうやって直していくのも！"
"90001130-94-モモイ" = "うわああああん、アリス～！"
"90001130-95-ミドリ" = "はぁ……アリスちゃんがお姉ちゃんを甘やかすからこうなるんじゃないのかな。"
"90001130-96-ユズ" = "で、でも実際……何が足りてなかったのかな？"
"90001130-97-ミドリ" = "シナリオライター兼企画者兼統括プロデューサーとして、ちゃんと向き合わないとだよね！"
"90001130-98-ミドリ" = "最後のは自称でしょ……。"
"90001130-99-モモイ" = "分かった！#n「アークティック・アドベンチャー」にはリサーチが足りてないんだ！"
"90001130-100-モモイ" = "そうと決まれば、氷河に行こう！"
"90001130-101" = "なに言ってるのお姉ちゃん！ちゃんと資料を調べるだけでも、ある程度まともなゲームになるでしょ！現地に行く必要なんて……。"
"90001130-102-ユズ" = "氷河……！？#nそ、そんな遠いところに行くなんて……。"
"90001130-103-アリス" = "大丈夫ですか、ユズ！？"
"90001130-104-ミドリ" = "雪が積もった平原、青くて透明な氷河、仲良く遊んでいる白熊とペンギン……。"
"90001130-105-ミドリ" = "インスピレーションを与えてくれる素晴らしい景色だと思わない！？"
"90001130-106-ミドリ" = "お姉ちゃんが見てみたいだけでしょ。#nというか、白熊とペンギンは同じ地域に生息してないよ？"
"90001130-107-ミドリ" = "うっ……。"
"90001130-108-モモイ" = "これ、アリスのじゃない？"
"90001130-109-アリス" = "この番号は……？"
"90001130-110-モモイ" = "先生……？"
"90001130-111-モモイ" = "え、先生から電話？"
"90001130-112-ユズ" = "ふふっ……なんだか久しぶりな気がする。"
"90001130-113-アリス" = "もしもし、先生！"
"90001130-114" = "[s] \"こんにちは、アリス。\""
"90001130-115-アリス" = "はい、アリスです！#nこうしてお話するのは久しぶりな気がします！"
"90001130-116-アリス" = "「気がする」というより、全然会ってないような……。"
"90001130-117-アリス" = "みんなも先生と会いたがっています！"
"90001130-118" = "[s] \"ごめんね。\""
"90001130-119" = "[ns] \"ユズたちもそこにいるの？\""
"90001130-120-アリス" = "はい、新しく作ったゲームのテストを一緒にしていました！"
"90001130-121-アリス" = "ゲームの出来ですか……？"
"90001130-122-アリス" = "楽しく作れました！"
"90001130-123-アリス" = "それより先生、いつもと声が違うような……？"
"90001130-124" = "[s] \"えっと……みんな、そこにいるんだよね？\""
"90001130-125-アリス" = "はい、そうですが……。"
"90001130-126" = "（どこまで話すか悩んだけど……）"
"90001130-127" = "（素直に言うのが一番良い気がした）"
"90001130-128" = "[ns] \"みんな、よく聞いてほしいんだ。\""
"90001130-129-ミドリ" = "氷？"
"90001130-130-モモイ" = "河！"
"90001130-131-ユズ" = "探？"
"90001130-132-アリス" = "検！"
"90001130-133-アリス" = "みんなと一緒に氷河に行くんですか？#n良かったですね、モモイ！"
"90001130-134-モモイ" = "流石だよ、先生！"
"90001130-135" = "[s1] \"えっと、さっきも言ったけど……。\"\n[s2] \"危険もいっぱいあると思うんだ。\""
"90001130-136-ミドリ" = "そ、そうだよお姉ちゃん！"
"90001130-137-ミドリ" = "氷河に現れた巨大変身怪獣が何か変な事をしてて……。"
"90001130-138-ミドリ" = "その親玉が隠れてそうなとこに行くために、アリスちゃんの力を借りるかもしれないってことでしょ！？"
"90001130-139-ユズ" = "うぅ……ゲームの世界の話みたい。#n現実味がないよ……。"
"90001130-140" = "[s3] \"これはゲームじゃなくて、現実の話なんだ。\"\n[s4] \"だから、よく考えて決めてほしい。\""
"90001130-141-アリス" = "……先生は、アリスの仲間です。"
"90001130-142" = "[s] \"そう思ってくれるのは本当に嬉しいけど……。\""
"90001130-143" = "[ns] \"もう一度説明するね。これは――\""
"90001130-144-アリス" = "大丈夫です、アリスはちゃんと分かっていますから。"
"90001130-145-アリス" = "アリスたちの安全を確保できないかもしれないのですよね。"
"90001130-146-ユズ" = "アリスちゃん……。"
"90001130-147-アリス" = "……先生。"
"90001130-148-アリス" = "それで、どうやって向かえば良いんですか？"
"90001130-149" = "[s] \"！？\""
"90001130-150-モモイ" = "あ、アリス！？"
"90001130-151-ミドリ" = "アリスちゃん！？"
"90001130-152-アリス" = "どうしてそんなに驚くのですか？#n仲間が大変な時は、みんなで助けるべきです。パーティープレイの基本です。"
"90001130-153-アリス" = "何よりもアリスは、困った時に先生がこうして頼ってくれて嬉しいです。"
"90001130-154-アリス" = "信頼こそ、仲間である一番の証拠ですから。"
"90001130-155" = "[s] \"……本当に大丈夫？\""
"90001130-156-アリス" = "先生……アリスは見習いですが、これでも勇者です。そうであろうと努力しています。"
"90001130-157-アリス" = "見習い勇者として、少しでも良い世界になってほしいと思っています。"
"90001130-158-アリス" = "だからこそ、困っている人がいるのなら、力になりたいのです。"
"90001130-159-アリス" = "そうすれば、世界は少しだけ素敵になるからです。"
"90001130-160" = "[s] \"もしも、危険な状況になってしまったら……アリスはどうするの？\""
"90001130-161-アリス" = "その時は……。"
"90001130-162-アリス" = "生徒にジョブチェンジして、安全な場所に隠れます！"
"90001130-163-ユズ" = "それ良いね！#nゲームなら、何してもいいわけだし！"
"90001130-164-ミドリ" = "チートはダメだけどね。"
"90001130-165-ミドリ" = "わ、わたしもそれなら大丈夫だと思う……。"
"90001130-166" = "[s] \"本当に危なくなったら、ちゃんと言うことを聞いてくれる？\""
"90001130-167-アリス" = "もちろんです、先生！#n勇者は必ず約束を守ります！"
"90001130-168-アリス" = "……でも、変なお願いだったらどうしましょう？"
"90001130-169-モモイ" = "大丈夫だよ、アリス！#n先生が変な事いうのはいつものことだし！"
"90001130-170-ミドリ" = "まぁ……そうだね。"
"90001130-171-モモイ" = "で、でも……危ないときに変な事は言わないと思うから。"
"90001130-172-アリス" = "そうですね！#n先生、氷河に行く方法を早く教えてください！"
"90001130-173" = "[s5] \"ありがとう、みんな。\"\n[s6] \"モモトークで説明するね。\""
"90001130-174" = "[ns] \"そうだ、最後に伝えておかないと。\""
"90001130-175-ミドリ" = "どうしました？"
"90001130-176" = "[s] \"暖かい格好で来てね。\""
"90001130-177" = "次回;合流"
