[translation]
"52010-1" = "第1話;届かない指先"
"52010-2-百花繚乱の部員" = "……百花繚乱紛争調停委員会1年、[ruby=ごりょう]御稜[/ruby]ナグサ。"
"52010-3-百花繚乱の部員" = "同じく百花繚乱紛争調停委員会1年、[ruby=ななかど]七稜[/ruby]アヤメ。"
"52010-4-百花繚乱の部員" = "両者とも、前へ。"
"52010-5-百花繚乱の部員" = "古来より伝わる百花繚乱のしきたりに従い――"
"52010-6-百花繚乱の部員" = "いざ尋常に――"
"52010-7-百花繚乱の部員" = "勝負！"
"52010-8-ナグサ" = "……隙あり。"
"52010-9-アヤメ" = "そこっ――！！"
"52010-10-ナグサ" = "ぐっ……。"
"52010-11-百花繚乱の部員" = "一本！それまで！"
"52010-12-アヤメ" = "これで201戦、201勝……。"
"52010-13-アヤメ" = "今日もありがと、ナグサ！良い試合だったよ。"
"52010-14-ナグサ" = "うっ……うぅっ……。"
"52010-15-アヤメ" = "な、ナグサ？"
"52010-16-ナグサ" = "また……アヤメに負けちゃった……。"
"52010-17-アヤメ" = "な、泣かないで！ナグサも強かったよ！？"
"52010-18-ナグサ" = "でも……これじゃ、また役立たずになっちゃう。"
"52010-19-ナグサ" = "ずっと……頑張ってきたのに、いつもこう……。#n私はアヤメの足元にも及ばない。"
"52010-20-アヤメ" = "あまり自分を責めないの。"
"52010-21-アヤメ" = "ほら、手。"
"52010-22-アヤメ" = "私はいつでもそばにいるから。#nナグサが転んだら、すぐ手を差し伸べられるように。"
"52010-23-ナグサ" = "……足手まといでも？"
"52010-24-アヤメ" = "もちろん。"
"52010-25-ナグサ" = "……泣き虫でも？"
"52010-26-アヤメ" = "うん。"
"52010-27-ナグサ" = "優柔不断で、一人じゃ何も決められなくて――"
"52010-28-アヤメ" = "大丈夫だよ！#nだって私は――"
"52010-29-アヤメ" = "私は……あんたを友達だと思ったことなんてないから。"
"52010-30-ナグサ" = "……！！"
"52010-31-ナグサ" = "はぁっ……はぁ……っ！#n……夢？"
"52010-32-ナグサ" = "たしかに、アヤメが……そこにいたのに。"
"52010-33-ナグサ" = "……っ！"
"52010-34-ナグサ" = "痛……っ。"
"52010-35-ナグサ" = "腕の中で、炎が渦巻いているみたい……熱い……。"
"52010-36-ナグサ" = "あの時、私がアヤメを止められていれば……。"
"52010-37-ナグサ" = "うぅ……っ。"
"52010-38-ナグサ" = "ごめ……んっ、アヤメ……。"
"52010-39-ナグサ" = "ごめんなさい……っ。"
"52010-40-ナグサ" = "役立たずで、弱虫で……。"
"52010-41-ナグサ" = "こんな私で……。"
"52010-42-ナグサ" = "……ごめんなさい、アヤメ。"
"52010-43" = "次回;新たな怪談"
