[translation]
"52040-1" = "第4話;勘解由小路家の貴人"
"52040-2-ユカリ" = "身共たち[ruby=かでのこうじ]勘解由小路[/ruby]一家は[ruby=いにしえ]、古よ[/ruby]り百鬼夜行内外の名家や組織と、#n信頼を築き上げてきましたの。"
"52040-3-ユカリ" = "百鬼夜行を訪ねた名士のみなさまに食事や居場所を提供し、#nその代わりに一族の問題へのご助力をお願いしていて――"
"52040-4-ユカリ" = "ちょうど今、お世話になっているお医者様が滞在しておりますの。"
"52040-5-キキョウ" = "医者……？"
"52040-6-ユカリ" = "著名なお方ではありませんが、一風変わった医術をお持ちで……#n以前、身共もその方のお薬で病を克服しました。"
"52040-7-ユカリ" = "巫女の責務を放棄した身共が、#n勘解由小路家の力を借りられるかはわかりません。#nですが……。"
"52040-8-ユカリ" = "これも、ナグサ先輩に元気になってもらうためですの！"
"52040-9-ナグサ" = "ごめん、ユカリ。この腕は――"
"52040-10-？？？" = "あら？#n……お嬢様！お帰りになっていたのですか！？"
"52040-11-使用人" = "便りもなく心配しておりました。#nお元気そうで本当によかったです！"
"52040-12-使用人" = "お戻りになったということは、巫女としての御役目を――"
"52040-13-使用人" = "――というわけでは、なさそうですね。"
"52040-14-使用人" = "いらっしゃいませ、ご友人の皆様。"
"52040-15-使用人" = "百花繚乱紛争調停委員会はご多忙であると耳にしていますが……#nどのようなご用向きで？"
"52040-16-ユカリ" = "勘解由小路家の一員として、お願いをしたく参りました。#n厚かましいとは承知していますが……。"
"52040-17-使用人" = "お願い……？ご用命いただければ、すぐにでも――"
"52040-18-ユカリ" = "当家に滞在されている、お医者様のお力を借りたいのです。"
"52040-19-使用人" = "お、お嬢様がお怪我を……！？"
"52040-20-ユカリ" = "診ていただきたいのは、こちらの先輩ですわ。"
"52040-21-ユカリ" = "傷は一刻を争います。どうか、お願いいたしますの。"
"52040-22-使用人" = "……かしこまりました。すぐにお連れします。"
"52040-23" = "（しばらくして……）"
"52040-24-使用人" = "お嬢様、医師をお呼びしました。"
"52040-25-怪しげな医者" = "……おや、こちらが例の急患ですか？"
"52040-26-怪しげな医者" = "ふむ、しばらく薬の調合は控えるつもりだったのですが……。"
"52040-27-怪しげな医者" = "勘解由小路家にはお世話になっておりますから――#nどれ、一肌脱ぐとしましょうか。"
"52040-28-ユカリ" = "まあ！"
"52040-29-レンゲ" = "（この風貌、どこかで……）"
"52040-30-レンゲ" = "あっ！"
"52040-31-キキョウ" = "レンゲ、何か心当たりがあるの？"
"52040-32-レンゲ" = "かっこいいメガネしてるな……！"
"52040-33-キキョウ" = "そこ！？"
"52040-34-リク" = "はじめまして、百花繚乱の皆さん。#nキヴォトス各地で医術を学んでいる旅の医師――リクと申します。"
"52040-35-リク" = "訳あって宿に困っていたところ、#n勘解由小路一家のご厚意に預かり、身を寄せておりまして。"
"52040-36-リク" = "お役に立てるかは分かりませんが、#nこのご恩を返せるのなら、喜んで力をお貸ししましょう。"
"52040-37-ユカリ" = "ありがとうございます……！"
"52040-38-ユカリ" = "診ていただきたいのは、こちらの方の腕ですの。"
"52040-39-リク" = "おっと……外傷ですか。#n専門は内科なのですが――"
"52040-40-リク" = "診てみましょう。包帯を取っていただけますか？"
"52040-41-ナグサ" = "……。"
"52040-42-ユカリ" = "何度見ても……ひどい傷ですの。"
"52040-43-キキョウ" = "傷の見立ては？"
"52040-44-リク" = "これはこれは興味深い……。"
"52040-45-リク" = "腕に痛みはありますか？"
"52040-46-ナグサ" = "……時々。"
"52040-47-リク" = "ならば、[ruby=げんしつう]幻肢痛[/ruby]と呼ばれるものでしょう。"
"52040-48-ナグサ" = "……幻肢痛？"
"52040-49-リク" = "はい、一種の神経疾患です。"
"52040-50-リク" = "身体の一部が欠損もしくは切断された時、#n患部の末端神経に偽りの刺激が加わり、#n存在しないはずの部位に激痛が走る……。"
"52040-51-レンゲ" = "でも……。"
"52040-52-レンゲ" = "ナグサ先輩の腕はちゃんと……。"
"52040-53-リク" = "いいえ、腕はここにありません。"
"52040-54-リク" = "見たところ……数か月ほど前に切断され、#n今は遠いどこかへ放置されている――そんなところでしょうか。"
"52040-55-リク" = "例えば……底しれぬ常闇――「黄昏」の中、とか？"
"52040-56-ナグサ" = "……どうしてそれを。"
"52040-57-リク" = "薬材を集めるために、キヴォトス各地を回っておりまして。"
"52040-58-リク" = "野生の動植物は生まれ育った環境に応じてその姿や効能を変えるもの。#nですが、百鬼夜行の「北部自治区」に生えていたものは、#n特異な性質を持っていました。"
"52040-59-リク" = "一見普通の草でも、その実生きながらにして死んでいる――#n命の息吹を感じられない「影」のような状態。"
"52040-60-リク" = "現地の方々が言っていましたよ、「あれは黄昏に呑まれたんだ」と。"
"52040-61-リク" = "……あなたの腕も、そうなのでは？"
"52040-62-ナグサ" = "……そう。この傷は黄昏の痕だよ。"
"52040-63-レンゲ" = "ヤブじゃなかったんだな……。"
"52040-64-キキョウ" = "……レンゲ。相手は勘解由小路家の客人だよ。少し口を慎んで。"
"52040-65-ユカリ" = "すぐに原因を見抜くだなんて、さすがお医者さまですの！"
"52040-66-ユカリ" = "それで……ナグサ先輩の腕はどうすれば治るんですの？"
"52040-67-リク" = "幻肢痛を完全に治す方法は一つ。失くした体を取り戻すことです。"
"52040-68-リク" = "腕を取り戻すまで、この痛みはずっと続くでしょうね。"
"52040-69-ナグサ" = "やっぱり、あそこに行くしかないのね……。"
"52040-70-ユカリ" = "他に方法はないのでしょうか……？"
"52040-71-リク" = "気休め程度……ではありますが、体操が痛みを和らげるそうです。"
"52040-72-リク" = "病床に伏しがちな[ruby=・]知[/ruby][ruby=・]人[/ruby]が、#n健康のためにと始めた体操があります。#n後ほど、動画をお送りしましょう。"
"52040-73-ナグサ" = "ありがとう。観てみるね。"
"52040-74-リク" = "ですが、これだけは心得ておいてください。"
"52040-75-リク" = "時間はこの傷を癒しません。#nむしろ機を逸するほどに、#n不治のものとして心身を蝕んでいくでしょう。"
"52040-76-リク" = "先延ばしにすることは、あまりおすすめしませんよ。"
"52040-77-ナグサ" = "……。"
"52040-78-リク" = "お大事に。"
"52040-79-レンゲ" = "腕があるのに取り戻せだってさ。謎かけか……？"
"52040-80-キキョウ" = "でもナグサ先輩の言う通り、黄昏が原因の傷なら、#n普通の治療は無意味なんでしょう？"
"52040-81-ユカリ" = "身共も、黄昏に呑まれたものを取り戻す方法なんて聞いたことがありませんわ……。"
"52040-82-ユカリ" = "そもそも「黄昏」や「百物語」だって、#nあの日まではクズノハ様と同じ――#nおとぎ話だと思っていたからね。"
"52040-83-ナグサ" = "あの、聞いてほしい話があるの。"
"52040-84-ナグサ" = "私……まだみんなに言ってないことがある。"
"52040-85-ナグサ" = "恥ずかしくて、怖くて……話せなかった、あの日のこと。"
"52040-86-ナグサ" = "アヤメとの間に何があったのか。#n全部――聞いてくれる？"
"52040-87" = "次回;憧れは記憶の彼方に"
