[translation]
"52080-1" = "第8話;悪夢"
"52080-2-ナグサ" = "……記憶の中のアヤメは、#n朝の日差しのように明るくてあたたかい子だった。"
"52080-3-ナグサ" = "どんなお願いにも嫌な顔一つしない、百花繚乱の委員長。"
"52080-4-ナグサ" = "その笑顔に、みんなが安心させられた。"
"52080-5-アヤメ" = "お祭りの屋台の人手が足りない？任せて！#n一人暮らしが長いし、料理なら慣れてるの。"
"52080-6-アヤメ" = "神木展望台の前で魑魅一座が暴れてるって？#n困った子たちだなぁ。ちょっと行ってくる！"
"52080-7-アヤメ" = "お姉ちゃんとはぐれちゃったの？#n……よしよし、私が探してきてあげるからね！#nいい子だから、ここで待ってて。"
"52080-8-ナグサ" = "みんな、何かあればアヤメを探して、アヤメに頼った。"
"52080-9-ナグサ" = "他の人なら顔をしかめる頼みでも、アヤメはいつも笑ってて――"
"52080-10-アヤメ" = "アヤメ委員長！本日のお稽古も、よろしくお願いします！"
"52080-11-百鬼夜行の生徒" = "アヤメ先輩。今度のお祭りのスローガンなんですが、ネタ切れで……。"
"52080-12-商店街の住民" = "悪いんだけどアヤメちゃん、週末に店番をお願いできないかな……？#n来るはずの子が体調崩しちゃってねぇ……。"
"52080-13-アヤメ" = "うん！まかせて！"
"52080-14-ナグサ" = "それなのに、私ときたら……アヤメに追いつくだけで精一杯だった。"
"52080-15-ナグサ" = "少しでも壁にぶつかると、勝手に涙がこぼれる。#n勝負では一度もアヤメに勝てなかった。"
"52080-16-ナグサ" = "みんなに頼られるアヤメの姿を目にする度に……#n心の中で、口には出せない言葉が反響する。"
"52080-17-ナグサ" = "アヤメがいなければ、何もできない。できるはずがない。"
"52080-18-ナグサ" = "私は、アヤメじゃないから。"
"52080-19-ナグサ" = "百花繚乱の委員長としての資格があるのは、アヤメだけだから。"
"52080-20-ナグサ" = "でも、アヤメはそんな私の気持ちを察して、#nいつも明るい笑顔で手を差し伸べてくれた。"
"52080-21-アヤメ" = "大丈夫だよ、ナグサ。"
"52080-22-アヤメ" = "だって私は――"
"52080-23" = "私は……あんたを友達だと思ったことなんて、ない。"
"52080-24-ナグサ" = "……っ！"
"52080-25-ナグサ" = "はぁ、はぁ……また、夢……。"
"52080-26-ナグサ" = "なんで、ずっとこんな悪夢が……。"
"52080-27-？？？" = "……もう起きちゃったんですかぁ？"
"52080-28-？？？" = "枕が変わると寝つきが悪いたちだったんですねぇ、ナグサちゃん。"
"52080-29-ナグサ" = "……[ruby=やぶき]箭吹[/ruby]シュロ。"
"52080-30-シュロ" = "はいはぁい。手前ですよぉ？"
"52080-31-シュロ" = "こんなところでまた会えるだなんて、不思議な縁ですねぇ？"
"52080-32-シュロ" = "……いえ、ナグサちゃんの方から首を突っ込んできたんでしたっけ？"
"52080-33-シュロ" = "なんでわざわざ、こんな魑魅魍魎のうろつく土地に来たんですかぁ？"
"52080-34-シュロ" = "幼なじみにまた会えるかも……なぁんて、#nおバカな望みを持ってるとかぁ？"
"52080-35-ナグサ" = "……それは、こっちの台詞だよ。"
"52080-36-ナグサ" = "ここで何をしているの？#nこの周辺で見つかっている百物語は、あなたの仕業？"
"52080-37-シュロ" = "どうでしょうねぇ[ruby=ものがたり]？怪談は[/ruby]ネタバレ厳禁ですからぁ。"
"52080-38-シュロ" = "再会の挨拶に、覚めない悪夢をお贈りしたかったですけど……#n起きちゃったならしょうがないですねぇ。"
"52080-39-シュロ" = "悪夢を現実にしてあげますよぉ？"
"52080-40-シュロ" = "アハハッ！#nやっぱりあの時「百蓮」が使えたのは、まぐれじゃないんだぁ！"
"52080-41-シュロ" = "まさかまさかぁ……#n自分がアヤメの代わりに百花繚乱のリーダーになれる……#nまだそんなこと思ってるんですかぁ？"
"52080-42-ナグサ" = "なれるかなれないか、じゃない。"
"52080-43-ナグサ" = "みんなを守るために、私はやるの。#n……委員長のフリだけでも、やってみせる。"
"52080-44-シュロ" = "へぇ～、いいお話ですねぇ。"
"52080-45-シュロ" = "でも……いくら強くなったところで、二人分の働きはできないでしょう？"
"52080-46-シュロ" = "ず～っと襲いかかってくる恐怖に、どれだけ耐えられるんでしょうねぇ。"
"52080-47-シュロ" = "さあ、新しい物語の幕開けといきましょうかぁ？イヒヒッ！"
