[translation]
"52180-1" = "第18話;同床異夢"
"52180-2-レンゲ" = "ふんっ……ぬぬぬぬぬ……！"
"52180-3-レンゲ" = "もう……ちょっとで……！"
"52180-4-レンゲ" = "キキョウ、見てないで手伝えよ！"
"52180-5-レンゲ" = "この鉄格子、あとちょっとで人が通れるくらいの隙間ができ……そうっ！#n……なんだよ……！"
"52180-6-キキョウ" = "そんな無駄なことしないで、ちょっとは体力を温存したら？"
"52180-7-キキョウ" = "あいつらは監視も立ててない……つまり、私たちをここから出さないだけの自信があるってことだよ。"
"52180-8-レンゲ" = "だからってじっとしてろってか！？#nやれることは試してみないとだろ！？"
"52180-9-キキョウ" = "はぁ……今、脱出方法を考えてるところなんだけど。#nみんながあんたみたいに、気合と根性で解決するタイプじゃないの。"
"52180-10-キキョウ" = "そもそも最初から[ruby=・]あ[/ruby][ruby=・]の[/ruby]アヤメを信じなければ……。"
"52180-11-レンゲ" = "それは、そうだけど……。"
"52180-12-レンゲ" = "な、何か考えがあるなら言ってくれよ！"
"52180-13-キキョウ" = "集中したいからちょっと黙ってて！"
"52180-14-レンゲ" = "なっ、キキョウお前――！"
"52180-15-ユカリ" = "き、キキョウ先輩、レンゲ先輩！落ち着いてくださいまし！"
"52180-16-ユカリ" = "今は言い争っている場合では……！"
"52180-17" = "[ns1] \"なんだか騒がしいね……。\"\n[ns2] \"……私、どれくらい寝てたんだろう。\""
"52180-18-ユカリ" = "[USERNAME]先生！"
"52180-19-ユカリ" = "師匠！"
"52180-20-ユカリ" = "先生、大丈夫？怪我はない？"
"52180-21" = "[s3] \"うん、ちょっと頭は痛いけど平気。\"\n[s4] \"みんなも怪我はない？\""
"52180-22-ユカリ" = "ああ。こっちは軽い擦り傷程度だよ。"
"52180-23-ユカリ" = "百花繚乱たるもの、この程度へっちゃらですの！"
"52180-24" = "[ns] \"ここは……？\""
"52180-25-ユカリ" = "ここは「彼岸邸」の地下。"
"52180-26-ユカリ" = "私たちは花鳥風月部との戦闘に負けて……ここに連れてこられた。"
"52180-27-ユカリ" = "勘解由小路家の地下にも似たような倉庫がありますが……それを牢屋として使っているなんて。"
"52180-28-ユカリ" = "ちっ、アイツらに銃弾が通ればな……。"
"52180-29" = "[s5] \"花鳥風月部……？\"\n[s6] \"何があったの？\""
"52180-30-ユカリ" = "結論から言えば――"
"52180-31-キキョウ" = "北部自治区であの女から見聞きしたことは、全部ウソだったってこと。"
"52180-32" = "（気絶していた時の出来事を説明してもらった）"
"52180-33" = "[ns] \"……まさか、アザミが花鳥風月部の一人だったなんて。\""
"52180-34-ユカリ" = "ええ。あの優しそうな会長さんが……しょっくです。"
"52180-35-ユカリ" = "最初から私たちを騙すための芝居だったんだよ。#nあの笑顔、思い出すだけで寒気がする。"
"52180-36-ユカリ" = "じゃあエビス分校の自治区も、住民もニセモノだったってことか……？"
"52180-37-ユカリ" = "いや、あの人たちは関係ないんじゃないかな。"
"52180-38-ユカリ" = "いくら百物語が強力だとしても、お祭りに使われる食材までは作り出せないと思うよ。"
"52180-39-ユカリ" = "それに、一部の人は[ruby=はぶ]土生[/ruby]アザミに対して初対面みたいな反応だったし。"
"52180-40" = "[s] \"じゃあ……アヤメもニセモノだったのかな？\""
"52180-41-ユカリ" = "それなんだけどさ……。"
"52180-42-ユカリ" = "私たちも気になって、アヤメ先輩と最後まで一緒だったナグサ先輩に聞いてみたんだけど……。"
"52180-43-ユカリ" = "でも、何があったのかまでは……。#nナグサ先輩、ずっと塞ぎ込んでしまっておりまして。"
"52180-44" = "[ns7] \"……大丈夫？\"\n[ns8] \"どこか具合でも悪い？\""
"52180-45-ナグサ" = "……大丈夫。"
"52180-46-ナグサ" = "ごめんなさい……私が未熟だから、みんなを危険な目に遭わせた。"
"52180-47-レンゲ" = "先輩は何も悪くないだろ！全部花鳥風月部のせいだって！"
"52180-48-レンゲ" = "ええ、ナグサ先輩は皆のために最善を尽くしていましたわ！"
"52180-49-キキョウ" = "いま自分を責めてもしょうがないでしょ。"
"52180-50-キキョウ" = "この事態を招いたのはあんたじゃなくてアヤメ先輩でしょ？"
"52180-51-ナグサ" = "……ううん、アヤメのせいじゃない。#n彼女は間違ってないの。"
"52180-52-キキョウ" = "は？"
"52180-53-ナグサ" = "結局私が、アヤメを理解できていなかったから――"
"52180-54-？？？" = "そうですよねぇ。都合のいい夢に甘えてた、[ruby=てめぇ]手前[/ruby]のせいですよぉ。#nねっ、ナグサちゃん？"
"52180-55-キキョウ" = "[ruby=やぶき]箭吹[/ruby]シュロ……！"
"52180-56-キキョウ" = "あはっ、アハハハッ！"
"52180-57-シュロ" = "何ですかぁ、その無様な姿。"
"52180-58-シュロ" = "あの時の威勢のよさは、どこ行っちゃったんですぅ？"
"52180-59-シュロ" = "まさかぁ……優しい優しいアヤメがニセモノだなんて思ってなかったんですぅ？#n夢にまで見た親友を、間違えちゃったんですかぁ？"
"52180-60-シュロ" = "……ウソばっかり。"
"52180-61-シュロ" = "都合の悪い現実に、蓋をしてただけですよねぇ？"
"52180-62-キキョウ" = "そう……じゃあ、私たちが会ったアヤメ先輩は本物じゃなかったんだね。"
"52180-63-シュロ" = "ええ、そうですよぉ？"
"52180-64-シュロ" = "仲間の危機に颯爽と駆けつけて、感動の再会を果たす親友だなんてぇ……ご都合主義も大概にしてくださいよぉ？"
"52180-65-シュロ" = "あのアヤメ……いえ、「アレ」は、怪書「[ruby=とうていぶっかいろく]稲亭物怪録[/ruby]」から生まれた、ナグサちゃんの「恐怖」なんですよぉ！"
"52180-66-ユカリ" = "で、でも、あのお方はとても明るくて……恐怖だなんてとてもそんな風には。"
"52180-67-シュロ" = "相変わらず、なぁんにも知らないんですねぇ？"
"52180-68-シュロ" = "恐怖は、ときに[ruby=・]幸[/ruby][ruby=・]せ[/ruby]の姿をしてやってくるんですよぉ？"
"52180-69-シュロ" = "心の中でずぅっと否定してきた、夢みたいな幸せ。#nそれが現実になるほど恐いことなんて、ないですよねぇ？"
"52180-70-シュロ" = "偽りの幸せを享受すればするほど……残酷な現実がくっきり浮かび上がるんですから。"
"52180-71-ナグサ" = "っ……。"
"52180-72-シュロ" = "だ～か～らぁ、あなたはアヤメの代わりになれないんですよ、ナグサちゃん。"
"52180-73-レンゲ" = "お前にナグサ先輩の何がわかるんだよ！？"
"52180-74-シュロ" = "アハッ！ムキになっても無駄ですよぉ？"
"52180-75-シュロ" = "いくら泣いたって怒ったって、現実は変わらないんですからぁ。"
"52180-76-シュロ" = "手前らがいくら努力したって、あのアヤメの足元にも及びませんよぉ？"
"52180-77-シュロ" = "どうせ、いつかは捨てられる消耗品に、何一つできやしないんですから！"
"52180-78" = "[s] \"シュロ、一つ聞きたいんだけど。\""
"52180-79-シュロ" = "何ですかぁ？"
"52180-80-シュロ" = "もう屁理屈は聞き飽きてますよぉ。"
"52180-81-シュロ" = "負け犬の遠吠えなんて、手前には響きませんしぃ？"
"52180-82" = "[s9] \"最初から、全部知ってたんだよね？\"\n[s10] \"あの時アヤメに撃たれたのも、演技だったのかな。\""
"52180-83-シュロ" = "……はぁ？"
"52180-84-シュロ" = "そんなくだらないことが聞きたかったんですぅ？手前、興醒めなんですけど？"
"52180-85-シュロ" = "当然でしょう？全部ぜ～んぶ、手前さん方を捕まえるためのお芝居だったんですから。"
"52180-86-シュロ" = "アレに捕まったのも、手前さん方を彼岸邸に誘い出したのもぉ……。"
"52180-87-シュロ" = "……え？"
"52180-88-シュロ" = "……シャーレの先生？"
"52180-89-シュロ" = "手前様を盾にしたのも、全部、全部――"
"52180-90-シュロ" = "……っ、コクリコ様のための演技だったんですからぁ！"
"52180-91" = "[ns11] \"捕まっといて言うことでもないし……。\"\n[ns12] \"それに、もう聞き飽きてるかもしれないけど……。\""
"52180-92" = "[ns13] \"……自分以外の何かを演じるのは、悪いことじゃない。\"\n[ns14] \"誰だってすることだからね。\""
"52180-93" = "[ns] \"でも、だからこそ……自分がした行動に目を背けないで。\""
"52180-94" = "[ns] \"シュロは、シュロのすべきことをしたんだよね？\""
"52180-95-シュロ" = "は、ハハッ……何を言うかと思えばぁ。"
"52180-96-シュロ" = "それっぽいこと言って、手前を引き入れようって魂胆ですかぁ？"
"52180-97-シュロ" = "助けられたからって、コクリコ様を裏切るとでもぉ？"
"52180-98-シュロ" = "ほんっと、頭お花畑なんですねぇ……。"
"52180-99-シュロ" = "幼稚でくだらない、おままごとみてぇな発想……。"
"52180-100-シュロ" = "全部、[ruby=てめえ]手前[/ruby]らが信じるクズノハと同じ、くだらないくだらない妄想ですよぉ！"
"52180-101-ナグサ" = "……クズノハ。"
"52180-102-ナグサ" = "……あの時どうして私を助けたのかな。"
"52180-103-ナグサ" = "どうして、アヤメじゃなくて私を……あのまま放っておいてくれたらよかったのに……。"
"52180-104-シュロ" = "は？何言ってるんです？"
"52180-105-シュロ" = "まるで本当にクズノハと会ったかのような……。"
"52180-106" = "[s15] \"クズノハはただのおとぎ話じゃないよ。\"\n[s16] \"私も前に、ナグサからクズノハの手紙をもらったんだ。\""
"52180-107-シュロ" = "クズノハが……いるっていうんですかぁ？"
"52180-108-シュロ" = "全ての怪書の始まりであり、百花繚乱の初代委員長――大預言者クズノハが？"
"52180-109-シュロ" = "そんな世迷言……手前をからかってるんですね？#nでしたら――！"
"52180-110-シュロ" = "いや、でも……。"
"52180-111-シュロ" = "コクリコ様は、あの時ナグサは大雪原のど真ん中にいたって……それなのに、生きて帰ってきてる。"
"52180-112-シュロ" = "獣も寄りつかない大雪原で、誰がナグサを……？"
"52180-113-シュロ" = "それに、シャーレの先生は……屁理屈をこねても嘘はつかない……。"
"52180-114-シュロ" = "本当に大預言者クズノハが……黄昏の寺院にいるのなら……。"
"52180-115-シュロ" = "失くした「稲生物怪録」の代わりの怪書が作れる……？#nそうしたら……コクリコ様だって、もっと手前を……。"
"52180-116-シュロ" = "……本当に本当に残念でしたねぇ、ナグサちゃん。#n針のむしろに座ってる気分でしょう？"
"52180-117-シュロ" = "ああ、可哀想なナグサちゃん。#n心の底から同情しちゃいますぅ。"
"52180-118-シュロ" = "そんなナグサちゃんに……優しい優しい手前が機会を差し上げましょうかぁ？"
"52180-119-ナグサ" = "……機会？"
"52180-120-シュロ" = "ナグサちゃんは、なんとしてでも助けたい存在がいるのでしょう？"
"52180-121-シュロ" = "だったら、また会えばいいんですよぉ……クズノハに。"
"52180-122" = "次回;彼岸の記憶"
