[translation]
"52190-1" = "第19話;彼岸の記憶"
"52190-2-シュロ" = "こっちに本当に「黄昏の寺院」があるんですかぁ？"
"52190-3-ナグサ" = "……うん、合ってるよ。"
"52190-4-ナグサ" = "こんな雪原でも、道しるべはあるから。"
"52190-5-ナグサ" = "雪の降り積もった木々に、凍りついた川――あの丘も。"
"52190-6-ナグサ" = "あのときの風景と……同じ。"
"52190-7-シュロ" = "ナグサちゃんの妙に細かいとこ、こういう時は役に立ちますねぇ。"
"52190-8-シュロ" = "さ、行きましょうかぁ。"
"52190-9-ユカリ" = "……あいつ、なんか変なもんでも食ったのか？"
"52190-10-ユカリ" = "いきなりアタシらを解放して……何企んでるのやら。"
"52190-11-キキョウ" = "さあね。でも、花鳥風月部は信用ならない。"
"52190-12-キキョウ" = "裏があるのは確かだよ。"
"52190-13-ユカリ" = "身共もそう思います……元は百鬼夜行に混乱を招いた相手ですもの。信用できませんわ。"
"52190-14-キキョウ" = "ただ……なんとなくだけど、独断で動いてるような気がする。"
"52190-15-キキョウ" = "もしかしたら、花鳥風月部の監視の目から抜け出せるかもしれない。"
"52190-16-シュロ" = "おやおやぁ？まさか、逃げようだなんて思ってませんよねぇ？"
"52190-17-シュロ" = "くだらないことは考えないでくださいねぇ？#nいくら足が速くても、手前からは逃れられませんよぉ？"
"52190-18-シュロ" = "それに……ついつい銃口が先生の頭に向いちゃう――#nなぁんてことも、あるかもしれませんし？"
"52190-19-キキョウ" = "……ふん。"
"52190-20" = "[ns] \"あ、私が人質だったの？\""
"52190-21-シュロ" = "はぁ？"
"52190-22-シュロ" = "生徒を言葉一つで操る癖に、#n銃弾の一発にも耐えられないですよぉ？#nみーんな、真っ先に手前様を狙うに決まってますぅ。"
"52190-23-シュロ" = "そのクセ、自分の身も顧みず飛び込んで。本当に……。"
"52190-24-シュロ" = "……本当に、愚か。"
"52190-25" = "[s] \"誰かを守るのに、自分の強さは関係ないよ。\""
"52190-26-シュロ" = "はぁ、またそれですか……。"
"52190-27-シュロ" = "自分の身も守れない弱者が、誰かを庇うだなんて……それ、本当に意味ありますぅ？#n庇う相手よりも先に崩れ落ちて、終わりじゃないですか。"
"52190-28-シュロ" = "どういう理屈で、そんなことするんですぅ？#n意味不明なんですけど？"
"52190-29" = "[s1] \"前にも言ったけど、危険な目に遭っている子を見て体が動くのは……。\"\n[s2] \"合理的か、普通かの以前に。\"\n[s3] \"人として当然のことだから。\""
"52190-30-シュロ" = "当……然……？"
"52190-31-シュロ" = "そんなの……。"
"52190-32-シュロ" = "当然なわけないでしょう！"
"52190-33-ユカリ" = "はぁ、はぁ……。"
"52190-34-シュロ" = "本当に本当にくだらない……。"
"52190-35-シュロ" = "とっとと黄昏の寺院に行きますよぉ……。#n逃げようだなんて、考えないでくださいね？"
