[translation]
"52210-1" = "第21話;視線"
"52210-2-アヤメ" = "百花繚乱にいた頃の私は、いつも皆の視線を集めていた。"
"52210-3-アヤメ" = "ねえねえ、アヤメ。"
"52210-4-アヤメ" = "あの……アヤメ先輩……。"
"52210-5-アヤメ" = "アヤメ委員長だ！"
"52210-6-アヤメ" = "憧れと羨望に満ちた視線が、私を縛りつけていった。"
"52210-7-アヤメ" = "「百花繚乱の委員長」の仮面を外せなくなっただけじゃない。#nその仮面が重いことも、私を傷つけ始めていることも、誰にも知られてはならなかった。"
"52210-8-アヤメ" = "花々も羨むあの凛としたお姿……本当に素敵ですよね、アヤメ委員長。"
"52210-9-アヤメ" = "容姿端麗で品行方正……。"
"52210-10-アヤメ" = "百花繚乱のリーダーたるもの、あれくらい才色兼備な方でないと……。"
"52210-11-アヤメ" = "こ、これくらいのお願いで……。"
"52210-12-アヤメ" = "……気を悪くなんて、しないよね？"
"52210-13-アヤメ" = "平気平気！だって、アヤメ委員長だよ？"
"52210-14-アヤメ" = "うん、大丈夫！なんでも言ってね！"
"52210-15-アヤメ" = "――そんなの嘘。"
"52210-16-アヤメ" = "張りついた笑顔の仮面は、私を苦しめ続けていた。#nみんなの声に応えれば応えるほど、期待と憧れの視線は増えていって……何度も、私の顔を作り変える。"
"52210-17-アヤメ" = "いつも笑っていて、眉根を寄せることなんてない。#n不機嫌になるなんてもってのほか。"
"52210-18-アヤメ" = "困った時にはいつでも駆けつける。#n誰もが目を背けたくなるようなことだって、全部向き合って。"
"52210-19-アヤメ" = "それでも、疲れて立ち止まってしまう日はあった。#nそんな時は――"
"52210-20-アヤメ" = "今日は委員長らしくないですね。"
"52210-21-アヤメ" = "何かあったのですか？"
"52210-22-アヤメ" = "少し休めば、[ruby=・]い[/ruby][ruby=・]つ[/ruby][ruby=・]も[/ruby][ruby=・]の[/ruby][ruby=・]委[/ruby][ruby=・]員[/ruby][ruby=・]長[/ruby]に戻れますって！"
"52210-23-アヤメ" = "……いつの間にか、みんなは[ruby=・]仮[/ruby][ruby=・]面[/ruby]を本当の私だと思うようになった。"
"52210-24-アヤメ" = "私はどうしてこの仮面を着けたんだろう。"
"52210-25-アヤメ" = "みんな、どうしてこの仮面が私だと思ったんだろう。"
"52210-26-アヤメ" = "どうして、自分で解決できないんだろう……？"
"52210-27-アヤメ" = "私、アヤメ委員長みたいに上手くできなくて……。"
"52210-28-アヤメ" = "アヤメ委員長は、何でもできてすごいですっ！"
"52210-29-アヤメ" = "それができるのは、委員長だけですよ！"
"52210-30-アヤメ" = "これが仮面なのか、本当の顔なのか……次第に分からなくなっていった。"
"52210-31-アヤメ" = "でも、闇の中で影と向き合った時に――百蓮の力を使えないことに気づいた。#n……気づいてしまった。"
"52210-32-アヤメ" = "自分は、完璧なんかじゃない。"
"52210-33-アヤメ" = "それは委員長として許されることじゃない――なのに、胸をなで下ろす「私」もいた。"
"52210-34" = "[log=아야메 황혼 1]当然だよ。[/log]"
"52210-35" = "[log=아야메 황혼 1]仮面は、所詮仮面。[/log]"
"52210-36" = "[log=아야메 황혼 1]私じゃないんだから。[/log]"
"52210-37" = "[log=아야메 황혼 1]この責任は――[/log]"
"52210-38" = "[log=아야메 황혼 1]私のものじゃないんだから。[/log]"
"52210-39-アヤメ" = "でも、クズノハ様なら……全部解決してくれるはず。"
"52210-40-アヤメ" = "うんざりするような頼み事も、みんなの視線も――クズノハ様なら、代わりに引き受けてくれるんだ。"
"52210-41-ナグサ" = "もう帰ろうよ。"
"52210-42-ナグサ" = "クズノハ様なんて、いない。ただの言い伝えで――"
"52210-43-ナグサ" = "あの子は、迷わずそう言った。"
"52210-44-ナグサ" = "泣き虫のくせに。"
"52210-45-ナグサ" = "一度も私に勝てなかったくせに。"
"52210-46-ナグサ" = "へばりつく視線から逃げられず、仮面も外せなかったくせに。"
"52210-47-アヤメ" = "…………。"
"52210-48-アヤメ" = "……バカな女。"
"52210-49-アヤメ" = "だからいつまでも、[ruby=・]そ[/ruby][ruby=・]こ[/ruby]から出られないんだよ。"
"52210-50-アヤメ" = "何か心配事でも？"
"52210-51-アヤメ" = "少し、昔を思い出してたの。"
"52210-52-アヤメ" = "私を頼った、みんなのこと。"
"52210-53-アザミ" = "ふむ？"
"52210-54-アヤメ" = "私を求める……みんなの視線。"
"52210-55-アヤメ" = "[ruby=ここ]百鬼夜行[/ruby]の連中は相変わらずだね。"
"52210-56-アヤメ" = "みんな失敗や後悔を恐れて、誰かにやってもらおうとする。"
"52210-57-アヤメ" = "でも、いつまでも見守ることなんて……できない。"
"52210-58-アヤメ" = "結局、みんなの視線に応えられなかったんだ……私は。"
"52210-59-アザミ" = "今のあなたならできるのでは？"
"52210-60-アザミ" = "心に秘めし後悔と憎悪が、華やかに咲き誇る今の[ruby=あなた]怪談[/ruby]に、できないことなど。"
"52210-61-アヤメ" = "……そうだね。"
"52210-62-アヤメ" = "応えるのは、もうおしまい。"
"52210-63-アヤメ" = "今度は、みんなが私に見られる番。"
"52210-64-アザミ" = "ああぁ……っ！美しい……。"
"52210-65-アザミ" = "そう、これこそ私の求めていた光景……！"
"52210-66-アザミ" = "やはり私は、間違っていなかった。"
"52210-67-アザミ" = "いかにおぞましい異形といえど、対峙しなければ所詮は[ruby=ひとごと]他人事[/ruby]。#n恐怖を与える相手にも、限りがあります。"
"52210-68-アザミ" = "ですが……この「[ruby=とうていぶっかいろく]稲亭物怪録[/ruby]」から生まれし百物語は、性質が違う。悍ましい絵画のように新鮮な恐怖を人々へと注いでくれるのですよ。"
"52210-69-アザミ" = "どこへ逃げようと、へばりつく視線からは逃れられない。"
"52210-70-アザミ" = "嗚呼……この美しき百物語を何と呼びましょう。"
"52210-71-アザミ" = "――数多の目が咲き乱れる中、たどり着く先は唯一の恐怖。"
"52210-72-アザミ" = "そう……「ヒトツメ」とでも呼びましょうか。"
"52210-73-アザミ" = "アヤメ……いいえ、ヒトツメよ。"
"52210-74-アザミ" = "誰かに縋りつくことしかできず、あなたを縛りつけていた者たちに――その想いを味わわせる日がきた。"
"52210-75-アザミ" = "他人の視線に怯える者には、瞬きすら許されないということを教えてあげなさい。"
"52210-76-アヤメ" = "…………。"
"52210-77" = "次回;祭りは続く"
