[translation]
"1202-1" = "Maid&Made（１）"
"1202-2-？？？" = "……あれ、"
"1202-3-？？？" = "誰もいないの？"
"1202-4-？？？" = "あ、ドア開いてる。"
"1202-5-？？？" = "入るわよ？"
"1202-6" = "C&Cの部室"
"1202-7-ユウカ" = "あら、いるなら返事してくれれば良かったのに。"
"1202-8-カリン" = "あっ……。"
"1202-9-ユウカ" = "「あっ」って、もしかして私、本当にどこに行っても歓迎されないのかしら……？立場上仕方ないのだけど……。"
"1202-10-カリン" = "ああいや、すまない。そういう意味ではなくって、ただ急な来訪で驚いてというか……。"
"1202-11-アカネ" = "あら、ユウカ。"
"1202-12-アカネ" = "今日は何か、"
"1202-13-アカネ" = "依頼でも？"
"1202-14-アカネ" = "もし任務の件でしたら、ちょっと今はネル先輩が不在で……何か伝言でもしておきますか？"
"1202-15-ユウカ" = "ううん、大丈夫よ。今日来たのは任務じゃなくて……"
"1202-16-ユウカ" = "いや、捉えようによっては任務かもだけど……。"
"1202-17-ユウカ" = "普段の任務とは別で、お願いしたいことがあって。"
"1202-18" = "お願いしたいこと……？珍しいな、どういう内容？"
"1202-19-ユウカ" = "うーん、何て言ったら良いのかしら……。"
"1202-20-ユウカ" = "依頼であっても任務ではない……うん、やっぱり「お願いしたいこと」っていう表現が、一番合ってるかもしれない。"
"1202-21-カリン" = "ますます分からなくなってきたな……。"
"1202-22-アカネ" = "依頼であっても任務ではない……"
"1202-23-アカネ" = "なるほど、何だか複雑そうなお話ですね？"
"1202-24-ユウカ" = "あ、いやその、本当に大したことじゃないの。"
"1202-25-ユウカ" = "今、お祭りを開く準備が進んでるのは知ってるわよね？"
"1202-26-カリン" = "ああ、電気街の話か。"
"1202-27-カリン" = "そういえば生徒たちが主催でお祭りをするとか、どこかで聞いたような気がする。"
"1202-28-ユウカ" = "そう。"
"1202-29-ユウカ" = "それでお祭りとして盛り上げるために、色んなコンセプトのカフェを開こうとしてるのだけど……。"
"1202-30-カリン" = "……だけど？"
"1202-31-ユウカ" = "だけど……"
"1202-32-ユウカ" = "結局その、ミレニアムの生徒たちが大半だから……。"
"1202-33-ユウカ" = "「色んなコンセプト」も何も、変に偏ってるって言うか……。"
"1202-34-アカネ" = "ああ、なるほど……ふふっ、だいたい分かりました。"
"1202-35-ユウカ" = "コーディング体験とか、工学実験とか……どれもこれも、お客さんが集まりそうにないものばっかりで。"
"1202-36-ユウカ" = "百鬼夜行やトリニティのお祭りは相当盛り上がるのに、どうしてうちの学園はこう……。"
"1202-37-ユウカ" = "それで、不安に思った電気街の方からセミナーに連絡があったの。何か代案があった方が良いんじゃないかって……。"
"1202-38-ユウカ" = "ここまでセミナーの管轄なのかしらって気持ちはさておき、とりあえずミレニアム自治区内の話ではあるから、何もしないわけにもいかなくて……。"
"1202-39-アカネ" = "な、なるほど……。"
"1202-40-アカネ" = "お話は分かりました。ただ、どうしてそれで私たちのところに……？"
"1202-41-ユウカ" = "それは、"
"1202-42-ユウカ" = "その……。"
"1202-43-ユウカ" = "C&C、同時にメイド部である皆さんを見込んで、お願いしたいのですが……。"
"1202-44-カリン" = "どうして急に敬語に……。"
"1202-45-アカネ" = "な、何だか嫌な予感が……。"
"1202-46-ユウカ" = "それ、れっきとしたメイド服よね？"
"1202-47-ユウカ" = "偽装で、色んな機能もあるとしても、メイド服であることに変わりは無いわよね？"
"1202-48-ユウカ" = "それに、今までその格好のままメイドカフェに潜入したことも何度かあるわよね？"
"1202-49-アカネ" = "まあ、それはそうですね……？"
"1202-50-カリン" = "そ、そんなこともあったな……。"
"1202-51-ユウカ" = "だからその、一週間で良いから、この間の埋め合わせとかそういうものだと思って……"
"1202-52-ユウカ" = "C&Cでメイドカフェ、やってくれないかしら……？"
"1202-53" = "（１時間後……）"
"1202-54-ネル" = "はあぁぁぁっ！？"
"1202-55-ネル" = "メイドカフェ！？何言ってんだバカ！？意味分かんねぇ！！"
"1202-56-ネル" = "普段メイド服着てるからって、本物のメイドだとでも思われてんのか！？"
"1202-57-ネル" = "それはまあ、普段からメイド服を着てたら普通はメイドだと思われるでしょうけど……。"
"1202-58-カリン" = "でも、それは逆に良いことでもある。"
"1202-59-カリン" = "メイドとしてのイメージを植え付けることに成功してるわけだから。"
"1202-60-ネル" = "ざっけんな！却下だ却下！"
"1202-61-ネル" = "セミナーんとこ行って今すぐ断ってこい！"
"1202-62-アカネ" = "いえ、実はその……。"
"1202-63-ネル" = "……？"
"1202-64-ネル" = "んだよ、はっきり言え。ってかさっさと行ってこい。"
"1202-65-カリン" = "もうすでに依頼は受諾した。"
"1202-66-カリン" = "セミナー側で、すでに諸々の予算も組んでくれたらしい。"
"1202-67-カリン" = "それにもう引き下がれない。契約のサインもしたから、もし取り消したら色々と問題になる。"
"1202-68-ネル" = "……は？"
"1202-69-ネル" = "え、はぁ？何で今回に限って契約？どうして急にそんなしっかりしてんだよ……？"
"1202-70-ネル" = "……ってか待て。おい、なんだよサインって。"
"1202-71-ネル" = "あたしサインしてねぇぞ！？どういうことだ！？"
"1202-72" = "私がやっておいたよ！！"
"1202-73-カリン" = "……。"
"1202-74-カリン" = "……。"
"1202-75-アスナ" = "……え？なになに？"
"1202-76-アスナ" = "どうかした？サインはちゃんとしたよ！"
"1202-77-ネル" = "てんめっ……！"
"1202-78-ネル" = "いや、まぁ、そうか……。"
"1202-79-アカネ" = "……そう、ですね。"
"1202-80-アカネ" = "ネル先輩が不在の時はアスナ先輩が決める……そういうルールでしたので……。"
"1202-81-ネル" = "はぁぁぁ……ったくよぉ……。"
"1202-82-アスナ" = "え、サインしちゃダメだった？"
"1202-83-アスナ" = "どうして？"
"1202-84-アスナ" = "すっごい面白そうだったよ！それに、売り上げも一部貰えるんでしょ？部長も一緒にやろ、メイドカフェ！"
"1202-85-ネル" = "やるかバカ！"
"1202-86-ネル" = "ってか何も面白くねぇよ！？"
"1202-87-ネル" = "そんなことないよ、きっと楽しいって！"
"1202-88-アカネ" = "ネル先輩、諦めよう。こうなったらもうアスナ先輩はてこでも動かない。"
"1202-89-アカネ" = "そうですね、取り合えずやることは決定として、その先のことを考えた方が良さそうです。"
"1202-90-ネル" = "はぁ……。"
"1202-91-ネル" = "ったく……てめぇらはいつもいつもそうやって、面倒ごとをっ！！！"
