[translation]
"1009202-1" = "美的感覚"
"1009202-2" = "（ヨシミと約束した場所に来た）"
"1009202-3-ヨシミ" = "コーデは大切なんだから。#n先生も真面目に見なさいよね。"
"1009202-4-ヨシミ" = "間違っても、変な動物の服とか水着を選ばないでよ？"
"1009202-5" = "[s1] \"そういうのを選ぶと思われてるんだ……。\"\n[s2] \"いやいや、そんな事はしないよ。\""
"1009202-6-ヨシミ" = "ふんっ、一応言っておかないと。#n何するか分かったもんじゃない。"
"1009202-7-ヨシミ" = "……ま、とにかく行くわよ。"
"1009202-8-ヨシミ" = "選ぶのは私がやるから、意見をちょうだい。"
"1009202-9-ヨシミ" = "まずはジャケット……"
"1009202-10-ヨシミ" = "その次は、えっと……。"
"1009202-11-ヨシミ" = "コンセプトを合わせないとだから、スカートと靴も要るわね。#n色違いで揃えたら可愛いかも。"
"1009202-12-ヨシミ" = "Ｔシャツは、後からバンドのロゴを入れるから無地で……。"
"1009202-13-ヨシミ" = "あとは、アクセサリーと……。"
"1009202-14-ヨシミ" = "……ん？何よ？"
"1009202-15-ヨシミ" = "……センス有る？"
"1009202-16-ヨシミ" = "そ、そう……？#nあ、ありがと。"
"1009202-17-ヨシミ" = "……ちょっと待った。"
"1009202-18-ヨシミ" = "それってつまり、前まではセンス無いと思ってたってこと？"
"1009202-19-ヨシミ" = "ねぇ、そういうことよね？"
"1009202-20-ヨシミ" = "確かに手先は器用じゃないけど、それとこれとは……。"
"1009202-21-ヨシミ" = "ま、他のみんなに比べたら少しはマシなんじゃない？"
"1009202-22-ヨシミ" = "……？"
"1009202-23-ヨシミ" = "他のみんなを呼ばなかった理由……？"
"1009202-24-ヨシミ" = "それは、その……。"
"1009202-25" = "[ns3] \"ごめん。もしかして変な質問だった？\"\n[ns4] \"答えにくかったら聞かなかったことに……。\""
"1009202-26-ヨシミ" = "はぁ……。"
"1009202-27-ヨシミ" = "ほんと察し悪いわね。ちょっと考えたら分かるでしょ？"
"1009202-28-ヨシミ" = "あいつらを呼んだら――"
"1009202-29-ヨシミ" = "うっ、考えるだけで頭痛くなってきた……。"
"1009202-30-ヨシミ" = "はあぁ……。"
"1009202-31" = "[s5] \"だ、大丈夫！？\"\n[s6] \"なんかごめん……。\""
"1009202-32-ヨシミ" = "……本当に何も知らないのね。"
"1009202-33-ヨシミ" = "呼ばなかったんじゃなくて、呼んじゃダメなの。"
"1009202-34-ヨシミ" = "絶対大変なことになるから。"
"1009202-35-ヨシミ" = "断言できるわ。"
"1009202-36-ヨシミ" = "ほんと、センスが壊滅的なのよ……"
"1009202-37-ヨシミ" = "具体的に言うと――"
"1009202-38-ヨシミ" = "「明後日方向のファッション」とか、「ミント＆チョコまみれファッション」とか、#n「バンギャ風のファッション」とか、もしかして見たいわけ？"
"1009202-39" = "[ns7] \"……。\"\n[ns8] \"……なるほど。\""
"1009202-40" = "[ns9] \"理解しました……。\"\n[ns10] \"一旦聞かなかったことにするね……。\""
"1009202-41-ヨシミ" = "別に大丈夫よ、本人たちにも言ってるし。"
"1009202-42-ヨシミ" = "だからこうして先生に頼ってるの。"
"1009202-43-ヨシミ" = "まぁ、そういうことだから。#nそれじゃ、気を取り直して……"
"1009202-44-ヨシミ" = "これとこれを合わせて……。"
"1009202-45-ヨシミ" = "……うーん……こんなものかしら？"
"1009202-46" = "[s11] \"大体は揃ったかな？\"\n[s12] \"一回全部合わせてみたら？\""
"1009202-47-ヨシミ" = "んー……。"
"1009202-48-ヨシミ" = "確かに一回全部合わせてみたら、後はカラバリ揃えるだけでいいし……。"
"1009202-49-ヨシミ" = "そうね……。"
"1009202-50-ヨシミ" = "ここでちょっと待ってて、試着してくるから。"
"1009202-51-ヨシミ" = "……。"
"1009202-52-ヨシミ" = "大体イメージ通りなんだけど……。"
"1009202-53-ヨシミ" = "ど……どう？#n全体のバランスとか……。"
"1009202-54-ヨシミ" = "か……可愛い？"
"1009202-55-ヨシミ" = "ほ、本気で思ってる？#nもし[ruby=からか]揶揄[/ruby]ってるなら――"
"1009202-56" = "[ns13] \"本当に可愛いよ。\"\n[ns14] \"冗談じゃなく、本当に。"
"1009202-57-ヨシミ" = "そ、そう？#nなら良いんだけど……。"
"1009202-58-ヨシミ" = "……ふぅん。"
"1009202-59-ヨシミ" = "ちょっとオーバーサイズ気味だけど……まぁこれは許容かな。"
"1009202-60-ヨシミ" = "んー……。"
"1009202-61-ヨシミ" = "よし、じゃあこれで。"
"1009202-62-ヨシミ" = "あ、でも4人分だと結構かさばるわね。持ち帰ろうにも……。"
"1009202-63-ヨシミ" = "……え？"
"1009202-64-ヨシミ" = "……手伝ってくれるの？"
"1009202-65" = "[s15] \"そのために来たようなものだし。\"\n[s16] \"大人だからね。\""
"1009202-66-ヨシミ" = "え、えぇ……？"
"1009202-67-ヨシミ" = "べ、別に私は、そんなつもりで呼んだわけじゃないけど……。"
"1009202-68-ヨシミ" = "……結構重いし？"
"1009202-69" = "[ns17] カゴを持つ。\n[ns18] \"レジへ行こっか。\""
"1009202-70-ヨシミ" = "あっ、ちょっ、待って！"
"1009202-71-ヨシミ" = "一緒に……！！"
"1009202-72" = "（会計を済ませて、荷物を全部まとめた）"
