[translation]
"1004102-1" = "肉体という檻"
"1004102-2-ミサキ" = "……。"
"1004102-3" = "[s] \"……。\""
"1004102-4-ミサキ" = "……なんでこんなことになったんだろ。会うつもりはなかったんだけど。"
"1004102-5" = "[s] \"あ……その……。\""
"1004102-6-ミサキ" = "どうして呼び出したの？"
"1004102-7-ミサキ" = "何が望み？"
"1004102-8" = "[s] \"いや……特に…。\""
"1004102-9-ミサキ" = "じゃあ、帰る。"
"1004102-10" = "[s] \"ま、待って！\""
"1004102-11-ミサキ" = "……何？"
"1004102-12" = "[s1] \"ミサキは……その、危なっかしい感じがするというか……。\"\n[s2] \"何を考えているのか分からないというか……。\""
"1004102-13-ミサキ" = "……それで？"
"1004102-14-ミサキ" = "……それで？"
"1004102-15" = "[s3] \"だから……その、ミサキと話をしてみたくて……。\"\n[s4] \"もう少しミサキのことを知りたくて……。\""
"1004102-16-ミサキ" = "……。"
"1004102-17-ミサキ" = "……。"
"1004102-18-ミサキ" = "……はあ。 "
"1004102-19-ミサキ" = "私には、アリウスのみんなを守る役目がある。"
"1004102-20-ミサキ" = "私たちを探してる連中の目から逃れなきゃいけないんだ。"
"1004102-21-ミサキ" = "だから、外部の人間と連絡を取り合うなんて、原則NG。わかる？"
"1004102-22-ミサキ" = "でも……まぁ、今回はいいよ。"
"1004102-23-ミサキ" = "どうせ私たちの命はあなたが握ってるようなものだし。"
"1004102-24-ミサキ" = "それで、私に何をしてほしいの？"
"1004102-25" = "[s] \"じゃあ、お話とか……？\" "
"1004102-26-ミサキ" = "……。 "
"1004102-27" = "[s] \"それか、何か手伝えることはある？\""
"1004102-28-ミサキ" = "別に。 "
"1004102-29-ミサキ" = "ああ……手伝えること……ひとつ、あることにはある。"
"1004102-30" = "[s] \"よかった！どんなことでも手伝うよ！\""
"1004102-31-ミサキ" = "それじゃ……"
"1004102-32-ミサキ" = "……エラーの修正、完了。"
"1004102-33" = "[s] \"終わった？\""
"1004102-34-ミサキ" = "うん。私たちの使ってるGPS機器、古いからさ。こういう高いところでしかエラーの修正ができないの。 "
"1004102-35-ミサキ" = "でも、私ひとりじゃ来られなかったから……。"
"1004102-36-ミサキ" = "これで道に迷うことはしばらくないかな。ありがとう、先生。"
"1004102-37" = "[s] \"ミサキの役に立てて安心したよ。\""
"1004102-38-ミサキ" = "……安心？なんで？"
"1004102-39" = "[s] \"……ミサキってあんまり感情を表に出してくれないから、役に立てたのかわからなくて。\""
"1004102-40-ミサキ" = "……そっか。 "
"1004102-41-ミサキ" = "そういうの、よく言われる……まぁ、別に誰が何と言おうと興味ないけど。"
"1004102-42-ミサキ" = "やること終わったし、帰ろっか。"
"1004102-43" = "[s] \"お、お腹空いてない？何か食べに行く？\""
"1004102-44-ミサキ" = "ううん、いらない。"
"1004102-45-ミサキ" = "用は済んだし、行こう。 "
"1004102-46" = "[ns] \"……う、うん。\""
"1004102-47" = "……。"
"1004102-48" = "[s] \"……。\""
"1004102-49" = "……。"
"1004102-50" = "……ごめん、居心地悪いでしょ。私といると、多分ずっとそうだよ。"
"1004102-51" = "私、何に対してもあんまり興味ないから。 "
"1004102-52" = "さっき、なにか食べに行くって聞いたよね？"
"1004102-53" = "……そういうのにも、興味が無い。"
"1004102-54" = "お腹がすいたとしても、死なない程度に食べればいいから。何を食べたいとか、無くて。胃に入っちゃえば全部同じだし。 "
"1004102-55" = "[s] \"でも、ちゃんと食べないと身体を壊しちゃうよ。\""
"1004102-56" = "……だろうね。そうなったとしても、その時に身体を壊すだけだよ。肉体なんてどうせ土に還るだけの無意味な器なんだし、死んだらその時はその時。"
"1004102-57" = "[s] \"そっか……。\""
"1004102-58" = "そういうこと。"
"1004102-59" = "[s] \"じゃあ何か他にでも、ミサキが大切だと思うことは……？\""
"1004102-60" = "……さあね。"
"1004102-61" = "そんなもの、あるのかな。"
"1004102-62" = "大切に思ってもすべてが無駄になるだ、け――"
"1004102-63" = "ッ！？"
"1004102-64" = "[ns] \"エレベーターが止まった？\""
"1004102-65" = "……！？"
"1004102-66" = "ちょっと……よりによって今……！？"
"1004102-67" = "えー、ただいま防災システムのエラーにより、建物内の電源が落ちました。復旧まで1時間ほどかかる見込みです。"
"1004102-68" = "い、1時間……？ちょっと待って……！"
"1004102-69" = "ちょっと……！今は――"
"1004102-70" = "[s] \"仕方ないね。\""
"1004102-71" = "仕方ないじゃないよ……1時間も……。"
"1004102-72" = "[s] \"ん？今日は暇だったんじゃ……？\""
"1004102-73" = "そう、だけど……！"
"1004102-74" = "い、今は……。 "
"1004102-75" = "[s] \"落ち着いて待ってたら、すぐ復旧するよ。\" "
"1004102-76" = "それは、だから……！"
"1004102-77" = "[s] \"何か顔色が悪いけど……大丈夫？\""
"1004102-78" = "は、話しかけな――"
"1004102-79" = "[s] \"……ミサキ？顔色がすごく悪いけど……\""
"1004102-80" = "……。"
"1004102-81" = "[s5] \"大丈夫？\"\n[s6] \"どこか具合でも悪い？\"\n[s7] \"ざっくりでも良いから、教えてもらえると……。\""
"1004102-82" = "は、話しかけないで……。 "
"1004102-83" = "は、話しかけないで……。 "
"1004102-84" = "は、話しかけないで……。 "
"1004102-85" = "わ、私……。"
"1004102-86" = "[s8] \"ミサキ、どうしたの？\"\n[s9] \"……？\"\n[s10] \"何かできることがあるなら……。\""
"1004102-87" = "閉所恐怖症なんだってば！"
"1004102-88" = "閉所恐怖症なんだってば！"
"1004102-89" = "閉所恐怖症なんだってば！"
"1004102-90" = "[s] \"……。\""
"1004102-91" = "あー、っ……。"
"1004102-92" = "[ns] \"ドアが開いた！\""
"1004102-93" = "おや、エレベーターに閉じ込められた方がいらっしゃいましたか。ただいま復旧完了しました。ご不便をおかけして申し訳ございません。"
"1004102-94" = "[s] \"えっと……はい、ありがとうございます。\""
"1004102-95-ミサキ" = "……。"
"1004102-96" = "[s11] 土下座して謝る。\n[s12] 額を床につけて謝罪する。"
"1004102-97-ミサキ" = "先生……。"
"1004102-98-ミサキ" = "先生……。"
"1004102-99" = "[s] \"……ミサキ、本当にごめん。そうとも知らずに……。\""
"1004102-100-ミサキ" = "……もういいよ。 "
"1004102-101-ミサキ" = "地下のカタコンベに出入りしてるし、普通は言われないと気づかないと思うから……。"
"1004102-102-ミサキ" = "まぁ、だから……狭くて暗いところにいるの、苦手なんだ。"
"1004102-103-ミサキ" = "……肉体の欠陥ってやつ。別に先生のせいじゃないから、気にしないで。"
"1004102-104" = "[s] \"……う、うん。\""
"1004102-105" = "（帰っていくミサキの後ろ姿には哀愁が漂っていた。）"
