[translation]
"2600203-1" = "彼女の料理"
"2600203-2" = "ゲヘナ・第8学生食堂"
"2600203-3-ジュリ" = "今日作る料理は……。"
"2600203-4-ジュリ" = "カレーです！"
"2600203-5" = "[s] \"思ったより直球のメニュー。\""
"2600203-6-ジュリ" = "せっかく先生と一緒に挑戦する料理ということで、"
"2600203-7-ジュリ" = "誰もが好きなカレーが無難かなと思いまして。"
"2600203-8-ジュリ" = "あっ、もしかしてカレーは嫌いでしたか……？"
"2600203-9-ジュリ" = "以前作ったアヒージョをもう一度、ということもできますが……。"
"2600203-10" = "[s] \"そんなことないよ！無難っていいよね！無難万歳！！\""
"2600203-11-ジュリ" = "そうでしたか、ありがとうございます。"
"2600203-12-ジュリ" = "では、まず材料の準備から始めていきましょう！"
"2600203-13-ジュリ" = "材料を持ってきました。"
"2600203-14-ジュリ" = "カレーのルー、豚肉、ジャガイモを3つ、玉ねぎ１個……。"
"2600203-15-ジュリ" = "それからニンジンと、調味料など……。"
"2600203-16-ジュリ" = "だいたいこんなところでしょうか。"
"2600203-17" = "[s] \"まだ普通だ……。\""
"2600203-18-ジュリ" = "あれ、どうかしましたか、先生？"
"2600203-19" = "[s] \"う、ううん、なんでもないよ。\""
"2600203-20-ジュリ" = "そうですか？では、食材の下処理から始めましょう。"
"2600203-21-ジュリ" = "まずレシピによると、特に甘みのあるカレーではお肉の食感が重要だそうです。"
"2600203-22-ジュリ" = "なので、豚肉を柔らかくしていきましょう。"
"2600203-23" = "[s1] \"なるほど。柔らかくするのも、色々方法があるよね。\"\n[s2] \"すりおろしたニンニクを使ったり、牛乳を使ったり。\""
"2600203-24-ジュリ" = "はい、お肉を柔らかくするのは色々な方法がありますが……。"
"2600203-25-ジュリ" = "はい、お肉を柔らかくするのは色々な方法がありますが……。"
"2600203-26-ジュリ" = "ちょうど良い方法があります。"
"2600203-27-ジュリ" = "お肉は叩いたりして、衝撃を与えるほど柔らかくなるものですよね？"
"2600203-28-ジュリ" = "そのためにぴったりの道具を持ってます！"
"2600203-29" = "[s] \"えっと……ジュリさん？その手に持ってるものは……。\""
"2600203-30-ジュリ" = "これはですね……"
"2600203-31-ジュリ" = "ダブルバレルショットガンです！一度に数十発の弾丸を発射できます！きっとお肉をすっごい柔らかく……！"
"2600203-32" = "[s3] \"柔らかくっていうか！\"\n[s4] \"木っ端微塵になるよね！？\""
"2600203-33-ジュリ" = "えいっ☆"
"2600203-34-ジュリ" = "えいっ☆"
"2600203-35-ジュリ" = "お肉はこれでしっかり柔らかくなりましたね。"
"2600203-36" = "[ns5] \"しっかりとかいうレベルじゃないよ！？\"\n[ns6] \"何で料理に銃を使うの！？\""
"2600203-37-ジュリ" = "あっ、だ、ダメでしたか……！？"
"2600203-38-ジュリ" = "あっ、だ、ダメでしたか……！？"
"2600203-39-ジュリ" = "や、やっぱり……。"
"2600203-40-ジュリ" = "私が銃を取り出すたびにみなさんすごい剣幕で私のことを止めようとするので、もしかしたらとは思っていたのですが……。"
"2600203-41-ジュリ" = "やっぱり銃の持ち方が良くないのですね……。"
"2600203-42" = "[s] \"持ち方の問題じゃないけど！？\""
"2600203-43-ジュリ" = "先生！道具の使い方は大事なんですよ？"
"2600203-44-ジュリ" = "包丁を間違った方法で握ってしまうと、大怪我に繋がってしまうこともあるんですから！"
"2600203-45" = "[s] \"それはその通りだけど、何で私が怒られてるのかな！？\""
"2600203-46-ジュリ" = "とにかくもう大丈夫です、次はミスしませんので！"
"2600203-47-ジュリ" = "えっと、レシピレシピ……。"
"2600203-48-ジュリ" = "あっ、ありました。"
"2600203-49-ジュリ" = "次は材料を炒める工程ですね。"
"2600203-50-ジュリ" = "炒める順番は……。"
"2600203-51-ジュリ" = "ニンジンが最初で、ジャガイモ、そして玉ねぎとのことです。"
"2600203-52" = "[s] \"うん、じゃあニンジンから……。\""
"2600203-53-ジュリ" = "……ですが、それでは時間がかかりすぎると思いませんか？"
"2600203-54" = "[s] \"……え？\""
"2600203-55-ジュリ" = "給食は決まった時間に提供されなくてはいけないので、私たち給食部はたくさんの食事を、手ばやく作る必要があります。"
"2600203-56-ジュリ" = "そこで私、考えてみたのです。"
"2600203-57-ジュリ" = "そしたら画期的な方法を見つけたんですよ！"
"2600203-58-ジュリ" = "えいっ！"
"2600203-59" = "[s] \"待って待って待って！？\""
"2600203-60-ジュリ" = "どうかしましたか？"
"2600203-61" = "[s] \"一気に入れると、火の通りがバラバラに……！\""
"2600203-62-ジュリ" = "あっ、野菜によって火が通るまでの時間が違うから、"
"2600203-63-ジュリ" = "その点に注意しようってお話ですよね？"
"2600203-64" = "[s] \"よく知ってるね！じゃあどうして！？\""
"2600203-65-ジュリ" = "えへん、これでも給食部の部員ですから！それぐらいはもちろん知ってますよ～♪"
"2600203-66-ジュリ" = "そしてその問題は、私が思いついた画期的な方法で解決できるはずです！"
"2600203-67-ジュリ" = "じゃーん、これを使います！"
"2600203-68" = "[s] \"それは……バーナー？\""
"2600203-69-ジュリ" = "はい、ガスコンロの火力だけで火の通りに問題があるのでしたら、"
"2600203-70-ジュリ" = "バーナーも利用すれば……！"
"2600203-71-ジュリ" = "ガスコンロとバーナーを合わせて、2倍の火力で一気に！"
"2600203-72" = "[s] \"料理は足し算じゃないんだよ！？\""
"2600203-73-ジュリ" = "えいやっ★"
"2600203-74" = "（その結果は悲惨なものだった。危ない行動だったとはいえ、なぜここまでの事態になるのだろう……）"
"2600203-75" = "（学生食堂の床の半分以上を覆う、黒く焦げたカレー粉の散乱……）"
"2600203-76" = "（メラメラと高く燃え上がる炎……）"
"2600203-77" = "（鍋から零れ落ちていくカレーのような何かは、まるでマグマのようにぐつぐつと煮え滾っている）"
"2600203-78-ジュリ" = "うーん、どうしてこんなことになってしまったのでしょう……？"
"2600203-79" = "[s] \"その、原因はある程度明確だと思うけど……。\""
"2600203-80-ジュリ" = "わ、私はただみなさんのために、早くカレーを作りたくて……。"
"2600203-81" = "[s] \"スピードを優先しちゃった結果がこれだね……。\""
"2600203-82-ジュリ" = "だ、大丈夫です！最初からまたやり直しましょう！"
"2600203-83-ジュリ" = "まずは、えっと火をどうにか……！"
"2600203-84-ジュリ" = "えぇいっ！"
"2600203-85" = "[s] \"ジュリ！これ以上もう何も触らない方が……っ！\""
"2600203-86-ジュリ" = "あらっ、爆発してスプリンクラーが……。"
"2600203-87" = "（なぜか盛大に爆発した後、ジュリと一緒にびしょ濡れになったまま、どこが間違っていたのか熱い議論（？）を交わした）"
