[translation]
"90002025-1-モモイ" = "やった！"
"90002025-2-ミドリ" = "敵が撤退していきます！"
"90002025-3-ユズ" = "ど、どうにかなったぁ……ふぅ……。"
"90002025-4-アリス" = "ありがとうございます、エイミ！"
"90002025-5-エイミ" = "こういうのは慣れてるからね。"
"90002025-6-エイミ" = "なにより、私をここに配置した先生の判断が良かったんだよ。"
"90002025-7-リオ" = "先生、聞こえるかしら？エンジンの緊急修理が完了したわ。"
"90002025-8-トキ" = "私もいます。先生は迅速に褒めてください。"
"90002025-9" = "[s] \"リオもトキも偉い！お疲れ様！\""
"90002025-10-トキ" = "ありがとうございます。これでまだまだ戦えます。"
"90002025-11-ケイ" = "――エンジンの修復が確認できました。#nケイ、輸送船の状態をどうみますか？"
"90002025-12-ケイ" = "再飛行は可能だと思います。ただ、これ以上ダメージを負うと……。"
"90002025-13-アリス" = "アリスです！こちらは終わりました！みんな無事です！"
"90002025-14-ヒマリ" = "お見事です。ゲーム開発部の皆さん、エイミ。"
"90002025-15-ヒマリ" = "お疲れのところ申し訳ないのですが、戻ってくるついでに、敵の残骸を回収していただけますか？"
"90002025-16-エイミ" = "今回は持って帰れそう。どれくらい必要？20体？"
"90002025-17-ヒマリ" = "多すぎても、船内に収納できませんので……。"
"90002025-18-ケイ" = "船外カメラ、再起動。モニターに映します。"
"90002025-19-ヒマリ" = "これは……。"
"90002025-20-ケイ" = "……。"
"90002025-21" = "[s] \"……。\""
"90002025-22" = "[ns] \"あれが、鋼鉄大陸……。\""
"90002025-23" = "次回;出撃"
