[translation]
"90002140-1" = "第14話;持って生まれたもの"
"90002140-2-アイン" = "で、でも私たちは結局……プログラムされた通りに動いているだけ、ですよ……？"
"90002140-3" = "[s1] \"それを言うなら私たちも同じだよ。\"\n[s2] \"人間は、愛するようにプログラムされているからね。\""
"90002140-4-アイン" = "えぇっ！？"
"90002140-5-アイン" = "人間も同じ……そ、そうなんですか……？"
"90002140-6" = "[log]親が子を愛するように。[/log]"
"90002140-7" = "[log]子が親を愛するように。[/log]"
"90002140-8" = "[log]ひいては――個が個を愛するように。[/log]"
"90002140-9-ソフ" = "でも、全員がそうとは限らないんじゃない……？"
"90002140-10" = "[s] \"もちろん程度の差はあると思うよ。例外だって。\""
"90002140-11" = "[ns3] \"だけど私たちも、[ruby=作られた時]生まれた時[/ruby]から行動をプログラムされている。\"\n[ns4] \"それを「遺伝子」と呼んでるだけだよ。\""
"90002140-12-ソフ" = "[ruby=プログラム]遺伝子[/ruby]……。"
"90002140-13-ソフ" = "でもそれって……そうだよね。淘汰された個体もたくさんいて……。"
"90002140-14-ソフ" = "そっか……[ruby=生命]人間[/ruby]はそうやって繋いできたんだね……。"
"90002140-15" = "[log]だから大事なのは[/log]"
"90002140-16" = "[log]愛すること。[/log]"
"90002140-17" = "[log]君たちがマルクトを愛したという事実だと思うよ。[/log]"
"90002140-18-オウル" = "その「愛」が最初から偽りだったとしてもですか……？"
"90002140-19-オウル" = "どうせ世の中なんて嘘だらけって……あなたがそれを言うんですか？"
"90002140-20-オウル" = "私たちが鋼鉄大陸をつくった理由は、全部、お姉様のためでした。"
"90002140-21-オウル" = "ですがこの気持ちはもともと設定されていたもので……。"
"90002140-22-オウル" = "……はい？「行動」に意味がある？"
"90002140-23-オウル" = "理由が偽りだとしても……「やったこと」は揺るがない事実だ、と……？"
"90002140-24" = "[s5] \"マルクトのために鋼鉄大陸を作ったんだよね？\"\n[s6] \"だったらその「行動」が、君たちを証明してくれるよ。\""
"90002140-25-アイン" = "だ、大丈夫だと……言ってくれるんですか……？"
"90002140-26-アイン" = "私たちは世界を敵に回したんだよ……？"
"90002140-27-アイン" = "私たちは……頑張りました。ですがそれは[ruby=・]私[/ruby][ruby=・]た[/ruby][ruby=・]ち[/ruby][ruby=・]の[/ruby][ruby=・]た[/ruby][ruby=・]め[/ruby]です。"
"90002140-28-アイン" = "先生からすれば、色々なことをめちゃくちゃにされたのではありませんか……？"
"90002140-29" = "[s7] \"私は腹黒い大人だからね！\"\n[s8] \"前に言われたことをそのまま返すのが好きなんだけど――\""
"90002140-30" = "[log]それはただ、[wa:500]情報が足りなかっただけ。[/log]"
"90002140-31" = "[log]だから、[wa:1000]やり直せばいい。[/log]"
"90002140-32-アイン" = "！！！"
"90002140-33-リオ" = "……ええ。まだ間に合うわ。"
"90002140-34-リオ" = "だから、手遅れになってしまう前に……。"
"90002140-35-アリス" = "……。"
"90002140-36-アリス" = "泣かないでください、と……それを言う資格がアリスにないのは分かっています。"
"90002140-37-アリス" = "あなた達の悲しみを、アリスが完全に理解することはできないと思います。"
"90002140-38-アリス" = "でも、一緒に悲しむことはできると思います。"
"90002140-39-アリス" = "アリスも、先生を――"
"90002140-40-アリス" = "ケイやモモイ、ミドリ、ユズ、エイミ、トキ、ヒマリ先輩にリオ先輩……。"
"90002140-41-アリス" = "誰かを失うことになったら、耐えられないくらい悲しいですから。"
"90002140-42-オウル" = "はぁ……知った風なことを言うじゃないですか。"
"90002140-43-アリス" = "いいえ。アリスは何も知りません。"
"90002140-44-アリス" = "おそらく……アリスにはできないと思います。"
"90002140-45-アリス" = "……誰かの悲しみを、まったく同じように理解することは。"
"90002140-46-アリス" = "だって、アリスには[ruby=・]設[/ruby][ruby=・]定[/ruby][ruby=・]さ[/ruby][ruby=・]れ[/ruby][ruby=・]て[/ruby][ruby=・]い[/ruby][ruby=・]な[/ruby][ruby=・]い[/ruby][/ruby]機能ですから。"
"90002140-47-アリス" = "だからアリスは――アリスにできることをしようと思います。"
"90002140-48-アイン" = "できること、ですか……？"
"90002140-49-アリス" = "はい。"
"90002140-50-アリス" = "アイン、ソフ、オウル。"
"90002140-51-アリス" = "アリスと、友達になってください。"
"90002140-52-アイン" = "と、友達！？"
"90002140-53-リオ" = "！？！？"
"90002140-54-リオ" = "……！"
"90002140-55-アリス" = "はい。アリスは、みなさんと友達になりたいです。"
"90002140-56-アリス" = "そして……アリスにも、一緒に悲しませてほしいです。"
"90002140-57-アイン" = "うっ……！"
"90002140-58-アリス" = "前に、先生が教えてくれました。"
"90002140-59-アリス" = "悲しみに暮れている時。#n隣で一緒に泣いてくれる人がいると、悲しみに打ち勝つ力を得られるのだと。"
"90002140-60-オウル" = "でも、お姉様は……。"
"90002140-61-アリス" = "はい。"
"90002140-62-アリス" = "もしもそれでも足りなければ……。"
"90002140-63-アリス" = "どうしてもアリスたちが憎いのであれば……。"
"90002140-64-アリス" = "その時は、そうだと言ってください。"
"90002140-65-リオ" = "（ああ……）"
"90002140-66-アリス" = "みなさんが何を感じても――"
"90002140-67-アリス" = "アリスは頑張って……それを受け止めます。"
"90002140-68-アリス" = "……アリスは覚えています。"
"90002140-69-アリス" = "生きるのは苦痛だと話していたことを、鮮明に覚えています。"
"90002140-70-アリス" = "その話には、正しい部分もあるのだと思います。#nなぜならこれも……先生が教えてくれましたから。"
"90002140-71-ケイ" = "……。"
"90002140-72-アリス" = "明日はおそらく何かを失う日で、良いことなんて、そうそう起きない――"
"90002140-73-アリス" = "人々が話すのは漠然とした希望であって、[ruby=明日]静かに迫る未来[/ruby]ではありません。"
"90002140-74-リオ" = "そうね。未来は「期待」という錯覚を伴って、楽観視される傾向が強いものね。"
"90002140-75-リオ" = "逆に過去は思い出として美化されていくわ。#nけれど、過ぎ去ったものは戻ってこない。"
"90002140-76-リオ" = "そして現在とは、過去と未来の狭間に辛うじて存在する刹那。#n希薄すぎるあまり、知覚するのは限りなく難しい。"
"90002140-77-リオ" = "曖昧模糊としたものに包み隠され続けているから……#nいざ現実を直視した時、人生に残るのは苦痛だけなのかもしれないわね。#n……貴女たちが言った通りに。"
"90002140-78-アリス" = "ですが、先生は教えてくれました。"
"90002140-79-アリス" = "それを放っておいてはいけないと。"
"90002140-80-アリス" = "私たちはみんな幸せになるべきだと。"
"90002140-81-アリス" = "幸せになることで……闘い続けるべきだと。"
"90002140-82-アリス" = "まるで、ケイのように。"
"90002140-83-ケイ" = "はい！？！？"
"90002140-84-アリス" = "ケイは、アリスの自慢の友達です。"
"90002140-85-アリス" = "直面する理不尽に怒りを覚えて、どうにか解決しようと努力しています。"
"90002140-86-アリス" = "その姿勢をアリスも見習いたいと思っています！"
"90002140-87-アリス" = "……たまに小言を言ってくるのは怖いですが。"
"90002140-88-ケイ" = "いえ、それは全部アリスのためであって……。"
"90002140-89-アリス" = "それでも怖いものは怖いです！"
"90002140-90-ケイ" = "はぁ……。"
"90002140-91-アリス" = "そして……リオ先輩。"
"90002140-92-リオ" = "私……？"
"90002140-93-アリス" = "リオ先輩はいつだって、自分にできることを探しています。"
"90002140-94-アリス" = "予想できるすべての可能性と、予想できない他の可能性に備えて、#nいつも入念に準備をしています。"
"90002140-95" = "その途中で何かが失敗しても、絶対に挫けません。"
"90002140-96-アリス" = "時には自分自身を投げ打ってでも、最悪を回避しようとします。"
"90002140-97-アリス" = "アリスは……そういう人たちが一緒にいてくれて、本当に良かったと思います。"
"90002140-98-アリス" = "ケイも、リオ先輩も、そしてアリスが知っているみんなも。"
"90002140-99-アリス" = "もちろん、先生もです。"
"90002140-100-アリス" = "だから――アリスは、絶対に諦めません。 "
"90002140-101-アリス" = "絶対に諦めないことの大切さをアリスは学びました。"
"90002140-102-アリス" = "アリスは何があっても、[ruby=闘い]幸せ[/ruby]を諦めません。"
"90002140-103-アリス" = "……そして、それと同じくらいに、アリスはあなた達と友達になりたいです。"
"90002140-104-ソフ" = "とも、だち……。"
"90002140-105-アリス" = "アリスはまだ見習い勇者です。"
"90002140-106-アリス" = "未熟で、弱くて、自分でも悲しくなるときがあります。"
"90002140-107-アリス" = "でも……隣にいるみんなに手を伸ばすことだけは、諦めません。"
"90002140-108-アリス" = "それが――今のアリスにできる最善ですから。"
"90002140-109-アリス" = "先生、覚えていますか？#n人生には大きな意味や目的は必要ないと、アリスに言ってくれたことを。"
"90002140-110" = "[ns] \"うん……覚えてるよ。\""
"90002140-111-オウル" = "それは、どうして……？"
"90002140-112-アリス" = "なぜなら、もしも絶対に必要だったなら……#n意味や目的を見つけられなかった人生は価値がないことになってしまうからです。"
"90002140-113-アイン" = "……。"
"90002140-114-アリス" = "そんなの間違っていると思います。あまりにも悲しいです。"
"90002140-115-アリス" = "ジョブや育成ルートが1つしかないゲームは、ただのクソゲーです。#n企画段階から失敗しています。"
"90002140-116-アリス" = "アリスは悲しい気持ちになりたくないからこそ、他の誰かが悲しんでいる姿も見たくありません。"
"90002140-117-アリス" = "人は誰かの幸せな姿を見て、自分も同じ気持ちになれます。"
"90002140-118-アリス" = "誰かの苦しむ姿を見て、自分もそれに共感できるのです。"
"90002140-119-ソフ" = "……そんなの偽善だよ。錯覚にすぎない。"
"90002140-120-ソフ" = "他人の気持ちなんて、理解できるはずがない。"
"90002140-121-アリス" = "たしかに、そうかもしれません。"
"90002140-122-アリス" = "でも、お互いに支え合って生きていけると、アリスは思っています。"
"90002140-123-アリス" = "先生が、アリスやケイ、リオ先輩、そして他のみんなに出会えてよかったと――"
"90002140-124-アリス" = "――幸せだと、話してくれたように。"
"90002140-125-アリス" = "アリスは、あなた達と話ができたこと自体、嬉しく思っています。#nだから――"
"90002140-126-アリス" = "アリスと、友達になってください。"
"90002140-127-アリス" = "この手を取ってくれたら……アリスはとても嬉しいです。"
"90002140-128-アリス" = "そして、アリスが幸せなのと同じくらい、あなた達にも幸せになってほしいです。"
"90002140-129-アリス" = "[ruby=闘い]幸せ[/ruby]こそ、私たちが絶対に諦めてはいけない、#n私たちにとって一番大事なものの1つですから。"
"90002140-130-オウル" = "……これが[ruby=・]王[/ruby][ruby=・]女[/ruby][ruby=・]の[/ruby][ruby=・]言[/ruby][ruby=・]葉[/ruby]なんですね。"
"90002140-131-アリス" = "はい！？#nそれは違います！アリスは王女なんかじゃありません！アリスはただのアリスです……！"
"90002140-132-アイン" = "は、はい。それは分かってます……。#nわ、分かっているんですが、えっと……。"
"90002140-133-ソフ" = "私たちが言ってるのは、言葉そのものが力を持ってるってことだよ。"
"90002140-134-ソフ" = "聞く側が、自然と耳を傾けちゃうような……。"
"90002140-135-ソフ" = "外から与えられたものじゃなくて、内から生まれる権威のこと。"
"90002140-136-オウル" = "それゆえに、絶対的な力を持っているとも言えます。"
"90002140-137-アイン" = "で、でも……幸せ、ですか……。#nそ、それが何なのか……私たちにはまだ、よく分かりません……。"
"90002140-138-ソフ" = "……幸せがまだ残ってるかすら怪しいんだよね。"
"90002140-139-オウル" = "それが果たして、私たちに手を差し伸べてくれるでしょうか。"
"90002140-140-ソフ" = "で、でも……。"
"90002140-141-ソフ" = "ありがとう、ございます。"
"90002140-142-ソフ" = "本当に……。"
"90002140-143-アイン" = "あぅっ！？"
"90002140-144-オウル" = "アイン！？"
"90002140-145-オウル" = "くっ、脚が……！"
"90002140-146" = "（倒れそうだった3人をなんとか支えた）"
"90002140-147-オウル" = "せん、せい……？"
"90002140-148-オウル" = "あーあ……搾りカスまで持っていこうとするんだ。"
"90002140-149-オウル" = "ええ。役目を終えた道具は捨てられるものですから。#nははっ……。"
"90002140-150-ケイ" = "……どういう意味ですか？"
"90002140-151-オウル" = "た、単純な話です。ただ――"
"90002140-152-オウル" = "預言者も私たちも、このための道具に過ぎなかったんだよ。"
"90002140-153-オウル" = "そして、目的が達成されたから……。"
"90002140-154-リオ" = "貴女たちに……何が起きるの？"
"90002140-155-オウル" = "あ、あの方が神としてキヴォトスに降臨したら……私たちは用済みで……。"
"90002140-156-オウル" = "あ、あれ……？この話、しましたっけ……？"
"90002140-157-オウル" = "どのみち、すぐに分かるでしょ。"
"90002140-158-オウル" = "このまま機能を止められるか、吸収されて分解されるか……そんなところじゃないですかね。"
"90002140-159-アイン" = "……。"
"90002140-160-アイン" = "その、先生。やっぱり……。"
"90002140-161-アイン" = "先生と皆さんだけでも……逃げるのはどうですか……？"
"90002140-162" = "[s] \"え……？\""
"90002140-163-アリス" = "はい……？"
"90002140-164-アイン" = "わ、私たちがこんなことを言うのもあれですけど……。"
"90002140-165-アイン" = "――ありがとうございます。"
"90002140-166-アイン" = "頑張ったねと言ってくれて……嬉しかったです。"
"90002140-167-アイン" = "私たちのことを見ていてくれて、嬉しかったです。"
"90002140-168-アイン" = "……幸せになってほしいと言ってくれて……本当に、嬉しかったです。"
"90002140-169-ソフ" = "まあ……そうだね。"
"90002140-170-オウル" = "そう難しく考えなくていいですよ。#nキヴォトスをめちゃくちゃにしようとした悪党は、墓穴を掘ってそのまま終わり！"
"90002140-171-オウル" = "多分もっと大きな問題が差し迫ってますが……それはそのとき考えてください！#nワハハハ！"
"90002140-172-オウル" = "ハハ、ハ……。"
"90002140-173-ケイ" = "……噓つき。"
"90002140-174-オウル" = "わざわざ指摘しなくていいですから。"
"90002140-175-ケイ" = "まあ……よっぽどのことじゃない限り、そうしていたでしょうね……。"
"90002140-176-ケイ" = "でも――！"
"90002140-177-ケイ" = "どうしても腹が立って仕方ないんです！#nあなた達、人を馬鹿にするのも大概にしてください！"
"90002140-178-アイン" = "えっ、ええ？ど、どうしてですか！？"
"90002140-179-ケイ" = "どうしても何も！全っ然平気じゃないくせに平気なふりをして！#n見え見えなんですよ！"
"90002140-180-ケイ" = "なのに逃げろですって！？#nアリスの言ったことを聞いてなかったんですか！？"
"90002140-181-ケイ" = "ふざけないでください！#n生きているんでしょう！？足搔いて、闘ってください！"
"90002140-182-ケイ" = "何度言わせれば気が済むんですか！#n待っていたって幸せは訪れません！"
"90002140-183-ケイ" = "望みがあるのなら！そして……それが何より切実な願いなのであれば！"
"90002140-184-ケイ" = "すべてを賭けて[ruby=闘え]行動しろ[/ruby]！"
"90002140-185-アイン" = "望み……。"
"90002140-186-アイン" = "そんなの……。"
"90002140-187-アイン" = "……。"
"90002140-188-アイン" = "ぐすっ……。"
"90002140-189-アイン" = "お姉様に……会いたいです。"
"90002140-190-アイン" = "何があっても……どんなことがあってもいいから……。"
"90002140-191-アイン" = "もう一度、お姉様に会いたいです……。"
"90002140-192-アイン" = "もっとお話したかったこと、たくさんあるのに……。"
"90002140-193-アイン" = "もっと遊びたいことも、たくさんあるのに……。"
"90002140-194-アイン" = "なのに……こんなお別れは……イヤです……。"
"90002140-195-オウル" = "……。"
"90002140-196-オウル" = "……。"
"90002140-197-アイン" = "あっ……！"
"90002140-198-アイン" = "うわっ！？"
"90002140-199-オウル" = "気をつけてください！"
"90002140-200" = "[ns] \"え……？\""
"90002140-201" = "（その瞬間、足元の地面が文字通り[ruby=・]消[/ruby][ruby=・]え[/ruby][ruby=・]て[/ruby]しまった）"
"90002140-202-アリス" = "先生！？"
"90002140-203-アイン" = "せ、先生――！！！"
"90002140-204" = "次回;新しき空、新しき地"
