[translation]
"90002070-1" = "第7話;ケイ"
"90002070-2-アリス" = "ケイ？起きてください、ケイ！#nこんなの、嫌です……アリスを、独りにしないでください！"
"90002070-3-アリス" = "ケイ！！！！"
"90002070-4-ケイ" = "……アリス。"
"90002070-5-アリス" = "ケイ！？アリスはここにいます！どうか……！"
"90002070-6-アリス" = "すみません、落ち着いてください……。"
"90002070-7-アリス" = "え……？"
"90002070-8-アリス" = "はぁぁ……疲れました……。"
"90002070-9-アリス" = "大丈夫……なんですか？"
"90002070-10-アリス" = "問題ありません。身体のあちこちが壊れているだけです。"
"90002070-11-アリス" = "私が診るわ。アリス、ちょっといいかしら。"
"90002070-12-アリス" = "は、はい……！"
"90002070-13-ケイ" = "ケイの意識……生命に異常はないわ。"
"90002070-14-アリス" = "本当ですか！？ケイ……よかったです……！"
"90002070-15-ヒマリ" = "ただ、ケイの身体はほぼ限界に達しています。"
"90002070-16-アリス" = "そ、それはどうすればいいんですか……？"
"90002070-17-リオ" = "なんら難しいことではないわ。身体をオーバーホールすれば解決することよ。"
"90002070-18-リオ" = "問題が生じているのは、あくまでハード面だけのようね。"
"90002070-19-モモイ" = "よ、よかったね、ケイちゃん……。"
"90002070-20-ケイ" = "待ってください。つまり、この身体を整備して使い続けるという意味ですか？"
"90002070-21-リオ" = "そのつもりだけれど……何か問題あるかしら？"
"90002070-22-ケイ" = "……。"
"90002070-23-ケイ" = "これは提案なのですが……。"
"90002070-24-ケイ" = "これを機に、他の身体に変えてくれませんか？"
"90002070-25-ヒマリ" = "といっても、使えそうな素体が……。"
"90002070-26-ケイ" = "あるじゃないですか！そこに！"
"90002070-27-リオ" = "そこ……？"
"90002070-28-エイミ" = "もしかして、ここにあるやつ？"
"90002070-29-エイミ" = "でもこれ、デカグラマトン側が作ったものなんだよね……？"
"90002070-30-ケイ" = "分析をして、問題ないと判明したはずです。"
"90002070-31-ケイ" = "それは違うわ。[ruby=・]稼[/ruby][ruby=・]働[/ruby][ruby=・]に[/ruby][ruby=・]は[/ruby]問題がないという話だったでしょう？"
"90002070-32-ヒマリ" = "そうです。意識回路を移植すれば、すぐ動けるとは言いましたけど……。"
"90002070-33-ケイ" = "だから！私を！使ってください！"
"90002070-34-ケイ" = "賛成できないわ。何が起きるか予測すらできないもの。あまりにも危険よ……。"
"90002070-35-ケイ" = "なにより、素体内部のセキュリティを、私たちで突破できるか確信が持てないわ。"
"90002070-36-ケイ" = "それは私がやってみます。#nさっきも言いましたが、時間があれば突破できるはずですから。"
"90002070-37" = "[s] \"あんまり時間は残されてないんじゃないかな……。\""
"90002070-38-ヒマリ" = "うーん……可能性がない、とは言い切れませんが、やはりリスクを考えると――"
"90002070-39-ケイ" = "なぜやる前から諦めるんですか！"
"90002070-40-ケイ" = "やってみないと分からないんでしょう！？"
"90002070-41-エイミ" = "お、いつもの調子が戻ってきたみたい。"
"90002070-42-ケイ" = "この素体、鋼鉄大陸の素材で作ったものですよね？"
"90002070-43-ケイ" = "上手くいけば、何か手掛かりを掴める可能性だってあるじゃないですか！"
"90002070-44-リオ" = "でも、失敗すれば……。"
"90002070-45-ケイ" = "だから、ネガティブなことばかり言わないでください！"
"90002070-46-ケイ" = "まずはやってみる！それでダメだったら、そのとき考えればいいじゃないですか！"
"90002070-47-ヒマリ" = "なんだか、いつにも増して感情的になっていませんか……？"
"90002070-48-ケイ" = "意識を移すこと自体は、既に成功しています。#nだって私、元々キーホルダーの中にいたんですよ？"
"90002070-49-アリス" = "はい！アリス、まだ思い出として持っています！"
"90002070-50-ケイ" = "あ、はい。ありがとうございます。#nとにかく、私が言いたいのは――"
"90002070-51-ケイ" = "前回成功したのだから、今回も大丈夫だということです！"
"90002070-52-ケイ" = "もう何度目か分かりませんが……#nダメだったら、そのとき考えればいいでしょう！？"
"90002070-53-リオ" = "もしかして……そんなに、今の身体が嫌なのかしら……？"
"90002070-54-ケイ" = "もし言うことを聞いてくれないのなら――"
"90002070-55-ケイ" = "私はもう一歩も動きませんから！！！"
"90002070-56-アリス" = "ケイ！？"
"90002070-57-アリス" = "くっ……つい興奮して身体が……。"
"90002070-58" = "[ns] \"……ケイの言うとおりにしてみない？\""
"90002070-59-リオ" = "でも……。"
"90002070-60-リオ" = "え？不可能なのか、って？#n違うと、思うわ……でも、やはり……リスクは伴うものよ。"
"90002070-61-リオ" = "できれば、これ以上の変数は増やしたくないの。"
"90002070-62" = "[s] \"成功すれば、得るものもあると思うよ？\""
"90002070-63-ヒマリ" = "希望的観測ではありますが……何にせよ、あの素体はデカグラマトンのエンジニアたちが作った可能性が高いです。"
"90002070-64-ヒマリ" = "加えて、セキュリティのシステムは、ほぼ間違いなくケイに関係がある。#n解析できれば、きっと大きな手がかりになるはずです。"
"90002070-65-ヒマリ" = "追加の補助記憶装置をつなげておくことで、失敗に備えることも可能です。"
"90002070-66-ヒマリ" = "ケイの意識を保存させることに、大きなリスクはないと考えられますが……。"
"90002070-67-ヒマリ" = "懸念しているのは、大幅な時間のロスよ。"
"90002070-68-ヒマリ" = "新しい素体に意識を移す時間と、セキュリティを分析する時間――"
"90002070-69-ヒマリ" = "一刻の猶予も無い中で、それが無駄になるかもしれない。"
"90002070-70" = "[s] \"……。\""
"90002070-71" = "[ns] \"それでも、やってみよう！\""
"90002070-72-リオ" = "先生、本気で言っているの！？"
"90002070-73-リオ" = "いえ、言いたいことは理解しているわ。#n成功のリターンは大きいし、失敗したとしてもケイを失うことはない。でも……。"
"90002070-74-リオ" = "あまりにも、変数が多すぎるのよ……。"
"90002070-75-リオ" = "え……？お願いを聞いてあげたい……？#n先生、貴方ね……。"
"90002070-76-リオ" = "……。"
"90002070-77-リオ" = "分かったわ……。"
"90002070-78-ヒマリ" = "先生がそこまで言うのですから、仕方ありませんよ。#n可愛い後輩の[ruby=・]お[/ruby][ruby=・]願[/ruby][ruby=・]い[/ruby]でもありますし。"
"90002070-79-アリス" = "ケイ、やりましたね！みんなが力を貸してくれます！"
"90002070-80-アリス" = "ふふ、ふふふ……やはり、必死に訴えかけていけば……#n通じるものなんですね……。"
"90002070-81-モモイ" = "そっか！じゃあ、今度ユウカに試してみよっと！"
"90002070-82-ミドリ" = "たぶん、ダメだと思うよ……。"
"90002070-83-リオ" = "3で同時に入力するわよ。いち、に――"
"90002070-84-ヒマリ" = "――さん！"
"90002070-85-アリス" = "……ケイ？"
"90002070-86-モモイ" = "私も！私も見る！#nおぉ……！"
"90002070-87-ヒマリ" = "素体の正常な稼働が確認できました。あとは……。"
"90002070-88-ヒマリ" = "ケイ。私たちのこと、分かるかしら？"
"90002070-89" = "[ns] \"……ケイ？\""
"90002070-90-ケイ" = "……先生？"
"90002070-91-ケイ" = "アリス？"
"90002070-92-アリス" = "ケイ！！！"
"90002070-93-アリス" = "さすがはケイです！アリス、信じていました！"
"90002070-94-ケイ" = "……言ったでしょう。大丈夫だって。皆さん大袈裟すぎるんですよ……。"
"90002070-95" = "[s] \"それくらい大事なことだったからね。\""
"90002070-96-エイミ" = "みんなが冷静だったら、それはそれで寂しかったかもしれないよ？"
"90002070-97-トキ" = "仕方ありません。私だけでも平静を装うことにします。"
"90002070-98-エイミ" = "いえ、結構です……。"
"90002070-99-ケイ" = "えっと……改めまして、ケイです。"
"90002070-100-ケイ" = "ケイです！"
"90002070-101-モモイ" = "おぉ、これでようやく美少女アンドロイドって感じになったね！"
"90002070-102-モモイ" = "うん。良いデザインだと思う。"
"90002070-103-モモイ" = "よ、よかったね……ケイちゃん。"
"90002070-104-リオ" = "（前のデザインも、悪くなかったと思うのだけれど……）"
"90002070-105-ケイ" = "……二足で歩けるし、喉がスピーカーじゃない。"
"90002070-106-ケイ" = "髪の毛に、手、指まで……。"
"90002070-107-ケイ" = "……う、うぅっ。"
"90002070-108-ヒマリ" = "ケイ、おめでとうございます。#n感動に水を差すようで申し訳ないのですが……何か、分かったことはありますか？"
"90002070-109-ヒマリ" = "何もなかったとしても、ケイが喜んでいますし、十分だとは思いますが。"
"90002070-110-ケイ" = "あれほど駄々をこねて何も無かったら、皆さんに顔向けできませんよね。"
"90002070-111-ケイ" = "幸い、お話しできることがたくさんあります。"
"90002070-112-ケイ" = "一旦、輸送船に戻りましょう。"
"90002070-113" = "次回;可能性"
