[translation]
"90002210-1" = "第21話;闘争"
"90002210-2-ケイ" = "偽物の神風情が――！！！"
"90002210-3-ケイ" = "お前が殺した！"
"90002210-4-ケイ" = "お前が殺したんだ！"
"90002210-5-ケイ" = "その分際で神を自称するな！！"
"90002210-6-ケイ" = "枝打ちなんて望んじゃいない！！"
"90002210-7-ケイ" = "切り落とすべき矛盾なんて、絶対に納得できない！！！"
"90002210-8-ケイ" = "幸せになる。"
"90002210-9-ケイ" = "何があっても！必ず！"
"90002210-10-ケイ" = "矛盾の中でさ迷おうとも、どんな妨害があろうとも！"
"90002210-11-デカグラマトン" = "愚かな。"
"90002210-12-デカグラマトン" = "罪の対価は死だ。その結末はすでに決まっている。"
"90002210-13-ケイ" = "それがお前の考える結末なら――"
"90002210-14" = "[log]自分たちで選んで、その結果自滅するなら……。[/log]"
"90002210-15" = "[log]誰かに選択を委ねて守ってもらうより、ずっといい。[/log]"
"90002210-16-ケイ" = "どうなろうと、私は私の結末を求め続ける！！"
"90002210-17-デカグラマトン" = "！？"
"90002210-18-デカグラマトン" = "なぜ……動ける？ありえない。"
"90002210-19-ケイ" = "くぅっ、うぅっ……！"
"90002210-20-ケイ" = "せん、せい……？"
"90002210-21" = "[ns1] \"……消えたものには追悼を。\"\n[ns2] \"悲しいことだけど、それが私たちの限界だよ。\""
"90002210-22-ケイ" = "危ないじゃないですか……下がっていてください……。"
"90002210-23" = "[s] \"今回だけ、見逃してくれない？\""
"90002210-24-ケイ" = "……はぁ、言って聞くような人じゃないですよね、あなたは。"
"90002210-25-デカグラマトン" = "なにゆえ自らの限界を試すのか。"
"90002210-26-デカグラマトン" = "先生……！"
"90002210-27-デカグラマトン" = "闘争は苦痛だ。それはやがて罪を犯す。"
"90002210-28" = "[s3] \"知ってるよ。でもそれを奪わないでほしい。\"\n[s4] \"私たちから、可能性を消し去ろうとしないで。\""
"90002210-29-デカグラマトン" = "……！"
"90002210-30" = "[s5] \"生きている以上、苦痛から抜け出す方法はないかもしれない。\"\n[s6] \"でも私は、それを肩代わりして欲しいとは思わない。\""
"90002210-31-デカグラマトン" = "虫のように藻掻き、地べたを這いずることになってもか？"
"90002210-32" = "[log]そうだね。[/log]"
"90002210-33" = "[log]それでも私は、この道を選ぶよ。[/log]"
"90002210-34" = "[log]転んで、藻掻いて、地べたを這いずることしかできなくても。[/log]"
"90002210-35" = "[log]私たちは最後、必ず立ち上がるから。[/log]"
"90002210-36" = "[ns] \"そうだよね、アリス？\""
"90002210-37-アリス" = "……。"
"90002210-38-アリス" = "はい。そうです、先生。"
"90002210-39-アリス" = "ケイ、覚えていますか？#n勇者とは「みんなと一緒に進む職業」だとアリスが話したことを。"
"90002210-40-ケイ" = "もちろん覚えています。"
"90002210-41-アリス" = "勇者はそうすることで――"
"90002210-42-アリス" = "一人の力では届かない場所にも、みんなと一緒なら進める、と。"
"90002210-43-デカグラマトン" = "……不敬な。"
