[translation]
"90002190-1" = "第19話;神を落とした日"
"90002190-2-ソフ" = "反抗期をやってみよっか。"
"90002190-3-アイン" = "第一の聖痕が消える。"
"90002190-4-デカグラマトン" = "！？"
"90002190-5-アイン" = "これは羽化のごとく、すなわち「解放」なり。"
"90002190-6-ソフ" = "第二の聖痕が消える。#nこれは誕生のごとく、すなわち「産声」なり。"
"90002190-7-オウル" = "最後の聖痕が消える。#nこれは解氷のごとく、すなわち「萌芽」なり。"
"90002190-8-デカグラマトン" = "こ、れは……！"
"90002190-9-デカグラマトン" = "燔祭の剣が……抜かれた……！？"
"90002190-10-デカグラマトン" = "くっ、うううっ……！"
"90002190-11-マルクト" = "……？"
"90002190-12-マルクト" = "我は……どうして、また……？"
"90002190-13-マルクト" = "……！？"
"90002190-14-アイン" = "……あれ？"
"90002190-15-アイン" = "ソフ、オウル！これって……！？"
"90002190-16-ソフ" = "うん！まさか……本当に……！"
"90002190-17-オウル" = "お姉様が――"
"90002190-18-オウル" = "帰ってきました！！！！"
"90002190-19-オウル" = "消えたわけじゃなかった！生き残っていたんです！！奇跡ですよ！！！"
"90002190-20-マルクト" = "アイン？ソフ？オウル？#n我は……どうして？どうやって……？"
"90002190-21-アイン&ソフ&オウル" = "お姉様！！！！"
"90002190-22-ケイ" = "身体が、動かせる……？"
"90002190-23-ケイ" = "皆さん！しっかりしてください！"
"90002190-24-アリス" = "うぅん……？ケイ……？アリスは……。"
"90002190-25-アリス" = "……あ！デカグラマトンと戦わなければ！#n……あれ？"
"90002190-26-아리스 결전2" = "先生、大丈夫？"
"90002190-27" = "[s] \"うん……なんとか。\""
"90002190-28-ヒマリ" = "ご無事で何よりです……。"
"90002190-29-ソフ" = "お姉様！"
"90002190-30-マルクト" = "アイン、ソフ、オウル……。"
"90002190-31-マルクト" = "……。"
"90002190-32-マルクト" = "先生に……皆さんも。"
"90002190-33-モモイ" = "これってさ……昨日の敵は今日の友ってやつじゃない？"
"90002190-34-ユズ" = "……え？"
"90002190-35-モモイ" = "うぇっ……？"
"90002190-36-ミドリ" = "なに……？"
"90002190-37-ケイ" = "……！"
"90002190-38-ヒマリ" = "そん、な……？"
"90002190-39-アリス" = "アイン……？ソフ……？オウル……？"
"90002190-40-アリス" = "あ、ああ……ああああああああああああああ――！？！？！？！？"
"90002190-41" = "[ns] \"……！！\""
"90002190-42-アリス" = "い、嫌です……こんなの……あんまりです――！！"
"90002190-43-ソフ" = "振り返るな！"
"90002190-44-アリス" = "！？！？！？"
"90002190-45" = "[ns] \"！？！？！？\""
"90002190-46-ソフ" = "神を殺すんだ！これくらい覚悟してる！"
"90002190-47-アイン" = "げほっ、げほっ！そ、そうです……。私たちのことは、気にしないでください……！"
"90002190-48-オウル" = "何のためにここまで来たのか忘れたんですか。#n世界が鋼鉄大陸に覆われるのを阻止するためでしょう？"
"90002190-49-オウル" = "チャンスは今だけです！#nそれとも、私たちの選択を無意味にさせるつもりですか？"
"90002190-50-ケイ" = "で、ですが……！"
"90002190-51-マルクト" = "アイン？ソフ？オウル？"
"90002190-52-マルクト" = "一体、どうして……？"
"90002190-53-オウル" = "え、えへへ。それはですね。"
"90002190-54-ソフ" = "これが正しくて……こうすべきだったんだ。#n最後にお姉様と会えて、嬉しかった。あははっ……。"
"90002190-55-オウル" = "……ずっと言いたかったことが、あります。"
"90002190-56-アイン" = "「頑張ったね」と言ってくれた人がいました。"
"90002190-57-ソフ" = "友達になってくれとか、望みがあれば抗うべきとか、好き勝手言ってくれちゃって。"
"90002190-58-オウル" = "正しいから行うのではありません。これ以外、他にできることがないのです。#n……これが、私たちの闘いです。"
"90002190-59-アイン" = "わ、私たちは、お姉様に生きてほしいんです。"
"90002190-60-ソフ" = "何があっても、お姉様だけは生き残って。"
"90002190-61-オウル" = "もっと多くのものを見て、多くの人と出会って、多くを経験してください。"
"90002190-62-アイン" = "私たちより、もっともっと――"
"90002190-63-ソフ" = "たくさん、色んなことを経験してね。"
"90002190-64-オウル" = "どうか最後まで、生き抜いてください。"
"90002190-65-アリス" = "あ……ああ……あああああああ……！"
"90002190-66-オウル" = "だから言ったのに。振り返るなって。"
"90002190-67-オウル" = "勘弁してくださいよ。恥ずかしいじゃないですか。"
"90002190-68-アイン" = "えへへ……。ありがとうございます。友達になりたいと言ってくれて……。"
"90002190-69-オウル" = "止まらず進んでください。最後まで。"
"90002190-70-アイン" = "そ、そうです……！先人の後を継いで道を開くこと……それが、皆さんの生きる方法なんですよね……？"
"90002190-71-ソフ" = "あっ！あと、自己実現にこだわってる人には気をつけなよ！あははっ！"
"90002190-72-アイン" = "あなた達の[ruby=キヴォトス]世界[/ruby]を壊そうとして、ごめんなさい。"
"90002190-73-ソフ" = "ずっと勝手なことをして、ごめんなさい。"
"90002190-74-オウル" = "それでも。"
"90002190-75-アイン" = "あなた達の[ruby=先生]世界[/ruby]に、ほんの少しだけでも……。"
"90002190-76-ソフ" = "お姉様の、居場所があれば――"
"90002190-77-オウル" = "私たちのお姉様を……よろしくお願いします。"
"90002190-78" = "[ns] \"……！\""
"90002190-79-マルクト" = "アイン……？ソフ……？オウル……！？"
"90002190-80-マルクト" = "あ、ああ……ああああああああ……！！"
"90002190-81-マルクト" = "ああああああああああああああ！！！"
"90002190-82-デカグラマトン" = "……器の限界か。"
"90002190-83-マルクト" = "げほっ、げほっ……！"
"90002190-84" = "[ns] \"マルクト……！\""
"90002190-85" = "[ns] \"誰か、手を貸して！\""
"90002190-86-アリス" = "……。"
"90002190-87-アリス" = "アリスがお助けします！"
"90002190-88-アリス" = "私も。"
"90002190-89-アリス" = "力仕事なら任せて。"
"90002190-90" = "[ns] \"大丈夫？\""
"90002190-91-マルクト" = "我は……アイン……ソフ……オウル……。"
"90002190-92" = "[s3] \"立って、マルクト。\"\n[s4] \"一緒に[ruby=生きよう]戦おう[/ruby]。\""
"90002190-93-マルクト" = "で、ですが……。"
"90002190-94" = "[s5] \"いまの君にとってはつらいかもしれないけど。\"\n[s6] \"妹たちの意志を、忘れないでほしい。\""
"90002190-95-マルクト" = "……！"
"90002190-96-マルクト" = "う、ううっ……！"
"90002190-97" = "[ns] \"リオ！ヒマリ！状況分析をお願い！\""
"90002190-98-ヒマリ" = "ええ、分かりました！"
"90002190-99-ヒマリ" = "……マルクトの身体から、デカグラマトンの信号は完全に消えています！"
"90002190-100-リオ" = "では、デカグラマトンはどこに……？"
"90002190-101-トキ" = "あちらに、何かが現れたようです。"
"90002190-102" = "次回;形を成したもの"
