[translation]
"10046140-1-ナギサ" = "はあ、どうしてこんなことに……。"
"10046140-2-ナギサ" = "申し訳ありません。まさかこのような事態になるなんて。"
"10046140-3-イチカ" = "はは……大丈夫です。いつものことですから。"
"10046140-4-ナギサ" = "いつものこと……？"
"10046140-5-ナギサ" = "まさか、トリニティの治安はここまで悪化しているのですか……？#nそんな情報は――"
"10046140-6-イチカ" = "あっ、いえ……あくまで[ruby=・]私[/ruby][ruby=・]に[/ruby][ruby=・]と[/ruby][ruby=・]っ[/ruby][ruby=・]て[/ruby][ruby=・]は[/ruby]という意味です。#n私は自治区の境界とか、外でのパトロールが多いので。"
"10046140-7-ナギサ" = "なるほど……それでも、負担が大きすぎるのは望ましくありませんね。#nこの件は、ツルギさんとハスミさんにも話をしてみます。"
"10046140-8-イチカ" = "よろしくお願いします……。"
"10046140-9-ナギサ" = "ああ、それと……話は変わりますが……。"
"10046140-10-ナギサ" = "立場がある以上、普段の私は安易に動くことができません。"
"10046140-11-ナギサ" = "ですが今日は、一人の生徒として休暇を楽しんでいます。"
"10046140-12-ナギサ" = "多少のサポートならできると思いますが……いかがでしょうか？"
"10046140-13-イチカ" = "えっ！？#nまさか……ナギサ様ご自身でパトロールするおつもりですか？"
"10046140-14-ナギサ" = "ええ。この事態は、私の見込みの甘さが招いたも同然ですので。"
"10046140-15-ナギサ" = "であれば、すべて任せきりにするわけにはいきません。"
"10046140-16-ナギサ" = "い、いえいえ！本当に大丈夫ですから！"
"10046140-17-ナギサ" = "どうかお願いします。#nこのままでは、私の気が収まらないのです。"
"10046140-18-イチカ" = "そ、そこまでおっしゃるのなら……。"
"10046140-19-イチカ" = "……分かりました。"
"10046140-20-ナギサ" = "ふふ、至らぬ点もあるかと思いますが、よろしくお願いします。"
"10046140-21-イチカ" = "（どうしよう……）"
"10046140-22-イチカ" = "（いまさらダメとも言えないし……）"
"10046140-23-イチカ" = "（でも万が一、ナギサ様に何かあったら……）"
"10046140-24-イチカ" = "（……）"
"10046140-25-イチカ" = "（…………）"
"10046140-26-イチカ" = "（絶対にお守りしないと）"
