[translation]
"10052015-1-ミドリ" = "……。"
"10052015-2-ミドリ" = "……。"
"10052015-3-モモイ" = "え、夢じゃないよね……？"
"10052015-4-ミドリ" = "うん、現実だと思う。くねくね動いてて……すごかったね……。"
"10052015-5-ミドリ" = "私たち、無事に帰れるのかな……。"
"10052015-6-エイミ" = "心配ないよ。先生がいるんだから。"
"10052015-7-エイミ" = "きっと、大丈夫。"
"10052015-8-ユズ" = "ど、どうしてそんなに落ち着いてるんですか……？"
"10052015-9-エイミ" = "うーん、理由は色々あるけど……。"
"10052015-10-エイミ" = "前にも遭遇したことあるからかな。"
"10052015-11" = "[ns] \"ところで、ビナーのコアは？\""
"10052015-12-ケイ" = "そのことなんですが……。"
"10052015-13-ケイ" = "結論から言いますと、穴を降りる必要があります。#n反応からして、コアはこの底にあるみたいです。"
"10052015-14-ミドリ" = "ええっ！？降りる！？"
"10052015-15-ミドリ" = "もしかして、この先も毎回……？"
"10052015-16-ユズ" = "いえ、先ほども話しましたが、ビナーが特殊なだけだと思います。#nある種のセキュリティ対策なのでしょうね。"
"10052015-17-ユズ" = "ぶ、物理的な対策だね……。"
"10052015-18-エイミ" = "でも、底が見えないのに、ただただ降りるのは非効率的すぎるよ……。"
"10052015-19-エイミ" = "部長、輸送船にある小型の支援機、送ってくれる？"
"10052015-20-ヒマリ" = "すでに向かわせています。"
"10052015-21-ヒマリ" = "……ちなみに、リオも一緒です。止めても聞かなかったので。"
"10052015-22-エイミ" = "会長も来るの？"
"10052015-23-ヒマリ" = "はい。追加の調査で、ネットワーク経由ではファイアウォールを突破できないことが判明しまして……。"
"10052015-24-ヒマリ" = "現場に出向くのが最も合理的だ、と……。"
"10052015-25-ケイ" = "……リオらしいですね。"
"10052015-26" = "（まもなく小型の支援機が到着し、リオが姿を現した）"
"10052015-27" = "（みんなの何とも言えない顔に、リオは首を傾げていた）"
