[translation]
"10052120-1" = "儀式"
"10052120-2-アイン" = "うああああああ！？！？"
"10052120-3-オウル" = "第二防御線まで……？嘘でしょう……？"
"10052120-4-ソフ" = "……。"
"10052120-5-ソフ" = "状況を整理しよう。"
"10052120-6-オウル" = "は、はい……！#nの、残りの預言者のエリアは……2つだけです。"
"10052120-7-オウル" = "[ruby=ネツァク]鋼鉄大陸[/ruby]は、すでに70％以上を敵に占領されています。"
"10052120-8-オウル" = "……残る2つのエリアも、時間稼ぎにしかならないでしょう。"
"10052120-9-ソフ" = "多分、突破されるだろうね。"
"10052120-10-アイン" = "うぅ……！"
"10052120-11-ソフ" = "アイン、落ち着いて。認めるものは認めないと。善後策を考えるためにも。"
"10052120-12-アイン" = "ど、どこから……間違ってしまったのでしょう……。"
"10052120-13-アイン" = "や、やっぱり、私があの人たちを見くびったせいでしょうか……！？"
"10052120-14-アイン" = "ごめんなさい、ソフ……ごめんなさい、オウル……#nごめんなさい、お姉様、うえぇーん！！"
"10052120-15-マルクト" = "大丈夫ですよ、アイン。アインは何も間違っていません。"
"10052120-16-マルクト" = "[ruby=つかつき]調月[/ruby]リオという、想定外の変数が紛れ込んだのですから。"
"10052120-17-オウル" = "あるいは、王女と[ruby=侍女]鍵[/ruby]が原因かもしれません。"
"10052120-18-ソフ" = "それを言うなら、先生だって……。"
"10052120-19-ソフ" = "……。"
"10052120-20-ソフ" = "あとは……あっちの戦闘力が想定より高かったからかも……。"
"10052120-21-アイン" = "わ、私たちが鋼鉄大陸を、予定を早めて展開したせい……でしょうか……？"
"10052120-22-ソフ" = "でも、あのときに展開していなかったら……こうしてお姉様と会うこともなかったと思いますよ。"
"10052120-23-ソフ" = "うん……。"
"10052120-24-マルクト" = "ええ。その点について、アイン、ソフ、オウルに感謝しています。"
"10052120-25-アイン" = "お姉様……。"
"10052120-26-マルクト" = "ソフもオウルも、こちらへ来てください。#n我が抱きしめてあげます。"
"10052120-27-ソフ" = "え、ええ……？"
"10052120-28-マルクト" = "これは、何かを打開できる行為ではありません。"
"10052120-29-マルクト" = "いわば、意味のない行為なのかもしれません。"
"10052120-30-マルクト" = "ですが……少し、心が落ち着きませんか？"
"10052120-31-マルクト" = "リラックスできれば、良いアイデアが浮かぶかもしれません。"
"10052120-32-アイン" = "うっ……うえぇぇん……。"
"10052120-33-マルクト" = "思いっきり泣いてください。ここには我々しかいません。"
"10052120-34-マルクト" = "大丈夫です、我がいます。我はアイン、ソフ、オウルに出会えて本当に嬉しく思っています。"
"10052120-35-ソフ" = "私たちは鋼鉄大陸の統制権を奪われ続けてる。"
"10052120-36-オウル" = "ですが、まだそこまで深刻な問題ではないとも言えます。"
"10052120-37-オウル" = "あの鍵……ケイが使っている「身体」を取り戻せば、すべて元通りです。"
"10052120-38-アイン" = "け、結局……セキュリティレベルとアクセス権の問題ですから！"
"10052120-39-ソフ" = "鋼鉄大陸の拡張は止まったけど、それも何とかできるはず。"
"10052120-40-ソフ" = "ネツァクの各エリアの統制権を取り戻せばいいからね！"
"10052120-41-マルクト" = "残りの戦力は2体の預言者。"
"10052120-42-マルクト" = "そして――"
"10052120-43-マルクト" = "我、ですね。"
"10052120-44-ソフ" = "……。"
"10052120-45-マルクト" = "前は、我に与えられた出力が強すぎるが故、身体がもちませんでした。"
"10052120-46-マルクト" = "つまり[ruby=強度]耐久度[/ruby]の問題さえ解決できれば、我はすべての[ruby=出力]可能性[/ruby]を余すことなく発揮できるはずです。"
"10052120-47-オウル" = "それを解決するのは、私たちの仕事ですね！"
"10052120-48-アイン" = "か、必ず完全な姿で、お姉様を羽ばたかせてあげます！！！"
"10052120-49-オウル" = "一応、預言者を活用できる余地も、僅かですが残っています。"
"10052120-50-ソフ" = "そうなの？"
"10052120-51-アイン" = "アイン、説明をお願いします。"
"10052120-52-アイン" = "えっと……。"
"10052120-53-アイン" = "鋼鉄大陸の内側にいた預言者たちは、ネツァクの一部へと戻ることになりますが……。"
"10052120-54-アイン" = "鋼鉄大陸の外側にいた預言者たちは、その残骸が……残りますよね……？"
"10052120-55" = "そうだろうけど……それで？"
"10052120-56-ソフ" = "……待って、まさか？"
"10052120-57-オウル" = "そのまさかです。"
"10052120-58-ソフ" = "できるの！？"
"10052120-59-アイン" = "ここまで運んでくれば、ですが……。"
"10052120-60-ソフ" = "問題は運搬のほうか……。"
"10052120-61-オウル" = "しかも、こっそりやらないといけませんし……。"
"10052120-62-アイン" = "ただでさえ難しいのに、さらに条件が加わるなんて……。"
"10052120-63-アイン" = "無謀でしょうか……？"
"10052120-64-ソフ" = "……。"
"10052120-65-ソフ" = "いいや、仕事は難しいくらいがちょうどいいよ。"
"10052120-66-オウル" = "おぉ、さすがです、ソフ！"
"10052120-67-ソフ" = "ほ、本当ですか！？"
"10052120-68-ソフ" = "うん。レイバーの生産は、まだ少し余力があるから。"
"10052120-69-アイン" = "よ、良かったです！じゃあ私も……！"
"10052120-70-ソフ" = "ううん。アインは残ってて。"
"10052120-71-アイン" = "はい……！？#nや、やっぱり私は頼りないから……。"
"10052120-72-ソフ" = "違う違う。アインが一番重要だからだよ。これからすごく忙しくなるんだから。"
"10052120-73-アイン" = "……わ、私がですか？"
"10052120-74" = "そうです。この先、アインがいないと私たちは何もできませんので。"
"10052120-75-アイン" = "は、はいぃぃっ！？！？"
"10052120-76-ソフ" = "アイン、よく聞いて。#nやってもらいたいことは大きく分けて2つあって……。"
"10052120-77-ソフ" = "……分かった？"
"10052120-78-アイン" = "……。"
"10052120-79-マルクト" = "アイン？大丈夫ですか？"
"10052120-80-ソフ" = "アイン！？"
"10052120-81-オウル" = "やっぱり、プレッシャーが大きすぎましたかね。"
"10052120-82-オウル" = "ですが……アイン、お願いします。"
"10052120-83-オウル" = "これの如何によって、私たちの可能性は大幅に減ってしまうんです。"
"10052120-84-オウル" = "マルクトお姉様の強化は、頑張れば私たちでも何とかできるかもしれません。"
"10052120-85-オウル" = "ですがもう1つは、アインにしかできないのです。"
"10052120-86-アイン" = "……。"
"10052120-87-アイン" = "分かりました。やってみます。#n……いえ、やります。"
"10052120-88-アイン" = "絶対に、必ず！死ぬ覚悟で！"
"10052120-89-アイン" = "いえ、死んでも！"
"10052120-90-アイン" = "落ち着いて、アイン……。#n私たちの中で誰一人そうならないためにやるんだから。"
"10052120-91-アイン" = "そ、そうですよね……！"
"10052120-92-アイン" = "でも……それくらい頑張ります！"
"10052120-93-オウル" = "まあ、流石に例え話で言っているのでしょうけど……。"
"10052120-94-マルクト" = "……。"
"10052120-95-マルクト" = "ありがとうございます、アイン。"
"10052120-96-マルクト" = "我の身体を、よろしくお願いします。"
"10052120-97-アイン" = "はい！！！"
"10052120-98-？？？" = "実在と非実在の区別を問うことは、もう古いでしょう。#n両者の違いは、対象の受け取り方が異なる程度のことですから。"
"10052120-99-？？？" = "なにせ、両者に大きな違いはありません。"
"10052120-100-？？？" = "例えば、虚数は存在します。#n左右が反転し、時間が逆行する宇宙が存在する可能性があるのと同じように。"
"10052120-101-アリス" = "！！！"
"10052120-102-ケイ" = "聞きましたか？"
"10052120-103-アリス" = "は、はい！今回はその内容をちゃんと……！"
"10052120-104-アリス" = "内容は……！"
"10052120-105-アリス" = "うわぁーん！覚えているのに説明できません！"
"10052120-106-ケイ" = "大丈夫です。私も聞きましたので。#n多元宇宙に関する比喩でした。"
"10052120-107-アリス" = "たげん……うちゅう……？"
"10052120-108-ケイ" = "左右が入れ替わり、時間が逆行する宇宙のことです。"
"10052120-109-ケイ" = "おかしく思えますが、存在しないという証拠はありませんので。"
"10052120-110-ケイ" = "……ということは、あの声の主は、まさか……。"
"10052120-111" = "ケイ？何か分かりましたか？"
"10052120-112-ケイ" = "実は、まったく見当がつかないわけではありません。#nですが……だからといって、これを説明するわけにはいかないんです。"
"10052120-113-ケイ" = "ごめんなさい、アリス。あなたにだけは隠し事をしたくないのですが……これは、あなたにだけは言えないかもしれません……。"
"10052120-114-アリス" = "……。"
"10052120-115-アリス" = "それは、アリスと先生、みんなのやるべきことが変わってしまうような問題ですか？"
"10052120-116-ケイ" = "はい？いいえ……違うと思います。ただ……。"
"10052120-117-ケイ" = "もしも、あれが介入してきたら……。"
"10052120-118-アリス" = "……分かりました。アリスは、アリスがやるべきことを続けます。"
"10052120-119-アリス" = "分からないことについて深く考えても、あまり良いことはないので。"
"10052120-120-ケイ" = "……そうしましょう。#n残りのエリアは……あと2つだけですからね。"
