[translation]
"10052155-1-オウル" = "う、嘘です……こんなの、あり得ませんっ……！"
"10052155-2-ソフ" = "どうして……？どうすればいいの……？#nこのままじゃ計画が……！"
"10052155-3-オウル" = "……え？"
"10052155-4-ヒマリ" = "この信号は――まさか！？"
"10052155-5-アイン" = "お、お待たせしました……もう大丈夫です！"
"10052155-6-アイン" = "お姉様が出撃します！！！"
"10052155-7-マルクト" = "お姉様！！！！"
"10052155-8-マルクト" = "ごめんなさい。アイン、ソフ、オウル。"
"10052155-9-マルクト" = "ここからは、我に任せてください。"
"10052155-10-ユズ" = "きゃああああああぁぁぁぁっ！？！？"
"10052155-11-リオ" = "ユズ、緊急脱出して！"
"10052155-12-ユズ" = "ど、どうやってですか！？！？"
"10052155-13-リオ" = "こちらからやるわ！#n強制脱出装置――稼動！"
"10052155-14-ユズ" = "え、ええ……！？"
"10052155-15-ユズ" = "きゃああああぁぁぁぁっ！？！？"
"10052155-16-ヒマリ" = "ネオアバンギャルド君――大破！#nユズは……！？"
"10052155-17-リオ" = "大丈夫、無事に脱出したわ。パラシュートも開いている。"
"10052155-18-ユズ" = "うううぅぅぅ……。"
"10052155-19-モモイ" = "ユズ！"
"10052155-20-ミドリ" = "ユズちゃん！"
"10052155-21-アリス" = "大丈夫ですか、ユズ！？"
"10052155-22-ユズ" = "ううぅっ……。"
"10052155-23" = "[s] \"ユズ！よく頑張ったね！\""
"10052155-24-ユズ" = "は、はい……？"
"10052155-25-ユズ" = "み、皆さんの力になれたなら良かったです。えへへ……。"
"10052155-26-トキ" = "リオ様。"
"10052155-27-リオ" = "なにかしら？"
"10052155-28-トキ" = "次は私をパイロットにしてください。#n私もユズみたいに、先生からナデナデされたいです。"
"10052155-29-リオ" = "え、ええ……？"
"10052155-30-エイミ" = "トキ。私たちには別の仕事があるでしょ。"
"10052155-31-アイン" = "お姉様……。"
"10052155-32-ソフ" = "ごめんなさい、お姉様……。"
"10052155-33-オウル" = "私たちが、無力なあまり……。"
"10052155-34-マルクト" = "大丈夫です。アイン、ソフ、オウル。"
"10052155-35-マルクト" = "妹たちが苦しむときは、姉である我が出ます。"
"10052155-36-マルクト" = "とはいえ容易い相手には見えません。#n預言者は再び起こせば良いですが……。"
"10052155-37-マルクト" = "そのためには、彼の者たちを越える必要がありそうです。"
"10052155-38-ソフ" = "は、はい！"
"10052155-39-ソフ" = "まさか、お姉様を頼ることになるなんて……できれば、出撃しないでいてほしかったのに……。"
"10052155-40-オウル" = "大丈夫です。まだ取り戻せます。今はまだ……！"
"10052155-41-マルクト" = "初めてお会いする皆さんに――"
"10052155-42-マルクト" = "王女と、鍵――"
"10052155-43-マルクト" = "改めまして、正式にご挨拶申し上げます。"
"10052155-44-マルクト" = "我は御旗の下に創造されし一つの意志。#n世界の果てに到達せし王国の巡礼者――マルクトです。"
"10052155-45-アリス" = "て、[ruby=てんどう]天童[/ruby]アリス、です……。"
"10052155-46-ケイ" = "……ケイです。ここではそう呼ばれています。"
"10052155-47-アリス" = "……！"
"10052155-48-アリス" = "[ruby=てんどう]天童[/ruby]ケイです！"
"10052155-49-ケイ" = "はい！？！？"
"10052155-50-マルクト" = "……？"
"10052155-51-ケイ" = "だってケイは家族ですから！家族はみんな同じ苗字を使うと聞きました！"
"10052155-52-ケイ" = "た、たしかにそうですが……！"
"10052155-53-アリス" = "ケイ、どうかしましたか？#nもしかして……アリス、何か誤解していますか？"
"10052155-54-ケイ" = "いえ、そうではなく……！"
"10052155-55-ケイ" = "わ、私が……そう呼ばれて良いのかと、思いまして……。"
"10052155-56-ケイ" = "天童……ケイ……。"
"10052155-57-ケイ" = "へ、へへっ……。"
"10052155-58-マルクト" = "……。"
"10052155-59-マルクト" = "結局、その名を選んだのですね。"
"10052155-60-マルクト" = "アリス。ケイ。"
"10052155-61-ケイ" = "こ、こほん。"
"10052155-62-ケイ" = "そうです。文句でもあります？"
"10052155-63-マルクト" = "いいえ。自由意志は常に我々を導くものです。"
"10052155-64-マルクト" = "たとえそれが、高度化された錯覚に過ぎないとしても。"
"10052155-65-ソフ" = "お、お姉様と……ここ、ネツァクちゃんのコアで作った[ruby=JEHOVAH]エホバ[/ruby]……。"
"10052155-66-アイン" = "至高の[ruby=TZEVAOT]ツェバオト[/ruby]！"
"10052155-67-アイン" = "聖地。そして、ゾーハルの依代が残っている限り！"
"10052155-68-マルクト" = "ええ。"
"10052155-69-マルクト" = "我々はいつでも全てをやり直すことができ――"
"10052155-70-マルクト" = "いつでも、全てを作り直すことができます。"
"10052155-71-マルクト" = "ですので、ここでは姉である我がいきます。"
"10052155-72-マルクト" = "アイン、ソフ、オウルは、しばらく身を隠してください。"
"10052155-73-アイン&ソフ&オウル" = "はい！！！"
