[translation]
"10014040-1" = "第4話;放課後スイーツ団？"
"10014040-2" = "（……翌日）"
"10014040-3-カズサ" = "ああ、先生……来てたんだ。"
"10014040-4-カズサ" = "……それで、どうしたの？"
"10014040-5-カズサ" = "まさか、また何かあったわけじゃないよね？"
"10014040-6-カズサ" = "あ、いや。#n怒ってるとかじゃなくて、純粋に気になって……"
"10014040-7-カズサ" = "……え？"
"10014040-8-カズサ" = "解決のために「相談」を続けた方がいい……？"
"10014040-9-カズサ" = "……相談？#nそれはそうだけど……"
"10014040-10-カズサ" = "宇沢じゃなくて……私が？#n相談の対象って私なの？どうして……？"
"10014040-11-カズサ" = "うーん。まぁ、大人の先生がそう言うなら、そうなんだろうね。#nいちいち理由を聞くのも良くないと思うし。"
"10014040-12-カズサ" = "じゃあ、とりあえず座ろっか……"
"10014040-13-？？？" = "へいへ～い#nそこのかわい子ちゃん～"
"10014040-14-？？？" = "退屈そうだね～#nお姉さんたちと楽しく遊ばない～？"
"10014040-15-カズサ" = "……？"
"10014040-16" = "[ns] \"この声は……\""
"10014040-17-カズサ" = "……？"
"10014040-18-カズサ" = "……？？？"
"10014040-19-ナツ" = "ハッハッハ！#n慌ててるねぇ。なかなか可愛い顔をするじゃあないか。"
"10014040-20-アイリ" = "あ、当たり前です！#nわ、私たちは怖いですからね！ふ、不良なんですから！"
"10014040-21-ヨシミ" = "えー……これで合ってる？#n本当に大丈夫？"
"10014040-22-カズサ" = "……なに？"
"10014040-23" = "[s3] \"……？？？\"\n[s4] （不良のコスプレ……？）"
"10014040-24-カズサ" = "あ、あんた達……ここで何してるの？#n……その格好は一体？"
"10014040-25-カズサ" = "あ、あんた達……ここで何してるの？#n……その格好は一体？"
"10014040-26-アイリ" = "か、カズサちゃん！#nカズサちゃんが何者だったとしても、私たちはカズサちゃんと一緒だよ！"
"10014040-27-カズサ" = "それはありがたいけど……#nそれ以上に、今なにしてるのか聞いてるんだけど……。"
"10014040-28-カズサ" = "マジで意味わかんないんだけど。#n何なのそれ？ナツの話し方もヘンだし……。"
"10014040-29-ナツ" = "ふっふっふ……拒む必要はないのだよカズサ。"
"10014040-30-ナツ" = "これからの人生、今までとは違う世界……共に行こうじゃないか。"
"10014040-31-カズサ" = "これからの人生……？今までとは違う世界……？"
"10014040-32-アイリ" = "……いや、ちょっと待ってよ。#nコレ、単純に理解できてないんじゃないの？"
"10014040-33" = "[s5] \"えっと、説明してもらえるかな。\"\n[s6] \"コスプレ失敗だね……。\""
"10014040-34-アイリ" = "今日から私たちの部活は「放課後スイーツ部」から#n「放課後スイーツ団」に変えることにしたのだ。"
"10014040-35-アイリ" = "今日から私たちの部活は「放課後スイーツ部」から#n「放課後スイーツ団」に変えることにしたのだ。"
"10014040-36-アイリ" = "カズサちゃん！#n私たち、カズサちゃんが無理しないで一緒に居られるようにしたいんだ。"
"10014040-37-カズサ" = "いや、「部」が「団」に変わっただけじゃん。#nなんで急にそんな事するのさ……。"
"10014040-38-カズサ" = "一体どういう……"
"10014040-39-アイリ" = "ねえ、待って。これ、やっぱり理解できてなくない？"
"10014040-40-ヨシミ" = "まず、私たちの意図からちゃんと説明しないと……"
"10014040-41-？？？" = "やっぱり！！そうだと思ってました！！！"
"10014040-42" = "[ns] \"……あ。\""
"10014040-43-ヨシミ" = "……？？"
"10014040-44-アイリ" = "あれ、この声は……"
"10014040-45-ナツ" = "……聞き覚えのある。"
"10014040-46-レイサ" = "……そうだったんですね。#nやっぱりそういう事でした……！"
"10014040-47-レイサ" = "もしかしたら、本当に悔い改めてるのではないかと思ったのに……やっぱり！#nそんな事ないですよね！！"
"10014040-48-レイサ" = "あなたの邪悪な本性は、そう簡単に変わるようなものではないでしょうから！"
"10014040-49-レイサ" = "「放課後スイーツ団」……なんという恐ろしい名前！！"
"10014040-50-レイサ" = "まるでやわらかいスイーツを食べるように……#n辺り一帯を食べ尽くすという恐ろしい意味なのでしょうね！？"
"10014040-51-レイサ" = "さらに、また先生を誘拐して……！#n公権力まで掌握しようとするなんて！！"
"10014040-52-レイサ" = "やはり、あなたは再起のチャンスを窺っていた……"
"10014040-53-レイサ" = "そう、復活のために新しい組織を立ち上げたのですね[ruby=きょうやま]杏山[/ruby]カズサ！"
"10014040-54-レイサ" = "いえ……"
"10014040-55-レイサ" = "「キャスパリーグ」！！"
"10014040-56-トリニティの生徒B" = "何の話……？#nキャス……なに？"
"10014040-57-トリニティの生徒B" = "キャスパリーグって伝説のスケバンでしょ？#nあの子たちスケバンなの？"
"10014040-58-ナツ" = "……キャスパ……なに？"
"10014040-59-ナツ" = "誘拐……！？"
"10014040-60-ナツ" = "……カズサが！？#n先生を誘拐！？"
"10014040-61-アイリ" = "か、カズサちゃん……？#n本当なの！？"
"10014040-62-カズサ" = "いや、なに言ってんの！？"
"10014040-63" = "[s9] \"カズサ……そういうことだったの！？\"\n[s10] \"誤解というのはあっという間に大きくなってしまうもの。\""
"10014040-64-カズサ" = "アホか！あなたが呼んだんでしょうが！！"
"10014040-65-カズサ" = "先生、なに普通に解説してんの！！"
"10014040-66-カズサ" = "今ふざけてる場合じゃないんだって！#n変な噂が広まっちゃう前に早く訂正しないと……"
"10014040-67-カズサ" = "いま、先生を脅迫しましたね？"
"10014040-68-レイサ" = "大人相手にそんな態度をとれるなんて……やはり無慈悲ですね、杏山カズサ！！"
"10014040-69-カズサ" = "……くそ。#nもう遅いか。"
"10014040-70-カズサ" = "さっきから何言ってんの、あいつ……"
"10014040-71-ヨシミ" = "ねえ、ちょっとカズサ。#nあいつどうにかしなさいよ。あんたの友達でしょ？"
"10014040-72-カズサ" = "……いや、友達じゃないんですけど！？"
"10014040-73-レイサ" = "……許せません。#nこの地の平和のために！みんなが安心して登校できる街のために！！"
"10014040-74-レイサ" = "覚悟してください、杏山カズサ。#nそして「放課後スイーツ団」！！"
"10014040-75-レイサ" = "今度こそ、あなたたちを倒して正義を実現します！！"
"10014040-76-レイサ" = "挑戦状を受け取ってください！！"
"10014040-77-カズサ" = "いや、だからちょっと……"
"10014040-78-ナツ" = "ふっふっふ……。#nその挑戦、受けて立とう。"
"10014040-79-アイリ" = "そ、そうです！#nよく分からないですけど、これ以上カズサちゃんをいじめるのは許しません！！"
"10014040-80-アイリ" = "あなたが誰かは知りませんが……私たちも黙っていませんから！！"
"10014040-81-カズサ" = "……なに？"
"10014040-82-レイサ" = "決闘成立ですね……いいでしょう。#n覚悟してください！！"
"10014040-83-ナツ" = "私たち「放課後スイーツ団」の結束を見せてやろう！！"
"10014040-84-ナツ" = "攻撃ぃぃぃいー！！！"
"10014040-85-アイリ" = "わ、わぁー！！！"
"10014040-86-レイサ" = "とりゃああああああーっ！"
"10014040-87-カズサ" = "先生……#n私、どうすれば……"
"10014040-88" = "[s13] \"行くよ！！『放課後スイーツ団』！！\"\n[s14] \"やわらかなスイーツを食べるように、一帯を掌握してやろう！！\""
"10014040-89-カズサ" = "……。"
"10014040-90-カズサ" = "……。"
"10014040-91-カズサ" = "……私は。"
"10014040-92-カズサ" = "ああ、変われたと思っていたのは私だけで。#n結局、過去の罪が追いかけてきてるのかな……。"
