[translation]
"10014020-1" = "第2話;誰だって一つや二つくらい"
"10014020-2-カズサ" = "もうすぐ正門だし、ここまで来たら安心。"
"10014020-3-カズサ" = "いくらあいつでも校内では騒がないと思うし……。"
"10014020-4-カズサ" = "うーん……。"
"10014020-5-カズサ" = "なんか、先生がエスコートしてくれたみたいになっちゃったね。"
"10014020-6-カズサ" = "……ご迷惑をおかけしてすみません。"
"10014020-7-カズサ" = "そして、手伝ってくださってありがとうございます。"
"10014020-8" = "[s1] \"……礼儀正しいね、カズサは。\"\n[s2] \"急にかしこまってどうしたの？\""
"10014020-9-カズサ" = "え、そ、そうかな？"
"10014020-10-カズサ" = "え、そ、そうかな？"
"10014020-11-カズサ" = "そりゃ、先生だし……目上の人だし……。"
"10014020-12-カズサ" = "とにかく。今回の相談はここまで。#n後でまた時間作って会いに行くね。"
"10014020-13-カズサ" = "……ん？"
"10014020-14-カズサ" = "今更だけど過去のこと話して良かったのかって？#n……なにを？"
"10014020-15-カズサ" = "……スケバンの話？"
"10014020-16-カズサ" = "あー……「隠していた過去」じゃないのかって事か。"
"10014020-17-カズサ" = "そうだね……。"
"10014020-18-カズサ" = "まぁ、胸を張って言えるような事じゃないけど……。"
"10014020-19-カズサ" = "でも仕方ないでしょ。事実は事実だし。"
"10014020-20-カズサ" = "隠したいとかじゃないんだけど……ただ、あんまり思い出したくないかな。#nそんな感じ。"
"10014020-21-カズサ" = "思い出しても疲れるだけだし……。"
"10014020-22-カズサ" = "……[ruby=うざわ]宇沢[/ruby]もいい加減気づけばいいのに。"
"10014020-23-カズサ" = "私たち、もう高校生なのにさ。#nいつまでも子供みたいな事……。"
"10014020-24-カズサ" = "そろそろ、中学の時と違うってわかってほしいんだけどな。#n昔の感覚で突っかかって来られるの、いい加減ウザいんだよね。"
"10014020-25-カズサ" = "……高校生なんだから、もう中学の姿とか忘れてもいい頃じゃない？"
"10014020-26-カズサ" = "お互い忘れて、新生活を満喫すればいいのに……。#nどうしてあんな事するのか、心底理解できない。"
"10014020-27" = "[s] \"……。\""
"10014020-28-カズサ" = "……？"
"10014020-29-カズサ" = "……どうしたの？"
"10014020-30-カズサ" = "……え？"
"10014020-31-カズサ" = "スケバンをやめたきっかけ……？"
"10014020-32-カズサ" = "あー……それは……。"
"10014020-33-カズサ" = "急に聞いてくるんだね……？#n……まぁ、その……。"
"10014020-34-カズサ" = "やっぱ、スケバンは……ちょっと……。"
"10014020-35-カズサ" = "っていうか、急に何でそんな事聞くの！？#n別にそんな珍しい事でもないでしょ？"
"10014020-36-カズサ" = "誰だって言いたくない過去の一つや二つくらいあるものじゃん……"
"10014020-37-カズサ" = "スパイだったとか、銀行を襲ったとか、メイドに見せかけたエージェントとか、#n忍者とか……。"
"10014020-38-カズサ" = "きっと、そういう人もたくさんいるだろうし。#n別に特別なことじゃないでしょ。"
"10014020-39" = "[s3] \"そ、そうだね……。\"\n[s4] \"……微妙に否定しにくい。\""
"10014020-40-カズサ" = "ほらね。私だって変わらないよ。"
"10014020-41-カズサ" = "ほらね。私だって変わらないよ。"
"10014020-42-カズサ" = "ちゃんと『その時』になったら分別がつくようになる。#nだから、当時のことはもう聞かないで。……恥ずかしいから。"
"10014020-43-カズサ" = "……そう。#nああいうの、恥ずかしいの。"
"10014020-44-カズサ" = "……あ、時間が……。"
"10014020-45-カズサ" = "さすがに先生の前で遅刻はできないから、先に入るね。#nまたね、先生。"
"10014020-46-カズサ" = "今日は本当にありがとう、先生。#n相談して、少しスッキリした。"
"10014020-47-カズサ" = "……本当にありがとうございます。"
"10014020-48-カズサ" = "それじゃ。"
"10014020-49" = "（…………）"
"10014020-50" = "[ns] \"……自警団か。\""
"10014020-51-？？？" = "……あ、先生。こちらです。"
"10014020-52-スズミ" = "お待ちしておりました、先生。#n聞きたい事とはなんでしょう？"
"10014020-53-スズミ" = "あ、いえ。負担だなんてとんでもないです。#nむしろ、私としてはこのような機会を頂けてとても嬉しいです。"
"10014020-54-スズミ" = "先生にはいつもお世話になっていますので……。"
"10014020-55-スズミ" = "私にできることなら、誠心誠意お手伝いさせてください。"
"10014020-56-スズミ" = "……あ、授業ですか？#n大丈夫です。今の時間はなにもないので。"
"10014020-57-スズミ" = "学年やクラスごとに時間割も違いますから。#nお気遣いありがとうございます。"
"10014020-58-スズミ" = "それで、聞きたい事とは……"
"10014020-59-スズミ" = "……え、自警団メンバーに関すること？#nなるほど……それで私に……。"
"10014020-60-スズミ" = "ですが、お役に立てるかどうか……。#n自警団は、普通の「組織」ではないので。"
"10014020-61-スズミ" = "文字通り「自警団」ですから。#n各々、近隣の治安を守ろうと自発的に集まって結成されました。"
"10014020-62-スズミ" = "誰が所属していて、どのような活動をしているのか。#n全てを把握するのは難しく……。"
"10014020-63-スズミ" = "……えっ？"
"10014020-64-スズミ" = "宇沢レイサ……さんですか？"
"10014020-65" = "[s5] \"前に一緒にいるのを見たことがあって。\"\n[s6] \"スズミもレイサの事は知ってるかなって。\""
"10014020-66-スズミ" = "……そうですね。#nレイサさん……ですか。"
"10014020-67-スズミ" = "……そうですね。#nレイサさん……ですか。"
"10014020-68-スズミ" = "また何か問題を起こしたのですね。#n今度は大事ではないと良いのですが……。"
"10014020-69" = "[s7] \"ちょっと待って。今「また」って……。\"\n[s8] \"問題児なの……？\""
"10014020-70-スズミ" = "決して悪い方ではありません。#n志はとても立派な方です。"
"10014020-71-スズミ" = "決して悪い方ではありません。#n志はとても立派な方です。"
"10014020-72-スズミ" = "その……少しエネルギッシュすぎて人と馴染めない部分もありますが……。"
"10014020-73-スズミ" = "でも意外ですね。#nいくらレイサさんでも、先生に迷惑をかけたりはしないと思っていたのですが……。"
"10014020-74-スズミ" = "……ああ、他の方に関する事……なるほど。"
"10014020-75-スズミ" = "そうですね。よろしければ、少し状況を聞かせていただけませんか。#nその方の個人情報は伏せていただいて大丈夫ですので……。"
"10014020-76" = "[ns] 現状を説明する。"
"10014020-77-スズミ" = "……なるほど。"
"10014020-78-スズミ" = "レイサさんらしいですね。#nお相手も困っている事でしょう。"
"10014020-79-スズミ" = "それにしても驚きました。#nスケバンの事は詳しいと自負していたのですが……。"
"10014020-80-スズミ" = "「スケバン社会」というのも存在するとは。#nやはり世の中は広いようです。"
"10014020-81-スズミ" = "……ですが、結局その方はスケバンをやめたわけですよね。#nレイサさんはどうしてずっと追いかけているのでしょう？"
"10014020-82-スズミ" = "もうスケバンではない人に、決闘の申込みを……。#n何か理由でもあるのでしょうか。"
"10014020-83-スズミ" = "……これは、レイサさんに直接お聞きした方がよさそうですね。"
"10014020-84-スズミ" = "レイサさんなら私も連絡先を知っているので、呼べばすぐ来ると思います。"
"10014020-85-スズミ" = "先程も少しお話したように、行動力がある方ですから。"
"10014020-86-スズミ" = "それでは連絡を……。"
"10014020-87-スズミ" = "すみません、電話が……失礼します。"
"10014020-88-スズミ" = "……レイサさん？"
"10014020-89" = "[s9] \"レイサから連絡が？\"\n[s10] \"どうしたの？\""
"10014020-90-スズミ" = "あ……"
"10014020-91-スズミ" = "あ……"
"10014020-92-スズミ" = "……これは支援要請、ですね。"
