[translation]
"10014055-1-スケバンたち" = "う、ううっ……！？"
"10014055-2-レイサ" = "はぁ、はぁ……びっくりしました。"
"10014055-3-レイサ" = "せ、先生？大丈夫ですか？#nお怪我は……"
"10014055-4" = "[s1] \"私は全然問題ないよ。\"\n[s2] \"心配しないで、大丈夫だよ。\""
"10014055-5-レイサ" = "そ、そうですか。良かったです……。"
"10014055-6-レイサ" = "そ、そうですか。良かったです……。"
"10014055-7-レイサ" = "どうやら、[ruby=きょうやま]杏山[/ruby]カズサが新しい組織を再建するという噂が広まっているみたいですね。"
"10014055-8-レイサ" = "この一帯にいるスケバンにとっては、ただ事ではないでしょうから……何が何でも、組織が大きくなる前に止めようとかかってくる事でしょう。"
"10014055-9-レイサ" = "私のせいで……状況が複雑になってしまいました。"
"10014055-10" = "[s3] \"レイサのせいじゃないよ。\"\n[s4] \"誰のせいでもないよ。\""
"10014055-11-レイサ" = "あはは……ありがとうございます、先生。"
"10014055-12-レイサ" = "あはは……ありがとうございます、先生。"
"10014055-13-レイサ" = "ですが、事を大きくしてしまったのは私ですから。#nその事実は変わりません。"
"10014055-14-レイサ" = "これは、私が負うべき責任です。"
"10014055-15-レイサ" = "それに、杏山カズサ本人は……今はそんな人ではありませんし。"
"10014055-16-レイサ" = "なら、これ以上迷惑をかけるわけにはいかないじゃないですか……"
"10014055-17-レイサ" = "……忘れたい過去のことなんかで！"
"10014055-18" = "[s5] \"……\"\n[s6] \"レイサ、それは……\""
"10014055-19-レイサ" = "よし。とりあえず撃退しましたが、これはまだ序の口でしょう。"
"10014055-20-レイサ" = "よし。とりあえず撃退しましたが、これはまだ序の口でしょう。"
"10014055-21-レイサ" = "きっと、後から数多くのスケバンが絶えず押し寄せて来ると思います！"
"10014055-22-レイサ" = "ですが、スケバンと戦うのは自警団の宿命！！#n私にとっては日常茶飯事です！！"
"10014055-23-レイサ" = "これは自警団である私のところで終わらせます！！#n「平凡な」杏山カズサを守らないといけませんからね！！"
"10014055-24-レイサ" = "ですから先生、まずはこれを……"
"10014055-25" = "[ns7] \"これは……\"\n[ns8] \"……伝えてほしいってこと？\""
"10014055-26-レイサ" = "今後、私から挑戦状を投げることはないという意味です。#n口だけではなく、こちらの方が杏山カズサも気楽でしょう。"
"10014055-27-レイサ" = "今後、私から挑戦状を投げることはないという意味です。#n口だけではなく、こちらの方が杏山カズサも気楽でしょう。"
"10014055-28-レイサ" = "……先生、私分かりました。#n先生がわざわざ私のところに来てくださった理由が。"
"10014055-29-レイサ" = "先生は優しい方ですね。おかげで、だいぶ楽になりました。#n本当にありがとうございます。"
"10014055-30-レイサ" = "だから、これは先生にだけ言う愚痴のようなものです。#n本人に伝えなくても大丈夫です。"
"10014055-31-レイサ" = "……短い間でしたが、久しぶりに彼女に会えて嬉しかったんです。#n実は、もう二度と会えないと思ってたんです。"
"10014055-32-レイサ" = "それで、つい浮かれてしまったみたいです。#n迷惑だったなら……本当にごめんなさい。"
"10014055-33-レイサ" = "それでも……"
"10014055-34-レイサ" = "……やっぱり。"
"10014055-35-レイサ" = "……誰かにとって、忘れたい思い出になってしまったのは、ほんの少し残念です。"
"10014055-36" = "[ns] \"レイサ、ちょっと……\""
"10014055-37-レイサ" = "……おっと！"
"10014055-38-レイサ" = "またお客様が押し寄せて来ましたね！#n増援を呼んだのでしょうか？"
"10014055-39-レイサ" = "これ以上先生にご迷惑をかけられませんので、この辺で失礼します。"
"10014055-40-レイサ" = "いつか機会があれば、また……"
"10014055-41-レイサ" = "杏山カズサのいないところで、またお会いできる日が来ますように！"
"10014055-42-レイサ" = "……では！！"
