[translation]
"1600505-1" = "夏の海 憧憬 感慨"
"1600505-2" = "（海辺に向かうと、ツルギが海辺に座っていた）"
"1600505-3" = "（以前とは違って、今日は静かに海を見つめている……）"
"1600505-4" = "[s1] \"ツルギ？\"\n[s2] \"海、綺麗だね。\""
"1600505-5-ツルギ" = "……。"
"1600505-6-ツルギ" = "……。"
"1600505-7-ツルギ" = "……はっ！？"
"1600505-8-ツルギ" = "せ、先生！？どうしてここに……？"
"1600505-9-ツルギ" = "モモトーク……？し、心配して来てくださったんですか……！？"
"1600505-10-ツルギ" = "す、すみません、本当に特に何があったわけではないのですが……。"
"1600505-11-ツルギ" = "気を使わせてしまいましたね……申し訳ありません……。"
"1600505-12-ツルギ" = "あ、ありがとうございます。そう言っていただけるとありがたいです……。"
"1600505-13-ツルギ" = "ここで、何を……ですか？"
"1600505-14-ツルギ" = "えっと……。"
"1600505-15-ツルギ" = "……その。"
"1600505-16-ツルギ" = "じ、実は自分でも良く分からないと言いますか、何をしていたわけでもなく……。"
"1600505-17-ツルギ" = "ただ……。"
"1600505-18-ツルギ" = "ただこうして座って、ずっと海を見ていました……。"
"1600505-19-ツルギ" = "何と言いますか……。"
"1600505-20-ツルギ" = "もともと小説で読んだ「海」とは違っていて……。"
"1600505-21-ツルギ" = "他の観光客もほとんどいなくて、静かで、私だけがポツンと……。"
"1600505-22-ツルギ" = "それが少し寂しいような、でもこれも不思議と悪くないような……？"
"1600505-23-ツルギ" = "……？"
"1600505-24-ツルギ" = "楽しそう、ですか？"
"1600505-25-ツルギ" = "そ、そうですか？すみません、自分で自分のことがよく分からなくて……。"
"1600505-26-ツルギ" = "きひ……。"
"1600505-27" = "[s3] \"必ずしも誰かの考えと一致してなくても、良いと思うよ。\"\n[s4] \"ツルギの感じてることが全てだと思う。\""
"1600505-28-ツルギ" = "そ、そうなんですか？なるほど……？"
"1600505-29-ツルギ" = "そ、そうなんですか？なるほど……？"
"1600505-30-ツルギ" = "……ここに来てから、トリニティにいる時には知らなかったことがたくさんで。"
"1600505-31-ツルギ" = "それはどれも、体験してみると何だか不思議な感じで……。"
"1600505-32-ツルギ" = "これで合ってるんだろうか、間違ってないかって、ずっと考えてしまって……。"
"1600505-33" = "[s5] \"知らないことって、最初は不安だよね。\"\n[s6] \"でも、今のツルギは結構良い表情をしてると思うよ。\""
"1600505-34-ツルギ" = "あ、は、はい……。"
"1600505-35-ツルギ" = "あ、は、はい……。"
"1600505-36-ツルギ" = "そうなのかも、しれません……。"
"1600505-37-ツルギ" = "何だか、最初は混乱してばかりでしたが……。"
"1600505-38-ツルギ" = "ただ確かに、今思えばどれも……最後には楽しくなっていましたね……？"
"1600505-39-ツルギ" = "……。"
"1600505-40-ツルギ" = "きひ……。"
"1600505-41-ツルギ" = "きひひ……そうですね。やはり、楽しかったのかもしれません。それに、今もこうして……。"
"1600505-42-ツルギ" = "……先生はすごいですね。"
"1600505-43-ツルギ" = "スッキリしました。そうですね、思えばどれも、すごく楽しかったです。"
"1600505-44-ツルギ" = "ここでしかできないことが、たくさんありましたし……。"
"1600505-45" = "[s7] \"うん。それに、私もツルギと一緒で楽しかったよ。\"\n[s8] （結構特殊な遊び方が多かったけどね……）"
"1600505-46-ツルギ" = "……くくっ、きききっ。"
"1600505-47-ツルギ" = "……くくっ、きききっ。"
"1600505-48-ツルギ" = "……せ、先生。"
"1600505-49-ツルギ" = "その……。"
"1600505-50-ツルギ" = "ありがとうございます。"
"1600505-51-ツルギ" = "……こうして、"
"1600505-52-ツルギ" = "一緒に海に来られて、私、すごく嬉しかったです。"
