[translation]
"1600502-1" = "夏の海といえば……"
"1600502-2" = "（海辺に着くと、遠くにツルギが見えた）"
"1600502-3" = "（周りは静かで……というよりも、人けがほとんど無かった。ツルギは何かを探しているかのようにキョロキョロと周囲を見渡している）"
"1600502-4-ツルギ" = "……。"
"1600502-5" = "[s1] \"ツルギ、お待たせ！\"\n[s2] ツルギに向かって手を振る。"
"1600502-6-ツルギ" = "……！！"
"1600502-7-ツルギ" = "……！！"
"1600502-8-ツルギ" = "こ、こんにちは……先生……！"
"1600502-9-ツルギ" = "き、来てくれて、ありがとうございます。連絡を差し上げたのは、その……。"
"1600502-10-ツルギ" = "私一人ではちょっと難しそうなので、先生に助けていただきたく……。"
"1600502-11-ツルギ" = "……。"
"1600502-12" = "[s3] \"何をしたらいい？\"\n[s4] \"何か探してた感じだけど。\""
"1600502-13-ツルギ" = "あ、はい、実は探しものといいますか……"
"1600502-14-ツルギ" = "あ、はい、実は探しものといいますか……"
"1600502-15-ツルギ" = "その、最初から説明をしますと……"
"1600502-16" = "（一時間前）"
"1600502-17-ツルギ" = "……きひ……きひひひひっ！！"
"1600502-18-ツルギ" = "海……！砂浜……！！！！！太陽ぉ！！！！"
"1600502-19-ツルギ" = "青春……！青春の海……！！"
"1600502-20-ツルギ" = "きひひひひひひ！！！！"
"1600502-21-ツルギ" = "きひ……？"
"1600502-22-観光客A" = "ひっ……！？な、何あれ？"
"1600502-23-ツルギ" = "……あん？"
"1600502-24-観光客B" = "う、海に変なのがいる……。"
"1600502-25-観光客C" = "か、怪物……？いや、お化け！？"
"1600502-26-ツルギ" = "……？"
"1600502-27-ツルギ" = "お化け……？"
"1600502-28-観光客A" = "静かに！こっちに来たらマズい、早く逃げよう！"
"1600502-29-観光客C" = "そ、そうね。ほら、近くのお店もどんどん閉まってるし……。"
"1600502-30-観光客B" = "視界に入れたままゆっくり逃げよう。もし目が合っちゃったら逆に逸らさないで、そのまま後ろ向きに下がって……！"
"1600502-31-ツルギ" = "……？？？"
"1600502-32" = "（ざわざわ……）"
"1600502-33-ツルギ" = "……。"
"1600502-34-ツルギ" = "あぁ……？"
"1600502-35-ツルギ" = "と、ということで、もうここには私しか残っていなくて……。"
"1600502-36-ツルギ" = "このままだと本で読んだような、夏っぽい、キラキラしてにぎやかな光景が見られないので……それは困るなと思い……。"
"1600502-37-ツルギ" = "その「お化け」を私が探し出して、消し去らないとと思ったのですが……。"
"1600502-38" = "[s] \"……。\""
"1600502-39" = "[s] \"……！\""
"1600502-40-ツルギ" = "だいぶ探したのですが、見つからず……気配を絶っているのか……。"
"1600502-41-ツルギ" = "な、何か良い方法が無いかと思い、先生にご連絡を……。"
"1600502-42" = "[s] \"それは、多分……\""
"1600502-43-ツルギ" = "……先生？"
"1600502-44" = "[s] \"……。\""
"1600502-45" = "[s5] \"難しい問題だね……。\"\n[s6] （言えない、私には言えない……！）"
"1600502-46-ツルギ" = "せ、先生？変な方向を向いてどうかしましたか？あっちの方に、お化けが……？"
"1600502-47-ツルギ" = "せ、先生？変な方向を向いてどうかしましたか？あっちの方に、お化けが……？"
"1600502-48-ツルギ" = "な、何でもない、ですか……？そ、そうですか、すみません……。"
"1600502-49-ツルギ" = "一瞬、何かに気づいたような表情をされていたので……。"
"1600502-50-ツルギ" = "ですが、どうしましょう……このままだと……。"
"1600502-51-ツルギ" = "せっかく海に来たのに、何と言いますか……物語で読んだような海とは違った状態になってしまっていて……。"
"1600502-52-ツルギ" = "ど、どうしたら……。"
"1600502-53-ツルギ" = "諦めて、別の海岸に移動した方が良いのでしょうか？"
"1600502-54" = "[s7] （被害が広がっちゃう……）\n[s8] 考え込む。"
"1600502-55-ツルギ" = "わ、私は、どうすれば……"
"1600502-56-ツルギ" = "わ、私は、どうすれば……"
"1600502-57-ツルギ" = "うぅ……。"
"1600502-58-ツルギ" = "……え、えっと。"
"1600502-59-ツルギ" = "やっぱり、無理なのでしょうか……私には、そういう雰囲気は一生味わえないまま……。"
"1600502-60-ツルギ" = "……？"
"1600502-61-ツルギ" = "静かな海辺も悪くない、ですか……？"
"1600502-62-ツルギ" = "た、確かにこのままでも、海は綺麗、ですが……。"
"1600502-63" = "[s9] \"二人っきりって、良い響きだよね。\"\n[s10] \"二人っきりの海、ロマンティックじゃない？\""
"1600502-64-ツルギ" = "そ、そうですね……。"
"1600502-65-ツルギ" = "そ、そうですね……。"
"1600502-66-ツルギ" = "ふ、二人っきりの海……。"
"1600502-67-ツルギ" = "……二人っきりの……。"
"1600502-68-ツルギ" = "……？"
"1600502-69-ツルギ" = "……二人、っきり？"
"1600502-70-ツルギ" = "……ッ！！！？！？"
"1600502-71" = "[s] \"……ツルギ？\""
"1600502-72-ツルギ" = "……き、"
"1600502-73" = "[s] \"……き？\""
"1600502-74-ツルギ" = "……きえぇぇぇぇっ！！！"
"1600502-75" = "（……？）"
"1600502-76" = "（……一人ぼっちの海になってしまった）"
