[translation]
"1009402-1" = "メイドな気分！"
"1009402-2" = "（勢いの良いモモイの言葉を受け……）"
"1009402-3" = "（漠然とした不安を抱えつつ、急いでシャーレに向かった）"
"1009402-4" = "[ns] \"モモイ？いるかな……？\""
"1009402-5" = "[wa:420]― [log=모모이 메이드]うへへ……[wa:2420]お菓子、[wa:1490]美味しい……。[/log]"
"1009402-6" = "[wa:3020]― [log=모모이 메이드]日差しが温かくて……[wa:3080]ソファもふわふわ……。[/log]"
"1009402-7" = "[ns] \"モモイさん？メイドは？お掃除は？\""
"1009402-8" = "[wa:630]― [log=모모이 메이드]うぅん……[wa:1590]おそうじ……？[/log]"
"1009402-9" = "[wa:2790]― [log=모모이 메이드]するから……[wa:2330]これだけ食べて……[wa:2370]ちょっと[wa:670]休んでから……。[/log]"
"1009402-10" = "[wa:1420]― [log=모모이 메이드]あれ？[wa:1430]先生？[/log]"
"1009402-11" = "[wa:3340]― [log=모모이 메이드]そっか。[wa:1580]これ、[wa:720]まだ夢なんだね。[/log]"
"1009402-12" = "[wa:670]― [log=모모이 메이드]夢の中でも先生に会えるなんて……[wa:4220]いい夢だねぇ……。[/log]"
"1009402-13" = "[wa:3160]― [log=모모이 메이드]今日はなんだか、[wa:1960]楽しいことがあるかも……[wa:2560]うへへ……。[/log]"
"1009402-14" = "[wa:670]― [log=모모이 메이드]むにゃむにゃ……[wa:3070]あ、[wa:1180]ボーナスライフだ……。[/log]"
"1009402-15" = "[ns] \"まったく……。\""
"1009402-16" = "（モモイの肩を揺すってみても起きず……）"
"1009402-17" = "（いたずらごころも相まって、軽くデコピンをしてみた）"
"1009402-18-モモイ" = "んうわっ！？"
"1009402-19-モモイ" = "何すんのさぁ！"
"1009402-20-モモイ" = "ってあれ、先生……？"
"1009402-21" = "[ns] \"モモイ、掃除はしてくれたの？\""
"1009402-22-モモイ" = "こ、これは、その……だ、だから！"
"1009402-23-モモイ" = "し、仕方なかったの！#n誰だって同じ状況になったら、きっと……っ！"
"1009402-24-モモイ" = "とにかく聞いて！このソファの周りを整理しようと思ったの！"
"1009402-25-モモイ" = "でも、動いてたらお腹が空いてきて……。#n掃除をするにも、まずは腹ごしらえをしないとでしょ？"
"1009402-26-モモイ" = "そしたらそこに、ちょうどお菓子があるじゃん！"
"1009402-27-モモイ" = "ちょっと食べて掃除しようと思ったんだけど……#n食べ終わったら今度は、眠くなってきて……。"
"1009402-28-モモイ" = "そんな時、目の前に柔らかそうなソファがあったらさっ！"
"1009402-29-モモイ" = "誰だって、少し横になりたくなっちゃうよね？"
"1009402-30" = "[ns] \"ふむふむ、それで？\""
"1009402-31-モモイ" = "だ、だから、えっと……。"
"1009402-32-モモイ" = "ちょっと横になるだけのつもりだったんだよ？#nでも、このソファがあまりにふかふかだったからっ！"
"1009402-33-モモイ" = "だから悪いのは私じゃなくて、このソファ！#nそれに、先生もだよ！"
"1009402-34" = "[s] \"え？私も……？\""
"1009402-35-モモイ" = "生徒が来るところに、こんなふかふかのソファを置くなんて！"
"1009402-36-モモイ" = "寝心地の良いソファは誰にとっても、あったかいベッドと同じぐらい#n危険な罠なんだよ？"
"1009402-37-モモイ" = "朝、ベッドからなかなか起き上がれないのも、このふかふかに潜む#n恐ろしい魔物のせいなんだから！"
"1009402-38-モモイ" = "だ、だから……これは事故だったの！#nなんだっけ、不可能力……？ってやつ！"
"1009402-39" = "[s] \"「不可抗力」かな……？\""
"1009402-40-モモイ" = "と、とにかく……っ！"
"1009402-41" = "（モモイの熱心な説明は、その後も続いた……）"
"1009402-42" = "[ns] \"……で、今に至ると。\""
"1009402-43-モモイ" = "うん……。"
"1009402-44-モモイ" = "ごめんね、先生……。"
"1009402-45" = "[s1] \"それじゃあ本来の目的に戻って。\"\n[s2] \"今から、一緒にお掃除しようか。\""
"1009402-46-モモイ" = "ええっ！？掃除！？"
"1009402-47-モモイ" = "そもそも掃除のためにシャーレに来たっていうのは……#nそ、それはまあ、そうだけどっ！"
"1009402-48-モモイ" = "で、でもさ、ほら……先生が普段からちゃんと綺麗にしてたら……。#n私が掃除をするまでもなかったわけじゃん？"
"1009402-49-モモイ" = "それはさすがに本末転倒だって？だ、だって、面倒なんだもん！"
"1009402-50" = "[s3] \"掃除は始めるまでが一番大変だけど。\"\n[s4] \"手を動かせば、すぐ終わるはず！\""
"1009402-51-モモイ" = "な、なるほど？さすが先生！それはそうかも！"
"1009402-52-モモイ" = "だから、逃げずに箒を持て、って……？うぅ――"
"1009402-53-モモイ" = "わ、わかったよ！やればいいんでしょ！#nうぅぅ、メイドの気分ってこういう感じだったの！？"
"1009402-54" = "（覚悟を決めたモモイと「シャーレのお掃除大作戦」を決行した……）"
"1009402-55-モモイ" = "ふぅ～終わったあ！"
"1009402-56-モモイ" = "いやぁ～さすが私！やればできる子！"
"1009402-57-モモイ" = "あ、先生もお疲れさま！#nふっふっふ、でもっ！本番はここからだよ！"
"1009402-58" = "[s] \"また不安になってきた！\""
"1009402-59-モモイ" = "ふふふ……鋭くなったね、先生。"
"1009402-60-モモイ" = "考えてみてよ！#nメイドってさ、普通は雇われて仕事をするもんでしょ？"
"1009402-61-モモイ" = "ご主人様に雇われて家事をして、報酬をもらう仕事じゃん？"
"1009402-62" = "[s] \"そう、だよね……？\""
"1009402-63-モモイ" = "だから先生はご主人様として、メイドに報酬を支払わないと！"
"1009402-64" = "[s] \"私も一緒に掃除したのに！？\""
"1009402-65-モモイ" = "ダメダメ！そもそも掃除なんて自分でやるのが普通だから！"
"1009402-66" = "[s] \"それは、その通りだけど……！\""
"1009402-67-モモイ" = "とにかく！先生はメイドに報酬を支払う義務があるっ！"
"1009402-68-モモイ" = "別にね、お金が欲しいなんて野暮なことは言わないよ？"
"1009402-69-モモイ" = "私が先生にして欲しいこと……それは……！"
"1009402-70-モモイ" = "一日中、一緒に遊んでくれること！"
"1009402-71-モモイ" = "何で遊べばいいかわからないって？#nふっふっふっ。先生はそう言うと思って……！"
"1009402-72-モモイ" = "じゃ～ん！ゲーム機をたくさん持ってきたの！"
"1009402-73" = "（綺麗になったシャーレで、モモイと楽しくゲームした……）"
"1009402-74" = "（プレイ中、興奮したモモイは目隠ししたりくすぐったりと#n物理的に妨害してきた……！）"
"1009402-75" = "（そして……）"
"1009402-76-通りすがりの人２" = "お聞きになりました？シャーレの先生のお話……。"
"1009402-77-通りすがりの人２" = "ええ……最近噂になってますね。#nなんでも、生徒にメイド服を着せていろんなプレイを試してるって……。"
"1009402-78" = "（シャーレの評判は、ますます変な形で広まっていくのだった……）"
