[translation]
"1013005-1" = "社会経験"
"1013005-2-スバル" = "……。"
"1013005-3" = "[s] \"……。\""
"1013005-4-スバル" = "こ、こんにちは、先生。"
"1013005-5-スバル" = "そ、その……これは……。"
"1013005-6-スバル" = "あ、アルバイトです……。"
"1013005-7-スバル" = "ち、違いますからっ！先生が思ってるようなものじゃないです……！#nみんなで話し合った結果――"
"1013005-8-スバル" = "この機会に「接客」を体験して、色々な対応を覚え――"
"1013005-9-スバル" = "己の限界を体で覚えつつ、経済活動をしてみよう、と……。"
"1013005-10" = "[ns] \"たしかに、目的と合致してる気も。\""
"1013005-11-スバル" = "そう、ですよね……？"
"1013005-12-スバル" = "でも、急に外に出されてしまい……#n私には接客する資格もなかったようです。"
"1013005-13-スバル" = "この看板を持って立っているように、と……#n絵になるから？よくわかりませんが。"
"1013005-14" = "[ns1] \"……たしかにそうかも。\"\n[ns2] \"スバルはもっと自分に自信を持っていいと思う。\""
"1013005-15-スバル" = "……店長と同じことを言いますね。"
"1013005-16-スバル" = "どういう意味なのかはよく分かりませんが……。"
"1013005-17-スバル" = "……なんだかんだ言って頑張ってるスバルがかっこいいよ？"
"1013005-18-スバル" = "……。"
"1013005-19-スバル" = "で、では！そんな私たちのためにも！#n売り上げに貢献していただけると……！"
"1013005-20" = "[s3] \"ふむ。なかなか筋がいいですね、スバルさん。\"\n[s4] \"では、よろしくお願いします。\""
"1013005-21-スバル" = "ありがとうございます！ご案内します！"
"1013005-22" = "[ns] \"おお……思ったよりも本格的だ。\""
"1013005-23-スバル" = "どうですか？先生。みんなのこんな姿は、新鮮ですよね？"
"1013005-24-スバル" = "最初は悩んでいたのですが、制服を見て前向きになってくれて……。"
"1013005-25-スバル" = "「可愛い」「着てみたい」、って。"
"1013005-26-スバル" = "……。"
"1013005-27-スバル" = "私、先輩なのに、後輩の気持ちにも気づけてなくて……情けなく思いました。"
"1013005-28" = "[s5] \"そんなことないよ、知らなかっただけだから。\"\n[s6] \"気がつけたなら、大丈夫。\""
"1013005-29-スバル" = "……そうですよね。"
"1013005-30-スバル" = "[USERNAME]先生がおかえりになられました！"
"1013005-31-スバル" = "おかえりなさいませ、ご主人様！"
"1013005-32" = "[ns] \"スバルも一緒に行こう。\""
"1013005-33-スバル" = "わ、私もですか！？でも、看板を持ってないと……。"
"1013005-34-スバル" = "一人でも多くのお客様をご案内して、売り上げに貢献しないと……。"
"1013005-35" = "（その言葉を待っていた私は、会心の笑みを浮かべ……）"
"1013005-36" = "（店長に声をかけた）"
"1013005-37-店長" = "どうかされましたか？"
"1013005-38-店長" = "なるほど。こちらの方が先生の教え子で……。"
"1013005-39-店長" = "社会勉強する様子を見に来た、と。#nそれでお話がしたいと。"
"1013005-40-店長" = "その代わり、今いるお客様全員に、飲み物と……ケーキを？"
"1013005-41-店長" = "支払いは全額、先生が負担……？"
"1013005-42-店長" = "そういうことでしたら大歓迎ですとも！#nスバルさん、先生とゆっくりしてきてください！"
"1013005-43-スバル" = "……いいんですか？"
"1013005-44" = "[s] \"ふっ……これが大人ってものさ。\""
"1013005-45-スバル" = "……勉強になります。すごく。"
"1013005-46" = "（そうしてスバルと他愛のない話を交わした）"
"1013005-47" = "（日常や学校でのこと、そして、後輩と向き合う中でのこと……）"
"1013005-48" = "（ひとつひとつは本当に他愛ない。でも、だからこそ大事な話を）"
"1013005-49-スバル" = "先生。"
"1013005-50" = "[ns] \"うん？\""
"1013005-51-スバル" = "アリウスのみんな、頑張ってますよね？"
"1013005-52" = "[ns7] \"そうだね。\"\n[ns8] \"もちろんスバルも。\""
"1013005-53-スバル" = "……。"
"1013005-54-スバル" = "そういうことを言っても、何も出ませんから……。"
"1013005-55-スバル" = "えっ？素直に思っただけ……？"
"1013005-56-スバル" = "…………。"
"1013005-57-スバル" = "私、先生のわる～いウワサ、聞いてるんですよ？"
"1013005-58-スバル" = "ある日先生の身に何かあっても……全部自業自得！という話です。"
"1013005-59-スバル" = "なんでその話を今するのか、って？"
"1013005-60-スバル" = "知りませんっ。先生は頭のいいお方ですから、ご自分で考えてみてください。"
"1013005-61- けんか腰の客" = "なんだこの店！#nサービスでケーキが出るって聞いたのにめちゃくちゃじゃねえか！"
"1013005-62-アルバイトのアリウス生徒" = "ど、どうかされましたかお客様？"
"1013005-63- けんか腰の客" = "姿勢がなってねえんだよ、姿勢が！声もかけてこないしよぉ！#nもっと周りを見たらどうなんだ！"
"1013005-64- けんか腰の客" = "まあ、もう来ねえけどな！ "
"1013005-65-アルバイトのアリウス生徒" = "も、申し訳ございません！どうかまたお越しください……。"
"1013005-66- けんか腰の客" = "はんっ！もうどうでもいいよ！#n大体なんだよ、この服のひらひらは。飾りか？"
"1013005-67-アルバイトのアリウス生徒" = "きゃあっ！？"
"1013005-68-店長" = "お、お客様！？キャストに触れるのは……！"
"1013005-69-スバル" = "……！"
"1013005-70- けんか腰の客" = "ぐあぁっ！なっ、なんだお前！"
"1013005-71-スバル" = "申し訳ありません。#nご主人様がバランスを崩されたようでしたので――"
"1013005-72-スバル" = "お支えしようと思った次第です……ご体調でも優れませんか？"
"1013005-73-スバル" = "（先輩の[ruby=CQB]近接戦闘[/ruby]をこんな間近で！？ラッキー！！）"
"1013005-74-スバル" = "さ、支えるってこれのどこがっ……！いてててて！#nおっ、おい腕が折れちまうだろ！はっ、離せっ……！ぐあぁ……！"
"1013005-75-スバル" = "ふふっ、少々お待ちを。#nご自身で立てますか？"
"1013005-76-スバル" = "……この腕、今まで通りに使いたいだろ？"
"1013005-77-スバル" = "……ヒィッ！？"
"1013005-78-スバル" = "私が何を言いたいのか……今のお前がどんな立場か。#n分かるな？"
"1013005-79-スバル" = "わわ、分かった、分かったからっ……！だ、だからっもう……！"
"1013005-80-スバル" = "失せろ。"
"1013005-81- けんか腰の客" = "こ、こんな店っ、二度と来るかっ！！"
"1013005-82-店長" = "……。"
"1013005-83-店長" = "スバルさん、ありがとう！いや……ありがとうございました！#nおかげでみんな無事だったよ！"
"1013005-84-スバル" = "いえ、やるべきことをやっただけですから。"
"1013005-85-店長" = "スバルさん、でしたよね？お写真いいですか……？"
"1013005-86-店長" = "別料金が必要でしたらいくらでも……！"
"1013005-87-店長" = "いっ、いえ特にそういういったものは……というか店長！？先生！？"
"1013005-88-スバル" = "なんで二人とも笑顔でサムズアップしてるんですか！！？"
