[translation]
"10002120-1" = "第12話;花火"
"10002120-2" = "（紆余曲折の末、何とかリストに書かれた5つのミッションを終わらせて、今はゆっくりと夕日の空を見つめていた）"
"10002120-3" = "（最後に残った「花火」は日が暮れないとできないことだったので、少し時間の余裕がある）"
"10002120-4-マシロ" = "もうこんな時間……。"
"10002120-5-マシロ" = "それに、ヒフミさんとアズサさん、遅いですね……。"
"10002120-6" = "[s] \"花火を買いに、遠くまで行っちゃったのかな？\""
"10002120-7-マシロ" = "もしかしたら、そうかもしれません。"
"10002120-8-ツルギ" = "……きひっ！きひひっ！げへへへ！！"
"10002120-9-マシロ" = "……先輩も、楽しみですか？"
"10002120-10-マシロ" = "買いに行ってもらったのは申し訳ないのですが……こうして少しゆっくり休めましたので、お二人には感謝しないとですね。"
"10002120-11-マシロ" = "全部終わったら、帰ってハスミ先輩に報告して、写真をお見せして……"
"10002120-12-マシロ" = "問題無く終わりそうですね、先生のおかげです。"
"10002120-13" = "[s1] \"マシロは楽しかった？\"\n[s2] \"他に何か、やりたいこととかない？\""
"10002120-14-マシロ" = "え、えっと、本来私はおまけと言いますか、ハスミ先輩に言われて付いてきただけで……。"
"10002120-15-マシロ" = "え、えっと、本来私はおまけと言いますか、ハスミ先輩に言われて付いてきただけで……。"
"10002120-16-マシロ" = "ですが雰囲気にのまれて、私もだいぶ楽しんでしまいました。"
"10002120-17-マシロ" = "いついかなる時も正義の心を、と思っていたのですが……だいぶ夢中になってしまいました。"
"10002120-18-マシロ" = "そこは、反省しないとですね……。ですが、はい。楽しかったです、ありがとうございます。"
"10002120-19-マシロ" = "ヒフミさんたち、少し遅いですね。ちょっとお迎えに行ってきます。"
"10002120-20" = "[ns3] \"ツルギはどうだった？\"\n[ns4] \"楽しかった？\""
"10002120-21-ツルギ" = "……！！"
"10002120-22-ツルギ" = "……！！"
"10002120-23-ツルギ" = "わ、私ですか！？え、えっと、私は……！"
"10002120-24-ツルギ" = "……。"
"10002120-25-ツルギ" = "じ、実は、よく分からないんです……これで正しいのか……。"
"10002120-26-ツルギ" = "お、思っていたのとは違う気もしますし……。"
"10002120-27-ツルギ" = "正しいような気も、しますし……。"
"10002120-28" = "[s5] \"ツルギが楽しかったなら、それが正しいと思うよ。\"\n[s6] \"正しいかどうかより、ツルギの感じたことが全てだよ。\""
"10002120-29-ツルギ" = "な、なるほど……まだはっきりとは良く分かりませんが……。"
"10002120-30-ツルギ" = "な、なるほど……まだはっきりとは良く分かりませんが……。"
"10002120-31-ツルギ" = "本で見た海とは、少し違いましたが……こうして、一緒にみんな遊んでくれて……。"
"10002120-32-ツルギ" = "す、すごく、その……。"
"10002120-33-ツルギ" = "それに、な、何より、えっと……！"
"10002120-34-ツルギ" = "せ、せん――"
"10002120-35-ヒフミ" = "ただいま戻りましたー！"
"10002120-36-ツルギ" = "……っ！？"
"10002120-37-ヒフミ" = "すみません、お待たせしました。ようやくお店が見つかりまして、とりあえず買える分だけ買ってきました……！"
"10002120-38-アズサ" = "範囲や火力は微々たるものだけど、注文通りの爆発物だ。"
"10002120-39-アズサ" = "私としては、火力が弱い割に値段が高くてどうかとも思うのだけど……。"
"10002120-40-ヒフミ" = "アズサちゃん、花火に火力は要らないんですよ……。"
"10002120-41-アズサ" = "念のため、花火以外にも幾つか使えそうな爆弾を手に入れてきた。万が一の時はこれを使おう。"
"10002120-42-ヒフミ" = "その「万が一」は、できれば起きてほしくないのですが……。"
"10002120-43-ヒフミ" = "……えっと、"
"10002120-44-ヒフミ" = "ツルギさんどうかしましたか？あ、もしかしてお話の途中に割り込んでしまいましたか……！？"
"10002120-45-ツルギ" = "……え、や、その……。"
"10002120-46-ツルギ" = "……きっ、ききっ！くきききっ……！"
"10002120-47-ツルギ" = "ううっ、すみません、なんだか分かりませんがごめんなさいいぃぃぃ……。"
"10002120-48" = "[s] \"……ふふっ。\""
"10002120-49" = "（その後、なんだかんだで時間が過ぎ、日が完全に暮れた頃）"
"10002120-50" = "（水平線の向こうに太陽が沈むと、すぐに周囲は暗くなった）"
"10002120-51" = "（次々とお店も閉店し、海辺には波の音だけが響いている）"
"10002120-52-ヒフミ" = "静かですね……もう誰も見当たりませんし、私たち以外みなさん帰られてしまったんでしょうか？"
"10002120-53-アズサ" = "いや、あっちの方に、まだスケバンたちが残ってる。今何をしてるかは知らないけど。"
"10002120-54-マシロ" = "そうでしたか。距離はそれなりにありますが……念のため、先制攻撃しておきますか？"
"10002120-55-ヒフミ" = "な、何が「念のため」なのか良く分かりませんが、喧嘩は売らなくても良いのではないかと……！まだ何も起こっていませんし……！"
"10002120-56-マシロ" = "確かにそうですが、"
"10002120-57-マシロ" = "これまで何度もあちらから仕掛けてきました。また次もやってくると思いませんか？"
"10002120-58" = "[s7] \"そうかもしれないけど、そうじゃないかもしれない。\"\n[s8] \"もしかしたらあっちでも、花火をしてるんじゃないかな。\""
"10002120-59-マシロ" = "花火……ですか？"
"10002120-60-マシロ" = "花火……ですか？"
"10002120-61-アズサ" = "一概に否定できる話でもない。さっき花火を買いに、爆発物を取り扱ってるお店に入った時、そこにスケバン達もいた。"
"10002120-62-アズサ" = "あの状況からして、他の変数を加味しても花火を買っていた可能性は高い。"
"10002120-63-アズサ" = "もちろん、それでも万が一ということはある。できる限りのリスクを洗い出して備えるという意味では、私は賛成だけど……"
"10002120-64-ヒフミ" = "そ、そこまでやらなくても良いと思います……。"
"10002120-65-アズサ" = "……ヒフミならそう言うと思った。とりあえず、警戒だけはしておく。"
"10002120-66-マシロ" = "分かりました。でしたら私も、これ以上は何も言わないでおきますね。"
"10002120-67" = "花火……。"
"10002120-68" = "ですね。"
"10002120-69" = "スケバンたちがいた方角……本当に花火だったんだ。"
"10002120-70-ツルギ" = "……すごい。キラキラ、してる……。"
"10002120-71-ツルギ" = "……！？！？"
"10002120-72" = "（……パァン！！！）"
"10002120-73-マシロ" = "まだです、これでは足りません！アズサさん、あちらの花火に負けないくらいもっと大きいのを打ち上げましょう！"
"10002120-74-アズサ" = "もちろん、負けるわけにはいかない。"
"10002120-75-ヒフミ" = "えぇぇぇっ！？な、何を張り合ってるんですか！？"
"10002120-76-ヒフミ" = "どうしてまた勝負してるんですか！？"
"10002120-77-ヒフミ" = "な、何だか向こうも対抗してきているような……！？"
"10002120-78-ヒフミ" = "はうぅぅ！！せ、せんせえ～～！！"
"10002120-79" = "[s] \"……綺麗だね。\""
"10002120-80-アズサ" = "意地の張り合いか、"
"10002120-81-アズサ" = "悪くない。"
"10002120-82-ヒフミ" = "こ、これじゃ、せっかく買ってきた花火があっという間に……！！"
"10002120-83" = "（ドカアアァァァァン！！）"
"10002120-84-ヒフミ" = "……！？"
"10002120-85-アズサ" = "……！！"
"10002120-86-マシロ" = "……あれは、"
"10002120-87-マシロ" = "恐らく、ナパーム弾ですね。"
"10002120-88-アズサ" = "確かに、ナパーム弾は普通の花火より遥かに強力。それを花火として使うとは、考えたな……？"
"10002120-89-ヒフミ" = "もうあれは花火じゃないと思いますが……。"
"10002120-90-アズサ" = "狙撃手、こちらにナパーム弾は？"
"10002120-91-マシロ" = "ありません。"
"10002120-92-マシロ" = "あっ、また何か……！"
"10002120-93-マシロ" = "……？"
"10002120-94-マシロ" = "軌道が低い、ですね……？"
"10002120-95-マシロ" = "……あ。"
"10002120-96-ヒフミ" = "……？"
"10002120-97-アズサ" = "……はぁ。"
"10002120-98-アズサ" = "そういうことか。"
"10002120-99" = "（ドカアアァァァァン！！）"
"10002120-100-アズサ" = "……良いだろう、ならば戦争だ。"
