[translation]
"10002110-1" = "第11話;ビーチバレー"
"10002110-2" = "（リストに残っているのはあと二つ）"
"10002110-3-ヒフミ" = "では、ビーチバレーを始めましょう！"
"10002110-4-ヒフミ" = "ボールもちゃんとここにあります！"
"10002110-5-ヒフミ" = "正確には「先生が買ってくれたボール」が、ですね。"
"10002110-6-ヒフミ" = "うう……。"
"10002110-7-ヒフミ" = "忘れ物ばっかりでごめんなさい……先生も、ありがとうございます。"
"10002110-8-ヒフミ" = "少し人も減ってきて、スケバンの方々も見当たりませんし……今度こそ何も起きなさそうですね。"
"10002110-9" = "[s1] \"ヒフミ、大丈夫……？\"\n[s2] \"表情が疲れてる気が……。\""
"10002110-10-ヒフミ" = "だ、大丈夫です……！"
"10002110-11-ヒフミ" = "だ、大丈夫です……！"
"10002110-12-ヒフミ" = "ただその、これで良いのかなって思ってしまって……。"
"10002110-13-ヒフミ" = "本当なら、こんなはずではなかったのですが……。"
"10002110-14-ヒフミ" = "最初はただ、アズサちゃんに海を見せてあげたくて……できればみんなで、楽しい時間を過ごしたいなって……。"
"10002110-15-アズサ" = "私は楽しいけど？"
"10002110-16-ヒフミ" = "いえ、えっと、それは嬉しいのですが。何と言いますか、夏休みというのは……。"
"10002110-17-ヒフミ" = "恐る恐る何かをするようなものでもなく、何度もスケバンの方々から襲撃されるものでもないはずで……。"
"10002110-18-ヒフミ" = "それにああやって、何かをする度に「見つけたぞ！」って邪魔が入ってくると――"
"10002110-19-チンピラB" = "見つけたぞ！！ここにいたのか！"
"10002110-20-チンピラA" = "手間をかけさせやがって、こんなところに隠れてたのか！"
"10002110-21" = "[ns] \"……。\""
"10002110-22-マシロ" = "応戦します！"
"10002110-23-マシロ" = "うぅ……はい……。"
