[translation]
"10002160-1" = "後日談その3;騙し騙され埋められて"
"10002160-2" = "Ｑ．なんであの状況で逃げなかったの？"
"10002160-3-チンピラB" = "はぁ？何これ、何のつもり？"
"10002160-4-チンピラB" = "え……インタビュー？正気かあんた……？こちとら散々やられて頭に来てんだけど、死にてぇのか！？"
"10002160-5-チンピラB" = "なに、今の心情……？おまっ、だからそれ本気で聞いてんの！？"
"10002160-6-チンピラB" = "さっきまでの戦闘を見ておいて、っていうかあんたが指揮しておいて、そんなこと聞く！？あれか、嫌がらせか！？"
"10002160-7-チンピラB" = "何なんだよったく……いや仕掛けたのはあたしらだけどさ……。"
"10002160-8-チンピラB" = "いやでも、普通行けると思うじゃんあの状況……何あれ、あたしらをおびき寄せるための罠だったってこと？"
"10002160-9-チンピラB" = "あの正義実現委員会の委員長だぞ！？あたしらが一泡吹かせるチャンスなんて滅多にないじゃん！"
"10002160-10-チンピラB" = "そりゃ溺れてるって知ったら、攻撃くらいするでしょ！？"
"10002160-11-チンピラB" = "っていうかあんだけ必死そうだったのに、あの溺れ方が演技だなんて思わないじゃん！！"
"10002160-12-チンピラB" = "はぁ……。"
"10002160-13-チンピラB" = "もういいよ……で、何を聞ければ納得してくれるわけ？……なんであの状況で逃げずに攻撃してきたのか、って？"
"10002160-14-チンピラB" = "はんっ……。"
"10002160-15-チンピラB" = "大した理由じゃねえよ。今言った通り、溺れてんなら勝てると思ったし、罠だと分かっても退ける状況じゃなくなっちまったし……。"
"10002160-16-チンピラB" = "いや、不意を突けば一回くらい勝てるんじゃね？って思って……。"
"10002160-17-チンピラB" = "あたしら、いっつもやられてばっかりだし、あそこまでコテンパンにされていつまでも黙ってられないっていうか……。"
"10002160-18-チンピラB" = "毎回どこ行っても倒されてばっかりで、そんなことが毎回お決まりみたいに続いて……。"
"10002160-19-チンピラB" = "だから、一回くらい勝ってみたくて、そうすればまた明日から明るい気持ちで頑張れっかなって……。"
"10002160-20-チンピラB" = "でも、結局こんなんで……情け、なくて……。"
"10002160-21-チンピラB" = "……。"
"10002160-22-チンピラB" = "うっ……うぅっ……！"
"10002160-23-チンピラB" = "うああぁぁぁぁぁ～～～ん！！"
"10002160-24" = "（インタビュー相手が情緒不安定になってしまったため、インタビューは中断することにした（あと慰めてあげた）。）"
