[translation]
"10002070-1" = "第7話;海の家（１）"
"10002070-2-ヒフミ" = "……。"
"10002070-3-ヒフミ" = "と、とにかく二番目までは終えられましたね……。"
"10002070-4-アズサ" = "ペースは悪くない。次のミッションを始めよう。"
"10002070-5-アズサ" = "できるだけ早く終わらせて、最初の目的通り普通に海を楽しむとしよう。"
"10002070-6-ヒフミ" = "そ、そうですね……。"
"10002070-7" = "[s1] （うーん……）\n[s2] （もうすでに、それなりに楽しんでる気がするけど……）"
"10002070-8-アズサ" = "それでヒフミ、次のミッションは？"
"10002070-9-アズサ" = "それでヒフミ、次のミッションは？"
"10002070-10-ヒフミ" = "えっと、「海の家」にしましょうか。ただ普通に行って、食事をしているところを撮れば良さそうです。"
"10002070-11-ヒフミ" = "海といえば色んなものが美味しいですし、定番のお楽しみの一つですよね。"
"10002070-12-ヒフミ" = "実は事前に調べておいたのですが、この[ruby=むいがはま]無為ヶ浜[/ruby]には有名なお店があるそうで……"
"10002070-13-ヒフミ" = "あ、ここですね。"
"10002070-14" = "海の家"
"10002070-15-ヒフミ" = "えっと、失礼します……！"
"10002070-16-イズミ" = "ん？……あれ、先生！？"
"10002070-17" = "[s3] \"どうしてイズミがここに……？\"\n[s4] \"イズミもご飯食べに来たの？\""
"10002070-18-イズミ" = "ちょっと事情があって、今はここで働いてるの！"
"10002070-19-イズミ" = "ちょっと事情があって、今はここで働いてるの！"
"10002070-20-イズミ" = "店主さんがちょっと寝込んじゃって。それで今日一日、代わりにね！"
"10002070-21-イズミ" = "まさかこんなところで先生に会うなんて、ビックリした―！"
"10002070-22-ヒフミ" = "えっと、先生のお知り合いの方ですか？"
"10002070-23-マシロ" = "どこかで見たような……ゲヘナ？いや、まさか……"
"10002070-24-ツルギ" = "……？"
"10002070-25" = "[s] 全力で誤魔化す。"
"10002070-26-マシロ" = "なるほど、先生のお知り合いでしたか。一瞬変に気を張ってしまって、失礼しました。"
"10002070-27-イズミ" = "よく分かんないけど気にしないで！さあ、せっかく来てくれたんだし、私の新作を味わっていってよ！"
"10002070-28" = "[s5] \"イズミの新作！？\"\n[s6] \"まさか、店主さんが寝込んでるのって……！\""
"10002070-29-イズミ" = "そっちのみんなも座って座って！"
"10002070-30-イズミ" = "そっちのみんなも座って座って！"
"10002070-31-イズミ" = "ここのメニューは何でも美味しいから、期待してて良いよ！ちょっとだけなら割引もしてあげる！"
"10002070-32-アズサ" = "なるほど、"
"10002070-33-アズサ" = "じゃあありがたく。"
"10002070-34-マシロ" = "それではお言葉に甘えて……。"
"10002070-35-マシロ" = "先輩も、こちらへどうぞ。"
"10002070-36" = "[ns] \"えっと、みんな、その……。\""
"10002070-37-ヒフミ" = "ありがとうございます！えっと、どれにしましょう……！"
"10002070-38" = "[s] \"ちょっと話を聞いてほしいんだけど……。\""
"10002070-39-ヒフミ" = "先生、どうかしましたか？"
"10002070-40-マシロ" = "あ、メニューの名前がすごく斬新ですね。"
"10002070-41-マシロ" = "「牡蠣氷」「チョコミント焼きそば」「練乳冷やし中華」「なまこジュースのチョコレートがけ」……"
"10002070-42-マシロ" = "ユニークですね、良いセンスです。"
"10002070-43" = "[s] \"ユニークっていうか、多分それ文字通りっていうか……。\""
"10002070-44-ヒフミ" = "……？どういうことですか？"
"10002070-45-イズミ" = "みんなそろそろ選んだ？"
"10002070-46-イズミ" = "ご注文をどうぞー！"
"10002070-47" = "では、私はこの「牡蠣氷」というのを。"
"10002070-48" = "先輩は何にしますか？"
"10002070-49-ツルギ" = "……「チョコミント焼きそば」。"
"10002070-50-ヒフミ" = "では、私は「なまこジュースのチョコレートがけ」」で……！"
"10002070-51-アズサ" = "「練乳冷やし中華」。"
"10002070-52-イズミ" = "オーダー承りましたー！"
"10002070-53-イズミ" = "「牡蠣氷」「チョコミント焼きそば」「なまこジュースのチョコレートがけ」「練乳冷やし中華」を一つずつね！牡蠣シロップはまだあったかな……まあ多分大丈夫！"
"10002070-54" = "[s] \"ちょっ、ちょっと待って……！\""
"10002070-55-イズミ" = "あ、先生は何を食べるの？"
"10002070-56-イズミ" = "私に作れそうなものなら、何でも作ってあげるよ？"
"10002070-57-イズミ" = "どうする？何が良い？"
"10002070-58" = "[s] \"わ、私は……っ！！\""
"10002070-59" = "（ッダァン！！）"
"10002070-60-ヒフミ" = "……え？"
"10002070-61" = "（ダダダダダッ！ダダダダダンッ！！）"
"10002070-62-イズミ" = "ふえぇっ！？"
"10002070-63-イズミ" = "お、お店が襲撃されてる！？何で、どうして！？"
"10002070-64-？？？" = "「どうして」だと……！？"
"10002070-65-？？？" = "本気で言っているのか、このバイオテロリストめ！！"
"10002070-66" = "[s] \"この声は……。\""
"10002070-67-チンピラB" = "許さない……"
"10002070-68-チンピラB" = "許さないぞ！"
"10002070-69-チンピラA" = "お前たちのせいで、あたしらのヘッドは今でもトイレから離れられない！"
"10002070-70-ヒフミ" = "ま、またスケバンの方々が……！？"
"10002070-71-チンピラB" = "自信満々に出してきたと思って油断した……くそっ、お前の料理のせいで……！！！"
"10002070-72-チンピラB" = "こんなお店、ぶっ壊しちまった方がキヴォトスのためだ！いくぞ！"
"10002070-73-ヒフミ" = "え、えっと、状況がよく掴めないのですが……？"
"10002070-74-チンピラA" = "問答無用！！"
"10002070-75-チンピラA" = "おら、やっちまえ！！"
"10002070-76" = "（ダダダダダッ！ダララッ！ドカアァァン！！）"
"10002070-77-イズミ" = "あああっ！！私の……じゃないけど、お店が！！！"
"10002070-78-イズミ" = "待って待って！ここ私のお店じゃないから余計にダメだって！うわああん！！"
"10002070-79-アズサ" = "……よく分からないけど、応戦した方が良い？"
"10002070-80-マシロ" = "食べ物を粗末にするなどという、とんでもない悪の行い……見過ごすわけには行きません！"
"10002070-81-マシロ" = "さあ、正義の鉄槌を！"
"10002070-82-ヒフミ" = "え、ちょっ、これ何度目ですか！？"
