[translation]
"10002065-1" = "第6話;泳ぎを習得する（２）"
"10002065-2-ヒフミ" = "……。"
"10002065-3-ヒフミ" = "スケバンのみなさん、全然懲りませんね……。"
"10002065-4-マシロ" = "あの気絶したまま海の上に浮かんでる人たち、どうします？"
"10002065-5-ヒフミ" = "と、とりあえず浜辺まで引っ張ってきていただけると……。"
"10002065-6-アズサ" = "なるほど、こういうのが海か。悪くない。"
"10002065-7-ヒフミ" = "違います、アズサちゃん。違うんです……。"
