[translation]
"10040020-1" = "第2話;それぞれの年末年始"
"10040020-2-ノア" = "なるほど……。"
"10040020-3-ノア" = "パジャマで来るよう言ってたのは、このためだったんですね？"
"10040020-4-ユウカ" = "ちょっとノア、あんまり見ないでよ！#nまだ準備中なんだから！"
"10040020-5-ノア" = "ふふっ、ごめんなさい。#n面白そうだったので、つい。"
"10040020-6-ノア" = "それにしてもいろいろありますね。トラベルセットに、お菓子……。"
"10040020-7-ノア" = "この可愛いウサギのパジャマは……#nサイズを見るに、コユキちゃん用でしょうか？"
"10040020-8-ユウカ" = "そ、それは……！"
"10040020-9-ノア" = "不思議ですねぇ。#nここ数日、ユウカちゃんはずっと部室にいたのに。"
"10040020-10-ノア" = "一体いつ用意したんですか？"
"10040020-11-ユウカ" = "それは、その……先週、出かけた時に偶然見つけて……。"
"10040020-12-ユウカ" = "私が着るにはアレだけど、コユキにならちょうど良いかもって――"
"10040020-13-ユウカ" = "ああっ！？ここまで話すつもりじゃなかったのに！"
"10040020-14-ノア" = "ふふっ。#nユウカちゃんは優しいですね。"
"10040020-15-ノア" = "……そういうところですよね、きっと。多少叱られたとしても、#n面倒見の良い先輩はやっぱり接しやすいですから。#n……どこかの掴みどころのない先輩と違って。"
"10040020-16-ユウカ" = "もしかしてさっき言われたの、気にしてる？"
"10040020-17-ノア" = "……いえ、そんなことは。"
"10040020-18-ユウカ" = "気にしているじゃない……。"
"10040020-19-ユウカ" = "……コユキは気に障ることも言うけど、#n先入観で人を決めつけたりしないわ。"
"10040020-20-ユウカ" = "時間をかけて話し合えば、誤解も解けるはずよ。"
"10040020-21-ユウカ" = "ほら、最近あれこれ事件が続いたでしょ。#nそれでプライベートな話をする時間もなかったじゃない。"
"10040020-22-ユウカ" = "だから、良い機会だし、パジャマパーティーを開くのはどうかしら！"
"10040020-23-ノア" = "……やっぱり、ユウカちゃんは優しいですね。"
"10040020-24-ノア" = "いいと思います。#n私たちでパジャマパーティーなんて、どうなるか楽しみです。#n可愛い後輩との関係も良くしたいですし。"
"10040020-25-ノア" = "ユウカちゃんの新たな一面を知ることもできそうですし、ふふっ。"
"10040020-26-ユウカ" = "（これがコユキの言ってた「[ruby=あつ]圧[/ruby]」ってやつかしら……）"
"10040020-27-ノア" = "そういえば、久しぶりですね。ユウカちゃんの部屋に来るの。"
"10040020-28-ノア" = "前に来た時より随分と物が増えましたね。#n見慣れないポスターや写真も……。"
"10040020-29-ノア" = "あら、これはもしかして先生の――"
"10040020-30-ユウカ" = "ちょ、ちょっと！あんまり触っちゃダメ……！"
"10040020-31-ノア" = "ふふっ、いいじゃないですか。#nこういうの、パジャマパーティーのお約束なんですよね？"
"10040020-32-ノア" = "以前読んだ少女小説に、そう書かれてました。"
"10040020-33-ユウカ" = "どんな本よ、それ！#nしかもパジャマパーティーはまだ始まってないでしょ！"
"10040020-34-ユウカ" = "もう、変なこと言ってないで片付けを手伝って。"
"10040020-35-ノア" = "はーい。"
"10040020-36-ユウカ" = "パジャマ以外だと……#nみんなで遊べるテーブルゲームなんかもほしいわね。"
"10040020-37-ユウカ" = "セミナーの部室には、トランプくらいしかないわよね。#nノアは何か持ってない？"
"10040020-38-ノア" = "いえ、残念ながら……。"
"10040020-39-ノア" = "たしか、マキちゃんがたくさん持っていたはずです。#n貸してくれないか頼んでみるのはどうでしょう？"
"10040020-40-ユウカ" = "うーん。"
"10040020-41-ユウカ" = "どうしようかしら。"
"10040020-42-ユウカ" = "ヴェリタスはセミナーに非協力的だから……。"
"10040020-43-ノア" = "あら。話し合えば誤解は解ける、とさっきは言ってませんでしたっけ？"
"10040020-44-ノア" = "この機に、彼女たちとの関係も改善を図ってみては？"
"10040020-45-ユウカ" = "わ、分かったわよ。#nじゃあ、マキに貸してもらえないか頼んでみるわ。"
"10040020-46-ユウカ" = "でもあくまでプライベートなパジャマパーティーで借りるだけだから。#n変な言いがかりをつけられないように、公式記録には残さないでよね？"
"10040020-47-ノア" = "ふふっ、大丈夫ですよ。"
"10040020-48-マキ" = "うーん……やっぱりこれじゃ物足りないなあ。シンプルすぎるかも？"
"10040020-49-マキ" = "真ん中の彩度を低くして、もっとコントラストを――"
"10040020-50-ユウカ" = "ここにいたのね。"
"10040020-51-ユウカ" = "寮にいないから、探したのよ。"
"10040020-52-マキ" = "およ、ユウカ先輩？#nそれにノア先輩まで……。"
"10040020-53-マキ" = "あれ、パジャマ着てる……もう寝ちゃうの？#n年末とはいえ、ちょっと早すぎない？"
"10040020-54-ノア" = "いや、これは……。"
"10040020-55-ノア" = "親睦を深めるため、年越しパジャマパーティーを開こうと思って。"
"10040020-56-ノア" = "まあ、本当は反省部屋で一人ぼっちのコユキちゃんのために、ユウカちゃんが……。"
"10040020-57-ユウカ" = "もう、ノア！"
"10040020-58-マキ" = "へぇ、良いなぁ……あたしたちもやってみたいかも。"
"10040020-59-マキ" = "あーでも、いつもお菓子食べながら徹夜でゲームしてるし、#nあんまり変わんないか……。"
"10040020-60-ノア" = "ところでマキちゃんは、ひとりで何を？"
"10040020-61-マキ" = "「ミレニアムEXPO」のポスターを描いてたんだ。"
"10040020-62-マキ" = "前倒しになったからもうすぐ開催でしょ。#nそれで応募期間も短くなっちゃったから。"
"10040020-63-ノア" = "そういえば、人手不足でスケジュールが変更になってましたね。"
"10040020-64-ノア" = "ご迷惑をおかけして、申し訳ないです。"
"10040020-65-マキ" = "いいよ、ちょうど年末は予定もなかったし。だいじょーぶ。"
"10040020-66-マキ" = "それに、この時期でしか湧かないインスピレーションもあるからさ。"
"10040020-67-ユウカ" = "それにしても本当、すごいわね。これが才能かしら……。"
"10040020-68-ユウカ" = "こんなに絵が上手いのに、どうしてワイルドハントに進学しなかったの？"
"10040020-69-マキ" = "あー、その話は長くなっちゃうから、また今度……。"
"10040020-70-マキ" = "それより、なにか用があるんじゃないの？"
"10040020-71-ユウカ" = "ああ、そうそう。"
"10040020-72-ユウカ" = "テーブルゲームを貸してもらえないかしら。#nパジャマパーティーで使いたくて。"
"10040020-73-マキ" = "あー、最近使ってないし全然良いんだけど……。"
"10040020-74-ユウカ" = "いま、コタマ先輩とハレ先輩に貸してて、返してもらってないんだよね。"
"10040020-75-マキ" = "悪いけど、二人に聞いてもらえるかな？#nあたしは絵の方をなんとかしたいからさ。"
"10040020-76-ユウカ" = "分かったわ。#n借りたらあとはマキに返せばいいのよね。"
"10040020-77-マキ" = "だね。じゃ、次に会うのは来年かな。"
"10040020-78-マキ" = "またね、ユウカ先輩！良いお年を！"
"10040020-79-ユウカ" = "ええ。マキも良いお年を。"
"10040020-80-ユウカ" = "まさか、コタマ先輩もハレもどっちも寮にいないなんて……。"
"10040020-81-ユウカ" = "何か企んでたりするんじゃないかしら。"
"10040020-82-ノア" = "考えすぎだと思いますよ？"
"10040020-83-ノア" = "年末ですし、マキちゃんみたく来年に向けて何かしているのかもしれませんし。"
"10040020-84-ユウカ" = "ううん、油断は禁物よ。"
"10040020-85-ユウカ" = "今までヴェリタスがしでかしてきたことを考えると――"
"10040020-86-ノア" = "うちの子が、また何かやったの？"
"10040020-87-ノア" = "あら、これはこれは……。"
"10040020-88-ユウカ" = "あ、チヒロ先輩。コタマ先輩とハレを見なか――"
"10040020-89-ユウカ" = "って、すごい顔色ですけど！？大丈夫なんですか！？"
"10040020-90-チヒロ" = "気にしないで。二日寝てないだけだから。"
"10040020-91-ユウカ" = "[ruby=おおごと]大事[/ruby]じゃないですか！"
"10040020-92-ノア" = "セキュリティに問題でもあったんですか？"
"10040020-93-チヒロ" = "というほどじゃないけど……最新のアンチウイルスソフトでも検出できない悪性コードが、ミレニアムの共用サーバーで発見されてね。"
"10040020-94-チヒロ" = "デスクトップ背景がいきなりホラー画像に変わったり、迷惑メールが大量に送られたり……一見、ジョークプログラムみたいなんだけど……丸々二日メンテナンスしても何の痕跡も見つからなくて。"
"10040020-95-ノア" = "……痕跡が見つからない、というとつまり？"
"10040020-96-チヒロ" = "報告が間違ってるか、あるいは私より腕のいいハッカーの仕業だってこと。"
"10040020-97-チヒロ" = "まあ、いずれにせよ今は何もできないし、そろそろ寝ようと思ってたんだ。"
"10040020-98-ノア" = "年末だというのに、ご苦労さまです……。"
"10040020-99-チヒロ" = "セキュリティの仕事だからね。よくあることだよ。"
"10040020-100-チヒロ" = "それより、うちの部員に用があったんじゃない？"
"10040020-101-ユウカ" = "その……これからパジャマパーティーをするんですけど、#nコタマ先輩とハレからテーブルゲームを借りたくて。"
"10040020-102-チヒロ" = "パジャマパーティーか……楽しそうだね。#n私とは縁のない話だけど。"
"10040020-103-チヒロ" = "さっき共用サーバーで二人のスマホが接続されてたのを見たから、#nたぶんヴェリタスの休憩室にいると思うよ。"
"10040020-104-ユウカ" = "そこまで分かるんですね！？"
"10040020-105-チヒロ" = "真っ暗な部屋で得体の知れないコードを探すよりは簡単だよ。"
"10040020-106-チヒロ" = "ふぁ……今夜は何もないと良いんだけど。"
"10040020-107-ノア" = "大丈夫です。ヴェリタスの副部長が二日もメンテナンスしたんですよ。#n完璧なはずです。"
"10040020-108-ユウカ" = "いまはゆっくり休んでください。"
"10040020-109-ノア" = "ですね、おやすみなさい先輩。"
"10040020-110-チヒロ" = "ありがとう。二人とも、良いお年を。"
"10040020-111-ハレ" = "はい、コタマ先輩。頼まれた通り、#n「ルーレットのハズレで自動録音する機能」をプログラミングしてきたよ。"
"10040020-112-ハレ" = "でも、なんでテーブルゲームにそんな機能を……？"
"10040020-113-コタマ" = "愚問ですね、ハレ。#n「海賊危機一髪」のようなゲームに#n録音機能をつける理由なんてひとつしかないでしょう。"
"10040020-114-コタマ" = "悲鳴を録るためです。"
"10040020-115-コタマ" = "いや、それは分かるけど……そんな声を録って、何に使うつもり？"
"10040020-116-ハレ" = "先輩がよく聞くASMRも、悲鳴より柔らかい音声がほとんどでしょ。"
"10040020-117-コタマ" = "たしかに人の叫び声に人気はありません。#nが、そのせいでサンプル数が少ないんです。"
"10040020-118-ハレ" = "古典映画が劣化した悲鳴を何度も再利用しているのだって、#nそれが原因だと言われているくらいですから。"
"10040020-119-コタマ" = "ナチュラルな悲鳴の録音を大量に録っておけば、#nより価値のある音源と交換できますし。"
"10040020-120-ハレ" = "……交換？#nコタマ先輩みたいな趣味の人が他にいるの？"
"10040020-121-コタマ" = "加えてこの機能を追加しておけば、#n何かの機会に先生の驚く声を録音できる可能性もあります。"
"10040020-122-ハレ" = "それは興味あるかも……。"
"10040020-123-コタマ" = "ふふっ。#n超小型ボイスレコーダーも取り付けましたし、これで完成です。"
"10040020-124-コタマ" = "後はルーレットを元に戻して、誰かが使うのを――"
"10040020-125-ユウカ" = "……そんなの、放っておくわけないでしょう。"
"10040020-126-ハレ" = "い、いつの間に……！？"
"10040020-127-コタマ" = "まさか、この録音機能付きのテーブルゲームをセミナーも狙ってたんですか？"
"10040020-128-ノア" = "どちらかというと、普通のものを探していたのですが……。"
"10040020-129-ノア" = "とりあえずプライバシー保護のため、ボイスレコーダーは没収しますね。"
"10040020-130-コタマ" = "そんな……。"
"10040020-131-ユウカ" = "まったく、年末までトラブルを起こそうとしてくれちゃって……。"
"10040020-132-ユウカ" = "こんなんだからミレニアムには変な部活が多いって言われるのよ。#n少しは副部長を見習ってほしいものね。"
"10040020-133-ハレ" = "うーん……。"
"10040020-134-ハレ" = "こんなこと言えた立場じゃないけど……。"
"10040020-135-ユウカ" = "納得できてないって顔ね……。いいわ、言ってみなさい。"
"10040020-136-ハレ" = "トラブルメイカーは、セミナーにもいるよね？"
"10040020-137-コタマ" = "無効化したセキュリティの数で言えば、#nヴェリタスよりも「セミナーの誰か」の方が#nずっと多いって話もあるみたいだけど……。"
"10040020-138-ユウカ" = "こ、コユキはちゃんと反省してるわよ！？"
"10040020-139-ユウカ" = "ここ一ヶ月……ううん、一週間は何も起こしてないもの！"
"10040020-140-ノア" = "ユウカちゃん、落ち着いて。"
"10040020-141-ノア" = "……でも、ここ最近大人しくしていたのはその通りですね。"
"10040020-142-ノア" = "反省部屋からの脱走もしてませんし、#n認可外の電子機器にも手を出してないようですし……。"
"10040020-143-コタマ" = "新年も近いし、少し大人しくしてるのかな？"
"10040020-144-コタマ" = "なるほど。つまり先程おっしゃっていたパジャマパーティーは、#n大人しくしているコユキさんへのプレゼントというわけですか。"
"10040020-145-ユウカ" = "プレゼントとは違うわね……#n目を離したら何か騒ぎを起こすんじゃないかって心配なだけ。"
"10040020-146-ユウカ" = "だから悪い気を起こさないように、たまには娯楽を提供しなきゃって思って。"
"10040020-147-コタマ" = "（なんか、ペット扱いしているような……）"
"10040020-148-コタマ" = "だとしたら、一刻も早く反省部屋に戻った方がいいのでは？"
"10040020-149-ノア" = "大丈夫よ。#n反省部屋でちゃんと大人しくしてる姿を見たんだから。数時間前だけど。"
"10040020-150-ユウカ" = "いくらコユキでも、それくらいなら……。"
"10040020-151-ノア" = "ふふっ、まさかそんな――"
