[translation]
"1902-1" = "嵐を呼ぶ突発の会計監査"
"1902-2" = "風紀委員会・大会議室"
"1902-3-マコト" = "……以上が、来月に予定している戦術訓練の計画案です。"
"1902-4-マコト" = "ふむ……[ruby=パンデモニウム・ソサエティー]我々万魔殿が提[/ruby]案した計画が、影も形も無いようだが？"
"1902-5-アコ" = "……こちらの方が合理的だと判断いたしましたので。"
"1902-6-アコ" = "この訓練で使用する予算案については既に提出済みです。内容は今回の計画案と照らし合わせても問題ないかと思いますので、そちら側でご確認いただいて、本決定にできればと。"
"1902-7-マコト" = "……ああ、そういえば届いていたな。目は通した。確かに問題は無い。"
"1902-8-アコ" = "では――"
"1902-9-マコト" = "しかし却下だ。"
"1902-10-アコ" = "……はい？ですが今、問題は無い、と……。"
"1902-11-マコト" = "ああ、確かに問題は無い。"
"1902-12-アコ" = "ではなぜ……"
"1902-13-マコト" = "それでも却下だ。"
"1902-14-アコ" = "……何か不備や要望があれば、調整いたしますが？"
"1902-15-マコト" = "キキキッ……！無駄だ、どう書類を調整したところで、結果は変わらない。"
"1902-16-アコ" = "……どういうことでしょう？"
"1902-17-マコト" = "仕方ない、説明してやろう。前々から思っていたのだ……風紀委員会の予算周りについては、もっと精査が必要だと。"
"1902-18-マコト" = "書類がいくら整っていようと、実際にはどこで着服されているか、変な使い方をされているか分かったものではない。そうだろう？"
"1902-19-アコ" = "（あなたがそれを言いますか……！？誰よりもゲヘナの予算を浪費しているあなたが！？）"
"1902-20-アコ" = "ふぅ。では、どうすれば……？"
"1902-21-マコト" = "ちょうど良い機会だ、風紀委員会。仕方ないから我々が会計監査をしようじゃないか。"
"1902-22-アコ" = "ちょっ、ちょっと待ってください、急にそんな……！"
"1902-23-マコト" = "仕方あるまい。最近は風紀委員会に、色々と怪しい動きがあると聞いているしな？"
"1902-24-マコト" = "例えば、風紀委員長でもないどこかの行政官が、独断で兵力を運用した……とか。"
"1902-25-アコ" = "……っ！"
"1902-26-マコト" = "キシシシシシ……！何だ、良い顔ができるじゃないか！"
"1902-27-アコ" = "（普段こちらからの情報なんて全部無視してるのに、こういうところだけ抜け目ない……！）"
"1902-28-マコト" = "キキキキッ……！何度でも言ってやろう、[ruby=あまう]天雨[/ruby]アコ。万魔殿を出し抜こうなど、所詮は無駄な足搔きだとなぁ！"
"1902-29-アコ" = "本当に困ったタヌキですね……！"
"1902-30-アコ" = "（どうやら誤解があるようですので、それも合わせて少し検討させていただきましょうか）"
"1902-31-アコ" = "あらっ、思ったことと言おうとしたことが逆に……。"
"1902-32-マコト" = "……ま、まぁ良い。"
"1902-33-マコト" = "精々念入りに、首でも洗って楽しみにしてるがいい！今度こそ徹底的に思い知らせてくれるわ！キキキキ、キャハハハハハ！！！"
"1902-34-アコ" = "全く……！"
"1902-35-マコト" = "イロハ、仕事だ。"
"1902-36-イロハ" = "……お呼びでしょうか、マコト先輩。"
"1902-37-マコト" = "お前に、風紀委員会への会計監査を命じる！キキキキ……やつらの腹の底を、全て暴いてやれ！"
"1902-38-マコト" = "あの気に入らない鼻をへし折り、我々万魔殿の恐ろしさを思い知らせてやるのだ！"
"1902-39-イロハ" = "……めんどくさ。"
"1902-40-マコト" = "い、イロハ……？今、なんて……？"
"1902-41-イロハ" = "はあ、分かりました。仕事なら仕方ありません。で、会計監査ですか？"
"1902-42-マコト" = "そうだ！やってしまえ、徹底的に風紀委員会を叩きのめせ！"
"1902-43-イロハ" = "叩きのめすも何も、ただの監査ですよね。"
"1902-44-マコト" = "キシシシシシ……風紀委員会め、今度こそその心をへし折って、二度と我々を舐めるなんて真似ができないように――"
"1902-45-イロハ" = "はいはいそうですか。"
"1902-46-マコト" = "た、頼むから、せめて最後まで話を聞いてくれ……。"
"1902-47-イブキ" = "……というわけで、監査をしに来たよ！"
"1902-48-イロハ" = "はぁ……。"
"1902-49-イブキ" = "せっかくマコト先輩が任せてくれたことだから、イブキ頑張るね！"
"1902-50-イオリ" = "えっ、今から！？"
"1902-51-チナツ" = "こんな、訓練が目の前に迫っている状況で……。"
"1902-52-イオリ" = "アコちゃんこれどういうこと！？よりによって委員長がいない、こんなタイミングで……！"
"1902-53-アコ" = "くっ……！"
"1902-54-イロハ" = "諦めてください。万魔殿の上層部直々の指示ですので。"
"1902-55-アコ" = "……まあ構いません。どちらにせよ杜撰な管理をしているつもりはありませんし、探られたところで痛くも痒くもありませんから。"
"1902-56-アコ" = "むしろこの機に、これ以上無いくらい完全な身の潔白を証明して、今後は変な脅しなんてできないようにして差し上げましょう。"
"1902-57-アコ" = "さぁ、やるのでしたら存分にどうぞ！"
"1902-58" = "アコちゃん、自信満々なのは良いけど……。"
"1902-59-チナツ" = "行政官がこういうテンションの時は、逆に不安です。"
"1902-60-イロハ" = "では遠慮なく。"
"1902-61-イロハ" = "まず最初は……"
"1902-62-イロハ" = "……風紀委員会の本部ですね。"
"1902-63" = "ゲヘナ風紀委員会本部・廊下"
"1902-64-イオリ" = "……廊下に見るところなんてあるのか？"
"1902-65-イロハ" = "……なるほど。"
"1902-66-イオリ" = "な、何だよ……。"
"1902-67" = "万魔殿が配布している新聞、掲示されてませんね。"
"1902-68" = "減点です。"
"1902-69" = "はいっ！？"
"1902-70" = "何それ、知らないんだけど！？"
"1902-71" = "……はあ。"
"1902-72" = "万魔殿が定期的に配布している新聞は、どの建物の掲示板にも必ず貼られていなくてはなりません。校則で決められています。"
"1902-73" = "そんな校則があったのか！？"
"1902-74" = "まあ、つい先々月にマコト先輩が発議したばかりの校則ですので、まだ現場には情報が届いていないかもしれませんが。"
"1902-75" = "……それでも校則は校則なので。"
"1902-76" = "それはもう暴挙じゃんか！？"
"1902-77" = "戦術訓練の予算はまず、こちらに割り当てるべきですね。そういう形で予算使用の予定を書き換えておきます。"
"1902-78" = "予算の名目は「掲示板の整備」とかにしておきましょうか。"
"1902-79" = "くうっ……！"
"1902-80" = "では次です。"
"1902-81" = "ゲヘナ風紀委員会本部・2F休憩室"
"1902-82-チナツ" = "こちらが、普段風紀委員会で使っている休憩室です、が……ここまで調査するんですか？"
"1902-83-イロハ" = "そうですね。校則で決められている備品が揃っているか、賞味期限切れの物などが放置されていないか……"
"1902-84-イロハ" = "そういう部分の調査になります。それらを誤魔化すことで、数値の粉飾に繋げることもできますから。"
"1902-85-アコ" = "そういうことでしたらきちんと管理していますから、心配ありません！"
"1902-86-イブキ" = "ねえねえイロハ先輩。"
"1902-87-イロハ" = "イブキ？どうかしましたか？"
"1902-88" = "この休憩室、ココアは無いの？"
"1902-89-イロハ" = "なるほど……ありませんね。これは減点です。お客さんに対するおもてなしの準備がなっていません。こちらにも予算を割くべきでしょう。"
"1902-90-イオリ" = "はぁっ！？ココアで減点！？"
"1902-91-イロハ" = "いつどんなお客さんが来るかは分かりません、様々な好みに合わせて品を揃えておくのは当然のこと……。"
"1902-92-イロハ" = "といった感じで、「何でも良いからいちゃもんを付けてこい」とマコト先輩に言われてますので。"
"1902-93-イオリ" = "それ、この場で言っちゃって良いことなのか！？"
"1902-94-イロハ" = "まあ、では聞かなかったことにしてください。はぁ、どうしてそもそも私がこんなことを……。"
"1902-95-イロハ" = "では次……。"
"1902-96-アコ" = "……。"
"1902-97" = "（その後もイロハは無情にも、徹底的にいちゃもんをつけ、風紀委員会の予算を次々と削減したり用途を変更していった……）"
"1902-98-イロハ" = "これも、あれも、それも……。"
"1902-99-イロハ" = "削減、変更、削減、変更、削除、削減です。"
"1902-100-アコ" = "……！"
"1902-101-チナツ" = "酷いですね……。"
"1902-102-イオリ" = "いくら何でも無茶苦茶だろ！？途中からもう論理が飛躍しまくってるし！"
"1902-103-イロハ" = "そう言われましても、私はただの公務員みたいなものなので。"
"1902-104-イロハ" = "あなた方に対して個人的な敵意はありませんが、これも仕事ですから……。"
"1902-105" = "（そうして、約3時間に渡る会計監査（？）が繰り広げられ……）"
"1902-106-イロハ" = "そういうわけで……諸々確認した結果、戦術訓練の予算における約95%は削減、あるいは環境整備など別の予算に割り当てられるべきですね。"
"1902-107-イオリ" = "ああもう無茶苦茶だよ！そんなのもう訓練にならないじゃんか！？"
"1902-108-チナツ" = "これがまかり通ってしまうと、次の戦術訓練は……。"
"1902-109-イロハ" = "さて、残りは……"
"1902-110-イブキ" = "ふんふん～るんるん～♪"
"1902-111-チナツ" = "あっ、イブキ！そこ、前っ……！"
"1902-112-イロハ" = "イブキっ！"
"1902-113-イブキ" = "い、痛い……うぅ……。"
"1902-114-イロハ" = "大丈夫ですかイブキ！？どこか怪我は！？"
"1902-115-イオリ" = "なんか今、ものすごい派手に転んだけど……大丈夫か？"
"1902-116-イブキ" = "ひぐっ、うぅ……ぐすっ……な、泣かないもん……大丈夫……。"
"1902-117" = "……来年度の予算はゼロですね。"
"1902-118-イオリ" = "はぁ！？急にどうして！"
"1902-119-チナツ" = "一応聞きますが、理由は……。"
"1902-120-イロハ" = "イブキを泣かせたから。"
"1902-121-イオリ" = "もう無茶苦茶ってレベルじゃないぞ！？"
"1902-122-イロハ" = "イブキを泣かせるなんて、許しません。"
"1902-123" = "うぅ……あっ、それ、マコト先輩がいつも言ってる台詞だ！"
"1902-124-イオリ" = "でも今のは別に私たちのせいじゃ……！これくらい物が置いてあるのは普通のことだろ！？"
"1902-125-イロハ" = "私たちが来ると知っていたのですから、あらかじめ片付けることはできたはずです。それにもし、イブキがこうして怪我をしたことが、マコト先輩に知られたら……。"
"1902-126-イロハ" = "「配慮が足りない、そのせいでこちらの大切な人員に被害が出た」とカンカンに怒り、来年度の予算がどうこうのレベルでは済まないでしょう。"
"1902-127-イロハ" = "これくらいで済んで良かったと思ってください。"
"1902-128-イオリ" = "横暴だぁ！！"
"1902-129-イロハ" = "さて、では後は……。"
"1902-130-マコト" = "キキッ、キャハハハハハ！よくやったぞイロハ！素晴らしい！"
"1902-131-アコ" = "……。"
"1902-132-マコト" = "これで分かっただろう、アコ行政官？万魔殿が本気を出したらどうなるのか！"
"1902-133-アコ" = "くっ……。"
"1902-134-マコト" = "キシシシッ！そろそろ無意味な抵抗は止めて、理解したらどうだ？"
"1902-135-マコト" = "お前たち風紀委員会なんか、我々万魔殿の下っ端に過ぎないのだということを！"
"1902-136" = "この事実をきちんと受け止め、噛みしめ！"
"1902-137-マコト" = "まるで子犬のように我々の前でお腹を見せて、服従するが良い！！キキッ、キャハハハハハハッ！"
"1902-138-マコト" = "……あの。これ、ただの会計監査なんですが。"
"1902-139-イロハ" = "予算の再分配案は一応作りましたが、これを正式に処理するためには行政的な手続きが必要で、それができないとただの案に過ぎないですし……って、聞いてないですね。"
"1902-140-アコ" = "といったことが、先ほどありまして……。"
"1902-141-アコ" = "（ちらっ……）"
"1902-142-ヒナ" = "……そう。"
"1902-143-ヒナ" = "はぁ、あのタヌキたちめ……できるだけ会いたくなかったけど、仕方ない。"
"1902-144" = "い、委員長……？"
"1902-145-チナツ" = "もしかして……？"
"1902-146-ヒナ" = "ちょっと行ってくる。"
"1902-147" = "（その後銃声が響き渡り、万魔殿の本部が突然の爆発音と共に一部崩壊した、と言われているものの……）"
"1902-148" = "（それはまた別のお話……）"
"1902-149" = "嵐を呼ぶ突発の会計監査"
