[translation]
"10016120-1" = "後日談その2;RABBIT小隊編"
"10016120-2-ミヤコ" = "……こちらRABBIT1。現在時刻は1930。#nミレニアムの生徒が大運動会の備品、及び機材の回収を確認。"
"10016120-3-ミヤコ" = "続いて、応援ロボットに偽装し会場内に持ち込まれた戦車――通称「ブルジョアクラッシャー」の機能停止も確認しました。"
"10016120-4-ミヤコ" = "その他、安全性が確認されていないロボットも、「ヴェリタス」の関係者と思しき生徒により全て回収済みです。"
"10016120-5-ミユ" = "こ、こちら、RABBIT4……#nアスレチックスタジアムの郊外で、デモを起こしてる工務部を発見……"
"10016120-6-ミユ" = "「週休4日制」を主張して、ヴァルキューレの生徒と言い争いをしてたけど……#n観客が減って、勢いが弱まってる……"
"10016120-7-ミユ" = "ここでデモを続けても、意味がないことに気づいたみたい……"
"10016120-8-サキ" = "こちらRABBIT2。観客の帰宅が済んだ観覧席エリアのパトロールを完了した。#n爆発物や引火性の高い不審物は無し。"
"10016120-9-サキ" = "観客がゴミを持ち帰ってくれたおかげだ。#nこれなら見るまでもなかったな。"
"10016120-10-モエ" = "こちらRABBIT3。救護所の電子カルテを調べてみたよ。#n幸い、重症者はいなかったみたい。"
"10016120-11-モエ" = "SNSの反応も好意的なものが多いし……#nこれなら大成功って言ってもいいんじゃないの？"
"10016120-12-ミヤコ" = "アスレチックスタジアム内の危険因子は、すべて取り除かれたと判断して良いでしょう。"
"10016120-13-ミヤコ" = "……ミッションクリアです！"
"10016120-14-モエ" = "みんな、本当にお疲れ様……"
"10016120-15-モエ" = "まあ、SRT特殊学園の総合成績は最下位だったけどね……ふふ。"
"10016120-16-サキ" = "くっ……あのとき戦車にぶつからなければ1勝はできたのに……"
"10016120-17-モエ" = "またその話？"
"10016120-18-モエ" = "それを言うなら、「借り物競争」は？#n規則をちゃんと読んでたら、失格にならずに済んだでしょ。"
"10016120-19-サキ" = "う、うるさいな！#n競技場に白リン弾を持ってくるやつに言われたくない！"
"10016120-20-ミユ" = "私たち……4人しかいないから……"
"10016120-21-ミユ" = "参加できる競技の数が少なかったし……#n最下位になっちゃったのも、仕方ないんじゃないかな……？"
"10016120-22-モエ" = "でも、アビドス高校ってとこは、全生徒5人しかいないのに真ん中くらいの成績だったらしいよ？"
"10016120-23-モエ" = "うーん……やっぱり、ここはサキのせいにしとこっか。"
"10016120-24-サキ" = "おいっ！"
"10016120-25-ミヤコ" = "気にする必要はありませんよ。"
"10016120-26-ミヤコ" = "私たちは、すでに24時間以上作戦を継続している状態です。#n精神的にも体力的にも、不利な状態でしたから。"
"10016120-27-ミヤコ" = "それに、ミレニアムに持ち込まれた軍用パーツの行方を追いかけたおかげで、戦車が暴れても慌てず速やかに動けました。"
"10016120-28-ミヤコ" = "何より……「市民の安全を守る」という一番の目標は達成できましたので。"
"10016120-29-ミヤコ" = "……記録には残らないかもしれませんが、きっと誰かの記憶には残ってくれるはず。"
"10016120-30-ミヤコ" = "……なら、良しとするか。"
"10016120-31" = "作戦なのに、こんなこと思っちゃダメだと思うんだけど……"
"10016120-32-ミユ" = "今回の作戦は、いつもよりちょっと……"
"10016120-33-モエ" = "ちょっと……？"
"10016120-34-ミユ" = "……ちょっと、楽しかったな。"
"10016120-35" = "お、おかしいよね……？#n市民の安全を守るSRTが、作戦を楽しむなんて……"
"10016120-36-ミユ" = "うぅ……やっぱり、私はSRT特殊学園に[ruby=ふさわ]相応[/ruby]しくない役立たずで――"
"10016120-37-ミユ" = "……いや、その気持ちは私も分かるぞ。"
"10016120-38-サキ" = "久しぶりに色々な学園と競い合って汗をかいたおかげで、あらためて実感した。"
"10016120-39-サキ" = "私たちは、このために街を守っているんだなぁって。"
"10016120-40-サキ" = "あっ、いや……ほら！教範で読むよりも実際にやってみたほうが理解しやすいこともあるだろう？SRTの目的も、時たま実感しづらいし……"
"10016120-41-サキ" = "SRTの存在意義を肌で感じる、良い機会になったというか……"
"10016120-42-ミユ" = "サキちゃん……"
"10016120-43-サキ" = "私も今回の大運動会、楽しかったよ。"
"10016120-44-モエ" = "普段は触れられないデータにもアクセスできたし……"
"10016120-45-モエ" = "ちょっとした臨時収入も……"
"10016120-46-サキ" = "お前は楽しみすぎだ！"
"10016120-47-ミヤコ" = "目まぐるしい1日でしたが、皆さんの笑顔を近くで見られた貴重な1日でもありましたね。"
"10016120-48-ミヤコ" = "SRTの隊員として、今日という日常を大切に、これからも正義のために――"
"10016120-49-ミヤコ" = "……。"
"10016120-50-モエ" = "そういや、今日は何も食べてなかったね……"
"10016120-51-ミユ" = "廃棄弁当を探す暇もなかったから……"
"10016120-52-サキ" = "「パン食い競争」でアンパンを食べたぐらいだな……"
"10016120-53-ミユ" = "……さっき、ゲヘナ生がトングと食材を持って中央フィールドに向かってたけど……"
"10016120-54-ミユ" = "バーベキューでもするのかな……？"
"10016120-55-ミヤコ" = "中央フィールドでしたら……「後夜祭」のキャンプファイヤーが行われているはずです。"
"10016120-56-ミヤコ" = "バーベキューを行うというのは聞いていませんが……"
"10016120-57-ミヤコ" = "何か問題が発生するかもしれません……様子を見に行きましょう。"
"10016120-58-サキ" = "そ、そうだよな！大人数で集まって火を扱うんだ、用心するに越したことはない！"
"10016120-59-モエ" = "……バーベキューの残りを狙ってるわけじゃないけどね！"
"10016120-60-ミユ" = "なんか、手段と目的が入れ替わってるような気も……"
"10016120-61-ミヤコ" = "……それでは、三日月作戦ミッションリスタートです！"
"10016120-62-モエ" = "了解！"
