[translation]
"10016080-1" = "第8話;偶然の縁"
"10016080-2" = "（騒がしい状況が一段落し……）"
"10016080-3-ユウカ" = "はぁ、はぁ……。#n戦車……じゃなかった、応援ロボットの機能停止を確認。"
"10016080-4-ユウカ" = "カタピラとエンジンを完全に破壊したから、もう暴れる事はないと思うわ。"
"10016080-5-ハスミ" = "逃げていた不良生徒の身柄も確保しました。"
"10016080-6-ハスミ" = "幸い、この騒動に便乗して、暴動を起こすような生徒はいませんでしたね。"
"10016080-7-ハスミ" = "選手たちも無事に避難できています。#n怪我をされた方は、さきほど合同医療本部へ搬送されました。"
"10016080-8-ユウカ" = "ひとまず最悪の事態は避けられたわね。#nみんな、お疲れさま。"
"10016080-9-アコ" = "業務の一環とはいえ、まさか他校の生徒と肩を並べて戦うことになるとは……。"
"10016080-10-ハスミ" = "なにか不満でも？"
"10016080-11-アコ" = "いえ……むしろ滅多にない経験ですから、新鮮ですね。"
"10016080-12-アコ" = "トリニティの実力はある程度把握していましたが、#nミレニアムの情報処理能力は想像以上でした。"
"10016080-13-アコ" = "現場で収集したデータを瞬時に分析し、相手の弱点を見極めるとは。#nやはり[ruby=セミナー]生徒会[/ruby]役員は伊達じゃありませんね。"
"10016080-14-ユウカ" = "そっ、そんな急に褒められると……。"
"10016080-15-アコ" = "まあ、騒動の発端となったロボットもミレニアムが作ったものですが。"
"10016080-16-ユウカ" = "うっ……で、でも技術に罪はないでしょう？"
"10016080-17-ユウカ" = "エンジニア部の発明品が不要な機能まで搭載していたのは事実だけど、#n悪いのは騒動を起こした――"
"10016080-18-マリー" = "お、落ち着いてください、ユウカさん。#nミレニアムの責任と言っているわけではありませんから。"
"10016080-19-ユウカ" = "こほん……データの分析くらい、そこまで難しいものでもないわ。#nセミナーの会計だもの、これくらいできるわよ。"
"10016080-20-ユウカ" = "むしろ、ハスミ副委員長の精密な射撃に驚いたくらい……。"
"10016080-21-ユウカ" = "スコープも使わずに動く砲身を正確に撃ち抜くなんて……#n一体どういう技を使ったの？"
"10016080-22-ユウカ" = "そうですね……直感、とでも言いましょうか。"
"10016080-23-ハスミ" = "正義実現委員会として活動する中で自然と身についた感覚なので、言葉での説明は難しいですね……。"
"10016080-24-ユウカ" = "……その直感って言い方が気になるわね。"
"10016080-25-ユウカ" = "今度、ミレニアムの測定装置で射撃の様子を撮影させてくれない？"
"10016080-26-ハスミ" = "はい、構いませんよ。"
"10016080-27" = "[s] \"みんな、お疲れさま\""
"10016080-28-ハスミ" = "あ、先生。支援ありがとうございました。"
"10016080-29" = "[s1] \"よかったら、みんなでパフェでも食べない？\"\n[s2] \"お疲れさま。屋台で何かご馳走するよ。\""
"10016080-30-マリー" = "嬉しいお話なのですが、合同医療本部の手が足りていないようで……。#n私は負傷者の救護に向かいますね。皆さんで食べてきてください。"
"10016080-31-マリー" = "嬉しいお話なのですが、合同医療本部の手が足りていないようで……。#n私は負傷者の救護に向かいますね。皆さんで食べてきてください。"
"10016080-32-ユウカ" = "私も今は食欲がなくて……少し休憩室で休んできますね。"
"10016080-33-アコ" = "私はゲヘナの選手控え室に向かいます。#n最後のリレー前に、ヒナ委員長のコンディションを確認しておきたいですから。"
"10016080-34-ハスミ" = "……"
"10016080-35" = "[s] \"ハスミは？\""
"10016080-36-ハスミ" = "パフェ……パフェ……。#nわ、私も遠慮しておきます。"
"10016080-37-ハスミ" = "他の方と違って、何か予定があるわけではありませんが、#n気分転換を兼ねて競技場を見回ってこようかと。"
"10016080-38" = "[s3] \"それなら競技に参加してみたら？\"\n[s4] \"新しい経験になるし、きっと楽しいよ。\""
"10016080-39-ハスミ" = "私が……競技に？"
"10016080-40-ハスミ" = "私が……競技に？"
"10016080-41-ハスミ" = "……先ほども申し上げましたが、競技に参加するのは私の役目ではありません。"
"10016080-42-ハスミ" = "トリニティの優勝に貢献するため……それに今日のお祭りを成功させるためにも、私よりツルギのような身体能力が優れた生徒に任せたほうが合理的です。"
"10016080-43-ハスミ" = "私は後ろから皆さんの頑張りを支えられたら、それで十分です。"
"10016080-44" = "[s] \"でも……。\""
"10016080-45-ハスミ" = "それでは、失礼いたします。"
"10016080-46-選手A" = "ふっふーん！最後に私が帽子を取った瞬間は爽快だったわ！"
"10016080-47-選手B" = "ぐぬぬ……体勢を崩しさえしなければ、私が勝ってたはずなのに……！"
"10016080-48-選手B" = "次こそ私が勝ってMVPを頂くから！#n覚えておくことね！"
"10016080-49-選手A" = "ふふっ、いつでもかかってきなさい！"
"10016080-50-ハスミ" = "なんだか皆さん……とても楽しそうですね。"
"10016080-51-ハスミ" = "（いえ、楽しむのは当たり前ですね。今日はせっかくのお祭りですから）"
"10016080-52-ハスミ" = "（先生は私にも競技に参加するようおっしゃっていましたが……）"
"10016080-53-ハスミ" = "（しかし、私まで楽しんでいてはなりません。平和の影には、いつも誰かの働きがあるものですから）"
"10016080-54-ハスミ" = "（いけませんね……まだ閉会まで時間はありますし、気を緩めるのは早いです）"
"10016080-55-イズナ" = "うぅ……どうしましょう。#nこれから決勝戦だというのに、部長が腹痛で倒れてしまうとは……。"
"10016080-56-カエデ" = "もう！だからあのたこ焼きはなんか怪しいって言ったのに！"
"10016080-57-カエデ" = "お店の人はただのタコを入れただけって言ってたけど、焼き上がってるのにあんなうにょうにょ動くタコ、どう考えてもおかしいよ！"
"10016080-58-チセ" = "きらきら～たこやき～……まんまる～たこやき～……。"
"10016080-59-チセ" = "素敵な俳句が詠めるかも～。"
"10016080-60-ツクヨ" = "わ、私にできることはありますでしょうか……。"
"10016080-61-ツクヨ" = "そんなに交友関係が広くないので……騎手、どうしましょう……。"
"10016080-62-イズナ" = "うーん、一応4人ではありますが……"
"10016080-63-ハスミ" = "あちらの生徒……たしか百鬼夜行の……。"
"10016080-64-ハスミ" = "そうでした、次は騎馬戦の決勝ですね。#nたしか、百鬼夜行とミレニアムの……。"
"10016080-65-ハスミ" = "現時点の総合1位はミレニアムですし、ここで百鬼夜行に善戦していただいて、#nミレニアムの独走状態にブレーキをかけてくれると助かるのですが……。"
"10016080-66-カエデ" = "それでは、部長の代わりにツクヨ殿が騎手を務めるのはどうでしょう！"
"10016080-67-ツクヨ" = "む、無理ですよぉ……。"
"10016080-68-ツクヨ" = "私みたいなのが騎手になったら、騎馬のバランスがうまく取れないと思います……。"
"10016080-69-イズナ" = "でしたらイズナに騎手をお任せください！"
"10016080-70-カエデ" = "えっ！？それだと今度は私の腕が届かないよー！"
"10016080-71-チセ" = "つぼの中のタコ。 #n食中毒の夢を見る……"
"10016080-72-ハスミ" = "あの様子ではミレニアムが勝つでしょうね……。"
"10016080-73-ハスミ" = "残念ですが、トリニティの戦いではありませんし、見守る事しか……。"
"10016080-74-イズナ" = "うぅ、何か良い案はないでしょうか？"
"10016080-75-イズナ" = "イズナが『彷徨う孤独な忍者77人組』に出てくる策士・甲斐兵衛のような優れた秘策を持っていれば……。"
"10016080-76-イズナ" = "うぅっ……ご、ごめんなさい……。"
"10016080-77-ツクヨ" = "私みたいな無駄に大きいだけで役に立たない部員が残ってしまって……。"
"10016080-78-ツクヨ" = "私の背が高いばっかりに……ごめんなさい……。"
"10016080-79-ハスミ" = "――背の高さが、なぜ問題になるのでしょうか？"
"10016080-80-イズナ" = "あ、あなたは……？"
"10016080-81-カエデ" = "（お、大きい……！）"
"10016080-82-ハスミ" = "黙って聞いていようと思っていましたが、今の言葉は聞き流せません。"
"10016080-83-ハスミ" = "皆さん、騎馬戦のルールはご存知ですか？"
"10016080-84-ハスミ" = "そりゃもちろん！"
"10016080-85-カエデ" = "3人で作った騎馬の上に騎手を乗せて、帽子を奪い合う競技だよね。"
"10016080-86-ハスミ" = "そうです。騎馬戦の勝敗は、いかに素早く相手の帽子を奪えるかで決します。"
"10016080-87-ハスミ" = "そう……つまり、背の高さが有利に働くのです。#n相手の騎馬より高ければ、上から一方的に帽子を奪えますから。"
"10016080-88-ハスミ" = "気にされていた背の高さですが、むしろ騎馬戦では長所足り得るのです！"
"10016080-89-ツクヨ" = "そ、そうなんですね……！"
"10016080-90-チセ" = "でもツクヨちゃんが騎馬になったら、私たちと身長が合わないよ。"
"10016080-91-チセ" = "う～ん、踏み台が必要だねぇ。"
"10016080-92-チセ" = "……騎馬の左右を支える生徒が、必ずしも同じ身長である必要はありません。"
"10016080-93-チセ" = "なぜなら、身長が低い生徒の足元に踏み台を置くことで、高さを均等にできるからです。"
"10016080-94-イズナ" = "踏み台を……？#nでもそれだと動けないですよ？"
"10016080-95-ハスミ" = "騎馬戦のルールに、必ずしも動かなければならないというものはありません。#nじっとしていると狙われやすいので動いているだけです。"
"10016080-96-ハスミ" = "そう……高さのある踏み台を用意することで、よほどの高さでもない限りこちらを攻撃することできませんから――"
"10016080-97-ハスミ" = "最強の砦が完成するのです！"
"10016080-98-ツクヨ" = "な、なるほど……いっそのこと城塞を築いてしまえばいいんですね！"
"10016080-99-ハスミ" = "この短時間でこんなにも見事な作戦を立てるなんて……"
"10016080-100-イズナ" = "まるで『彷徨う孤独な忍者77人組』108話で黒い耳をつんと立たせながら大軍を阻止していた策士・甲斐兵衛の姿、そのものですね！"
"10016080-101-イズナ" = "ありがとうございます！甲斐兵衛殿！"
"10016080-102-ハスミ" = "私はハスミですが……。"
"10016080-103-イズナ" = "失礼しました、ハスミ殿！#nイズナたちに知恵をお貸しください！"
"10016080-104-ハスミ" = "ち、知恵ですか？"
"10016080-105-イズナ" = "部長が倒れてしまってからというもの、私たちは主を失った浪人のように当てもなくさまよっていました。"
"10016080-106-ハスミ" = "そんなところに現れたのがハスミ殿なんです！#nどうかお願いします！"
"10016080-107-ツクヨ" = "うんうん！トリニティの素敵なレディーが助けてくれたら、私たち勝てそうだね！"
"10016080-108-チセ" = "暑い午後～、黒翼の少女、何かの縁……。"
"10016080-109-ツクヨ" = "わ、私からも、お願いします……！"
"10016080-110-ハスミ" = "……仕方ありませんね。"
"10016080-111-ハスミ" = "どうせ休んでいたところですし、百鬼夜行が勝てばトリニティにとってもプラスですから……"
"10016080-112-ハスミ" = "ここは一つ、手を貸すとしましょう。"
