[translation]
"10016035-1" = "（観戦のため、席に座っていたところ……）"
"10016035-2-ノア" = "あ、先生。ここにいらっしゃったのですね。"
"10016035-3-ノア" = "ふふ、昨日は夜遅くまでお疲れ様でした。#n少しは眠れましたか？"
"10016035-4" = "[s1] \"うん、みんなのおかげでちゃんと休めたよ。\"\n[s2] \"ノアも休めた？\""
"10016035-5-ノア" = "はい、私も開会式が始まる前に少し仮眠をとりました。"
"10016035-6-ノア" = "はい、私も開会式が始まる前に少し仮眠をとりました。"
"10016035-7-ノア" = "その間に、知らないところで何かあったような気もしますが……"
"10016035-8-ノア" = "皆さん……楽しそうで良かった。"
"10016035-9" = "[s] \"頑張って準備した甲斐があったね。\""
"10016035-10-ノア" = "はい、本当に。#nさて、次の種目は……"
"10016035-11-ノア" = "あら、「借り物競争」ですね。"
"10016035-12-ノア" = "そろそろ出かける準備をしなければ……。"
"10016035-13" = "[s] \"「借り物競争」に出るの？\""
"10016035-14-ノア" = "はい、選手ではなく審判ですが……。"
"10016035-15-ノア" = "選手は、ゲーム開発部の[ruby=はなおか]花岡[/ruby]さんが出る予定だったのですが……ユウカちゃん本人の強い要望で、彼女が出ることになりました。"
"10016035-16-ノア" = "ふふ……「借り物競争」は開催毎に伝説を生む人気の競技なんですよ。"
"10016035-17-ノア" = "実行委員でさえも何を借りてくる事になるかは分からないハラハラ感……#n「好きな人」と書かれたメモが毎回必ず入っているのも見どころです。"
"10016035-18-ノア" = "……果たして、ユウカちゃんが何を借りてくる事になるか、楽しみですね。"
"10016035-19-ノア" = "それでは、先生。#n引き続き晄輪大祭を楽しんでくださいね。"
"10016035-20-シノン" = "クロノスチャンネルをご視聴の皆さん、お待たせしました！"
"10016035-21-シノン" = "さあ、ついに晄輪大祭名物「借り物競争」が幕を開けます！"
"10016035-22-シノン" = "観客席も盛り上がっていますねー！"
"10016035-23-シノン" = "ルールは単純明快！トラック上にある箱からメモを取り出し、そこに書かれたキーワードに合致するものと共にゴールするだけ！"
"10016035-24-シノン" = "ただし、キーワードは審判に見せるまで秘匿しなければならないそうです！"
"10016035-25-シノン" = "さあ、選手の入場が開始しました！"
"10016035-26-ユウカ" = "（借り物競争をユズが交代してくれてよかった……）"
"10016035-27-ユウカ" = "（ユズ、知らない人に話しかけるのは苦手だから……）"
"10016035-28-ユウカ" = "（ミレニアムの総合優勝のためにも……この試合、絶対に負けられない！）"
"10016035-29-サキ" = "（審判の生徒……たしか、前に見たセミナーの役員だよな？）"
"10016035-30-サキ" = "（一つの試合に主催校の生徒会役員が選手と審判で出場するとは……#n　やはり怪しいな、ミレニアム……）"
"10016035-31-サキ" = "（まぁいい。何を画策していようが、フィジカルで優勝すればいいだけだ！）"
"10016035-32-アコ" = "（前回の大会結果の分析でメモのパターンはすべて把握しました）"
"10016035-33-アコ" = "（この試合も勝って、ゲヘナの総合優勝を確定させてみせます！）"
"10016035-34-シノン" = "さあ、それでは皆さん、位置について……"
"10016035-35-シノン" = "よーい、ドン！"
"10016035-36-シノン" = "さあ始まりました「借り物競争」！#n各選手、一斉に箱に向かっていきます！"
"10016035-37-シノン" = "最初に到達したのは……"
"10016035-38-シノン" = "SRT特殊学園の[ruby=そらい]空井[/ruby]サキ選手！"
"10016035-39-シノン" = "SRT特殊学園は皆様御存知の通り廃校になった学園ですが、#nシャーレの協力によって大運動会に限り学園としての参加が許されています。"
"10016035-40-シノン" = "果たしてサキ選手はこの試合でSRT特殊学園の初勝利を手に入れることができるのでしょうか？"
"10016035-41-サキ" = "さて、一体なにが出るのやら……"
"10016035-42-サキ" = "……4.2インチ白リン弾？#nこんなもの、いったい競技場のどこで手に入れるんだ！？"
"10016035-43-サキ" = "ブ～！空井サキ選手、失格です！"
"10016035-44-サキ" = "し、失格だと！？"
"10016035-45-ノア" = "試合開始前に申し上げた通り、メモの内容を周囲に知られたら失格です。"
"10016035-46-ノア" = "メモの中身が分かってしまったら面白くな――"
"10016035-47-ノア" = "こほん。いえ、周囲の手助けが容易になってしまいますから。"
"10016035-48-ノア" = "残念ですが……空井サキ選手は失格。SRT特殊学園はランキング外となります。"
"10016035-49-モエ" = "サキ、あんた何してるのよ！"
"10016035-50-モエ" = "やっぱり4人しかいない私たちじゃ……最初から無理だったんだ……"
"10016035-51-ミヤコ" = "お疲れ様でした、サキ。"
"10016035-52-ミヤコ" = "まだ試合はありますから大丈夫です。#n次で1位を狙いましょう。"
"10016035-53-サキ" = "うっ……"
"10016035-54-サキ" = "だ、だが、失格にならなくても1位は難しかったんじゃないのか？"
"10016035-55-サキ" = "白リン弾を持っている人なんて競技場に――"
"10016035-56-モエ" = "私、持ってるよ？"
"10016035-57-サキ" = "なんで持ってるんだ……？"
"10016035-58-シノン" = "サキ選手の失格によって状況は一気に読めなくなってまいりました！"
"10016035-59-シノン" = "続いて箱に近づいたのは――ミレニアムの[ruby=はやせ]早瀬[/ruby]ユウカ選手！"
"10016035-60-ユウカ" = "はぁ、はぁ……えっと、お題は……"
"10016035-61-ユウカ" = "うーん……この人、じゃないし……"
"10016035-62-ユウカ" = "こっちでもないし……#nえーっと……"
"10016035-63-ユウカ" = "あっ、いた！"
"10016035-64-ユウカ" = "先生、ちょっと一緒に来てください！"
"10016035-65" = "[s] \"わ、私！？\""
"10016035-66-ユウカ" = "ええ！#n時間がありません、急ぎますよ！"
"10016035-67-シノン" = "ユウカ選手、メモを確認するやいなや、シャーレの先生を連れて疾走！"
"10016035-68-シノン" = "現在の順位は1位！果たしてメモの中身は一体なんだったのでしょうか！？#n何故シャーレの先生を選んだのか！"
"10016035-69-シノン" = "ユウカ選手独走を続け……そのままゴールラインを通過！暫定1位です！"
"10016035-70-シノン" = "ですが、まだ審判のお題確認が残っております！"
"10016035-71-ユウカ" = "へぇ……"
"10016035-72-ノア" = "ユウカちゃんは、[USERNAME]先生の事をそう思っていたんですね……ふふっ。"
"10016035-73-ユウカ" = "な、なによ！？お題は主観的なものじゃない。#n焦らさないで早く判定して！"
"10016035-74-ノア" = "ふふっ……はい、お題内容は問題ありませんよ。#n早瀬ユウカ選手、1位です。"
"10016035-75-ノア" = "やった！"
"10016035-76-観客A" = "たしか……借りてくるものの中に「好きな人」ってあったよね？"
"10016035-77-観客B" = "毎度、好きな人を連れて行ってカップル成立する選手が必ず一組は出るよね。"
"10016035-78-観客A" = "他の選手のお題は「好きな人」じゃなさそうだし……"
"10016035-79-観客B" = "ユウカさん、メモを見るやいなや先生のところに真っ直ぐ向かっていったよね……#nま、まさか……"
"10016035-80-ユウカ" = "ちょ、ちょっと待って！なんか誤解されてない！？"
"10016035-81-ユウカ" = "私のお題は「好きな人」じゃなくて――"
"10016035-82-ユウカ" = "あっ、ダメですよユウカちゃん。お題を言うのはルール違反です。"
"10016035-83-ノア" = "選手のお題を推測するところまでが「借り物競争」の観戦ポイントですからね。"
"10016035-84-ユウカ" = "ゴールした後は言ってもいいんじゃなかったっけ？"
"10016035-85-ユウカ" = "それに、[ruby=身内]ミレニアム生[/ruby]への誤解くらい解いたって……"
"10016035-86-ノア" = "ダメです。「[ruby=こうりんたいさい]晄輪大祭[/ruby]」に例外はありません。"
"10016035-87-ノア" = "結果的にユウカちゃんが恥ずかしい思いをしたとしても、ダメなものはダメです。"
"10016035-88-ユウカ" = "だから好きな人じゃないって何回言えば――"
"10016035-89" = "[s] \"好きな人じゃなかったんだ……。\""
"10016035-90-ユウカ" = "えっえぇ！？"
"10016035-91-ユウカ" = "い、いえ！その……先生のことが好きじゃないという意味ではなくて……"
"10016035-92-ユウカ" = "あ……そ、そうじゃなくて！"
"10016035-93-観客A" = "……今の、聞いた？"
"10016035-94-観客A" = "すごい瞬間……見ちゃったね……"
"10016035-95-観客B" = "ミレニアム生って大胆……。"
"10016035-96-ノア" = "だから誤解だってば！"
"10016035-97" = "（その後、しどろもどろのユウカを宥めるのに苦労した）"
