[translation]
"10036140-1" = "スクワッドがゲームを楽しむ方法（２）"
"10036140-2-ゲームコーナーのスタッフ" = "おぉ！#n初級クリアおめでとうございます！"
"10036140-3-サオリ" = "ふっ。"
"10036140-4-サオリ" = "あの程度、訓練にすらならない。"
"10036140-5-サオリ" = "みんな、次も行けるか？"
"10036140-6-ミサキ" = "問題ないよ。"
"10036140-7-アツコ" = "みんなでゲームするの、楽しいね。"
"10036140-8-ヒヨリ" = "え、えへへ……「BiBi」の最新号に一歩近づきました……！"
"10036140-9-ヒヨリ" = "もしかすると、本当に景品を手に入れられるかもしれません……！"
"10036140-10-ミサキ" = "たまたまかもしれないけど。"
"10036140-11-ヒヨリ" = "あ、あぁ……やっぱり私たちには……。"
"10036140-12-ミサキ" = "いや、その……冗談だよ。"
"10036140-13-アツコ" = "ミサキが……。"
"10036140-14-サオリ" = "冗談を……？"
"10036140-15-ヒヨリ" = "み、ミサキさんのユーモアセンスって……。"
"10036140-16-ミサキ" = "う、うるさい！#nまだ次のゲームがあるんでしょ、早く。"
"10036140-17-ゲームコーナーのスタッフ" = "それでは準備ができたようなので、中級を開始します！"
