[translation]
"10036080-1" = "第8話;伝説のスケバン"
"10036080-2-ニヤニヤ教授" = "かつて、ヴァルキューレ警察学校にとって悪夢のような事件がありました。"
"10036080-3-ニヤニヤ教授" = "12台の警備車両、2台の戦車が全損し、多数の怪我人を出した大惨事。#nその甚大な被害は、たった一人による犯行だったのです。"
"10036080-4-ニヤニヤ教授" = "あの身体能力は他の追随を許しません。"
"10036080-5-ニヤニヤ教授" = "悪名高き「七囚人」の一人であり、「伝説のスケバン」――"
"10036080-6-アケミ" = "うふふっ。美しい夜ですわね、皆さん。"
"10036080-7-アケミ" = "すぅぅぅ、はぁ……やっぱり、シャバの空気は格別です。"
"10036080-8-ヘルメット団員B" = "[ruby=くりはま]栗浜[/ruby]アケミ……！"
"10036080-9-アケミ" = "覚えていただけていたようで、感激ですわ。"
"10036080-10-アケミ" = "あらためて、ご挨拶いたしましょう。"
"10036080-11" = "[s] （彼女が伝説のスケバン……？）"
"10036080-12-アケミ" = "私の名は、栗浜アケミ。"
"10036080-13-アケミ" = "こう見えて、スケバンをしておりますの。"
"10036080-14-アケミ" = "皆さんにお会いできる日を、いまかいまかと待ち焦がれておりましたのよ？"
"10036080-15-アケミ" = "……私のこと、覚えていらっしゃるでしょう？"
"10036080-16-ヘルメット団員A" = "……！"
"10036080-17-アケミ" = "忘れられては、困りますのよ。"
"10036080-18-アケミ" = "うふふっ。#nだって、皆さんの密告によって私は捕まったんですもの。"
"10036080-19-アケミ" = "矯正局で過ごした時間が、懐かしいですわね……。"
"10036080-20-アケミ" = "どうやってアンタたちに復讐しようかと考えていた毎日が！"
"10036080-21-アケミ" = "では――お覚悟を。"
"10036080-22-ヘルメット団員A" = "か、覚悟……！？"
"10036080-23-アケミ" = "ええ……今から、私にブッ殺される覚悟です。"
"10036080-24-ヘルメット団員A" = "ひ、ひいっ……！"
"10036080-25-ヘルメット団員A" = "やっぱり、あのスケバンに奇襲を指示していたのは、お前だったんだな！"
"10036080-26-アケミ" = "はい……？"
"10036080-27-スケバンA" = "ね、姐様ぁぁぁっ！！！！"
"10036080-28-アケミ" = "あらまあ、皆さんどうしてこちらに？"
"10036080-29-スケバンA" = "もちろん、姐様の仇を討つためですよ！"
"10036080-30-アケミ" = "そんな、私はもうスケバンではありませんわ。#n矯正局から脱獄してきた囚人に過ぎませんのよ。"
"10036080-31-アケミ" = "そんなこと言わないでください！"
"10036080-32-アケミ" = "ウチらを守るために、捕まったようなものじゃないですか！"
"10036080-33-スケバンA" = "ヴァルキューレめ……よくも姐様を！"
"10036080-34-スケバンA" = "皆さん、そこまで私のことを想っていてくださったのですね……。"
"10036080-35-スケバンA" = "感動いたしましたわ……！"
"10036080-36-スケバンA" = "うふふ。やはり、あの教授に頼んでおいて正解でした。"
"10036080-37-スケバンA" = "姐様も、ニヤニヤ教授に依頼を！？"
"10036080-38-スケバンA" = "まさか、あいつが言ってた「彼女」が、姐様だったとは……！"
"10036080-39" = "[ns] （ニヤニヤ教授、どこかで聞いた覚えがあるような……）"
"10036080-40-ヘルメット団員A" = "スキだらけだな！"
"10036080-41-ヘルメット団員B" = "さっきまで矯正局に捕まってたんなら、腕が鈍ってるに違いねぇ！"
"10036080-42-ヘルメット団C" = "ここで倒しちまえば、ヘルメット団の株はうなぎ登りだぜ！"
"10036080-43-アケミ" = "うふふ、良いですわね。"
"10036080-44-アケミ" = "ですが、この戦いは私が一人で参りましょう。"
"10036080-45-アケミ" = "ここまで頑張ってくださったことには、感謝いたします。"
"10036080-46-アケミ" = "うふふ、ここからは私とエリザベスでお相手するといたしましょう！"
"10036080-47-アケミ" = "さぁ、行きますわよ！"
"10036080-48-ヘルメット団員A" = "うわあぁぁっ！"
"10036080-49-ヘルメット団員A" = "お、お前たち、逃げるんじゃねぇ！"
"10036080-50-ヘルメット団員A" = "――ぎゃあぁぁぁっ！#nやっぱ無理だ逃げろ！"
"10036080-51-ミサキ" = "姫、危なっ――！"
"10036080-52-ミサキ" = "くっ……"
"10036080-53-アツコ" = "み、ミサキさん！"
"10036080-54-サオリ" = "ミサキ！"
"10036080-55-サオリ" = "みんなが危ない……！"
"10036080-56-サオリ" = "先生……！"
"10036080-57" = "[s] \"分かった！\""
"10036080-58-サオリ" = "そこまでだ！"
"10036080-59-アケミ" = "はい？"
"10036080-60-アケミ" = "なっ、私のエリザベスが……！"
"10036080-61" = "[s] （あの武器、そんな名前だったんだ……）"
"10036080-62-アケミ" = "許せません……！"
"10036080-63-サオリ" = "大人しく立ち去れ。"
"10036080-64-サオリ" = "そうすれば、見逃してやろう。"
"10036080-65-アケミ" = "どちら様でしょう？"
"10036080-66-アケミ" = "私に指図するだなんて……。"
"10036080-67-アケミ" = "この程度で、私が引き下がるとでも！？"
"10036080-68-アケミ" = "立ちふさがる者は……。"
"10036080-69-アケミ" = "一人残らず、徹底的に教育して差し上げましょう！"
