[translation]
"10036130-1" = "スクワッドがゲームを楽しむ方法（１）"
"10036130-2-ゲームコーナーのスタッフ" = "お待たせしました！"
"10036130-3-ゲームコーナーのスタッフ" = "「全弾発射ゲーム」へようこそ！"
"10036130-4-アツコ" = "これは、どんなゲーム？"
"10036130-5-ゲームコーナーのスタッフ" = "はい、ご説明しましょう！"
"10036130-6-ゲームコーナーのスタッフ" = "ルールは簡単！#n流れる標的が、景品に近づかないよう阻止するだけです！"
"10036130-7-ヒヨリ" = "さ、サオリ姉さん！#nあ、アレを見てみてください……！"
"10036130-8-ヒヨリ" = "なんと、景品に最新号の「BiBi」がありますよ！？"
"10036130-9-ヒヨリ" = "他にもフードコートのお食事券や、プリント写真の利用券などもあります！"
"10036130-10-ゲームコーナーのスタッフ" = "ちなみに今日は、まだ誰も景品を手に入れられていません！"
"10036130-11-ヒヨリ" = "そ、そんな……！"
"10036130-12-サオリ" = "……そこまで難しいゲームなのか？"
"10036130-13-サオリ" = "いや、変な質問をしたな。"
"10036130-14-サオリ" = "簡単なことなど、どこにも存在しない。"
"10036130-15-サオリ" = "だが、それでも諦めるわけには……。"
"10036130-16-サオリ" = "鉄くずの収集、リサイクル品の回収……#n今まで数多くの試練を乗り越えてきた。"
"10036130-17-サオリ" = "それに加え……。"
"10036130-18-サオリ" = "今はみんなが一緒だ！#nもう何も怖くない！"
"10036130-19-アツコ" = "うん！"
"10036130-20-ヒヨリ" = "は、はい！#n今までの[ruby=かんなんしんく]艱難辛苦[/ruby]に比べたら、これくらい……！"
"10036130-21-ミサキ" = "……ただゲームに挑戦するだけなのに。"
"10036130-22-ゲームコーナーのスタッフ" = "では、初級から開始です！"
"10036130-23-サオリ" = "行くぞ、みんな！"
"10036130-24-ミサキ" = "は、はい！"
"10036130-25-ミサキ" = "まぁ、やってみようか……。"
"10036130-26-ミサキ" = "（ふふ。サッちゃん、楽しそう……）"
