[translation]
"10036045-1-屋台の調理師" = "ぐはっ！"
"10036045-2-屋台の調理師" = "こ、降参する！"
"10036045-3-サオリ" = "呆気なかったな。"
"10036045-4-サオリ" = "メニューを見せてもらおうか。"
"10036045-5-屋台の調理師" = "は、はい！#nすべて無料でお持ちください！"
"10036045-6-サオリ" = "いや、そうじゃない。"
"10036045-7-屋台の従業員" = "これは……？"
"10036045-8-サオリ" = "お代は払うから、さっきの子たちに焼きそば3つ、焼きとうもろこしとかき氷とアイスクリームを1つ届けてくれ。"
"10036045-9-サオリ" = "私からだということは伏せるように。"
"10036045-10-屋台の従業員" = "そ、それだけで良いのですか……？"
"10036045-11-屋台の従業員" = "代金を頂けるとは……。"
"10036045-12-サオリ" = "私は対価を支払っただけだ。"
"10036045-13-屋台の従業員" = "……！"
"10036045-14-屋台の従業員" = "す、すぐに用意します！"
"10036045-15" = "[ns9] \"サオリ、お金なら私が出すよ。\"\n[ns10] \"ここは私のカードで。\""
"10036045-16-サオリ" = "いや、大丈夫だ。"
"10036045-17-サオリ" = "ただでさえ、先生にはいつもお世話になっているからな。"
"10036045-18-サオリ" = "それに、ここは私が奢りたい。"
"10036045-19" = "[s] （サオリ……）"
"10036045-20-サオリ" = "よし、みんなの様子を見に行こう。"
"10036045-21-屋台の従業員" = "お、お待たせしました！"
"10036045-22-屋台の従業員" = "こちら、焼きそば3つに焼きとうもろこし、かき氷、アイスクリームです！"
"10036045-23-アツコ" = "……私たち、焼きそば1つしか頼んでない。"
"10036045-24-ミサキ" = "まさか、今度は押し売りするつもり？"
"10036045-25-ヒヨリ" = "ひいっ、まさか本当に……！"
"10036045-26-屋台の従業員" = "い、いえ！#nそんなつもりはありません！"
"10036045-27-屋台の従業員" = "えっと、そうです！#n皆さんは1万人目のお客様だったんです！"
"10036045-28-屋台の従業員" = "代金も不要ですので！"
"10036045-29-屋台の従業員" = "……おい、お前たちも合わせるんだぞ。"
"10036045-30-屋台の従業員" = "お、おめでとうございます……！"
"10036045-31-ミサキ" = "怪しい……何を企んでるの？"
"10036045-32-ヒヨリ" = "うわぁぁぁぁあああああん！ありがとうございますぅぅぅぅ！"
"10036045-33-ヒヨリ" = "いつもつらいことばっかだったのに！#nまさかこんな幸せが訪れるなんてぇぇぇ！"
"10036045-34-アツコ" = "よく分からないけど、良かった。"
"10036045-35-アツコ" = "冷めないうちに食べよう。"
"10036045-36-ヒヨリ" = "はい……！これが、焼きそば……！"
"10036045-37-ヒヨリ" = "うぅぅ……美味ひいへふぅ！"
"10036045-38-ミサキ" = "……悪くないね。"
"10036045-39-ミサキ" = "こんなに幸せで良いんでしょうか……！#nやっぱり、このあと絶対何かされるんですよね……！"
"10036045-40-サオリ" = "……。"
"10036045-41" = "[s] \"良かったね、サオリ。\""
"10036045-42-サオリ" = "自分で稼いだお金で、#nみんなに何かを買ったのは初めてだ。"
"10036045-43-サオリ" = "……ふっ、こんなにも嬉しいものなんだな。"
"10036045-44" = "[s] \"私たちもそろそろお昼にしようか。\""
"10036045-45-サオリ" = "焼きそば、だと？"
"10036045-46-サオリ" = "いつの間に注文を……？"
"10036045-47" = "[s] \"ここは私が奢りたかったんだ。\""
"10036045-48-サオリ" = "……そうか。"
"10036045-49-サオリ" = "では、ありがたく頂こう。"
