[translation]
"1600002-1" = "送信先間違い"
"1600002-2-ハルカ" = "あっ、来ていただいてありがとうございます。実は、ここに爆弾を設置したんですが……"
"1600002-3-ハルカ" = "ちょっと少ない気もしていて……これぐらいでいいかどうか確認を……"
"1600002-4-ハルカ" = "……？"
"1600002-5" = "[s] \"……？\""
"1600002-6-ハルカ" = "……先生？"
"1600002-7" = "[s] \"や、ハルカ。\""
"1600002-8-ハルカ" = "……？"
"1600002-9-ハルカ" = "せ、せせせせ、先生！？どうして先生がここに……！？"
"1600002-10-ハルカ" = "え、はい？よ、よよ、呼びました？わ、わ、私が、先生を！？"
"1600002-11-ハルカ" = "メッセージ……？"
"1600002-12-ハルカ" = "……。"
"1600002-13-ハルカ" = "……。"
"1600002-14-ハルカ" = "……！！！す、すすすすすみません！た、たた、大変失礼なことを……！"
"1600002-15-ハルカ" = "わ、私、その、これは……！先生に送ろうとしたのではなく……！"
"1600002-16-ハルカ" = "間違えて……！間違えて先生に送ってしまっていました……！ど、どうしましょう……！"
"1600002-17-ハルカ" = "私のせいで、私なんかのために先生がこんなところまで……！"
"1600002-18-ハルカ" = "すみません……ほ、本当にすみません……。"
"1600002-19-ハルカ" = "すみませんすみませんすみませんすみませんすみませんすみませんすみません……"
"1600002-20-ハルカ" = "……？"
"1600002-21-ハルカ" = "え、だ、大丈夫、ですか……？それより何をしてたのかって……？"
"1600002-22-ハルカ" = "そ、それは、えっと……。"
"1600002-23-ハルカ" = "……。"
"1600002-24-ハルカ" = "ば、爆弾……。"
"1600002-25-ハルカ" = "爆弾を、設置していました……。"
"1600002-26" = "[s] \"……爆弾？\""
"1600002-27-ハルカ" = "はい、えっと……便利屋への依頼で……明日、どうしても遅刻させなきゃいけない人がいるみたいでして……。"
"1600002-28-ハルカ" = "その人がここを通るみたいなので、通る時に爆破させれば……。"
"1600002-29-ハルカ" = "そしたら……遅刻、させられますから……永遠に……。"
"1600002-30-ハルカ" = "……え？あ、いえ、特に爆弾を設置してと誰かから指示されたわけでは……。"
"1600002-31-ハルカ" = "こ、これはただ……私が勝手に……。"
"1600002-32-ハルカ" = "そ、それできちんとできたかどうか不安になってしまって……！確認してもらおうとメッセージを送ったのですが、それを間違えて先生に……。"
"1600002-33-ハルカ" = "こんなところまで呼び出してしまってすみません、本当にすみません……。"
"1600002-34-ハルカ" = "……え、これで大丈夫、ですか？"
"1600002-35-ハルカ" = "あ、連絡したのが大丈夫ということですか……はい、すみません……。"
"1600002-36-ハルカ" = "……え、爆弾は全部回収しよう……？"
"1600002-37-ハルカ" = "は、はい、それは全然……！先生がそうおっしゃるなら……。"
"1600002-38" = "（その後、ハルカが設置した爆弾を回収していったら、その数は二桁に上った）"
"1600002-39-ハルカ" = "終わりました……えっと、もしかして私、余計なことをしてしまったのでしょうか……？"
"1600002-40-ハルカ" = "……え、他にも設置した場所？は、はい、確実に消すためにあちこちに……。"
"1600002-41-ハルカ" = "け、消さなくてもいいんじゃないか……？それと残りの爆弾がどこにあるか、ですか……？"
"1600002-42-ハルカ" = "えっと……ビルの地下と……ジム……それから公園……。"
"1600002-43-ハルカ" = "は、はい？全部解体ですか……？はい、分かりました……。"
"1600002-44-ハルカ" = "え、えっ！？いえいえ！私一人で大丈夫です！わざわざ私なんかに先生を付き合わせてしまうわけには……！"
"1600002-45" = "[s1] \"私がハルカと一緒に行きたいから。\"\n[s2] \"私と一緒に行くのは嫌？\""
"1600002-46-ハルカ" = "……！？"
"1600002-47-ハルカ" = "ど、どうして……私なんかと……。"
"1600002-48-ハルカ" = "い、いえ！決して嫌なんてことはありません……！"
"1600002-49-ハルカ" = "……で、でも、本当に……？ぜひ一緒に行きたい……えぇ……？"
"1600002-50-ハルカ" = "わ、分かりました……先生がそう仰るのでしたら……。"
"1600002-51-ハルカ" = "そ、それでは出発します……。"
"1600002-52-ハルカ" = "……ここ……柱の裏に……はい、OKです……。"
"1600002-53" = "[s] \"お疲れ様。\""
"1600002-54-ハルカ" = "お、お疲れ様だなんて……そんな、勿体ないお言葉……。"
"1600002-55-ハルカ" = "……うぅ、ありがとうございます。"
"1600002-56" = "（ハルカはその後も早歩きで、逃げるように歩いていく）"
"1600002-57-ハルカ" = "ここも……。"
"1600002-58-ハルカ" = "……ちょっともったいないです……ここで爆発させたら、綺麗に消せたのに……。"
"1600002-59-ハルカ" = "あ、な、なんでもありません。ただの独り言です……。"
"1600002-60" = "[s] \"まだあるんだよね、行こっか。\""
"1600002-61-ハルカ" = "は、はい……。"
"1600002-62-ハルカ" = "これで……全部……撤去しました……。"
"1600002-63-ハルカ" = "……せ、先生、あの……もしかして私……何か、先生にとって困ることをしてしまったんでしょうか……？"
"1600002-64-ハルカ" = "私のせいで……こんな時間からご迷惑をかけて……私なんかに付き合ってくれて……。"
"1600002-65-ハルカ" = "す……すみません……いつも……迷惑ばかり……。"
"1600002-66-ハルカ" = "こうすれば、みんな喜んでくれるかと思ったんですが……。"
"1600002-67" = "[s3] \"ううん、面白かったよ。\"\n[s4] \"珍しく深夜のお散歩ができて楽しかった。\""
"1600002-68-ハルカ" = "……え、そ、そんな……。"
"1600002-69-ハルカ" = "……え、そ、そんな……。"
"1600002-70-ハルカ" = "ど、どうしてそんな優しい言葉を……私なんかに……。"
"1600002-71-ハルカ" = "え……もう少し肩の力を抜いて……ですか……？"
"1600002-72-ハルカ" = "そんなに畏まらなくても大丈夫……？"
"1600002-73-ハルカ" = "そ、そんな……！そんなわけっ、わ、私はだって……！"
"1600002-74-ハルカ" = "い、いえ！決して！決して先生のお話が間違ってるなんてことが言いたいのではなく、その、これは、これは、えっと……！"
"1600002-75-ハルカ" = "そ、それが、だから、そんな……そんなこと……！"
"1600002-76-ハルカ" = "そんなことを言われたのは、初めてで……！"
"1600002-77-ハルカ" = "……。"
"1600002-78-ハルカ" = "……えへへ……。"
"1600002-79-ハルカ" = "ありがとうございます……先生は……本当に良い方ですね……。"
"1600002-80-ハルカ" = "私なんかとこうやってお話してくれて……付き合ってくれて、アドバイスもしてくれて……。"
"1600002-81-ハルカ" = "……ありがとうございます……本当に……。"
"1600002-82-ハルカ" = "先生……先生のためなら、私……全部……。"
"1600002-83-ハルカ" = "全部……。"
"1600002-84-ハルカ" = "先生のために……目障りなやつらを全部、排除できそうです……。"
"1600002-85" = "[s] \"……！？\""
"1600002-86-ハルカ" = "へへ……ふふ、ふふふ……。"
"1600002-87" = "（ハルカはその後も何度も腰を90度に曲げて謝ったりお礼を言ったりしてから、ちょっと変わった笑い方のままどこかに行ってしまった）"
