[translation]
"1010602-1" = "努力の成果"
"1010602-2" = "シャーレ・休憩室"
"1010602-3" = "（休憩室の掃除をしていると……）"
"1010602-4-？？？" = "……ふふっ。"
"1010602-5" = "[ns1] \"……サクラコさん？\"\n[ns2] \"予想はしてたけど……。\""
"1010602-6-サクラコ" = "やはり、先生は驚かないのですね。"
"1010602-7-サクラコ" = "……これが、私の成果です。"
"1010602-8-サクラコ" = "皆様とお近づきになれるよう、積み上げてきた努力が……。"
"1010602-9-サクラコ" = "ようやく実を結び――"
"1010602-10-サクラコ" = "……何だか見覚えがある、と？"
"1010602-11-サクラコ" = "それは、どういった意味で……。"
"1010602-12" = "[ns3] （あの話をするのはやめておこう……）\n[ns4] \"な、何でもないよ！\""
"1010602-13-サクラコ" = "そ、そうですか……？#nどことなく、気を遣われたような気が……。"
"1010602-14-サクラコ" = "とにかく、先生を訪ねたのは努力の成果をお話しようと思ったからです。"
"1010602-15-サクラコ" = "今までは助けを求めるばかりでしたが……。"
"1010602-16-サクラコ" = "今回は違います。#n……これで、ようやく私は自信を持って皆様を引っ張っていけるでしょう。"
"1010602-17-サクラコ" = "……ええ、リーダーとして一歩前進したのです。"
"1010602-18-サクラコ" = "このアイドルのれいそ……。"
"1010602-19-サクラコ" = "……衣装で！"
"1010602-20" = "[s5] \"れいそ……？\"\n[s6] \"今、礼装って言いかけてなかった？\""
"1010602-21-サクラコ" = "……気のせいです。"
"1010602-22-サクラコ" = "こほん……。"
"1010602-23-サクラコ" = "この衣装を着るようになってから、皆様の反応が変わりました。"
"1010602-24-サクラコ" = "避けられている感じはなく、#nむしろ声をかけていただく機会が増えたのです。"
"1010602-25-サクラコ" = "どんなに頑張っても叶わなかったというのに、#nこんなにもあっさり手に入るとは……。"
"1010602-26-サクラコ" = "そこで気がついたのです。#n本質も大事ではありますが……。"
"1010602-27-サクラコ" = "……時にはイメージも重要なのだと！"
"1010602-28" = "[s7] \"……おお。\"\n[s8] \"たしかに大事だよね。気づいてくれて嬉しいよ！\""
"1010602-29-サクラコ" = "ええ、そうなのです。"
"1010602-30-サクラコ" = "何日か試しにアイドルのれいそ……いえ、衣装で過ごしてみたところ、#n思った以上に効果がありました。"
"1010602-31-サクラコ" = "この衣装は繊細ですし、#nどこかに引っ掛けたりしないか気にしながら過ごさなくてはいけませんが……。"
"1010602-32-サクラコ" = "皆様と距離が近づいたのですから、贅沢は言ってられません。"
"1010602-33-サクラコ" = "これからも、アイドルの格好で過ごそうと思っております。"
"1010602-34" = "[s9] \"うん。\"\n[s10] \"良かったね、サクラコ。\""
"1010602-35-サクラコ" = "これからも先生には、色々とご迷惑をおかけするかもしれませんが……。"
"1010602-36-サクラコ" = "以前からの悩みが解決して、ホッとしております。"
"1010602-37-サクラコ" = "あらためて、お礼を申し上げます。"
"1010602-38-サクラコ" = "……ありがとうございました、先生。"
"1010602-39" = "[s11] \"またいつでも相談してね。\"\n[s12] \"明るい報告が聞けて、私も嬉しいよ。\""
"1010602-40-サクラコ" = "どうやら、しばらく忙しくなりそうです。"
"1010602-41-サクラコ" = "これから皆様の分の衣装まで作成するのですから。"
"1010602-42" = "[ns13] \"……えっ？\"\n[ns14] \"……全員の衣装を用意するの？\""
"1010602-43" = "[ns15] \"まさか……。\"\n[ns16] \"シスターフッドが全員アイドルに！？\""
"1010602-44-サクラコ" = "……ええ。"
"1010602-45-サクラコ" = "そのつもりですが、なぜそんなに驚いて……？"
"1010602-46-サクラコ" = "皆様のお話を聞く立場として、#n少しでも距離感は近いほうが良いでしょうし……。"
"1010602-47-サクラコ" = "せっかくですから、全員で取り入れようかと思ったのです。"
"1010602-48-サクラコ" = "――！？"
"1010602-49-サクラコ" = "どうしていきなり手を……！？"
"1010602-50-サクラコ" = "せ、先生……！"
"1010602-51" = "（サクラコを連れて全力でシスターフッドへ向かうと……）"
"1010602-52" = "（発注書を持って困っているシスターがいた）"
"1010602-53" = "（何とかサクラコを説得し、「シスターフッドアイドル化計画」を中止させた）"
