[translation]
"1601302-1" = "コハルの使命"
"1601302-2" = "（一人で余暇を満喫しようと思い、滝の音に耳を傾けていたところ……）"
"1601302-3" = "（どこからか、[ruby=せわ]忙[/ruby]しない足音が聞こえてきた）"
"1601302-4" = "[ns1] \"コハル……？\"\n[ns2] \"結構遅かったけど、迷ってたのかな……？\""
"1601302-5-？？？" = "やっと見つけた、先生！！"
"1601302-6-コハル" = "私が先生を探してた理由くらい分かるわよね？"
"1601302-7-コハル" = "こんな人気のない場所で何してたの？#n隠そうとしたって無駄よ！"
"1601302-8-コハル" = "……滝を眺めながら、ぼーっとしてた？"
"1601302-9-コハル" = "ふん！そんな話、一体誰が信じると思ってるの？"
"1601302-10-コハル" = "またいつもみたいに、変な妄想してたんじゃないの？"
"1601302-11-コハル" = "え？本当に違うの……？"
"1601302-12-コハル" = "大人には、孤独な時間が必要……？"
"1601302-13-コハル" = "夏だから、とか言われても……"
"1601302-14-コハル" = "……意味分かんないんだけど。"
"1601302-15-コハル" = "うーん、夏……無人島……"
"1601302-16-コハル" = "そういう、ものなの……かな。"
"1601302-17" = "[s3] \"時間も場所も違えば……当然、その意味も。\"\n[s4] \"コハルも、いつか分かると思うよ……きっとね。\""
"1601302-18-コハル" = "そんなはずないわよ……！"
"1601302-19-コハル" = "変なこと考えてない先生なんて、ありえないし……！"
"1601302-20-コハル" = "……私？"
"1601302-21-コハル" = "ここに来てから、何か変わったこと……？"
"1601302-22-コハル" = "私は先生を監視するために来たんだから。#n先生から目を離すわけにはいかないでしょ？"
"1601302-23-コハル" = "私が見てない間に、また変なことをするかもしれないし……"
"1601302-24-コハル" = "それをちゃんと監視するのが正義実現委員会としての使命なの！"
"1601302-25-コハル" = "うーん。でも、今日の先生は普段とちょっと違うような……"
"1601302-26-コハル" = "それなら、私は何のために無人島まで……"
"1601302-27" = "[s5] \"コハル……？\"\n[s6] \"難しく考える必要は無いんじゃない？\""
"1601302-28-コハル" = "でも、そんな簡単に……"
"1601302-29-コハル" = "……え？"
"1601302-30-コハル" = "夏だから、って……"
"1601302-31-コハル" = "なんでも夏のせいにすれば良いと思ってない？"
"1601302-32-コハル" = "そ、そうやって私を騙そうとしても無駄よ、先生！#n絶対に騙されないんだから！"
"1601302-33-コハル" = "まぁ……でも……"
"1601302-34-コハル" = "……うん。#nでも、今日は変なことしないって分かったから、それは信じてあげる。"
"1601302-35-コハル" = "……？"
"1601302-36-コハル" = "なら、もう帰るのかって？"
"1601302-37-コハル" = "ば、バカ言わないで！"
"1601302-38-コハル" = "というか……私がそばにいたら何か問題あるの？"
"1601302-39" = "[s7] \"そんな事は全くないけど……。\"\n[s8] \"もちろん、ずっとここにいても大丈夫だよ？\""
"1601302-40-コハル" = "な、なんか怪しい……帰ってほしそうな気がするもん。#n私が目を離したら、何をするか分からないし……"
"1601302-41-コハル" = "やっぱり、監視を続ける事にするわ。"
"1601302-42-コハル" = "もう、何言われても騙されないんだからね。"
"1601302-43-コハル" = "……別に、問題ないのよね？"
"1601302-44" = "[s9] \"私は構わないけど……。\"\n[s10] \"退屈かもしれないよ？\""
"1601302-45-コハル" = "誤魔化そうとしても無駄！"
"1601302-46" = "（そう言って、コハルは隣に座り、周囲をキョロキョロと見回し始めた）"
"1601302-47" = "（自然を感じながら身体を休めていると、いつの間にか1時間ほど経過し……）"
"1601302-48" = "（……ふと、隣に目をやると、コハルは疲れたのかウトウトしていた）"
"1601302-49" = "[wa:300]― [log=코하루 수영복]……えっと……。[/log]"
"1601302-50" = "― [log=코하루 수영복]……先生……[wa:1050]その……[wa:1250]いつまでこうしてるの……？[/log]"
"1601302-51" = "― [log=코하루 수영복]意味分かんない……。[/log]"
"1601302-52" = "[ns11] \"先に帰って休んでも大丈夫だよ。\"\n[ns12] \"私もしばらくしたら戻るから。\""
"1601302-53" = "[wa:300]― [log=코하루 수영복]そう……[wa:1400]んむ……。[/log]"
"1601302-54" = "[wa:300]― [log=코하루 수영복]そう……[wa:1400]んむ……。[/log]"
"1601302-55" = "― [log=코하루 수영복]じゃあ、[wa:670]帰ろっかな……。[/log]"
"1601302-56" = "― [log=코하루 수영복]……はっ！！[/log]"
"1601302-57" = "― [log=코하루 수영복]（ダメダメダメ！）[/log]"
"1601302-58" = "[wa:100]― [log=코하루 수영복]（私は今何をっ！）[/log]"
"1601302-59" = "[wa:350]― [log=코하루 수영복]（危ない！[wa:800]また先生に[wa:580]騙されるところだった）[/log]"
"1601302-60" = "― [log=코하루 수영복]（警戒を緩めるなんて……）[/log]"
"1601302-61" = "― [log=코하루 수영복]（ダメ、[wa:500]絶対にダメ！）[/log]"
"1601302-62" = "[wa:200]― [log=코하루 수영복]私を油断させようとしたって[wa:1550]無駄なんだからっ！[/log]"
"1601302-63" = "― [log=코하루 수영복]……むんっ！[/log]"
"1601302-64" = "（そうしてコハルは再び姿勢を正し、眠気との戦いを再開するも……）"
"1601302-65" = "（……ほどなくして、静かな呼吸音が聞こえ始めた）"
"1601302-66" = "（その後、もうしばらく大自然に癒やされてから、コハルを起こさないようにおんぶして拠点に戻った）"
