[translation]
"2600802-1" = "私、成功しちゃいました！"
"2600802-2" = "（シズコとの約束通り、海の家へとやって来た）"
"2600802-3-シズコ" = "あっ！"
"2600802-4-シズコ" = "全く、遅いですよ先生！"
"2600802-5" = "[s] \"ごめんごめん。シズコはいつも元気いっぱいだね。\""
"2600802-6-シズコ" = "当たり前です！ "
"2600802-7-シズコ" = "百夜堂のオーナーでありアイドルとして、いつ何時も明るく前向きな姿勢を忘れてはいけませんから！"
"2600802-8" = "[s] \"なるほど。ところで、今日はどうしたの？\""
"2600802-9-シズコ" = "い、至って冷静ですね……！"
"2600802-10-シズコ" = "せっかくの海、そして夏なんですから！"
"2600802-11-シズコ" = "海の家もそう、まるで大波に乗ったように！"
"2600802-12-シズコ" = "もっとテンション上げ上げで行きましょうっ！"
"2600802-13" = "[s1] \"よ、よーし！！\"\n[s2] \"よく分からないけど、了解！\""
"2600802-14-シズコ" = "む、無理に乗ってくれてる感が否めませんね……。"
"2600802-15-シズコ" = "とりあえず、話を進めるとしましょう。"
"2600802-16-シズコ" = "ですが、この後の私の話を聞けば……"
"2600802-17-シズコ" = "先生は夢中になって、私から目が離せなくなること請け合いです！"
"2600802-18-シズコ" = "見てください。この百夜堂のフランチャイズ店、"
"2600802-19-シズコ" = "「海の家」を！"
"2600802-20" = "何を隠そう、このシズコ…… "
"2600802-21" = "数々のリゾートとの業務提携を通じたフランチャイズ化……"
"2600802-22" = "それをほぼ全て完了させました！"
"2600802-23" = "そして様々な商品、そして各リゾートで独自に発達したサービス……"
"2600802-24" = "それらを全て練り上げた、旗艦のようなお店！"
"2600802-25" = "各支店を本店同様、しっかりと管理できる体制を整え！"
"2600802-26" = "それぞれの支店の特徴を生かした商品も販売！"
"2600802-27" = "そして重要なアイテムは全店舗で手に入れることができるようにしたことで！"
"2600802-28" = "全体として、過去最高の収益を創出しました！"
"2600802-29-シズコ" = "具体的な数値は企業秘密ですが……"
"2600802-30-シズコ" = "百夜堂の売り上げは、以前とは比にならないほど急上昇したのです！"
"2600802-31-シズコ" = "これを機に、この海や群島だけでなく……"
"2600802-32-シズコ" = "キヴォトス全体に、百夜堂の名を轟かせてやる予定なんです！"
"2600802-33-シズコ" = "そう、この展開はもはや留まるところを知りません！！"
"2600802-34" = "[s3] \"おお……シズコ、すごく楽しそうだね。\"\n[s4] \"流石はシズコ、やっぱりすごいね。\""
"2600802-35-シズコ" = "ぐっ、あまり熱量が伝わっていない……。"
"2600802-36-シズコ" = "先生はどうしてこう、そういうところで妙に冷静に……！"
"2600802-37-シズコ" = "え、もうあちこちの支店に行ってきたんですか？"
"2600802-38-シズコ" = "な、なるほど。それで、どうでしたか？ "
"2600802-39-シズコ" = "生まれ変わった、夏の百夜堂のサービスは！"
"2600802-40" = "[s] \"良かったけど、今までの百夜堂のサービスが無いのは寂しいかも。\""
"2600802-41-シズコ" = "そ、それはつまり……。"
"2600802-42-シズコ" = "あの、ドジっ子サービスのことを指してるんですか？"
"2600802-43-シズコ" = "あ、あれは結果だけを見るとあまり効率的ではないと言いますか……。"
"2600802-44-シズコ" = "優先順位の問題と言いますか……。"
"2600802-45-シズコ" = "あるいは、そこまで考えが至らなかったといいますか……。"
"2600802-46-シズコ" = "その、特に……"
"2600802-47-シズコ" = "現実的な、工数の問題で……。"
"2600802-48-シズコ" = "それで……まあ、私も寂しさは感じていたのですが……。"
"2600802-49" = "[s] \"シズコ、最近ちゃんと休んでる？\""
"2600802-50-シズコ" = "そ、それは……！？"
"2600802-51-シズコ" = "わ、私何か今、変なところとかあります！？"
"2600802-52" = "[s5] \"今までお客さんを楽しませるシズコが、楽しそうで可愛かったから。\"\n[s6] \"まあ、やむを得ない変化っていうのはあるものだと思うけど……。\" "
"2600802-53-シズコ" = "えっ、と……。"
"2600802-54-シズコ" = "それは、その……。"
"2600802-55" = "（シズコの顔が、みるみる赤くなっていく）"
"2600802-56-シズコ" = "ちょ、ちょっと用事を思い出しました！ "
"2600802-57-シズコ" = "この後その、インテリでゴージャスでスマートな会議をしなくてはならないので！"
"2600802-58-シズコ" = "そ、それではまた明日！"
"2600802-59" = "（シズコは駆け足で去っていった）"
"2600802-60" = "（いろいろ気になる部分はありつつ、とりあえずリゾートへと戻った）"
