[translation]
"1010105-1" = "二人だけの打ち上げ"
"1010105-2" = "（サオリに連絡をもらい、会場のDJステージにやって来ていた）"
"1010105-3-ステージの観客A" = "めっちゃ良かったね！"
"1010105-4-ステージの観客B" = "DJの人、新人みたいだけど超うまかったし！"
"1010105-5-ステージの観客C" = "だよね、分かる！#nこっちまで熱が伝わってきたもん！"
"1010105-6" = "[ns1] （サオリ、すごく頑張ってたな……）\n[ns2] （観客にも伝わっていたみたいだ）"
"1010105-7" = "[ns] \"サオリ。\""
"1010105-8-サオリ" = "……ん？"
"1010105-9-サオリ" = "あ、先生。"
"1010105-10-サオリ" = "……ステージ、大丈夫だったか？"
"1010105-11" = "[s3] \"すっごく楽しかったよ！\"\n[s4] \"おかげでテンション上がったよ！\""
"1010105-12-サオリ" = "そ、そうか……。"
"1010105-13-サオリ" = "それは良かった。"
"1010105-14-サオリ" = "先生がそう言ってくれると安心する。"
"1010105-15-サオリ" = "おかげで気が楽になった。"
"1010105-16" = "[ns] \"ところで、ほかのスタッフは？\""
"1010105-17-サオリ" = "あぁ、みんなは打ち上げに向かった。"
"1010105-18-サオリ" = "私も誘われたんだが……。"
"1010105-19-サオリ" = "まだ機材の片付けも残っているからな。#n……それに、賑やかな場所は、あまり得意じゃない。"
"1010105-20-サオリ" = "だから一人で――"
"1010105-21-サオリ" = "ごほっ！"
"1010105-22" = "[s] \"大丈夫？\""
"1010105-23-サオリ" = "し、心配ない。"
"1010105-24-サオリ" = "ちょっと喉が乾燥しただけだ。"
"1010105-25-サオリ" = "……これは？#n差し入れのジュース……？"
"1010105-26-サオリ" = "ありがとう、先生。#nいつも世話になってばかりだな。"
"1010105-27" = "[s] \"気にしなくて良いんだよ。\""
"1010105-28-サオリ" = "少し座ろうか。#n先生もこっちに来てくれ。"
"1010105-29" = "[wa:1090]― [log=사오리 수영복]終演後の客席というのは、[wa:2200]寂しいものだな。[/log]"
"1010105-30" = "[wa:2670]― [log=사오리 수영복]大勢いた観客がはけ、[wa:2130]照明はすべて消えて……[/log]"
"1010105-31" = "[wa:1380]― [log=사오리 수영복]華やかなステージは[wa:1660]跡形もなく、[wa:1640]静寂に沈んでいる。[/log]"
"1010105-32" = "― [log=사오리 수영복]熱気と歓声に満ちていた空間が[wa:2360]突如静まると……[/log]"
"1010105-33" = "[wa:2410]― [log=사오리 수영복]どこか、[wa:1570]切なさを覚えるほどだ。[/log]"
"1010105-34" = "[wa:670]― [log=사오리 수영복]……[wa:940]でも、[wa:2050]今はもう、[wa:1260]大丈夫だ。[/log]"
"1010105-35" = "[wa:1340]― [log=사오리 수영복]変わったことは何もないが、[wa:2300]穏やかでいられる。[/log]"
"1010105-36" = "[wa:790]― [log=사오리 수영복]……[wa:2020]先生が隣にいるから、[wa:2760]かもしれないな。[/log]"
"1010105-37-サオリ" = "ありがとう、先生。#nおかげで元気になった。"
"1010105-38" = "[s] \"ジュースだけで足りた？\""
"1010105-39-サオリ" = "あ、ああ。まったく問題――"
"1010105-40-サオリ" = "……問題、あるようだ。"
"1010105-41-サオリ" = "ステージで体力を使いすぎたな。"
"1010105-42" = "[s5] \"じゃあ、一緒に打ち上げをしようか？\"\n[s6] \"二人でなら、どうかな？\""
"1010105-43-サオリ" = "……先生なら、そう言うだろうと思った。"
"1010105-44-サオリ" = "もちろんだ、行こう。"
