[translation]
"1010305-1" = "快刀乱麻"
"1010305-2" = "桃源郷"
"1010305-3-マリナ" = "うむ、良い香りだ。"
"1010305-4-マリナ" = "どんな茶葉を使っているのだろうか？"
"1010305-5" = "[s] \"マリナって、お茶に詳しいんだね？\""
"1010305-6-マリナ" = "レッドウィンターで、よく飲んでいるからな。"
"1010305-7-マリナ" = "サモワールと呼ばれる湯沸かし器具も持っているくらいだ。"
"1010305-8-マリナ" = "中央に収納した燃料で、お湯を沸かせるものでな。"
"1010305-9-マリナ" = "電気ポットのようなものをイメージしてくれ。"
"1010305-10-マリナ" = "いつか先生にも、レッドウィンター流の紅茶でおもてなしをしよう！"
"1010305-11-マリナ" = "期待してくれて構わないぞ！"
"1010305-12-マリナ" = "……ふむ。#n山海経のお茶は、透き通った香りがするな。"
"1010305-13-マリナ" = "ただ、少し物足りない気が……。"
"1010305-14" = "（どこからか、騒がしく言い争っている声が聞こえてきた）"
"1010305-15-山海経の生徒A" = "だから、月餅は私が切るって。#nあんた、いつも8等分にしちゃうじゃん。"
"1010305-16-山海経の生徒A" = "8等分で良いんだよ。#nなんで4等分にこだわってるんだ？"
"1010305-17-山海経の生徒A" = "はぁ、何回言ったら分かるの？"
"1010305-18-山海経の生徒A" = "4等分に切ったほうが、きれいな形のまま食べられるでしょ。"
"1010305-19-山海経の生徒B" = "いやいや、月餅は厚みがあるんだし、#n8等分じゃないと食べづらくない？"
"1010305-20-山海経の生徒B" = "それに、お茶と交互に味わえる回数は多いほうがお得だし！"
"1010305-21-マリナ" = "……何の討論をしているんだ？"
"1010305-22" = "[s1] \"月餅を何等分にするか……。\"\n[s2] \"……で、悩んでいるみたいだね。\""
"1010305-23-マリナ" = "ふむ……？"
"1010305-24-山海経の生徒A" = "そもそも8等分にするのが難しいから！#n失敗したら、月餅が崩れちゃうかもしれないし！"
"1010305-25-山海経の生徒B" = "それは、あんたが下手くそだからでしょ！"
"1010305-26-山海経の生徒A" = "大は小を兼ねるんだって！#nとりあえず4等分して、自分は2回に分けて食べたら良いじゃん！"
"1010305-27-山海経の生徒B" = "その分けて考えるのが嫌なの！"
"1010305-28-山海経の生徒A" = "うぅ……これでは、いつまで経っても結論が。"
"1010305-29-山海経の生徒B" = "あそこ、外部の人たちなのかな？"
"1010305-30-山海経の生徒A" = "ちょうど良かった！#n第三者なら、きっと客観的に見えているはず！"
"1010305-31-山海経の生徒B" = "あの人たちに、どうすれば公平に月餅を食べられるのか聞いてみよう！"
"1010305-32" = "（こうして、公平な月餅の食べ方（？）についての判断を迫られることになった）"
"1010305-33" = "（どちらが正解とは、はっきり言いづらいな……。）"
"1010305-34-マリナ" = "よし、何をするべきか分かった気がする。"
"1010305-35" = "[s] \"マリナ……？\""
"1010305-36" = "（マリナは勢いよく立ち上がり、議論の真っ只中にあるテーブルに向かっていった）"
"1010305-37-マリナ" = "では、少し失礼する。"
"1010305-38-山海経の生徒B" = "げ、月餅を一気に手で掴んだ……！"
"1010305-39-山海経の生徒B" = "しかも、一口で食べるとは……！"
"1010305-40-マリナ" = "（もぐもぐ、もぐもぐ）"
"1010305-41-マリナ" = "うむ、美味しいな。"
"1010305-42-マリナ" = "結局、どう食べたところで基本的な味は変わらない。"
"1010305-43-マリナ" = "何より、茶菓は本来の味を楽しむためにある。"
"1010305-44-マリナ" = "にもかかわらず、茶菓の切り分け方で争い、#nお茶を放置しては本末転倒だろう。"
"1010305-45-マリナ" = "……えっと、本末転倒の使い方、これで合ってるか？"
"1010305-46" = "[s] \"完璧だよ、マリナ。\""
"1010305-47-マリナ" = "よし、なら問題ないな！"
"1010305-48-マリナ" = "とにかく、そういうわけだ。#n……少し、言い過ぎてしまったような気も。"
"1010305-49-山海経の生徒B" = "な、なるほど……！"
"1010305-50-山海経の生徒B" = "「物事の本質」を考えるべき、と……。"
"1010305-51-山海経の生徒A" = "食べ方で争うのは、無意味……！"
"1010305-52-山海経の生徒B" = "やっぱり、聞いて良かった！"
"1010305-53-マリナ" = "うむ。#n力になれたのであれば、私も嬉しい限りだ。"
"1010305-54-マリナ" = "しかし、先ほどから何かが足りない……。"
"1010305-55-マリナ" = "そうだ、ジャムはないのか？#n果肉を潰さずに、砂糖漬けしたジャムだ！"
"1010305-56-山海経の生徒A" = "じゃ、ジャム……！？"
"1010305-57-山海経の生徒B" = "お茶を飲むんじゃ！？"
"1010305-58-マリナ" = "もちろんだ！#nやはり、お茶にはジャムが欠かせない！"
"1010305-59-マリナ" = "一口目をそのまま味わったら、次はジャムを一匙。#nこれぞ、究極の楽しみ方！"
"1010305-60-マリナ" = "ジャムがないのなら、角砂糖でも大丈夫だ。"
"1010305-61-マリナ" = "甘みもほのかに楽しめるだろう！"
"1010305-62-山海経の生徒A" = "なっ……。"
"1010305-63-山海経の生徒B" = "お茶に対する冒涜だ！"
"1010305-64-マリナ" = "な、何だって！？"
"1010305-65-山海経の生徒A" = "お茶は素材の味を楽しむもの！"
"1010305-66-山海経の生徒B" = "透き通った色を目で、注ぐ時の清らかな音を耳で楽しまなくちゃ！"
"1010305-67" = "ジャムも角砂糖も、すべて邪道！"
"1010305-68-マリナ" = "私はただ、レッドウィンターでのお茶の楽しみ方を話しただけなんだが……。"
"1010305-69" = "（山海経の生徒たちとマリナによるお茶の飲み方議論は、その後も続いた）"
"1010305-70" = "（当然、お茶は議論が終わる頃には冷えてしまっていた……）"
