[translation]
"1001515-1" = "アリスの花丸シール"
"1001515-2" = "（アリスと会うために、ゲーム開発部の部室へ向かった）"
"1001515-3" = "（到着した途端……）"
"1001515-4-アリス" = "先生――！！！"
"1001515-5" = "[s] \"アリス～～！！！\""
"1001515-6-アリス" = "本物の先生です！"
"1001515-7" = "（アリスは いきおいよく とびついた！）"
"1001515-8" = "（せんせいは たおれそうになった！）"
"1001515-9-アリス" = "待ってましたよ！"
"1001515-10" = "[s] \"私も会いたかったよ。それで見せたいものって……？\""
"1001515-11-アリス" = "ふっふっふ、それは……。"
"1001515-12-アリス" = "こちらです！"
"1001515-13" = "（アリス は バッジのようなものを さしだした！）"
"1001515-14" = "[ns1] \"……バッジ？\"\n[ns2] \"「Good job」……って書いてある。\""
"1001515-15-アリス" = "バッジではなく、「花丸シール」です！"
"1001515-16-アリス" = "どこから説明しましょうか……。"
"1001515-17-アリス" = "以前、みんなでローグライクゲームを作りました。"
"1001515-18-アリス" = "その中には滅多に手に入らない、とても運気の上がるアイテムがあったんです。"
"1001515-19-アリス" = "それがこの「先生の花丸シール」です！"
"1001515-20-アリス" = "持っているだけで強くなり、幸運値のステータスも上がる……。"
"1001515-21-アリス" = "とってもすごいアイテムなんです！"
"1001515-22" = "[s3] \"なるほど……。\"\n[s4] \"それをこうして、実際に作ってみたと。\""
"1001515-23-アリス" = "その通りです！"
"1001515-24-アリス" = "というわけで先生、アリスと冒険に出ましょう！"
"1001515-25-アリス" = "このシールを沢山配らないと！"
"1001515-26" = "（元気いっぱいのアリスに手を引かれ、外へ向かった）"
"1001515-27-アリス" = "こんにちは！"
"1001515-28-新素材開発部員A" = "やっ、アリス。#nそれに先生も、こんにちは。"
"1001515-29-新素材開発部員A" = "今日はどうしたの？"
"1001515-30-新素材開発部員A" = "「よくできましたシール」です！"
"1001515-31-新素材開発部員A" = "「Good job」……へぇ、何だか嬉しいね。"
"1001515-32-アリス" = "要するに、褒めてくれてるってこと？"
"1001515-33-新素材開発部員A" = "先生も、ありがとうございます。"
"1001515-34" = "[s] \"うん、何か理由があったわけじゃないんだけど。\""
"1001515-35-新素材開発部員A" = "ふふっ。それでも、ありがとうございます。"
"1001515-36-新素材開発部員A" = "大切にするね、アリス。"
"1001515-37-アリス" = "はい、絶対に良いことが起こるはずです！#nゲームでも幸運値が上がるので！"
"1001515-38-新素材開発部員A" = "なるほど……ま、運に頼りたくなる時はあるよね。"
"1001515-39-新素材開発部員A" = "新素材の開発なんてのは、運次第みたいなところもあるし。"
"1001515-40-新素材開発部員A" = "乳鉢に素材を入れて、一つひとつ丁寧に擦って、焼いて――"
"1001515-41-新素材開発部員A" = "それを今度は砕いて、混ぜて、回して、振って……。"
"1001515-42-新素材開発部員A" = "どれだけ考えても、何度繰り返しても……最後は祈るしかない。"
"1001515-43-新素材開発部員A" = "というわけで……次こそお願いします、「よくできましたシール」様！！！"
"1001515-44" = "[s] \"い、色々と大変なんだね……。\""
"1001515-45-アリス" = "アリスも詳しくは知りませんが……。"
"1001515-46-アリス" = "きっと大丈夫です！"
"1001515-47-アリス" = "さあ、どんどん行きましょう！"
"1001515-48-新素材開発部員A" = "みんな、ちょっと来て！#n今、新しい数値が出た！"
"1001515-49-新素材開発部員A" = "嘘！？"
"1001515-50-新素材開発部員B" = "本当だってば！"
"1001515-51-新素材開発部員A" = "まさか……。"
"1001515-52-新素材開発部員A" = "……あのシールの効果？"
"1001515-53-アリス" = "では、アリスはそろそろ行きます！#n上手くいきますように！"
"1001515-54-アリス" = "ありがとね、アリス。#nサーバーの相手してると、祈ることが多くて……。"
"1001515-55-ミレニアムの生徒A" = "あれ……？"
"1001515-56-ミレニアムの生徒A" = "サーバーエラーが直ってる……！？"
"1001515-57-アリス" = "お、これが例の「よくできましたシール」？"
"1001515-58-アリス" = "アリスと先生からのプレゼントです！#n大切にしてくれると嬉しいです！"
"1001515-59-アリス" = "勿論だよ、ありがとう。"
"1001515-60-ミレニアムの生徒B" = "っ……学食の抽選当たった！3等賞！"
"1001515-61-ミレニアムの生徒B" = "……。"
"1001515-62-ミレニアムの生徒B" = "よっしゃ、今日は唐揚げも追加で！"
"1001515-63-疑似科学部員" = "これを着けると、遠赤外線とマイナスイオンで血行が良くなります！"
"1001515-64-疑似科学部員" = "銃の汚れを減らしたり、弾詰まりをなくしたりする効果まで！"
"1001515-65-疑似科学部員" = "その名も、げるげるゲルマニウム・ブレスレット！！！"
"1001515-66-疑似科学部員" = "……。"
"1001515-67-疑似科学部員" = "はぁ、全然売れないな……。"
"1001515-68-アリス" = "こんにちは！何か困ってるんですか？"
"1001515-69-アリス" = "えっ？"
"1001515-70-アリス" = "特に無……くもないかな。"
"1001515-71-アリス" = "ではこちらを！"
"1001515-72-アリス" = "「よくできましたシール」です！幸運値のステータスを上げてくれます！"
"1001515-73-アリス" = "ちょっ、押し売り！？"
"1001515-74-アリス" = "いえ、プレゼントです！"
"1001515-75-アリス" = "みなさんに、幸せになってほしいので！"
"1001515-76-疑似科学部員" = "な、何なんだ……？"
"1001515-77-疑似科学部員" = "……ん？"
"1001515-78-疑似科学部員" = "……ず、ずっと詰まってた薬莢が、勝手に排出された！？"
"1001515-79-疑似科学部員" = "おかしいな。#nげるげるゲルマニウム・ブレスレットには、何の効果も無いはずだし……。"
"1001515-80" = "（アリスと一緒に、よくできましたシールを配り終え……）"
"1001515-81" = "（部室に戻って、二人でゲームをすることに）"
"1001515-82-アリス" = "ありがとうございます、先生。"
"1001515-83" = "[s] \"ん？\""
"1001515-84-アリス" = "今日、アリスと一緒にいてくれたこと。"
"1001515-85-アリス" = "それに今こうして、一緒にゲームをしてくれることも！"
"1001515-86-アリス" = "ゲーム開発部でも、よく一緒にゲームはしますが……。"
"1001515-87-アリス" = "先生と二人で遊べる時間は、珍しいですから。"
"1001515-88-アリス" = "アリスにとってこれは、大事な経験値獲得チャンスです！"
"1001515-89" = "[s] \"なるほど……？\""
"1001515-90-アリス" = "なのでアリスは、こうして先生と一緒に過ごせて、とっても嬉しいです！"
"1001515-91-アリス" = "どれくらい嬉しいかと言うと……。"
"1001515-92-アリス" = "二人でパーティーを組んで、この「花丸シール」を装備すれば……。"
"1001515-93-アリス" = "三日間徹夜で、ゲームができそうなくらいです！"
"1001515-94" = "[s5] \"そ、それはあんまり良くないかな……？\"\n[s6] \"三日の徹夜はもう厳しい……。\""
"1001515-95-アリス" = "そ、そうでしたか……。"
"1001515-96-アリス" = "ですが、この「花丸シール」の効き目は本当にすごいんです！#nアリスもそうでした！"
"1001515-97-アリス" = "格闘ゲームで体力が1ドットしか残っていない時に、#n相手の必殺技をジャストガードして――"
"1001515-98-アリス" = "レイジ状態から逆転、一撃の超必殺技を決められましたから！"
"1001515-99" = "[s] \"それはすごい！？\""
"1001515-100-アリス" = "はい！#nモモイとの試合で、一度だけですが！"
"1001515-101-アリス" = "その日の部室は――"
"1001515-102-アリス" = "それは、それはもう……！"
"1001515-103-アリス" = "爆発寸前の盛り上がりでした！"
"1001515-104" = "[s]\"私も見てみたかったなぁ……。\""
"1001515-105-アリス" = "……あっ。"
"1001515-106-アリス" = "思えば、先生にシールを渡しそびれていました！"
"1001515-107" = "[s] \"あ、そういえば？\""
"1001515-108" = "[ns7] \"でも、貰っちゃって良いの？\"\n[ns8] \"これ「先生のよくできましたシール」じゃ……？\""
"1001515-109-アリス" = "確かにそうかもしれませんが……。"
"1001515-110-アリス" = "……大丈夫です！"
"1001515-111-アリス" = "実はアリス、先生専用の「アリスのよくできましたシール」を作っておいたんです！2枚だけ！"
"1001515-112" = "[s] \"「アリスのよくできましたシール」？\""
"1001515-113-アリス" = "はい！#nこれは――"
"1001515-114-アリス" = "アリスが先生を褒めるための「よくできましたシール」です！"
"1001515-115-アリス" = "先生のシールほど万能ではないですし、幸運値も上がらないかもしれませんが……。"
"1001515-116-アリス" = "それでも、受け取ってもらえたら嬉しいです！"
"1001515-117-アリス" = "これがあると、いつも繋がってるような気がします。"
"1001515-118" = "[ns] \"ありがとね、アリス。\""
"1001515-119-アリス" = "はい、先生。"
"1001515-120-アリス" = "やっぱりアリスは、先生のことが大好きです。"
"1001515-121" = "[s] \"私も大好きだよ。\""
"1001515-122-アリス" = "ありがとうございます！"
"1001515-123-アリス" = "そしてこの隙に！二連続で葉蛾扇、そしてジャンプ強キックからの強パンチスタン……！"
"1001515-124-アリス" = "そしてスペシャルアーツ、レベル3です！！！"
"1001515-125" = "[ns9] \"や、やられた！！！\"\n[ns10] \"感動してる間にウルトラコンボが！？\""
"1001515-126-アリス" = "ふっふっふ、血も涙も師弟の情も通じない修羅の道――"
"1001515-127-アリス" = "――これこそ、格ゲーの世界です！"
"1001515-128" = "（その後も、二人で仲良くゲームを続けた）"
"1001515-129" = "（アリスは対戦の合間、「アリスのよくできましたシール」を宝物のように見つめていた）"
