[translation]
"2003003-1" = "これぞ新たな美食ですわ"
"2003003-2" = "（会場のパトロール中、見知った影が通り過ぎ……）"
"2003003-3" = "[ns] \"あれ、ハルナ？\""
"2003003-4-ハルナ" = "あら先生。丁度いいところに。"
"2003003-5-ハルナ" = "どうぞ、こちらを召し上がってみてくださいませ。"
"2003003-6" = "（ハルナは紫色の粒……がたくさん乗ったスプーンを差し出してきた）"
"2003003-7" = "[ns1] \"ん？味は……ブルーベリー？\"\n[ns2] \"パチパチ弾ける不思議な食感……。\""
"2003003-8-ハルナ" = "うふふ……"
"2003003-9-ハルナ" = "いかがでしたか、先生。新鮮な体験でしょう？"
"2003003-10" = "[s] \"初めて食べた。不思議な食感だね。\""
"2003003-11-ハルナ" = "その体験こそ、美食の世界に革新をもたらす大切な要素なのです。"
"2003003-12-ハルナ" = "故にこそ――先生に「分子料理」を食していただく試みは成功したと言えます。"
"2003003-13-ハルナ" = "これであのミレニアムの方も浮かばれることでしょう……。"
"2003003-14-普通のミレニアムの生徒" = "いや、私はピンピンしてますけど？"
"2003003-15" = "[s] \"分子料理って？\""
"2003003-16-ハルナ" = "分子料理とは、伝統的な調理法から脱却し全く新しい方法で食にアプローチしていく美食改革の最先端ですわ。"
"2003003-17-普通のミレニアムの生徒" = "実は今回、その分子料理で屋台を開いていたのですが……。"
"2003003-18" = "（ハルナたちから聞いた話によると……）"
"2003003-19-普通のミレニアムの生徒" = "ぶ、分子料理はいかがですか……！"
"2003003-20-普通のミレニアムの生徒" = "一度で良いので、召し上がってみてください……！"
"2003003-21-通りすがりの通行人B" = "分子料理？何それ？"
"2003003-22-通りすがりの通行人A" = "さあ……このよくわからない食べ物のことじゃない？"
"2003003-23-通りすがりの通行人A" = "ふーん……ちょっと高いね。#nそれに見た目も変だし……。"
"2003003-24-通りすがりの通行人B" = "だよね。なのにわざわざ食べるっていうのも……。#nたこ焼きとか、焼きそばとか、美味しいものは他にもたくさんあるのに。"
"2003003-25-通りすがりの通行人A" = "あー、それ聞いたらたこ焼き食べたくなってきた！#nさっきよさげなお店あったけど、行く？"
"2003003-26-通りすがりの通行人B" = "いいじゃん！早く行こ！"
"2003003-27-普通のミレニアムの生徒" = "ま、待って……！"
"2003003-28-普通のミレニアムの生徒" = "はぁ……またダメだった。"
"2003003-29-普通のミレニアムの生徒" = "やっぱり分子料理は斬新過ぎるのかな……。"
"2003003-30-ハルナ" = "……あら、面白そうな試みをされていますわね？"
"2003003-31-普通のミレニアムの生徒" = "！！！"
"2003003-32-ハルナ" = "なるほど。これが噂の分子料理……。"
"2003003-33-ハルナ" = "そして、こちらはフルーツジュースを固めたものなのですね？#nまるでキャビアのようですわ……。"
"2003003-34-普通のミレニアムの生徒" = "えへへ……塩化カルシウムを溶かした水に、アルギン酸ナトリウムを#n混ぜたジュースを少しずつ落とすとこうなるんです。"
"2003003-35-ハルナ" = "興味深いですわね。他の料理も紹介していただけますか？"
"2003003-36-普通のミレニアムの生徒" = "も、もちろんです！"
"2003003-37-普通のミレニアムの生徒" = "このステーキは真空調理法を使っていて……。"
"2003003-38-ハルナ" = "ああ、その調理法はよく耳にしますわね。"
"2003003-39-普通のミレニアムの生徒" = "そうなのですね！知れ渡っていて嬉しいです！真空調理法では、食材を真空包装して#n60度くらいのお湯に入れるんです。そのまま長時間、低温で加熱すると……"
"2003003-40-普通のミレニアムの生徒" = "とっても柔らかい食感に仕上がるんですよ！#nタンパク質の変性温度の違いを利用し、#nお肉の良さを最大限に生かせる調理法なんです！"
"2003003-41-ハルナ" = "そのような原理だったのですか。#nでは、この果物は？炭酸飲料のような刺激を感じたのですが……。"
"2003003-42-普通のミレニアムの生徒" = "ドライアイスを使ったんです！#n一緒に保存すると、発生した二酸化炭素が果物の中に入って、#nそのような食感になるんですよ！"
"2003003-43-普通のミレニアムの生徒" = "そうなのですね。果物の食感と炭酸飲料の刺激を同時に楽しめるなんて、驚きましたわ。"
"2003003-44-ハルナ" = "ところで、ミレニアムの技術力なら#n特定の味のみを抽出することも可能ですわよね？#nでしたら……"
"2003003-45" = "（ハルナは、その後も分子料理の概念や使用する調理器具について聞いたそうだ）"
"2003003-46-ハルナ" = "その途中でちょうど先生がいらっしゃったので、#nお声かけしたのですわ。"
"2003003-47-ハルナ" = "しかし、皆さんがこれほど素晴らしい料理に興味を示さないなんて……。"
"2003003-48-ハルナ" = "美食の道を歩む者として、胸が痛みますわ……。"
"2003003-49" = "[s] \"馴染みのない料理ばかりだからね……。\""
"2003003-50-普通のミレニアムの生徒" = "はい……。そこさえどうにかなれば、#nお客さんも来てくれると思うんですけど……。"
"2003003-51" = "[s] \"馴染みやすそうな分子料理はないの？\""
"2003003-52-ハルナ" = "ふむ……。"
"2003003-53-ハルナ" = "――そうですわ！！！"
"2003003-54-普通のミレニアムの生徒" = "わっ！？どうしたんですか？"
"2003003-55" = "[ns3] \"ハルナの目つきが鋭くなった！\"\n[ns4] \"これはハルナの美食センサーが発動したという証拠！\""
"2003003-56-普通のミレニアムの生徒" = "美食……センサー……！？"
"2003003-57" = "[s] \"……すみません言ってみただけです。\""
"2003003-58-普通のミレニアムの生徒" = "え、えぇ！？"
"2003003-59-ハルナ" = "ふふっ。ここはずばり――"
"2003003-60-ハルナ" = "綿菓子でいきましょう！"
"2003003-61-普通のミレニアムの生徒" = "綿菓子……ですか？"
"2003003-62-ハルナ" = "ええ。そもそも分子料理は、食材を分子レベルで捉え斬新さを追求する調理法……。"
"2003003-63-ハルナ" = "ならば砂糖を変形させ、材料とは全く異なる食感を作り出す綿菓子も、#n素晴らしい分子料理と言えるでしょう！ "
"2003003-64" = "[s] \"さすがはハルナの美食センサーだ！\""
"2003003-65-普通のミレニアムの生徒" = "言ってみただけじゃなかったんですか！？"
"2003003-66-ハルナ" = "い、いらっしゃいませ……！#nぜひ一度、分子料理を召し上がってみてください……！"
"2003003-67-ハルナ" = "斬新な料理はもちろん、昔懐かしい綿菓子も取りそろえていますわ。"
"2003003-68-ハルナ" = "いかがですか？甘くて美味しいですわよ。"
"2003003-69-通りすがりの通行人C" = "綿菓子か……懐かしいな。"
"2003003-70-通りすがりの通行人C" = "ちょうど甘いものが食べたかったし、ひとつもらえるかい？"
"2003003-71-ハルナ" = "ふふっ、承知いたしましたわ。"
"2003003-72-ハルナ" = "トッピングもサービスしておきますわね。#nこちら、オススメのブルーベリーキャビアです。#nぜひお試しくださいませ？"
"2003003-73-通りすがりの通行人C" = "あ、ありがたいけど……"
"2003003-74-通りすがりの通行人C" = "これ、食べられるのかい？#n変わった形をしてるけど……。"
"2003003-75-ハルナ" = "心配なさらないでください。#n安全はこちらの先生が保証してくださりますから。"
"2003003-76" = "[s] \"大丈夫です。私も食べましたので。\""
"2003003-77-通りすがりの通行人C" = "それなら……"
"2003003-78-通りすがりの通行人C" = "んんっ！？"
"2003003-79-通りすがりの通行人C" = "口の中がパチパチする……！？"
"2003003-80-待っている客A" = "こちらがあの分子料理の屋台ですか？"
"2003003-81-待っている客B" = "ええ。しかし、なかなか列が進みませんね。#nもう30分以上も待っているのに。"
"2003003-82-待っている客A" = "それだけ人気なのでしょう。#nそれに、人が並んでいると余計に気になりますし……。"
"2003003-83-待っている客B" = "楽しみですね。一体どんな料理が出てくるのでしょうか？"
"2003003-84-普通のミレニアムの生徒" = "確かに屋台がうまくいけばいいなとは思ってましたけど……。"
"2003003-85-普通のミレニアムの生徒" = "こんなに行列ができるなんて予想外です！"
"2003003-86-普通のミレニアムの生徒" = "分子料理は調理に時間がかかりますし、一体どうすれば……。"
"2003003-87-ハルナ" = "ふふっ、美食の道は常に苦難がつきまとうのですね……。"
"2003003-88-ハルナ" = "また一つ、学びを得られましたわ。"
"2003003-89" = "[s] \"ハルナさん、ひとりで納得しないでくださいね……？\""
"2003003-90-普通のミレニアムの生徒" = "……あっ。でもエンジニア部に頼んで#n大量生産用の機械を作ってもらえば……。"
"2003003-91-普通のミレニアムの生徒" = "きっと何とかなるはず！"
"2003003-92-普通のミレニアムの生徒" = "……ありがとうございます。先生、ハルナさん！#nお陰で分子料理をもっと広められそうです！"
"2003003-93-ハルナ" = "ふふっ、お役に立ててよかったですわ。"
"2003003-94-ハルナ" = "では先生、私たちは行きましょうか？"
"2003003-95" = "[s] \"あれ？もう行くの？\""
"2003003-96-ハルナ" = "新たな美食を多くの人に広めるという目的は達成しましたから。"
"2003003-97-ハルナ" = "それに、きっと残りの問題は私が手を出す必要もないでしょう？"
"2003003-98-ハルナ" = "何より……ここで味わえるものは全て味わったと思いますので。"
"2003003-99" = "[s] \"……うん。確かにそうかも。\""
"2003003-100-ハルナ" = "ところで……私たちには、まだ出向いていない屋台がたくさんありますわ。"
"2003003-101-ハルナ" = "美食とは新たな料理だけでなく、馴染みの料理の中にも存在する――"
"2003003-102-ハルナ" = "ということで、先生。#n今日も最後までお付き合いいただけますわね？"
