[translation]
"1006203-1" = "普通の学園生活"
"1006203-2" = "ミレニアムスクールキャンパス"
"1006203-3" = "（トキに会うために、ミレニアムを訪れた）"
"1006203-4-トキ" = "お待ちしておりました、先生。"
"1006203-5-トキ" = "お忙しい中、ご足労くださりありがとうございます。"
"1006203-6" = "[s] \"それで、困ったことって？\""
"1006203-7-トキ" = "それがですね……。"
"1006203-8-トキ" = "まずは、この手紙をご覧ください。"
"1006203-9-トキ" = "学校から届いたのですが、私の認識が正しいのか確信が持てず……。"
"1006203-10-トキ" = "先生なら詳しいかと思い、アドバイスをいただきたく……"
"1006203-11" = "（トキから手紙を受け取った）"
"1006203-12" = "[ns1] \"出席日数が足りないから、\"\n[ns2] \"このままだと留年しちゃうって、書いてあるね……。\""
"1006203-13-トキ" = "なるほど、私の認識と一致しています。つまり……。"
"1006203-14-トキ" = "放っておいても構いませんね。"
"1006203-15-トキ" = "では、特に問題もないようですし、今日も先生を補佐いたします。"
"1006203-16" = "[ns3] \"いやいや、大変なことになってるよ！？\"\n[ns4] \"そこの認識までは一致してないよ！？\""
"1006203-17-トキ" = "留年なら一度していますし、二度、三度留年したところで一向に構いません。"
"1006203-18-トキ" = "むしろ、留年すれば来年、再来年だけでなく、その先も先生を補佐できます。"
"1006203-19-トキ" = "C&Cとして活動する期間も延びますから、いいこと尽くめですね。"
"1006203-20" = "[s5] \"全然違うからね！？\"\n[s6] \"今まではどうしてたの！？\""
"1006203-21-トキ" = "これまでは特例として、出席扱いになっていました。"
"1006203-22-トキ" = "ですが、今は事情が変わったこともあり、通常通りの出席が求められているようです。"
"1006203-23-トキ" = "待ってください、先生。#n閃いたのですが……。"
"1006203-24-トキ" = "先生のお世話を、学校側で特例として認めてもらえば良いのでは……？"
"1006203-25-トキ" = "良いアイデアだと思いませんか？#nせっかくですから、先生がミレニアムに転勤するというのはどうでしょう？"
"1006203-26" = "[s7] \"それは色々と困るかな……。\"\n[s8] \"ちょっと待ってね。手紙の続きは……。\""
"1006203-27-トキ" = "そうですか……。"
"1006203-28-トキ" = "手紙には、これからは学生の本分をおろそかにせず、生徒の一人として過ごすのであれば……。"
"1006203-29-トキ" = "これまでの状況を鑑みて、救済措置を考慮しても良いと書かれてありました。"
"1006203-30" = "[s] \"つまり「普通の学園生活」が必要ってことなんだね。\""
"1006203-31-トキ" = "普通の学園生活……？"
"1006203-32-トキ" = "そんなに意気込んで、どうされたのですか？"
"1006203-33" = "[s9] \"不安だったりする？\"\n[s10] \"あんまり気が乗らないかな？\""
"1006203-34-トキ" = "……。"
"1006203-35-トキ" = "よく知らないものですから、不安がないとは言えませんね。"
"1006203-36-トキ" = "私はどうしたら良いのでしょうか……。"
"1006203-37" = "[s] \"私が手伝ってあげるよ。\""
"1006203-38-トキ" = "せ、先生？"
"1006203-39-トキ" = "先生、そんな急に引っ張らないでください……！？"
"1006203-40" = "（こうして、トキの「普通の学園生活」が始まった）"
"1006203-41" = "（まずは授業を受けてもらって、そっと見守ることにした）"
"1006203-42" = "教室"
"1006203-43-講師" = "それでは、本日のオンライン授業はここまでとします。"
"1006203-44-講師" = "皆さん、最後までご清聴いただきありがとうございました。"
"1006203-45-講師" = "[ruby=あすま]飛鳥馬[/ruby]トキさん、久しぶりに参加されたようですから、理解度を確かめたいのでこちらの問題を解いてもらえませんか？"
"1006203-46-トキ" = "……。"
"1006203-47-トキ" = "問題を解く、つまり解決すれば良いということですね……。"
"1006203-48-トキ" = "もし複雑な問題が立ちふさがった時には……。"
"1006203-49-トキ" = "力技で正面突破することも、エージェントには求められます！"
"1006203-50-講師" = "な、何を！？画面が……！"
"1006203-51-講師" = "おやめください！授業中にC&Cの道具を使ってはいけません！"
"1006203-52-講師" = "しかも、ミレニアムのファイアウォールを一瞬で解除してしまうほどの#nハッキングツールなんて……！"
"1006203-53-講師" = "すぐに停止しなければ、出席は認められませんよ！！"
"1006203-54-トキ" = "！？"
"1006203-55-トキ" = "先生、こういった時はどうしたら？"
"1006203-56" = "[s] \"素直に問題を解けば良いんじゃ……。\""
"1006203-57-トキ" = "そう素直な人ばかりなら、世の中に争いなんて生まれないでしょう。#n非常に残念なことですが……。"
"1006203-58" = "[s] \"そこをなんとか！出席のために！\""
"1006203-59-トキ" = "……もう、仕方ないですね。大人しく問題に取り組むとしましょうか。"
"1006203-60-ミレニアムの生徒" = "トキさんですよね？前から話してみたかったんです。#n良かったらカフェに行きませんか？"
"1006203-61-トキ" = "！？"
"1006203-62-トキ" = "せ、先生……。"
"1006203-63" = "[s] \"行ってらっしゃい。ゆっくり楽しんでおいで。\""
"1006203-64-トキ" = "ですが……。"
"1006203-65" = "[s] \"友人と放課後にカフェで過ごすなんて、学園生活の醍醐味だよ！\""
"1006203-66-トキ" = "そ、そうなんですか……？"
"1006203-67-トキ" = "でしたら、先生もご一緒に……。"
"1006203-68" = "[s] \"生徒同士で楽しむ時間も大切だからね。\""
"1006203-69-トキ" = "一緒ではダメなのですか……？"
"1006203-70-トキ" = "先生？先生！？"
"1006203-71" = "（捨てられた子犬のような目をしていたが、涙を飲んで見送った）"
"1006203-72" = "（しばらくして……）"
"1006203-73" = "ドカァァン！！"
"1006203-74" = "[ns] \"ば、爆発！？\""
"1006203-75-ミレニアムの生徒" = "きゃぁぁぁっ！？"
"1006203-76-チンピラA" = "な……何なんだよ、このメイド……。"
"1006203-77-チンピラB" = "売れ残りそうなケーキを捨てるのも、もったいないだろうからなあ。#nだったら食べてやろうと思っただけなのによ……。"
"1006203-78-トキ" = "そういった行為を無銭飲食と言うのです。"
"1006203-79-チンピラC" = "んだと！ミレニアムのメイドには近寄るなって噂にビビると思ってんのか！？"
"1006203-80-トキ" = "……。"
"1006203-81-トキ" = "なるほど、これが普通の学園生活ですか。"
"1006203-82-トキ" = "C&Cの部室にあった本で見たことがあります。"
"1006203-83-トキ" = "喧嘩を売ってくる問題児を全員倒し、#n学園を支配することこそ生徒の本分であると！"
"1006203-84-チンピラC" = "はあ？やれると思ってんのか、ふざけやがって！"
"1006203-85" = "[ns] \"生徒の本分を勘違いしてない！？\""
"1006203-86-トキ" = "こうなった以上、本気で参ります。"
"1006203-87-トキ" = "全力とはいきませんが、ここは一つ、私の力をお見せしましょう。"
"1006203-88-トキ" = "パワードスーツ【アビ・エシュフ】移行ーー"
"1006203-89" = "（その後も暴走しようとするトキを何とか抑えた）"
"1006203-90-トキ" = "先生、大丈夫ですか？"
"1006203-91" = "[s] \"寿命が何年か縮まったかも……。\""
"1006203-92-トキ" = "……。"
"1006203-93-トキ" = "……申し訳ございません。 "
"1006203-94-トキ" = "またご迷惑をかけてしまいましたね……。"
"1006203-95-トキ" = "先生を補佐する身だというのに、ご迷惑をかけてばかりで……。"
"1006203-96-トキ" = "私には、補佐をする資格がありません……。"
"1006203-97" = "[s11] \"そんなことないよ。一緒に勉強していけば大丈夫。\"\n[s12] \"もう一度、気を取り直して挑戦してみよう！\""
"1006203-98-トキ" = "……はい。"
"1006203-99-トキ" = "先生が、そう仰るのでしたら……。"
"1006203-100-トキ" = "それにしても、先生。"
"1006203-101-トキ" = "普通の学園生活とは、こうも難しいものなのですね。"
"1006203-102" = "（クールな表情で切実な思いを吐露するトキと目が合うと……）"
"1006203-103" = "（小さく頷くことしかできなかった）"
