[translation]
"1006215-1" = "繋がりの証"
"1006215-2" = "シャーレ・オフィス"
"1006215-3" = "（知らない番号から電話がかかってきた）"
"1006215-4" = "（保険やローンの勧誘なら、丁重にお断りする気でいたのだが……）"
"1006215-5-トキ" = "もしもし、先生でしょうか。"
"1006215-6" = "[s] \"トキ！？\""
"1006215-7-トキ" = "回線の接続に成功したようですね。"
"1006215-8-トキ" = "試してみて正解でした。さすがは優秀な私です。"
"1006215-9-トキ" = "これで私と先生は、#n24時間常時つながっているも同然だと確認できました。"
"1006215-10" = "[s] \"その言い方は誤解を生むから……\""
"1006215-11-トキ" = "ですが事実でもあります。"
"1006215-12-トキ" = "現に今、私は普段と異なる通信回線で先生と連絡を取っているでしょう？ "
"1006215-13-トキ" = "れっきとした事実を否定するなど、教育者としてどうかと思います。"
"1006215-14-トキ" = "事実に基づいて生徒を正しく導くのが、#n教育者としてあるべき姿ではないでしょうか？"
"1006215-15" = "[s] \"それはもちろん、そうだけど……\""
"1006215-16-トキ" = "さすがは先生、理解が早いですね。"
"1006215-17-トキ" = "では本題に移りますが……#n先生、今すぐ会えませんか。渡したいものがありますので。"
"1006215-18" = "[s] \"トキが、私に？\""
"1006215-19-トキ" = "ええ。気の利いた完璧なるメイドの私が、先生のために用意した一種の足枷……"
"1006215-20-トキ" = "……ではなく、「繋がりの証」を贈りたいのです。"
"1006215-21" = "[s] \"今、ものすごく物騒な言葉が聞こえましたが！？\""
"1006215-22-トキ" = "気のせいでしょう。"
"1006215-23-トキ" = "それか、聞き間違いです。"
"1006215-24-トキ" = "ほかでもない私がそう言っているのですから。"
"1006215-25-トキ" = "……ところで先生、#n人は年に平均8匹のクモを、知らずに飲み込んでいるらしいです。"
"1006215-26-トキ" = "ということは、人は1年に平均してその100倍、#n聞き間違えていてもおかしくはないと思いませんか？"
"1006215-27-トキ" = "……論理がめちゃくちゃ？"
"1006215-28-トキ" = "……。"
"1006215-29-トキ" = "確かに、そうかもしれませんが。#nとにかく今のは、絶対に先生の聞き間違いです。"
"1006215-30" = "[s] \"なら、そういうことにしておくよ……\""
"1006215-31-トキ" = "ありがとうございます。"
"1006215-32-トキ" = "ということで、これから先生のところにお邪魔させていただきます。"
"1006215-33-トキ" = "先程お話しした「繋がりの証」を渡しに。よろしいでしょうか？ "
"1006215-34" = "[s] \"わかった……今どこにいるの？\""
"1006215-35-トキ" = "……なんだか、全てを諦めたような声がしましたが。"
"1006215-36-トキ" = "まあ大丈夫でしょう。私が大丈夫ですので。#nそれで私の居場所ですが……シャーレのオフィス前です。"
"1006215-37" = "[s1] \"えっ！？じゃあドアの前で電話をかけて……\"\n[s2] \"ずっと話していたってこと！？\""
"1006215-38-トキ" = "はい。"
"1006215-39-トキ" = "改めまして――先生、こんにちは。"
"1006215-40" = "[s3] \"う、うん……こんにちは。\"\n[s4] \"入ってくればよかったのに……\""
"1006215-41-トキ" = "いいえ。これも全て先生の同情を誘うための作戦ですから。"
"1006215-42-トキ" = "そして、さらには通りすがりの人に……"
"1006215-43-トキ" = "「こんなに完璧で最高のメイドを外に立たせておくだなんて酷い！」#nと思わせる素敵な副次効果まで付いてきます。"
"1006215-44-トキ" = "……しかし大きな問題があり、結局うまくいきませんでした。"
"1006215-45-トキ" = "シャーレのオフィス前は、思ったより通行人が少なかったのです。"
"1006215-46-トキ" = "何という不覚……次こそはより綿密に計画を立て、#n先生からの同情と周囲からの困惑を完璧に誘いたいと思います。"
"1006215-47" = "[s] \"困惑ってなに！？\""
"1006215-48-トキ" = "なんでもありません。聞き間違いです。"
"1006215-49" = "[s] \"……今日はそれで押し通すんだね……\""
"1006215-50-トキ" = "……とにかく、今日の目的はこちらです。"
"1006215-51-トキ" = "これこそがメイド兼エージェント用の完璧なるヘッドセット。"
"1006215-52-トキ" = "防音性能が高く、カナル型でありながら聴力を損なわないよう#n特殊な音響処理が施された優れモノです。"
"1006215-53-トキ" = "基本的なチャンネル干渉やハッキング対策は当然されていますが、#n万が一チャンネルに入られた場合でも……"
"1006215-54-トキ" = "自動的に回線を迂回して新たに生成する機能が付いています。"
"1006215-55-トキ" = "他にも多種多様の便利機能を搭載しているのですが、#n時間の関係上割愛させていただきます。"
"1006215-56-トキ" = "とにかく結論を申し上げますと……#nこれさえあれば、別途用意されている安全な通信チャンネルを通じ――"
"1006215-57-トキ" = "いつでもダイレクトに連絡が取れるのです。"
"1006215-58-トキ" = "ちなみにそのヘッドセットは、私のものとペアになっています。"
"1006215-59" = "[s] \"そんなにいいものをもらっていいの？\""
"1006215-60-トキ" = "ええ。むしろ是非受け取っていただければと。"
"1006215-61-トキ" = "これは以前仕えていた方が、私のために用意してくださった「トキ・カスタム」ですので。"
"1006215-62-トキ" = "……その人が戻ってくるまで持っておくべきではないか、と？"
"1006215-63-トキ" = "その必要はありません。それに使えるものを使わないのは、非合理的です。#n……そう、あの方もおっしゃるでしょう。"
"1006215-64-トキ" = "ですので、今は先生に使っていただければと。"
"1006215-65-トキ" = "それに、このヘッドセットも誰かに使ってもらった方が喜ぶと思います。"
"1006215-66-トキ" = "道具というのは、使われないと意味がありませんから。"
"1006215-67-トキ" = "というわけで、先生。さっそくヘッドセットを装着してください。#nそして24時間、私と繋がっていてください。"
"1006215-68" = "[s] \"う、うーん……それはちょっと……\""
"1006215-69-トキ" = "何故ためらうのですか？もしや先生には、私以外の誰かがいると？ "
"1006215-70-トキ" = "私とは――"
"1006215-71-トキ" = "――遊びだったのですか！？"
"1006215-72" = "[s] \"ト、トキさん？突然なにを！？\""
"1006215-73-トキ" = "……申し訳ありません、ただの冗談です。"
"1006215-74-トキ" = "雰囲気が和らぐかと思い、先日見たドラマの決め台詞を引用してみました。"
"1006215-75-トキ" = "ドラマや映画も、鍛錬は引き続き行っていますので。#n相変わらず詳しくはないですが。"
"1006215-76-トキ" = "今のはその中で、特別記憶に残っている台詞です。[ruby=ビクトリー]ぶいっ[/ruby]。"
"1006215-77-トキ" = "とにかく、私は先生に伝えたいのです――"
"1006215-78-トキ" = "そのヘッドセットを受け取ってほしい。#nそしていつも私と一緒にいてほしい、と。"
"1006215-79-トキ" = "ただ、それだけなのです。"
"1006215-80" = "[ns] \"……気持ちは嬉しいよ。なら一旦、受け取るね。\""
"1006215-81-トキ" = "ありがとうございます、先生。"
"1006215-82" = "[s] \"でも……いつも身につけるのは、やめておくよ。\""
"1006215-83-トキ" = "……どうしてですか？私は失望しました。"
"1006215-84-トキ" = "見てください先生。すっかり肩を落とした私の姿を。#n早急に釈明を行い、責任を取っていただくよう要求します。"
"1006215-85" = "[s5] \"だってこれは……トキにとって大切なものでしょう？\"\n[s6] \"私も大切にしたいから……\"\n[s7] \"本当に必要な時が来たら、その時に使うね。\""
"1006215-86-トキ" = "……なるほど。そういう理由なら……"
"1006215-87-トキ" = "納得できますね。"
"1006215-88-トキ" = "それに装着していなくても……"
"1006215-89-トキ" = "私たちが「カップルヘッドセット」を持っている事実に変わりはありませんから。"
"1006215-90" = "[s] \"ど、どこでそんな言葉を覚えたの！？\""
"1006215-91-トキ" = "今のは映画から引用してみました。"
"1006215-92" = "[s] \"誤解を招くから、言葉の使いどころは気を付けようね……\""
"1006215-93-トキ" = "その必要はないでしょう。私は誤解されたくて言っているので。"
"1006215-94" = "[s] \"……トキさんお願い、勘弁してください……\""
"1006215-95" = "（トキはしばらくシャーレで遊んだ後、満足した顔で帰っていった）"
"1006215-96" = "（……トキのヘッドセットは、引き出しに入れて大切に保管することにした）"
