[translation]
"1010505-1" = "ライブを終えて"
"1010505-2" = "（ライブ当日、マリーに会いに行った）"
"1010505-3-マリー" = "……はい、そろそろ時間ですね。"
"1010505-4-マリー" = "準備はできています。"
"1010505-5-マリー" = "……？"
"1010505-6-マリー" = "先生……！？"
"1010505-7-マリー" = "もしかして、心配で様子を見に……？"
"1010505-8-マリー" = "……申し訳ありません。#nまた先生に気を遣わせてしまいました。"
"1010505-9" = "[s1] \"気にしないで、私が会いたかっただけだから。\"\n[s2] \"マリーのライブを見たくて来たんだ。\""
"1010505-10-マリー" = "……ありがとうございます、先生。"
"1010505-11-マリー" = "ほかのお二人ですか……？"
"1010505-12-マリー" = "このステージは、私だけで行う予定になっています。"
"1010505-13-マリー" = "学園祭期間中、ミニライブを何回も開催するんだそうです。"
"1010505-14-マリー" = "お二人は、別の場所で頑張ってくださっています！"
"1010505-15" = "[s3] \"今日はマリーの単独ライブなんだ！\"\n[s4] \"盛り上がりそうだね！\""
"1010505-16-マリー" = "えへへ……。"
"1010505-17-マリー" = "……私にとって、この時間はかけがえのない贈り物です。#n皆さんの前で歌を披露したり、先生に応援していただいたり……。"
"1010505-18-マリー" = "こんなにも、たくさんの笑顔が見られるだなんて。"
"1010505-19-マリー" = "考えてみれば……。"
"1010505-20-マリー" = "……相談室よりも、多くの方が訪れているような気も。"
"1010505-21-マリー" = "あれ……。"
"1010505-22-マリー" = "……こ、これで良いんでしょうか？"
"1010505-23" = "[s5] \"普段からそんなに多くの人が……？\"\n[s6] \"それよりも多いって……マリーはすごいね！\""
"1010505-24-マリー" = "そんな、もったいないお言葉を……。"
"1010505-25-マリー" = "……ふふっ。"
"1010505-26-マリー" = "あっ、そろそろ行かないと……。"
"1010505-27-マリー" = "その、先生……よろしければ、ライブが終わったら……。"
"1010505-28-マリー" = "……な、何でもありません！"
"1010505-29" = "[s7] \"応援してるね！\"\n[s8] \"行ってらっしゃい！\""
"1010505-30-マリー" = "……！"
"1010505-31-マリー" = "はい、先生。"
"1010505-32-マリー" = "……行ってきます！"
"1010505-33" = "（ライブが終わるまで、舞台袖でマリーを待った）"
"1010505-34" = "（ステージ上のマリーも、とても輝いていた）"
"1010505-35" = "（そして、ライブ終了後……）"
"1010505-36-マリー" = "……先生！"
"1010505-37" = "（マリーは元気良く戻ってきた）"
"1010505-38" = "[wa:800]― [log=마리 아이돌]先生、[wa:880]待っていてくださったのですね！[/log]"
"1010505-39" = "― [log=마리 아이돌]まさか[wa:930]ずっとここで[wa:550]待っていてくださったなんて……[/log]"
"1010505-40" = "[wa:1500]― [log=마리 아이돌]その……[wa:1500]ステージ、[wa:1200]どうでしたか？[/log]"
"1010505-41" = "― [log=마리 아이돌]舞台袖からだと[wa:1550]あんまり良く[wa:700]見えなかったとは思うのですが……[/log]"
"1010505-42" = "[wa:830]― [log=마리 아이돌]でも、[wa:1050]先生はずっと[wa:900]見守ってくださっていたから……[/log]"
"1010505-43" = "― [log=마리 아이돌]舞台袖からでも[wa:1300]大丈夫かな……[/log]"
"1010505-44" = "[wa:830]― [log=마리 아이돌]その……[wa:1250]パフォーマンス、[wa:1200]どうでした？[/log]"
"1010505-45" = "― [log=마리 아이돌]ちゃんと……[wa:950]「アイドル」に[wa:900]なれていました？[/log]"
"1010505-46" = "[ns9] \"正真正銘、アイドルだったよ！\"\n[ns10] \"マリーは最初から、みんなのアイドルだよ！\"\n[ns11] \"ファン一号の私が保証する！\""
"1010505-47" = "[wa:670]― [log=마리 아이돌]……！！[/log]"
"1010505-48" = "[wa:1300]― [log=마리 아이돌]……ありがとうございます、[wa:1100]先生……！[/log]"
"1010505-49" = "[wa:1350]― [log=마리 아이돌]……えへへ。[/log]"
"1010505-50" = "（その後、熱気で火照ったマリーが落ち着くのを待ってから）"
"1010505-51" = "（ライブの余韻を胸に、会場をあとにした）"
