[translation]
"1012005-1" = "3時間目「清掃：招かれざる客」"
"1012005-2" = "（辛うじて拾えた情報を頼りに練習室を訪れた）"
"1012005-3" = "（しかし、ナツの姿はなく――）"
"1012005-4-ナツ" = "せ、せ、せんせぇ……。"
"1012005-5" = "[wa:840]― [log=나츠 밴드]こ、[wa:780]こっち……[wa:1230]こっちだ……[wa:740]せんせ……。[/log]"
"1012005-6" = "[ns] \"ナツ！？\""
"1012005-7" = "[wa:670]― [log=나츠 밴드]うう……[wa:1260]ドラムセットの中に……[wa:2160]いるんだ……[/log]"
"1012005-8" = "[wa:1440]― [log=나츠 밴드]黒くてカサカサ動く……[wa:2390]あいつが。[/log]"
"1012005-9" = "― [log=나츠 밴드]いくら探しても[wa:980]見つからなくてぇ……。[/log]"
"1012005-10" = "[ns] \"ナツもそういうのは怖がるんだね……。\""
"1012005-11" = "[wa:1610]― [log=나츠 밴드]な、[wa:1000]何を言ってるのだ、[wa:1140]先生！？[/log]"
"1012005-12" = "[wa:1340]― [log=나츠 밴드]キヴォトスで[wa:920]アレを怖がらない[wa:960]女子高生なんて[wa:880]いないんだよ！？[/log]"
"1012005-13" = "― [log=나츠 밴드]銃弾なんかより[wa:1220]よっぽど怖いんだよぉ！？[/log]"
"1012005-14" = "[ns] \"そ、そうなんだ……。\""
"1012005-15" = "[wa:560]― [log=나츠 밴드]うぅ、[wa:1360]このままでは……。[/log]"
"1012005-16" = "― [log=나츠 밴드]せっかく手に入れた[wa:1360]限定マカダミアクッキーが、[/log]"
"1012005-17" = "[wa:2540]― [log=나츠 밴드]餌食になってしまう……。[/log]"
"1012005-18" = "[ns] \"怖いのってそっち……！？\""
"1012005-19" = "[wa:520]― [log=나츠 밴드]だからお願い、[wa:1360]先生……。[/log]"
"1012005-20" = "[wa:2090]― [log=나츠 밴드]助けてぇ……。[/log]"
"1012005-21" = "（ひとまずナツを落ち着かせたあと、練習室をくまなく探した）"
"1012005-22" = "（そして……風に乗って動く、とても大きなホコリの塊を見つけた）"
"1012005-23" = "（ホコリを捨てて、ナツのところに戻った）"
"1012005-24-ナツ" = "ホコリ……？虫じゃなくて……？"
"1012005-25-ナツ" = "……。"
"1012005-26-ナツ" = "だとしても――"
"1012005-27-ナツ" = "マカダミアクッキーを汚そうとしたのは変わらない！"
"1012005-28-ナツ" = "ありがとう。先生はクッキーの命を救った恩人だよ。"
"1012005-29-ナツ" = "これで安心して練習――"
"1012005-30-ナツ" = "――できないんだった。"
"1012005-31" = "[s] \"ドラムセットが、バラバラに……。\""
"1012005-32-ナツ" = "犯人探しには必要な犠牲だったのだよ……。#n仕方ない。組み立てるとしようか。"
"1012005-33-ナツ" = "うん？一人で練習してる理由？"
"1012005-34-ナツ" = "ドラムを叩けるのってここくらいなんだよね。"
"1012005-35-ナツ" = "寮でやったら……ドラムじゃなくて私が叩き出されちゃう。"
"1012005-36-ナツ" = "だから合わせ練習とは別の日に、一人で練習してるんだ。"
"1012005-37-ナツ" = "寂しくないのかって？"
"1012005-38-ナツ" = "全然……ではないけど。"
"1012005-39-ナツ" = "ほら、そのおかげで先生とこうしていられてるし。"
"1012005-40-ナツ" = "悪いことばかりでもないかな？"
"1012005-41-ナツ" = "さーて……。"
"1012005-42-ナツ" = "ドラム、組み立てますか……。"
"1012005-43" = "（最後までナツを手伝ったあと……）"
"1012005-44" = "（マカダミアクッキーを一緒に食べた）"
