[translation]
"1006308-1" = "幸運の証"
"1006308-2" = "（気になって訪ねてみると、コユキは草むらにしゃがんで何かをしていた）"
"1006308-3" = "（横から見えた表情は真剣だった）"
"1006308-4" = "…………うーん。"
"1006308-5" = "そろそろ見つかってくれてもいいと思うんだけど……。"
"1006308-6" = "[ns1] \"コユキ？\"\n[ns2] \"どうしたの？\""
"1006308-7-コユキ" = "……えっ、先生？"
"1006308-8-コユキ" = "あ、連絡したから来てくれたんですか？#nにはは……本当に何でもないですよ。"
"1006308-9-コユキ" = "うぅ、最近ちょっと連絡しすぎな気がしたので……。"
"1006308-10-コユキ" = "大したことでもないのにいちいち連絡してると、いつか相手にされなくなっちゃうんじゃないかと思って……。"
"1006308-11-コユキ" = "そんなことはない……って？#nに、にはは……照れますね。"
"1006308-12-コユキ" = "ん？"
"1006308-13-コユキ" = "何をしていたのか、って？んー、それが……その。"
"1006308-14-コユキ" = "急にこんなことをしてるなんて、変に思われるかもしれないんですけど……。"
"1006308-15-コユキ" = "四つ葉のクローバーを探していたといいますか……。"
"1006308-16-コユキ" = "にはは……今どき流行らないですよね……。"
"1006308-17" = "[s3] \"四つ葉のクローバーを？\"\n[s4] \"予想外ではあったけど……。\""
"1006308-18-コユキ" = "で、ですよね？#nやっぱりそういう反応されると思っていました！"
"1006308-19-コユキ" = "ちゃんと説明するので……わ、笑わないでくださいよ！"
"1006308-20-コユキ" = "私って、ゲーム運があまり良くないじゃないですか？#nいや、まあゲームに限った話ではないですけど……。"
"1006308-21-コユキ" = "それで運を上げるにはどうすればいいのかな～って……#nそうだ四つ葉のクローバーを探そうって！"
"1006308-22-コユキ" = "四つ葉のクローバーといえば、幸運の証じゃないですか！#n見つけたら私にも幸運が訪れるかなって。"
"1006308-23-コユキ" = "でも、問題があって……。"
"1006308-24-コユキ" = "そもそも四つ葉のクローバー自体、運のいい人の前にしか現れないんじゃ……という。"
"1006308-25-コユキ" = "それに四つ葉のクローバーなんかで運が良くなるなら、この世から困ってる人がいなくなりますもんね。"
"1006308-26-コユキ" = "というか幸運の証は運のいい人の前に現れるものであって……。"
"1006308-27-コユキ" = "私みたいな運の悪い人には見つけられませんよね……。#nにはは……。"
"1006308-28" = "[s5] \"コユキは迷信を信じる方？\"\n[s6] \"運の良し悪しってあると思う？\""
"1006308-29-コユキ" = "うーん……。"
"1006308-30-コユキ" = "先生はどう思います？"
"1006308-31-コユキ" = "私は……自分でもよく分かりません！#n真剣に考えたこともありませんし！"
"1006308-32-コユキ" = "でも、ほとんどの出来事は原因と結果が結びついてるので……。#nそれがそれとして起きるのは、自然のような気もするんですよね。"
"1006308-33-コユキ" = "問題には正解が用意されているのと同じようなことだったり？"
"1006308-34-コユキ" = "……でも。"
"1006308-35-コユキ" = "もし運や迷信なんてものがまったくないって決めつけるのも……。"
"1006308-36-コユキ" = "それはそれで面白くないですし……。"
"1006308-37-コユキ" = "……だから私は、信じてみようと思います！#nにはっ！"
"1006308-38" = "[s] \"……。\""
"1006308-39-コユキ" = "にはは……。#nうぅ、何だか小難しいことを考えてしまいました。"
"1006308-40" = "[ns] \"……コユキ。\""
"1006308-41" = "[ns7] \"ちょっと後ろ向いて。\"\n[ns8] 向かい合うコユキの少し後ろを指差す。"
"1006308-42" = "……ん？後ろですか？"
"1006308-43-コユキ" = "……ん？後ろですか？"
"1006308-44-コユキ" = "……あれ？"
"1006308-45-コユキ" = "えっ？"
"1006308-46-コユキ" = "ええええええええええっ！！！！！"
"1006308-47" = "[wa:500]― 先生！[wa:750]見てください！！[wa:850]四葉のクローバーですよ！！"
"1006308-48" = "― どういうこと！？[wa:1000]さっきまでなかったのに！"
"1006308-49" = "― もしかして……[wa:1200]いきなり生えたとか？"
"1006308-50" = "[wa:500]― や、[wa:1000]そんなのありえないか……。"
"1006308-51" = "[wa:50]― 見落としてたのかな……？[wa:2350]先生はいつ気づいたんですか？"
"1006308-52" = "[wa:300]― それに、[wa:1600]どうやって、[wa:550]こんな……"
"1006308-53" = "― タイミングよく……[wa:1000]見つかる、[wa:350]なんて……？"
"1006308-54" = "[ns9] \"幸運を信じてるからかな？\"\n[ns10] \"そのほうが楽しいよ。\""
"1006308-55" = "[wa:450]― ……！！！"
"1006308-56" = "[wa:450]― ……！！！"
"1006308-57" = "― ……なるほど……！[wa:1400]そうですね……！！"
"1006308-58" = "[wa:1100]― ……はい！[wa:1300]そう考えたほうが、[wa:1300]きっと……。"
"1006308-59" = "― ……楽しいですもんね！！"
"1006308-60" = "（その後、コユキと他愛もない話で盛り上がってから、シャーレに戻った）"
