[translation]
"10011070-1" = "第7話;第四関門：トリックハウス"
"10011070-2-カエデ" = "はいはーい！第四関門へようこそ！！"
"10011070-3-カエデ" = "ここは罠や仕掛けがいっぱいの「トリックハウス」！この渦巻映画村でも、かなり有名なアトラクションの一つだよ！"
"10011070-4-カエデ" = "つまり……忍者屋敷？"
"10011070-5-ミチル" = "それはよく分かんない！！"
"10011070-6-カエデ" = "とにかく、「第四関門」はこのトリックハウス！担当は私、[ruby=いさみ]勇美[/ruby]カエデ15歳！趣味はカブトムシ集めだよ！"
"10011070-7" = "[s] \"やっぱりカエデもいたんだね。\""
"10011070-8-カエデ" = "ふっふっふっ……まあね！ちなみにお姫様を誘拐した悪党は、この屋敷の中に逃げた……らしいよ！多分！"
"10011070-9-カエデ" = "そして、この関門でのルールは簡単！"
"10011070-10" = "このトリックハウスの中に入って、"
"10011070-11" = "ゴールに辿り着けば"
"10011070-12" = "OK！"
"10011070-13-カエデ" = "でも、中にはたくさんの試練があるから、一筋縄じゃ行かないよ！"
"10011070-14-ミチル" = "よっし、分かりやすい！トリックハウスでも忍者屋敷でも、何でもかかってこいだよ！"
"10011070-15-ミチル" = "あ、部長……！？"
"10011070-16-ミチル" = "部長、事前に攻略方法の相談などは……！"
"10011070-17-ツクヨ" = "大丈夫大丈夫、進めば何とかなるよ！"
"10011070-18-ミチル" = "基本的に観光客向けなんだし、そんなに難しいのは無いはず……！"
"10011070-19-カエデ" = "あっ！まだ説明の途中なのに！"
"10011070-20-ミチル" = "……え？"
"10011070-21" = "[s] \"ミチル、危なっ……！？\""
"10011070-22-ニヤ" = "にゃはは。次々と襲ってくる試練、それに立ち向かっていく少女たち……。"
"10011070-23-ニヤ" = "そして、その横には……。"
"10011070-24-ニヤ" = "ふふっ……まあ期待はあったけど、なるほど。"
"10011070-25-ニヤ" = "うんうん、面白いねぇ。"
"10011070-26-ニヤ" = "ニヤ様、これは一体どういう状況ですか……！？"
"10011070-27-カホ" = "んー？どうしたの、カホ？"
"10011070-28-ニヤ" = "お姫様を誘拐する役の方から、ご連絡がありました。「自分たちの出番はいつなのか」、と……。"
"10011070-29-ニヤ" = "これが本当だとしたら、今イブキさんを誘拐しているのは一体……？"
"10011070-30-カホ" = "あらまぁ、それはおかしいねぇ？"
"10011070-31-カホ" = "どういうことなんだろうね～？"
"10011070-32-ニヤ" = "またこういう流れですか……今回は何のために……。"
"10011070-33-ニヤ" = "とにかく、後は私の方で動きますので。"
"10011070-34-ニヤ" = "全く、相変わらず真面目だねぇ♪"
"10011070-35-ニヤ" = "はてさて、この先はどうなるかな～？"
"10011070-36-ニヤ" = "今までは何とかなってたけど、そろそろ問題が顕在化してもおかしくない……。"
"10011070-37-ニヤ" = "さて、そんな彼女たちのために、どんな答えを導くのか……。"
"10011070-38-ニヤ" = "期待しとりますよ、先生♪"
"10011070-39-ニヤ" = "ということで忍術研究部のみなさん、今度の公演はよろしくお願いしますね～♪"
"10011070-40-魑魅一座のリーダー" = "では行動を開始する。迅速に進め、邪魔者は処理せよ……行くぞ、「魑魅一座・気まぐれ流」！"
"10011070-41-百鬼夜行の生徒B" = "眠り姫って、あの修行部の部長でしょ？すごいけど、そもそも「忍術研究部」ってあんまり聞いたこと無いような……。"
"10011070-42-百鬼夜行の生徒B" = "……にしても変わった名前だね。"
"10011070-43-ミチル" = "（千載一遇のチャンス……）"
"10011070-44-ミチル" = "（一気にイメージアップして、堂々と正式な部活になって……）"
"10011070-45-ミチル" = "（イズナとツクヨの前でしっかりと胸を張れるようになる、大事なチャンス……！）"
"10011070-46-ミチル" = "（だから私は、絶対に……！）"
"10011070-47-ミチル" = "あれ、ここは……？"
"10011070-48" = "[s] \"あ、起きた？罠が発動して、ここに落ちちゃったみたい。\""
"10011070-49-ミチル" = "……罠？"
"10011070-50-ミチル" = "ってことは、やっぱりこれ忍者屋敷じゃん！"
"10011070-51-ミチル" = "はっ！こんなことしてる場合じゃない……先生殿、早くここから抜け出――"
"10011070-52" = "[s1] \"ごめん、ちょっと待ってもらえる？\"\n[s2] \"足、くじいちゃったみたいで……。\""
"10011070-53-ミチル" = "足、ってことは……ここへ落ちた時に……？"
"10011070-54-ミチル" = "もしかして、私が無傷なのって……先生殿が……？"
"10011070-55-ミチル" = "私が……ひとりで勝手に、走り出したせいで……。"
"10011070-56" = "[s] \"ミチルのせいじゃないよ、大丈夫。\""
"10011070-57-ミチル" = "……。"
"10011070-58" = "[s] \"ミチル？\""
"10011070-59-ミチル" = "……私の、せいで。"
"10011070-60-ミチル" = "私のせいで、全部台無しに……ど、どうしよう……！ごめん、ごめん、先生殿……！！"
"10011070-61" = "[ns] \"少し落ち着いた？\""
"10011070-62-ミチル" = "ぐすっ……うん。"
"10011070-63" = "[s3] \"さっきの「台無しに」っていうのは……。\"\n[s4] \"どういうことか、聞いても良い？\""
"10011070-64-ミチル" = "最初から……全部、私のわがままだった。"
"10011070-65-ミチル" = "あの子……イブキが誘拐された時、本当ならすぐ通報するべきだった。"
"10011070-66-ミチル" = "すぐに陰陽部とか百花繚乱に連絡してれば、多分解決してた……。"
"10011070-67-ミチル" = "私が、自分の我儘を……。"
"10011070-68" = "[s] \"正式な部活になるために？\""
"10011070-69-ミチル" = "……！"
"10011070-70-ミチル" = "うん……。"
"10011070-71-ミチル" = "忍者のことを広めたいのは本当。でも他の生徒たちに話したところで、それを笑わずに受け入れてくれるか、すごく怖い……"
"10011070-72-ミチル" = "だからこの機に、とにかく先に、正式な部活になりたかった。"
"10011070-73-ミチル" = "推薦状無しに、正式な認可が貰えるかもしれないなんて……こんなチャンス、二度と無いかもしれない。だから、何とかして成功させたかった。"
"10011070-74-ミチル" = "あんなに純粋な憧れを持ったイズナと、"
"10011070-75-ミチル" = "何も知らなかったのに巻き込んじゃったツクヨ……私は、あのふたりに対する責任がある。"
"10011070-76-ツクヨ" = "あなたがツクヨ？"
"10011070-77-ミチル" = "！！"
"10011070-78-ツクヨ" = "もし良かったら……忍術研究部に入らない？"
"10011070-79-ミチル" = "二人に胸を張れる、そんな先輩になりたかった……。"
"10011070-80-ミチル" = "最悪の場合……このまま公演が失敗して、チャンスが無くなるだけならまだ良い。"
"10011070-81-ミチル" = "でも私が通報を躊躇ったせいで……魑魅一座に誘拐されたあの子は、"
"10011070-82-ミチル" = "今も泣いてるかもしれない。辛い目に、遭ってるかもしれない。"
"10011070-83-ミチル" = "全部、私のせいで……。"
"10011070-84-ミチル" = "もしこれが世間に知られたら、イズナもツクヨも、何もしてないのに後ろ指を指されるかもしれない。「忍術研究部」に関わってたってだけで。"
"10011070-85-ミチル" = "私の我儘のせいで、たくさんの人に迷惑が掛かってる。"
"10011070-86-ミチル" = "イズナも、ツクヨも……"
"10011070-87-ミチル" = "全部知ったら、きっとガッカリすると思う。全部、私が怖がってたせいで、こんなことに……。"
"10011070-88-ミチル" = "私は、もう……"
"10011070-89" = "[s] \"……足、治ったかも！！\""
"10011070-90-ミチル" = "せ、先生殿！？今、すごい真面目な話をしてたんだけど！？"
"10011070-91-ミチル" = "アニメでよくある、メインヒロインが大事な悩みを暴露する9話か10話あたりのシーンだったんだけど！！？"
"10011070-92-ミチル" = "それをそんな、軽く……！"
"10011070-93-ミチル" = "もう泣いちゃいそうだよ！いやもう半分くらい泣いてるけど……！じゃなくて！"
"10011070-94" = "[s] \"「申請書」を出さなかったのは、怖かったから？\""
"10011070-95-ミチル" = "……っ。"
"10011070-96-ミチル" = "そ、それはそう！正式な申請書なんて、出せるわけがないじゃん……！"
"10011070-97" = "「忍者って何？」って、「忍術研究部って何？」って、それが普通の反応でしょ！"
"10011070-98" = "アニメや漫画の話って思われて当然……！"
"10011070-99" = "そんな部活の推薦書なんて、誰にも頼めない……！"
"10011070-100" = "誰かが認めてくれるなんて、思えなかった……。"
"10011070-101" = "下手に何かを言い出したら後ろ指を指されたり、バカにされたりするかもだし……"
"10011070-102" = "私だけならまだしも、"
"10011070-103" = "あの二人は……！"
"10011070-104" = "[ns5] \"そこから先は、私が勝手に同意できることじゃないかな。\"\n[ns6] \"その答えを知ってるのは、あの二人だけじゃないかな。\""
"10011070-105-ミチル" = "せ、先生殿……？"
"10011070-106" = "[s] \"さて、そろそろ行こっか。後悔先に立たずって言うからね。\""
"10011070-107-ミチル" = "……うん。"
"10011070-108-ミチル" = "とりあえず、ここを抜け出さないと。"
"10011070-109-ミチル" = "……ありがとう、先生殿。"
"10011070-110" = "[s] \"どういたしまして……あ、ちょっとメイクよれてるよ。\""
"10011070-111-ミチル" = "ぬあぁっ！？"
"10011070-112-ミチル" = "い、今の流れから、普通レディーにそんなこと言う！？"
"10011070-113-ミチル" = "全くもう……。"
"10011070-114-미치루01" = "とにかく何の話をするにせよ、ここを抜け出さないと始まらないかー……。"
"10011070-115-ミチル" = "でもこれ、てきとうに進んだところで……。"
"10011070-116-ミチル" = "……あれ？"
"10011070-117" = "[s] \"どうしたの？\""
"10011070-118-ミチル" = "この廊下、この間取り、"
"10011070-119-ミチル" = "見たことある……。"
"10011070-120-ミチル" = "もしかしてこれ、「かまぼこ突風伝」……？"
"10011070-121-ミチル" = "分かる、全部覚えてる……！"
"10011070-122-ミチル" = "先生殿、こっち！"
"10011070-123" = "[ns] \"うん、行こう。\""
"10011070-124-ミチル" = "やっぱりこれ、「かまぼこ突風伝」の忍者屋敷そのままだ……！"
"10011070-125-ミチル" = "っていうかこれ、著作権的に大丈夫なの！？"
"10011070-126" = "[s] \"観光地にはよくあるよね。もしかしたらコラボしてるとか……。\""
"10011070-127-ミチル" = "うう、後で担当者を問い詰めないと！でもそれより……"
"10011070-128-ミチル" = "あっ、お疲れ様ー！"
"10011070-129" = "[s] \"あれ、カエデ？\""
"10011070-130-カエデ" = "もー。ふたりともルール説明が終わる前に行っちゃうから、困っちゃったよ。"
"10011070-131-カエデ" = "さて、じゃあ今さらだけどあらためてルール説明！"
"10011070-132-ミチル" = "このトリックハウスを抜けた人には、挑戦権が与えられるの！"
"10011070-133-ミチル" = "挑戦権……？"
"10011070-134-カエデ" = "そう、挑戦権！つまり……"
"10011070-135-傭兵バイトA" = "私カエデに対して、挑戦を申し込める権利だよ！"
"10011070-136-傭兵バイトA" = "私に勝てたら晴れてクリア！それじゃあ行っくよー！"
"10011070-137-ミチル" = "結局そうなるんじゃん！？"
"10011070-138" = "[s] \"まあ、そういうものだよね。\""
