[translation]
"10011080-1" = "第8話;せき止めていたもの"
"10011080-2" = "[ns] \"中止って……。\""
"10011080-3-カホ" = "遅まきながら状況は把握しました。"
"10011080-4-カホ" = "よりによってこの交流会で、こんなことが起こるだなんて……"
"10011080-5-カホ" = "どうしてこのタイミングまで誘拐の件についての連絡が無かったのか、お伺いしたいところではありますが……。"
"10011080-6-ミチル" = "うっ……そ、それは……！"
"10011080-7-カホ" = "それについては一旦、不問といたします。色々と頑張ってくださったような感じもありますし。"
"10011080-8-カホ" = "しかしこの件は、一旦ここまでです。"
"10011080-9-ツクヨ" = "手を引いて、という、ことですか……？"
"10011080-10-カホ" = "はい。幸いにも、逃走中の「魑魅一座・気まぐれ流」の現在地は把握できています。"
"10011080-11-カホ" = "百花繚乱も召集済みです。以後は陰陽部の方で受け持ちますので、"
"10011080-12-カホ" = "それでは……"
"10011080-13-イズナ" = "ま、待ってください！"
"10011080-14-イズナ" = "そうです、まだ公演が、失敗したわけでは……！"
"10011080-15-イズナ" = "みんなで、力を合わせて、ここまで来たんです。あとは魑魅一座さえ、捕まえられれば……！"
"10011080-16-カホ" = "その心意気は結構ですが……それは本当に、全員の総意なのですか？"
"10011080-17-カホ" = "肝心な方だけは、何も口にされてない気がしますが。"
"10011080-18-ミチル" = "……！"
"10011080-19-カホ" = "……ふう。"
"10011080-20-カホ" = "外部的にはまだ公演が続いてることになっていますが、"
"10011080-21-カホ" = "正直に申し上げます。"
"10011080-22-カホ" = "すでに公演は失敗です。"
"10011080-23-カホ" = "その後始末を、正式な部活でもない忍術研究部の皆さんに任せるわけにはいかないのです。"
"10011080-24-カホ" = "ですから、ここで手を引いてください。"
"10011080-25-カホ" = "正式な部活になる方法でしたら、"
"10011080-26-カホ" = "他にもあるでしょう。"
"10011080-27-ミチル" = "うっ……！"
"10011080-28-ミチル" = "……カホの、言う通りかもしれない。"
"10011080-29-イズナ" = "部長……？"
"10011080-30-ツクヨ" = "……。"
"10011080-31" = "[ns] \"ミチル……。\""
"10011080-32-ミチル" = "最初から、全部私のワガママのせいだった。私が欲張ったせいで……。"
"10011080-33-ミチル" = "ごめん、みんな……カホも、先生殿も……。"
"10011080-34-ミチル" = "こんなことに巻き込んで……。"
"10011080-35-ミチル" = "私のせいであの子も……イブキも、泣いてるかもしれない。"
"10011080-36-ミチル" = "私が、バカなことを考えたせいで……"
"10011080-37-ミチル" = "だから、ここでもう終わ――"
"10011080-38-ツクヨ" = "……ダメです！"
"10011080-39-ツクヨ" = "カホさんの、仰ることは……間違ってないかも、しれません。"
"10011080-40-ツクヨ" = "私には、分からないことばっかりです……まだ、忍者のことも、今回のことも……。"
"10011080-41-ツクヨ" = "申請書の件も……どうしてそれを、私や、イズナちゃんに言ってもらえなかったのかも……。"
"10011080-42-ツクヨ" = "私はただ、身体が大きいだけだから……できないことだらけで、分からないことだらけです！"
"10011080-43-ミチル" = "ツクヨ……。"
"10011080-44-ミチル" = "ですがそんなの、今はどうでも良いんです……！だって、私たち、約束したじゃないですか……！"
"10011080-45-ツクヨ" = "約束……？"
"10011080-46-ミチル" = "イブキちゃんに、怖がらないでって――"
"10011080-47-ツクヨ" = "「何があっても絶対助けに行く」って！"
"10011080-48-ミチル" = "……！"
"10011080-49-ツクヨ" = "忍者の鉄則その参！「忍者とは、一度交わした約束は――"
"10011080-50-イズナ" = "――必ず守るもの」、です！"
"10011080-51-ツクヨ" = "だから、先生……！"
"10011080-52" = "[s] \"うん。\""
"10011080-53-カホ" = "引き下がれない、と……仕方ありませんね。"
"10011080-54-カホ" = "ならばこちらも、実力行使とさせていただきます。"
