[translation]
"22140-1" = "第14話;要塞都市エリドゥ"
"22140-2-アカネ" = "思ったより早く現れてくれましたね。"
"22140-3-カリン" = "私たちがここに来る事は最初からお見通しだったというわけだ。"
"22140-4-トキ" = "はい。リオ様はすべて把握されておいでです。"
"22140-5-トキ" = "C&Cの判断も、その動きも――"
"22140-6-トキ" = "そしてもちろん――先生のねらいも、全て。"
"22140-7-トキ" = "ですので、僭越ながら申し上げます。#n――これ以上の抵抗は無意味です。大人しく投降をお願い致します。"
"22140-8-カリン" = "ほう……なるほど。"
"22140-9-アスナ" = "う～ん、それはちょっと難しいかなぁ？"
"22140-10-トキ" = "……！？"
"22140-11-アスナ" = "わっ、ビックリした！"
"22140-12-アカネ" = "あら、この程度では相手にもなりませんか。"
"22140-13-カリン" = "あ、アカネ……？"
"22140-14-トキ" = "……[ruby=むろかさ]室笠[/ruby]アカネ先輩。"
"22140-15-トキ" = "……戦闘では爆発物を利用した広域制圧を得意とする――"
"22140-16-トキ" = "――C&Cの要注意人物。"
"22140-17-アカネ" = "ふふ、初対面の後輩にそう言われると少し照れくさいですね。"
"22140-18-アカネ" = "先程のは、あくまでも挨拶のつもりだったのですが……。"
"22140-19-トキ" = "……。"
"22140-20-アカネ" = "はじめまして後輩さん。#nトキ……でしたね？"
"22140-21-アカネ" = "先日は部長が大変お世話になったと伺いました。"
"22140-22-アカネ" = "それに……投降しろという丁寧なご勧告まで頂くなんて……。"
"22140-23-アカネ" = "ふふ、あなたがリオ会長のボディーガードだということは伺っていましたが……#nまったく。"
"22140-24-アカネ" = "……C&Cを、見くびってもらっては困りますね。"
"22140-25-トキ" = "……！"
"22140-26-アカネ" = "目には目を、歯には歯を。本日はそのために来ておりますから。"
"22140-27-アスナ" = "……もちろんここで大人しく投降するのでしたら、水に流す事もできますよ？"
"22140-28-トキ" = "……それはできません。"
"22140-29-トキ" = "私はリオ様から命令を受けております。"
"22140-30-トキ" = "「指示に背いて行動しているC&Cを制圧せよ」と……。"
"22140-31-トキ" = "そのため、この場から退く事はできません。"
"22140-32-アスナ" = "ふ～ん、真面目ちゃんなんだね、トキちゃんは♪"
"22140-33-カリン" = "想定通りの反応だ。"
"22140-34-トキ" = "C&Cは秘密エージェント組織……。"
"22140-35-トキ" = "最初は、潜入によってこちらを[ruby=かくらん]撹乱[/ruby]すると踏んで、備えておりましたが……"
"22140-36-トキ" = "まさかこんな正面からいらっしゃるとは……。"
"22140-37-トキ" = "……想定外でした。#nですが、私がここにいる事もあなた方の作戦の内なのでは？"
"22140-38-アスナ" = "……そうなのか？"
"22140-39-アスナ" = "あはは♪そういうのじゃないかなぁ～？"
"22140-40-アカネ" = "あら、そうですねぇ……私たちとしても想定外ですよ。"
"22140-41-トキ" = "――誤魔化そうとしても無駄です。"
"22140-42-トキ" = "すでに先輩方の思惑など分かっております。"
"22140-43-トキ" = "ネル先輩と先生がおりませんね。"
"22140-44-トキ" = "つまり、そういう作戦なのでしょう？#n先輩方は私の足止めを任されている。"
"22140-45-トキ" = "それはある意味で正しいです。リオ様の「武装」を纏った私との正面対決を避け、"
"22140-46-トキ" = "その間にミレニアムの最強戦力であるネル先輩を自由にさせる――"
"22140-47-トキ" = "それであれば、ええ……たしかに勝算はあるでしょう。"
"22140-48-ネル" = "誰に勝算があるって？"
"22140-49-アスナ" = "あははっ！遅かったじゃん部長！"
"22140-50-トキ" = "ネル……先輩が何故……ここに……？"
"22140-51-ネル" = "あぁ？んなの決まってんだろ。"
"22140-52-ネル" = "リベンジマッチだよ。"
"22140-53-トキ" = "リベンジ……？"
"22140-54-ネル" = "あたしが別行動してたら、てめぇは絶対止めに来るだろ？"
"22140-55-ネル" = "面倒なのはごめんだからよぉ。"
"22140-56-ネル" = "それなら、チビを助けに行くのは――"
"22140-57-ネル" = "てめぇを倒した「後」でも、遅くねぇって事だ。"
"22140-58-ネル" = "おい、後輩。この間はよくもやってくれたな。"
"22140-59-ネル" = "先輩に楯突いたらどうなんのか、じ～っくり教えてやるよ。"
"22140-60-トキ" = "……！！"
"22140-61-トキ" = "対応、開始。"
"22140-62-ネル" = "は！いいぜ！やってやろうじゃねーか！"
"22140-63-コトリ" = "これで……！"
"22140-64-ヒビキ" = "邪魔なドローンは、全部、倒した……！"
"22140-65" = "[ns] \"みんな、気を引き締めて！そろそろ地上だよ……！\""
"22140-66-モモイ" = "よーーし！外に出れた！"
"22140-67-モモイ" = "それで、ここからどこに向かえばいいの？"
"22140-68-ハレ" = "アリスがいるのはおそらくエリドゥの中心部……。"
"22140-69-ハレ" = "そう、この中央にあるタワーだよ。"
"22140-70-ハレ" = "現在地からルートを算出しました。#n左手にある大通りをまっすぐ北に進めば辿り着けます。"
"22140-71" = "[ns] \"サポートありがとう。じゃあ、行こうか。"
"22140-72-モモイ" = "どいたどいたー！！"
"22140-73-ハレ" = "道はこっちでナビするから。"
"22140-74-マキ" = "どんどん行っちゃおー！GOGO～！"
"22140-75" = "次回;罠"
