[translation]
"22150-1" = "第15話;罠"
"22150-2-アスナ" = "アスナ！いっくよ～！"
"22150-3-トキ" = "……！"
"22150-4-カリン" = "今だ！"
"22150-5-アカネ" = "無駄です！"
"22150-6-ネル" = "逃がすもんか！"
"22150-7-トキ" = "（……強力ですね）"
"22150-8-トキ" = "（エージェントとして複数人での戦闘に長けているC&Cは、連携がとても強い部活……）"
"22150-9-トキ" = "（息の合った戦術……他校の戦力と最も差別化されている点であり――）"
"22150-10-トキ" = "……その戦略に穴はない。"
"22150-11-トキ" = "それなら……。"
"22150-12-アカネ" = "……部長、これは…！"
"22150-13-アスナ" = "えっ？なにこれー！？#n地面がぐらぐらしてる！！"
"22150-14-カリン" = "それだけじゃない……アカネ、様子が変だ。"
"22150-15-アカネ" = "……建物が、動いている？"
"22150-16-ネル" = "ちょ……！？んだよこれ！？"
"22150-17-アカネ" = "部長……！！隔壁が……！"
"22150-18-ネル" = "揺れは……止まったのか？"
"22150-19-ネル" = "あいつらは……？"
"22150-20-トキ" = "この一帯の都市構造を変更し、他の先輩方と隔離させていただきました。"
"22150-21-ネル" = "は？んだよ、それ。"
"22150-22-トキ" = "「エリドゥ」は本来、侵入者を撃退する要塞の役割を兼ねておりますので。"
"22150-23-トキ" = "リオ様からいただいた権限によって、皆様を分断させていただいたのです。"
"22150-24-トキ" = "さあネル先輩、これであなたの勝率は限りなく低くなりました。"
"22150-25-ネル" = "…………。"
"22150-26-ネル" = "はぁ……勝率だの……何だの……"
"22150-27-ネル" = "――ふざけてやがる。"
"22150-28-マキ" = "え！？ちょ、ちょっと待って！今、通信の状態が……！"
"22150-29-コタマ" = "これは……。"
"22150-30-？？？" = "ヴェリタス……やはり貴女たちだったのね。"
"22150-31-？？？" = "流石あの「ヒマリ」の後輩なだけあるわ。"
"22150-32-マキ" = "え？だ、誰！？"
"22150-33-ユズ" = "ヴェリタスの通信が……"
"22150-34" = "[s] \"途絶えてしまった……。\""
"22150-35-リオ" = "予想はしていたけれど……本当にここまで来たのね、先生。"
"22150-36" = "[s1] \"リオ……。\"\n[s2] \"君を止めに来たよ。\""
"22150-37-リオ" = "……そう。"
"22150-38-リオ" = "……そう。"
"22150-39-リオ" = "やはり、あの時の私の言葉と行動だけでは貴方を……。"
"22150-40-リオ" = "そして、その子たちを説得できなかったのね。"
"22150-41-リオ" = "…………先生。"
"22150-42-リオ" = "トロッコ問題をご存知かしら？"
"22150-43-ミドリ" = "トロッコ……？"
"22150-44-ユズ" = "……問題？"
"22150-45-リオ" = "簡単なお話よ。"
"22150-46-リオ" = "故障し、止まる事ができなくなってしまった列車がレールの上を走っている時。#n大多数を生かすために一人を犠牲にするか――"
"22150-47-リオ" = "それとも、一人を生かすために大多数を犠牲にするか――#nそういう選択を迫る問題。"
"22150-48-リオ" = "そう。誰かがレバーを引く役割を担わなければならない。"
"22150-49-リオ" = "そして……私は喜んでその役を引き受けようとしているだけ。"
"22150-50-リオ" = "悪意も敵意も、端から持ち合わせていない。#n私はただ――"
"22150-51-モモイ" = "もう！分かんないよ！！#n難しい話はいいから、アリスを返して！！"
"22150-52-リオ" = "あら、貴方は……。"
"22150-53-モモイ" = "話は聞いたんだからね！"
"22150-54-モモイ" = "会長が意味わかんないこと言ってアリスを連れて行ったって！"
"22150-55-リオ" = "……意味不明な話などではないわ。"
"22150-56-リオ" = "他の誰でもない、#n「名もなき神々の王女」に攻撃された貴女なら分かるのではなくて？"
"22150-57-モモイ" = "分かんないよ！"
"22150-58-リオ" = "……！"
"22150-59-モモイ" = "私はただ、会長の元からアリスを連れ戻したいだけ！"
"22150-60-ミドリ" = "お姉ちゃん……。"
"22150-61-ユズ" = "モモイ……。"
"22150-62-モモイ" = "そもそもキヴォトスの脅威だとかなんとか理由をつけてアリスを誘拐するなんて、#nスケールが小さすぎるよ！"
"22150-63-モモイ" = "普段私が書いているシナリオの規模の方がず～っと大きい！"
"22150-64-モモイ" = "そんな話通じるわけ無いじゃん！"
"22150-65-リオ" = "……そうね。今すぐ貴女たちに納得してもらうのは難しいのでしょうね。"
"22150-66-リオ" = "……私自身、すぐに納得してもらえないということは、十分理解しているもの。"
"22150-67-リオ" = "――アバンギャルド君、発進。"
"22150-68-ミドリ" = "うわぁっ！？#nダサ……"
"22150-69-ミドリ" = "たしかに、あんまり可愛いデザインじゃないけど……"
"22150-70-リオ" = "……見た目は関係ないわ。"
"22150-71" = "[s] \"……本音がちょっと見えてるよ、リオ。\""
"22150-72-リオ" = "理解されないのなら、もういいわ。#nそのままで構わない。"
"22150-73-モモイ" = "う、うわああっ！？"
"22150-74" = "[ns] \"みんな気をつけて……来るよ！\""
