[translation]
"22155-1-ヒビキ" = "外見からは想像つかない火力してるね……。"
"22155-2-モモイ" = "見た目はすっごいダサいのに、めっちゃ強いよ！？どうしよう！？"
"22155-3" = "[ns1] \"一番大きな障害はトキになると思って、C&Cにお願いしたけど……。\"\n[ns2] \"まさかこんなところに伏兵が潜んでいたなんて……。\""
"22155-4-ヒビキ" = "最初にトキを連れていたのは、判断を鈍らせるためだったんだね……。"
"22155-5-ヒビキ" = "最初にトキを連れていたのは、判断を鈍らせるためだったんだね……。"
"22155-6-ウタハ" = "C&Cがいない今こそ……。"
"22155-7-ユズ" = "会長にとって……「先生」を制圧できるチャンス……。"
"22155-8-モモイ" = "えっ……じゃあ全部、会長の手のひらの上だったってこと！？"
"22155-9-ミドリ" = "最初から仕組まれていた罠だったんだ……。"
"22155-10-リオ" = "C&Cと先生を分断する――"
"22155-11-リオ" = "それも私の手ではなく、自らの決断によって。"
"22155-12-リオ" = "そうすれば、こちらの計画が伝わる可能性なんて万に一つもないですから。"
"22155-13-ウタハ" = "なるほど……どうやら、会長の方が一枚上手だったようだね。"
"22155-14-リオ" = "さあ、終わりにしましょう――アバンギャルド君。"
"22155-15" = "次回;チェックメイト"
