[translation]
"22210-1" = "第21話;その名が示すのは。"
"22210-2" = "[ns] \"ネル！頼んだよ！\""
"22210-3-トキ" = "……どのような攻撃であろうと、私の「武装」には通じません。"
"22210-4-トキ" = "そんな手負いの状態で、これ以上の抵抗は無意味です！"
"22210-5-ネル" = "………は、"
"22210-6-ネル" = "んなの、知るかよ。"
"22210-7-ネル" = "あたしはもう決めたんだ。"
"22210-8-ネル" = "ここで、てめぇを倒して……"
"22210-9-ネル" = "面倒なのはごめんだからよぉ。"
"22210-10-ネル" = "それなら、チビを助けに行くのは――"
"22210-11-ネル" = "てめぇを倒した「後」でも、遅くねぇって事だ。"
"22210-12-ネル" = "チビを連れ戻しに行くってなぁ！"
"22210-13-ネル" = "おら、後輩ども！#nあたしらのリベンジマッチだ！"
"22210-14-ネル" = "アスナ！！"
"22210-15-トキ" = "……！？"
"22210-16-アスナ" = "はーい！#nあははっ！突撃～～！"
"22210-17-トキ" = "こんな攻撃など……"
"22210-18-トキ" = "……！？全部、避けた……！？"
"22210-19-アスナ" = "うん！#n野生の勘？ってやつ？"
"22210-20-ネル" = "カリン。"
"22210-21-トキ" = "視野外からの……狙撃！"
"22210-22-トキ" = "その程度でやられる訳――"
"22210-23-ネル" = "……アカネ！このまま押し込むぞ！ぶっ壊しちまえ！"
"22210-24-アカネ" = "はい！部長！"
"22210-25-リオ" = "ドアを壊してタワー内部に侵入を……？"
"22210-26-リオ" = "一体、どうやって……？"
"22210-27-チヒロ" = "…………それって、言うほど簡単じゃないけど……。"
"22210-28-アスナ" = "そうですね。簡単というより……。"
"22210-29-アスナ" = "あははっ！#n作戦というには結構めちゃくちゃなんじゃない？"
"22210-30-ユズ" = "そ、そうですね……やっぱり、わたしの話はなかった事に……。"
"22210-31" = "いや、やろう。"
"22210-32-ネル" = "こ、こんな作戦をですか！？"
"22210-33-チヒロ" = "……大丈夫なの？#nさっき話したのは、結局仮説に過ぎないんだよ。"
"22210-34-ネル" = "は、んなもん分かってらぁ。#nだが、他の誰でもない「おでこ」が出した作戦だからな。"
"22210-35-ユズ" = "お、おでこ……？"
"22210-36-ネル" = "こいつは、どれだけピンチに陥ってようが、友達のためなら臆せず度胸を見せる。"
"22210-37-ネル" = "そんなヤツの作戦を、あたしが気に入らないわけねぇだろ？"
"22210-38-ネル" = "ネル先輩ってユズの事よく知ってるんだね！いつの間に仲良くなったの？"
"22210-39-モモイ" = "やっぱ……普段ユズとゲームでいっぱい戦ってるから？"
"22210-40-モモイ" = "なんで今その話が出てくんだよ！？"
"22210-41-アカネ" = "ご意向は分かりました。ですが部長、その傷ではやはり……"
"22210-42-ネル" = "あぁ？何言ってんだ？ここで無茶しないで、いつ無茶すんだよ？#nこいつらがかけてくれた期待には、ちゃんと応えなきゃな。"
"22210-43-ネル" = "こんくらい根性でなんとかなるっての。"
"22210-44-ネル" = "――んで、お前らは？別に無理に手伝えとは言わねぇ。"
"22210-45-アカネ" = "私たちは……"
"22210-46-アカネ" = "……仕方ないですね。リーダーの決定なら。"
"22210-47-アスナ" = "うん！部長が決めたことだし、従うよ～！"
"22210-48-チヒロ" = "……でも大丈夫なの？C&Cだけでその作戦を進めるだなんて……"
"22210-49-アカネ" = "ええ。部長がそう決めたのであれば、私たちは従うだけです。"
"22210-50-アカネ" = "……それに、また戦うことになるのでしたら、前回とは少し違う予定ですから。"
"22210-51" = "[s] \"みんながそう言うのなら……分かった。\""
"22210-52-チヒロ" = "……みんな、作戦に同意したんだね？"
"22210-53-チヒロ" = "作戦実行に適した場所を見つけたから……"
"22210-54-チヒロ" = "ナビを開始するよ――行こう！"
"22210-55" = "[ns] \"このまま真っ直ぐ……目標は目の前だよ！\""
"22210-56-リオ" = "（無謀だ）"
"22210-57-リオ" = "（これは絶対に、合理的な選択ではない）"
"22210-58-リオ" = "（C&Cはもちろん、シャーレの先生もすでに一度トキの「武装」に負けている。#n　それは不変の事実）"
"22210-59-リオ" = "（だから、合理的に考えれば……#n　自然と、次に取る作戦は正面突破ではなく絡め手になる）"
"22210-60-リオ" = "（けれど、もしもこれが……シャーレの[USERNAME]先生が編み出した作戦だったとしたら……？）"
"22210-61-リオ" = "トキ！主砲の使用を許可するわ！"
"22210-62-トキ" = "イエス、マム。"
"22210-63-チヒロ" = "中央タワーに電力が集まってる！みんな、気をつけ――"
"22210-64" = "[ns1] \"さっきの……あれは、レーザー……？\"\n[ns2] \"こんなものを……まだ隠していたの……？\""
"22210-65-リオ" = "（今のは一体なんだったのだろう……）"
"22210-66-リオ" = "（勝率やデータに基づく判断ではなく……）"
"22210-67-リオ" = "（嫌な予感がした……ただそれだけの理由で、判断を変更した……？）"
"22210-68-リオ" = "（そんな……私がそんな非合理的な選択をするはずが……#n　単純に感覚を勘違いしただけ）"
"22210-69" = "[s] \"……リオ。\""
"22210-70-リオ" = "……ここまでよ。"
"22210-71-リオ" = "「武装」を通じて確定した結果――#n　データで算出された未来は、誰も覆すことなどできない。"
"22210-72-リオ" = "シャーレの先生……貴方なら「武装」に敗れた時点で分かっていたはずよ。#n私たちに勝てる確率なんて、ゼロだということを。"
"22210-73-リオ" = "それなのに、何故私たちに挑んできたのか……理解ができないわ。"
"22210-74-リオ" = "僅かな勝機というものをどこかに見出していたのであれば、#nそんなものは無意味で、非合理きわまりない行動よ。"
"22210-75-リオ" = "もし、そんな些細な錯覚を理由に、満身創痍の生徒にこんな事をさせたのであれば……"
"22210-76-リオ" = "……心底、失望するよ。"
"22210-77" = "[s] \"それは……。\""
"22210-78-アカネ" = "先生は、そのような指揮をしておりません。"
"22210-79-リオ" = "アカネ？"
"22210-80-アカネ" = "いえ、そもそもその認識を最初から訂正する必要がありますね。"
"22210-81-アカネ" = "私たちは別に、勝率やデータを信じて戦ったわけではありません。"
"22210-82-リオ" = "……なに？"
"22210-83-アカネ" = "部長。"
"22210-84-ネル" = "あ？どうした、アカネ。"
"22210-85-アカネ" = "すでに申し上げた通り、#nチヒロさんが仰った作戦が成功する可能性は非常に低いです。"
"22210-86-アカネ" = "なのにそんな身体で……。"
"22210-87-ネル" = "知るか。"
"22210-88-ネル" = "勝率だの可能性だの、そんな細々とした事はどうでもいい。"
"22210-89-ネル" = "んなもんは、お前か先生に任せればなんとかなる。"
"22210-90-ネル" = "大事なのは「チビを助けたいか、否か」それだけだろ？"
"22210-91-アカネ" = "……ふふっ。"
"22210-92-アカネ" = "やはり、以前から思っていましたが……部長、少し変わりましたね。"
"22210-93-アカネ" = "……きっと、それは。"
"22210-94-アカネ" = "あの子たちと会った、あの日から……少しずつ。"
"22210-95-アカネ" = "それにしても……誘拐された友人を救うために冒険に出るだなんて。"
"22210-96-アカネ" = "私たち、まるで……。"
"22210-97-アカネ" = "――ゲームの主人公みたいですね。"
"22210-98-アカネ" = "大切な友人を救いたい……ええ、ただそれだけです。"
"22210-99-リオ" = "……。"
"22210-100-アカネ" = "あ、そういえばリオ会長。#nまさか忘れていませんよね？"
"22210-101-アカネ" = "――ネル先輩のもう一つの名前。"
"22210-102-アカネ" = "コールサイン・ダブルオー。"
"22210-103-アカネ" = "私たちミレニアムの「約束された勝利の象徴」ということを。"
"22210-104-トキ" = "…………！？"
"22210-105-ネル" = "とらえた。"
"22210-106-リオ" = "主砲を正面から浴びたのに動けるだなんて……！？"
"22210-107-ネル" = "あいにく、この間も似たようなのを食らったばっかでな！"
"22210-108-チヒロ" = "中央タワーの貨物エレベーターをハッキングしたよ！"
"22210-109" = "[ns] \"ネル！！今だよ！\""
"22210-110-リオ" = "エレベーター……？#nまさか、あの子たちの目的地って……！？"
"22210-111-ユズ" = "も、モモイが前に言ったアイデアなんだけど。"
"22210-112-モモイ" = "え！？私！？"
"22210-113-ユズ" = "エレベーターを活用したら……もしかしたら……。"
"22210-114-リオ" = "……！！！"
"22210-115-リオ" = "「武装」の欠点……！#nまさか、そんなやり方で……！？"
"22210-116-リオ" = "トキ！早くそこから出て！！あの子たちは……！"
"22210-117-リオ" = "エレベーターで「武装」の回避システムを麻痺させるつもりよ！！"
"22210-118-ネル" = "いや、遅ぇ。"
"22210-119-ネル" = "あたし、前に言ったことあったよな？"
"22210-120-ネル" = "あたしの間合いに入って勝てるヤツなんか、このキヴォトスのどこにもいないって。"
"22210-121-トキ" = "……。"
"22210-122-ネル" = "あ……てめぇには言ってなかったか？#nまぁ、どっちでもいいんだけど。"
"22210-123-チヒロ" = "加速させて！"
"22210-124-チヒロ" = "重力加速度を10倍に！！"
"22210-125-トキ" = "……回避システム麻痺。"
"22210-126-ネル" = "…………さて、と。"
"22210-127-ネル" = "これでチートは使えねぇ。#n正々堂々戦うとしようぜ、後輩？"
"22210-128-トキ" = "はぁ……終わりですか。"
"22210-129-ネル" = "ぺっ……"
"22210-130-ネル" = "ケッ、大したことねぇな。"
"22210-131-リオ" = "これが……"
"22210-132-リオ" = "ミレニアム最強の……"
"22210-133-リオ" = "ダブルオー……"
"22210-134" = "次回;王女のためのパヴァーヌ（１）"
