[translation]
"2003305-1" = "偉大な議長の休日"
"2003305-2" = "（次の休日、シャーレ近くのショッピングモールにやって来た）"
"2003305-3" = "[ns] \"今日はせっかくだし、お肉でも買って――ん？\""
"2003305-4" = "[ns] \"……あれは、マコト？\""
"2003305-5-マコト" = "うーん……これも違う。あれも……違うな。"
"2003305-6-マコト" = "……くしゅんっ。"
"2003305-7-マコト" = "どうなってるんだ……？同じ商品かと思えば、デラックスだとかインペリアルだとか……まさか期間限定版まであるとは……"
"2003305-8-マコト" = "はくしょん！"
"2003305-9-マコト" = "あぁ、このマコト様を惑わしてくるとは……"
"2003305-10-マコト" = "は……は、はくしょんっ！"
"2003305-11-マコト" = "ぐああ！もう少し分かりやすくならないのか！#n……ぐしゅんっ。"
"2003305-12" = "[s] \"マコト、こんなところで何してるの？\""
"2003305-13-マコト" = "ぬおわあぁぁぁぁぁ！？"
"2003305-14-マコト" = "……は、はくしょん！ゲホゲホゲホゲホッ！！！"
"2003305-15" = "[s] \"大丈夫！？\""
"2003305-16-マコト" = "ゲホッゲホッ……はぁ、はぁ……っ、ぐしゅん。"
"2003305-17-マコト" = "ゆったりとショッピングを楽しんでいるこの私に話しかけてくるなんて、どこの命知らずかと思いきや先生だったか。"
"2003305-18" = "[s] （ゆったり楽しんでいるようには見えなかったけど……）"
"2003305-19-マコト" = "……あぁ、ここで何をしてたのかって？"
"2003305-20-マコト" = "必要なものがあっ――"
"2003305-21-マコト" = "……あっ、っくしょん！"
"2003305-22-マコト" = "ぐずっ……ずずっ。"
"2003305-23-マコト" = "……必要なものがあって、ちょっと買い物に来ただけだ。"
"2003305-24" = "[s] \"マコトが自分で買い物に来るなんて、ちょっと意外だね。\""
"2003305-25-マコト" = "……ぐじゅんっ……ふぅ。"
"2003305-26-マコト" = "……リーダーたるもの、自ら動くのは当然だろう。"
"2003305-27-マコト" = "キキッ、そういう先生も買い物か？"
"2003305-28-マコト" = "……新発売のペロロ様グッズを見に来た、って？#n……このカバのことか？"
"2003305-29-マコト" = "……はっ……はっ、はっくしょん！"
"2003305-30-マコト" = "ペロロ様はカバじゃない……？#nよく分からんな。"
"2003305-31" = "[s1] \"そ、それよりマコトは何を買いに来たの？\"\n[s2] \"そのカゴに入ってるのって……\""
"2003305-32-マコト" = "キシシッ。そうだ、見ての通り猫用のおもちゃとおやつの「にゃ～る」だ。"
"2003305-33-マコト" = "全部、エンペラー・ライオンマル・ジュニア3世のためにな。"
"2003305-34" = "[s] \"ライオンマルって、たしか……\""
"2003305-35-マコト" = "そういえば、先生は会っていたか。"
"2003305-36-マコト" = "キキッ。舌が肥えているのか、適当な餌をやっても食べようとすらしない。#nそれで今日は、わざわざ私が買いに来たのだ。"
"2003305-37" = "[s] \"あっ、この間のモモトークは……すごく可愛がってるんだね。\""
"2003305-38-マコト" = "この私が、猫を可愛がっているだと？"
"2003305-39-マコト" = "何か勘違いしているな？"
"2003305-40" = "[s] \"……うん？\""
"2003305-41-マコト" = "この私がライオンマルを引き取ったのは、あくまでビジネスだ。"
"2003305-42-マコト" = "つまり、投資目的だな。ライオンマルは、いずれ万魔殿のシンボルとなる。"
"2003305-43-マコト" = "ライオンマルの内側には……凶暴な野生が眠っている。#nこいつは磨けば磨くほど光るに違いない。"
"2003305-44-マコト" = "育て上げて、いつ[ruby=パンデモニウム・ソサエティー]か万魔殿の[/ruby]代表、[ruby=はぬま]羽沼[/ruby]マコト様の忠実なお供に――"
"2003305-45-マコト" = "……はっくしょん！"
"2003305-46-マコト" = "……するのが、最終的な目標だ。"
"2003305-47-マコト" = "キキキッ……ぐすん……ずずっ、ライオンマルめ。"
"2003305-48-マコト" = "このまま面倒を見てやれば、いつか勇ましいライオンに成長するはず……！"
"2003305-49" = "[s] \"マコト、猫は大きくなってもライオンにはならないよ……\""
"2003305-50-マコト" = "はっくしょん！"
"2003305-51-マコト" = "キキッ、それは気合いが足りていないだけだな。"
"2003305-52-マコト" = "そうしてライオンマル専用の動画投稿チャンネルを作り……#n万魔殿を宣伝するためにこき使ってやるのだ！"
"2003305-53-マコト" = "さあ、どうだ先生よ。この私の壮大な計画を聞いた感想は。"
"2003305-54-マコト" = "万魔殿の勢いが増す前に協力しておいた方が賢明じゃないのか？"
"2003305-55-マコト" = "ここで私と手を組むのなら、まだ誰にも触れさせていないライオンマルの肉球を触る機会を与えよう。"
"2003305-56-マコト" = "ん？いくら何でも肉球に釣られはしない、だと？"
"2003305-57-マコト" = "キキッ。この写真を見れば、そうも余裕な態度でいられなくなるぞ？"
"2003305-58" = "[s] \"やっぱり可愛がってるよね……？\""
"2003305-59-マコト" = "そういう個人的な感情で……"
"2003305-60-マコト" = "は……ずずっ。"
"2003305-61-マコト" = "感情では――"
"2003305-62" = "[ns] \"マコト、大丈夫？何だか顔色が……\""
"2003305-63-マコト" = "は、は、はあっくしょん！"
"2003305-64-マコト" = "ゲホゲホッ……グフッ！？"
"2003305-65" = "[ns] \"ま……マコト！？\""
"2003305-66" = "ゲヘナ・病院"
"2003305-67-医者" = "猫アレルギーですね。"
"2003305-68-マコト" = "なっ……！？"
"2003305-69-マコト" = "は、は――"
"2003305-70-マコト" = "はくしょん！"
"2003305-71-マコト" = "はっっくしょん！！！"
"2003305-72" = "[s] \"…………やっぱり。\""
"2003305-73-マコト" = "いや……そんなわけが……"
"2003305-74" = "[s] \"マコト、ライオンマルを飼ってから何か変わったことは？\""
"2003305-75-マコト" = "変わったこと……うむ。#nライオンマルを触るたびに、肌が痒くなったり、鼻水が垂れたり……"
"2003305-76-マコト" = "くしゃみが止まらなくなったり、喉の痛みや咳が出たくらいだな。"
"2003305-77-マコト" = "まさか、その程度でこの私が猫アレルギーだと？#n診断が間違っているんじゃないか！？"
"2003305-78" = "[s] \"むしろ、どう考えても猫アレルギーだよ！？\""
"2003305-79-医者" = "軽度の症状なら、ある程度は抑えられますが……"
"2003305-80-医者" = "これほど重い場合は難しいでしょう。"
"2003305-81" = "[s] \"じゃあ、猫の飼育は……\""
"2003305-82-医者" = "はい、とても申し上げにくいのですが……"
"2003305-83-医者" = "アレルギー症状が酷い状態で、一緒に暮らすのは危険かと……"
"2003305-84-マコト" = "キキッ。"
"2003305-85-マコト" = "キキキッ、キキキキキッ……！"
"2003305-86-マコト" = "キャハハハッ…………"
"2003305-87-マコト" = "ゲホッゲホッ！！"
"2003305-88" = "[s] \"マコト……！\""
"2003305-89-マコト" = "……ぐっ。アレルギーがあるから、猫と一緒に暮らすのはやめろだと？"
"2003305-90-マコト" = "……そうはいかん。"
"2003305-91-マコト" = "一度引き取った以上、たとえアレルギーを引き起こそうと最後まで責任を持って世話をする。それが、この羽沼マコト様の信念だ！"
"2003305-92-マコト" = "先程の話は聞かなかったことにしよう。"
"2003305-93" = "[s] \"マコト、本当に大丈夫なの……？\""
"2003305-94-マコト" = "キシシッ、問題ない。もちろん、今までのように触れ合う頻度は減らそう。"
"2003305-95-マコト" = "しかし、この程度でマコト様の偉大な計画は崩れやしない！"
"2003305-96-マコト" = "ライオンマルを動画投稿サイトにデビューさせて、万魔殿の名を世に知らしめる立派な存在として育て上げてみせる。その日を楽しみにしているのだ、先生よ！"
"2003305-97" = "[s] \"マコトらしい計画だね、私も応援するよ。\""
"2003305-98-マコト" = "キキキッ！キキキキキッ！！！"
"2003305-99-マコト" = "………………ゲホゲホッゲホッ！"
"2003305-100" = "（それから数日後、シャーレで仕事をしていると……）"
"2003305-101" = "[ns] \"……マコト？\""
"2003305-102-マコト" = "不本意だが、ライオンマルの世話係は部員に任せることになった。"
"2003305-103-マコト" = "とはいえ、今後も欠かさず見守るとも。#n先生にも、奴の勇ましい姿を定期的に共有してやろうじゃないか。"
"2003305-104-マコト" = "今度こそ万魔殿に協力すると言うのなら……秘蔵の写真も送ってやるぞ？"
"2003305-105" = "[ns] \"……やっぱり、ちゃんと可愛がってるんだね。\""
"2003305-106" = "（そうして、マコトから送られてきたライオンマルの写真を見ながら、癒やしの時間を過ごした）"
