[translation]
"1004606-1" = "イズナと一緒に手を取り合って"
"1004606-2" = "（やはり触れてはいけなかっただろうかと思いつつ、イズナとの待ち合わせ場所へと訪れた）"
"1004606-3-イズナ" = "あっ、主殿！こっちです！こっち！"
"1004606-4" = "[ns] \"イズナ、お待たせ。\""
"1004606-5-イズナ" = "とんでもありません！"
"1004606-6-イズナ" = "えーっと、どうしましょうか？海でできること……"
"1004606-7-イズナ" = "むむむ、いっぱいあるはずなのに難しいですね……修行も良いですが、ここは……！"
"1004606-8-イズナ" = "今度は最初から忍術修行じゃなくて、"
"1004606-9-イズナ" = "夏のおいしいお店を探すとか、そんなことをしてみるのも……！"
"1004606-10" = "[s] \"今後のために、聞いておきたいんだけど……。\""
"1004606-11-イズナ" = "主殿、どうかしましたか？"
"1004606-12" = "[s] \"イズナは海で泳ぐの、嫌い？\""
"1004606-13-イズナ" = "！？"
"1004606-14" = "[s1] \"言いたくなかったら良いんだけど、避けてる気がして……。\"\n[s2] \"せっかくだしって気持ちもありつつ、何か理由があるのかなって。\""
"1004606-15-イズナ" = "そ、それは……"
"1004606-16" = "[s] \"ごめん、言いたくなかったら気にしないで。嫌なこと聞いてごめんね。\""
"1004606-17-イズナ" = "ち、違うんです主殿！嫌というわけではなく……！"
"1004606-18-イズナ" = "イズナはその、えっと……"
"1004606-19-イズナ" = "……"
"1004606-20-イズナ" = "う、うわあぁぁぁん！！"
"1004606-21" = "[s] \"い、イズナ！？\""
"1004606-22-イズナ" = "す、すみません！隠そうと思ったわけではないのですが……！"
"1004606-23" = "（その後、イズナから話を聞かせてもらった）"
"1004606-24" = "[ns] \"つまり、かなづち……？\""
"1004606-25-イズナ" = "は、はい……。"
"1004606-26-イズナ" = "イズナ、どうしても慣れることができなくて……。"
"1004606-27-イズナ" = "今まで何度か、挑戦はしてみたのですが……。"
"1004606-28-イズナ" = "こう、つい怖がってしまうと言いますか……。"
"1004606-29-イズナ" = "海水が目や口に入ると、何だかおっかなびっくりになってしまい……。"
"1004606-30-イズナ" = "ご、ごめんなさい主殿……！"
"1004606-31-イズナ" = "先に言っておけば良かったのに、イズナが誤魔化したせいで……。"
"1004606-32-イズナ" = "本当に、申し訳ありません……！"
"1004606-33" = "[s] \"いや、謝るようなことじゃ……\""
"1004606-34" = "[ns] \"あ、でも一つ気になったんだけど。\""
"1004606-35-イズナ" = "……？"
"1004606-36" = "[s] \"どうして誤魔化してたんだろう、って。\""
"1004606-37-イズナ" = "そ、それは……"
"1004606-38-イズナ" = "イズナはその、主殿に何度も……。"
"1004606-39-イズナ" = "キヴォトス最強の忍者になると、言っていたので……。"
"1004606-40" = "[s] \"うん。\""
"1004606-41-イズナ" = "キヴォトス最強を目指しておきながら、その、泳げないとなってしまったら……。"
"1004606-42-イズナ" = "えっと、つまりは……。"
"1004606-43-イズナ" = "あ、主殿に、ガッカリされてしまうのではと思い……それが、怖くて……。"
"1004606-44" = "[s3] \"……大丈夫だよ。イズナ。\"\n[s4] \"それだけのことで、イズナを判断したりはしないから。\""
"1004606-45-イズナ" = "そ、そうなんですか……？"
"1004606-46-イズナ" = "よ、良かったです……えへへ……。"
"1004606-47-イズナ" = "主殿に直接そう言っていただけると、安心します……！"
"1004606-48-イズナ" = "ですがイズナは同時に、一つの決心をしました！"
"1004606-49" = "[s] \"決心……？\""
"1004606-50-イズナ" = "はい！怖いことは怖いとしても、逃げてばかりでは何も変わりません！"
"1004606-51-イズナ" = "キヴォトスで一番の忍者を目指す者として……。"
"1004606-52-イズナ" = "やはり、いつかは乗り越えなくてはならないのです！"
"1004606-53" = "[s] \"っていうことは……？\""
"1004606-54-イズナ" = "ということで主殿、少々お待ちください！"
"1004606-55" = "[s] \"あ、うん……？\""
"1004606-56-イズナ" = "お待たせしました！！"
"1004606-57" = "[ns] \"これは……？\""
"1004606-58-イズナ" = "いつかはこんな日も、来るかもしれないと"
"1004606-59-イズナ" = "思ってました……。"
"1004606-60-イズナ" = "克服のため、いつかは正々堂々と戦わなくてはならない、と！"
"1004606-61" = "[s] \"なるほど、それは良い心意気。\""
"1004606-62-イズナ" = "そしてこれらは、そのための忍具です！"
"1004606-63-イズナ" = "ご覧ください主殿！"
"1004606-64-イズナ" = "不思議な形をしていますが、これは忍びが水の上を歩くのに使った道具です！"
"1004606-65-イズナ" = "そしてこの筒！"
"1004606-66-イズナ" = "こちらは忍びが、水中からでも息ができるように作られた竹筒です！"
"1004606-67-イズナ" = "さらにこちらは、忍びが水上を素早く移動するための――"
"1004606-68-イズナ" = "簡易型超電導スクリューモーター！"
"1004606-69" = "[s] \"よく分からないけどすごい！\""
"1004606-70-イズナ" = "たとえ力が及ばなくても、忍びには忍びなりのやり方があります！"
"1004606-71-イズナ" = "というわけでイズナは、これを使って水泳を克服してみようと思います！"
"1004606-72" = "（そして、イズナの特訓が始まった）"
"1004606-73-イズナ" = "まずはこの、[ruby=みずぐも]水蜘蛛[/ruby]から！"
"1004606-74-イズナ" = "ではイズナ、参ります！"
"1004606-75" = "[ns] \"イズナーーー！？\""
"1004606-76-イズナ" = "ぜ、"
"1004606-77-イズナ" = "全然立てませんでした……！"
"1004606-78-イズナ" = "イズナの修行が、まだまだ足りないということでしょうか！？"
"1004606-79" = "[s] \"ミレニアム製でもない限り、そういうので立つのは無理じゃないかな……。\""
"1004606-80-イズナ" = "くっ……しかし、イズナは諦めません！"
"1004606-81-イズナ" = "次は、この竹筒で……！"
"1004606-82-イズナ" = "イズナ！参ります！"
"1004606-83-イズナ" = "（ブクブクブク……）"
"1004606-84" = "[s] \"イズナーーーーー！？！？\""
"1004606-85-イズナ" = "ぷはぁっ！"
"1004606-86-イズナ" = "あ、主殿……"
"1004606-87-イズナ" = "水中で目を開けるのって大変なのですね！？"
"1004606-88-イズナ" = "目が痛くて、竹筒を手放してしまいました……。"
"1004606-89" = "[s] \"そ、そっか……とりあえず目を洗っておいで……。\""
"1004606-90-イズナ" = "い、イズナは諦めません！次こそは……！"
"1004606-91" = "（そうしてイズナは何度も挑戦してみたものの……）"
"1004606-92-イズナ" = "うわぁぁん、主殿ー！？"
"1004606-93" = "（残念ながら、ことごとく失敗に終わってしまった）"
"1004606-94-イズナ" = "ぐすん……どうやら忍具で海を克服するのは、難しいようです……。"
"1004606-95-イズナ" = "イズナは、このままなのでしょうか……。"
"1004606-96-イズナ" = "これではイズナ、キヴォトス最高の忍者には……"
"1004606-97" = "[s] \"イズナ、泳ぐ練習してみない？"
"1004606-98-イズナ" = "……え？"
"1004606-99" = "[s5] \"忍具や忍術で克服できないとしても……。\"\n[s6] \"それなら、泳ぎを学んでみるのはどうかなって。\""
"1004606-100-イズナ" = "主殿が、教えてくださる……ということですか？"
"1004606-101" = "[s7] \"うん、それなりに泳げるから。任せて。\"\n[s8] \"イズナのために全力を尽くすよ！\""
"1004606-102-イズナ" = "は、はいっ……！"
"1004606-103-イズナ" = "で、では、お願いします！主殿……！"
"1004606-104" = "（そうして、特に忍術は関係ない、純粋な水泳のレッスンが始まった）"
"1004606-105-イズナ" = "えっと、主殿の手を握って良いのですか？"
"1004606-106" = "[s] \"うん。それでまず顔を水につけて、水に慣れることから。\""
"1004606-107-イズナ" = "は、はい！ではイズナ、参ります……！"
"1004606-108" = "お手を拝借し、顔を……！"
"1004606-109" = "顔を……。"
"1004606-110" = "あの……主殿の手は、握ったままで……！？"
"1004606-111" = "[s] \"うん、何かやりにくかったりする？\""
"1004606-112" = "い、いえ！ではイズナ、参ります！"
"1004606-113" = "[ns] \"どう？\""
"1004606-114-イズナ" = "ぷはっ……は、はい、何とか……。"
"1004606-115-イズナ" = "それよりも、その……。"
"1004606-116" = "[s] \"じゃあ、次はバタ足かな。\""
"1004606-117-イズナ" = "は、はいっ！"
"1004606-118" = "（そうして、少しずつレッスンは続いていく）"
"1004606-119" = "（手を握って顔を水につけることから始め、続けてバタ足）"
"1004606-120" = "（そこから息継ぎの練習などを行い……）"
"1004606-121" = "（一つずつ、必要な要素を教えていった）"
"1004606-122" = "[ns] \"じゃあ私の方で支えるから、水中で身体を横にしてみよっか。\""
"1004606-123" = "ひゃぅっ！？"
"1004606-124" = "[ns] \"い、イズナ！？大丈夫！？\""
"1004606-125" = "だ、大丈夫です……その、急に腰だったので……。"
"1004606-126" = "[ns] \"いつの間にこんな時間か……この辺りにしておく？\""
"1004606-127-イズナ" = "は、はい……ありがとうございました、主殿……。"
"1004606-128" = "[s] \"うん、お疲れ様。じゃあ帰ろうか。\""
"1004606-129-イズナ" = "は、はいっ……！"
"1004606-130" = "（そうして、リゾートへと戻る途中……）"
"1004606-131-イズナ" = "主殿と……。"
"1004606-132-イズナ" = "何だかまだ……"
"1004606-133-イズナ" = "………。"
"1004606-134" = "[s] \"何だかごめんね。\""
"1004606-135-イズナ" = "は、はいっ……！？"
"1004606-136" = "[s9] \"無理に付き合わせちゃったんじゃないかなって思って\"\n[s10] \"珍しくイズナ、すごい疲れてそうだなって……。\""
"1004606-137-イズナ" = "そ、そんな……！"
"1004606-138-イズナ" = "え、歩き方、ですか……？"
"1004606-139-イズナ" = "そ、そうでしょうか……イズナ、変ですかね……？"
"1004606-140" = "[s11] \"まあ基礎の基礎は教えられたから、もう大丈夫だと思う。\"\n[s12] \"あとはイズナひとりでも、気が向いた時に練習してもらえれば。\""
"1004606-141-イズナ" = "それはつまり……。"
"1004606-142-イズナ" = "主殿と練習するのは、今日で終わりという……？"
"1004606-143" = "[s] \"あ、日も落ちてきたね。早めに――\""
"1004606-144-イズナ" = "そ、そんなことはありません！"
"1004606-145-イズナ" = "違うんです、主殿！"
"1004606-146" = "[s] \"イズナ……？\""
"1004606-147-イズナ" = "無理にだなんてことはありません！"
"1004606-148-イズナ" = "疲れたからではないんです……！"
"1004606-149-イズナ" = "イズナは、イズナは……！"
"1004606-150" = "[wa:800]― （どうしてでしょうか……"
"1004606-151" = "― 主殿が、[wa:1200]水泳を教えてくれると[wa:1200]言った時から……）"
"1004606-152" = "― （イズナの心臓、[wa:1900]すごく……"
"1004606-153" = "― ドキドキしています……)"
"1004606-154" = "[wa:900]― （先ほど[wa:1250]主殿が握ってくれた、"
"1004606-155" = "[wa:100]― イズナの[wa:650]手……"
"1004606-156" = "[wa:100]― 他にも[wa:1150]主殿に触れられた場所が、"
"1004606-157" = "[wa:150]― なんだか[wa:400]少し熱くて……)"
"1004606-158" = "[wa:850]― あの、[wa:1200]主殿。[wa:1500]先ほどは[wa:750]その、"
"1004606-159" = "― 少し[wa:450]バタバタしてしまいましたが……。"
"1004606-160" = "― 今日一日……"
"1004606-161" = "― イズナはすごく楽しくて、[wa:2000]幸せでした！"
"1004606-162" = "― ですから、[wa:750]その……"
"1004606-163" = "[wa:150]― 何と[wa:550]言いますかえっと……！"
"1004606-164" = "[wa:1000]― 少しだけ、[wa:1650]我儘を[wa:750]言ってもよろしければ……"
"1004606-165" = "― 今度また……"
"1004606-166" = "[wa:100]― もう一度[wa:1200]泳ぎ方を、[wa:750]教えていただけないでしょうか？"
"1004606-167" = "[ns] \"……それはもう、喜んで。\""
"1004606-168" = "― えへへっ……"
"1004606-169" = "― はい、[wa:950]ありがとうございます！"
"1004606-170" = "― イズナのこと、"
"1004606-171" = "― これからも[wa:350]よろしくお願いしますね！[wa:1800]主殿！"
"1004606-172" = "（そうして夕焼けにきらめく街にも負けないくらい、輝く笑みを浮かべるイズナと一緒に）"
"1004606-173" = "（ゆっくりと、色んな話をしながら帰るのだった）"
