[translation]
"2300402-1" = "職人魂"
"2300402-2" = "エンジニア部・作業室"
"2300402-3" = "ウタハにお願いしていたペン立てを受け取りに、エンジニア部を訪れた。"
"2300402-4-ウタハ" = "違うな……このままではダメだ……。"
"2300402-5" = "[s1] \"来たよ、ウタハ。\"\n[s2] \"ペン立てはどう？\""
"2300402-6-ウタハ" = "ああ、先生。いらっしゃい。#nもう少し待ってもらえるかな？思っていたより時間がかかりそうで……。"
"2300402-7-ウタハ" = "ああ、先生。いらっしゃい。#nもう少し待ってもらえるかな？思っていたより時間がかかりそうで……。"
"2300402-8-ウタハ" = "ちょっとばかり予想外のトラブルが発生したんだ。"
"2300402-9" = "[s] \"大丈夫、ゆっくりでいいよ。\""
"2300402-10-ウタハ" = "ありがとう。……普段はこんなこと起きないのだけど、今日はなんだか機械の機嫌が悪いみたいだ。"
"2300402-11-ウタハ" = "まさか2回も失敗はしないと思うが……。"
"2300402-12" = "しばらくした後……。"
"2300402-13" = "出力が完了しました、確認してください。"
"2300402-14-ウタハ" = "……。"
"2300402-15" = "[s] \"すごい、想像以上にキレイにできてるね。じゃあありがたく……\""
"2300402-16-ウタハ" = "ダメだ……っ！"
"2300402-17" = "[s] \"ど、どうしたの……？\""
"2300402-18-ウタハ" = "私が作りたかったペン立てはこんなものじゃない。"
"2300402-19-ウタハ" = "この辺りを見てほしい。切断処理も甘いし、二重になっている部分が図面通りの曲面をきちんと再現できていない。"
"2300402-20-ウタハ" = "それに、耐久性も想像以上に良くない。これでは、22口径の弾丸すら跳ね返せないに違いない……。"
"2300402-21" = "[s3] \"だ、大丈夫だと思うけど……。\"\n[s4] \"ペン立てに防弾機能は必要ないんじゃないかな……？\""
"2300402-22-ウタハ" = "いや、たとえ先生がそうだとしても、私は納得できない。#nこんな中途半端では不良品と同じだ。"
"2300402-23-ウタハ" = "いや、たとえ先生がそうだとしても、私は納得できない。#nこんな中途半端では不良品と同じだ。"
"2300402-24-ウタハ" = "それに、こんな不良品を先生にプレゼントしたという事実が他の生徒たちに知られたら、私はもう恥ずかしくてミレニアムの中を歩くことができない……！"
"2300402-25" = "[s] \"そ、そういうものなのかな……。\""
"2300402-26-ウタハ" = "だが先生、安心してほしい。必ずや完璧なペン立てを作ってみせる――"
"2300402-27-ウタハ" = "エンジニア部の名にかけて！"
"2300402-28" = "しかしその後も失敗（？）を重ね、それでもウタハは妥協することなく、製作を続けた。"
"2300402-29" = "出力が完了しました、確認してください。"
"2300402-30-ウタハ" = "ダメだ……！"
"2300402-31" = "[s] \"今度はどこがダメなの？\""
"2300402-32-ウタハ" = "ここだ。表面に細かな傷のようなものが付いてしまっている。"
"2300402-33-ウタハ" = "やはり熱溶解積層法では限界があるのか……。"
"2300402-34-ウタハ" = "やり直しだ、もう一度製作方法から考え直してみよう。"
"2300402-35" = "[s] \"それくらいでいいからそろそろペン立てが欲しいな……。\""
"2300402-36" = "その後、さらに10個以上の試行錯誤の末、ようやくウタハの満足いくものができたのであった。"
