[translation]
"1002520-1" = "変わること、変わらないもの"
"1002520-2-シュン" = "こんにちは！お忙しいところありがとうございます。#nご迷惑ではありませんでしたか？"
"1002520-3" = "[s] \"ううん！全然暇だよ！\""
"1002520-4-シュン" = "それなら良いのですが……。"
"1002520-5-シュン" = "先生は、お忙しくても気を遣ってくださりそうで……。"
"1002520-6" = "[s] \"シュンに会えるなら、時間なんていくらでも作るから気にしないで。\""
"1002520-7-シュン" = "私にそんな言い聞かせるように仰っても……"
"1002520-8-シュン" = "それにしてもこんなに時間のある日は久しぶりです。"
"1002520-9-シュン" = "天気もいいし、風も気持ちいいし……。"
"1002520-10-シュン" = "ぼんやりと時間を過ごしてもいいって素敵なことですね。"
"1002520-11" = "[s] \"私もシュンと一緒にいられて嬉しいよ。\""
"1002520-12-シュン" = "も、もう！急にそんなことを！"
"1002520-13-シュン" = "先生は、ご自身が何を言ってるのか、ちゃんと自覚する必要があると思います！"
"1002520-14" = "[s] \"はーい！シュン教官。\""
"1002520-15-シュン" = "うぅ、またからかって……。"
"1002520-16" = "[s] \"ところで、シュンがしてるヘアピンは……？\""
"1002520-17-シュン" = "あ、これですか？"
"1002520-18-シュン" = "実はこれ、私が一番好きなヘアピンなんです。"
"1002520-19-シュン" = "リボンがついていて可愛いんですよ。"
"1002520-20-シュン" = "……ツインテール、好きなんです。"
"1002520-21-シュン" = "走ったりジャンプしたりすると、両側でサラサラ動く所も気に入っているポイントです。"
"1002520-22-シュン" = "実は……いつもの姿でつけているヘアピンも、"
"1002520-23-シュン" = "今のヘアピンに似たものを探したくらいです。"
"1002520-24" = "[s1] \"そこまで気に入っているヘアピンなら……。\"\n[s2] \"いつもの時も使えばいいんじゃないかな？\""
"1002520-25-シュン" = "うーん……ですが……大きさも合いませんし。"
"1002520-26-シュン" = "うーん……ですが……大きさも合いませんし。"
"1002520-27-シュン" = "ツインテールにリボンはちょっと恥ずかしくて……。"
"1002520-28-シュン" = "子どもの頃の思い出は、そのまま残しておいた方がいいのではないでしょうか？"
"1002520-29" = "[s] \"でも年齢関係なく、好きなのは変わらないものなんでしょう？\""
"1002520-30-シュン" = "えっと……。"
"1002520-31-シュン" = "……。"
"1002520-32-シュン" = "それじゃあ先生は、変わらないものってあると思いますか？"
"1002520-33" = "[s3] \"あると思うよ。\"\n[s4] \"変わるものがあれば、変わらないものもあるんじゃないかな。\""
"1002520-34-シュン" = "あはは。何ですか、それ。"
"1002520-35-シュン" = "あはは。何ですか、それ。"
"1002520-36-シュン" = "でも、そうですね……変わらないもの、好きなもの……。"
"1002520-37-シュン" = "えへへ。何か嬉しくなりました。"
"1002520-38-シュン" = "少し恥ずかしかったり、むずむずしたり……。"
"1002520-39" = "[s] \"大丈夫？アレルギーのお薬飲む？\""
"1002520-40-シュン" = "……。"
"1002520-41-シュン" = "今のは減点ですよ、先生！"
"1002520-42" = "[s] \"怒られてしまった……。\""
"1002520-43-シュン" = "もう、しゅんってなっても無駄ですよ！大目に見てあげませんからね！"
"1002520-44" = "きゃっ？何してるんですか？"
"1002520-45" = "えっ？拗ねたから「たかいたかい」？そ、それはそれでいいですけど！"
"1002520-46" = "[s] \"たかいたかい～たかいたかい～\""
"1002520-47" = "あはっ、くすぐったいです！#nい、いい加減降ろしてください！気持ちは嬉しいですけど……。"
"1002520-48-シュン" = "うーん……わかりました。"
"1002520-49-シュン" = "そういうことにします。"
"1002520-50-シュン" = "別にそもそも拗ねてないんですけどね……。"
"1002520-51-シュン" = "その代わり……。"
"1002520-52" = "[s] \"その代わり？\""
"1002520-53-シュン" = "後で……"
"1002520-54-シュン" = "大きい私がツインテールをしていても、からかっちゃダメですよ？"
"1002520-55-シュン" = "いいですね？"
