[translation]
"1300708-1" = "孤独じゃないグルメ"
"1300708-2" = "山海経高級中学校付近・中華街"
"1300708-3-ジュンコ" = "はあ～、ほんっとーに美味しかった！"
"1300708-4-ジュンコ" = "噂通り、この中華街の料理は何でも美味しい！"
"1300708-5-ジュンコ" = "チャーハンも、チャーシューも、肉まんも……全部すごかった！"
"1300708-6-ジュンコ" = "わざわざ遠くから来た甲斐があったわね、ふふっ。"
"1300708-7-ジュンコ" = "ん？お腹がいっぱいだから少し休んでから行きたい、って？"
"1300708-8-ジュンコ" = "ダメ！まだ半分も巡れてないんだから！"
"1300708-9-ジュンコ" = "頑張って回らないと、今日中にすべての料理が味わえないじゃん！"
"1300708-10-ジュンコ" = "うーん……でもたしかに、脂っこいものばかり食べたし……。"
"1300708-11-ジュンコ" = "あ、じゃあそこのカフェでちょっと休んでからにする？"
"1300708-12" = "[wa:2000]― え、[wa:1000]な、[wa:800]なに。[wa:1200]なんでそんな目で見るの？"
"1300708-13" = "― （……もう、[wa:1000]本当に……）"
"1300708-14" = "― ちょっと休んで、[wa:1500]また食べに行くんでしょ？[wa:2500]次は何食べる？"
"1300708-15" = "[wa:3000]― おいしー♪"
"1300708-16" = "― なに？[wa:1200]一緒に飲もうって！？"
"1300708-17" = "― 変なこと言わないで！[wa:1500]殺すよ！？"
"1300708-18" = "― （からかってるよね、[wa:1500]これ？[wa:1000]そうだよね？[wa:1500]ストロー、一本しかないのに……）"
"1300708-19" = "[wa:200]― （……でも先生なら……。[wa:1800]大丈……）"
"1300708-20" = "― ……やっ！！[wa:500]やっぱだめ！！"
"1300708-21-ジュンコ" = "ああ～いっぱい食べた～。"
"1300708-22-ジュンコ" = "今日一日、本当に大満足！美味しい料理もたくさん食べたし！"
"1300708-23-ジュンコ" = "それに、先生と二人っきりで食事できたし……。"
"1300708-24-ジュンコ" = "か、勘違いしないで！美味しい料理は一人でも十分美味しいから！"
"1300708-25-ジュンコ" = "でもやっぱり……一人で食べるより二人で食べた方がもっと……楽しい、し……。"
"1300708-26-ジュンコ" = "次もまた、一緒に、ご飯食べに行ってくれる？"
"1300708-27" = "[s] \"もちろん。\""
"1300708-28-ジュンコ" = "本当？約束だからね！絶対よ、絶対！"
"1300708-29" = "その後、嬉しそうなジュンコと一緒に学園に戻った。"
