[translation]
"2003602-1" = "最高の休暇"
"2003602-2" = "（セリカに呼ばれ、リゾートにやって来た）"
"2003602-3-セリカ" = "お待たせ、先生！#nよし、それじゃさっそく……。"
"2003602-4-セリカ" = "……うっ。"
"2003602-5-セリカ" = "その、先生……悪いんだけど、手伝ってくれないかな？"
"2003602-6-セリカ" = "ちょっと一人じゃ持ちきれなくて……。"
"2003602-7" = "[s1] \"もちろんだよ、手伝うね。\"\n[s2] \"こんなに何を持ってきたの？\""
"2003602-8-セリカ" = "大したものじゃないんだけどね。"
"2003602-9-セリカ" = "最高の休暇を送るためには必要かなって。#n食べ物や飲み物に、カメラ、サバイバルナイフ……"
"2003602-10-セリカ" = "あとはレジャーシートとかゴーグルとか……"
"2003602-11-セリカ" = "……冷静になってみたらすごい量ね。"
"2003602-12-セリカ" = "全部持っていく必要はなさそう、って？"
"2003602-13-セリカ" = "なに言ってるのよ！#n最高の休暇を送るためには、これでも足りないくらいなんだから！"
"2003602-14-セリカ" = "……違うって、何が？"
"2003602-15" = "[s3] \"最高の休暇と完璧な休暇は違うよ。\"\n[s4] \"それで疲れちゃったら、本末転倒じゃないかな？\""
"2003602-16-セリカ" = "確かに言われてみれば……"
"2003602-17-セリカ" = "って、今日は自分なりにちゃんと考えてきたの！"
"2003602-18-セリカ" = "いったん私に任せて、先生！"
"2003602-19-セリカ" = "……え？"
"2003602-20-セリカ" = "こんなにあっけなく引かれると、調子狂うわね……。"
"2003602-21-セリカ" = "べ、別に先生と言い合いがしたいわけじゃないけど！"
"2003602-22-セリカ" = "ま、まあ先生も同意してくれたってことで。"
"2003602-23-セリカ" = "さ、行くわよ！#n「最高の休暇」を過ごしに！"
"2003602-24" = "（こうしてセリカと最高の休暇を過ごすために、色々な場所を散策した）"
"2003602-25" = "[ns5] \"……どう？\"\n[ns6] \"良い場所だね。\""
"2003602-26-セリカ" = "ん～……確かに良い場所だけど……。"
"2003602-27-セリカ" = "なんというか、ありきたりのような……。"
"2003602-28-セリカ" = "最高の休暇を過ごすには、ちょっと物足りないかも。"
"2003602-29" = "[ns7] \"ここはどう？\"\n[ns8] \"少し雰囲気は違うと思うけど、どうかな？\""
"2003602-30-セリカ" = "うーん……。"
"2003602-31-セリカ" = "これ！って感じがしないのよね。#n海だからかな……？"
"2003602-32" = "[ns9] \"ここも良い場所じゃない？\"\n[ns10] \"海から離れてみたけど、今度はどう？\""
"2003602-33-セリカ" = "ううん……。"
"2003602-34-セリカ" = "確かに全部良い場所なんだけど……#n何が気になってるんだろ。"
"2003602-35-セリカ" = "これじゃ、先生をただ連れ回してるだけだし……。"
"2003602-36-セリカ" = "……うぅ、どうしよう。"
"2003602-37" = "（……結局、セリカが気に入る場所は見つからず、リゾートに戻ってきた）"
"2003602-38-セリカ" = "…………。"
"2003602-39-セリカ" = "えっと……その、先生。"
"2003602-40-セリカ" = "……ごめん。"
"2003602-41-セリカ" = "荷物を持たせた挙げ句、#n歩き回らせるだけになっちゃった。"
"2003602-42-セリカ" = "やっぱり、難しいわね。"
"2003602-43-セリカ" = "最高の休暇を過ごすのも……。"
"2003602-44-セリカ" = "……えっ？"
"2003602-45-セリカ" = "最高の休暇だった……？"
"2003602-46-セリカ" = "今日は一日中、#n私のせいで先生を当てもなく付き合わせちゃったのに……"
"2003602-47" = "[s11] \"最高の休暇と完璧な休暇は違うからね。\"\n[s12] \"休暇だからって、無理に何かする必要はないよ。\""
"2003602-48-セリカ" = "……はぁ。#nまた慰められちゃったわね。"
"2003602-49-セリカ" = "……え？#n慰めてくれたわけじゃないの？"
"2003602-50-セリカ" = "本気で言ってるって……。"
"2003602-51" = "[s13] \"おかげで楽しく過ごせたからね。\"\n[s14] \"こうやって、ゆっくりセリカと話せてるし。\""
"2003602-52-セリカ" = "……う～ん。"
"2003602-53-セリカ" = "先生がそう言うなら、良かったのかな……？"
"2003602-54-セリカ" = "確かに、海にも森にも行ったし、洞窟にも……。"
"2003602-55-セリカ" = "二人でお昼も食べて……。"
"2003602-56-セリカ" = "……そっか。"
"2003602-57-セリカ" = "うん……。"
"2003602-58-セリカ" = "……ふふっ。"
"2003602-59-セリカ" = "……私も、楽しかったわ。"
"2003602-60-セリカ" = "それじゃ、そろそろ帰りましょ！"
"2003602-61-セリカ" = "最高の休暇は帰るまで続くんだから！"
"2003602-62-セリカ" = "それと、今日だけで終わりだと思わないでよね？"
"2003602-63-セリカ" = "まだ満足してないし、明日も付き合ってもらうわ！"
"2003602-64-セリカ" = "約束よ？"
"2003602-65-セリカ" = "じ、じゃあ……またね！"
"2003602-66" = "（すごい慌てようのセリカは、荷物を忘れていった……）"
