[translation]
"11007-1-ワカモ" = "私はここまで、後は任せます。"
"11007-2-ユウカ" = "逃げられてるじゃない！？追うわよ！"
"11007-3-ハスミ" = "いいえ、生半可な行動をしてはなりません。私たちの目標はあくまでも、シャーレの奪還。"
"11007-4-ハスミ" = "このままシャーレのビルまで前進するべきです。"
"11007-5-ユウカ" = "……うん、まあいいわ。あいつを追うのは私たちの役目じゃないってことね。"
"11007-6" = "罠かもしれませんし。"
"11007-7-ハスミ" = "はい。建物の奪還を優先で。このまま引き続き、進むとしましょう。"
