[translation]
"10012035-1-ジャブジャブヘルメット団B" = "ちょっと、また負けちゃったじゃん！！せっかく応援部隊を連れて来たっていうのに～！！"
"10012035-2-ジャブジャブヘルメット団B" = "なんかこいつの様子変じゃない？なんでこんなボーっとしてんの！？"
"10012035-3-ワカモ" = "せ、先生……？先生がどうして……ここに……？"
"10012035-4-ワカモ" = "先生は……えっ……？あれ？"
"10012035-5-ワカモ" = "ワカモ、馬鹿！あんた何やってんの！"
"10012035-6-ラブ" = "ワカモってば！！"
"10012035-7-ジャブジャブヘルメット団A" = "完全に呆けてますけど。"
"10012035-8-ジャブジャブヘルメット団B" = "ま、まずは退却しましょうよ！連れ帰って、コイツがしっかりしたらまた来るとか……。"
"10012035-9-ジャブジャブヘルメット団B" = "あっ、イタタ、痛い！！"
"10012035-10-ジャブジャブヘルメット団B" = "やめて、もう分かったから！！"
"10012035-11-ラブ" = "ちっ……クソッ……！"
"10012035-12-ラブ" = "これで終わりだと思わないでよね！！"
"10012035-13-アヤネ" = "いったい誰だったんでしょうか……。"
"10012035-14-シロコ" = "セリカとホシノ先輩が言っていた……私たちのリゾートを奪おうとしていたやつらなのかも。"
"10012035-15-シロコ" = "……ね、先生？"
"10012035-16" = "[s1] \"大体はあってるけど……。\"\n[s2] \"ちょっと違うとこもあるけど……。\""
"10012035-17-アヤネ" = "そういえば、お一人、先生の名前を呼んでた方がいらっしゃいましたが……"
"10012035-18-アヤネ" = "そういえば、お一人、先生の名前を呼んでた方がいらっしゃいましたが……"
"10012035-19-アヤネ" = "もしかしてワカモという方はお知り合いだったり……？"
"10012035-20" = "[s3] \"えっと……話せば長くなるけど……。\"\n[s4] \"知らない方がいいかも……。\""
"10012035-21-シロコ" = "……。"
"10012035-22-シロコ" = "先生……。"
"10012035-23-シロコ" = "……あっ！！"
"10012035-24-シロコ" = "……アヤネ、どうしたの？"
"10012035-25-シロコ" = "釣竿が……道具が……"
"10012035-26-アヤネ" = "戦ってる間に、壊れてしまったみたいで……"
"10012035-27-シロコ" = "……？"
"10012035-28-シロコ" = "……！！！"
"10012035-29" = "（その後、落ち込んだシロコを慰めて、みんなでリゾートに帰った）"
"10012035-30" = "（リゾートに帰ってからも、シロコは釣竿のことを引きずっているようだった）"
