[translation]
"10012095-1-ノノミ" = "今日は本当にいろんな事がありましたね～☆"
"10012095-2-ノノミ" = "せっかく一等が当たったって喜んでたのに、めちゃくちゃな事ばっか……もう嫌……。"
"10012095-3-シロコ" = "セリカ、タダより高い物はないよ。"
"10012095-4-シロコ" = "そういうシロコ先輩だって、喜んで水着を用意してたじゃん！？"
"10012095-5-シロコ" = "それはそれ、これはこれ。"
"10012095-6-ホシノ" = "でもまぁ、なんとか帰れそうでよかった、よかった。"
"10012095-7-ホシノ" = "先生も、わざわざ時間を割いていただいたのに、こんな事になってしまって……。"
"10012095-8-ホシノ" = "うへ～ここ来てからも色々あったし、先生あんま休めなかったんじゃない？"
"10012095-9" = "[s] \"ううん、私は大丈夫。\""
"10012095-10-アヤネ" = "大丈夫……ですか？"
"10012095-11" = "[s1] \"みんなで楽しく過ごせたから。\"\n[s2] \"いいバカンスだったよ。\""
"10012095-12-ノノミ" = "ふふっ……それなら良かったです☆"
"10012095-13" = "[s] \"みんなはこの夏、楽しかった？\""
"10012095-14-セリカ" = "……き、急に何よ！？"
"10012095-15-ホシノ" = "セリカちゃん恥ずかしがってる～可愛いね～"
"10012095-16-セリカ" = "うっ！ ほ、ホシノ先輩まで！"
"10012095-17-シロコ" = "……ん。あえて言うなら当然――"
"10012095-18-ノノミ" = "はい～！ と～っても楽しかったですよ☆"
"10012095-19-ノノミ" = "いろいろあったけど……みんなと、先生と一緒に過ごせましたから。"
"10012095-20-シロコ" = "ん。セリカは、どう？"
"10012095-21-セリカ" = "わ、私！？そ、そりゃあ……！"
"10012095-22-セリカ" = "と、当然、た、た、楽しかっ……。"
"10012095-23" = "[s] \"うん、じゃあ私はそろそろ帰るね。\""
"10012095-24-ホシノ" = "そっか……残念だけど、先生忙しいもんね。"
"10012095-25-アヤネ" = "それでしたら早めに動かないと……ヘリでお送りできなくなっちゃいます。"
"10012095-26-シロコ" = "私たちは片付けがあるから、明日まで残る予定。"
"10012095-27-セリカ" = "ねぇ、私の返事まだ終わってないんだけど！？"
"10012095-28-ノノミ" = "セリカちゃん、その続きは今度、帰ってからゆっ～くり伝えてもいいんですよ？"
"10012095-29-ノノミ" = "ああもう！じゃあこれで終わり！"
"10012095-30-セリカ" = "終わりだから！"
"10012095-31" = "[ns] \"うん、じゃあ先に帰るね。\""
"10012095-32-アヤネ" = "はい！それでは、先生をシャーレまで送ってきますね！"
"10012095-33-ホシノ" = "いってらっしゃ～い。"
"10012095-34-ノノミ" = "……先生、短い間でしたが、リフレッシュできたでしょうか？"
"10012095-35-シロコ" = "十分だよ。元気もフル充電できたんじゃないかな。"
"10012095-36-ノノミ" = "だといいですね～"
"10012095-37-ノノミ" = "さてと。おじさんたちは、リゾートに戻って荷物をまとめますか～"
"10012095-38-セリカ" = "はぁ……帰ったら早くバイト入らなきゃ。お休みもあとちょっとだし……。"
"10012095-39-ノノミ" = "あっ「リゾート使用券」が……。"
"10012095-40-セリカ" = "あれ？ノノミ先輩、もうそれは必要ないんじゃない？"
"10012095-41-ノノミ" = "ふふっ、記念に持って帰ろうかな～と思いまして。"
"10012095-42-ノノミ" = "よいしょ。"
"10012095-43-ノノミ" = "……あら？"
"10012095-44-ノノミ" = "ノノミちゃん、どうしたの？"
"10012095-45-ノノミ" = "えっと……この、ちょうど端っこの方に……「リゾート使用権」の最終権利者の名前を見つけまして。"
"10012095-46-ノノミ" = "えっ、最終権利者！？"
"10012095-47-ノノミ" = "さっき、見落としてたの？"
"10012095-48-ノノミ" = "最終権利者ってことは……今回の騒動を起こした主犯？"
"10012095-49-ノノミ" = "「リゾート狩り」が起こるように、穴だらけの「リゾート使用券」をばらまいた張本人ってことよね？"
"10012095-50-ノノミ" = "一体誰なの！？"
"10012095-51-ノノミ" = "ちょっとそれ、見せて～"
"10012095-52-ノノミ" = "はい、どうぞ。ホシノ先輩。"
"10012095-53-ノノミ" = "ふむふむ。ローストパラダイース～リゾート投資及び運営総括……"
"10012095-54-ホシノ" = "ええと。"
"10012095-55-ホシノ" = "……うん？"
"10012095-56" = "アビドスリゾート復旧対策委員会"
