[translation]
"10012025-1-ジャブジャブヘルメット団A" = "こ、こいつらめちゃくちゃ強いじゃん！総員退却！！"
"10012025-2-ジャブジャブヘルメット団B" = "うちらが負けるなんて信じらんない！向こう二人しかいないのに！？"
"10012025-3-ラブ" = "ぐっ……うちらジャブジャブヘルメット団がやられるなんて……！"
"10012025-4-ラブ" = "強敵ってわけね……！"
"10012025-5-ラブ" = "でも諦めるわけには……！！"
"10012025-6-ラブ" = "あっ、アイタタタッ！"
"10012025-7-ラブ" = "い、痛い！痛いってば！"
"10012025-8-ラブ" = "くっそー！覚えてなさいよ！"
"10012025-9-ラブ" = "うちらがこのまま諦めると思わないでよね……！！"
"10012025-10-セリカ" = "あいつら……いったい何なの……？"
"10012025-11-セリカ" = "暴れるだけ暴れて、どっか行くなんて……。"
"10012025-12-セリカ" = "……あ～あ。せっかく片付けたのに、振り出しに戻っちゃった。"
"10012025-13-ホシノ" = "皆になんて言おうねぇ……。"
"10012025-14-ノノミ" = "ただいま戻りましたよ～☆"
"10012025-15-セリカ" = "……先輩たち！？"
"10012025-16-ホシノ" = "ナイスタイミングだねぇ。"
"10012025-17-ノノミ" = "備品は全部運び出せた。特に壊れたものもなく、無事だったよ。"
"10012025-18-ノノミ" = "セリカちゃんたちの方、お片付けは順調です……"
"10012025-19-アヤネ" = "……？"
"10012025-20-ホシノ" = "ちょ、ちょっと待って！"
"10012025-21-セリカ" = "掃除は終わってる、いや終わってたのよ！先輩と先生とやってたの！"
"10012025-22-セリカ" = "終わってたんだけど、こうなってるのには理由があって……！"
"10012025-23-ノノミ" = "セリカちゃん……。"
"10012025-24-アヤネ" = "二人で片付けるには広すぎましたからね……大丈夫ですよ。"
"10012025-25-シロコ" = "……ん、今からみんなで手分けすればすぐ終わる。"
"10012025-26-ノノミ" = "ほ、本当だってば！？掃除をサボってたんじゃなくて……！"
"10012025-27-セリカ" = "まぁまぁ、今から一緒に片付ければいいんですよ。"
"10012025-28-ノノミ" = "みんなで頑張りましょう～☆"
"10012025-29-セリカ" = "本当だってばぁぁぁぁー！！"
"10012025-30" = "（その後、掃除が終わってからこれまでの事についてゆっくり説明した）"
"10012025-31-ジャブジャブヘルメット団B" = "うう、肩痛い……赤くなってるじゃん……。"
"10012025-32-ジャブジャブヘルメット団A" = "やっぱこのままじゃ厳しいよ……どうしよう隊長……？"
"10012025-33-ジャブジャブヘルメット団A" = "もう戻る……？他の島を探してみるとか……？"
"10012025-34-ラブ" = "……今、なんて？"
"10012025-35-ジャブジャブヘルメット団B" = "ひ、ひいっ……な、何も……。"
"10012025-36-ジャブジャブヘルメット団B" = "しょうがないじゃん……！今のうちらじゃ歯がたたないよ。"
"10012025-37-ジャブジャブヘルメット団B" = "それにあいつら、まだ仲間がいそうだったし……。"
"10012025-38-ラブ" = "……そうね。"
"10012025-39-ラブ" = "……じゃあ、あんま気が向かないけど……。"
"10012025-40-ラブ" = "……うちらも増員呼ぶとすっかぁ。"
