[translation]
"3702-1" = "怪しいリミナルスペース（１）"
"3702-3" = "とある穏やかな昼下がり――"
"3702-7-エリ" = "みなさん、大事なお話があります。"
"3702-12-ツムギ" = "ふふっ。今日も面白い日になりそうですね。"
"3702-13-エリ" = "「リミナルスペース」をご存じですか？"
"3702-14-レナ" = "なにそれ？"
"3702-15-カノエ" = "私的空間と公共空間の境界が薄れた場所……。"
"3702-16-カノエ" = "現実と似ているようで、現実ではない……未知の空間。"
"3702-17-カノエ" = "異世界のスーパーに迷い込んだ話が有名だねぇ。"
"3702-18-カノエ" = "誰もいないスーパーをさまよい続けて、ようやく出会った店員……。#nしかしそれは店員ではなく――"
"3702-19-カノエ" = "化け物だった……って話。"
"3702-20-レナ" = "……それは私も聞いたことある。"
"3702-21-レナ" = "でも、ただの噂でしょ？"
"3702-22-エリ" = "にゅふふ……果たしてそうでしょうか？"
"3702-23-エリ" = "情報によると本当に存在するらしいのです。"
"3702-24-エリ" = "それも、このワイルドハントに！"
"3702-27-カノエ" = "イヒッ……その話、私も聞いたよぉ。"
"3702-28-ツムギ" = "一度行ってみたいですね。"
"3702-29-レナ" = "本気！？"
"3702-30-ツムギ" = "傑作とは多様な経験から生まれるもの。"
"3702-31-ツムギ" = "まだ見ぬ経験は、私たちの芸術を昇華させる助けとなってくれることでしょう。"
"3702-32-ツムギ" = "果てしない挑戦こそが――"
"3702-36-ツムギ" = "――「イノベーション」。"
"3702-37-ツムギ" = "……ですから。"
"3702-38-レナ" = "まーた適当なこと言って！もう騙されないんだから！！"
"3702-39-ツムギ" = "ふふ。でも楽しそうじゃありませんか？#nみんなと一緒ならきっと怖くもありませんよ。"
"3702-40-カノエ" = "ホラー映画も、みんなで観れば怖くない……でしょ？"
"3702-41-エリ" = "みんなで行けば大丈夫です！"
"3702-45-レナ" = "……はぁ、行けばいいんでしょ？まあ、どうせそんな場所あるわけないけどね。"
"3702-46-ツムギ" = "では、決まりですね。"
"3702-49-エリ" = "いざ行かん！オカルトの[ruby=たび]研究[/ruby]へ！"
"3702-51" = "しばらくして――"
"3702-53" = "怪しげな建物・1階"
"3702-56-レナ" = "ごめんくださーい……。"
"3702-57-レナ" = "入るよー？"
"3702-60-レナ" = "……。"
"3702-61-レナ" = "……電気もついてないし、本当に誰も居ないみたい。"
"3702-65-エリ" = "ここが、噂のリミナルスペース……。"
"3702-66-エリ" = "どこかに異世界と繋がる入口があるはずです！"
"3702-67-レナ" = "いや、よくある建物じゃない？#n窓の外が見えないことを除けば。"
"3702-70-レナ" = "……ん？#n待って、窓の外が見えない……？"
"3702-71-ツムギ" = "外が見えないように、全て覆われています。"
"3702-72-ツムギ" = "ふふっ、面白くなってきましたね。"
"3702-73-レナ" = "な、なんでそんなことしてるのよ？"
"3702-74-カノエ" = "いま分かることは1つだけ……。"
"3702-75-カノエ" = "ここには……なにか「特別な目的」があるんだろうねぇ。"
"3702-76-レナ" = "と、特別な目的？"
"3702-77-エリ" = "おおっ！きっと異世界と繋がる場所に違いありません！#nさっそく探検を始めましょう！"
"3702-88" = "みんなで建物の1階を見て回った。"
"3702-89" = "そして――"
"3702-91-ツムギ" = "この場所、思ったより興味深い構造をしています。"
"3702-92-ツムギ" = "中からでは外の様子が分からず、なぜか階段は全てふさがれている。"
"3702-93-ツムギ" = "たしかにここは「境目」が薄れた、外部と断絶された空間です。"
"3702-94-ツムギ" = "リミナルスペースと呼ばれるのもおかしくありません。"
"3702-95-エリ" = "でも、エレベーターは普通に使えるみたいですね。"
"3702-100-エリ" = "ほら、ちゃんと動いてます！"
"3702-101-カノエ" = "上がってみる？"
"3702-102-レナ" = "う、うーーん……。"
"3702-103-カノエ" = "それとも……帰る？"
"3702-104-レナ" = "い、いや。ここで帰ったら、リミナルスペースの存在を認めることになるでしょ！"
"3702-105-レナ" = "この世にオカルトなんて無いって確認してやるんだから！"
"3702-106-カノエ" = "イヒッ、じゃあ行こうかぁ……。"
"3702-108-エリ" = "8階まであるんですね。"
"3702-109-レナ" = "まずは7階から行こ！7はラッキーナンバーだから。"
"3702-110-ツムギ" = "ふふ。迷信は信じないのでは？"
"3702-111-レナ" = "これくらいは普通でしょ！行くよ！"
"3702-118" = "怪しげな建物・4階"
"3702-121-レナ" = "なんで4階で止まるの？7階押したよね？"
"3702-128-レナ" = "反応しない！？"
"3702-131-エリ" = "ずっとエレベーターの中にいる訳にもいきませんし、とりあえず降りましょう。"
"3702-132-エリ" = "にゅふふっ……何があるのかワクワクします。"
"3702-133-レナ" = "4階……なんか不吉……。"
"3702-134-ツムギ" = "心配せずとも、私たちが守ってあげますよ。"
"3702-140" = "怪しげな建物・4階廊下"
"3702-141-エリ" = "……綺麗な廊下ですね。"
"3702-142-エリ" = "このドアはどこに繋がるんでしょう？"
"3702-143-レナ" = "ちょっ、すぐ開けようとしないで！なんか出てきたらどうするのよ！"
"3702-144-ツムギ" = "あら？ここ、見てください。何か貼ってあります。"
"3702-145-カノエ" = "読んでみようか……。"
"3702-148-カノエ" = "好奇心は猫をも殺す、という言葉を知っていますか？"
"3702-150-カノエ" = "皆さんは入ってはならない場所に足を踏み入れました。"
"3702-151-カノエ" = "ここは現実の裏面。迷宮とも言える、境界の空間。"
"3702-152-カノエ" = "ここから出るためには異常現象を調べなくてはなりません。"
"3702-154-カノエ" = "異常現象を発見した場合、エレベーターに乗って1つ上の階へ。"
"3702-155-カノエ" = "異常現象がない場合は、1つ下の階へ。"
"3702-156-カノエ" = "「外に出たい」と心から思うのならば――このルールを必ず守ってください。"
"3702-157-カノエ" = "ルールに違反した場合、皆さんは8階へ導かれます。"
"3702-158-カノエ" = "そして、永遠に8階をさまようことになるでしょう……まるでメビウスの輪のように。"
"3702-159-カノエ" = "ふふ、ふふふふふ……。"
"3702-164-カノエ" = "――だって。"
"3702-167-レナ" = "……。"
"3702-168-レナ" = "な、なに……？"
"3702-169-レナ" = "うぅぅ……。"
"3702-170-レナ" = "こんなイタズラ仕掛けたの誰！？"
