[translation]
"1009706-1" = "Area beautification"
"1009706-2-村の住民" = "使われてない空き家か？#nもちろんあるさ。"
"1009706-3-村の住民" = "昔は賑わってたが、#n10年前くらいからほとんどの住民が都会に行っちまったからな……。"
"1009706-4-村の住民" = "今は空き家が何軒も放置されてるんだ。"
"1009706-5-村の住民" = "風倉ちゃんたちなら、好きに使ってくれて構わんよ。"
"1009706-6" = "[s] \"ありがとうございます！\""
"1009706-7-村の住民" = "むしろ、こっちとしても管理の手間が省けて助かるんだ。"
"1009706-8-村の住民" = "無料で貸し出したり、#n補助金を出しても入居者が集まらなくてな……。"
"1009706-9-村の住民" = "ただ、古い家だから掃除が大変だと思うが、それでも大丈夫かい？"
"1009706-10-村の住民" = "野宿に比べたら、どうってことないよ！"
"1009706-11-村の住民" = "の、野宿……？"
"1009706-12-村の住民" = "まあ、好きに使ってくれ。"
"1009706-13-モエ" = "いや～。名案だったね、先生。"
"1009706-14-モエ" = "せっかく持ってきたポータブル発電機が、#n持ち腐れになるところだったよ。"
"1009706-15-モエ" = "でも、これで安心して使えるね。"
"1009706-16" = "[s] \"役に立てて良かったよ。\""
"1009706-17-モエ" = "先生にも、住民の人たちにも、お世話になりっぱなしだねぇ。"
"1009706-18-モエ" = "水に食糧だけじゃなくて、拠点まで……。#n子ウサギ公園よりも快適な生活が送れてるような。"
"1009706-19-モエ" = "公園に戻らず、ここで生活してたいくらいだよ。#nくひひ……。"
"1009706-20" = "[s] \"本当に……？\""
"1009706-21-モエ" = "……もちろん、冗談だよ。#nいくら居心地が良いとは言っても、子ウサギ公園が一番だからね。"
"1009706-22-モエ" = "あの公園にも、少なからず思い入れがあるし……。"
"1009706-23-モエ" = "何より、SRT特殊学園が復活するまで、#nみんなで頑張ろうって約束したから。"
"1009706-24-モエ" = "うぅ。#n何か柄にもないこと言ったせいで、蕁麻疹が出そう……。"
"1009706-25-モエ" = "……とにかく！#nまずはここの掃除をするよ！"
"1009706-26-モエ" = "思った以上に時間がかかりそうだしさ。"
"1009706-27" = "（その後、モエと一緒に空き家の掃除をした）"
"1009706-28-モエ" = "はぁ……やっぱり大変だね。"
"1009706-29-モエ" = "残置物を片付けるだけでも、結構時間かかっちゃったし。"
"1009706-30" = "[s] \"お疲れ様、モエ。\""
"1009706-31-モエ" = "ううん。#n先生こそ、手伝ってくれてありがとう。"
"1009706-32-モエ" = "ここで生活するためには、もう何日かかかりそうだけど……。"
"1009706-33-モエ" = "とりあえず、雨風を気にせずデータの分析ができ――"
"1009706-34-モエ" = "……ん？"
"1009706-35-モエ" = "なんだ、蚊か……。"
"1009706-36-モエ" = "って、蛾も虻もいるんだけど！？"
"1009706-37-モエ" = "完全に虫の巣窟じゃん！"
"1009706-38-モエ" = "うあああっ！こっち飛んでくる！"
"1009706-39" = "[s1] \"巣を作ってたのかな？\"\n[s2] \"すごい数だね……。\""
"1009706-40-モエ" = "はぅ……。#nこれだけは使いたくなかったけど。"
"1009706-41-モエ" = "虫退治に効果的な白リン弾の出番――"
"1009706-42" = "[s3] \"それはダメ！\"\n[s4] \"私にも効果あるからね！？\""
"1009706-43-モエ" = "考えてみれば、後片付けも大変だし……。"
"1009706-44-モエ" = "じゃあ、人体に無害なCS手榴弾なら――"
"1009706-45" = "[s] \"それも充分有害だよ！？\""
"1009706-46" = "[ns5] \"ちょっと待って。\"\n[ns6] \"念のため、持ってきた物があるから。\""
"1009706-47-モエ" = "……蚊取り線香？"
"1009706-48-モエ" = "ちぇっ。#nこんなんじゃ、虫くらいしか捕まえられないよ。"
"1009706-49" = "[s7] \"……虫を捕まえるのが目的じゃなかった？\"\n[s8] \"まずは蚊取り線香で様子を見ようか。\""
"1009706-50" = "[wa:570]― [log=모에 수영복]うーん。[wa:1150]何回見ても火力弱く[wa:1740]感じるなぁ……[/log]"
"1009706-51" = "[wa:2090]― [log=모에 수영복]ま、[wa:820]煙が出てるからいっか。[/log]"
"1009706-52" = "[ns9] \"強ければ良いってものじゃないからね。\"\n[ns10] \"もう少し待ってみよう。\""
"1009706-53" = "[wa:1920]― [log=모에 수영복]なんか……[wa:1250]この匂いを嗅ぐのも、[wa:1510]久しぶりだなぁ。[/log]"
"1009706-54" = "― [log=모에 수영복]SRTに居たころ……[/log]"
"1009706-55" = "[wa:2380]― [log=모에 수영복]いや、[wa:1000]それよりずっと前かも？[/log]"
"1009706-56" = "― [log=모에 수영복]これを嗅いでいると、[/log]"
"1009706-57" = "[wa:1270]― [log=모에 수영복]昔の夏を思い出すんだ。[/log]"
"1009706-58" = "[wa:610]― [log=모에 수영복]ほんと、[wa:1020]不思議。[/log]"
"1009706-59" = "― [log=모에 수영복]これは虫にとって[wa:1010]有害な破滅の香りなのに、[/log]"
"1009706-60" = "[wa:2390]― [log=모에 수영복]人によっては懐かしく[wa:1120]感じるなんて……[/log]"
"1009706-61" = "― [log=모에 수영복]人って、[wa:1180]案外破滅が好きなのかも。[wa:2480]くひひ……[/log]"
"1009706-62" = "[wa:1140]― [log=모에 수영복]先生。[wa:1310]もうちょっとこっちに寄れる？[/log]"
"1009706-63" = "― [log=모에 수영복]先生に悪い虫が寄ってきたら[wa:1880]大変だし……[/log]"
"1009706-64" = "[wa:2300]― [log=모에 수영복]今晩はこれを[wa:1520]たっ[wa:320]ぷり[wa:120]浴びてこうね。[/log]"
"1009706-65" = "（その後、夏の香りを感じながらモエと二人で過ごした）"
