[translation]
"2600102-1" = "大人の秘密"
"2600102-2" = "シャーレ・執務室"
"2600102-3" = "コタマの当番の日。コタマがシャーレの執務室に、大きなクマのぬいぐるみを持ってきた。"
"2600102-4" = "[ns] \"急にどうしたの？\""
"2600102-5-コタマ" = "その、えっと……うーん……。"
"2600102-6-コタマ" = "そう、プレゼントです。先生に、プレゼント。"
"2600102-7" = "[s] \"誕生日でもないのに！？\""
"2600102-8-コタマ" = "今まで先生には、色々と助けていただいたので。"
"2600102-9-コタマ" = "悩んだ結果、先生にプレゼントをお渡ししようという結論に至りました。"
"2600102-10" = "[s] \"ちょっと飛躍してる気が……でもありがたく貰うね。\""
"2600102-11-コタマ" = "はい。"
"2600102-12-コタマ" = "あの、先生。このクマのぬいぐるみ、できればシャーレの執務室に置いていただけませんか。"
"2600102-13-コタマ" = "と、特に理由があるわけではないのですが。"
"2600102-14-コタマ" = "ただ……その方が、そのぬいぐるみも嬉しいだろうなと思いまして。"
"2600102-15-コタマ" = "それから、できるだけ執務室の全体が見渡せる位置が望ましいです。"
"2600102-16-コタマ" = "あと、ぬいぐるみの前には視野を遮るものを置かないようにしていただいて、湿気と電磁波は良くないので可能な限り避けるように……。"
"2600102-17" = "[s] ぬいぐるみの中身を調べてみる。"
"2600102-18-コタマ" = "せ、先生？急に何を……。"
"2600102-19" = "クマのぬいぐるみのボタンの裏から怪しげな装置が発見された。"
"2600102-20-コタマ" = "そ、それは、その……特に怪しいものではありません。#nそれはただの……。"
"2600102-21-コタマ" = "ただ、周囲の音を録音するだけの機械です！"
"2600102-22" = "[s] \"悪いけど、このクマのぬいぐるみは貰えないな……。\""
"2600102-23-コタマ" = "……お気に召しませんでしたか。仕方ありません……。"
"2600102-24" = "しかしその後も、コタマの試みは続いた……。"
"2600102-25-コタマ" = "先生、新しい壁掛け時計を持ってきました。どうぞ。"
"2600102-26-コタマ" = "今回は普通の時計です、はい。"
"2600102-27" = "[s] 時計を調べる。"
"2600102-28" = "時計の針の裏側に、盗聴器が付いていた。"
"2600102-29-コタマ" = "そ、それは……録音機能付きの時計なんです。それ以外、特に変わったことはありません。"
"2600102-30" = "[s] \"返品。\""
"2600102-31-コタマ" = "ふぅ……ダメでしたか。"
"2600102-32-コタマ" = "今日は先生のための、食事を用意しました。"
"2600102-33-コタマ" = "冷める前にどうぞ。"
"2600102-34" = "スープの上に、堂々と盗聴器が浮いていた。"
"2600102-35" = "[s] ……。"
"2600102-36-コタマ" = "……気づかれましたか。"
"2600102-37-コタマ" = "食べ物であれば、と思いましたが、やはりダメですね……。"
"2600102-38-コタマ" = "ぬいぐるみも、時計も、料理も失敗……次はどんな方法にしましょうか……。"
"2600102-39" = "[s] \"どうしてそんなに盗聴器を設置しようと頑張るの？\""
"2600102-40-コタマ" = "盗聴がしたいわけではありません。先生の声を録音したいだけです。"
"2600102-41" = "[s] \"だったらこっそり仕込もうとしなくてもいいんじゃ……？\""
"2600102-42-コタマ" = "それは、その……。"
"2600102-43-コタマ" = "……他の生徒たちが知らない、先生の秘密が知りたかったからです。"
"2600102-44-コタマ" = "24時間執務室を盗聴できるようにしておけば、先生の秘密を知ることができるかなと思いまして……。"
"2600102-45" = "[s1] \"私の秘密を調べて、一体何をしようと……？\"\n[s2] \"私にひどいことする気でしょう！？薄い本みたいに！\""
"2600102-46-コタマ" = "い、いえ、何も変なことは！"
"2600102-47-コタマ" = "い、いえ、何も変なことは！"
"2600102-48-コタマ" = "私はただ先生と、普通の会話がしたくって……。"
"2600102-49-コタマ" = "私にとって先生は、短所なんて一つもない完璧な大人に見えます。"
"2600102-50-コタマ" = "もちろんそんな先生にこれまでたくさん助けていただきましたが、そのせいか、先生と普通に会話をすることのハードルが、どんどん高くなってきてしまって……。"
"2600102-51-コタマ" = "もし他の生徒たちは知らない先生の秘密を知ることができれば、もっと気楽に会話ができるのでは……と、そう思いまして。"
"2600102-52-コタマ" = "とはいえ、やはりシャーレに盗聴器を設置するのは難しいみたいですし……。#n先生の秘密を探るのは諦めます……。"
"2600102-53" = "[s] \"実は私、高いところが怖いんだ。\""
"2600102-54-コタマ" = "……え？"
"2600102-55" = "[s] \"高いところ、それが私の弱点だよ。\""
"2600102-56-コタマ" = "そ、そうなんですね。先生は高いところが怖い……。"
"2600102-57-コタマ" = "ふふ、失礼ですが、ちょっと笑ってしまいますね。こんなに高いところで働いている先生なのに、高いところが怖いなんて。"
"2600102-58" = "[s] \"だから秘密だよ。\""
"2600102-59-コタマ" = "はい。完璧に見える先生も、やはり意外な弱点を持っているんですね……。"
"2600102-60-コタマ" = "でもこれで少しだけ、前よりも先生のことが理解できた気がします。"
"2600102-61-コタマ" = "ありがとうございます、先生。"
