[translation]
"11050-1" = "第5話;セリカの平凡な一日"
"11050-2" = "アビドス住宅街・45ブロック地区"
"11050-3" = "（アビドスの住宅街で、知ってる顔に出会った）"
"11050-4-セリカ" = "うっ……な、何っ……！？"
"11050-5" = "[s] \"おはよう。\""
"11050-6-セリカ" = "な、何が「おはよう」よ！なれなれしくしないでくれる？"
"11050-7-セリカ" = "私、まだ先生のこと認めてないから！"
"11050-8-セリカ" = "まったく、朝っぱらからのんびりうろついちゃって。#nいいご身分だこと。"
"11050-9" = "[s] \"セリカちゃんは、これから学校？\""
"11050-10-セリカ" = "な、何よ！何でちゃん付けで呼んでんのよ！"
"11050-11-セリカ" = "私が何をしようと、別に先生とは関係ないでしょ？"
"11050-12-セリカ" = "朝っぱらからこんなところをうろちょろしてたら、ダメな大人の見本みたいに思われるわよ？"
"11050-13-セリカ" = "じゃあね！せいぜいのんびりしてれば？私は忙しいの。"
"11050-14-セリカ" = "え？学校に行くなら一緒に行こうって？"
"11050-15-セリカ" = "あのね、なんで私があんたと仲良く学校に行かなきゃならないわけ？"
"11050-16-セリカ" = "それに悪いけど今日は自由登校日だから、学校に行かなくてもいいんだけど？"
"11050-17-セリカ" = "ん？それなら、どこに行くのかって？……そんなの教えるわけないでしょ？"
"11050-18-セリカ" = "じゃあね、バイバイ。"
"11050-19" = "（セリカは砂埃を立てながら走り去っていった）"
"11050-20" = "[s] 追いかける。"
"11050-21-セリカ" = "ひゃあっ！？な、なんでついてくるの！？"
"11050-22-セリカ" = "ついて行けば、どこに行くのかわかるから？"
"11050-23-セリカ" = "何言ってんの！？あっち行ってよ！ストーカーじゃないのっ！！"
"11050-24-セリカ" = "わかった！わかったってば！行先を教えればいいんでしょ？"
"11050-25-セリカ" = "……バイトよ。"
"11050-26-セリカ" = "あ、あんたみたいにのんびりしてられないのよ、こっちは。少しでも稼がなきゃ！"
"11050-27-セリカ" = "もういいでしょ？ついてこないで！"
"11050-28" = "[s] 追いかける。"
"11050-29-セリカ" = "うう……しつこい。"
"11050-30-セリカ" = "……え？バイト先が気になる？"
"11050-31-セリカ" = "ああもうっ！意味わかんない！あっち行ってよ！ダメ大人！！あっち行けってば！ぶっ殺すわよ！？"
"11050-32" = "（セリカは砂埃を立てながら走り去った）"
"11050-33-セリカ" = "いらっしゃいませ！[ruby=しばせき]柴関[/ruby]ラーメンです！"
"11050-34-セリカ" = "何名様ですか？空いてるお席にご案内いたしますね！"
"11050-35-セリカ" = "少々お待ちください！3番テーブル、替え玉追加です！"
"11050-36" = "（ガララッ）"
"11050-37-セリカ" = "いらっしゃいませ！柴関ラーメンで……。"
"11050-38-セリカ" = "わわっ！？"
"11050-39-ノノミ" = "あの～☆5人なんですけど～！"
"11050-40-アヤネ" = "あ、あはは……セリカちゃん、お疲れ……。"
"11050-41-シロコ" = "お疲れ。"
"11050-42" = "み、みんな……どうしてここを……！？"
"11050-43" = "うへ～やっぱここだと思った。"
"11050-44" = "[s] \"どうも。\""
"11050-45-セリカ" = "せっ、先生まで……やっぱストーカー！？"
"11050-46-ホシノ" = "うへ、先生は悪くないよー。セリカちゃんのバイト先といえば、やっぱここしかないじゃん？だから来てみたの。"
"11050-47-セリカ" = "ホシノ先輩かっ……！！ううっ……！"
"11050-48-柴大将" = "アビドスの生徒さんか。セリカちゃん、おしゃべりはそれぐらいにして、注文受けてくれな。"
"11050-49-セリカ" = "あ、うう……はい、大将。それでは、広い席にご案内します……こちらへどうぞ……。"
"11050-50-ノノミ" = "はい、先生はこちらへ！私の隣、空いてます！"
"11050-51-シロコ" = "……ん、私の隣も空いてる。"
"11050-52" = "[s1] ノノミの隣に座る。\n[s2] シロコの隣に座る。"
"11050-53" = "（すとん）"
"11050-54" = "んん、ちょっと狭いですけど、大丈夫ですよね？"
"11050-55" = "あら、窮屈ですか？それなら、私の膝の上にでもどうぞ？"
"11050-56" = "何してんのよ！人の店で！"
"11050-57" = "あはは、冗談ですよ、セリカちゃん☆"
"11050-58" = "他にも空いてる席たくさんあるじゃん！みんなちゃんと座って！"
"11050-59" = "あ、あはは……はあい。"
"11050-60" = "（すとん）"
"11050-61" = "ふむ……。"
"11050-62" = "狭すぎ！シロコ先輩、そんなにくっついてたら先生が窮屈でしょ！もっとこっちに寄って！"
"11050-63" = "いや、私は平気。ね、先生？"
"11050-64" = "何でそこで遠慮するの！？空いてる席たくさんあるじゃん！ちゃんと座ってよ！"
"11050-65" = "わ、分かった……。"
"11050-66-ノノミ" = "セリカちゃん。バイトのユニフォーム、とってもカワイイです☆"
"11050-67-ホシノ" = "いやぁー、セリカちゃんってそっち系か。ユニフォームでバイト決めちゃうタイプ？"
"11050-68-セリカ" = "ち、ち、ち、違うって！関係ないし！#nこ、ここは行きつけのお店だったし……。"
"11050-69-ホシノ" = "ユニフォーム姿のセリカちゃん、写真撮っとけば一儲けできそうだねー。#nどう？一枚買わない、先生？"
"11050-70-アヤネ" = "変な副業はやめてください、先輩……。"
"11050-71-シロコ" = "バイトはいつから始めたの？"
"11050-72-セリカ" = "い、一週間ぐらい前から……。"
"11050-73-ノノミ" = "そうだったんですね☆時々姿を消していたのは、バイトだったということですか！"
"11050-74-セリカ" = "も、もういいでしょ！ご注文はっ！？"
"11050-75-ホシノ" = "「ご注文はお決まりですか」でしょー？セリカちゃーん、お客様には笑顔で親切に接客しなくちゃー？"
"11050-76-セリカ" = "あうう……ご、ご注文は、お決まりですか……。"
"11050-77-ノノミ" = "私は、チャーシュー麺をお願いします！"
"11050-78-シロコ" = "私は塩。"
"11050-79-アヤネ" = "えっと……私は味噌で……。"
"11050-80-ホシノ" = "私はねー、特製味噌ラーメン！炙りチャーシュートッピングで！"
"11050-81-ホシノ" = "先生も遠慮しないで、ジャンジャン頼んでねー。#nこの店、めちゃくちゃ美味しいんだよー！アビドス名物、柴関ラーメン！"
"11050-82-セリカ" = "……ところで、みんなお金は大丈夫なの？もしかして、#nまたノノミ先輩に奢ってもらうつもり？"
"11050-83-ノノミ" = "はい、私はそれでも大丈夫ですよ☆このカードなら、限度額までまだ余裕ありますし。"
"11050-84-ホシノ" = "いやいや、またご馳走になるわけにはいかないよー。きっと先生が奢ってくれるはず。だよね、先生？"
"11050-85-ホシノ" = "……え？初耳だって？あはは、今聞いたからいいでしょ！"
"11050-86" = "[s] 逃げる。"
"11050-87-ホシノ" = "そうはさせないよー。"
"11050-88" = "（捕まってしまった）"
"11050-89-ホシノ" = "うへ～大人のカードがあるじゃん。これは出番だねー！"
"11050-90-アヤネ" = "大人のカードを使うような場所でもなさそうですが……#n先輩、最初からこうするつもりで、私たちをご飯に誘ってくれたんですね。"
"11050-91-ホシノ" = "先生としては、カワイイ生徒たちの空腹を満たしてやれる絶好のチャンスじゃーん？"
"11050-92-ノノミ" = "……。"
"11050-93-ノノミ" = "（ボソッ）先生、こっそりこれで支払ってください。"
"11050-94-ノノミ" = "え……？大丈夫ですか？でも……。"
"11050-95" = "（みんなの分まで会計を済ませた）"
"11050-96-ホシノ" = "いやぁー！ゴチでしたー、先生！"
"11050-97-ノノミ" = "ご馳走様でした。"
"11050-98-シロコ" = "うん、お陰様でお腹いっぱい。"
"11050-99-セリカ" = "早く出てって！二度と来ないで！仕事の邪魔だから！"
"11050-100-アヤネ" = "あ、あはは……セリカちゃん、また明日ね……。"
"11050-101-セリカ" = "ホント嫌い！！みんな死んじゃえー！！"
"11050-102-ホシノ" = "あはは、元気そうで何よりだー。"
"11050-103" = "[s] 帰る。"
"11050-104" = "（お疲れ様ー！）"
"11050-105-セリカ" = "はあ……やっと終わった。目まぐるしい一日だったわ。"
"11050-106-セリカ" = "みんなで来るなんて……騒がしいったらありゃしない。"
"11050-107-セリカ" = "人が働いているってのに、先生先生って、チヤホヤしちゃって。ホント迷惑、何なのアレ。"
"11050-108-セリカ" = "ホシノ先輩、昨日のことがあったからってわざと先生を連れてきたに違いないわ！"
"11050-109-セリカ" = "……ふざけないで。私がそう簡単に折れると思ったら大間違いなんだから。"
"11050-110-ヘルメット団B" = "……。"
"11050-111-ヘルメット団A" = "あいつか？"
"11050-112-ヘルメット団B" = "……はい、そうです。アビドス対策委員会のメンバーです。"
"11050-113-ヘルメット団A" = "準備はいいか？次のブロックで捕獲するぞ。"
"11050-114-セリカ" = "……。"
"11050-115-セリカ" = "ふう……。"
"11050-116-セリカ" = "……そういえば、この辺も結構人がいなくなったなあ。前はここまでじゃなかったのに。"
"11050-117-セリカ" = "治安も悪くなったみたいだし……。"
"11050-118-セリカ" = "このままじゃダメだ。私たちが頑張らないと……そして学校を立て直さないと……。"
"11050-119-セリカ" = "とりあえずバイト代が入ったら、利息の返済に充てて……。"
"11050-120-セリカ" = "……！？"
"11050-121-セリカ" = "何よ、あんたたち。"
"11050-122-ヘルメット団A" = "[ruby=くろみ]黒見[/ruby]セリカ……だな？"
"11050-123-セリカ" = "……カタカタヘルメット団？あんたたち、まだこの辺をうろついてんの？"
"11050-124-セリカ" = "ちょうど良かった。虫の居所が悪かったの。二度とこの辺りに足を踏み入れられないようにしてやるわっ……！！"
"11050-125" = "（ダダダダダダダダッ！！）"
"11050-126-セリカ" = "くっ、ううっ！！"
"11050-127-セリカ" = "（背後にも敵！？……こいつら、最初から私を……）"
"11050-128-ヘルメット団A" = "捕らえろ。"
"11050-129" = "（プシュウーーーー！！）"
"11050-130" = "ドドドドドーーーーーン！！！"
"11050-131-セリカ" = "ケホッ、ケホッ……。"
"11050-132-セリカ" = "（対空砲……？違う……この爆発音は、Flak41改……？）"
"11050-133-セリカ" = "（火力支援？どこから……？ち、違う、これは……まさか……）"
"11050-134-セリカ" = "（こっ、こいつら、ハンパじゃない……ヤバい……）"
"11050-135-セリカ" = "（意識が……）"
"11050-136-セリカ" = "（……）"
"11050-137" = "（ドサッ）"
"11050-138-ヘルメット団A" = "……。"
"11050-139-ヘルメット団B" = "続けますか？"
"11050-140-ヘルメット団A" = "いや、生かさなければ意味がない。この程度でいいだろう。車に乗せろ、ランデブーポイントへ向かう。"
"11050-141" = "（ブーン……）"
"11050-142" = "次回;救出作戦！"
