[translation]
"11110-1" = "第11話;ブラックマーケットへ（１）"
"11110-2" = "ブラックマーケット"
"11110-3" = "（ガヤガヤ）"
"11110-4-セリカ" = "ここがブラックマーケット……。"
"11110-5-ノノミ" = "わあ☆すっごい賑わってますね？"
"11110-6-シロコ" = "本当に。小さな市場を想像していたけど、街ひとつぐらいの規模だなんて。"
"11110-7-シロコ" = "連邦生徒会の手が及ばないエリアが、ここまで巨大化してるとは思わなかった。"
"11110-8-ホシノ" = "うへ～普段私たちはアビドスにばっかりいるからねー。学区外は結構変な場所が多いんだよー。"
"11110-9-シロコ" = "ホシノ先輩、ここに来たことあるの？"
"11110-10-ホシノ" = "いんやー、私も初めてだねー。でも他の学区には、へんちくりんなものがたくさんあるんだってさー。"
"11110-11-ホシノ" = "ちょーデカい水族館もあるんだって。アクアリウムっていうの！"
"11110-12-ホシノ" = "今度行ってみたいなー。うへ、魚……お刺身……。"
"11110-13-セリカ" = "よくわかんないけど、アクアリウムってそういうのじゃないような……。"
"11110-14-アヤネ" = "皆さん、油断しないでください。そこは違法な武器や兵器が取引される場所です。何が起こるかわからないんですよ。"
"11110-15-アヤネ" = "何かあったら私が……きゃあっ！？"
"11110-16" = "（タタタタタタタタタ！）"
"11110-17-シロコ" = "銃声だ。"
"11110-18-チンピラ１" = "待て！！"
"11110-19-ヒフミ" = "う、うわああ！まずっ、まずいですー！！つ、ついてこないでくださいー！！"
"11110-20-チンピラ１" = "そうはいくか！"
"11110-21-アヤネ" = "あれ……あの制服は……。"
"11110-22-ヒフミ" = "わわわっ、そこどいてくださいー！！"
"11110-23" = "（ドンッ）"
"11110-24-ヒフミ" = "い、いたた……ご、ごめんなさい！"
"11110-25-シロコ" = "大丈夫？"
"11110-26-シロコ" = "なわけないか、追われてるみたいだし。"
"11110-27-ヒフミ" = "そ……それが……。"
"11110-28-チンピラ２" = "何だおまえらは。どけ！アタシたちはそこのトリニティの生徒に用がある。"
"11110-29-ヒフミ" = "あ、あうう……わ、私の方は特に用はないのですけど……。"
"11110-30-アヤネ" = "……！！"
"11110-31-アヤネ" = "思い出しました、その制服……キヴォトスいちのマンモス校のひとつ、トリニティ総合学園です！"
"11110-32-チンピラ２" = "そう、そしてキヴォトスで一番金を持っている学校でもある！#nだから拉致って身代金をたんまり頂こうってわけさ！"
"11110-33-チンピラ２" = "拉致って交渉！なかなかの財テクだろう？くくくくっ。"
"11110-34-チンピラ２" = "どうだ、おまえらも興味があるなら計画に乗るか？身代金の分け前は……。"
"11110-35-チンピラ１" = "ん？"
"11110-36" = "（バスッバスッ！）"
"11110-37-ノノミ" = "うぎゃあっ！"
"11110-38" = "悪人は懲らしめないとです☆"
"11110-39-シロコ" = "うん。"
"11110-40-ヒフミ" = "あ……えっ？えっ？"
"11110-41-ヒフミ" = "あ、ありがとうございました。みなさんがいなかったら、学園に迷惑をかけちゃうところでした……。"
"11110-42-ヒフミ" = "それに、こっそり抜け出してきたので、何か問題を起こしたら……あうう……想像しただけでも……。"
"11110-43-ホシノ" = "えっとー、ヒフミちゃんだっけ？それにしても、トリニティのお嬢様が何でこんな危ない場所に来たの？"
"11110-44-ヒフミ" = "あ、あはは……それはですね……実は、探し物がありまして……。"
"11110-45-ヒフミ" = "もう販売されていないので買うこともできない物なのですが、ブラックマーケットでは密かに取引されているらしくて……。"
"11110-46-シロコ" = "もしかして……戦車？"
"11110-47-ホシノ" = "もしくは違法な火器？"
"11110-48-ノノミ" = "化学武器とかですか？"
"11110-49-ヒフミ" = "えっ！？い、いいえ……えっとですね、ペロロ様の限定グッズなんです。"
"11110-50-セリカ" = "ペロロ？"
"11110-51-シロコ" = "限定グッズ？"
"11110-52-ヒフミ" = "はい！これです。ペロロ様とアイス屋さんがコラボした、限定のぬいぐるみ！"
"11110-53-ヒフミ" = "限定生産で100体しか作られていないグッズなんですよ。"
"11110-54-ヒフミ" = "ね？可愛いでしょう？"
"11110-55-シロコ" = "……。"
"11110-56-ノノミ" = "わあ☆モモフレンズですね！私も大好きです！ペロロちゃん可愛いですよねえ！#n私はミスター・ニコライが好きなんです。"
"11110-57-ヒフミ" = "分かります！ニコライさんも哲学的なところがカッコ良くて。"
"11110-58-ヒフミ" = "最近出たニコライさんの本『善悪の彼方』も買いましたよ！それも初版で！"
"11110-59-ホシノ" = "……いやぁー何の話だか、おじさんにはさっぱりだなー。"
"11110-60-セリカ" = "ホシノ先輩はこういうファンシー系にまったく興味ないでしょ。"
"11110-61-ホシノ" = "ふむ、最近の若いやつにはついていけん。"
"11110-62-セリカ" = "歳の差、ほぼないじゃん……。"
"11110-63-ヒフミ" = "というわけで、グッズを買いに来たのですが、先ほどの人たちに絡まれて……#nみなさんがいなかったら今頃どうなっていたことやら。"
"11110-64-ヒフミ" = "……ところで、アビドスのみなさんは、なぜこちらへ？"
"11110-65-ホシノ" = "私たちも似たようなもんだよ。探し物があるんだー。"
"11110-66-シロコ" = "そう。今は生産されていなくて手に入れにくい物なんだけど、ここにあるって話を聞いて。"
"11110-67-ヒフミ" = "そうなんですか、似たような感じなんですね。"
"11110-68-アヤネ" = "皆さん、大変です！四方から武装した人たちが向かってきています！"
"11110-69-セリカ" = "何っ！？"
"11110-70-チンピラ１" = "あいつらだ！！"
"11110-71-チンピラ３" = "よくもやってくれたな！痛い目にあわせてやるぜ！"
"11110-72-アヤネ" = "先ほど撃退したチンピラの仲間のようです！完全に敵対モードです！"
"11110-73-シロコ" = "望むところ。"
"11110-74-セリカ" = "まったく、なんでこんなのばっかり絡んでくるんだろうね？私たち、何か悪いことした？"
"11110-75-アヤネ" = "愚痴は後にして……応戦しましょう、皆さん！"
