[translation]
"11160-1" = "第16話;明かされる真実"
"11160-2" = "対策委員会・教室"
"11160-3" = "（ヒフミと共にアビドスに戻り、全員で書類の確認を行っていた）"
"11160-4" = "（バン！！）"
"11160-5-セリカ" = "なっ、何これ！？一体どういうことなのっ！？"
"11160-6-ノノミ" = "……！！"
"11160-7-シロコ" = "現金輸送車の集金記録にはアビドスで788万円集金したと記されてる。#n私たちの学校に来たあのトラックで間違いない。"
"11160-8-シロコ" = "……でも、その後すぐにカタカタヘルメット団に対して「任務補助金500万円提供」って記録がある……。"
"11160-9-ノノミ" = "ということは……それって……。"
"11160-10" = "私たちのお金を受け取った後に、ヘルメット団のアジトに直行して任務補助金を渡したってことだよね！？"
"11160-11-アヤネ" = "任務だなんて……？カタカタヘルメット団に……？"
"11160-12-アヤネ" = "ヘルメット団の背後にいるのは、まさか……カイザーローン？"
"11160-13-シロコ" = "……。"
"11160-14-セリカ" = "……。"
"11160-15-ヒフミ" = "……。"
"11160-16-ノノミ" = "ど、どういうことでしょう！？理解できません！学校が破産したら、貸し付けたお金も回収できないでしょうに……#nどうしてそのようなことを……？"
"11160-17-ホシノ" = "ふーむ……。"
"11160-18-シロコ" = "この件、銀行単独の仕業じゃなさそうだね。#nカイザーコーポレーション本社の息がかかってるとしか思えない……。"
"11160-19-ヒフミ" = "……はい。そう見るのが妥当ですね。"
"11160-20-ヒフミ" = "みなさん、色々とありがとうございました。"
"11160-21-ノノミ" = "変な事に巻き込んでごめんなさい、ヒフミさん。"
"11160-22-ヒフミ" = "あ、あはは……。"
"11160-23-ホシノ" = "今度遊びに行くから、その時はよろしくー。"
"11160-24-ヒフミ" = "はいっ、もちろんです。"
"11160-25-ヒフミ" = "まだ詳しいことは明らかになっていませんが……#nこれはカイザーコーポレーションが、犯罪者や反社会勢力と何かしら関連があるという事実上の証拠になり得ます。"
"11160-26-ヒフミ" = "戻ったら、この事実をティーパーティーに報告します！"
"11160-27-ヒフミ" = "それと、アビドスさんの現在の状況についても……。"
"11160-28-ホシノ" = "……。"
"11160-29-ホシノ" = "まー、ティーパーティーはもう知ってると思うけどねー。"
"11160-30-ヒフミ" = "は、はいっ！？"
"11160-31-ホシノ" = "あれほどの規模を持つ学園の首脳部なら、それぐらいはもうとっくに把握してると思うんだよー。#nみんな、遊んでばかりじゃないだろうしさ。"
"11160-32-ヒフミ" = "そ、そんな……知っているのに、みなさんのことを……。"
"11160-33-ホシノ" = "うん、ヒフミちゃんは純真で良い子だねー。でも世の中、そんなに甘くないからさ。"
"11160-34-ヒフミ" = "……。"
"11160-35-ホシノ" = "ヒフミちゃんの気持ちはありがたいけど、そっちに知らせたところで、これといった打開策が出るわけじゃないし#nかえって私たちがパニくることになりそうな気がするんだよねー。"
"11160-36-ヒフミ" = "そ、そうですか……？"
"11160-37-ホシノ" = "ほら、今のアビドスって廃校寸前じゃん？トリニティとかゲヘナみたいな#nマンモス校からのアクションをコントロールできる力がないんだよー。#n言ってる意味、わかるよね？"
"11160-38-ヒフミ" = "……サポートするという名目で悪さをされても、それを阻止できない……#nってことですよね。"
"11160-39-ヒフミ" = "……そうですね、その可能性もなくはありません。#nあうう……政治って難しいです。"
"11160-40" = "でも……ホシノ先輩、悲観的に考え過ぎなのではないでしょうか？#n本当に助けてくれるかもしれませんし……。"
"11160-41-ホシノ" = "うへ～私は他人の好意を素直に受け取れない、汚れたおじさんになっちゃってねー。"
"11160-42-ホシノ" = "「万が一」ってことをスルーしたから、アビドスはこの有様になっちゃったんだよー。"
"11160-43" = "……。"
"11160-44-ヒフミ" = "……。"
"11160-45-ヒフミ" = "では……。"
"11160-46-ヒフミ" = "えっと……。"
"11160-47-ヒフミ" = "本当に……一日で色んな出来事がありましたね。"
"11160-48-シロコ" = "そうだね、すごく楽しかった。"
"11160-49-セリカ" = "……楽しかったのはシロコ先輩だけじゃないの？"
"11160-50" = "あ、あははは……私も楽しかったです。"
"11160-51-ホシノ" = "いやぁー、ファウストちゃん、お世話になったね。"
"11160-52-ヒフミ" = "そ、その呼び方はやめてください！"
"11160-53-ノノミ" = "よっ、覆面水着団のリーダーさん！"
"11160-54-アヤネ" = "みなさん……ヒフミさんが困ってるじゃないですか。"
"11160-55-ヒフミ" = "と、とにかく……これからも大変だとは思いますが、頑張ってくださいね。応援してます。"
"11160-56-ヒフミ" = "それでは……みなさん、またお会いしましょう。"
"11160-57-アヤネ" = "みなさんお疲れ様でした。今日はゆっくり休んで、明日改めて集まりましょう。"
"11160-58-ホシノ" = "解散～。"
"11160-59" = "次回;立ち込める暗雲"
