[translation]
"11195-1-アル" = "はあ……はあ……こいつら……！！"
"11195-2-アル" = "なんでこんなに……しぶと……。"
"11195-3" = "（ドゴゴゴゴゴーーーン！！）"
"11195-4" = "（ズガガガガガーーーーーン！！）"
"11195-5" = "（ドッカーーーーーーーン！！）"
"11195-6-ムツキ" = "うっわ！？今度は何なのさ！？"
"11195-7-カヨコ" = "……。"
"11195-8-カヨコ" = "これは……！"
"11195-9-シロコ" = "何……？"
"11195-10-セリカ" = "この音は……。"
"11195-11" = "砲撃です！！3kmの距離に多数の擲弾兵を確認！"
"11195-12-アヤネ" = "50mm迫撃砲です！標的は私たちではなく便利屋の方みたいなのですが、#nもう少し確認を……。"
"11195-13-ノノミ" = "迫撃砲、ですか……？"
"11195-14-シロコ" = "50mm迫撃砲といえば……。"
"11195-15-アヤネ" = "兵力の所属、確認できました！！ゲヘナの風紀委員会！#n一個中隊の規模です！"
"11195-16-シロコ" = "風紀委員会……！"
"11195-17" = "次回;風紀委員会、参戦！"
