[translation]
"42020-1" = "第2話;ウサギの見る夢"
"42020-2" = "「SRT特殊学園は……連邦生徒会長の認可の下……」"
"42020-3" = "「SRTの小隊は少数精鋭のチームで構成され……」"
"42020-4" = "「……正義とは、理にかなった正しい道理のこと。」"
"42020-5" = "「SRTの正義は、いかなる状況でも揺らぎはしません。」"
"42020-6" = "……テレビに映る先輩方は、眩いほど輝いていた。"
"42020-7" = "理想を体現したその姿は……私たちの[ruby=せんぼう]羨望[/ruby]、そのものだった。"
"42020-8" = "過酷な状況にも決して折れない、強い信念と厳格な規律に憧れた。"
"42020-9" = "どんな悪人をも一撃で制圧できる、圧倒的な力に憧れた。"
"42020-10" = "[ruby=おぞ]悍[/ruby]ましい敵の前でも揺るがない、大胆な勇気に憧れた。"
"42020-11" = "――いつまでも変わらない正義に憧れた。"
"42020-12" = "先輩方は私たちの夢、そして未来だった。"
"42020-13" = "その背中を追って走り――"
"42020-14" = "そして私たちは……"
"42020-15" = "SRTになった。"
"42020-16-ミヤコ" = "んん……。"
"42020-17-ミユ" = "あっ、ミヤコちゃん。おはよう。"
"42020-18-ミヤコ" = "……おはようございます、ミユ。"
"42020-19-ミユ" = "もう起きるの？朝ごはんまでまだ時間あるよ……？"
"42020-20-ミユ" = "ミヤコちゃん、昨日の夜間警戒で遅かったから……もう少し寝ててもいいのに。"
"42020-21-ミヤコ" = "大丈夫です、睡眠は十分に取れましたので。"
"42020-22-ミヤコ" = "今日はいい天気ですね、洗濯物もよく乾きそうです。"
"42020-23-ミヤコ" = "ところで、モエとサキは……？"
"42020-24-ミヤコ" = "さっき、おかずになる食材を探しに行くって……。"
"42020-25-ミユ" = "おい、見てくれ！"
"42020-26-ミユ" = "いつもの散歩コースから少し外れたところに、キノコがたくさん生えてたんだ！#nデカいやつを集めてきたぞ。"
"42020-27-サキ" = "これだけあれば、キノコだけで2日は持つな！"
"42020-28-モエ" = "くひひひ……こっちもビックリするかもよ？"
"42020-29-モエ" = "ほら見て、卵がいっぱい！"
"42020-30-モエ" = "さっき商店街でもらってきたんだ。害虫駆除のお礼だって。"
"42020-31-モエ" = "ちょ～っと、新しい煙幕弾を試しただけなんだけど……得しちゃったね。"
"42020-32-ミユ" = "わっ……新鮮な食材がこんなに……！"
"42020-33-ミヤコ" = "缶詰のパンも残っていますから……今日の朝ごはんは豪華になりそうですね。"
"42020-34-ミヤコ" = "くひひ、ワクワクしてくるねぇ。#nそれじゃ、まずは火をおこさないと。私、枯れ枝を集めてくるよ。"
"42020-35-サキ" = "フライパンと野菜の準備は任せろ！"
"42020-36-ミヤコ" = "それでは、調味料やその他の準備は私がしますね。"
"42020-37-ミユ" = "わ、私も手伝う……！"
"42020-38-サキ" = "パンにキノコ炒めと卵……今まで想像すらできなかった贅沢な朝食だな。"
"42020-39-サキ" = "毎日これくらい豊かなご飯を食べていたい――"
"42020-40-モエ" = "んだねぇ。それに、今日は涼しくて天気もいいし……"
"42020-41-モエ" = "こんな日々が続くなら、ずっとここにいてもいいかも――"
"42020-42-サキ" = "……なぁ。私たち、この状況に慣れすぎてないか？"
"42020-43-モエ" = "……たしかに。なんかもう、作戦は二の次で生活の些細なあれこれが改善されることに一喜一憂しているくらいだし……。"
"42020-44-サキ" = "くっ……SRTのエリートだというのに……#n装備は常に最先端の特殊学園の小隊員なのに……。"
"42020-45-モエ" = "……この話はやめよう。#nせっかくの素敵なご飯がまずくなっちゃう。"
"42020-46-サキ" = "そうだな。今は食事に――"
"42020-47" = "[ns] \"おはよう、みんな元気？\""
"42020-48-モエ" = "あ、[USERNAME]先生だ。"
"42020-49-サキ" = "ああ、見慣れた顔がいると思ったら先生か。"
"42020-50-サキ" = "いらっしゃい、先生。今日は気分がいいから歓迎してやる。"
"42020-51" = "[s1] \"サキに満面の笑みで歓迎されるなんて……。\"\n[s2] \"先生になってよかった……。\""
"42020-52-モエ" = "う、うるさい！満面の笑みじゃないし！"
"42020-53-モエ" = "う、うるさい！満面の笑みじゃないし！"
"42020-54-ミヤコ" = "あ、先生。おはようございます。"
"42020-55-ミヤコ" = "こんな朝早くにどうしたのですか？#n特に連絡はしていませんが……"
"42020-56-ミヤコ" = "もしかして、何か問題でも……？"
"42020-57" = "[s] \"ううん、そういうのじゃなくて……。\""
"42020-58" = "[ns] \"この前のお礼をしたかったんだ。\""
"42020-59-ミヤコ" = "この前の……。"
"42020-60-サキ" = "ああ……あの事件のことか。"
"42020-61-モエ" = "……キヴォトスの危機なんて、刺激的な体験だったよねぇ。"
"42020-62-モエ" = "破滅を楽しむ私でも背筋が凍っちゃうくらいだったよ、くひひ……。"
"42020-63-ミユ" = "空は真っ赤で、正体不明の敵がたくさん出てきて……#n怖くてずっと逃げ出したかったけど……。"
"42020-64-ミユ" = "……みんな、キヴォトスのために頑張ってたから。"
"42020-65" = "[s] \"あの事件ではたくさんの生徒に助けられたけど……。\""
"42020-66-サキ" = "どりゃあぁぁぁ――！！！"
"42020-67-ミヤコ" = "RABBIT小隊。先生の救助要請を確認し、参上いたしました。"
"42020-68" = "[ns3] \"あの時、RABBIT小隊のみんなが来てくれなかったら。\"\n[ns4] \"反撃を始めるなんて、夢のまた夢だったから。\""
"42020-69-ミヤコ" = "……いいえ、お礼なんて必要ありません。"
"42020-70-ミヤコ" = "SRTとして、やるべきことをやっただけですから……。"
"42020-71-ミヤコ" = "そうだ、正義を守るのがSRTの役目だからな！"
"42020-72-モエ" = "それに、シャーレの建物に向かってミサイルをぶっ放せる貴重なチャンスだったし、くひひ……。"
"42020-73" = "[s] \"ありがとう。でも何かお礼をしないと気が済まなくて。\""
"42020-74" = "[ns] \"差し入れを持ってきたんだけど……。\""
"42020-75-モエ" = "ふっ……すっかりこの生活に馴染んだ私たちだぞ？#n食料なんて間に合っているが――"
"42020-76-サキ" = "まぁ、気持ちだけもらっておくから、しまっておいてくれ。"
"42020-77-ミヤコ" = "市民の安全を守れたのが一番の喜びですから。#nそれ以上は何も望みません。"
"42020-78-モエ" = "ところで先生。朝ごはんまだなら、良かったらここで食べていかない？#nちょうど卵もキノコもいっぱいあるし。"
"42020-79-サキ" = "ああ、それがいい。このキノコ、この辺りでは滅多に獲れない種類でな。#n「香りはマツタケ、味はしめじ」と言われるほどの――"
"42020-80" = "[ns] \"でも、これ……。\""
"42020-81" = "[ns] \"ステーキ用の特上牛ロースなんだけど……。\""
"42020-82-ミヤコ" = "え、ええと……その……。"
"42020-83-ミヤコ" = "……も、もちろん市民の安全が一番の喜び、ですが……。"
"42020-84-ミユ" = "特上牛……ロース……ステーキ……！！"
"42020-85-モエ" = "こんな霜降り肉……一度も食べたことない……。"
"42020-86" = "[s5] \"いらないなら仕方ないね……。\"\n[s6] \"いっぱいあるから適当にカップ麺にでも……。\""
"42020-87-サキ" = "なんだと！？"
"42020-88-モエ" = "今、霜降りの特上牛ロースをカップ麺に入れて食べるって言った？"
"42020-89-モエ" = "どんな判断だ！？金をドブに捨てる気か！"
"42020-90" = "[ns7] \"でも他にいい食べ方が見つからないし……。\"\n[ns8] \"それに量も多いから、一人じゃ食べきれないかも。\""
"42020-91-モエ" = "だ、だったらここで食べればいいじゃないか……。"
"42020-92-モエ" = "だ、だったらここで食べればいいじゃないか……。"
"42020-93-モエ" = "ここなら火も使えるし、食べる人ならいくらでも……。"
"42020-94" = "[ns] \"じゃあ、みんなで食べよっか。\""
"42020-95-一同" = "やったー！"
"42020-96-ミヤコ" = "私は網を用意してきますね。"
"42020-97-ミユ" = "お皿、もう一枚とってくる……！"
"42020-98-サキ" = "に、肉には何を添えればいいんだ？#nジャガイモか？それとも玉ねぎ……？"
"42020-99-サキ" = "とりあえずこのキノコは片付けて、と……。"
"42020-100-モエ" = "……滅多に獲れないキノコとか言ってなかった？"
"42020-101-サキ" = "それはそうだが……一生に一度拝めるかどうか分からない特上牛ロースだぞ？#nより相応しいつけ合わせがあるはずだ！"
"42020-102-サキ" = "それよりモエ、早く火を起こしてくれ！#n炭火焼きは火力が命だからな！"
"42020-103-モエ" = "はいはい、おおせのままに～"
"42020-104" = "次回;餌"
