[translation]
"42040-1" = "第4話;予期せぬ再会"
"42040-2-ミヤコ" = "……こちらRABBIT1。現在時刻は1625。"
"42040-3-ミヤコ" = "RABBIT3からのGPS信号を追跡し、ポイン[ruby=シエラ]トSに[/ruby]侵入していた容疑者の位置を特定。ターゲットエリアに到着しました。"
"42040-4-ミヤコ" = "降下ポイントであるポイン[ruby=ロミオ]トRに[/ruby]は現在雨が降っており、#n視界が500m以内に制限されています、注意してください。"
"42040-5-ミヤコ" = "こ、こちらRABBIT4……雨のおかげで通行人はいなさそう……。"
"42040-6-ミユ" = "待ち伏せの戦闘員もいない……この位置ならどこでも狙撃できるよ……。"
"42040-7-ミユ" = "了解。続いてRABBIT2、報告をお願いします。"
"42040-8-ミヤコ" = "こちらRABBIT2、建物外部の閉鎖回路に[ruby=サボタージュ]破壊工作[/ruby]を実行した。#nこれでしばらく警報は鳴らないはずだ。"
"42040-9-サキ" = "だが……。"
"42040-10-ミヤコ" = "RABBIT2、何か問題でも？"
"42040-11-サキ" = "いや、問題というか……この建物、やけに見覚えがあって。"
"42040-12-モエ" = "勘違いじゃない？この近くで作戦を実行した記録はないよ。"
"42040-13-モエ" = "それはわかっている。そうではなく……#nこの建物の「構造」に見覚えがあるんだ。"
"42040-14-サキ" = "3つの進入路と3階建ての迷路のような室内構造……#nまるで、SRT訓練施設の屋内戦訓練場みたいじゃないか？"
"42040-15-モエ" = "くひひ、言われてみればそっくりだねぇ。"
"42040-16-ミユ" = "敵地なのにやけに落ち着くと思ったら、そういうことだったんだね……。"
"42040-17-ミヤコ" = "ええ。見慣れた場所だからこそ、#n不測の事態が起こっても冷静に対処できそうです。"
"42040-18-モエ" = "しかし、この構造は攻撃側に不利なんだよな。#n学園内の模擬戦でも、いつも防御側の勝率が高かったから、少し不安だ……。"
"42040-19-モエ" = "サキ、何ビビってんの？私たちはSRTでしょ。"
"42040-20-モエ" = "もし敵が未知の武器を持っていても、火力でごり押せば問題ないよ、くひっ……。"
"42040-21-サキ" = "……たしかにそうだな。それにPMCのエリートだって私たちの前では手も足も出なかったし……。"
"42040-22-サキ" = "後方支援は任せて……大丈夫、いけるよ。"
"42040-23-ミヤコ" = "では、突入を開始します。RABBIT2、作戦ポイントへ！"
"42040-24-サキ" = "ブリーチング。"
"42040-25-サキ" = "進入路、確保！"
"42040-26-ミヤコ" = "RABBIT1、建物内に進入します！"
"42040-27-ミヤコ" = "……Aサイト、クリア。"
"42040-28-サキ" = "Bサイト、クリア！"
"42040-29-サキ" = "そのままCサイトへ移動する！"
"42040-30-ミヤコ" = "（……変ですね。こんなに入り込んでいるというのに姿を見せないなんて）"
"42040-31-ミヤコ" = "（トラップなどはないようですが……何かを見落としているような……）"
"42040-32-ミヤコ" = "こちらRABBIT2。#nRABBIT1、この先にバリケードが設置されていて進めない。#nどうする？このまま突破するか？"
"42040-33-ミヤコ" = "いえ、大きな音を出すと敵にこちらの位置を察知される危険があります。#n迂回しましょう。"
"42040-34-サキ" = "承知した。開放されている中央通路方面だな……。"
"42040-35-サキ" = "RABBIT2、作戦を続行――"
"42040-36-サキ" = "うっ……！"
"42040-37-ミヤコ" = "今の銃声は！？"
"42040-38-ミヤコ" = "RABBIT2、報告してください。RABBIT2！"
"42040-39-ミヤコ" = "通信が、途切れた……？"
"42040-40-ミヤコ" = "RABBIT4、観測情報を要請します。RABBIT3、GPS情報を確認してください！"
"42040-41-ミヤコ" = "……[ruby=ジャマー]通信阻害[/ruby]、ですか。"
"42040-42-ミヤコ" = "（この状況……RABBIT2はもちろん他の小隊員にも支援を要請できそうにないですね）"
"42040-43-ミヤコ" = "（先頭を奇襲すると共にジャマーを発動し、通信を途絶。#n　各部隊員を孤立させる……）"
"42040-44-ミヤコ" = "（無線が沈黙した状況で相手を制圧するには高度なチームワークが必要……#nその辺の傭兵や生徒ができる事ではありません……）"
"42040-45-ミヤコ" = "（まずは、RABBIT2の救助を……）"
"42040-46-ミヤコ" = "（奇襲！？いつの間に……？）"
"42040-47-？？？" = "………。"
"42040-48-ミヤコ" = "（くっ……通路が狭くて主武装が邪魔に……）"
"42040-49-ミヤコ" = "（近接戦闘は慣れていませんが、仕方ありません……）"
"42040-50-ミヤコ" = "（まず相手の重心を崩すように――）"
"42040-51-？？？" = "……[ruby=フォックストロット]FOXTROT[/ruby]。"
"42040-52-ミヤコ" = "（……！まさか、閃光弾――）"
"42040-53-？？？" = "……1.5秒。爆音と閃光によるストレスの影響があったにせよ、反応が遅い。"
"42040-54-？？？" = "[ruby=近接戦闘]CQB[/ruby]の教範に沿って射程距離の内側に入り込んだのは評価するが、#nその状況では定石通りに手を引くより頭突きをした方が良かったはずだ。"
"42040-55-ミヤコ" = "うっ……！"
"42040-56-？？？" = "下手に動かない方がいい。腕が折れるぞ。"
"42040-57-ミヤコ" = "あなたは……？#n傭兵や武器商人には見えませんが……。"
"42040-58-？？？" = "……作戦において重要なのは、相手の正体でない。#n最悪の事態を想定することだ。"
"42040-59-？？？" = "優れた装備で武装したベテランでも、戦場では流れ弾一発で制圧されてしまう事だってある。"
"42040-60-？？？" = "故に、特殊部隊は臆病者のように慎重に行動する事が求められる。"
"42040-61-ユキノ" = "この声、まさか……"
"42040-62-？？？" = "久しぶりだな、[ruby=つきゆき]月雪[/ruby]小隊長。"
"42040-63-ユキノ" = "……再会できて、嬉しいぞ。"
"42040-64-ミヤコ" = "ユキノ先輩……！？"
"42040-65" = "次回;先輩の影"
