[translation]
"42080-1" = "第8話;新たな代行"
"42080-2" = "連邦生徒会の建物の入口"
"42080-3" = "（カヤの放送を見て、連邦生徒会の建物にやってきた）"
"42080-4-アユム" = "せ、先生……！"
"42080-5-アユム" = "た、大変です……リン先輩が……リン先輩が……！"
"42080-6" = "[s1] \"落ち着いて、アユム。\"\n[s2] \"何があったの？\""
"42080-7-アユム" = "えっと……それが……。"
"42080-8-アユム" = "えっと……それが……。"
"42080-9-アユム" = "リン先輩が、[ruby=なんきん]軟禁[/ruby]されちゃったの。"
"42080-10-モモカ" = "私利私欲のために連邦生徒会長の手紙を偽装して、#n他の役員にテロ行為を仕掛けた疑いだとかでさ。"
"42080-11" = "[s] \"連邦生徒会長の、手紙……？\""
"42080-12-アユム" = "き、きっと何かの誤解です……！"
"42080-13-モモカ" = "誤解っていうか……どうせ誰かに嵌められたんでしょ。"
"42080-14-モモカ" = "あの生真面目な先輩が私利私欲で動く人だったら、#n連邦生徒会の仕事がこんなに行き詰まることなんてなかったはずだし。"
"42080-15-モモカ" = "……まあ、その性格のお陰でこんなにあからさまな手にも#n引っかかっちゃったんだろうけど。"
"42080-16" = "[s] \"アユムとモモカは大丈夫だったの？\""
"42080-17-アユム" = "はい……私たちの方への影響は特にありません。#nですが……"
"42080-18-アユム" = "リン先輩の軟禁が知らされた途端、議会の中で連邦生徒会長代行の後任に#nカヤ防衛室長を推す声が大きくなって……"
"42080-19-アユム" = "リン先輩を支持する人たちは、#n勢いに圧されて会場から追い出されてしまいました……。"
"42080-20-モモカ" = "たしかに働きたくないって何度も言ったけどさぁ……#nまさかこんな風にサボる日がくるとは思いもしなかったよ。"
"42080-21-アユム" = "……[USERNAME]先生、ご足労いただきありがとうございます。"
"42080-22-連邦生徒会役員" = "「新しい連邦生徒会長代行」がお待ちです。"
"42080-23-連邦生徒会役員" = "こちらへどうぞ。"
"42080-24-モモカ" = "――先生、私だったら行かないよ。"
"42080-25-モモカ" = "こんなあからさまな罠、自分からかかりに行くなんて正気？"
"42080-26-モモカ" = "袋ごと潰れたポテチみたいに、ぐちゃぐちゃになっても知らないからね。"
"42080-27" = "[s] \"……きっと大丈夫、なはず。\""
"42080-28" = "[ns] \"行ってくるよ。モモカ、アユム。\""
"42080-29-モモカ" = "はぁ……能天気でポジティブなのが先生の取り柄だけどさ……。"
"42080-30-モモカ" = "まあ、言っても仕方ないか。#n私みたいな怠け者は力になれないだろうし……。"
"42080-31-モモカ" = "ど、どうか気をつけてください、先生……！"
"42080-32-連邦生徒会役員" = "……こちらへ。"
"42080-33" = "連邦生徒会長代行執務室"
"42080-34-カヤ" = "こんにちは、[USERNAME]先生。"
"42080-35-カヤ" = "こちらの事情で突然お呼び立てしてしまい、申し訳ありません。"
"42080-36-カヤ" = "一度迎えを送ったのですが、今日の午後はシャーレにいらっしゃらなかったようですので、このような形を取らせていただきました。"
"42080-37-カヤ" = "現在、連邦生徒会では一刻を争う事案が起きています。#nその件に関して少々先生とお話したく、ご足労頂いた次第です。#n火急の用だったとはいえ、不躾な手段を取ったことをお詫びいたします。"
"42080-38-カヤ" = "……ところで、先程は急用でもあったのでしょうか？#nスケジュール上にはこれといった予定がなかったと記憶しているのですが。"
"42080-39" = "[s] \"ちょっと野暮用で。\""
"42080-40" = "[ns] \"……それより、リンは？\""
"42080-41-カヤ" = "リン行政官は、諸事情で寮に。"
"42080-42-カヤ" = "そして放送でもお伝えしたとおり、彼女の代わりとして、#n現在は私が連邦生徒会長代行を勤めています。"
"42080-43-カヤ" = "――「連邦生徒会長の手紙」に従って。"
"42080-44" = "[s] \"その手紙はどこにあったの？\""
"42080-45-カヤ" = "……シャーレの地下です。"
"42080-46-カヤ" = "そこには手紙だけでなく、クラフトチェンバーを始めとする世に知られていない連邦生徒会長の私物が保管されておりましたので、間違いはないかと。"
"42080-47-カヤ" = "おそらくシャーレに権限を渡す際、ちょっとしたミスがあったのでしょう。"
"42080-48-カヤ" = "リン行政官のような方でも、時には間違えることもありますから。"
"42080-49" = "[s] \"……カヤ、無断でシャーレの地下に入ったの？\""
"42080-50-カヤ" = "……そうですね、その点は否定しません。"
"42080-51-カヤ" = "たしかに私は先のクーデターでD.U.が混乱に陥った際、シャーレの地下に侵入し、#n連邦生徒会長が残した物を持ってくるよう指示しました。#n――連邦生徒会長の真意を知るために。"
"42080-52-カヤ" = "ずっと疑問だったのです。何故、連邦生徒会長は完璧とは言えないリン行政官に代行業務を任せて姿を消したのか、と。"
"42080-53-カヤ" = "そこには何か、凡人には理解出来ないお考えがあるのではないか。#nその思いで私は捜索を遂行し――"
"42080-54-カヤ" = "ついに、彼女の本当の想いを知ることができました。"
"42080-55-カヤ" = "もちろん、そのために先生のプライベート空間を侵害してしまったことは自覚しています。しかし……"
"42080-56" = "[s] \"……仕方のないことだったと思っているんだね。\""
"42080-57-カヤ" = "さすが、理解が早くて助かります。#n先生もご存知ですよね？規則に縛られていては守れない正義があることを。"
"42080-58-カヤ" = "規則とは、司る者が超人でもない限り、いずれ歪みが生じるもの。#nそこにつけいる者が必ず現れる。"
"42080-59-カヤ" = "故に彼らを排除するためには、強い力が必要なのです。"
"42080-60-カヤ" = "……たしかにカイザーコーポレーションは先の件で少々張り切り過ぎていたようですが、彼らの持つ力は紛れもなく本物……。"
"42080-61-カヤ" = "ですので、私はその力を有効活用することに決めたのです。"
"42080-62-カヤ" = "もちろん心配はいりません。#n防衛室長として、力の扱いには慣れていますから。"
"42080-63" = "[s] \"……そんな力を手に入れて、何をするつもり？\""
"42080-64-カヤ" = "あらあら、そんなに怖い顔をしないでください。#nご心配なさらなくても、シャーレに手を出す気はありませんから。"
"42080-65-カヤ" = "シャーレは混乱していた連邦生徒会の代わりに#nキヴォトスの問題を解決し、多くの生徒から絶大な信頼を得ています。"
"42080-66-カヤ" = "お礼を言いこそすれ、危害を加えるなんて私たちがする理由がありません。"
"42080-67-カヤ" = "しかし……先生が日々、多すぎる業務と責任を負っているのも事実です。"
"42080-68-カヤ" = "様々な生徒が当番活動を行い、先生の業務を減らそうと尽力しているようですが……シャーレの根本的な構造を変えない限り、先生の負担は変わらないでしょう。"
"42080-69-カヤ" = "この問題については、「私たち」も考え続けていました。#n先生のために連邦生徒会ができることはないか、と。"
"42080-70-カヤ" = "その答えが――"
"42080-71" = "[ns] \"……これは？\""
"42080-72-カヤ" = "シャーレの行政手続きの改善案です。"
"42080-73-カヤ" = "主に先生の業務負担の軽減を目的とし――"
"42080-74-カヤ" = "いくつかの業務においては、先生の権限が強化される内容となっています。"
"42080-75-カヤ" = "軽く目を通していただき、問題がないようでしたら、#nこちらにサインをお願いします。"
"42080-76" = "[s] \"ここにサインしたら……何が変わるの？\""
"42080-77-カヤ" = "……特に何も。変わるものはありませんよ。"
"42080-78-カヤ" = "先生はやりたいことを続ければいいのです。#n今まで通り、ね。"
"42080-79-カヤ" = "生徒と日常を過ごし、困っている人を助け――"
"42080-80-カヤ" = "ですが、それらを必ずしも行う必要はありません。#n何もせずとも、先生を責める事はありません。"
"42080-81-カヤ" = "お金が必要でしたら、いくらでも支援いたしましょう。"
"42080-82-カヤ" = "面倒な報告書だって、代わりに作成いたしますよ。"
"42080-83-カヤ" = "ええ……すべては、先生の自由ですので。"
"42080-84-カヤ" = "ただ……一つだけ、約束してください。"
"42080-85-カヤ" = "今後シャーレのすべての活動は、連邦生徒会の名で行うと。"
"42080-86-カヤ" = "承諾していただけるのならば、#n先生がされたことに対する責任はすべて私たちが負いましょう。"
"42080-87-カヤ" = "先生がどんな罪を犯しても、どんな問題を起こしても……#n先生が責められることはありません。"
"42080-88-カヤ" = "どうです？悪い話ではないでしょう。"
"42080-89-カヤ" = "ほら、大人は責任を負うのが大嫌いというではありませんか？"
"42080-90" = "ですから、私が先生の面倒を見ます。"
"42080-91" = "何もかもを私に任せて、自由に――楽になりましょう？"
"42080-92" = "[ns] \"提案してくれるのはとても嬉しいけど、遠慮しておくね。\""
"42080-93" = "[ns] \"大人は自分の言動に責任をもってこそだから。\""
"42080-94-カヤ" = "…………はい？"
"42080-95-カヤ" = "先生、もう一度説明させていただきますが……。"
"42080-96-カヤ" = "この改善案は、先生を自由にするための提案です。"
"42080-97-カヤ" = "先生を拘束したり、シャーレの権限を制限したりするものではありませんが……"
"42080-98-カヤ" = "何か気になる項目でもありましたか？"
"42080-99" = "[s] \"たしかに魅力的だけど……。\""
"42080-100" = "[ns3] \"でも、大人が責任逃れをする姿を見せてしまったら……\"\n[ns4] \"先生として、生徒の模範になれないから。\""
"42080-101-カヤ" = "はぁ……。"
"42080-102-カヤ" = "まったく、聞き分けの悪い大人ですねぇ。"
"42080-103-カヤ" = "社会から目をそらし、子どものような空想を抱き続ける……。"
"42080-104-カヤ" = "そんな情けない大人の相手をする事ほど、疲れることもありませんが……。"
"42080-105-カヤ" = "……わかりました。でしたら、この件についてはしばらく保留としましょう。"
"42080-106-カヤ" = "……明日から、新体制になった連邦生徒会による行政改革が行われる予定です。"
"42080-107-カヤ" = "この改革により、キヴォトスは規定によって完璧に統制され、#n安全かつ「素敵な新世界」に生まれ変わることでしょう。"
"42080-108-カヤ" = "新たなキヴォトスをご覧になれば、先生もお考えが変わるかもしれません。"
"42080-109-カヤ" = "私たち防衛室は――いえ、連邦生徒会は、いつでも先生をお待ちしておりますよ。"
"42080-110-カヤ" = "では、引き続きよろしくお願い致します。"
"42080-111" = "[ns] 帰る。"
"42080-112" = "次回;D.U.の新しい朝"
