[translation]
"42140-1" = "第14話;囚人のジレンマ"
"42140-2" = "（荷物を片付けて子ウサギ公園から帰ったら、ずいぶんと遅い時間になってしまった……）"
"42140-3" = "エンジェル24コンビニ"
"42140-4" = "（お弁当の棚を見てみると……）"
"42140-5" = "[ns] \"あれ？お弁当が一つもない……？\""
"42140-6-ソラ" = "す、すみません……今日は全部売り切れてしまって。"
"42140-7" = "[s1] \"今日の夕飯をコンビニ弁当にしようと思ってたのに……\"\n[s2] \"そうなると、廃棄もなかったり……？\""
"42140-8-ソラ" = "はい……いつも廃棄されていたもやし弁当も……"
"42140-9-ソラ" = "それと、何故か昨日からうちの店舗だけお弁当の発注が禁止されてしまって……"
"42140-10-ソラ" = "理由を聞いても、新しい行政命令だ、としか教えてもらえず……#n発注していたお弁当も全部キャンセルされちゃって……"
"42140-11-ソラ" = "もう、残ってるのはミネラルウォーターくらいしかないんです……"
"42140-12" = "[s] \"もしかして、パンとかお茶も……？\""
"42140-13-ソラ" = "はい。パンはもちろん、各種飲み物も発注できなくて……"
"42140-14-ソラ" = "今日は開店休業状態になっちゃいました。#nご不便をおかけして申し訳ありません……"
"42140-15" = "[s3] \"ソラが謝る事じゃないよ。\"\n[s4] （これは……もしかして、私への当てつけなのかな……？）"
"42140-16-ソラ" = "せ、先生……その、最近D.U.で起こっている事について、#n何か知っていたりしますか？"
"42140-17-ソラ" = "一昨日、市内で騒ぎが起きたからか、人がいなくて……#n本社も不穏な空気ですし……"
"42140-18-ソラ" = "サービス業の新たな規則だ、とぶ厚いマニュアルが送られてきたり……#n行政命令を遵守しているか確認する、とカイザーセキュリティの怖い人たちがお店にやってきたり……"
"42140-19-ソラ" = "「エンジェル24」が閉店して、代わりに「カイザー26」になってしまうかもしれないという噂まで流れていて……一体どうすればいいんでしょう？"
"42140-20-ソラ" = "「カイザー26」は、毎日26時間勤務でも足りないくらい労働環境が過酷らしいですし……そんな所で働いたら過労死しちゃいます……。"
"42140-21" = "[ns5] \"26ってそういう意味だったんだ……\"\n[ns6] \"毎日26時間勤務って、不可能では……？\""
"42140-22" = "[ns] \"ソラはもう晩ごはん食べた？\""
"42140-23-ソラ" = "はい。私はお弁当を持ってきたので大丈夫です。"
"42140-24-ソラ" = "昨日、肉じゃがを作りすぎちゃって――"
"42140-25-ソラ" = "あ、えっと……"
"42140-26-ソラ" = "その……もし、良かったら……"
"42140-27" = "[ns] \"だ、大丈夫！気にしないで！\""
"42140-28" = "（さすがにソラのお弁当をもらうわけにはいかないので、慌ててシャーレの執務室に戻った）"
"42140-29" = "シャーレ・執務室"
"42140-30" = "[ns] \"お腹すいた……。\""
"42140-31-？？？" = "「\"FOX EATS\"で―す！」"
"42140-32-？？？" = "「[USERNAME]様、お弁当頼まれましたよね？」"
"42140-33" = "[ns] \"えっと、頼んでいませんが……。\""
"42140-34-？？？" = "「おかしいですね……おいなりさん1人前をこちらに届けてほしいというオーダーを受けたんですよ」"
"42140-35-？？？" = "「確認しますので、少しドアを開けていただけますか？」"
"42140-36" = "[ns7] ドアを開ける。\n[ns8] ドアを開けない。"
"42140-37-？？？" = "「……ありがとうございます」"
"42140-38" = "[ns9] \"君たちは、あの時の……？\""
"42140-39-ニコ" = "こんばんは、先生。またお会いできて嬉しいです。"
"42140-40-オトギ" = "やあ！元気してた？"
"42140-41-クルミ" = "はぁ……また会う事になるなんて……"
"42140-42-クルミ" = "先生は、お夕飯もう食べました？"
"42140-43-？？？" = "……仕方ないですね。#nここで引き返すのも……"
"42140-44-？？？" = "……設置完了、起爆準備。"
"42140-45" = "[s10] \"……何をしているの？\""
"42140-46-？？？" = "3……2……1……"
"42140-47" = "[ns11] \"待って、今開けるから――\""
"42140-48-オトギ" = "おっと、思ってたより派手だったね。"
"42140-49-クルミ" = "オトギ！ブリーチングに一体どれだけの爆薬を使ったのよ？#nドアがフレームごと飛んでいったじゃない！"
"42140-50-オトギ" = "ごめんごめん。CQBには慣れてなくてさ。"
"42140-51-ニコ" = "あはは……すみません、先生。#nドアはすぐ修理しますので……"
"42140-52" = "[s12] \"君たちは、あの時の……？\""
"42140-53-ニコ" = "こんばんは……というには少しおこがましい状況ですが……#nまたお会いできて嬉しいです、先生。"
"42140-54-ニコ" = "先生は、お夕飯もう食べました？"
"42140-55" = "[ns] \"まだだよ。\""
"42140-56-ニコ" = "……やっぱり。"
"42140-57-ニコ" = "今回の行政命令で、コンビニの物流に影響が出てしまったみたいで……"
"42140-58-オトギ" = "影響も何も、言いなりにならないから意地悪してるだけじゃない。"
"42140-59-クルミ" = "小学生じゃあるまいし……こんな事するなんて、ほんとバカみたい。"
"42140-60-オトギ" = "まあでも、敵の野営中に兵糧を断つのは戦略の一つだよ。"
"42140-61-オトギ" = "いくら強い意思を持っていたとしても、お腹を空かせてしまっては戦えないからね。"
"42140-62-ニコ" = "別に、先生はシャーレで野営をしているわけじゃないと思うよ……"
"42140-63-ニコ" = "ええと、とりあえず。私たちFOX EATS……#nいえ、FOX小隊が簡単なお食事を用意してきました。"
"42140-64" = "[ns] \"これは……いなり寿司？\""
"42140-65-ニコ" = "はい。以前も私が作ったおいなりさんを食べたことがありますよね？"
"42140-66-ニコ" = "美味しそうに食べてくださっていたので……あの時と同じレシピで作ってきました。"
"42140-67-ニコ" = "たくさんありますから、好きなだけ召し上がってください。"
"42140-68-オトギ" = "まぁ、私たちが持ってきた食べ物を口にするのは気が引けると思うけど――"
"42140-69" = "[ns] おいなりさんをいただく。"
"42140-70-オトギ" = "……ふつーに食べてるよ？"
"42140-71-クルミ" = "え……？マジ……？#nヤバ……警戒心とかないの……？"
"42140-72-ニコ" = "あの、大丈夫ですか……？"
"42140-73" = "[s13] \"大丈夫、美味しいよ。\"\n[s14] \"味もいい感じに染みてて、ご飯もほどよい固さで最高だよ！\""
"42140-74-ニコ" = "いえ、そういう意味ではなくて……"
"42140-75-ニコ" = "私たちが言うのも違うかもしれませんが……#n毒が入っているかもとか、疑ったりしないのですか？"
"42140-76" = "[s] \"……え？このおいなりさんに毒入ってるの？\""
"42140-77-ニコ" = "いえ、入っていませんが……"
"42140-78-クルミ" = "あのね、何か勘違いしてるみたいだけど……今の私たちは敵対関係にあるのよ。"
"42140-79-クルミ" = "シャーレの先生ならもう知ってるでしょ？私たちFOX小隊は、SRT特殊学園復活のためにカヤ連邦生徒会長代行と手を組んでる。"
"42140-80-クルミ" = "カヤ連邦生徒会長代行の提案を断ったのに、協力者の私たちが何の下心もなく食べ物を持ってくるとでも思ったわけ？"
"42140-81-クルミ" = "いくらお人好しでも限度ってものがあるでしょ……"
"42140-82-オトギ" = "「敵に塩を送る」なんて言ったりもするけどさぁ、#n普通は敵が送ってきた物には手を出さない方が賢明だよねぇ。"
"42140-83-オトギ" = "戦場だとさぁ、敵に奪われた時のために、わざと不良弾薬を持っておく事があるし……"
"42140-84-オトギ" = "SRTでも「敵陣では自分で持ってきた食べ物以外は水も飲むな」と繰り返し教えているくらいなんだけど……"
"42140-85" = "[ns] \"私は君たちの敵じゃないからね。\""
"42140-86" = "[ns] \"……ただの先生だよ。\""
"42140-87-オトギ" = "うーん……。"
"42140-88-クルミ" = "……聞いてた通りの人みたいね。"
"42140-89-ニコ" = "敵じゃなくても、簡単に人を信じると後で痛い目をみますよ。"
"42140-90-ニコ" = "すぐに信用するというのは、相手に対して未熟だという印象を与えてしまいますから……交渉事で損をしやすいんです。"
"42140-91-ニコ" = "社会では、他人に対しては最初から疑ってかかって……#nちゃんと警戒しないと損をしてしまう――"
"42140-92-ニコ" = "……先生も大人ですから、ご存知ですよね？"
"42140-93" = "[s] \"疑って失うものより、信じて得るものの方が多いからね。\""
"42140-94-クルミ" = "……ふぅん。"
"42140-95-クルミ" = "先生は「囚人のジレンマ」を知らないの？"
"42140-96-クルミ" = "お互いが相手に有利な選択をすれば何の損害も受けないけど、#n相手が自分を裏切れば余罪を被ることになる状況で――どんな選択が一番「合理的」なのかを論じたもので……"
"42140-97-クルミ" = "つまり――相手の選択とは関係なく、裏切った方が得だから、#n常に裏切りを選ぶのよ。"
"42140-98-クルミ" = "実際、私たちもこれまでたくさんの「囚人」と相対してきたけど……#nわざと相手の有利になるような選択をする人は一人もいなかったわ。"
"42140-99-クルミ" = "……大人の言う「信頼」も、本質的には同じ。"
"42140-100" = "[s15] \"なんだか難しい話だけど……興味深いね。\"\n[s16] \"……さすがSRTのエリートだね！\""
"42140-101-クルミ" = "ふん、エリートじゃなくてもこの程度は知ってて当然――"
"42140-102-クルミ" = "じゃなくて……！"
"42140-103-オトギ" = "チョロい……"
"42140-104" = "[s] \"でも、現実では違うんじゃないかな？\""
"42140-105-オトギ" = "もちろん、これを現実に置き換えて考えるなら、色んな変数も加味しないとねぇ。"
"42140-106-オトギ" = "この選択がもたらした結果が、未来にどんな影響を及ぼすかとか……"
"42140-107-オトギ" = "……でも先生。この話は一本勝負でも終われるよ。"
"42140-108-オトギ" = "敗者が永遠に戻って来られない野生の社会で最も有効なのは#n「常に相手を裏切って恐怖を抱かせる事」――All-Defect戦略。"
"42140-109-ニコ" = "……これが終わったら、私たちは二度と戻って来られないかもしれません。"
"42140-110-ニコ" = "でも、私たちは武器ですから。#n先生の選択を覚えることもありません。"
"42140-111-ニコ" = "この選択が他の生徒に影響を与えることもないでしょう。"
"42140-112-ニコ" = "それでも私たちを……生徒を信頼するのですか？"
"42140-113" = "[s] \"うん、信頼するよ。\""
"42140-114-クルミ" = "口ではなんとだって――"
"42140-115-オトギ" = "……落ち着いて、クルミ。"
"42140-116-ニコ" = "みんなが今日のことさえ約束できないのに、#n先生は明日の可能性に賭けるのですね。"
"42140-117" = "[ns] \"もちろん。\""
"42140-118" = "[ns17] \"私は先生だからね。\"\n[ns18] \"明日の大人になる子供たちを導くのが役割だから。\""
"42140-119-クルミ" = "……変な人。"
"42140-120-オトギ" = "……本当に、噂通りというか。"
"42140-121" = "[s] \"それに「信頼」の強さは君たちが証明してくれてるからね。\""
"42140-122" = "[ns19] \"FOX小隊は小隊長に対する信頼が厚いチームだと聞いてるよ。\"\n[ns20] \"FOX小隊の強みは、隊員同士の信頼関係にあると思ってるよ。\""
"42140-123-ニコ" = "ユキノちゃん、ですか……。"
"42140-124-クルミ" = "……まあ、一応そうね。"
"42140-125-オトギ" = "……小隊長だし。"
"42140-126" = "[ns] \"……どうかしたの？\""
"42140-127-ニコ" = "いえ、何も……。"
"42140-128-ニコ" = "FOX小隊の絆は何よりも強固ですからね。"
"42140-129-オトギ" = "少なくとも、タヌキみたいな先生の一言で揺らぐようなことは絶対にないわ。"
"42140-130-オトギ" = "……一応、小隊長になる前からの親友だしね。"
"42140-131-ニコ" = "ありがとうございました。先生のお心は確認できたみたいですし……"
"42140-132-ニコ" = "お弁当もお届けしましたので、私たちはそろそろ帰りましょうか。"
"42140-133-ニコ" = "夜分に大変失礼しました。#n急に質問攻めにしてしまって申し訳ないです……"
"42140-134-ニコ" = "そのお詫びにはならないかもしれませんが、#n何か私たちに聞きたいことはありますか？"
"42140-135" = "[s21] \"RABBIT小隊がそっちに合流したって聞いたけど……\"\n[s22] \"RABBIT小隊のみんなは元気？\""
"42140-136-オトギ" = "RABBIT小隊はいま……"
"42140-137-オトギ" = "小隊の位置は一応機密扱いだから、ちょっと言いづらいね……"
"42140-138-ニコ" = "……シャーレ前の停留所から、新木呂尾方面の10番バスに乗って終点で下車し、乾いた渓谷に沿って東に1kmほど歩いていくと地図にはない施設があります。"
"42140-139-ニコ" = "放棄されたキャンプ場に見えるかもしれませんが、そこは連邦生徒会長が失踪する前にSRT生の訓練と作戦のために建てられた軍事施設です。"
"42140-140-ニコ" = "……RABBIT小隊は、そこにいます。"
"42140-141-ニコ" = "あの子たちの安否は、[USERNAME]先生がその目で確かめてください。"
"42140-142-クルミ" = "ちょっと、ニコ！どうして言っちゃうの？"
"42140-143-クルミ" = "彼女達が滞在している宿営地の場所は2級機密に当たるのよ？"
"42140-144-ニコ" = "大丈夫、安否を聞くぐらいなら問題にはならないから。"
"42140-145-ニコ" = "でも、バレたら怒られちゃいそうだから……ユキノちゃんには内緒にしてね。"
"42140-146-クルミ" = "本当に、あんたねぇ……！"
"42140-147-クルミ" = "はぁ……どうなっても知らないわよ。"
"42140-148-オトギ" = "副小隊長の命令だし、従うしかないよねぇ。"
"42140-149-ニコ" = "ふふっ、ありがと。"
"42140-150-ニコ" = "それに[USERNAME]先生があの子たちを変えられるなら、いつかは私たちも……"
"42140-151-オトギ" = "それでは、また……。"
"42140-152-オトギ" = "いえ、お元気で――先生。"
"42140-153" = "（FOX小隊員が帰った後、残ったおいなりさんを食べながら、これからのことについて考えた）"
"42140-154" = "（……ニコが持ってきてくれたおいなりさんは、以前より少しだけ味が濃い気がした）"
"42140-155" = "次回;SRTの正義"
