[translation]
"10019060-1-モモカ" = "よし、これで5か所のサンクトゥムは全部攻略完了！"
"10019060-2-モモカ" = "残るは――D.U.中心部の第6サンクトゥムだけ！"
"10019060-3-リン" = "はい。それでは「シャーレ」の全戦力を第6サンクトゥムに集結させます。"
"10019060-4-リン" = "おそらく、これが最後の戦いとなるでしょう。"
"10019060-5-リン" = "第6サンクトゥム攻略の準備をお願いします……！！"
"10019060-6-モモカ" = "ま、待ってください……！#nD.U.シラトリ区から、強力なエネルギー反応が確認されました……！！"
"10019060-7-アユム" = "こ、これは……"
"10019060-8-リン" = "……！？#nついに、第6サンクトゥムの「守護者」が……？"
"10019060-9-リン" = "んん……？#nり、リン先輩待って……！こっちもヤバい。"
"10019060-10-リン" = "破壊されたサンクトゥムの座標から、超高濃度のエネルギー反応が……！！"
"10019060-11-リン" = "！！"
"10019060-12-アユム" = "破壊したはずのサンクトゥムが――"
"10019060-13-モモカ" = "……こ、これ……一体どういう事……復活したってわけ？"
"10019060-14-リン" = "……っ！"
"10019060-15-アユム" = "こ、れは……"
"10019060-16-アユム" = "今までの攻撃は、無意味だったのでしょうか……？"
"10019060-17-ヒマリ" = "いいえ、それは違います。"
"10019060-18-ヒマリ" = "各サンクトゥムが復活したことで、第6サンクトゥムのエネルギー反応が消滅しました。つまり、アレは他サンクトゥムのバックアップシステムだったと見て良いでしょう。"
"10019060-19-ヒマリ" = "これで第6サンクトゥムは他と変わらなくなりました。#n「守護者」が出現したことがその証左です。"
"10019060-20-リン" = "……それであれば話は単純ですね。 "
"10019060-21-リン" = "復活した5つのサンクトゥム、そして第6サンクトゥムの攻略を――開始します！！"
"10019060-22-リン" = "先生。#nもう一度、指揮をお願いします。"
