[translation]
"10019010-1" = "うわぁぁっ！出たわよ！！"
"10019010-2" = "さあ、走りましょう！"
"10019010-3" = "目標地点まで引きつけるよ～"
"10019010-4-マキ" = "エネルギー反応！？#nき、気をつけて、レーザーが来るよ！！ "
"10019010-5-セリカ" = "こ、こっちに来てるわよ！？"
"10019010-6-アヤネ" = "回避タイミングが計算できません！#n――ホシノ先輩！"
"10019010-7" = "うっわ、アレ直撃……？"
"10019010-8" = "あ、アル様……！"
"10019010-9-アル" = "……ふん。"
"10019010-10-アル" = "あの程度でやられる訳ないわ。予定通り、計画を進めるわよ。"
"10019010-11-ハルカ" = "そ、そうなんですか……？#n……そ、そうですね、分かりました！"
"10019010-12-ムツキ" = "……なるほどねぇ。#nんじゃ、引き続き前進～☆"
"10019010-13-マキ" = "うわぁああっ！？正面から食らっちゃってるよ、ヤバいって！！"
"10019010-14-アヤネ" = "……いえ、あの程度ならおそらく――"
"10019010-15-アヤネ" = "ホシノ先輩、状況はどうですか？"
"10019010-16-ホシノ" = "いやぁ、なかなか痛いねぇ～#nでもまあ、セーフかな。"
"10019010-17-ノノミ" = "うんうん、私たちは無事ですよ、アヤネちゃん。"
"10019010-18-セリカ" = "この程度、どうってことないわよ。"
"10019010-19-マキ" = "あの攻撃を、耐えた……！？ "
"10019010-20-ホシノ" = "ほんと、危ないとこだったよぉ～#n最近腰も弱ってきてるし、無理はできないんだけどなぁ……湿布代もバカにならないしさぁ～"
"10019010-21-ホシノ" = "だからそんなに歳変わらないでしょうが！！"
"10019010-22-マキ" = "……すごいね、あなた達の委員長……いや、アビドスってみんな強いんだね。"
"10019010-23-セリカ" = "えっ、そうなの？ "
"10019010-24-アヤネ" = "あはは……比較するものが無いから、あまりよく分からないんですけどね……"
"10019010-25-アヤネ" = "……これで攻略準備は完了です！お疲れ様でした。"
"10019010-26-アヤネ" = "第1サンクトゥムの守護者との交戦、すぐにでも開始できます！"
"10019010-27-ホシノ" = "じゃあ、ちゃちゃっと行っちゃおっか。"
