[translation]
"10019020-1-エイミ" = "防衛隊とパラシュート隊が合流。#n現在、最後の交戦中。"
"10019020-2" = "ははっ！結構やるじゃねーか！#nお前、気に入った！"
"10019020-3" = "ひゃっはははあぁーーっ！"
"10019020-4-エイミ" = "……あの二人、楽しそうだね。"
"10019020-5-エイミ" = "なかなか珍しい光景っすねぇ～"
"10019020-6" = "う、うーん……。"
"10019020-7-アカネ" = "それにしても……"
"10019020-8-アカネ" = "敵の数が全然減りません。"
"10019020-9-アカネ" = "これでは埒があきませんね……"
"10019020-10-？？？" = "……ご苦労、諸君！"
"10019020-11-アカネ" = "え、えっと……どちら様でしょうか？"
"10019020-12-イチカ" = "あれ、あの制服は……"
"10019020-13-イチカ" = "レッドウィンター……？"
"10019020-14-親衛隊" = "おいらこそが、このレッドウィンター連邦学園の生徒会長であり、環境美化部部長兼、書記長兼、清掃部部長兼、風紀委員長兼、給食部部長の――"
"10019020-15-親衛隊" = "偉大なるチェリノ様だ！！"
"10019020-16-親衛隊" = "カムラッドの救援要請を受けて、諸君たちを助けに来たぞ！#nこの一大事に、おいらが居なくては皆が困るだろうからな！"
"10019020-17-ツルギ" = "……。"
"10019020-18-カリン" = "……。"
"10019020-19-イチカ" = "えっーと……愉快なアクセサリーっすね。"
"10019020-20-イチカ" = "あれってヒゲ？#nあはははっ！すっご～い！"
"10019020-21-ネル" = "（何だあのヒゲ……か……カッケェ！？！？）"
"10019020-22-エイミ" = "……。"
"10019020-23-エイミ" = "……ええっと、応援部隊、なんですよね？"
"10019020-24" = "そうだよ。レッドウィンターの応援部隊を確認。#nこれで互角に渡り合えそうだね。"
"10019020-25" = "おら！仕切り直しだ、行くぞ！！"
"10019020-26" = "きひひっ……"
"10019020-27-チェリノ" = "諸君、戦列を整えろ！ "
"10019020-28" = "これより、レッドウィンター大決戦を始める！"
