[translation]
"34100-1" = "第10話;アリウス自治区へ（２）"
"34100-2-ミサキ" = "……ここから地下道を通ってカタコンベの入り口に入る。"
"34100-3-ミサキ" = "でも……さっきの様子を見るに、「彼女」も私たちがこの通路を使うだろうことは分かってるみたいだね。"
"34100-4-サオリ" = "……ああ。おそらく準備されているだろうな。"
"34100-5-ミサキ" = "まあ、少し考えれば分かることか。"
"34100-6-ミサキ" = "そもそも、アリウスの生徒なら誰でも知ってる入り口だし。"
"34100-7-ヒヨリ" = "そ、それではどうしましょう？"
"34100-8-ミサキ" = "そうは言っても迂回路は無いし、当然他の入り口を探す時間もない。"
"34100-9-サオリ" = "強行突破する。"
"34100-10-ミサキ" = "……だね。どうせ向こうも私たちも、考えは同じ。でも私達には「シャーレ」の先生がいる。"
"34100-11-ヒヨリ" = "へへ……そ、そうですね。よろしくお願いします……。"
"34100-12" = "[s] \"え、う、うん。こちらこそ……？\""
"34100-13-サオリ" = "この先には訓練されたエリート兵が待ち受けているはずだ。"
"34100-14-サオリ" = "我々が先頭に立つ。先生は安全が確保されたら、後ろからついてこい。"
"34100-15-サオリ" = "厳しい戦いになるが、ここを突破すればアリウス自治区に入れる。"
"34100-16-サオリ" = "行くぞ。"
