[translation]
"34110-1" = "第11話;追撃者"
"34110-2-サオリ" = "[ruby=みその]聖園[/ruby]、ミカ……。"
"34110-3-ミカ" = "悪役登場☆ってところかな！……まだ覚えててくれてたんだね？"
"34110-4-ミカ" = "会えて嬉しい……って顔じゃなさそうだけど、どうしたの？"
"34110-5-ミカ" = "そんな、魔女でも見たみたいな顔しちゃって。"
"34110-6-サオリ" = "……檻の中にいると聞いたが。"
"34110-7-ミカ" = "出てきちゃった☆#n……早く、あなた達に会いたくってさ。 "
"34110-8-ミカ" = "だってほら……私たち、まだお話しなきゃいけない事があるんじゃないかなって。"
"34110-9-ヒヨリ" = "……。"
"34110-10-ヒヨリ" = "……先生は？"
"34110-11-ヒヨリ" = "う、後ろから来てます……多分すぐに到着するかと……。"
"34110-12-ミカ" = "私もこれまで、それなりにあなた達と一緒に行動してたからさ。ここに来るってすぐ分かったよ。"
"34110-13-ヒヨリ" = "……通路が閉じるまでは？"
"34110-14-ヒヨリ" = "残り約28分……まさか戦うつもり？今、あの女と交戦するのは無謀だと思うけど。"
"34110-15-ヒヨリ" = "む、無謀ですかね……？"
"34110-16-ヒヨリ" = "……。"
"34110-17-ヒヨリ" = "ただでさえ、姫と一緒にアリウスから逃げ続けた私達の体力は底を尽いてる。#n指揮が無ければ、まともに戦える状態じゃない。"
"34110-18-ヒヨリ" = "さっきまでは、先生の指揮があったからなんとか戦えてたけど……。"
"34110-19-ヒヨリ" = "聖園ミカ……彼女はティーパーティーとしては異様なほど、それこそ群を抜く武力を持っている。おまけに、乱戦のこの状況は彼女にとって最も有利な戦場だよ。"
"34110-20-ミカ" = "あはは☆[ruby=ぐどん]愚鈍[/ruby]な女だと侮ってたのかな？そうだよね。#nでも、あなた達の暗号ぐらいは分かるんだから。"
"34110-21-ミカ" = "集合場所とか、拠点とかもまだ覚えてる。#nこう見えても、クーデターを起こした張本人だからね！"
"34110-22-ミカ" = "あはは。多分、バカだと思われてたみたいだけど。#n……利用しやすかったかな？まあそれは否定しないよ。"
"34110-23-ヒヨリ" = "後退して、出直すのは？"
"34110-24-ヒヨリ" = "無理だ、時間がない。じきに通路が閉じる。"
"34110-25-ヒヨリ" = "先生が到着するまで時間を稼ぐのは？"
"34110-26-ヒヨリ" = "それは……"
"34110-27-ミカ" = "ねえねえ、私の話聞いてる？無視？#n無視ってひどくない？これでも一緒にクーデターを起こした仲なのにさぁ。"
"34110-28" = "それって……仲間外れじゃないの？"
"34110-29-ヒヨリ" = "ひっ！こ、こっちに来ました！？"
"34110-30-サオリ" = "散れ！正面から受けるな！"
"34110-31" = "[ns1] （先に入って、中の状況を伝えてくれるはずのスクワッドと連絡がつかない）\n[ns2] （さっきの銃声は……）"
"34110-32" = "[ns] （急いで追いかけないと）"
"34110-33-ヒヨリ" = "う、うう……速すぎます……。"
"34110-34-サオリ" = "くっ……"
"34110-35-ミカ" = "ねえ？ねえねえサオリ？本当にこれで終わりなの？"
"34110-36-ミカ" = "お飾りの人形だって今のあなたよりは上手く戦えるんじゃない？#nこの程度じゃないよね、「スクワッド」は。ねえ、どうしたの？"
"34110-37-ミカ" = "くっ……。"
"34110-38-ミカ" = "あれ、そういえば一人いないね？マスク姿の無口なあの子は？"
"34110-39-サオリ" = "……！！"
"34110-40-ミカ" = "あーあ……もう弾切れなの？#nほら、もっと撃ちなよ？私がこんなに無防備に立っているんだから、さぁ！"
"34110-41-ミサキ" = "ぐ、ぁっ……。"
"34110-42-サオリ" = "ミサキ……！"
"34110-43-ミカ" = "へぇ……あなた達も仲間は大切なんだ？#nてっきり、任務のために一緒にいるだけだと思ってた。"
"34110-44-ミカ" = "どんな人にだって大事な存在っているよね。うんうん、私にもいたから分かるよ。#n――あなた達が殺そうとした、セイアちゃんの事なんだけどさ。"
"34110-45-ミカ" = "知ってる？セイアちゃんってさ、人を怒らせる天才なんだよ。#n何回グーパンが出そうになったか分かんないくらい！"
"34110-46-ミカ" = "でも……普段は嫌なヤツって思ってるのに、いざケガしたら心配なの。#n大丈夫かなって不安になっちゃうの。"
"34110-47-ミカ" = "セイアちゃんが死んだって聞いた時は、すごく辛かった。#n……変だよね。あんなに話すだけでイライラするのに、ちっとも嬉しくなかったの。"
"34110-48-ミカ" = "そりゃあセイアちゃんの事は嫌いだったよ？ワケ分かんない事ばっかいうし。#nでも、私にとっては大切な人だったの。#n――死んで欲しいわけじゃなかった。人殺しになるつもりもなかった。"
"34110-49-ミカ" = "けど、もう……全部、ぜーんぶ無駄になっちゃった……。"
"34110-50-ミサキ" = "ぐっ―――ッ！！"
"34110-51-サオリ" = "ミサキ！！"
"34110-52-ミカ" = "私は……ちょっと痛い目に、みたいなこと言ったよね？#nいつヘイローを壊せなんて言ったのかな？"
"34110-53-ミカ" = "まぁ、私も一人で勝手に暴れて台無しにしたくせに、いまさら被害者ヅラするの？って感じだけどさ……。"
"34110-54-ミカ" = "でも……。"
"34110-55-ミカ" = "私の……大切なもの……ぜーんぶ、なくなっちゃったんだよ？"
"34110-56-ミカ" = "学園も……友達も……宝物も………帰る場所も……先生との約束だって……。"
"34110-57-ミカ" = "明日になったら、全部元通りになるかもしれないって、信じてたのに……。#nそんなものはお話の中だけだった……あはは……運命はもう決まってるみたい。"
"34110-58-ミカ" = "だからさ……「スクワッド」の……特にサオリ。#nあなた達も私と同じ痛みを受けなきゃね。"
"34110-59-ミカ" = "私が失った分だけ、あなた達も失ってよ。そうじゃないと――不公平でしょう？"
"34110-60-サオリ" = "……！！"
"34110-61" = "[ns] \"ちょっと待った！！\""
"34110-62-ミカ" = "せ、せ、先生……！？"
"34110-63-サオリ" = "先生……。"
"34110-64" = "[ns] \"ミカ……一体ここで何をしてるの？\""
"34110-65-ミカ" = "わ、私は……えっと……その……。"
"34110-66-ミカ" = "それより、どうして……？ "
"34110-67-ミカ" = "ね、ねえ……先生！？どうして、先生がスクワッドと一緒にいるの……？"
"34110-68-ミカ" = "こ、こんなはずじゃ……。"
"34110-69-ミカ" = "ねえ……どうしてこうなるの……？#nよりによって、こんな姿を……どうして……。"
"34110-70-アリウスの生徒A" = "こっちだ！"
"34110-71-アリウスの生徒B" = "聖園ミカもいるぞ！撃て！！"
"34110-72" = "[ns] \"ミカ……！\""
"34110-73-ミサキ" = "けほっ……先生、時間がない……すぐ入らないと。"
"34110-74" = "[s3] \"ミカはとにかく、トリニティに戻って！後で説明するから！\"\n[s4] \"トリニティで待ってて！必ず帰るから！\""
"34110-75-アリウスの生徒A" = "あっちだ！「スクワッド」がいる！"
"34110-76-アリウスの生徒A" = "あっちだ！「スクワッド」がいる！"
"34110-77-ヒヨリ" = "い、急がないと！もうすぐ通路が閉まります！"
"34110-78" = "[s] スクワッドと一緒にカタコンベに入る。"
"34110-79-サオリ" = "走れ！"
"34110-80-ヒヨリ" = "はぁ、はぁ……せ、セーフ……。"
"34110-81-ミサキ" = "……まだ通路が完全に閉じるまで猶予がある。追手が来る前に急がないと。"
"34110-82-ヒヨリ" = "移動するぞ。先生、ここから先は道が複雑だから気をつけた方が良い。"
"34110-83-ミサキ" = "こ、ここは電波も通じないから……道に迷ったら終わりです……。"
"34110-84-ヒヨリ" = "この先がアリウス自治区だ。行こう。"
"34110-85" = "[ns] （ミカ……）"
"34110-86" = "[ns5] （まさか、スクワッドに復讐するために脱獄を？）\n[ns6] （トリニティで一体何が……？）"
"34110-87-アリウスの生徒C" = "ヤツら、カタコンベに逃げ込みました！追いますか？"
"34110-88-アリウスの生徒A" = "まだ時間が残ってる、追うぞ！"
"34110-89-ミカ" = "あーもう痛いじゃん！"
"34110-90-アリウスの生徒C" = "聖園ミカ……！？"
"34110-91-ミカ" = "ふーん、援軍？"
"34110-92-アリウスの生徒A" = "聖園ミカ……君は一時期、私たちの自治区を支援してくれていたな。#nそれを考慮して、今すぐここから消えるなら、手出しはしないでおいてやろう。"
"34110-93-ミカ" = "なになに？その程度の人数で私の相手をするってこと？ちゃんと脳みそ入ってる？"
"34110-94-ミカ" = "面白いね！私が一人だからって勝てると思ってるの？#nそんなんじゃ、日常生活大変じゃない？"
"34110-95-ミカ" = "「スクワッド」はどこに行ったの？ねえ、もしかして時間を稼ぐつもり？"
"34110-96-アリウスの生徒A" = "いや……私たちが追っているのは「スクワッド」だ。"
"34110-97-ミカ" = "……えっ？"
"34110-98-アリウスの生徒B" = "「スクワッド」はアリウスを裏切って逃げた。彼女たちを処分するのが我々の任務だ。"
"34110-99-ミカ" = "ちょっと待って……何を言ってるの？裏切り？逃げた？"
"34110-100-ミカ" = "……。"
"34110-101-ミカ" = "あはは☆そうなんだ……面白いね、味方に捨てられちゃったんだ？"
"34110-102-ミカ" = "……サオリ、これがあなたの結末なんだ。"
"34110-103-ミカ" = "……そっか。狩りに失敗した猟犬は用済み、って事なんだね。"
"34110-104-ミカ" = "先生は………。"
"34110-105-ミカ" = "また、危機に陥ってる子のために、その身を犠牲にしてるんだね。"
"34110-106-ミカ" = "本当に、もう……。"
"34110-107" = "……救えないな。"
"34110-108-アリウスの生徒A" = "そこをどけ！今なら目をつぶってやる。"
"34110-109-アリウスの生徒B" = "報告です！スクワッドに「シャーレ」の先生が同行しているとのこと！"
"34110-110-アリウスの生徒A" = "なっ、何だって！？早速、彼女に報告を……。"
"34110-111-ミカ" = "ねぇねぇ、私の話聞いてなかったの？スクワッドは私のものだよ。#n誰にも渡さない。"
"34110-112-ミカ" = "――だからさ、消えてくれる？"
"34110-113-アリウスの生徒C" = "う、撃て！！"
"34110-114" = "次回;アリウス自治区"
