[translation]
"34145-1" = "[ns] \"ミカ……！？\""
"34145-2-サオリ" = "……まさか、ここまで追いかけてきたのか。"
"34145-3-ミカ" = "久しぶり……ってほどでもないか。また会えて嬉しいよ、サオリ。"
"34145-4-ミカ" = "先生が指揮するスクワッドに、どうやったら勝てるか考えてみたんだけどさ……あんまりいいアイデアが浮かばなくて。"
"34145-5-ミカ" = "とりあえず一回ぶつかってみようかな？って思って来てみたんだけど……。"
"34145-6-ミカ" = "……やっぱダメだったね。"
"34145-7-ミカ" = "相変わらず強いね、先生は。"
"34145-8" = "次回;残されたもの"
