[translation]
"34160-1" = "第16話;地下回廊"
"34160-2" = "アリウス分校・旧校舎 "
"34160-3-サオリ" = "こっちだ。"
"34160-4" = "[s] \"ここがアリウス分校の、昔の校舎……。\""
"34160-5-ヒヨリ" = "中に入ったのは初めてです……。"
"34160-6-ミサキ" = "そうだね。ここは廃墟……というより、もはや遺跡に近いところだから。"
"34160-7" = "昔はここでアリウス生が勉強をしていたのでしょうか……。#nど、どんなことを学んでいたんでしょう……。"
"34160-8-ミサキ" = "さぁ……それを覚えている人は、もういないだろうね。 "
"34160-9-ヒヨリ" = "急ぐぞ……回廊は地下にある。"
"34160-10" = "旧校舎・地下回廊"
"34160-11-ヒヨリ" = "み、見つけました！こっちです！"
"34160-12-ヒヨリ" = "そうか。 "
"34160-13-ヒヨリ" = "……待って。"
"34160-14-ヒヨリ" = "リーダーの言葉通り、ここがバシリカまで一直線に繋がっている通路なら……この地形は危ない。"
"34160-15-ヒヨリ" = "待ち伏せの可能性なら私も考えている。だが、むしろ一直線なら……。"
"34160-16-ヒヨリ" = "いや、[ruby=みその]聖園[/ruby]ミカの話。"
"34160-17-ヒヨリ" = "私が彼女ならどうするのか……考えたの。"
"34160-18-ミサキ" = "彼女にとって一番の障害は多分、先生の存在。#n怪我をさせたくもないし、先生の指揮も厄介だろうから。"
"34160-19-ミサキ" = "ならきっと……。"
"34160-20" = "ゴゴゴゴゴゴゴゴゴゴ"
"34160-21-ミサキ" = "これは……。"
"34160-22-ヒヨリ" = "き、気をつけてください！先生、後ろから柱が……！！"
"34160-23" = "[ns1] \"………！！\"\n[ns2] 倒れてくる柱を避けて前へ走る。"
"34160-24" = "ドォォオオン！！！！"
"34160-25-ミサキ" = "くっ……先生、大丈夫？"
"34160-26" = "[s] \"うん、何とか……。\""
"34160-27-ヒヨリ" = "よ、よかったです……急に柱が壊れるなんて……いったい……。"
"34160-28-ヒヨリ" = "あ、ああっ！？り、リーダーは？"
"34160-29-ミサキ" = "リーダー、どこ？"
"34160-30-サオリ" = "……ここだ。反対側にいる。"
"34160-31-ミサキ" = "瓦礫のせいでよく見えない。怪我は？"
"34160-32-サオリ" = "ああ、大丈夫だ。"
"34160-33-ヒヨリ" = "ちょ、ちょっと待ってくださいね、リーダー！柱をどかしてみます……。"
"34160-34-ヒヨリ" = "あ、ああっ！まだ終わってないんですか！？もっと倒れてくるっ！？"
"34160-35-ミサキ" = "……けほっ、けほっ。"
"34160-36-ミサキ" = "ダメだ……完全に塞がれてる。"
"34160-37-ヒヨリ" = "か、完全に終わりですね！？リーダーは大丈夫なんですか！？"
"34160-38-ミサキ" = "リーダー、聞こえる？そっちに戻る道が塞がってないなら、合流地点を探すよ。"
"34160-39-サオリ" = "……いや、それは厳しそうだ。"
"34160-40-？？？" = "……良かった！先生が巻き込まれるかもと思って、威力を下げたんだけどさ。#nそれでも不安だったから。"
"34160-41-サオリ" = "……。"
"34160-42-ミカ" = "まあでも、[ruby=じょうまえ]錠前[/ruby]サオリ――こうして、あなたが綺麗に残ってくれて良かった。"
"34160-43" = "次回;対決"
