[translation]
"34170-1" = "第17話;対決"
"34170-2" = "[ns] \"ミカ！！やめて！！\""
"34170-3-ミカ" = "……ごめんね、先生。#nそれはできないよ。"
"34170-4-ミカ" = "ねえ、サオリ。#n時間がないんでしょう？急がなくていいの？"
"34170-5-サオリ" = "……。"
"34170-6-サオリ" = "日の出まで……あと1時間か。"
"34170-7-ミカ" = "あーあ……せっかく分断したけど……先生がここに来ちゃったら、#nこれ以上私にできる事はないんだよね。"
"34170-8-ミカ" = "でも、それって一体どのくらいかかるんだろうね？"
"34170-9-ミカ" = "――それまで持ち堪えられたらあなたの勝ちだよ、サオリ。"
"34170-10-サオリ" = "……。"
"34170-11-ミカ" = "……なに、その表情。#n何か楽しいことでもあったの？それとも諦めちゃった？"
"34170-12-サオリ" = "……いや、昔のことを思い出しただけだ。"
"34170-13-サオリ" = "……。"
"34170-14-サオリ" = "来るな！！先生！！"
"34170-15-ミカ" = "……！！"
"34170-16-ミサキ" = "……。"
"34170-17-ヒヨリ" = "！？"
"34170-18-サオリ" = "時間がない……そのままアツコの所へ行ってくれ！"
"34170-19-サオリ" = "……姫を、頼む。"
"34170-20-ヒヨリ" = "リ、リーダー……！"
"34170-21" = "[s] \"…………！！\""
"34170-22-ミサキ" = "……リーダーの言う通りだよ。"
"34170-23-ミサキ" = "あるのかも分からない道を探す時間はない。"
"34170-24-ミサキ" = "それに、もし道を見つけたとしても――手遅れだよ。"
"34170-25-ヒヨリ" = "……。"
"34170-26-ミサキ" = "今のリーダーではミカの相手なんかできない。#n私たちが到着するまで耐えられるかだって怪しいくらい。"
"34170-27-ヒヨリ" = "で、でも……。"
"34170-28-ミサキ" = "だから……このまま姫を助けに行くのが正しいよ。#n私たちが何のためにここにいるのか、思い出して。"
"34170-29" = "[s] \"…………。\""
"34170-30-ミサキ" = "最終判断は先生に任せる……"
"34170-31-ミサキ" = "それに、ミカは自分がやっている事を自覚しているみたいだけど……"
"34170-32-ミサキ" = "そんなあの女を先生は説得できるの？"
"34170-33" = "[s] \"…………私は。\""
"34170-34" = "[ns1] 目的を果たす。\n[ns2] 急ぐ。"
"34170-35-サオリ" = "……。"
"34170-36-ミカ" = "あーあ……結局、先生は行っちゃったね。"
"34170-37-ミカ" = "よかったねサオリ。#nきっと、あなたのお姫様は助かるよ。"
"34170-38-サオリ" = "ミカ……お前が望んでいたのはこんな事だったのか？"
"34170-39-ミカ" = "私が望んでいたこと……？"
"34170-40-ミカ" = "私、何を望んでたんだっけ……#nああ、うん……そうだね。目的達成、みたいな？"
"34170-41-ミカ" = "……。"
"34170-42-ミカ" = "……でも、別にあなたを狙ったわけじゃないよ。"
"34170-43-ミカ" = "正直に言えば、誰でもよかった。"
"34170-44-ミカ" = "むしろ……先生がここに残ってくれたらいいなーとか……思ったりしたくらい。"
"34170-45-ミカ" = "……まぁ、それはちょっと高望みだと思うけどね。"
"34170-46-サオリ" = "……。"
"34170-47-ミカ" = "えー……そんな目で見ないでくれる？"
"34170-48-ミカ" = "セイアちゃんによく言われるんだよね「衝動的で何も考えてない」ってさ。#n私だって自覚してるけど……ちょっとひどくない？本人に言う？ソレ。"
"34170-49-ミカ" = "……うん。#nやっぱり、私が一番望んでいたのはコレかなぁ。"
"34170-50-ミカ" = "――最も憎いあなたが、こうして私の前にいる事。"
"34170-51-サオリ" = "……。"
"34170-52-ミカ" = "それに、先生は……生徒を助けに行くのが正しいよ。#n最後はすべての苦難を乗り越えてみんなで幸せになる――そんなハッピーエンドに向かうのがね。"
"34170-53-ミカ" = "そして、数多くの悪行を重ねてきた私たちは――ここで結末を迎える。"
"34170-54-サオリ" = "……。"
"34170-55-ミカ" = "だからさ――そろそろ私たちの結末を迎えようか、サオリ。"
"34170-56-ミカ" = "黙ってないで何か言ったらどう？#n「魔女」が「猟犬」を処刑する場面だよ？何か言い残したい事とか、ないの？"
"34170-57-ミカ" = "「納得できない」とか、「お前の不幸は自業自得だろう」だとか、#n言い訳しなくていいの？"
"34170-58-ミカ" = "……いや、納得している。"
"34170-59-ミカ" = "手榴弾！？#n違う……煙幕……？なに、これ？"
"34170-60-ミカ" = "い……いたた……。"
"34170-61-サオリ" = "今は生産が禁止されている武器だ。#nアリウスの訓練場にたくさん捨てられていてな。"
"34170-62-ミカ" = "そうなんだ☆#n別に興味ないんだけど？"
"34170-63-ミカ" = "くっ……！？"
"34170-64-サオリ" = "――お前を相手にする際の注意点は理解した。"
"34170-65-ミカ" = "……うっ。"
"34170-66-サオリ" = "ミカ……私はお前の憎悪を否定しない。"
"34170-67-サオリ" = "お前に幸せな未来が訪れない事も、すべてを奪われた事も、孤独になった事だって……私に原因がある。"
"34170-68-サオリ" = "ならば、私はその憎悪に応じよう。"
"34170-69-ミカ" = "……面白いね、うん。"
"34170-70-ミカ" = "ゲリラ戦でいくんだ？#nまぁ、この地形を考慮したらそれが最善だろうね。"
"34170-71-ミカ" = "それに……それってサーモバリック手榴弾でしょ？あはは☆#nちゃんとたくさん用意してる？少量で私を相手にできるなんて思わないでよね？"
"34170-72-ミカ" = "……これなら、うん。"
"34170-73-ミカ" = "今からちゃんと相手するからさ……全力で抵抗してみてよ？#n――あなたにとっては、すべては虚しいものなんだろうけど。"
"34170-74" = "そうか――なら、最後までもがいてやろう。"
"34170-75-ミカ" = "へぇ……退屈させないでよね？"
"34170-76-ベアトリーチェ" = "面白い見世物。そうして互いの地獄を深めていくなんて……#nミカ、やはりあなたは私のミューズです。"
"34170-77-ベアトリーチェ" = "他者との接触は地獄である……互いが憎しみ合うことで、その実在を証明しているに他なりません。"
"34170-78-ベアトリーチェ" = "証明できない楽園に比べたら、こちらの方がはるかに明確です。#n――そうは思いませんか、セイア？"
"34170-79-ベアトリーチェ" = "……。"
"34170-80-ベアトリーチェ" = "まだ諦めていないようですね。"
"34170-81-ベアトリーチェ" = "……トリニティに戻りたいのですか？#nですが、夢の隙間から脱することは容易ではないでしょう。"
"34170-82-ベアトリーチェ" = "あなたは「儀式」に巻き込まれましたからね。#nキヴォトスの外部に通じる窓に顔を出したも同然です。"
"34170-83-ベアトリーチェ" = "ええ……あなたの存在はまるで暗闇に浮かぶ灯火のように目立った事でしょう。"
"34170-84" = "……「アレ」によって、ね。"
"34170-85-ベアトリーチェ" = "「アレ」に露出されたあなたの[ruby=mystery]神秘[/ruby]は[ruby=terror]恐怖[/ruby]に反転され――裏面の原理があなたを支配し始めたのです。"
"34170-86-ベアトリーチェ" = "気になりますね……この先、あなたがどうなってしまうのか。#n私たちも何も知らないのです。"
"34170-87-ベアトリーチェ" = "「アレ」について、私たちは全くの無知なのですから。"
"34170-88-ベアトリーチェ" = "解釈されず、理解されず、疎通されず――ただ到来するだけの不吉な光。#n目的も疎通もできない不可解な観念……。"
"34170-89-ベアトリーチェ" = "私たちゲマトリア最大の宿敵……。"
"34170-90-ベアトリーチェ" = "私たちはそれを「色彩」と呼んでいます。"
"34170-91-ベアトリーチェ" = "………ふむ。アレもそろそろ完成が目前ですね。"
"34170-92-ベアトリーチェ" = "ええ、気づきましたか？#nそう――アレが「シャーレ」を相手するために準備した私の切り札。"
"34170-93-ベアトリーチェ" = "聖徒会の最も偉大な聖女――バルバラ。"
"34170-94-ベアトリーチェ" = "彼女が予定通り完成したら……あの人工天使シリーズより強力なはずです……ふふ。"
"34170-95-ベアトリーチェ" = "マエストロの言う通り、この方式に美学はないかもしれませんが……"
"34170-96-ベアトリーチェ" = "「兵器」には兵器なりの機能美というものがありますから。"
"34170-97-ベアトリーチェ" = "その時、マエストロはどのような顔をするのでしょうね……ああ、彼は表情を作れないでしょうが。"
"34170-98-ベアトリーチェ" = "果たしてシャーレとスクワッドは「兵器」を突破し、私の元に来れるのでしょうか？"
"34170-99-ベアトリーチェ" = "ふふ――すべては抗えない運命なのですよ、セイア。"
"34170-100-ベアトリーチェ" = "私とこの地獄の存在証明の行く末を見守ろうではないですか。"
"34170-101-セイア" = "はぁ……はぁ……。"
"34170-102-セイア" = "私は……諦める事などできないよ、ベアトリーチェ。#n何処かに……何処かに……この状況を打破できる方策があるはずだからね……。"
"34170-103-セイア" = "一刻も早く、ここを抜け出す方法を……見つけなければ……。"
"34170-104-セイア" = "いつまでも、この白昼夢に囚われてはいられない……。"
"34170-105-セイア" = "嗚呼……私にはまだ……為すべき事が残っているのだから……。"
"34170-106" = "次回;もう一人の私たち"
