[translation]
"34195-1-セイア" = "此処は……"
"34195-2-セイア" = "蜃気楼……いや……百鬼夜行自治区……？"
"34195-3" = "ふぅむ、お客様かの？"
"34195-4-セイア" = "……！！"
"34195-5-？？？" = "ここに妾以外が足を踏み入れるとは……初めてじゃのう。"
"34195-6-？？？" = "如何してこのような白昼夢に[ruby=まみ]見[/ruby]えたのじゃ？"
"34195-7-セイア" = "貴女は……誰だ？#n私を認識、できるのか？"
"34195-8-？？？" = "……ふむ？"
"34195-9-セイア" = "……。"
"34195-10-？？？" = "……。"
"34195-11" = "次回;聖女バルバラ"
