[translation]
"34250-1" = "第25話;大切な人"
"34250-2" = "[ns] \"みんな大丈夫？\""
"34250-3-ミサキ" = "うん……辛うじて。"
"34250-4-ミサキ" = "ああ……。"
"34250-5-ヒヨリ" = "も、もう本当に終わりなんですよね……？"
"34250-6-ヒヨリ" = "ベアトリーチェは……。"
"34250-7" = "[s] \"逃げたよ。\""
"34250-8-ヒヨリ" = "逃げた……？"
"34250-9" = "[s] \"でも、もう二度とみんなを苦しめる事はないと思う。\""
"34250-10-ヒヨリ" = "……。"
"34250-11-ミサキ" = "……。"
"34250-12-ヒヨリ" = "……。"
"34250-13-アツコ" = "先生、私たちを助けてくれてありがとう。"
"34250-14" = "[s] \"マスクはもう付けなくてもいいの？\""
"34250-15-アツコ" = "……うん、大丈夫。"
"34250-16-アツコ" = "マダムがどうして私にマスクを付けさせたがってたのか、分からなかったんだけど……。"
"34250-17-アツコ" = "アズサの爆弾に巻き込まれた時、私の体を保護してくれた装置があって……#n多分、それを作動させるのに必要だったんだと思う。"
"34250-18-アツコ" = "結局、マダムは私を守るためにこのマスクを付けさせていたんだろうね。"
"34250-19" = "[s1] \"じゃあ、今後も必要な時には付けようか。\"\n[s2] \"アツコが怪我をしたら悲しむ人が多いからね。\""
"34250-20-アツコ" = "……。"
"34250-21-アツコ" = "……。"
"34250-22-アツコ" = "そうだね……マスクはたまに付けるようにする。"
"34250-23-サオリ" = "……先生。"
"34250-24-サオリ" = "約束通り……姫を救ったから……#n先生の好きにしてくれ。"
"34250-25" = "[s] \"好きに……？\""
"34250-26-サオリ" = "私がすべての元凶だ……エデン条約事件も、セイア襲撃も、ナギサ襲撃も………#nミサキも、ヒヨリも、アツコも……みんな私のせいでこうなってしまった。"
"34250-27-サオリ" = "連邦生徒会でも、トリニティでも……矯正局でも何でも構わない。#n先生が思う、一番適切な所に私を送ってくれ。"
"34250-28-ミサキ" = "一体何を……！？"
"34250-29-ミサキ" = "り、リーダー……！？"
"34250-30-ミサキ" = "……。"
"34250-31-ミサキ" = "ふ、ふざけないでリーダー……一人だけそんな……！"
"34250-32-サオリ" = "いや……私は、長い間負うべき責任を放棄して生きてきた……。"
"34250-33-サオリ" = "これでいい……今がその時なんだ。"
"34250-34-ヒヨリ" = "り、リーダー……。"
"34250-35" = "[ns3] \"………………。\"\n[ns4] \"……そうだね。サオリは責任を負わないといけない。\""
"34250-36" = "[ns] \"サオリは長い間、周囲の子たちを守るために頑張ってきた。\""
"34250-37" = "[ns5] \"他人の面倒を見て、守り、\"\n[ns6] \"耐え――責任を負ってきたんだ。\""
"34250-38" = "[ns7] \"だからこそ、おかしな環境で狂った教育を受け、\"\n[ns8] \"誤った選択をしてきたのだと思う。\""
"34250-39" = "[ns] \"サオリたちは、罪を犯した悪い生徒……それは変わらない。\""
"34250-40-ヒヨリ" = "……。"
"34250-41-ヒヨリ" = "……。"
"34250-42-ミサキ" = "……。"
"34250-43" = "[ns] \"だからといって、苦しんで当然なわけじゃない。\""
"34250-44" = "[ns9] \"子供たちが苦しむのは、その子のせいじゃない。\"\n[ns10] \"子供たちが苦しむような世界を作った責任は、大人の私が負うものだからね。\""
"34250-45-サオリ" = "な、何言ってるんだ……！そんな……！！"
"34250-46-サオリ" = "では……一体私は……私は何の責任を負わなければならないんだ……？"
"34250-47-ヒヨリ" = "……。"
"34250-48-ミサキ" = "リーダー……。"
"34250-49-アツコ" = "……。"
"34250-50" = "[ns] \"責任を負うのは、自分の人生そのものだよ、サオリ。\""
"34250-51-サオリ" = "……ど、どういう意味なのか、分からない。"
"34250-52-サオリ" = "……私は分かる気がする。"
"34250-53-サオリ" = "姫……？"
"34250-54-アツコ" = "サオリ、やりたい事はある？"
"34250-55-アツコ" = "アズサは学ぶのが楽しいって言ってた。#n友達と一緒にいる事が幸せだって。"
"34250-56-アツコ" = "サオリの好きなものは何？やりたいことは？趣味は？"
"34250-57-アツコ" = "好きな食べ物は？#n私は今まで、一つも聞いたことがない。"
"34250-58-アツコ" = "サオリ、将来の夢は？#nなりたいものはある？"
"34250-59-サオリ" = "……そんな、そんなものは……"
"34250-60-サオリ" = "わからない……一度も、そんなもの考えた事がなかった……。"
"34250-61-サオリ" = "私が何が好きなのか、何がしたいのか……私は、一つも分からない……。"
"34250-62-アツコ" = "サオリは、責任感が強くて………決断力があって……んーと。"
"34250-63-ヒヨリ" = "お、教えるのが上手です……いろいろ……教えてくれる時は、怖いですけど……。"
"34250-64-ミサキ" = "真面目ではあるよね。計画を立てるのも上手いし、指揮をするのも上手だし。"
"34250-65-サオリ" = "……。"
"34250-66" = "[ns] \"そっか……それなら、サオリは今後……。\""
"34250-67" = "[ns] \"いい先生になれるかもしれないね。\""
"34250-68-サオリ" = "……！！！"
"34250-69-ヒヨリ" = "リーダーがせ、先生に……！？"
"34250-70-ミサキ" = "まあ、あんまり想像はつかないけど。"
"34250-71-ヒヨリ" = "ううん、そんな事ないよ。#nよく似合いそう……でしょう？"
"34250-72-サオリ" = "……分からない。私に……そんな未来が本当に……？"
"34250-73-サオリ" = "そんな……人生の責任を負うという意味も、私が好きなことも、そんな未来も……何も分からない……。"
"34250-74-サオリ" = "私は……。"
"34250-75-サオリ" = "……私は、生きていても……いいのか？"
"34250-76" = "[s] \"その答えは、自分で見つけようね。\""
"34250-77-サオリ" = "……。"
"34250-78-ヒヨリ" = "……。"
"34250-79-ミサキ" = "……。"
"34250-80-ヒヨリ" = "……。"
"34250-81" = "[ns] \"じゃあ、ここでお別れだよ。\""
"34250-82-サオリ" = "なっ……！？#n急に……待ってくれ先生！？"
"34250-83" = "[s] \"まだ助けが必要な生徒がいるんだ。\""
"34250-84-サオリ" = "ま、待ってくれ……！！"
"34250-85-サオリ" = "私は……私たちは……。"
"34250-86-サオリ" = "いや、そうか……"
"34250-87-サオリ" = "それを見つけるのが私の……。"
"34250-88" = "[s] \"大人の私が保証するよ――その答えは、必ず見つけられる。\""
"34250-89-サオリ" = "……！！"
"34250-90-ヒヨリ" = "い、行ってしまいました……？"
"34250-91-ミサキ" = "……きっと、ミカを助けに行ったんでしょ。"
"34250-92-ヒヨリ" = "ひ、一人で大丈夫でしょうか……。"
"34250-93-アツコ" = "……大丈夫だと思うよ。あの時もそうだったから。"
"34250-94-サオリ" = "あの時……？"
"34250-95-アツコ" = "先生は大人だから、きっと何か方法があるんだと思うよ。"
"34250-96-アツコ" = "もうベアトリーチェもいなくなって、アリウス自治区を抑圧するのはすべて消えたから。"
"34250-97-サオリ" = "……。"
"34250-98" = "リーダー……。"
"34250-99-アツコ" = "サオリ、大丈夫……？"
"34250-100-サオリ" = "うん……#nまだ……何も分からないけど……それでも……。"
"34250-101-サオリ" = "初めて……この世界にいてもいいのだと、思う事ができたよ。"
"34250-102-ミカ" = "ゲホッ……ゲホッ。"
"34250-103-ミカ" = "……あーあ、全身どっろどろ……。"
"34250-104-ミカ" = "でも……日が昇るまで耐えきったよ……結構大変だったけど……。"
"34250-105-ミカ" = "きっと、アツコは助けられたよね？"
"34250-106-ミカ" = "サオリも、他のスクワッドも……みんな、ハッピーエンドを迎えられたかな。#n先生が一緒にいただろうから、きっと……。"
"34250-107-ミカ" = "うん……それなら、いいや……。"
"34250-108-ミカ" = "ごめんね、先生……私はここまでかな……"
"34250-109-ミカ" = "先生と一緒に、帰りたかったのに……。"
"34250-110" = "[ns] \"待って！！！\""
"34250-111-ミカ" = "せ、せ……先生！？"
"34250-112" = "[s] \"遅くなってごめんね、ミカ。\""
"34250-113-ミカ" = "せ、先生……なんでここに……？#nど、どうして……？"
"34250-114" = "[s] \"言ったでしょ？私はいつもミカの味方だって。\""
"34250-115-ミカ" = "……！！"
"34250-116" = "[s] \"ミカのピンチには、当然駆けつけるよ。\""
"34250-117-ミカ" = "そ、そんな……わ、私は……悪い子で……"
"34250-118-ミカ" = "先生が救う価値のある存在じゃないのに……。"
"34250-119-ミカ" = "そ、それに……せ、先生一人であの聖徒会をどうやって相手にするの……？"
"34250-120-ミカ" = "アレは次元が違うよ、先生……#nわ、私も結構強いけど……アレは反則みたいなものだよ！？"
"34250-121-ミカ" = "先生、お願いだからやめて！#n私はそんな価値のある存在じゃないよ……今からでも逃げて……！！"
"34250-122" = "[s] \"ミカは問題児だよ。\""
"34250-123" = "[ns11] \"でも、問題だらけの不良生徒だとしても……。\"\n[ns12] \"危険に晒されている生徒に背を向ける先生なんて、どこにもいない！\""
"34250-124" = "[ns] 大人のカードを取り出す。"
"34250-125" = "[ns] \"……私の。\""
"34250-126" = "[ns13] \"私の大切な生徒に何してるの！！\"\n[ns14] \"私の大切なお姫様に何してるの！！\""
"34250-127-ミカ" = "！？"
"34250-128-ミカ" = "……わーお。"
