[translation]
"34260-1" = "第26話;これからの私たち"
"34260-2-ハスミ" = "さあ皆さん！カタコンベの道はセイア様が教えてくれた通りに！"
"34260-3-正義実現委員会部員A" = "は、はい……！！"
"34260-4-ハスミ" = "イチカ、そちらはどうですか？先生は見つかりましたか？"
"34260-5-イチカ" = "あ、はい！見つけました。#nところで……ツルギ先輩が……。"
"34260-6-ハスミ" = "……えっ？ツルギが？"
"34260-7-イチカ" = "落ち着いてほしいっす、ツルギ先輩。#nそこはドアじゃなくて壁……。"
"34260-8-イチカ" = "あ、おわった。"
"34260-9-ツルギ" = "……けけけけけけ。"
"34260-10-ツルギ" = "きあああああああっーー！！"
"34260-11" = "[ns] \"ツルギ……。\""
"34260-12-ミカ" = "……正義実現委員？#nど、どうしてここに……。"
"34260-13-イチカ" = "あ、ああ……こんにちはっす、先生。#n正義実現委員のイチカっす。"
"34260-14-イチカ" = "この前、美食研究会の逮捕の際に一応お会いしたっすが……もしかしたら覚えてないかもしれないっすね………ご覧の通り、助けに来たっす。"
"34260-15" = "[s] \"うん、会えてとても嬉しいよ、イチカ。\""
"34260-16-イチカ" = "えへへ……先生と挨拶できて嬉しいっす。"
"34260-17-イチカ" = "ハスミ先輩、先生とミカ様を確保したっす。"
"34260-18-ハスミ" = "それでは早急に安全地帯へ退却してください……先生をカタコンベの確保されたルートへご案内します！"
"34260-19-イチカ" = "はいはーい。さあ、行きましょう！#n皆さんを待っている人がいるっすよ。"
"34260-20-ナギサ" = "先生……！！ミカさん……！！ご無事でしたか！"
"34260-21-ミカ" = "な、ナギちゃん……？#nあれ、どうしてここに……。"
"34260-22-ナギサ" = "ここがアリウス修復作戦の指揮本部です……。"
"34260-23-ミカ" = "ど、どうやってここに来たの……？"
"34260-24-セイア" = "私が教えたのだよ。"
"34260-25" = "[ns] \"セイア……！！？\""
"34260-26-ミカ" = "せ……"
"34260-27-ミカ" = "セイア……ちゃん……。"
"34260-28-セイア" = "本当に愚かだね、ミカ。"
"34260-29-セイア" = "常のように、衝動で動いて事[ruby=あやま]を過つ[/ruby]。それが君の悪癖だよ。"
"34260-30-ミカ" = "……セイアちゃん。#nど、どうやって……？"
"34260-31-セイア" = "……言葉を紡ぐには、些か時間が足りないかもしれないね。"
"34260-32-セイア" = "白昼夢の中で偶然、在る人と邂逅できたんだ……。"
"34260-33-セイア" = "語ると長くなってしまうから割愛するが……言わば、小さな取引を交わしたのだよ。"
"34260-34-ハナエ" = "せ、セイア様……！？"
"34260-35-セイア" = "ゲホッ、ゲホッ……"
"34260-36-セリナ" = "だ、団長！セイア様が……！！"
"34260-37-セイア" = "頼む。今すぐナギサを……シスターフッドと、正義実現委員をここに……！"
"34260-38-ハナエ" = "はい！？#nわ、分かりました！！"
"34260-39-セイア" = "時間がない……今すぐ先生とミカの元へ向かわなければ……！！"
"34260-40-セイア" = "そうして私は……シスターフッドと救護騎士団、そして正義実現委員を呼び出してここへ出動させた。"
"34260-41-セイア" = "一つ確かなことは――ナギサはミカを救うためなら、自分の全ての権力を手放しても構わないとまで告げ、周囲を総動員させたという事かな。"
"34260-42-ナギサ" = "……お願い致します、皆様……#nミカさんを、救ってください……。"
"34260-43-セイア" = "私からも頼む。"
"34260-44-サクラコ" = "……。"
"34260-45-ハスミ" = "そんな……。"
"34260-46-ミネ" = "頭を上げてくださいナギサ様、セイア様。#nあなた方が私たちに頭を下げないでください。"
"34260-47-ミネ" = "ミカ様の問題は承知しました。#nそして……セイア様がご無事でなによりです。一体、何があったのですか？"
"34260-48-セイア" = "それは……語ると長くなってしまうのだが……"
"34260-49-ミネ" = "……分かりました。"
"34260-50-ミネ" = "それならば、今は止めておきましょう。"
"34260-51-サクラコ" = "何より優先すべきは、先生の事です。#n……私も最善を尽くしましょう。"
"34260-52-ハスミ" = "トリニティには私だけでなく、先生を慕う生徒が多いです。#n彼女たちなら協力してくれるでしょう。"
"34260-53-セイア" = "ああ……お願いするよ。"
"34260-54-アズサ" = "……これが、私が知っているカタコンベの変化パターンの全て。"
"34260-55-サクラコ" = "大変助かりました。ありがとうございます、アズサ。"
"34260-56-アズサ" = "えっと……本当に、私が行かなくても大丈夫なのか？"
"34260-57-サクラコ" = "はい。あなたはここで先生を待っていてください。"
"34260-58-サクラコ" = "この任務で補習授業部……特にあなたの手を借りたら、#n私たちの矜持や体裁が崩れてしまいますから。"
"34260-59-サクラコ" = "ハナコさんのお手もそこまで煩わせないようにしております。"
"34260-60-サクラコ" = "これは、私たちで解決させてください。"
"34260-61-アズサ" = "そう……。"
"34260-62-アズサ" = "え、えっと……。"
"34260-63-サクラコ" = "……何か他にあるのですか？"
"34260-64-アズサ" = "その……アツコを、助けてあげて。"
"34260-65-サクラコ" = "アズサ……その子は既に先生が助けていると思いますよ。#n私たちは先生を助けに行くのです。"
"34260-66-アズサ" = "……分かってる。#nでも……どうせなら、他の皆も無事に……助けられたらと思うんだ……。"
"34260-67-サクラコ" = "……そうですか。#n彼女たちは、あなたに銃を向けたというのに……。"
"34260-68-アズサ" = "……うん。数え切れないほどの、取り返しのつかない事をしてるよ。"
"34260-69-アズサ" = "でも……私の家族でもあったんだ……。"
"34260-70-ウイ" = "う、うぅ……いま何時だと思ってるんですか……。"
"34260-71-ハナコ" = "うふふ、皆さん眠りについている時間ですね、ウイさん。#nあちらのページを探してくださいますか？"
"34260-72-ウイ" = "い、いや……ところでどうしてそんな格好を……。"
"34260-73-ハナコ" = "私も急に散歩……いえ、水泳の最中に知らせを受けましたので………"
"34260-74-ハナコ" = "うーん、これでしょうか？次のページを探しましょう。"
"34260-75-ウイ" = "水泳……？この時間に……？#nいや、その前に散歩って言いませんでした！？"
"34260-76-ハナコ" = "待って！そこ、それです！#n見つかりました！古代聖徒会が残したカタコンベの地図！"
"34260-77-ウイ" = "こ、このページですか？#nだいぶ傷んでしまって変色が酷いけど……。"
"34260-78-ハナコ" = "ええ、だからこちらに来たんです。#n古書館の魔術師と呼ばれる[ruby=こぜき]古関[/ruby]ウイさん……。"
"34260-79-ウイ" = "う、あ、うぅ……。"
"34260-80-ハナコ" = "あなたなら、この地図を復元できますよね？#n時間がないんです。"
"34260-81-ハナコ" = "今からこれの復元をお願いできますか、こ・ぜ・き・せ・ん・ぱ・い？#n私が力いっぱいお手伝いしますから。"
"34260-82-ウイ" = "う、うぅ……。#nどうして私がこんな目に……。"
"34260-83-イチカ" = "さあ、行くっすよ！一番近い遺跡はアレっす！"
"34260-84-正義実現委員たち" = "は、はい！"
"34260-85-コハル" = "あ、あの……！"
"34260-86-イチカ" = "あれ？君は……コハル……？"
"34260-87-コハル" = "あ、うぅ……わ、私も正義実現委員会だけど……#nい、今は補習授業部で、一緒に出動できないから……その、先輩……。"
"34260-88-コハル" = "これを……ティーパーティーのあの方に。"
"34260-89-イチカ" = "……これは何すか？#nリボンとアクセサリー……？"
"34260-90-コハル" = "その……正義実現委員会の押収品倉庫に残っていた、あの方の私物……です。"
"34260-91-イチカ" = "ああ……確かにそうっすね。#nこれはミカ様が集めていたアクセサリーっすね。"
"34260-92-イチカ" = "あれ、でも……暴動で燃やされたと聞いてたっすけど……倉庫にあったっすか？"
"34260-93-コハル" = "あ、えっと……燃え残った中から、無事なものをこっそり集めていたんです……#nえ、えっと……本来ならダメ、なんですけど……。"
"34260-94-イチカ" = "……なるほど。#n了解っす、コハル。"
"34260-95-イチカ" = "ミカ様に伝えておくっす。"
"34260-96-コハル" = "あうぅ……ありがとう……ございます。"
"34260-97-ミカ" = "みんな……。"
"34260-98-セイア" = "私たちも、先生の力を借り続けていてはならない。#n彼の人の道先に光を灯せてこそ、理想的な関係足り得るからね。"
"34260-99-セイア" = "だから……君を救うために来たよ、ミカ。"
"34260-100-ミカ" = "……セイアちゃん、相変わらず何言ってるのか分かんないよ。#n本当に偉そうだし、心底ムカつく。"
"34260-101-ミカ" = "何度も懲らしめたいと思ってた。"
"34260-102-ミカ" = "――それでも大好き、セイアちゃん。"
"34260-103-セイア" = "……え？"
"34260-104-ミカ" = "ナギちゃんはヒステリーがひどすぎ！#nっていうか、こんな所まで紅茶を手放せないのちょっとどうかと思うよ？"
"34260-105-ミカ" = "カフェイン中毒？それとも強迫症？"
"34260-106-ミカ" = "――でも、そんなナギちゃんが大好き。"
"34260-107-ナギサ" = "い、いえ、これは……緊張してしまって……。"
"34260-108-ナギサ" = "……えっ？"
"34260-109-ミカ" = "うん……二人とも、大好きだよ。"
"34260-110-ミカ" = "二人ともありがとう……そして、ごめんね……。"
"34260-111-セイア" = "ミカさん……。"
"34260-112-ナギサ" = "……いや、むしろ謝るのは私の方だよ。#n……すまなかった、ミカ。"
"34260-113-ナギサ" = "いつも君に謝ろうと思っていたんだ。"
"34260-114" = "だが、子供みたいな意地が邪魔をして、果たすことができなかった……。"
"34260-115-セイア" = "ミカ……君が、アリウスと和解したいと言い出した時、私は……。"
"34260-116-ミカ" = "ううん、何も言わないで……大丈夫だから。"
"34260-117-ミカ" = "ごめんね……私が悪かったの……。"
"34260-118-ナギサ" = "ミカさん……。"
"34260-119-セイア" = "ミカ……。"
"34260-120-イチカ" = "あ、ええっと……いい雰囲気のなか申し訳ないっすけど……#nミカ様に渡したいものがあるっす。"
"34260-121-ミカ" = "私に……？"
"34260-122-イチカ" = "これを……。"
"34260-123-ミカ" = "……これは。"
"34260-124-ミカ" = "私の……アクセサリー……？#nえ、どうして？全部燃えちゃったはずなのに……！？"
"34260-125-イチカ" = "ああ、えっと……押収品の管理室担当員が……"
"34260-126-イチカ" = "んー、説明しにくいんすけど……"
"34260-127-イチカ" = "その子が、ミカ様のアクセサリーで燃えずに残ってたものを保管してたみたいで。"
"34260-128-ミカ" = "コハルちゃんが……？"
"34260-129-イチカ" = "はい、コハルが……って、"
"34260-130-イチカ" = "ええっ！？#nコハルの事ご存知だったんすか？"
"34260-131-ミカ" = "……うん。知ってる。"
"34260-132-ミカ" = "ありがとうコハルちゃん……#n私、あなたに酷いことをしたのに……。"
"34260-133-セイア" = "……。"
"34260-134-ナギサ" = "……。"
"34260-135" = "[ns] \"お互いに色々と話す時間をとったほうがいいね。\""
"34260-136-セイア" = "……ああ、そのようだね。"
"34260-137-ナギサ" = "では、そろそろ参りましょうか。#nミカさんの聴聞会まで、もう時間がありませんから。"
"34260-138-ナギサ" = "ああ。"
"34260-139-ミカ" = "えー……私、この格好で行かなきゃダメ？"
"34260-140-ミカ" = "ちょっと着替えたいんだけど……傷の治療もしたいし。#n人前に立つんだから、髪もセットし直さなきゃいけないし。"
"34260-141-ナギサ" = "……。"
"34260-142-ナギサ" = "……。"
"34260-143-ナギサ" = "はぁ……好きにするといい。"
"34260-144-ナギサ" = "ええ。それに私たち三人とも徹夜してしまってますし、こんな格好では……。"
"34260-145" = "[ns] \"私も一緒に行くよ。\""
"34260-146-ナギサ" = "……勿論です先生。#n全員で聴聞会に出席するのが、私たちの約束ですからね。"
"34260-147" = "次回;エピローグ"
