[translation]
"1008902-1" = "出番のないドレス"
"1008902-2" = "（何かあったのかと心配になり、便利屋の事務所を訪れた）"
"1008902-3" = "[ns1] \"……あれ、開いてる。\"\n[ns2] \"アル、入ってもいい？\""
"1008902-4-アル" = "……あれ、先生？"
"1008902-5-アル" = "どうしたの？#n何か約束でもあったかしら？"
"1008902-6-アル" = "いや、何もないはず……#nさっきカレンダーを見たばかりだもの。"
"1008902-7-アル" = "……あら、用事があって来たわけではないのね。"
"1008902-8-アル" = "……本当に？たまたま近くに寄ったから？"
"1008902-9-アル" = "い、いえ！ダメとは言ってないわ！#n私もちょうど時間ができたところよ。"
"1008902-10-アル" = "パートナーシップを深めるためには、こういうのも悪くないわね。#nそんなところに立ってないで早く入ってちょうだい、先生。"
"1008902-11-アル" = "……えっと、先生？"
"1008902-12-アル" = "本当にただ寄ってみただけなの？#n先生のことだから、理由があると思ったのだけど……"
"1008902-13-アル" = "何かあるのよね……？"
"1008902-14-アル" = "大丈夫よ、正直に話してちょうだい。#n私たちの間で、今さら気を遣う必要なんて無いわ。"
"1008902-15-アル" = "……え？"
"1008902-16-アル" = "モモトークって……？"
"1008902-17-アル" = "……あ。"
"1008902-18-アル" = "……やっぱり気を遣わせてしまったわね。"
"1008902-19-アル" = "ほ、本当に大したことはなくって……#nむしろ、こう改まって言うのは恥ずかしいというか……"
"1008902-20-アル" = "……うん？"
"1008902-21-アル" = "どうかしたの、先生？"
"1008902-22-アル" = "……ああ、アレ？"
"1008902-23" = "[ns3] \"……ドレス、飾ってるんだね。\"\n[ns4] \"あれから一度も着てないの？\""
"1008902-24-アル" = "う、うーん……"
"1008902-25-アル" = "そ、そうね……"
"1008902-26-アル" = "どうしても、色々と気になっちゃって……"
"1008902-27-アル" = "実はモモトークで相談しようとしていたのは、ドレスに関する話なのよ。"
"1008902-28" = "[s5] \"相談……？\"\n[s6] \"ドレスについて？\""
"1008902-29-アル" = "ええ。"
"1008902-30-アル" = "前回の依頼の時、勢いで手に入れたのは良かったのだけど……"
"1008902-31-アル" = "なかなか着るタイミングがね。"
"1008902-32-アル" = "たまに気分転換に着てみるくらいしか、使い道が無いのよ。"
"1008902-33-アル" = "はあ……"
"1008902-34-アル" = "いっそのこと、売り払って便利屋の運転資金に回した方が良いかしら？"
"1008902-35-アル" = "……結構な値段したわけだし。"
"1008902-36-アル" = "でも、本当に売っても良いものか悩んでしまって……"
"1008902-37-アル" = "そこで先生ならどうするか聞いてみたかったの。"
"1008902-38-アル" = "朝のモモトークはそれだけよ。それ以上の意味は無いわ。"
"1008902-39-アル" = "だから、心配せずとも大丈夫。"
"1008902-40-アル" = "……気分転換に着るくらいでちょうどいいって？"
"1008902-41-アル" = "たしかに、せっかくお気に入りのドレスを手に入れたわけだし……"
"1008902-42-アル" = "手放して後悔するくらいなら、今は手元に置いておいた方が良い気もしてきたわ。"
"1008902-43-アル" = "ただ、どうせなら使ってあげたいところね……"
"1008902-44-アル" = "うーん、ただ置きっぱなしになるくらいなら、やっぱり便利屋のためにもお金にした方が……"
"1008902-45-アル" = "いつまでも悩んでいたところでキリが無いことくらい、分かっているのだけど……"
"1008902-46-アル" = "……ん？"
"1008902-47-アル" = "ドレスを着て何をしたいのか、具体的なイメージはあるのかって？"
"1008902-48-アル" = "えっと、そうね……まだ何も浮かばないかしら……"
"1008902-49-アル" = "……え？"
"1008902-50-アル" = "それなら尚さら手放さない方がいいって……どうして？"
"1008902-51-アル" = "使い道が浮かばないなら、普通は……"
"1008902-52" = "[s7] \"いつか必要になると思うよ。\"\n[s8] \"着るべき時は、いずれ訪れるはずだから。\""
"1008902-53-アル" = "……？？？"
"1008902-54-アル" = "え、えっと……なるほ……ど……？"
"1008902-55-アル" = "どういう意味なのか……"
"1008902-56-アル" = "分かるような……分からないような……"
"1008902-57-アル" = "……ふふっ。"
"1008902-58-アル" = "まあ、いいわ！#nとにかく先生の意見は「持っておくべき」なのね。"
"1008902-59-アル" = "参考にさせてもらうわ。#nひとまずドレスを売るのは保留にしましょう。"
"1008902-60-アル" = "……ふう！"
"1008902-61-アル" = "まだ解決されたわけじゃないのに、おかげでスッキリしたわ。"
"1008902-62-アル" = "……さすが、先生ね。"
"1008902-63-アル" = "でも、きっと先生の言葉だからかしら。"
"1008902-64-アル" = "ふふっ……"
"1008902-65-アル" = "結局こうなるのなら、モモトークで素直に聞いておくべきだったわね。"
"1008902-66-アル" = "……うーん。"
"1008902-67" = "[s9] \"……アル？\"\n[s10] \"どうかしたの？\""
"1008902-68-アル" = "……いや。"
"1008902-69-アル" = "今の言葉は撤回するわ。"
"1008902-70-アル" = "やっぱり、話し合いは電話やメールよりも顔を合わせて行なうものよね？"
"1008902-71-アル" = "……ふふっ。"
"1008902-72-アル" = "だから……"
"1008902-73-アル" = "今後も何かあれば、こうやって……"
"1008902-74-アル" = "直接、話せると嬉しいわ……先生。"
