[translation]
"1600403-1" = "大事なのは中身"
"1600403-2-フィーナ" = "あ、センセイ！来てくれたんデスね！神！"
"1600403-3-フィーナ" = "大変なんデス！一人では解決できマセン！"
"1600403-4-フィーナ" = "……喧嘩？イエ、そういうのじゃないデス。"
"1600403-5-フィーナ" = "服を買いに行きたくって、呼びマシた！"
"1600403-6" = "[s] \"……服？\""
"1600403-7-フィーナ" = "ハイ！この前見た「るろうの柴蔵」に主人公の服が、すっごくステキで！"
"1600403-8-フィーナ" = "デスから、ワタシも同じ服を探しに行きながら……。"
"1600403-9-フィーナ" = "センセイと一緒にアレコレ見たりシテ、これはどうデスか？良いと思うよ、なんて！エヘへ！"
"1600403-10-フィーナ" = "……他の友達？アーー……それは、誘ったのデスが……。"
"1600403-11-フィーナ" = "……。"
"1600403-12-フィーナ" = "なぜか「服を見たいデス」と言うと、いつも優しいみんなが逃げてしまうのデス……。"
"1600403-13-フィーナ" = "いつもはそんなことないのデスが、どうして？と聞いても、ごめんとだけ……。"
"1600403-14-フィーナ" = "バストがどうとか、スタイルがどうとか……良く分からなったデス……。"
"1600403-15-フィーナ" = "……もしかしてフィーナ、何か悪いことをしたのデショウか？"
"1600403-16" = "（フィーナの胸を収めきれずに、苦しそうにしている服が目に入った）"
"1600403-17" = "[s1] \"たしかに、フィーナ（のスタイル）が悪いかも。\"\n[s2] \"……フィーナ「は」悪くないね。\""
"1600403-18-フィーナ" = "エッ……！？そ、そうなのデスか！？"
"1600403-19-フィーナ" = "……？それデハ、誰が……？"
"1600403-20-フィーナ" = "と、とにかく！だからセンセイを呼んだのデス！"
"1600403-21-フィーナ" = "フィーナにはセンセイしかいマセン！助けてくれマスか？"
"1600403-22" = "[s3] \"そういうことであれば喜んで！\"\n[s4] \"私は、逃げるわけにはいかない……！\""
"1600403-23-フィーナ" = "ヒャッホウ！ありがとうございマス！センセイ最高！！それでは出発デス！"
"1600403-24-フィーナ" = "ヒャッホウ！ありがとうございマス！センセイ最高！！それでは出発デス！"
"1600403-25-フィーナ" = "GoGo～！！"
"1600403-26-フィーナ" = "あれ！あれデス！前から行きたかったんデス、似たような服がたくさん！"
"1600403-27-フィーナ" = "うちの服に興味があるのかい？学生さん、良い趣味してるじゃないか。"
"1600403-28-フィーナ" = "フフフ、身に余るお言葉、光栄デス。いつか任侠になるために、修行は怠っていマセン！"
"1600403-29-店長" = "そ、そうか、まあとりあえず……好きに見ていってくれ。"
"1600403-30-フィーナ" = "あ、あれデス！すぐに見つかりマシタ！"
"1600403-31-フィーナ" = "「るろうの柴蔵」で、主人公の「柴蔵」が着ていた服デス！！"
"1600403-32-フィーナ" = "これフィーナが、着ても良いデスか？良いデスよね？着てみマス！！"
"1600403-33" = "え、えっ？ま、待って学生さん！その服は……！！"
"1600403-34-フィーナ" = "アレ、アレレ？服がすごく……小さいような……？"
"1600403-35-フィーナ" = "ん、アレ！？ま、待ってクダサイ！Wait！Wait！！"
"1600403-36" = "プツッ、バリバリバリッ！"
"1600403-37-フィーナ" = "……？"
"1600403-38-フィーナ" = "……や、"
"1600403-39-フィーナ" = "破れてしまいマシタ……。"
"1600403-40-フィーナ" = "……なっ、ナナナナナナナゼ！？ワタシはただ試着をしただけなのデスが……！"
"1600403-41-フィーナ" = "そりゃあ、主人公の「柴蔵」の服だし……。"
"1600403-42-店長" = "柴犬サイズで作られてるものだから……。"
"1600403-43" = "（その後、何度も店長に謝罪をして、服の代金を弁償してお店を出た）"
"1600403-44" = "（その後、他のお店も見て回ったけれど、フィーナのスタイルに合う服は、結局見つからなかった）"
"1600403-45" = "（結局成果が無いまま、日が暮れてしまった）"
"1600403-46-フィーナ" = "結局見つかりませんでした……フィーナの服……。"
"1600403-47-フィーナ" = "「るろうの柴蔵」も、「任侠ニャンニャン伝」も、そして他の映画の主人公たちのも全部駄目デシタ……。"
"1600403-48-フィーナ" = "全部ニャンコさんとワンちゃんの服で……フィーナは着ることができません……。"
"1600403-49-フィーナ" = "……ううっ。"
"1600403-50-フィーナ" = "フィーナ……任侠になりたいのに……。"
"1600403-51-フィーナ" = "フィーナは、「柴蔵」や「任侠ニャンニャン」のようにはなれないのデショウか……。"
"1600403-52-フィーナ" = "……。"
"1600403-53" = "[s] （この間買ったBDを渡す）"
"1600403-54-フィーナ" = "……ん？何デスか？"
"1600403-55-フィーナ" = "「セクシー猫・女傑任侠伝」……？これ、任侠の映画なのデスか？"
"1600403-56-フィーナ" = "……初めて見る映画デス！主人公が任侠の女性なのデスか？メス猫が可愛いデス！！"
"1600403-57-フィーナ" = "ア……。"
"1600403-58-フィーナ" = "この表紙の、肩が出たこの服……。"
"1600403-59-フィーナ" = "これ、すごく……。"
"1600403-60-フィーナ" = "フィーナが今着てる服と……似てマスね……？"
"1600403-61-フィーナ" = "……え？"
"1600403-62-フィーナ" = "任侠映画の女主人公たちは、よく着ているのデスか？今フィーナが着てるこのような服を？"
"1600403-63-フィーナ" = "……たしかに……すごく似ていマス……。"
"1600403-64-フィーナ" = "……はい？"
"1600403-65-フィーナ" = "大事なのは服装ではなく、中身……？"
"1600403-66-フィーナ" = "フィーナはフィーナの任侠を持ってるから、フィーナが着る服こそが任侠らしい服……ですか？"
"1600403-67-フィーナ" = "フィーナの……任侠……。"
"1600403-68-フィーナ" = "……"
"1600403-69-フィーナ" = "……エヘへ。"
"1600403-70-フィーナ" = "ヤッパリ……いつかフィーナと湯呑を飲み交わす相手は、センセイかもしれマセン。"
"1600403-71-フィーナ" = "センセイの話を聞いたら、そんな気がしてきマシタ！"
"1600403-72-フィーナ" = "あれだけ悩んでいた問題を、こんなに簡単に解決するなんて！さすがセンセイ！"
"1600403-73-フィーナ" = "え？あれは湯呑じゃない？そうなんデスか？問題ありマセン。"
"1600403-74-フィーナ" = "……エヘへ。"
"1600403-75-フィーナ" = "なぜなら、大事なのは湯呑かどうかではなく、その中身デスから！ネ？"
"1600403-76" = "（その後、完全にいつもの調子を取り戻したフィーナと、二人で「セクシー猫・女傑任侠伝」を見た）"
"1600403-77" = "（フィーナは満足げな表情で帰っていった）"
