[translation]
"1600902-1" = "忍者少女は気難しい"
"1600902-2" = "（いつものようにシャーレで仕事をしていると……）"
"1600902-3" = "[ns] \"……そろそろお昼でも食べようかな。\""
"1600902-4" = "（仕事がひと段落して立ち上がろうとしたその時、何か変な音が聞こえた）"
"1600902-5" = "[ns] \"……とりあえず今日は時間も無いし、カップ麺で良いかな。\""
"1600902-6" = "[ns] \"あとは3分待って……\" "
"1600902-7" = "（おとなしくカップ麵が出来上がるのを待っていると……）"
"1600902-8" = "[ns] \"……ん？\""
"1600902-9" = "[ns] \"……？？\""
"1600902-10" = "[ns] \"……気のせいかな？\""
"1600902-11" = "[ns] \"あ、3分経ってる。\""
"1600902-12-？？？" = "……ふふっ、隙あり！"
"1600902-13-？？？" = "ぎゃっ！"
"1600902-14-ミチル" = "ちょっとぉ！避けないでよ、先生殿！私のアンブッシュが見事に成功しそうだったのに！"
"1600902-15" = "[s] \"いやいやいや……。\""
"1600902-16-ミチル" = "まったく、勿体ない。"
"1600902-17-ミチル" = "にしても、"
"1600902-18-ミチル" = "私の完璧な奇襲を避けるなんて……先生殿、なかなかやるね！"
"1600902-19" = "[s] \"それほどでも……少し前からちらちら見えてたし。\""
"1600902-20-ミチル" = "むむむっ……！"
"1600902-21-ミチル" = "「お前のアンブッシュなどお見通しだ」と……"
"1600902-22-ミチル" = "なるほど、強者の台詞！"
"1600902-23-ミチル" = "強くない言葉から強さが感じられる表現、良いよね！"
"1600902-24-ミチル" = "うん、やっぱり私の目に狂いは無かった！先生殿には素質がある！"
"1600902-25" = "[s1] \"素質……？\"\n[s2] \"ごめんミチル、ちょっと今カップ麵が……。\""
"1600902-26-ミチル" = "素質と言ったら、忍者の素質に決まってるでしょ！"
"1600902-27-ミチル" = "素質と言ったら、忍者の素質に決まってるでしょ！"
"1600902-28" = "[s] \"忍者の素質……。\""
"1600902-29-ミチル" = "うんうん大丈夫、分かってるよ。"
"1600902-30-ミチル" = "急に忍者を始めるとなっても、その不安な気持ちはよく理解できる。"
"1600902-31-ミチル" = "まず初心者の時は、コツコツとステップアップしていくことが大事だよね？"
"1600902-32-ミチル" = "じゃあまずは……例えば、忍者オタクから始めるのはどう？"
"1600902-33" = "[s] \"忍者オタクがレベルアップすると、忍者に……？\""
"1600902-34-ミチル" = "あ、でも初歩ばっかりやるのも、時には退屈だったりするよね。"
"1600902-35-ミチル" = "うんうん、それも分かる。"
"1600902-36-ミチル" = "複雑な心境、それもまた当然のことだね！"
"1600902-37" = "[s] \"話が勝手に進んでいく……！？\""
"1600902-38-ミチル" = "でも心配しないで、先生殿！私を誰だと思ってるの？私はあの忍術研究部の部長、[ruby=ちどり]千鳥[/ruby]ミチル！"
"1600902-39-ミチル" = "まあ、部活はまだ非公認だけど……将来性はバッチリ！"
"1600902-40-ミチル" = "とにかくそんな先生のためだけに、今なら何と、私たち忍術研究部から「忍者プランB」をご案内！"
"1600902-41" = "[s] \"何か通販番組みたいになってきた。\""
"1600902-42-ミチル" = "まあとにかく、導入には色んなパターンがあるから心配ないよ。"
"1600902-43-ミチル" = "そう、たとえば……"
"1600902-44-ミチル" = "亀とか！"
"1600902-45" = "[s3] \"話が加速して止まらない……！\"\n[s4] \"亀と忍者に、何の関係が……？\""
"1600902-46-ミチル" = "亀と言えば忍者！結構昔からそう相場は決まってるの！"
"1600902-47-ミチル" = "亀と言えば忍者！結構昔からそう相場は決まってるの！"
"1600902-48-ミチル" = "基地を下水道にするのがちょっとハードル高いけど、まあこの間ミレニアムの工事が入ったところなら綺麗だろうし、多分大丈夫……な気がする。"
"1600902-49" = "[s] \"話が見えてこないんだけど、ミチルが今日来たのはどうして……？\""
"1600902-50-ミチル" = "あ、うっかりしてた！"
"1600902-51-ミチル" = "先生殿先生殿！大変なの！本当に大変なことが起きてて……！"
"1600902-52-ミチル" = "えーっと、まず私、動画チャンネル「少女忍法帖ミチルっち」を運営してるでしょ？"
"1600902-53" = "[s5] \"うん、そうだったね。\"\n[s6] \"忍術とかを紹介するチャンネルだよね。\""
"1600902-54-ミチル" = "そうそう！あのチャンネル、週に2回アップするようにしてるんだけど……全然アイデアが浮かばなくなっちゃって……"
"1600902-55-ミチル" = "そうそう！あのチャンネル、週に2回アップするようにしてるんだけど……全然アイデアが浮かばなくなっちゃって……"
"1600902-56-ミチル" = "もー完全にピンチ！もう「ミチルの忍者人生、17年目にして最大の危機！？」みたいなタイトルで雑談配信するしかないくらい！"
"1600902-57-ミチル" = "そのことを相談したくて来てたの！"
"1600902-58" = "[s] \"なるほど。\""
"1600902-59-ミチル" = "このピンチを救えるのは、もう先生殿くらいしかいないんじゃ！？って思って……！"
"1600902-60-ミチル" = "私の頭ではもう限界が来ちゃったんだけど……"
"1600902-61-ミチル" = "先生殿だったら、大人ならではのアイディアを閃いてくれるかも？って。"
"1600902-62-ミチル" = "それでアンブッシュしに来たってわけ！"
"1600902-63" = "[s7] \"アンブッシュは要らなかったんじゃ……？\"\n[s8] \"助けを求めるためだったのに、どうして奇襲が……。\""
"1600902-64-ミチル" = "とにかくお願い、先生殿！一応それっぽいネタの候補は考えてきたから、どれが良いか意見をくれるだけでも……！"
"1600902-65-ミチル" = "とにかくお願い、先生殿！一応それっぽいネタの候補は考えてきたから、どれが良いか意見をくれるだけでも……！"
"1600902-66-ミチル" = "まずはたとえば……「パルクール系忍者に人気の忍具、TOP10レビュー！」とか。"
"1600902-67-ミチル" = "他にも……「『忍者デストロイヤー実写版』のCGについて分析してみよう！」とか。"
"1600902-68-ミチル" = "あ、「忍者はどうしてラーメン屋で『ニンニク多めチャーシュー追加』にしがちなのか！」でも良いかも！"
"1600902-69" = "[s9] \"最後のは一体……？\"\n[s10] \"それ、忍者の話かな……？\""
"1600902-70-ミチル" = "細かいことは良いから！さあ、先生殿はどれがいいと思う？"
"1600902-71-ミチル" = "細かいことは良いから！さあ、先生殿はどれがいいと思う？"
"1600902-72-ミチル" = "見ただけで忍者に興味が湧いて、"
"1600902-73-ミチル" = "「忍者って最高だな～」って思えて、"
"1600902-74-ミチル" = "「これを作った忍術研究部の部長ってもしかして天才！？」ってなるような……！"
"1600902-75-ミチル" = "そんな最高の動画になりそうなネタ、どれかな！？"
"1600902-76" = "[s] \"期待が重い！！\""
"1600902-77-ミチル" = "あ、もちろんこれ以外のネタでも大歓迎！"
"1600902-78-ミチル" = "忍術研究部の目標は「忍者をより多くの人に知ってもらうこと」！あとゆくゆくは、正式な部活として認めてもらうこと！"
"1600902-79-ミチル" = "それに関係することなら、何でもOK！先生殿だったら、きっと画期的なアイディアを出してくれるだろうし！"
"1600902-80" = "[s] \"じゃあ、例えば……\""
"1600902-81-ミチル" = "おぉっ……！？"
"1600902-82" = "[s11] \"どの作品に登場する忍者が一番強いのか？とか。\"\n[s12] \"どの作品に登場する忍者が一番素早いのか？とか。\"\n[s13] \"どの作品に登場する忍者が一番カッコよいか？とか。\""
"1600902-83-ミチル" = "なっ……！？"
"1600902-84-ミチル" = "なっ……！？"
"1600902-85-ミチル" = "なっ……！？"
"1600902-86" = "[s] \"ほら、忍者って色んな漫画とか映画に出てるから。\""
"1600902-87-ミチル" = "……。"
"1600902-88" = "[s] \"その中のどの忍者が一番……ってミチル？目が怖いけど……。\""
"1600902-89-ミチル" = "いやいやいやいやいや！！それは違うよ！先生殿！"
"1600902-90-ミチル" = "そもそも別作品の忍者を比較って、何を基準に比べるわけ！？"
"1600902-91-ミチル" = "そもそも数が膨大だし！小説、漫画、映画、アニメ……！"
"1600902-92-ミチル" = "あの「柴犬ワン蔵」監督の作品から、私が考えたオリジナル作品まで……！"
"1600902-93" = "[s] \"オリジナル作品、気になる……。\""
"1600902-94-ミチル" = "それぞれの作品には固有の世界観、各々の趣があるわけで……"
"1600902-95-ミチル" = "それに、作品ごとの世界観とかパワーバランスだってある！それを「強さ」とか「速さ」とかで分けようなんて、そもそも無理！！"
"1600902-96-ミチル" = "そこに「違い」こそあれど、それは優劣じゃないんだから！そもそも忍者っていうのは、色んな媒体において常に時代と共に進化し続けているものであって……！"
"1600902-97-ミチル" = "くっ、これがオタクと一般人の差異……！"
"1600902-98" = "[s] \"何かごめん！？\""
"1600902-99-ミチル" = "くっ、これは一から説明するしかない！先生殿、そこに座って！"
"1600902-100-ミチル" = "今から忍者の凄さと歴史について、その起源から説明してあげるから！"
"1600902-101" = "[s] \"ミチル、私お昼ご飯が……。\""
"1600902-102-ミチル" = "とにかく、忍者というのはね……！"
"1600902-103" = "[s] \"う、うん……。\""
"1600902-104" = "（そうしてミチルから3時間もの間、忍者コンテンツの歴史に関する講義（要約ver）を受けることになった……）"
"1600902-105" = "（その間放置され続けたカップ麵は、笑えるほど伸びてしまった）"
