[translation]
"2002-1" = "いつもの彼女たちの放課後"
"2002-2" = "（学校からの帰り道、放課後スイーツ部の部員たちが並んで川沿いを歩いていた）"
"2002-3-ヨシミ" = "そういえばもうすぐ連休じゃん、4日間だっけ？それぞれ何か予定とかあるの？"
"2002-4-カズサ" = "特に何も。せっかく連休なんだから、何もしないのが一番良い。"
"2002-5-ヨシミ" = "ま、どうせあんたはそう言うと思ったわよ。"
"2002-6-カズサ" = "何それ、どういう意味？"
"2002-7-ヨシミ" = "べっつにー？言ったとおりの意味～。"
"2002-8-アイリ" = "え、えっと！よ、ヨシミちゃんは、何か予定とかあるの？"
"2002-9-アイリ" = "私は最近の授業で分からなかったところの勉強でもしようかな、って思ってるけど……。"
"2002-10-ヨシミ" = "んー、別にまだ何も考えてないわね……連休であちこちイベントとかやってるだろうし、どこかスイーツ巡りにでも行こうかなってくらいで。"
"2002-11-ナツ" = "……っ！"
"2002-12-アイリ" = "……な、何？"
"2002-13-ナツ" = "……っっっ！！"
"2002-14-カズサ" = "……？"
"2002-15-アイリ" = "な、ナツちゃん？急にどうしたの……？"
"2002-16-ナツ" = "……甘いもの食べたい。"
"2002-17-ヨシミ" = "そんなに溜めてから言うようなこと！？"
"2002-18-カズサ" = "な、ナツちゃん、ついさっきスイーツ食べてきたばっかりなのに……？"
"2002-19-ナツ" = "ノンノン、それとこれとは話が別だよ。何せ私たちは成長期、および思春期真っ盛りの女子高生。糖分はいくら摂っても摂り過ぎなんてことはない。"
"2002-20-カズサ" = "また変な口調になってる……。"
"2002-21-ナツ" = "気のせい気のせい～。"
"2002-22-カズサ" = "はぁ……。"
"2002-23-ヨシミ" = "で、とにかくあんたが言ってるのは、もう一軒行きたいってこと？そういうことなら私も付き合うけど？"
"2002-24-アイリ" = "なんか「もう一軒」って言葉、女子高生っぽくないね……。"
"2002-25-ヨシミ" = "えっ、そ、そう……！？"
"2002-26-ナツ" = "むーん、それも悪くないけど……。"
"2002-27-ナツ" = "こう、"
"2002-28-ナツ" = "刺激が足りない気がする。"
"2002-29-アイリ" = "刺激……？スイーツに刺激って、どういうの……？あ、辛いのとか？"
"2002-30-ナツ" = "ううん、"
"2002-31-ナツ" = "例えばそう……"
"2002-32-ナツ" = "「伝説のスイーツを探す冒険」、みたいな！！！！"
"2002-33-カズサ" = "はいじゃあ今日はこれで解散。またね。"
"2002-34-アイリ" = "えーっと……なんか私も、もう少し甘いもの食べたくなってきちゃった。ヨシミちゃん、一緒にもう一軒、行く？"
"2002-35-ヨシミ" = "うん、そうしよっか……って、あんたも「もう一軒」って言ってるじゃん！？"
"2002-36-ナツ" = "……ちーん。"
"2002-37-ナツ" = "悲しい……せっかくワクワクするような意見を出したのに、みんなが協力してくれない……。"
"2002-38-ヨシミ" = "協力も何も、さっきの話で「行こう行こう！」ってなるとでも思った！？"
"2002-39-ナツ" = "だってこの私が事前に、調査も準備も済ませておいたんだよ？せめて話だけでも聞いてみたくない？"
"2002-40-ヨシミ" = "いや、別に……。"
"2002-41-ナツ" = "実はトリニティの自治区から結構離れたところに、とある洞窟があって……！"
"2002-42-アイリ" = "始まっちゃった……。"
"2002-43-ナツ" = "その洞窟では夏でも氷点下の気温が保たれてて、一年中「つらら」ができる環境になってるらしいんだ。"
"2002-44-ナツ" = "それで、その「つらら」っていうのが普通の「つらら」じゃなくて……"
"2002-45-ナツ" = "「天然のメープルシロップでできたつらら」なんだって！"
"2002-46-ナツ" = "洞窟にサトウカエデが生えてて、その樹液が凍って生まれるらしくって……どう、気になってきたでしょ？"
"2002-47-ナツ" = "何それ……情報源はどこ？"
"2002-48-ナツ" = "「月刊スイーツと機関銃」のミステリーコーナー。はいこれ、見る？"
"2002-49-ヨシミ" = "「ミステリーコーナー」って言っちゃってるじゃん！？見なくても分かるわよ、それミステリーなんでしょ！？ほぼ間違いなく噓じゃん！？"
"2002-50-ナツ" = "それはミステリーに失礼～。とにかく行ってみようよ、天然のメープルアイスがあるかもしれないんだよ？気になるでしょ？"
"2002-51-ヨシミ" = "行かないわよ！わざわざ連休を消費してまで、そんな嘘っぽい話を確かめに行くとでも思った！？"
"2002-52-ナツ" = "え、噓でしょ……？本当に？本当に行かないの……？"
"2002-53-ヨシミ" = "だから行かないって言ってるでしょ？私はスイーツ巡りだし、アイリはアイリで勉強するんだから。"
"2002-54-ナツ" = "……（ちらっ）。"
"2002-55-カズサ" = "さりげなくこっちを見てもダメ。"
"2002-56-カズサ" = "私にだって、「何もしない」っていうれっきとした予定がある。"
"2002-57-ヨシミ" = "そういうこと、"
"2002-58-ヨシミ" = "じゃあこの話はおしまい。"
"2002-59-ナツ" = "ただのつららじゃなくて、メープルシロップのつららなんだよ……？見たくないの？"
"2002-60-ナツ" = "こんなロマンに満ちたスイーツを、この目で見ずに終われるの……！？"
"2002-61-カズサ" = "いや別に何も終わらないし。メープルシロップならあそこのコンビニにもあるでしょ。買ってきたら？"
"2002-62-ナツ" = "そんな……"
"2002-63-ナツ" = "これで、"
"2002-64-ナツ" = "本当にこれでいいの……？"
"2002-65-ナツ" = "青春真っ盛りの女子高生たちが、イベントやら試験やらに夢中になってて、本当に良いと思ってるの……！？"
"2002-66-ヨシミ" = "いや、いたって健全な青春だと思うけど。"
"2002-67-カズサ" = "……なんかもう、ツッコまれるのを楽しんでない？"
"2002-68-ナツ" = "……そっか。みんなは本当に興味ないんだ……ごめんね、何か、私ひとりだけで……。"
"2002-69-ナツ" = "でも……ぐすっ……くすん……。"
"2002-70-カズサ" = "……。"
"2002-71-アイリ" = "あ、あの……な、ナツちゃん。私、その……"
"2002-72-ヨシミ" = "……待って！！情に流されちゃダメ！！"
"2002-73-ヨシミ" = "この展開もう何回目！？分かってるでしょ、毎回似たような流れなんだから！"
"2002-74-ヨシミ" = "ナツ、私たちだってそうやって毎回騙されると思ったら大間違いよ！"
"2002-75-ナツ" = "ぐすっ……。"
"2002-76-ナツ" = "……。"
"2002-77-ナツ" = "……ダメかぁ、残念。"
"2002-78-ヨシミ" = "あ、あははは……。"
"2002-79-ヨシミ" = "ほらそうだと思った！"
"2002-80-ヨシミ" = "とにかく今日はもう解散！じゃあね！"
"2002-81-アイリ" = "う、うん。じゃあ、またね。"
"2002-82-カズサ" = "……私も今日は帰る、バイバイ。"
"2002-83-ナツ" = "ふむ……。"
"2002-84-ナツ" = "……。"
"2002-85" = "（その日の夜）"
"2002-86-ヨシミ" = "こんな夜中に呼び出して、何の用……？"
"2002-87-カズサ" = "私も知らない。"
"2002-88-カズサ" = "寝る直前に、アイリからすごい慌てた様子の連絡が来て……。"
"2002-89-アイリ" = "ヨシミちゃん、カズサちゃん！"
"2002-90-アイリ" = "ナツちゃんが、ナツちゃんがっ……！！！"
"2002-91-ナツ" = "ぐすっ……みんなぁ……。"
"2002-92-カズサ" = "え、何？どうして泣いてるの？"
"2002-93-ヨシミ" = "っていうかナツ、今どこにいるの！？"
"2002-94-ナツ" = "お昼に話したメープルシロップの洞窟……"
"2002-95-ナツ" = "やっぱり見に行って写真でも撮ろうと思って、一人で来たんだけど……。"
"2002-96-ナツ" = "洞窟の中で、迷っちゃった……。"
"2002-97-カズサ" = "……はぁ？"
"2002-98-カズサ" = "……。"
"2002-99-アイリ" = "……。"
"2002-100-ナツ" = "助けて～……"
"2002-101-ナツ" = "暗いよう怖いよう、何も見えないよ～……。"
"2002-102-ナツ" = "ね、ねぇ……まさか友達を見捨てたりしないよね……？"
"2002-103-ナツ" = "ね……？"
"2002-104-ヨシミ" = "……。"
"2002-105-カズサ" = "……ふぅ。"
"2002-106-アイリ" = "さ、流石に行く、よね……？"
"2002-107-ヨシミ" = "……はぁ、全くもう……！"
"2002-108" = "（その後ナツを助けるために、ヨシミとカズサとアイリは洞窟へと向かった）"
"2002-109" = "（洞窟にたどり着くと、そこには本当にメープルシロップのつららがあり……）"
"2002-110" = "（ナツのことは何とか救出できたものの、そのつららを食べた放課後スイーツ部一同はみんなしてお腹を下し、せっかくの連休が台無しになってしまったのだった）"
"2002-111" = "いつもの彼女たちの放課後"
