[translation]
"10010110-1" = "第11話;イット・サーヴズ・ユー・ライト（１）"
"10010110-2-ヒナタ" = "う、うぅ……。"
"10010110-3-ヒナタ" = "ごめんなさい、先生、ウイさん。"
"10010110-4-ヒナタ" = "せっかく手伝っていただいたのに、まさかこんなことになるなんて……。"
"10010110-5" = "[s1] \"開催時間の前倒しだなんて……。\"\n[s2] \"どうして急にこんなことに……。\""
"10010110-6-ウイ" = "な、何なんですかもう……。"
"10010110-7-ウイ" = "な、何なんですかもう……。"
"10010110-8-ウイ" = "今回の式典、何もかもおかしいこと尽くしです。急な予定の変更だなんて……。"
"10010110-9-ウイ" = "ま、まだ本の復元も、終わっていないのに……。"
"10010110-10-ヒナタ" = "今このタイミングで連絡が来たのは、私は本来参加しない立場だからかと……他の出席される方には、とっくに連絡が行ってるはずです。"
"10010110-11-ヒナタ" = "それに……復元が間に合っていたとしても、もう……。"
"10010110-12-ヒナタ" = "……1時間後には式典が始まるなら、今頃もう会場には来賓の方々が着席されているはずです。"
"10010110-13-ヒナタ" = "出席者の方が全員揃えば会場は閉鎖され、周辺を警備が固めてしまいます。"
"10010110-14-ヒナタ" = "もし今ここに本があったとしても、今から現地に運ぶには時間がかかりますし……。"
"10010110-15-ヒナタ" = "到達できたとしても同じ、です。"
"10010110-16-ヒナタ" = "会場の警備は、正義実現委員会のみなさんが担当するとお聞きしました。"
"10010110-17-ヒナタ" = "定期巡回の時期ですから、全員ではないにせよ……。"
"10010110-18-ヒナタ" = "私みたいな普通のシスターが、そこでこっそり本を入れ替えるなんて……そんなことは……。"
"10010110-19-ヒナタ" = "うぅ、ごめんなさいサクラコ様……このままでは、みなさんの前で……。"
"10010110-20" = "[s3] \"カーマスートラを……。\"\n[s4] \"ど、どうにか、他の手段を……。\""
"10010110-21-ヒナタ" = "うっ、うぅ……！"
"10010110-22-ヒナタ" = "ごめんなさい、私が……私のせいで……。"
"10010110-23-ヒナタ" = "サクラコ様はもちろん、みなさまにとんでもないご迷惑を……。"
"10010110-24-ヒナタ" = "全ては、私が……。"
"10010110-25-ウイ" = "ヒナタさん……。"
"10010110-26-ヒナタ" = "……。"
"10010110-27" = "[ns5] \"……ヒナタ？\"\n[ns6] \"もしかして……。\""
"10010110-28-ヒナタ" = "と、とにかく最悪の事態は避けないといけません……。"
"10010110-29-ヒナタ" = "と、とにかく最悪の事態は避けないといけません……。"
"10010110-30-ヒナタ" = "会場へ行けば、なにかはできるはずです。警備をどうにかすり抜けて……中に入ってサクラコ様を止めて……。"
"10010110-31-ヒナタ" = "せめて本当のことを、私の口から……。"
"10010110-32-ヒナタ" = "……先生。今日一日、本当にありがとうございました。"
"10010110-33-ヒナタ" = "こんな結果になってしまいましたが……先生に助けていただいて、すごく嬉しかったです。"
"10010110-34-ヒナタ" = "疲れたのは本当ですが、同時に楽しくもありました。"
"10010110-35-ヒナタ" = "……本当に、ありがとうございました。"
"10010110-36-ヒナタ" = "ウイさんも、ありがとうございます。その本の復元――"
"10010110-37-ヒナタ" = "……いえ。"
"10010110-38-ヒナタ" = "……「その子の治療」を、してくださって。"
"10010110-39-ウイ" = "……え。"
"10010110-40-ヒナタ" = "よろしければ、最後までお願いいたします。式典に関係なく、大切な子に変わりはないので。"
"10010110-41-ウイ" = "……あの。"
"10010110-42-ウイ" = "ちょっ、ちょっと待ってくださいヒナタさん。今、何と……"
"10010110-43-ヒナタ" = "すみません、急ぎますね。"
"10010110-44-ヒナタ" = "お先に、失礼します。"
"10010110-45" = "[s7] \"ヒナタ、待って。\"\n[s8] \"私にも責任はあるから、一緒に……。\""
"10010110-46-ヒナタ" = "……いえ。"
"10010110-47-ヒナタ" = "……いえ。"
"10010110-48-ヒナタ" = "先生は手伝ってくださいましたが、これはやはり私の責任です。"
"10010110-49-ヒナタ" = "最後はどうか、私にやらせてください。"
"10010110-50-ヒナタ" = "お願いします。"
"10010110-51" = "[ns] \"……。\""
