[translation]
"10010130-1" = "第13話;イット・サーヴズ・ユー・ライト（３）"
"10010130-2-正義実現委員会部員A" = "「七転八倒団」、戦力はそれほどでも……いえ、相当弱いです！"
"10010130-3-正義実現委員会部員A" = "なら、どうしてこんな時間がかかっているのですか！"
"10010130-4-正義実現委員会部員B" = "わ、分かりません、敵が多いわけではないのですが……。"
"10010130-5-正義実現委員会部員B" = "良く見えませんが、多分裏側で治療がされてるような……ですがこの復帰スピード、普通こんなに多くの衛生兵がいるはずが……！？"
"10010130-6-マシロ" = "みなさん、目標に惑わされないでください！あまり離れてはいけません！"
"10010130-7-マシロ" = "私たちの目的はあくまで、ここ一帯の警護です！誘い出されないように！"
"10010130-8-正義実現委員たち" = "はいっ！！"
"10010130-9-ヒナタ" = "これは、一体……？"
"10010130-10-ヒナタ" = "どうしてあの方々が、ここを攻撃して……！？？"
"10010130-11-ヒナタ" = "……？この音は、車の……いえ、トラック……？"
"10010130-12-スイーツ屋の店主" = "さあ、そこのみなさん！何だか騒がしい中ですが、少々お耳をこちらへ！"
"10010130-13-スイーツ屋の店主" = "あ、あなたは……！"
"10010130-14-ヒナタ" = "こんな時だからこそ、落ち着くためにもケーキはいかがでしょうか！"
"10010130-15-スイーツ屋の店主" = "ただのケーキではありません、あの限定商品「ミラクル5000」です！今日だけは何と、無料でお配りしてしまいます！"
"10010130-16-スイーツ屋の店主" = "今ここにいるみなさんが全員食べたとしても、十分余るはずの量です。さあ、いかがですか！？"
"10010130-17-ヨシミ" = "ど、どうかご遠慮なさらずー！もしかすると明日からはまた、限定商品になってしまうかもしれませんのでー！"
"10010130-18-ヨシミ" = "もちろん、すっごく美味しいですよー！"
"10010130-19-ヒナタ" = "ほ、放課後スイーツ部のみなさんまで……！？"
"10010130-20-カズサ" = "……これ、本当に行けるのかな。ここにいるのって、結構偉い人たちなんでしょ？"
"10010130-21-カズサ" = "いくら限定の「ミラクル5000」だからって、私たちみたいに――"
"10010130-22-参列者A" = "く、ください！ずっと食べたかったんです！"
"10010130-23-参列者B" = "えぇい、どきなさい！私が先です！普段であれば、お金を積んでも中々食べられないあの「ミラクル5000」……！"
"10010130-24-参列者A" = "ちょっと、割り込みしないでください！マナーを守って！"
"10010130-25-参列者B" = "「ミラクル5000」とマナーと、どっちが大事なんですか！？"
"10010130-26-アイリ" = "めっちゃ食いついてるじゃん。"
"10010130-27-ヨシミ" = "ほら、さっさと手伝うわよ。"
"10010130-28-カズサ" = "……。"
"10010130-29-ナツ" = "結局誰も彼も同じ……でもそれは決して、悪いことじゃない。"
"10010130-30-ナツ" = "美味しい食べ物を食べる、それは人生そのものと言っても過言じゃない。そして何より、後悔は先に立たず！"
"10010130-31-ナツ" = "ちょっとナツ、さりげなく逃げようとしないで。"
"10010130-32-ナツ" = "ああもう、良いから早く来なさいよ！お客さん来てるんだから！！"
"10010130-33-ナツ" = "はーい……。"
"10010130-34-サクラコ" = "なっ、何なんですかこの状況は……！"
"10010130-35-サクラコ" = "み、「ミラクル5000」……私だって、一度も食べたことないというのに……！"
"10010130-36-サクラコ" = "で、ですが私には、私の役割が……。"
"10010130-37" = "（……）"
"10010130-38" = "[s1] \"せっかくだし、行ってきたら？\"\n[s2] \"何かあったら、私がどうにかするから。\""
"10010130-39-サクラコ" = "こ、この声……？"
"10010130-40-サクラコ" = "こ、この声……？"
"10010130-41-サクラコ" = "……！"
"10010130-42-サクラコ" = "せ、先生！？"
"10010130-43-正義実現委員会部員A" = "報告します！「七転八倒団」、総員の退却を確認しました！こちら側の被害は軽微！"
"10010130-44-正義実現委員会部員B" = "今からでしたら、追撃できそうですが……どうしますか？"
"10010130-45-マシロ" = "いえ、やめておきましょう。繰り返しになりますが、私たちの今日の任務は「会場の警備」です。"
"10010130-46-マシロ" = "会場側からも、特に通信連絡などは無いようですし……。"
"10010130-47-マシロ" = "防衛成功です、詳しい調査はまた後にしましょう。"
"10010130-48-マシロ" = "それでは総員、元の位置へ。"
"10010130-49-正義実現委員会部員B" = "はいっ！！"
"10010130-50-ヒナタ" = "い、いなくなっちゃいました……。"
"10010130-51-ヒナタ" = "さっきまでの銃撃戦が嘘みたいに……あれは一体……？"
"10010130-52-ヒナタ" = "……？"
"10010130-53-ヒナタ" = "……あれ？"
"10010130-54-ヒナタ" = "せ、先生……？"
"10010130-55-ヒナタ" = "ど、どうして先生がここに……！？古書館にいらっしゃったのでは……？"
"10010130-56-ヒナタ" = "……はい？"
"10010130-57-ヒナタ" = "想像以上に重かった……？"
"10010130-58" = "[s3] \"……これ、お願いしても良い？\"\n[s4] 手に持っていたものをヒナタに渡す。"
"10010130-59-ヒナタ" = "……あ、はい。"
"10010130-60-ヒナタ" = "……あ、はい。"
"10010130-61-ヒナタ" = "それはもちろんですが、えっと……。"
"10010130-62-ヒナタ" = "あれ、これは……？"
"10010130-63-ヒナタ" = "カーマ、スートラ……？"
"10010130-64-ヒナタ" = "どうしてこれが、先生の手に……？"
"10010130-65-ヒナタ" = "経典の入れ物に、入っていたはず……。"
"10010130-66-ヒナタ" = "……？？？？"
"10010130-67-サクラコ" = "みなさんお静かに！何だか変なことになってしまいましたが、式典を再開します。"
"10010130-68-サクラコ" = "重要な席なのですから、お口周りのケーキは拭いてください！"
"10010130-69-サクラコ" = "ふぅ……では、あらためまして。"
"10010130-70-ヒナタ" = "えっと、つまり……。"
"10010130-71" = "[s] \"うん。\""
"10010130-72-ヒナタ" = "せ、先生……。"
"10010130-73" = "[s] \"……間に合って良かった。\""
"10010130-74-ヒナタ" = "……！！！！"
"10010130-75-サクラコ" = "公開します、こちらが――"
"10010130-76-サクラコ" = "公会議を通じて解釈された、古代の経典……その第4次注釈が入った物です！"
