[translation]
"10010030-1" = "第3話;スラムの要塞へ（１）"
"10010030-2" = "（まず限定ケーキの「ミラクル5000」を手に入れるため、ソルート川へと向かった）"
"10010030-3" = "（川沿いに到着すると、何だか不自然にざわついており……）"
"10010030-4-トリニティの生徒B" = "え、ではこの状態のまま……？"
"10010030-5-トリニティの生徒B" = "うん。正義実現委員会が解決してくれるまで、ただ待つしか……。"
"10010030-6-トリニティの生徒A" = "来てくれる、かな？ここ、ほとんどトリニティの外だし……。"
"10010030-7-トリニティの生徒B" = "それもそうかも……ああもう、ここ最近毎日来てるのに！"
"10010030-8" = "[s] \"……？\""
"10010030-9-ヒナタ" = "えっと……これは、どういう状況なのでしょうか？なんだかみなさん、暗い顔をされて……。"
"10010030-10-？？？" = "……あれ、先生？"
"10010030-11-？？？" = "どうして先生がここにいるの？"
"10010030-12-ヒナタ" = "あら、先生のお知り合いの方ですか……？"
"10010030-13-カズサ" = "久しぶり。隣にいるのは……誰？"
"10010030-14-カズサ" = "見ればわかるでしょ、シスターさんだよ。"
"10010030-15-ヨシミ" = "いや、そういう意味じゃなくて……っていうか、もしかしてバカにしてる？"
"10010030-16-カズサ" = "……。"
"10010030-17-ヨシミ" = "……どうしてそこで黙るのよ。"
"10010030-18-カズサ" = "あらためて考えたけど、やっぱその可能性あるなって。"
"10010030-19-ヨシミ" = "やっぱりバカにしてるじゃんバーカ！！"
"10010030-20-ヨシミ" = "えっと、お話の途中にすみません。こんにちは、シスターフッドのヒナタと申します。"
"10010030-21-ヨシミ" = "実はここに、「ミラクル5000」というケーキを買いに来たのですが……。"
"10010030-22-アイリ" = "あ、シスターさんもそうなんですね。実は私たちも同じ目的でして！"
"10010030-23-アイリ" = "ただその、残念なことに買えなかったのですが……。"
"10010030-24-アイリ" = "そ、そうなのですか？もしかして売り切れで……？"
"10010030-25-アイリ" = "いえ、そうではなかったのですが、えっと……"
"10010030-26-ナツ" = "資本主義の歪みに魅入られちゃったの。"
"10010030-27-ナツ" = "……ミラクル5000も。そして、私たちも。"
"10010030-28" = "[s1] \"資本主義の歪み……？\"\n[s2] 事情を聞いてみる。"
"10010030-29-ナツ" = "まあ実際のところ、そこまで複雑な話じゃないよ。"
"10010030-30-ナツ" = "まあ実際のところ、そこまで複雑な話じゃないよ。"
"10010030-31-ナツ" = "数に限りがある、限定の貴重なケーキ。みんながそれを欲しがれば、自然とその価値は上がる。"
"10010030-32-ナツ" = "それが積み上げられていくと、どこかでケーキそのものじゃなく、「ケーキの価値」の方が目につきやすくなって……。"
"10010030-33-ナツ" = "そのラインが分からなくなったり、そのダメージを被ったりすることがある。"
"10010030-34-ヒナタ" = "え、っと……？"
"10010030-35-カズサ" = "すみません、こういう話し方をするやつなんです。"
"10010030-36-カズサ" = "つまりは「ミラクル5000」を転売して利益を出そうとしたどこかの輩が、全部のケーキを買い占めた……そういうお話ですね。"
"10010030-37-カズサ" = "しかもこれ以上ケーキが増産されないように、トラックごとケーキ屋の店主さんまで攫われちゃって。その方が利益、増すんでしょうね。"
"10010030-38-カズサ" = "どうしても今すぐ手に入れようとすると、スラム街に行って法外な値段を払わないとっていう状況。"
"10010030-39-ヒナタ" = "どうしてそんなことを……食べ物は普通、みんなで分け合って美味しくいただくべきもののはず……。"
"10010030-40-ヒナタ" = "ま、そもそも限定版なんだし「みんなで」は難しそうだけど。"
"10010030-41-ヨシミ" = "それはさておき、転売のためにこんなことをするなんて許せない！"
"10010030-42-ヨシミ" = "こんなのスイーツに対する侮辱よ！！"
"10010030-43-アイリ" = "それでこの先どうしようかと、「ミラクル5000を愛する会」のみんなで集まって悩んでいたんです。"
"10010030-44" = "[s3] \"たしかに転売は許されない……。\"\n[s4] \"すごい、かなりの人数が集まってるね。\""
"10010030-45-ナツ" = "集まってはみたものの、それだけで解決できるわけでもなくってねー。"
"10010030-46-ナツ" = "話し合いは通じなかったし、どうしたもんだか……。"
"10010030-47-ヨシミ" = "トラックごと攫った挙句、それを建物の中に格納して周囲一帯を封鎖とかよくやるわ。"
"10010030-48-ヨシミ" = "もう要塞みたいになってるし、あんなの正義実現委員会みたいな「ちゃんとした戦闘集団」じゃないと無理でしょ。"
"10010030-49-ナツ" = "……？"
"10010030-50-ナツ" = "……なるほど？"
"10010030-51-ナツ" = "解決できるかも。"
"10010030-52-ナツ" = "え？"
"10010030-53-ヨシミ" = "それ、どういうことよ？"
"10010030-54-ヨシミ" = "備えあれば患いなし……準備ならもう揃ってる。"
"10010030-55-ナツ" = "「ちゃんとした戦闘集団」。少なくとも、それに近しい形にはなれるでしょ。"
"10010030-56-カズサ" = "……？"
"10010030-57-アイリ" = "えっと、ナツちゃん？"
"10010030-58-ヨシミ" = "アイリ、「ちゃんとした戦闘集団」に必要な条件って何だと思う？"
"10010030-59-ヨシミ" = "まーたクイズ始まった……。"
"10010030-60-アイリ" = "えっと……銃器、戦闘人員、あとそれぞれの役割と……。"
"10010030-61-カズサ" = "……なるほどね。"
"10010030-62-カズサ" = "アイリが挙げたのもその通りだけど、あと必要なのは「指揮官」。"
"10010030-63-ヨシミ" = "指揮官……？"
"10010030-64-ヨシミ" = "……あ。"
"10010030-65" = "[s5] \"それってつまり……。\"\n[s6] \"……私？\""
"10010030-66-ナツ" = "にひ……お察しの通りだよ、「コマンダー」。"
"10010030-67-ナツ" = "にひ……お察しの通りだよ、「コマンダー」。"
"10010030-68-ナツ" = "さあ。私たちを導き、奇跡を解放してくれたまえ。遍く地域に甘い恩恵を届けるために……"
"10010030-69-ナツ" = "……ってね？"
"10010030-70" = "[s7] \"困ってるみたいだし、もちろん私は良いけど……。\"\n[s8] \"ヒナタもそれで良い？\""
"10010030-71-ヒナタ" = "は、はい、もちろんです！"
"10010030-72-ヒナタ" = "もちろん私たちとしてもあのケーキが必要なのですが……それ以前に、困っている方々を見て見ぬふりはできません。"
"10010030-73-ヒナタ" = "ですので、むしろお手伝いさせてください！"
"10010030-74-ヨシミ" = "うんっ、了解！そういうことなら話は早いわ！"
"10010030-75-ヨシミ" = "さあ、全面抗争よ！こうなったら正面突破で！"
"10010030-76-ヨシミ" = "今すぐ出発！"
"10010030-77-ナツ" = "私たちは、転売の奴隷にはならない！！スイーツの主になるんだ！"
"10010030-78-カズサ" = "何かどっかで聞いた台詞……。"
"10010030-79-ナツ" = "進もう、ただひたすらに前へ！！"
"10010030-80-ヒナタ" = "えっと、えっと……。"
"10010030-81-ヒナタ" = "わ、わああぁぁぁっ……！？"
"10010030-82-ヘルメット団A" = "いやー、ぼろい商売だな。もっと早く思いついてれば良かった。"
"10010030-83-ヘルメット団A" = "まさか本当にあんな値段で買うやつらがいるとはね……今日も結構な売り上げじゃん。"
"10010030-84-ヘルメット団B" = "ははっ、ありがたいこったな。"
"10010030-85-ヘルメット団B" = "トリニティの生徒が多かった気がするな。金払いが良くって助かる。"
"10010030-86-ヘルメット団A" = "このまま行けばうちら、お金持ち一直線じゃん！"
"10010030-87-ヘルメット団B" = "ん？誰か来る……？"
"10010030-88-ヘルメット団A" = "……。"
"10010030-89-ヘルメット団B" = "何だ？お前も「ミラクル5000」を買いに来た口か？"
"10010030-90-ヘルメット団B" = "ここまで来たってことは、状況は分かってるんだろ？で、いくら出す？"
"10010030-91-ナツ" = "いくら、かぁ……。"
"10010030-92-ヘルメット団B" = "ああ、変に交渉なんか考えない方が良いぜ？こっちの機嫌を損ねたら、後からいくら積んだって買えないことも――"
"10010030-93-ヘルメット団B" = "……？"
"10010030-94-ナツ" = "……じゃあお支払いは、これで。"
"10010030-95-ヘルメット団B" = "ぐはっ……！？"
"10010030-96-ヘルメット団A" = "な、なんだと！やる気か！？"
"10010030-97-ヘルメット団A" = "ひとりで勝てるとでも！？"
"10010030-98-ナツ" = "……私はひとりじゃない。"
"10010030-99-ナツ" = "スイーツを愛する全ての同士たちよ、今こそ立ち上がる時！"
