[translation]
"2005003-1" = "こっちのほうが早いよ！"
"2005003-2" = "シャーレ・オフィス"
"2005003-3" = "（いつものように、仕事と格闘していたある日……）"
"2005003-4" = "（誰か来た……？）"
"2005003-5" = "[ns] \"開いてますよ～\""
"2005003-6" = "[ns1] \"あれ、この音……。\"\n[ns2] \"ドアからじゃない……？\""
"2005003-7" = "（窓のほうに視線を向けると……）"
"2005003-8" = "[ns] \"……んん？\""
"2005003-9" = "（リツが、窓の外にぶら下がっていた）"
"2005003-10" = "[ns] \"リツ！？\""
"2005003-11-リツ" = "先生先生！"
"2005003-12-リツ" = "ここ閉まってる！割って入ってもいい？"
"2005003-13" = "[s3] \"それ、防弾ガラスだから！\"\n[s4] \"待って！今開ける！\""
"2005003-14" = "（急いで窓を開け、リツを中に入れた）"
"2005003-15-リツ" = "じゃじゃーん！"
"2005003-16" = "[ns] \"もしかして……壁を登ってきたの……？\""
"2005003-17-リツ" = "うん！#nエレベーター来るの遅くてさ！"
"2005003-18" = "[s] \"一応、階段もあるんだけど……。\""
"2005003-19-リツ" = "うーん……？"
"2005003-20-リツ" = "でも、壁を登ったほうが近くない？"
"2005003-21" = "[s] \"そ、そうかもしれないけど……！\""
"2005003-22" = "[ns] \"あれ、今日は当番じゃないよね？外出許可取ってきたの？\""
"2005003-23-リツ" = "そそ！#n彫刻に使う大理石がなくて……って言ったらいけたんだ！"
"2005003-24-リツ" = "ワイルドハントって、外出にすっごく厳しいけど……。"
"2005003-25-リツ" = "芸術のことになると、#nちょっとだけオッケーをもらいやすいんだ！"
"2005003-26-リツ" = "それで、大理石を買った帰りに、シャーレに寄ったの！"
"2005003-27" = "[s] \"大理石って持ち帰れるんだ……。\""
"2005003-28-リツ" = "うん！#n1階に置いといたよ。先生も見たい？持ってくる？"
"2005003-29" = "[s] \"あ、あとで見に行くよ……！\""
"2005003-30-リツ" = "あ！そうだそうだ！"
"2005003-31-リツ" = "はい先生！これ！"
"2005003-32" = "[ns] \"……シャツ？\""
"2005003-33-リツ" = "こないだの彫刻のとき、先生粉だらけになっちゃったでしょ？"
"2005003-34-リツ" = "そのせいで服も汚れちゃってたからさ……。"
"2005003-35-リツ" = "衣装デザイン専攻の友達に、作ってもらったんだ！"
"2005003-36" = "[s] \"ああ、それで好きな色の話を！\""
"2005003-37-リツ" = "そそ！最初は先生の好きな色にしようかなーって#n思ったんだけど……。"
"2005003-38-リツ" = "専門家におまかせもアリかなって！"
"2005003-39" = "[s] \"透明とか言わなくてよかった……。\""
"2005003-40-リツ" = "あ、スケスケがよかったの？"
"2005003-41" = "[s5] \"いやいや！\"\n[s6] \"とにかくありがとう、リツ！\""
"2005003-42-リツ" = "どういたしまして！ねね、いま着てみてよ！"
"2005003-43" = "[s] \"わかった！じゃあ隣の部屋で着替えてく……。\""
"2005003-44" = "[ns] \"……えっと、どうしたのリツ？\""
"2005003-45-リツ" = "うん？何が～？"
"2005003-46" = "[s] \"ついて来られると……脱げないのですが……。\""
"2005003-47-リツ" = "……。"
"2005003-48-リツ" = "あ、もしかして恥ずかしい？"
"2005003-49-リツ" = "じゃ、ボクも作業服に着替えるよ！#n一緒に脱げば――"
"2005003-50" = "[s] \"やめてください！\""
"2005003-51" = "（その後、なんとか着替え終わって……）"
"2005003-52-リツ" = "おお～"
"2005003-53-リツ" = "どうかな？いい感じ？#n気に入ってくれた？"
"2005003-54" = "[s] \"ピッタリだよ！さすがワイルドハント……！\""
"2005003-55-リツ" = "うーん……。"
"2005003-56-リツ" = "ちょっとイマイチかも！"
"2005003-57" = "[s] \"そ、そんな……！\""
"2005003-58-リツ" = "あ、先生にはよく似合ってるよ？"
"2005003-59-リツ" = "ただ、今着てる服だと、ちょっとバランス悪いかも！"
"2005003-60" = "[s] \"あ、ああ、そういうことね……！\""
"2005003-61-リツ" = "まあ大丈夫大丈夫！"
"2005003-62-リツ" = "今度一緒に、似合うやつ買いにいこ！"
