[translation]
"2004703-1" = "離さないで"
"2004703-2" = "（海辺にやってきた。本日は晴天なり）"
"2004703-3" = "[ns] \"あの、キキョウ？\""
"2004703-4" = "[ns] \"怒ってる……？\""
"2004703-5-キキョウ" = "え……？"
"2004703-6-キキョウ" = "私が？どうして？"
"2004703-7-キキョウ" = "鼻をくすぐる潮風に、心地いい波の音、輝く海原――"
"2004703-8-キキョウ" = "海に浮かぶ先生。"
"2004703-9-キキョウ" = "この状況で、何に怒るっていうの？"
"2004703-10" = "[s] \"それなら、見てないでこっちにおいでよ。\""
"2004703-11-キキョウ" = "そ、それは……。"
"2004703-12-キキョウ" = "準備運動をしっかりしたくて。"
"2004703-13-キキョウ" = "……それだけ。"
"2004703-14" = "[s] \"パラソルの下で本を読むのが……？\""
"2004703-15-キキョウ" = "知識をつけておくのも立派な準備運動だよ。"
"2004703-16-キキョウ" = "これは水泳の基礎から応用まで、すべてのテクニックが詰まってる教本なの。"
"2004703-17-キキョウ" = "夏休みに読むべき100冊にも選ばれてる。"
"2004703-18-キキョウ" = "これさえあれば、どんな状況でも溺れることはない。"
"2004703-19" = "[s] \"案ずるより産むが易しって言うよね？\""
"2004703-20-キキョウ" = "石橋を叩いて渡るとも言うでしょ？"
"2004703-21-キキョウ" = "私は百花繚乱の作戦参謀だもの。#n想定できるリスクなら、対策するべきでしょう？"
"2004703-22" = "[s] \"今日の海は穏やかだって予報で言ってたよ。\""
"2004703-23-キキョウ" = "……急に海からダイオウイカが現れたらどうするの？"
"2004703-24-キキョウ" = "最近よく出没するらしいし。"
"2004703-25-キキョウ" = "今日だってその可能性は……。"
"2004703-26" = "[s] \"大丈夫だよ！きっと！\""
"2004703-27-キキョウ" = "大丈夫？何を根拠に……。"
"2004703-28-キキョウ" = "はぁ……あんた、そんなに私と泳ぎたいの？"
"2004703-29-キキョウ" = "……そ、そんなに頷かなくても、分かったから。"
"2004703-30-キキョウ" = "（大丈夫……教本は頭に入ってる……）"
"2004703-31-キキョウ" = "でも、入るのは腰の高さまで。"
"2004703-32-キキョウ" = "何かあってもすぐに戻れる距離を保つ。いい？"
"2004703-33-キキョウ" = "……。"
"2004703-34-キキョウ" = "……ねぇ、何か変なこと考えなかった？"
"2004703-35-キキョウ" = "水が苦手なわけじゃないからね？"
"2004703-36" = "[s3] \"変なことって例えば……？\"\n[s4] \"猫みたいでかわいい！\""
"2004703-37-キキョウ" = "……！！"
"2004703-38-キキョウ" = "い、いきなり何言ってるの！？"
"2004703-39-キキョウ" = "まったく、あんたって人は。"
"2004703-40-キキョウ" = "じゃあ――"
"2004703-41-キキョウ" = "――エスコートして。"
"2004703-42-キキョウ" = "猫は慣れない環境が苦手なんだから。"
"2004703-43-キキョウ" = "あんたがちゃんとリードするの。わかった？"
"2004703-44" = "[s5] \"じゃあ、猫用のハーネスをつけてもいい？\"\n[s6] \"離れないためにもね！\""
"2004703-45-キキョウ" = "そんなもの用意してるわけないでしょ……。"
"2004703-46" = "[s] \"あやとりの糸が代わりにならないかな？\""
"2004703-47-キキョウ" = "……ふふ、からかうのもいいけど、ちゃんと想像したほうがいいよ。"
"2004703-48-キキョウ" = "あんたにできると思うの？"
"2004703-49-キキョウ" = "糸を巻き付けられるのを、私もただ黙ってみてるわけじゃないんだけど。"
"2004703-50" = "[s] \"じゃあ、手をつなぐことで妥協しよう！\""
"2004703-51-キキョウ" = "……なるほどね。"
"2004703-52-キキョウ" = "最初に大きな要求をして、その後に小さな「本当の」要求を通す……。#nまあ、交渉としては及第点かな。"
"2004703-53-キキョウ" = "……いいよ。#nでもその代わり、絶対に離さないで。"
"2004703-54" = "冷たくて気持ちいい……。#n波は少し怖いけど……。"
"2004703-55" = "一人だったら、こんなところまで来られな――"
"2004703-56" = "……ちょっと、どこまで行くつもり？"
"2004703-57" = "私、腰下の深さまでって言ったよね。"
"2004703-58" = "……亀？#n近くにいるの？"
"2004703-59" = "それは……惹かれないことも――"
"2004703-60" = "いや、だから……はぁ。#n気になるなら、あんた一人で見てくれば？"
"2004703-61" = "……えっ。"
"2004703-62" = "待って、手を離さない約束でしょう？"
"2004703-63" = "ちゃんと握ってて。"
"2004703-64" = "え？ちょっと、なにを……。"
"2004703-65" = "きゃっ……！"
"2004703-66" = "（キキョウをお姫様抱っこして、一緒に亀を見に行った）"
"2004703-67" = "（その後も、日が暮れるまでキキョウと二人で海を楽しんだ）"
