[translation]
"62060-1" = "第6話;迷子の子ども"
"62060-2-アツコ" = "みんな、お疲れ様。"
"62060-3-ヒヨリ" = "と、とんでもない一日でしたね……。"
"62060-4-サオリ" = "ああ、たしかに。"
"62060-5-サオリ" = "だが……あの状況下で三人ともよく動いてくれた。"
"62060-6-ミサキ" = "逃亡生活には慣れてるからね。#n急に襲われることだってあったし。"
"62060-7" = "[s] \"みんな、強くなったんだね……。\""
"62060-8-ミサキ" = "別に、なりたくてなったわけじゃないんだけど。"
"62060-9-ミサキ" = "……なに？環境に背中を押されて強くなるもの……？"
"62060-10-ミサキ" = "はぁ……。#nほんと、それっぽく正論言うのやめてくれない？"
"62060-11-ヒヨリ" = "で、でも……私たちって……。"
"62060-12-ヒヨリ" = "……。"
"62060-13-ヒヨリ" = "この先も……ずっと、逃げながら生きていくんでしょうか……？"
"62060-14-サオリ" = "ヒヨリ……？"
"62060-15-ヒヨリ" = "い、いえっ！私、今の生活も好きですから！えへへ……。"
"62060-16-ヒヨリ" = "でも、やっぱり……。"
"62060-17-ヒヨリ" = "なんだか……。"
"62060-18-ヒヨリ" = "久しぶりに帰ってきたからか、変なことばっか考えちゃって……。"
"62060-19" = "[s1] \"……ごめんね。そんな思いをさせてしまって。\"\n[s2] \"アリウス分校のことは全部……。\"\n[s3] \"私の職務放棄のせいだから……。\""
"62060-20-ヒヨリ" = "えっ？そ、それってどういう……？"
"62060-21-サオリ" = "先生……？"
"62060-22-ミサキ" = "……。"
"62060-23-アツコ" = "ねえ、先生。なんでもかんでも、自分一人で背負い込もうとしないで。"
"62060-24-アツコ" = "これは私たちが、自分で選んだ道なんだから。"
"62060-25-アツコ" = "だから、もし……他の選択肢があるかもしれないって思うなら……。"
"62060-26-アツコ" = "その時は、みんなで考えよう。"
"62060-27-アツコ" = "今は、ミネさんからのお願いについて話さない？"
"62060-28" = "[s] \"「日常」のことだね。\""
"62060-29-アツコ" = "うん。アリウスの日常。"
"62060-30-ミサキ" = "たぶん……あの人が思ってるものとは、かけ離れてるんだけどね。"
"62060-31-ヒヨリ" = "い、今のアリウスの子たちにとっては……初めての経験ばっかりだと思うんです……。"
"62060-32-ヒヨリ" = "授業も……勉強も……校外学習も……。#n水を濾過できる道具とか、新しい医薬品だって……。"
"62060-33-サオリ" = "保温効果のある布団もあったな。前は破れたテントを使ってたのに。"
"62060-34-サオリ" = "あとは……栄養改善用の救援食も、ここじゃ見たことがなかった。"
"62060-35-サオリ" = "……改めて実感する。#n誰かにとっての「日常」が、別の誰かにとっては「奇跡」なのだと。"
"62060-36-アツコ" = "でも、ミネさんはそれを守ってほしいって言ってたよね？"
"62060-37-アツコ" = "「当たり前」を守ってほしい、って……。"
"62060-38-ミサキ" = "言うほど簡単じゃないでしょ、それ。"
"62060-39" = "[s4] \"そうだね。\"\n[s5] \"だからこそ、私が頑張らなきゃいけない。\""
"62060-40-ヒヨリ" = "でも……やっぱり勉強はイヤです……。"
"62060-41" = "[s] \"生徒の本分を忘れちゃダメだよ？\""
"62060-42-ヒヨリ" = "い、今のすごく「先生」っぽかったです……！"
"62060-43-ヒヨリ" = "あ、そっか……先生は元から先生でした……。"
"62060-44" = "[s6] \"ふふっ。思い出させてあげよう。\"\n[s7] \"私が「先生」だということをね。\""
"62060-45-ミサキ" = "何するつもり……？"
"62060-46" = "[s8] \"明日も、授業をやるよ。\"\n[s9] \"みんなにモモトークでお知らせしておかないと。\""
"62060-47-ミサキ" = "いい性格してるよね、先生。"
"62060-48-ミサキ" = "……何？嫌なことを繰り返し乗り越えることで、人は強くなるって？"
"62060-49-ミサキ" = "はぁ……その言葉、アリウスでもよく言われてたよ。#nもっと違う言い方をしてたけど。"
"62060-50-サオリ" = "たしかに、そうだったな……。"
"62060-51-サオリ" = "だが、アリウス式の訓練に比べれば、先生の授業の方がずっとマシだと思う。"
"62060-52-サオリ" = "私はそうだが……お前は違うのか？"
"62060-53-ミサキ" = "……そんなこと、言った覚えないんだけど。"
"62060-54-アツコ" = "ふふっ。"
"62060-55-ヒヨリ" = "えへへ……。"
"62060-56-ミサキ" = "……ねぇ、なんで私ばっかり？"
"62060-57-アリウスの生徒C" = "モモトーク……先生から？"
"62060-58-アリウスの生徒C" = "「今日は本当にお疲れ様でした」"
"62060-59-アリウスの生徒C" = "「色々なことがありましたが、変わらず明日も授業を行います」"
"62060-60-アリウスの生徒C" = "「皆さん、奮ってご参加ください」"
"62060-61-アリウスの生徒C" = "……何これ、ふざけてるの？"
"62060-62-アリウスの生徒D" = "今がどんな状況か分かってないのかな……。"
"62060-63-アリウスの生徒D" = "先輩が戻ってきたら伝えなきゃ……。"
"62060-64-アリウスの生徒C" = "あっ、先輩！さっき先生からモモトークが来て……！"
"62060-65-アリウスの生徒D" = "それで、その内容がですね――"
"62060-66-スバル" = "知ってますよ。"
"62060-67-アリウスの生徒D" = "えっ、はい？"
"62060-68-アリウスの生徒D" = "そ、そうですか……それなら、よかったです……。"
"62060-69-スバル" = "とはいえメッセージは消してしまったので、もう読めませんが。"
"62060-70-アリウスの生徒B" = "はい……？"
"62060-71-アリウスの生徒B" = "け、消しちゃったんですか……？"
"62060-72-スバル" = "何か問題でも？"
"62060-73-アリウスの生徒A" = "い、いえっ！何でもないです！"
"62060-74-スバル" = "それでは。"
"62060-75-スバル" = "もういい時間ですから、そろそろ休みましょう。"
"62060-76-アリウスの生徒D" = "……寝る、んですか？"
"62060-77-アリウスの生徒D" = "たしかに寝る時間だけど……。"
"62060-78-アリウスの生徒C" = "こんな風に何も知らないふりしてモモトーク送ってくる先生とか……。"
"62060-79-アリウスの生徒C" = "あと、一緒にいるスクワッドに……#nちょっとくらい抗議してもいいんじゃないんですか……？"
"62060-80-アリウスの生徒D" = "……マイアだって、追い出しちゃったけど。#nそれでもせめて、毛布くらいは届けてあげたほうが……。"
"62060-81-スバル" = "……。"
"62060-82-スバル" = "同じことを言わせないでください。"
"62060-83-アリウスの生徒B" = "先輩……？"
"62060-84-アリウスの生徒B" = "え……？"
"62060-85-スバル" = "さっさと――"
"62060-86-スバル" = "寝なさい。"
"62060-87-スバル" = "いいですね？"
"62060-88-アリウスの生徒D" = "……！"
"62060-89-アリウスの生徒C" = "は、はいっ！"
"62060-90-アリウスの生徒D" = "先輩も……おやすみなさいっ！"
"62060-91-スバル" = "ふぅ……。"
"62060-92-スバル" = "……。"
"62060-93-スバル" = "今日は[ruby=ここ]バシリカ[/ruby]で寝るとしましょうか。"
"62060-94-スバル" = "……。"
"62060-95-スバル" = "はぁ……この感覚は……。"
"62060-96-スバル" = "死してなお、眠れないような……あの感覚ですね……。"
"62060-97-マイア" = "……。"
"62060-98-マイア" = "どう、しよう……これから……。"
"62060-99-マイア" = "……。"
"62060-100-マイア" = "いっそ、このまま……。"
"62060-101-マイア" = "……このまま。"
"62060-102-マイア" = "消えてしまいたい……。"
"62060-103-マイア" = "モモトーク……？誰から……？"
"62060-104-マイア" = "……。"
"62060-105-マイア" = "授業……明日も……こんな時に？"
"62060-106-マイア" = "先生は、本当に……。"
"62060-107-マイア" = "……。"
"62060-108-マイア" = "うぅ……。"
"62060-109" = "机はあるし、イスも起こせば問題ない。"
"62060-110" = "教卓も黒板もある！完璧な教室じゃないかな？"
"62060-111" = "初回は短めだから大丈夫だよ。"
"62060-112" = "出席を取って、軽くガイダンスをして終わりかな。"
"62060-113-マイア" = "うぅっ……。"
"62060-114-マイア" = "……行こう。"
"62060-115-マイア" = "先生の……ところに……。"
"62060-116-マイア" = "うぅ……ひっく……。"
"62060-117-マイア" = "うわああああああん……！"
"62060-118" = "（眠れなくて、天井を見つめていた）"
"62060-119" = "（黙示録……ラッパの音……天使……言葉が頭の中を駆け巡っていく……）"
"62060-120" = "[ns] \"はーい、ちょっと待ってね。\""
"62060-121" = "[ns] \"マイア！？どうしたの？\""
"62060-122-マイア" = "こ、こんな時間にすみません……。"
"62060-123-マイア" = "本当に……本当に申し訳ないんですけど――"
"62060-124-マイア" = "ひと晩だけ……泊めていただけませんか……？"
"62060-125-マイア" = "明日には、ちゃんと……消えますから。"
"62060-126-マイア" = "二度とご迷惑はおかけしませんから……今日だけ……どうか……。"
"62060-127" = "[ns] \"いいよ。どうぞ、中に入って。\""
"62060-128-マイア" = "わわっ！？"
"62060-129" = "[ns] \"まずは手と顔を洗おうか。\""
"62060-130-マイア" = "だ、大丈夫です！大丈……夫、です……。"
"62060-131" = "（顔の腫れがひどいので、水で洗ってあげた）"
"62060-132" = "（その水を飲もうとしたので、急いで飲み物をたくさん用意した）"
"62060-133" = "（何があったのか聞こうかと思ったけど……）"
"62060-134-マイア" = "……。"
"62060-135" = "[s10] \"さ、今日はゆっくり休もう。\"\n[s11] \"寝袋は自由に使っていいからね。\""
"62060-136-マイア" = "え……？"
"62060-137-マイア" = "で、でもこれ、先生の……ですよね？"
"62060-138-マイア" = "こ、こんなに気を遣っていただかなくても……。"
"62060-139-マイア" = "って、先生！それアルミブランケットですよね……？"
"62060-140-マイア" = "だ、ダメです！それはおかしいですっ！私がそのブランケットを使います！"
"62060-141-マイア" = "えっ？それなら外で寝る……？それはもっとダメですけど！？"
"62060-142-マイア" = "はぁ……はぁ……わ、分かりまし……た……。"
"62060-143-マイア" = "寝袋、使わせてもらいます……ありがとうございます……。"
"62060-144-マイア" = "お腹……？いえっ、大丈夫ですっ！全然空いてないのでっ！"
"62060-145" = "[ns] \"ふふっ、お腹は正直だね。\""
"62060-146-マイア" = "うぅ……すみません……。"
"62060-147-マイア" = "もぐもぐ……ごくっ。"
"62060-148" = "[s] \"焦らなくて大丈夫だよ。\""
"62060-149-マイア" = "で、でも……でも……。"
"62060-150-マイア" = "これ、美味しいです。"
"62060-151-マイア" = "……本当に、美味しい……です……。"
"62060-152-マイア" = "……。"
"62060-153-マイア" = "うっ……。"
"62060-154" = "[s] \"……。\""
"62060-155" = "[ns] \"……お腹いっぱいになった？\""
"62060-156-マイア" = "はい……ありがとうございます……。"
"62060-157-マイア" = "えっ……先生、食べてすぐ寝るんですか……？"
"62060-158-マイア" = "……。"
"62060-159-マイア" = "あの……。"
"62060-160-マイア" = "何があったのか、とか……聞かないんですか……？"
"62060-161" = "[s12] \"今日はもう遅いしさ。\"\n[s13] \"ふわぁ……眠くなってきちゃった……。\""
"62060-162-マイア" = "すみません……。"
"62060-163-マイア" = "私がこんな時間に来たせいで……。"
"62060-164-マイア" = "ごめんなさ……い……。"
"62060-165-マイア" = "えっ？気にしないでいい、と言われても……だって……。"
"62060-166-マイア" = "あの、私……明日、先生が起きるまでには……消えますから……。"
"62060-167-マイア" = "……なんで、ですか。#n本当に……ここにいても……いいんですか……？"
"62060-168-マイア" = "でも、私、その……。"
"62060-169" = "[s14] \"なにも気にしなくていいんだよ。\"\n[s15] \"話だって、マイアが話したくなったら聞くからさ。\""
"62060-170-マイア" = "……。"
"62060-171-マイア" = "…………。"
"62060-172-マイア" = "ありがとうございます、先生。"
"62060-173-マイア" = "ありがとう、ござい……ます……。"
"62060-174-マイア" = "うぅっ、うぅ……。"
"62060-175" = "（よほど疲れていたのだろう。すぐに小さな寝息が聞こえてきた）"
"62060-176" = "（悲しい夢を見ているのか、時折うなされていたけれど……）"
"62060-177" = "（こういうのこそ、先生の役目なんだと思った）"
"62060-178-スバル" = "皆さん、集まっていますね？"
"62060-179-アリウスの生徒たち" = "はい！"
"62060-180-スバル" = "それでは――"
"62060-181-スバル" = "ポルタパシスへ向かいます。"
"62060-182-アリウスの生徒たち" = "はい！"
"62060-183-アリウスの生徒B" = "……本当に大丈夫かな？"
"62060-184-アリウスの生徒B" = "まだ夜明け前だよ……？#n早く寝ろって昨日言ってたのは、このため？"
"62060-185-アリウスの生徒B" = "なんでこんな早朝に……ポルタパシスのこともよく分かんないし……#nなんか不安かも……。"
"62060-186-アリウスの生徒A" = "このままついて行ったら、先生の授業に出られないよね……。"
"62060-187-アリウスの生徒B" = "というか、ポルタパシスに行って何も分からなかったらどうするの……？"
"62060-188-アリウスの生徒A" = "しっ、聞こえちゃうって！"
"62060-189-スバル" = "何か問題でも？"
"62060-190-アリウスの生徒たち" = "いえっ！なんでもありません！"
"62060-191-スバル" = "――だから、目をさましていなさい。"
"62060-192-スバル" = "その日その時が、あなたがたには分からないからである。"
"62060-193-ミサキ" = "……。"
"62060-194-ミサキ" = "……。"
"62060-195-ヒヨリ" = "だ、誰も……来てないみたい……ですね？"
"62060-196-マイア" = "……。"
"62060-197-サオリ" = "これが……いわゆる「無断欠席」か？"
"62060-198" = "[s16] \"……そうだね。\"\n[s17] \"でも、全員一斉に、か……。\""
"62060-199-アツコ" = "先生、どうする？といっても、みんなが行きそうな場所の心当たりはないんだけど。"
"62060-200-アツコ" = "え？電話してみるって……誰に？"
"62060-201-アツコ" = "スバル……？"
"62060-202-アツコ" = "……分かった、お願い。"
"62060-203-ヒヨリ" = "……。"
"62060-204-ヒヨリ" = "出ない……ですか……？"
"62060-205" = "[s18] \"授業が嫌になっちゃったのかもしれないけど……。\"\n[s19] \"黙っていなくなったら心配だよね……。\""
"62060-206-マイア" = "あの、先生……。#nみんなが行った場所の心当たりが、あります。"
"62060-207-サオリ" = "分かるのか？"
"62060-208-マイア" = "はい……たぶん、みんな――"
"62060-209-マイア" = "「ポルタパシス」に向かったんだと思います……。"
"62060-210-アツコ" = "！！！"
"62060-211" = "次回;ポルタパシス（１）"
