[translation]
"1005105-1" = "情熱の応援魂"
"1005105-2" = "ラーメン屋の前"
"1005105-3-ラーメン屋の店主" = "あのぉ……。"
"1005105-4-ラーメン屋の店主" = "客引き用の応援ロボットを注文したはずなのですが……。"
"1005105-5-ラーメン屋の店主" = "どうしてエンジニア部のマイスターご本人がいらっしゃったのでしょうか……？"
"1005105-6-ウタハ" = "そう、なぜなら……"
"1005105-7-ウタハ" = "応援ロボットの開発に失敗したからさ！"
"1005105-8-ラーメン屋の店主" = "えっ……そうですか。#nそれは残念です……。"
"1005105-9-ウタハ" = "落ち込まなくても大丈夫だよ、大将。#n今日はロボットの代わりを私が務めよう！"
"1005105-10-ラーメン屋の店主" = "マイスター自らが応援してくださると……？"
"1005105-11-ラーメン屋の店主" = "あの……それでしたら、バイトを雇おうと思うのですが……。"
"1005105-12-ウタハ" = "いいや、一度引き受けた依頼は最後までやり遂げる！#nそれこそがマイスターとしての責務だからね。"
"1005105-13-ウタハ" = "お金をもらうつもりはないから、費用の心配はいらない。#nここは私に任せてくれ。"
"1005105-14-ラーメン屋の店主" = "そ、それならお願いします……。"
"1005105-15-ウタハ" = "よし……ラーメン店の繁盛を祈って、エールを送る！"
"1005105-16-ウタハ" = "フレーッ、フレーッ、すずめ亭！"
"1005105-17-ウタハ" = "頑張れ、頑張れ、すずめ亭！"
"1005105-18-ウタハ" = "行けるぞ、勝てるぞ、すずめ亭！"
"1005105-19" = "[ns] \"……何に頑張って勝つの？\""
"1005105-20-ウタハ" = "飲食店を経営する以上、様々な困難に立ち向かうわけだろう？"
"1005105-21-ウタハ" = "テナントの賃料や人件費もそうだが、厳しい衛生管理も求められる。#nそういったものに打ち勝ってほしいという願いを込めたんだ。"
"1005105-22-ラーメン屋の店主" = "す、すごい気合ですね。声を聞いているだけで力が湧いてきます。"
"1005105-23-ラーメン屋の店主" = "……ところで、どうして厨房の前で応援を……？"
"1005105-24-ウタハ" = "それはもちろん、繁盛するためには大将の熱意が必要不可欠だからだ。"
"1005105-25-ウタハ" = "客を呼び込んだところで、大将に熱意がなければ、元の木阿弥だからね。"
"1005105-26-ラーメン屋の店主" = "た、確かに……。勉強になりました。"
"1005105-27-ウタハ" = "……待ってくれ。まだ生地を練っているのかい？"
"1005105-28-ウタハ" = "これでは開店時間を過ぎてしまう。#nなのに製麺が終わっていないなんて……。"
"1005105-29-ラーメン屋の店主" = "問題ありませんよ。#nどうせお客さんは来ませんし、なんならまだゆっくりしていられますから……。"
"1005105-30-ウタハ" = "問題大有りだ！"
"1005105-31-ウタハ" = "店が準備を怠ってどうする！ラーメン屋はスピード命！#n注文を受けた瞬間に麺を茹で始めなければ、客は愛想を尽かしてしまう！"
"1005105-32-ウタハ" = "ああ、じれったい。#nそんな手付きでは[ruby=マイスター]職人を[/ruby]名乗れないぞ！"
"1005105-33-ラーメン屋の店主" = "えぇ、私は職人を目指したいとは――"
"1005105-34-ウタハ" = "口を動かす暇があるなら手を動かせ！"
"1005105-35-ラーメン屋の店主" = "こ、こうですか？"
"1005105-36-ウタハ" = "まだまだ！もっと速く！#nそうだ、その調子だ！"
"1005105-37-ラーメン屋の店主" = "ひぃ……。"
"1005105-38-ウタハ" = "全力で！情熱を！戦うんだ大将！"
"1005105-39-ラーメン屋の店主" = "は、はいっ！"
"1005105-40-市民B" = "……ほらあれ、ラーメン屋の大将が応援団のかけ声で麺を打ってるよ。"
"1005105-41-市民B" = "手の動きが見えない……隠れ家的な職人のお店なのかな。"
"1005105-42-市民A" = "なんだかラーメンの気分になってきちゃった。#nお昼、ここにしよっか。"
"1005105-43-市民B" = "いいね！二人前お願いしまーす！"
"1005105-44-ラーメン屋の店主" = "……ありがとうございます！少々お待ちを！"
"1005105-45-ラーメン屋の店主" = "開店直後から列ができるだなんて……。"
"1005105-46-ラーメン屋の店主" = "これが応援の効果……？"
"1005105-47-ウタハ" = "ふふ、応援大成功だな。"
"1005105-48-ウタハ" = "先生、急ごう。#n次の人も待っているはずだ。"
"1005105-49-ファンクラブ会員A" = "……つまり、お願いした応援ロボットは完成しなかったということですね？"
"1005105-50-ウタハ" = "ああ、申し訳ない。私の力では期限までに間に合わせることができなかった。"
"1005105-51-ファンクラブ会員A" = "仕方ありませんね。お伝えしていた期限も短かったですし……。"
"1005105-52-ウタハ" = "安心してくれ。今日はロボットに代わって、#n私が応援団長として全力でエールを送ろう！"
"1005105-53-ウタハ" = "さあ、どんな悩みがあるんだい？"
"1005105-54-ファンクラブ会員A" = "じ、実は……"
"1005105-55" = "私はモモフレンズのビッグブラザー様が大好きなんです。#nあの全てを見抜く視線にやられてしまって、神秘的な魅力の虜になってしまいました。"
"1005105-56-ファンクラブ会員A" = "それ以来、ビッグブラザーファンクラブに加入してはいるんですが……。"
"1005105-57-ファンクラブ会員A" = "来週、ファンクラブの会長選挙が開かれるんです。#n本当は私も会長選挙に出て、ビッグブラザー様への思いを伝えたいのですが……勇気が出なくて。"
"1005105-58-ファンクラブ会員A" = "自分の気持ちすら正直に打ち明けられないような私が、全てを見抜くビッグブラザー様のファンクラブの会長になんて、なれっこないですよね……。"
"1005105-59-ウタハ" = "君の情熱はその程度なのかい？"
"1005105-60-ファンクラブ会員A" = "そ、そんなことは……。"
"1005105-61-ウタハ" = "好きなことを好きだと言う。それのどこに気後れする必要があるんだ！"
"1005105-62-ウタハ" = "もっと正直に！#nもっと勇気を！"
"1005105-63-ウタハ" = "それとも……もしやビッグブラザー様を恥ずかしく思っているのかい？"
"1005105-64-ウタハ" = "違います！心の底からビッグブラザー様が好きです！"
"1005105-65-ウタハ" = "だったら叫ぶんだ！自分の本当の気持ちを！"
"1005105-66-ファンクラブ会員A" = "私はビッグブラザー様が好きです！"
"1005105-67-ウタハ" = "ほら、もっとだ！"
"1005105-68-ファンクラブ会員A" = "ビッグブラザー様が大好きです！お慕いしています！"
"1005105-69-ファンクラブ会員C" = "……あの、会員さんですよね？#nこんなところでどうしたんですか？"
"1005105-70-ファンクラブ会員A" = "えっと……これはその、ビッグブラザー様に思いを伝えたくて……。"
"1005105-71-ファンクラブ会員B" = "いくらビッグブラザー様が好きとはいえ、#nこんな往来の場所で堂々と愛を叫ぶだなんて……。"
"1005105-72-ファンクラブ会員C" = "……感激です！"
"1005105-73-ファンクラブ会員A" = "……えっ？"
"1005105-74-ファンクラブ会員B" = "私たちも常日頃からビッグブラザー様への愛を叫びたいと思っていましたが、#n人目を気にして胸の内に留めていたんです。"
"1005105-75-ファンクラブ会員B" = "その愛をありのまま伝えることができるなんて、素晴らしいです！"
"1005105-76-ファンクラブ会員C" = "あなたこそ次期会長にふさわしい！"
"1005105-77-ファンクラブ会員A" = "ほ、本当ですか？"
"1005105-78-ファンクラブ会員A" = "私でも本当に……ビッグブラザーファンクラブの会長になれるのでしょうか？"
"1005105-79-ファンクラブ会員C" = "もちろんです！"
"1005105-80-ファンクラブ会員C" = "私たちも一緒にビッグブラザー様の魅力を大声で叫ばせてください！"
"1005105-81-ウタハ" = "……今回も大成功だね！"
"1005105-82" = "[s] \"すごい情熱だ……。\""
"1005105-83-ウタハ" = "ふふ、先生に褒めてもらえて光栄だ。"
"1005105-84-ウタハ" = "こうしてはいられない。まだまだ私たちの応援を待っている人がいるのだから！"
"1005105-85" = "（その後もウタハと一緒に市内各地を回って、エールを送り続けた）"
"1005105-86-ウタハ" = "ふぅ……良い一日だったね。"
"1005105-87" = "[s] \"お疲れさま、ウタハ。\""
"1005105-88-ウタハ" = "そもそも私が期限を守れていれば良かったのだけど……。#nでも、みんなが満足してくれて良かったよ。"
"1005105-89-ウタハ" = "それに普段は機械をいじってばかりだから、たまには身体を動かすのも良いものだね。"
"1005105-90-ウタハ" = "おかげで新しいインスピレーションも得られたよ……初心を思い出すこともできた。"
"1005105-91-ウタハ" = "早く帰って次の発明品を作りたくなってきたよ。"
"1005105-92" = "[ns1] \"ところで、どうしてさっきから…\"\n[ns2] \"ささやくように話してるの？\""
"1005105-93-ウタハ" = "それが……"
"1005105-94-ウタハ" = "一日中、叫んでいたせいで……"
"1005105-95-ウタハ" = "声が……出な……っ。"
"1005105-96" = "（その後、喉が枯れてしまったウタハを労りながら、シャーレに戻った）"
