[translation]
"1005106-1" = "情熱の応援歌"
"1005106-2" = "ミレニアムサイエンススクール・近所のカラオケ店"
"1005106-3" = "[ns1] \"……どうしたの？\"\n[ns2] \"……なんでカラオケ？\""
"1005106-4-ウタハ" = "先生が言っていたじゃないか。#n後輩たちが元気を取り戻せる方法を探そうって話だよ。"
"1005106-5-ウタハ" = "応援と言えば応援歌。先生も分かるだろう？"
"1005106-6-ウタハ" = "つまりはカラオケというわけだ！"
"1005106-7" = "[ns3] \"……ど、どういう繋がり？\"\n[ns4] \"……置いてけぼりになってる。\""
"1005106-8-ウタハ" = "ほら、楽しい歌を聞けば元気が出るだろう？"
"1005106-9-ウタハ" = "ほら、楽しい歌を聞けば元気が出るだろう？"
"1005106-10-ウタハ" = "私の持ち得る技術を駆使しても、後輩たちの悩みを完璧に解消はできない……。"
"1005106-11-ウタハ" = "せめて気が晴れるようにと思って、楽しい歌を聴かせるのはどうかなと。"
"1005106-12-ウタハ" = "……そう、エンジニア部の活動を歌詞に盛り込んだオリジナル曲でね！"
"1005106-13" = "[s] \"オリジナル曲？\""
"1005106-14-ウタハ" = "ふふ、実は前からエンジニア部のテーマ曲を作ってみたかったんだ。"
"1005106-15-ウタハ" = "応援もできて、エンジニア部の曲も作れる良い機会だろう。"
"1005106-16" = "[s] \"ウタハが作曲を……？\""
"1005106-17-ウタハ" = "そんなに驚く事かい？"
"1005106-18-ウタハ" = "音を扱うこと、機械を扱うこと。#nどちらも本質的な部分は一緒さ。"
"1005106-19-ウタハ" = "エンジニアが設計書を作成して部品を組み合わせるように、音楽家は音を重ねて楽譜を形にするんだ。"
"1005106-20-ウタハ" = "しかも、指揮者を意味する「マエストロ」と「マイスター」は語源が一緒なんだ。"
"1005106-21-ウタハ" = "ふふ……もし私がミレニアムではなく、ワイルドハント芸術学院に入学していたら、マエストロの道を歩んでいたかもしれないね。"
"1005106-22" = "[s] \"……。\""
"1005106-23-ウタハ" = "……どうしたんだい？何か悪い記憶でも？"
"1005106-24-ウタハ" = "とにかく、頭に浮かんだ歌詞にメロディーを乗せてみたんだ。#n聞いてもらおうじゃないか。"
"1005106-25-ウタハ" = "それじゃあ……コホン、『燃えるマイスターの魂』。"
"1005106-26" = "― マイスターの　熱い　魂を　込め"
"1005106-27" = "― 皆様の　物を　改造して　差し上げます"
"1005106-28" = "― 望まなくても　改造して　差し上げます"
"1005106-29" = "[ns] \"………。\""
"1005106-30" = "― 動いて　もらいたい　所は　グリースオイル"
"1005106-31" = "― 固定して　欲しい　所はぁ　ダクトテープ"
"1005106-32" = "― 誰だって　簡単に　直せる　けど"
"1005106-33" = "― 確実な　性能を　求めるなら　お申しつけください"
"1005106-34" = "[ns] \"……ちょっと待って、ウタハ。\""
"1005106-35-ウタハ" = "おや、どこかおかしかったかな？"
"1005106-36-ウタハ" = "ここからが盛り上がるところなんだ。"
"1005106-37" = "[s5] \"……メロディーとリズムが合ってない。\"\n[s6] \"歌詞が……。\""
"1005106-38-ウタハ" = "え？リズムが合ってなかった？"
"1005106-39-ウタハ" = "いや……歌詞に情熱を込めすぎたか。#nメロディー以上の燃え上がりを見せてしまったようだね。"
"1005106-40-ウタハ" = "うん？歌詞の内容が難しかったかな？"
"1005106-41-ウタハ" = "いや……メロディーに情熱を込めすぎたかな。まさか歌詞を圧倒するなんて。"
"1005106-42-ウタハ" = "まだ調整段階なんだ。もう少しで良くなると思うんだけど……。"
"1005106-43-ウタハ" = "とりあえずサビまで聞いてくれ。きっと先生にもこの歌の魅力が伝わるはずさ！"
"1005106-44-ウタハ" = "……それでは、続けるよ。"
"1005106-45" = "― 湧き上がるぅ　＜チャバスコ！＞　飛び散る　＜パルメザン！＞"
"1005106-46" = "― 情熱さえ　あれば　なんだって　改造できるさ"
"1005106-47" = "[ns] \"なんでチャバスコ……？\""
"1005106-48" = "（その後、ウタハの変な歌は1時間以上続いた……）"
"1005106-49" = "（……後日、部員の元気がなかった理由は、ウタハが作業室でずっと変な歌を口ずさんでいたせいだと分かった……）"
