[translation]
"1300905-1" = "ツバキの修行法：実践編"
"1300905-2-ツバキ" = "今日は修行部の部長として、修行部の顧問である先生に、真の修行について教えてあげる。"
"1300905-3-ツバキ" = "真の修行。そう、つまり、「より気持ちよく、ぐっすりと熟睡できる睡眠法」について。"
"1300905-4" = "[s] \"やっぱりそういうのなんだね。\""
"1300905-5-ツバキ" = "先生、寝ることを侮ったらダメだよ……。"
"1300905-6-ツバキ" = "きちんと寝るのは、想像以上に難しいことだからね。"
"1300905-7-ツバキ" = "見て、現代の社会人たちはあらゆる原因の不眠症に悩まされてて、よく眠るコツや、"
"1300905-8-ツバキ" = "熟睡できる方法を求めて、こうやってネットに質問を投げてるくらいなんだから。"
"1300905-9-ツバキ" = "寝る前に温かいシャワーを浴びる、ココアを飲む、ホワイトノイズを聞きながら瞑想する、等々……。"
"1300905-10-ツバキ" = "色んな方法があるけど。その中でも私が実際に試してみて、効果があった方法を教えてあげる。"
"1300905-11-ツバキ" = "先生は特に毎日の残業のせいで、眠りが浅くなってそうだし……。"
"1300905-12" = "[s] \"そうだね、修行部の部長を全面的に信頼して拝聴します！\""
"1300905-13-ツバキ" = "うん。それじゃあ、まずはお手本を見せるね。見てて、先生。"
"1300905-14-ツバキ" = "まず見せるのは、丹田呼吸法。"
"1300905-15-ツバキ" = "こうやって横になって、しばらく瞑想をするように……。"
"1300905-16-ツバキ" = "お腹の下の方に精神を集中して……。"
"1300905-17-ツバキ" = "…………。"
"1300905-18-ツバキ" = "……。"
"1300905-19" = "[s] \"ツバキ？\""
"1300905-20-ツバキ" = "ぐぅぅ……。"
"1300905-21" = "[s1] \"横になってまだ20秒も経ってないよ！？\"\n[s2] \"ツバキさん待って！伝授の進みが早すぎます！\""
"1300905-22-ツバキ" = "んん……？もうご飯の時間……？"
"1300905-23" = "[s3] \"眠ってから起きるまでも20秒経ってないよツバキ！\"\n[s4] \"これを真似するのは難易度が高すぎませんか！？\""
"1300905-24-ツバキ" = "うーん、そう？じゃあ、丹田呼吸法は無しで……。"
"1300905-25-ツバキ" = "うーん、そう？じゃあ、丹田呼吸法は無しで……。"
"1300905-26-ツバキ" = "じゃあ今度は……座禅をしてみようか。座禅なら、もっと簡単に真似できると思う。"
"1300905-27-ツバキ" = "座禅は横にならずに、こうやって座ったまま、精神を集中するの。"
"1300905-28-ツバキ" = "先生もまずこういう風に座って、こう、やっ……て……すやぁ。"
"1300905-29" = "[s] \"説明の途中で寝ちゃった！？\""
"1300905-30-ツバキ" = "はっ！……あれ？えっと、これもダメ？"
"1300905-31" = "[s] \"私みたいなアマチュアにはまだ真似できなさそう……。\""
"1300905-32-ツバキ" = "良くないよ、先生。試す前からそうやってダメだ、ダメだって言うの。"
"1300905-33-ツバキ" = "うん、よし。私がお手本を見せるより、隣で指導する方が良いかも。"
"1300905-34-ツバキ" = "先生、やってみて。"
"1300905-35" = "[s] \"今から？\""
"1300905-36-ツバキ" = "ほら、こうやって横になってみて。それから、目を閉じて。"
"1300905-37-ツバキ" = "さあ、息を吸って……吐いて。胸が上がって……下がるよ。"
"1300905-38-ツバキ" = "ゆっくり、ゆっくり。精神を集中してね、先生。"
"1300905-39-ツバキ" = "だんだん、楽になっていくよ。精神がまるで、水面の下に潜って行くように……。"
"1300905-40-ツバキ" = "あなたはだんだん、眠くなる……。"
"1300905-41" = "（ツバキの声の通りに、だんだん世界が遠くなっていくような感じがする）"
"1300905-42" = "（ゆっくり、ゆっくり……目を閉じたまま、意識が……）"
"1300905-43" = "（……なんてことは起きず、何故かむしろ、だんだんと意識がはっきりしてきた）"
"1300905-44" = "[ns] \"……。\""
"1300905-45" = "[ns] （私には効かなかった感じかな？）"
"1300905-46" = "[ns] （ツバキは……もしかして寝ちゃった？）"
"1300905-47" = "（ツバキの声が聞こえなくなったので、微かに目を開けてみることにした）"
"1300905-48-ツバキ" = "（先生の寝顔……こんな感じなんだ。ふふっ……）"
"1300905-49" = "[ns] \"……ツバキ？\""
"1300905-50" = "（不意に、ツバキと目が合ってしまった）"
"1300905-51-ツバキ" = "えっ、先生、眠ったんじゃ……。"
"1300905-52-ツバキ" = "あっ、うわっ……！"
"1300905-53" = "[s] \"だ、大丈夫！？急にひっくり返って……！\""
"1300905-54-ツバキ" = "う、うん……。"
"1300905-55-ツバキ" = "先生、その……見た？"
"1300905-56" = "[s5] \"うん。ツバキの熱い視線、感じたよ。\"\n[s6] \"いや、な、何も見てないけど……？\""
"1300905-57-ツバキ" = "……私、もう寝る。"
"1300905-58" = "[s7] \"ごめん、今の無し！\""
"1300905-59-ツバキ" = "うう……。"
"1300905-60-ツバキ" = "……見てない？本当に？"
"1300905-61" = "[s8] \"全然見てないってわけではないけど、その、少しだけ……。\""
"1300905-62-ツバキ" = "うっ……意地悪。"
"1300905-63-ツバキ" = "先生の……意地悪……。"
"1300905-64" = "（その後、夕方までツバキを慰めないといけなくて大変だった）"
