[translation]
"1004205-1" = "街の花園"
"1004205-2" = "[ns] \"おはよう、アツコ。\""
"1004205-3-アツコ" = "うん、おはよう。先生。"
"1004205-4-アツコ" = "……それは、何？"
"1004205-5" = "[s] \"生け花をするならって思って。\""
"1004205-6-アツコ" = "……え？"
"1004205-7" = "[wa:400]― この花、[wa:1800]もしかして……。"
"1004205-8" = "― ……持ってきて、[wa:1200]くれたんだ。"
"1004205-9" = "[wa:300]― 私の[wa:800]ために……？"
"1004205-10" = "― ……そっか。"
"1004205-11" = "[wa:500]― ……大切にするね、[wa:2100]ずっと。"
"1004205-12" = "[wa:1800]― ……すごく[wa:900]嬉しい。"
"1004205-13" = "― ありがとう。"
"1004205-14-アツコ" = "……でも、私、生け花をするとは、言ってないよ。"
"1004205-15" = "[s1] \"……え？\"\n[s2] \"あれ、そうだったっけ……！？\""
"1004205-16-アツコ" = "うん。花壇を作ろうとしてた。"
"1004205-17-アツコ" = "うん。花壇を作ろうとしてた。"
"1004205-18" = "[s] \"花壇……。\""
"1004205-19-アツコ" = "これは、花壇に植えられないけど、大切にするね。"
"1004205-20-アツコ" = "ふふっ……これは、特別だから。"
"1004205-21-アツコ" = "花壇はこっちだよ、先生。"
"1004205-22" = "（人々が往来する街の片隅に、花壇が作られていた。）"
"1004205-23" = "（花壇の所々に、花が植えられている。）"
"1004205-24" = "[ns] \"これが花壇？\""
"1004205-25-アツコ" = "うん。しばらくは、この地域にいる予定なんだって。"
"1004205-26-アツコ" = "だから、花壇を作ってもいいかなって。"
"1004205-27-アツコ" = "日当たりのいい場所を探して、ここに花を植え替えたの。"
"1004205-28-アツコ" = "始めたばかりだけど……ここを全部、花でいっぱいにしたい。"
"1004205-29" = "[s] \"これはなんて名前の花なの？\""
"1004205-30-アツコ" = "……私も知らない。"
"1004205-31" = "[s] \"そっか。調べるの難しいよね。\""
"1004205-32-アツコ" = "……ただの花。都市に野放図に生えている雑草。どれも名前があったかもしれないけど、私は知らない。"
"1004205-33-アツコ" = "そのままにしておいたら、枯れちゃったかも……だからここに移したの。"
"1004205-34-アツコ" = "ここで、地に根を下ろしたらいいなって……そう思って。"
"1004205-35" = "[s] \"それなら、私も手伝うよ。\""
"1004205-36-アツコ" = "……うん、ありがとう。"
"1004205-37-アツコ" = "じゃあ、近くで花を見つけたら、根っこまで掘り起こしてここに持ってきてくれる？"
"1004205-38" = "[s3] \"わかった。\"\n[s4] \"任せて。\""
"1004205-39-アツコ" = "気をつけてね。根が傷むと死んじゃうから。"
"1004205-40-アツコ" = "気をつけてね。根が傷むと死んじゃうから。"
"1004205-41" = "（その後、しばらく街に咲いている花を探し回った。）"
