[translation]
"2300505-1" = "アヤネの悲惨な修理劇"
"2300505-2" = "アビドス高等学校"
"2300505-3-アヤネ" = "あはは……せっかくの休みの日なのに、学校の修理だなんて。"
"2300505-4-アヤネ" = "私は良いのですが、先生は大丈夫ですか？"
"2300505-5" = "[s1] \"問題ないよ。\"\n[s2] \"どうせ暇だから。\""
"2300505-6-アヤネ" = "お忙しいはずなのに……。"
"2300505-7-アヤネ" = "お忙しいはずなのに……。"
"2300505-8-アヤネ" = "えっと、アビドスの校舎はかなり古くて、壊れたところは一か所や二か所ではありません。直すところはたくさんありまして……。"
"2300505-9-アヤネ" = "いつもは壊れても、そのまま放置してしまっているのですが……。"
"2300505-10-アヤネ" = "それでいつまでも放置したままにはできませんから……こうして、少しずつでも日を決めて修理をして、維持していくしかないんです。"
"2300505-11" = "[s] \"なるほど……うん、じゃあ行こっか。\""
"2300505-12" = "グラウンド・水飲み場"
"2300505-13" = "[ns] \"水飲み場だね。\""
"2300505-14-アヤネ" = "はい。数日前から蛇口の水が出てこなくなってしまって……。"
"2300505-15-アヤネ" = "どこか水道の配管に問題がありそうなのですが……部活が忙しかったこともあって、原因が特定できていなくて。"
"2300505-16" = "[s3] \"配管の問題なら大ごとになりそうだね。\"\n[s4] \"私たちにできるかな？\""
"2300505-17-アヤネ" = "大丈夫かと思います。以前に、私も何回か直してますから。"
"2300505-18-アヤネ" = "大丈夫かと思います。以前に、私も何回か直してますから。"
"2300505-19" = "[s] \"アヤネが？\""
"2300505-20-アヤネ" = "はい。最初、水道の専門業者の方にお願いした時、どうやって直すのかをじっと見ていたんです。"
"2300505-21-アヤネ" = "どうやら一人でもできそうでしたので、それからはずっと、壊れた時は私が修理していました。"
"2300505-22" = "[s] \"アヤネはすごいね。\""
"2300505-23-アヤネ" = "あはは……修理マニュアルですとか、上水道の配管の本などで勉強もしましたので……。"
"2300505-24-アヤネ" = "そんな、大したことではありません。"
"2300505-25-アヤネ" = "えっと……では、とりあえず状況を……。"
"2300505-26" = "（キュッ、キュッ）"
"2300505-27-アヤネ" = "……。"
"2300505-28" = "[s] \"蛇口をどれだけひねっても、全然出てこないね。\""
"2300505-29-アヤネ" = "そうですね。どれどれ……えっと、こういう時は……下の計量器を……。"
"2300505-30" = "（スッ）"
"2300505-31-アヤネ" = "この辺にあったような……。"
"2300505-32" = "（ガサゴソ……）"
"2300505-33-アヤネ" = "……あれ？"
"2300505-34" = "[s] \"どうしたの？\""
"2300505-35-アヤネ" = "はい、それが――"
"2300505-36-アヤネ" = "（スッ）"
"2300505-37" = "（ゴンッ！！！！）"
"2300505-38-アヤネ" = "ぎゃんっ！？"
"2300505-39" = "（アヤネが身体を起こそうとして、ものすごい音を立てて水飲み場のコンクリートの角に頭を打った）"
"2300505-40" = "[s5] \"アヤネ、大丈夫？！\"\n[s6] \"ものすごい音がした！？\"\n[s7] \"変な悲鳴が！？\""
"2300505-41-アヤネ" = "あ……うあぁぅぅ……。"
"2300505-42-アヤネ" = "あ……うあぁぅぅ……。"
"2300505-43-アヤネ" = "あ……うあぁぅぅ……。"
"2300505-44-アヤネ" = "……わ、私は大丈夫です、うぅ……も、もう原因も分かったので……。"
"2300505-45-アヤネ" = "……。"
"2300505-46" = "[s8] \"……。\"\n[s9] \"…………。\""
"2300505-47-アヤネ" = "み、水漏れなら、計量器が回っているはずなんです。ですが……計量器が全然回っていなかったので……。"
"2300505-48-アヤネ" = "み、水漏れなら、計量器が回っているはずなんです。ですが……計量器が全然回っていなかったので……。"
"2300505-49" = "[s10] \"いや、それより……。\"\n[s11] \"頭が……。\""
"2300505-50-アヤネ" = "ちょっとぶつかっただけですから、大丈夫です……。"
"2300505-51-アヤネ" = "ちょっとぶつかっただけですから、大丈夫です……。"
"2300505-52-アヤネ" = "……。"
"2300505-53-アヤネ" = "痛くない、です……。（うるうる）"
"2300505-54-アヤネ" = "原因も分かりましたし……行きましょう……。"
"2300505-55" = "（無理して我慢しなくてもいいよと言いたかったけれど、）"
"2300505-56" = "（それを言うとアヤネがもっと恥ずかしがる気がして、言えなかった……）"
"2300505-57" = "アビドス高等学校・地下の設備"
"2300505-58" = "（ゴウン、ゴウン、ゴウン……）"
"2300505-59-アヤネ" = "ここに、校舎の配管が全て集まっているんです。"
"2300505-60-アヤネ" = "必要な配管以外は私が閉じてまして……普段使っているシャワー室やトイレ、給湯室など、いつも使うところだけを開けていました。"
"2300505-61-アヤネ" = "もちろんグラウンドの水道も、開けていたはずなのですが……。"
"2300505-62" = "[s] \"閉まってるね。\""
"2300505-63-アヤネ" = "はい、誰かがバルブを閉めたのかもしれません。"
"2300505-64-アヤネ" = "多分ですが、私たちへの嫌がらせ目的ではないと思います。もしそうだとしたら、もっと効果的な方法がありますし。たとえばトイレの配管とか……"
"2300505-65-アヤネ" = "……。"
"2300505-66" = "[s] \"ん……？ごめん、よく聞こえなかった、何て言ったの？\""
"2300505-67-アヤネ" = "……いえ、何でもありません。恐らく、これをしたのは対策委員会の誰かだと思います。理由は分かりませんが……。"
"2300505-68-アヤネ" = "とにかく、原因も分かりましたし……バルブを開ければ解決です。"
"2300505-69-アヤネ" = "あ、これ、12インチのレンチが必要ですね……。"
"2300505-70-アヤネ" = "えっと……確か第3体育倉庫にあったような……。"
"2300505-71" = "[s] \"私が取ってこようか？\""
"2300505-72-アヤネ" = "いえ、その倉庫、少し離れたところにありますので……一緒に行きましょう、先生。"
"2300505-73" = "（ギイイイィィッ……）"
"2300505-74-アヤネ" = "けほっ、けほっ。"
"2300505-75-アヤネ" = "ふう……古くて、扉も開きにくいですね。"
"2300505-76-アヤネ" = "第3倉庫は珍しく、入り口が鉄製でして……開ける時、いつも大変なんです。"
"2300505-77-アヤネ" = "多分……元々は防空壕の役割をしていたのではないでしょうか。"
"2300505-78-アヤネ" = "もしこんな重い扉が壊れてしまったら、中からは絶対に開けられないでしょうし、壊れる前にこれもいつか修理を……。"
"2300505-79" = "（ガチャンッ！！）"
"2300505-80-アヤネ" = "……。"
"2300505-81" = "[s] \"何か、不吉な音が聞こえたような気が……。\""
"2300505-82-アヤネ" = "あ、あれ……！？"
"2300505-83-アヤネ" = "（ガチャッガチャッ）扉が！？"
"2300505-84-アヤネ" = "だ、ダメ……！！"
"2300505-85-アヤネ" = "あ、開きません！ど、どどど、どうしましょう……！"
"2300505-86" = "[s12] \"落ち着いて、アヤネ。\"\n[s13] \"今すぐに死ぬわけじゃないから！\""
"2300505-87-アヤネ" = "も、もちろん今すぐ死ぬわけではないですが……。"
"2300505-88-アヤネ" = "も、もちろん今すぐ死ぬわけではないですが……。"
"2300505-89-アヤネ" = "委員会の皆さんに連絡をして、第3体育倉庫に先生と二人で閉じ込められていると言えばもちろん、すぐに助けに来てくれると思います、が……。"
"2300505-90-アヤネ" = "「アヤネちゃん、どうしてこんなひと気のない体育倉庫で、先生と二人っきりだったの？」なんて聞かれたら、どう答えれば良いのか……。"
"2300505-91" = "[s] \"正直に言えばいいと思うよ！？\""
"2300505-92-アヤネ" = "……。"
"2300505-93-アヤネ" = "や、やっぱり、そうですよね……。ちゃんと、分かってくれますよね……？"
"2300505-94-アヤネ" = "……。"
"2300505-95-アヤネ" = "分かって、くれるでしょうか……？"
"2300505-96-アヤネ" = "も、もちろん先生となら……私は嫌じゃない、ですが……嫌どころか、むしろ嬉し……いやっ、でも……。"
"2300505-97-アヤネ" = "「アヤネちゃんは大人しい子だと思ってたけど、やるじゃーん。能ある鷹は爪を隠すって言うもんね、こんなに鋭い爪を隠してたなんてさー」みたいな、生暖かい目で見られたら、私は一体どうすれば……。"
"2300505-98-アヤネ" = "もう穴でも掘ってそこに入るしか……うあぁ……。"
"2300505-99" = "[s14] \"アヤネ、落ち着いて。 \"\n[s15] \"出られる方法、見つけたから。\""
"2300505-100-アヤネ" = "……はい！？"
"2300505-101-アヤネ" = "……はい！？"
"2300505-102" = "[ns] 反対側の壁を指さす。"
"2300505-103-アヤネ" = "あ……。"
"2300505-104-アヤネ" = "そういえば、窓がありましたね。"
"2300505-105" = "[s] \"良かった。\""
"2300505-106-アヤネ" = "あそこ、確かに一人くらいなら出られそうですが……ちょっと位置が高いですね。"
"2300505-107" = "[s16] \"肩車してあげるから、\"\n[s17] \"アヤネが飛び越えて、扉を開けてきて。\""
"2300505-108-アヤネ" = "はい！？"
"2300505-109-アヤネ" = "はい！？"
"2300505-110-アヤネ" = "私のことを、先生がですか！？"
"2300505-111-アヤネ" = "そ、そんな……！？"
"2300505-112" = "[s] \"そうでなければ、対策委員会のみんなに連絡を……。\""
"2300505-113-アヤネ" = "……。"
"2300505-114-アヤネ" = "……か、肩車にしましょう！"
"2300505-115-アヤネ" = "そ、それでは、よろしくお願いします。"
"2300505-116" = "（スッ）"
"2300505-117-アヤネ" = "す、すみません先生、重くないですか……？"
"2300505-118-アヤネ" = "う、うぅ……こ、こうなると分かっていたら、せめてストッキングを……。"
"2300505-119" = "（ガラッ）"
"2300505-120-アヤネ" = "幸い窓に鍵はかかってないですね、では……。"
"2300505-121-アヤネ" = "よっ……とっ！"
"2300505-122" = "（ズルッ）"
"2300505-123-アヤネ" = "あっ、きゃあっ！？"
"2300505-124" = "（ドサッ！バタンッ！）"
"2300505-125" = "[s] \"アヤネ、大丈夫！？\""
"2300505-126-アヤネ" = "けほっ、けほっ……ちょ、ちょっと転んだだけです。うぅ……口の中に砂が……。"
"2300505-127-アヤネ" = "とりあえず、無事に出られましたので……。"
"2300505-128-アヤネ" = "すぐに扉を開けてきますね。"
"2300505-129" = "（タッタッタッタッ……）"
"2300505-130" = "（ガチャッ）"
"2300505-131" = "（ギイイイィィッ……）"
"2300505-132-アヤネ" = "……。"
"2300505-133" = "[s18] \"やったね！\"\n[s19] \"砂まみれになっちゃったね。\""
"2300505-134-アヤネ" = "あ、あはは……。"
"2300505-135-アヤネ" = "あ、あはは……。"
"2300505-136" = "（その後、無事にレンチを手に入れて、水道のバルブを開けることができた）"
"2300505-137-アヤネ" = "……。"
"2300505-138" = "（キュッキュッ）"
"2300505-139" = "（ジャー―――――……）"
"2300505-140-アヤネ" = "ふぅ……無事水が出るようになりましたね、先生。"
"2300505-141-アヤネ" = "お疲れ様でした、水飲み場が直って良かったです。"
"2300505-142" = "[s] \"アヤネもお疲れ様。\""
"2300505-143-アヤネ" = "ふう……あちこち汚れちゃいましたね……喉も乾きましたし……くたくたです……。"
"2300505-144-アヤネ" = "すみません、先生。ちょっと待ってていただけますか？"
"2300505-145" = "― ……？[wa:1500]……先生？[wa:1500]そこに[wa:500]いらっしゃいます、[wa:1000]よね？[wa:500] "
"2300505-146" = "― メガネが無いと……[wa:1500]ちょっと[wa:500]よく見えなくて。[wa:300] "
"2300505-147" = "[ns] \"メガネを取ったアヤネの顔、初めて見たかも。\""
"2300505-148" = "― え？[wa:1000]あ、[wa:500]はい。[wa:1500]確かに私、[wa:1000]ほとんどずっと付けてますもんね。"
"2300505-149" = "― あ、[wa:500]あはは……[wa:1500]流石に、[wa:500]顔を洗う時は外しますから。"
"2300505-150" = "[wa:500]― な、[wa:500]なんだか[wa:700]顔が熱いです……。[wa:300] "
"2300505-151" = "― 先生に、[wa:1000]恥ずかしいところを見られてしまって……。"
"2300505-152" = "[ns20] \"パニック状態のアヤネ、\"\n[ns21] \"可愛かったよ。\""
"2300505-153" = "― はいっ？！[wa:1000]か、[wa:300]可愛いって……[wa:1500]そんな……"
"2300505-154" = "― あ、[wa:900]あぅぅ……。"
"2300505-155" = "― そ、[wa:1000]そんなに見つめられますと……。"
"2300505-156" = "― は……[wa:800]恥ずかしいです……。[wa:200] "
