[translation]
"1007906-1" = "自動販売機"
"1007906-2" = "（急ぎの救援要請を受けて、公園まで走った）"
"1007906-3" = "[ns1] \"……？？？\"\n[ns2] 音がした方へ向かう。"
"1007906-4-御坂美琴" = "……んん、もう。"
"1007906-5-御坂美琴" = "どうしてこっちの世界でも、自販機にお金を飲まれなきゃいけないわけ？"
"1007906-6-御坂美琴" = "ここまで来ると、私になにか問題があるのかしら……？"
"1007906-7-御坂美琴" = "いやいや、あり得ないでしょ。どう考えても自販機が悪いわね。"
"1007906-8" = "[s3] \"御坂？\"\n[s4] \"自販機を蹴ってどうしたの！？\""
"1007906-9-御坂美琴" = "……あっ、先生。"
"1007906-10-御坂美琴" = "恥ずかしいところを見られちゃったわね……"
"1007906-11-御坂美琴" = "……ん？あぁ、そうなの、コイツよ。"
"1007906-12-御坂美琴" = "自販機で飲み物を買おうとしたら、「また」お金を飲まれちゃったの。"
"1007906-13-御坂美琴" = "いや……「また」って言うのは、ちょっと違うか。"
"1007906-14-御坂美琴" = "……ああ、先生は知らないわよね。"
"1007906-15-御坂美琴" = "向こうの学園都市にある自販機が、よく私のお金を飲んじゃうのよ。#n私が買おうとする時だけよく起こってね……"
"1007906-16-御坂美琴" = "でも、理由はよく分からなくて……もしかしたら、嫌われてるのかもね。"
"1007906-17-御坂美琴" = "キヴォトスなら大丈夫だと思ったんだけど……"
"1007906-18-御坂美琴" = "残念ながら、この通り。"
"1007906-19-御坂美琴" = "……ん？いや、毎回ってわけじゃないわ。"
"1007906-20-御坂美琴" = "いっそ必ず発生するんだったら、原因も調べやすいんだけど。"
"1007906-21" = "[s5] \"よくトラブルに巻き込まれるんだね。\"\n[s6] \"……他人事には思えないような。\""
"1007906-22-御坂美琴" = "とにかく、そういう理由なのよ。#nあっちでは、これでジュースが落ちてくるから。"
"1007906-23-御坂美琴" = "ほら、叩けば直るってよく言うでしょう？"
"1007906-24-御坂美琴" = "……イメージとは違うって、何が？"
"1007906-25-御坂美琴" = "ああ、そういうことね。"
"1007906-26-御坂美琴" = "電気で操作して解決すると思ったの？"
"1007906-27-御坂美琴" = "……いくら能力があるからって、こんなことにまで使わないわよ。"
"1007906-28-御坂美琴" = "自販機に電気を流したら壊れる可能性が高いし、毎度のようにそれで故障させてたら、私の仕業だってバレるでしょ。"
"1007906-29-御坂美琴" = "それに、蹴った方が早いじゃない？"
"1007906-30-御坂美琴" = "……ん？"
"1007906-31-御坂美琴" = "公共の物を蹴るのは良くないって……？"
"1007906-32-御坂美琴" = "な、何よ！"
"1007906-33-御坂美琴" = "急に正論なんて持ち出して！"
"1007906-34-御坂美琴" = "でも……たしかに先生の言う通りね。#nここは私たちの学園都市じゃないし。"
"1007906-35-御坂美琴" = "……え？"
"1007906-36-御坂美琴" = "場所は関係ない……？"
"1007906-37-御坂美琴" = "はあ……まさか、そんな先生らしいことを言うとは。"
"1007906-38" = "[s7] \"まあ、これでも先生だからね。\"\n[s8] \"私の立場、忘れてない……？\""
"1007906-39-御坂美琴" = "……あ。"
"1007906-40-御坂美琴" = "そ、そうだったわね。"
"1007906-41-御坂美琴" = "もしかして……"
"1007906-42-御坂美琴" = "先生を呼ばない方が良かったり……？"
"1007906-43-御坂美琴" = "……いや。#nこれに関しては私が悪かったわ、ごめんなさい。"
"1007906-44" = "[s9] 公園の管理組合に連絡する。\n[s10] 自販機に貼ってある連絡先に問い合わせる。"
"1007906-45" = "（自販機の修理が終わってから、飲み込まれたお金を返してもらいジュースを買い直した）"
"1007906-46-御坂美琴" = "人を呼んで直してもらうのは新鮮ね。"
"1007906-47-御坂美琴" = "……本来は、これが当然？そ、そうよね。"
"1007906-48-御坂美琴" = "まぁ、そうよね……先生ってたまに先生みたいな事いうのね。"
"1007906-49-御坂美琴" = "でも、おかげでジュースはちゃんと買えたもの。ありがとう、先生。"
"1007906-50-御坂美琴" = "……ん？"
"1007906-51-御坂美琴" = "分かってるわ。今度からは、蹴らずにちゃんと問い合わせるから。"
"1007906-52-御坂美琴" = "……これでも、ちゃんと反省してるのよ。"
"1007906-53-御坂美琴" = "人として当たり前のことで怒られて、ちょっと恥ずかしくなったわ……。"
