[translation]
"2000206-1" = "チーズ・イン・ザ・トラップ"
"2000206-2" = "サヤの研究室"
"2000206-3-サヤ" = "この前言ってたボードゲームを見せてほしいって？#nふっふっふっ。待つのだ、すぐに出してあげるから。"
"2000206-4-サヤ" = "じゃーん！これがぼく様が言った特製ボードゲームなのだ。#nその名も「チーズ・イン・ザ・トラップ」！"
"2000206-5-サヤ" = "ルールは簡単。このプラスチックの罠の上にチーズの模型をたくさん乗せておいて、罠に引っかからないように気を付けながら、チーズを一つずつ取ってくればいいのだ。#nどう、簡単だろう？"
"2000206-6-サヤ" = "今からこれで一緒に遊ぼう、ゲームに負けた方はデコピンなのだ！"
"2000206-7" = "[s] \"いいよ。\""
"2000206-8-サヤ" = "さあ、先生の分のチーズを分けてあげる。"
"2000206-9-サヤ" = "……今更だけど、先生の手は大きくて暖かいのだ。#nさすが、大人の手って感じがする。"
"2000206-10-サヤ" = "ネズ助のお腹を撫でてるみたいにふかふかで……。"
"2000206-11" = "[s] \"くすぐったい。\""
"2000206-12-サヤ" = "わ、わ、分かってるのだ！ぼく様ったら……ちょっと違うことを考えてたのだ。"
"2000206-13-サヤ" = "じゃ、じゃあゲームを始めてみようか？"
"2000206-14-サヤ" = "さあ、先生から始めて。"
"2000206-15" = "[s] 罠をかいくぐってチーズ模型を一つ取る。"
"2000206-16-サヤ" = "へえ……やるのだ。では今度はぼく様の番ね！"
"2000206-17-サヤ" = "うーん……罠にチーズがいっぱい、美味しそうなチーズがいっぱい……。"
"2000206-18-サヤ" = "取るのは一つだけだっけ？いや、二つでもいいかも……。"
"2000206-19" = "（バタンッ）"
"2000206-20-サヤ" = "はうっ。"
"2000206-21" = "[s] \"今回はサヤの負けだね。\""
"2000206-22-サヤ" = "うう……油断したのだ。一瞬チーズに気を取られて……。"
"2000206-23-サヤ" = "次は負けないのだ！"
"2000206-24" = "次、サヤのターンから。"
"2000206-25-サヤ" = "うう、これは確かに罠なのだ、でもこんなにチーズがいっぱいあるのに……。"
"2000206-26" = "（バタンッ）"
"2000206-27-サヤ" = "はうっ！"
"2000206-28" = "[s] \"またサヤの負け。\""
"2000206-29-サヤ" = "ううっ、これはぼく様に不利なのだ！#nどうしてよりによってチーズを持ってくるゲームなのだ？"
"2000206-30-サヤ" = "も、もちろんぼく様が選んだゲームではあるけど……#nぼく様にチーズを我慢しろなんて、これはあまりにも過酷すぎるのだ！"
"2000206-31-サヤ" = "……なに？天才であるぼく様ならチーズの誘惑も追い払えるって？"
"2000206-32-サヤ" = "はっはっは！それは当たり前なのだ。#n見てて！今度こそ勝って見せるから！もう一回！"
"2000206-33" = "次、再びサヤのターンから。"
"2000206-34-サヤ" = "……あれは模型、食べられない模型なのだ……。"
"2000206-35-サヤ" = "でもあの色鮮やかな黄色と柔らかそうな質感を見ていると、うう……。"
"2000206-36" = "（バタンッ）"
"2000206-37-サヤ" = "うわっ！"
