[translation]
"2000205-1" = "ダイエット薬"
"2000205-2" = "玄武商会通り"
"2000205-3-サヤ" = "迷わずにちゃんと来られたみたいだね。"
"2000205-4-サヤ" = "ふっふっふ、先生も知ってると思うけど、ここがあの山海珍味で有名な、山海経の玄武商会なのだ！"
"2000205-5-サヤ" = "露店の運営をめぐって生徒会と運営陣が暗闘をしているとか、#n色んな面白い噂がある場所ではあるけど、味だけは間違いないところなのだ！"
"2000205-6-サヤ" = "前回のミスへのお詫びになるか分からないけど、#n今日は特別に、ぼく様がここで見つけた美味しいお店を紹介してあげるのだ！"
"2000205-7-サヤ" = "そういえば先生……まだネズ助みたいな産毛が顔に残ってるね。くくっ……。"
"2000205-8-サヤ" = "ご、ごめん、先生。笑っちゃいけないと思っても、面白くて……うははっ！"
"2000205-9-サヤ" = "ぷっくく……心配しないで、先生。その霊薬の効果は長くないから。#nたぶん、一か月もしたら綺麗に抜け落ちるはずなのだ。"
"2000205-10-サヤ" = "さて、じゃあお店に入ってみようか。"
"2000205-11" = "ラーメン屋"
"2000205-12-店主" = "いらっしゃいませ、ご注文は何になさいますか？"
"2000205-13-サヤ" = "いつもの、#n「麺固め、スープ濃いめ、野菜ダブル、ニンニクと油多め」を二丁！"
"2000205-14-店主" = "はい、ご注文承りました。#n「麺固め、スープ濃いめ、野菜ダブル、ニンニクと油多め」二丁！"
"2000205-15" = "（ざわざわ）"
"2000205-16-ヘルメット団員" = "た、隊長、今の聞きましたか？あのチビ、「例のコール」で頼みましたよ。"
"2000205-17-ヘルメット団幹部" = "聞き間違いじゃないよな…？まさかここで「麺固め、スープ濃いめ、野菜ダブル、ニンニクと油多め」を頼む女子高生がいるなんて……。"
"2000205-18-サヤ" = "ふふ、今から楽しみだな。"
"2000205-19" = "[s] \"麺固め、スープ……なんて？\""
"2000205-20-サヤ" = "先生は記憶力が悪いんだな。#n「麺固め、スープ濃いめ、野菜ダブル、ニンニクと油多め」。#nぼく様の特製注文だから、きっと美味しいはずなのだ～。"
"2000205-21-サヤ" = "食べきれる量なのかって？#nもちろん！ぼく様は何でもできるんだから！"
"2000205-22-サヤ" = "あの年頃の女子学生なら、油を追加するだけでもカロリーが気になるはず……。#nあのカロリー爆弾を食べてあんなに細い体を維持できるはずがない！"
"2000205-23-ヘルメット団員" = "その通りです、「いつもの」なんて言ってましたが、きっと半分も食べられないに違いありません。"
"2000205-24-ヘルメット団員" = "お待たせしました、#n「麺固め、スープ濃いめ、野菜ダブル、ニンニクと油多め」、二丁です。"
"2000205-25" = "やっと来たのだ！いただきま～す！"
"2000205-26-サヤ" = "ごちそうさまでした！"
"2000205-27-ヘルメット団員" = "見ましたか隊長！#nあのチビ一瞬で……スープまで飲み干しました。"
"2000205-28-ヘルメット団幹部" = "あんな小さい体なのに、「麺固め、スープ濃いめ、野菜ダブル、ニンニクと油多め」を一瞬で平らげるなんて！恐ろしい……。"
"2000205-29-ヘルメット団幹部" = "なあ、もしかしなくても今「麺固め、スープ濃いめ、野菜ダブル、ニンニクと油多め」をスープごと完食したよな？"
"2000205-30-サヤ" = "そうだけど？何か問題が？"
"2000205-31-ヘルメット団幹部" = "あのスープに入ってるカロリーが怖くないのか！？#n一杯食べるだけで、一日の摂取カロリーを優に超えるはずなのに……！"
"2000205-32-サヤ" = "ふっふっふっ、心配はいらないのだ！ぼく様が開発したこの特製ダイエット薬さえあればね！"
"2000205-33-ヘルメット団幹部" = "特製ダイエット薬？"
"2000205-34-サヤ" = "そう、これさえ飲めばいくらカロリーの高い食べ物を食べても、ちっとも太らないのだ！"
"2000205-35-ヘルメット団幹部" = "おお……そ、その薬、私たちに売ってくれないか？金はいくらでも払う！"
"2000205-36-サヤ" = "お金は要らない。その代わり、薬を飲んでどれぐらい効果があったか後で教えてほしいのだ！"
"2000205-37-ヘルメット団幹部" = "それはありがたい、恩に着る！"
"2000205-38-ヘルメット団員" = "この薬さえあれば豚の背油も、マカロンも、好きなだけ食べられる！"
"2000205-39-ヘルメット団幹部" = "本当に楽しみだな……。"
"2000205-40-サヤ" = "ふっふっふっ、そうだね。本当に、楽しみなのだ。"
"2000205-41" = "サヤの研究室"
"2000205-42-ヘルメット団員" = "はあ、はあ……よ、ようやく見つけたぞ。こ、この詐欺師め……。"
"2000205-43-ヘルメット団幹部" = "よ、よくも私たちにでたらめな薬をくれたな……！"
"2000205-44-サヤ" = "あれ？ダイエットの効果がイマイチだったのだ？もっと強い薬を渡した方がよかったかな？"
"2000205-45-ヘルメット団員" = "違う！その逆だ！"
"2000205-46-ヘルメット団幹部" = "何を食べてもすぐに消化されてしまうせいで……#nいくら食べてもお腹がいっぱいにならない……！"
"2000205-47-ヘルメット団幹部" = "このままでは飢え死にしかねない……。"
"2000205-48-サヤ" = "でもダイエットの効果は確実だろう？#n結果太らないなら成功なのだ。はっはっは！"
"2000205-49-ヘルメット団員" = "このっ、ただじゃすまないぞ……！"
"2000205-50-ヘルメット団員" = "ダメだ……力が抜けてきて……ただ立っていることさえ、もう……。"
"2000205-51-サヤ" = "うーん……次は、水だけ飲んでも太る薬でも作って売ってみようかな？"
